bitwarden/clients

libs/vault/src/cipher-form/components/attachments/delete-attachment/delete-attachment.component.html
https://bitwarden.atlassian.net/browse/PM-12553?atlOrigin=eyJpIjoiYjM2Y2QxYjc3MmIzNDhjY2I2MjhjYWQ5YzkwYWIzZWQiLCJwIjoiaiJ9
Replaces the `tw-border-none` class from the delete button which was preventing the button hover state from appearing. Added `tw-border-transparent` which works on both the `ps/extension-refresh` and `main` branches (allows hover state without showing a border when not hovered). …
=> [PM-12553][Defect] Delete Attachment button needs hover state.

apps/desktop/src/main/native-messaging.main.ts
https://bitwarden.atlassian.net/browse/PM-12617
Add support for system authentication support in Chromium on linux. …
=> [PM-12617] native-messaging: Add chromium support

libs/tools/send/send-ui/src/send-form/components/options/send-options.component.html
https://bitwarden.atlassian.net/browse/PM-12721
This PR disables the copy password button when the password input is blank.
https://github.com/user-attachments/assets/0de54226-da5b-45df-813f-854faa455f10
- …
=> [PM-12721]- disable copy button if no password is present

apps/web/src/app/billing/organizations/billing-sync-api-key.component.html, apps/web/src/app/billing/organizations/billing-sync-key.component.html, apps/web/src/app/billing/organizations/organization-subscription-cloud.component.html, apps/web/src/app/billing/organizations/organization-subscription-selfhost.component.html, apps/web/src/locales/en/messages.json
=> [PM-11503] Organization Automatic Sync verbiage is misleading

apps/browser/src/vault/popup/settings/trash-list-items-container/trash-list-items-container.component.html
[PM-12718](https://bitwarden.atlassian.net/browse/PM-12718)
I was so focused on the virtual scrolling fixes in https://github.com/bitwarden/clients/pull/11338, that I forgot about the trash page completely. 
- Updating the trash page to use a `button` element rather than anchor element. An anchor without an `href` attribute is not keyboard accessible. 
|Trash Page|
|-|
|<video src="https://github.com/user-attachments/assets/aa62abfc-e4e1-475e-b733-5f883c27be62"/>|
- 🎨 (`:art:`) for suggestions / …
=> [PM-12718] Keyboard accessible trash links

apps/browser/src/platform/popup/layout/popup-tab-navigation.component.ts
https://bitwarden.atlassian.net/browse/PM-13077
This PR fixes the logic to display the sends tab if one or more sends are present. …
=> [PM-13077] - fix logic for hiding sends tab

libs/tools/send/send-ui/src/send-form/components/send-details/send-text-details.component.html
https://bitwarden.atlassian.net/browse/PM-12560
This PR reduces the number of rows in the textarea of the text sends from `6` to `3` as per the designs. …
=> [PM-12560] - fix rows for textarea in text send

apps/web/src/connectors/duo-redirect.ts
https://bitwarden.atlassian.net/browse/PM-13103
To fix users with frameless Duo 2FA from not being able to login. The existing logic failed because the construction of the previous check would reject all URLs.
Info: I temporarily mocked one of the known failing redirects to prove that the `Invalid redirect URL` error would not be thrown after the logic change. 
https://github.com/user-attachments/assets/7a56b55f-61fe-44e8-81e7-62d64469f887
- Updated any …
=> Auth/PM-13103 - Fix Users with Frameless Duo 2FA not being able to login

apps/web/src/app/core/core.module.ts, apps/web/src/app/platform/web-environment.service.ts
https://bitwarden.atlassian.net/browse/PM-13114
To make the web env selector properly change regions
Note: the `.com` env already had the `email-verification` flag turned off so that's why access was denied. 
https://github.com/user-attachments/assets/2f25d1eb-12a7-4c09-98e0-a986487357ee …
=> Auth/PM-13114 - Web - Registration Env Selector now navigates to proper region

libs/tools/generator/core/src/rx.spec.ts, libs/tools/generator/core/src/rx.ts
N/A
Generalize common operations found in the credential generator service.
These were split from `tools/PM-8282/credential-generator` (only on my local) so they can be tested and merged independently of the code that consumes them.
- ⛏ (`:pick:`) for minor or nitpick …
=> Reactive extension helper methods

apps/web/src/locales/en/messages.json
[PM-12727](https://bitwarden.atlassian.net/browse/PM-12727)
[PM-12737](https://bitwarden.atlassian.net/browse/PM-12737)
Some copy was missed when porting over the add/edit component into the web vault
- Heading and size limit for attachments
- Warning message for deleting an attachment
|Adding attachment|Deleting attachment|
|-|-|
|<img width="480" alt="Screenshot 2024-10-02 at 2 18 58 PM" src="https://github.com/user-attachments/assets/b19e7874-d110-4ac2-8127-52d625a19fee">|<img width="339" alt="Screenshot 2024-10-02 at 2 19 05 PM" src="https://github.com/user-attachments/assets/4fc023d9-1bee-4bbc-b9ab-adb41638e32d">| …
=> [PM-12727/12737] Adding copy for Add/Edit

apps/browser/src/background/main.background.ts
Fix bug where the vault locks even when interacting with it when  timeout is set to Immediately in Chrome.
Only load vault timeout setting service in the background. This should be ok since the vault timeout checks are properly scheduled using MV3 compatible alarms.
Lock works by `VaultTimeoutService` constantly calling `checkVaultTimeout` at regular intervals. One of the conditions that this function checks is if the extension has any views open, it does this by calling `platformUtilsService.isViewOpen()`. This function in turn uses the following call to verify if this is the case:
```
await BrowserApi.sendMessageWithResponse("checkVaultPopupHeartbeat")
``` 
Now, the main issue is that as we transitioned to MV3 we started creating creating the background services in the popup too. This …
=> [PM-12308][Defect] `Immediately` vault timeout causes locking while using the extension

apps/browser/src/autofill/popup/fido2/fido2-cipher-row.component.html
PM-11681
Fix fido2 cipher row component subname not having proper layout/styling
| --- | --- |
| ![Screenshot 2024-10-03 at 1 06 41 PM](https://github.com/user-attachments/assets/c9e911a2-96ba-4d2a-8aa9-226425029549) | ![Screenshot 2024-10-03 at 1 04 28 PM](https://github.com/user-attachments/assets/eacb7184-a0a9-4fc6-af02-d8dcf2e70325) | 
- 🌱 …
=> [PM-11681] Fix fido2 cipher row component subname not having proper layout/styling

apps/web/src/app/vault/components/vault-item-dialog/vault-item-dialog.component.ts, apps/web/src/app/vault/individual-vault/vault.component.ts
[PM-12738](https://bitwarden.atlassian.net/browse/PM-12738)
- Adds a premium check when trying to access attachments in the `VaultItemDialogComponent`
| Premium Dialog from Edit dialog |
|-|
|<video src="https://github.com/user-attachments/assets/5d3f5935-d738-43af-b10e-18276a4f7abb"/>|
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications …
=> [PM-12738] Show Premium dialog when accessing attachments

apps/web/src/app/vault/individual-vault/vault.component.ts
[PM-12981](https://bitwarden.atlassian.net/browse/PM-12981)
When a cipher type isn't passed to `addCipher` use the filtered cipher type when creating a cipher.
|Adding a cipher - all types|
|-|
|<video src="https://github.com/user-attachments/assets/b523246b-e1b3-4615-9b41-2248c8256d95" />|
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or …
=> [PM-12981] Web Vault - Creating a cipher type

apps/desktop/src/app/app.component.ts, apps/desktop/src/app/tools/generator/credential-generator.component.html, apps/desktop/src/app/tools/generator/credential-generator.component.ts, apps/desktop/src/locales/en/messages.json, apps/desktop/src/vault/app/vault/vault.component.ts
https://bitwarden.atlassian.net/browse/PM-13172
Create a desktop-specific hosting component for the new full credential-generator. Temporarily, this is going to use the new password-generator component, but will be replaced once https://github.com/bitwarden/clients/pull/11398 has merged.
The swap is guarded by a feature flag, so this can be merged without affecting current production. …
=> [PM-13172] Create desktop-specifc full credential-generator component

libs/vault/src/cipher-form/components/autofill-options/uri-option.component.spec.ts, libs/vault/src/cipher-form/components/autofill-options/uri-option.component.ts
[PM-13117](https://bitwarden.atlassian.net/browse/PM-13117)
Fix property name of `matchDetection` for updating the form value.
|Before|After|
|-|-|
|<video src="https://github.com/user-attachments/assets/42b333bb-eaed-486a-b059-e7b162dc4d2e"/>|<video src="https://github.com/user-attachments/assets/b3dafaad-f1b2-4ed2-b9ff-5f3cb94fb47e" />|
- 🌱 (`:seedling:`) or ♻️ …
=> [PM-13117] Match Detection updating on individual vault

apps/web/src/app/vault/org-vault/vault.component.ts, libs/common/src/vault/abstractions/cipher.service.ts, libs/common/src/vault/services/cipher.service.ts, libs/vault/src/components/assign-collections.component.ts
[PM-13177](https://bitwarden.atlassian.net/browse/PM-13177)
Add logic to the Assign To Collections dialog to handle Unassigned ciphers and ciphers that an admin does not "normally" have access to when assigning ciphers in the Admin Console.
Previously, the AC would attempt to use the normal `/collections_v2` endpoint which did not properly support the above scenario. We already have an `collections/admin` endpoint that was in use by the old Collections dialog, so this is a drop in replacement.
https://github.com/user-attachments/assets/61b99e13-34e1-452c-bd89-f4c6b253a1b5
- …
=> [PM-13177] Fix Unassigned cipher collection assignment in AC

apps/desktop/src/main/native-messaging.main.ts
When running the desktop app in dev mode, we force the selection of IPC proxy binary to be the `target/debug` artifacts. This is fine when using `npm run electron`, but will fail when using the production builds and setting the ELECTRON_IS_DEV=1 environment variable.
By changing the behavior to check if the debug artifact exists first and falling back to the prod artifact, we allow this to work regardless of how the `isDev` flag got activated.
- Updated …
=> Fix IPC proxy selection in prod when using ELECTRON_IS_DEV

libs/angular/src/vault/components/add-edit.component.ts
https://github.com/orgs/bitwarden/discussions/10760
When saving a password into an organization, if there's only one collection available to save to, select it by default. This improves UX by decreasing the number of clicks required.
- ❓ …
=> [PM-11497] If an org has only one collection, check it by default

libs/components/src/form-field/form-field.stories.ts, libs/components/src/form-field/prefix.directive.ts, libs/components/src/form-field/suffix.directive.ts, libs/components/src/form/forms.mdx
[PM-11131](https://bitwarden.atlassian.net/browse/PM-11131)
Originally, when we updated the prefix and suffix directives, we added in an automatic `aria-describedby` assignment that referenced the form field label. The idea was that this would help provide context for what the button was associated with. However, when implementing it in the browser extension, we ran into issues where a button with an `ngIf` on it would not get the `aria-describedby` applied properly due to either race conditions or lifecycle event ordering within Angular. The simplest solution is to remove the `aria-describedby` from the prefix and suffix directives and move the label/context responsibility to the implementation, which already is using the `appA11yTitle` directive to apply a label.
This PR also updates …
=> [PM-11131] Prevent duplicated sr labels on form field icon buttons

libs/importer/src/importers/lastpass/access/services/parser.ts
https://bitwarden.atlassian.net/browse/PM-12102
Closes #11051
LastPass encrypts URLs of items in their vault. When importing, they need to be decrypted to appear properly.
I used [this code](https://github.com/detunized/password-manager-access/commit/213e966bb651e9323f5508c79568809da7a6ab83#diff-bef5fc4c400af83e7b83a90460331c45ad3be3db95756ac60597f4ba430a909fR52) as reference for my implementation.
Before:
After: …
=> PM-12102 | Fix LastPass importer not properly de-encrypting URLs

apps/browser/src/platform/services/sdk/browser-sdk-client-factory.ts, apps/browser/src/safari/desktop.xcodeproj/project.pbxproj, apps/browser/webpack.config.js
https://bitwarden.atlassian.net/browse/PM-11290
We ran into some inconsistencies between how manifest v2 and v3 are handled in browsers. To resolve this we have a different flow for manifest v2 which dynamically imports, while v3 uses the sync importScripts. …
=> [PM-11290] Fix safari not starting with sdk

apps/web/src/app/vault/components/vault-items/vault-items.component.html, apps/web/src/app/vault/components/vault-items/vault-items.component.ts
Reverts bitwarden/clients#11370 as it was causing some unexpected behavior in the AC that needs additional QA before release. This will need to be cherry-picked into `rc`.
=> Revert "[PM-11201] Add the ability to sort by Name, Group, and Permission within the collection and item tables"

libs/tools/send/send-ui/src/send-form/components/options/send-options.component.html
https://bitwarden.atlassian.net/browse/PM-13194
This PR disables both the copy and generate buttons when sends are disabled. …
=> [PM-13194] - disable copy and generate buttons when sends are disabled

.github/workflows/build-browser.yml, apps/browser/gulpfile.js, apps/browser/package.json
https://bitwarden.atlassian.net/browse/PM-13271
Part of the browser build script refactor effort.
Remove the gulp coverage report since we now use jest, and coverage is handled through the root coverage report which is done in a different script.
Supersedes https://github.com/bitwarden/clients/pull/4781.
- 📝 …
=> [PM-13271] Remove unused ci:coverage from gulpfile

libs/vault/src/cipher-view/login-credentials/login-credentials-view.component.html
[PM-12355](https://bitwarden.atlassian.net/browse/PM-12355)
Move the password count to display before the password toggle. The password count used to force the password toggle out from underneath the users mouse.
Admin Console, Password Manager, Extension
<video src="https://github.com/user-attachments/assets/b73cba45-b52b-4c40-8d1f-b059b037aca2" />
- 🌱 …
=> [PM-12355] Password Toggle Order

libs/vault/src/cipher-form/components/autofill-options/autofill-options.component.spec.ts, libs/vault/src/cipher-form/components/autofill-options/autofill-options.component.ts, libs/vault/src/cipher-form/components/autofill-options/uri-option.component.spec.ts, libs/vault/src/cipher-form/components/autofill-options/uri-option.component.ts
[PM-13016](https://bitwarden.atlassian.net/browse/PM-13016)
The browser currently shows the users preferred URI Match Detection strategy in parentheses when adding or editing a Login cipher. This removes that for the web implementation.  
|Web|Browser (no change)|
|-|-|
|<img width="674" alt="Screenshot 2024-10-03 at 10 20 43 AM" src="https://github.com/user-attachments/assets/7ad9a3cc-bfd5-4a35-9903-7ad5cdb4e127">|<img width="382" alt="Screenshot 2024-10-03 at 10 20 23 AM" src="https://github.com/user-attachments/assets/c97b651d-9795-4640-8907-c5172933133f">| …
=> [PM-13016] Remove user match strategy on the web

libs/vault/src/cipher-form/cipher-form.stories.ts
N/A - Introduced in https://github.com/bitwarden/clients/pull/11385
`PlatformUtilsService` was added to an underlying component in the `CipherForm but I missed adding a provider to the story, causing storybook to throw errors.
=> [Storybook] Add platform service to cipher form story

apps/browser/src/autofill/background/overlay-notifications.background.spec.ts, apps/browser/src/autofill/background/overlay-notifications.background.ts
https://bitwarden.atlassian.net/browse/PM-13284
The rework of the notification bar depends fairly heavily on proper requests being made when a website submits a form. That isn't always a consistent methodology for identifying submissions for a user, in particular websites that use an SPA structure and handle authentication without calling a backend (https://www.saucedemo.com/).
The changes in this PR introduce a fallback approach for capturing form submissions from these kinds of use cases. 
- …
=> [PM-13284] Reworked notification bar does not display for certain websites

apps/browser/src/popup/scss/tailwind.css
[CL-469](https://bitwarden.atlassian.net/browse/CL-469)
Implements scrollbar styles specific to browsers. See the comments in [CL-469](https://bitwarden.atlassian.net/browse/CL-469) for the options/discussion.
- Chrome and FireFox support the scrollbar-color CSS attribute that respects the macOS setting for only showing a scrollbar when scrolling
- Safari needs webkit specific styling which does not respect the macOS scrollbar settings
|Chrome|FireFox|Safari|
|-|-|-|
|<video src="https://github.com/user-attachments/assets/dd71e033-fb83-4aaf-a0e1-460a15532472"/>|<video src="https://github.com/user-attachments/assets/f7edaa4f-cbe0-4ed9-b97a-7557655be593"/>|<video src="https://github.com/user-attachments/assets/c3e9e0ce-c6a5-4051-ac18-9ac8e2be7e5b"/>| …
=> [CL-469] ScrollBar Styles

apps/browser/src/autofill/background/overlay-notifications.background.spec.ts, apps/browser/src/autofill/background/overlay-notifications.background.ts
https://bitwarden.atlassian.net/browse/PM-13284
Another issue was found with how we handle the new notification bar logic. We need to ensure that the logic for this feature is updated to reflect the feature flag set for the current user's server. This avoids a situation where the background script could potentially be aligned with the feature flag in one state, but the content scripts being injected are aligned with a different state. 
https://github.com/user-attachments/assets/cb0cb63a-74d4-4094-98ce-0715dd06b52b
- CI …
=> [PM-13284] Implement method to ensure that we can handle logic when switching the notification improvements feature flag

apps/browser/src/autofill/background/overlay.background.ts, apps/browser/src/autofill/fido2/background/abstractions/fido2.background.ts, apps/browser/src/autofill/fido2/background/fido2.background.spec.ts, apps/browser/src/autofill/fido2/background/fido2.background.ts, apps/browser/src/autofill/fido2/content/fido2-page-script-append.mv2.ts, apps/browser/src/autofill/fido2/content/fido2-page-script-delay-append.mv2.ts, apps/browser/src/autofill/fido2/content/fido2-page-script.ts, apps/browser/src/background/main.background.ts, apps/browser/src/background/runtime.background.ts
https://bitwarden.atlassian.net/browse/PM-12548
The content scripts used to override the Webauthn  API are being injected when a user is in a logged out state. This problem introduces an issue where we break the default Webauthn API since an un-authed user cannot respond to the overriden Webauthn API call in any manner.
The changes in this PR address that problem by reworking how we handle injecting the fido2 content scripts on load of the extension. Effectively, we should only be injecting those scripts if the user is logged in or shortly after the user logs into the browser extension.
Resolves https://github.com/bitwarden/clients/issues/11199#issuecomment-2395593752
- Written new unit and / or …
=> [PM-12548] Fido2 scripts should not load when user is logged out

apps/web/src/app/vault/org-vault/vault.component.ts
[PM-13279](https://bitwarden.atlassian.net/browse/PM-13279)
The types for the `editCipher` method were a little misleading causing a runtime error. The `cipherView` parameter can be `null` when adding a cipher.
- Updated the corresponding types and all downstream logic to account for a `null` cipher value.
|Admin Console - No Extension Refresh Flag| Admin Console with Extension Refresh Flag|
|-|-|
|<video src="https://github.com/user-attachments/assets/bdb923d4-ccdb-4b48-92e9-0b111fbe904d"/>|<video src="https://github.com/user-attachments/assets/6cb6816e-7b5c-4835-941c-5faad6a668ef"/>| …
=> [PM-13279] Adding a new cipher in the admin console

apps/browser/src/_locales/en/messages.json, apps/browser/src/tools/popup/send-v2/send-created/send-created.component.html, apps/browser/src/tools/popup/send-v2/send-created/send-created.component.spec.ts, apps/browser/src/tools/popup/send-v2/send-created/send-created.component.ts
https://bitwarden.atlassian.net/browse/PM-11926
This PR fixes the send created expiration length text to account for singular days or hours left.
|Before|After|
---|---
|![Screenshot 2024-10-08 at 1 12 20 PM](https://github.com/user-attachments/assets/e94d948f-988f-4137-a759-d0c64d8753e2)|![Screenshot 2024-10-08 at 1 12 02 PM](https://github.com/user-attachments/assets/967d89ab-b7aa-41d7-bd3b-e77c216d6b0a)| …
=> [PM-11926] - fix send created page text

libs/tools/send/send-ui/src/send-form/components/options/send-options.component.html
https://bitwarden.atlassian.net/browse/PM-12724
This PR fixes an issue where the label was changing when the password field was filled. Perhaps this was due to the fact that the design shows both "New Password" and "Password" in the various comps. …
=> [PM-12724] - consistent send password field label

apps/browser/src/platform/browser/browser-api.register-content-scripts-polyfill.ts
https://bitwarden.atlassian.net/browse/PM-9876
Some changes made recently to facilitate upgrading to Typescript 5.3 have created an issue within Safari where the expected passkeys workflow is not triggering as expected. Modifications were made to the `browser-api.register-content-script-polyfill.ts` typings to ensure that Typescript 5.3 can compile as expected.
Those changes are reverted instead opting to use a casted `as` reference on the two areas that present problems in Typescript 5.3. [This fix can be seen on this JS playground link.](https://www.typescriptlang.org/play/?ts=5.3.3#code/CYUwxgNghgTiAEA3W8wAsYHsC2IBc8UAdgJ4DcAUBfPAGYCuRYALgJaZHwByIAzsyGAAFLAA8SAHgAq8EKIFFgveJgBGAK3DMAfAApmsAOYhmBKQEoz8AN7Ua8OM3oxOREAHd4IzOP1GTADQ2dvbwxsx+MOFBAA5YMebBoaGstPC6AIQGUSYA2nGYMYTKANYgJJhpUgC6ib …
=> [PM-9876] Safari Passkeys Prompt is Not Triggered

libs/components/src/tw-theme.css
[PM-12776](https://bitwarden.atlassian.net/browse/PM-12776)
The default `z-index` of draggable items from the CDK is 1000. There is a z-index of 2000 set for the dialog component causing the draggable preview to show up behind the dialog.
Add the `cdk-drag-preview` class to the same styles as the dialog so they have the same z-index and thus the draggable item will display on top of the dialog. 
| Web Vault | Browser (no change here, just validation it still works)|
|-|-|
|<video src="https://github.com/user-attachments/assets/3facef3c-aa83-46a5-97cf-d05a3c987caf" />|<video src="https://github.com/user-attachments/assets/526ae711-73ce-47b8-b10d-9e9a2123bae0" />|
- ❓ …
=> [PM-12776] Draggable Items within a dialog

libs/components/src/card/card.component.ts, libs/components/src/item/item.component.html, libs/components/src/tw-theme.css, libs/components/tailwind.config.base.js
[CL-481](https://bitwarden.atlassian.net/browse/CL-481)
This PR:
- Updates the color of `primary-100` in dark mode
- Displays the `bit-item` border on hover
- Switches `bit-card` and `bit-item` to use a new `shadow` color for their bottom borders. The `shadow` color ensures that the item and card look "popped out" instead of "sunken in". The only exclusion is when `bit-card` is used within `bit-layout`, because its border transforms from a bottom shadow to a divider and thus should remain light-colored in dark mode.
- CI …
=> [CL-481] Style updates for bit-item, bit-card, and primary-100

apps/web/src/app/tools/reports/pages/weak-passwords-report.component.html, apps/web/src/app/tools/reports/pages/weak-passwords-report.component.ts
https://bitwarden.atlassian.net/browse/PM-13350
Fix the sorting by weakness on the weak-password report. The `bitSortable` does not support sorting by object/object-key so I had to add the scoring to the result row as an independent property.
Change will need to be 🍒 ⛏️ 'ed to `rc` …
=> [PM-13350] Fix sorting on weak-password report

apps/browser/src/popup/services/services.module.ts
https://bitwarden.atlassian.net/browse/PM-13312
Usage of the `getBgService` reference within the Angular dependency structure for the browser extension popup is causing an issue with the `TaskSchedulerService` where a registered task handler method in the background script will be overwritten with a popup-based method. This causes a DeadObject issue within Firefox and other mv2 extension implementations. 
To resolve this, we need to remove usage of `getBgService` when instantiating the `TaskSchedulerService` for the popup. …
=> [PM-13312] Task scheduler loses event callback reference when popout opens

apps/browser/src/auth/popup/extension-anon-layout-wrapper/extension-anon-layout-wrapper.component.ts, apps/browser/src/auth/popup/extension-anon-layout-wrapper/extension-anon-layout-wrapper.stories.ts, apps/browser/src/popup/app-routing.module.ts, apps/desktop/desktop_native/napi/index.d.ts, apps/desktop/src/app/app-routing.module.ts, apps/web/src/app/auth/trial-initiation/complete-trial-initiation/resolver/free-trial-text.resolver.spec.ts, apps/web/src/app/auth/trial-initiation/complete-trial-initiation/resolver/free-trial-text.resolver.ts, apps/web/src/app/oss-routing.module.ts, apps/web/src/app/tools/send/access.component.ts, libs/auth/src/angular/anon-layout/anon-layout-wrapper.component.ts, libs/auth/src/angular/anon-layout/anon-layout-wrapper.stories.ts, libs/auth/src/angular/lock/lock.component.ts
https://bitwarden.atlassian.net/browse/PM-13318
To refactor the `AnonLayoutWrapperData` interface to support all possible string scenarios (untranslated string, translated string, and translated string with placeholders). 
- ❓ …
=> Auth/PM-13318 - AnonLayoutWrapperData Refactor to add full Translation support

libs/tools/generator/components/src/password-settings.component.html
https://bitwarden.atlassian.net/browse/PM-13390
.This PR fixes the width of the min number and special character inputs in the password generator.
|Before|After|
---|---
|![Screenshot 2024-10-10 at 12 56 05 PM](https://github.com/user-attachments/assets/70fc462f-70a4-406c-8611-9e3bcaae85be)|![Screenshot 2024-10-11 at 11 47 40 AM](https://github.com/user-attachments/assets/1475887e-8907-4dc6-a630-7f1d23dd66ce)| …
=> [PM-13390] - fix label width in password generator

libs/common/src/platform/services/sdk/default-sdk.service.spec.ts, libs/common/src/platform/services/sdk/default-sdk.service.ts
When we implement the SDK with instances for each user account, we need to provide the ability to clean up instances of the SDK when a user logs out so that in-memory state is cleared. …
=> [PM-13260] implement cleanup logic for sdk on account logout

libs/tools/send/send-ui/src/services/send-list-filters.service.spec.ts, libs/tools/send/send-ui/src/services/send-list-filters.service.ts
https://bitwarden.atlassian.net/browse/PM-13669
Show disabled Sends within Send list view
With #10192 we introduced the new send-list-filters, and filtered out any disabled sends. These still need to be shown as the the other clients still support enabling/disabling Sends
This will be removed once all clients use the same shared components.
- 👍 …
=> [PM-13669] Show disabled Sends within Send list view

libs/tools/generator/components/src/generator.module.ts, libs/tools/generator/components/src/password-settings.component.html
[PM-13397](https://bitwarden.atlassian.net/browse/PM-13397)
- Update the "Options" heading to be `h2` to follow the heading hierarchy of the page. 
- Import the `TypographyModule` so the proper styles from the component library are applied
|Before|After|
|-|-|
|![Screenshot 2024-10-15 at 9 43 12 AM](https://github.com/user-attachments/assets/879895cb-a8ae-4f7c-84b6-0be7fdc925af)|![Screenshot 2024-10-15 at 9 42 30 AM](https://github.com/user-attachments/assets/bdae2645-5e5b-4d38-8cd5-92f1598744e5)| …
=> [PM-13397] Heading level + Styling for generator components

libs/tools/generator/components/src/credential-generator.component.html, libs/tools/generator/components/src/password-generator.component.html, libs/tools/generator/components/src/username-generator.component.html
[PM-13399](https://bitwarden.atlassian.net/browse/PM-13399)
Fix wrapping of the copy and generate buttons by making their container a flex container. Flex containers do not wrap their children by default. 
|Before|After|
|-|-|
|<video src="https://github.com/user-attachments/assets/3af860da-404f-47ed-a143-1935b5a2beb9" />|<video src="https://github.com/user-attachments/assets/7bd41a1c-b82a-4db3-b505-cf0015f84704" />|
- ❌ (`:x:`) or ⚠️ (`:warning:`) for …
=> [PM-13399] Generate & Copy wrapping

apps/browser/src/background/main.background.ts, apps/browser/src/popup/app.component.ts, apps/cli/src/service-container/service-container.ts, apps/desktop/src/app/app.component.ts, apps/web/src/app/app.component.ts
https://bitwarden.atlassian.net/browse/PM-13685
We ran into a ```Unhandled error in angular Error: Uncaught (in promise): TypeError: Cannot read properties of undefined (reading 'write') TypeError: Cannot read properties of undefined (reading 'write')``` due to log service losing `this`. Fixed by using the arrow function. 🤦  …
=> Fix log service not binding this

libs/tools/send/send-ui/src/send-form/components/options/send-options.component.html
https://bitwarden.atlassian.net/browse/PM-13676
This PR fixes the logic that was preventing users from unchecking the "hide email" checkbox when the disable hide email policy was enabled afterwards.
- 🤔 …
=> [PM-13676] - fix logic for displaying hide email in send options

libs/vault/src/cipher-form/components/autofill-options/uri-option.component.spec.ts, libs/vault/src/cipher-form/components/autofill-options/uri-option.component.ts
[PM-13016](https://bitwarden.atlassian.net/browse/PM-13016)
- The `UriMatchStrategy` for Domain was 0 and hitting the conditional and thus returning early and not showing the `Domain` on the browser.
- Note: No change to the web implementation, the video below just shows that the value is still hidden.
<video src="https://github.com/user-attachments/assets/99bcb787-7dd1-43d0-a8ad-47737b2207b5" />
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant …
=> [PM-13016] Browser default match detection

apps/browser/src/popup/scss/misc.scss, libs/components/src/form-field/form-field.component.html
[CL-477](https://bitwarden.atlassian.net/browse/CL-477)
This PR removes the focus indicators from the readonly input fields, and adds custom selection styling to the readonly input.
With flag off (existing selection styling unchanged):
https://github.com/user-attachments/assets/b4aed71a-bfd9-467c-b791-d7716055d117
With flag on (new selection styling):
https://github.com/user-attachments/assets/1f8c9e4e-0698-4fc5-b4e3-57ec43bbfb71
Storybook:
https://github.com/user-attachments/assets/7669eca6-52e3-43cb-8a9b-78e621e4d1a1
- CI …
=> [CL-477] Remove focus styles for readonly input

bitwarden_license/bit-web/src/app/admin-console/organizations/manage/domain-verification/domain-add-edit-dialog/domain-add-edit-dialog.component.ts, bitwarden_license/bit-web/src/app/admin-console/organizations/manage/domain-verification/domain-verification.component.ts, libs/common/src/admin-console/services/organization-domain/org-domain.service.spec.ts, libs/common/src/admin-console/services/organization-domain/org-domain.service.ts
[PM-11920](https://bitwarden.atlassian.net/browse/PM-11920)
This PR removes the deprecated call to `platformUtilsService.showToast` function in the `org-domain.service` and refactors the `domain-add-edit-dialog` and `domain-verification.component` to use the ToastService to show toasts when copying the DNS text. …
=> [PM-11920] Remove platformUtilService.showToast call

apps/web/src/app/vault/components/vault-items/vault-items.component.ts
[CL-487](https://bitwarden.atlassian.net/browse/CL-487)
This PR fixes the virtual item height of the vault items list, which was incorrectly calculated/set after we updated the base rem to 16px in the extension refresh feature branch. It was causing issues with the scrollbar behavior.
I also checked other areas where the item height is hardcoded for virtual lists, but the others all look correct.
Note the scrollbar behavior.
Before:
https://github.com/user-attachments/assets/f9aae7e0-d0cf-4a61-b312-0320043ce11c
After:
https://github.com/user-attachments/assets/e40fcfd3-5342-426d-a18a-40000335eb82 …
=> [CL-487] Fix vault items virtual scroll height

libs/tools/send/send-ui/src/send-form/components/options/send-options.component.html
https://bitwarden.atlassian.net/browse/PM-13725
This PR fixes a bug where we were calling `hideEmail` on a `null` send in the send options form. …
=> [PM-13725] - account for possible null send when showing hide email input

apps/web/src/app/admin-console/organizations/policies/personal-ownership.component.html, apps/web/src/app/admin-console/organizations/policies/personal-ownership.component.ts
[PM-11613](https://bitwarden.atlassian.net/browse/PM-11613)
This PR refactors the personal-ownership.component to use a reactive form. …
=> [PM-11613] Refactor personal-ownership.component to use reactive form

apps/browser/src/autofill/services/autofill-overlay-content.service.ts
https://bitwarden.atlassian.net/browse/PM-13768
This fixes an issue where turning off the "show identities in the inline menu" feature disables the inline menu for account creation forms.
- 🤔 …
=> [PM-13768] Create account fields are no longer showing the inline menu when identities are turned off

apps/desktop/electron-builder.json
The Publish Desktop workflow [failed](https://github.com/bitwarden/clients/actions/runs/11389845537/job/31690107099#step:9:42) on submitting the Snap artifact to the Snap store. The `default` plug list already includes `network`, so adding it after `default` causes it to be included twice, which `snapcraft` does not like. …
=> Remove 'network' from Snap plugs for Desktop

libs/importer/spec/keepassx-csv-importer.spec.ts, libs/importer/spec/test-data/keepassx-csv/testdata.csv.ts, libs/importer/src/importers/keepassx-csv-importer.ts
Fixes #11522 - Keepass CSV import doesn't include TOTP
This pull request resolves an issue where TOTP fields were not imported from KeePass CSV files into Bitwarden vault entries. The `keepassx-csv-importer` was modified to parse and include TOTP fields during the import process. Unit tests were also added to ensure TOTP values are handled correctly.
- Updated `keepassx-csv-importer` to support TOTP field import.
- Added unit tests for TOTP parsing in `libs/importer/spec/keepassx-csv-importer.spec.ts`.
=> [PM-13708] Fix: Add TOTP import support to KeePassX CSV importer

apps/browser/src/popup/app-routing.module.ts, apps/browser/src/vault/popup/components/vault-v2/vault-password-history-v2/vault-password-history-v2.component.html, apps/browser/src/vault/popup/components/vault-v2/vault-password-history-v2/vault-password-history-v2.component.spec.ts, apps/browser/src/vault/popup/components/vault-v2/vault-password-history-v2/vault-password-history-v2.component.ts, apps/web/src/app/vault/individual-vault/password-history.component.html, apps/web/src/app/vault/individual-vault/password-history.component.ts, apps/web/src/locales/en/messages.json, libs/vault/src/cipher-view/item-history/item-history-v2.component.html, libs/vault/src/components/password-history-view/password-history-view.component.html, libs/vault/src/components/password-history-view/password-history-view.component.spec.ts, libs/vault/src/components/password-history-view/password-history-view.component.ts, libs/vault/src/index.ts
[PM-13251](https://bitwarden.atlassian.net/browse/PM-13251)
- Migrate the Password History UI from the individual vault to `PasswordHistoryViewComponent` within the vault library.
- Refactor the individual vault to consume the new shared component
- Build a V2 popup page that also uses the shared component within the browser extension. Hidden behind the extension refresh feature flag
|Regression of individual vault, then browser extension|
|-|
|<video src="https://github.com/user-attachments/assets/54e8b35d-c591-4404-84a8-8fbffb1f734f"/>| …
=> [PM-13251] Password History

apps/web/src/app/vault/components/web-generator-dialog/web-generator-dialog.component.html, libs/tools/generator/components/src/passphrase-settings.component.html, libs/tools/generator/components/src/passphrase-settings.component.ts, libs/tools/generator/components/src/password-generator.component.html, libs/tools/generator/components/src/password-generator.component.ts, libs/tools/generator/components/src/password-settings.component.html, libs/tools/generator/components/src/password-settings.component.ts, libs/tools/generator/components/src/username-generator.component.html, libs/tools/generator/components/src/username-generator.component.ts, libs/vault/src/cipher-form/components/cipher-generator/cipher-form-generator.component.html, libs/vault/src/cipher-form/components/cipher-generator/cipher-form-generator.component.ts
[PM-13132](https://bitwarden.atlassian.net/browse/PM-13132)
- A little bit of drilling because of the component hierarchy. Adding a `disableMargin` Input to be passed down the component tree to remove the margin from applicable `bit-section` elements in the web dialog implementation. 
|Before|After|
|-|-|
| <video src="https://github.com/user-attachments/assets/c48357fd-b476-4c43-af9c-13aada6f7cc2" />|<video src="https://github.com/user-attachments/assets/2802dcad-4768-44ad-aa70-c5ee9ee5cf91" />|
- …
=> [PM-13132] Generators - Web Dialog Margins

apps/browser/src/autofill/popup/fido2/fido2.component.html, apps/browser/src/autofill/popup/fido2/fido2.component.ts
PM-13687
Note: follow up from [PM-12368](https://github.com/bitwarden/clients/pull/11460)
When a user registers a new passkey via the extension popup and no login ciphers exist in the vault for that page, show a "No matching logins for this site" message with a search bar and button to save passkey as a new login. If the user searches from this view (or another view) and there are no login cipher matches for the search, display a "No items match your search" message with a button to clear search.
- …
=> [PM-13687] Update search state to show contextually relevant no results view messages

apps/browser/src/autofill/popup/settings/autofill-v1.component.html, apps/browser/src/autofill/popup/settings/autofill.component.html
PM-13675
With the new autofill [inline menu sub-options merged in](https://github.com/bitwarden/clients/pull/11260), there are some inconsistencies around the placement and display of the browser autofill override instructions between Firefox and other browsers (the former doesn't have an option/toggle for the override). This PR aims to make the placement and display of those instructions more consistent. 
NOTE: The Submenu options are behind the `inline-menu-positioning-improvements` feature-flag
**Submenu options OFF**
| Chrome No Submenu (Before) | Chrome No Submenu (After) |
| --- | --- |
| ![before-chrome-nosub](https://github.com/user-attachments/assets/c8417f51-42de-4e11-abae-5b3fa5570aa8) | ![after-chrome-nosub](https://github.com/user-attachments/assets/a3ff133c-7b84-4c27-b045-930 …
=> [PM-13675] Adjust browser autofill override instructions conditions and placement in the settings view

apps/browser/src/vault/popup/components/vault-v2/vault-generator-dialog/vault-generator-dialog.component.html, apps/browser/src/vault/popup/components/vault-v2/vault-generator-dialog/vault-generator-dialog.component.ts
[PM-13393](https://bitwarden.atlassian.net/browse/PM-13393)
Remove slideIn animation as it doesn't support the "show animations" setting and adding a close animation is going to require a non-trivial solution. Dialog animations will be handled in https://bitwarden.atlassian.net/browse/PM-13766
- The default dialog animation is now used (very subtle) until https://bitwarden.atlassian.net/browse/PM-13766 is complete
<video src="https://github.com/user-attachments/assets/f532f5c5-1664-4b3b-a0be-c591afe39a0c"/> …
=>  [PM-13393] Remove animation from Generator dialog.

apps/browser/src/tools/popup/send-v2/send-created/send-created.component.html, libs/tools/send/send-ui/src/send-form/components/send-details/send-details.component.html
https://bitwarden.atlassian.net/browse/PM-13813
This PR fixes an issue where screen readers weren't reading the send created success text. Adding an autofocus and tabindex allows for the text to be focused.
As a bonus autofocus was also added to the `name` input in the the send details form to improve the ux …
=> [PM-13813] - fix voiceover on send created screen

apps/browser/src/auth/popup/extension-anon-layout-wrapper/extension-anon-layout-wrapper.component.ts, libs/auth/src/angular/anon-layout/anon-layout-wrapper.component.ts
n/a but blocks https://github.com/bitwarden/clients/pull/10856
To add support to the default and extension AnonLayoutWrapperComponents for removing previously set values by passing null. 
Page subtitle removal demo:
https://github.com/user-attachments/assets/21babf30-aaa7-4bd0-b6d3-3a0f26b52a75
- 📝 (`:memo:`) …
=> Auth/AnonLayoutWrapperComponents - Add reset support for null values

.github/renovate.json, apps/browser/gulpfile.js, package-lock.json, package.json
https://bitwarden.atlassian.net/browse/PM-13277
Part of the browser build script refactor effort. https://bitwarden.atlassian.net/browse/PM-6683
We seem to have some very old filters related to fonts and safari build files. These predates our modern usage of webpack for bundling only used assets.
I've run `diff -qr` on Chrome, Firefox and Safari builds and the only difference is that we now include a `bwi-font.svg` resource. `bwi-font.svg` is referenced in our css files and "should" be included.
- …
=> [PM-13277] Gulp: Remove unnecessary filtering

package.json
Seems to work more reliably than the overrides. The root issue should be fixed when https://github.com/electron/asar/pull/332 is merged. …
=> Delete @types/gulp & @types/minimatch on posinstall

apps/browser/src/tools/popup/send-v2/send-file-popout-dialog/send-file-popout-dialog-container.component.ts
https://bitwarden.atlassian.net/browse/PM-13113
This PR attempts to fix the issue of the extension window closing after selecting a file in the file send. …
=> [PM-13113] - account for potential null config in SendFilePopoutDialogContainerComponent

apps/browser/src/vault/popup/components/vault-v2/vault-list-items-container/vault-list-items-container.component.html
https://bitwarden.atlassian.net/browse/PM-12996
Update UI to have more spacing to the left of the header where it's off. …
=> [PM-12996] Updating UI Spacing for bit section header

apps/desktop/src/scss/left-nav.scss, apps/web/src/scss/vault-filters.scss
update styles so that folders and subfolders are correctly aligned in vault filters on web and desktop
```
```
Fixes #8553 
Small styling fix to align icons in vault filters when subfolders are present. Desktop and web.
Added a margin-right style attribute to the "toggle-button" class (folders with subfolders) to match the layout of 
the "filter-button" class (folders without subfolders).
=> [PM-7565] fix filter icon alignment

libs/common/src/platform/enums/encryption-type.enum.ts, libs/common/src/platform/services/cryptography/encrypt.service.implementation.ts
-
Improve the logging around encryption failures. Again no sensitive data is logged. Just encryption key types (i.e their algorithm). This allows us to better see what's going wrong (i.e instead of seeing "encryption type mismatch", we can see which encryption types are expected for the key / encstring).
- 📝 …
=> Add logging for decryption failures

apps/browser/src/vault/popup/components/vault-v2/item-more-options/item-more-options.component.html, apps/browser/src/vault/popup/components/vault-v2/item-more-options/item-more-options.component.ts, apps/web/src/app/vault/components/vault-items/vault-cipher-row.component.ts, apps/web/src/app/vault/components/vault-items/vault-items.component.ts
[PM-13187](https://bitwarden.atlassian.net/browse/PM-13187)
When a user is not a part of an organization, the "Assign To Collection" option should be hidden in both the web vault and browser.
- Note: The "Assign To Collections" option on the web is _not_ behind the extension refresh feature flag
|Web|Browser|
|-|-|
|<img width="377" alt="browser" src="https://github.com/user-attachments/assets/333abd34-d85a-4e96-a684-12ab4dcd87b6">|<img width="1779" alt="web" src="https://github.com/user-attachments/assets/e5cd0b51-c11d-4de9-a874-556d36ad7e30">| …
=> [PM-13187] Hide "Assign To Collections" when the user has no orgs

apps/desktop/src/app/accounts/settings.component.html, apps/desktop/src/app/accounts/settings.component.ts, apps/desktop/src/locales/en/messages.json, apps/desktop/src/main/window.main.ts, apps/desktop/src/platform/services/desktop-settings.service.ts
https://bitwarden.atlassian.net/browse/PM-11312
https://bitwarden.atlassian.net/browse/PM-13924
This reverts the commit from https://github.com/bitwarden/clients/pull/10707 that introduced a setting to prevent screenshots.  We have had reports of users not able to view the desktop UI:
- https://github.com/bitwarden/clients/issues/11654
- https://www.reddit.com/r/Bitwarden/comments/1e5wzxq/bitwarden_desktop_app_not_opening_on_windows_10/
Users have confirmed with a build from this branch that reverting this feature resolves the issue for them.
We plan to follow up to make this feature disabled by default, as well as provide a way for users to disable it if they are no longer able to access the desktop when they do enable it.
- All formatters and local …
=> Revert [PM-11312] Add "prevent screenshot" setting

apps/browser/src/_locales/en/messages.json, apps/browser/src/vault/popup/components/vault-v2/vault-list-items-container/vault-list-items-container.component.html
[PM-13854](https://bitwarden.atlassian.net/browse/PM-13854)
Update "autofill" label in browser to "fill" to fix horizontal spacing in the browser vault for long translations. …
=> [PM-13854] update autofill label in browser

apps/web/src/app/billing/organizations/organization-subscription-cloud.component.html, apps/web/src/app/billing/organizations/organization-subscription-cloud.component.ts
https://bitwarden.atlassian.net/browse/PM-14007
In determining the experience for a client organization subscription, I was only pivoting off of the `enable-consolidated-billing` feature flag, but that flag is enabled now in all environments, so it doesn't do anything. I needed to check the provider status as well to determine if the provider has been migrated or not.
https://github.com/user-attachments/assets/31cbf095-09e7-464a-b80f-5b04c3670953
- …
=> [PM-14007] Only show CB client org exp when provider is Billable

apps/browser/src/_locales/en/messages.json, apps/browser/src/vault/popup/components/vault-v2/item-more-options/item-more-options.component.html, apps/browser/src/vault/popup/components/vault-v2/item-more-options/item-more-options.component.ts, apps/browser/src/vault/popup/components/vault-v2/vault-list-items-container/vault-list-items-container.component.html, apps/browser/src/vault/popup/components/vault-v2/vault-list-items-container/vault-list-items-container.component.ts, libs/common/src/vault/models/view/cipher.view.ts
[PM-13907](https://bitwarden.atlassian.net/browse/PM-13907)
[PM-13849](https://bitwarden.atlassian.net/browse/PM-13849)
Add external link icon to Login items in the Vault for the Favorites and All Items lists. Also re-adds double click to launch support for Login items.
https://github.com/user-attachments/assets/b946659d-f5fd-4a24-94b7-aa8730bddd87
- …
=> [PM-13907] [PM-13849] Browser Refresh - Improve launch login UX

apps/web/src/app/auth/key-rotation/user-key-rotation.service.spec.ts, apps/web/src/app/auth/key-rotation/user-key-rotation.service.ts, libs/common/src/auth/services/device-trust.service.implementation.ts, libs/common/src/services/notifications.service.ts
No specific ticket here. This is to debug tde key rotation issues.
Add client-side logging needed to debug userkey rotation operations. Specifically, to userkey rotation service, notification service (for logout notifications) and device trust service.
_No sensitive data is logged._
These logs can then be provided by users or QA during screen recordings to better see what's going on. …
=> Add logging for userkey / device trust rotation

apps/browser/src/vault/popup/services/vault-popup-items.service.spec.ts, apps/browser/src/vault/popup/services/vault-popup-items.service.ts
[PM-13896](https://bitwarden.atlassian.net/browse/PM-13896)
Do not sort "All Items" section by name when a search term is applied. Default to sorting by the search score handled by the `searchService` to keep the existing extension search behavior. …
=> [PM-13896] Browser Refresh - Avoid sorting items when a search term is applied

apps/browser/src/_locales/en/messages.json, apps/browser/src/tools/popup/generator/credential-generator-history.component.html, apps/browser/src/tools/popup/generator/credential-generator.component.html, libs/tools/generator/components/src/empty-credential-history.component.html
https://bitwarden.atlassian.net/browse/PM-13658
Update the copy of buttons and titles to represent that the generator history supports all types and not just passwords/passphrases. …
=> [PM-13658] Update copy of password history to generator history

libs/angular/src/auth/functions/unauth-ui-refresh-redirect.spec.ts, libs/angular/src/auth/functions/unauth-ui-refresh-redirect.ts, libs/angular/src/utils/extension-refresh-redirect.ts
https://bitwarden.atlassian.net/browse/PM-13945
To allow a browser extension TDE user with a MP to access the lock screen so they can decrypt their vault. 
Further context:
The Extension Refresh redirects should persist the query params as we use query params to execute guard logic (e.g., `lockGuard`). The loss of the `from: login-initiated` query param after the redirect to the `lockV2` route prevented navigation to the lock screen.
https://github.com/user-attachments/assets/a2664e7d-faf8-40ee-a8d1-ba6562ea9ea7
- CI builds …
=> Auth/PM-13945 - Extension - Fix TDE User with MP can't navigate to Lock Screen

apps/browser/src/_locales/en/messages.json, apps/browser/src/tools/popup/generator/credential-generator-history.component.ts
https://bitwarden.atlassian.net/browse/PM-13996
Add a warning dialog for the user to confirm they, want to delete the generator history.
@danielleflinn I went with "removing entries" instead of "removing credentials" …
=> [PM-13996] Add warning dialog when clearing generator history

apps/desktop/src/app/app.component.ts, apps/desktop/src/locales/en/messages.json
server PR: https://github.com/bitwarden/server/pull/4932
[PM-12600](https://bitwarden.atlassian.net/browse/PM-12600)
This PR adds a check for if a user is managed by an organization before deleting and shows a simple dialog if they are, preventing the deletion. …
=> [PM-12600] prevent verified user from deleting their account

bitwarden_license/bit-web/src/app/admin-console/organizations/manage/scim.component.ts
[PM-13729](https://bitwarden.atlassian.net/browse/PM-13729)
This PR adds calls to the toast service to show success toasts when copying a SCIM api key or URL. …
=> [PM-13729] Show toast when copying SCIM api key and URL

apps/browser/src/autofill/background/abstractions/overlay.background.ts, apps/browser/src/autofill/background/overlay.background.ts, apps/browser/src/autofill/services/autofill-overlay-content.service.spec.ts, apps/browser/src/autofill/services/autofill-overlay-content.service.ts
https://bitwarden.atlassian.net/browse/PM-14045
A regression with how the inline menu repositions itself for iframe content has been identified. When an form within an iframe has an parent frame that overflows the viewport, it’s possible to scroll that parent frame and misalign the inline menu. We need to account for scroll events that happen outside of iframes when triggering an inline menu re-position. 
This can be observed very easily on a page such as https://webtests.dev/forms/login/iframe-login/ if you attempt to scroll from the navigation bar when the screen is presented at a very small height.  …
=> [PM-14045] Scrolling content outside of iframe bounds breaks inline menu position

libs/tools/send/send-ui/src/send-form/components/options/send-options.component.html
https://bitwarden.atlassian.net/browse/PM-14018
This PR fixes the icon placement in the send password input
|Before|After|
---|---
|![Screenshot 2024-10-25 at 3 05 02 PM](https://github.com/user-attachments/assets/3abbbaf3-9f03-426b-ad5a-8ed995f301ea)|![Screenshot 2024-10-25 at 2 56 58 PM](https://github.com/user-attachments/assets/e55ea0ff-5f6f-4a3f-ae04-f8075a3b1dcb)| …
=> [PM-14018]- fix icon placement in password input

libs/common/src/platform/services/sdk/default-sdk.service.ts
When a user doesn't have any organization keys `orgKeys` will be null, which causes the SDK initialization step to be skipped. 
This PR changes it so the initialization is done even when `orgKeys` is null. Note that we still call `initialize_org_crypto` to make sure any keys that could already be there are cleared. …
=> Initialize SDK even when orgKeys is null

apps/web/config/usdev.json
https://bitwarden.atlassian.net/browse/SRE-1060
This populates the web vault client `additionalRegions` configuration with USDEV environment details to fix an issue where the web vault defaults to self hosted region if one isn't explicitly defined. This issue was leading to an incorrect url being generated when enabling SCIM provisioning on an Organization in the USDEV environment.  …
=> SRE-1060 Add usdev to additional regions config

apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.html, apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.ts, apps/web/src/locales/en/messages.json
[PM-13645](https://bitwarden.atlassian.net/browse/PM-13645)
This PR fixes the hint message for the email field when inviting new members to an organization to calculate how many seats remain in an org.
- 🤔 …
=> [PM-13645] Fix invite counter to check remaining number of seats in plan

libs/tools/generator/components/src/subaddress-settings.component.ts
https://bitwarden.atlassian.net/browse/PM-13878
Fix regression: the subaddress email should default to the active account email
=> [PM-13878] default subaddress email to active account email

libs/tools/generator/components/src/credential-generator-history.component.html, libs/tools/generator/components/src/credential-generator-history.component.ts
https://bitwarden.atlassian.net/browse/PM-14182
Add character highlighting to password history
All passwords in the following screenshot were generated in a test environment. …
=> [PM-14182] colorize password history

apps/browser/src/_locales/en/messages.json, apps/desktop/src/locales/en/messages.json, apps/web/src/locales/en/messages.json, libs/tools/generator/components/src/passphrase-settings.component.html, libs/tools/generator/components/src/passphrase-settings.component.ts, libs/tools/generator/components/src/password-settings.component.html, libs/tools/generator/components/src/password-settings.component.ts
https://bitwarden.atlassian.net/browse/PM-12338
Add help text explaining min/max boundaries to password and passphrase settings
=> [PM-12338] add boundary help text to credential settings

apps/web/src/locales/en/messages.json
Found some duplicate entries within en/messages.json, likely caused by a bad merge conflict resolution. …
=> Remove duplicate entries from web messages.json

apps/browser/src/autofill/background/overlay.background.ts
https://bitwarden.atlassian.net/browse/PM-14054
An issue continues to exist with how the inline menu repositions itself against an iframed field after a scroll event is triggered on the page. 
It’s relative easy to misalign the inline menu list if you switch the inline menu setting from “on field focus” to “on button click” and then attempt to scroll an element outside of the form field iframe with the inline menu list open. To resolve this, we need to take into account the open state of the inline menu list after a reposition event occurs. 
- Used internationalization (i18n) …
=> [PM-14054] Fix scroll based re-positioning of the inline menu within iframes after setting is changed to on button click

apps/browser/src/auth/popup/settings/account-security-v1.component.ts
https://bitwarden.atlassian.net/browse/PM-2410
Changes the types for the timeout obj to strings. Officially, the array of substitutions [only supports strings](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/i18n/getMessage#substitutions).  …
=> [PM-2410] convert timeout value substitutions to strings

libs/components/src/link/link.directive.ts
[PM-13820](https://bitwarden.atlassian.net/browse/PM-13820)
This PR adds an explicit class to the link directive to remove underline. Some clients and default browser stylesheets add an underline, so we can't rely on no underline being the default state. 
| <img width="383" alt="Screenshot 2024-10-28 at 5 45 30 PM" src="https://github.com/user-attachments/assets/69907f11-e0c4-4d69-a1d8-83df57432659"> | <img width="383" alt="Screenshot 2024-10-28 at 5 41 35 PM" src="https://github.com/user-attachments/assets/52a8ec62-03bb-42cf-a96f-7f423c0e9852"> | …
=> [CL-13820] Add class to remove link underline

apps/browser/src/autofill/content/bootstrap-autofill-overlay-menu.ts, apps/browser/src/autofill/content/bootstrap-autofill-overlay.ts, apps/browser/src/autofill/services/autofill-overlay-content.service.spec.ts, apps/browser/src/autofill/services/autofill-overlay-content.service.ts
https://bitwarden.atlassian.net/browse/PM-14054
Fixing another edge case encountered when triggering scroll based repositioning. When the inline menu is focused in some manner, it is possible for reposition events to be ignored at the top level frame of a page.  …
=> [PM-14054] Fixing scroll-based repositioning of inline menu when inline menu is focused

libs/tools/generator/components/src/credential-generator-history.component.html, libs/tools/generator/components/src/credential-generator-history.component.ts
https://bitwarden.atlassian.net/browse/PM-14190
https://bitwarden.atlassian.net/browse/PM-13998
Improve credential generator history UX.
* Use `bit-item` for better visual consistency with other credential lists.
* Introduce dynamic copy text for consistency with main generator copy button.
These screenshots do not have browser refresh stylesheets applied.
Generator history: 
Example copy text (toast and tooltip/a11y):
- ❌ (`:x:`) or ⚠️ (`:warning:`) for …
=> [PM-14190] Replace history card with item component

apps/browser/src/autofill/services/autofill.service.ts
#11076 
The totp autofill filled on a site with one field per totp digit every field with the entire code. I changed it if the number of totp fields is equal to the length of the totp, every field is filled with only one digit
- ❓ …
=> [PM-13858] fix TOTP fills every input box/field individually

libs/vault/src/cipher-form/components/card-details-section/card-details-section.component.html, libs/vault/src/cipher-form/components/custom-fields/custom-fields.component.html, libs/vault/src/cipher-form/components/login-details-section/login-details-section.component.html, libs/vault/src/cipher-view/card-details/card-details-view.component.html, libs/vault/src/cipher-view/custom-fields/custom-fields-v2.component.html, libs/vault/src/cipher-view/login-credentials/login-credentials-view.component.html
[PM-13145](https://bitwarden.atlassian.net/browse/PM-13145)
Update hidden field inptus on the cipher view/add/edit screens to use the mono font.
- Login ciphers: Password and TOTP inputs
- Card ciphers: Card number and security code inputs
- All ciphers: custom hidden field inputs
|Password & TOTP| Card Number, Security Code, Custom Field|
|-|-|
|![Screenshot 2024-10-28 at 4 43 25 PM](https://github.com/user-attachments/assets/bd0f5939-7f3e-497c-af0d-33aaa6ce3edc)|![Screenshot 2024-10-28 at 4 43 35 PM](https://github.com/user-attachments/assets/b8fdbae3-79c4-4be3-a2a7-91819251c655)| …
=> [PM-13145] Hidden fields font

apps/web/src/app/billing/shared/payment/payment-v2.component.ts, apps/web/src/app/billing/shared/verify-bank-account/verify-bank-account.component.ts, libs/angular/src/billing/components/manage-tax-information/manage-tax-information.component.ts
https://bitwarden.atlassian.net/browse/PM-13947
While I was unable to reproduce the issue in the ticket I found a couple places where calling `this.onSubmit` could result in an error if `onSubmit` was not provided. This PR adds a guard against this. …
=> [PM-13947] - guard against call to undefined onSubmit

apps/browser/src/autofill/deprecated/overlay/iframe-content/autofill-overlay-iframe.service.deprecated.ts, apps/browser/src/autofill/notification/abstractions/notification-bar.ts, apps/browser/src/autofill/notification/bar.ts, apps/browser/src/autofill/overlay/inline-menu/iframe-content/autofill-inline-menu-iframe.service.ts, apps/browser/src/autofill/overlay/notifications/abstractions/overlay-notifications-content.service.ts, apps/browser/src/autofill/spec/autofill-mocks.ts, libs/angular/src/platform/services/theming/angular-theming.service.ts, libs/angular/src/platform/services/theming/theming.service.abstraction.ts, libs/angular/src/services/injection-tokens.ts, libs/common/src/platform/enums/theme-type.enum.ts
PM-14351
We should use objects and types instead of enums which [have unsafe typing](https://dev.to/ivanzm123/dont-use-enums-in-typescript-they-are-very-dangerous-57bh)
=> [PM-14351] Migrate away from theme enum

apps/web/src/app/auth/settings/webauthn-login-settings/create-credential-dialog/create-credential-dialog.component.html, apps/web/src/app/auth/settings/webauthn-login-settings/webauthn-login-settings.component.html, apps/web/src/app/oss-routing.module.ts
https://bitwarden.atlassian.net/browse/PM-14361
In PM-8111 (https://github.com/bitwarden/clients/pull/10856), the `loginWithPasskey` web translation was changed to be `logInWithPasskey` but the usages were not updated. This updates the usages to point to the new translation key. …
=> Auth/PM-14361 - Fix missed translation key updates for loginWithPasskey changing to logInWithPasskey

apps/web/src/app/admin-console/organizations/members/members.component.ts
https://bitwarden.atlassian.net/browse/PM-13962
This PR fixes a bug where the app would attempt to show the upgrade organization plans dialog to non-owner members. Since non-owners don't have access to subscriptions they should not see this modal and instead see the "contact your organization owner dialog".
- …
=> [PM-13962] - check if member has subscription access before showing subscription modal

apps/web/src/app/vault/components/vault-item-dialog/vault-item-dialog.component.html, libs/vault/src/cipher-view/cipher-view.component.html, libs/vault/src/cipher-view/cipher-view.component.ts, libs/vault/src/cipher-view/item-details/item-details-v2.component.html, libs/vault/src/cipher-view/item-details/item-details-v2.component.spec.ts, libs/vault/src/cipher-view/item-details/item-details-v2.component.ts
[PM-13449](https://bitwarden.atlassian.net/browse/PM-13449)
The ownership field was hidden from the edit view in https://github.com/bitwarden/clients/pull/11588, this hides it from the view dialog, only when viewing in the Admin Console.
No ownership shown in the Admin Console, then showing the same cipher with ownership from the Password Manager.
<video src="https://github.com/user-attachments/assets/9048d8f5-d443-462e-b5b6-45ae4a65cb97" />
- ❌ (`:x:`) …
=> [PM-13449] Hide ownership when viewing in Admin Console

libs/common/src/platform/misc/flags.ts, libs/common/src/services/api.service.ts
https://bitwarden.atlassian.net/browse/PM-13804
We want the ability to control feature flags based on whether the requesting client is a beta build or not.
To provide this context to LaunchDarkly, we must introduce a way for the clients to communicate that they are a beta to the server, where it can be used to build the LaunchDarkly context.
This will be done with an `Is-Prerelease` header on the request.
This PR adds that header to all API requests to our back-end based on whether the client-side `prereleaseBuild` flag is enabled. …
=> [PM-13804] Add new Is-Prerelease header to requests

libs/vault/src/cipher-view/login-credentials/login-credentials-view.component.html
[PM-13145](https://bitwarden.atlassian.net/browse/PM-13145)
Kyra found that the TOTP code should also be monospcae font, which I missed in https://github.com/bitwarden/clients/pull/11764
|Web|Browser
|-|-|
|![Screenshot 2024-11-04 at 8 51 04 AM](https://github.com/user-attachments/assets/41504d39-43ae-4144-aaf1-0a92f8f80526)|![Screenshot 2024-11-04 at 8 52 38 AM](https://github.com/user-attachments/assets/0d356b78-b0cd-42b3-8938-5ec3f403cd04)|
- ❌ …
=> [PM-13145] TOTP Code - monospace font

apps/web/src/app/admin-console/organizations/settings/account.component.ts
https://bitwarden.atlassian.net/browse/PM-14533
> Fix a small oversight with the enabled state of the Organization Name field when the `pm-10863-limit-collection-creation-deletion-split` flag is **on**
- 🤔 …
=> [PM-14533] Update enabled state of Organization Name

apps/browser/src/popup/scss/base.scss
[CL-435](https://bitwarden.atlassian.net/browse/CL-435)
This PR prevents a scrollbar from briefly appearing on the browser extension `html` element when the `bit-select` or `bit-multi-select` components are opened. This was happening on Windows and Linux machines and was causing an undesirable jumping effect.
Before
https://github.com/user-attachments/assets/3595564c-1a20-4af2-b3f7-5e95e8cba93b
After
https://github.com/user-attachments/assets/c2e150fc-3c63-4a91-b310-eb6a246b9337
- Communicated to DevOps …
=> [CL-435] Prevent Windows extension from shifting

apps/browser/src/platform/browser/browser-api.ts
https://bitwarden.atlassian.net/browse/PM-12971
This PR fixes a bug where, in Safari, after "popping out" the extension in a new window/ the original window would persist until the user clicked on the main window. …
=> [PM-12971] - close safari default extension on pop out

libs/angular/src/vault/components/add-edit.component.ts
https://bitwarden.atlassian.net/browse/PM-13829
This PR fixes an issue where owners cannot delete unassigned items from the item modal. This change brings the logic in line with the vault component, where the item **can** be deleted when it is unassigned (i.e the inline delete button on the item).
- 📝 …
=> [PM-13829] Allow deletion for items with no collectionId(s)

libs/components/src/toggle-group/toggle.component.ts
[PM-14043](https://bitwarden.atlassian.net/browse/PM-14043)
This PR updates the font size of the toggle group to match the design spec (should match `body2` typography variant), and reduces the x padding on the label to give more horizontal space to longer words.
| ![Screenshot 2024-11-06 at 11 31 02 AM](https://github.com/user-attachments/assets/005f700b-7904-4562-ac31-7f498cf9c3f9) | ![Screenshot 2024-11-06 at 11 27 43 AM](https://github.com/user-attachments/assets/15703b17-56fb-4cdb-8164-c9d7e998cd14) | …
=> [PM-14043] Update size of toggle group label to fit more content

libs/auth/src/angular/login/login.component.html
https://bitwarden.atlassian.net/browse/PM-14495?atlOrigin=eyJpIjoiZjg1ODEwYWM0ZWJhNGYzMTgyZTAxZjU1YWQ0NDhlMTkiLCJwIjoiaiJ9
Uses `divs` with conditional `tw-invisible tw-h-0` classes to show hide the email entry and MP entry states of the new login component (instead of `ng-container *ngIf`). This allows autofill via the extension  to work while logging in to the web by keeping both email and MP fields in the DOM. Without this, autofill needed to be applied twice (once for the email state, once for the MP entry state).
https://github.com/user-attachments/assets/6c6007f0-c502-4128-b593-3fb58e8fafd7
https://github.com/user-attachments/assets/c19afcd0-7517-40ae-a4b1-a5f94b4ecd3f
- Written new unit and / …
=> [PM-14495] Web - Autofill from the extension no longer works

libs/tools/generator/components/src/catchall-settings.component.ts, libs/tools/generator/components/src/credential-generator.component.html, libs/tools/generator/components/src/password-generator.component.html, libs/tools/generator/components/src/username-generator.component.html
https://bitwarden.atlassian.net/browse/PM-13876
As mentioned on https://github.com/bitwarden/clients/pull/11816, this is a follow-up to removed some smaller nits from my review of https://github.com/bitwarden/clients/pull/11816.
- **Remove unused regex -** https://github.com/bitwarden/clients/commit/21f929a88847dc4edbce48c24a78cf9e3821e8d7 
- https://github.com/bitwarden/clients/pull/11816#discussion_r1829320234
- **Remove viewChild reference from markup -** https://github.com/bitwarden/clients/commit/3dc92e0c35a2f03303382bfa5b80db375d928791
- https://github.com/bitwarden/clients/pull/11816#discussion_r1829336942
- Protected functional …
=> [PM-13876] Generator PR review follow up

apps/browser/src/autofill/popup/settings/autofill.component.ts
PM-13950
Do not do browser extension permission check if the Show autofill suggestions setting is being turned off
https://github.com/user-attachments/assets/5adfb07d-e328-4312-ac61-1f9ad92f68b7
- 🤔 …
=> [PM-13950] Do not do browser extension permission check if the Show autofill suggestions setting is being turned off

.github/workflows/build-browser.yml, .github/workflows/build-cli.yml, .github/workflows/build-desktop.yml, .github/workflows/build-web.yml
Internal change, corresponding to https://github.com/bitwarden/server/pull/4992.
Migrates build artifact generation to the "check run" workflow, enabling an engineer to approve the run and still receive artifacts. …
=> Check run permissions for build artifact generation secrets usage

apps/web/src/app/vault/individual-vault/vault-filter/components/organization-options.component.ts
https://bitwarden.atlassian.net/browse/PM-11409
This PR hides the leave option for the managing organization that a manged user belongs to.
Organization that does **not** manage this user
Organization that **does** manage this user (cannot leave) …
=> [PM-11409] prevent managed user from leaving organization

libs/tools/generator/core/src/policies/constraints.ts, libs/tools/generator/core/src/policies/dynamic-password-policy-constraints.spec.ts, libs/tools/generator/core/src/policies/dynamic-password-policy-constraints.ts
https://bitwarden.atlassian.net/browse/PM-14198
Fix negative number entries not resetting to zero when the cursor moves away. …
=> [PM-14198] zero minimums when the character category is disabled

apps/browser/src/tools/popup/send-v2/add-edit/send-add-edit.component.ts
While looking for a pattern where import path were using `/src/`instead of the proper import,  I discovered this issue within the new SendAddEditComponent …
=> Fix wrong import of SendFormModule

libs/common/src/services/api.service.ts
https://bitwarden.atlassian.net/browse/PM-13804
In [discussion](https://github.com/bitwarden/server/pull/4994#pullrequestreview-2421469231) on the consuming server PR for this change, we determined it would be better to serve this header as an integer (0/1) instead of string (`true`/`false`) for a boolean representation. …
=> Update Is-Prerelease header to be integer instead of string

libs/vault/src/components/password-history-view/password-history-view.component.html, libs/vault/src/components/password-history-view/password-history-view.component.spec.ts, libs/vault/src/components/password-history-view/password-history-view.component.ts
https://bitwarden.atlassian.net/browse/PM-14183
Update styling of the copy success toast
- **Remove unnecessary copy icon -** https://github.com/bitwarden/clients/commit/53fbfc22d3fa91887a11b2c8f6dbde180e34b4f2
- **Fix styling of copy success toast -** https://github.com/bitwarden/clients/commit/478c313737c5295c26746c1921c1d2e697d5b2a5
- Use CopyClick directive instead of manually copying and showing the toast
- Adjust tests …
=> [PM-14183] Show success toast on copy history value

libs/components/src/chip-select/chip-select.component.html, libs/components/src/chip-select/chip-select.component.ts
[CL-498](https://bitwarden.atlassian.net/browse/CL-498)
This PR sets the width of the chip select menu based on whichever value is larger -- the chip select's width or the width of the menu items. The min and max widths are still respected.
Before:
https://github.com/user-attachments/assets/0d830c0a-a35f-450b-9c5d-326672867386
After:
https://github.com/user-attachments/assets/e01effb1-998a-457f-896f-a505568fe58b
In-app:
https://github.com/user-attachments/assets/e98be350-0b71-4547-af3d-66b3cb9b5a4b
- …
=> [CL-498] Set chip menu width minimum to chip select width

apps/web/src/locales/en/messages.json, bitwarden_license/bit-web/src/app/billing/providers/clients/create-client-dialog.component.html, bitwarden_license/bit-web/src/app/billing/providers/clients/create-client-dialog.component.ts, bitwarden_license/bit-web/src/app/billing/providers/subscription/provider-subscription-status.component.html, bitwarden_license/bit-web/src/app/billing/providers/subscription/provider-subscription-status.component.ts, libs/common/src/admin-console/enums/provider-type.enum.ts, libs/common/src/billing/models/response/provider-subscription-response.ts
https://bitwarden.atlassian.net/browse/PM-13470
Allow creating clients for multi-organization enterprise in the provider portal.
Changes:
- Client creation dialog should enumerate assigned provider plans. Managed Service Providers should display both Teams and Enterprise monthly plans, while Multi-organization Enterprise typically have only 1 provider plan being either Enterprise Monthly or Enterprise Annual.
- Provider portal should render the correct provider type's name on the Subscription page. Previously we have 'Managed Service Provider' hard-coded.
- Used …
=> [PM-13470] Allow creating clients for multi-org providers

libs/common/src/tools/state/user-state-subject.spec.ts, libs/common/src/tools/state/user-state-subject.ts, libs/tools/generator/core/src/services/credential-generator.service.spec.ts
https://bitwarden.atlassian.net/browse/PM-13398
Fixed length allowing negative values on Chrome extension. 
The root cause of this bug is that Firefox updates on every state save, whereas Chrome only updates when the value stored changes. (e.g. Chrome requires `{ foo: 1 }` to become `{ foo: 2 }` to trigger its storage changed event.)
The current mechanism is a stopgap for browser UI refresh. 
* It does not affect encrypted payloads, since their IVs vary the encrypted payload.
* It could be implemented properly as a new `ObjectKey` format.
* It could be extended into a [version vector](https://en.wikipedia.org/wiki/Version_vector) or [vector clock](https://en.wikipedia.org/wiki/Vector_clock) to provide distributed change detection.
- 📝 (`:memo:`) …
=> [PM-13398] embed counter into saved state so chrome always sends change notifications

.github/workflows/build-browser.yml, .github/workflows/build-cli.yml, .github/workflows/build-desktop.yml, .github/workflows/build-web.yml
Follow-up to earlier check run changes.
To drive awareness of the need for the check run, just require it across the common setup job all the builds use, this way it's checked early and at the first time code is checked out.
- ❓ …
=> Check run earlier during setup

apps/web/src/app/vault/components/vault-item-dialog/vault-item-dialog.component.ts
[PM-14653](https://bitwarden.atlassian.net/browse/PM-14653)
When a cipher is unassigned in the Admin Console it needs to be deleted with admin privileges. Without passing the admin flag, the delete request comes back as a 404 as the user does not have direct access to it.
- This bug only occurs when the `Owners and admins can manage all collections and items` setting is disabled.
- Parallel PR that fixes this when the extension refresh is disabled: #11927
|Before (error) | After (success)|
|-|-|
|<video src="https://github.com/user-attachments/assets/831cf04e-ff51-4370-88a9-08af0bc37a8f" /> | <video src="https://github.com/user-attachments/assets/f731bb9b-63c8-484e-a62f-20a25efcdf74" />| …
=> [PM-14653] Delete Unassigned Ciphers 

libs/tools/generator/components/src/passphrase-settings.component.ts
https://bitwarden.atlassian.net/browse/PM-12338
The passphrase settings screen needs to `.toString()` translations for Safari compatibility.
=> [PM-12338] fix length hint on passphrase num words field

libs/common/src/platform/services/fido2/fido2-utils.spec.ts, libs/common/src/platform/services/fido2/fido2-utils.ts
The original implementation of bufferSourceToUint8Array was incorrect as it did not consider that TypedArray instances represent a view of the underlying ArrayBuffer which does not necessarily cover the entire backing ArrayBuffer. This resulted in the output of this function containing data which would not be logically contained in the input.
This was partially fixed by #8787 for the common case of the input already being an Uint8Array, but it was still broken for any other TypedArrays. But #8222 introduced another copy of the original broken code, breaking the Uint8Array case again.
Fix this once and hopefully for the last time with a correct implementation of bufferSourceToUint8Array and using that in the appropriate places instead of open-coding it. In addition there are now tests …
=> [PM-14242] fido2-utils: fix BufferSource conversions

apps/browser/src/autofill/services/autofill.service.ts, apps/browser/src/vault/popup/components/vault/current-tab.component.ts
(https://github.com/bitwarden/clients/issues/10475)
Firefox disallows add-ons to keep strong references to DOM objects after their parent document (the popup in this case) has been destroyed. The result is a "TypeError: can't access dead object", which prevents successfully calling updateLastUsedDate() to move the selected cipher to the top of the list. A similar issue with totp copy is resolved in https://github.com/bitwarden/clients/pull/2067, but has an exclusion for Firefox. Removing Firefox from that exclusion stops the issue. …
=> [PM-11332] Prevent dead object error in Firefox due to timing issue

libs/tools/generator/components/src/password-settings.component.ts
https://bitwarden.atlassian.net/browse/PM-14001
Fix a bug caused by the logic that saved the user's last value when deselecting a character class. The logic read the current value of the checkbox to determine whether the value was saveable, which was incorrect when setting the value manually to 0.
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or …
=> [PM-14001] do not store last value when it is 0

libs/common/src/enums/feature-flag.enum.ts
[PM-8682](https://bitwarden.atlassian.net/browse/PM-8682)
Add two flags for the two phases of the new device verification notice epic …
=> [PM-8682] Add flags for new device verification

libs/importer/spec/dashlane-csv-importer.spec.ts, libs/importer/spec/test-data/dashlane-csv/credentials-otpurl.csv.ts, libs/importer/src/importers/dashlane/dashlane-csv-importer.ts, libs/importer/src/importers/dashlane/types/dashlane-csv-types.ts
https://bitwarden.atlassian.net/browse/PM-13952
Within credentials.csv  the column `otpSecret` got replaced with `otpUrl`. This adds support for both of them, in case a user tries to import from an older source. …
=> [PM-13952] Fix totp import on Dashlane csv importer

apps/browser/src/tools/popup/send-v2/send-v2.component.html, libs/tools/send/send-ui/src/send-search/send-search.component.html
[PM-14895](https://bitwarden.atlassian.net/browse/PM-14895)
Add autofocus to search field on Send page.
https://github.com/user-attachments/assets/6c3bece0-5ff0-46b9-8ba6-d414e9e73313 …
=> [PM-14895] Add autofocus to search field on Send page

apps/browser/store/windows/AppxManifest.xml, apps/desktop/electron-builder.json
The legal info on the windows store account was updated from `8bit Solutions LLC` to `Bitwarden Inc`. I believe these updates are necessary to match that change for future app releases.
=> Update the publisher name to Bitwarden Inc

apps/web/src/app/tools/risk-insights/password-health-members-uri.component.spec.ts, apps/web/src/app/tools/risk-insights/password-health-members-uri.component.ts, apps/web/src/app/tools/risk-insights/password-health-members.component.ts, apps/web/src/app/tools/risk-insights/password-health.component.spec.ts, apps/web/src/app/tools/risk-insights/password-health.component.ts, bitwarden_license/bit-common/src/tools/reports/risk-insights/services/member-cipher-details-api.service.spec.ts, bitwarden_license/bit-common/src/tools/reports/risk-insights/services/member-cipher-details-api.service.ts, bitwarden_license/bit-common/src/tools/reports/risk-insights/services/password-health.service.spec.ts, bitwarden_license/bit-common/src/tools/reports/risk-insights/services/password-health.service.ts
https://bitwarden.atlassian.net/browse/PM-14813
This PR uses the `MemberCipherDetailsApiService` for the member data in the risk insights tables. 
*Note to reviewers*
The `getMemberCipherDetails` function was returning an empty `data` array. The data was in the private `response` array which is inaccessible to the caller so I removed the `ListResponse` code and passed the data directly. If there is an alternative please let me know.
- Updated any …
=> [PM-14813] - Implement server API to user member cipher details instead of mock data

.github/workflows/build-desktop.yml, .gitignore, apps/desktop/package.json, apps/desktop/resources/com.bitwarden.desktop.devel.yaml
https://bitwarden.atlassian.net/browse/PM-14850
Adds QA artifacts for flatpak, and adds npm command to pack flatpak for development. …
=> [PM-14850] Flatpak development & qa artifacts

apps/browser/src/vault/popup/components/vault-v2/view-v2/view-v2.component.spec.ts, apps/browser/src/vault/popup/components/vault-v2/view-v2/view-v2.component.ts
[PM-14221](https://bitwarden.atlassian.net/browse/PM-14221)
Removes the check for `SHOW_AUTOFILL_BUTTON` in `view-v2.component.` This stops the extension from autofilling and closing when a user clicks the "view" button on the autofill component. 
- From my testing the `AUTOFILL_ID` check is still needed for when a cipher has master password reprompt set 
View action from autofill and verification that master password reprompt still works: 
<video src="https://github.com/user-attachments/assets/b4318eca-3dda-46ed-8931-32d8dc550728" /> …
=> [PM-14221] Fix extension autofilling instead of viewing

apps/browser/src/background/main.background.ts, apps/browser/src/popup/services/services.module.ts, apps/browser/src/vault/popup/services/vault-popup-autofill.service.spec.ts, apps/browser/src/vault/popup/services/vault-popup-autofill.service.ts, apps/browser/src/vault/popup/services/vault-popup-items.service.spec.ts, apps/browser/src/vault/popup/services/vault-popup-items.service.ts
PM-12399
Show card and identity ciphers in the autofill suggestions only if the active tab appears to have fields for that type of cipher
https://github.com/user-attachments/assets/84f5abb9-13d5-480b-9c98-92a1965a1e95 …
=> [PM-12399] Show card and identity ciphers in the autofill suggestions only if the active tab appears to have fields for that type of cipher

apps/web/src/app/vault/individual-vault/vault-filter/components/vault-filter.component.ts, apps/web/src/app/vault/individual-vault/vault-filter/services/vault-filter.service.ts, apps/web/src/app/vault/individual-vault/vault-filter/shared/models/filter-function.ts, apps/web/src/app/vault/individual-vault/vault-filter/shared/models/routed-vault-filter.model.ts
https://bitwarden.atlassian.net/browse/PM-14914
in web, filtering by SSH Key would not set the vault filter active as expected in the UI or return SSH Key item types only …
=> PM-14914/ssh-key-item-type-filtering-web

apps/web/src/app/vault/components/vault-item-dialog/vault-item-dialog.component.ts
[PM-14653](https://bitwarden.atlassian.net/browse/PM-14653)
The `VaultItemDialogComponent` is shared between Password Manager and Admin Console.
- Personal Items do not have assigned collections, the collection check to use the admin endpoint should only be applicable when the dialog is rendered within the Admin Console.
| AC - Unassigned Cipher | AC - Assigned Cipher | PM - Personal Cipher|
|-|-|-|
| <video src="https://github.com/user-attachments/assets/47a82007-2348-4809-92fc-d02acbb7f8cb" />| <video src="https://github.com/user-attachments/assets/49f45dd0-e523-4e3e-a4fe-5f2f4dd69a06" />| <video src="https://github.com/user-attachments/assets/6fa2811f-52b7-42c6-a6c2-dad7f6579c9e" /> …
=> [PM-14653] PM/AC Delete Cipher

libs/tools/generator/components/src/password-settings.component.ts
https://bitwarden.atlassian.net/browse/PM-13711
Fix a bug where the generator interpreted the "avoid ambiguous characters" flag as an "include ambiguous characters" flag.
=> [PM-13711] invert ambiguous character flag

libs/angular/src/vault/components/add-edit.component.ts
https://bitwarden.atlassian.net/browse/PM-13829
This PR adds a check to see if a cipher belongs to an organization to determine which REST call to make. Personal items should not be deleted with the admin delete call. This check is refactored as a getter property and is added to the `restoreCipher()` function to resolve the same issue.
- 👍 (`:+1:`) …
=> [PM-13829] Add organizationId to isAdmin check, refactor isAdmin to getter

.github/workflows/crowdin-pull.yml
- [Card](https://bitwarden.atlassian.net/browse/BRE-438?atlOrigin=eyJpIjoiMTI1ODU4NjFhNjkyNGY2ZmI0MmZhYmQ1YmNhZDhjODIiLCJwIjoiaiJ9)
This PR updates the Crowdin workflow to use a temporary token. This will allow the PR to trigger the test workflow. …
=> BRE-438 - Update Crowdin workflow

apps/browser/src/_locales/en/messages.json, apps/desktop/src/locales/en/messages.json, apps/web/src/app/admin-console/organizations/policies/password-generator.component.ts, apps/web/src/locales/en/messages.json, libs/common/src/tools/types.ts, libs/tools/generator/components/src/passphrase-settings.component.ts, libs/tools/generator/components/src/password-settings.component.ts, libs/tools/generator/core/src/data/default-passphrase-boundaries.ts, libs/tools/generator/core/src/data/generators.ts, libs/tools/generator/core/src/policies/dynamic-password-policy-constraints.spec.ts, libs/tools/generator/core/src/policies/dynamic-password-policy-constraints.ts, libs/tools/generator/core/src/policies/passphrase-policy-constraints.spec.ts, libs/tools/generator/core/src/policies/passphrase-policy-constraints.ts
https://bitwarden.atlassian.net/browse/PM-14964
Revert 0254550b07277be7f0d6fedcd862b462e80947a3 and explain recommended boundaries using hint text.
No policy; value exceeds recommended value:
No policy; value less than or equal to recommended value:
With policy; value exceeds recommended value:
With policy' value less than or equal to recommended value:
- 🌱 …
=> [PM-14964] revert passphrase minimum

libs/importer/src/components/dialog/import-success-dialog.component.ts
https://bitwarden.atlassian.net/browse/PM-14923
The i18n key for ssh items had incorrect capitalization in the import success dialog, leading to no text being shown. This fixes the key. …
=> [PM-14923] Fix import dialog ssh key i18n

README.md
The https://github.com/bitwarden/mobile repository was retired. Update current Bitwarden mobile repositories at README.md .
=> Update Bitwarden mobile repositories at README.md

apps/web/src/app/vault/org-vault/vault-header/vault-header.component.html, apps/web/src/app/vault/org-vault/vault-header/vault-header.component.ts
[PM-14473](https://bitwarden.atlassian.net/browse/PM-14473)
The ticket is geared towards custom users that _cannot_ create a collection. Those users were only seeing the "new item" button rather than the dropdown to select the cipher type.
This was caused by the hierarchy of logic favoring the user's permissions rather than the extension refresh first. To solve:
- I moved the check for extension refresh up, so the user will always see the dropdown menu unless they can _only_ create collection<sup>1</sup>. 
- This does create a little but of duplicate markup, but it will be easy to strip out the non-refresh code once that is enabled.
- There is internal logic within the dropdown menu to properly show the available options respective of the permissions.
<sup>1</sup> I wasn't able to find …
=> [PM-14473] AC - "New" item button

libs/components/src/navigation/nav-group.component.html, libs/components/src/navigation/nav-group.component.ts, libs/components/src/navigation/nav-group.stories.ts
TBA depending on feedback
In our layouts, we often have a `bit-nav-group` with child `bit-nav-item`s which are conditionally rendered based on the user's permissions. If no child items are rendered, then the user can't access anything in the group, so we hide the group.
For example:
```ts
<bit-nav-group
icon="bwi-sliders"
[text]="'reporting' | i18n"
route="reporting"
*ngIf="organization.canAccessEventLogs || organization.canAccessReports)"  // duplicate logic
>
<bit-nav-item
[text]="'eventLogs' | i18n"
route="reporting/events"
*ngIf="organization.canAccessEventLogs"
></bit-nav-item>
<bit-nav-item
[text]="'reports' | i18n"
route="reporting/reports"
*ngIf="organization.canAccessReports"
></bit-nav-item>
</bit-nav-group>
```
As you can see, this means we have to duplicate the conditional …
=> Add hideIfEmpty to bit-nav-group

apps/browser/src/_locales/en/messages.json
=> Fix missing i18n

libs/common/src/platform/abstractions/fido2/fido2-authenticator.service.abstraction.ts, libs/common/src/platform/services/fido2/credential-id-utils.spec.ts, libs/common/src/platform/services/fido2/credential-id-utils.ts, libs/common/src/platform/services/fido2/fido2-authenticator.service.spec.ts, libs/common/src/platform/services/fido2/fido2-authenticator.service.ts, libs/common/src/platform/services/fido2/guid-utils.spec.ts
Implement support for `credentialIds` encoded as Base64. This does not change how new `credentialIds` are created, this is on purpose so that we don't break older clients …
=> [PM-7382] Add support for non-UUID credential

apps/desktop/src/app/app.component.ts, apps/desktop/src/app/tools/generator/credential-generator.component.html, apps/desktop/src/app/tools/generator/credential-generator.component.ts, apps/desktop/src/locales/en/messages.json
https://bitwarden.atlassian.net/browse/PM-13304
Add button to the bottom of the credential-generator to open the credential generator history
- **Add button to open credential history on desktop -** https://github.com/bitwarden/clients/commit/45b68d88de446a17383201f03a4025e93eafe51d
- Register route to open new CredentialGeneratorHistoryDialogComponent when FeatureFlag/GeneratorToolsModernization is enabled
- Add button to credential generator
- Add missing keys to en/messages.json …
=> [PM-13304] Add button to open credential history on desktop

apps/desktop/src/app/app.component.ts, apps/desktop/src/app/tools/generator/credential-generator.component.html, apps/desktop/src/app/tools/generator/credential-generator.component.ts, apps/desktop/src/locales/en/messages.json, apps/web/src/app/tools/credential-generator/credential-generator.component.html, apps/web/src/app/tools/credential-generator/credential-generator.component.ts, apps/web/src/locales/en/messages.json, libs/tools/generator/components/src/credential-generator-history-dialog.component.html, libs/tools/generator/components/src/credential-generator-history-dialog.component.ts, libs/tools/generator/components/src/index.ts
https://bitwarden.atlassian.net/browse/PM-13667
Add button to the bottom of the credential-generator to open the credential generator history
- **Create CredentialGeneratorHistoryDialogComponent to be re-used on web and desktop -** https://github.com/bitwarden/clients/commit/fcfdb8f164fa83d859b74323b8002b474c369f96
- **Add button to open credential history on web -** https://github.com/bitwarden/clients/commit/1c1be55d2a03a350e32289dff440c3a25bf93d4e
- Add button
- Add missing keys to en/messages.json
- …
=> [PM-13667] Add button to open credential history on web

apps/browser/src/auth/popup/settings/account-security.component.ts, libs/common/src/enums/feature-flag.enum.ts
https://bitwarden.atlassian.net/browse/PM-14593
In the legacy `AccountSercurityV1Component` the `updateBiometric(enabled: boolean)` method had an [else block](https://github.com/bitwarden/clients/blob/main/apps/browser/src/auth/popup/settings/account-security-v1.component.ts#L428-L431) to handle an `enabled` value of `false`. The new `AccountSecurityComponent` is missing this block, which makes it so the user cannot disable biometrics because we aren't handling the case where they uncheck the biometrics checkbox. This PR just adds it back in so we handle a `false` value.
- …
=> [PM-14593] Bugfix for "Cannot disable biometrics on extension" (ExtensionRefresh)

apps/web/src/app/tools/access-intelligence/risk-insights.component.html
https://bitwarden.atlassian.net/browse/PM-15105
This PR removes the check for `apps.length` as the criterion for displaying the date last checked and refresh button in the risk insights page.
- 🤔 …
=> [PM-15105] - add date last checked and refresh button

apps/browser/src/_locales/en/messages.json, apps/browser/src/platform/popup/browser-popup-utils.ts, apps/browser/src/platform/popup/layout/popup-layout.stories.ts, apps/browser/src/platform/popup/layout/popup-width.service.ts, apps/browser/src/popup/app.component.ts, apps/browser/src/popup/main.ts, apps/browser/src/popup/scss/base.scss, apps/browser/src/vault/popup/settings/appearance-v2.component.html, apps/browser/src/vault/popup/settings/appearance-v2.component.spec.ts, apps/browser/src/vault/popup/settings/appearance-v2.component.ts, libs/common/src/platform/services/config/default-config.service.ts, libs/common/src/platform/state/state-definitions.ts, libs/components/src/select/index.ts
https://bitwarden.atlassian.net/browse/CL-508
Adds an setting to the extension for configuring the popup's width. 🚀 
https://github.com/user-attachments/assets/e6b64008-501a-4f81-94e8-fb53c0720bfd
- 🤔 …
=> [CL-508] extension width setting

apps/browser/src/platform/popup/layout/popup-width.service.ts, apps/browser/src/popup/scss/base.scss
[PM-15021](https://bitwarden.atlassian.net/browse/PM-15021)
When opening the browser extension in a new tab, the UI remained constrained to the width of the extension window. It should stretch to fill the tab window. This improves the experience because animations and dialogs span the full width, which caused jarring visuals and missing functionality.
Before:
https://github.com/user-attachments/assets/210cd1f9-e1b9-4dc9-a162-04515c459c1e
After:
https://github.com/user-attachments/assets/585b7ea7-b7a7-464c-9ab9-096d4a678d70
Confirming no regressions to popup and popout views:
https://github.com/user-attachments/assets/72fbb2e7-3de5-4aff-9801-3bb670706d1c
- Written new unit and / or integration tests …
=> [PM-15021] Improve in-tab experience for extension

apps/browser/src/autofill/services/autofill.service.spec.ts, apps/browser/src/autofill/services/autofill.service.ts
[PM-15065](https://bitwarden.atlassian.net/browse/PM-15065)
When loading the extension directly via URL, i.e. `moz-extension://...` the vault was failing to load in Firefox. This was occurring because `tabSendMessage` is not throwing an error and the message is not being received to provide autofill suggestions.  
- Chrome and Safari were functioning correctly but with this undocumented behavior it felt safer to add checks for those as well.   
|Chrome|FireFox|Safar|
|-|-|-|
|<video src="https://github.com/user-attachments/assets/f99cca52-1f4e-4ec7-84ea-388e8edaca21"/>|<video src="https://github.com/user-attachments/assets/fb9a48a4-f016-42e2-a916-1fd78ffd8c8d"/>|<video src="https://github.com/user-attachments/assets/e6b73033-b3d2-44cc-8740-4c849700317e"/>| …
=> [PM-15065] Extension not loading when accessed via URL

apps/browser/src/platform/popup/browser-popup-utils.ts
https://bitwarden.atlassian.net/browse/PM-15410
https://bitwarden.atlassian.net/browse/PM-15428
https://github.com/bitwarden/clients/pull/12040 adds a reference to `document.body.clientWidth` in the `BrowserPopupUtils.openPopout`. This is causing an error because this function is imported in the background script, where `document` is undefined (see screenshot #1). 
I assumed this was safe because `BrowserPopupUtils` is located in `apps/browser/src/platform/popup`, which contains other non-background-safe code. This is a quick fix; we probably want to make additional changes to better guard against this in the future (lint for forbidden APIs, moving this class/function somewhere else).
1. 
- Written …
=> [PM-15410][PM-15410] add nullish check when referencing `document` in `BrowserPopupUtils`

apps/web/src/app/auth/settings/account/profile.component.html, apps/web/src/locales/en/messages.json
https://bitwarden.atlassian.net/browse/PM-14874
> As a result of the copy updates we have been making (replacing Verified domains as Claimed accounts, using ownership terminology instead of managed) we would like to replace managed with owned on the members Account page
> [Figma](https://www.figma.com/proto/lHZXTF0bl9fEB42FroKNOb/Account-management-and-deprovisioning?page-id=1%3A12&node-id=530-47299&viewport=-2598%2C-1498%2C0.23&t=PScSIhiDMXqxj9fV-1&scaling=scale-down-width&content-scaling=fixed&starting-point-node-id=530%3A47299&show-proto-sidebar=1)
- Used …
=> [PM-14874] Update account ownership message in account page

bitwarden_license/bit-web/src/app/admin-console/organizations/manage/domain-verification/domain-verification.component.ts
https://bitwarden.atlassian.net/browse/PM-15386
The pop up for the warning message “Verifying a domain will turn on the single organization policy“ will show up even if the single org policy is enabled. This PR addresses this by checking the policy state to decide if it shows the warning or not.
- 📝 …
=> [PM-15386] Refactor DomainVerificationComponent to warn about enabling SingleOrg policy only when it is not already enabled

apps/desktop/src/locales/en/messages.json, apps/desktop/src/vault/app/vault/add-edit.component.ts, libs/importer/src/components/dialog/index.ts, libs/importer/src/components/dialog/sshkey-password-prompt.component.html, libs/importer/src/components/dialog/sshkey-password-prompt.component.ts
https://bitwarden.atlassian.net/browse/PM-14990
Adds a password prompt UI for importing password protected ssh keys in the desktop app.
https://github.com/user-attachments/assets/fa66e14d-5556-4a1b-b54f-6d4fbb9cf964 …
=> [PM-14990] Add password prompt for ssh key import

apps/web/src/app/admin-console/organizations/members/components/bulk/bulk-delete-dialog.component.html, apps/web/src/app/admin-console/organizations/members/components/bulk/bulk-remove-dialog.component.html, apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.ts, apps/web/src/app/admin-console/organizations/members/members.component.ts, apps/web/src/locales/en/messages.json
https://bitwarden.atlassian.net/browse/PM-15156
Update warning messages for bulk delete dialog and single member deletion.
[Single delete](https://www.figma.com/proto/lHZXTF0bl9fEB42FroKNOb/Account-management-and-deprovisioning?page-id=1783%3A33700&node-id=1984-18922&node-type=frame&viewport=-1190%2C-5500%2C0.39&t=7jCztb2PXpqrl9Lx-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=1984%3A18857&show-proto-sidebar=1)
[Bulk delete](https://www.figma.com/proto/lHZXTF0bl9fEB42FroKNOb/Account-management-and-deprovisioning?page-id=1783%3A33700&node-id=1984-18940&node-type=frame&viewport=-1190%2C-5500%2C0.39&t=7jCztb2PXpqrl9Lx-1&scaling=min-zoom&content-scaling=fixed&starting-point-node-id=1984%3A18879&show-proto-sidebar=1)
Rename 'Delete members' to 'Remove members' on bulk remove …
=> [PM-15156] Copy update on Organization member Delete modals

apps/cli/src/tools/generate.command.ts
https://bitwarden.atlassian.net/browse/PM-15353
Fix broken ambiguous flag on CLI. 
The services use `true` to indicate ambiguous characters should be included. The CLI was passing `false`.
Example output with `--ambiguous` flag:
Note that when `--ambiguous` is present, ambiguous characters are _excluded_. The flag would more properly be called `--no-ambiguous`, but changing this is out of scope of this PR. 
We should consider addressing this when we migrate the CLI to the credential generator backend. An appropriate solution would issue a deprecation warning when the old flag is used. That could be updated to a failure when the deprecated flag is removed. …
=> [PM-15353] invert ambiguous flag

apps/cli/src/commands/get.command.ts, apps/cli/src/oss-serve-configurator.ts, apps/cli/src/tools/send/send.program.ts, apps/cli/src/vault.program.ts
While updating a different PR I noticed the unused stateService within some CLI commands. This removes them as a ctor param and dependency. …
=> Remove unused stateService dependency

apps/browser/src/vault/popup/components/vault-v2/view-v2/view-v2.component.spec.ts, apps/browser/src/vault/popup/components/vault-v2/view-v2/view-v2.component.ts, libs/vault/src/services/copy-cipher-field.service.spec.ts, libs/vault/src/services/copy-cipher-field.service.ts
[PM-14965](https://bitwarden.atlassian.net/browse/PM-14965)
Fix the updated vault item view page to handle all context menu and inline menu actions when an item is protected with password reprompt.
https://github.com/user-attachments/assets/ec97fe77-810a-40c3-a42f-d7ad4e16edb2 …
=> [PM-14965] Fix password reprompt for context menu actions

apps/web/src/app/admin-console/organizations/policies/policy-edit.component.html, apps/web/src/app/admin-console/organizations/policies/policy-edit.component.ts
https://bitwarden.atlassian.net/browse/PM-13757
This PR resolves an issue where the Policy Edit component's form validation on the save button is not synced with the validation status of the Policy Component's form group.
- ❓ …
=> [PM-13757] Add policy component form validation to policy edit component

apps/web/src/app/vault/individual-vault/vault.component.html, apps/web/src/app/vault/individual-vault/vault.component.ts
[PM-15520](https://bitwarden.atlassian.net/browse/PM-15520)
Fix the `organizationsPaymentStatus$` observable so that it does not return an empty observable when the user is not the owner of any organization. This would prevent the vault from refreshing as it would show a loading spinner while it waits for the empty observable to never emit.
Also, moves the `organizationsPaymentStatus$` out of the `firstSetup` subscription to avoid depending on the payment status for rendering the vault. That way if the `organizationsPaymentStatus$` observable fails or hangs, the vault is still capable of being rendered.
https://github.com/user-attachments/assets/964131f1-ecb6-4171-a46f-1a95cb35a647
- Written new unit …
=> [PM-15520] Fix empty organization payment status observable

apps/browser/src/autofill/background/overlay.background.ts
https://bitwarden.atlassian.net/browse/PM-15046
https://github.com/bitwarden/clients/issues/12047
A `generatePassword` call in `handleOverlayCiphersUpdate` of `OverlayBackground` is causing the password generation to fire as a side-effect of any user interaction with a page. This update stops that behaviour, so the generated password history is not flooded with entries the user has never seen.
Note, this behaviour is ultimately behind the `inline-menu-positioning-improvements` feature flag
- 🎨 …
=> [PM-15046] Do not regenerate passwords on every overlay ciphers update

libs/tools/send/send-ui/src/new-send-dropdown/new-send-dropdown.component.html
https://bitwarden.atlassian.net/browse/PM-15544
When selecting a new text send the premium page was shown although it should only show when a user has no premium and select a file send.
Changes will need to be 🍒 ⛏️  to `rc`
- ❓ …
=> [PM-15544] Fix the new send dropdown showing premium when it should not

apps/browser/src/vault/popup/settings/trash-list-items-container/trash-list-items-container.component.html, apps/browser/src/vault/popup/settings/trash-list-items-container/trash-list-items-container.component.ts, apps/browser/src/vault/popup/settings/trash.component.ts, libs/vault/src/components/can-delete-cipher.directive.ts, libs/vault/src/index.ts
https://bitwarden.atlassian.net/browse/PM-15535
Added permission check to restrict delete functionality in the trash component.
https://github.com/user-attachments/assets/23ff3114-49bf-4032-83c0-2823fed4794a …
=> [PM-15535] User with Edit* permission can permanently delete item from more actions menu on extension

apps/web/src/app/admin-console/organizations/members/members.component.ts
https://bitwarden.atlassian.net/browse/PM-15548
Resolves an error that occurred when the system would attempt to display subscription info to a non-owner, or non-provider user. …
=> [PM-15548] If user can't view subscription, don't show upgrade modal

apps/web/src/app/vault/components/vault-item-dialog/vault-item-dialog.component.ts, apps/web/src/app/vault/org-vault/services/admin-console-cipher-form-config.service.spec.ts, apps/web/src/app/vault/org-vault/services/admin-console-cipher-form-config.service.ts
[PM-15559](https://bitwarden.atlassian.net/browse/PM-15559)
The admin console cipher form service was always fetching ciphers from the API which do not have permissions available. The PR updates the logic to only fetch from the API when the user has `CanEditAllCiphers` permission or when the cipher is `Unassigned` (and thus only available via the admin API). 
The same applies after the form is submitted, we should only fetch the updated cipher from the API.
https://github.com/user-attachments/assets/4b21bbd8-ed9e-488e-82e0-6797e2cca5b8 …
=> [PM-15559] Fix hide passwords in AC for users that have view, except password

apps/web/src/app/vault/individual-vault/vault.component.ts, apps/web/src/app/vault/org-vault/vault.component.ts
https://bitwarden.atlassian.net/browse/PM-15585
Linking a newly created stripe subscription to a Reseller causes the client org owner to be immediately logged out after logging in.
Uploading Screen Recording 2024-12-05 at 20.36.14.mov…
- …
=> [PM-15585]401 Unauthorized when attempting to authenticate newly linked Client Org Owner

libs/angular/src/auth/components/two-factor.component.ts, libs/auth/src/common/abstractions/login-strategy.service.ts, libs/auth/src/common/services/login-strategies/login-strategy.service.ts
https://bitwarden.atlassian.net/browse/PM-13659
Initial PR which works locally but not in deployed envs: https://github.com/bitwarden/clients/pull/12201
Attempted Fix 1: https://github.com/bitwarden/clients/pull/12263
To add logs to try to figure out why authn timeout emissions are not working to navigate the user. 
no applicable code changes other than logs.  …
=> Auth/PM-13659 - 2FA Timeout - Add logs to try to figure out issue with timeout not working

apps/web/src/scss/plugins.scss
https://bitwarden.atlassian.net/browse/PM-15611
Adjust height of WebAuthn 2FA iframe so it doesn't get cut off.
| Before  | After |
| ------------- | ------------- |
| ![image-20241205-200706](https://github.com/user-attachments/assets/67e39d3c-d2af-4267-8501-52ade1cc1cf5) | <img width="541" alt="Screenshot 2024-12-05 at 3 30 32 PM" src="https://github.com/user-attachments/assets/f928fcd2-bbde-44e1-a6b5-90cbe8d94f1b"> | …
=> [PM-15611] UI Bugfix - WebAuthn 2FA iFrame height adjustment

apps/cli/src/service-container/service-container.ts, libs/angular/src/auth/components/two-factor.component.ts, libs/angular/src/services/injection-tokens.ts, libs/angular/src/services/jslib-services.module.ts, libs/auth/src/common/abstractions/login-strategy.service.ts, libs/auth/src/common/services/login-strategies/login-strategy.service.ts
https://bitwarden.atlassian.net/browse/PM-13659?atlOrigin=eyJpIjoiMGZkZTFkMjZhNzdiNDZmYzljODI0MjYzMWJkZWZlYTQiLCJwIjoiaiJ9
Reverts adding an `authnSessionTimeoutExecutor` and logging used for debugging the original PM-13659 work. It turned out the `two-factor-component-refactor` feature flag needs to be disabled in dev so these changes were unnecessary. …
=> [PR-13659] revert adding executor function and logging

libs/vault/src/cipher-view/item-history/item-history-v2.component.html
[PM-12771](https://bitwarden.atlassian.net/browse/PM-12771)
- Visually the password history looked accurate to the designs, unlike the screenshot in the ticket. 
- Refactoring the password history to be a `button` and use `bitLink` does improve the consistency for future changes and make the dialog keyboard accessible. 
- Previously the link did not have an `href` and thus was excluded from the tab order. 
<video src="https://github.com/user-attachments/assets/5b06f009-a3d1-435d-bf47-de31494b3094" /> …
=> [PM-12771] Password History Styles

libs/components/src/checkbox/checkbox.component.ts, libs/components/src/form-control/form-control.component.html, libs/components/src/form-control/form-control.module.ts, libs/components/src/form/form.stories.ts, libs/components/src/radio-button/radio-group.component.html, libs/components/src/radio-button/radio-input.component.ts
[CL-522](https://bitwarden.atlassian.net/browse/CL-522)
This PR reduces the font size of checkbox and radio labels from `body1` to `body2`, which will improve the way forms and pages with these elements look by normalizing the font size hierarchy.
It also fixes a couple of errors in the form full example story.
| ![Screenshot 2024-12-04 at 10 34 46 AM](https://github.com/user-attachments/assets/44dfb1c4-d114-4950-be0d-5c718c1bd1cf) | ![Screenshot 2024-12-04 at 2 56 01 PM](https://github.com/user-attachments/assets/840fd79a-556b-4162-9818-62298851de1d) |
| ![Screenshot 2024-12-04 at 3 47 53 PM](https://github.com/user-attachments/assets/dbc21f21-3ac2-474c-9688-c0b895d9824c) | ![Screenshot 2024-12-04 at 3 15 …
=> [CL-522] Reduce font size for checkbox and radio labels

apps/web/src/app/billing/organizations/change-plan-dialog.component.ts, apps/web/src/app/layouts/product-switcher/product-switcher-content.component.html, apps/web/src/app/settings/domain-rules.component.html, bitwarden_license/bit-web/src/app/billing/providers/clients/create-client-dialog.component.html, bitwarden_license/bit-web/src/app/billing/providers/clients/create-client-dialog.component.ts, libs/components/src/layout/layout.component.html, libs/components/src/table/sortable.component.ts
[CL-351](https://bitwarden.atlassian.net/browse/CL-351)
In PR #10188, we fixed an issue where styles were colliding due to multiple `tw-group`s being on a page together. This was solved by namespacing the `tw-group` for that instance. 
This PR namespaces the remaining `tw-group`s used in the app to prevent the issue from occurring elsewhere. Some of the existing `tw-group`s were actually not being used (leftovers from previous implementations of components), so those were removed.
- Communicated to DevOps …
=> [CL-351] Prevent tw-group styling conflicts by namespacing

apps/browser/src/background/main.background.ts, apps/browser/src/platform/browser/browser-api.ts
https://bitwarden.atlassian.net/browse/PM-14012
https://github.com/bitwarden/clients/issues/11694
https://github.com/bitwarden/clients/issues/3840
Safari handles `chrome.runtime.reload` weird. It triggers an `install` event, which we use to show the "Getting started with the Bitwarden extension" tab. This results in that tab being opened whenever we reload the extension for any reason.
This was fixed for one case on https://github.com/bitwarden/clients/pull/11115, but this left out the case for native messaging [here](https://github.com/bitwarden/clients/blob/17cd251732bf61737ffe5b937f8e1cdc5379073a/apps/browser/src/background/nativeMessaging.background.ts#L91).
To fix this forever for any calls to refresh the extension via `BrowserApi` I've moved the condition into that method instead of …
=> fix(safari): add a bespoke implementation for `reloadExtension`

apps/web/src/app/billing/organizations/payment-method/organization-payment-method.component.html, apps/web/src/app/billing/services/trial-flow.service.ts, apps/web/src/app/billing/shared/payment-method.component.html, apps/web/src/app/vault/individual-vault/vault-banners/vault-banners.component.html, apps/web/src/app/vault/individual-vault/vault-banners/vault-banners.component.ts, apps/web/src/app/vault/org-vault/vault.component.html, apps/web/src/locales/en/messages.json, bitwarden_license/bit-web/src/app/secrets-manager/overview/overview.component.html
https://bitwarden.atlassian.net/browse/PM-15180
This PR updates the translation keys for the different trial banners to all have complete sentences to allow for proper translation.
Uploading Screen Recording 2024-11-25 at 3.43.04 PM.mov… …
=> [PM-15180] - update copy for free trial banner

.github/workflows/build-browser-target.yml, .github/workflows/build-cli-target.yml, .github/workflows/build-desktop-target.yml, .github/workflows/build-web-target.yml
=> fix: target workflows not triggering on pull_request_target

apps/desktop/desktop_native/core/src/ssh_agent/unix.rs
#10825
When starting the ssh-agent the first time on unix, the rust code tries to remove the previous ssh-agent socket. On first time setup, there is no file, so it fails. This change makes it fail gracefully when no file is found.
- ❓ …
=> [PM-15937] ssh agent: fix first start when no .bitwarden-ssh-agent.sock exists

apps/browser/src/vault/popup/components/vault/add-edit.component.ts, apps/desktop/src/vault/app/vault/add-edit.component.ts, apps/web/src/app/auth/settings/emergency-access/view/emergency-add-edit-cipher.component.ts, apps/web/src/app/vault/individual-vault/add-edit.component.ts, apps/web/src/app/vault/org-vault/add-edit.component.ts, libs/angular/src/vault/components/add-edit.component.ts
While looking into code-usage and planning to move send-related files I noticed that some components passed the SendApiService into their constructor, but actually never used it anywhere.
This aims to remove those unneeded params and imports …
=> Removed unused ctor param for SendApiService

bitwarden_license/bit-web/src/app/admin-console/providers/clients/vnext-clients.component.html, bitwarden_license/bit-web/src/app/billing/providers/clients/vnext-manage-clients.component.html
https://bitwarden.atlassian.net/browse/PM-15958
This PR fixes an issue in the vNext components where variable length organization names would cause the table column width to resize.
https://github.com/user-attachments/assets/5c6d0c6b-6b70-45dc-aa2e-ad64bb457a4d …
=> [PM-15958] set fixed width for organizationName column

libs/vault/src/cipher-form/components/item-details/item-details-section.component.spec.ts, libs/vault/src/cipher-form/components/item-details/item-details-section.component.ts
[PM-15824](https://bitwarden.atlassian.net/browse/PM-15824)
Stop showing read only collections to admins with access to all ciphers/collections in the Password Manager. The setting to allow admins to edit all ciphers/collections only applies within the Admin Console (e.g. only when the `config.admin` is true). …
=> [PM-15824] Prevent privileged admins from seeing read only collections in Password Manager item dialog

libs/auth/src/angular/login/login.component.ts
[PM-8220](https://bitwarden.atlassian.net/browse/PM-8220)
When a 400-error comes back from the server the password login flow assumes it's a bad password. We are now sending 400s when a user is required to use SSO to login. This allows that toast to display.
https://github.com/user-attachments/assets/b2cbee73-2e7e-466d-8832-440cd7bedc66
- 👍 (`:+1:`) …
=> [PM-8220] Show toasts for other 400 responses

.github/CODEOWNERS
I didn't realize auto merge was on for [this PR](https://github.com/bitwarden/clients/pull/12365).
Just a small thing related to my comment [here](https://github.com/bitwarden/clients/pull/12365#discussion_r1884538621): any worth in moving this under the Autofill team section? We can keep platform if desired, wasn't sure if they were retaining ownership or not. (I can definitely add them back, so no problem either way.)
I made this PR more as a proposal, so no big deal. …
=> Slight codeowners change for ssh agent

bitwarden_license/bit-web/src/app/billing/providers/clients/index.ts, bitwarden_license/bit-web/src/app/billing/providers/clients/replace.pipe.ts, bitwarden_license/bit-web/src/app/billing/providers/clients/vnext-manage-clients.component.html, bitwarden_license/bit-web/src/app/billing/providers/clients/vnext-manage-clients.component.ts
https://bitwarden.atlassian.net/browse/PM-15960
This PR fixes an issue where replacing the plan name on the data causes issues when trying to manage the subscription. The resolution is to implement a replace pipe that we can use to trim/replace strings in the template. …
=> [PM-15960] create pipe for replacing string in template

apps/web/src/app/admin-console/organizations/members/members.component.html
https://bitwarden.atlassian.net/browse/PM-15903
The icons for bulk remove, bulk delete, and individual delete buttons are misaligned due to missing css classes.
Bulk remove and delete:
Individual delete:  …
=> [PM-15903] Fix icon alignment in members component options

libs/auth/src/angular/login-decryption-options/login-decryption-options.component.html, libs/auth/src/angular/login-decryption-options/login-decryption-options.component.ts
https://bitwarden.atlassian.net/browse/PM-15945
This PR adds a logout option to the TDE approval screen. A TDE user on this page cannot use the "Back" button or click the Bitwarden logo to navigate back to `/` because the user is currently authenticated, which means that navigating to the `/` route would activate the [redirectGuard](https://github.com/bitwarden/clients/blob/main/libs/angular/src/auth/guards/redirect.guard.ts#L60) and simply route the user back to `/login-initiated`. So we must log the user out first before routing.
https://github.com/user-attachments/assets/18b4487b-f0fe-41ad-b5b6-daff95796c6b
- Protected functional …
=> [PM-15945] Add logout option to TDE approval screen

apps/desktop/src/main/menu/menu.view.ts
https://bitwarden.atlassian.net/browse/PM-16046
This PR updates the label of the "Password history" button in the desktop app menu to "Generator history". This change ensures consistency with the rest of the app's terminology.
- ❓ …
=> Update Password history button label to Generator history

apps/browser/package.json, libs/importer/src/components/import.component.html, libs/importer/src/components/import.component.ts
https://bitwarden.atlassian.net/browse/PM-15571
This PR fixes a styling issue where the Bitwarden help link on the Import Vault page was not readable in Dark Mode due to poor color contrast on Extension. 
The bit-link directive with the appropriate linkType has been applied to resolve this issue.
- 📝 …
=> [PM-15571] Help link on import vault

libs/importer/src/components/import.component.ts
https://bitwarden.atlassian.net/browse/PM-15623
Fix an issue where regular users can no longer import into an organization vault from the Password Manager import page.
This was caused by #12062, which intended to inline the [canAccessImport function](https://github.com/bitwarden/clients/pull/12062/files#diff-f2058abda4c6915d9795428d41060ce253e3d71777e73061178c8af4e9b62040L65-L83), but accidentally inlined the deprecated `canAccessImportExport` function next to it instead. The practical result is that the `|| org.canCreateNewCollections` part of the conditional was dropped and regular users lost access to organization import from PM.
Note that this cannot be moved inside `org.canAccessImport` because that is used to control access to the Admin Console import page.
Tools Team: I caused the …
=> [PM-15623] Fix user import permissions in Password Manager

apps/web/src/app/auth/settings/emergency-access/view/emergency-view-dialog.component.ts
https://github.com/bitwarden/clients/pull/12054 was an older PR that was raised before strict typing was enabled but merged after it was enabled. One property to add a default value to for all strict typing to pass.
=> Fix Strict Type: Emergency View Dialog

apps/desktop/src/app/services/services.module.ts, apps/desktop/src/autofill/services/desktop-fido2-user-interface.service.ts
https://bitwarden.atlassian.net/browse/PM-16234
Move `DesktopFido2UserInterfaceService` and `DesktopFido2UserInterfaceSession` (part of the same file) to Autofill team ownership. These will need to be implemented / used for the MacOS Desktop passkey UI. …
=> [PM-16234] Move DesktopFido2UserInterfaceService and DesktopFido2UserInterfaceSession

apps/browser/src/platform/popup/layout/popup-layout.mdx, apps/browser/src/platform/popup/layout/popup-layout.stories.ts, apps/browser/src/platform/popup/layout/popup-page.component.html
CL-510
The popup-page component should have a banner content projection slot for banners. This slot will have zero margin, unlike slot="above-scroll-area".
=> [CL-510] Create slot for banners in popup-page component

apps/browser/src/vault/popup/services/vault-popup-items.service.spec.ts, apps/browser/src/vault/popup/services/vault-popup-items.service.ts
[PM-16194](https://bitwarden.atlassian.net/browse/PM-16194)
Revert the change to favorite item sorting so that favorite items are once again only sorted alphabetically by name. …
=> [PM-16194] Do not sort Favorite ciphers by last used date

libs/common/src/platform/abstractions/environment.service.ts, libs/common/src/platform/services/default-environment.service.spec.ts, libs/common/src/platform/services/default-environment.service.ts, libs/common/src/platform/services/sdk/default-sdk.service.spec.ts, libs/common/src/platform/services/sdk/default-sdk.service.ts
The main objective was to fix a bug where we depended on the wrong environment in `SdkService`. To do that we had to first convert `getEnvironment` to observable …
=> [PM-16262] Make `getEnvironment` observable and use it in SdkService

apps/browser/src/vault/popup/services/vault-popup-list-filters.service.ts, libs/common/src/vault/services/folder/folder.service.spec.ts, libs/common/src/vault/services/folder/folder.service.ts
https://bitwarden.atlassian.net/browse/PM-16197
https://github.com/user-attachments/assets/bd12edcc-ecbf-41fc-8d54-4a8ae3864180 …
=> [PM-16197] "Items with No Folder" shows as a folder to edit name and delete

apps/browser/src/vault/popup/components/vault-v2/vault-list-items-container/vault-list-items-container.component.html, apps/browser/src/vault/popup/components/vault-v2/vault-list-items-container/vault-list-items-container.component.ts
[PM-16102](https://bitwarden.atlassian.net/browse/PM-16102)
When a user hovers over the "fill" button in the extension, we want the title to display the autofill keyboard shortcut that they have configured. This will serve as a reminder that they can use the keyboard shortcut. If it's not configured, the title will display what it currently displays, which is the name of the cipher. The aria label will remain as the cipher name even if a keyboard shortcut is configured.
| Without configured shortcut | With configured shortcut |
| ![Screenshot 2024-12-20 at 2 13 24 PM](https://github.com/user-attachments/assets/075d3e07-0093-4fb0-8a88-08f3775b00df) |  ![Screenshot 2024-12-20 at 2 13 36 PM](https://github.com/user-attachments/assets/d55437df-527b-4394-a405-dda390faf69b) …
=> [PM-16102] Display autofill shortcut on Fill button hover

apps/browser/src/_locales/en/messages.json, apps/browser/src/autofill/popup/settings/autofill.component.html, apps/browser/src/autofill/popup/settings/autofill.component.ts, apps/browser/src/vault/popup/components/vault-v2/autofill-vault-list-items/autofill-vault-list-items.component.html, apps/browser/src/vault/popup/components/vault-v2/autofill-vault-list-items/autofill-vault-list-items.component.ts, apps/browser/src/vault/popup/components/vault-v2/item-more-options/item-more-options.component.html, apps/browser/src/vault/popup/components/vault-v2/item-more-options/item-more-options.component.ts, apps/browser/src/vault/popup/components/vault-v2/vault-list-items-container/vault-list-items-container.component.html, apps/browser/src/vault/popup/components/vault-v2/vault-list-items-container/vault-list-items-container.component.ts, libs/common/src/vault/abstractions/vault-settings/vault-settings.service.ts, libs/common/src/vault/services/key-state/vault-settings.state.ts, libs/common/src/vault/services/vault-settings/vault-settings.service.ts
https://bitwarden.atlassian.net/browse/PM-16428
- Add an option/setting for the primary action of autofill suggestions on the Vault view to perform an "Autofill" operation instead of the default "View" action. 
- "View" becomes an option under the 3 dot "more options" menu.
- "Fill" button goes away.
New autofill setting
Vault view …
=> [PM-16428] Option for primary click action to autofill on Vault view

apps/browser/src/autofill/services/autofill.service.spec.ts, apps/browser/src/autofill/services/autofill.service.ts
PM-16431
Fix an issue autofilling card expiry date values when the field placeholders are uppercase
Note: this change/feature is behind the `enable-new-card-combined-expiry-autofill` feature-flag
=> [PM-16431] Bugfix - Handle expiry field placeholder values with uppercased values

apps/browser/package.json, apps/browser/src/manifest.json, apps/browser/src/manifest.v3.json, apps/cli/package.json, apps/desktop/package.json, apps/desktop/src/package-lock.json, apps/desktop/src/package.json, apps/web/package.json, package-lock.json
=> Bump version to 2025.1.0

apps/browser/src/vault/popup/components/vault-v2/add-edit/add-edit-v2.component.ts, apps/browser/src/vault/popup/components/vault-v2/view-v2/view-v2.component.spec.ts, apps/browser/src/vault/popup/components/vault-v2/view-v2/view-v2.component.ts, apps/web/src/app/vault/components/vault-item-dialog/vault-item-dialog.component.ts
https://bitwarden.atlassian.net/browse/PM-16094
Nouns in different languages are capitalized. The `.toLowerCase()` used within the header overrides the translation which takes care of language-specific capitalization.
This was initially observed when using the German extension/web-vault …
=> [PM-16094] Remove lowercasing of vault page headers titles

apps/browser/src/platform/popup/layout/popup-layout.stories.ts, libs/components/src/menu/menu-trigger-for.directive.ts, libs/components/src/stories/kitchen-sink/components/dialog-virtual-scroll-block.component.ts, libs/components/src/stories/kitchen-sink/kitchen-sink.stories.ts
[CL-524](https://bitwarden.atlassian.net/browse/CL-524)
We're seeing some frequent and noisy Chromatic diffs for stories that have no changes. 
For the kitchen sink stories, it is usually the menu component being positioned ~1px lower or higher than the previous build, or the virtual scroll story showing more or less rows of data in the screenshot. These are not actual useful diffs, so this PR is going to try to ignore the elements that are causing the diffs while keeping the stories around.
For the popup layout stories, we are still working on debugging why sometimes the snapshots include all the item info, and sometimes they don't. The Storybook live instance consistently shows all the item info as expected, so it is an issue with how the snapshots are getting taken. While we work to …
=> [CL-524] Ignore flaky elements in Chromatic tests

libs/common/src/platform/state/state-definitions.ts
[PM-16507](https://bitwarden.atlassian.net/browse/PM-16507)
When a user dismissed the new device verification notice on web, that dismissal only lasted on the one tab. Opening a new tab and logging in would should the user the notification again.
Updated the state definition to the `NEW_DEVICE_VERIFICATION_NOTICE` so the dismissal value can persist throughout new tabs. 
https://github.com/user-attachments/assets/77add635-bc8f-421c-9317-72e865956400
- …
=> [PM-16507] update new device verification notice state definition

apps/browser/src/auth/popup/extension-anon-layout-wrapper/extension-anon-layout-wrapper.component.html, apps/browser/src/auth/popup/extension-anon-layout-wrapper/extension-anon-layout-wrapper.component.ts, apps/browser/src/popup/app-routing.module.ts
[PM-16505](https://bitwarden.atlassian.net/browse/PM-16505)
Added a `hideFooter` value to the extension anon wrapper for the browser call. This will remove the excess footer element and the scroll bar that appears on page 1 of the new device verification notification in the browser.  …
=> [PM-16505] new device verification browser scroll remove

apps/browser/src/platform/browser/browser-api.ts
https://bitwarden.atlassian.net/browse/PM-16564
On https://github.com/bitwarden/clients/pull/12326 I refactored and extended a bit of special case logic for process reloads on Safari. This appears to have caused a regression, and I think it's because I didn't return from the function when Safari reloads. This makes it still call `chrome.runtime.reload()`, which makes Safari send an "install" event, which leads to our extension opening it's Getting Started page.
This commit returns after the location reload in Safari. This is tricky to test locally as the issue does not appear with sideloaded apps. I'll test it with Testflight!
- Protected …
=> fix(safari): make sure to return from bespoke reload clause

libs/vault/src/cipher-form/cipher-form.stories.ts, libs/vault/src/cipher-form/components/attachments/delete-attachment/delete-attachment.component.spec.ts, libs/vault/src/cipher-form/components/attachments/delete-attachment/delete-attachment.component.ts, libs/vault/src/components/copy-cipher-field.directive.ts, libs/vault/src/components/org-icon.directive.ts, libs/vault/src/components/password-reprompt.component.ts, libs/vault/src/services/copy-cipher-field.service.spec.ts, libs/vault/src/services/copy-cipher-field.service.ts, libs/vault/src/services/new-device-verification-notice.service.ts
Another round of cleaning up some of the strict types in `libs/vault`
- Added `!` to required inputs as stated in the [decision document](https://contributing.bitwarden.com/architecture/adr/typescript-strict#use--on-required-input-parameters)
- Added `!` within the `CipherForm` stories, these are a constant object for the stories so they're always defined.
- Used an empty string for toast `title` to match the needed type
- Maybe this should be made optional? 
- Used default values or guards where needed/made sense. …
=> Vault Strict Typing cleanup

libs/components/src/item/item.component.ts, libs/tools/send/send-ui/src/send-list-items-container/send-list-items-container.component.html
[PM-16675](https://bitwarden.atlassian.net/browse/PM-16675)
On the Send page, items were rendering with individual scrollbars. This was due to a misplaced padding override on the send items causing it to be shorter than expected, and a previous change to increase the click area of item action buttons causing the buttons to overflow the short item container. This PR fixes the send item padding and hides overflow on items.
Before:
https://github.com/user-attachments/assets/568848b5-5855-42fe-9e8a-b4d16e302480
After:
https://github.com/user-attachments/assets/819f41cb-52d7-4ab5-9a86-0c261da5d47b …
=> [PM-16675] Prevent scrollbar from appearing on each send item

apps/browser/src/vault/popup/components/vault-v2/vault-search/vault-v2-search.component.html, libs/components/src/search/search.component.html, libs/components/src/search/search.component.ts
https://bitwarden.atlassian.net/browse/PM-16680
- Add property to the search component to control the autocomplete attribute
- Turn off autocomplete for the search component in browser client.
=> [PM-16680] Turn off autocomplete for browser search input

apps/web/src/app/admin-console/organizations/manage/events.component.ts
https://bitwarden.atlassian.net/browse/PM-13737
> When a F4E sponsorship sync happens, an event is logged in the corresponding Cloud organization, but the installation ID is not included in that event log
The issue occurred because the `getUserName` method was expected to return an object, but it returned a string when handling the installation ID.
- …
=> [PM-13737] Fix installation ID missing in events by returning an object with the 'name' property instead of a string

libs/vault/src/cipher-view/card-details/card-details-view.component.html
https://bitwarden.atlassian.net/browse/PM-16265
Fixes https://github.com/bitwarden/clients/issues/12505
While migrating the credit card view, the formatting for credit card numbers was missed. This pipe takes care of different credit card spacing patterns based on the brand …
=> [PM-16265] Add missing credit card number pipe

libs/vault/src/components/new-device-verification-notice/new-device-verification-notice-page-one.component.html, libs/vault/src/components/new-device-verification-notice/new-device-verification-notice-page-one.component.ts
[PM-16696](https://bitwarden.atlassian.net/browse/PM-16696)
add learn more link to new device verification notification page one
https://github.com/user-attachments/assets/ad742a5c-41e8-4e7a-9ab6-480983ba6b80 …
=> [PM-16696] New Device Verification Notice Learn More

libs/common/src/services/vault-timeout/vault-timeout.service.ts
https://bitwarden.atlassian.net/browse/PM-16685
To restore locking functionality to the clients affected by the issue (web, browser, and CLI - not desktop).
The issue was caused the new `await this.folderService.clearDecryptedFolderState(userId);` using the optional `userId` instead of the `lockingUserId`.
Web broken:
https://github.com/user-attachments/assets/a42b4649-f567-4346-83e2-58dff50fc629
Web fixed:
https://github.com/user-attachments/assets/dbe9425e-80bf-4a63-9f76-c2329b7ea632 …
=> PM-16685 - Fix locking

libs/components/src/button/button.stories.ts, libs/components/src/dialog/dialog/dialog.stories.ts, libs/components/src/dialog/simple-dialog/simple-configurable-dialog/simple-configurable-dialog.service.stories.ts, libs/components/src/form-field/bit-validators.stories.ts, libs/components/src/form-field/form-field.stories.ts, libs/components/src/search/search.stories.ts, libs/components/src/toast/toast.stories.ts, libs/components/tsconfig.json
Fixing some low hanging fruits for moving CL to strict typescript.
This primarily removes the types from `args` since TS infers them differently. We previously needed them since storybook would use `any` for args but now provides proper typings. …
=> Strict typescript for Component Library stories

libs/vault/src/components/new-device-verification-notice/new-device-verification-notice-page-one.component.html, libs/vault/src/components/new-device-verification-notice/new-device-verification-notice-page-one.component.ts
[PM-16824](https://bitwarden.atlassian.net/browse/PM-16824)
using the `<a href="link">` was opening the learn more in a pop up from desktop. 
updating the learn more navigate in new device verification page one component  to use the platformso web, browser, and desktop all open the help page on a new page in the clients browser window. 
https://github.com/user-attachments/assets/ee2dc0e8-1882-4655-9f8d-52a8b333085f …
=> [PM-16824] update new device verification notice page for desktop learn more link

apps/desktop/src/platform/main/main-ssh-agent.service.ts
https://bitwarden.atlassian.net/browse/PM-16836
Keygen and import were accidentally also in the featureflag for the ssh-agent, since it is (temporarily until moved to the sdk) within the ssh-agent module in desktop-native.
- ❓ …
=> [PM-16836] Fix ssh generation and import not being available when agent featureflag is disabled

apps/desktop/src/main.ts, apps/desktop/src/platform/main/main-ssh-agent.service.ts, apps/desktop/src/platform/preload.ts, apps/desktop/src/platform/services/ssh-agent.service.ts
https://bitwarden.atlassian.net/browse/PM-16837
The ssh-agent only checked the feature-flag once during startup. This changes it to listen to an observable, and enable it when on an account for which the flag is available. From then on it stays active until the application is closed. …
=> [PM-16837] Fix agent only loading when featureflag is on during startup

apps/web/src/app/vault/individual-vault/vault.component.ts, libs/vault/src/cipher-form/components/item-details/item-details-section.component.ts
https://bitwarden.atlassian.net/browse/PM-14289
This PR fixes an issue where if the user goes directly to a collection and creates a new item the default owner was previously being set to the user even if the collection was part of an organization. We now attempt to get the organization from the `vaultFilterService` using the filtered `collectionId` when populating the form's initial values to be used when setting the default owner.
- Updated any …
=> [PM-14289] - vault cipher form - set default owner as organization from collection when possible

apps/desktop/resources/com.bitwarden.desktop.devel.yaml
While testing #12760, I needed to build the Flatpak on my arm64 VM and noticed the build path was different. This just adds the correct build dir for arm64. …
=> fix: account for different build output on arm

apps/browser/src/vault/popup/components/vault-v2/new-item-dropdown/new-item-dropdown-v2.component.ts, apps/web/src/app/vault/individual-vault/add-edit.component.ts
https://bitwarden.atlassian.net/browse/PM-16859
https://github.com/bitwarden/clients/pull/12176 updated buildQueryParams in new-item-dropdown-v2 to be async, which (somehow) broke item creation on browsers, resetting to login always.
Also makes code blocking ssh-key creation on web dependent on the featureflag.
https://github.com/user-attachments/assets/032d3cf0-4098-4b72-a6c9-db8cb4a4e26e …
=> [PM-16859] Fix item creation resetting to login item type on browser

libs/angular/src/vault/components/icon.component.html
https://bitwarden.atlassian.net/browse/PM-13028
This PR fixes an issue with cipher login icons being differing widths by explicitly setting the width as it is now expected that all icons are rendered in equal size.
|Before|After|
---|---
|![Screenshot 2025-01-06 at 2 51 24 PM](https://github.com/user-attachments/assets/8129f6de-367d-4acc-93e5-a7a404e08e82)|![Screenshot 2025-01-06 at 2 50 44 PM](https://github.com/user-attachments/assets/2665140a-de87-4fc4-9a10-55866d0634f3)| …
=> [PM-13028] - fixed icon width

.github/workflows/deploy-web.yml
https://github.com/bitwarden/clients/pull/12755
On the linked PR I attempted to resolve all warnings and errors raised by the
new workflow linter. I missed one instance for Slack, which is causing
errors. This one line commit updates this variable name. …
=> fix(ci): Adjust variable name missed during lint update

apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.html, apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.ts, apps/web/src/locales/en/messages.json
https://bitwarden.atlassian.net/browse/PM-13645
This PR resolves an issue where the invite member dialog in admin console was not showing the correct number or remaining seats. …
=> Fix invite member dialog remaining count

apps/web/src/app/app.component.ts, libs/common/src/enums/notification-type.enum.ts, libs/common/src/models/response/notification.response.ts, libs/common/src/services/notifications.service.ts
[PM-13764](https://bitwarden.atlassian.net/browse/PM-13764)
When the server pushes the notification message, the cached organization can be updated locally to set the "Create Organization" and "Delete Organization".
Link to server side changes: https://github.com/bitwarden/server/pull/5230
- 📝 (`:memo:`) or …
=> [PM-13764] - Update Collection Settings

libs/common/src/platform/abstractions/crypto-function.service.ts, libs/common/src/platform/models/domain/decrypt-parameters.ts, libs/common/src/platform/models/domain/symmetric-crypto-key.ts, libs/common/src/platform/services/cryptography/encrypt.service.implementation.ts, libs/common/src/platform/services/web-crypto-function.service.spec.ts, libs/common/src/platform/services/web-crypto-function.service.ts, libs/node/src/services/node-crypto-function.service.spec.ts, libs/node/src/services/node-crypto-function.service.ts
https://bitwarden.atlassian.net/browse/PM-16831
This PR makes crypto function services TS-strict compliant and improves the type safety of AES decryption …
=> [PM-16831] TS Strict crypto function service

apps/browser/src/autofill/content/notification-bar.ts, apps/browser/src/autofill/types/index.ts
PM-16924
Fix bad/restricted import paths
- 🎨 (`:art:`) …
=> [PM-16924] Fix bad imports

apps/browser/src/key-management/lock/services/extension-lock-component.service.spec.ts, apps/browser/src/key-management/lock/services/extension-lock-component.service.ts
https://bitwarden.atlassian.net/browse/PM-16895
The biometrics service did not take into account the local settings from the biometricsstateservice to return the "NotEnabledLocally" status, and returned "desktopDisconnected" instead. The former should take priority so that the UI for biometrics gets hidden when the setting is disabled.
https://github.com/user-attachments/assets/0d3eb994-24f7-4b32-9c1d-a5be91a77cc9 …
=> [PM-16895] Fix biometric prompt showing up in browser while disabled

apps/browser/src/auth/popup/settings/account-security.component.ts
https://bitwarden.atlassian.net/browse/PM-16910
The refactor of biometrics made the settings dynamically enable based on the status of the biometrics service. However, this did not take into account permissions being granted. It failed to connect because no permission was granted, and thus disabled the settings button. But clicking the settings button first prompts for permission, making it impossible to enable biometrics. This makes it so the button is always enabled before permissions are granted.
Note that this screen recording also includes other changes to fix biometrics, which must be tested together to exhibit this behavior.  These changes are:
https://github.com/bitwarden/clients/pull/12797
[bitwarden.atlassian.net/browse/PM-16914](https://bitwarden.atlassian.net/browse/PM-16914) …
=> [PM-16910] Fix biometrics being disabled before permission is granted

apps/browser/src/platform/services/browser-script-injector.service.spec.ts, apps/browser/src/tools/background/fileless-importer.background.spec.ts, libs/common/src/autofill/services/domain-settings.service.spec.ts, libs/common/src/autofill/services/domain-settings.service.ts
PM-16956
Fix issue where state evaluation would fail, preventing injections from occurring …
=> [PM-16956] Bugfix - Fix broken blockedInteractionsUris state construction

bitwarden_license/bit-web/src/app/admin-console/providers/setup/setup.component.ts
https://bitwarden.atlassian.net/browse/PM-16682
When setting up a new provider, the tax information is not being saved, neither is the error message shown as would be expected if the tax id is invalid.
This pull request allows returning localized error messages when entering tax information for setting up providers,
Not blocking, but is combined with: https://github.com/bitwarden/server/pull/5211 …
=> [PM-16682] Return a localized error message for entering tax information

libs/importer/src/components/import.component.html
https://bitwarden.atlassian.net/browse/PM-16868
When the Nordpass was selected on the import page, no instructions for th csv export were shown. This PR adds instructions when the Nordpass csv format is selected. I must have missed this, when I implemented the importer with https://github.com/bitwarden/jslib/pull/360 …
=> [PM-16868] Add csv export instructions for Nordpass

apps/web/src/app/auth/settings/security/device-management.component.html, apps/web/src/app/auth/settings/security/device-management.component.ts, apps/web/src/locales/en/messages.json, libs/angular/src/services/jslib-services.module.ts, libs/auth/src/angular/login-approval/login-approval.component.html, libs/auth/src/angular/login-approval/login-approval.component.spec.ts, libs/auth/src/angular/login-approval/login-approval.component.ts, libs/common/src/auth/abstractions/devices/responses/device.response.ts
https://bitwarden.atlassian.net/browse/PM-16947
To add the ability to approve or deny pending auth requests for devices on the new device management screen
Normal Login with device:
https://github.com/user-attachments/assets/d178784c-2747-4c78-bac7-9359cd5ebcd3
TDE Login with device:
https://github.com/user-attachments/assets/6ca3ba72-cd4e-499e-8e1f-1555209a3c7f …
=> Auth/PM-16947 - Web - Device Management - Add Manage Auth Requests support

libs/angular/src/auth/components/two-factor.component.ts
https://bitwarden.atlassian.net/browse/PM-16988
Fixes the error prompt for the old two-fa component, to be the same as the new component which shows an i18n message. …
=> Make old two-factor component show i18n webauthn error

libs/components/src/stories/kitchen-sink/components/dialog-virtual-scroll-block.component.ts, libs/components/src/stories/kitchen-sink/kitchen-sink.stories.ts
[CL-524](https://bitwarden.atlassian.net/browse/CL-524)
The kitchen sink virtual scroll story is still causing unwanted diffs because the previous method used to ignore changes (`data-chromatic=ignore`) does not ignore height changes, which is exactly what's causing the diffs. Skipping the whole test for now until we can figure out why the row count is inconsistent. …
=> [CL-524] Ignore kitchen sink virtual scroll story

apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.ts, apps/web/src/app/admin-console/organizations/members/members.component.ts, bitwarden_license/bit-web/src/app/tools/reports/member-access-report/member-access-report.component.ts
https://bitwarden.atlassian.net/browse/PM-13645
This PR fixes the seat count to include members that are in invited and accepted statuses. …
=> [PM-13645] fix seat count to include invited and accepted members

libs/auth/src/angular/login-decryption-options/login-decryption-options.component.ts
https://bitwarden.atlassian.net/browse/PM-17047
Bugfix: Switches an expression to an assignment. This would only effect the create new user flows, so I've added videos of all of those below.
https://github.com/user-attachments/assets/6a4ac6a9-29c8-46f6-940d-e6b18ac06305
https://github.com/user-attachments/assets/aef0c8ce-07ae-4301-a7c6-53fae578706c
https://github.com/user-attachments/assets/73990fa0-4489-4cb3-94c4-326cd76edecf …
=> [PM-17047] Bugfix: Change clientType expression to assignment

libs/tools/generator/components/src/credential-generator-history-dialog.component.html, libs/tools/generator/components/src/credential-generator-history-dialog.component.ts
https://bitwarden.atlassian.net/browse/PM-16906
`bit-dialog` overlaps the electron windows' dragable “title” area. While waiting for a fix from UIF, this should be mitigated by adding a “close” button to the password history dialog box.
Empty:
Lots of entries: …
=> [PM-16906] add close button to password history dialog

libs/common/src/platform/state/implementations/default-derived-state.provider.ts, libs/common/src/platform/state/implementations/default-derived-state.spec.ts
https://bitwarden.atlassian.net/browse/PM-15914
When switching accounts derived state was still fetching from a cache for the
previous account, leading to UI elements being displayed with data from an
inactive account's cache. The DerivedStateProvider now uses a WeakMap to
maintain separate caches for each user's state Observable.
- Modifies DefaultDerivedStateProvider to use WeakMap for caching
- Each user's state Observable gets its own definition cache
- Added test to verify correct behavior during account switching
- Automatically cleans up inactive user caches on parentState change …
=> fix: use `WeakMap` in `DerivedStateProvider` to separate user state caches

apps/browser/src/key-management/biometrics/background-browser-biometrics.service.ts, apps/browser/src/popup/app.component.ts, tsconfig.eslint.json
https://bitwarden.atlassian.net/browse/PM-17042
This is due to missing await before process reload, triggered by lock, effectively disabling the biometrics auto prompt on safari.
This should be detected by eslint, but due to misconfiguration, nothing was reported. Also fixed two other missing awaits on biometrics unlock. …
=> [PM-17042] Biometrics auto prompt popup does not show up on safari

libs/common/src/tools/extension/runtime-extension-registry.spec.ts
n/a
Fix broken unit tests merged in e79dab868956a21e1886f38ae8d1dbc05246ead9. The tests are broken because the `toBeTrue()` checker was removed. …
=> replace toBeTrue() with toBe(true)

apps/desktop/desktop_native/core/src/password/windows.rs
This function has defined a generic lifetime parameter that is never used, so it can safely be removed.
This was failing a lint, probably a rust update? It doesn't appear in other action runs, which seems a bit strange though.
https://github.com/bitwarden/clients/actions/runs/12791798693/job/35660738448
- 📝 …
=> Remove unused lifetime

.github/renovate.json
https://bitwarden.atlassian.net/browse/PM-14640
As we have started to share ownership of our build pipelines between BRE and Platform, BRE no longer owns all of the `github-action`-managed dependencies.  The current `renovate.json` results in misleading PR titles like https://github.com/bitwarden/clients/pull/12706/.
This PR does the following:
- Removes the addition of the `BRE` prefix for all `github-action` dependencies.
- Removes patch updates from the scope of PR creation.
❓ What will upcoming PRs look like?
- Patch updates will be ignored
- Minor updates will be grouped into a single PR, with no team-specific prefix, with the PR reviewer(s) determined by who owns the workflow files in which the dependencies are used (e.g. Platform would need to review build/lint/test workflows, BRE …
=> Adjust handling of GH action dependencies for CI/CD partnership

libs/key-management/src/angular/lock/components/lock.component.ts
https://bitwarden.atlassian.net/browse/PM-17088
When a new user is selected through account switching, the new lock component will reinitialize with that user. If that user is unlocked, the app will quickly redirect to vault, but that reinitialization was still running. This meant that things like bio prompts would show before switching to vault.
- 👍 …
=> [PM-17088] Prevent lock component init when switching to unlocked account

apps/desktop/package.json
https://bitwarden.atlassian.net/browse/PM-17137
Snapcraft requires special packing using the `snapcraft` cli instead of directly creating the image. The latter works for local snap installations but not for snapcraft.
This is a change to the `pack:lin` step that was originally introduced in https://github.com/bitwarden/clients/pull/12187.
- 👍 …
=> Attempt to fix snap build

.github/workflows/staged-rollout-desktop.yml
[BRE-560](https://bitwarden.atlassian.net/browse/BRE-560)
Simple update to show the rollout percentage input in the run-name …
=> [BRE-560] Display rollout percentage in run name

.github/workflows/build-browser.yml, apps/browser/package.json
https://bitwarden.atlassian.net/browse/PM-8319
https://bitwarden.atlassian.net/browse/PM-17141
Reverts part of https://github.com/bitwarden/clients/pull/12674.
We have encountered issues with the Opera Mv3 build and need to revert to Mv2 so they can be addressed.
This changes the `build-browser` workflow to produce the `dist-opera` artifact as before, along with the `DO-NOT-USE` Mv3 artifact.  It then changes the `build:opera` script to build the Mv2 version, so that version will be used in the workflow.
Note that the workflows run on this branch are those in `main` and therefore are building the Mv3 artifact still.
We will address the underlying issue and test the functionality in the Mv3 build locally before attempting the Mv3 release again.
- All …
=> Revert Opera to Mv2 build

apps/browser/src/vault/popup/components/vault-v2/view-v2/view-v2.component.ts, apps/browser/src/vault/popup/settings/trash-list-items-container/trash-list-items-container.component.html, libs/vault/src/cipher-view/cipher-view.component.ts
https://bitwarden.atlassian.net/browse/PM-15572
This PR removes the ability to restore deleted ciphers for users with the "edit, except passwords" permission. …
=> [PM-15572] - don't allow restore for 'edit except password' permission

apps/cli/src/commands/edit.command.ts, libs/common/src/vault/abstractions/folder/folder-api.service.abstraction.ts, libs/common/src/vault/services/folder/folder-api.service.ts
https://bitwarden.atlassian.net/browse/PM-8634
This PR updates the folder `save` function to return the updated folder to allow the `editFolder` to return the updated folder to the client.
- 🤔 …
=> [PM-8634] - CLI - return updated folder when saving a folder

libs/vault/src/cipher-form/components/custom-fields/custom-fields.component.ts, libs/vault/src/cipher-view/custom-fields/custom-fields-v2.component.html, libs/vault/src/cipher-view/custom-fields/custom-fields-v2.component.ts
https://bitwarden.atlassian.net/browse/PM-15938
This PR removes the visibility toggle and copy buttons from hidden fields in the view modal as well as disables the input in the edit modal for `except passwords` permissions.
- ❓ …
=> [PM-15938] - don't allow 'except password' permissions to view or copy hidden fields

.github/workflows/publish-desktop.yml
[BRE-563](https://bitwarden.atlassian.net/browse/BRE-563)
Reverting out ability to turn off electron publishing, which publishes all artifacts and is needed for other installers to function properly.
- 🤔 …
=> [BRE-563] Reverting out electron_publish option.  Needs to always happen

libs/vault/src/cipher-view/custom-fields/custom-fields-v2.component.html
https://github.com/bitwarden/clients/pull/12899 and https://github.com/bitwarden/clients/pull/12161 both added a structural element to the same element--bad merge.  …
=> fix main - remove duplicate ngIf

apps/web/src/locales/en/messages.json, bitwarden_license/bit-web/src/app/billing/providers/clients/create-client-dialog.component.html, bitwarden_license/bit-web/src/app/billing/providers/clients/create-client-dialog.component.ts
https://bitwarden.atlassian.net/browse/PM-16664
- The price for Enterprise shows as $72/month per member. It should show as $6/month per member.
- Applied TypeScript strict rules.
- Minimum seats now defaults to '1' which is the lowest value for the given validation rules. …
=> [PM-16664] Incorrect price value in "add new organization" modal

apps/web/src/app/vault/individual-vault/vault.component.ts
https://bitwarden.atlassian.net/browse/PM-14952
This PR fixes an issue where restoring items in the individual vault trash would result in an error. This was due to the fact the `restore` function was being called from another component and `this` wasn't bound to it. Changing to an arrow function accomplishes this. …
=> [PM-14952] - restoring item in individual vault results in error

apps/browser/src/autofill/services/collect-autofill-content.service.spec.ts, apps/browser/src/autofill/services/collect-autofill-content.service.ts, apps/browser/src/autofill/utils/index.ts
https://bitwarden.atlassian.net/browse/PM-17393
Resolve case breakage from https://github.com/bitwarden/clients/pull/12695
=> [PM-17393] Bugfix - Resolve breakage of delayed input appearance

apps/browser/src/auth/popup/two-factor.component.ts, apps/browser/src/auth/popup/utils/auth-popout-window.spec.ts, apps/browser/src/auth/popup/utils/auth-popout-window.ts, apps/browser/src/background/runtime.background.ts
https://bitwarden.atlassian.net/browse/PM-8113
As part of the 2FA UI refresh work, I discovered the need to update and enhance the Auth owned `AuthPopoutWindows.ts` to add additional clarity + add support for closing the SSO auth result popout. 
n/a. …
=> Auth/PM-8113 - Extension - AuthPopoutWindows - Add new method + refactor names

.github/CODEOWNERS
We regularly have to modify all tsconfig files together and having platform own them will make those PRs easier. This also adds another safe guard against teams making accidentally mistakes like cyclic dependencies. …
=> Change tsconfig to be owned by platform

apps/browser/src/vault/popup/components/vault-v2/add-edit/add-edit-v2.component.spec.ts, apps/browser/src/vault/popup/components/vault-v2/add-edit/add-edit-v2.component.ts
[PM-17443](https://bitwarden.atlassian.net/browse/PM-17443)
When the `PersistPopupView` flag is active the root route has a [popupRouterCacheGuard](https://github.com/bitwarden/clients/blob/5d014fb7d3fad156c61bfa5c6c859b6633b011d4/apps/browser/src/platform/popup/view-cache/popup-router-cache.service.ts#L130-L136) that will navigate to the last route.
This causes the edit view to stay in view when deleting a cipher. Navigating to `/tabs/vault` directly fixes the issue as the guard is avoided.
I also fixed strict-typings in the test file while I was here.
|Before|After|
|-|-|
|<video src="https://github.com/user-attachments/assets/dfe7f464-3308-4cb3-9841-02668d95beda" />|<video src="https://github.com/user-attachments/assets/737cfb6d-fc87-45e5-8f42-2755e2cdff6c" />| …
=> [PM-17443] Navigation After Deletion

apps/web/src/app/admin-console/organizations/shared/components/access-selector/access-selector.component.spec.ts, apps/web/src/app/admin-console/organizations/shared/components/access-selector/access-selector.component.ts, apps/web/src/app/admin-console/organizations/shared/components/integrations/integration-card/integration-card.component.spec.ts, apps/web/src/app/admin-console/organizations/shared/components/integrations/integration-grid/integration-grid.component.spec.ts, apps/web/src/app/auth/core/services/login/web-login-component.service.spec.ts, apps/web/src/app/auth/settings/webauthn-login-settings/enable-encryption-dialog/enable-encryption-dialog.component.ts, apps/web/src/app/auth/two-factor-auth-duo.component.ts, apps/web/src/app/auth/two-factor-auth.component.ts, apps/web/src/app/billing/organizations/organization-billing.module.ts, apps/web/src/app/key-management/key-rotation/request/update-key.request.ts, apps/web/src/app/layouts/product-switcher/navigation-switcher/navigation-switcher.component.spec.ts, apps/web/src/app/layouts/product-switcher/navigation-switcher/navigation-switcher.stories.ts, apps/web/src/app/layouts/product-switcher/product-switcher.component.ts, apps/web/src/app/layouts/product-switcher/product-switcher.stories.ts, apps/web/src/app/oss-routing.module.ts, apps/web/src/app/secrets-manager/models/requests/request-sm-access.request.ts, apps/web/src/app/tools/import/import-collection-admin.service.ts, apps/web/src/app/vault/individual-vault/vault-filter/services/abstractions/vault-filter.service.ts, apps/web/src/app/vault/individual-vault/vault-filter/shared/models/vault-filter.type.ts, apps/web/src/app/vault/individual-vault/view.component.ts, apps/web/src/app/vault/org-vault/services/admin-console-cipher-form-config.service.ts, apps/web/src/app/vault/services/web-view-password-history.service.ts
Found more bad imports.
- 🎨 (`:art:`) for suggestions / …
=> Ignore more bad imports

apps/browser/src/vault/popup/services/vault-popup-autofill.service.spec.ts, apps/browser/src/vault/popup/services/vault-popup-autofill.service.ts
https://bitwarden.atlassian.net/browse/PM-15943
This PR uses `requestAnimationFrame` instead of an arbitrary time value when closing the popout. This has the benefit of ensuring the copy operation completes and avoids the animation flicker noted in the ticket. …
=> [PM-15943] - When filling a password, the extension flickers

apps/web/src/app/components/environment-selector/environment-selector.component.html, apps/web/src/app/layouts/frontend-layout.component.html, apps/web/src/app/layouts/org-switcher/org-switcher.component.html, apps/web/src/app/settings/domain-rules.component.html, bitwarden_license/bit-web/src/app/secrets-manager/projects/project/project-secrets.component.html, bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-import.component.html
https://bitwarden.atlassian.net/browse/PM-17162
Migrates the following components to not use bootstrap.
- apps/web/src/app/components/environment-selector/environment-selector.component.html
- apps/web/src/app/layouts/frontend-layout.component.html
- apps/web/src/app/layouts/org-switcher/org-switcher.component.html
- apps/web/src/app/settings/domain-rules.component.html
- bitwarden_license/bit-web/src/app/secrets-manager/projects/project/project-secrets.component.html
- bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-import.component.html
Styling should be identical or only have minor differences.
Two components experienced minor visual changes. Frontend footer is more aligned with the new annon-layout, environment switcher has some weird padding removed and more …
=> [PM-17162] Migrate shared components

apps/web/src/locales/en/messages.json
https://bitwarden.atlassian.net/browse/PM-17451
Add missing keys to en/messages.json so they are displayed on the new SSH-key add/edit screen
| ![image](https://github.com/user-attachments/assets/d2e2f769-2e98-47a0-b219-54f8e8b7215f) | ![image](https://github.com/user-attachments/assets/bc5a9703-d614-4e03-b161-b4f5f144c988) | …
=> [PM-17451] Add missing keys for ssh fields to web/en/messages.json

apps/browser/src/services/families-policy.service.ts, apps/web/src/app/billing/services/free-families-policy.service.ts, apps/web/src/app/billing/settings/sponsored-families.component.ts, apps/web/src/app/billing/settings/sponsoring-org-row.component.ts, libs/angular/src/tools/send/add-edit.component.ts, libs/common/src/admin-console/abstractions/policy/policy.service.abstraction.ts, libs/common/src/admin-console/services/policy/policy.service.spec.ts, libs/common/src/admin-console/services/policy/policy.service.ts, libs/tools/send/send-ui/src/send-form/components/options/send-options.component.ts
https://bitwarden.atlassian.net/browse/PM-17465
Fixes an issue where the PolicyService.getAll$ accepts an optional userId param that is passed to the OrganizationService call that requires a userId, resulting in cases where we pass undefined to the OrganizationService call. …
=> [PM-17465] refactor PolicyService.getAll$ to make userId not optional

apps/web/src/app/auth/settings/account/change-avatar-dialog.component.html
[PM-258](https://bitwarden.atlassian.net/browse/PM-258)
This PR adds the `text-muted` class to the custom avatar color picker, so that the contrast is better when viewing in dark mode. Effects both light and dark mode.
Before:
After:
- ❓ …
=> [PM-258] Add text-muted to custom avatar picker

libs/common/src/state-migrations/migrate.ts, libs/common/src/state-migrations/migrations/69-migrate-incorrect-folder-key.spec.ts, libs/common/src/state-migrations/migrations/69-migrate-incorrect-folder-key.ts, libs/common/src/vault/services/key-state/folder.state.ts
[PM-17541](https://bitwarden.atlassian.net/browse/PM-17541)
Update the `FOLDER_ENCRYPTED_FOLDERS` key definition key back to `folders` and write a migration script to revert any users that may have updated to the `folder` key.
- ❓ …
=> [PM-17541] Fix folder service key definition

libs/angular/src/auth/guards/unauth.guard.spec.ts, libs/angular/src/auth/guards/unauth.guard.ts, libs/common/src/auth/abstractions/device-trust.service.abstraction.ts, libs/common/src/auth/services/device-trust.service.implementation.ts, libs/common/src/auth/services/device-trust.service.spec.ts
https://bitwarden.atlassian.net/browse/PM-17197
To make the `unauthGuard` aware of the Trusted Device Encryption lock state so that, in specific situations where you refresh on an unauthenticated screen in the sidebar of Firefox or other browsers with sidebars after completing authentication in the extension popout, the sidebar can refresh and take you to the login initiated screen appropriately. Previously, the `unauthGuard` would send the user to the lock screen and the `lockGuard` would deny navigation so the user would be left on a blank screen in the sidebar. 
https://github.com/user-attachments/assets/aa4c0511-cb1e-482f-8fec-56bd7d89d348 …
=> Auth/PM-17197 - UnauthGuard Trusted Devices Lock State Refactor

libs/auth/src/angular/registration/registration-finish/registration-finish.component.ts
https://bitwarden.atlassian.net/browse/PM-17466
To resolve issues with the extension vault load where the vault expects a sync to have occurred already after account creation when email verification is disabled by the server flag, we are adding a call to the `loginSuccessHandlerService` which executes a full sync after a successful login. 
Extension:
https://github.com/user-attachments/assets/d881461d-6ede-49b4-9362-be0b57260538
Desktop:
https://github.com/user-attachments/assets/c6dde222-b43c-4cea-a79a-08ae58a66510
Web:
https://github.com/user-attachments/assets/13231ebd-2591-42fb-ab90-2431525ff33f …
=> Auth/PM-17466 - RegistrationFinishComp Bugfix - Add call to loginSuccessHandlerService after successful login

apps/browser/src/vault/popup/services/vault-popup-autofill.service.spec.ts, apps/browser/src/vault/popup/services/vault-popup-autofill.service.ts
https://bitwarden.atlassian.net/browse/PM-15943
This PR reverts the [previous PR](https://github.com/bitwarden/clients/pull/12900) as it didn't satisfy QA and they want the changes reverted until the entire fix is in place.
- ❓ …
=> [PM-15943] - Revert When filling a password, the extension flickers

libs/components/src/tabs/shared/tab-list-item.directive.ts
https://bitwarden.atlassian.net/browse/CL-276
Update the tab component styles to match the new Design System styles:
- Update top border radius for active and focus states 
- Update focus ring to primary-600
- Remove active state text underline
- Update disabled styles
**Before:**
**After:** 
- 📝 (`:memo:`) …
=> CL-276 - Update tab styles

libs/common/src/vault/icon/build-cipher-icon.spec.ts
I original wrote these tests with the intent of updating this logic to use the `URL` class instead of string parsing. However, these tests reveiled that behavior is actually quite different from typical URL handling.
I chose to abandon the idea of using `new URL`, but that doesn't mean we need to lose out on the added coverage for login uri parsing.  …
=> Test existing Login URI icon retrieval behavior

libs/common/src/platform/sync/core-sync.service.ts, libs/common/src/platform/sync/default-sync.service.ts
https://bitwarden.atlassian.net/browse/PM-17610
This PR fixes the error that gets thrown by the getUserId custom rxjs operator in instances where we rely on null/undefined being unhandled.
- 🤔 …
=> [PM-17610] Remove getUserId operator

apps/web/src/app/vault/components/vault-item-dialog/vault-item-dialog.component.ts, libs/vault/src/cipher-form/index.ts
N/A
https://github.com/bitwarden/clients/pull/11758 had a deep import into the vault library which breaks linting. I added the `CipherFormComponent` to the barrel file and fixed the import here
N/A
=> Fix deep import for `CipherFormComponent`

bitwarden_license/bit-web/src/app/tools/access-intelligence/critical-applications.component.html, bitwarden_license/bit-web/src/app/tools/access-intelligence/critical-applications.component.ts, libs/common/src/enums/feature-flag.enum.ts
https://bitwarden.atlassian.net/browse/PM-14562
Adding the feature flag for risk insights notifications to the client and displaying the "request password change" button only when the feature is enabled.  …
=> [PM-14562] Risk insights notification feature flag

apps/desktop/package.json, apps/desktop/src/package-lock.json, apps/desktop/src/package.json, package-lock.json
We currently have the desktop version in `main` as `2025.1.8`, which is incorrect.  The latest desktop [release](https://github.com/bitwarden/clients/releases/tag/desktop-v2025.1.3) was `2025.1.3`, which means `main` should be `2025.1.4` after bumping the version in preparation for the next release.
What has happened is that:
1. We have an Automated Desktop Version Bump workflow [here](https://github.com/bitwarden/clients/actions/workflows/version-auto-bump.yml) that bumps the version, and it incorrectly bumped the version last week.
2. We attempted to correct this with https://github.com/bitwarden/clients/commit/01803eb29cca9283f3ba967dfca960c74fd1db6d, but it didn't update all the places the version is kept, and so the subsequent updates kept incrementing it incorrectly.
To compare …
=> Fix desktop version to be 2025.1.4

apps/browser/src/background/main.background.ts, libs/angular/src/services/jslib-services.module.ts, libs/common/src/platform/notifications/internal/default-notifications.service.spec.ts, libs/common/src/platform/notifications/internal/default-notifications.service.ts
#11346 re-ordered the constructor parameters of the default notification service causing a mismatch with the noop notification service. This re-orders them to be the same to prevent the Web application from failing to start with the noop service. …
=> Fix noop notification service registration

libs/vault/src/cipher-form/components/cipher-form.component.ts
[PM-17713](https://bitwarden.atlassian.net/browse/PM-17713)
The various child forms call `cipherFormContainer.getInitialCipherView()` sequentially as they're initialized. However, once the first component is initialized, it ends saving a new value to the cache which is then read by the subsequent child form components. 
This is fine when there is a value in the cache; however, when creating a new cipher without a cache this causes subsequent child forms to skip their `initiNewCipher()` methods because they believe they're restoring from cache. Which, for example, caused the autofill section to not populate the first empty URL for new login ciphers. …
=> [PM-17713] Ensure cached cipher value is used only if initialized from cache

apps/web/src/app/vault/components/vault-item-dialog/vault-item-dialog.component.html, apps/web/src/app/vault/components/vault-item-dialog/vault-item-dialog.component.ts
https://bitwarden.atlassian.net/browse/PM-14952
This PR replaces the "Edit" button with a "Cancel" button while a user without edit permission is viewing an item in the trash. It also cleans up a bit of the logic in the component.
|Before|After|
---|---
|![Screenshot 2025-01-23 at 11 29 15 AM](https://github.com/user-attachments/assets/bb4412e0-7a64-4ddf-8f93-ef507bd06c7a)|![Screenshot 2025-01-23 at 11 51 35 AM](https://github.com/user-attachments/assets/0dc1cac9-62e8-4538-81e6-7e759eb50008)|
- …
=> [PM-14952] - show "close" button if user doesn't have edit permission in vault dialog trash

apps/browser/src/_locales/en/messages.json, apps/desktop/src/locales/en/messages.json, apps/desktop/src/vault/app/vault/credential-generator-dialog.component.html, apps/desktop/src/vault/app/vault/credential-generator-dialog.component.ts, apps/web/src/locales/en/messages.json, libs/vault/src/cipher-form/components/cipher-generator/cipher-form-generator.component.html, libs/vault/src/cipher-form/components/cipher-generator/cipher-form-generator.component.ts
https://bitwarden.atlassian.net/browse/PM-17688
This PR fixes an issue with missing i18n keys for the username generator dialog. It also adds some logic for disabling the action button if the user hasn't selected an algorithm and/or generated a value.
https://github.com/user-attachments/assets/a79a8e6a-aba5-4bf1-82f1-9c47274571e9 …
=> [PM-17688] - generator dialog - add missing button label i18n keys. fix logic for disabling button

libs/angular/src/vault/guards/new-device-verification-notice.guard.spec.ts, libs/angular/src/vault/guards/new-device-verification-notice.guard.ts
[PM-17745](https://bitwarden.atlassian.net/browse/PM-17745)
Add `try/catch` to the `NewDeviceVerificationNoticeGuard` to prevent locking users out of the client when there is a network error or is otherwise unable to retrieve the user profile to determine eligibility for showing the new device notification.
- …
=> [PM-17745] Catch network errors in new device notification guard

apps/web/src/app/admin-console/organizations/settings/account.component.ts, libs/common/src/enums/feature-flag.enum.ts
https://bitwarden.atlassian.net/browse/PM-17763
> Fix feature flag casing and move to appropriate feature flag grouping …
=> [PM-17763] Update LimitItemDeletion feature flag

libs/components/src/item/item-content.component.html, libs/components/src/item/item-content.component.ts, libs/components/src/item/item.mdx, libs/components/src/item/item.stories.ts
[CL-569](https://bitwarden.atlassian.net/browse/CL-569)
This PR adds the option to allow bit item content to wrap instead of truncate.
Check Storybook action for new text overflow wrap story. 
- 🤔 …
=> [CL-569] Optionally allow item content to wrap

apps/web/src/app/billing/organizations/change-plan-dialog.component.ts
https://bitwarden.atlassian.net/browse/PM-17132
When rate limiter is triggered when previewing an organization, an empty error message is being shown. This is due to the fact no translation exists for the rate limiter error message.
https://github.com/user-attachments/assets/88a35a41-a7c9-4e09-8fee-deb36ee4b5f0 …
=> [PM-17132] Fix rate limiter error message when upgrading organization

libs/auth/src/angular/user-verification/user-verification-form-input.component.html
https://bitwarden.atlassian.net/browse/PM-17181?atlOrigin=eyJpIjoiNDg2OTkyMzBjMjdjNDlhOWI5ZmY5NmFkOGE1OTVjOTgiLCJwIjoiaiJ9
Remove Bootstrap styles from `UserVerificationFormInputComponent`.
- 🤔 …
=> [PM-17181] Remove Bootstrap style from UserVerificationFormInputComponent

apps/browser/src/autofill/services/autofill-overlay-content.service.ts, apps/browser/src/autofill/services/collect-autofill-content.service.spec.ts, apps/browser/src/autofill/services/collect-autofill-content.service.ts, apps/browser/src/autofill/services/inline-menu-field-qualification.service.ts
[PM-17969](https://bitwarden.atlassian.net/browse/PM-17969)
Notification bar does not come up when creating an account demo.yubico.com/playground …
=> [PM-17969] Bugfix - Notification bar does not come up when creating an account demo.yubico.com/playground

apps/browser/src/autofill/services/autofill.service.spec.ts, apps/browser/src/autofill/services/autofill.service.ts, apps/browser/src/background/main.background.ts, apps/browser/src/background/runtime.background.ts
https://bitwarden.atlassian.net/browse/PM-15943
This PR fixes an issue where, upon autofilling, the extension UI would quickly reload before closing. The cause was the call to `await this.cipherService.updateLastUsedDate(options.cipher.id);` which was causing the service to re-emit values and the consuming components to re-render. Doing the update in the background avoids the UI flicker but still ensures the last used password is still top of the autofill suggestion list.
https://github.com/user-attachments/assets/5bbb4b1c-3e49-40cc-98d4-19c793bd6642
- Used …
=> [PM-15943] - fix extension flicker when filling in a password

apps/browser/src/vault/popup/components/vault-v2/vault-v2.component.html
[PM-17974](https://bitwarden.atlassian.net/browse/PM-17974)
https://github.com/bitwarden/clients/pull/13068 introduced a change that didn't expect a `null` list of ciphers during first load and would throw an exception. This PR prevents passing a null value while the `async` pipe resolves.
- 📝 (`:memo:`) or …
=> [PM-17974] Fix Browser vault not rendering after initial unlock 

apps/desktop/src/scss/base.scss
[CL-530](https://bitwarden.atlassian.net/browse/CL-530)
This PR adds a css override that excludes the component library form field components from receiving background colors set in global css.
| <img width="1055" alt="Screenshot 2025-02-04 at 3 43 55 PM" src="https://github.com/user-attachments/assets/dd2032c0-d7f4-4f42-9d35-23375a133a50" /> | <img width="1055" alt="Screenshot 2025-02-04 at 3 43 45 PM" src="https://github.com/user-attachments/assets/f6fb5783-db14-4319-878b-ac38dc32edc3" /> |
| <img width="1055" alt="Screenshot 2025-02-04 at 3 44 09 PM" src="https://github.com/user-attachments/assets/9ed6cd60-4534-4f3f-99ec-4bd8f618a5fe" /> | <img width="1055" alt="Screenshot 2025-02-04 at 3 43 27 PM" …
=> [CL-530] Exclude CL inputs from global css

apps/browser/src/platform/services/platform-utils/browser-platform-utils.service.spec.ts, apps/browser/src/platform/services/platform-utils/browser-platform-utils.service.ts
https://bitwarden.atlassian.net/browse/PM-7548
Right now during use of the browser extension we get a lot of `Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.` errors in the console. After investigation it seems that most of them are coming from the `checkVaultPopupHeartbeat` which adds up since that is called quite often. The solution for this is to no longer not check the `chrome.runtime.lastError` and then special case the message that essentially means that the popup doesn't exist. Resolving `false` makes sense in that case. This cleans up the console a lot making it easier to focus on real logs.  …
=> [PM-4783] Special case browser error

apps/web/src/app/auth/settings/account/account.component.html, apps/web/src/app/auth/settings/account/account.component.ts
https://bitwarden.atlassian.net/browse/PM-17715
In https://github.com/bitwarden/clients/pull/12880 we added the ability for users to opt out of New Device Verification.
In the original PR, the functionality was gated behind the `new-device-verification` feature flag.
This PR removes this feature from the larger feature flag scope, so that we can allow users to opt out prior to the feature being introduced.
See https://github.com/bitwarden/server/pull/5342 for corresponding server PR.
https://github.com/user-attachments/assets/33ca29d1-7fb9-4ee0-8735-7606197eaf41
- Used …
=> [PM-17715] Remove feature flag check from New Device Verification opt-out

libs/vault/src/cipher-form/components/custom-fields/custom-fields.component.ts
https://bitwarden.atlassian.net/browse/PM-15938
This PR fixes a bug introduced by the [previous PR](https://github.com/bitwarden/clients/pull/13016) for this ticket that caused disabled custom fields to not be included in the submitted cipher. …
=> [PM-15938] - ensure disabled fields are still included with cipher

apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.ts, apps/web/src/app/admin-console/organizations/members/members.component.ts
https://bitwarden.atlassian.net/browse/PM-18081
Adds modal for admins and users with canManageUser permissions …
=> [PM-18081] admins owners and canManageUsers permissions can see the modal

bitwarden_license/bit-common/src/tools/reports/risk-insights/services/risk-insights-data.service.ts, bitwarden_license/bit-web/src/app/tools/access-intelligence/all-applications.component.html, bitwarden_license/bit-web/src/app/tools/access-intelligence/all-applications.component.ts, bitwarden_license/bit-web/src/app/tools/access-intelligence/critical-applications.component.html, bitwarden_license/bit-web/src/app/tools/access-intelligence/critical-applications.component.ts, bitwarden_license/bit-web/src/app/tools/access-intelligence/risk-insights.component.html
https://bitwarden.atlassian.net/browse/PM-17783
Highlight the cards when the drawer is open
Highlight rows when the drawer for that row is open
This behavior applies to all tabs and critical tabs as well. …
=> PM-17783 highlight when drawers are open

apps/web/src/app/billing/organizations/change-plan-dialog.component.ts
https://bitwarden.atlassian.net/browse/PM-18134
Steps:
Create an org Teams org with Secrets Manager
Upgrade org in Subscription page and check the Total breakdown section
Expected: Total amount should be displayed
Actual: Total is showing blank
Uploading Screen Recording 2025-02-07 at 22.27.11.mov…
- 📝 …
=> [PM-18134][Defect] The Total amount is showing blank in Upgrade flow

apps/web/src/app/billing/services/stripe.service.ts, apps/web/src/app/billing/shared/payment/payment-label.component.html, apps/web/src/app/billing/shared/payment/payment-label.component.ts
https://bitwarden.atlassian.net/browse/PM-17736
With the extension refresh released, the conditional code around the ExtensionRefresh-feature-flag within the web-vault should also be removed.
Relates to https://github.com/bitwarden/clients/pull/10978
- **Remove conditional code around extensionRefreshFlag] -** https://github.com/bitwarden/clients/commit/bb627fad8b84034c01f167c3e4eeb2a58fc4168a …
=> [PM-17736] Remove conditional code around extensionRefreshFlag for Stripe/billing pages

apps/desktop/package.json, apps/desktop/src/package-lock.json, apps/desktop/src/package.json, package-lock.json
In https://github.com/bitwarden/clients/pull/13334, we adjusted the `desktop/src/package.json` and `desktop/src/package-lock.json` to correct the desktop version from `2025.2.1` to `2025.2.0`.
However, we left the version as `2025.2.1` in the `desktop/package.json` and `package-lock.json`, which are changed in the Version Bump job.
Since these were left at `2025.2.1`, subsequent version bumps (e.g. https://github.com/bitwarden/clients/commit/6aeab0765dd707b31cf7b9076c66092d4629dc7f) bumped to `2025.2.2` instead of `2025.2.1` as it should be.
Once this is in `main`, both this and https://github.com/bitwarden/clients/commit/6aeab0765dd707b31cf7b9076c66092d4629dc7f will be picked to `rc`.
- Written new …
=> (chore) Update desktop version to 2025.2.1

apps/web/src/app/vault/individual-vault/vault-filter/shared/components/vault-filter-section.component.html
[CL-527](https://bitwarden.atlassian.net/browse/CL-527)
This PR adds the `tw-truncate` class to the `+ New Organization` button in the individual vault, so that it truncates like the rest of the filter items and does not overflow its div
Before:
After: …
=> [CL-527] Add truncate class to new organization button

apps/browser/src/platform/popup/layout/popup-layout.mdx, libs/components/src/avatar/avatar.mdx, libs/components/src/badge/badge.mdx, libs/components/src/banner/banner.mdx, libs/components/src/breadcrumbs/breadcrumbs.mdx, libs/components/src/button/button.mdx, libs/components/src/callout/callout.mdx, libs/components/src/chip-select/chip-select.mdx, libs/components/src/color-password/color-password.mdx, libs/components/src/dialog/dialog/dialog.mdx, libs/components/src/dialog/dialogs.mdx, libs/components/src/dialog/simple-dialog/simple-dialog.mdx, libs/components/src/disclosure/disclosure.mdx, libs/components/src/drawer/drawer.mdx, libs/components/src/form/forms.mdx, libs/components/src/icon-button/icon-button.mdx, libs/components/src/item/item.mdx, libs/components/src/menu/menu.mdx, libs/components/src/popover/popover.mdx, libs/components/src/progress/progress.mdx, libs/components/src/section/section.mdx, libs/components/src/stories/compact-mode.mdx, libs/components/src/tabs/tabs.mdx, libs/components/src/typography/typography.mdx
[CL-444](https://bitwarden.atlassian.net/browse/CL-444)
This PR solves two issues --
1. Some stories were not rendering properly on the docs pages. This was because we were improperly using the Storybook `Canvas` as a wrapper. (This was behavior supported a couple major versions ago but is no longer supported.)
2. Many stories on the docs pages did not have the option to show the code for that story. Using `Canvas` provides the "show code" option, while using `Story` does not. (Under the hood, `Canvas` wraps `Story`.)
This PR only modifies CL-owned docs pages.
| ![Screenshot 2025-02-12 at 10 43 57 AM](https://github.com/user-attachments/assets/a65c7083-bf11-47bf-a6f7-4a75a904b884) | ![Screenshot 2025-02-12 at 10 44 …
=> [CL-444] Use Canvas story wrapper properly

libs/vault/src/cipher-form/components/item-details/item-details-section.component.ts
[PM-18192](https://bitwarden.atlassian.net/browse/PM-18192)
Add a null check that was preventing assigning personal items to an organization from the cipher form.
https://github.com/user-attachments/assets/ace938d9-73b9-4430-aff0-91f031d1a446 …
=> [PM-18192] Fix assign to org flow for cipher edit form

apps/web/src/app/vault/individual-vault/vault-filter/services/vault-filter.service.ts
https://bitwarden.atlassian.net/browse/PM-17609
This PR fixes an issue where cipherView$ may emit null during encryption. This is an expected behavior, so we will filter out the null emission at the consumer of this observable.
https://github.com/user-attachments/assets/02f4b9f7-9be6-4b05-b678-e72ee14424ad
- …
=> [PM-17609] Filter out null emissions during decryption

apps/web/src/app/admin-console/organizations/members/components/bulk/bulk-restore-revoke.component.html
https://bitwarden.atlassian.net/browse/PM-16953
Fixes UI to align with the intended design for the bulk restore/revoke dialog …
=> [PM-16953] fix UI design

apps/web/src/app/admin-console/organizations/members/components/bulk/bulk-delete-dialog.component.html
https://bitwarden.atlassian.net/browse/PM-16971
This PR fixes the UI design to remove  the warning callout …
=> [PM-16971] bulk delete dialog UI fixes

apps/web/src/app/admin-console/organizations/manage/entity-events.component.ts
https://bitwarden.atlassian.net/browse/PM-17852
This PR fixes an issue where the veiwEvents query param is not being removed after closing the event dialog. The result is that router events will trigger an emission with the query param in the vault component that is supposed to open the entity event dialog. Removing the query param after closing the dialog resolves this issue.
https://github.com/user-attachments/assets/667bdff7-5430-4154-9418-51dcde64944c …
=> [PM-17852] ensure query param is removed when component is destroyed

libs/auth/src/angular/login-decryption-options/login-decryption-options.component.html
https://bitwarden.atlassian.net/browse/PM-17179?atlOrigin=eyJpIjoiNWQ5OTc0OTc5MTZiNGFlOWJjNzRjODI2NTE2YzdmNjkiLCJwIjoiaiJ9
Replaces the Bootstrap styles from the LoginDecryptionOptionsComponent with the Tailwind equivalents.
- ❓ …
=> [PM-17179] Remove Bootstrap style from LoginDecryptionOptionsComponent

apps/web/src/app/vault/components/vault-items/vault-collection-row.component.html
[PM-17512](https://bitwarden.atlassian.net/browse/PM-17512)
There were not any applied styles for this bootstrap class so it can be removed!
N/A
[PM-17512]: https://bitwarden.atlassian.net/browse/PM-17512?atlOrigin=eyJpIjoiNWRk …
=> [PM-17512] Remove unused "icon" class

apps/web/src/app/vault/org-vault/vault-header/vault-header.component.html
https://bitwarden.atlassian.net/browse/PM-18278
Fixes an issue where canCreateCiphers conditional overrides the canCreateCollections permission due to the structure of the template …
=> [PM-18278] fix conditional in template

apps/web/src/app/billing/organizations/change-plan-dialog.component.ts
https://bitwarden.atlassian.net/browse/PM-18321
`smServiceAccounts` contains the base service accounts seats amount for the selected plan. We are not supposed to include this as an additional machine account, otherwise it results into sales tax being abnormally high. …
=> [PM-18321] Fix sales tax calculation for secrets manager

apps/web/src/app/billing/services/stripe.service.ts
https://bitwarden.atlassian.net/browse/PM-17170
Added retry logic when mounting Stripe elements and extended timout to 50 ms …
=> [PM-17170] Added retry logic when mounting Stripe elements and extended timout to 50 ms

tsconfig.eslint.json, tsconfig.json
N/A
`typescript-transform-paths` was already removed as a dependency but the config was never removed. It has been replaced by `tsconfig-paths-webpack-plugin`.  …
=> Remove typescript-transform-paths config

.github/CODEOWNERS
Since the ownership for `desktop_native` was defined later than where autofills ownership of `desktop_native/core/src/ssh_agent` or `desktop_native/core/windows-plugin-authenticator` are defined, which means that platform just owns all of it. (Hence the request to platform from https://github.com/bitwarden/clients/pull/13468). …
=> Fix autofill ownership of ssh agent and windows-plugin-authenticator

apps/browser/src/platform/popup/layout/popup-back.directive.ts, apps/browser/src/tools/popup/send-v2/add-edit/send-add-edit.component.html, apps/browser/src/tools/popup/send-v2/add-edit/send-add-edit.component.ts, apps/browser/src/tools/popup/settings/export/export-browser-v2.component.html, apps/browser/src/tools/popup/settings/export/export-browser-v2.component.ts, libs/components/src/index.ts
https://bitwarden.atlassian.net/browse/PM-15827
Add close button to sends and vault export pages.
Send screen video:
https://github.com/user-attachments/assets/e1786e6b-47f9-43e7-810a-ae620f87e617
Export screen video: 
https://github.com/user-attachments/assets/e98ca4f4-80c6-4eac-a400-5037fcd4e3b2
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or …
=> [PM-15827] add `popupBackAction` to send item and export vault pages

.github/renovate.json, .storybook/main.ts, .storybook/preview.tsx, libs/components/src/drawer/drawer.stories.ts, libs/components/src/stories/kitchen-sink/kitchen-sink.stories.ts, libs/components/src/stories/storybook-decorators.ts, package-lock.json, package.json
[CL-317](https://bitwarden.atlassian.net/browse/CL-317)
We removed light and dark theme combined mode from Storybook in a previous PR. To switch between light and dark themes, we can now use Storybook's built-in `theme` addon.
Should visually look the same as before, except for the theme switcher in the toolbar. …
=> [CL-317] Use storybook theme addon for theme switching

apps/web/src/app/auth/core/services/login/web-login-component.service.spec.ts, apps/web/src/app/auth/core/services/login/web-login-component.service.ts, libs/auth/src/angular/login/default-login-component.service.spec.ts, libs/auth/src/angular/login/default-login-component.service.ts, libs/auth/src/angular/login/login-component.service.ts, libs/auth/src/angular/login/login.component.ts
https://bitwarden.atlassian.net/browse/PM-17693
To restore the functionality that we broke during the UI refresh where existing BW users that are invited to an organization should be forced to update their password to meet org master password policy requirements (regardless of the `enforceOnLogin` setting).
As info, org invites are only accepted on the web. 
https://github.com/user-attachments/assets/31dd44ac-d13a-4f07-b082-2660d025ed33
https://github.com/user-attachments/assets/547f9d4c-7270-4ed6-91db-ca6924537f29
- CI …
=> Auth/PM-17693 - Web - Existing users accepting an org invite are required to update password to meet org policy requirements

libs/components/src/tw-theme.css
https://bitwarden.atlassian.net/browse/PM-17207
Angular CKD LiveAnnouncer depends on some css logic to hide announcements from being displayed. We are currently missing this functionality as we don't import CDK styles globally.
Resolves #13260
Resolves https://github.com/bitwarden/clients/issues/13471
- 📝 …
=> Add cdk-visually-hidden to tw-theme for Angular CDK LiveAnnouncer

apps/browser/src/background/main.background.ts, apps/browser/src/platform/services/popup-view-cache-background.service.ts, libs/common/src/platform/scheduling/index.ts, libs/common/src/platform/scheduling/scheduled-task-name.enum.ts, libs/common/src/platform/scheduling/task-scheduler.service.ts
https://bitwarden.atlassian.net/browse/PM-17658
Fix `delay` to still trigger a cleanup even in the event that the service worker dies. By using a `SchedulerLike` based on our own `TaskSchedulerService` it will utilize a more long lived scheduling infrastructure when needed. When it's not needed it will still use `setTimeout` under the hood, just like the default scheduler in rxjs.  …
=> [PM-17658] Fix persist route to clear if service worker dies

apps/browser/src/autofill/services/autofill-overlay-content.service.spec.ts
[PM-18051](https://bitwarden.atlassian.net/browse/PM-18051)
[Removing](https://bitwarden.atlassian.net/browse/PM-16635) the `inline-menu-field-qualification` feature flag revealed a weakened assumption in a test for the `AutofillOverlayContentService`.
Namely, the spec previously reused a global mock for this spec entitled `autofillFieldData` which resembled the data for a username field, and then simply overrode its type to "password" while leaving its other attributes identical. 
I surmise with the new feature flag available, the qualification for what was a login form and what was a password field both became stricter. In other words, the overlay relies on field qualification which both identifies this field as a password, which disqualifies the form as a login form (since two …
=> Use a newly mocked autofill field for password data in AutofillOverlayContentService spec

apps/browser/src/_locales/en/messages.json, apps/browser/src/autofill/popup/settings/blocked-domains.component.html
[PM-15997](https://bitwarden.atlassian.net/browse/PM-15997)
Adds learn more link to blocked domains description. …
=> Add learnMoreAboutBlockedDomains translation key and append to desc.

apps/browser/src/autofill/popup/settings/excluded-domains.component.html, apps/browser/src/autofill/popup/settings/excluded-domains.component.ts
Changing to new <bit-form-field> component necessitates modifying form to use ReactiveForms conventions. To handle this change, the deletable/uneditable domain state and new form control state are managed separately, including clearing the form state on save. Fields which compute vaules from the former state should now compute both values (see domain count); [formGroup], formArrayName, formControlName all necessary directives/properties on form and children.
[Excluded Domain field is incorrect component/styling - Jira](https://bitwarden.atlassian.net/browse/PM-13808)
> The field where you enter the excluded domain is incorrect (the label is not nested in the input border). It should use the same field and label component and stylings as the vault item page.
> 
> The added domain item …
=> PM-13808 - Use new <bit-form-field> component in Excluded domains settings.

apps/browser/src/autofill/popup/settings/blocked-domains.component.html, apps/browser/src/autofill/popup/settings/blocked-domains.component.ts
Replicate ReactiveForms and bit-* component changes to Blocked Domains from Excluded Domains update [PM-13808].
[PM-17819](https://bitwarden.atlassian.net/browse/PM-17819)
- Field styles use `<bit-form-field>` styles
- Field extends width of the card
- Added domains are aligned vertically with the remove icon button
After: …
=> [PM-17819] Replicate ReactiveForms and bit-* component changes to Blocked Domains

apps/browser/src/_locales/en/messages.json, apps/browser/src/tools/popup/settings/about-dialog/about-dialog.component.html, apps/browser/src/tools/popup/settings/about-dialog/about-dialog.component.ts
https://bitwarden.atlassian.net/browse/PM-18396
Add a copy button to browser extension about dialog for quickly copying the version number now that we have 3 different values we'd like to collect.
Related to https://github.com/bitwarden/clients/pull/13467
Clicking on the button copies the data from the dialog. Example:
```text
Version: 2025.2.1
SDK: 'main (28c7e29)'
Server version: 2025.1.4
``` …
=> [PM-18396] Add a copy button to browser ext about dialog

libs/common/src/enums/feature-flag.enum.ts
https://bitwarden.atlassian.net/browse/PM-7125
With the removal of the last usage of the `extension-refresh`-feature flag (https://github.com/bitwarden/clients/pull/13449), this flag can finally be removed from clients. …
=> [PM-7125] Remove extension-refresh feature flag from clients

apps/web/src/app/auth/recover-two-factor.component.spec.ts, apps/web/src/app/auth/recover-two-factor.component.ts, libs/angular/src/vault/guards/new-device-verification-notice.guard.spec.ts, libs/angular/src/vault/guards/new-device-verification-notice.guard.ts, libs/vault/src/services/new-device-verification-notice.service.spec.ts, libs/vault/src/services/new-device-verification-notice.service.ts
https://bitwarden.atlassian.net/browse/PM-18474
Fixed the recovery code login to work with the new device verification notice flow.
https://github.com/user-attachments/assets/573a0e35-85fc-48cc-88b6-517fc4f041e6 …
=> fix(recovery-code-login): [PM-18474] Fix for Recovery Code Login

bitwarden_license/bit-web/src/app/tools/reports/member-access-report/member-access-report.component.html, bitwarden_license/bit-web/src/app/tools/reports/member-access-report/member-access-report.component.ts
https://bitwarden.atlassian.net/browse/PM-18441
To add a loading icon to the member details report …
=> pm-18441 add loading icon to member details

apps/browser/src/vault/popup/services/vault-popup-autofill.service.spec.ts, apps/browser/src/vault/popup/services/vault-popup-autofill.service.ts
[PM-18287](https://bitwarden.atlassian.net/browse/PM-18287)
Vault autofill suggestions view hangs on load when the current tab is on the blocked domains list.
The issue in this case was two-fold:
- Primarily, `_currentPageDetails` in `VaultPopupAutofillService` would invoke `AutofillService.collectPageDetailsFromTab$` which was unguarded against cases where the current page was blocked. The page details state informs several presentational aspects of the autofill suggestions, including whether cards and identities should be included in the page suggestions (and is gathered via script injection).
- `AutofillService.collectPageDetailsFromTab$` in turn invokes `BrowserApi.tabSendMessage`. In Chrome, this will result in a thrown error if the targeted tab has no listener for the message. …
=> [PM-18287] Bugfix - Vault autofill suggestions view hangs on load when the current tab is on the blocked domains list

apps/browser/src/background/main.background.ts, apps/browser/src/platform/services/browser-script-injector.service.ts, apps/browser/src/vault/popup/services/vault-popup-autofill.service.ts, libs/common/src/autofill/utils.spec.ts, libs/common/src/autofill/utils.ts
https://bitwarden.atlassian.net/browse/PM-18219
- In callsites where we resolve a URI (from the current/active tab) against blocked domains, we use slightly differing logic - we should unify that logic (ideally abstracted to a single resolver)
- The current resolution pattern for current URI against blocked domains is to look for an exact match. However, in cases where the user has included a subdomain `sandbox.paypal.com` the current URI hostname value will resolve to `www.sandbox.paypal.com`. Resolution checks the `currentUri` with an `endsWith` against the blocked URLs array (do not use `startsWith` as that will allow unsafe comparisons against packed subdomains; e.g. `sandbox.paypal.com.some.otherdomain.com`)
- Rename "URI" to "URL" to reflect contextual expectations and narrower case …
=> [PM-18219] Normalize blocked domain checks to a common util

libs/auth/src/angular/login/login.component.html
https://bitwarden.atlassian.net/browse/PM-18408
Original Attempt: https://github.com/bitwarden/clients/pull/13475
To prevent scrollbars from appearing on the new UI refreshed login component in the browser extension. They only show up upon logging back into an account that you've logged into previously as the login with device section appears in the incorrectly hidden second stage of the component. We should have used `tw-hidden` to ensure the second stage renders so autofill works while remaining hidden and not taking up any space in the DOM. 
Demo of the bad behavior:
https://github.com/user-attachments/assets/d96203d3-f98a-4c45-9252-08704f4ff843
Demo of fixed behavior + web autofill still working:
https://github.com/user-attachments/assets/0541e9b5-2801-4c92-8114-76e5bedecbe5
- …
=> Auth/PM-18408 - LoginComp - Fix extension showing scrollbars (attempt 2)

libs/key-management-ui/src/lock/components/lock.component.ts
https://bitwarden.atlassian.net/browse/PM-18509
A regression caused by #13121, which broke unlock with master password.
Root cause: too wide condition block for reading master password policy, not setting the password as valid.
UT coverage to be added separately, since we want to get this in before RC cut.
https://github.com/user-attachments/assets/effde1f6-eba9-4ca8-b2c2-65c20d4030ac
Other unrelated issues:
- 0:29 - 0:55: slow unlock, known issue
- 2:29 - 2:55: biometrics issue, investigating
- …
=> [PM-18509] Unable to unlock vault

apps/browser/src/vault/popup/services/vault-popup-items.service.ts
https://bitwarden.atlassian.net/browse/PM-17793
Fixes the vault page from getting stuck in an infinite loading indicator. The exact reason it was broken with the code before is still a bit of a mystery even though the implementations are _pretty_ close to the same thing. I had a `tap` after the `getAllDecrypted` call and a `tap` after `failedToDecryptCiphers` and both get an emission but we never get to the `map` right after the `withLatestFrom`. My best guess is some kind of race condition that makes the internals of `withLatestFrom` believe it hasn't received an emission from the source and the past in observable.
Before:
https://github.com/user-attachments/assets/c2e2059b-96f4-4566-9583-d88b76872466
After:
https://github.com/user-attachments/assets/0111ade0-207e-4d99-867b-c71a0b76b2d5 …
=> [PM-17793] Fix Vault Loading

apps/browser/src/auth/popup/settings/account-security.component.html, apps/browser/src/auth/popup/settings/account-security.component.ts, libs/auth/src/angular/fingerprint-dialog/fingerprint-dialog.component.html
https://bitwarden.atlassian.net/browse/PM-14588
To resolve some minor styling issues on the Extension `AccountSecurityComponent` and the global `FingerprintDialogComponent`
Before:
After (normal scenario w/ no org policy requirements):
After (demo of org policy requirements having proper spacing between timeout action select):
Fingerprint dialog now has correct info icon styling: …
=> Auth/PM-14588 - Extension Account Security Component + Account Fingerprint Dialog styling fixes

apps/web/package.json
N/A
Our client builds are presently monolithic and require a substantial amount of memory. Most builds were updated, but the web watch builds [listed in the contrib docs](https://contributing.bitwarden.com/getting-started/clients/web-vault/#build-instructions) were missed.
This ticket increases their memory limit to 8 GB.
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for …
=> increase memory limit for web watch builds

apps/browser/src/background/main.background.ts, apps/browser/src/platform/services/popup-view-cache-background.service.ts
https://bitwarden.atlassian.net/browse/PM-18549
In order to support using extension route persistence for login flows that require the user to go to their email inbox or another tab to perform the operation, we need to remove the restriction that cleared the cache on tab change.
Examples of user flows that would require this are:
- New Device Verification OTP (the trigger for this issue)
- Email 2FA
Note that I also removed the TS strict comment from this file while I was modifying it.
https://github.com/user-attachments/assets/08eeb0a6-c282-41dc-ab4e-a6c15f4af949
- Used …
=> [PM-18549] Do not clear route or view persistence on tab change

apps/browser/src/platform/popup/view-cache/popup-router-cache.service.ts, apps/browser/src/platform/popup/view-cache/popup-view-cache.service.ts, apps/browser/src/platform/popup/view-cache/popup-view-cache.spec.ts, libs/common/src/enums/feature-flag.enum.ts
https://bitwarden.atlassian.net/browse/PM-18529
Remove the `persist-popup-view` feature flag from clients.
This flag has been enabled on all 3 environments since December 17.
https://github.com/user-attachments/assets/d184a904-3792-45ac-b4a8-2ba4c01342dc …
=> [PM-18529] Remove persist-popup-view feature flag

libs/auth/src/angular/login-via-auth-request/login-via-auth-request.component.html
https://bitwarden.atlassian.net/browse/PM-18506
To add missing spaces into the bottom of the `LoginViaAuthRequestComponent` for the admin auth request and normal auth request flows. 
Login via Admin Auth request:
Login via Normal Auth Request: …
=> Auth/PM-18506 - LoginViaAuthReqComp - fix missing spaces

apps/browser/src/_locales/en/messages.json, apps/browser/src/vault/popup/components/vault-v2/item-copy-action/item-copy-actions.component.html, apps/browser/src/vault/popup/components/vault-v2/item-copy-action/item-copy-actions.component.ts
https://bitwarden.atlassian.net/browse/PM-13989
This PR updates the vault item copy button to immediately copy if the vault item only has a single field with a value.
https://github.com/user-attachments/assets/5ffed2e1-7219-406d-8653-625203a99ded …
=> [PM-13989] - Extension Vault screen - allow copy icon to copy data directly if only 1 piece of data is available

apps/browser/src/platform/popup/layout/popup-tab-navigation.component.html
https://bitwarden.atlassian.net/browse/CL-554
Added `tw-text-sm` class to navigation tabs
See Chromatic …
=> CL-554 update extension navigation text size 

apps/cli/src/auth/commands/login.command.ts
[PM-18583](https://bitwarden.atlassian.net/browse/PM-18583)
User's were unable to login to the CLI with New Device Verification. This allows users to login using the device code sent via email.
Before testing was completed for each round, I deleted the `data.json` for the CLI client to ensure a new generated app id to force the New Device Verification Feature to apply.
I don't have SSO set up locally so I opted to leave that test out but the API and two-factor flows being unaffected builds enough confidence in the other flows being stable with this addition.
https://github.com/user-attachments/assets/f7cd2b22-8a7c-4d6e-958b-de3a1c1da959
1. User tries to login with mp but doesn't supply code: error
1. User tries to login with mp but supplies wrong code: error
1. (I goof and accidently hit …
=> [PM-18583] Login with new device verification in CLI

apps/web/src/locales/en/messages.json, bitwarden_license/bit-web/src/app/tools/access-intelligence/critical-applications.component.html
https://bitwarden.atlassian.net/browse/PM-18616
Disable the notifications button when there are no at-risk passwords in the critical apps list. …
=> Tools/pm 18616/disable notify button

libs/auth/src/common/services/auth-request/auth-request-api.service.ts
https://bitwarden.atlassian.net/browse/PM-18639
This PR makes sure we are specifically constructing and returning a `new AuthRequestResponse()` object from the `AuthRequestApiService` calls.
**Background**
In https://github.com/bitwarden/clients/pull/11545 we created an `AuthRequestApiService` as part of the refresh work for the `LoginViaAuthRequestComponent`. In that new `AuthRequestApiService` I missed wrapping the returned response in a `new AuthRequestResponse()` constructor.
This object construction is important in the case of this bug because it sets the `isAnswered` property [here](https://github.com/bitwarden/clients/blob/main/libs/common/src/auth/models/response/auth-request.response.ts#L58).
The bug occurred because this `isAnswered` property was getting read as `undefined` …
=> [PM-18639] Bugfix - Resend Admin Auth Request After Previous Denial

apps/browser/src/_locales/en/messages.json, apps/browser/src/vault/popup/components/at-risk-passwords/at-risk-passwords.component.html, apps/browser/src/vault/popup/components/at-risk-passwords/at-risk-passwords.component.spec.ts, apps/browser/src/vault/popup/components/at-risk-passwords/at-risk-passwords.component.ts
[PM-18463](https://bitwarden.atlassian.net/browse/PM-18463)
[PM-18465](https://bitwarden.atlassian.net/browse/PM-18465)
PM-18463
- Fix missing hyphen in page description
- Fix pluralization of page description when the user only has a single task
- Fix spacing between UI buttons
PM-18465
- Prevent autofill callout from flashing briefly after previously being dismissed …
=> [PM-18463] [PM-18465] At-risk Password Page Fixes

libs/auth/src/angular/sso/sso.component.ts
https://bitwarden.atlassian.net/browse/PM-18661
Addresses a bug in which redirect-based SSO clients (desktop, extension) were not checking claimed domains.
This is because we were early-returning from our initialization routine, when we should have been allowing the code to progress to checking for any claimed domains.
The existing logic in the `v1` `SsoComponent` can be seen [here](https://github.com/bitwarden/clients/blob/e448afb064a7a530553dcf55696253fe46f47d88/apps/web/src/app/auth/sso-v1.component.ts#L101).
https://github.com/user-attachments/assets/901cf713-bd46-4933-accb-0f354e42caed
https://github.com/user-attachments/assets/376abc75-2d64-4833-aa3f-c697c052e835
- Written new unit and / or …
=> [PM-18661] Remove early return on SSO component initialization

libs/auth/src/angular/login/login.component.ts
https://bitwarden.atlassian.net/browse/PM-18693
To restore form validation behavior where the user is told email is required when clicking the SSO button without an email entered. 
Diagnosis:
The newly added early return logic for type safety in the `handleSsoClick()` method was preventing the `validateEmail()` method from executing which is responsible for showing the form validation errors. 
Before: 
https://github.com/user-attachments/assets/15a954ea-1c6d-475e-93d0-73dfa0e0b219
After:
https://github.com/user-attachments/assets/140280b2-dbc9-43c1-bd01-6cca4a7ae5be
- Used …
=> Auth/PM-18693 - New UI - LoginComp - fix SSO click email required validation

apps/browser/src/billing/popup/settings/premium-v2.component.html, apps/web/src/app/billing/individual/user-subscription.component.html
[PM-18663](https://bitwarden.atlassian.net/browse/PM-18663)
In #12835, we changed the way the button component's loading and disabled properties are implemented, from inputs to signals. I went through and updated consumer files because signals are accessed by calling them, but missed a few instances that were referencing those properties in the template file. This PR fixes those so that the buttons aren't displayed as infinitely loading.
Example with the browser extension file
| ![Screenshot 2025-02-27 at 10 41 26 AM](https://github.com/user-attachments/assets/413794c1-a3cb-461f-be4d-00f819cd9428) |![Screenshot 2025-02-27 at 10 40 41 AM](https://github.com/user-attachments/assets/5ef96397-9545-4d84-a35b-24ce85fdf744) | …
=> [PM-18663] Fix calls to bit-button loading states

apps/web/src/app/tools/reports/pages/inactive-two-factor-report.component.html, apps/web/src/app/tools/reports/pages/inactive-two-factor-report.component.ts, apps/web/src/app/tools/reports/pages/organizations/inactive-two-factor-report.component.ts
https://bitwarden.atlassian.net/browse/PM-18706
The inactive 2fa report when run from Admin Console did not properly check the CanManage permissions and would offer to open the View Dialog, instead of just displaying the item name.
- ❓ …
=> [PM-18706] Added permission check for organizational inactive 2fa report

apps/web/src/app/tools/reports/pages/organizations/unsecured-websites-report.component.ts, apps/web/src/app/tools/reports/pages/unsecured-websites-report.component.html, apps/web/src/app/tools/reports/pages/unsecured-websites-report.component.ts
https://bitwarden.atlassian.net/browse/PM-16219
The unsecure website report when run from Admin Console did not properly check the CanManage permissions and would offer to open the View Dialog, instead of just displaying the item name.
- …
=> [PM-16219] Added permission check for organizational unsecure website report

apps/browser/src/_locales/en/messages.json, apps/browser/src/auth/popup/account-switching/current-account.component.html
https://bitwarden.atlassian.net/browse/PM-12766
To adjust the Extension `CurrentAccountComponent's` screen reader text for the user's avatar from `Active Account: <account>` to `Bitwarden account: <account>` to avoid confusion regarding account switching which isn't supported in all scenarios.
https://github.com/user-attachments/assets/59c50923-bb00-4d06-a76d-0af9bf655cde …
=> Auth/PM-12766 - Extension - Current Acct Comp - adjust screen reader text

libs/common/src/models/response/notification.response.ts, libs/common/src/platform/notifications/internal/worker-webpush-connection.service.ts
https://bitwarden.atlassian.net/browse/PM-16787
Fixes a small issue with #11346 where the payload of a push notification was not being parsed prior to sending into the `NotificationResponse` class, which expects a parsed JSON object.
- ❓ …
=> Parse web push payload JSON

apps/browser/src/autofill/content/components/lit-stories/notification/footer.lit-stories.ts, apps/browser/src/autofill/content/components/lit-stories/rows/button-row.lit-stories.ts, apps/browser/src/autofill/content/components/notification/confirmation-message.ts, apps/browser/src/autofill/content/components/notification/confirmation.ts, apps/browser/src/autofill/content/components/notification/container.ts, apps/browser/src/autofill/content/components/notification/footer.ts, apps/browser/src/autofill/content/components/rows/button-row.ts
https://bitwarden.atlassian.net/browse/PM-18522
Adjust styling on confirmation UI to no longer truncate full string when a user name is too long, but still truncate the username 
Additional clean up: Added action button text and localized save as new login  …
=> PM-18522 Adjust Confirmation UI text to accommodate truncating

libs/common/src/platform/services/config/config.service.spec.ts
https://bitwarden.atlassian.net/browse/PM-18658
`runOnlyPendingTimers` should only be called when using fake timers. This line is currently producing warnings at run and does not seem necessary.
- 🤔 …
=> [PM-18658] Remove runOnlyPendingTimers

libs/angular/src/vault/components/vault-items.component.ts, libs/common/src/vault/services/cipher.service.ts
[PM-18707](https://bitwarden.atlassian.net/browse/PM-18707)
Fix the live sync feature on Desktop by waiting for ElectronStore storage service to stabilize in the CipherService before continuing on with an `upsert` operation.
The `ElectronStorageService` save method does not "wait" for the Electron store to finish saving (`store.set()` is not awaitable) so our upsert methods in the `CipherService` notify subscribers to the store that the value has been updated. This appears to race, and our subscribers fetch the value from the ElectronStore (`store.get()`) before the prior `store.set()` call finalized. This results in cipherService subscribers (`ciphers$` and `cipherViews$`) receiving and caching the old cipher data; causing the UI to become stale.
Adding an artificial delay of one tick …
=> [PM-18707] Fix desktop live sync

libs/common/src/tools/dependencies.ts, libs/common/src/tools/log/factory.ts, libs/common/src/tools/state/user-state-subject-dependency-provider.ts, libs/common/src/tools/state/user-state-subject.ts, libs/tools/generator/core/src/metadata/algorithm-metadata.ts, libs/tools/generator/core/src/metadata/index.ts, libs/tools/generator/core/src/services/generator-profile-provider.spec.ts, libs/tools/generator/core/src/services/generator-profile-provider.ts
https://bitwarden.atlassian.net/browse/PM-16791
Profiles allow the generator to run with specialized settings and policy controls.
The generator profile provider surfaces policy and settings into the credential generator service.
A future PR will replace the `CredentialGeneratorService`'s current settings and policy lookups with an implementation that delegates to the `GeneratorProfileProvider` and `ExtensionService` in #13590. This implementation will extend `CredentialGeneratorService.settings` and `CredentialGeneratorService.generate$` with profile support.  …
=> [PM-16791] introduce generator profile provider

libs/tools/send/send-ui/src/send-search/send-search.component.html, libs/tools/send/send-ui/src/send-search/send-search.component.ts
https://bitwarden.atlassian.net/browse/PM-18913
During the browser extension refresh a dedicated `send-search.component`was created and a margin was added, but it’s unneeded on browser where it is currently used. It also causes some issues when re-using it in different parts/clients (web/desktop)
- **Remove unneeded margin -** https://github.com/bitwarden/clients/commit/b71a0083a26da44fb0e0e3115a5bfe695ed5dc0b
- **Made send-search.component ts-strict compliant -** https://github.com/bitwarden/clients/commit/9ef76a2edd74f66c1ca7ff3d6a2addb8fa52a02c …
=> [PM-18913] Remove unneeded margin from send search component

apps/browser/src/auth/services/extension-two-factor-auth-component.service.spec.ts, apps/browser/src/auth/services/extension-two-factor-auth-component.service.ts
https://bitwarden.atlassian.net/browse/PM-18901
For the new extension 2FA duo flow, update `determineDuoLaunchAction` to consider if the extension is already in the popout mode.
https://github.com/user-attachments/assets/e3bd9d83-0d1a-45b0-b501-e6dc93a13a3d …
=> Auth/PM-18901 - UI Refresh - Extension Duo 2FA - fix determineDuoLaunchAction to consider if already in popout

apps/browser/src/auth/services/extension-two-factor-auth-webauthn-component.service.spec.ts, apps/browser/src/auth/services/extension-two-factor-auth-webauthn-component.service.ts, apps/browser/src/popup/services/services.module.ts, libs/auth/src/angular/two-factor-auth/child-components/two-factor-auth-webauthn/two-factor-auth-webauthn.component.ts
https://bitwarden.atlassian.net/browse/PM-18836
Chromium still doesn't support inline iframe WebAuthn apparently. It worked locally but doesn't work in dev with error: "NotAllowedError: WebAuthn is not supported on sites with TLS certificate errors" so revert turning that back on with the UI refresh. 
https://github.com/user-attachments/assets/c35022c9-e508-43e8-bb8b-7fdfa5f08e62 …
=> Auth/pm 18836 - UI Refresh - Chrome extension - WebAuthn 2FA revert inline iframe for chromium

libs/components/tailwind.config.base.js
[CL-281](https://bitwarden.atlassian.net/browse/CL-281)
We are overriding the `text-3xl` tailwind style to have: `font-size: 1.75rem; line-height: 2rem;` …
=> [CL-281] Override tailwind text-3xl style

apps/browser/src/_locales/en/messages.json, apps/desktop/src/locales/en/messages.json, apps/web/src/locales/en/messages.json, bitwarden_license/bit-common/src/admin-console/auth-requests/pending-auth-request.view.ts, bitwarden_license/bit-common/src/admin-console/auth-requests/pending-organization-auth-request.response.ts, libs/auth/src/angular/login-approval/login-approval.component.html, libs/auth/src/angular/login-via-auth-request/login-via-auth-request.component.ts, libs/common/src/auth/models/response/auth-request.response.ts
[PM-15015](https://bitwarden.atlassian.net/browse/PM-15015)
[Server PR](https://github.com/bitwarden/server/pull/5471)
We are adding country name from the request header to the `AuthRequest` for better readability for users trying to decide to approve an auth request.
A screen shot of the desktop dialog.
https://github.com/user-attachments/assets/e65c757e-178c-4e83-a501-341b4e02a1ee
User uses web app approvals to allow desktop to login. The login flow is not impacted by the changes as the user is allowed to login to the vault on the desktop after inputting their two-factor authentication code. …
=> [PM-15015]  Adding Request Country Name to auth requests approval dialog

libs/auth/src/angular/sso/sso-component.service.ts, libs/auth/src/angular/sso/sso.component.ts
https://bitwarden.atlassian.net/browse/PM-18945
We were not allowing CLI as a valid `ClientType` for SSO.  This was causing `clientId=web` to be passed to the server in the request to `/connect/authorize`, which was rejected for an invalid `redirect_uri`.  The CLI's `localhost` `redirect_uri` is not valid for the web client.
https://github.com/user-attachments/assets/218f70a9-c7ce-4fd3-a766-8d1f21a2da5e …
=> [PM-18945] Add CLI as valid SSO client

apps/web/src/app/vault/components/browser-extension-prompt/browser-extension-prompt.component.spec.ts, apps/web/src/app/vault/components/browser-extension-prompt/browser-extension-prompt.component.ts, libs/auth/src/angular/anon-layout/anon-layout.component.html, libs/vault/src/icons/browser-extension.ts
[PM-18859](https://bitwarden.atlassian.net/browse/PM-18859)
Present the `/browser-extension-prompt` page in a mobile friendly fashion.
- The original issue that was called out by Kyra is caused by global styles/configuration set to not let the width of the page go below `1010px`.
- Editing this globally would be a huge undertaking across teams and be a large impact to QA to start allowing for mobile/tablet viewports.
- [Min-width set on the body](https://github.com/bitwarden/clients/blob/f95ce4e44253d7f724cae8cb580016d24755c091/apps/web/src/scss/base.scss#L6)
- [viewport meta](https://github.com/bitwarden/clients/blob/5e3830fb5140052aaffbf5af345f80550ae0c211/apps/web/src/index.html#L5)
- To provide a better experience for this individual page, those values out/removed and then replaced …
=> [PM-18859] Mobile Viewports - Extension Prompt

apps/web/src/app/vault/individual-vault/password-history.component.html
https://bitwarden.atlassian.net/browse/PM-12699
This PR increases the size of the password history dialog to the default size as per design. …
=> [PM-12699] - increase size of password history dialog

apps/browser/src/vault/popup/components/vault-v2/autofill-vault-list-items/autofill-vault-list-items.component.html, apps/browser/src/vault/popup/components/vault-v2/vault-list-items-container/vault-list-items-container.component.html, apps/browser/src/vault/popup/components/vault-v2/vault-list-items-container/vault-list-items-container.component.ts
https://bitwarden.atlassian.net/browse/PM-15391
This PR removes some extra bottom margin from the vault list items description when it's displaying an empty autofill list. This ensures consistent spacing between the sections.
|Before|After|
---|---
|![Screenshot 2025-03-04 at 3 16 45 PM](https://github.com/user-attachments/assets/ddaded91-cae9-45d9-9611-5a6e6efbdbf8)|![Screenshot 2025-03-04 at 3 16 28 PM](https://github.com/user-attachments/assets/09c2a4de-eb2a-45f2-92e0-ca1e8ef80a7c)| …
=> [PM-15391] - Autofill suggestions margin when no items appear is too large

apps/web/src/app/vault/individual-vault/vault-filter/components/vault-filter.component.ts, libs/vault/src/cipher-view/item-history/item-history-v2.component.html
https://bitwarden.atlassian.net/browse/PM-12726
- 🎨 …
=> [PM-12726] - [Defect] [Web] "Secure Note" shows in item filters instead of "Note"

libs/angular/src/vault/vault-filter/components/collection-filter.component.ts
[All Collections opening on vault timeout - MacOS](https://bitwarden.atlassian.net/browse/PM-16610)
This PR sets all the collections in the collections filter as collapsed on initialization.
https://github.com/user-attachments/assets/6e74b620-2c74-49d1-bc55-c977b3908a83 …
=> [PM-16610] - Desktop  - collapse nested collection initially

libs/vault/src/cipher-form/components/custom-fields/custom-fields.component.html
https://bitwarden.atlassian.net/browse/PM-12557
This PR center aligns the custom field buttons with the input …
=> [PM-12557] - center align custom field buttons

apps/browser/src/_locales/en/messages.json, apps/web/src/locales/en/messages.json, libs/vault/src/cipher-form/components/autofill-options/autofill-options.component.html, libs/vault/src/cipher-form/components/autofill-options/autofill-options.component.spec.ts, libs/vault/src/cipher-form/components/autofill-options/autofill-options.component.ts, libs/vault/src/cipher-form/components/autofill-options/uri-option.component.html, libs/vault/src/cipher-form/components/autofill-options/uri-option.component.ts
https://bitwarden.atlassian.net/browse/PM-13991
This PR adds the ability to reorder the login website uri's via drag and drop or keyboard.
https://github.com/user-attachments/assets/a1022db9-d929-44d7-8ce6-247c82424500 …
=> [PM-13991] - Edit login - reorder website URIs

libs/tools/send/send-ui/src/send-form/services/default-send-form-config.service.ts
https://bitwarden.atlassian.net/browse/PM-19082
The current buildConfig method on the DefaultSendFormConfigService has an optional sendType and within in edit mode the SendId is passed in, but the SendType might no be passed in, as it’s not required.
This ensures the type is always set, either by passing in the SendType, taken from the loaded Send or falling back to SendType.Text …
=> [PM-19082] Ensure the SendType is always set when building a SendFormConfig

apps/web/src/app/key-management/migrate-encryption/migrate-legacy-encryption.component.ts
https://bitwarden.atlassian.net/browse/PM-19052
Fixes an error where the migrate legacy user component was failing if the folders couldn't be decrypted. The type of the returned error was an `ErrorResponse`. …
=> [PM-19052] change Error check to ErrorResponse

libs/vault/src/cipher-view/cipher-view.component.ts
[PM-19106](https://bitwarden.atlassian.net/browse/PM-19106)
Inside the `cipher-view` the task api endpoint was being called when `security-task` flag was false. 
The returning api error occurs before the folder logic in the `loadCipherData` method, which is why the folders were not showing. 
added a check to the `checkPendingChangePasswordTasks` method to look at the `security-task` flag.
https://github.com/user-attachments/assets/b473612c-a1b9-441e-afd6-489465979aca …
=> [PM-19106] View Item Bug, folders not displaying

apps/web/src/app/auth/settings/change-password.component.ts, libs/angular/src/services/jslib-services.module.ts, libs/common/src/auth/opaque/default-opaque-api.service.ts, libs/common/src/auth/opaque/default-opaque.service.ts, libs/common/src/auth/opaque/models/cipher-configuration.ts, libs/common/src/auth/opaque/models/login-finish.request.ts, libs/common/src/auth/opaque/models/login-start.request.ts, libs/common/src/auth/opaque/models/login-start.response.ts, libs/common/src/auth/opaque/models/registration-finish.request.ts, libs/common/src/auth/opaque/models/registration-finish.response.ts, libs/common/src/auth/opaque/models/registration-start.request.ts, libs/common/src/auth/opaque/models/registration-start.response.ts, libs/common/src/auth/opaque/opaque-api.service.ts, libs/common/src/auth/opaque/opaque.service.ts, libs/common/src/types/guid.ts
https://bitwarden.atlassian.net/browse/PM-18993
Add client-side support for opaque enrollment. …
=> [PM-18993] Opaque enrollment

libs/auth/src/angular/two-factor-auth/two-factor-auth.component.ts
https://bitwarden.atlassian.net/browse/PM-19086
To fix the extension's 2FA WebAuthn response processing as it was pulling from the incorrect property and was always appearing as null.  This only revealed itself when a higher priority 2FA method (Org Duo) was configured b/c otherwise the child `TwoFactorAuthWebAuthn` component would trigger the submit once it became active. 
Before:
https://github.com/user-attachments/assets/12ba4306-50a8-4c49-a521-574931e76264
After: 
https://github.com/user-attachments/assets/27df6b65-6278-435a-a951-4b2ba6110f4c …
=> Auth/PM-19086 - UI Refresh - Extension WebAuthn 2FA - fix WebAuthn response processing

apps/browser/src/autofill/background/overlay.background.spec.ts, apps/browser/src/autofill/deprecated/background/overlay.background.deprecated.spec.ts, apps/browser/src/vault/popup/components/vault-v2/vault-v2.component.html, apps/browser/src/vault/popup/components/vault-v2/vault-v2.component.ts, apps/browser/src/vault/popup/services/vault-popup-copy-buttons.service.ts, apps/web/src/app/vault/components/vault-items/vault-items.stories.ts, libs/angular/src/vault/components/icon.component.html, libs/angular/src/vault/components/icon.component.ts, libs/common/src/vault/icon/build-cipher-icon.spec.ts, libs/common/src/vault/icon/build-cipher-icon.ts
[PM-18946](https://bitwarden.atlassian.net/browse/PM-18946)
Improve the vault loading experience in the Browser extension for slower devices that have shown the vault rendering in chunks causing the UI to jump around. See commit messages for each change / reason.
> Using Chrome Performance tab to add artificial 20x CPU slowdown.
| <video src="https://github.com/user-attachments/assets/25ebd447-98cc-42b1-9e24-f95bc7303c50" /> | <video src="https://github.com/user-attachments/assets/72473b61-f150-402c-a8d9-a7b390c1d126" /> |
- Used …
=> [PM-18946] Improve Vault loading experience

libs/common/src/services/api.service.ts
[PM-19209](https://bitwarden.atlassian.net/browse/PM-19209)
fix : updating error string for new device response from server.
We are currently using a brittle string comparison to know that we need to accomplish new device verification. The error string response was changed and that was causing an error where a user wasn't given the option to login with a new device, but were just given an error toast.
https://github.com/user-attachments/assets/878e39c3-7ab6-4e70-a58e-68c52f89fe87
https://github.com/user-attachments/assets/b0b95830-ed76-4cdc-a68b-d54de8b2c690
https://github.com/user-attachments/assets/05938983-0eaf-43ef-a12b-ed53549803b1
https://github.com/user-attachments/assets/5c6a255e-78a9-4f2b-8438-5177783b3247
- All formatters and local linters …
=> [PM-19209] Update New device verification error response expectation

libs/common/src/services/api.service.ts
Reverts bitwarden/clients#13829
Does not support backwards compatibility.
=> Revert "[PM-19209] Update New device verification error response expectation"

apps/browser/src/autofill/content/content-message-handler.ts
[PM-18895](https://bitwarden.atlassian.net/browse/PM-18895)
When the extension is first installed or enabled it can occur that events occur before the `windowMessageHandlers` is defined. The variable is hoisted but falls into the temporal dead zone as it is accessed before initialized.
- Moving the `windowMessageHandlers` variable above event listeners solves the issue.
Uninitialized error:
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or …
=> [PM-18895] Message handlers hoisting

apps/browser/src/background/main.background.ts, apps/browser/src/background/runtime.background.ts, apps/browser/src/platform/services/browser-initial-install.service.ts, libs/common/src/platform/state/state-definitions.ts
https://bitwarden.atlassian.net/browse/PM-14012
https://github.com/bitwarden/clients/issues/11694
We're still seeing a bunch of unexpected "Getting start" screens for the extension in safari. Currently the reports seem to be scoped to just happening when the application is updated.
It seems like Safari sends an unexpected "install" browser event in update. We hook into the install event for detecting first time installs to show the "Getting started" screen.
To my knowledge there isn't a great way to fix this. What I've done on this PR is implement a simple boolean value in state that is set when the screen is shown the first time. That bit is checked _before_ showing the screen and so when it is true the screen never shows.
There is one limitation, which you can observe in the demos …
=> fix: save indication of browser installation to storage

apps/web/src/app/auth/recover-two-factor.component.spec.ts, apps/web/src/app/auth/recover-two-factor.component.ts, apps/web/src/app/auth/settings/two-factor/two-factor-setup.component.ts, libs/common/src/abstractions/api.service.ts, libs/common/src/auth/models/request/two-factor-recovery.request.ts, libs/common/src/enums/feature-flag.enum.ts, libs/common/src/services/api.service.ts
https://bitwarden.atlassian.net/browse/PM-18175
Removed the `RecoveryCodeLogin` feature flag.
This also allowed removal of the entire obsolete flow that `POST`ed a separate request to the server to initiate the recovery process, since we are now leveraging our normal authentication flows.
See corresponding server PR: https://github.com/bitwarden/server/pull/5513.
https://github.com/user-attachments/assets/3359353c-e282-424d-9e5b-53447a605d03
- Updated …
=> [PM-18175] Remove two factor recovery feature flag and old recovery flow

libs/auth/src/common/abstractions/login-strategy.service.ts, libs/auth/src/common/login-strategies/base-login.strategy.spec.ts, libs/auth/src/common/login-strategies/base-login.strategy.ts, libs/auth/src/common/login-strategies/opaque-login.strategy.ts, libs/auth/src/common/login-strategies/password-login.strategy.spec.ts, libs/auth/src/common/login-strategies/password-login.strategy.ts, libs/auth/src/common/services/login-strategies/login-strategy.service.ts
https://bitwarden.atlassian.net/browse/PM-19273
`loginStrategyService.makePrePasswordLoginMasterKey` is no longer called with a null kdfConfig. Make that parameter required and remove dead code. Also move the method onto the base login strategy, as it is now only used by subclasses of that class.
- 📝 …
=> [PM-19273] [opaque] LoginStrategyService - refactor makeprepasswordloginmasterkey

apps/cli/src/service-container/service-container.ts, apps/web/src/app/auth/settings/change-password.component.ts, libs/auth/src/common/login-strategies/password-login.strategy.ts, libs/auth/src/common/services/login-strategies/login-strategy.service.spec.ts, libs/common/src/auth/opaque/default-opaque-key-exchange.service.ts, libs/common/src/auth/opaque/models/cipher-configuration.ts, libs/common/src/auth/opaque/opaque-key-exchange.service.ts, libs/key-management/src/index.ts, libs/key-management/src/models/kdf-config.ts
KDF config is in MiB while the KSF config is directly referencing argon2's parameters (KiB). This also changes the opaque service api to take an entire cipher configuration instead of the argon config.
- 🤔 …
=> Fix unit conversion bug

libs/common/src/enums/feature-flag.enum.ts
[PM-19342](https://bitwarden.atlassian.net/browse/PM-19342)
Adding Feature Flag for Onboarding Nudges  …
=> [PM-19342] Onboarding Nudges Feature Flag

apps/desktop/src/vault/app/vault/vault-items.component.ts, apps/desktop/src/vault/app/vault/vault.component.ts, apps/desktop/src/vault/app/vault/view.component.ts, libs/angular/src/vault/components/vault-items.component.ts, libs/angular/src/vault/components/view.component.ts
[PM-19032](https://bitwarden.atlassian.net/browse/PM-19032)
Stacking on top of @shane-melton's [previous PR](https://github.com/bitwarden/clients/pull/13681) so the diff is a little be easier to differentiate 
- The electron app uses [electron-store](https://github.com/sindresorhus/electron-store) as a way to store the local data on a users computer. This is stored in a JSON file where the app reads and writes. 
- This package uses a handful of other packages, one of which handles the JSON file. To update the file, it creates a copy of the current JSON file, updates the contents and then saves the copy. Then it overwrites the existing file. There could be some timing issues our close read/writes here but I was not able to confirm. 
- The vault list and view components were using …
=> [PM-19032] Live Sync on Desktop

apps/browser/src/tools/popup/settings/about-dialog/about-dialog.component.html, apps/web/src/app/auth/settings/emergency-access/emergency-access.component.html
https://bitwarden.atlassian.net/browse/CL-611
Resolves some more whitespace issues …
=> [CL-611] Fix whitespaces for about dialog & emergency access

libs/common/src/platform/notifications/internal/default-notifications.service.spec.ts, libs/common/src/platform/notifications/internal/default-notifications.service.ts
https://bitwarden.atlassian.net/browse/PM-19377
Lowers notifications to only connect when the user is unlocked. We do eventually want users to connect to notifications while locked as well but right now this causes an increased load on us which degrades the experience for everyone. This is particularly bad because while the code here is designed to NOT reconnect (the most costly thing) during a `Unlocked` -> `Locked` state it still does because we do a process reload during the lock process. Which means this code gets completely destroyed. Small win, it did do the reconnect from pure reactive means and not needing to be called manually so I guess that is nice. Connecting to notifications through web push will be coming to the browser extension very soon and that should help us a lot here. …
=> Switch Notifications to only connect on unlocked

apps/browser/src/autofill/content/components/notification/button-row.ts, apps/browser/src/autofill/content/notification-bar.ts
https://bitwarden.atlassian.net/browse/PM-19361
All accounts have a default `No folder` which has a null id. This folder is shown within the folders section of the vault and even if deleted, the `No folder` option will persist which gives me confidence to remove the default No folder insertion. 
- Remove default folder option
- Edit iFrame height
- 👍 …
=> PM-19361 Notification bar dropdown folder component displays "No Folder" twice

apps/web/src/app/auth/settings/security/device-management.component.ts
Follow up from feedback for https://bitwarden.atlassian.net/browse/PM-18757
Checks the device `id` and `creationDate` for empty strings (or any falsey values) since they are strings (defined in `libs/common/src/auth/abstractions/devices/views/device.view.ts`). …
=> Check device id and creationDate for falsey values

apps/browser/src/vault/popup/settings/archive.component.html, libs/common/src/vault/services/cipher.service.ts
[PM-19339](https://bitwarden.atlassian.net/browse/PM-19339)
- Fix header spacing on the Archive items page
- Fix cipher archivedDate being lost on cipher modification …
=> [PM-19339] Innovation Archive - Extension cleanup

apps/web/src/app/billing/shared/adjust-payment-dialog/adjust-payment-dialog.component.html, apps/web/src/app/billing/shared/adjust-payment-dialog/adjust-payment-dialog.component.ts, libs/angular/src/billing/components/manage-tax-information/manage-tax-information.component.ts
https://bitwarden.atlassian.net/browse/PM-19347
This PR hides the bank account option for a provider on the Adjust Payment Dialog when the provider's saved tax information is not within the United States.
It also resolves an issue where saving the tax information form without changing it results in a malformed request. 
https://github.com/user-attachments/assets/ba1d89de-347e-4ac7-af19-11d2f34a30ac …
=> [PM-19347] Hide bank account for provider when initial tax tax information is non-US

apps/browser/src/auth/popup/components/set-pin.component.html, apps/browser/src/vault/popup/components/at-risk-carousel-dialog/at-risk-carousel-dialog.component.html, apps/desktop/src/auth/components/set-pin.component.html, apps/desktop/src/auth/delete-account.component.html, apps/web/src/app/admin-console/organizations/settings/account.component.html, apps/web/src/app/admin-console/organizations/settings/components/delete-organization-dialog.component.html, apps/web/src/app/auth/settings/account/change-email.component.html, apps/web/src/app/auth/settings/emergency-access/confirm/emergency-access-confirm.component.html, apps/web/src/app/auth/settings/emergency-access/takeover/emergency-access-takeover.component.html, apps/web/src/app/auth/settings/security/api-key.component.html, apps/web/src/app/auth/settings/security/security-keys.component.html, apps/web/src/app/auth/settings/security/security-keys.component.ts, apps/web/src/app/tools/send/send.component.html, bitwarden_license/bit-web/src/app/secrets-manager/shared/dialogs/bulk-confirmation-dialog.component.html, libs/importer/src/components/dialog/import-error-dialog.component.html, libs/vault/src/cipher-form/components/custom-fields/add-edit-custom-field-dialog/add-edit-custom-field-dialog.component.html, libs/vault/src/components/add-edit-folder-dialog/add-edit-folder-dialog.component.html
https://bitwarden.atlassian.net/browse/CL-614
Resolves more spacing issues.
- Updates all dialogs to use `ng-container bitDialogFooter` which applies flex and gap.
- Updates api key buttons to have spacing.
- Updates send status icons to have appropriate spacing. …
=> [CL-614] More spacing fixes

apps/browser/src/_locales/bg/messages.json
https://bitwarden.atlassian.net/browse/PM-19435
Shorten appName for Bulgarian translation as that apparently is blocking submission to Opera …
=> [PM-19435] Opera extension will not upload to store due to Short Name over 12 characters 

apps/browser/src/manifest.json
https://bitwarden.atlassian.net/browse/PM-19435
We are unable to upload the Opera extension due to it not liking the fact that our placeholder `__MSG_appName__` is over 12 characters. …
=> Removed translation to upload to Opera.

apps/web/src/app/admin-console/organizations/manage/group-add-edit.component.html, apps/web/src/app/admin-console/organizations/manage/group-add-edit.component.ts, libs/common/src/enums/feature-flag.enum.ts
https://bitwarden.atlassian.net/browse/PM-18523
> Only display the external ID in the group dialog if it has been set up and configured through BWDC or the API. 
Group **with** External ID: 
Group **without** External ID:
- ❓ …
=> [PM-18523] Make the External ID in the Group dialog conditional

apps/browser/src/manifest.json, apps/browser/src/manifest.v3.json
https://bitwarden.atlassian.net/browse/PM-19435
In order to address an issue that prevents Opera extensions from being uploaded, we must ensure that the `short_name` placeholder (not the localized value) is less than 12 characters.  Rather than shorten the placeholder, we have opted to not localize this value until Opera has address the underlying problem.
We are tracking internally the work to add it back in https://bitwarden.atlassian.net/browse/PM-19610. …
=> [PM-19435] Update extension short name to no longer be localized

libs/common/src/vault/services/cipher.service.spec.ts, libs/common/src/vault/services/cipher.service.ts
https://bitwarden.atlassian.net/browse/PM-19359
For servers with key encryption enabled, this PR prevents users without viewPassword access from migrating to cipher key encryption if the cipher hasn't yet been migrated. …
=> [PM-19359] - Prevent limited access users from migrating to cipher key encryption

apps/browser/src/_locales/en/messages.json, apps/browser/src/vault/popup/components/at-risk-carousel-dialog/at-risk-carousel-dialog.component.html
[PM-14426](https://bitwarden.atlassian.net/browse/PM-14426) parent ticket
- [PM-19004](https://bitwarden.atlassian.net/browse/PM-19004) - Pause after image alt text for screen readers
- [PM-19298](https://bitwarden.atlassian.net/browse/PM-19298) - Add `data-testid` to carousel button …
=> [PM-14426] At-risk password carousel fixes

libs/tools/export/vault-export/vault-export-core/src/services/individual-vault-export.service.ts
https://bitwarden.atlassian.net/browse/PM-19582
While testing the changes made with https://github.com/bitwarden/clients/pull/13842, QA discovered that the filename extensions weren't set properly. They defaulted to `.csv` even if `.json` was selected. This only occurred on individual vault exports.
- 📝 …
=> [PM-19582] Set correct filename extensions on vault-export

libs/vault/src/cipher-form/cipher-form.mdx, libs/vault/src/cipher-form/cipher-form.stories.ts
[CL-550](https://bitwarden.atlassian.net/browse/CL-550)
This PR updates the story for the cipher form to more closely reflect the scope of the component. As I made spacing updates in a previous PR, I noticed the stories each included an optional submit button that is not actually part of the component, which led to some visual spacing discrepancies that looked like bugs. This PR removes the submit buttons from all stories except for a dedicated story for showcasing the form with the optional submit button and some additional bespoke spacing. The intent is that the primary stories reflect only the component, but that we still have one story for showing the composed-with-button version. I also renamed the default story to match the "mode" names of the other stories for clarity.
| Before | …
=> [CL-550] Update cipher form story

apps/browser/src/auth/popup/extension-anon-layout-wrapper/extension-anon-layout-wrapper.component.html, apps/browser/src/auth/popup/extension-anon-layout-wrapper/extension-anon-layout-wrapper.component.ts, apps/browser/src/auth/popup/extension-anon-layout-wrapper/extension-anon-layout-wrapper.stories.ts, libs/auth/src/angular/anon-layout/anon-layout.component.html, libs/auth/src/angular/anon-layout/anon-layout.component.ts, libs/auth/src/angular/anon-layout/anon-layout.stories.ts
[PM-19654](https://bitwarden.atlassian.net/browse/PM-19654)
Adding the option to hide icon in the extension anon layout wrapper for the upcoming intro carousel component in the vault nudges epic.
- 🤔 …
=> [PM-19654] add hideIcon option to extension anon layout

libs/common/src/enums/feature-flag.enum.ts
Completed the grouping of feature flags started in https://github.com/bitwarden/clients/pull/13809, moving the rest into their owning teams.
See https://github.com/bitwarden/server/pull/5574 for corresponding work on server.
- ❓ …
=> Complete feature flag grouping by team

libs/common/src/enums/feature-flag.enum.ts
https://bitwarden.atlassian.net/browse/PM-19679
Removes the `unauth-ui-refresh` feature flag from clients now that all clients are live with the new UI 🎉 .
This was no longer being referenced in code once we removed the route swaps with https://github.com/bitwarden/clients/pull/13645 and https://github.com/bitwarden/clients/pull/13928 for 2FA.
- 👍 …
=> [PM-19679] Remove unauth-ui-refresh flag from clients

libs/tools/export/vault-export/vault-export-core/src/services/individual-vault-export.service.ts, libs/tools/export/vault-export/vault-export-core/src/services/org-vault-export.service.ts
https://bitwarden.atlassian.net/browse/PM-19724
When exporting account/password-protected exports, the filename generated for the export file, did not contain `_encrypted_`, like it did before merging https://github.com/bitwarden/clients/pull/13842 …
=> [PM-19724] Fix filename not including "_encrypted_" when selecting encrypted vault exports

apps/desktop/src/autofill/services/desktop-autofill.service.ts
https://bitwarden.atlassian.net/browse/PM-19138
This PR removes .then.catch. …
=> PM-19138: Add support for async-await-catch

apps/browser/src/vault/popup/components/vault-v2/vault-v2.component.ts, apps/browser/src/vault/popup/services/vault-popup-items.service.ts, apps/browser/src/vault/popup/services/vault-popup-list-filters.service.ts, libs/common/src/vault/abstractions/cipher.service.ts, libs/common/src/vault/services/cipher.service.ts
https://bitwarden.atlassian.net/browse/PM-18869
This PR fixes an issue where the vault list wasn't updating after favoring/unfavoriting an item. This was due a few places attempting to call `cipherService.cipherViews$` when it was `null`. Accounting for this fixed the issue.
https://github.com/user-attachments/assets/f3932154-7eed-49a4-8cef-ca7cfd587345
https://github.com/user-attachments/assets/55a39f20-3c07-4d2b-9294-1355dce831a0
- Updated any …
=> [PM-18869][defect] - browser - vault list not updating after favorite/unfavorite

apps/web/src/app/vault/components/vault-items/vault-items.component.html, apps/web/src/app/vault/components/vault-items/vault-items.component.ts
http://bitwarden.atlassian.net/browse/PM-19744
Fixes the bulk menu to look at the new featureflagged permissions logic.
https://github.com/user-attachments/assets/40f33c8e-436d-4508-ab70-d454583858f8
- 🤔 …
=> [PM-19744] Fix bulk menu

libs/components/src/menu/menu-trigger-for.directive.ts
https://bitwarden.atlassian.net/browse/CL-617
This PR updates the fallback position config to ensure that the menu renders above the trigger.
|Before|After|
---|---
|![Screenshot 2025-03-27 at 5 00 03 PM](https://github.com/user-attachments/assets/4731ef1a-c20c-43da-adc1-bcd8f77a9f51)|![Screenshot 2025-03-27 at 4 59 23 PM](https://github.com/user-attachments/assets/9718fdfd-4e77-4214-ab58-7fc7f760459b)| …
=> [PM-617] - Menu component does not open to top of triggering elements at the bottom of a viewport 

libs/tools/export/vault-export/vault-export-ui/src/components/export.component.ts
https://bitwarden.atlassian.net/browse/PM-19775
The text within the export callout, wasn't set properly when switching between MyVault and an organization and back, as the filter only removed the zip-format option, but didn't set a new value.  …
=> [PM-19775] Vault export: Set selected format to json, when the zip format option is removed

apps/browser/src/vault/popup/components/vault-v2/view-v2/view-v2.component.html, apps/browser/src/vault/popup/components/vault-v2/view-v2/view-v2.component.spec.ts, apps/browser/src/vault/popup/components/vault-v2/view-v2/view-v2.component.ts, apps/browser/src/vault/popup/settings/trash-list-items-container/trash-list-items-container.component.html, apps/browser/src/vault/popup/settings/trash-list-items-container/trash-list-items-container.component.ts, apps/cli/src/commands/restore.command.ts, apps/cli/src/oss-serve-configurator.ts, apps/cli/src/vault.program.ts, apps/desktop/src/vault/app/vault/view.component.html, apps/desktop/src/vault/app/vault/view.component.ts, libs/angular/src/vault/components/view.component.ts
http://bitwarden.atlassian.net/browse/PM-19746
https://bitwarden.atlassian.net/browse/PM-19748
Adds new permission logic to vault item trash container in the extension. Fixes permission model for CLI and Desktop
https://github.com/user-attachments/assets/62201706-15a5-4b01-b735-7f889bb0baf1
https://github.com/user-attachments/assets/a93c469a-ec30-4dcb-b973-6843d4ce422d …
=> [PM-19746] Add new permission check to browser

apps/desktop/src/vault/app/vault/vault.component.html, apps/desktop/src/vault/app/vault/vault.component.ts, libs/angular/src/vault/components/view.component.ts
https://bitwarden.atlassian.net/browse/PM-432
This PR triggers a password re-prompt when viewing a MP enabled cipher in the desktop client and retains the prompt while the cipher is being viewed.
https://github.com/user-attachments/assets/13888a50-bb93-4b85-aa4d-28a41b4b5e92 …
=> [PM-432] - Protect entire item when Master Password Re-prompt is selected - desktop

libs/components/src/menu/menu-trigger-for.directive.ts
This reverts commit b0ccadcc0f11594351484a2b6eab5556b8580c38.
[PM-19847](https://bitwarden.atlassian.net/browse/PM-19847)
[CL-617](https://bitwarden.atlassian.net/browse/CL-617)
PR #14040 introduced a regression to the default positioning of some menus, which were reported as bugs in our latest `main` build. Design has indicated that the new regressions are less desirable than the original issue that the PR fixed, so we are reverting the PR to get back to production behavior and will re-address the original ticket separately.
| Before Revert | After Revert |
| ![Screenshot 2025-04-03 at 1 59 02 PM](https://github.com/user-attachments/assets/778f008d-4546-49fe-a52d-df8ff2cec1b5) |  ![Screenshot 2025-04-03 at 2 00 …
=> Revert "fix menu trigger fallback position (#14040)"

libs/importer/src/components/import.component.html, libs/importer/src/models/import-options.ts, libs/importer/src/services/import.service.ts
https://bitwarden.atlassian.net/browse/PM-19468
The ChromeCsvImporter already takes care of imports from Chrome, Vivaldi, Opera and Edge. 
The first three are also selectable within the import format options, but Edge isn’t. To make this more obvious and easier for users, we want to add Edge as an import option. …
=> [PM-19468] Add Edge (csv) as a import format option

apps/browser/src/platform/services/local-backed-session-storage.service.ts, libs/angular/src/platform/abstractions/view-cache.service.ts, libs/auth/src/angular/login-via-auth-request/AUTH_REQUEST_LOGIN_README.md, libs/auth/src/angular/login-via-auth-request/auth_request_login_readme.md, libs/auth/src/angular/login-via-auth-request/login-via-auth-request.component.html, libs/auth/src/angular/login-via-auth-request/login-via-auth-request.component.ts, libs/auth/src/common/services/auth-request/default-login-via-auth-request-cache.service.spec.ts, libs/auth/src/common/services/auth-request/default-login-via-auth-request-cache.service.ts, libs/common/src/auth/models/view/login-via-auth-request.view.ts
https://bitwarden.atlassian.net/browse/PM-19380
* Fixed standard login with device auth request flow for when the extension is closed.
* Restructured code to be easier to follow.
* Added documentation for login with auth request process.
Recordings of 9 Flows
Browser
* Login with device
* TDE User approve from another device
* TDE User admin approval
Web
* Login with device
* TDE User approve from another device
* TDE User admin approval
Desktop
* Login with device
* TDE User approve from another device
* TDE User admin approval
https://drive.google.com/drive/folders/17pAw4ijHzO-dxZIx2XCD0wz38vt96GgP?usp=sharing
These flows were also tested on main, but there are no recordings of those for time savings sake. They are working as far as my domain of testing is concerned.
- Contributor …
=> feat(device-approval-persistence): [PM-19380] Device Approval Persistence

libs/vault/src/cipher-view/cipher-view.component.html, libs/vault/src/cipher-view/login-credentials/login-credentials-view.component.html
[PM-19906](https://bitwarden.atlassian.net/browse/PM-19906)
Use appStopClick to prevent default navigation event which caused the extension to flash before navigating.
| <video src="https://github.com/user-attachments/assets/71953a2a-1c09-47f6-a5d4-5e18cb297269" /> | <video src="https://github.com/user-attachments/assets/fc4e4dc8-f4d3-4e43-a265-eae98a94679f" /> | …
=> [PM-19906] Add appStopClick to prevent default navigation

apps/desktop/desktop_native/macos_provider/src/lib.rs, apps/desktop/macos/autofill-extension/CredentialProviderViewController.swift, apps/desktop/package.json
https://bitwarden.atlassian.net/browse/PM-19424
This PR adds support for tracking the IPC connection and exits the passkey flow if the IPC connection is dropped (e.g. the bitwarden app is terminated).
I originally tried a callback based approach, but I kept running into rust-panics so opted for this simpler approach. …
=> PM-19424: React to IPC disconnect

bitwarden_license/bit-web/src/app/admin-console/providers/providers.component.html
[PM-17361](https://bitwarden.atlassian.net/browse/PM-17361)
This is another step in removing references to bootstrap.
Before:
After: …
=> [PM-17361] Migrating providers.component.html to TW

libs/components/src/badge/badge.component.ts, libs/components/src/badge/badge.stories.ts
[CL-421](https://bitwarden.atlassian.net/browse/CL-421)
Add new notification variant to bitbadge …
=> [CL-421] add new notification variant to badge

apps/desktop/src/app/app.component.ts, apps/desktop/src/modal/passkeys/create/fido2-create.component.html, apps/desktop/src/modal/passkeys/create/fido2-create.component.ts, apps/desktop/src/modal/passkeys/fido2-vault.component.html, apps/desktop/src/modal/passkeys/fido2-vault.component.ts, apps/desktop/src/scss/header.scss, libs/common/spec/fake-account-service.ts, libs/common/src/auth/abstractions/account.service.ts, libs/common/src/auth/services/account.service.spec.ts, libs/common/src/auth/services/account.service.ts
[PM-19607](https://bitwarden.atlassian.net/browse/PM-19607)
Remove the account switcher and blue heading from the pop up windows for the create and select passkey user flow.  
To test: 
* Visit https://webauthn.io
To view available keys:
* In the input field click the key and choose Bitwarden
* You will see the updated popout without the blue header and account switcher.
* Make sure you can move the window around your screen.
To create a new key:
* Fill in the input and click `Register`
* You will see the updated popout without the blue header and account switcher.
* Make sure you can move the window around your screen.
https://github.com/user-attachments/assets/394d980f-8a54-4391-b41f-be3316ff7764
- …
=> Hide blue header for passkey popouts

libs/components/src/button/button.mdx, libs/components/src/button/button.stories.ts
https://bitwarden.atlassian.net/browse/CL-635
Add a story and docs to promote consistent button icon spacing …
=> adds button story and docs for button with icon spacing

bitwarden_license/bit-web/src/app/tools/access-intelligence/critical-applications.component.ts
https://bitwarden.atlassian.net/browse/PM-19470
The `Mark Critical Apps` button does not redirect to the right location.
This should now redirect to the `Risk Insights` page and launch the `All Applications` tab
No screen shots at this time. …
=> [PM-19470] Redirect to the first tab

libs/components/src/radio-button/radio-button.component.ts
https://bitwarden.atlassian.net/browse/CL-567
Remove margin-top from hint text when hint is rendered under a radio button label …
=> remove hint margin in radio button

apps/web/src/app/tools/reports/pages/weak-passwords-report.component.html, apps/web/src/app/tools/reports/pages/weak-passwords-report.component.ts
https://bitwarden.atlassian.net/browse/PM-13404
Fix the sorting in the weak passwords report.
It should sort by alphabet - ascending => a -> z and descending => z - a
Ascending order:
Descending order:
- 🤔 …
=> [PM-13404] Weak passwords report - sort on Weakness column

apps/web/src/locales/en/messages.json
[PM-20126](https://bitwarden.atlassian.net/browse/PM-20126)
Remove duplicate message catalog keys:
```
atRiskMembersWithCount
atRiskMembersDescription
atRiskMembersDescriptionWithApp
singleSignOn
```
- 🤔 …
=> [PM-20126] Bugfix - Remove duplicate message catalog keys

apps/desktop/desktop_native/objc/src/native/utils.m
This PR fix a bug in the base64url decoding when syncing credentials to MacOS. …
=> Fix base64url decode on MacOS passkeys

.github/CODEOWNERS
Follow-up to: https://bitwarden.atlassian.net/browse/PM-17665
https://github.com/bitwarden/clients/pull/13285#discussion_r2035344712
This just moves the codeownership down to KM, and changes the comment to reflect that it's nodecryptofunction service. …
=> Move nodecryptofunctionservice codeownership

.github/DISCUSSION_TEMPLATE/password-manager.yml, .github/DISCUSSION_TEMPLATE/secrets-manager.yml
[PM-18897](https://bitwarden.atlassian.net/browse/PM-18897)
@dwbit requested this copy update due to Topic Area stating the same. …
=> [PM-18897] Remove duplicated copy in GitHub Discussion templates

libs/components/src/form-control/form-control.component.html
https://bitwarden.atlassian.net/browse/CL-567
Remove margin top from checkbox hint text …
=> remove margin from checkbox hint

libs/auth/src/angular/login/login.component.ts
https://bitwarden.atlassian.net/browse/PM-20174
In #13391, we added a check on email input to persist the email field to state if valid.  However, the validation check that was added both validated the email address _and_ displayed errors in the UI.
It is the desired experience that a user not see any validation errors until they click "Submit" (here "Continue" or "Login with SSO").
This PR refactors the `validateEmail()` method to extract the checking for validity into a new `emailIsValid()` method, which we can then call from both `validateEmail()` and from the email input.
https://github.com/user-attachments/assets/acc8f6b8-4599-4b32-8529-5bb6cab71233
https://github.com/user-attachments/assets/cfa52ce4-1533-4135-81a3-2751e5a4da93
- All formatters and …
=> [PM-20174] Do not show validation errors on email input on LoginComponent

.github/workflows/build-web.yml
https://bitwarden.atlassian.net/browse/PM-19254
This PR makes two changes to the workflow for building the web client, to allow QA to test the docker image for a community PR:
1. Changes the check for `pull_request` trigger to also include `pull_request_target`, as we are now triggering this workflow from `pull_request_target` and want to treat it like a PR.
2. If we are triggering this from a fork, include the fork `username/repo` in the image tag, so that QA can disambiguate this tag when finding the image in ACR.
For example, for a PR from the `test-pr-changes` branch of the `odieman44/bitwarden-test` fork:
And from a branch that includes symbols - `branch%symbols$test`
- Written new unit and / or …
=> [PM-19254] Update image tag generation for builds from forked PRs

apps/browser/src/autofill/background/overlay.background.spec.ts, apps/browser/src/autofill/background/overlay.background.ts, apps/browser/src/autofill/deprecated/background/overlay.background.deprecated.spec.ts, apps/browser/src/autofill/deprecated/background/overlay.background.deprecated.ts
[PM-19149](https://bitwarden.atlassian.net/browse/PM-19149)
The message `inlineAutofillMenuRefreshAddEditCipher` is sent to the extension runtime in several places, but no longer consumed anywhere. It looks like it was originally used in `apps/browser/src/vault/popup/components/vault/add-edit.component.ts` but was not carried over when the extension refresh work migrated over to `apps/browser/src/vault/popup/components/vault-v2/add-edit/add-edit-v2.component.ts`:
https://github.com/bitwarden/clients/pull/7773/files#diff-799cbe1a807467982798206cb38e1caf4b3275c7146a95f9d1e4340da28b805cR387-R391
Since we no longer consume it, remove message emit. Vault team added to confirm intent of add-edit-v2 component in regards to this event.
- 📝 (`:memo:`) or …
=> [PM-19149] Remove inlineAutofillMenuRefreshAddEditCipher message

.github/workflows/publish-web.yml
https://bitwarden.atlassian.net/browse/BRE-461
Add trigger for self-host unified build in publish web workflow. …
=> [BRE-461] Implement new self-host docker unified release process

apps/web/src/locales/en/messages.json, bitwarden_license/bit-web/src/app/tools/access-intelligence/risk-insights-loading.component.html, bitwarden_license/bit-web/src/app/tools/access-intelligence/risk-insights.component.html
https://bitwarden.atlassian.net/issues/PM-20118?filter=11401
Two changes:
1. Capitalize "Risk Insights" (for english)
2. Hide the "Data refresh..." block until there is data to be displayed
- 🤔 …
=> [PM-20118] Capitalize risk insights

libs/admin-console/src/common/collections/services/default-collection.service.ts
[PM-19538](https://bitwarden.atlassian.net/browse/PM-19538)
`encryptedCollectionsWithKeys` is re-subscribed to for every subscription to `decryptedCollectionViews$()` which in turn subscribes to `keyService.orgKeys$` repeatedly causing delays for users with many (dozens) of organizations. Adding a `shareReplay` to this internal observable ensures we're not repeatedly decrypting orgKeys for every subscription to decrypted collections.
- Updated any …
=> [PM-19538] Add shareReplay to internal orgKeys subscription

apps/browser/src/popup/app-routing.module.ts
[PM-20236](https://bitwarden.atlassian.net/browse/PM-20236)
update routing so path is not saved during popout. If a user pops the extension out and selects `Log In` and/or logs in, the next time the extension is open it should not show the intro carousel
User pops out extension and navigates to login
https://github.com/user-attachments/assets/6ee0e0c6-06d3-494d-9c98-9c10c74e8af8
User pops out extension and logs into account
https://github.com/user-attachments/assets/875c74b5-6adc-464e-a81a-149977af821e
- …
=> [PM-20236] intro carousel popout login dismiss

libs/auth/src/angular/login/login.component.ts
https://bitwarden.atlassian.net/browse/PM-20287
We currently set the email state when a there is input on the email or remember me form fields.  However, this doesn't work if the user has "Remember Me" selected and attempts a subsequent login _without editing the email address_.  This never fires the email input event and so the `loginEmail` is never persisted to state for that login flow.
This change sets the `loginEmail` if an email is remembered, ensuring that the field is initialized in sync with the remembered email if one exists.
https://github.com/user-attachments/assets/58550c8e-f3b1-4754-b242-f9ce62669d24
- Protected functional …
=> [PM-20287] Initialize login email state when email is remembered

libs/common/src/platform/notifications/internal/worker-webpush-connection.service.ts
https://bitwarden.atlassian.net/browse/PM-18980
`userVisisbleOnly` should only be true when the reception of the notification will result in UI visible to the user ([see docs](https://developer.mozilla.org/en-US/docs/Web/API/PushSubscriptionOptions/userVisibleOnly)). Many of our notifications do not do that and instead result in us syncing data behind the scenes to keep the client up to date with the latest information in case the client goes offline.
- …
=> [PM-18980] Switch userVisibleOnly to `false`

apps/desktop/src/main/window.main.ts
https://bitwarden.atlassian.net/browse/PM-19869
This PR reverts the event driven call to .show() to introduced in the Desktop Modal Experiment PR ([line](https://github.com/bitwarden/clients/pull/11484/files#diff-329e0465d1ce6029fa8b2d5138f854b6c3f39117e2fa55148a6062edce664c34R267))
When using the event, the bootstrap code that subscribes to "hide-to-tray" settings being loaded fired before this event, which caused the window to be hidden first, the shown again. This changes makes the operation sync, so the window is shown, then hidden. …
=> Revert event-driven .show, in order for bootstrap/hide-to-tray to work

bitwarden_license/bit-web/src/app/tools/reports/member-access-report/services/member-access-report.mock.ts, bitwarden_license/bit-web/src/app/tools/reports/member-access-report/services/member-access-report.service.spec.ts, bitwarden_license/bit-web/src/app/tools/reports/member-access-report/services/member-access-report.service.ts
https://bitwarden.atlassian.net/browse/PM-19810
In a member access report, when a user has no collections or groups, the record shows up the UI but not in the CSV file.
That's because the record is not included in the CSV export.
This PR should now take into account all those records without a collection or group and include them in the CSV export.
- …
=> [PM-19810] Member Access Report - CSV export fix

.github/CODEOWNERS
In #13750 we removed Platform from owning `Cargo.toml` so that Renovate can manage individual packages. 
However, we also need to remove Platform ownership from `Cargo.lock` in order to ensure that Platform is not asked to review every dependency update (e.g. https://github.com/bitwarden/clients/pull/12298). …
=> Remove Platform ownership of Cargo.lock on desktop_native

libs/tools/export/vault-export/vault-export-ui/src/components/export.component.ts
https://bitwarden.atlassian.net/browse/PM-20386
The export page for an organization should list out organizations in a drop down. That is missing.
If there are organizations, then the dropdown should render: (it may be disabled)
- ❓ …
=> [PM-20386] Export Org does not show org list

.github/workflows/build-cli.yml, .github/workflows/build-web.yml
https://bitwarden.atlassian.net/browse/PM-20431
Changes to code in bit-web should trigger the web build in CI.  See https://github.com/bitwarden/clients/pull/14324 for an example of a PR that should have triggered a web artifact build.
This matches what was done for the CLI here: https://github.com/bitwarden/clients/pull/9491. …
=> [PM-20431] Add bit-web to build-web workflow paths

apps/browser/src/platform/popup/view-cache/popup-view-cache.service.ts, apps/browser/src/platform/popup/view-cache/popup-view-cache.spec.ts, apps/browser/src/platform/services/popup-view-cache-background.service.ts, apps/browser/src/vault/popup/services/vault-popup-items.service.ts, apps/browser/src/vault/popup/services/vault-popup-list-filters.service.ts, libs/angular/src/platform/abstractions/view-cache.service.ts
[PM-20433](https://bitwarden.atlassian.net/browse/PM-20433)
#13742 introduced a change to prevent clearing the popup view cache when navigating within the vault to persist vault filters. This inadvertently prevents clearing the cipher form cache when the user clicks the back/cancel buttons.
To address this the view cache service was internally refactored to support an optional `persistNavigation` option. When present on a cached signal/form group, the view cache service will **NOT** clear the value on navigation events in the popup/foreground. The values are still cleared automatically after the 2-minute timer.
Example usage:
```ts
const cachedFilters = this.viewCacheService.signal<CachedFilterState>({
key: "vault-filters",
initialValue: {},
deserializer: (v) => v,
persistNavigation: …
```
=> [PM-20433] Fix clearing of cached cipher form 

apps/desktop/src/app/app.module.ts, apps/desktop/src/app/shared/shared.module.ts, apps/desktop/src/vault/app/vault/vault-filter/vault-filter.module.ts
https://bitwarden.atlassian.net/browse/PM-20448
Desktop imported `BrowserModule` & `BrowserAnimationModule` multiple times which can result in compile errors. Following the patterns used in our other clients this updates the BrowserModule import to only occur in `app.module`. …
=> [PM-20448] Only import BrowserModule once

libs/components/src/input/autofocus.directive.ts, libs/components/src/search/search.component.ts, libs/components/src/shared/focusable-element.ts
https://bitwarden.atlassian.net/browse/PM-19923
We have a directive called autofocus which serves to automatically focus a component when it is created. However certain "page level" components supports dynamically showing a loading state. This works by hiding the actual content and displaying a spinner on top of it.
In those scenarios elements like the `SearchComponent` which uses the autofocus directive are created before they are even in the DOM and certainly before they end up being visible.
This PR aims to solve this issue by changing the autofocus implementation to continually check focus conditions when angular change detection is run. In order to prevent repeat focus certain conditions apply. Such as only focusing once and making sure the element is visible before focusing.
- …
=> [PM-19923] Update autofocus directive to be more aggressive in focusing

libs/common/src/tools/send/services/send.service.ts
(no ticket)
The send service currently makes the encryption scheme fairly difficult to follow. This somewhat increases readability by adding some comments, and renaming "key" to "userkey", since the only key used here is the UserKey.
- ❓ …
=> Add comments to make send-service encryption more readable

apps/browser/src/autofill/background/notification.background.ts, libs/common/src/key-management/crypto/services/encrypt.service.implementation.ts, libs/common/src/key-management/crypto/services/encrypt.service.spec.ts
Looks like https://github.com/bitwarden/clients/pull/14080 forgot to take into account the feature-flag for blocking type0 encryption during merge conflict resolution. This adds it back and adds tests.
- 🤔 …
=> Fix type 0 not being blocked on key wrapping

libs/common/src/vault/services/cipher.service.ts
[PM-20573](https://bitwarden.atlassian.net/browse/PM-20573)
Remove dependency on cipher decryption keys
- It was not being used in the observable pipeline and causing multiple decryptions and can also block a vault from being viewed if `cipherDecryptionKeys$` throws.
This is the problematic account in the ticket but logging in successfully:
<video src="https://github.com/user-attachments/assets/13902486-f5d4-42cb-9eb4-c631cdf22562" />
- ❌ (`:x:`) or ⚠️ …
=> [PM-20573] Remove dependency on decryption keys

apps/web/src/app/billing/shared/payment-method.component.html
https://bitwarden.atlassian.net/browse/CL-661
Remove unused `payment_trigger_button`. It's not used in our own code or by stripe. …
=> Remove unused payment_trigger_button

apps/desktop/src/modal/passkeys/create/fido2-create.component.html, apps/desktop/src/modal/passkeys/fido2-vault.component.html, apps/desktop/src/scss/header.scss
[PM-20346](https://bitwarden.atlassian.net/browse/PM-20346)
Set the passkey header to be sticky in the modal for creating or selecting a passkey.
https://github.com/user-attachments/assets/272a830d-69c9-4e56-b285-4438f463d467
https://github.com/user-attachments/assets/916a3bb1-05b9-46b6-b500-0b4e79ddab05
- 📝 …
=> Make passkey header sticky

apps/desktop/desktop_native/build.js
https://bitwarden.atlassian.net/browse/PM-20597
We want the final binary to be copied to the `dist` folder even when we're compiling a specific target only, currently we're only doing it for the `cross-platform` command. 
To be able to do it without duplicating the targets array (which maps rust targets to node targets), I've extracted it to a shared object. …
=> [PM-20597] Fix linux desktop_native script

libs/common/src/key-management/crypto/services/encrypt.service.spec.ts
https://github.com/bitwarden/clients/pull/14371
Fixes build conflicts with:
https://github.com/bitwarden/clients/pull/14371
to save some re-reviews. …
=> [PM-20492] Remove direct key buffer access in encrypt service test

apps/browser/src/autofill/background/notification.background.ts, apps/browser/src/autofill/notification/bar.ts
https://bitwarden.atlassian.net/browse/PM-20546
When a user selects a vault and a folderId, open the add edit vault view to facilitate adding a new login with a vault
https://github.com/user-attachments/assets/3e4af163-aa77-4de9-9568-dbd9f7d69c9a …
=> PM-20546 pass folder to openAddEditVaultItemPopout

apps/web/src/app/admin-console/organizations/manage/events.component.html, apps/web/src/locales/en/messages.json
https://bitwarden.atlassian.net/browse/PM-20404
Internal feedback was that the term “real event logs” was confusing. We will update the copy on the informational callout and the upgrade prompt to remove references to that term.
Updated copy is shown in the annotated screenshot below:
Open Screenshot 2025-04-18 at 09.33.56.png
Screenshot 2025-04-18 at 09.33.56.png
These copy updates should show for both Free and Families organizations. 
“Upgrade to see event logs from your organization”
“Event logs are not stored for your organization. Upgrade to a Teams or Enterprise plan to get full access to organizations event logs.”
- Protected …
=> [PM-20404]Copy update: don't reference "real" event logs

apps/browser/src/autofill/content/components/notification/button-row.ts, apps/browser/src/autofill/content/components/notification/container.ts, apps/browser/src/autofill/content/components/notification/footer.ts, apps/browser/src/autofill/notification/bar.ts
[PM-20636](https://bitwarden.atlassian.net/browse/PM-20636)
GIVEN: the user is viewing the “Save login?” UI 
AND: the user is in only 1 organization, and that org has turned off the individual vault 
THEN: no vault select is displayed
WHEN: the user selects the “Save” action 
THEN: the “New item” form opens with relevant fields filled in (including folder if the user preselected a folder from the notification UI)
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more …
=> [PM-20636] Handle PersonalOwnership policy and vault selector with only one option

libs/auth/src/angular/login-decryption-options/login-decryption-options.component.ts, libs/auth/src/angular/login-via-auth-request/login-via-auth-request.component.ts, libs/auth/src/angular/login/login.component.ts, libs/auth/src/angular/password-hint/password-hint.component.ts
https://bitwarden.atlassian.net/browse/PM-20587
We are setting the `loginEmail` state before navigating the user to the login decryption options, so that we have the email available.  However, we were not `await`ing the call, which meant that it was not set in state when we need to access it on the routed component.  This resulted in a race condition and an error on the first attempt to navigate to the component.
We were setting the `loginEmail` state immediately before routing to the Login Decryption Options component, which felt a bit odd, since we weren't actually logging in (at this point we have already logged in).  It violated the assumptions of the state and meant that it was not cleared correctly - since clearing it is done only in the login success handler.
Instead of persisting …
=> [PM-20587] Fix unawaited calls to set login email

apps/browser/src/vault/popup/components/vault-v2/new-item-dropdown/new-item-dropdown-v2.component.html, apps/browser/src/vault/popup/settings/folders-v2.component.html, libs/tools/send/send-ui/src/new-send-dropdown/new-send-dropdown.component.html
https://bitwarden.atlassian.net/browse/PM-20511
Update extension header to use new small button variant …
=> Use small buttons in extension header

apps/browser/src/platform/sync/foreground-sync.service.spec.ts, apps/browser/src/platform/sync/foreground-sync.service.ts, apps/browser/src/platform/sync/sync-service.listener.spec.ts, apps/browser/src/platform/sync/sync-service.listener.ts, libs/common/src/platform/sync/core-sync.service.ts, libs/common/src/platform/sync/default-sync.service.spec.ts, libs/common/src/platform/sync/default-sync.service.ts, libs/common/src/platform/sync/sync.service.ts
https://bitwarden.atlassian.net/browse/PM-20032
Expose an option for optionally skipping the token refresh that is part of `fullSync`. Auth will likely want to take advantage of this for the initial login sync.  …
=> [PM-20032] Give option to skip token refresh on `fullSync`

apps/web/src/app/billing/members/free-bitwarden-families.component.html, apps/web/src/app/billing/settings/sponsored-families.component.html, apps/web/src/locales/en/messages.json
https://bitwarden.atlassian.net/browse/PM-21059
The purpose of this PR is to fix a grammatical error in the text displayed on the Free Bitwarden Families > Sponsored Families tab. Specifically, it updates the phrase "The Bitwarden for Families plan include:" to "The Bitwarden for Families plan includes:" by adding an 's' to the end of the word "include."
Additionally, this PR also updates the same incorrect text instance on the Password Manager (/vault) > Settings > Free Bitwarden Families page, ensuring consistency and correctness across both pages where the text appears.
This change improves the readability and accuracy of the content for users. …
=> [PM-21059] Fix Typo: Update 'include' to 'includes' on Free Bitwarden Families Sponsored Tab and Org Sponsored Page

apps/browser/src/vault/popup/components/vault-v2/vault-v2.component.html, apps/browser/src/vault/popup/components/vault-v2/vault-v2.component.ts
[PM-20423](https://bitwarden.atlassian.net/browse/PM-20423)
Update the `New Item` button in the browser empty vault to go directly to a `New Login` item page inside of a dropdown. This will be align closely to the flow in Web
https://github.com/user-attachments/assets/845eee96-4c5c-4b4d-b3ae-9dfa55a00401
- 📝 …
=> [PM-20423] Update Empty Vault Button on Browser to follow Web

libs/components/src/icon-button/index.ts, libs/vault/src/components/copy-cipher-field.directive.spec.ts, libs/vault/src/components/copy-cipher-field.directive.ts
[PM-20110](https://bitwarden.atlassian.net/browse/PM-20110)
When the `CopyCipherFieldDirective` is used with `BitIconButtonComponent` there is a conflict of managing the `disabled` attribute on the host element. This caused the UI to show the button as enabled when it was disabled under the hood.
Manually setting the disabled state of `BitIconButtonComponent` from the copy cipher directive resolves the issue.
Manually updating states of other components could lead to high maintenance costs down the road. Having two ( `BitIconButtonComponent` and `MenuItemDirective`) doesn't cross the threshold for me to refactor now but this could become cumbersome if more are added.
Disabled quick action buttons: …
=> [PM-20110] Disabled copy buttons on vault

apps/browser/src/vault/popup/components/at-risk-callout/at-risk-password-callout.component.ts, apps/web/src/app/auth/settings/emergency-access/view/emergency-view-dialog.component.spec.ts, libs/common/src/vault/tasks/services/default-task.service.spec.ts, libs/common/src/vault/tasks/services/default-task.service.ts, libs/vault/src/cipher-view/cipher-view.component.html, libs/vault/src/cipher-view/cipher-view.component.ts
[PM-21041](https://bitwarden.atlassian.net/browse/PM-21041)
Add `tasksEnabled$` as a dependency of `tasks$`/`pendingTasks$` observables to avoid attempting to fetch tasks for users that do not have the feature enabled for their organization. …
=> [PM-21041] Fix cipher view security tasks fetching

libs/vault/src/cipher-form/components/cipher-form.component.spec.ts, libs/vault/src/cipher-form/components/cipher-form.component.ts
[PM-21022](https://bitwarden.atlassian.net/browse/PM-21022)
When cloning a cipher, the `fido2Credentials` should not be carried to the newly created cipher.
- Set `fido2Credentials` to null whenever a cipher is cloned to ensure they are not copied over. 
|Browser|Web|Desktop|
|-|-|-|
|<video src="https://github.com/user-attachments/assets/326d3ebe-6482-46dc-883d-490742089108" />|<video src="https://github.com/user-attachments/assets/267eeb30-e488-4ec3-8ac1-1e352abc0fbc" />|<video src="https://github.com/user-attachments/assets/9626e805-46df-48e1-b099-537b52c2124f" /> …
=> [PM-21022] Remove fido2Credentials when cloning a cipher

apps/web/src/app/billing/members/add-sponsorship-dialog.component.html, apps/web/src/app/billing/members/add-sponsorship-dialog.component.ts, apps/web/src/app/billing/settings/sponsoring-org-row.component.html
https://bitwarden.atlassian.net/browse/PM-21114
https://bitwarden.atlassian.net/browse/PM-21073
https://bitwarden.atlassian.net/browse/PM-21094
https://bitwarden.atlassian.net/browse/PM-21113
1. This PR fixes an issue where submitting a sponsorship with more than 1000 characters in the Notes field results in a generic and unclear error:
"Modal state is invalid."
2. This PR fixes a bug where the “Notes” field in the Add Sponsorship modal does not allow users to input spaces in their text.
3.  This PR addresses a validation issue in the Add Sponsorship modal on the Free Sponsored Families page.
4. This PR updates the Add Sponsorship modal to align with app-wide form labeling conventions by removing colons (:) after field names.
- All formatters and local …
=> [PM-21073] No error when submitting empty form

.github/renovate.json5
https://github.com/bitwarden/clients/pull/14580 moved some linting dependencies to architecture but only added them to the group and not did not assign reviewers correctly. …
=> Add typescript-eslint to be owned by arch

apps/desktop/src/services/biometric-message-handler.service.spec.ts, apps/desktop/src/services/biometric-message-handler.service.ts
https://bitwarden.atlassian.net/browse/PM-19677
Browser integration verification always re-prompts after desktop app is locked.
Can also be reproduced by disabling and re-enabling the fingerprint verification in Desktop app.
When a browser integration setting or fingerprint verification setting changes in Desktop app, we have a mechanism to remove any existing browser extension connections.
The idea is correct, but the implementation needs to be a bit different:
- We should only remove existing connections when browser integration is disabled - The bug happens because the observable that holds the browser integration setting (or the fingerprint verification setting) changes value causing the subscription to be called, and since we do not check for the value, we remove existing connections …
=> [PM-19677] Browser integration verification always re-prompts after desktop app is locked

libs/components/src/select/select.component.spec.ts, libs/components/src/select/select.component.ts
https://bitwarden.atlassian.net/browse/PM-21121
If a _value_ is provided to `bit-select` before a corresponding _option_ (via the `items` input) is available, the option will not appear selected when the option is later provided. This PR fixes this bug by rerendering the selected option whenever the `items` input changes. …
=> [PM-21121] fix(select): update selected item when items input changes

apps/browser/src/autofill/background/notification.background.ts, apps/browser/src/autofill/content/components/notification/confirmation/body.ts, apps/browser/src/autofill/content/components/notification/confirmation/container.ts, apps/browser/src/autofill/content/components/notification/confirmation/message.ts, apps/browser/src/autofill/notification/bar.ts
https://bitwarden.atlassian.net/browse/PM-20514
The objective of this PR is to check if a user has edit permissions when attempting to update a cipher that belongs to an org. If the permission is not present on the cipher, the standard error populates. 
https://github.com/user-attachments/assets/86939d07-a8ae-496b-8ef9-769faeef06f1 …
=> PM-20514 do not allow users without edit permissions to edit a cipher in notification bar

libs/common/src/billing/services/account/billing-account-profile-state.service.ts
https://bitwarden.atlassian.net/browse/PM-18812
In https://bitwarden.atlassian.net/browse/PM-13086, we discovered that the root cause of (at least some of) the issues is the electron-store implementation that we use on the desktop, and how it performs reads and writes.  This is exacerbated by the large size of the data.json file in which we store all local state on the desktop.
You can see here: https://github.com/sindresorhus/conf/blob/05f1b87cc1475922ba7e9c5455cf361f07174ae7/source/index.ts#L329-L331 that every get store() does a fs.readFileSync and this getter is called every time we request a key from the store. Currently we seem to be regularly requesting the following keys:
- State Provider Framework documentation: https://contributing.bitwarden.com/architecture/deep-dives/state/#upd …
=> [PM-18812] Avoid unnecessary I/O for frequently updated state `accountProfile`

apps/browser/src/tools/popup/settings/about-page/about-page-v2.component.html, apps/browser/src/tools/popup/settings/about-page/about-page-v2.component.ts, apps/browser/src/tools/popup/settings/settings-v2.component.html, apps/browser/src/tools/popup/settings/settings-v2.component.ts
https://bitwarden.atlassian.net/browse/PM-21280
This PR hides the nudge epic settings page UI changes behind the feature flag. …
=> [PM-21280] - hide setings UI changes behind feature flag

apps/desktop/src/locales/en/messages.json, apps/desktop/src/vault/app/vault/item-footer.component.html, apps/desktop/src/vault/app/vault/vault-v2.component.html, apps/desktop/src/vault/app/vault/vault-v2.component.ts, libs/vault/src/components/totp-countdown/totp-countdown.component.html
https://bitwarden.atlassian.net/browse/PM-21016
This PR fixes a number of UI defects that came from the [desktop cipher from update](https://github.com/bitwarden/clients/pull/13992) …
=> [PM-21016] - various fixes to desktop cipher form

libs/components/src/color-password/color-password.component.ts, libs/vault/src/cipher-view/login-credentials/login-credentials-view.component.spec.ts, libs/vault/src/components/password-history-view/password-history-view.component.spec.ts
The color-password component was converted to use @for over NgFor with https://github.com/bitwarden/clients/pull/12390
This has caused a performance issue as the component is tracking the characters, but these are by design most likely not going to be unique. This causes the component to re-render and throw the following warning on the console:
```
NG0955: The provided track expression resulted in duplicated keys for a given collection. 
Adjust the tracking expression such that it uniquely identifies all the items in the collection. 
Duplicated keys were: 
key "3" at index "2" and "3". Find more at 
```
By using `$index` instead of character for tracking changes, this is prevented.
In addition the component was migrated to use Angular Signal inputs and I made it ts-strict compliant.
- …
=> Fix angular performance issue on color-password.component

apps/browser/src/autofill/notification/bar.ts
https://bitwarden.atlassian.net/browse/PM-21318
Avoid passing default string literal in folder
https://github.com/user-attachments/assets/1acdad77-fc6f-49b4-b617-59d155c7ef70 …
=> PM-21318 Org member with Manage collection permission getting error when saving item to org collection

apps/desktop/src/autofill/services/desktop-fido2-user-interface.service.ts, apps/desktop/src/main/window.main.ts, apps/desktop/src/platform/models/domain/window-state.ts, apps/desktop/src/platform/popup-modal-styles.ts, apps/desktop/src/platform/services/desktop-settings.service.ts
[PM-20409](https://bitwarden.atlassian.net/browse/PM-20409)
Currently when the vault is locked the user is unable to cancel out of the passkey flow.  With this change the traffic light buttons are restored (Close/Minimize/Maximize) and the flow can be exited without causing issues. …
=> Display traffic light MacOS buttons when the vault is locked

apps/browser/src/platform/popup/layout/popup-layout.mdx
[CL-680](https://bitwarden.atlassian.net/browse/CL-680)
A previous PR changed the name of a story, which caused the docs page that referenced that story to error out.
In this PR, I also added a docs reference to a new story that was added in the previous PR.
See Storybook Publish action for the Popup Layout docs. …
=> [CL-680] Fix broken popup layout docs page

apps/desktop/src/modal/passkeys/create/fido2-create.component.ts
[PM-20347](https://bitwarden.atlassian.net/browse/PM-20347)
Filter the available ciphers so we only display ciphers that are valid and match the username or userhandle.
Previously all available ciphers were being displayed and we weren't filtering on validity, or a userHandle/username match.
Now, two checks are made against a cipher to make sure it matches the `lastRegistrationRequest`.
* The cipher is valid to use with Fido2.  It is a login cipher, matches the uri, and and is not in the trash.
* Matches the `userHandle` (or matches the `username` for logins that don't have Fido2 credentials).
To Test this create a login cipher, for example `pm20347` for webauthn.io.
* Move the cipher to the trash
* Visit webauthn.io and use `pm20347` in the field.
* Choose `register`.  You should not see …
=> Filter available cipher results

libs/vault/src/services/vault-nudges.service.spec.ts, libs/vault/src/services/vault-nudges.service.ts
https://bitwarden.atlassian.net/browse/PM-21343
This PR adds the `DownloadBitwarden` nudge to `hasActiveBadges$` observable which ensures the settings tab badge will be shown if the user hasn't yet visited the download bitwarden screen.
- …
=> [PM-21343] - add download bitwarden to list of nudges for settings badge

apps/browser/src/background/main.background.ts, apps/cli/src/platform/services/node-api.service.ts, libs/angular/src/services/injection-tokens.ts, libs/angular/src/services/jslib-services.module.ts, libs/common/src/services/api.service.spec.ts, libs/common/src/services/api.service.ts
https://bitwarden.atlassian.net/browse/PM-14484
9ea72d4d86a5b530a8f09734d0feb0934f679b0e - Adds a relatively minor change to inject code for creating `Request` this is because this type doesn't exist in our tests and while technically testable in other ways, this is the easiest IMO. 
1398f144f21c1ed274d362d92130b0974d557e09 - Adds tests for the current `send` method of `ApiService` especially around how it handles errors. This commit includes tests that are removed later because this change is an accepted change of behavior.
0bd0fafe6c0e620211f61a70963fe454c23ea632 - Fixes the bug where HTML is able to be displayed (because it's coming from the `ErrorResponse.message` property. I unfortunately don't know for a fact that we never receive HTML when the content type is `text/plain` but that …
=> [PM-14484] `ApiService` showing html in error message

apps/web/src/connectors/duo-redirect.spec.ts, apps/web/src/connectors/duo-redirect.ts
https://bitwarden.atlassian.net/browse/VULN-241
As a follow-up to #14174, this provides additional scrutiny to the redirectUrl parameter of the Duo redirect …
=> Duo URL redirect enhancements

apps/browser/src/autofill/background/notification.background.spec.ts, apps/browser/src/autofill/background/notification.background.ts, apps/browser/src/autofill/overlay/notifications/abstractions/overlay-notifications-content.service.ts, apps/browser/src/autofill/overlay/notifications/content/overlay-notifications-content.service.ts, apps/browser/src/autofill/services/abstractions/autofill.service.ts, apps/browser/src/autofill/services/autofill.service.ts, apps/browser/src/vault/popup/components/vault-v2/view-v2/view-v2.component.ts, libs/common/src/autofill/constants/index.ts
[PM-20637](https://bitwarden.atlassian.net/browse/PM-20637)
GIVEN: the user is viewing the “Update existing login” UI
AND: Master password re-prompt is ON for that item
WHEN: the user selects “Update” on the login shown
THEN: the popout opens for the user to enter their master password before updating that item
**Reprompt happy path**
https://github.com/user-attachments/assets/0dea3c46-f043-4d57-beff-79a367acb961 
**Reprompt sad path**
https://github.com/user-attachments/assets/8bff0f57-e601-4086-8f33-88f368f3f417 …
=> [PM-20637] Trigger password reprompt when updating a reprompt cipher via notification

libs/common/src/enums/feature-flag.enum.ts
https://bitwarden.atlassian.net/browse/PM-13112
> Remove the `vault-bulk-management-action` feature flag that won't go away! 3rd times a charm... …
=> [PM-13112] Remove vault-bulk-management-action feature flag definition

apps/browser/src/autofill/services/autofill-browser-settings.service.ts, apps/browser/src/platform/browser/browser-api.ts
https://bitwarden.atlassian.net/browse/PM-21480
This PR fixes an issue where `BrowserApi.browserAutofillSettingsOverridden` wasn't properly checking for privacy permission grant before checking for `chrome.privacy`.
Previously the assumption that this was being checked before calling `browserAutofillSettingsOverridden` but this is prone to bugs like this one. …
=> [PM-21480] - check for privacy granted in isBrowserAutofillSettingOverridden

libs/auth/src/angular/login-via-auth-request/login-via-auth-request.component.ts, libs/auth/src/common/services/auth-request/default-login-via-auth-request-cache.service.spec.ts, libs/auth/src/common/services/auth-request/default-login-via-auth-request-cache.service.ts, libs/common/src/enums/feature-flag.enum.ts
https://bitwarden.atlassian.net/browse/PM-18512
Removes the `pm-9112-device-approval-persistence` feature flag from the clients.  This also allowed the removal of the `init()` method as it was only used to set the flag value.
https://github.com/user-attachments/assets/cfc8f614-050a-4819-8f4a-4f0635cd92b9
- 📝 …
=> [PM-18512] Remove pm-9112-device-approval-persistence feature flag

apps/web/src/app/billing/accounts/trial-initiation/trial-billing-step.component.html, apps/web/src/app/billing/accounts/trial-initiation/trial-billing-step.component.ts, libs/common/src/billing/abstractions/tax.service.abstraction.ts, libs/common/src/billing/models/request/tax/index.ts, libs/common/src/billing/models/request/tax/preview-tax-amount-for-organization-trial.request.ts, libs/common/src/billing/models/response/tax/index.ts, libs/common/src/billing/models/response/tax/preview-tax-amount.response.ts, libs/common/src/billing/services/tax.service.ts
https://bitwarden.atlassian.net/browse/PM-20087
This PR adds a new endpoint invocation to the `tax.service` to preview the tax amount for an organization trial initiation. That endpoint was wired up in this `server` PR (https://github.com/bitwarden/server/pull/5787). 
When the `trialLength` query parameter is 0, we start previewing the tax amount as the user makes changes within the trial initiation stepper. Tax amount should not be previewed when the trial length is not 0.
When Trial Length is not 0 (No tax preview):
https://github.com/user-attachments/assets/8fafa1f8-5db9-41c3-b611-fe144fcf87e1
When Trial Length is 0 (tax preview):
https://github.com/user-attachments/assets/adf43500-7aa3-45da-bc89-c9411014c3be
- All formatters and local linters executed …
=> [PM-20087] Estimate tax for trial initiation flow when trial length is 0

libs/common/src/key-management/master-password/abstractions/master-password.service.abstraction.ts, libs/common/src/key-management/master-password/services/master-password.service.ts, libs/key-management-ui/src/lock/components/lock.component.ts
https://bitwarden.atlassian.net/browse/PM-21586
https://github.com/bitwarden/clients/commit/5408a62b7df4631564601fb5fc056e718b6c74f9#diff-cc453f6e4a1aa6a10902799593c7fc471252ae21f5b4d5c664948dd50f238fa8L201
changed the behavior to where the decrypt function now throws if it fails to decrypt. This was not communicated to consumers, and is an unintentional change. Further our API does not explicitly state that it can return null.
This forces a return null on error by catching any errors to keep compatibility, until we *want* to explicitly break this behavior. Further, this makes the behavior explict by changing the type to include null.
- …
=> [PM-21586] Return null in decryptUserKeyWithMasterKey if decrypt fails

bitwarden_license/bit-common/src/dirt/reports/risk-insights/services/risk-insights-report.service.spec.ts, bitwarden_license/bit-common/src/dirt/reports/risk-insights/services/risk-insights-report.service.ts
https://bitwarden.atlassian.net/browse/PM-19223
This is a duplicate of: https://github.com/bitwarden/clients/pull/14009
The report service and the spec files were moved into the new team dirt location and complicated the PR with conflicts.  …
=> [PM-19223] - Aggregate by domain (with file move)

apps/cli/src/auth/commands/login.command.ts, apps/cli/src/program.ts, libs/auth/src/angular/sso/sso.component.ts, libs/auth/src/common/services/sso-redirect/sso-url.service.spec.ts, libs/auth/src/common/services/sso-redirect/sso-url.service.ts
https://bitwarden.atlassian.net/browse/PM-21116
The `bw login --sso` option did not support any way to pass the SSO org identifier as a command line argument.  Doing so allows us to leverage the "auto-submit" functionality that is built in to the SSO component; when the SSO component detects that an org identifier is in the query string, it automatically progresses the user to the IdP.
Intended usage:
```
bw --sso {Identifier}
```
While still supporting the old usage:
```
bw --sso
```
This required 2 sets of changes:
1. The most straightforward - exposing the new configuration option in the CLI, and passing it in to the redirect URL builder.  Note the parsing of an optional parameter value, as documented in the Commander docs [here](https://github.com/tj/commander.js/blob/HEAD/examples/opt …
=> [PM-21116] Add SSO org identifier option for SSO on CLI

apps/browser/src/_locales/en/messages.json, apps/browser/src/tools/popup/settings/settings-v2.component.html
[PM-21286](https://bitwarden.atlassian.net/browse/PM-21286)
Add an Aria label to the nudge settings badge. Currently there is only 1 nudge notification for these label badges. If there are custom nudges added in the future that increases the badge numbers of a label we can update the code be take dynamic numbers. 
https://github.com/user-attachments/assets/c3d4c7e8-5d69-44e3-8ec3-b30b06a04c63 …
=> [PM-21286] add aria label to nudge settings badge

apps/browser/src/platform/popup/layout/popup-size.service.ts, apps/browser/src/popup/app.component.ts, apps/browser/src/popup/scss/base.scss
[PM-17091](https://bitwarden.atlassian.net/browse/PM-17091)
[PM-17043](https://bitwarden.atlassian.net/browse/PM-17043)
This PR does two things:
- Moves the setting of the extension height to the `app.component.ts` `init` function instead of the root `init.service.ts`. There have been intermittent reports of the extension opening at half-height in Firefox and Chrome, although internally we have not been able to reproduce this in some time. There is likely a race condition where the extension height class (`body-xxs`) was being set before the browser had returned the available window height. By moving the function call to a later `init` function, this may help prevent the race condition. We are unable to test if it solves the problem given that we cannot reproduce it.
- Adds logic to …
=> [PM-17091][PM-17043] Support system zoom in browser extension

libs/vault/src/cipher-form/components/additional-options/additional-options-section.component.html, libs/vault/src/cipher-form/components/autofill-options/autofill-options.component.html, libs/vault/src/cipher-form/components/card-details-section/card-details-section.component.html, libs/vault/src/cipher-form/components/custom-fields/custom-fields.component.html, libs/vault/src/cipher-form/components/item-details/item-details-section.component.html, libs/vault/src/cipher-form/components/login-details-section/login-details-section.component.html, libs/vault/src/cipher-form/components/sshkey-section/sshkey-section.component.html, libs/vault/src/cipher-view/additional-options/additional-options.component.html, libs/vault/src/cipher-view/attachments/attachments-v2-view.component.html, libs/vault/src/cipher-view/autofill-options/autofill-options-view.component.html, libs/vault/src/cipher-view/card-details/card-details-view.component.html, libs/vault/src/cipher-view/custom-fields/custom-fields-v2.component.html, libs/vault/src/cipher-view/item-details/item-details-v2.component.html, libs/vault/src/cipher-view/login-credentials/login-credentials-view.component.html, libs/vault/src/cipher-view/sshkey-sections/sshkey-view.component.html, libs/vault/src/cipher-view/view-identity-sections/view-identity-sections.component.html
https://bitwarden.atlassian.net/browse/PM-21213
This PR replaces all instances of `<bit-section` for all the components that are nested in the the cipher-view and cipher-form components. The reason being the section component uses the following class
`tw-mb-5 bit-compact:tw-mb-4 [&:not(bit-dialog_*):not(popup-page_*)]:md:tw-mb-12`
Since we cannot target desktop with a class like we are with `popup-page_*` and `bit-dialog_*` we're getting `tw-mb-12` in the desktop client and was deemed unacceptable by QA/design. The solution was suggested by UIF team.
|Before|After|
---|---
|![Screenshot 2025-05-09 at 11 24 17 AM](https://github.com/user-attachments/assets/f75f2a38-c580-4378-a2e6-a0dbada06e1f)|![Screenshot 2025-05-09 at 11 09 31 AM](https://github.com/user-attachments/assets/3932b518-b9ea-4 …
=> [PM-21213] - replace bit-section with section for all shared cipher form and views

libs/common/src/platform/services/fido2/guid-utils.spec.ts, libs/common/src/platform/services/fido2/guid-utils.ts
Autofill found a bug where converting a too long array buffer to a GUID would just improperly return a truncated result …
=> Better handle array buffers that are too long to be a GUID

libs/components/src/chip-select/chip-select.component.html, libs/components/src/chip-select/chip-select.component.ts, libs/components/src/form-field/form-field.component.html, libs/components/src/form-field/form-field.component.ts, libs/components/src/item/item-content.component.ts, libs/components/src/item/item.component.html, libs/components/src/item/item.component.ts, libs/components/src/navigation/nav-item.component.html, libs/components/src/navigation/nav-item.component.ts
https://bitwarden.atlassian.net/browse/CL-659
The component library currently uses classes to determine fvw target, default content and main content. This replaces them with data attributes which avoids the css class linter from detecting them as invalid classes. …
=> [CL-659] Replace CL non tw css classes with data attributes

.github/workflows/build-browser-target.yml, .github/workflows/build-cli-target.yml, .github/workflows/build-desktop-target.yml, .github/workflows/build-web-target.yml, .github/workflows/scan.yml
[BRE-609](https://bitwarden.atlassian.net/browse/BRE-609)
update workflows to be compliant with pull_request_target workflow linter rule ahead of changing rule log level to error …
=> BRE-609/update-workflows

apps/desktop/src/vault/app/vault/vault-v2.component.ts, libs/vault/src/cipher-form/components/cipher-form.component.ts
https://bitwarden.atlassian.net/browse/PM-21554
This PR fixes an issue where, (only on prod builds), if while editing a cipher and then creating a new one, the edited cipher would be overwritten with the new cipher. This was due to the `updatedCipherView` being set to the `cachedCipher` even when the `cachedCipher` didn't match the existing cipher. It also fixes an issue where the `cipherId` wasn't being set to `null` in before saving the cipher which caused the `config.originalCipher` to be set to the previous cipher, occasionally causing an error when saving the cipher.
- …
=> [PM-21554] - Creating a new item while editing edits the item

apps/browser/src/autofill/popup/settings/autofill.component.ts, apps/browser/src/popup/tabs-v2.component.ts, apps/browser/src/tools/popup/settings/settings-v2.component.html, apps/browser/src/tools/popup/settings/settings-v2.component.ts, apps/browser/src/vault/popup/components/vault-v2/vault-v2.component.html, apps/browser/src/vault/popup/components/vault-v2/vault-v2.component.ts, apps/browser/src/vault/popup/settings/download-bitwarden.component.ts, libs/common/src/platform/state/state-definitions.ts, libs/vault/src/cipher-form/cipher-form.stories.ts, libs/vault/src/cipher-form/components/new-item-nudge/new-item-nudge.component.spec.ts, libs/vault/src/cipher-form/components/new-item-nudge/new-item-nudge.component.ts, libs/vault/src/index.ts, libs/vault/src/services/custom-nudges-services/autofill-nudge.service.ts, libs/vault/src/services/custom-nudges-services/download-bitwarden-nudge.service.ts, libs/vault/src/services/custom-nudges-services/empty-vault-nudge.service.ts, libs/vault/src/services/custom-nudges-services/has-items-nudge.service.ts, libs/vault/src/services/custom-nudges-services/new-item-nudge.service.ts, libs/vault/src/services/default-single-nudge.service.ts, libs/vault/src/services/nudges.service.spec.ts, libs/vault/src/services/nudges.service.ts, libs/vault/src/services/vault-nudges.service.spec.ts
[PM-21663](https://bitwarden.atlassian.net/browse/PM-21663)
This PR refactors:
- `VaultNudgesService` -> `NudgesService` and other related names (state, type, status)
- NudgesService updates: New observables added for `showNudgeBadge$` and `showNudgeSpotlight`. Added Unit Test
- Components that used `showNudge$` to get the `NudgeStatus` have been updated to target the new observables and get a boolean value in return. …
=> [PM-21663] nudge service name refactor

apps/browser/src/vault/popup/components/vault-v2/item-copy-action/item-copy-actions.component.html, apps/browser/src/vault/popup/components/vault-v2/item-copy-action/item-copy-actions.component.ts
Fixes #14167
#14167 
- When TOTP secret is the only login item, use `appCopyField` to copy the TOTP code instead of copying the authenticator secret with `appCopyClick`
- Also refactored the `findSingleCopiableItem` method to be more efficient (`O(n^2)` -> `O(n)`) …
=> [PM-21433] fix(browser): use appCopyField instead of appCopyClick for singleCopiableLogin

apps/browser/src/_locales/en/messages.json, apps/browser/src/autofill/content/components/lit-stories/mock-data.ts, apps/browser/src/autofill/content/components/notification/container.ts, apps/browser/src/autofill/content/components/notification/footer.ts, apps/browser/src/autofill/content/components/notification/header.ts, apps/browser/src/autofill/notification/bar.ts
[PM-21456](https://bitwarden.atlassian.net/browse/PM-21456)
With the v3 notification experience, when the vault is locked and a user logs in, they do not receive the usual prompt to unlock and save the cipher.
**After Changes**
https://github.com/user-attachments/assets/1cbb14af-a59b-4593-b53d-516c56dda24f
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future …
=> [PM-21456] Notification bar does not appear when user is adding a new login when vault is locked

apps/browser/src/autofill/fido2/utils/webauthn-utils.ts, libs/common/src/platform/services/fido2/fido2-utils.ts
https://bitwarden.atlassian.net/browse/PM-21553
This PR adds support for [.toJSON()](https://developer.mozilla.org/en-US/docs/Web/API/PublicKeyCredential/toJSON).
It's part of the spec, and also resolves #14334.  …
=> PM-21553: Added support for credential.toJSON()

libs/components/src/menu/menu-trigger-for.directive.ts
[CL-627](https://bitwarden.atlassian.net/browse/CL-627)
This PR adds more menu position options. Previously, we had 2 positions (the first two), but now we will have 4:
1. Opens **below** the trigger element, anchored to the **start** of the trigger element (for LTR, the left)
2. Opens **below** the trigger element, anchored to the **end** of the trigger element (for LTR, the right)
3. Opens **above** the trigger element, anchored to the **start** of the trigger element (for LTR, the left)
4. Opens **above** the trigger element, anchored to the **end** of the trigger element (for LTR, the right)
Before:
https://github.com/user-attachments/assets/086a767b-1513-453a-8e3f-93a71df0215c
After:
https://github.com/user-attachments/assets/8a8658fd-8610-4394-ae94-843e18854b53
Before: …
=> [CL-627] Allow menu to open above trigger without blocking trigger

apps/desktop/src/platform/main/clipboard.main.ts
https://bitwarden.atlassian.net/browse/PM-650
If a value is copied to the clipboard, but the application is closed, we leave that data in the clipboard. This PR ensures that the clipboard is cleared upon closing the app if it matches a value copied from the vault. …
=> fix: clear clipboard on close

apps/web/src/app/billing/members/free-bitwarden-families.component.ts, libs/common/src/billing/abstractions/organizations/organization-sponsorship-api.service.abstraction.ts, libs/common/src/billing/services/organization/organization-sponsorship-api.service.ts
https://bitwarden.atlassian.net/browse/PM-21666
If there is more than one sponsorship in the table, when you attempt to remove a sponsorship in a ‘Sent’ or ‘Active’ status, it does not respond. The Sponsorship remains in a ‘Sent’ and can be redeemed, remains in an ‘Active’ status.
https://github.com/user-attachments/assets/b13d94ba-033b-4286-ae2e-e877d9784bca …
=> [PM 21666]If there is more than one Sponsorship in the table, you cannot remove 'Sent' or 'Active' sponsorships

apps/browser/src/autofill/content/components/notification/confirmation/body.ts, apps/browser/src/autofill/content/components/notification/confirmation/container.ts, apps/browser/src/autofill/content/components/notification/confirmation/message.ts
[PM-21723](https://bitwarden.atlassian.net/browse/PM-21723)
If a security task is associated with a cipher that just failed to save, security task success information is included with the error message
| --- | --- |
| ![Screenshot 2025-05-16 at 1 04 16 PM](https://github.com/user-attachments/assets/fa7402dc-32f8-405d-81bb-982f03e330c2) ![Screenshot 2025-05-16 at 1 04 06 PM](https://github.com/user-attachments/assets/61fe0f24-e125-4f4d-b82e-4b10f7bd48d1) | ![Screenshot 2025-05-16 at 1 03 09 PM](https://github.com/user-attachments/assets/954e8196-9e03-46a9-bcf5-687f829a0cf3) | …
=> [PM-21723] Failure to save a cipher with a security task shows success content alongside the error message

apps/web/src/app/billing/shared/payment/payment.component.ts, apps/web/src/locales/en/messages.json, bitwarden_license/bit-web/src/app/admin-console/providers/setup/setup.component.ts, libs/angular/src/billing/components/manage-tax-information/manage-tax-information.component.ts
https://bitwarden.atlassian.net/browse/PM-21665
This PR resolves a few input validation errors on the provider setup page:
1. The `manage-tax-information.component` needs to run `markAllAsTouched` even if it's not `dirty` in order to trigger the validation. 
2. The `payment.component` needs to validate the bank account inputs when the selected option is Bank Account since these fields are ours and not Stripe's.
3. If a user never adds their PayPal payment method, they get an unhelpful error. I made the catch for this component check for the specific error thrown by Braintree when this happens and show a more helpful Toast.
https://github.com/user-attachments/assets/2876e1a3-b226-4dd7-942e-8128bdad9540 …
=> [PM-21665] Fix input errors on provider setup

libs/components/src/table/table-scroll.component.ts
A directive import was mistakenly removed from the `virtual-scroll-table` between https://github.com/bitwarden/clients/pull/14827/files# and https://github.com/bitwarden/clients/pull/14795/files#diff-1e9698f26a35aa72fb3faa41b2cb1108f277151a303efdf027d701c38be75cff …
=> [UIF] add missing directive import to virtual scroll table

.github/CODEOWNERS, .github/renovate.json5
https://bitwarden.atlassian.net/browse/PM-21370
Introduces several QoL improvements to how we group dependencies:
- Grouped all Github Action minor updates together to reduce PR noise.
- See https://github.com/bitwarden/server/pull/5790 for corresponding changes on `server`.
- Removed the groupings using `matchFileNames`, which was introduced to try to separate out PRs for BRE and Platform for workflow maintenance, as the Renovate [documentation](https://docs.renovatebot.com/configuration-options/#matchfilenames) and source code indicates that this only works for matching package and lock files.  In other words, this configuration wasn't doing anything.
- Removed handling of `patch` updates for `zone.js` since we are no longer creating PRs for patches automatically.
- Grouped all …
=> [PM-21370] Add additional dependency groupings

apps/browser/src/popup/tabs-v2.component.ts
https://bitwarden.atlassian.net/browse/PM-21844
This PR adds default values as `false` for both the config service `getFeatureFlag$` and nudge service `hasActiveBadges$` observables to avoid any delay of rendering of the navigation tabs.
https://github.com/user-attachments/assets/c351e179-48ff-4001-af17-4626b78c1fc0
https://github.com/user-attachments/assets/db475ecd-8ac6-4f3f-90ae-c9687bf52ef1 …
=> [PM-21844] - set default values for navButtons$ observable

apps/web/src/app/auth/core/services/login/web-login-component.service.ts
https://bitwarden.atlassian.net/browse/PM-21085
So this issue was occuring because we were consuming the policy api incorrectly. We were not passing in the policies that we had retrieved and instead relying on the default policy service to provide us the policies but none had been set yet.
In the ticket I've asked for some clarification from Thomas to see if they have ongoing efforts with regards to the default policy service because it seems like there could be other occurrences across the app where we are trying to leverage the cached policies when none are set.
* Fixed up code that was not properly using the policy api.
https://github.com/user-attachments/assets/badc2efc-da38-428d-9fad-155ef73542cd
https://github.com/user-attachments/assets/e5a3aa1d-4aee-452b-a677-2aa1ab9711f1
- …
=> fix(policy-enforcement): [PM-21085] Fix Bug with Policy Enforcement

libs/common/src/tools/send/services/send.service.spec.ts, libs/common/src/tools/send/services/send.service.ts
https://bitwarden.atlassian.net/browse/PM-21867
Despite it's name; send.key is not a key. We had documented this in a few other places, but not yet in the key-rotation code, so it was incorrectly assumed to be a key. The new validation on unwrapSymmetricKey / wrapSymmetricKey assumes a symmetric cryptokey to be passed in, which only accepts 32 / 64 / >64 byte keys which made this fail. (In any case, it is the incorrect primitive and would otherwise have lead to issues later on when switching out the implementation of wrapSymmetricKey). …
=> [PM-21867] Fix send rotation broken due to incorrect types

apps/desktop/src/vault/app/vault/vault.component.html, apps/desktop/src/vault/app/vault/view.component.ts, libs/angular/src/vault/components/view.component.ts
https://bitwarden.atlassian.net/browse/PM-21896
This PR prevents double password prompt when copying a password in the desktop cipher form for a MP protected cipher.
https://github.com/user-attachments/assets/53a1899a-ab73-4cf4-8259-74f9e9a0be31 …
=> [PM-21896] - prevent double reprompt for copy password in desktop cipher form

apps/desktop/src/autofill/modal/credentials/fido2-create.component.html, apps/desktop/src/autofill/modal/credentials/fido2-create.component.ts, apps/desktop/src/locales/en/messages.json
[PM-21870](https://bitwarden.atlassian.net/browse/PM-21870)
Update the styling for the credential creation modal when no credentials are available for the site.
Before:
After: …
=> Add correct design when no credentials available

libs/vault/src/components/assign-collections.component.spec.ts
https://bitwarden.atlassian.net/browse/PM-21006
On https://github.com/bitwarden/clients/pull/14804 I introduced a new eslint rule meant to document suspicious imports across the monorepo to aid in the separation of circular references and the introduction of monorepo tooling [Nx](nx.dev).
Between the time of me putting up the PR and it merging one new violation was introduced. This PR ignores it.
Platform is going to be looping through these and working with teams to abstract code in a way that avoid these kinds of references, but in the meantime existing errors need to be ignored.  …
=> ignore one eslint error

apps/browser/src/autofill/content/components/buttons/option-selection-button.ts, apps/browser/src/autofill/content/components/lit-stories/buttons/option-selection-button.lit-stories.ts, apps/browser/src/autofill/content/components/lit-stories/notification/confirmation/container.lit-stories.ts, apps/browser/src/autofill/content/components/lit-stories/notification/container.lit-stories.ts, apps/browser/src/autofill/content/components/lit-stories/options-selection/option-selection.lit-stories.ts, apps/browser/src/autofill/content/components/notification/confirmation/container.ts, apps/browser/src/autofill/content/components/notification/container.ts, apps/browser/src/autofill/content/components/option-selection/option-item.ts, apps/browser/src/autofill/content/components/option-selection/option-items.ts, apps/browser/src/autofill/content/components/option-selection/option-selection.ts, apps/browser/src/autofill/content/components/rows/button-row.ts, apps/browser/src/autofill/notification/bar.ts
https://bitwarden.atlassian.net/browse/PM-21651
- 🎨 …
=> PM-21651 [For Automation Purposes] add test IDs to notification bar

libs/common/src/platform/abstractions/sdk/sdk.service.ts
Follow up PR to https://github.com/bitwarden/sdk-internal/pull/225 which adds converters between strings and SDK UUIDs. …
=> Add UUID helpers to the SDK

apps/web/src/app/auth/settings/account/account.component.ts, apps/web/src/app/auth/settings/account/change-avatar-dialog.component.ts, apps/web/src/app/auth/settings/account/change-email.component.spec.ts, apps/web/src/app/auth/settings/account/change-email.component.ts, apps/web/src/app/auth/settings/account/danger-zone.component.ts, apps/web/src/app/auth/settings/account/deauthorize-sessions.component.ts, apps/web/src/app/auth/settings/account/delete-account-dialog.component.ts, apps/web/src/app/auth/settings/account/profile.component.ts, apps/web/src/app/auth/settings/account/selectable-avatar.component.ts, apps/web/src/app/auth/settings/security/api-key.component.ts, apps/web/src/app/auth/settings/security/security-keys.component.ts, apps/web/src/app/auth/settings/security/security.component.ts, apps/web/src/app/shared/loose-components.module.ts
https://bitwarden.atlassian.net/browse/PM-21600
Migrates account and security settings components to standalone and removing them from the `LooseComponentsModule`. …
=> [PM-21600] Migrate account and security to standalone 

package.json
Chromatic runs out of memory. This increases the allowed memory usage and avoid future errors. …
=> Increase allowed memory for chromatic

apps/web/src/app/layouts/product-switcher/navigation-switcher/navigation-switcher.stories.ts, apps/web/src/app/layouts/product-switcher/product-switcher.stories.ts, apps/web/src/app/layouts/product-switcher/shared/product-switcher.service.spec.ts, apps/web/src/app/layouts/product-switcher/shared/product-switcher.service.ts
https://bitwarden.atlassian.net/browse/PM-21122
This PR checks to see if the user has a single org policy applied to them and, if true, hides the "Organizations" option in the product switcher.
https://github.com/user-attachments/assets/6a2dc826-df81-4413-a3da-240a93a683fa …
=> [PM-21122] - Hide orgs in product switcher for single org policy users

apps/browser/src/vault/popup/components/vault-v2/vault-search/vault-v2-search.component.ts
https://bitwarden.atlassian.net/browse/PM-21871
On large vaults, typing in the search field remains responsive and instant. 
Improves search input responsiveness by using distinctUntilChanged to prevent duplicate filtering operations, runs filtering outside Angular's zone to prevent change detection freezes, and re-enters the zone only after filtering completes. `onSearchTextChanged` now pushes search text to the subject and decouples the user input from direct filtering operation. 
| Before  |  After |
|---|---|
|<video src="https://github.com/user-attachments/assets/9fa6ce18-ab5e-4772-8b06-8e9b8987b8a3" controls></video>|<video src="https://github.com/user-attachments/assets/105ea724-a634-4d70-b695-1d0046800a4b" controls></video>|
- All formatters and …
=> [PM-21871] Search field slows down on extension when searching large vaults

apps/browser/src/autofill/popup/settings/autofill.component.ts
https://bitwarden.atlassian.net/browse/PM-21724
This PR adds safari and firefox to the list of potential browser vendors for the autofill spotlight nudge. …
=> [PM-21724]  - add safari and firefox to list of potential browser vendors

apps/web/src/app/tools/send/send.component.html
https://bitwarden.atlassian.net/browse/PM-17501
As part of a larger initiative to replace all usage of bootstrap/custom css with tailwind, the `send.component` on web was still using some small parts. This migrates the remaining places to unblock the initiative. 
```
6:11  error  Classname 'text-muted' is not a Tailwind CSS class!  tailwindcss/no-custom-classname
186:10  error  Classname 'no-items' is not a Tailwind CSS class!    tailwindcss/no-custom-classname
189:11  error  Classname 'text-muted' is not a Tailwind CSS class!  tailwindcss/no-custom-classname
```
- Used …
=> [PM-17501] Migrate send.component on web to use tailwind

libs/angular/src/platform/view-cache/README.md
Updated the `view-cache` documentation to use the Github syntax for callouts. …
=> Update documentation callout syntax for Github

apps/browser/src/autofill/background/auto-submit-login.background.spec.ts, apps/browser/src/autofill/background/auto-submit-login.background.ts, apps/browser/src/background/main.background.ts, bitwarden_license/bit-web/src/app/app.component.ts, libs/common/src/enums/feature-flag.enum.ts
https://bitwarden.atlassian.net/browse/PM-16653
remove idp auto submit login step 1 …
=> PM-16653 remove idp auto submit login step 1

apps/browser/src/vault/popup/components/vault-v2/add-edit/add-edit-v2.component.spec.ts, apps/browser/src/vault/popup/components/vault-v2/add-edit/add-edit-v2.component.ts
https://bitwarden.atlassian.net/browse/PM-19826
This PR ensures the `PopupRouterCacheService` history is cleared after creating a new cipher to prevent the "Back" button from navigating to an empty form when clicking away and back into the extension. This is due to the fact that the 
`PopupRouterCacheService` reloads its old history (including  the /add-edit form) upon re-initialization.
https://github.com/user-attachments/assets/e10fd320-288c-4b49-9d14-05e6729c36b0 …
=> [PM-19826] - browser - clear history after creating new cipher

libs/importer/src/services/import.service.spec.ts
While reviewing https://github.com/bitwarden/clients/pull/14871 I noticed that some of the setup/mock code wasn't actually needed anymore. This PR removes those unneeded mock setups (arrange).
- 🤔 …
=> Remove unneeded setup code for import.service tests

libs/angular/src/vault/services/custom-nudges-services/empty-vault-nudge.service.ts
[PM-21848](https://bitwarden.atlassian.net/browse/PM-21848)
Previously when both `hasManageCollections` and `canCreateCollections` were both false, the nudge/spotlight logic would default to the number of contents in a vault. When the vault is empty this causes the import spotlight/vault to show inaccurately. 
When both `hasManageCollections` and `canCreateCollections` return early and hide both the nudge and spotlight.
|Before|After|
|-|-|
|<video src="https://github.com/user-attachments/assets/18d9e80d-0d3b-46c4-b009-0c9067e28f6a" />|<video src="https://github.com/user-attachments/assets/26024a84-cb0f-4874-bbd9-7f8d29d08a1e" />
- 🤔 …
=> [PM-21848] Rework empty vault spotlight logic

apps/cli/src/auth/commands/login.command.ts
https://bitwarden.atlassian.net/browse/PM-22222
In https://github.com/bitwarden/server/pull/5782, we removed the sending of 2FA email if it was the only method, because the 2FA component on the client was sending the email.
However, what this didn't capture is that there are clients that do not use the 2FA component that relied on the contract with the server that it would send the 2FA email if it was the only method.  By changing the server, that implicit contract was broken, and some clients no longer send 2FA emails if email is the only method.
This PR addresses the CLI, and subsequent PRs will address the iOS and Android clients.
https://github.com/user-attachments/assets/13518eaa-b74c-46cc-820a-3f2ad8282916
(Note: The 2FA email was sent but the inbox is not shown for security …
=> [PM-22222] Update CLI to send email regardless of number of methods

apps/browser/src/_locales/en/messages.json, apps/browser/src/auth/popup/components/set-pin.component.html
[PM-22421](https://bitwarden.atlassian.net/browse/PM-22421)
update copy of Set Pin Modal in Browser …
=> [PM-22421] update copy for set pin modal

apps/browser/src/vault/popup/components/vault-v2/item-more-options/item-more-options.component.html, apps/browser/src/vault/popup/components/vault-v2/item-more-options/item-more-options.component.ts, apps/desktop/src/vault/app/vault/add-edit.component.html, apps/web/src/app/vault/components/vault-items/vault-items.component.ts
[PM-21719](https://bitwarden.atlassian.net/browse/PM-21719)
Remove assign to collections option when user does not have editable collections
Remove Move button in desktop when no editable collections
https://github.com/user-attachments/assets/ecc7f47f-a81f-4458-9f47-e4e788797026 …
=> [PM-21719] Remove Assign To Collections Modal When No Editable Collections

libs/common/src/vault/services/cipher.service.ts
[PM-22636](https://bitwarden.atlassian.net/browse/PM-22636)
Possibly nullish `orgKeys` values are not ultimately handled by nullish coalescing operator. This causes both the browser and web client to hang in a loading state after logging into a self-hosted environment that doesn't have an org set up.
Making the changes in this PR (tested with a side-loaded web client build) resolves the loading hang and normal functionality is restored.
- Updated any …
=> [PM-19574] Bugfix - Add optional chaining to possibly nullish orgKeys

.github/ISSUE_TEMPLATE/browser.yml, .github/ISSUE_TEMPLATE/web.yml
https://github.com/bitwarden/clients/issues/15104
In https://github.com/bitwarden/clients/issues/15104, the reporter noted that we do not offer the DuckDuckGo browser in the selection list when creating a Github issue.
This PR adds it to the list. …
=> Add DuckDuckGo to web app for selection when creating a Github issue

libs/common/src/platform/services/sdk/default-sdk.service.ts, package-lock.json, package.json
https://bitwarden.atlassian.net/browse/PM-22721
Init now takes an optional signing key. This is set to undefined for now, to unblock SDK updates.
SDK PR:
https://github.com/bitwarden/sdk-internal/pull/207 …
=> [PM-22721] Update sdk for breaking init change

apps/desktop/src/vault/app/vault/vault-v2.component.ts
[PM-22734](https://bitwarden.atlassian.net/browse/PM-22734)
Allow modifying a cipher immediately after modifying attachments via the dialog.
https://github.com/user-attachments/assets/64fe19af-873a-4833-9612-5d5e9890640b
- ❓ …
=> [PM-22734] Update CipherForm after modifying attachments on Desktop

apps/desktop/src/vault/app/vault/item-footer.component.ts, apps/desktop/src/vault/app/vault/vault-v2.component.html, apps/desktop/src/vault/app/vault/vault-v2.component.ts
https://bitwarden.atlassian.net/browse/PM-22560
This PR prevents the copy and delete functions in the updated desktop cipher form from re-prompting a user for MP as they would have already been prompted once in order to view it. I also removed an unused method and adding some additional type checking.
https://github.com/user-attachments/assets/48540915-d6df-479f-b46d-08b765c52f6b …
=> [PM-22560] - [Defect] Desktop: MP reprompt should not show twice to delete or clone item when viewing item

libs/common/src/abstractions/api.service.ts, libs/common/src/services/api.service.ts, libs/common/src/vault/services/file-upload/cipher-file-upload.service.ts
https://bitwarden.atlassian.net/browse/PM-2703
This PR removes legacy attachment upload methods for compatibility with old server setups. Now that over 4 years have passed since these methods were deprecated we no longer run the risk of servers potentially running this code. …
=> [PM-2703] - remove legacy attachment upload

libs/nx-plugin/src/generators/files/tsconfig.spec.json__tmpl__
This is a one-liner that removes an extra `/` character from the `tsconfig.spec.json` template for the `basic-lib` generator. …
=> fix(nx-plugin): remove extra / from tsconfig.spec template

libs/tools/generator/components/src/nudge-generator-spotlight.component.html
[PM-22269](https://bitwarden.atlassian.net/browse/PM-22269)
Fix screen reader text for generator spotlight. The pattern used in [this pr](https://github.com/bitwarden/clients/pull/10490/files) helps with inconsistencies between browsers/screen readers from the `aria-label` usage. 
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of …
=> [PM-22269] Refactor aria-label to use screen reader only text

apps/web/src/app/admin-console/organizations/members/members.component.ts, apps/web/src/app/admin-console/organizations/members/services/organization-user/organization-user.service.ts, libs/admin-console/src/common/organization-user/models/requests/organization-user-confirm.request.ts, libs/common/src/enums/feature-flag.enum.ts
https://bitwarden.atlassian.net/browse/PM-22536
This pr: 
- Copies the member component's `confirmUser` function into its own service
- Adds encrypted `defaultUserCollectionName` property to the `OrganizationUserConfirmRequest` model. 
- Calls the new `orgKeys$(userId)` in favor of deprecated method.
- Adds feature flag …
=> [PM-22536] add encrypted collection name to confirmUser request

apps/web/src/app/admin-console/common/base-members.component.ts, apps/web/src/app/admin-console/organizations/members/components/account-recovery/account-recovery-dialog.component.html, apps/web/src/app/admin-console/organizations/members/components/account-recovery/account-recovery-dialog.component.ts, apps/web/src/app/admin-console/organizations/members/components/account-recovery/index.ts, apps/web/src/app/admin-console/organizations/members/components/reset-password.component.ts, apps/web/src/app/admin-console/organizations/members/members.component.ts, apps/web/src/app/admin-console/organizations/members/services/organization-user-reset-password/organization-user-reset-password.service.ts, apps/web/src/locales/en/messages.json, libs/auth/src/angular/input-password/input-password.component.html, libs/auth/src/angular/input-password/input-password.component.ts
[PM-18721](https://bitwarden.atlassian.net/browse/PM-18721)
[PM-21272](https://bitwarden.atlassian.net/browse/PM-21272)
This PR stacks on top of these two PRs:
- https://github.com/bitwarden/clients/pull/14636
- https://github.com/bitwarden/clients/pull/14226
This PR integrates the `InputPasswordComponent` within the `AccountRecoveryDialogComponent` (formerly called `ResetPasswordComponent`).
The result is that:
- The `InputPasswordComponent` will now handle form field UI display and validation that is common to all of our set/change password flows
- The `AccountRecoveryDialogComponent` will now just be responsible for displaying the dialog and calling `resetPasswordService.resetMasterPassword()` to perform the password reset operation.
The showing of the new dialog component is behind …
=> [PM-18721][PM-21272] Integrate InputPasswordComponent in AccountRecoveryDialogComponent

apps/browser/src/autofill/browser/main-context-menu-handler.spec.ts, apps/browser/src/autofill/browser/main-context-menu-handler.ts, apps/browser/src/background/main.background.ts, libs/common/src/autofill/services/autofill-settings.service.ts
[PM-20625](https://bitwarden.atlassian.net/browse/PM-20625)
Remove the 'Autofill card' option from the context menu if a user is part of an organization with the 'Remove card item type' policy on.
https://github.com/user-attachments/assets/e7d04b9d-a182-4f6f-ba6e-9c1ee6802c0b …
=> Hide card option from context menu when user is affected by card policy

apps/desktop/electron-builder.json, apps/desktop/package.json
https://bitwarden.atlassian.net/browse/PM-22464
Snaps take _way_ too long to launch after installation or updates. [Canonical suggests using LZO compression](https://snapcraft.io/blog/how-to-make-snaps-faster) as a possible means to make them less slow. …
=> [PM-22464] Use LZO to speed up slow Snap initialization

libs/angular/src/auth/guards/auth.guard.ts
Follow up to [PM-22822](https://bitwarden.atlassian.net/browse/PM-22822)
The conditional checks on the `AdminForcePasswordReset` case were slightly off, allowing for an infinite redirect loop such that when `ForceSetPasswordReason` is `AdminForcePasswordReset`, then we redirect to `/update-temp-password`. But `/update-temp-password` itself has the `authGuard` applied, which would re-run this code in an infinite loop, continually redirecting to `/update-temp-password`.
My fix makes sure that the `authGuard` will not attempt to redirect if the destination url is `"update-temp-password"` (that is, `routerState.url.includes("update-temp-password")`). This allows the user to actually continue to `/update-temp-password` to change their password. …
=> [PM-22822] Fix redirect loop bug

apps/desktop/src/main.ts
https://bitwarden.atlassian.net/browse/PM-21608
Some users have rendering issues and are unable to launch the application to toggle hardware acceleration as a workaround. This provides an environment variable (`ELECTRON_DISABLE_GPU`) as a non-graphical way to disable it. …
=> Allow disabling hardware acceleration with environment variable

apps/desktop/src/vault/app/vault/vault-v2.component.ts
[PM-21719](https://bitwarden.atlassian.net/browse/PM-21719)
Add a check to the desktop assign to collections menu option so if a user who right clicks on a personal item, should only see the assign to collections option when they have Edit Access to Collections. …
=> [PM-21719] update desktop to address personal items who cant assign to collections

apps/web/src/app/admin-console/organizations/members/members.component.ts
https://bitwarden.atlassian.net/browse/PM-23130
Fix the Invite Member button missing in Admin Console for Providers when the `pm-19917-separate-custom-role-permissions` feature flag was turned on.
This was caused by reactive code accessing a class property that wasn't set yet. There's no reason why it should only be limited to Providers - it's a race condition - but Providers specifically seem to lose the race.
I have created a tech debt ticket to refactor this component to be more reactive. We shouldn't have a non-reactive `this.organization` class property at all.
- Used …
=> [PM-23130] Fix race condition for invite member button

apps/web/src/app/oss-routing.module.ts, libs/components/src/anon-layout/anon-layout-wrapper.component.html, libs/components/src/anon-layout/anon-layout-wrapper.component.ts, libs/components/src/anon-layout/anon-layout.component.html, libs/components/src/anon-layout/anon-layout.component.ts, libs/components/src/anon-layout/anon-layout.mdx, libs/components/src/anon-layout/anon-layout.stories.ts
https://bitwarden.atlassian.net/browse/PM-17737
Originally, we thought adding subtitle width control would be a good idea. Instead, I realized that it would be a better UX to just make the existing max width control the width of the title, subtitle, and primary content area.  As auth no longer owns this component, happy to discuss this if y'all disagree w/ this approach! 
Secondarily, one of my goals is to shrink https://github.com/bitwarden/clients/pull/15319 by removing the straightforward anon-layout changes. 
See [storybook](https://62a88a6de5b807fa98886113-fvaiihvkcm.chromatic.com/?path=/docs/component-library-anon-layout--docs).
- …
=> PM-17737 - AnonLayout - Consolidate max width instead of providing subtitle width control

apps/desktop/src/main/window.main.ts
https://bitwarden.atlassian.net/browse/PM-791
Resolves https://github.com/bitwarden/clients/issues/4675
This PR fixes an issue where the desktop vault’s zoom level would reset to the previously saved value whenever the user locks the vault. Previously, we only persisted the zoom factor when the window was closing, so any zoom adjustments made during an open session were never saved until shutdown. As a result, locking the vault (which does not close the window) caused the UI to revert to the old zoom on the next navigation.
Changes:
- In `WindowMain.createWindow()`, add a listener on `webContents` for the `zoom-changed` event  
- Immediately capture the new `zoomFactor` on each zoom in/out/reset and update the persisted `WindowState` via `desktopSettingsService.setWindow(...)`  
- Retain …
=> fix(desktop): save zoom level to state when it is adjusted

bitwarden_license/bit-common/src/dirt/reports/risk-insights/models/password-health.ts, bitwarden_license/bit-common/src/dirt/reports/risk-insights/services/risk-insights-api.service.spec.ts, bitwarden_license/bit-common/src/dirt/reports/risk-insights/services/risk-insights-api.service.ts
https://bitwarden.atlassian.net/browse/PM-20578
Create an api service that fetches and saves data
none at this time …
=> PM-20578 Added api to fetch and save data

libs/common/src/platform/state/implementations/default-active-user-state.spec.ts, libs/common/src/platform/state/implementations/default-global-state.provider.ts, libs/common/src/platform/state/implementations/default-global-state.ts, libs/common/src/platform/state/implementations/default-single-user-state.provider.ts, libs/common/src/platform/state/implementations/default-single-user-state.ts, libs/common/src/platform/state/implementations/specific-state.provider.spec.ts, libs/common/src/platform/state/implementations/state-base.ts, libs/common/src/platform/state/implementations/util.ts, libs/common/src/platform/state/state-event-registrar.service.spec.ts, libs/common/src/platform/state/state-event-runner.service.spec.ts, libs/common/src/platform/state/state-event-runner.service.ts
https://bitwarden.atlassian.net/browse/PM-23205
This change updates every import of StorageServiceProvider, AbstractStorageService, and ObservableStorageService throughout the common state code to pull from the new @bitwarden/storage-core package instead of their old relative paths. The cuts out one of the issues that needs to be resolved before state can hold its own as a library without importing common. …
=> refactor(state): point storage imports to @bitwarden/storage-core

libs/vault/src/components/totp-countdown/totp-countdown.component.spec.ts, libs/vault/src/components/totp-countdown/totp-countdown.component.ts
[PM-23226](https://bitwarden.atlassian.net/browse/PM-23226)
The ToTp component was setting an observable in `ngOnInit`, with the nature of switching views on desktop the `LoginCredentialsViewComponent` is re-rendered by not re-initialized. This causes the old observable to stay intact with old cipher data when jumping between two ciphers.
- Using `ngOnChanges` the totp observable can be reset when the cipher is updated.
|Before|After|
|-|-|
|<video src="https://github.com/user-attachments/assets/d2bf14ac-01d9-456c-b4f2-760f2d51db4f" /> |<video src="https://github.com/user-attachments/assets/2e59c38e-d06c-48cc-94db-e9448f35683d"/>|
- 🤔 …
=> [PM-23226] ToTp updating on Desktop

package.json
This is a random PR
Storybook keeps crashing locally for me after a few rebuilds, so this gives it more memory to avoid that problem …
=> Increase memory limit for local storybook npm command

libs/components/src/dialog/dialog.service.stories.ts, libs/components/src/dialog/dialog/dialog.component.html, libs/components/src/dialog/dialog/dialog.component.ts, libs/components/src/dialog/simple-dialog/simple-dialog.service.stories.ts
[CL-748](https://bitwarden.atlassian.net/browse/CL-748)
This PR adds support for non-dismissable dialogs and simple dialogs. Specifically:
- A dialog opened with the dialog service can be marked as non-dismissable with the `disableClose` option, which will now hide the X button and prevents escape key and clickaway functionality.
- A simple dialog opened with the dialog service can be marked as non-dismissable with the `disableClose` option, which prevents escape key and clickaway functionality.
Stories have been added to Storybook to provide clear code examples for the following use cases:
- Non-dismissable dialog with only a primary footer button
- Non-dismissable simple dialog with only a primary footer button
- Non-dismissable simple dialog with no footer buttons
- Contributor …
=> [CL-748] Support nondismissable dialogs and simple dialogs

apps/desktop/src/autofill/modal/credentials/fido2-create.component.ts
**Passkeys filtering breaks on SSH keys**
This PR filters ciphers shown in the UI to only be of type login. …
=> Autofill: Fix matching url on native paskeys

apps/browser/src/platform/popup/layout/popup-tab-navigation.component.html, libs/components/src/button/button.component.ts, libs/components/src/item/item.component.ts, libs/components/src/menu/menu-item.directive.ts, libs/components/src/table/row.directive.ts, libs/components/src/toggle-group/toggle.component.ts, libs/components/src/tw-theme.css, libs/components/tailwind.config.base.js
https://bitwarden.atlassian.net/browse/CL-686
Updated components to use new `--color-hover-default` variable. Components updated include
- item
- toggle group
- secondary button
- table row
- menu list item
- extension nav buttons
- ❓ …
=> [CL-686] updated hover states

libs/vault/src/cipher-form/components/sshkey-section/sshkey-section.component.html
[PM-22782](https://bitwarden.atlassian.net/browse/PM-22782)
Add missing aria label / title to the Import SSH Key button. This feature is only available on browser and desktop. 
|Browser|Desktop
|-|-|
|<img width="525" alt="Screenshot 2025-07-07 at 12 45 15 PM" src="https://github.com/user-attachments/assets/210f85d3-7d99-408a-9864-40cb73e6d24a" />|<img width="728" alt="Screenshot 2025-07-07 at 12 42 10 PM" src="https://github.com/user-attachments/assets/3ac328aa-c058-40af-80ec-e62242d6297a" />|
- 🎨 …
=> [PM-22782] Missing SSH Key title/label

apps/web/src/app/admin-console/organizations/collections/vault.component.ts
[PM-21943](https://bitwarden.atlassian.net/browse/PM-21943)
Users cannot edit a cipher that has recently been moved to unassigned (before another full sync).  
When deleting a collection from the action menu the ciphers are not refreshed. The unassigned cipher still has a defined `collectionId` stored in local state. 
This works when a user deletes a collection when viewing it, the ciphers are cleared for this logic path. To solve all other means of deleting a collection I moved the clear logic outside of the redirection logic.
|Deleting while viewing|Bug Before| Fixed|
|-|-|-|
|<video src="https://github.com/user-attachments/assets/4ea043dd-77bf-4e80-9531-fe41774511d1" /> |<video src="https://github.com/user-attachments/assets/6014ed7b-14f3-4ee4-b0df-fb4f312df06f" /> |<video …
=> [PM-21943] Editing Unassigned Cipher

bitwarden_license/bit-web/src/app/dirt/access-intelligence/risk-insights.component.html, bitwarden_license/bit-web/src/app/dirt/access-intelligence/risk-insights.component.ts
[PM-23353](https://bitwarden.atlassian.net/browse/PM-23353)
This pull request fixes extra padding that was introduced after changes to the `bit-layout` component. The changes fixed the need for a nested `bit-layout` which is unsupported. The nested component was needed due to the page throwing an error when the drawer couldn't access the higher level `bit-layout`
Note: Hide white space changes when reviewing to more easily see the changes made.
<details>
<summary>Before</summary>
</details>
<details>
<summary> After </summary>
</details> …
=> [PM-23353] Fix second drawer padding

libs/vault/src/cipher-view/autofill-options/autofill-options-view.component.html
[PM-23697](https://bitwarden.atlassian.net/browse/PM-23697)
Copy the unmodified login URI without prepending any protocol when the copy value button is clicked.
https://github.com/user-attachments/assets/fa34435d-89c5-4e68-b64a-ec17e5ef635c …
=> [PM-23697] Copy unmodified login uri instead of launchUri

apps/browser/webpack.config.js, apps/desktop/webpack.renderer.js
https://bitwarden.atlassian.net/browse/PM-23550
Prevent fonts from being cached in the browser extension and desktop. This change was previously made in web: #5054  …
=> [PM-23550] prevent fonts from being cached in browser extension and desktop clients

apps/web/src/app/billing/organizations/payment-details/organization-payment-details.component.ts
https://bitwarden.atlassian.net/browse/PM-23687
This PR resolves an issue where the billing address section of the payment details page would not reload with new information when the user adds a payment method (with a billing address) when they currently have no billing address on file. 
https://github.com/user-attachments/assets/510fd771-abb4-4187-8020-cd14e69c9402 …
=> [PM-23687] Fix reload on organization-payment-details page

apps/web/src/app/admin-console/organizations/collections/vault.component.ts, apps/web/src/app/vault/individual-vault/vault.component.ts, libs/common/src/vault/abstractions/cipher.service.ts, libs/common/src/vault/services/cipher.service.ts
https://bitwarden.atlassian.net/browse/PM-20554
This PR fixes an issue in the web client where you are unable restore deleted unassigned items.
https://github.com/user-attachments/assets/3adcae8b-cc97-4f5c-94d5-e4545045a304
- ❓ …
=> [PM-20554] Fix bulk restore for unassigned items

apps/browser/src/popup/components/extension-anon-layout-wrapper/extension-anon-layout-wrapper.component.ts, libs/components/src/anon-layout/anon-layout-wrapper.component.ts
https://bitwarden.atlassian.net/browse/CL-765
To make the `AnonLayout` `hideIcon` configuration option reset properly. 
Before (account registration had `hideIcon` temporarily set to true):
https://github.com/user-attachments/assets/1ea48fb1-981a-4fbf-b0ac-7ccb5ad4c2aa
After fix:
https://github.com/user-attachments/assets/b67ba1c3-6d30-4f14-811d-bac65cd8376f …
=> CL-765 - AnonLayoutWrapperComponents - make hideIcon reset properly

apps/web/src/app/vault/individual-vault/vault.component.ts
[PM-23199](https://bitwarden.atlassian.net/browse/PM-23199)
Added `distinctUntilChange` to decrease repeated filtering in the web search. Tested on a vault with 5000+ items.
NOTE: Only added the change to web. Below is a screen recording of desktop, the search seems to be fine on the same large vault. 
Web
https://github.com/user-attachments/assets/d5207b8c-7328-4cff-aa34-dfc4ed224953
Desktop
https://github.com/user-attachments/assets/a9f7c496-d46d-439c-b18d-9e4d1749b916 …
=> [PM-23199] update web vault search to use distinctUntilChange

libs/common/src/platform/abstractions/config/config-api.service.abstraction.ts, libs/common/src/platform/abstractions/environment.service.ts, libs/common/src/platform/services/config/config-api.service.ts, libs/common/src/platform/services/config/config.service.spec.ts, libs/common/src/platform/services/config/default-config.service.ts, libs/common/src/platform/services/default-environment.service.ts
Reverts bitwarden/clients#15432.
We noticed that with this change in place we are not making a `/api/config` request when logging in when starting from an empty state.
=> [PM-23062] Revert Fix extra SignalR connections

apps/browser/src/vault/popup/services/vault-popup-items.service.ts
Stacked on top of https://github.com/bitwarden/clients/pull/15174
[PM-23350](https://bitwarden.atlassian.net/browse/PM-23350)
The `cipherViews$` observable can [emit null when the cache is cleared](https://github.com/bitwarden/clients/blob/6a48db8dac2cd9beab2a7affb4212fc95b61747e/libs/common/src/vault/services/cipher.service.ts#L230-L231). This occurs when a cipher is moved to a collection in the browser. Adding a filter to the observable does the trick.
|Before|After
|-|-|
|<video src="https://github.com/user-attachments/assets/6273dec9-d4b2-4c3c-b007-da62a8946488" /> |<video src="https://github.com/user-attachments/assets/e43c3659-34ac-4fca-999d-444181fa7bc2" />|
- ❓ …
=> [PM-23350] Filter out null ciphers in browser

apps/browser/src/_locales/en/messages.json
[PM-14939](https://bitwarden.atlassian.net/browse/PM-14939) (follow-up)
This PR adds some translations to Browser. These translations are necessary when the user is using the browser extension, but using it as an extension tab (which means the device management will use the table, not the item-list view)
These screenshots show the Table view when using an _Extension tab_ (they are not showing the Web client). …
=> [PM-14939] (follow-up) add missing translations for when user is using Browser extension as an extension tab"

apps/web/src/app/vault/components/vault-items/vault-items.component.ts, apps/web/src/app/vault/components/vault-items/vault-items.stories.ts
https://bitwarden.atlassian.net/browse/PM-23478
This PR fixes an issue where the restricted item types weren't being properly filtered out in the AC vault.
https://github.com/user-attachments/assets/b2e66363-56aa-4d2e-947e-a71ae26ed777
- …
=> [PM-23478] - Can view org's cards in AC

apps/browser/src/vault/popup/components/vault-v2/vault-list-items-container/vault-list-items-container.component.ts
[PM-24012](https://bitwarden.atlassian.net/browse/PM-24012)
When there are no ciphers `[{ciphers: []}]` was being passed into the template for `cipherGroups()`. The conditionals within the template are checking for an empty array rather than an empty `ciphers` within the array. 
Fix: Only return ciphers directly when they are not sorted by groups _and_ there is at least one. 
|Before|After|
|-|-|
|<img width="390" height="607" alt="image" src="https://github.com/user-attachments/assets/de770d47-3877-4700-97ef-e8338185054c" />|<img width="390" height="607" alt="Screenshot 2025-07-21 at 11 25 50 PM" src="https://github.com/user-attachments/assets/959e88af-7099-4182-b958-b7ffd28b9088" />| …
=> [PM-24012] Empty Favorites section

apps/desktop/electron-builder.json
https://bitwarden.atlassian.net/browse/PM-527
Build `rpm` without symlinks, to prevent conflicts with other Electron apps.  This is a similar issue as was encountered by Ferdium, and the PR author [here](https://github.com/ferdium/ferdium-app/issues/416) has extensive research. …
=> [PM-527] Build rpm with _build_id_links none to avoid file conflicts

apps/web/src/app/billing/settings/sponsored-families.component.html
https://bitwarden.atlassian.net/browse/PM-23856
🐛 **Problem**
The application encountered the following Angular runtime error:
`NG0950: Input is required but no value is available yet.`
This occurred because a <bit-option> used as a placeholder was passing an empty string ("") to the required [value] input, which Angular considered invalid during initial rendering, especially when using strict input validation or signals.
✅ **Solution**
- Replaced "" with null for the [value] input of the disabled placeholder <bit-option> to provide a safe and defined value.
- Ensured compatibility with Angular’s strict input validation by avoiding undefined or delayed values.
💡 **Notes**
- If necessary, consumers of this select can treat null as a sentinel value indicating no selection.
- This change …
=> [PM 23856] Organization not found in dropdown for Free Bitwarden Families for Enterprise Subscriptions

.github/workflows/chromatic.yml, libs/components/tailwind.config.base.js
[CL-801](https://bitwarden.atlassian.net/browse/CL-801)
We noticed that a component library PR did not trigger the expected Chromatic UI Test diffs. The PR modified a file that is included in our chromatic workflow’s `externals` configuration, which tells Chromatic to rerun snapshots when anything in “externals” is changed because these files are processed outside of Webpack, where Chromatic sources its dependency graph from. ([Docs here](https://www.chromatic.com/docs/turbosnap/setup/#specify-external-files-to-trigger-a-full-re-test-when-they-change)) The formatting for our externals didn't match what’s in the docs, so I am updating it to match.
This first screenshot is from the PR that had the issue. It is the workflow run from the original commit that changed the file specified in …
=> [CL-801] Fix chromatic.yml externals formatting

apps/desktop/src/app/accounts/settings.component.html, apps/desktop/src/locales/en/messages.json
From the original PR - changes the name of the autotype checkbox from `Enable autotype shortcut` to `Enable Autotype`.
This has been approved by design, and it is still hidden behind a feature flag.
---
This PR deletes the transition key and adds back the fixed original.
Original: https://github.com/bitwarden/clients/pull/15753
New Look:
- 👍 (`:+1:`) …
=> Remove Transition Key

apps/web/src/app/core/core.module.ts, apps/web/src/theme.ts
[PM-23374](https://bitwarden.atlassian.net/browse/PM-23374)
This PR ensures that we are defaulting to the user's system theme when a user visits the web app for the first time and makes a new account. It also removes some old legacy code from the theme file to clean up some tech debt.
Both videos taken with MacOS set to dark mode, and Chrome browser set to system.
Before:
https://github.com/user-attachments/assets/f4856087-aa70-4a0d-93cb-36aa771de8a8
After:
https://github.com/user-attachments/assets/18dc23a5-46ae-4e27-a14a-e594fddce18a …
=> [PM-23374] Default to system theme in web app

apps/web/src/app/vault/components/vault-items/vault-items.component.ts
[PM-24219](https://bitwarden.atlassian.net/browse/PM-24219)
- Use bang operator to check for the presence of an 1organizationId1, strict equality with `null` doesn't work with the SDK as `undefined` is populated rather than `null`
<video src="https://github.com/user-attachments/assets/a1ed4de4-e389-4734-933b-00974450db48" />
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) …
=> [PM-24219] CipherListView from SDK cannot be bulk moved.

apps/desktop/desktop_native/autotype/src/lib.rs, apps/desktop/desktop_native/autotype/src/linux.rs, apps/desktop/desktop_native/autotype/src/macos.rs, apps/desktop/desktop_native/autotype/src/windows.rs, apps/desktop/desktop_native/napi/index.d.ts, apps/desktop/desktop_native/napi/src/lib.rs
https://bitwarden.atlassian.net/browse/PM-22790
Adds the ability to send UTF-16 encoded characters as keyboard events to the focused location in Windows for the new autotype feature. This feature is behind a feature flag.
Please note, the `println` will be removed in a future PR, for now it provides logging during development after input insertion:
```rust
let e = unsafe { GetLastError().to_hresult().message() };
println!("type_input() called, GetLastError() is: {:?}", e);
```
(We can eventually use the `GetLastError()` function for more precise error handling.)
- Used …
=> [PM-22790] Adds SendInput() Functionality to the Autotype Crate

apps/browser/src/platform/popup/layout/popup-layout.stories.ts, libs/components/src/card/card.stories.ts, libs/components/src/checkbox/checkbox.stories.ts, libs/components/src/form-field/form-field.stories.ts, libs/components/src/popover/popover.stories.ts, libs/components/src/stories/icons/icons.stories.ts, libs/components/src/stories/kitchen-sink/components/kitchen-sink-main.component.ts, libs/components/src/toggle-group/toggle-group.stories.ts
[CL-786](https://bitwarden.atlassian.net/browse/CL-786)
[CL-770](https://bitwarden.atlassian.net/browse/CL-770)
[CL-778](https://bitwarden.atlassian.net/browse/CL-778)
[CL-787](https://bitwarden.atlassian.net/browse/CL-787)
[CL-789](https://bitwarden.atlassian.net/browse/CL-789)
[CL-771](https://bitwarden.atlassian.net/browse/CL-771)
[CL-781](https://bitwarden.atlassian.net/browse/CL-781)
This PR fixes some small accessibility errors in our storybook stories. The goal is to reduce the amount of noise in the accessibility results so that real issues are more easily discoverable. There are still remaining errors that are legitimate errors in some components.
- Written new unit and / or integration tests …
=> [CL-768] Fix small a11y errors in storybook stories

apps/web/src/app/admin-console/organizations/members/members.component.ts
https://bitwarden.atlassian.net/browse/PM-24261
This Pr fixes a race condition introduced in the CollectionService vNext refactor. Use of `withLatestFrom` operator caused an issue where this observable never emits. Switching to `combineLatest` resolves the issue.
https://github.com/user-attachments/assets/340a1f13-7132-49e5-9e3b-0231840531a8
- 👍 …
=> [PM-24261] Switch withLatestFrom to combineLatest

apps/desktop/src/autofill/services/desktop-fido2-user-interface.service.ts
[PM-23873](https://bitwarden.atlassian.net/browse/PM-23873)
When registering or authenticating a passkey when the vault is locked the blue header is missing.  Now the header will be displayed if the traffic light OS buttons are displayed since they are displayed together.
Old:
New: …
=> Display the blue header on the locked vault passkey flow

apps/desktop/macos/autofill-extension/Base.lproj/CredentialProviderViewController.xib, apps/desktop/macos/autofill-extension/CredentialProviderViewController.swift
https://bitwarden.atlassian.net/browse/PM-23848
This PR changes adds an approproraite error response to the the `provideCredentialWithoutUserInteraction`-interface and uses the `prepareInterface`-method instead.
The Pull request also fixes a fatal-warning about a missing outlet. …
=> PM-23848: Use the MacOS UI-friendly API instead

apps/web/src/app/vault/individual-vault/vault-header/vault-header.component.html, libs/vault/src/cipher-form/cipher-form-container.ts, libs/vault/src/cipher-form/components/cipher-form.component.ts, libs/vault/src/cipher-form/components/item-details/item-details-section.component.ts, libs/vault/src/cipher-form/components/sshkey-section/sshkey-section.component.ts, libs/vault/src/components/new-cipher-menu/new-cipher-menu.component.html, libs/vault/src/components/new-cipher-menu/new-cipher-menu.component.ts
https://bitwarden.atlassian.net/browse/PM-24232
This PR does the following:
- "Folder" will no longer be shown as an option in the AC "New" menu, a regression from [creating the new item menu component](https://github.com/bitwarden/clients/pull/15467)
- the sshkey form will no longer be incorrectly enabled, a regression from [ Update cipher form component to restrict editing old My Vault items](https://github.com/bitwarden/clients/pull/15687)
https://github.com/user-attachments/assets/15d86077-f19f-4439-b5a5-91a02bc4e5dc
- …
=> [PM-24232] - [Defect][Web] Admin Console - SSH key and Folder should not show as options from New button

apps/web/src/app/billing/accounts/trial-initiation/trial-billing-step.component.ts, libs/common/src/billing/abstractions/tax.service.abstraction.ts, libs/common/src/billing/services/tax.service.ts
https://bitwarden.atlassian.net/browse/PM-24309
Genuinely not sure how this was working before unless something changed that I can't identify, but the return type in `clients` on the API invocation that was providing the tax amount for organization trial estimation did not match what `server` was giving back. This PR resolves that.
https://github.com/user-attachments/assets/55d7d470-cce2-45b8-a133-58ffda0b6887 …
=> [PM-24309] Fix `TaxService.previewTaxAmountForOrganizationTrial` return type

libs/auth/src/angular/login/login.component.html
[PM-19475](https://bitwarden.atlassian.net/browse/PM-19475)
Login component button icons were not previously marked `aria-hidden="true"`. This would cause undesirable screen reader output of `[?]`, and in certain cases could prevent a user from properly navigating off the element.
Adding the aria attributes to Passkey, SSO, and Device login buttons should improve the user experience for users with screen readers.
https://github.com/user-attachments/assets/af2478a1-733a-45f9-bae5-b621a7585123
- …
=> [PM-19475] Login component button icons are not marked as aria-hidden="true"

apps/browser/src/autofill/background/abstractions/notification.background.ts, apps/browser/src/autofill/background/abstractions/overlay-notifications.background.ts, apps/browser/src/autofill/background/notification.background.spec.ts, apps/browser/src/autofill/background/notification.background.ts, apps/browser/src/autofill/background/overlay-notifications.background.ts
Related to [PM-19848](https://bitwarden.atlassian.net/browse/PM-19848)
Small refactor to:
- remove unnecessary message passing syntax as part of a longstanding plan for regular function calls.
- make calling a smaller subset of notification checks possible by allowing a skippable notification type argument 
- aim for consistency in notification attempt checks/triggers
- simplify and unite the signatures of these functions to allow for a terser notification processing function
- uses a switch case to resolve notification attempt checks instead of relying on dedicated functions (co-locating all the possible states for ease of readability) 
- colocates the at risk notification async calls to notification.background with the other notification background logic (instead of in …
=> Combine notif check/attempt, end msg pass syntax.

libs/key-management-ui/src/lock/components/lock.component.spec.ts, libs/key-management-ui/src/lock/components/lock.component.ts
https://bitwarden.atlassian.net/browse/PM-18535
Adds master password unlock unit test coverage to Lock component. …
=> [PM-18535] lock component unit test coverage for master password unlock

apps/web/src/app/auth/settings/security/device-management-old.component.html, apps/web/src/app/billing/payment/components/enter-payment-method.component.ts, libs/angular/src/auth/device-management/device-management.component.html, libs/vault/src/cipher-form/components/login-details-section/login-details-section.component.html
[CL-753](https://bitwarden.atlassian.net/browse/CL-753)
This PR fixes a spacing issue in the client implementations of the popover.
Please be sure to do this for future implementations!
Also, auth team, the popover on the devices page is overlapping the trigger button, so there is something weird going on with the trigger button.
Sorry billing, I couldn't figure out where to find your popover 🤦‍♀️ 
|------- | ----- |
| <img width="788" height="785" alt="Screenshot 2025-07-30 at 9 58 38 AM" src="https://github.com/user-attachments/assets/9dc56477-e014-4a76-949f-d711de1879d2" /> | <img width="788" height="785" alt="Screenshot 2025-07-30 at 9 50 00 AM" src="https://github.com/user-attachments/assets/d8c5a5b7-07af-4a46-b48a-3736e7e5b52e" /> |
| <img width="788" height="785" …
=> [CL-753] Fix popover spacing in client code

libs/components/src/color-password/color-password.component.ts
[CL-682](https://bitwarden.atlassian.net/browse/CL-682)
This PR converts the one enum in the CL to a const, to follow our coding guidelines and remove an eslint ignore. …
=> [CL-682] Convert color password enum to const

apps/web/src/app/platform/web-environment.service.ts, libs/common/src/platform/abstractions/config/config-api.service.abstraction.ts, libs/common/src/platform/abstractions/environment.service.ts, libs/common/src/platform/services/config/config-api.service.ts, libs/common/src/platform/services/config/config.service.spec.ts, libs/common/src/platform/services/config/default-config.service.ts, libs/common/src/platform/services/default-environment.service.ts
https://bitwarden.atlassian.net/browse/PM-23062
https://bitwarden.atlassian.net/browse/PM-23800
Unrevert of https://github.com/bitwarden/clients/pull/15432 and then a fix for web not calling `/config` when it has empty state. The problem was that we were now supplying global config, meant to be used as a backup, for when user config fails to be retrieved. The problem is we were also checking it for if it was up to date and to skip retrieving altogether. The fix is to add another argument one for the actual existing server config and one that should be used as the fallback.
- …
=> Fix extra signalr connection web

apps/cli/src/tools/send/send.program.ts
https://bitwarden.atlassian.net/browse/PM-19054
Hide the `bw send --email` flag until end-to-end connectivity is available.
=> [PM-19054] hide experimental `bw send --email` flag

apps/browser/src/background/main.background.ts, apps/browser/src/vault/popup/components/at-risk-passwords/at-risk-passwords.component.spec.ts, apps/browser/src/vault/popup/components/at-risk-passwords/at-risk-passwords.component.ts, libs/common/src/enums/feature-flag.enum.ts
[PM-20205](https://bitwarden.atlassian.net/browse/PM-20205)
Remove pm-10609-end-user-notifications feature flag
Respective PR that utilized the feature flag:
- https://github.com/bitwarden/clients/pull/14116
[PM-20205]: …
=> [PM-20205] Remove pm-10609-end-user-notifications feature flag

apps/browser/src/auth/popup/account-switching/current-account.component.html
[PM-16263](https://bitwarden.atlassian.net/browse/PM-16263)
Updates the outline color of user account avatar to prefer the _primary_ theme color. This creates consistency with other element outlines for both light and dark themes.
Should remain unchanged. …
=> fix(current-account-component): [Auth/PM-16263] In dark mode, browser profile icon outline is white.

libs/common/src/vault/services/restricted-item-types.service.spec.ts, libs/common/src/vault/services/restricted-item-types.service.ts
[PM-24689](https://bitwarden.atlassian.net/browse/PM-24689)
The `restricted$` observable internally subscribes to `activeAccount$` (instead of accepting a userId) and needs to consider if the active user is null (e.g. during logout).
https://github.com/user-attachments/assets/69851939-1e0c-4df8-bed5-2543575708a6 …
=> [PM-24689] Handle possible null active account

libs/common/src/vault/services/cipher.service.ts
[PM-24379](https://bitwarden.atlassian.net/browse/PM-24379)
The `getManyFromApiForOrganization` call was passing `any` into the `decryptOrganizationCiphersResponse()` instead of a `ListResponse`. This led to mismatched types for the CipherPermissionApi object which was missing its prototype that comes from the `ListResponse` constructor.
- 👍 (`:+1:`) …
=> [PM-24379] Use ListResponse constructor for API response

libs/vault/src/cipher-view/login-credentials/login-credentials-view.component.html, libs/vault/src/cipher-view/login-credentials/login-credentials-view.component.ts
https://bitwarden.atlassian.net/browse/PM-24082
This PR fixes an issue where, in the desktop app in the cipher view, if the password visibility was toggled on and the user selected a cipher from a different org, the password visibility state would remain visible. This was due to the password input field type not being reset.
https://github.com/user-attachments/assets/2f3c06be-73ac-4ae6-b9b7-50c833f4a062
https://github.com/user-attachments/assets/226a46f0-b8f1-4a8c-b4fd-fbb28320139f …
=> [PM-24082] - Unauthorized Password Visibility in Bitwarden Desktop App

libs/common/src/tools/state/buffered-state.ts, libs/tools/generator/extensions/legacy/src/legacy-password-generation.service.ts
https://bitwarden.atlassian.net/browse/PM-22309
Adds explicit return types that TypeScript complains about being inferred in 5.8.
```
libs/common/src/tools/state/buffered-state.ts:48:17 - error TS7011: Function expression, which lacks return-type annotation, implicitly has an 'readonly [false, any]' return type.
48       concatMap(async ([hasValue, [shouldOverwrite, dependency]]) => {
libs/common/src/tools/state/buffered-state.ts:74:37 - error TS7011: Function expression, which lacks return-type annotation, implicitly has an 'any' return type.
74     await this.bufferedState.update((state) => {
libs/tools/generator/extensions/legacy/src/legacy-password-generation.service.ts:348:9 - error TS7010: 'with', which lacks return-type annotation, implicitly has an 'any[]' return type.
348 …
```
=> [PM-22309] Resolve TypeScript 5.8 blockers for tool owned files

apps/web/src/app/billing/accounts/trial-initiation/trial-billing-step.component.html, apps/web/src/app/billing/accounts/trial-initiation/trial-billing-step.component.ts
https://bitwarden.atlassian.net/browse/PM-24351
The marketing initiated Families plan billing flow was displaying the VAT/Tax ID field, which should only be shown for Business plan subscriptions (Teams and Enterprise). This created confusion for users signing up for personal/family plans.
**Root Cause**
The TrialBillingStepComponent was using ManageTaxInformationComponent without specifying the showTaxIdField property, causing it to default to true and display the VAT field for all organization types, including Families plans.
**Solution**
- Added showTaxIdField getter to TrialBillingStepComponent that returns false for ProductTierType.Families plans
- Updated the component template to pass the showTaxIdField property to ManageTaxInformationComponent
**Changes Made**
1. …
=> [PM-24351] Fix: Hide VAT/Tax ID field for Families plans in marketing initiated billing flow

libs/common/src/platform/services/sdk/default-sdk.service.spec.ts, libs/common/src/platform/services/sdk/default-sdk.service.ts
With this change, the SDK service requires the StateProvider and the tests mock it with FakeStateProvider. This has no functional differences and is a follow up to https://github.com/bitwarden/clients/pull/14839#discussion_r2291420727
- ❓ …
=> Use FakeStateProvider in SdkService tests

apps/web/src/app/vault/components/setup-extension/setup-extension.component.spec.ts, apps/web/src/app/vault/components/setup-extension/setup-extension.component.ts, apps/web/src/app/vault/guards/setup-extension-redirect.guard.spec.ts, apps/web/src/app/vault/guards/setup-extension-redirect.guard.ts, libs/auth/src/angular/registration/registration-finish/registration-finish.component.ts, libs/common/src/enums/feature-flag.enum.ts
[PM-22371](https://bitwarden.atlassian.net/browse/PM-22371)
removing the `PM19315EndUserActivationMvp` flag and it's usages.  …
=> [PM-22371] remove end user activation flag

apps/desktop/src/locales/en/messages.json, libs/vault/src/cipher-form/components/attachments/delete-attachment/delete-attachment.component.ts, libs/vault/src/components/download-attachment/download-attachment.component.html, libs/vault/src/components/download-attachment/download-attachment.component.spec.ts, libs/vault/src/components/download-attachment/download-attachment.component.ts
[PM-22987](https://bitwarden.atlassian.net/browse/PM-22987)
When an attachment cannot be decrypted hide the ability to download it. 
- Also noticed that the desktop was missing some translations for the add attachment dialog. Tacked those on here too.
The scenario for a user to end up in this spot has sense been fixed, I made some notes in the `QA testing notes` of the ticket if you'd like to test locally. 
|Desktop|Web|Extension|
|-|-|-|
|<video src="https://github.com/user-attachments/assets/63e54f83-7351-4743-89fa-852af2409626"/>|<video src="https://github.com/user-attachments/assets/4dd745a6-a593-4685-8478-ea47c633aae5"/>|<video src="https://github.com/user-attachments/assets/81651d64-4d9e-4afe-acd7-d18d9dcee0ce" />| …
=> [PM-22987] Hide download for corrupt attachments

apps/browser/src/platform/services/local-backed-session-storage.service.ts
Fixing an issue where the cache gets corrupted (incorrectly set to `null`) due to a race condition.
I think there are two solutions to this problem:
1. Always write to local storage _FIRST_. That way if anyone reads local storage they will always get the correct value and can update the cache with it without consequences.
2. When reading the data, double-check the `cache` to see if it has changed while we were checking local storage. If it has then trust the cache because that is always updated first (and that update is atomic).
I think 1. has the issue that if we update `localStorage` first then `get` might get called before we have a chance to update the `cache` causing it to return incorrect data. This PR therefore implements 2.
1. `LocalBackedSessionStorageService.get` gets called, …
=> Fix a cache race condition in local backed session storage

apps/cli/src/auth/commands/login.command.ts
[PM-25001](https://bitwarden.atlassian.net/browse/PM-25001)
Refresh token is not being fetched properly intermittently, this should rectify the issue by not fetching the refresh token on the `fullSync` call right after login.
We think the root cause of the refresh token fetch error is a rate limit that is being intermittently triggered on a full sync similar to [this PR](https://github.com/bitwarden/clients/pull/14423). …
=> [PM-25001] Do not fetch refresh token on sync during login

apps/web/src/locales/en/messages.json, libs/vault/src/cipher-view/sshkey-sections/sshkey-view.component.html
https://bitwarden.atlassian.net/browse/PM-16938
Fixes the copy toast messages for ssh key items in the web and browser. Currently the toast message for all three items is `Copy Successful`.
Also fixes the hover labels to show `Copy <item>`, instead of just `<item>`. …
=> Fix copy labels and toasts for ssh key items in web and browser

libs/common/src/platform/services/sdk/default-sdk.service.spec.ts, libs/vault/src/services/copy-cipher-field.service.ts
N/A
https://github.com/bitwarden/clients/pull/14962 introduced some typing changes, on `main` these are failing because of:
- `string | undefined` being passed to `uuidAsString`
- Missing `load_flags` within a test file for the SDK client
N/A
- ⛏ (`:pick:`) for minor or …
=> Fix SDK typings

libs/vault/src/cipher-form/services/default-cipher-form-cache.service.spec.ts, libs/vault/src/cipher-form/services/default-cipher-form-cache.service.ts
[PM-24796](https://bitwarden.atlassian.net/browse/PM-24796)
The `{ ...cipherView } as CipherView` was stripping the `CipherView` prototype which would lead to failures when calling the `toSdkCipherView` method during save.
Another alternative would be to pass a custom equality operator to the `WritableSignal` during its construction, however that would involve modifying the `ViewCacheService` interface to support passing in `CreateSignalOptions` with a `equal: () => false` value. This would then allow us to simply set the same `cipherView` multiple times to the signal and it would still propagate. …
=> [PM-24796] Keep CipherView prototype when caching cipher form value

apps/web/src/app/admin-console/organizations/layouts/organization-layout.component.html, apps/web/src/app/admin-console/organizations/layouts/organization-layout.component.ts, apps/web/src/app/admin-console/organizations/manage/events.component.html, apps/web/src/app/admin-console/organizations/manage/events.component.ts, apps/web/src/app/admin-console/organizations/policies/policies.component.html, apps/web/src/app/admin-console/organizations/policies/policies.component.ts, apps/web/src/app/admin-console/organizations/policies/policy-edit.component.html, apps/web/src/app/admin-console/organizations/policies/policy-edit.component.ts, apps/web/src/app/admin-console/organizations/reporting/organization-reporting-routing.module.ts, apps/web/src/app/admin-console/organizations/settings/organization-settings-routing.module.ts, apps/web/src/app/admin-console/organizations/shared/components/collection-dialog/collection-dialog.component.ts, apps/web/src/app/vault/individual-vault/vault-header/vault-header.component.ts, libs/angular/src/services/jslib-services.module.ts, libs/common/src/billing/abstractions/organization-billing.service.ts, libs/common/src/billing/services/organization-billing.service.spec.ts, libs/common/src/billing/services/organization-billing.service.ts, libs/common/src/enums/feature-flag.enum.ts
https://bitwarden.atlassian.net/browse/PM-24550
This PR retains code for Event Log changes and reverts code for Policy changes from the implementation of feature flag PM-12276.
- The visibility of the "eventLogs" tab in the admin console is now determined solely by organization properties (`canAccessEventLogs`, `useEvents`) removing the feature flag.
- Remove the feature flag check when validating free org limits. 
- Remove the feature flag check when adding a collection.
- The visibility of the "policies" tab in the admin console is now determined solely by organization properties (`isOwner`, `canManagePolicies`) rather than `ConfigService` using feature flag logic.
- The code related to upgrading plans for policies has been removed from `PoliciesComponent` and `PolicyEditComponent`.
- …
=> [PM-24550] Remove Feature Flag Code for PM-12276

libs/vault/src/cipher-form/components/custom-fields/custom-fields.component.html, libs/vault/src/cipher-form/components/custom-fields/custom-fields.component.ts
[PM-24797](https://bitwarden.atlassian.net/browse/PM-24797)
When adding a new cipher the user should be able to edit & reorder a hidden field
The `canEdit` method was not handing the add state of the form where `originalCipherView` will be null.
The hidden field was still draggable even when the user could not edit it - I disabled the drag-ability when the user cannot edit. 
<video src="https://github.com/user-attachments/assets/c585f5ae-b36b-46ed-a4b7-1f61dab46d21" />
- 🎨 (`:art:`) for suggestions …
=> [PM-24797] Hidden custom fields for new ciphers

.github/CODEOWNERS
It was [suggested](https://github.com/bitwarden/clients/pull/13963#discussion_r2315813514) that Autofill should own the macos_provider that provides passkey data to the MacOS Autofill API's. It makes sense. …
=> Autofill should own the macos_provider

apps/web/src/app/billing/organizations/organization-subscription-selfhost.component.html, apps/web/src/app/billing/shared/self-hosting-license-uploader/self-hosting-license-uploader.component.html, apps/web/src/app/billing/shared/update-license.component.html
https://bitwarden.atlassian.net/browse/CL-641
**🐛 Issue**
Resolves spacing issues in the self-hosted admin console billing section where UI elements were too close together, affecting readability and user experience.
**Reference: CL-641**
**🔧 Changes**
**1. Licensing and Billing Management Buttons**
- File: `organization-subscription-selfhost.component.html`
- Fix: Added proper horizontal spacing between "Manage billing token" and "Sync license" buttons
- Implementation: Applied tw-flex tw-gap-2 classes to create consistent button spacing
**2. License Upload File Selection**
- File: `update-license.component.html`
- Fix: Improved spacing between "Choose File" button and filename display
- Implementation:
- Added `tw-flex tw-items-center tw-gap-3 `for proper horizontal alignment
- Wrapped …
=> [CL-641][Defect][Web] More spacing defects including self-host environment

bitwarden_license/bit-web/src/app/secrets-manager/overview/overview.component.html, bitwarden_license/bit-web/src/app/secrets-manager/shared/secrets-list.component.html, bitwarden_license/bit-web/src/app/secrets-manager/shared/secrets-list.component.ts
https://bitwarden.atlassian.net/browse/SM-1548
Update secrets list to use virtual scrolling to improve performance of the page. …
=> [SM-1548] Updating the secrets list to use <bit-table-scroll>

apps/web/src/app/admin-console/organizations/collections/vault.component.ts, apps/web/src/app/admin-console/organizations/shared/components/access-selector/access-selector.component.ts, apps/web/src/app/admin-console/organizations/shared/components/collection-dialog/collection-dialog.component.html, apps/web/src/app/admin-console/organizations/shared/components/collection-dialog/collection-dialog.component.ts, apps/web/src/app/vault/components/vault-items/vault-collection-row.component.html, apps/web/src/app/vault/components/vault-items/vault-collection-row.component.ts, apps/web/src/app/vault/components/vault-items/vault-item-event.ts
https://bitwarden.atlassian.net/browse/PM-23998
This PR makes the default permission in the collection dialog "Manage" when being accessed from the collections page by clicking the add access button. The ability to click the add access button to open the collection dialog is also new functionality.
- 📝 …
=> [PM-23998] Make manage the initial permission when clicking the add access badge

libs/importer/src/components/import.component.ts
https://bitwarden.atlassian.net/browse/PM-25600
Addresses an issue when selecting an import format (non-chromium) when the use-chromium-importer feature flag is enabled
```
Unhandled error in angular TypeError: Cannot read properties of undefined (reading 'includes')
at Object.next (import.component.ts:263:43)
at ConsumerObserver.next (Subscriber.ts:161:25)
at Subscriber._next (Subscriber.ts:119:22)
at Subscriber.next (Subscriber.ts:75:12)
at map.ts:58:20
at OperatorSubscriber._this._next (OperatorSubscriber.ts:70:13)
at Subscriber.next (Subscriber.ts:75:12)
at combineLatest.ts:272:34
at OperatorSubscriber._this._next (OperatorSubscriber.ts:70:13)
at Subscriber.next (Subscriber.ts:75:12)
```
was logged on the console, as the existing import formats have not been defined in the …
=> [PM-25600] Fix issue with import format selector

libs/pricing/src/components/cart-summary/cart-summary.component.html, libs/pricing/src/components/cart-summary/cart-summary.component.mdx, libs/pricing/src/components/cart-summary/cart-summary.component.spec.ts, libs/pricing/src/components/cart-summary/cart-summary.component.stories.ts, libs/pricing/src/components/cart-summary/cart-summary.component.ts, libs/pricing/src/index.ts
https://bitwarden.atlassian.net/browse/PM-24982
This PR Adds a new cart summary component to the pricing library.
This component provides a reusable way to display order summary information, including line items for password manager, additional storage, and secrets manager, along with estimated tax and total cost. It includes a collapsible interface to toggle between a summary view and a detailed view of the cart items. Also includes storybook stories and documentation for the new component.
- 📓  Has a description of the change
- ✏️ Has tests
- 📝 Has documentation
- 📚  Has a story in storybook
🖌️ Design Note: I don't currently have access to Figma or the component just yet, so some things may be off a bit.
https://github.com/user-attachments/assets/59d7a418-002f-4395-a09d-02119452886f
- …
=> [PM-24982] Create Cart Summary Component in Bitwarden Pricing

apps/browser/src/vault/popup/components/vault-v2/view-v2/view-v2.component.ts
[PM-25634](https://bitwarden.atlassian.net/browse/PM-25634)
- Login on Extension on Firefox
- Have a login for a website that has MP reprompt enabled
- Navigate to website
- Autofill login
- Change filled PW before submitting
- Submit form
- Click Update from Notification Bar
- Enter MP on new popup
Expected: Popup is dismissed, creds updated, notification bar switches to let me know creds have been updated
Actual: Popup hangs, creds not updated, notification bar not updated …
=> [PM-25634] Bugfix - Cannot update new credentials with MP reprompt on Firefox

bitwarden_license/bit-web/src/app/dirt/access-intelligence/app-table-row-scrollable.component.html
https://bitwarden.atlassian.net/browse/PM-19989
1. The table is sorted by at-risk passwords, but the sort indicator was not reflected in the table header. 
2. Previously, only selecting the application name would open the drawer component. This behavior has been updated to ensure the drawer opens as expected when the row is clicked. …
=> [PM-19989] Fix table header sort indicator and enable drawer open on row click

bitwarden_license/bit-web/src/app/secrets-manager/integrations/integrations.module.ts
https://bitwarden.atlassian.net/browse/PM-25694
A change made to the integrations module in the admin module cause the integrations module to break in the Secrets manager module. This PR should fix it.
- 🤔 …
=> [PM-25694] [Defect] Secrets manager + AC integrations page not listing any integrations

libs/importer/src/importers/bitwarden/bitwarden-password-protected-importer.spec.ts, libs/importer/src/importers/bitwarden/bitwarden-password-protected-importer.ts
https://bitwarden.atlassian.net/browse/PM-23906
When the user tries to import a password protected file entering the wrong password, then the error message The cipher's MAC doesn't match the expected value is displayed
Log in to Bitwarden
Navigate to Tools > Export vault
Select Json Encrypted (Password protected)
Enter a password and save the export file 
Navigate to Tools > Import Data 
Import the file previously generated and enter the wrong password 
The error message The cipher's MAC doesn't match the expected value is displayed
`encryptService.decryptString()` calls a method in the internal SDK which when provided an invalid key returns `CryptoError::InvalidMac`. The originating callsite has been wrapped in a try/catch in order to intercept the error and return false so that logic in …
=> PM-23906 Wrap sdk callsite with try/catch to handle errors appropriately

apps/desktop/desktop_native/bitwarden_chromium_importer/src/windows.rs, libs/importer/src/services/import.service.ts
https://bitwarden.atlassian.net/browse/PM-25629
Hide / disable the "direct from browser" Chromium importer for Brave on Windows desktop clients only.  …
=> [PM-25629] Hide Chromium importer for Brave/Windows only

bitwarden_license/bit-common/src/dirt/reports/risk-insights/models/report-models.ts, bitwarden_license/bit-common/src/dirt/reports/risk-insights/services/risk-insights-report.service.ts, bitwarden_license/bit-web/src/app/dirt/access-intelligence/all-applications.component.ts, bitwarden_license/bit-web/src/app/dirt/access-intelligence/critical-applications.component.ts
https://bitwarden.atlassian.net/browse/PM-25838
Adding properties to the risk insights report summary and renaming the type to match the new naming convention. New properties added are to assist in report metrics and reduce recalculation on load.  …
=> [PM-25838] Adding new properties to the summary and renaming the type

bitwarden_license/bit-web/src/app/dirt/organization-integrations/integration-dialog/connect-dialog/connect-dialog-hec.component.spec.ts, bitwarden_license/bit-web/src/app/dirt/organization-integrations/integration-dialog/connect-dialog/connect-dialog-hec.component.ts
https://bitwarden.atlassian.net/browse/PM-25991
The pattern validator could not use a customized message.
Also, the pattern validator was never used within Bitwarden.
Given that, the validation was changed to use a minLength
- ❓ …
=> [PM-25991] Change validation from pattern to minLength

apps/desktop/desktop_native/autotype/src/windows.rs, apps/desktop/src/autofill/main/main-desktop-autotype.service.ts, apps/desktop/src/autofill/services/desktop-autotype.service.ts
https://bitwarden.atlassian.net/browse/PM-26013
Two small updates:
1. Update the default key sequence for autotype to be: `Ctrl+Shift+B`
2. Update the window title uri prefix that we match on to match our other schemes: `apptitle://`
To note: there is a better way to do the key sequencing, this will be partially updated in a PR coming soon for PM-22785, and then after MVP we can improve the desktop native API further. …
=> [PM-26013] Small Autotype Updates

apps/browser/src/autofill/popup/settings/autofill.component.html, apps/browser/src/autofill/popup/settings/notifications.component.html, apps/browser/src/popup/scss/box.scss, apps/desktop/src/scss/box.scss
https://bitwarden.atlassian.net/browse/PM-21812
https://bitwarden.atlassian.net/browse/PM-21813
- To continue to migrate all existing components to Tailwind, it's important for us to remove any unnecessary and/or unused stylings.
- I verified that removal of the non-Tailwind classes did not impact the UI by double-checking against similarly style bit-icon elements (see screenshot below). 
- I successfully ran all unit tests locally and performed a variety of spot checking throughout the browser settings prior to raising the PR. 
| Autofill Before (Dark) | Autofill After (Dark) |
|----|----|
| <img width="478" height="488" alt="Autofill - Before Dark" src="https://github.com/user-attachments/assets/de41eb47-d136-487c-a55c-279d8e7bbc47" /> | <img width="466" height="422" alt="Screenshot …
=> [PM-21812][PM-21813] Migrate autofill and notification settings

apps/browser/src/key-management/key-connector/remove-password.component.html
https://bitwarden.atlassian.net/browse/PM-21815?focusedCommentId=110347
The goal is to bring the component up-to-date with the proper components form the component library and to utilize only the most current Tailwind CSS classes for styling. I ensured that existing functionality remained in tact after the change by removing the master password from a dev-test account and only leveraged SSO. All local unit tests are passing as expected.
| Light Theme | Dark Theme |
|-----|-----|
|  <img width="455" height="661" alt="After - Light Theme" src="https://github.com/user-attachments/assets/504f70c0-2d39-4382-a23d-2d48bc407df9" /> |  <img width="452" height="631" alt="After - Dark Theme" src="https://github.com/user-attachments/assets/cce7e3a0-6fca-4e83-a770-5ea1ef9d57f0" /> |
- Contributor …
=> [PM-21815] - Implement component form the component library & Tailwind CSS

libs/common/src/vault/models/domain/login.ts
[PM-25172](https://bitwarden.atlassian.net/browse/PM-25172)
Do not null coalesce a login's autofillOnPageLoad setting to false when mapping from the `SdkLoginView`. Undefined is a valid option that defaults to the extension autofill on page load setting
https://github.com/user-attachments/assets/4c5273c3-a81c-4dfb-ac4c-1d448e6ec601 …
=> [PM-25172] Fix default autofill on page load cipher level setting

apps/browser/src/popup/scss/base.scss
https://bitwarden.atlassian.net/browse/PM-26105
This PR fixes an issue in Safari/FF where the main app-root element isn't occupying the full height of the window. This was caused from a [previous PR](https://github.com/bitwarden/clients/pull/16292) to fix the toast element not showing over dialogs which removed the `position: absolute` style from `app-root`. 
Test with At Risk Carousel dialog and a test toast notification 
https://github.com/user-attachments/assets/2d87523d-6b63-42d2-81c3-c9c614a63c06
- …
=> [PM-26105] - [Defect][Browser] Firefox and Safari toolbar is in the middle of extension

apps/web/src/app/core/core.module.ts, apps/web/src/app/vault/components/vault-item-dialog/vault-item-dialog.component.ts, apps/web/src/app/vault/individual-vault/view.component.ts, apps/web/src/app/vault/services/web-premium-upgrade-prompt.service.ts
[PM-26125](https://bitwarden.atlassian.net/browse/PM-26125)
[PM-26149](https://bitwarden.atlassian.net/browse/PM-26149)
https://github.com/bitwarden/clients/pull/16461 introduced a unified approach using premium badge component. A couple of usage locations on the web were missing the `WebVaultPremiumUpgradePromptService` provider. 
- To handle on a wide scale basis I moved the provider to `core.module.ts`
- In doing so I had to make the `DialogRef` optional as the `DialogRef` isn't available in the root module. Components like the `VaultItemDialogComponent` that are a dialog and contain the premium badge component have to add the `WebVaultPremiumUpgradePromptService` as a provider so `DialogRef` is populated.
<video src="https://github.com/user-attachments/assets/e2d0dcbb-1faa-47fc-bb35-66 …
=> [PM-26125][PM-26149] `WebVaultPremiumUpgradePromptService` provider

bitwarden_license/bit-web/src/app/dirt/access-intelligence/app-table-row-scrollable.component.html
https://bitwarden.atlassian.net/browse/PM-25893
Make headers and 3 dot menu keyboard focusable. …
=> [PM-25893] Accessibility for risk insights

apps/browser/src/autofill/background/abstractions/overlay.background.ts, apps/browser/src/autofill/background/overlay.background.ts, apps/browser/src/autofill/services/abstractions/autofill.service.ts, apps/browser/src/autofill/services/autofill-overlay-content.service.ts, apps/browser/src/autofill/services/autofill.service.ts
[PM-25073](https://bitwarden.atlassian.net/browse/PM-25073)
On the sign-in form for bedbathandbeyond.com (hover over `Account` and click `Sign In`) the page has two forms.  One is to Create and Account and the other is to Sign In.  Autofill would always fill incorrectly.  Now we check to see if the currently focused form has autofill fields and we only autofill those.  If it doesn't we fall back to regular autofill behavior. …
=> Autofill form that has the focus

libs/node/package.json, libs/node/project.json
- https://bitwarden.atlassian.net/browse/PM-20254
- https://github.com/bitwarden/clients/pull/16538
- https://github.com/bitwarden/clients/pull/16539
- https://github.com/bitwarden/clients/pull/16540
- https://github.com/bitwarden/clients/pull/16542
- https://github.com/bitwarden/clients/pull/16544
- https://github.com/bitwarden/clients/pull/16545
- https://github.com/bitwarden/clients/pull/16546
- https://github.com/bitwarden/clients/pull/16547
- https://github.com/bitwarden/clients/pull/16548
- https://github.com/bitwarden/clients/pull/16549
- https://github.com/bitwarden/clients/pull/16550
- https://github.com/bitwarden/clients/pull/16551
- https://github.com/bitwarden/clients/pull/16562
- https://github.com/bitwarden/clients/pull/16563
- https://github.com/bitwarden/clients/pull/16564 …
=> build: add nx configuration in libs/node

.github/workflows/test-browser-interactions.yml
[PM-26120](https://bitwarden.atlassian.net/browse/PM-26120)
We presently trigger “Autofill BIT checks” every time the “Build Browser” workflow completes. Since the chrome build artifact is a requirement for BIT, we should only run the triggering workflow when the “Build Browser” workflow actually succeeds
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future …
=> [PM-26120] Only run BIT trigger workflow when Build Browser workflow completes successfully

libs/common/src/platform/misc/utils.spec.ts, libs/common/src/platform/misc/utils.ts
https://bitwarden.atlassian.net/browse/PM-26186
I first discovered the issue here: https://github.com/bitwarden/clients/pull/16007/files#diff-8204084e4ff23efa6f4e62286432fea59ae914706140ba21a0b1c06cab29bd5dR162
`Utils.fromBufferToB64` only accepts ArrayBuffer inputs. This means callers cannot call `Utils.fromBufferToB64(<Uint8Array>)` without getting a `Type '"Uint8Array"' is not assignable to type '"ArrayBuffer"'.ts(2345)` error. We should update `fromBufferToB64` to broaden its signature to support an `ArrayBufferView` (e.g., `Uint8Array`) as we historically call it with `Uint8Array` anyway.
n/a …
=> Platform/PM-26186 - Utils.fromBufferToB64 - add type safety and ArrayBufferView support + tests

apps/desktop/src/autofill/services/desktop-autotype.service.ts
https://bitwarden.atlassian.net/browse/PM-26311
The bug is that autotype is being disabled when first starting the app and on a fresh login.
The root cause is the premium account check.
This fix adds protections to running check for premium account through billing service only when the account is not null and is not undefined.
See ticket for screen recordings. …
=> Fix desktop windows autotype disabled on first login

apps/cli/src/commands/list.command.ts
[PM-26440](https://bitwarden.atlassian.net/browse/PM-26440)
In https://github.com/bitwarden/clients/pull/16502 I introduced a refactor for handling the trash and archive filters on the `list` command. This logic was incorrect by only working when one of the `--trash` or `--archived` filters were defined. It also needs to consider when none of the are passed.
- This updates the logic to match the filter state directly to the state on the cipher, `options.trash === c.isDeleted`,  `options.archived === c.isArchived` and ensure that _both_ pass. 
<video src="https://github.com/user-attachments/assets/3ab8094b-361b-4e7a-8ae8-8edaef90440a"/>
- 🤔 …
=> [PM-26440] Fix logic for list filtering for trash and archived items

apps/desktop/src/platform/services/electron-storage.service.ts
https://bitwarden.atlassian.net/browse/PM-26318
Limits desktop's data store (`data.json`) to 0600 permissions, or read/write for current user and inaccessible otherwise. …
=> [PM-26318] Limit data.json to current user read/write

apps/browser/src/auth/services/auth-status-badge-updater.service.ts, apps/browser/src/autofill/services/autofill-badge-updater.service.ts, apps/browser/src/background/main.background.ts, apps/browser/src/platform/badge/badge-browser-api.ts, apps/browser/src/platform/badge/badge.service.spec.ts, apps/browser/src/platform/badge/badge.service.ts, apps/browser/src/platform/badge/scope.ts, apps/browser/src/platform/badge/state.ts, apps/browser/src/platform/badge/test/mock-badge-browser-api.ts, apps/browser/src/vault/services/at-risk-cipher-badge-updater.service.spec.ts, apps/browser/src/vault/services/at-risk-cipher-badge-updater.service.ts, libs/state/src/core/state-definitions.ts
Rewrites the badge service to not rely on state, that way these values won't be able to stay in memory.
This new design also greatly simplifies the usage by unifying general and tab-specific states into a single callback function.
- ❓ …
=> [PM-25488] Badge stays after lock when using pin

apps/web/src/locales/en/messages.json, bitwarden_license/bit-web/src/app/dirt/access-intelligence/all-activity.component.html, bitwarden_license/bit-web/src/app/dirt/access-intelligence/all-activity.component.ts
https://bitwarden.atlassian.net/browse/PM-26495
Change the empty state of the All activities tab …
=> [PM-26495] Activity tab empty state changed

libs/common/src/key-management/pin/pin-state.service.abstraction.ts, libs/common/src/key-management/pin/pin-state.service.implementation.ts, libs/common/src/key-management/pin/pin-state.service.spec.ts
https://bitwarden.atlassian.net/browse/PM-24124
The idea here is to disconnect the `VaultTimeoutSettingService` dependency on the `PinService` due to circular dependency issues:
Pin Service -> SDK Service -> Config Service -> Config API Service -> API Service -> Vault Timeout Settings Service -> Pin Service
This creates a `PinStateService` that is responsible for setting and getting Pin state. The `PinService` is still KM's official API surface and it is highly recommended to use that instead of reaching out to the `PinStateService`. 
`VaultTimeoutSettingService` would then replace the `PinService.isPinSet()` call with:
```
await pinStateService.getPinLockType(userId) !== "DISABLED";
```
Obviously not an ideal API, but necessary until Auth can disconnect VaultTimeoutSettings as a …
=> [PM-24124] Pin State Service

apps/desktop/src/main/window.main.ts
https://github.com/bitwarden/clients/issues/2617
Makes a small change to center the window of the desktop app when bounds change. ([#2617](https://github.com/bitwarden/clients/issues/2617))
This is my first commit, and I don't believe this would count as a major UX change so I have not made a forum post.
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future …
=> [PM-26196] Correct error with desktop window being off screen when displays are changed/unplugged

.github/workflows/test.yml
This was disabled in https://github.com/bitwarden/clients/pull/11003.
I'm opening a PR to re-enable so we have coverage in CI for windows unit tests.
Unit tests are being added to other crates outside of `core` (example: https://github.com/bitwarden/clients/pull/16710)
First tried enabling for all, but still was seeing the errors that resulted in 11003. So excluding only desktop_napi now. …
=> Re-enable CI to run rust unit tests in desktop_native on Windows platform

libs/common/src/platform/sync/default-sync.service.spec.ts
[PM-13422](https://bitwarden.atlassian.net/browse/PM-13422)
Updates the unit test `DefaultSyncService` > `fullSync` > `mutate 'last update time'` > `uses the current time when a sync is forced` to use [Jest's Fake Timers](https://jestjs.io/docs/jest-object#fake-timers) to make time predictable during a unit test. …
=> [PM-13422] Fix flaky test around sync time
