README.md
=> Some screenshots of the browser extension

src/_locales/fi/messages.json
Translated the new strings to Finnish.
=> Translated the new strings.

src/_locales/de/messages.json, store/de-DE/CAPTIONS.md, store/de-DE/COPY.md
This will add German translation to the bitwarden extension. I've also included the two store description files.
=> Add German translation files

src/_locales/nl/messages.json, store/nl-NL/CAPTIONS.md, store/nl-NL/COPY.md
I really like the idea of this project, and saw there wasn't a Dutch translation yet, so I decided to make one. I'm a native speaker.
=> Add Dutch translation

src/_locales/zh_CN/messages.json
Add Chinese translations and fixed an translation error.
=> Add Chinese Translations

src/_locales/zh_CN/messages.json
=> Chinese translation update

src/_locales/sv/messages.json
Swedish translations have been refined.
=> Translations

store/sv/COPY.md
Minor changes to some sentences
=> Slight text changes

src/_locales/en/messages.json, src/background.js, src/popup/app/settings/settingsFeaturesController.js, src/popup/app/settings/views/settingsFeatures.html, src/services/constantsService.js
=> Add option to disable content menu integation

src/_locales/it/messages.json, store/it/CAPTIONS.txt, store/it/COPY.txt
First upload of the italian translation for the bitwarden extension
=> Italian Translation

src/_locales/fr/messages.json
Correction of spelling mistakes + add strings (lines 626 to 650)
=> Corrections + new strings

src/popup/app/vault/views/vaultViewLogin.html
As discussed in #107, this adds the login's URI as a tooltip via a title attribute.
=> Show full URI of the login as a tooltip in the view login form (#107)

src/_locales/pt_PT/messages.json, store/pt_PT/CAPTIONS.md, store/pt_PT/COPY.md
I have a question though, when you say "free" does it mean software libre or just free for use?
=> pt_PT translation

src/_locales/fr/messages.json
=> Update french messages.json

store/pt_PT/COPY.md
=> Word repetition mistake in pt_PT

src/_locales/pt_PT/messages.json
Adding new strings for vault exporting.
=> Updating pt_PT translation

src/_locales/sv/messages.json
Added additional translated strings for organisations, context menu and exporting your vault.
=> Additional strings

src/content/notificationBar.js
Set Z-index to the maximum value so it is always on top
https://stackoverflow.com/a/25461690/1961513
=> Fix #234 Save notification hidden by elements with high z-index

src/popup/app/tools/tools.component.ts
Reused existing code from accountsLoginTwoFactorController.js as mentioned by @amenk in issue #352
=> on-premise support for "bitwarden Web Vault" tool

src/manifest.json
Fixes #392 
I'm not sure if this works or not, and I'd like to test this myself, but the extension is not able to build on Linux..
=> Execute the sidebar action with Ctrl+Shift+Comma

src/services/autofill.service.ts
I added some values that might be used by french developers in their forms.
Discussion started in #521
=> [WIP] Add possible french tags for card auto-fill

README.md
This changes the image to use https and it also has all the recent styling changes from recent updates 🙂
=> Update the README image to reflect current styling of extension popup

README.md
Just a simple little commit to move images and links over to only use https because we can :slightly_smiling_face:
=> Updating readme links and images to use https

src/services/autofill.service.ts
These should match `expirationDateMonth` and `expirationDateYear`
=> Add more expiration date fields

src/browser/browserApi.ts
I’m hoping you can release this quickly. It’s super annoying to close the popout tab manually and switching back and forth between the popout and page.
Partially addresses issue #642.
=> Close the popout as expected on Firefox on Android

src/services/autofill.service.ts
This commit intends to add support for `paymentCardExpiration`, I'm not sure anymore if that syntax will work 🤔
=> Add paymentCardExpiration met on Payplug

src/services/autofill.service.ts
=> Support Yurplan payment form

src/services/autofill.service.ts
Ticketac is a french website for spectacle tickets.
=> Add fields met on Ticketac payment form

src/services/autofill.service.ts
This fixes username entry on websites such as https://online.virginmoney.com
=> Add customer-id to username field names

package-lock.json, package.json, src/_locales/en/messages.json, src/popup/app.module.ts, src/popup/scss/box.scss, src/popup/vault/add-edit.component.html
Companion pull request for https://github.com/bitwarden/desktop/pull/237
Depends on the jslib pull request https://github.com/bitwarden/jslib/pull/35
=> Drag n drop sorting for custom fields 

src/services/browserPlatformUtils.service.ts
Vivaldi has u2f support.  With the following change I can login to the extension using u2f.
=> Support u2f on Vivaldi

src/background/main.background.ts
=> Unbreak building from git master

src/services/autofill.service.ts
=> Fix autofill with empty custom field

src/manifest.json
This is part #1 of fix for https://github.com/bitwarden/browser/issues/899
=> Fix for Firefox "Manage Extension Shortcuts" UI (part 1)

src/popup/vault/add-edit.component.ts
- **add-edit.component.ts**: adjusted strict equals comparison for string value of true
=> Fixed issue with strict equals operator

src/popup/vault/add-edit.component.html, src/popup/vault/add-edit.component.ts
- **add-edit.component.html**: Added missing `cloneMode` check for attachments visibility
- **add-edit.component.ts**: Added missing `cloneMode` check in the conditional for setting potentially null/empty name/URI fields
=> Added missing attachments conditional

src/_locales/en/messages.json, src/popup/app.module.ts, src/popup/generator/password-generator.component.html, src/popup/scss/misc.scss, src/popup/scss/variables.scss
Show a callout banner when policies are affecting the generator settings:
=> implement callout component w/ generator policy

README.md
Microsoft introduced a new logo for Microsoft Edge last year.   
This PR updates the logo in README.md   
Logo sourced from https://en.wikipedia.org/wiki/Microsoft_Edge#/media/File:Microsoft_Edge_logo_(2019).svg
=> Update Microsoft Edge logo

src/_locales/en/messages.json, src/background/commands.background.ts, src/background/contextMenus.background.ts, src/background/idle.background.ts, src/background/main.background.ts, src/background/runtime.background.ts, src/background/webRequest.background.ts, src/popup/accounts/lock.component.ts, src/popup/services/launch-guard.service.ts, src/popup/services/services.module.ts, src/popup/settings/settings.component.html, src/popup/settings/settings.component.ts
> Update the browser application to use the updated VaultTimeoutService to allow for logging out on an interval timeout. Allow users to choose what action takes place when the timer expires (Lock vs Log out)
- **jslib**: Update from `31a2574` -> `28e3fff`
- **messages.json**: Updated `lockOptions` string and added new strings for timeout action.
- **commands.background.ts**: Updated import. Updated constructor. Updated calls to use new `vaultTimeoutService`.
- **contextMenus.background.ts**: Updated import. Updated constructor. Updated calls to use new `vaultTimeoutService`.
- **idle.background.ts**: Updated import. Updated constructor. Updated calls to use new `vaultTimeoutService`. Added helper method for retrieving timeout options. Added comments to clarify magic ints and explain …
=> [Auto-Logout] Implement Vault Timeout Options

src/background/main.background.ts
- **jslib**: Update from `28e3fff` to `72e3893`
- **main.background.ts**: Updated `vaultTimeoutService` init
=> Update jslib (28e3fff -> 72e3893)

gulpfile.js
Revert back to name vs. thumbprint
=> Revert signature thumbprint

src/browser/browserApi.ts, src/safari/safari/SafariExtensionViewController.swift
Trying to put getAppPath _back_ into the handlers for the swift controller after styling issue with dist package.
=> try revert getAppPath

src/browser/browserApi.ts, src/safari/safari/SafariExtensionViewController.swift
So these still aren't being called and had no impact on the distribution package, so I'm taking it back out for now. I'll figure out the dist package issue separately.
=> Reapply removal of dead code

src/safari/safari/SafariExtensionViewController.swift
Even if `options?.currentWindow` is `true`, `SFSafariApplication.getActiveWindow` could still return `nil` for `win` completion handler parameter (according to the docs). This may be contributing to an application crash, and would make sense given the additional logging details which show the `"tabs_query"` command being handled at the same time the crash is occurring, consistently.
=> Potential fix for swift nil unwrap exception

src/safari/safari/SafariExtensionViewController.swift
Goal - Add an egregious amount of debug statements via `NSLog` so we can hopefully capture a better idea of exactly where this issue is coming from for the Safari crashes.
=> Ridiculously verbose debug build

src/safari/safari/SafariExtensionViewController.swift
Does exactly as the name implies... need to get these debug statements out of the `master` repo.
=> Removed verbose debug logging

src/background/main.background.ts
Check to make sure the user has access to premium before offering TOTP copying options in the context menu.
=> Check for premium access for totp copying option

src/background/idle.background.ts
> Fixes https://github.com/bitwarden/browser/issues/1254
- **idle.background.ts**: Make sure that `lock` is the default condition in case action is `null`
=> [Bug] On System Lock set lock as default action

src/popup/vault/view.component.html
null refs were occuring since cipher may not be inited yet
=> fix null ref of cipher.isDeleted

src/_locales/en/messages.json, src/popup/vault/add-edit.component.html, src/popup/vault/add-edit.component.ts
Some cleanup from this previous PR: https://github.com/bitwarden/browser/pull/1290
=> Cleanup current uris selection list

.gitignore, src/manifest.json
Also added to .gitignore the files needed/copied locally to debug the browser extension for safari (copy of browser html, css, js, etc.)
Version bump
=> Update jslib + version bump

src/popup/vault/add-edit.component.html, src/popup/vault/add-edit.component.ts
Updated Example text to be dynamic to current year using New Date(); and then a Date pipe to display properly in the UI.
=> Updated expiration year placeholder text to be dynamic

src/popup/services/services.module.ts, src/services/browserPlatformUtils.service.ts
Changes to ensure compatibility with https://github.com/bitwarden/jslib/pull/119
=> Support biometric changes in jslib

src/_locales/en/messages.json, src/background/main.background.ts, src/background/runtime.background.ts, src/background/tabs.background.ts, src/background/windows.background.ts, src/browser/browserApi.ts, src/content/sso.ts, src/popup/accounts/home.component.ts, src/popup/accounts/login.component.ts, src/popup/accounts/sso.component.ts, src/popup/vault/view.component.html, src/popup/vault/view.component.ts
- Finish some missing pieces from PR #1367
- String cleanup
- Reload page details when tabs or window changed. This is necessary for when the popup is docked in the sidebar
- Fix vulnerability in SSO auth result
- Other misc cleanup of lint and formatting issues from past contributions
=> finish autofill from view, other misc cleanup

src/_locales/en/messages.json, src/content/sso.ts, src/popup/accounts/login.component.html, src/popup/accounts/set-password.component.html, src/popup/accounts/set-password.component.ts, src/popup/app-routing.module.ts, src/popup/app.module.ts, src/popup/services/services.module.ts
Added the set password flow into the browser based SSO.
**src/popup/accounts/set-password.component.html
src/popup/accounts/set-password.component.ts
src/popup/app.module.ts**
New Component
**src/popup/app-routing.module.ts** 
Add routing for new set-password route.
**src/popup/services/services.module.ts**
Crypto Function Service was throwing errors in multiple components, and was coming in as null. Cleaned up the references in this module and it seems to have fixed it..
=> Added set password flow to browser based SSO

src/popup/accounts/set-password.component.html, src/popup/accounts/set-password.component.ts, src/popup/scss/base.scss, src/popup/services/services.module.ts
- Fix CryptoFunctionService registration with service module
- Add syncLoading flag to set password flow. @vincentsalucci Might want to make sure it looks decent on the UI. I kinda just threw it in there.
=> Fix CryptoFunctionService and implement syncLoading

src/manifest.json
=> version bump

src/services/autofill.service.ts
=> Update last used index when auto-fill worked correctly

src/content/autofill.js
=> use element classList to add animations

src/_locales/en/messages.json, src/popup/accounts/register.component.html, src/popup/accounts/register.component.ts, src/popup/scss/misc.scss
> In order to complete GDPR compliance, moving forward with new user creation, we need to have explicit user interaction for Terms of Service and Privacy Policy acknowledgement.
- **register.component.html**: Added new checkbox and label elements. Styled similarly to other footer text within this component - with `box-content-row` styling.
- **messages.json**: Added label message and error message for policy acceptance.
- **misc.scss**: Added `checkbox` styling
- **jslib**: Update jslib from d84d6da to 5e50aa1
=> [GDPR] Adjusted TOS/Privacy acceptance

src/_locales/en/messages.json, src/popup/settings/export.component.html
Adds encrypted json export option and accompanying warning message.
=> add support for encrypted json export

src/popup/services/services.module.ts, src/services/browserPlatformUtils.service.ts
Depends on https://github.com/bitwarden/jslib/pull/161.
Closes https://github.com/bitwarden/browser/issues/1256.
=> feat: Use system theme if available

package-lock.json
Update jslib for browser (and fix the build)
=> jslib update

src/_locales/en/messages.json, src/popup/settings/export.component.html
React to PR https://github.com/bitwarden/jslib/pull/238
=> warning dialog is now handled in base component

src/background/nativeMessaging.background.ts
Sometimes when restarting the desktop application the connection to the native messaging proxy would silently disconnect. This PR resolves it by wrapping `postMessage` in try-catch.
=> Resolve native messaging silently disconnecting

src/background/runtime.background.ts
https://app.asana.com/0/1195018406457675/1153292148278664
As a user, I would like to be able to configure another user with access to manage user/group/collection assignment without being able to see organization passwords that are not directly assigned to them.
1. Changed the personal ownership Admin check to a permission check
=> Implemented Custom role and permissions

src/background/nativeMessaging.background.ts
Depends on https://github.com/bitwarden/jslib/pull/244
=> SystemService, Store if fingerprints have been validated or not

src/popup/accounts/lock.component.html
Changed the link to a button which can be selected using tab.
=> Make biometric button tabable to improve accessibility

src/background/contextMenus.background.ts, src/background/main.background.ts, src/background/nativeMessaging.background.ts, src/background/runtime.background.ts, src/browser/browserApi.ts, src/browser/safariApp.ts, src/content/autofiller.ts, src/content/notificationBar.ts, src/content/shortcuts.ts, src/content/sso.ts, src/popup/app-routing.module.ts, src/popup/app.component.ts, src/popup/app.module.ts, src/services/autofill.service.ts, src/services/browserPlatformUtils.service.ts, src/services/browserStorage.service.ts, tslint.json
Match linter rules and autofixes
* **tslint.json**: Match rules with other TS projects
Others are autofixes
=> Linter updates and fixes

src/popup/app-routing.animations.ts, src/popup/app-routing.module.ts, src/popup/app.component.ts, src/popup/app.module.ts, src/popup/components/send-list.component.html, src/popup/send/send-groupings.component.ts, src/popup/send/send-type.component.html, src/popup/send/send-type.component.ts
> Add a component to view filtered sends by `SendType`. Include searching capabilities.
- **jslib**: Update from ee164be to 0951424
- **app-routing.animations.ts**: Added slide in/out animations for transitioning from `Tabs/Send-Groupings` to `Send-Type`
- **app-routing.module.ts**: Added `send-type` route
- **app.component.ts**: Added all new state data cleanup that mirrored existing groupings/ciphers logic. @kspearrin Any reason why you don't currently cleanup the `GroupingsComponentScope` data that lives in the `stateService` object as well? I wasn't sure if was necessary/missing. Left a TODO for a future PR
- **app.module.ts**: Added `SendTypeComponent` as a module
- **send-list.component.ts**: Reverted icon changes from previous PR. `Disabled` = `fa-warning` && `Max Access Count` = …
=> [Send] Type component

src/popup/accounts/home.component.ts, src/popup/accounts/two-factor.component.ts, src/popup/send/send-add-edit.component.ts, src/popup/services/services.module.ts, src/popup/settings/excluded-domains.component.ts, src/popup/settings/folder-add-edit.component.ts, src/popup/settings/settings.component.ts, src/popup/vault/add-edit.component.ts, src/popup/vault/attachments.component.ts, src/popup/vault/ciphers.component.ts, src/popup/vault/collections.component.ts, src/popup/vault/current-tab.component.ts, src/popup/vault/groupings.component.ts, src/popup/vault/password-history.component.ts, src/popup/vault/share.component.ts, src/popup/vault/view.component.ts, src/services/vaultTimeout.service.ts
> Recent lint changes have caused a lot of warnings. Fix all lint warnings for a clean build!
- **home.component.ts**: Adjusted import grouping/order
- **two-factor.component.ts**: Adjusted import grouping and removed unnecessary parens
- **send-add-edit.component.ts**: Removed unnecessary parens
- **services.module**: Adjusted import grouping and fixed `Shadow name` lint warning
- **exluded-domains.component.ts**: Adjusted import grouping/order and removed unnecessary parens
- **folder-add-edit.component.ts**: Removed unnecessary parens
- **settings.component.ts**: Removed unnecessary parens and added trailing comma
- **add-edit.component.ts**: Removed unnecessary parens
- **attachments.component.ts**: Removed unnecessary parens
- **ciphers.component.ts**: Removed unnecessary parens
- …
=> [Cleanup] Fixed lint warnings

.github/workflows/build.yml, .github/workflows/release.yml
Adding in the build and release workflows to the browser extension. These are both pretty easy and straight forward.
- **.github/workflows/build.yml:** creating the build workflow
- **.github/workflows/release.yml:** creating the release workflow
There shouldn't be any.
=> Adding build/release workflows

src/_locales/en/messages.json, src/services/browserPlatformUtils.service.ts
Companion to https://github.com/bitwarden/web/pull/866.
* update `showDialog` to allow html
* update locales
Doesn't depend on the latest changes to jslib [here](https://github.com/bitwarden/jslib/pull/295), but should probably be updated anyway to make all jslib versions consistent.
=> Encrypted export warning

src/popup/send/send-add-edit.component.html
Addresses https://app.asana.com/0/1183359552741420/1200039404738005/f
-  Fixes (1) by using the correct list sources for the safari time dropdowns. 
-  Fixes (2) by supplying the correct date format to the date input polyfill
=> fixed a few send date fallback bugs

src/manifest.json
Preparing for a patch release to address Firefox issue; may potentially have another fix for Safari, but unsure at this point. Either way we'll be ready for testing and a patch release ASAP.
=> version bump to 1.49.1

README.md
The UI element seems to have changed. Now states the correct UI element.
=> Correct UI element in readme

src/_locales/en/messages.json, src/popup/send/send-add-edit.component.html, src/popup/send/send-add-edit.component.ts
> Fix bug: Chromium browsers in Linux lose extension focus when selecting a file to upload during Send creation.
- **messages.json**: Added `sendLinuxChromiumFileWarning`
- **send-add-edit.component.html**: Fixed some formatting. Added linux chromium text/conditional to banner
- **send-add-edit.component.ts**: Added logic to properly show/hide file selctor/banner as necessary
Fixes #1688
=> [Send] Added pop out banner for linux os

src/popup/settings/premium.component.ts
Companion PR to bitwarden/jslib#311. Update jslib to get premium user changes.
* **premium.component.ts**: Changes dependencies from TokenService to UserService
=> Fix Premium user notification

src/_locales/en/messages.json, src/popup/send/send-add-edit.component.html
Browser implementation of https://github.com/bitwarden/server/pull/1234.
=> Hide email address in Sends

src/_locales/en/messages.json, src/background/main.background.ts, src/popup/services/services.module.ts, src/popup/vault/attachments.component.ts
Implement azure direct upload changes in browser.
* **messaged.json**: update message to reflect current limit
* **main.background**: update service dependencies for fileUploadService.
* **services.module.ts**: add FileUploadService to service provider
=> Use azure direct upload for send and attachments

src/background/main.background.ts, src/popup/services/popup-search.service.ts, src/popup/services/services.module.ts, src/services/browserPlatformUtils.service.ts
I added some breaking changes to jslib https://github.com/bitwarden/jslib/pull/332, bumping jslib to resolve this issues for everyone else.
=> [Chore] Bump jslib

src/popup/send/send-add-edit.component.ts
Browser implementation of https://github.com/bitwarden/web/pull/915
Note: very few changes on this one, as no popup alert is shown to the user and all other logic is in jslib.
Depends on jslib update.
=> Require user to verify email to use file Send

package-lock.json, package.json, src/background/commands.background.ts, src/background/contextMenus.background.ts, src/background/main.background.ts, src/background/runtime.background.ts, src/popup/app.component.ts, src/popup/app.module.ts, src/popup/components/action-buttons.component.ts, src/popup/components/pop-out.component.ts, src/popup/services/services.module.ts, src/popup/settings/options.component.ts, src/popup/settings/settings.component.ts, src/popup/settings/sync.component.ts, src/popup/vault/ciphers.component.ts, src/popup/vault/current-tab.component.ts, src/popup/vault/groupings.component.ts, src/services/browserPlatformUtils.service.ts
Remove the last remnants of the dead analytics code.
Depends on https://github.com/bitwarden/jslib/pull/345
=> Remove dead code

src/popup/components/action-buttons.component.ts
Password re-prompt was missing a conditional check which caused it to trigger for every cipher ignoring if they
=> Fix password re-prompt triggering on non-reprompt items

src/_locales/en/messages.json, src/popup/scss/box.scss, src/popup/settings/options.component.html, src/popup/settings/options.component.ts, src/services/autofill.service.ts
* reorganize and add headings to the Options page
* tidy up after #1626
=> Organize Options page and add headings

src/popup/vault/add-edit.component.ts
Fixed Name & URI 1 Fields populated incorrectly when creating new login in popout window (#1816)
=> Fixed Name & URI 1 Fields Populated Incorrectly

src/_locales/en/messages.json, src/background/runtime.background.ts
Browser implementation of https://github.com/bitwarden/mobile/pull/1395.
Screenshot:
=> Explain how to verify email for Sends

src/background/main.background.ts
Bump jslib for https://github.com/bitwarden/jslib/pull/369
=> Bump jslib

src/content/autofill.js
Adds the option for web developers to exclude fields with an attribute ("data-bwignore"), also added the LastPass variant of this feature("data-lpignore") for better compatibility with existing pages.
=> Minor change to the autofill content script to allow for manual exclusions by web developers.

src/_locales/en/messages.json
Change "Enable Auto-fill On Page Load" to "Enable Auto-fill on Page Load".
The word "on" should not be capitalize on title because it is a preposition.
Source : https://www.grammarly.com/blog/capitalization-in-the-titles/
=> English mistake correction

src/manifest.json
> Bump version for upcoming release from `1.50.0` to `1.51.0`
- **src/manifest.json**: Bump version
=> [Version] Bump to 1.51.0

store/locales/en/copy.resx
Crowdin sync failed due to invalid XML error on en/copy.resx file.
=> Fix & encoding in resx XML

src/background/main.background.ts, src/background/runtime.background.ts, src/popup/accounts/register.component.ts, src/popup/accounts/sso.component.ts, src/popup/services/services.module.ts, src/popup/settings/settings.component.ts
Bumps jslib to support the changes in bitwarden/jslib#435
=> Add support for helpers in environment service

src/popup/app.module.ts, src/popup/components/cipher-row.component.html, src/popup/vault/ciphers.component.html, src/popup/vault/groupings.component.html
Update browser to use the custom virtual scroll strategy here: https://github.com/bitwarden/jslib/pull/452
Includes an update to jslib.
=> Use custom virtual scroll strategy

src/_locales/en/messages.json, src/popup/accounts/login.component.ts, src/popup/accounts/set-password.component.ts, src/popup/accounts/sso.component.ts, src/popup/accounts/two-factor.component.ts, src/popup/accounts/update-temp-password.component.html, src/popup/accounts/update-temp-password.component.ts, src/popup/app-routing.module.ts, src/popup/app.module.ts
> Allow browser client to force a password update after an admin resets a user's master password.
- **login.component**: Added `userService` and overrode `onSuccessfulLoginNavigate` to check for `forcePasswordReset` after full sync
- **set-password.component**: Added `userService` and overrode `onSuccessfulLoginNavigate` to check for `forcePasswordReset` after full sync
- **sso.component**: Added `userService` and overrode `onSuccessfulLoginNavigate` to check for `forcePasswordReset` after full sync
- **two-factor.component**: Added `userService` and overrode `onSuccessfulLoginNavigate` to check for `forcePasswordReset` after full sync
- **update-temp-password.component.html**: Created UI
- **update-temp-password.component.ts**: Created component class
- **app-routing.module**: Added …
=> [Reset Password v1] Update Temp Password

.github/workflows/crowdin-sync.yml
Adding in the Crowdin Sync workflow that we spiked for Web. Changed the project ID. This will need testing in `master` since the workflow doesn't exist yet
=> Adding the crowdin sync workflow

src/manifest.json
Note: this will also be cherry picked to `rc`
=> Version bump to 1.52.0

src/_locales/en/messages.json
The Crowdin sync changed the English file which is our source of truth from commit 05ba96d3d5db76eb887c078da60150fc01c202c4
=> Reverting the Crowdin English changes

src/manifest.json
Note: Will be cherry picked to `rc`.
=> Bump version to 1.52.1

.github/workflows/build.yml, .github/workflows/crowdin-sync.yml, .github/workflows/release.yml
These changes were based off the linter output.
=> Update workflows with linter suggestions

src/_locales/en/messages.json, src/background/main.background.ts, src/content/contextMenuHandler.ts, src/popup/settings/export.component.html, src/popup/settings/export.component.ts
Adds support for the new policy which disables personal vault export.
Asana: https://app.asana.com/0/1198901840263430/1200900473757543
Depends on: https://github.com/bitwarden/jslib/pull/482
=> Disable Private Vault Export Policy

src/popup/accounts/set-password.component.html
> Fix typo in `set-password` html binding
- **set-password.component.html**: Removed an extra "s" in password - fixed binding to variable
- Will be merged into `master` and `rc`
=> [SSO/Auto Enroll] Fix type for banner

src/background/idle.background.ts, src/background/main.background.ts, src/background/nativeMessaging.background.ts, src/background/runtime.background.ts, src/background/webRequest.background.ts, src/popup/vault/view.component.ts, src/services/autofill.service.ts
Follow up to https://github.com/bitwarden/jslib/pull/490 which removed the `index.ts` files which means we need to use the explicit import paths.
=> Use explicit import paths

src/popup/app.module.ts, src/popup/vault/add-edit-custom-fields.component.html, src/popup/vault/add-edit-custom-fields.component.ts, src/popup/vault/add-edit.component.html, src/popup/vault/view-custom-fields.component.html, src/popup/vault/view-custom-fields.component.ts, src/popup/vault/view.component.html
Browser implementation of https://github.com/bitwarden/jslib/pull/489.
=> Move custom fields to separate components

src/manifest.json
Version bump to 1.53.0
Will need to be cherry-picked into the `rc` branch
=> Version bump to 1.53.0

.github/workflows/build.yml, .github/workflows/crowdin-sync.yml, .github/workflows/release.yml
Updating the workflow model to the new build/test/release model. 
Also updated all of the workflows with the linter suggestions.
=> Workflow model update

src/background/main.background.ts, src/popup/services/services.module.ts, src/popup/settings/options.component.ts, src/services/browserPlatformUtils.service.spec.ts, src/services/browserPlatformUtils.service.ts
Update this client to use the refactored code here: https://github.com/bitwarden/jslib/pull/497.
Waiting on jslib merge.
=> Use theme enum and platformUtilsService helpers

src/popup/vault/view.component.html
Remove an extra `<` which is breaking the build.
=> Fix breaking typo

src/background/runtime.background.ts
The Bitwarden WebExtension deploys a content script, which forwards any message event, that can be triggered by the currently loaded website, to the background script for further processing. It was discovered that in case the authResult command is sent, the background script does not apply any further validation or encoding to the additional parameters before including them in the BrowserApi.createNewTab call. This allows to specify additional path parameters, which could potentially be abused to exploit the WebExtensions popup page. It must be noted that the current logic verifies that the message object was sent by the configured vault domain and no vulnerability was discovered in the popups index page.
URL encode (with `encodeURIComponent()`) all message parameters used to build the …
=> url encode data from msg_handler content script

src/_locales/en/messages.json
Add missing i18n strings in `messages.json` relating to Key Connector.
If the user is prompted to remove their master password and chooses to leave the organization instead, make sure that all dialogs and toasts have the expected text in them.
=> [Key Connector] Add missing i18n strings

src/background/main.background.ts, src/popup/services/services.module.ts
Update jslib and service dependencies.
https://github.com/bitwarden/jslib/pull/552 must be merged first.
Regression testing on the password/OTP verification when exporting.
=> Update jslib and service dependencies

src/_locales/en/messages.json, src/popup/app.module.ts, src/popup/components/verify-master-password.component.html, src/popup/components/verify-master-password.component.ts, src/popup/settings/export.component.html
Updates the export modal to match the design mockup.
=> Update export design

.github/workflows/build.yml, package.json, src/popup/app.module.ts
Adds `npm run lint` to the CI pipeline. This will ensure the code passes linting before merging. While I was at it, I also changed `npm install` to `npm ci`.
=> Run npm lint in CI

src/popup/app-routing.module.ts
#2201 changed how guard services were initialized. I forgot to change it in routing which caused the application to not launch correctly.
=> Fix DI not working

src/popup/settings/export.component.ts
Rename all occurrences of fb to formBuilder as it can be confusing.
This was only an issue in one file:
-**src/popup/settings/export.component.ts**
No functionality changes, just make sure the export vault form works as expected
=> Tech Debt: Rename fb to formBuilder

package.json
The pre-commit hook which was added recently, did not run on `*.ts` files.
- **package.json:** Add ts to lint-staged
=> Run prettier on *.ts files

package.json
Add --ignore-unknown to prettier
- **package.json:** add the `--ignore-unknown` to lint-staged
=> Add --ignore-unknown to prettier

package-lock.json, package.json
Rename package to `@bitwarden/browser`.
=> Rename package to @bitwarden/browser

src/models/account.ts, src/popup/services/services.module.ts
Depends on https://github.com/bitwarden/jslib/pull/624 for environmentUrls fixes
* Correct DI setup for stateService 
* Null check account model objects on it
=> Base changes for account switching di fixes

src/background/main.background.ts, src/background/nativeMessaging.background.ts, src/safari/safari/SafariWebExtensionHandler.swift
Adds the `userId` property to each message, which improves ux when using multiple accounts.
=> Update native messaging to include the userId

webpack.config.js
It seems the `dot` is included in `[ext]`. Removed the duplicate.
=> Fix webpack using double dots

src/popup/app.component.ts
This PR is required to accompany the changes I made here: https://github.com/bitwarden/jslib/pull/616. jslib has already been updated to include that.
We moved the call to `keyConnectorService.setConvertAccountRequired` into `syncService`, therefore we can remove it from the message event handler in each client.
Basic regression testing around a user being prompted to convert their account to Key Connector (removing their master password)
=> Move keyConnectorService call to syncService

src/popup/scss/popup.scss
Run Prettier to fix the current build failing from #2163. (Prettier check is not run on Community PRs)
=> Run Prettier on #2163

src/popup/settings/options.component.ts
Updating jslib & adjusting for the change from using a string for theme to using an enum. I noticed that the "default" theme value here was null, when it should be "system" and applied the ThemeType there as well.
=> [chore] Update jslib

package-lock.json, package.json, src/popup/tabs.component.html, src/popup/vault/add-edit.component.html, src/popup/vault/ciphers.component.html, src/popup/vault/groupings.component.html
> Remove all instances of `FA` and make any requested icon changes. Merge to both `master` and `rc` once approved.
- **package.json**: Removed `FA` node module from the web application
- **package-lock.json**: Updated due to `package.json` changes
- **tab.component.html**: Icon update - `generate` -> `generate-f`
- **add-edit.component.html**: Icon update - `cog-f` -> `cog`
- **groupings/cipher.component.html**: Icon update - all folders -> `folder`
-  Make sure the components listed above are working/looking as expected
=> [Icons] FF - requested icon changes

src/background/main.background.ts
https://app.asana.com/0/inbox/1183359552741416/1201781964063944/1201782081866250
This will need to be cherry picked to rc
Logout timeout actions are not working, and instead are locking the vault
* Add a missing call to clean the StateService to the logout function to ensure users are fully logged out
=> [bug] Clean state service on logout

src/services/browserPlatformUtils.service.ts
Adds support for client and versions headers added in https://github.com/bitwarden/jslib/pull/651
=> Client and version headers

src/popup/private-mode.component.ts, src/popup/settings/settings.component.ts, src/popup/vault/add-edit.component.html
> Update all `help.bitwarden.com` and `bitwarden.com/help/article/*` to the new `bitwarden.com/help/*` URL pattern
- **private-mode.component.ts**: Updated URL to new pattern
- **settings.component.ts**: Updated URL to new pattern
- **add-edit.component.html**: Updated URL to new pattern
- [jslib - [Help] Update links to new pattern](https://github.com/bitwarden/jslib/pull/658)
- Make sure URL links don't 404 and take you to the correct page
=> [Help] Update links to new pattern

src/manifest.json
Ran prettier on `./src/manifest.json`.
- **./src/manifest.json:** - Ran prettier.
=> Ran prettier on manifest.json

.github/workflows/version-bump.yml
Fix the prettier linting issue on browser when bumping the version
- **.github/workflows/version-bump.yml:** Add prettier
=> Add prettier to the version bump workflow

src/manifest.json
Run Prettier to undo the breaking formatting by github bot.
=> Run prettier on manifest.json

webpack.config.js
Excludes the content scripts from producing a source map. To facilitate easier debugging in production I also excluded them from the minification process.
Resolves https://github.com/bitwarden/browser/issues/2365
Verify no more console warnings are showing up on websites.
=> Exclude content scripts from source maps

webpack.config.js
Take two on #2377. Excludes the notification from minifier and sourcemaps.
=> Fix console warnings in notification content script

src/content/autofiller.ts, src/content/notificationBar.ts
Improve the null checks in the content scripts to avoid running them with broken state.
=> Improve null checks in content scripts

.github/workflows/enforce-labels.yml
Adds Hold label enforcement as done in bitwarden/cli#456
=> Enforce hold label

package.json
See https://github.com/bitwarden/web/pull/1458
=> Exclude jslib from prettier hook 

.github/workflows/workflow-linter.yml
To automate our linting by using the Bitwarden linter action, so that workflows will be tested for styling and programmatic errors on a pull request.
* **.github/workflows/workflow-linter.yml:** NEW: A workflow to use the Bitwarden Github workflow linter against any workflows in the `.github/workflows/*` folder.
Example: https://github.com/bitwarden/mobile/actions/runs/1854819678
=> Created workflow file

.github/workflows/release.yml
Adds dry run logic in the release pipeline so that we are able to perform test runs without actually releasing anything.
- **.github/workflows/release.yml:** Added dry run logic.
=> Added dry run logic

src/background/main.background.ts
Fix typo
Fix typo, `isFirefox` is a method not a property or getter.
=> Fix syntax

.github/workflows/release.yml
Rename `hotfix` release branch name to `hotfix-rc` to avoid branch name collisions with branches like `hotfix/this-feature`.
- **.github/workflows/release.yml:** Rename `hotfix` branch in the branch check
=> Updating the hotfix release branch name to hotfix-rc

.github/workflows/build.yml
Update old actions to their newest version.
- **.github/workflows/build.yml:** Updated all old actions to their newest version.
=> Updated actions

src/popup/app.module.ts
SG-130
Update client to use the new `JslibModule`.
Depends on https://github.com/bitwarden/jslib/pull/733.
* remove any jslib modules from `app.module`, import `JslibModule` instead
=> [JslibModule] Refactor to use JslibModule

webpack.config.js
Add globals defined by Angular CLI for tree shaking.
https://github.com/angular/angular-cli/blob/0c112e5d915af9f2f30879cea55e41751dbf0f1b/packages/angular_devkit/build_angular/src/webpack/configs/common.ts#L367-L368
[EC-110](https://bitwarden.atlassian.net/browse/EC-110)
=> Define Angular CLI globals to support tree shaking

gulpfile.js
Moves to using the new Xcode 11 distribution certificate when we sign for the MAS.
- **gulpfile.js:** Updates the certificate used for singing in the Desktop build workflow.
=> Update signing certificate

src/_locales/en/messages.json
Add descriptions to vague messages. No prod impact but to provide context for translators.
None
=> Add descriptions for vague messages

gulpfile.js
Reverts bitwarden/browser#2493
=> Revert "Update signing certificate"

.github/workflows/release.yml
Bumping pinned commit of the download-artifact action to bypass the broken GitHub api
- **.github/workflows/release.yml:** bumped pinned commit
=> Bump pinned commit of download-artifacts

src/popup/generator/generator.component.html
Same as https://github.com/bitwarden/web/pull/1607
Same as above
https://user-images.githubusercontent.com/31796059/164406944-1ba53068-916f-4c92-9603-8b6b74684e32.mov
=> [PS-211] [PS-212] Make Generator page accessible

src/popup/vault/view.component.html
Adds the credit card number pipe to view item.
Supersedes https://github.com/bitwarden/browser/pull/2247
=> [CP-30] Use the CreditCardNumberPipe

README.md
Solving the important issue of the non working badge in the readme.
=> [EC-183] Fix the readme badge

.github/workflows/build-browser.yml, .github/workflows/build-desktop.yml
Remove the `lint` job from the `build` workflows.
- **.github/workflows/build-browser.yml:** Remove `lint` job from workflow
- **.github/workflows/build-desktop.yml:** Remove `lint` job from workflow
=> Remove lint job from build workflows

CONTRIBUTING.md, README.md, apps/browser/README.md, package-lock.json, package.json
Rename the repository to clients.
=> Rename repo to clients

.github/workflows/build-desktop.yml
This PR applies fixes to the `desktop` build workflow.
- **.github/workflows/build-desktop.yml:** Fixes caches, paths, and other working directory issues.
=> Fix Desktop Build Workflow

.github/workflows/build-desktop.yml
This PR increases the base number we start at for build numbers due to the value being higher in Test Flight.
- **.github/workflows/build-desktop.yml:** Increase build number base value to 3000 to satisfy Test Flight requirements.
=> Fix Build Number for Test Flight

.github/workflows/build-desktop.yml, apps/desktop/src/package.json
Resolves this [issue](https://github.com/bitwarden/clients/runs/6313728432?check_suite_focus=true#step:19:13) with Testflight uploads.
- **.github/workflows/build-desktop.yml:** Moving the provisioning profiles into the `/apps/desktop` directory. 
Test build passed: https://github.com/bitwarden/clients/runs/6325581630?check_suite_focus=true#step:19:1
=> Update provisioning files in desktop build

apps/browser/src/popup/components/send-list.component.html
Fix lint issues, introduced with https://github.com/bitwarden/clients/pull/2540
- **apps/browser/src/popup/components/send-list.component.html:** Fixed linter issues
=> Fix lint issues

apps/browser/package-lock.json, apps/browser/package.json
Fix the failing build in master due to #2646
=> Fix browser build failing

.github/workflows/build-browser.yml, .github/workflows/build-desktop.yml, .github/workflows/crowdin-pull.yml, apps/browser/crowdin.yml, apps/desktop/crowdin.yml
This PR fixes the `Crowdin Pull` workflow so that it can support all clients.
- **.github/workflows/build-browser.yml:** Moved environment variable `CROWDIN_PROJECT_ID` to step instead of job.
- **.github/workflows/build-desktop.yml:** Moved environment variable `CROWDIN_PROJECT_ID` to step instead of job.
- **.github/workflows/crowdin-pull.yml:** Modified logic to introduce matrix that will be used for all clients.
- **apps/browser/crowdin.yml:** Updated environment variable name to `CROWDIN_PROJECT_ID`.
- **apps/desktop/crowdin.yml:** Updated environment variable name to `CROWDIN_PROJECT_ID`.
=> Fix Crowdin Pull Workflow

apps/browser/src/popup/components/send-list.component.html
Resolves a regression from https://github.com/bitwarden/clients/pull/2540 where the remove password was incorrectly disabled without the policy.
=> [PS-569] Fix sends having the inverse condition for disabled

apps/desktop/src/app/vault/vault.component.ts
https://bitwarden.atlassian.net/jira/software/projects/SG/boards/34?selectedIssue=SG-333
Depends on https://github.com/bitwarden/jslib/pull/807
An issue that has been encountered in the web vault for the new organization filters in the filters bar is that they are sometimes hidden on initial login, because a sync didn't complete in time to create the filter component. This issue is also in desktop, but was missed and is being fixed now.
Reload organization filters alongside collection filters when a sync is complete.
=> [fix] Reload organization filter options on sync complete

.github/workflows/build-browser.yml, .github/workflows/build-desktop.yml
Run the build workflows when they change.
- **.github/workflows/build-desktop.yml:** Add in another workflow trigger path
- **.github/workflows/build-browser.yml:** Add in another workflow trigger path
=> Adding in another path to trigger the client build workflows

.github/workflows/build-browser.yml, .github/workflows/build-desktop.yml
Add the event type `pull_request` on the `build` workflows.
- **.github/workflows/build-browser.yml:** Add event type `pull_request`.
- **.github/workflows/build-desktop.yml:** Add event type `pull_request`.
=> Add 'pull_request' event to Build workflows

.github/workflows/build-browser.yml, .github/workflows/build-desktop.yml
This PR updates the build workflows `push` event to only trigger on `master`, `rc`, and `hotfix-rc/**` branches.
- **.github/workflows/build-browser.yml:** Remove `branches-ignore` key and add `branches` key to the `push` event trigger.
- **.github/workflows/build-desktop.yml:** Remove `branches-ignore` key and add `branches` key to the `push` event trigger.
=> Update Build Workflow Push Trigger

apps/browser/src/_locales/en/messages.json, apps/browser/src/background/main.background.ts, apps/cli/src/bw.ts, apps/cli/src/locales/en/messages.json, apps/desktop/src/app/app-routing.module.ts, apps/desktop/src/locales/en/messages.json
Update jslib and error message in accordance with jslib changes: https://github.com/bitwarden/jslib/pull/816
=> [EC-177] Update Key Connector error handling

.github/workflows/crowdin-pull.yml
The current Crowdin github action doesn't quite easily support a monorepo structure migration. Use our new custom Crowdin action in [gh-actions](https://github.com/bitwarden/gh-actions) to enable monorepo support.
=> Monorepo Crowdin Sync

.github/workflows/version-bump.yml
This PR fixes a bug with the `version-bump` workflow.  `working-directory` is not support on action steps.
- **.github/workflows/version-bump.yml:** Update all action steps with `file_path` containing the working directory and removing the `working-directory` key.
=> Fix Version Bump Workflow

.github/workflows/release-browser.yml
This PR fixes the `working-directory` in the Release Browser workflow.
- **.github/workflows/release-browser.yml:** Removes workflow default `working-directory` and uses it in steps directly instead.
=> Fix Release Browser Workflow

.github/workflows/release-desktop.yml
This PR fixes some of the issues found when running the new Release Desktop workflow for the first time.
- **.github/workflows/release-desktop.yml:** Removes the `working-directory` default key for the whole workflow and instead modifies the steps that actually need it.
=> Fix Desktop Release Workflow

apps/browser/src/popup/components/action-buttons.component.ts
Fixes an issue where password copy was sometimes populated with a totp.
- **action-buttons.component**: Only populate with totp code if the `aType === TOTP`
=> PS-786 Fix TOTP copy action

.github/workflows/build-web.yml
`check-failures` is looking for a job that was removed, this removes those dependencies.
- **.github/workflows/build-web.yml:** Removed Windows job dependency
=> [CI] - Remove dependencies for removed step

package-lock.json, package.json
This PR pins the `electron-builder` package at version `22.11.10`.  Any newer versions are currently failing to sign Mac App Store packages. See [here](https://github.com/electron-userland/electron-builder/issues/6621) for more information.
- **package.json:** Pin the `electron-builder` package to version `22.11.10`.
- **package-lock.json:** Pin the `electron-builder` package to version `22.11.10`.
=> Pin Electron Builder Version

.github/PULL_REQUEST_TEMPLATE.md
Template items here aren't really tasks as interpreted by github, this allows us to have the same MD experience without hinting to github that there are 2/8 tasks done, which was annoying.
=> PR template info as code

.github/workflows/build-browser.yml, .github/workflows/build-cli.yml, .github/workflows/build-desktop.yml, .github/workflows/build-web.yml
```
```
This PR updates all the `build` workflows to trigger when anything the `libs` directory has been changed.
- **.github/workflows/build-browser.yml:** Update both `pull_request` and `push` trigger paths to include `libs/**`.
- **.github/workflows/build-cli.yml:** Update both `pull_request` and `push` trigger paths to include `libs/**`.
- **.github/workflows/build-desktop.yml:** Update both `pull_request` and `push` trigger paths to include `libs/**`.
- **.github/workflows/build-web.yml:** Update both `pull_request` and `push` trigger paths to include `libs/**`.
```
```
=> Add 'libs' to build workflow event paths

.github/workflows/release-qa-web.yml
Provided QA the functionality to deploy Web to QA.
- **.github/workflows/release-qa-web.yml:** Workflow migrated from old web repo.
=> Add QA Web release

libs/common/src/services/organization.service.ts
```
```
The Vault Filters in the individual vault are not alphabetized on desktop or web. 
Return sorted list from organization service 
```
```
=> [PS-827] Sort organizations before returning all

apps/web/src/app/modules/vault-filter/organization-vault-filter.component.ts, apps/web/src/app/modules/vault-filter/vault-filter.component.html, apps/web/src/app/modules/vault-filter/vault-filter.component.ts, apps/web/src/app/modules/vault-filter/vault-filter.module.ts, apps/web/src/app/modules/vault-filter/vault-filter.service.ts, apps/web/src/app/modules/vault/modules/organization-vault/organization-vault.component.html, apps/web/src/app/modules/vault/modules/organization-vault/organization-vault.component.ts
https://bitwarden.atlassian.net/browse/SG-372
```
```
This is a 1:1 recreation of https://github.com/bitwarden/web/pulls/1700 for bitwarden/clients. It contains some hacks we did just to get things working for the May release. Some refactors will be coming soon, but I wanted to get this in before rc branches are cut so the bug is fixed.
- Recreate web/1700
```
```
=> [fix] Pull org admin collections directly from the API

.github/workflows/build-browser.yml, .github/workflows/build-cli.yml, .github/workflows/build-desktop.yml, .github/workflows/build-web.yml, .github/workflows/lint.yml, .github/workflows/release-web.yml
```
```
This PR updates all of our workflows to point to the new CloudFlare Pages branch `cf-pages`.
- **.github/workflows/build-browser.yml:** Change `gh-pages` to `cf-pages`.
- **.github/workflows/build-cli.yml:** Change `gh-pages` to `cf-pages`.
- **.github/workflows/build-desktop.yml:** Change `gh-pages` to `cf-pages`.
- **.github/workflows/build-web.yml:** Change `gh-pages` to `cf-pages`.
- **.github/workflows/lint.yml:** Change `gh-pages` to `cf-pages`.
- **.github/workflows/release-web.yml:** Remove any GitHub Pages reference.
```
```
=> Update workflows to deploy to CloudFlare Pages (cf-pages branch)

apps/desktop/electron-builder.json, apps/desktop/resources/entitlements.mas.loginhelper.plist, apps/desktop/resources/entitlements.mas.plist
```
```
This PR fixes our MAS builds so that we can submit them to Test Flight.
- **apps/desktop/electron-builder.json:** Add a `loginhelper` plist.
- **apps/desktop/resources/entitlements.mas.loginhelper.plist:** Added file.
- **apps/desktop/resources/entitlements.mas.plist:** Added application identifier and team identifier.
```
```
=> Update Plist files for MAS

apps/browser/src/_locales/en/messages.json, apps/browser/src/background/main.background.ts, apps/browser/src/popup/settings/options.component.html, apps/browser/src/popup/settings/options.component.ts, apps/browser/src/popup/settings/settings.component.html, apps/browser/src/popup/settings/settings.component.ts, apps/browser/src/services/autofill.service.ts, apps/cli/src/bw.ts, apps/desktop/src/app/accounts/settings.component.html, apps/desktop/src/app/accounts/settings.component.ts, apps/desktop/src/locales/en/messages.json, apps/desktop/src/main/biometric/biometric.darwin.main.ts, apps/desktop/src/main/biometric/biometric.windows.main.ts, apps/web/src/app/settings/preferences.component.html, apps/web/src/app/settings/preferences.component.ts, apps/web/src/locales/en/messages.json, libs/common/src/abstractions/totp.service.ts, libs/common/src/services/totp.service.ts
```
```
Update Negative Copy in Settings
All clients do not use a consistent method for labeling settings controls. We often see settings that include the word "Disable" along with a checkmark which implies "enabling" a disable; this can be [confusing for users](https://www.reddit.com/r/Bitwarden/comments/qhns9l/browser_extensions_can_now_autoprompt_for/).
```
```
=> [PS-683] Update negative copy

apps/web/package.json, package-lock.json
```
Web version bump to 2022.6.0
```
=> Bump Web version to 2022.6.0

apps/web/src/app/modules/organizations/users/enroll-master-password-reset.component.html, apps/web/src/app/modules/shared.module.ts, apps/web/src/app/organizations/settings/account.component.html, apps/web/src/app/reports/breach-report.component.html, apps/web/src/app/reports/exposed-passwords-report.component.html, apps/web/src/app/settings/change-kdf.component.html, apps/web/src/app/settings/change-password.component.html, apps/web/src/app/settings/emergency-access-add-edit.component.html, apps/web/src/app/settings/premium.component.html, apps/web/src/app/settings/two-factor-setup.component.html, libs/components/src/index.ts, libs/components/src/submit-button/index.ts, libs/components/src/submit-button/submit-button.component.html, libs/components/src/submit-button/submit-button.component.ts, libs/components/src/submit-button/submit-button.module.ts, libs/components/src/submit-button/submit-button.stories.ts
```
```
Adds a submit button components which has a `loading` input to toggle the spinner.
TODO: Some accessibility questions (posted in figma).
```
```
=> [CL-11] Submit button

.github/workflows/release-cli.yml, .github/workflows/release-desktop.yml
```
```
Updates the CLI and Desktop release workflows to pull the choco secret from Azure Key Vault.
- **.github/workflows/release-desktop.yml:** Add Azure login and secret retrieval from Azure Key vault
- **.github/workflows/release-cli.yml:** Add Azure login and secret retrieval from Azure Key vault
```
```
=> Update choco jobs to use secret from AzKeyVault

apps/desktop/scripts/choco-update.ps1
```
```
Fix old url in chocolatey script for downloading newest desktop relese.
- **/apps/desktop/scripts/choco-update.ps1:** Update desktop release URL to point to new monorepo
```
```
=> Fix download URL on choco update script

apps/web/package.json, package-lock.json
```
```
Version Bump Web to 2022.6.1
=> Manual Web Version Bump 2022.6.1

apps/web/src/app/app.component.ts, apps/web/src/app/organizations/manage/policies.component.html, apps/web/src/app/organizations/policies/disable-send.component.html, apps/web/src/app/organizations/policies/master-password.component.html, apps/web/src/app/organizations/policies/master-password.component.ts, apps/web/src/app/organizations/policies/password-generator.component.html, apps/web/src/app/organizations/policies/personal-ownership.component.html, apps/web/src/app/organizations/policies/require-sso.component.html, apps/web/src/app/organizations/policies/reset-password.component.html, apps/web/src/app/organizations/policies/send-options.component.html, apps/web/src/app/organizations/policies/single-org.component.html, apps/web/src/app/organizations/policies/two-factor-authentication.component.html, apps/web/src/app/organizations/policies/two-factor-authentication.component.ts, apps/web/src/locales/en/messages.json, bitwarden_license/bit-web/src/app/policies/disable-personal-vault-export.component.html, bitwarden_license/bit-web/src/app/policies/maximum-vault-timeout.component.html
```
```
Update the content on the policies and single sign-on pages to make them more consistent, easier to understand, and to align better with the Bitwarden voice, tone, and style. 
- **apps/web/src/app/app.component.ts:** Moved master password reset policy up to 3rd row
- **apps/web/src/app/organizations/manage/policies.component.html:** Updated “Enabled” badge text to “On”
- **apps/web/src/app/organizations/policies/disable-send.component.html:** Updated “enabled” checkbox to “Turn on”
- **apps/web/src/app/organizations/policies/master-password.component.html:** Updated “enabled” checkbox to “Turn on”
- **apps/web/src/app/organizations/policies/master-password.component.ts:** Use the new master-password policy title text
- **apps/web/src/app/organizations/policies/password-generator.co …
=> [EC-280] Update policies page content

apps/web/src/locales/en/messages.json
```
```
Updated the Delete account modal description.
- **apps/web/src/locales/en/messages.json:** Updated the modal dialog description
```
```
=> [EC-298] Updated the Delete account modal description

apps/browser/src/_locales/en/messages.json, apps/desktop/src/locales/en/messages.json
```
```
The minimum length error message on the desktop does not display.
- **apps/desktop/src/locales/en/messages.json:** Renamed error key from `masterPasswordMinLength` to `masterPasswordMinlength`
- **apps/browser/src/_locales/en/messages.json:** Renamed error key from `masterPasswordMinLength` to `masterPasswordMinlength`
```
```
=> [SG-422] Renamed minlength error key

apps/web/package.json
```
```
Manually bump web version since the version bump workflow is still broken.
=> Web Version Bump 2022.6.2

apps/web/src/app/modules/organizations/create/organization-information.component.html, apps/web/src/app/modules/organizations/create/organization-information.component.ts, apps/web/src/app/settings/organization-plans.component.html, apps/web/src/app/settings/organization-plans.component.ts
```
```
Fix issue where upgrading an organization is showing the name and email fields. Also add logic for providers and sponsorship that I missed.
- **apps/web/src/app/modules/organizations/create/organization-information.component.html:** Modify conditional showing of fields depending on inputs
- **apps/web/src/app/modules/organizations/create/organization-information.component.ts:** Add inputs for `createOrganization` and other items that were missed.
- **apps/web/src/app/settings/organization-plans.component.ts & html:** Properly pass inputs to org info component
|Before (incorrect showing of fields on upgrade) | After |
|-------|------|
| ![image](https://user-images.githubusercontent.com/8926729/178515687-2f21d0ac-ec08-4972-8bdc-a029a5a346ed.png) | ![Screen Shot 2022-07-12 at 10 32 …
=> [SG-431] Fix org upgrade issues

apps/web/src/app/organizations/manage/user-add-edit.component.ts
```
```
We were previously allowing email duplicates in the organization invites without validation. This could result in multiple users being added with the same email. This is a small client side change to prevent this behavior.
```
```
=> [EC-284] Prevent multiple invites to organization

tsconfig.json
```
```
Resolves storybook not showing the correct controls for components.
```
```
=> Fix storybook not showing the correct controls

.github/workflows/version-bump.yml
```
```
This PR updates the `Version Bump` workflow so that all of the NPM package versions are updated properly.
- **.github/workflows/version-bump.yml:** Removes using the `version-bump` action and switches most steps to use `npm version` command to update the NPM package versions.
```
```
=> DEVOPS-869 - Fix Web Version bump

libs/components/src/badge/badge.directive.ts
Make badge an inline element to hopefully improve compatibility with buttons and other elements.
```
```
=> [Cl-10] Make badge inline

apps/web/config/qa.json
```
```
Allow `trial` route to be navigated to.
- **apps/web/config/qa.json:** Change `showTrial` to true to allow navigation in qa environments to trial initiation
```
```
=> [SG-439] Update qa.json

.github/workflows/build-desktop.yml
```
```
This PR updates the `push` event branches to only match `hotfix-rc` instead of `hotfix-rc/**`.
- **.github/workflows/build-desktop.yml:** Change branch listed under `push` event from `hotfix-rc/**` to `hotfix-rc`.
```
```
=> DEVOPS-870 - Revert the hotfix-rc/* logic in relation to TestFlight

apps/desktop/src/scss/header.scss
```
```
This is to fix the Bitwarden window moves when trying to select text in the search input by drag over the text to highlight some of it to copy or delete, it drags the window around
- **/src/scss/header.scss** I added  `-moz-user-select: none, -webkit-user-select: none,-ms-user-select: none,user-select:none,-webkit-user-drag: none,-webkit-app-region: no-drag,cursor: default,` to  the file to disable window dragging.
```
```
=> [PS-694] Fix Bitwarden window moves when trying to select text in the search input

apps/web/config/cloud.json, apps/web/config/development.json, apps/web/config/qa.json, apps/web/config/selfhosted.json, apps/web/src/app/organizations/manage/manage.component.ts, apps/web/src/utils/flags.ts
```
```
Add a feature flag to disable SCIM navigation. Should be hidden in prod environments but available for qa/dev.
**This will be picked to rc**
* add feature flag and configurations
* hide navigation button if feature flag is set to false.
```
```
=> [EC-344] Add feature flag for SCIM navigation

apps/web/src/app/modules/register-form/register-form.component.html, libs/components/src/input/input.directive.ts
```
```
QA uses an application to run automated UI tests which require ids to locate an element. The current implementation of the registration form using the form components returns dynamic ids and this makes it difficult to run the automated tests for the UI.
- **apps/web/src/app/modules/register-form/register-form.component.html:** Added static ids to the form inputs.
- **libs/components/src/input/input.directive.ts:** Made the id property an input so it can be overridden when passed manually.
```
```
=> [SG-430] Modify registration component to use static ids

apps/browser/src/background/main.background.ts, apps/cli/src/bw.ts, apps/web/src/app/services/init.service.ts, libs/common/src/services/container.service.ts
```
```
Get rid of a deprecated method call. 
With the monorepo we have the technology to make this change very simply. Just ctrl+F's for this function and moved it to the new name...
```
```
=> Do not use deprecated method

apps/web/src/app/settings/organization-plans.component.ts
```
```
This is to fix the log-out issue that occurs when a user finishes uploading an organization license during the creation of a new organization on the self-hosted environment. 
- **src/app/settings/organization-plans.component.ts:** Added a call to refresh the Identity Token before making a call to post organization Keys.
```
```
=> [PS-678]Fix Defect- Logged out after creating Org on Self-Hosted Env

apps/cli/package-lock.json
```
```
I was looking into another change and noticed that the `apps/cli/package-lock.json` was not showing the same package versions as described in `apps/cli.package.json`. I re-built the `package-lock.json` with `npm i` in the /apps/cli folder.
**Content of current `apps/cli/package.json`**
```
"dependencies": {
"@koa/multer": "^3.0.0",
"@koa/router": "^10.1.1",
"big-integer": "^1.6.51",
"browser-hrtime": "^1.1.8",
"chalk": "^4.1.1",
"commander": "7.2.0",
"form-data": "4.0.0",
"https-proxy-agent": "5.0.0",
"inquirer": "8.0.0",
"jsdom": "^16.7.0",
"jszip": "^3.10.0",
"koa": "^2.13.4",
"koa-bodyparser": "^4.3.0",
"koa-json": "^2.0.2",
"lowdb": "1.0.0",
"lunr": "^2.3.9",
"multer": "^1.4.5-lts.1",
"node-fetch": "^2.6.7",
"node-forge": "1.3.1",
"open": "^8.4.0",
"papaparse": "^5.3.2", …
```
=> Re-generate CLI package-lock.json

libs/common/spec/services/folder.service.spec.ts
```
```
Fixes the folder service tests.
```
```
=> Fix folder tests

.github/workflows/build-browser.yml, .github/workflows/build-cli.yml, .github/workflows/build-desktop.yml, .github/workflows/build-web.yml, .github/workflows/release-browser.yml, .github/workflows/release-cli.yml, .github/workflows/release-desktop-beta.yml, .github/workflows/release-desktop.yml, .github/workflows/release-web.yml
```
```
Switch back to the single `hotfix-rc` branch. We experimented with using a `hotfix-rc/*` branching strategy for the last release from the monorepo and we ran into some issues that couldn't be resolved.
- **.github/workflows/build-browser:** switch hotfix-rc logic back to solely the `hotfix-rc` branch
- **.github/workflows/build-cli:** switch hotfix-rc logic back to solely the `hotfix-rc` branch
- **.github/workflows/build-desktop:** switch hotfix-rc logic back to solely the `hotfix-rc` branch
- **.github/workflows/build-web:** switch hotfix-rc logic back to solely the `hotfix-rc` branch
- **.github/workflows/release-browser:** switch hotfix-rc logic back to solely the `hotfix-rc` branch
- **.github/workflows/release-cli:** switch hotfix-rc logic back to solely the `hotfix-rc` …
=> Finish up the switch from the hotfix-rc/* back to hotfix-rc

libs/components/src/table/cell.directive.ts, libs/components/src/table/index.ts, libs/components/src/table/row.directive.ts, libs/components/src/table/table.component.html, libs/components/src/table/table.component.ts, libs/components/src/table/table.module.ts, libs/components/src/table/table.stories.ts
=> [CL-24] Add tables

apps/web/src/app/modules/vault-filter/components/organization-filter.component.html, apps/web/src/scss/vault-filters.scss
=> [SG-494] [Defect] - Disabled Organization Icon Causing Incorrect Alignment in Web For Long Names

.github/workflows/version-auto-bump.yml
```
```
Add stub to test auto bump workflow done in another PR: https://github.com/bitwarden/clients/pull/3182
- **.github/workflows/version-auto-bump.yml:** Add stub to test autobump workflow done in another PR: https://github.com/bitwarden/clients/pull/3182
```
```
=> Add version autobump stub

libs/common/src/services/passwordGeneration.service.ts
```
```
Fix password history showing no passwords. This is because the `getHistory` method looks for decrypted passwords first. Since we are keeping an in memory cache of those now it is returning the old list of them and that is what we are displaying AND adding to. If we also update the decrypted in memory cache when adding history it fixes the issue. 
- **libs/common/src/services/passwordGeneration.service.ts:** Update in memory decrypted cache when adding password history. 
```
```
=> [PS-1202] Update Decrypted Password Generation History

apps/web/src/app/app.component.ts
```
```
We moved the settings page for premium to `settings/subscription/premium` a while back, but it seems we forgot to update the "learn more" button for the prompt.
Duplicate jira tickets:
[bitwarden.atlassian.net/browse/SG-437](https://bitwarden.atlassian.net/browse/SG-437)
[bitwarden.atlassian.net/browse/SG-427](https://bitwarden.atlassian.net/browse/SG-427)
```
```
=> [SM-107] Fix url for premium subscription

.eslintignore, .prettierignore
```
```
Add `.angular` to eslint and prettier ignore lists.
```
```
=> Ignore .angular for prettier and eslint

bitwarden_license/bit-web/src/app/sm/sm-routing.module.ts
```
```
The routing for Secrets Manager was broken due to `pathMatch` missing.
```
```
=> Fix secrets manager

.github/workflows/release-web.yml
```
```
Updates the web deploy workflow to use the `release_version` output when creating a release.
- **.github/workflows/release-web.yml:** Change to `${{ needs.setup.outputs.release_version }}`
```
```
=> Update web depoy workflow to use release_version

apps/web/src/app/modules/vault-filter/components/organization-filter.component.html, apps/web/src/scss/vault-filters.scss
```
```
Fix layout of icons 
```
```
=> [SG-501]  [Defect] - More Actions and Disabled Org Icon No Longer Right Aligned

.storybook/tsconfig.json
```
```
Fixing storybook to run with new tests
.storybook/tsconfig.json
Adding jest reference for storybooks
```
```
=> Fixing storybook to run with new tests

apps/web/config/cloud.json, apps/web/config/selfhosted.json
```
```
Enable the SCIM feature flag for production environments (cloud and selfhosted).
```
```
=> [EC-415] Enable SCIM feature flag

apps/web/src/app/modules/vault-filter/components/link-sso.component.html
```
```
Missed styling a button as it existed in a different component.
```
```
=> fix: link sso button

.github/workflows/build-web.yml
- Check if trigger was a pull request
```
```
Updates the web build workflow to use the correct Git ref for the Docker image tags.
- **.github/workflows/build-web.yml:** Add logic to set the correct tag name.
```
```
=> Update web workflow with additional logic

.github/workflows/build-web.yml
Updates web workflow to handle the `/` in branch names when it's a PR.
```
```
Updates the tag logic to handle pull requests with `/` in the branch name.
Fixes: https://github.com/bitwarden/clients/runs/7726098878?check_suite_focus=true
- **.github/workflows/build-web.yml:** Description of what was changed and why
```
```
=> Handle "/" in branch names

.github/workflows/release-browser.yml, .github/workflows/release-cli.yml, .github/workflows/release-desktop-beta.yml, .github/workflows/release-desktop.yml, .github/workflows/release-qa-web.yml, .github/workflows/release-web.yml
```
```
@vgrassia recommended some cleanup changes to the workflows in `mobile` and `directory-connector` repos.  I'm making the same changes here for consistency.
- [.github/workflows/release-browser.yml](https://github.com/bitwarden/clients/compare/ENG-71-update-deployment-jobs?expand=1#diff-bad36661a8eb03a2093315a3b5849fd5cc764f7cfe28468d034a8f147c16e25b): Set `initial-status` and removed extra step.  Added explicit expression syntax.
- [.github/workflows/release-cli.yml](https://github.com/bitwarden/clients/compare/ENG-71-update-deployment-jobs?expand=1#diff-6ba0eeeb9cdfe6d2493769e2c1b9d3b249ab70bf3d9f1e9d0dc28296446f5a46): Set `initial-status` and removed extra step.  Added explicit expression syntax.
- [.github/workflows/release-desktop-beta.yml](https://github.com/bitwarden/clients/ …
=> ENG-71 - Updated release workflows with cleanup recommended by Vince

apps/cli/config/development.json, apps/cli/config/production.json, apps/cli/src/commands/serve.command.ts, apps/cli/src/flags.ts, apps/cli/src/program.ts
```
```
Improve logger message on empty Origin header.
=> PS-1230 PS-1152 Fix/improve null origin message

apps/browser/src/manifest.v3.json
```
```
Manifest v3 gets rid of browser_action api and renames to action api. This involves renaming our `_execute_browser_action` command to `_execute_action`
```
```
=> PS-818 Update browser_action to action

package-lock.json, package.json
```
```
Lock `node-ipc` version
```
```
=> Lock node-ipc version

libs/common/src/services/search.service.ts
```
```
Fixes #3267 by null checking URI values. 
We allow saving null URIs rather than just purging those prior to save, which means we need to validate this value on use.
```
```
=> PS-1267 Null check URI values

.github/workflows/build-web.yml
```
```
Update the web-sh image tag to use the correct branch name with pull request.
- **.github/workflows/build-web.yml:**  - Updated tagging logic and name of the job step.
```
```
=> Update tag logic for web-sh container

libs/angular/src/components/lock.component.ts
```
```
While working on a different task involving the lock.component, I noticed potential for a small refactor to simplify the logic inside of `submit()`. 
Mostly extract method refactor and use of early returns to reduce if-nesting.
- **libs/angular/src/components/lock.component.ts:** I have separated the commits and given them descriptive messages.
```
```
=> Small refactor of lock.component

apps/browser/src/popup/generator/generator.component.html, apps/desktop/src/app/vault/generator.component.html, apps/web/src/app/tools/generator.component.html, apps/web/webpack.config.js, libs/angular/src/components/generator.component.ts, libs/common/src/services/usernameGeneration.service.ts
```
```
DuckDuckGo has an awesome email forwarding service like SimpleLogin is. It also removes tracker from the emails and it is possible to answer directly like it would be a normal email. I trust DuckDuckGo more than any other service, and I find it the easiest one to use.
I want to thank them and contribute to bitwarden by helping implementing their forwarding service into the bitwarden clients.
Their were only a few files to be changed as the foundation of the email forwarding service was made by the other forwarding services.
- **generator.component.ts** Added DuckDuckGo as an option for the email forwarding services (I called it "Private Duck Address" like they did, change it if you have a better name :))
- …
=> [PS-1302] added duckduckgo's email forwarding service 🦆

apps/web/src/app/accounts/trial-initiation/content/cnet-enterprise-content.component.html, apps/web/src/app/accounts/trial-initiation/content/cnet-individual-content.component.html, apps/web/src/app/accounts/trial-initiation/content/cnet-teams-content.component.html, apps/web/src/app/accounts/trial-initiation/content/default-content.component.html, apps/web/src/app/accounts/trial-initiation/content/enterprise-content.component.html, apps/web/src/app/accounts/trial-initiation/content/enterprise1-content.component.html, apps/web/src/app/accounts/trial-initiation/content/enterprise2-content.component.html, apps/web/src/app/accounts/trial-initiation/content/teams-content.component.html, apps/web/src/app/accounts/trial-initiation/content/teams1-content.component.html, apps/web/src/app/accounts/trial-initiation/content/teams2-content.component.html, apps/web/src/app/accounts/trial-initiation/trial-initiation.component.html
```
```
Increases the header size and removes the slant so the subheader doesn't get cut off
```
```
=> [SG-577] Trial Initiation Header

.github/workflows/release-desktop-beta.yml
=> Fix typo in desktop beta release workflow

apps/web/webpack.config.js
```
```
SG-515 introduced Fastmail as a username provider.  This change will add the Fastmail URI to our CSP configuration for development.  Corresponding changes are to be made by DevOps for QA and Production.
- **webpack.config.js:** Added Fastmail URI
```
```
=> Added CSP configuration for Fastmail in local configuration

.github/workflows/release-qa-web.yml
```
```
https://bitwarden.atlassian.net/browse/DEVOPS-918
Fix failing deployment to Cloudflare. The error occurred because the download artifact action couldn't find the `hotfix-rc` build. It was too old.
- **.github/workflows/release-qa-web.yml:** Update Bitwarden's download artifact action SHA to the newest.
```
```
=> Fix QA web cloudflare deployment

.github/workflows/test.yml, apps/web/src/app/accounts/trial-initiation/trial-initiation.component.spec.ts, bitwarden_license/bit-web/tsconfig.json
```
```
Fixes tests that aren't working in master.
```
```
=> Fix failing tests

apps/browser/src/manifest.v3.json
Add managed schema to mv3 manifest.
=> PS-818 Add managed schema to mv3 manifest

apps/desktop/src/app/app.component.ts
```
```
This is a follow-up from https://github.com/bitwarden/clients/pull/3377 as I missed some changes on desktop which broke the desktop build.
- **apps/desktop/src/app/app.component.ts:** Remove the passing of the deprecated/removed `allowSoftlock` to `vaultTimeoutService.lock()`
```
```
=> [PS-1363] Fix changed lock method signature

libs/angular/src/components/generator.component.ts
```
```
https://bitwarden.atlassian.net/browse/SG-592
DDG is not able to be used until CORS issues can be addressed.  This change will remove DDG as an option on the Generator UI for release `2022.9` while leaving it on in `master` for future releases, once CORS has been addressed.
- **generator.component.ts:** Commented out the DDG forwarding option from the array that is the source of the radio button group.
```
```
=> Removed DDG option from UI until CORS can be addressed.

apps/browser/src/popup/app.module.ts, apps/browser/src/popup/settings/about.component.html, apps/browser/src/popup/settings/about.component.ts, apps/browser/src/popup/settings/settings.component.ts
```
```
Change the browser about page to be a modal, which in my opinion is easier to understand than the Sweet Alert modal.
```
```
=> [SM-90] Change to using a modal for browser about

apps/browser/src/background/main.background.ts, apps/browser/src/background/service_factories/vault-timeout-service.factory.ts, apps/browser/src/background/service_factories/vault-timeout-settings-service.factory.ts, apps/browser/src/popup/accounts/lock.component.ts, apps/browser/src/popup/services/services.module.ts, apps/browser/src/popup/settings/settings.component.ts, apps/cli/src/bw.ts, apps/desktop/src/app/accounts/lock.component.ts, apps/desktop/src/app/accounts/settings.component.ts, apps/desktop/src/app/app.component.ts, apps/web/src/app/accounts/lock.component.ts, apps/web/src/app/settings/preferences.component.ts, libs/angular/src/components/lock.component.ts, libs/angular/src/services/jslib-services.module.ts, libs/common/src/abstractions/vaultTimeout/vaultTimeout.service.ts, libs/common/src/abstractions/vaultTimeout/vaultTimeoutSettings.service.ts, libs/common/src/services/vaultTimeout/vaultTimeout.service.ts, libs/common/src/services/vaultTimeout/vaultTimeoutSettings.service.ts
```
```
This is a follow up from my previous PR (#3416), splitting up the vaultTimeout-Service
Extract vaultTimeout settings from vaultTimeoutService and put them into a separate service.
- Service extraction:
- **libs/common/src/abstractions/vaultTimeout/vaultTimeout.service.ts:** Extract settings related method signatures
- **libs/common/src/services/vaultTimeout/vaultTimeout.service.ts:** Extract settings related method
- **libs/common/src/abstractions/vaultTimeout/vaultTimeoutSettings.service.ts:** Insert settings related method signatures into new abstraction
- **libs/common/src/services/vaultTimeout/vaultTimeoutSettings.service.ts:** nsert settings related method
- Instantiation/Registration:
My commits got slightly messed up with amending a change in bw.ts which resulting in all …
=> Extract settings related methods into VaultTimeoutSettingsService

libs/common/src/abstractions/state.service.ts, libs/common/src/models/data/localData.ts, libs/common/src/models/domain/cipher.ts, libs/common/src/models/view/cipherView.ts, libs/common/src/services/state.service.ts
```
```
`LocalData` is missing typing, which really grinds my gears. Let's document what we're working with.
Add typing to `localData`.
```
```
=> [EC-490] Add typing to localData object

apps/browser/store/locales/en/copy.resx
Unless I am completely mistaken and there exist something called `salted hashtag`, I think there's a typo in the clients' description such that `salted hashtag` should be replaced with `salted hashing`.
```
- [x ] Other
```
Fix a typo
- multiple **copy.resx** files: replace 'salted hashtag' with 'salted hashing'
```
```
=> [PS-1383] fix typo: 'salted hashtag' to 'salted hashing'

apps/browser/src/popup/app.module.ts, apps/browser/src/services/i18n.service.ts, apps/desktop/src/app/app.module.ts, apps/desktop/src/services/i18n.service.ts, apps/web/src/app/core/i18n.service.ts, apps/web/src/app/shared/locales.ts, libs/common/src/services/i18n.service.ts
```
```
Thanks to our amazing community over at [Crowdin](https://crowdin.com/project/bitwarden-web) we can now add the Arabic language to our clients.
If you also want to get involved with more supported languages or improving our existing translations, please have a look at our [Contributing Guidelines](https://contributing.bitwarden.com/contributing/#localization-l10n)
Tagging @dwbit for visibility
- **libs/common/src/services/i18n.service.ts:** Register Arabic language with native name, which will be shown in the language dropdown if available in the client.
- Register with browser
- **apps/browser/src/services/i18n.service.ts:** Add `ar` as supported language
- **apps/browser/src/popup/app.module.ts:** Register Angular language module
- Register with desktop
- …
=> [PS-1282] Enable Arabic language support for desktop, browser, web

package-lock.json, package.json
```
```
Finishing up the contribution done in https://github.com/bitwarden/clients/pull/3110
- **package.json:** Pin the version of `nord` to `0.2.1`
- **package-lock.json:** Changes after running `npm i`
=> Pin Nord version to 0.2.1

.github/workflows/enforce-labels.yml
```
```
Adds `needs QA` banned label list. This will allow us to mark a PR as needing review prior to merge 
=> Add needs QA to enforce labels

apps/web/src/app/accounts/trial-initiation/content/abm-enterprise-content.component.html, apps/web/src/app/accounts/trial-initiation/content/abm-enterprise-content.component.ts, apps/web/src/app/accounts/trial-initiation/content/abm-teams-content.component.html, apps/web/src/app/accounts/trial-initiation/content/abm-teams-content.component.ts, apps/web/src/app/accounts/trial-initiation/trial-initiation.component.html, apps/web/src/app/accounts/trial-initiation/trial-initiation.module.ts
```
```
Add custom vault registration links for our ABM campaigns (teams/enterprise). For now, content remains as the default content.
=> Layout Params for ABM Campaign

.github/workflows/test.yml, jest.config.js, libs/shared/jest.config.base.js
```
```
There is a bug in node, or Jest, or ts-jest, causing tests to leak memory. See this issue thread and this comment specifically for more information: https://github.com/kulshekhar/ts-jest/issues/1967#issuecomment-994916049
There are various workarounds, and I previously added the `maxWorkers: 3` option to avoid it crashing CI altogether. That has worked so far in some but not all cases. It still uses lots of heap memory and can overflow depending on the weather, day of the week, etc.
One recommended option is to use `isolatedModules: true` (for ts-jest, [see docs](https://huafu.github.io/ts-jest/user/config/isolatedModules)), which reduces heap usage to about 30% of normal levels (from ~3gb to just under 1gb), but removes typechecking.
This PR enables that option, and then runs …
=> [EC-497] Fix memory leaks in tests

apps/browser/src/listeners/onCommandListener.ts, libs/common/src/services/noopEvent.service.ts
```
```
Our manifest v3 code has a file name that was incorrect in an import. I changed it to be accurate and made it non-default import so it is more inline with other imports.
- **libs/common/src/services/noopEvent.service.ts:** Removed `default` and went with `Noop` to be equal with our other no op service.
- **apps/browser/src/listeners/onCommandListener.ts:** Changed import and instantiation of object.
=> Fix file casing for `NoopEventService`

.eslintrc.json, apps/browser/src/content/message_handler.ts
```
```
Adds the https://eslint.org/docs/latest/rules/curly rule which prevents omitting the curly brackets after conditions and loops.
=> [SM-204] Add the `curly` eslint rule

libs/angular/src/components/register.component.ts
```
```
The code isolation in https://github.com/bitwarden/clients/pull/3481 has caused a regression allowing for the creation of an account without accepting the ToC. This is because the original `submit()` method relied on `return` statements to terminate the form submission. Isolating that code caused those `return` statements to just return from the validation function, and not the rest of the submit function at large. We need a new way to be able to stop the submission if validation fails.
We could be doing more with Angular forms here that would replace the way we `return` to something more bug-proof, but that would be a larger effort. I'm going to get a tech debt ticket opened for that.
- Change the name of the `captchaRequired` return value in the `registerAccount()` function to …
=> [SG-756] Add a fail state to registerAccount for failing validation

apps/desktop/config/development.json, apps/desktop/config/production.json, apps/desktop/src/app/accounts/settings.component.ts, apps/desktop/src/flags.ts
```
```
Add a feature flag to show/hide setting for native messaging changes
- **apps/desktop/config/development.json:** Add flag
- **apps/desktop/config/production.json:** Add flag
- **apps/desktop/src/app/accounts/settings.component.ts** Feature flag setting in Settings page
- **apps/desktop/src/flags.ts:** Add flag to `Flag` type
=> [SG-605] Feature flag native messaging service updates

apps/desktop/desktop_native/Cargo.lock, apps/desktop/desktop_native/Cargo.toml
```
```
We seem to somehow have regressed the rust versions somewhere along when merging the #2635. Upgrading Napi which seems to resolve the Windows 32bit issues we had in this release.
Resolves #3503, #3507
=> [PS-1474] Bump rust dependencies

apps/web/webpack.config.js
```
```
Angular virtual scrolling cdk is being blocked my CSP this updates it to the latest hash. 
- **apps/web/webpack.config.js:** Change existing Angular CDK hash. 
=> [PS-1475] Update CSP rule for Angular CDK

apps/desktop/stores/chocolatey/bitwarden.nuspec
```
```
Updated the description we use in the `bitwarden.nuspec` file which we use to display on [chocolately](https://community.chocolatey.org/packages/bitwarden)
Asking also for a review from DevOps to ensure I am not breaking our upload to the store once we release a new version.
- **apps/desktop/stores/chocolatey/bitwarden.nuspec:** Updated app description
=> [PS-1448] Update Chocolately description based on what we show on other stores

bitwarden_license/bit-web/src/app/sm/secrets/secrets.component.ts
```
```
Fix lint errors occurring after merging master into sm/secrets-feature
- bitwarden_license/bit-web/src/app/sm/secrets/secrets.component.ts
Removing async subscribe in favor of switchMap.
=> Fix SM lint errors

apps/web/webpack.config.js
```
```
Modified the CSP rule in dev to match QA and Production proxies.
- **webpack.config.js:** Modified URI to match QA and Production proxies.
- The QA and Production configuration is changed [here](https://github.com/bitwarden/misc/pull/130)
=> [SG-662] Modify Fastmail CSP rule

apps/desktop/package.json
```
```
Automatically run cargo build when running `npm run electron`. Streamlines things, especially since cargo doesn't do anything if there are no native changes.
=> Automatically build native rust for desktop in dev

.github/workflows/build-web-ee.yml
```
```
Add stub for build workflow for ephemeral env web container to be able to test actual workflow from another branch without merging to master.
https://bitwarden.atlassian.net/browse/DEVOPS-943 
- **.github/workflows/build-web-ee.yml:** Add stub workflow to be able to test actual workflow on another branch
=> Add stub for ephemeral env web build workflow

.github/workflows/build-web.yml
```
```
This PR updates the `Build Web` workflow packaging to remove zipping the artifact.
- **.github/workflows/build-web.yml:** Remove zipping of artifact and change appropriate `download-artifact` steps.
=> Fix packaging on Build Web workflow

apps/web/src/locales/en/messages.json, bitwarden_license/bit-web/src/app/sm/secrets/dialog/secret-delete.component.html, bitwarden_license/bit-web/src/app/sm/secrets/dialog/secret-delete.component.ts, bitwarden_license/bit-web/src/app/sm/secrets/secret.service.ts, bitwarden_license/bit-web/src/app/sm/secrets/secrets-list.component.html, bitwarden_license/bit-web/src/app/sm/secrets/secrets-list.component.ts, bitwarden_license/bit-web/src/app/sm/secrets/secrets.component.html, bitwarden_license/bit-web/src/app/sm/secrets/secrets.component.ts, bitwarden_license/bit-web/src/app/sm/secrets/secrets.module.ts
```
```
This PR is for implementing soft deleting secrets in the secrets manager project.
- apps/web/src/locales/en/messages.json
Adding in new messages for toast.
- bitwarden_license/bit-web/src/app/sm/secrets/dialog/secret-delete.component.html
bitwarden_license/bit-web/src/app/sm/secrets/dialog/secret-delete.component.ts
Component for the simple dialogs needed for bulk and singular soft deletes.
- bitwarden_license/bit-web/src/app/sm/secrets/secret.service.ts
Adding in delete method. 
- bitwarden_license/bit-web/src/app/sm/secrets/secrets-list.component.html
Event emitter for bulk delete button.
- bitwarden_license/bit-web/src/app/sm/secrets/secrets-list.component.ts
Adding in new event emitter.
- bitwarden_license/bit-web/src/app/sm/secrets/secrets.component.html …
=> [SM-64] Soft delete secrets

libs/components/src/icon-button/icon-button.component.ts
```
```
Fix incompatibilities between CL icon button and custom css styling on web vault
=> fix: icon button style incompats

apps/web/src/app/accounts/login/login.component.ts
```
```
Resolve storybook no longer working after #3424
=> Fix storybook

apps/web/webpack.config.js
```
```
Added https://quack.duckduckgo.com/api/email/addresses to the list of CSP exceptions for dev.  [This](https://github.com/bitwarden/misc/pull/133) PR includes the corresponding changes for QA and Prod proxies.
- **apps/web/webpack.config.js:** Added CSP rule for DDG
=> SG-592-Added CSP rule for DDG email fowarder API

apps/web/src/app/accounts/login/login-with-device.component.html, apps/web/src/locales/en/messages.json
```
```
Corrected typos in the messages.json file.
=> [SG 683] Crowdin string 12612 requires correction 'Biwarden'

.github/workflows/release-qa-web.yml
```
```
- **.github/workflows/release-qa-web.yml:** Change dir to which artifact will be downloaded. Removed the unzip, as the `download-artifacts` action unzipps it already.
=> Fix web qa deployment

apps/web/src/app/accounts/login/login.component.html
```
```
Added block directive and loader to login button to help with the `Login Page Object` for the automated test suite.
https://user-images.githubusercontent.com/13024008/192847195-efbdff13-912b-4fcf-b22c-2829fb42d3ee.mov
=> [SG-685] Added block directive and loader to login button

.gitignore, clients.code-workspace
```
```
I made a few changes to my local environment that I think should be standard across the team.
- add `storybook-static` to `.gitignore`. This folder is created and populated when running `npm run build-storybook`, but shouldn't be committed.
- use "project-relative" imports. This means that when vscode suggests an import, it'll suggest a relative path within the project, or an absolute path outside of it. For example: 
This fixes a problem where vscode otherwise suggests absolute paths in all cases, like `src/utils/flags`. That is not our current style and, in my case, was causing storybook to fail.
- If this …
=> Minor workspace tweaks

apps/browser/src/background/main.background.ts, apps/browser/src/globals.d.ts, apps/browser/src/services/browserPlatformUtils.service.ts
```
```
Add types for the Opera browser extension API so that work with Opera specific items and firefox sidebar actions (based on Opera) will be more maintainable.
- **apps/browser/src/background/main.background.ts:** Remove uses of `any` for `browserAction` and `sidebarAction`. Also use [`in`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/in) operator for checking if a property exists on the type for better typescript safety.
- **apps/browser/src/globals.d.ts:** Add types based on Opera documentation.
- **apps/browser/src/services/browserPlatformUtils.service.ts:** Remove unneeded uses of `any` and made checks for `window` more MV3 safe. …
=> Add Types for Opera API

.github/workflows/build-web.yml
```
```
- **.github/workflows/build-web.yml:** Fix hardcoded image name
=> Fix build web workflow

.github/workflows/automatic-issue-responses.yml
```
```
Fixes some typos in the auto issues responses in the workflow.
- **.github/workflows/automatic-issue-responses.yml:** Fixes some typos in the auto issues responses in the workflow.
=> Fix: typo in auto issues responses

bitwarden_license/bit-web/src/app/sm/layout/header.component.html, bitwarden_license/bit-web/src/app/sm/projects/projects-list.component.html, bitwarden_license/bit-web/src/app/sm/projects/projects.component.html, bitwarden_license/bit-web/src/app/sm/projects/projects.component.ts, bitwarden_license/bit-web/src/app/sm/secrets/secrets-list.component.html, bitwarden_license/bit-web/src/app/sm/secrets/secrets.component.html, bitwarden_license/bit-web/src/app/sm/secrets/secrets.component.ts
```
```
Improve the look'n'feel for table icons, and search field.
=> [SM-267] Minor visual fixes

apps/web/config/qa.json
```
```
Turned off the `showPasswordless` feature flag.
- **qa.json:** Set the feature flag to false in QA.
=> Turned off Passwordless feature flag in QA

.github/workflows/staged-rollout-desktop.yml
```
```
This PR adds the Staged Rollout Desktop workflow stub so that I can develop and test the workflow for DEVOPS-915.
- **.github/workflows/staged-rollout-desktop.yml:** Add workflow stub
=> Add Staged Rollout Desktop workflow stub

apps/web/src/app/accounts/login/login-with-device.component.ts
```
```
After confirming the login request having 2FA enabled, the user is redirected to the login screen instead of the 2FA page.
- **apps/web/src/app/accounts/login/login-with-device.component.ts:** Added condition to check if login response requires 2FA.
=> [SG-698] Passwordless Login with 2FA enabled does not redirect to 2FA page

apps/web/src/locales/en/messages.json, bitwarden_license/bit-web/src/app/sm/layout/new-menu.component.html, bitwarden_license/bit-web/src/app/sm/layout/new-menu.component.ts, bitwarden_license/bit-web/src/app/sm/secrets/dialog/secret-dialog.component.html, bitwarden_license/bit-web/src/app/sm/service-accounts/dialog/service-account-dialog.component.html, bitwarden_license/bit-web/src/app/sm/service-accounts/dialog/service-account-dialog.component.ts, bitwarden_license/bit-web/src/app/sm/service-accounts/requests/service-account.request.ts, bitwarden_license/bit-web/src/app/sm/service-accounts/service-account.service.ts, bitwarden_license/bit-web/src/app/sm/service-accounts/service-accounts.component.html, bitwarden_license/bit-web/src/app/sm/service-accounts/service-accounts.component.ts, bitwarden_license/bit-web/src/app/sm/service-accounts/service-accounts.module.ts
```
```
The purpose of this PR is to add a new Create Service Account Dialog for the Secrets Manager project.
- apps/web/src/locales/en/messages.json
Remove duplicate newServiceAccount and add in new local strings needed.
- bitwarden_license/bit-web/src/app/sm/layout/new-menu.component.html
bitwarden_license/bit-web/src/app/sm/layout/new-menu.component.ts
Add create service account dialog launch to the new title menu button.
- bitwarden_license/bit-web/src/app/sm/secrets/dialog/secret-dialog.component.html
Fix button to show blue as primary.
- bitwarden_license/bit-web/src/app/sm/service-accounts/dialog/service-account-dialog.component.html
bitwarden_license/bit-web/src/app/sm/service-accounts/dialog/service-account-dialog.component.ts
New Create service account dialog component. 
- …
=> [SM-187] Create Service Account Dialog

libs/angular/src/services/modal.service.ts
```
```
Mark `modalService.openViewRef` as deprecated with instructions to use the new method. This was always the case since `modalService` was created, it was just never marked as such.
=> Mark modalService.openViewRef as deprecated

libs/components/src/async-actions/bit-submit.directive.ts, libs/components/src/async-actions/in-forms.stories.ts
Clean up
```
```
Remove unused code.
=> [EC-558] chore: cleanup unused code

.github/workflows/version-auto-bump.yml
```
```
- **.github/workflows/version-auto-bump.yml:** Fix obtaining version tag. Fix regex matching major and minor portions of the released version.
=> [DEVOPS-1014] Fix desktop autobump workflow

apps/browser/src/background/service_factories/autofill-service.factory.ts, apps/browser/src/background/service_factories/totp-service.factory.ts
```
```
Fix spelling related to #3647 
- **apps/browser/src/background/service_factories/totp-service.factory.ts:** Spelling fix
- **apps/browser/src/background/service_factories/autofill-service.factory.ts:** Usage fix
=> [PS-1569] Fix spelling of totpServiceFactory

.github/workflows/release-web.yml
```
```
Add in unzip for cloudflare deploy
=> Add the cloudflare unzip back

.github/workflows/release-web.yml
```
```
Change the download target for the cloudflare deploy
=> Change the download target for cloudflare deploy

.github/workflows/version-auto-bump.yml
```
```
Fix desktop autobump workflow.
- **.github/workflows/version-auto-bump.yml:** Change trigger to tag push and change regex to support multiple clients.
=> Change trigger for desktop autobump

apps/browser/config/config.js, apps/desktop/config/config.js, apps/web/config.js
```
```
I found that clients are not using the environment settings in base.json because they are not being loaded.
I also found that config.js is not properly merging the keys provided in the .json files, which devs probably expect it to do. (e.g. if you set different flags in different config files)
In each `config.js`:
* import config from `base.json` and apply it before the chosen env (so we get `base`, `env` and `local` in that order)
* manually unpack nested keys (the structure doesn't change very often so didn't feel the need to recurse, just specify the keys we need) …
=> Fix local environment config loading

.github/whitelist-capital-letters.txt
```
```
The desktop security file got removed in between #3807.
=> [SM-296] Remove desktop security from the whitelist

apps/web/webpack.config.js
```
```
We use Azurite for uploading attachments. Now that CORS rules are working again, `127.0.0.1:10000` needs to be added to the whitelist to prevent requests from being blocked.
=> Whitelist 127.0.0.1:10000 for azurite

apps/browser/src/_locales/en/messages.json, apps/browser/src/popup/accounts/home.component.html, apps/browser/src/popup/accounts/home.component.ts, apps/browser/src/popup/accounts/login.component.html, apps/browser/src/popup/accounts/login.component.ts, apps/browser/src/popup/app-routing.module.ts, apps/browser/src/popup/components/private-mode-warning.component.html, apps/browser/src/popup/scss/base.scss, apps/browser/src/popup/scss/box.scss, apps/browser/src/popup/scss/misc.scss, apps/browser/src/popup/scss/pages.scss, apps/browser/src/popup/services/home.guard.ts, apps/browser/src/popup/services/services.module.ts, apps/desktop/src/app/accounts/login.component.ts, apps/web/src/app/accounts/login/login.component.ts, libs/angular/src/components/login.component.ts
```
```
Implement the browser changes for the two step login initiative.
This PR targets https://github.com/bitwarden/clients/pull/3648
See commits and descriptions for each individual change made.
=> [SG-164] Two Step Login Flow - Browser

libs/common/src/services/api.service.ts
```
```
Remove the deprecated calls to api for prelogin and register. Begins the deprecation process for the API hosted endpoints.
=> [SM-245] Change register and prelogin to always use api

apps/web/src/app/accounts/login/login.component.html, libs/angular/src/components/login.component.ts
```
```
Fix a couple of small bugs with the new two step login flow on web
- **apps/web/src/app/accounts/login/login.component.html:** Call `validateEmail()` on `keyup.enter` event.
- **libs/angular/src/components/login.component.ts:** Mark email form control is touched on `validateEmail()` so form errors are shown.
https://user-images.githubusercontent.com/8926729/196831275-75d25d04-ff62-49d3-9297-59d67bee7b40.mov
=> [SG-750] and [SG-751] Web two step login bug fixes

apps/web/docker/confd/app-id.toml, apps/web/docker/entrypoint.sh
wanted to reduce the number of directories under /etc/bitwarden to make it cleaner on disk.
=> consolidate subdirectories for persisted assets

apps/web/src/app/organizations/tools/import-export/org-export.component.ts
```
```
We should be able to export a password-protected file which can be imported into other Bitwarden vaults/accounts.
updating org-export.component.ts so that getExportData decides if it's going to be a password encrypted export
=> adding encrypted export with password functionality to web/organizations

libs/components/src/badge/badge.stories.ts, libs/components/src/banner/banner.stories.ts, libs/components/src/button/button.stories.ts, libs/components/src/callout/callout.stories.ts, libs/components/src/form-field/error-summary.stories.ts, libs/components/src/form-field/form-field.stories.ts, libs/components/src/form-field/multi-select.stories.ts, libs/components/src/icon-button/icon-button.stories.ts, libs/components/src/menu/menu.stories.ts
```
```
Updates the figma links to use the the merged file.
=> Update design urls to main figma file

apps/desktop/src/app/accounts/lock.component.ts
```
```
The auto prompt for desktop biometrics accidentally stopped working. This was caused by a timing issue where `supportsBiometric` is set after selecting the active account. To avoid this I've moved the checks into the biometric callback.
Resolves #3774.
=> [PS-1646] Resolve biometrics auto prompt not working

.storybook/main.js, angular.json
```
```
This PR disables Angular CLI usage analytics. Opt out directions can be found [here](https://angular.io/analytics).
**Added**: disables telemetry for Storybook. Documentation can be found [here](https://storybook.js.org/docs/react/configure/telemetry#how-to-opt-out).
- **angular.json:** Disable analytics for Angular CLI usage
- **main.js:** Disable telemetry for Storybook
=> Disable Angular Usage Analytics & Storybook Telemetry

apps/web/src/app/tools/generator.component.ts
```
```
Resolve #3798 by removing it as an option on web self hosted. In the same way firefox relay has to be disabled. 
- **apps/web/src/app/tools/generator.component.ts:** Remove DDG by it's value.
=> [PS-1768] Remove DDG forwarder from SH

bitwarden_license/bit-web/src/app/secrets-manager/projects/dialog/project-delete-dialog.component.ts, bitwarden_license/bit-web/src/app/secrets-manager/projects/dialog/project-dialog.component.ts, bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-dialog.component.ts, bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/dialog/service-account-dialog.component.ts
```
```
Mark all inputs as touched when submitting the forms. This ensures the validation is shown.
=> [SM-312] Mark all inputs as touched when submitting

bitwarden_license/bit-web/src/app/organizations/manage/sso.component.html
```
```
Removes usage of the, now removed, `bit-submit-button` that was left in the SSO edit page.
=> Remove usage of `bit-submit-button` 

apps/web/src/app/accounts/login/login.component.html, libs/angular/src/components/login.component.ts
```
```
Add focus to master password and email field for the web client.
- **apps/web/src/app/accounts/login/login.component.html:** Added the directive `appAutoFocus` to the `email` and `masterPassword` input fields.
https://user-images.githubusercontent.com/13024008/199103144-4d26efcb-b770-4ebe-a63d-fe1b26252e78.mov
=> [SG-770] Added focus to the email and master password fields

.github/workflows/build-desktop.yml
```
```
Add the 'libs/**' directory back to the Desktop build pipeline PR trigger list
- **.github/workflows/build-desktop.yml:** Add `libs/**` as a PR trigger.
=> Update Desktop build pipeline trigger

libs/angular/src/components/login.component.ts
```
```
Re-added the focusInput method to allow desktop build run
- **libs/angular/src/components/login.component.ts:** Added the focusInput method back while I work on a universal approach for the desktop client.
=> [FIX] Re-added the focusInput method to allow desktop build run

.eslintignore, .prettierignore
```
```
Running `npm run storybook` creates a build directory `storybook-static` in the root of the repo.
This is already in `.gitignore` but we should tell prettier and eslint to ignore it as well.
=> Tell eslint & prettier to ignore storybook-static

apps/web/src/locales/en/messages.json
```
- [ X] Bug fix
```
fixed event logs copy for EC bugs 679, 680, and 681
- loacales/en/**messages.json*** updated strings
=> [EC-680]-fixed EC reported event log copy bugs

.github/workflows/release-browser.yml, .github/workflows/release-cli.yml, .github/workflows/release-desktop.yml, .github/workflows/release-web.yml
```
```
This PR updates the workflow runs to include their `workflow_dispatch` name in each run, this separates `dry run` releases runs from the actual releases runs.
=> add run-name for releases to include their workflow trigger

.github/workflows/enforce-labels.yml, .github/workflows/version-bump.yml
```
```
FIx: the Enforce Labels workflow is not being run on version bump PRs.
- **.github/workflows/version-bump.yml:** Add API call to trigger enforce labels workflow
- **.github/workflows/enforce-labels.yml:** Add workflow_dispatch trigger to run action using API
=> Run enforce labels workflow on version bump in clients repo

apps/cli/src/commands/get.command.ts, apps/cli/src/commands/import.command.ts, apps/cli/src/commands/list.command.ts, libs/common/src/abstractions/organization/organization.service.abstraction.ts, libs/common/src/services/organization/organization.service.ts
```
```
Add an escape hatch to get organization information directly from state by id so that non-observable contexts like the CLI can guarantee that they get the information. 
- Added a method to `OrganizationService` to get a single organization by id from state.
- Used that method instead of `.get` throughout all of CLI. 
=> [PS-1841] Fix org-* commands for CLI

apps/browser/src/popup/vault/vault-select.component.ts
```
```
Instead of using a local object, switch to using the object that `vaultFilterService` keeps so that the selection can be shared between the Tab/Vault component in browser. 
* Use vault filter item from vaultFilterService
=> [PS-1839] Remove local vaultFilter

apps/web/src/app/components/organization-switcher.component.ts, libs/angular/src/vault/vault-filter/services/vault-filter.service.ts
```
```
Sort organizations inside of `buildOrganizations` so that it will be in name sort for both desktop and web.
- **libs/angular/src/vault/vault-filter/services/vault-filter.service.ts:** Sort by name exactly as it is done for the vault select component in browser. 
=> [PS-1843] Sort organizations in `buildOrganizations`

apps/browser/src/popup/vault/vault-select.component.html
```
```
Fix:
> When a user is a member of an Organization that has enabled the Remove Individual Vault policy, then they should not see the ‘My Vault’ option in the filter drop down. They should only see filters by Org name that they are members of. 
Fix typo 🙃 
=> [EC-748] Hide My Vault if Remove Individual Vault is on

apps/browser/src/popup/accounts/lock.component.html, apps/browser/src/popup/scss/base.scss, apps/browser/src/popup/scss/box.scss
```
```
Fix button style inside .box-footer for biometrics login
added a style to target the button in the .box-footer > .btn.primary for the biometric login
(log out button never had a hover style)
=> [EC-665] Fix biometrics button style

.github/workflows/release-browser.yml, .github/workflows/release-cli.yml, .github/workflows/release-desktop-beta.yml, .github/workflows/release-desktop.yml, .github/workflows/release-web.yml, .github/workflows/staged-rollout-desktop.yml
```
```
This PR adds a branch check to the `Staged Rollout Desktop` workflow in order to prevent running it from any branch besides `rc` and `hotfix-rc-desktop`.
- **.github/workflows/staged-rollout-desktop.yml:** Add `setup` job to check branch that workflow was triggered from.
=> Add branch check for Staged Rollout Desktop workflow

.github/whitelist-capital-letters.txt, apps/web/src/app/vault/ciphers.component.ts, libs/common/src/misc/serviceUtils.spec.ts, libs/common/src/misc/serviceUtils.ts
```
```
This PR adds tests and additional comments to our `ServiceUtils`. These functions can be difficult to read and modify, making documentation and testing useful.
I'm checking this in to my feature branch for OAVR due to the fact that I've already added previous documentation and an additional function to `ServiceUtils`. 
=> [EC-686] add tests and comments to serviceUtils

.github/workflows/build-web.yml
```
```
Update the version for the QA web artifacts to follow [Backus–Naur Form Grammar](https://semver.org/#backusnaur-form-grammar-for-valid-semver-versions) from SemVer
- **.github/workflows/build-web.yml:** Remove spaces in the QA Web artifact version
=> Update QA Web Artifact versioning

libs/common/src/abstractions/api.service.ts, libs/common/src/services/api.service.ts
```
```
Mark the `ApiService` as deprecated to encourage refactoring.
=> Deprecate the Api Service

README.md
```
```
In the original README.md, the url in the statement: `Please refer to the Clients section', redirected to a broken link: [https://contributing.bitwarden.com/clients/](https://contributing.bitwarden.com/clients/)
This PR adds /docs/ to the URL, allowing it to redirect to the correct page. (Fixes #4122)
**README.md:**
Changes the link in README.md from: 
`Please refer to the [Clients section](https://contributing.bitwarden.com/clients/)`
to
`Please refer to the [Clients section](https://contributing.bitwarden.com/docs/clients/)`
Before:
After:
- If this change has particular **deployment requirements** - notify …
=> [PS-1922] Fix 'clients section' link in README

apps/web/src/app/accounts/login/login.component.html, apps/web/src/app/accounts/register-form/register-form.component.html, apps/web/src/app/tools/import-export/export.component.html, apps/web/src/app/tools/import-export/file-password-prompt.component.html, bitwarden_license/bit-web/src/app/organizations/manage/scim.component.html, libs/components/src/form-field/form-field-control.ts, libs/components/src/input/input.directive.ts
```
```
Fixes build errors caused by #3601 
=> Fix build errors for strict templates

apps/web/src/app/organizations/manage/collections.component.ts, apps/web/src/app/organizations/manage/group-add-edit.component.ts, apps/web/src/app/organizations/manage/groups.component.ts, apps/web/src/app/organizations/shared/components/collection-dialog/collection-dialog.component.ts
```
```
I talked with design about having our dialogs aligned to the top, and we decided to keep all new dialogs centered. This PR removes the `Overlay` configuration while opening the Groups and Collection dialogs and returns their positioning to the center.
=> Center Groups and Collections Dialogs

.github/workflows/staged-rollout-desktop.yml
```
```
Fix the staged rollout pipeline for Desktop
- **.github/workflows/staged-rollout-desktop.yml:** Replace a Greek comma with double quotes
=> Fix the Staged Rollout Desktop Pipeline

.github/workflows/staged-rollout-desktop.yml
```
```
fix_staged_rollout_typo
=> fix_staged_rollout_typo

.github/workflows/staged-rollout-desktop.yml
```
```
This PR fixes an issue with the copy logic in the `Staged Rollout Desktop` workflow.
- **.github/workflows/staged-rollout-desktop.yml:** Remove the download from `S3` step since we can just get the files from `R2`. Update copy logic to copy each file separately due to how the `aws` cli works.
=> Fix the Staged Rollout Desktop workflow

bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/access/access.service.ts, bitwarden_license/bit-web/src/app/secrets-manager/sm-routing.module.ts
```
```
- Change landing page to projects
- Use camelCase for encrypted payload in access tokens.
=> Fixes for the demo

apps/web/src/app/components/organization-switcher.component.ts, apps/web/src/app/layouts/navbar.component.ts, libs/angular/src/components/share.component.ts, libs/angular/src/vault/vault-filter/services/vault-filter.service.ts, libs/common/src/abstractions/organization/organization.service.abstraction.ts
```
```
Reimplementation of #4147 on `hotfix-rc-web`.
- **libs/common/src/abstractions/organization/organization.service.abstraction.ts:** Add a helper for filtering out provider organizations.
- Utilize the filter in various places that it is needed based on who used to call `getAll` from before #3462 
=> Use isNotProviderUser

apps/web/README.md
=> [PS-1976] fix url

.github/workflows/build-browser.yml, .github/workflows/build-cli.yml, .github/workflows/build-desktop.yml, .github/workflows/build-web.yml, .github/workflows/release-desktop-beta.yml, .github/workflows/release-desktop.yml, .github/workflows/version-auto-bump.yml, .github/workflows/version-bump.yml
```
```
This PR is updating the set output command to the latest method, the previous is deprecated.
Change the ::set-output command to Github's environment variable $GITHUB_OUTPUT
- .github/workflows/*.yaml files
=> update ::set-output to latest

README.md, apps/browser/README.md, apps/cli/README.md, apps/desktop/README.md, apps/web/README.md
```
```
We changed the contributing links again in https://github.com/bitwarden/contributing-docs/pull/20.
=> Update urls to match the contributing docs

.github/workflows/build-cli.yml, package-lock.json, package.json
```
```
Bump `pkg` and `pkg-fetch` to use Node 16.16.
=> [SM-370] Bump pkg & pkg-fetch

apps/web/config/qa.json
```
```
Disable Secrets Manager for QA initially so we can test the touch points.
=> [SM-310] Disable Secrets Manager in QA

libs/components/src/async-actions/bit-action.directive.ts, libs/components/src/async-actions/bit-submit.directive.ts, libs/components/src/async-actions/standalone.stories.ts
```
```
Add logging to async actions
=> [EC-827] feat: add logging to async actions

libs/components/src/checkbox/checkbox.stories.ts
```
```
Show more helpful source code in storybook
=> fix: make checkbox story documentation easier

libs/components/src/async-actions/bit-action.directive.ts, libs/components/src/async-actions/form-button.directive.ts, libs/components/src/async-actions/in-forms.stories.mdx, libs/components/src/async-actions/standalone.stories.mdx
```
```
- Improve docs after questions I've gotten on slack
- Improve guards against multiple requests happening at the same time
=> feat: improve async actions docs and guards

apps/web/config/cloud.json
```
```
Set `showPasswordless` feature flag to true that I accidentally set to false in a bade merge resolution in [this PR](https://github.com/bitwarden/clients/commit/40cade39bb29f765478cbda85e4262b37058dd9f).
=> Set showPasswordless to true

apps/web/src/locales/en/messages.json, bitwarden_license/bit-web/src/app/secrets-manager/projects/projects-list/projects-list.component.html, bitwarden_license/bit-web/src/app/secrets-manager/projects/projects-list/projects-list.component.ts, bitwarden_license/bit-web/src/app/secrets-manager/shared/secrets-list.component.html, bitwarden_license/bit-web/src/app/secrets-manager/shared/secrets-list.component.ts
```
```
Based on new designs, remove the 'Import Secrets' button on the Projects & Secrets list when there are no items in the list.
**Empty Secrets List**
**Empty Projects List**
=> SM-261: Remove Import Secrets button

libs/components/src/dialog/dialog/dialog.component.ts, libs/components/src/form-control/form-control.component.ts
```
```
Updated boolean setters to follow a better convention. The dialog is used in secrets manager and inline is not used yet so should be safe to merge.
=> [SM-388] Make CL boolean setters more strict

libs/angular/src/components/generator.component.ts, libs/common/src/services/usernameGeneration.service.ts
```
```
Fix default value of email providers list.
- **generator.component.ts:** Add validation for empty value.
- **usernameGeneration.service.ts:** Set default value of forwardedService as "" in order to use the value as control for proper element display.
=> [SG-632] - Fix default value of email providers list

apps/browser/src/popup/scss/base.scss, apps/browser/src/popup/scss/box.scss, apps/browser/src/popup/scss/buttons.scss, apps/browser/src/popup/scss/pages.scss, apps/browser/src/popup/settings/excluded-domains.component.html, apps/browser/src/popup/vault/add-edit.component.html, apps/browser/src/popup/vault/attachments.component.html, apps/browser/src/popup/vault/view.component.html
https://bitwarden.atlassian.net/browse/PS-2078
```
```
This PR addresses feedback from the community on the new design changes that were released in the 2012.12.0 release. Mostly just adjustments to margins and padding and cleaning up a few inconsistencies in spacing throughout.
- **all css files:** Margin, padding, spacing adjustments
- **all html files:** Implementing new `single-line` class to certain box-content-rows for appropriate style application
This PR
2012.12
2012.11 and earlier
=> PS-2078: browser margin and padding style adjustments

apps/web/src/app/organizations/manage/people.component.ts
```
```
Fixing defect in the [SG-668 PR](https://github.com/bitwarden/clients/pull/4093) where users would not be presented with the upgrade modal if they used the filter buttons on the people management screen. 
- **apps/web/src/app/organizations/manage/people.component.ts:** Changed logic to use allUsers array instead of the standard users array because users gets filtered & the length changes when a user filters the data. 
Before: 
https://user-images.githubusercontent.com/116684653/208542757-2afece4c-55db-4521-ac04-b353a472b23e.mov
After: 
https://user-images.githubusercontent.com/116684653/208542769-610e098f-9788-42a0-8379-996c2df8a0d9.mov …
=> SG-898 - People Management - Upgrade Modal now presented properly in all scenarios 

apps/browser/src/background/main.background.ts
```
```
Use a multi-messaging service that can allow a message to be sent both in memory and to the detached background based on various scenarios.
- **apps/browser/src/background/main.background.ts:** Use array of message services and register them based on runtime mode. Then relay the messages sent to a multi-messaging service to each sub messaging service.
=> Use Multi-Messaging Service

apps/web/src/app/organizations/manage/group-add-edit.component.html
=> [EC-864] Dialog size is inconsistent

apps/web/src/app/organizations/shared/components/access-selector/access-selector.component.html, apps/web/webpack.config.js, libs/components/src/multi-select/scss/bw.theme.scss
```
```
Fix the following issues:
1. Input fields have slightly different height
2. Select focus ring is not consistent with standard form elements (eg. the icon button next to it)
3. Permission column static cells are misaligned with editable cells (select input padding offset)
Following fixes were used:
1. Multi-select uses a `min-height` which was 1px too big. Removing `min-height` completely breaks the component. I've updated the rule to match the standard select, but we should really look into fixing it properly with padding or something.
2. Problem was that the border was removed completely. I've re-added it but made it transparent.
2 Extra. I've added border border on hover that matches the icon button. This is a new feature that needs to be reviewed.
3. This is also an issue that …
=> [EC-828] Access selector layout bugs

apps/web/src/app/tools/import-export/export.component.html, apps/web/src/locales/en/messages.json
=> [EC-587] Update UI copy for Encrypted Export

apps/web/src/app/organizations/shared/components/collection-dialog/collection-dialog.component.ts
```
```
Update the new collection dialog to properly show success toasts when saving or deleting a collection.
=> [EC-872] Collection dialog success toasts

apps/browser/src/popup/vault/vault-select.component.ts
```
```
Add similar provider filter to browser vault select dropdown that we have on other organization selectors. 
- **apps/browser/src/popup/vault/vault-select.component.ts:** Import the filter used elsewhere and include it on the observable.
=> [PS-1942] Add Provider Filter to Browser Vault Select

apps/web/config/base.json, apps/web/config/cloud.json, apps/web/config/selfhosted.json
```
```
Set the secretsManager flag to false outside of dev to deactivate it in all other environments
=> [EC-892] Hide Secrets Manager

apps/web/src/app/organizations/vault/vault-filter/vault-filter.component.ts, apps/web/src/app/vault/vault-filter/components/vault-filter.component.ts
```
```
Organizations do not support the concept of "Favorites" so we should hide that filter from the organization vault filter.
- **vault/vault-filter/components/vault-filter.component.ts:** Introduce the option to specify a list of cipher filter types to exclude when building the type filters. 
=> [EC-885] Hide favorites filter for organizations

apps/web/src/app/reports/pages/inactive-two-factor-report.component.ts, apps/web/webpack.config.js
```
```
2fa.directory recently changed FQDN for API files. This PR changes the URI to reflect that.
=> [PS-2118] Update 2fa.directory API URI

apps/browser/src/background/main.background.ts
Reverts bitwarden/clients#4304
Currently AuthService needs the ability to send it's messages to the background from the background.
This will be 🍒 ⛏️  to `rc`
=> [PS-2164] Revert "Use Multi-Messaging Service"

apps/web/src/locales/en/messages.json, bitwarden_license/bit-web/src/app/secrets-manager/models/view/secret.view.ts, bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-dialog.component.html, bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-dialog.component.ts, bitwarden_license/bit-web/src/app/secrets-manager/secrets/requests/secret.request.ts, bitwarden_license/bit-web/src/app/secrets-manager/secrets/responses/secret-list-item.response.ts, bitwarden_license/bit-web/src/app/secrets-manager/secrets/responses/secret.response.ts, bitwarden_license/bit-web/src/app/secrets-manager/secrets/secret.service.ts, bitwarden_license/bit-web/src/app/secrets-manager/shared/secrets-list.component.html
```
- [ x ] New feature development
```
For each secret, we show a list of projects and allow the user to select a single project to assign it to.
bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-dialog.component.html
bitwarden_license/bit-web/src/app/secrets-manager/secrets/secret.service.ts
=> [SM-73] Edit Project for Secret

apps/web/src/app/settings/organization-plans.component.ts, apps/web/src/app/settings/premium.component.html, apps/web/src/app/settings/premium.component.ts, apps/web/src/locales/en/messages.json
```
```
Update the verbiage in the Go Premium callout to make it easier for new users to find the family plan with a direct link.  
- **apps/web/src/app/settings/premium.component.html:** Modified copy + provided link
- **apps/web/src/app/settings/premium.component.ts:** Added familyPlanMaxUserCount prop
- **apps/web/src/locales/en/messages.json:** Added new translations
- **apps/web/src/app/settings/organization-plans.component.ts:** Fix broken query param behavior so create-organization route query param handling works to have the organization-plans comp select the correct plan on load. 
Original copy:
New copy and behavior:
https://user-images.githubusercontent.com/116684653/210900120-184c6cc7-5eb7-48ee-a7f0-d5ee16eda741.mov …
=> Feature/SG-959 Update "Go premium" copy verbiage

libs/angular/src/components/send/add-edit.component.ts
```
```
Fixing the Issue with Successful toast message does not appear when creating a send
- **libs/angular/src/components/send/add-edit.component.ts:** Add a code to return a success toast message when copy is not selected
=> [PS-1770] Defect Successful toast message does not appear

apps/web/src/app/vault/vault.component.html, apps/web/src/app/vault/vault.component.ts
=> [EC-964] Fix missing breadcrumbs in vault

bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-dialog.component.ts
```
```
Ensure that editing and creating a secret within a project associates it with the project Id.
bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-dialog.component.ts 
If a projectId is being passed in set it on the formGroup 
=> [Sm-100] Create Secrets Modal

apps/browser/src/services/browserFileDownloadService.ts
```
```
Remove msSaveOrOpenBlob as we no longer support IE.
- **browserFileDownloadService.ts:** Removed call to msSaveOrOpenBlob
=> SG-852 Removed msSaveOrOpenBlob

apps/web/src/app/organizations/manage/groups.component.html, apps/web/src/app/organizations/members/people.component.html, apps/web/src/app/vault/vault-items.component.html
```
```
The new `bit-table` TableDataSource changes require using `<ng-template body>` instead of `<ng-container body>`. Updated our Vault, Members, and Groups tables.
=> update OAVR feature branch with bit-table changes

.github/CODEOWNERS
```
```
Add Codeowners for the secrets manager folder.
=> [SM-347] Add Codeowners

.github/workflows/version-auto-bump.yml
```
```
Fix the version autobump workflow.
- **.github/workflows/version-auto-bump.yml:** Fix regex extracting version from released tag.
=> Fix autobump workflow

apps/web/config/qa.json
```
```
Enable SM in QA cloud.
=> [SM-447] Enable Secrets Manager in QA

libs/common/spec/importers/keepass2-xml-importer-testdata.ts, libs/common/spec/importers/keepass2-xml-importer.spec.ts, libs/common/src/importers/keepass2-xml-importer.ts
```
```
Fix the issue with keepass2 import fails on cli 2022.9.1
- **libs/common/spec/importers/keepass2-xml-importer.spec.ts:** Added some tests to show that KeePassFile tag and root tag must exist before a file is parsed.
- **libs/common/src/importers/keepass2-xml-importer.ts:** Made changes to the query selector.
=> [PS 1579]kee pass2 import fails on cli

apps/web/src/locales/en/messages.json
```
```
Some changes from @djsmith85 were lost as part of the merge conflict resolution of OAVR. This branch reintroduces those changes.
=> Re-apply changes from #3971

bitwarden_license/bit-web/src/app/secrets-manager/models/view/project-list.view.ts, bitwarden_license/bit-web/src/app/secrets-manager/models/view/project.view.ts, bitwarden_license/bit-web/src/app/secrets-manager/models/view/secret-list.view.ts, bitwarden_license/bit-web/src/app/secrets-manager/models/view/secret-project.view.ts, bitwarden_license/bit-web/src/app/secrets-manager/models/view/secret.view.ts, bitwarden_license/bit-web/src/app/secrets-manager/models/view/service-account.view.ts, bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/models/view/access-token.view.ts
```
```
Remove `imports View` from secrets manager view models.
=> [SM-452] Remove imports view from secrets manager models

libs/common/src/enums/kdfType.ts
https://bitwarden.atlassian.net/browse/PS-2273
```
```
Latest OWASP recommendations are 600k iterations for PBKDF2. Update the default to match.
- **kdfType.ts:** Update default value to 600k.
=> [PS-2273] update to 600k per latest owasp

apps/browser/src/_locales/en/messages.json, apps/desktop/src/locales/en/messages.json, apps/web/src/locales/en/messages.json, libs/angular/src/components/add-edit.component.ts
```
```
Add the honorific title "Mx" as an option in the identity title.
- **libs/angular/src/components/add-edit.component.ts:** Extend identity title selection to include "Mx" 
- Ensure option is displayed on all platforms: 
- **apps/browser/src/_locales/en/messages.json:**
- **apps/web/src/locales/en/messages.json:**
- **apps/desktop/src/locales/en/messages.json:**
=> [PS-2323] Add honorific title "Mx"

libs/components/src/button/button.component.ts
```
```
Adds `disabled:tw-cursor-not-allowed` to buttons
See [Chromatic](https://62a88a6de5b807fa98886113-ndfzaudrle.chromatic.com/?path=/story/component-library-button--disabled)
=> [CL-73] Button Disabled State: Cursor Not Allowed

libs/components/src/progress/index.ts, libs/components/src/progress/progress.component.html, libs/components/src/progress/progress.component.ts, libs/components/src/progress/progress.module.ts, libs/components/src/progress/progress.stories.ts
```
```
Adds a Progress component to the component library
Same content changes as [4060 - closed](https://github.com/bitwarden/clients/pull/4060), which had unverified commits. So this (#4437) is just a clean PR with verified commits.
=> [CL-14] Progress Component

.eslintrc.json
```
```
Fix errors resoling tsconfig.eslint.json file when loading vs code workspace.
- **.eslintrc.json:** Glob wildcard for `tsconfig.eslint.json`
=> resolve tsconfig eslint errors

apps/web/src/app/organizations/vault/vault.component.html
```
```
adds `bitMenuItem` to the buttons inside the New button menu. This allows the items to be navigatable from the keyboard
=> [EC-1023] add bitMenuItem to menu buttons

apps/web/src/locales/en/messages.json
```
```
We forgot to update the invite helper text in OAVR v2.
=> [EC-1020] update invite helper text

apps/web/src/app/organizations/manage/groups.component.html, apps/web/src/locales/en/messages.json
```
```
Update the text placeholder for the Groups search bar from "Search" to "Search groups"
=> [EC-1024] update groups search placeholder

apps/web/src/app/organizations/members/people.component.html
```
```
The name in the members table wasn't focusable because we didn't add a button. This adds a button so we can tab into the name.
=> [EC-1019] add a button to members row around name

.eslintrc.json, clients.code-workspace
=> Override eslint config for vscode workspace

bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/access/access-list.component.html
```
```
Make 'All' label in table header match other column headers.
- `bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/access/access-list.component.html`: override global css interfering with `bitCell`
=> [SM-438] fix table header styles

.github/workflows/build-web.yml, apps/web/config/poc.json, apps/web/package.json
```
```
Add new POC web build artifact.
- **apps/web/config/poc.json:** Add the new poc artifact configuration
- **apps/web/package.json:** Add the build command for the new poc configuration
- **.github/workflows/build-web.yml:** Added a new build artifact matrix input
=> Add new POC web artifact

apps/web/src/app/organizations/manage/group-add-edit.component.html, apps/web/src/locales/en/messages.json
```
```
adds a hint to the Group dialog name about the max characters accepted.
=> [EC-1022] add hint to group name input about max chars

apps/web/src/app/settings/change-kdf.component.html, apps/web/src/locales/en/messages.json
```
```
Update warning message for iterations changes to align with contents of help article.
- **apps/web/src/locales/en/messages.json:** Added new translation message with key `changeKdfLoggedOutWarning`.
- **apps/web/src/app/settings/change-kdf.component.html:** Updated template with new translation key
=> [SG-1011] Updated warning message for iteration changes

apps/web/src/app/organizations/manage/groups.component.html, apps/web/src/app/organizations/members/people.component.html, apps/web/src/app/vault/vault-items.component.html
```
```
Our Component Library checkbox has better dark mode support so we should transition our table checkboxes to the CL component before releasing OAVR
=> [EC-1050] add CL checkbox to tables

bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/service-account.component.html
```
```
Seems a commit managed to get in before I merged #4576
=>  [SM-468] Add missed eslint exception

apps/desktop/src/app/app.component.ts, apps/desktop/src/app/app.module.ts
```
```
Seems some imports had unnecessary `../app` in the imports after #4542.
=> Fix imports going up to far

apps/web/src/app/settings/change-kdf.component.html
ref https://bitwarden.atlassian.net/browse/PS-2404
```
```
People end up bricking their accounts by using values that are way out of bounds of modern day devices. This PR puts some guard rails on that by adjusting the iteration count maximum values for Argon2.
- **change-kfd.component.html:** Adjust client side validation for Argon2 iterations.
=> adjust max iterations for argon2

apps/web/src/app/settings/change-kdf.component.html
```
```
Update the minimum value for KDF iterations to `100000`.
=> [SG-1025] Updated minimum value for KDF iterations

apps/browser/src/popup/accounts/login-with-device.component.ts, apps/desktop/src/main.ts
```
```
Added login flow sync to match the normal login sync. 
=> [SG-1034] [Defect] - Vault is empty upon login confirmation

apps/web/src/vault/app/vault/vault.component.ts
```
```
Disable the KDF iterations warning till authentication issues from KDF iterations changed have been sorted.
=> [SG-1039] Disable the KDF iterations warning

apps/web/src/app/organizations/shared/components/access-selector/access-selector.component.ts
```
```
Fix the sorting algorithm. We previously concatenated multiple fields of data into one string and then sorted it. This PR fixes that so that we sort on each field of data separately.
=> [EC-1025] [Design feedback] The nested collections within the multi-select dropdown are not ordered by the parent collection

README.md
=> [PS-2426] adding link to open positions

apps/web/config/qa.json
```
```
Disables Secrets Manager in QA environment.
=> Disable secrets manager

bitwarden_license/bit-web/src/app/secrets-manager/projects/projects-list/projects-list.component.html, bitwarden_license/bit-web/src/app/secrets-manager/projects/projects-list/projects-list.component.ts
```
```
The View Project option in the project list item menu will now navigate to the project details page.
- **`bitwarden_license/bit-web/src/app/secrets-manager/projects/projects-list/projects-list.component`:** Changed bitMenu button to anchor; added route; removed view event since it is no longer needed
=> [SM-462] fix View Project in dropdown

libs/angular/src/components/register.component.ts
```
```
Default to `true` for the new checkbox to check for password inclusion in breaches.
- **register.component.ts:** Set `checkForBreaches` to `true` by default
=> Set checkForBreaches to true (checked) by default.

apps/web/src/app/organizations/settings/account.component.ts, libs/common/src/models/request/organization-update.request.ts, libs/common/src/models/response/organization.response.ts
```
```
Remove obsolete fields
=> [EC-489] chore: remove obsolete `identifier` field

apps/browser/src/popup/accounts/two-factor.component.ts
=> [PS-2176] Backport Open WebAuthn Prompt in New Tab

apps/web/src/auth/register-form/register-form.component.ts
```
```
Fix breach checks happening for web before they are fully implemented
**apps/web/src/auth/register-form/register-form.component.ts:** Set `checkForBreaches` to false for web for now with comment to remove.
Before:
After:
=> Turn off checking for breaches in web for now

apps/web/src/vault/org-vault/vault.component.ts
```
```
Fix collections not being loaded overridden properly in the org vault.
This is caused by setting modal data after the modal has been opened by `modalService`. We should use the `setComponentParameters` callback to do this instead.
Alternative to #4693. I prefer this approach because it works in with the existing data flow rather than adding additional ways of overriding modal data.
Note that we have TDL-219 to track a refactor of this component to hopefully reduce/eliminate these issues.
**This will be cherry-picked**
- **apps/web/src/vault/org-vault/vault.component.ts** - 
- add additional parameter to `editCipherId` so that it can take another callback to set component parameters. If provided, it'll call both the standard callback (to set the common parameters always required) …
=> [EC-1069] Fix race condition when setting modal properties

libs/angular/src/auth/components/login-with-device.component.ts, libs/angular/src/auth/components/login.component.ts
```
```
Use loginService to help persist Remember email option when performing login through option Log in with device.
- **libs/angular/src/auth/components/login-with-device.component.ts:** Initialize property by fetching value though login service. 
- **libs/angular/src/auth/components/login.component.ts:** Set form value through loginService.
=> [SG-1047] Fix remember email on web

.github/renovate.json
```
```
Remove electron and zone.js from renovate. Those dependencies need some manual work.
=> Ignore electron dependency changes

apps/web/src/app/organizations/members/components/member-dialog/member-dialog.component.ts
```
```
Put the SM user toggle behind the feature flag.
=> [SM-493] Put user toggle behind feature flag

apps/web/src/vault/individual-vault/vault.component.ts
```
```
Enable KDF iterations warning that was previously disabled due to concerns with users having authentication problems after changing their iterations.
Reinitiailized the variable `this.showLowKdf` with `this.isLowKdfIteration()`.
=> [SG-1053] Enabled KDF iterations warning

bitwarden_license/bit-web/src/app/secrets-manager/projects/projects-list/projects-list.component.ts, bitwarden_license/bit-web/src/app/secrets-manager/projects/projects/projects.component.html, bitwarden_license/bit-web/src/app/secrets-manager/projects/projects/projects.component.ts, libs/components/src/table/table-data-source.ts, libs/components/src/table/table.stories.ts
```
```
Add filtering capabilities to table data source. Also updates the projects page in secrets manager to support search.
Uses the same implementation as the CDK. Currently does not support overriding the filtering logic, but something we should evaluate in the future.
=> [SM-497] Add filtering capabilities to the table datasource

bitwarden_license/bit-web/src/app/secrets-manager/shared/header.stories.ts, bitwarden_license/bit-web/tsconfig.json
```
```
The header stories accidentally broke in #4683.
=> Fix header stories

.github/workflows/build-web.yml, .github/workflows/release-web.yml
```
```
- **.github/workflows/build-web.yml:** Change `bitwardenqa` to `bitwardenprod` ACR
- **.github/workflows/release-web.yml** Change `bitwardenqa` to `bitwardenprod` ACR and login to PROD subsription
=> [DEVOPS-1211] Push web docker images to bitwardenprod ACR

.github/workflows/build-web.yml, .github/workflows/release-web.yml
```
```
Fix login to Azure to support prod ACR docker push.
- **.github/workflows/build-web.yml:** Change login to Azure from QA subscription to Prod subscription.
=> Fix Azure login in self-host web build

bitwarden_license/bit-web/src/app/secrets-manager/projects/projects-list/projects-list.component.html, bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/service-accounts-list.component.html, bitwarden_license/bit-web/src/app/secrets-manager/shared/secrets-list.component.html
```
```
The name of an item in the secrets list should be clickable and open the edit dialog on click.
- **`bitwarden_license/bit-web/src/app/secrets-manager/shared/secrets-list.component.html`:** Change name in list to button
=> [SM-463] add link to secrets list

apps/web/src/app/settings/change-kdf.component.html
```
```
Adjust the KDF algorithm and KDF iteration links. The wrong links were updated on each help link.
=> [SG-1012] Update help link for KDF algorithm and iterations

libs/components/src/table/sortable.component.ts
```
```
Changes the sortable directive to be bold to match the regular table headers.
=> [SM-469] Change sortable to be bold

apps/web/src/locales/en/messages.json, bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/access/access-list.component.html, bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/access/access-list.component.ts, bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/access/access-tokens.component.html, bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/access/access-tokens.component.ts, bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/access/access.service.ts, bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/models/requests/revoke-access-tokens.request.ts
```
```
Add support for revoking service accounts access tokens.
- **bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/access/access-list.component.html:** Wire up revoke events and provide a table menu.
- **bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/access/access-tokens.component.ts**: Add logic for revoking access tokens after verifying the user.
- **bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/access/access.service.ts**: Implement API logic.
=> [SM-501] Revoke Access Tokens

.github/workflows/build-web.yml
```
```
- Add temporary push to QA ACR to unblock QA Team
- Consolidate docker image build jobs into single matrix with renamed images
- **.github/workflows/build-web.yml:** Removed job. Updated pattern from server repo.
=> Add temporary QA ACR

bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-dialog.component.html
```
```
Remove Service Accounts tab from secrets dialog.
=> [SM-519]  Remove ServiceAccounts tab from secret dialog

bitwarden_license/bit-web/src/app/secrets-manager/layout/org-switcher.component.html, bitwarden_license/bit-web/src/app/secrets-manager/sm-routing.module.ts, libs/components/src/navigation/nav-group.component.html, libs/components/src/navigation/nav-group.component.ts, libs/components/src/navigation/nav-item.component.ts
```
```
Change the route matching in bit-nav-item to be subset instead of exact. Also added an input which allows us to toggle exact routing for some urls.
=> [SM-525] Fix projects not being active when on subroute

apps/web/src/app/shared/shared.module.ts, bitwarden_license/bit-web/src/app/secrets-manager/overview/overview.component.html, bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/service-accounts-list.component.html, bitwarden_license/bit-web/src/app/secrets-manager/shared/access-policies/access-selector.component.html, bitwarden_license/bit-web/src/app/secrets-manager/shared/header.component.html, bitwarden_license/bit-web/src/app/secrets-manager/shared/new-menu.component.html, bitwarden_license/bit-web/src/app/secrets-manager/shared/projects-list.component.html, bitwarden_license/bit-web/src/app/secrets-manager/shared/secrets-list.component.html, libs/components/src/typography/typography.directive.ts
```
```
Use `bitTypography` for headers. Also removed `tw-text-xl` from menus.
=> [SM-557] Use bitTypography for headers

package.json
```
```
We can speed up prettier by enabling caching.
=> Enable caching for prettier

package.json
```
```
Running prettier without `--cache` will delete the cache. Since we run prettier on staged files we will always delete the cache.
=> Add cache to lint-staged for prettier

bitwarden_license/bit-web/src/app/secrets-manager/shared/header.stories.ts
```
```
Resolves the broken stories due to header stories not importing the typography module.
=> Require typography module for header stories.

libs/components/src/dialog/dialog/dialog.component.html, libs/components/src/dialog/dialog/dialog.stories.ts
```
```
We should truncate dialog headers to prevent them from overflowing. Added a test to prevent this from regressing in the future.
=> [SM-402] Truncate dialog headers

bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-import.component.html
```
```
The import button should show a spinner when importing a large file. 
Fixed typo `bitformButton` --> `bitFormButton`
=> [SM-529] fix directive typo in SM import button

libs/components/src/table/table-data-source.ts, libs/components/src/table/table.stories.ts
```
```
Sorting by strings in tables should be case insensitive.
- **libs/components/src/table/table-data-source.ts:** Make value lowercase before sorting
- **libs/components/src/table/table.stories.ts:** Added story
=> [SM-552] make string sort in TableDataSource case insensitive

apps/web/src/app/organizations/members/components/member-dialog/member-dialog.component.html
```
```
We added the wrong `formControlName` to the Manage Users policy on the member dialog. This is a one liner to fix that
=> [AC-1108, AC-1107, AC-1109, AC-1106] add correct formControlName

bitwarden_license/bit-web/src/app/secrets-manager/shared/secrets-list.component.html, bitwarden_license/bit-web/src/app/secrets-manager/shared/secrets-list.component.ts
```
```
Users can now sort by the project column in the secrets list. This allows admins to easily view all unassigned projects. 
Added bitSortable and custom sort function to the projects column.
https://user-images.githubusercontent.com/17113462/222497455-4bfe1c72-f7ed-4de6-b27f-55ac12abcc88.mov
=> [SM-595] add project sort to secrets list

bitwarden_license/bit-web/src/app/secrets-manager/shared/access-policies/access-selector.component.ts
```
```
Items in the access selector multi-select should be sorted alphabetically.
- **bitwarden_license/bit-web/src/app/secrets-manager/shared/access-policies/access-selector.component.ts:** Add `localeCompare` for `SelectItemView.listName`
=> [SM-584] sort access select items

bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/service-accounts-list.component.html, bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/service-accounts-list.component.ts
```
```
Add ability to the table to sort the Service Account List by name or last revision date. By default sort by name alphabetically (ascending).
There is overlap with this PR, but the conflicts should be minimal, regardless which is merged first.
https://bitwarden.atlassian.net/browse/SM-586
=> SM-585: Table Sort for Service Account List

bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-export.component.ts, bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-import.component.html
```
```
Update import / export format text to "Bitwarden (json)" to make it more clear to the user what format we are allowing for import / export currently.
=> SM-569: Update Import / Export Format Text

bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/dialog/service-account-dialog.component.html, bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/dialog/service-account-dialog.component.ts
```
```
Remove access selector from create service account to match updated designs.
=> [SM-605] Remove access from create service account

apps/web/src/app/layouts/product-switcher/product-switcher-content.component.html, apps/web/src/app/layouts/product-switcher/product-switcher-content.component.ts
```
```
- Added the new SM marketing site to the product switcher.
- Fixed a small styling issue.
- Product switcher marketing links now open in a new tab
=> [SM-608] update SM marketing link in product-switcher

bitwarden_license/bit-web/src/app/secrets-manager/overview/onboarding.component.html, bitwarden_license/bit-web/src/app/secrets-manager/overview/onboarding.component.ts, bitwarden_license/bit-web/src/app/secrets-manager/overview/onboarding.stories.ts, bitwarden_license/bit-web/src/app/secrets-manager/overview/overview.component.html, bitwarden_license/bit-web/src/app/secrets-manager/overview/overview.component.ts
```
```
- Reorder tasks to match Figma
- Hide “Create a secret” if there are no projects
- Always show the dismiss button
- **bitwarden_license/bit-web/src/app/secrets-manager/overview/overview.component.html:** Reorder tasks in template; hide tasks with `ngIf`
- **bitwarden_license/bit-web/src/app/secrets-manager/overview/overview.component.ts:** Update localStorage on dismiss 
- **bitwarden_license/bit-web/src/app/secrets-manager/overview/onboarding.component.html:** Always show dismiss button
- Ensure that all UI additions follow …
=> [SM-613] Misc Onboarding UX fixes

bitwarden_license/bit-web/src/app/secrets-manager/layout/layout.component.html
```
```
The sidenav now has a fixed position that scrolls independent of the main content.
https://user-images.githubusercontent.com/17113462/224081139-78a56d59-bf3e-4bfa-b071-d1e35855adbc.mov
=> [SM-365] make sidenav fixed

bitwarden_license/bit-web/src/app/secrets-manager/overview/overview.component.ts
```
```
Fixes onboarding persistence.
- **bitwarden_license/bit-web/src/app/secrets-manager/overview/overview.component.ts:** Removes a debug line that I left in on accident that wipes local storage.
=> [SM-630] fix onboarding persistence

bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-export.component.html, bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-export.component.ts
```
```
My recent [PR](https://github.com/bitwarden/clients/pull/4944) accidentally changed the file extension during export download. This PR fixes that bug.
=> SM-634: Fix file extension bug on export

apps/web/src/app/organizations/members/components/member-dialog/member-dialog.component.html
```
```
Move External id field to the bottom of the dialog
=> [AC-1075] Member modal - custom permissions and external ID

apps/web/src/app/organizations/members/components/member-dialog/member-dialog.component.html
```
```
Update the help url again ...
=> [SM-521] Update help url again

bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-dialog.component.html
```
```
Fixes the spinner background color to match its container.
=> [SM-470] update spinner bg color

bitwarden_license/bit-web/src/app/secrets-manager/overview/overview.component.html
```
```
Update link for "Download Secrets Manager CLI"
=> [SM-533] update CLI download link

apps/web/src/app/organizations/members/components/member-dialog/member-dialog.component.html
```
```
Update the help link a third time.
=> [SM-521] Help link - third times the charm

apps/web/src/app/vault/individual-vault/bulk-action-dialogs/bulk-delete-dialog/bulk-delete-dialog.component.ts, apps/web/src/app/vault/org-vault/vault-header/vault-header.component.ts, apps/web/src/app/vault/org-vault/vault-items.component.ts
```
```
We were only checking for the Delete Assigned Collections permission in the organization vault when a user tried to delete a collection. This allows users with Delete Any Collections permissions to delete them as well.
=> [AC-1110] allow members with Delete Any Collection to delete collections

libs/angular/src/auth/components/change-password.component.ts
```
```
Fix multiple warnings from showing when the new master password chosen is both weak and breached.
=> [PM-1440] Fix showing multiple warnings

apps/web/config/cloud.json
```
```
The purpose of this PR is to set the `secretsManager` flag to true for the cloud.json config.
- apps/web/config/cloud.json
Set secrets manager flag to true.
=> [SM-661] Set secretsManager flag to true for cloud

apps/web/src/locales/en/messages.json, bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/access/access-list.component.html, bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/access/dialogs/access-token-create-dialog.component.html, bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/access/dialogs/access-token-dialog.component.html, bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/service-account.component.html
```
```
Change create access token verbiage to new access token.
=> [SM-626] Change create access token to new access token

libs/common/src/models/domain/send.ts, libs/common/src/services/send/send.service.ts
```
```
Fix sends list being null in mv3 version of browser extension.
- **libs/common/src/models/domain/send.ts:** Fix serialization issues
- **libs/common/src/services/send/send.service.ts:** Remove call that was setting decrypted sends to null
=> [PM-1347] Fix send key serialization

.github/workflows/build-web.yml
```
```
Switch back from `master` tag to `dev` tag for self-host docker images
- **.github/workflows/build-web.yml:** Add in `master` branch check and rename tag
=> Rename 'master' docker tag to 'dev'

.github/DISCUSSION_TEMPLATE/secrets-manager.yml
Create template for discussion topics for Secrets Manager
=> Create Secrets Manager discussion template

.github/DISCUSSION_TEMPLATE/password-manager.yml
Fix Github discussion template for Password Manager
=> Update Github discussion template

.github/CODEOWNERS
> Update `CODEOWNERS` file with `admin-console` and `billing` teams
- **.github/CODEOWNERS**: Added `admin-console` and `billing` team domains
=> [AC-1202] Update codeowners file 

libs/common/spec/services/export.service.spec.ts
```
```
Fix broken tests introduced by #4479
=> Fix broken export spec

.github/workflows/version-bump.yml
```
```
Add the option to bump all client's versions at once.
- **.github/workflows/version-bump.yml:** 
=> [DEVOPS-1326] Add all option for version bump workflow

.github/workflows/version-auto-bump.yml, .github/workflows/version-bump.yml
```
```
Call to GitHub API to trigger version bump workflow didn't work. Use workflow_call trigger instead.
- **.github/workflows/version-auto-bump.yml:** Replace call to GitHub API to workflow call with workflow_call trigger instead
- **.github/workflows/version-bump.yml:** Add workflow call trigger
=> Fix desktop autobump workflow

apps/web/src/locales/en/messages.json, bitwarden_license/bit-web/src/app/admin-console/policies/activate-autofill.component.ts
```
```
Update the autofill on page load policy copy:
* should refer to autofill **on** page load, not autofill **with** page load
* should refer to this as just one setting, not setting**s**
Update i18n strings.
=> [AC-1233] Fix description of auto-fill on page load policy

bitwarden_license/bit-web/src/app/secrets-manager/projects/project/project-secrets.component.html
```
```
The purpose of this PR is to fix the spinner on the project -> secrets tab.
- bitwarden_license/bit-web/src/app/secrets-manager/projects/project/project-secrets.component.html
Add a `<ng-container>` to wait for both async pipes to finish.
https://user-images.githubusercontent.com/43214426/230648587-40b82b8b-c54a-4252-800e-63861a52b2d7.mov
https://user-images.githubusercontent.com/43214426/230648611-44e895c0-87dd-4001-a475-e9e7bbda35f9.mov …
=> Fix spinner

apps/browser/src/popup/services/in-popup-services.module.ts
```
```
Fixes the lock action not having its message sent to the foreground app component. 
- **apps/browser/src/popup/services/in-popup-services.module.ts:** Switch to Combined messaging service so the messages sent by `VaultTimeoutService` has it's messages sent to the popup and the background.
=> Fix Lock Action

libs/angular/src/auth/components/lock.component.ts
```
```
Introduce a boolean parameter to prevent the `lock.component.ts` from attempting to evaluate an empty master password when a user unlocks with biometrics/PIN.
- **lock.component.ts:** Add `evaluatePasswordAfterUnlock` parameter to `doContinue` and `setKeyAndContinue` private methods, so that the master password is only evaluated when performing an unlock with password (not PIN or biometrics). 
=> [AC-1343] Fix incorrect update weak master password prompt on vault unlock

apps/desktop/src/models/native-messaging/encrypted-message-responses/message-response-data.ts, apps/desktop/src/models/native-messaging/index.ts, apps/desktop/src/services/encrypted-message-handler.service.ts
```
```
Fix model name that was uncovered to be a duplicate.
- **apps/desktop/src/models/native-messaging/encrypted-message-responses/message-response-data.ts:** Rename EncyptedMessageResponse to MessageResponseData, which is more fitting.
- **apps/desktop/src/models/native-messaging/index.ts:** Update file path
- **apps/desktop/src/services/encrypted-message-handler.service.ts:** Import import
=> Rename duplicate model more appropriately

apps/web/src/app/common/base.accept.component.ts, apps/web/src/auth/accept-emergency.component.ts, apps/web/src/auth/sso.component.ts, apps/web/src/auth/two-factor.component.ts, libs/angular/src/auth/components/sso.component.ts, libs/angular/src/auth/components/two-factor.component.ts, libs/common/src/abstractions/state.service.ts, libs/common/src/models/domain/global-state.ts, libs/common/src/services/state.service.ts
```
```
While going through an emergency invite flow, if a user has to login using SSO their browser will redirect away from Bitwarden to their IdP. This causes us to lose the previous url we have in memory, the emergency access url. 
In order to save the invitation during the SSO login process, this PR saves the SSO invitation to state and checks for the existence of it after an SSO login to complete the registration.
Note that this will accept the invitation after authentication, but before the user has unlocked their vault.
- **apps/web/src/app/common/base.accept.component.ts:** refactor observable to remove linter escapes
- **apps/web/src/auth/accept-emergency.component.ts:** set and clear emergency access invitation
- **apps/web/src/auth/sso.component.ts:** redirect to emergency …
=> [PM-687] emergency access invite lost during sso

bitwarden_license/bit-web/src/app/secrets-manager/projects/project/project.component.ts
```
```
Fixing merge conflict, changing handleError to return ProjectView instead of deprecated ProjectPermissionDetailView
changing handleError function on **project.component.ts** to return ProjectView instead of deprecated ProjectPermissionDetailView
=> [SM-602] Fixing merge conflict, changing handleError to return ProjectView instead of deprecated ProjectPermissionDetailView

apps/browser/src/vault/popup/components/action-buttons.component.ts, apps/web/src/app/vault/individual-vault/add-edit.component.ts, apps/web/src/app/vault/individual-vault/vault.component.ts, apps/web/src/app/vault/org-vault/vault.component.ts, libs/angular/src/vault/components/view.component.ts
```
```
When copying the password the wrong EventType was sent.
- **vault.component.ts and add-edit.component.ts:** Sending the `Cipher_ClientCopiedPassword` EventType when copying a password
=> [PM-730] Corrected EventType when copying password

.github/CODEOWNERS
```
```
Fixed 2 paths for tools code ownership
- **.github/CODEOWNERS:** Removed the app part fro browser and cli
=> CODEOWNERS: Fixed 2 paths for tools code ownership

bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-dialog.component.ts
```
```
The purpose of this PR is to correctly clear validators on the `newProjectName` form
- bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-dialog.component.ts
Swap to targeting the specific form control.
=> [SM-751] Fix validation clearing on secret dialog

apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.ts, apps/web/src/app/admin-console/organizations/shared/components/collection-dialog/collection-dialog.component.ts, apps/web/src/app/tools/import-export/dialog/import-success-dialog.component.ts, apps/web/src/app/vault/individual-vault/bulk-action-dialogs/bulk-delete-dialog/bulk-delete-dialog.component.ts, apps/web/src/app/vault/individual-vault/bulk-action-dialogs/bulk-move-dialog/bulk-move-dialog.component.ts, apps/web/src/app/vault/individual-vault/bulk-action-dialogs/bulk-restore-dialog/bulk-restore-dialog.component.ts, apps/web/src/app/vault/individual-vault/bulk-action-dialogs/bulk-share-dialog/bulk-share-dialog.component.ts, bitwarden_license/bit-web/src/app/admin-console/organizations/manage/domain-verification/domain-add-edit-dialog/domain-add-edit-dialog.component.ts, bitwarden_license/bit-web/src/app/secrets-manager/projects/dialog/project-delete-dialog.component.ts, bitwarden_license/bit-web/src/app/secrets-manager/projects/dialog/project-dialog.component.ts, bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-delete.component.ts, bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-dialog.component.ts, bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/access/dialogs/access-token-create-dialog.component.ts, bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/access/dialogs/access-token-dialog.component.ts, bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/dialog/service-account-delete-dialog.component.ts, bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/dialog/service-account-dialog.component.ts, bitwarden_license/bit-web/src/app/secrets-manager/settings/dialog/sm-import-error-dialog.component.ts, bitwarden_license/bit-web/src/app/secrets-manager/shared/access-policies/dialogs/access-removal-dialog.component.ts, bitwarden_license/bit-web/src/app/secrets-manager/shared/dialogs/bulk-status-dialog.component.ts, bitwarden_license/bit-web/src/app/secrets-manager/trash/dialog/secret-hard-delete.component.ts, bitwarden_license/bit-web/src/app/secrets-manager/trash/dialog/secret-restore.component.ts, libs/components/src/dialog/dialog.service.stories.ts, libs/components/src/dialog/simple-configurable-dialog/simple-configurable-dialog.component.ts, libs/components/src/dialog/simple-configurable-dialog/simple-configurable-dialog.service.stories.ts, libs/components/src/dialog/simple-dialog.service.stories.ts
```
```
Selectors aren’t required for dialog components. We should be able to safely remove all of them which ensures that we don’t accidentally include them in regular pages.
Remove `selector` for all dialogs.
=> [PM-1915] Remove selector for all dialogs

.github/renovate.json
```
```
Update the renovate config to better match the template. 
=> Update renovate config to match template

package.json
```
```
Seems npm can't retrieve the zone.js variable in the override for some reason. Explicitly specifying it seems to work and my hope is that renvovate will keep it in sync but that might be wishful thinking.
=> Explicitly specify zone.js version

apps/web/src/app/tools/import-export/dialog/import-success-dialog.component.html, libs/components/src/multi-select/scss/bw.theme.scss
```
```
Resolve two dialog defects.
- Import success dialog being small which cuts of the title.
- Ng-select appears behind the dialog.
=> [PM-2104] Resolve dialog defects

.github/renovate.json
```
```
Renovate upgraded typescript to a minor version. I believe this config will block it.
=> [Renovate] Disable major & minor typescript bumps

libs/components/src/banner/banner.stories.ts, libs/components/src/stories/banner-docs.stories.mdx
```
```
Change the banner buttons to use bitLink to better represent how they will be used.
=> [PM-2136] Change banner button to use bitLink

.github/renovate.json
```
```
Unblock renovate by temporarily ignoring `@types/koa-bodyparser`.
=> Disable koa-bodyparser from being updated by renovate

.prettierrc.json, libs/components/src/async-actions/in-forms.stories.mdx, libs/components/src/async-actions/overview.stories.mdx, libs/components/src/async-actions/standalone.stories.mdx, libs/components/src/form-field/form-field.stories.ts, libs/components/src/radio-button/radio-button.stories.ts, libs/components/src/stories/Introduction.stories.mdx, libs/components/src/stories/banner-docs.stories.mdx, libs/components/src/stories/button-docs.stories.mdx, libs/components/src/stories/colors.stories.mdx, libs/components/src/stories/forms-docs.stories.mdx, libs/components/src/stories/icons.stories.mdx, libs/components/src/stories/input-docs.stories.mdx, libs/components/src/stories/table-docs.stories.mdx
```
```
Rework some of the component library documentation.
=> Update CL documentation

.github/renovate.json
```
```
Add `cargo` and `github-actions` as enabled managers.
=> Enable renovate for github actions and cargo

.github/renovate.json
```
```
Seems we need to specify `matchManagers` for `manager` to be filled in correctly in `groupName`. Unfortunately it doesn't support wildcard.
=> Fix renovate branch name

.github/renovate.json
=> Use separate rules per manager

apps/web/src/app/vault/components/vault-items/vault-cipher-row.component.html, apps/web/src/app/vault/components/vault-items/vault-collection-row.component.html, apps/web/src/locales/en/messages.json
```
```
Add better titles to cipher and collection rows in the web vault.
- **apps/web/src/app/vault/components/vault-items/vault-cipher-row.component.html:** Add name to the hover text
- **apps/web/src/app/vault/components/vault-items/vault-collection-row.component.html:** Add hover text to collection rows
Before:
After:
=> Add more descriptive titles for web vault rows

apps/web/src/app/admin-console/organizations/manage/group-add-edit.component.html, apps/web/src/app/admin-console/organizations/shared/components/collection-dialog/collection-dialog.component.html
```
```
Change these two dialogs to large per design request.
=> [PM-2186] Change collection and group dialogs to large

.github/workflows/build-web.yml
```
```
Fix error in `Build Web` workflow
- **.github/workflows/build-web.yml:** Change publish branch name from `hotfix-rc` to `hotfix-rc-web`
=> Fix publish branches check

apps/web/src/app/tools/generator.component.ts, apps/web/src/app/tools/password-generator-history.component.html, libs/angular/src/tools/generator/components/password-generator-history.component.ts
```
```
Update the Password generator history to use Component Library on Web client
Update to use Component Library 
**Before:**
**After:**
=> [PM-2054] Updated Password Generator History to use Component Library on Web

apps/web/src/app/billing/organizations/organization-subscription-selfhost.component.html
```
```
Update the help link anchor tag to reference the re-written section title.
In response to: https://github.com/bitwarden/clients/pull/5101#discussion_r1194146629
=> [AC-358] Update help doc link

apps/desktop/src/app/app.component.ts, apps/web/src/app/app.component.ts, libs/common/src/abstractions/broadcaster.service.ts
```
```
Deprecate `BroadcasterService`. Please setup an observable in the appropriate service and subscribe to that instead.
=> Deprecated broadcaster

.github/renovate.json
```
```
These packages needs to be upgraded together.
=> Group jest packages

apps/browser/src/autofill/content/autofill.js
Be able to use autofill also for textareas. https://github.com/bitwarden/clients/issues/1966
- **https://github.com/mr-manuel/bitwarden_autofill_clients/commit/dbb7b6ec6d9e1a3700514d82cc8b00048480cd7b** Added textarea tag in order to use autofill also on textareas.
Accidentially deleted repo, old pull request: https://github.com/bitwarden/clients/pull/3192
=> [PS-1950] [PS-1211] Added autofill for textareas

libs/angular/src/auth/components/environment-selector.component.html
```
```
Hide EU environment on false flag.
=> [PM-2347]  Fix EU environment Browser and Desktop

libs/angular/src/auth/components/two-factor.component.ts
```
```
Fix hang for desktop and browser by removing `await` from `onSuccessfulLogin()` call as it was waiting for a full sync to finish before navigating to the vault which let the user see that the `loginTwoFactor` method had completed and the loading state of the component was "finished" even though it wasn't. Confirmed that the fix from PM-687 (see #5199) still works to allow an emergency contact to sign in via SSO after removing the await.
- **libs/angular/src/auth/components/two-factor.component.ts:** Remove await that was causing the hang.  …
=> Defect/PM-2373 - Fix desktop & browser hang after 2FA

apps/browser/src/background/main.background.ts, apps/browser/src/popup/services/services.module.ts, libs/angular/src/auth/components/environment-selector.component.ts, libs/angular/src/services/jslib-services.module.ts, libs/common/src/services/config/config.service.ts
```
```
UI updating inline with the selected environment.
Change Config service to subscribe to Environment url observable. When they change we need to force refresh new configs for that new environment.
=> [PM-2347] Refresh configs when environment urls change

libs/common/src/services/config/config.service.ts
```
```
Fix Firefox bug where environments screen wasn't closing.
Make config service unsubscribe from environment service observable.
https://github.com/bitwarden/clients/assets/4648522/3236e3a4-2b90-4692-9696-e4dab65f7425
=> [PM-2398] Fix firefox extension environments bug

apps/web/src/app/admin-console/organizations/members/components/reset-password.component.html, apps/web/src/app/admin-console/organizations/members/people.component.html, apps/web/src/app/admin-console/organizations/policies/reset-password.component.ts, apps/web/src/app/admin-console/organizations/users/enroll-master-password-reset.component.html, apps/web/src/app/core/event.service.ts, apps/web/src/app/vault/individual-vault/vault-filter/components/organization-options.component.html, apps/web/src/locales/en/messages.json, bitwarden_license/bit-web/src/app/auth/sso/sso.component.html
```
```
Change the "Master Password Reset" policy name to "Account recovery administration" and update all references to the new name
- **apps/web/src/app/admin-console/organizations/members/components/reset-password.component.html:** Under organization management updated the "reset password" model title to "recover account"
- **apps/web/src/app/admin-console/organizations/members/people.component.html:** Updated the action text to "recover account"
- **apps/web/src/app/core/event.service.ts:** Changed the EventType.User_UpdatedTempPassword to use the message updatedTempPassword
- **apps/web/src/locales/en/messages.json:** Updated existing "password reset" policy texts to "account recovery"
- If this …
=> [AC-1077] Update "Master Password Reset" policy copy

apps/web/src/app/admin-console/organizations/policies/policies.component.ts, apps/web/src/app/app.component.ts, apps/web/src/app/core/index.ts
> Update descoped service file from core barrel file
- **core/index.ts**: Update barrel file by removing descoped service class
=> [PM-2491] Fix core barrel file

apps/web/src/app/admin-console/organizations/users/organization-user.module.ts, apps/web/src/app/billing/organizations/organization-billing.module.ts
```
```
Fix missing imports of the `UserVerificationModule`. The `<app-user-verification/>` component was moved to its own module and was not being imported in the `organization-user.module.ts` and `organization-billing.module.ts` modules which caused unexpected exceptions.
=> [AC-1431] Add missing UserVerificationModule import

libs/components/src/dialog/simple-configurable-dialog/simple-configurable-dialog.service.stories.ts
```
```
Fix simple configurable dialog stories not working after the storybook 7 migration.
=> Fix simple configurable dialog stories

.github/CODEOWNERS
```
```
Set platform as codeowner for components
=> Set platform as codeowner for components

apps/web/src/app/tools/import-export/import.component.html
```
```
Replace the importer select dropwdown with the [searchable select from the CL](https://components.bitwarden.com/?path=/docs/component-library-form-select--docs).
- **apps/web/src/app/tools/import-export/import.component.html:** Use CL components for importer selection
**BEFORE:**
**AFTER:**
=> [PM-1435] Allow users to search Import file type select

libs/common/src/tools/generator/username/email-forwarders/forward-email-forwarder.ts
```
```
Fix build that broke by merging https://github.com/bitwarden/clients/pull/4809
A path to an import had changed
- **libs/common/src/tools/generator/username/email-forwarders/forward-email-forwarder.ts:** Fix import of `misc/utils`
=> Fix broken import of misc/utils

apps/web/src/app/vault/individual-vault/vault.component.ts
```
```
Remove feature flag conditionals for `low kdf iteration warning`
Removed logic to get `DisplayLowKdfIterationWarningFlag` value.
=> [PM-2478] Removed feature flag logic for low kdf iteration

.github/workflows/deploy-eu-prod-web.yml
```
- [X Build/deploy pipeline (DevOps)
```
This PR adds a branch input to the `Deploy Web EU-PRD` workflow.
- **.github/workflows/deploy-eu-prod-web.yml:** Input added for branch to workflow
=> Add branch input to Deploy Web EU-PRD workflow

apps/web/config/euprd.json
```
```
Trying a different top level domain to test the DNS change process
- **apps/web/config/euprd.json:** update the `notifications` and `scim` URLs
=> Devops 1421 test dns change take two

.github/workflows/deploy-eu-prod-web.yml
```
```
This PR adds a step to empty the `$web` container in the `EU-PRD` Web Storage Account.
- **.github/workflows/deploy-eu-prod-web.yml:** Add step to empty `$web` Storage Account. Remove Storage Account name as it isn't necessary with connection string.
=> Add step to empty container in Storage Container

.github/CODEOWNERS
```
```
Add a default code owner to all files. Their job will be to advocate for adding an owner to unowned files.
=> Add default code owners

.github/CODEOWNERS
```
```
Fix formatting issue in code owners introduced in #5687 
=> Fix code owners format issue

bitwarden_license/bit-web/src/app/secrets-manager/projects/project/project-people.component.html, bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/people/service-account-people.component.html
Change the column header from "Group/User" to "Name" in the `project-people` and `service-account-people` components.
```
```
Use "Name" as the column header instead of "Group/User"
Re-used the existing "name" prompt.
=> [SM-822] i18n changes to SM project-people and service-account-people tables

apps/browser/src/background/main.background.ts
```
```
Fix adding items on browser.
- **main.background.ts:** Reordered service creation so every service is defined when called.
=> [PM-2791] Fix adding items on browser

.github/CODEOWNERS
```
```
This PR allows the DevOps team to update and approve PRs to the Web client configuration and also to any GitHub workflows in the repository.
- **.github/CODEOWNERS:** Update as described above.
=> DEVOPS-1449 - Add DevOps to CODEOWNERS

.github/workflows/build-web.yml, .github/workflows/deploy-eu-qa-web.yml, apps/web/config/euprd.json, apps/web/config/euqa.json, apps/web/package.json
```
```
This PR adds the configuration logic necessary for the `EU QA` Web artifact to be built and deployed.
- **.github/workflows/build-web.yml:** Add `EU QA` build command to `Build Web` workflow
- **.github/workflows/deploy-eu-qa-web.yml:** Add `Deploy Web to EU-QA Cloud` workflow
- **apps/web/config/euprd.json:** Update the `EU-PRD` config to point to `icons.bitwarden.eu` which is a CNAME to `icons.bitwarden.net`
- **apps/web/config/euqa.json:** Add the `EU QA` config file
- **apps/web/package.json:** Add the `EU QA` build command …
=> DEVOPS-1396 - Add EU QA Web client information

.github/workflows/auto-branch-updater.yml
```
```
Add a support workflow for the hardcoded URL hack for testing `bitwarden.net`
- **.github/workflows/auto-branch-updater.yml:** Add a workflow to keep some branches up to date with `master` and `rc` with the added URL hack
=> Add a branch updater workflow for the hardcoded URL hack

.github/workflows/auto-branch-updater.yml
```
```
Add in bug fixes for the new Auto Branch Updater workflow.
- **.github/workflows/auto-branch-updater.yml:** Fix Actions git setup & testing cleanup
=> [DEVOPS-1421] fix auto branch updater

package.json
```
```
Gulp's dependency `replacestream` is owned by an unregistered email domain. Pinning this dependency to its current version to avoid update potential update attacks in the future.
Long term improvement is to move off of Gulp.
=> Override orphaned dependency version

.github/workflows/brew-bump-cli.yml
```
```
This PR removes/updates incorrect inputs to the `action-homebrew-bump-formula` action.
- **.github/workflows/brew-bump-cli.yml:** Change `cask` input to `formula` to match new action requirements. Remove `dryrun` as it's no longer an input.
=> DEVOPS-1400 - Fix input error in 'Update Homebrew formula' step

.github/workflows/crowdin-pull.yml
```
```
This PR updates the `crowdin` action in our `Crowdin Pull` workflow.
- **.github/workflows/crowdin-pull.yml:** Update hash of `bitwarden/gh-actions/crowdin`.
=> DEVOPS-1400 - Update crowdin action hash

apps/web/src/app/admin-console/organizations/members/components/bulk/bulk-enable-sm-dialog.component.html, apps/web/src/app/admin-console/organizations/members/components/bulk/bulk-enable-sm-dialog.component.ts, apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.html, apps/web/src/app/admin-console/organizations/members/people.component.html, apps/web/src/locales/af/messages.json, apps/web/src/locales/en/messages.json
```
```
Removes copy with "enable" from the SM bulk access dialog
=> [SM-839] remove enable from copy

apps/web/src/app/core/event.service.ts, apps/web/src/locales/en/messages.json, libs/common/src/enums/event-type.enum.ts
```
```
Add human readable text for the new events added in bitwarden/server#3046. 
- **apps/web/src/app/core/event.service.ts:** Add code for getting localized messages for new events.
- **apps/web/src/locales/en/messages.json:** English messages for new events.
- **libs/common/src/enums/event-type.enum.ts:** Added equivalent event enum entries for https://github.com/bitwarden/server/pull/3046/files#diff-b712119acdb072c1c9be78f0c97afecb4285f60be6dc006cac03c29b0813cee3 …
=> [PM-1338] `AuthRequest` Event Logs

.github/workflows/version-auto-bump.yml
```
```
This PR should fix the errors in the `Version Auto Bump` workflow when calling the `version-bump.yml` workflow.
- **.github/workflows/version-auto-bump.yml:** Moved workflow call to top level job instead of inside of another job as a step.
=> DEVOPS-1400 - Fix Version Auto Bump workflow

.github/workflows/test.yml
```
```
This PR updates the `test` workflow to remove the `action-rs/toolchain` action since it's running a deprecated version of Node (`node12`) and it is not needed as the latest `stable` version of `rustup` is included in the GitHub runner image.
- **.github/workflows/test.yml:** Update runner OS of `test` job to `ubuntu-22.04`. Add `rustup` version check. Remove `action-rs/toolchain` action.
=> DEVOPS-1400 - Fix Test Workflow

.github/workflows/release-cli.yml
```
```
This PR updates the action hash for the Snapcraft action to remove the `Node 12` warning in GitHub Actions.
- **.github/workflows/release-cli.yml:** Update hash to latest version.
=> DEVOPS-1400 - Release CLI Workflow - Fix Snapcraft Action Version

.github/CODEOWNERS
```
```
Fix autofill codeowners
=> Fix autofill codeowners

.github/CODEOWNERS
```
```
This PR adds entries for the files that are changed when bumping the client versions for release. This allows DevOps to review Version Bump PRs.
- **.github/CODEOWNERS:** Update file to allow for Version Bump reviews by DevOps.
=> Update CODEOWNERS file for Releases

.github/CODEOWNERS
```
```
team-leads-eng got asked for a review on https://github.com/bitwarden/clients/pull/5810/ which was caused by `apps/web/src/app/auth/login/login-decryption-options/login-decryption-options.component.ts`.
Realized the path in the CODEOWNERS must be wrong.
With https://github.com/bitwarden/clients/pull/5336 all files got moved to `apps/web/src/app/auth`, but CODEOWNERS still pointed to `apps/web/src/auth`
- **.github/CODEOWNERS:** Update path …
=> Update web-path for team-auth-dev

.github/workflows/release-cli.yml
```
```
This PR adds the default push source for Chocolatey.  It is now required in order to release.
- **.github/workflows/release-cli.yml:** Add default push source for Chocolatey
=> Release CLI Workflow - Add default push location for Chocolatey

.github/workflows/build-browser.yml
=> Disable mv3 artifacts

libs/common/src/platform/abstractions/environment.service.ts, libs/common/src/platform/services/environment.service.ts
```
```
Remove unused method in the environment service.
=> Remove unused method

bitwarden_license/bit-web/src/app/auth/sso/sso.component.ts
```
```
Removed restriction on member decryption options to prevent customers from using TDE if they are self-hosted.
- **sso.component.ts:** Removed self-hosted restriction.
=> [AC-1523] Removed self-hosted check from TDE SSO config

apps/desktop/src/platform/services/electron-state.service.ts
=> TDE - fix buffer null error

apps/browser/src/auth/popup/login-decryption-options/login-decryption-options.component.ts, apps/desktop/src/auth/login/login-decryption-options/login-decryption-options.component.ts, apps/web/src/app/auth/login/login-decryption-options/login-decryption-options.component.html, apps/web/src/app/auth/login/login-decryption-options/login-decryption-options.component.ts, libs/angular/src/auth/components/base-login-decryption-options.component.ts, libs/angular/src/services/jslib-services.module.ts, libs/common/src/auth/abstractions/password-reset-enrollment.service.abstraction.ts, libs/common/src/auth/services/password-reset-enrollment.service.implementation.spec.ts, libs/common/src/auth/services/password-reset-enrollment.service.implementation.ts
=> [PM-3143] Trusted device encryption: Refactor reset enroll service

apps/web/src/app/billing/organizations/organization-subscription-cloud.component.html
```
```
Hide "SM beta ending"  callout for free organizations
- **apps/web/src/app/billing/organizations/organization-subscription-cloud.component.html:** Added a && !userOrg.isFreeOrg to make sure that the message only show for non-free organizations
=> [AC 1551] Hide "SM beta ending" callout for free orgs

libs/common/src/auth/services/auth.service.ts, libs/common/src/platform/abstractions/crypto.service.ts, libs/common/src/platform/services/crypto.service.ts
```
```
Fix account switching in desktop when one user has never lock turned on and one account has biometrics turned on.
- **libs/common/src/auth/services/auth.service.ts:** Pass in `userId` to the `setUserKey` method so that it can work with account switching.
- **libs/common/src/platform/abstractions/crypto.service.ts:** Add `userId` param for methods that already have documentation that they accept `userId`. 
- **libs/common/src/platform/services/crypto.service.ts:** Pass `userId` into methods that take it to help facilitate account switching. …
=> Pass userId Through Inner Methods

apps/web/config/euprd.json
```
```
Add correct Production payment configs for the EU
- **apps/web/config/euprd.json:** Add strip, braintree, and paypal Ids
=> Update EU Prod config

bitwarden_license/bit-web/src/app/secrets-manager/shared/projects-list.component.html
```
```
Rearranging the order of items inside the project drop down to match secrets drop down.
UI changes only.
bitwarden_license/bit-web/src/app/secrets-manager/shared/projects-list.component.html - moving code block up a few lines
=> 647 - rearrange drop downs

apps/web/config/base.json, apps/web/config/development.json, apps/web/config/qa.json, apps/web/config/selfhosted.json
```
```
Turned item level encryption on.
=> Individual vault items activate encryption

apps/browser/src/auth/background/service-factories/user-verification-api-service.factory.ts, apps/browser/src/auth/background/service-factories/user-verification-service.factory.ts, apps/browser/src/autofill/background/service_factories/autofill-service.factory.ts, apps/browser/src/autofill/browser/cipher-context-menu-handler.spec.ts, apps/browser/src/autofill/browser/cipher-context-menu-handler.ts, apps/browser/src/autofill/services/autofill.service.ts, apps/browser/src/background/main.background.ts
```
```
Fix autofill by shortcut or context menu not working when users do not have a master password (uses key connector or TDE).
For other areas, we use the Password Reprompt service, but that was a lot of extra overhead to add to the browser background because it uses ModalService. I went back and forth on the correct way to approach this but decided to use the UserVerificationService here instead.
**Auth:**
- **apps/browser/src/auth/background/service-factories/user-verification-api-service.factory.ts:** and **apps/browser/src/auth/background/service-factories/user-verification-service.factory.ts** Add service factories for user verification services.
**Autofill:**
- **apps/browser/src/autofill/background/service_factories/autofill-service.factory.ts:** Inject UserVerification service …
=> [PM-3101] Fix autofill items not working for users without a master password

apps/desktop/src/app/app.component.ts
```
```
Removed buttons added for testing that were accidentally left in `app.component.ts`.
- **app.component.ts:** Removed buttons and `goTo()` method that they used.
=> [PM-3186] Removed buttons used for testing

apps/web/src/app/tools/import-export/import.component.html, apps/web/src/app/tools/import-export/import.component.ts, apps/web/src/locales/en/messages.json
```
```
Some updates requested by product/design
- **Display select folder/collection in targetSelector -** 65ed88f
- Filter the no-folder entry from the folderViews-observable
- Add labels for the targetSelector placeholders.ext:** 
- **Update importTargetHint and remove importTargetOrgHint -** 1d29f74
- **Update language on importUnassignedItemsError -** 7f2bfec
- **Add help icon with link to the import documentation-** 2806e3a
Individual vault
Organizational vault
Individual vault
Organizational vault
- Ensure that all UI additions …
=> [AC-1549] Import page design updates

libs/angular/src/services/jslib-services.module.ts
```
```
Added missing dependency to `UserVerificationService`.  The `StateService` was added as a dependency but not added to `jslib-services`.  This caused incorrect bindings in the constructor.
- **jslib-service.modile.ts:** Added `StateServiceAbstraction` dependency.
=> [PM-3291] Add missing dependency to UserVerificationService on web

libs/common/src/auth/services/devices-api.service.implementation.ts
```
```
Without the slash this results with a 404 on non local environments, TIL 🤷. 
- **libs/common/src/auth/services/devices-api.service.implementation.ts:** Add slash
=> Add Missing Slash

libs/common/src/auth/login-strategies/login.strategy.ts, libs/common/src/platform/models/domain/account.ts, libs/common/src/platform/services/state.service.ts
```
```
- toJSON isn't being called by ElectronStorageService
- Force it's conversion to JSON earlier so it happens for all storage methods
- **libs/common/src/auth/login-strategies/login.strategy.ts:** Save AdminAuthRequestStorable on Account in it's JSON friendly form.
- **libs/common/src/platform/services/state.service.ts:** When saving an AdminAuthRequestStorable force it into it's JSON friendly form.
=> [PM-3262][PM-3261] Fix AdminAuthRequest Serialization on Desktop

libs/angular/src/auth/components/login-with-device.component.ts
```
```
Fix issue where we were incorrectly calling `setRememberEmailValues` in the `AdminAuthRequest` state. There is no need to do this as the email is already saved to state. 
- By calling this method, we would actually overwrite the already saved email with `null` as the user's choice to remember email wasn't persisted through SSO on the `LoginService`
- **libs/angular/src/auth/components/login-with-device.component.ts** - Only call `setRememberEmailValues` on standard auth request state. 
- Ensure that all UI additions follow …
=> TDE - Admin Auth Approval Flow - Fix remember email not saving user email

apps/web/src/locales/en/messages.json, libs/angular/src/tools/export/components/export-scope-callout.component.ts
```
```
Update copy related to the organization vault export scope callout.
=> [AC-1361] Update copy for organization vault export scope call out

libs/common/src/services/vault-timeout/vault-timeout-settings.service.spec.ts
```
```
Fixed tests that were referencing a method that no longer exists on the state service.  `GetUserKeyPin` was renamed to `GetPinEncryptedUserKey`.
- **vault-timeout-settings.service.spec.ts** Updated to use the renamed methods in the tests.
=> Updated tests to use renamed method on state service

apps/web/src/app/settings/change-email.component.ts
```
```
On email change we were assuming that the `masterKey` existed.  I changed this to use the new `getOrDeriveMasterKey()` method on `cryptoService` that will derive the key if it doesn't exist.
- **change-email.component.ts:** Added call to `getOrDeriveMasterKey()`.
=> [PM-3374] Handle missing master key on email change

apps/desktop/src/app/accounts/settings.component.ts, apps/desktop/src/app/app.component.ts
```
```
The existence of having a PIN or Biometrics set up is an indicator for if an account without a MP and with TDE is able to lock their account. Since we give that option in the menu bar for desktop we have to tell the menu to update when either of these settings are added/removed.
- **apps/desktop/src/app/accounts/settings.component.ts:** Call `redrawMenu` action after each action has completed.
- **apps/desktop/src/app/app.component.ts:** Add listener for `redrawMenu` message to update the menu using existing method.
- Ensure …
=> [PM-3330] Force Update to Lockable Accounts on PIN/Biometric Update

apps/browser/src/auth/popup/sso.component.ts, apps/browser/src/auth/popup/two-factor.component.ts, apps/desktop/src/auth/sso.component.ts, apps/desktop/src/auth/two-factor.component.ts, libs/angular/src/auth/components/sso.component.ts, libs/angular/src/auth/components/two-factor.component.ts
```
```
To resolve issue [PM-3351](https://bitwarden.atlassian.net/browse/PM-3351) where, post TDE login, the Browser & Desktop clients did not have any logic to kick off a sync. I mirrored the existing `onSuccessfulLogin` logic to create a new `onSuccessfulLoginTde` callback. However, in order to avoid a hang in all scenarios waiting for the full sync to fire and complete, I removed awaits from the  `onSuccessfulLogin` and `onSuccessfulLoginTde` callbacks. 
- Note: as part of this, I also refactored the 2FA component to place the `onSuccessfulLogin` within the standard, non TDE success path (matching the SSO component) 
- I also cleaned up some unnecessary calls to the `this.loginService.clearValues();`
- This worked on web, browser, and desktop in all tested scenarios:
- Login with 2FA …
=> Auth / pm 3351 / TDE Login - Browser & Desktop vault sync issue fix

libs/components/src/dialog/dialog/dialog.component.html
```
- [X ] Other
```
Update dialog header styling to be more readable and consistent with Figma.
- **/clients/libs/components/src/dialog/dialog/dialog.component.html:** removed tw-uppercase class from header text
=> [CL-114] Remove all caps styling from dialogs

apps/browser/src/platform/services/browser-crypto.service.ts
```
```
We shouldn't be including an Auto key check when using biometrics on browser. This looks for the User Key provided by desktop _only_, excluding the Auto key check from before.
=> skip auto key check when using biometrics on browser

apps/browser/src/autofill/browser/cipher-context-menu-handler.spec.ts, apps/browser/src/autofill/browser/cipher-context-menu-handler.ts, apps/browser/src/autofill/services/autofill.service.ts
```
```
Resolve incorrect merge conflict fixes. 
=> TDE + Autofill - fix merge conflict fixes

.github/workflows/release-web.yml
```
```
This PR updates the `Release Web` workflow with new runner OS versions and a minor job name change for clarity.
- **.github/workflows/release-web.yml:** Update runner versions and update `ghpages-deploy` job name to not induce panic when running job before maintenance window starts.
=> Update Release Web workflow

apps/browser/src/background/nativeMessaging.background.ts, apps/browser/src/safari/safari/SafariWebExtensionHandler.swift, apps/desktop/src/platform/services/electron-crypto.service.ts, apps/desktop/src/services/native-messaging.service.ts, libs/common/src/platform/services/crypto.service.ts, libs/common/src/services/vault-timeout/vault-timeout.service.ts
```
```
Added comments for backward compatibility follow-up for Trusted Device Encryption.  All of the tickets are captured in the https://bitwarden.atlassian.net/browse/PM-3471 Epic, which has a due date of November 11, 2023 - the day of `rc` cut for the `2023.11` release.
- **nativeMessaging.background.ts:** Added backward compatibility comments.
- **nativeMessaging.service.ts:** Added backward compatibility comments.
- **SafariWebExtensionHandler.swift:** Added backward compatibility comments.
- **crypto.service.ts:** Added backward compatibility comments.
- **electron-crypto.service.ts:** Added backward compatibility comments.
- **vault-timeout.service.ts:** Added backward compatibility comments.
- …
=> Added comments for backward compatibility removal.

apps/web/src/locales/en/messages.json, bitwarden_license/bit-web/src/app/auth/sso/sso.component.html
```
```
We are making the RequireSSO policy a prerequisite for enabling TDE. This is because allowing users to use Login with Device puts users in a bad state that was unanticipated during implementation.
This change in policy application has been discussed and approved by Product as well.
- **sso.component.html:** Updated message to include reference to new policy.
- **messages.json:** Added new phrases.
=> [AC-1601] Updated warning TDE SSO config message to include new policy

apps/web/src/app/billing/organizations/organization-subscription-cloud.component.ts
```
```
Fix the dates on the "SM beta ending" callout. They should be:
* beta end date is 15 August (day of the SM GA release) - this is the date shown in the callout
* grace period end date is now 14 November - this is the end of the countdown
=> [AC-1598] Fix SM beta grace period dates

libs/components/src/table/table.mdx
```
- [X ] Other
```
The Design and Component Library team aligned on the behavior for interactive table cells today. This PR handles documenting this behavior in the Table docs in Storybook. 
- **clients/libs/components/src/table/table.mdx** added bullet about interactive elements in tables. 
=> Update table docs in Storybook

apps/desktop/desktop_native/Cargo.lock, apps/desktop/desktop_native/Cargo.toml
Reverts bitwarden/clients#5671
=> Revert "Update cargo minor"

libs/angular/src/services/jslib-services.module.ts
```
- x] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
```
Use useClass instead of useFactory https://github.com/bitwarden/clients/pull/5950#discussion_r1298623343
=> Use useClass instead of useFactory

.eslintrc.json, .github/CODEOWNERS, .github/whitelist-capital-letters.txt, apps/browser/tsconfig.json, apps/desktop/tsconfig.json, apps/web/tsconfig.json, bitwarden_license/bit-web/tsconfig.json, jest.config.js, libs/shared/tsconfig.libs.json, libs/vault/README.md, libs/vault/jest.config.js, libs/vault/package.json, libs/vault/test.setup.ts, libs/vault/tsconfig.json, libs/vault/tsconfig.spec.json, package-lock.json, tailwind.config.js, tsconfig.eslint.json, tsconfig.json
```
```
This PR adds a new lib @bitwarden/vault, which will contain cross client code from the Vault team.
Copied code changes from https://github.com/bitwarden/clients/pull/5906
- Scaffold new files in `libs/auth`
- src/index.ts
- README.md
- jest.config.js
- package.json
- test.setup.sh
- tsconfig.json
- tsconfig.spec.json
- Update other tsconfigs
- apps/browser/tsconfig.json
- apps/desktop/tsconfig.json
- apps/web/tsconfig.json 
- bitwarden_license/bit-web/tsconfig.json
- libs/shared/tsconfig.libs.json
- tsconfig.json
- Update .github
- .github/CODEOWNERS
- .github/whitelist-capital-letters.txt
- Update other global config
- .eslintrc.json
- tsconfig.eslint.json
- jest.config.js
- package-lock.json
- tailwind.config.js   …
=> [PM-3587] create @bitwarden/vault lib

apps/browser/src/popup/app-routing.module.ts
=> PM-3590 - Browser - redirect to current tab on logged in 

libs/components/src/multi-select/multi-select.component.html, libs/components/src/multi-select/multi-select.component.ts
```
- [ x ] New feature development
```
Multi Select drop down needs to select on enter not on tab.
libs/components/src/multi-select/multi-select.component.html - removing the select on tab functionality
libs/components/src/multi-select/multi-select.component.ts - removing logic that prevents enter from selecting
=> [SM-721] Project drop downs add on enter not on tab

.github/workflows/build-cli.yml, .github/workflows/release-desktop.yml
```
```
This PR updates the runner images to `ubuntu-22.04`.
- **.github/workflows/release-desktop.yml:** Update runners from `ubuntu-20.04` to `ubuntu-22.04`.
- **.github/workflows/build-cli.yml:** Update runners from `ubuntu-20.04` to `ubuntu-22.04`.
=> CLI/Release Desktop Workflow - Update runner to Ubuntu latest

.github/workflows/brew-bump-cli.yml, .github/workflows/brew-bump-desktop.yml, .github/workflows/release-desktop.yml, .github/workflows/version-auto-bump.yml, .github/workflows/version-bump.yml
```
```
- Clearing the warnings in the clients pipeline.
- **.github/workflows/brew-bump-cli.yml:** This change will create a new PR on `Homebrew-formula` repo, making our workflow to succeed 
- **.github/workflows/brew-bump-desktop.yml:** This change will create a new PR on `Homebrew-cask` repo, making our workflow to succeed 
- **.github/workflows/release-desktop.yml:** Update the `get-checksum` to use `GITHUB_OUTPUT`
- **.github/workflows/version-auto-bump.yml:** Remove the secret var passed to the `version bump` workflow
- **.github/workflows/version-bump.yml:** Remove the AZ KV passed to the 'on_worflow` it's not used.
- If this change requires a **documentation update** - notify the documentation …
=> [DEVOPS-1400] - UPDATE: fix all warnings in Clients workflow

apps/web/src/app/auth/trial-initiation/trial-initiation.component.ts, libs/common/src/models/request/reference-event.request.ts
```
```
Adding the session value to reference data on trial-initiation
=> [PM-3226] Adding session to ReferenceEventRequest

libs/common/src/vault/models/domain/cipher.ts
```
```
Added comment for future refactor, as requested in https://github.com/bitwarden/clients/pull/5623#discussion_r1312264421.
- **cipher.ts:** Added refactoring comment.
=> Added comment to Cipher for future refactoring

.github/workflows/version-auto-bump.yml, .github/workflows/version-bump.yml
```
```
This PR updates the way we call the `Version Bump` workflow.  Inputs have been changed to boolean values so that version bumps can be more flexible.
- **.github/workflows/version-auto-bump.yml:** Updated with new inputs and adds inheriting secrets to run properly.
- **.github/workflows/version-bump.yml:** Update inputs to booleans. Change logic to use the new input values and generate proper outputs for the PR.
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibil …
=> Update Version Bump workflow inputs

.github/workflows/build-browser.yml, .github/workflows/release-browser.yml
```
```
This change is to make is easier to troubleshoot build issues with Browser in the future.
- **.github/workflows/build-browser.yml:** Change runners to `ubuntu-22.04`. Update logic from `CMD` to `bash`. Update actions.
- **.github/workflows/release-browser.yml:** Change runners to `ubuntu-22.04` and update actions.
=> Browser Build/Release Workflows - Change runners to linux

libs/common/src/vault/models/domain/cipher.ts
```
```
In [this](https://github.com/bitwarden/clients/pull/5623#discussion_r1312264421) comment, @MGibson1 asked that we update the use of `null` from the `orgId` into `decrypt()` method, as the `decrypt()` will use the `encKey` if present (which it will be in all cases here) and ignore the `orgId` anyway.  See [this](https://github.com/bitwarden/clients/blob/6f82a9914ba9e8935f7d55865269b44f18afee9c/libs/common/src/platform/models/domain/enc-string.ts#L146) for where the key is checked and `orgId` is only used when `key` is null.
The alternate solution to refactor decrypt() to not expect an `orgId` was a larger effort that expanded the scope beyond the impact of the cipher encryption to Sends and Collections, and I have created a follow-up tech debt item to tackle this refactor: …
=> Added back organizationId to decrypt() calls for clarity

apps/browser/src/auth/popup/login.component.html, apps/browser/src/auth/popup/register.component.html, apps/browser/src/auth/popup/two-factor.component.html, apps/desktop/src/auth/login/login.component.html, apps/desktop/src/auth/register.component.html, apps/desktop/src/auth/two-factor.component.html, apps/web/src/app/auth/login/login.component.html, apps/web/src/app/auth/register-form/register-form.component.html, apps/web/src/app/auth/two-factor.component.html
```
```
Refactor Electron iframes.
=> [PM-3577] Refactor Electron iframes

libs/common/src/platform/services/crypto.service.ts
```
```
Updated `makeCipherKey()` to use the new key generation method introduced in #6162.
- **crypto.service.ts:** Updated to use new `aesGenerateKey()` method.
=> Added reference to new aesGenerateKey function

apps/web/src/app/tools/import-export/dialog/import-error-dialog.component.html, apps/web/src/app/tools/import-export/dialog/import-error-dialog.component.ts, apps/web/src/app/tools/import-export/dialog/index.ts, apps/web/src/app/tools/import-export/import-export.module.ts, apps/web/src/app/tools/import-export/import.component.ts
```
```
Cherry-picked changes from https://github.com/bitwarden/clients/pull/6170 as there were some weird conflicts after passing QA and the changes being ready to get merged.
- **apps/web/src/app/tools/import-export/dialog/import-error-dialog.component.html:**  and **apps/web/src/app/tools/import-export/dialog/import-error-dialog.component.ts:** Build import-error-dialog using CL
- **apps/web/src/app/tools/import-export/dialog/index.ts:** Export import-error-dialog.component folder
- **apps/web/src/app/tools/import-export/import-export.module.ts:** Import and export ImportErrorDialogComponent in module
- **apps/web/src/app/tools/import-export/import.component.ts:** Replace sweetalert2-dialog with DialogService using the new ImportErrorDialogComponent
- Please add **unit tests** where it …
=> [PM-147] Import error states usability improvements

apps/cli/src/bw.ts
```
```
Added initialization of the `ConfigService` to the CLI, as implemented in https://github.com/bitwarden/clients/pull/5602 and discussed here: https://github.com/bitwarden/clients/pull/6241#discussion_r1321059971.
- **bw.ts:** Initialized the `ConfigService` on initialization of the CLI.
=> [PM-3867] Added CLI initialization

apps/desktop/src/app/services/services.module.ts, apps/desktop/src/platform/services/electron-platform-utils.service.ts, libs/angular/src/services/injection-tokens.ts, libs/common/src/enums/client-type.enum.ts
```
```
Cleanup unused ClientType.DirectoryConnector.
=> [PM-3625] Remove ClientType.DirectoryConnector

apps/desktop/electron-builder.json, package-lock.json, package.json
```
```
Upgrades to the latest Electron v24 for bug fixes and security patches.
=> Upgrade to latest electron v24

apps/browser/src/popup/polyfills.ts, apps/browser/src/popup/scss/plugins.scss, apps/web/src/polyfills.ts, apps/web/src/scss/plugins.scss, package-lock.json, package.json
```
```
Remove date-input-polyfill since date fields have good cross-browser support. Last browser was Safari which added proper support in 14.1.
=> [BEEEP] [PM-4043] Remove date-input-polyfill

libs/common/src/enums/feature-flag.enum.ts
```
```
Adding a feature flag facilitating development for the browser file-less import feature.
* **libs/common/src/enums/feature-flag.enum.ts:** Adding an enum that can be called to verify the presence of a feature flag for `BrowserFilelessImport`.
=> [PM-4075] Setup Feature Flag for Browser File-less Import

apps/web/webpack.config.js
```
```
When attempting to test PayPal payments in a local development environment, the dialog fails to open. The following error is thrown in the console. This PR is an attempt to address this.
Refused to connect to 'https://api.sandbox.braintreegateway.com/merchants/yjpk3sgj4fzjrdyw/client_api/v1/paypal_hermes/setup_billing_agreement' because it violates the following Content Security Policy directive: "connect-src 'self' wss://notifications.bitwarden.com https://notifications.bitwarden.com https://cdn.bitwarden.net https://api.pwnedpasswords.com https://api.2fa.directory/v3/totp.json https://api.stripe.com https://www.paypal.com https://api.braintreegateway.com https://client-analytics.braintreegateway.com https://*.braintree-api.com https://*.blob.core.windows.net …
=> [BEEEP] Add Braintree sandbox API to permitted script sources in CSP

apps/desktop/src/scss/base.scss
=> [PM-4089] fix typo in base.scss

apps/web/src/app/admin-console/organizations/manage/groups.component.ts, apps/web/src/app/admin-console/organizations/tools/import-export/org-import.component.ts, apps/web/src/app/tools/import-export/import.component.ts, apps/web/src/app/tools/send/send.component.ts, bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/access/access-tokens.component.ts
```
```
The usage of `ModalService` is marked as deprecated and should be replaced by `DialogService`. With the replacement some of the constructor params weren’t checked and included unused references to ModalService.
This removes the ones I found.
=> [PM-4041][BEEEP] Removed unused references to ModalService

apps/web/src/app/admin-console/organizations/settings/account.component.html, apps/web/src/app/admin-console/organizations/settings/account.component.ts, apps/web/src/locales/en/messages.json, libs/common/src/admin-console/models/data/organization.data.ts, libs/common/src/admin-console/models/domain/organization.ts, libs/common/src/admin-console/models/response/organization.response.ts, libs/common/src/admin-console/models/response/profile-organization.response.ts
```
```
Rename this to LimitCollectionCreationDeletion to be more human readable and accurate.
See https://github.com/bitwarden/server/pull/3300 for corresponding server changes.
=> [AC-1646] Rename LimitCollectionCdOwnerAdmin column

libs/angular/src/vault/components/attachments.component.ts, libs/common/src/platform/services/config/config.service.ts, libs/common/src/vault/services/cipher.service.ts, libs/exporter/src/vault-export/services/vault-export.service.ts
```
```
Addressed PR feedback on https://github.com/bitwarden/clients/pull/6241 from @MGibson1.
- **vault-export.service.ts:** Removed extra parentheses.
- **config.service.ts:** Updated comment.
- **cipher.service.ts:** Updated  `SemVer` to only evaluate once, and used shorthand `||=` for assignment.
=> [PM-2669] PR review changes

libs/components/src/checkbox/checkbox.component.ts, libs/components/src/checkbox/checkbox.stories.ts
```
```
Adds an indeterminate image to `bitCheckbox`
=> [CL-80] feat: indeterminate checkbox

.github/CODEOWNERS
```
```
Updated CL codeowner to [team-component-library](https://github.com/orgs/bitwarden/teams/team-component-library?query=)
=> Update CL codeowners

apps/web/src/app/admin-console/organizations/users/enroll-master-password-reset.component.html, apps/web/src/app/admin-console/organizations/users/enroll-master-password-reset.component.ts, apps/web/src/app/vault/individual-vault/vault-filter/components/organization-options.component.ts
```
```
Migrate EnrollMasterPasswordReset to Component Library.
|-|-|
| ![image](https://github.com/bitwarden/clients/assets/137855/8b0b37a5-9804-4110-a8b1-7416ab48d3e8) | ![image](https://github.com/bitwarden/clients/assets/137855/d5d79d74-1385-476a-a075-8d955092053e) |
=> [PM-2157] Migrate EnrollMasterPasswordReset to CL

apps/desktop/electron-builder.json, package-lock.json, package.json
```
```
Bump electron to 24.8.5
=> [PM-4147] Bump electron to 24.8.5

libs/common/src/vault/services/fido2/fido2-client.service.ts
```
```
Error message not being displayed on abort when testing with https://webauthn.io/.
- **libs/common/src/vault/services/fido2/fido2-client.service.ts:** Replaced undefined with descriptive error message.
https://github.com/bitwarden/clients/assets/13024008/1e16ead3-2581-48b2-82ed-dab4de6bbbc5
=> [PM-4148] Added descriptive error messages

apps/browser/src/vault/popup/components/vault/add-edit.component.html, apps/browser/src/vault/popup/components/vault/view.component.html, apps/desktop/src/vault/app/vault/add-edit.component.html, apps/desktop/src/vault/app/vault/view.component.html, apps/web/src/app/vault/individual-vault/add-edit.component.html, apps/web/src/app/vault/individual-vault/add-edit.component.ts, apps/web/src/app/vault/individual-vault/vault.component.ts, libs/angular/src/vault/components/add-edit.component.ts, libs/angular/src/vault/components/view.component.ts, libs/common/src/models/api/login.api.ts, libs/common/src/models/export/fido2-credential.export.ts, libs/common/src/models/export/index.ts, libs/common/src/models/export/login.export.ts, libs/common/src/vault/api/fido2-credential.api.ts, libs/common/src/vault/models/data/fido2-credential.data.ts, libs/common/src/vault/models/data/login.data.ts, libs/common/src/vault/models/domain/cipher.spec.ts, libs/common/src/vault/models/domain/fido2-credential.spec.ts, libs/common/src/vault/models/domain/fido2-credential.ts, libs/common/src/vault/models/domain/login.spec.ts, libs/common/src/vault/models/domain/login.ts, libs/common/src/vault/models/request/cipher.request.ts, libs/common/src/vault/models/view/fido2-credential.view.ts, libs/common/src/vault/models/view/login.view.ts, libs/common/src/vault/services/cipher.service.ts, libs/common/src/vault/services/fido2/fido2-authenticator.service.spec.ts, libs/common/src/vault/services/fido2/fido2-authenticator.service.ts
```
```
Rename `Fido2Key` to `Fido2Credential`.
=> [PM-4054] Rename Fido2Key to Fido2Credential

.github/workflows/chromatic.yml
```
```
This PR fixes the `Chromatic` workflow.
- **.github/workflows/chromatic.yml:** Move checkout step before getting Node version to make sure `.nvmrc` file exists.
=> Chromatic Workflow - Move checkout step before getting Node version

.github/workflows/release-cli.yml, .github/workflows/release-desktop.yml
```
```
This PR updates the Snap jobs for `Desktop` and `CLI`.
- **.github/workflows/release-cli.yml:** Change to newer `upload` subcommand and remove unused input to snapcraft action.
- **.github/workflows/release-desktop.yml:** Change to use just `snapcraft` instead of full path to executable, remove useless environment variable from snapcraft action.
=> Standardize Snapcraft commands in workflows

libs/common/src/admin-console/models/domain/organization.ts
> Update the `organization.canCreateNewCollections` logic to include the `LimitCollectionCreationDeletion` boolean.
- **libs/common/src/admin-console/models/domain/organization.ts** Add `!limitCollectionCreationDeletion` to conditional to reference the newly added collection management setting
=> [AC-1659] Update CanCreateNewCollections with LimitCollectionCreationDeletion

libs/importer/src/importers/lastpass/access/exported-account.ts, libs/importer/src/importers/lastpass/access/vault.ts
=> helper to serialize vault accounts

apps/desktop/electron-builder.json, package-lock.json, package.json
```
```
Downgrades Electron from v26.3.0 to v25.9.1. 
Resolves #6560
=> [PM-4300] downgrade Electron to v25.9.1

apps/browser/src/auth/popup/two-factor.component.html, apps/desktop/src/auth/two-factor.component.html, apps/web/src/app/auth/two-factor.component.html
```
```
Duo needs the `allow-popups` and `allow-popups-to-escape-sandbox` permissions to function correctly with yubikeys.
=> [PM-4293] Update duo and add allow-popups and allow-popups-to-escape-sandbox

apps/web/src/app/vault/org-vault/vault.component.ts
```
```
Added Passkey Clone Warning For Org Vaults
https://github.com/bitwarden/clients/assets/13024008/ba85e90b-e46e-4561-90a1-47d9a67ff953
=> [PM-4315] Added Passkey Clone Warning For Org Vaults

apps/web/src/app/billing/organizations/billing-sync-key.component.html, apps/web/src/app/billing/organizations/billing-sync-key.component.ts, apps/web/src/app/billing/organizations/organization-subscription-selfhost.component.ts
```
```
[PM-2162](https://bitwarden.atlassian.net/browse/PM-2162)
This PR replaces the Modal construct with the `bit-dialog` directive for the `billing-sync-key` component.
- **[billing-sync-key.component.html](https://github.com/bitwarden/clients/pull/6547/files#diff-d4bb78b603c1a6d06d742802ce14edafc4edf989a3f1abadaddc4d773961033b):** Replaces old modal with bit-dialog directives.
- **[billing-sync-key.component.ts](https://github.com/bitwarden/clients/pull/6547/files#diff-a5e42622e07c8418be93a9eacc26fef48343abcf537bc61ebdbca459dcc9c16e):** Wires up the component to use dialog and form group.
- **[organization-subscription-selfhost.component.ts](https://github.com/bitwarden/clients/pull/6547/files#diff-d5d7fe6b620d2c868355500a6c8de86cbb1679630bb218b1932442ec7989c78b):** Wires up the …
=> [PM-2162] Update `billing-sync-key` to use Dialog

libs/common/src/vault/abstractions/fido2/fido2-authenticator.service.abstraction.ts, libs/common/src/vault/services/fido2/fido2-authenticator.service.spec.ts, libs/common/src/vault/services/fido2/fido2-authenticator.service.ts, libs/common/src/vault/services/fido2/fido2-client.service.spec.ts, libs/common/src/vault/services/fido2/fido2-client.service.ts
Fix typo `Fido2AutenticatorErrorCode`
=> [PM-4402] Fix typo Fido2AutenticatorErrorCode

apps/browser/src/platform/browser/browser-api.ts, apps/browser/src/vault/popup/components/fido2/fido2-cipher-row.component.ts, apps/browser/src/vault/popup/components/fido2/fido2-use-browser-link.component.ts, apps/browser/src/vault/popup/components/fido2/fido2.component.html, apps/browser/src/vault/popup/components/fido2/fido2.component.ts, apps/browser/src/vault/popup/components/vault/add-edit.component.ts
```
- [ X ] Tech debt (refactoring, code cleanup, dependency upgrades, etc)
```
Some small cleanup work leftover from previous PR https://github.com/bitwarden/clients/pull/4715. There is no change to functionality of the popup.
NOTE: if you pull this branch and the popup looks half size or search results is not showing only matching uri ciphers those updates can be found here: https://github.com/bitwarden/clients/pull/6615 and here: https://github.com/bitwarden/clients/pull/6628
https://github.com/bitwarden/clients/assets/8302660/082ce9d2-7ac5-4cef-995d-e8f9a424c43e
=> PM-4382 minor cleanup around the passkey popup

libs/importer/src/importers/lastpass/access/index.ts, libs/importer/src/importers/lastpass/access/models/client-info.ts, libs/importer/src/importers/lastpass/access/models/exported-account.ts, libs/importer/src/importers/lastpass/access/models/index.ts, libs/importer/src/importers/lastpass/access/models/user-type-context.ts, libs/importer/src/importers/lastpass/access/services/client.ts, libs/importer/src/importers/lastpass/access/services/rest-client.ts, libs/importer/src/importers/lastpass/access/ui/ui.ts, libs/importer/src/importers/lastpass/access/vault.ts
```
```
These are all changes pulled from https://github.com/bitwarden/clients/pull/6541 but targeting master first and with a bit more clearer commit messages. This should ease the review of this PR but also https://github.com/bitwarden/clients/pull/6541 due to less files needing review at once
- **Casing fixes from the original port of the code -** https://github.com/bitwarden/clients/commit/97247a91ec759eccc0a42d8b1b2b6dcad66f8830
- **Add static createClientInfo and export -** https://github.com/bitwarden/clients/commit/dce95465610a4590d3c456694c69e93ab80430bb
- **Add way to transform retrieve accounts into csv format -** https://github.com/bitwarden/clients/commit/95436c9116fdff4ca9b949bbc3d5b4707f1fd536
- Create ExportAccount model 
- accountsToExportedCsvString can transform and …
=> [PM-4195] Lastpass lib cleanup

apps/web/src/app/billing/individual/user-subscription.component.html, apps/web/src/app/billing/individual/user-subscription.component.ts, apps/web/src/app/billing/organizations/organization-subscription-cloud.component.html, apps/web/src/app/billing/organizations/organization-subscription-cloud.component.ts, apps/web/src/app/billing/organizations/sm-subscribe-standalone.component.html, apps/web/src/app/billing/organizations/sm-subscribe-standalone.component.ts, apps/web/src/app/billing/shared/sm-subscribe.component.ts, apps/web/src/locales/en/messages.json, libs/common/src/billing/models/response/organization-subscription.response.ts, libs/common/src/billing/models/response/subscription.response.ts
```
```
[AC-1706](https://bitwarden.atlassian.net/browse/AC-1706)
This PR checks for a Stripe customer-level discount and, if one exists, uses it to discount all the prices on the billing subscriptions page.
https://github.com/bitwarden/clients/assets/144709477/c9f5f2ec-5d3c-4143-8ce4-2a49c35122eb
[AC-1706]: …
=> [AC-1706] Show Discounted Prices

apps/web/src/app/admin-console/organizations/members/components/bulk/bulk-restore-revoke.component.html, apps/web/src/app/admin-console/organizations/members/components/bulk/bulk-restore-revoke.component.ts, apps/web/src/app/admin-console/organizations/members/people.component.ts
```
```
Found another blocker for the Angular 16 upgrade. This PR migrates the bulk restore component.
=> [PM-2052] Migrate bulk restore component

apps/desktop/src/main/window.main.ts, apps/desktop/src/utils.ts
```
```
Refactor utils helper functions. Introduce `isLInux`, `isWindows`.
=> [PM-4441] Refactor utils helper functions

apps/desktop/src/locales/en/messages.json
```
```
Adds the missing entry in the messages.json so the helper text is shown fully
Will be 🍒 ⛏️ to `rc`
- **apps/desktop/src/locales/en/messages.json:** Add missing "collection" which gets displayed as a helper text on the import dialog
=> [PM-4513] Import - Helper text under "Collections" Dropdown is cut off

.gitignore, apps/browser/src/background/main.background.ts, apps/cli/.gitignore, apps/desktop/.gitignore, apps/desktop/webpack.renderer.js, apps/web/.gitignore, libs/angular/src/services/jslib-services.module.ts, libs/common/src/platform/misc/flags.ts, libs/common/src/platform/services/noop-notifications.service.ts, libs/common/src/services/notifications.service.ts
We rarely have notifications set up for development environments, this removes the error messages related to missing server notification services
```
```
Dev flag to remove notification capabilities.
=> Noop notifications for dev

apps/web/src/app/vault/components/vault-items/vault-items.stories.ts
```
```
Storybook was failing because no `ConfigService` dependency was configured for `vault-items.component`.
This only affects the `canDelete` logic so its actual behaviour is not important for Storybook; I've just stubbed it out for now.
If we want it to be toggle-able we'd need to lift it to an `@Input` which is what I did for the bulk access feature flag, but it just doesn't seem necessary right now. …
=> [Flexible Collections] Update storybook dependencies

.github/workflows/brew-bump-cli.yml, .github/workflows/brew-bump-desktop.yml, .github/workflows/build-browser.yml, .github/workflows/build-cli.yml, .github/workflows/build-desktop.yml, .github/workflows/build-web.yml, .github/workflows/crowdin-pull.yml, .github/workflows/deploy-eu-prod-web.yml, .github/workflows/deploy-eu-qa-web.yml, .github/workflows/deploy-non-prod-web.yml, .github/workflows/release-browser.yml, .github/workflows/release-cli.yml, .github/workflows/release-desktop-beta.yml, .github/workflows/release-desktop.yml, .github/workflows/release-web.yml, .github/workflows/staged-rollout-desktop.yml, .github/workflows/version-bump.yml, .github/workflows/workflow-linter.yml
```
```
- Update all bitwarden actions to to reference master
- **.github/workflows/*:** The change was made for bitwarden actions to reference master branch
- Please check for formatting errors (`dotnet format --verify-no-changes`) (required)
- If making database changes - make sure you also update Entity Framework queries and/or migrations
=> UPDATE: pin bitwarden/actions to master

libs/angular/src/auth/guards/lock.guard.ts
```
```
The legacy migration added a legacy check before the auth check in the lock guard. Unauthenticated accounts weren't able to inspect their keys for legacy status, causing an error.
=> [PM-4208] Fix lock guard redirect

.github/renovate.json
```
```
Tweak renovate titles to be `[deps] Team: Update <dep> to <version>`.
Disable renovate PRs for node, since it's coupled to our electron version currently.
=> [PM-2331] Tweak renovate subject

libs/common/src/vault/services/fido2/fido2-authenticator.service.ts
```
```
The comment contained an incorrect AAGUID value
=> fix: incorrect AAGUID in comment

.github/workflows/deploy-eu-qa-web.yml, .github/workflows/deploy-non-prod-web.yml
```
```
Automate QA deploy messages to Slack.
- **.github/workflows/deploy-non-prod-web.yml:** Add job to notify slack with success or failure result of web deployment to US QA
- **.github/workflows/deploy-eu-qa-web.yml** Add job to notify slack with success or failure result of web deployment to EU QA
=> [DEVOPS-1578] Automate QA deploy messages

libs/common/src/vault/services/cipher.service.ts
=> [PM-4660] Check size of orgKeys map instead of against null

apps/browser/src/vault/fido2/browser-fido2-user-interface.service.ts
=> [PM-4693] Fallback to browser when the user closes out of the passkey prompt

.github/CODEOWNERS
```
```
Short follow-up from https://github.com/bitwarden/clients/pull/6746 where I missed the files for the stores.
- **.github/CODEOWNERS:** 
- Set ownership of locales for the stores to team-tools-dev
- Remove ownership for `apps/browser/store/locales/en` 
=> Update CODEOWNERS for Crowdin PRs Pt2

apps/web/src/app/admin-console/organizations/members/people.component.ts, apps/web/src/app/auth/trial-initiation/trial-initiation.component.ts, apps/web/src/app/billing/organizations/organization-plans.component.html
```
```
- **people.component.ts:** Combined conditionals in early return to prevent accidentally early returning
- **organization-plans.component.html:** Resolved issue where enterprise orgs were displaying plan details from more than one ng-container
- **trial-initiation.component.ts:** Updated `orgLabel` to use `orgDisplayName`
=> [PM-4716] [PM-4717] [AC-1799] UI Bugs around Paid Plans

apps/browser/src/tools/popup/generator/generator.component.html, apps/desktop/src/app/tools/generator.component.html, apps/web/src/app/tools/generator.component.html, libs/angular/src/tools/generator/components/generator.component.ts
=> Using rxjs to debounce

.codescene/code-health-rules.json
```
```
Disable code duplication check in unit tests since unit tests duplicate code instead of using control structures.
- **.codescene/code-health-rules.json:** Configures codescene health checks.
=> disable code duplication check in unit tests

.github/workflows/brew-bump-cli.yml, .github/workflows/brew-bump-desktop.yml, .github/workflows/build-browser.yml, .github/workflows/build-cli.yml, .github/workflows/build-desktop.yml, .github/workflows/build-web.yml, .github/workflows/crowdin-pull.yml, .github/workflows/deploy-eu-prod-web.yml, .github/workflows/deploy-eu-qa-web.yml, .github/workflows/deploy-non-prod-web.yml, .github/workflows/release-browser.yml, .github/workflows/release-cli.yml, .github/workflows/release-desktop-beta.yml, .github/workflows/release-desktop.yml, .github/workflows/release-web.yml, .github/workflows/staged-rollout-desktop.yml, .github/workflows/version-bump.yml, .github/workflows/workflow-linter.yml
```
```
This PR updates all of our action versions to reference `main` instead of `master`.
=> All workflows - Update 'master' to 'main' for any actions in the gh-actions repository

.github/workflows/deploy-non-prod-web.yml
```
```
- **.github/workflows/deploy-non-prod-web.yml:** Change the tag input to github ref to report actual branch to Slack instead of `cf-pages-qa` every time.
=> Fix branch name in report-deployment-status-to-slack

apps/web/src/app/auth/settings/webauthn-login-settings/webauthn-login-settings.component.html
```
```
Add a small beta badge
=> [PM-4737] Add Beta badge

apps/web/src/app/auth/trial-initiation/content/teams1-content.component.html, apps/web/src/app/auth/trial-initiation/content/teams3-content.component.html, apps/web/src/app/auth/trial-initiation/trial-initiation.component.ts
```
```
This PR adds a link on the Teams Starter trial page that navigates to the Teams trial page. On the Teams trial page, it adds pricing above the main body.
- **teams1-content.component.html:** Add pricing above the main body.
- **teams3-content.component.html:** Add new bullet point with link to the Teams trial page.
- **trial-initiation.component.ts:** I'm not sure if this was by design, but the `pipe(first())` on the `queryParams` observable was making it impossible to actually trigger the query params subscription. Navigating to another `/register` layout would not actually change the layout. Just subscribing to the `queryParams` resolved that.
Teams Trial with pricing:
Teams Starter pricing with link:
https://github.com/bitwarden/clients/assets/144709477/c2cd204c-ef36-4598-a3ac-0 …
=> [AC-1812] Add link to Teams Starter trial, pricing to Teams trial pages

.github/CODEOWNERS
```
```
Make Platform the owner of testing utilities.
- **.github/CODEOWNERS:** Add entry for platform team
=> Add Platform Entry to `CODEOWNERS`

.github/CODEOWNERS
```
```
Platform is the owner of state, they should also be the owner of migrating state.
- **f.github/CODEOWNERS:** Add entry in platform section.
=> Make Platform Own State Migrations

libs/importer/src/importers/lastpass/access/vault.ts
ref https://bitwarden.atlassian.net/browse/PM-4792
```
```
Fix a bug where k1 was not found when using Azure AD with LastPass federated login imports.
- **vault.ts:** The `extensions` property is an array, not an object, so fetch the k1 from the object in position 0 of the array.
=> [PM-4792] lastpass azure ad json extension prop is an array

.github/workflows/build-desktop.yml, .github/workflows/release-desktop-beta.yml
This PR updates the way we install the AST in our Build workflow.  This new version is now on .NET 6 which is still supported.
- **.github/workflows/build-desktop.yml:** Change install from action to single command.
- **.github/workflows/release-desktop-beta.yml:** Change install from action to single command.
=> Build Desktop - Remove AST action and replace with NuGet install command

apps/web/src/app/oss-routing.module.ts
```
```
Fix bug that was both loading and lazy loading emergency access accept component.
=> Fix bad merge

apps/browser/src/vault/fido2/content/content-script.ts, apps/browser/src/vault/fido2/content/messaging/message.ts, apps/browser/src/vault/fido2/content/page-script.ts, apps/browser/src/vault/fido2/webauthn-utils.ts
```
```
Critical params such as `origin` and `isSameOriginWithAncestors` cannot be provided by the page-script because that code is running in an insecure environment and can be spoofed. This PR fetches those fields from the page-script instead.
=> [PM-4830] Fix unsafe origin source

.github/workflows/deploy-eu-qa-web.yml, .github/workflows/deploy-non-prod-web.yml
```
```
https://bitwarden.atlassian.net/browse/DEVOPS-1651
- **.github/workflows/deploy-eu-qa-web.yml:** Change inputs to match new ones from [gh-actions PR](https://github.com/bitwarden/gh-actions/pull/215). Add a start message.
- **.github/workflows/deploy-non-prod-web.yml** Change inputs to match new ones from [gh-actions PR](https://github.com/bitwarden/gh-actions/pull/215). Add a start message.
=> [DEVOPS-1651] Update the QA deployment alert at the start 

.git-blame-ignore-revs
Per https://github.com/bitwarden/clients/pull/7014#issuecomment-1832155512
=> [PM-5040] Add prettier formatting merge commit to .git-blame-ignore-revs

apps/web/src/app/tools/send/send-access-text.component.ts
```
```
I merged https://github.com/bitwarden/clients/pull/7028 which had not been updated to the most recent master yet, which involved re-running prettier v3 (https://github.com/bitwarden/clients/pull/7014).
This will need to be 🍒 ⛏️  to `rc`
- **apps/web/src/app/tools/send/send-access-text.component.ts:** Result after running `npm run prettier`
=> [PM-5051] Make linter happy

apps/browser/src/auth/popup/lock.component.ts, apps/browser/src/popup/app-routing.animations.ts
```
```
Delete an overridden method that caused a double navigation. Instead we will just allow the messaging to handle the navigation to the next screen. On a single user this will bring them to the home screen to enter an email. With multiple users it will bring them to the next available users vault/lock screen.
- **apps/browser/src/auth/popup/lock.component.ts:** Delete the whole overridden method since we no longer needed the navigation and that was the only reason for the override. …
=> [PM-5005] Prevent Double Navigation

apps/web/src/app/billing/organizations/organization-plans.component.html, apps/web/src/app/billing/organizations/organization-plans.component.ts
```
```
Now that `billing-plans-upgrade` and `billing-starter-plan` have been released, we're now deleting the feature flag references from the codebase.
=> [AC-1865][AC-1866] Billing Feature Flag Cleanup

libs/common/src/vault/services/totp.service.spec.ts
```
```
Adds tests for the TOTP service in preparation for migrating it to the SDK.
=> [PM-4273] Add tests for TotpService

apps/desktop/electron-builder.json, package-lock.json, package.json
=> [PM-4988] Bump electron to v27.1.3

apps/browser/src/platform/services/browser-crypto.service.ts
```
```
Corrects handling of setting additional keys in browser client
=> Do not drop optional parameters in overrides

libs/common/spec/fake-storage.service.ts, libs/common/spec/utils.ts, libs/common/src/platform/state/implementations/default-active-user-state.spec.ts, libs/common/src/platform/state/implementations/default-active-user-state.ts, libs/common/src/platform/state/implementations/default-global-state.spec.ts, libs/common/src/platform/state/implementations/default-global-state.ts, libs/common/src/platform/state/implementations/default-single-user-state.spec.ts, libs/common/src/platform/state/implementations/default-single-user-state.ts, libs/common/src/platform/state/key-definition.spec.ts, libs/common/src/platform/state/key-definition.ts
Reverts bitwarden/clients#7124
This seems to be causing timeout issues
=> Revert "Ps/avoid state emit until updated"

.github/workflows/version-bump.yml
```
```
This PR adds the Bitwarden DevOps bot token for checking out the repository.  This enables the bot to push changes without errors when called from another repository.
- **.github/workflows/version-bump.yml:** Adds the `token` key to the checkout step.
=> Update version bump workflow token

apps/browser/src/background/idle.background.ts, apps/browser/src/background/main.background.ts
```
```
Change the `idle.onStateChanged` callback to check all tracked users instead of only checking the active user. While in there I got rid of some `any` uses. 
- **apps/browser/src/background/idle.background.ts:** Check all users instead of active user
- **apps/browser/src/background/main.background.ts:** Add `AccountService` to `IdleBackground`
=> [PM-5150] Timeout Vault of Inactive Users on System Lock

libs/common/src/platform/state/state-definitions.spec.ts, libs/common/src/platform/state/state-definitions.ts
```
```
Add tests enforcing some of the rules platform as for state definitions.
- **libs/common/src/platform/state/state-definitions.ts:** Show rules
- **libs/common/src/platform/state/state-definitions.spec.ts:** Enforce as many rules in unit tests as we can
=> State definitions tests

apps/browser/src/background/main.background.ts
```
```
Updates overlay on account switch
=> Update overlay on account switch

apps/browser/src/background/main.background.ts, apps/browser/src/popup/services/services.module.ts, apps/browser/src/vault/services/vault-filter.service.ts
```
```
clear vault filters on account switch -- they may not have the same filters available, which empties the vault and requires a reload of the service.
=> [PM-5296] Clear vault filter on account switch

apps/web/src/app/admin-console/organizations/manage/groups.component.html, apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.html, apps/web/src/app/admin-console/organizations/members/people.component.html, apps/web/src/app/admin-console/organizations/policies/policies.component.html, apps/web/src/app/admin-console/organizations/shared/components/access-selector/access-selector.component.html, apps/web/src/app/auth/settings/emergency-access/emergency-access.component.html, apps/web/src/app/auth/settings/webauthn-login-settings/webauthn-login-settings.component.html, apps/web/src/app/billing/individual/user-subscription.component.html, apps/web/src/app/billing/organizations/organization-subscription-cloud.component.html, apps/web/src/app/reports/pages/exposed-passwords-report.component.html, apps/web/src/app/reports/pages/reused-passwords-report.component.html, apps/web/src/app/reports/pages/weak-passwords-report.component.html, apps/web/src/app/reports/pages/weak-passwords-report.component.ts, apps/web/src/app/reports/shared/report-card/report-card.component.html, apps/web/src/app/vault/components/premium-badge.component.ts, apps/web/src/app/vault/individual-vault/add-edit.component.html, apps/web/src/app/vault/org-vault/collection-badge/collection-name-badge.component.html, apps/web/src/app/vault/org-vault/group-badge/group-name-badge.component.html, bitwarden_license/bit-web/src/app/admin-console/organizations/manage/domain-verification/domain-add-edit-dialog/domain-add-edit-dialog.component.html, bitwarden_license/bit-web/src/app/admin-console/organizations/manage/domain-verification/domain-verification.component.html, bitwarden_license/bit-web/src/app/admin-console/providers/manage/people.component.html, bitwarden_license/bit-web/src/app/secrets-manager/shared/secrets-list.component.html, libs/components/src/badge-list/badge-list.component.html, libs/components/src/badge-list/badge-list.component.ts, libs/components/src/badge-list/badge-list.stories.ts, libs/components/src/badge/badge.directive.ts, libs/components/src/badge/badge.stories.ts, libs/components/src/badge/index.ts, libs/components/src/multi-select/multi-select.component.html, libs/components/src/toggle-group/toggle-group.stories.ts
```
```
We're establishing a common language for the Component Library. As part of this work we're renaming `componentType` to `variant`. Starting with badges.
=> [CL-160] Rename BadgeType to BadgeVariant

apps/browser/src/background/main.background.ts, apps/cli/src/bw.ts
```
```
Register `StateProvider` in CLI and browser background to help facilitate migrations. 
- Register all the `Default*` implementations.
=> Register `StateProvider` in non DI clients

libs/components/src/banner/banner.component.html
```
```
Adds a bottom border to bit-banner, to improve the look of stacked banners. 
=> [CL-159] add bottom border to bit-banner

.github/workflows/deploy-web.yml
```
```
This PR updates the way we use the `Report Deployment Status to Slack` action so that we can edit messages instead of sending a new message each time.
- **.github/workflows/deploy-web.yml:** Added outputs to the `notify-start` job so they can be used in the `notify` job later on in the workflow. Added `notify-start` job as needed for the `notify` job so we can use the output values.
=> Update workflow to use new report action

apps/web/src/app/vault/utils/collection-utils.ts
=> [PM-5365] Clone manage property when cloning collection

.github/workflows/build-web.yml, .github/workflows/deploy-web.yml, apps/web/config/usdev.json, apps/web/package.json
```
```
Build and deploy Web Vault to Azure Storage Account. for new USDEV (DevTest) environment.
- **.github/workflows/build-web.yml:** Add new build artifact for USDEV.
- **.github/workflows/deploy-web.yml** Add `USDEV` option to environment, and setup job. Add check for sending QA deploy message only when deploying to QA env.
- **apps/web/config/usdev.json** Add USDEV configuration.
- **apps/web/package.json** Add command to build web with new usdev config. …
=> [DEVOPS-1501] Build and Deploy Web Vault for USDEV (DevTest)

.github/workflows/test.yml
```
```
Adds code coverage collection and submission to codecov.io.
- **.github/workflows/test.yml:** Submission to codecov.io.
=> Wire up code coverage

.github/workflows/test.yml
```
```
Run tests on pushes and not just pull requests. We want these results on all branches.
- **.github/workflows/test.yml:** Trigger change.
=> Run tests on pushes and not just pull requests

apps/browser/src/safari/desktop/Info.plist, apps/browser/src/safari/safari/Info.plist, apps/cli/stores/chocolatey/bitwarden-cli.nuspec, apps/desktop/electron-builder.json, apps/desktop/stores/chocolatey/bitwarden.nuspec, apps/web/src/404.html
```
```
Annual chore to update the year in the copyright information.
=> [PM-5479] Update year in copyright with 2023 to 2024

.github/workflows/build-web.yml
```
```
When we build the Web client on `main`, we want the workflow to automatically trigger the deployment workflow to push the artifacts to DevTest, so that every merge into `main` is deployed to the DevTest environment.
- **.github/workflows/build-web.yml:** Trigger `deploy-web` workflow for `USDEV` env on `main` when build artifacts are completed and the branch is `main`.
=> [DEVOPS-1656] Update Web build workflow to automatically trigger DevTest deploy

apps/web/src/app/auth/settings/webauthn-login-settings/create-credential-dialog/create-credential-dialog.component.ts
```
```
defaults the "use for encryption" checkbox to on when adding a passkey
=> [PM-5569] passkey use for encryption on by default

apps/desktop/src/vault/app/vault/add-edit.component.ts, apps/web/src/app/auth/settings/emergency-access/view/emergency-add-edit-cipher.component.ts, apps/web/src/app/vault/individual-vault/add-edit.component.ts, apps/web/src/app/vault/org-vault/add-edit.component.ts
```
```
Window objects added during the TOTP community PR. They are causing errors when adding new items in vault. Removing unnecessary objects.
https://github.com/bitwarden/clients/assets/8302660/31896416-b60f-46c0-9a45-d530e06ba405
=> PM-5589 add-edit defect update

.github/workflows/build-web.yml
```
```
Fix the auto-deploy on `main` to the new Dev environment
- **build-web.yml:** Fix the workflow trigger data.
=> Fix new CD to use correct workflow inputs

.github/workflows/build-web.yml, .github/workflows/deploy-web.yml
```
```
Fix workflow dispatch inputs. Attached is a screenshot of a success dispatch to US DEV.
- **.github/workflows/build-web.yml:** Explicitly set workflow dispatch inputs to strings
=> [DEVOPS-1705] Fix US DEV Web CD

apps/desktop/package.json, apps/desktop/src/package-lock.json, apps/desktop/src/package.json, package-lock.json
This reverts commit 624f3891fe9355526ce31b0cd4d8ece1b6b51640.
```
```
I accidentally ran the Desktop Version Bump on `main`.  This is reverting the bump.
=> Revert "Bumped desktop version to 2024.1.1 (#7476)"

libs/common/src/services/api.service.ts
```
```
Changed the `prevalidate` route to target `sso` instead of `account`
- **src\services\api.service.ts:** updated line 1622 from to target `sso` instead of `account`
=> Update sso prevalidate path

libs/angular/src/vault/components/add-edit.component.ts, libs/common/src/vault/models/request/cipher.request.ts, libs/common/src/vault/models/view/login.view.ts
```
```
Defensively checks for nulls in login views. Also sets them more appropriately to empty in known example of inappropriate nulls.
=> [PM-5465] Fix null checks in login view uris

apps/browser/src/_locales/en/messages.json, apps/desktop/src/locales/en/messages.json, apps/web/src/locales/en/messages.json, libs/importer/src/components/import.component.html, libs/importer/src/components/import.component.ts
```
```
Replace the existing empty line separator with a dashed line to make it more clear, added a label before the `common formats` on the selector
- **import.component:** Changed the empty separator option to a dashed line, added a new disabled option to the format selector that works as a label identifying the item, moved the `--Select--` label from `.ts` file to `.html`
Added videos as it better demonstrates the changes made.
**Web**
https://github.com/bitwarden/clients/assets/109146700/f655d538-77f1-4889-84f2-69ead86da4ba
**Desktop**
https://github.com/bitwarden/clients/assets/109146700/60b014a1-f8bc-4307-8808-fda883321c9c
**Browser**
https://github.com/bitwarden/clients/assets/109146700/3dc6d483-92cb-4044-89e1-d5d758867b81 …
=> [PM-5056] Improved UI on format selector for Importer

apps/web/src/connectors/sso.ts
```
```
Switch to using the `"load"` event on `window` vs `"DOMContentLoaded"`. The `load` event fires later after more of the page has been loaded. This allows the content script of our extension a better chance to register and be ready to handle the message from this page.
=> [PM-5597] Listen to Window Load

.github/workflows/deploy-web.yml
```
```
- This PR adds the Commit SHA of the branch or tag deployed to QA to the Slack notification.
- **.github/workflows/deploy-web.yml:** Adds a job to get the SHA of the branch or tag deployed and adds that value to the slack notif action's input
=> Add the Commit sha of the branch or tag deployed

apps/browser/src/popup/app.component.ts
```
```
As small a PR as you can make!
`VaultTimeoutService.lock()` is called with no parameters from the browser settings component. https://github.com/bitwarden/clients/blob/a572e4119edd6da65295268c8cab95a7ab16afc5/apps/browser/src/popup/settings/settings.component.ts#L425
This means that `userId` will be `undefined` throughout all of the the `lock` method and it will eventually pass that value to the `"locked"` message. 
https://github.com/bitwarden/clients/blob/a572e4119edd6da65295268c8cab95a7ab16afc5/libs/common/src/services/vault-timeout/vault-timeout.service.ts#L99
The handler, that I changed in this PR was skipping the router navigation if the `userId` wasn't strictly equal to `null` or if the userId passed in the message is equal to the last known active user id. Neither of those …
=> [PM-5640] Use Null-ish Comparison vs Strict Null

apps/web/src/app/vault/components/collection-dialog/collection-dialog.component.ts, clients.code-workspace, libs/common/src/auth/login-strategies/password-login.strategy.ts, libs/common/src/state-migrations/migrator.ts, package-lock.json, package.json
https://github.com/bitwarden/clients/pull/7564 with prettier formatting changes
=> [deps] Autofill: Update prettier to v3.2.2

README.md
```
```
Fixes errors in documentation related to the recent change of the primary branch's name from `master` to `main`.
- **README.md:** Correct links and wording
Additionally, while I was there, correct text styling of the word/name GitHub.
No
n/a
=> [PM-5763] Fix branch links

apps/web/src/app/layouts/header/web-header.component.html, apps/web/src/app/layouts/header/web-header.stories.ts
```
```
Remove title slot from header and add title-prefix slot instead.
=> [CL-167] Replace title slot with title-suffix for web header

libs/common/src/platform/services/crypto.service.ts, libs/common/src/platform/state/implementations/specific-state.provider.spec.ts, libs/common/src/platform/state/key-definition.spec.ts, libs/common/src/platform/state/key-definition.ts
```
```
Fix cache key to be unique per instance per user, right now it will return the same cache key for each user, therefore returning the first instance of `SingleUserState` no matter which user it was requested for.
- **key-definition.ts:** Fix logic to include the user id when there is one
- **key-definition.spec.ts:** Add test asserting unique cache keys.
=> Fix SingleUserStateProvider

apps/web/src/connectors/duo-redirect.html, apps/web/src/connectors/duo-redirect.scss, apps/web/src/connectors/duo-redirect.ts, apps/web/webpack.config.js
- New feature development
Creates a Duo redirect connector
- `apps/web/src/connectors/duo-redirect.ts` - add duo-redirect to handle browser/web and mobile/desktop
- `apps/web/src/connectors/duo-redirect.html` - add HTML
- `apps/web/webpack.config.js` - add to webpack
https://github.com/bitwarden/clients/assets/102181210/b6488629-592f-43e8-82a5-24153cda8604
=> [PM-5384] Create Duo Redirect Connector

apps/web/config/development.json, apps/web/webpack.config.js
```
```
Allow list connection src to local dev server for dev web client
=> Enable websocket connection in dev

clients.code-workspace
```
```
With https://github.com/bitwarden/clients/pull/7255 a change to the `clients.code-workspace`was merged, which prettier is now complaining about. This is the result from running `npm run prettier`.
=> Fix linting issue on main

libs/common/src/platform/services/cryptography/encrypt.service.implementation.ts
```
```
Fix a failing lint in `main`
- `libs/common/src/platform/services/cryptography/encrypt.service.implementation.ts` - fix a failing lint in main
=> fix const lint

libs/common/src/platform/state/implementations/default-active-user-state.spec.ts
```
```
The test always fails locally due to first setting a local time, and then fetching it through UTC which may have different timezones.
=> Fix DefaultActiveUserState test always failing locally

libs/components/src/navigation/nav-item.component.html
```
```
Add title tooltip so users can read truncated text in `bit-nav-item`
=> [CL-174] add title to bit-nav-item

.github/codecov.yml
```
```
Ignores Jest spec files for code coverage.
- Please check for formatting errors (`dotnet format --verify-no-changes`) (required)
- If making database changes - make sure you also update Entity Framework queries and/or migrations
=> Configure Codecov to ignore tests

clients.code-workspace
prettier didn't like this one, now we have lint build failures in main:
https://github.com/bitwarden/clients/pull/7475/files#diff-9f8fb9b6d99a405254d090b9cd4578c0a5b297da96e4b3e98a609447053501c7
=> Bug - Fix build lint failure for prettier formatting

.github/workflows/version-bump.yml
```
```
A couple of the steps for approving and merging the auto-generated PR were missing logic for when to run.
- **.github/workflows/version-bump.yml:** Add `if` keys to both the `Approve PR` and `Merge PR` steps.
=> Add proper logic for PR steps

apps/desktop/electron-builder.json
```
```
I bumped Electron with https://github.com/bitwarden/clients/pull/7584 and forgot to also update the version in electron-builder.json, which lets a verify build job fail.
=> Bump electron version in electron-builder.json

apps/web/src/app/core/core.module.ts
```
```
The web state overrides added in #7669 should have been using `OBSERVABLE_MEMORY_STORAGE` but state providers using their own implementation of memory storage in #7731 made this mistake more obvious. 
- **apps/web/src/app/core/core.module.ts:** Use State provider specific injection token instead of the normal `MEMORY_STORAGE` one.
=> Use `OBSERVABLE_MEMORY_STORAGE`

libs/components/src/layout/layout.component.html, libs/components/src/navigation/nav-item.component.html, libs/components/src/navigation/nav-item.component.ts
```
```
Style improvements for the CL nav-item:
- use **inset** focus ring when `:focus-visible`
- use lighter active background color in the secondary bit-layout variant 
- add hover background color to nav items
https://github.com/bitwarden/clients/assets/17113462/5e17b952-86b3-40fa-abb0-8e1c4a32ab4d
=> [CL-156][CL-176] update bit-nav-item styles

apps/web/src/connectors/duo-redirect.ts
```
```
[PM-5384](https://bitwarden.atlassian.net/browse/PM-5384)
Refactor duo redirect connector to use messaging to communicate with browser extension similar to SSO process as `BroadcastChannel` can only communication on same origins (not web to browser extension).
- **apps/web/src/connectors/duo-redirect.ts:** See above.
n/a
[PM-5384]: https://bitwarden.atlassian.net/browse/PM-5384?atlOrigin=eyJpIjoiNWRkNTljNz …
=> Auth/PM-5384 - Refactor duo redirect connector to work for browser extension

.husky/pre-commit, package-lock.json, package.json
Update husky hooks. Relates to #7687
Upgrade husky to 9.x and update the hooks, as suggested [here](https://github.com/typicode/husky/releases/tag/v9.0.1).
- **.husky/pre-commit:** Following upstream instructions.
- **package.json:** Following upstream instructions.
=> Update husky hooks

README.md
```
```
Prevent link underlines below the badges.
Remove the whitespace inside the anchor tags.
Before and after:
=> [PM-5943] Fix badge links

apps/cli/src/commands/completion.command.ts
Fix shell completions in #7329. The function bodies and case blocks were previously populated with Typescript. This now generates valid Zsh completions that are identical to what the prod CLI produces.
- **apps/cli/src/commands/completion.command.ts:** Fix Zsh completions.
=> [PM-5823] - fix shell completions

libs/common/src/platform/services/crypto.service.ts
```
```
Clear `everHadUserKey` on logout. This state was migrated to state providers.
https://github.com/bitwarden/clients/assets/24985544/ebf8e896-d86e-4434-b06a-638403e12d06
=> [PM-5995] Clear everhaduserkey on logout

libs/components/src/layout/layout.component.html
```
```
Remove `position: fixed` from `bit-layout`'s sidebar to make the main content viewable at smaller screen sizes. 
Before:
https://github.com/bitwarden/clients/assets/17113462/0b2e4547-953c-436e-8d03-2b3bce846cd1
After:
https://github.com/bitwarden/clients/assets/17113462/037381dc-ba56-4ea1-913c-857ccab8c280
=> [CL-175] remove position fixed from sidebar

apps/web/webpack.config.js
```
```
We already include the `DEV_FLAGS` during development in our Browser and Desktop webpack configs -- this updates the Web client's config to behave the same way.
- **apps/web/webpack.config.js:** Include `DEV_FLAGS` when in `development` environment.
=> Include DEV_FLAGS in webpack.config for Web 

libs/common/src/state-migrations/migrate.ts
```
```
Add `await` so that if the if the `migrate` function is awaited, migrations are guaranteed to have finished before the promise resolves.
- **libs/common/src/state-migrations/migrate.ts:** Add `await`
=> [PM-6032] Add Missing `await`

apps/desktop/src/app/app.component.ts
```
```
Fix authService.logOut not being called
=> [PM-6034] Fix authService.logOut not being called

apps/web/src/connectors/sso.ts
```
```
Try to resolve [PM-5976](https://bitwarden.atlassian.net/browse/PM-5976). Only try to initiate browser SSO when document is ready to avoid race condition between the browser extension content script message listener being registered and the browser SSO initiating message being sent.
We suspect that this is the same race condition issue that we tried to fix previously as part of [PM-5597](https://bitwarden.atlassian.net/browse/PM-5597) (#7506). 
Potentially related PR:
- #7346 
- **apps/web/src/connectors/sso.ts:** Modify browser extension SSO initialization logic to check if the document is ready before trying to send the browser extension SSO initialization message to the browser extension content script. 
- Please add **unit tests** where it makes sense to do so (encouraged but …
=> Auth/PM-5976 - Safari Browser SSO Initialization Race Condition Attempted Fix 

apps/browser/src/autofill/content/content-message-handler.ts, apps/web/src/connectors/sso.ts
```
```
Try to resolve [PM-5976](https://bitwarden.atlassian.net/browse/PM-5976) by implementing a ping system to determine when the browser extension content script is ready to receive the SSO auth result. 
Previous fix attempt: #7793
We suspect that this is the same race condition issue that we tried to fix previously as part of [PM-5597](https://bitwarden.atlassian.net/browse/PM-5597) (#7506). 
Potentially related PR:
- #7346 
- **apps/browser/src/autofill/content/content-message-handler.ts:** Add `checkIfReadyForAuthResult` message check  which will send `readyToReceiveAuthResult` back. 
- **apps/web/src/connectors/sso.ts:** Add ping to check every 50 ms for 10s to try and determine if the browser extension content script is ready to receive the SSO auth result. …
=> Auth & Autofill / PM-5976 - Safari Browser SSO Initialization Race Condition Attempted Fix 2

apps/web/src/app/auth/trial-initiation/content/logo-cnet-5-stars.component.html
```
```
The enterprise vauilt page was updated recently in 2023, but there was an oversight in the CNET review year where it was labeled as 2023 when it should be 2024.
- `logo-cnet-5-stars.component.html`: Update the year in the CNET review to 2024
=> [PM-5803] Update year in CNET review to 2024

.github/workflows/version-bump.yml
```
```
This PR updates the logic of the `Version Bump` workflow so that the PR containing the version bump is only created if we are not cutting `rc` **OR** if we are cutting `rc`, but it does not yet exist.  There are further checks in the `cut_rc` job that make sure the versions have been bumped by the PR being merged before cutting `rc`.
- **.github/workflows/version-bump.yml:** See above.
=> DEVOPS-1696  - Fix Version Bump workflow

apps/browser/src/popup/services/services.module.ts, libs/angular/src/services/jslib-services.module.ts
=> Properly set up StateProvider dependency for OrganizationService

apps/browser/src/popup/settings/folders.component.html
```
```
Refactored the folders component template so we avoid multiple subscriptions to the `folders$` observable.
=> Refactored folders component template to use a single subscription

.github/workflows/release-cli.yml, .github/workflows/release-desktop.yml
```
```
This PR updates the input description formatting on the Release Desktop and Release CLI workflows.
- **.github/workflows/release-cli.yml:** Update input description formatting.
- **.github/workflows/release-desktop.yml:** Update input description formatting.
=> Update input description on release workflows

apps/web/src/app/admin-console/organizations/settings/account.component.html
> Remove beta badge in preparation for soft release
- **account.component.html**: Removed `span` containing badge
=> [AC-2192] Remove collection management beta badge

.github/workflows/version-bump.yml
```
```
This PR fixes the `while` loop logic for verifying the version has updated.
* **.github/workflows/version-bump.yml:** Fix `while` loop logic.
- Please check for formatting errors (`dotnet format --verify-no-changes`) (required)
- If making database changes - make sure you also update Entity Framework queries and/or migrations
=> Version Bump workflow - Fix while loop logic

libs/common/src/platform/services/crypto.service.ts
```
```
clear the `everHadUserKey` for the logged out user, not the active one.
=> clear ever had user key for logged out user instead of active

.github/workflows/build-browser.yml, .github/workflows/build-cli.yml, .github/workflows/build-desktop.yml, .github/workflows/build-web.yml
```
```
Remove the 4 CLOC jobs. Pending review if anyone needs it if so we'll add a workflow for it.
=> Remove CLOC jobs

.checkmarx/config.yml
```
```
Exclude tests from Checkmarx
=> Exclude tests from checkmarx

.checkmarx/config.yml
```
```
Exclude `**/spec/**`, `apps/desktop/native-messaging-test-runner` from checkmarx.
=> Improve checkmarx config

libs/common/src/enums/notification-type.enum.ts, libs/common/src/models/response/notification.response.ts, libs/common/src/services/notifications.service.ts
```
```
See #3794 for context.
=> [AC-2184] Add NotificationType.SyncOrganizations

libs/common/spec/fake-state-provider.ts, libs/common/spec/fake-state.ts
```
```
Improves fake derived state class for testing purposes. The fake now watches the provided parent observable for any data changes, allowing control through the injected parent.
=> Link derived state fake to parent observable.

apps/web/src/app/layouts/product-switcher/product-switcher.stories.ts
```
```
- Update mock org data in the product switcher stories to work with the new AC option. 
- Rename stories to better convey the goal of each story
=> fix product switcher stories

apps/browser/src/_locales/en/messages.json, apps/browser/src/auth/popup/two-factor.component.ts, apps/browser/src/autofill/content/content-message-handler.ts, apps/desktop/src/auth/two-factor.component.ts, apps/desktop/src/locales/en/messages.json, apps/web/src/app/auth/two-factor.component.ts, apps/web/src/connectors/duo-redirect.ts, apps/web/src/locales/en/messages.json, libs/angular/src/auth/components/two-factor.component.ts
```
```
This PR has two purposes.
The first is the client side changes of using the `state` parameter of the duo authentication process. This ensures session validity during the duo redirection process. Server PR in bitwarden/server#3806
The second is making desktop and browser show a handoff message in the connector after the duo authentication. We can't use the same way as web because browser and desktop can't set cookies. Instead, we open a new tab in the duo redirect connector that will set a cookie and redirect the user to the duo connector from there.
https://github.com/bitwarden/clients/assets/24985544/5c0ac90e-ccf3-456d-a7dd-e3ed337d6be6
https://github.com/bitwarden/clients/assets/24985544/29925c31-70bc-4157-946a-f56d3ae0b0b0 …
=> [PM-6302, PM-6303] Add duo state and connector message on browser/desktop

.checkmarx/config.yml
```
```
The checkmarx config for native-messaging-test-runner didn't work. Adding wildard globs.
=> Fix checkmarx config

apps/web/src/connectors/duo-redirect.ts
```
```
Hide hand off message in mobile.
=> only show hand off message on desktop

.github/CODEOWNERS
```
```
Add Autofill Team as Codeowners of Autofill Libs Path
- **.github/CODEOWNERS:** Updating CODEOWNERS to reference the autofill team as owners of the recently introduced autofill settings service
=> Add Autofill Team as Codeowners of Autofill Libs Path

apps/web/src/app/tools/send/access.component.html
```
```
Add `rel="noreferrer"` to register link on send access.
=> Add rel=noreferrer to send register

apps/web/src/app/core/web-file-download.service.ts
```
```
Checkmarx complains about this method not using noreferrer, so we might as well add it. This shouldn't be exploitable in the first place since the target is a blob but in the event this was circumvented this adds an additional protection.
=> Add rel noreferrer to download link

jest.config.js
```
```
Our coverage reports only contained files included by tests, this caused the project to have an inaccurate coverage percentage. This change ensures every typescript file under `src` are included in the coverage report which should represent our coverage more accurately.
=> Configure coverage to count everything under src

apps/browser/src/_locales/en/messages.json, apps/browser/src/auth/popup/two-factor.component.html
```
```
Bringing Browser up to spec with Figma designs.
- **message.json:** changes message for duo and renamed key to better match function
- **two-factor.component.html:** changed the logic to show a consistent message to users of either Organization or Individual.
=> [PM-6219] Fix message in duo browser 2fa component

apps/browser/src/platform/services/browser-state.service.ts
```
```
This PR removed the setting of a session-synced subject but failed to remove session sync from the browser instance of state service.
=> Fix #7970 browser builds
