src/_locales/sv/messages.json

Added "none"-folder translation and replaced "View Site" with "View login" to make more sense and to reflect the mobile translations. I also changed the URI translation slightly to make more sense to people who might not know what an URI is; it basically says "URI (link)" now instead of just "URI".

Swedish translation changes and fixes #1

---

src/_locales/fi/messages.json

The "submit" meaning was okay in the Create Account screen, but not quite when the re-entering the master password (when the vault has been locked). Now it fits both.
Made the "lost2FAApp" translation less "clunky", more friendlier towards the user.

Changed translation for "submit" & "lost2FAApp"

---

src/popup/app/tools/views/toolsPasswordGenerator.html
src/services/passwordGenerationService.js

i see two problems here - the ``options.ambiguous`` boolean is set to ``true`` when "avoid ambiguous" is checked, however the code has:
```
var numberCharSet = '23456789';
if (o.ambiguous) numberCharSet += '01'; 
```
this logic is reversed, it should be ``if (!o.ambiguous) ...``.  i guess the meaning of that boolean is.. ambiguous.
--
second issue appears to be the max bound of ``randomInt(min, max)``.
it returns results between ``min`` and ``max - 1``.  you can see this easily by running ``randomInt(0, 1)`` in a loop; the current implementation only returns 0.  (note this bug effectively disables the "shuffle" block).
the fix should be to increase the range by 1: ``var range = max - min + 1;``
Fixes issue #97

Fix password generation's handling of the ambiguous option.

---

src/_locales/it/messages.json

When running master on a local Firefox, about:debugging refused to load it with the following error:
> 1489377078449   addons.webextension.<unknown>   ERROR   Loading extension 'null': Loading locale file _locales/it/messages.json: SyntaxError: JSON.parse: bad control character in string literal at line 135 column 36 of the JSON data
It turns out that is a tab character - this patch replaces it with a space.

Remove tab character from Italian translation

---

src/popup/app/tools/toolsPasswordGeneratorController.js

LastPass lets me generate passwords up to 100 chars in length, so only having 64 chars to play with is a bit of a regression for me.

PasswordGenerator: Increase max length from 64 to 128

---

src/popup/app/current/currentController.js
src/popup/app/current/views/current.html

For some sites I have over 10 "matching" sites because the matching is done on the TLD and ignores subdomains, making it difficult to find the single login I need to use.
This patch sorts the list of logins so exact matches (of which there will typically be zero or 1) appear at the top of the list. Issue #77 also suggested this as a short-term solution to fully featured sub-domain support.

Show exact matches for the URL at the top of the matching sites list

---

src/background.js
src/services/cryptoService.js

#272
officially supported by only firefox so far: [openPopup](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/browserAction/openPopup).
This function also exist on Chromium as I tested but it is not in the docs so I guess I shouldn't include it.

firefox: show popup when click "vault is locked"

---

README.md
package.json
webpack.common.js

Changed the npm scripts to also run `gulp build` and changed webpack to only copy html files for the popup application. The readme has also been updated with the proper commands and an additional section on how to build the extension for production was added.

Minor improvements to Typescript

---

src/popup/app/app.js
src/popup/app/components/componentsModule.js
src/popup/app/config.js
src/popup/app/tools/tools.component.ts
src/popup/app/tools/tools.controller.ts
src/popup/app/tools/tools.module.ts
src/popup/app/tools/toolsModule.js
src/popup/app/tools/views/tools.html

I decided to split this PR in three commits.
1. In the first commit https://github.com/Hinton/browser/commit/1e6ffbbbaca6d0e2970fa32ace0983f22ccee130, I convert the controller into TypeScript.
2. Afterwards in https://github.com/Hinton/browser/commit/1e63ad623bfe75345f7badd0a37a1ae0cd4d351b, I removed `$scope`, moved functions out into the class, and updated the template to use `$ctrl`.
3. Lastly in https://github.com/Hinton/browser/commit/f12b1d10c21bf33175a1a939e57e75e673a1534f, I changed the Controller into a Component.
For now we have to use a work-around in ui-router and set a template string to create the component, however version 1.0 or ui-router has native support for components which should improve support for variables and more.

[Typescript] Convert tools page to TS 

---

src/popup/app/settings/options.component.html

The options component had conflicting/duplicate id attributes. This caused problems when toggling checkboxes by clicking on their corresponding labels. The following GIF demonstrates this behavior.

Fix checkbox toggling

---

src/_locales/en/messages.json
src/popup/app/services/services.module.ts
src/popup/app/vault/vaultAddCipherController.js
src/popup/app/vault/vaultEditCipherController.js
src/popup/app/vault/views/vaultAddCipher.html
src/popup/app/vault/views/vaultEditCipher.html

This PR implements an initial proof of concept password check using the https://haveibeenpwned.com/Passwords API.
Instead of sending the password to an external service, the first 5 characters of the SHA-1 hash gets sent. The service returns all known hashes beginning with that combination. Allowing the client application to lookup if the password exists in the response and determine if it has been previously leaked.
The approach is explained in more detail at: https://www.troyhunt.com/ive-just-launched-pwned-passwords-version-2/#cloudflareprivacyandkanonymity
~~The initial PoC puts all of the logic inside the editCipher controller, a more logical place would be inside a new service. I would also want to explore if it's possible to return the amount of times it has been leaked inside the …

Integration with Have I been pwned

---

src/popup/app/vault/vaultViewCipherController.js

This is a pretty simple PR. I'm migrating from 1Password to Bitwarden, and I noticed that while 1Password has a constant-length password mask, Bitwarden's leaks the length of the password even when it's masked. This commit simply changes to a constant-length mask.

Don't leak password length through mask

---

src/services/autofill.service.ts

I encountered these tags on oui.sncf, the french train company :
- `numCarte` (credit card number)
- `EXPIRATION_MONTH`
- `EXPIRATION_YEAR`
- `codeSecurite` (CVV)

Add some other french tags for credit card.

---

src/content/notificationBar.ts

Since the notification bar is added inside of the active page, page specific styles may override how the iframe is rendered in an undesirable way.
I came across this when logging in an internal corporate web-app we're using which for some reason has a global css setting of `iframe { min-height: 349px }` because nobody anticipated that 3rd party DOM elements would be injected to the page.
This modification should have no impact other than negating these global styles.

Precaution against iframe creating blank space on the page

---

src/popup/vault/view.component.html

By default shows Card Security Code masked in the same way as Passwords.  ([bitwarden/desktop issue 78](bitwarden/desktop/issues/78))
Depends on [bitwarden/jslib#5](bitwarden/jslib/pull/5)

Masking Card Security Code in browser extension

---

src/services/autofill.service.ts

LDLC is a french tech shopping website, used by many customers and professionals in France.

Add fields for LDLC

---

src/background/runtime.background.ts

Hello,
Currently when you save a new login while being prompted after a login, it uses the full domain. By removing the leading `www.` I would find it to be easier  to manage multiple records from the same domain that uses both `www` and `non-www`, when sorted.
Thank you.

Remove leading www. from name on saveAddLogin

---

src/background/runtime.background.ts

In the last PR I introduced a bug, which would match `www` and any character after it. This fixes the match only with a literal `.`
Sorry about that.

Fix match the character . literally

---

package-lock.json

Upon cloning the repo, I was unable to build due to [this error](https://pastebin.com/VLZS4bXd).
As found [here](https://stackoverflow.com/questions/53146394/), updating the "natives" package to 1.1.6 fixes this issue.

Update natives package to fix build

---

src/popup/vault/add-edit.component.html

This fixes #847 by adding the `trackBy` option to the `ngFor` directives used for URIs and custom fields.
https://github.com/bitwarden/jslib/pull/27 is required.

Fix disappearing fields

---

src/notification/bar.scss

In Mac OS there is a wider variant of scrollbar on hover. Commit fixes overlapping of close button with scrollbar in chrome.
example of overlay:

Fix overlapping of close button with scrollbar

---

src/services/autofill.service.ts

When using autofill on certain websites (such as [this website](https://www.mybenefitscalwin.org/)), the autofill feature will put the user's entire password, even if said password is longer than the specified limit. I created a password for this website (20+ characters), and I was unable to login until I only used the first 20 characters.
This PR simply caps the length of a password when selecting to autofill a password field, if the form field restricts the length of the password

Capping length of Autofilled Passwords when necessary

---

package-lock.json
package.json
src/_locales/en/messages.json
src/popup/scss/variables.scss
src/popup/settings/options.component.ts

This PR maintains consistency across all the different products of Bitwarden (Desktop and Mobile apps) by adding support for the Nord theme.
**Preview**

Add support for the Nord Theme

---

src/popup/scss/misc.scss
src/popup/vault/view.component.html

In collaboration with the [pullrequest 51 at jslib](https://github.com/bitwarden/jslib/pull/51) this enables the possibilty to drag the username, password and totp from the extension into fields on the website or anywhere else a drag can reach.
A possible use case for avoiding the clipboard here are clipboard synchronization apps, where a password should not appear.

Enabled drag of username, password and totp in browser extension

---

src/notification/bar.scss

The save password prompt is no longer shown in print views.
Fixes #1034

Hide save password notification bar when printing the page

---

src/_locales/en/messages.json

This is the second part of the fix for https://github.com/bitwarden/browser/issues/899

Fix for Firefox "Manage Extension Shortcuts" UI (part 2)

---

azure-pipelines.yml

This step may be redundant since Gulp is already included as a devDependency for the project. The step is currently causing builds to fail so it's probably best just to remove it

Remove gulp global install step from Azure pipeline

---

package.json
src/_locales/en/messages.json
src/popup/app-routing.animations.ts
src/popup/app-routing.module.ts
src/popup/vault/add-edit.component.html
src/popup/vault/add-edit.component.ts
src/popup/vault/view.component.html
src/popup/vault/view.component.ts

> Allow cloning of personal items within the browser extensions. Cloning of organizational items should be restricted.
- **package.json**: Update sub:pull script to include target branches
- **messages.json**: Added "Clone" and "Clone Item" strings
- **app-routing.animations**: Added "clone-cipher" routing animations for views in/around clone item flow
- **app-routing.module**: Added "clone-cipher" routing information
- **add-edit.component.html**: Enabled/disabled fields based on clone mode
- **add-edit.component.ts**: Set cloneMode before loading shared add-edit component and adjusted back navigation
- **view.component.html**: Added "clone item" row
- **view.component.ts**:  Added clone method callback and adjusted cloneMode query parameter

Implement personal item cloning capability

---

src/background/commands.background.ts
src/background/contextMenus.background.ts
src/background/main.background.ts
src/popup/generator/password-generator.component.html

>Make sure the Password Generator enforces the specific rules set by an Organization for password generation. In the case of multiple Organizational rules, apply the stricter option.
- **commands.background.ts**: Updated call to `getOptions` to handle tuple return object
- **contextMenus.background.ts**: Updated call to `getOptions` to handle tuple return object
- **main.background.ts**: Added `policyService` to `passwordGeneratorService` constructor
- **password-generator.component.html**: Added `disabled` logic to all of the policy-tracked checkboxes. Adjusted the number count and special count input fields to `saveOptions` on `blur`. `input` changes weren't properly being tracked.

Enforce Password Generator Policy Options

---

src/_locales/en/messages.json
src/popup/generator/password-generator.component.html

> Add missing components for passphrase policy. Use existing data structures/patterns to implement a shared password generator (password/passphrase)
- **jslib**: Updated from 44b86f5 -> 36241e9
- **password-generator.component.html**: Updated existing fields to respect potentially enforced options for passphrase generation

Enforce Passphrase Policy

---

package.json

Tried setting up the symlink on Windows and noticed the npm script failed with unknown command... fixed the script to get that working.
rmdir vs. rm, /S /Q vs. -rf.

Fixed Windows Symlink command in package.json for npm scripts

---

src/background/main.background.ts

Fixes a bug where a context menu entry (auto-fill, copy password, etc.) would display incorrectly when it included an ampersand (&). I fixed it by doubling every occurring ampersand, as that produces one *single* ampersand in menus.
**I have only verified this behavior in Firefox 74.0.1 for Linux; I have not tried any other version or browser.**
Here is a screenshot from before the fix: ![](https://files.catbox.moe/xe8frk.png)
Here is how it looks after the fix: ![](https://files.catbox.moe/wy8xlr.png)
On line 599 I used a Regular Expression to achieve a way to replace *all* occurrences of a substring within a string.
Online I could find [one other implementation that didn’t use RegEx](https://stackoverflow.com/a/17606289), but according to [a provided benchmark](https://jsben.ch/LFfWA), …

Add context menu entry sanitation for ampersands (&)

---

src/_locales/en/messages.json
src/background/main.background.ts

> Update the context menu "locked" state to also look for the user being logged out. Update the context message accordingly.
- **messages.json**:  Added vault logged out string
- **main.background.ts**: Changed function name to better suit its use cases. Added conditional for determining which string to use based on lock vs log out state.

[Auto-Logout] Updated Context Menu State

---

src/_locales/en/messages.json
src/popup/vault/ciphers.component.ts
src/popup/vault/groupings.component.html
src/popup/vault/groupings.component.ts
src/popup/vault/view.component.html
src/popup/vault/view.component.ts
src/services/browserPlatformUtils.service.spec.ts

This change adds the soft-delete and restore actions to the browser extension client, as well as the trash view.
- **messages.json**: Added appropriate message/UI strings for display and i18n localization
- **ciphers.component.ts**: Add handler for "trash" view and prevention of adding new ciphers into trash
- **groupings.component.html**: Added trash grouping and trash "folder" to bottom of groupings component for navigation to the trash bin
- **groupings.component.ts**: Gather count for deleted items for consistency of display (small perf hit), but handle the deleted item count in state. Added handler for navigation to trash and prevented soft-deleted ciphers from showing in other folders, search or counts in primary `.forEach()`
- **view.component.html**: Add delete button for all …

[Soft delete] - Ads trash bin to browser extension

---

src/_locales/en/messages.json

Updated the deleted item toast message to indicate sent to trash (vs. deleted).

[Soft Delete] - Deleted toast message trash

---

src/_locales/en/messages.json
src/popup/settings/settings.component.html
src/popup/settings/settings.component.ts

> Users selecting the `Log Out` timeout action need to be made more aware of the necessary requirements for accessing their vault next time.
- **settings.component.ts**: Added warning dialog if selected vault action is `logOut`. 
- **settings.component.html**: Added element ref tag
- **messages.json**: Added title and body for warning dialog

[Auto Logout] Added warning dialog for log out action

---

package-lock.json
package.json
webpack.config.js

**What is fixed:**
Warning and error from npm and build log:
1. warning
`warning: Since webpack v4 the extract-text-webpack-plugin should not be used for css. Use mini-css-extract-plugin instead.`
2. error
`Entrypoint undefined = extract-text-webpack-plugin-output-filename...`
New plugin implementation documents:
[https://webpack.js.org/plugins/extract-text-webpack-plugin/#usage](https://webpack.js.org/plugins/extract-text-webpack-plugin/#usage)
[https://webpack.js.org/plugins/mini-css-extract-plugin/#advanced-configuration-example](https://webpack.js.org/plugins/mini-css-extract-plugin/#advanced-configuration-example)

fix: webpack.config.js plugin

---

src/browser/browserApi.ts
src/safari/safari/SafariExtensionViewController.swift

`getAssetUrl()` method is not referenced by any code anywhere any longer. Digging through git history it appears once upon a time it was used for showing icons stored via a local path. With that, nothing else raises the `'getAppPath'` message for the swift controller to handle; so that handler could be removed (which also seems to be the line of code from the app crash traces).
Besides that, I think I've address any of the last few places we're unwrapping `!` (unsafe) values without testing for `nil` first, so hopefully this either solves the issue, or the additional `NSLog()` will help trace it in the crash logs again if it continues crashing (not sure how else to get logging to work properly with Safari app extensions in this context).

Attempt fix for safari app extension crash

---

webpack.config.js

Prior changes updated the minified CSS filename from webpack config which broke the Safari browser plug-in once distributed/packed/signed by introducing a hash into the filename but no has was tokenized in the index.html using webpack either, reverting to the primary file name `'[name].css'`

Corrected webpacked CSS filename

---

src/content/shortcuts.ts

For whatever reason , the `Cmd + 9` keybinding doesn't work, so moving autofill to `Cmd + 8`. Resolves https://github.com/bitwarden/browser/issues/1285

cmd + 8 to autofill for safari

---

src/safari/safari/SafariExtensionViewController.swift

Based on Apple Developer Support's feedback I've cleaned up a bit of the type unwrapping to instead use `if let` and `guard let` accordingly vs. explicit type unwrapping with `!`. This may not resolve the application crash issue but it also may.
Related to https://github.com/bitwarden/browser/issues/1021.

Cleanup swift type unwrapping

---

src/services/autofill.service.ts

Many sites have one time password fields for Two Factor Authentication. A common name for those fields is OneTimePassword or some variant. If these fields were commonly of type "password" it would not be significant. However, since they are commonly of type "text", it is a security risk for users to auto fill these fields.

Avoid a common One Time Password field name

---

src/popup/vault/view.component.html

Resolve an issue involving users not being able to highlight notes on the view screen. This seems to be cause by a Firefox bug, and isn't specific to this page or to the Bitwarden extension.
Changed plain text fields to disabled inputs on the view screen. Made this change to notes per the issue, as well as the other fields for consistency. 
The only visual difference found is the draggable expand for the textarea field, everything else remains the same.
Resolves #1269

Addressed issue #1269

---

src/popup/scss/misc.scss

This PR fixes issue #1308 
Duplicate password reveal icon shown on Microsoft edge is fixed by using ms specific css selector -ms-reveal & marking it as display:none
This change fixes the issue for all password input fields throughout the extension.

Fix edge double password reveal buttons issue #1308

---

src/services/browserPlatformUtils.service.ts

When clearing the clipboard at an interval, the resulting clipboard clear should be '', nothing. Chrome was interpreting nothing as ' ', an empty space. To mitigate this, if Chrome, we transform the '' to unicode \u0000, or a null. 
**src/services/browserPlatformUtils.service.ts** - Modifications made on clear, if '' and Chrome are detected, it sets the text to unicode null.
Closes #1234

Modified Chrome to pass in null unicode on clear

---

.gitignore

When packaging, debugging and deploying the Safari App Extension locally on macOS, you need the appropriate assets from the browser build output (web), but those should be ignored/not checked in. These are copied manually to the `src/safari/safari/app/` directory from the browser build output, however the only file that should be included in that source control is the placeholder, `src/safari/safari/app/popup/index.html`

Ignore local safari debugging/packaging assets

---

src/safari/safari/SafariExtensionViewController.swift

Fixes https://github.com/bitwarden/browser/issues/1338
Prior refactoring of swift code removed a completion handler for the `openTab()` method of `SFSafariWindow`, which even though may be `nil`, in this case passing `nil` explicitly results in a memory access exception. Passing in an empty handler resolves this exception.

Fix completion handler nil crashes SFSafariWindow

---

src/popup/components/action-buttons.component.html
src/popup/generator/password-generator-history.component.html
src/popup/vault/password-history.component.html
src/popup/vault/view.component.html

According to: bitwarden/desktop#490
Replace the "copy value" icon with fa-clone.
I discovered a UX-related icon problem in the browser extension.
On the vault list screen, the copy of the user ID is represented by a human outline icon and the copy of the password is represented by a key icon.
However, on the item details screen, the copy is represented by a clipboard icon. (From this PR, it changes to a clone icon.)
This is inconsistent and new users will have to mouse hover to know how the icon works.
This cannot be addressed by replacing the icon. I'll try to post this in the forums later.

Consistent: Replaced the clipboard icon with a clone icon to improve UX 

---

src/popup/accounts/lock.component.ts

Looks like one of the jslib contructor signature changes were missed when making the browser extension reverse compatible with the jslib updates around biometrics.

Fixed jslib compat changes for biometrics

---

src/safari/safari/SafariExtensionViewController.swift

Over the course of the last few weeks I've noticed and found that while several async methods in WKWebView and associated framework allow `nil` completion handlers, every once in a while, if `nil` is indeed provided, there are app crashes without much explanation. In that light, and given that the crash occurring in #1021 is happening when calling into the JavaScript world and dies within the WebKit internals; this leads me to believe that it may be relating to a missing completion handler with some perhaps hardware specific handling of the same which we're not able to reproduce.
Either way, it doesn't hurt to have the relatively empty completion handlers with a little bit of error logging in there just in case and I've tested to ensure there are no regression issues with the addition of …

Added logging and completion handler for JS

---

src/background/runtime.background.ts
src/services/abstractions/autofill.service.ts
src/services/autofill.service.ts

I wanted to contribute with something to the project (besides the premium subscription) and I saw [this open feature request](https://community.bitwarden.com/t/cycle-through-multiple-logins-when-auto-filling-with-keyboard-shortcut/34) so I decided to implement it myself 😄
Let me know any doubt, any problem or anything you see that could've been done in a better way 👍

Cycle through every login when using the auto-fill shortcut

---

src/content/shortcuts.ts

fixes https://github.com/bitwarden/browser/issues/701
This relates to adding additional support for keyboards such as AZERTY, or QWERTY with a German or French layout, etc. where the existing hotkeys do not work due to additional key combinations that are already bound or simply not possible.
⌘8 does't work on all foreign keyboard layouts such as AZERTY, but supports some alternative keyboards
⌘\ also doesn't work on all keyboards
⇧⌘P, however, is not yet bound in Safari by default and does seem to work for all mentioned keyboards (so far).
Assuming this fix allows more possible keyboard combinations for macOS keyboards across regions with one of the 3 options since we can't control bindings themselves from an extension. In the future, we may be able to make this configurable through the …

Added Cmd+Shift+P for autofill in safari

---

src/_locales/en/messages.json
src/popup/vault/view.component.html
src/popup/vault/view.component.ts

I have added "Autofill" and "Autofill and Save" buttons in the View Item screen in the Vault. See [my post in the community forums](https://community.bitwarden.com/t/autofill-and-autofill-and-save-buttons-for-the-browser-extension-vault/13385) for more information about the proposal.
This makes it quicker and easier for users to:
- autofill login credentials where there are no saved URIs for those credentials
- save the URI of the current page for easier autofilling in the future
This reflects a similar feature that already exists in the mobile app.
I have used the existing autofill and cipher services.
- Tested manually in Firefox and Chrome
- Passed the test:watch script in Firefox and Chrome.

“Autofill” and “Autofill and Save” buttons for the browser extension Vault

---

src/background/main.background.ts
src/background/runtime.background.ts
src/browser/browserApi.ts

There are three issues addressed here:
1. The CryptoFunctionService abstraction was not publicly available in the background main service, so it was not accessible when trying to be resolved as a dependency to the popup angular app. This change exposes `cryptoFunctionService` as a public member of the background main service so that it can be resolved.
2. Opening the sso component on the SSO authResult used web extension API specifics (`chrome.tabs.create`) rather than the `BrowserApi` abstractions. Use `BrowserApi.createNewTab` instead.
3. The newly added `reloadOpenWindows` function used `chrome.extension.getViews({ type: 'sidebar' })` which only works with the Firefox sidebar. Opera doesn't work with this type filter. Switch to just `chrome.extension.getViews()` and reload them all.

fixes to SSO process

---

src/background/webRequest.background.ts

ref #1124 
Since filling HTTP basic auth credentials is non-interactive, this PR changes the default match detection rule for these operations to the more restrictive "Host", so that sub-domains are not matched. This can still be overwritten by the user if they desire by changing the match detection setting for that individual item back to "Base Domain". This would restore the current functionality that exists today.

change default match on basic auth to host

---

src/background/runtime.background.ts
src/popup/vault/current-tab.component.ts
src/popup/vault/view.component.ts
src/services/autofill.service.ts

Closes and resolves #842. The fields marked as `autocomplete="new-password"` should not be auto-filled with an existing password unless auto-fill is explicitly executed by a command or context menu action by the user. In other words, having automatic auto-fill on page load enabled should not populate fields on a user registration form OR reset password form unless the user expressly asks for it.
As a Bitwarden user who relies on the ability to create multiple accounts on the same site, I should not have my information or password automatically populated from another account (or last used account) in the `new-password` field for risk of creating a new user account with the same password so that I must manually enter a password or use Bitwarden's password generator feature to populate this …

Ensure auto auto-fill ignores new-password

---

src/safari/safari/SafariExtensionHandler.swift

This is a draft/potential fix for #1018 , but I'm no longer able to get my local Safari debug environment working (will have to play with that in a bit), however this _may_ work given pinned tabs have no container window, as a hack because any/every window can potentially own the tabs that are pinned (doesn't matter which window, just need 1 I believe), but need to ensure the index reference won't break anything else.

Potential fix for pinned tab auto-fill in Safari

---

src/services/autofill.service.ts

Relates to https://github.com/bitwarden/browser/issues/1372
Some non-password type fields are being autofilled as passwordLike erroneously. 
While I'm sure there will never be 100% coverage here these changes address the use cases mentioned in the linked issue, and sets us up to be able to better exclude certain unwanted fields from being autofilled in the future.
(also updated jslib)

beefed up restrictions on what is considered isLikePassword

---

tsconfig.json

The Ivy compiler breaks `onScroll` events for ngx-infinite-scroll plugin. Until we can figure out why or a fix, this change disabled the Ivy compiler.

disable angular ivy compiler

---

src/popup/vault/ciphers.component.ts
src/popup/vault/groupings.component.ts
src/services/autofill.service.ts

This is a recreation of the changes on https://github.com/bitwarden/browser/pull/1405 since that PR became stale and then I broke it horribly
It will resolve #1391
When using the search bar to launch a url & autofill the autofill process is not using the login that was clicked, it is using the last used login previous to the clicked login.
We can locally track last launched logins and get that data back for autofill

tracked last-launched ciphers for autofill

---

src/popup/accounts/set-password.component.ts
src/popup/accounts/two-factor.component.ts

> Currently, when a new bitwarden/org user is created, they are given a status of accepted. This can create issues for organizations trying to confirm the same user (which can't happen until they've set their master password). To alleviate the issue, change new user's orgUser status to invited until after they've set a master password.
- **jslib**: Update from 3bf322a to d84d6da
- **Components**: Update import/constructor to pass in active route

[SSO] New user provision flow jslib update (3bf322a -> d84d6da)

---

src/services/autofill.service.ts

Some german websites are using german input names :/
E.g. https://www.ingolstadt.de/tevisweb/select2?md=6 
For testing: 
1. select "Termin in der Zulassungsstelle" 
1. click on "Weiter"
1. select any date and time
1. use Bitwarden autofill for your identity

Add some german input field names

---

package.json

`npm run symlink:win` currently returns `Invalid switch - "jslib".`
`rmdir` appears to interpret `./jslib` as a switch rather than as an argument specifying the directory. Fixed by changing `/` to `\\`.

fix typo in symlink:win script

---

src/_locales/de/messages.json
src/_locales/en/messages.json
src/background/commands.background.ts
src/content/shortcuts.ts
src/manifest.json

Pull Request for [Contribution - Add 'lock_vault' command](https://community.bitwarden.com/t/add-lock-vault-command-to-browser-extension/15325) (addresses Feature Requests: [1](https://community.bitwarden.com/t/add-shortcut-to-manually-lock-vault/15319) and [2](https://community.bitwarden.com/t/add-global-hotkey-to-lock-log-out-without-closing-the-browser))
This Pull Request will add an command called 'lock_vault' in the manifest file without suggestedkeys (as there seems to be a limit of 4 suggestedkeys). see: [Chrome Commands](https://developer.chrome.com/apps/commands#usage)
But it will be possible to manually add a shortcut to trigger the command and lock the browser extension manually in Chrome Configure Commands (chrome://extensions/configureCommands) or Firefox About Addons …

Add 'lock_vault' command

---

src/content/shortcuts.ts

We only want this shortcut binding to apply to safari. Others that use shortcuts, like vivaldi, use this shortcut for something already.
ref #1450

lock vault shortcut only for safari

---

src/popup/accounts/register.component.html
src/popup/scss/box.scss
src/popup/scss/misc.scss

Some follow-up tweaks to #1445 to simplify styling for left-aligned `box-content-row-checkbox`

box-content-row-checkbox styling for left aligned

---

src/_locales/en/messages.json

Align messages for item delete across platforms. Mobile's example of "Do you really want to send to the trash?" makes it clear that an item is only going to be soft deleted, so that was used everywhere.
* **messages.json**: Updated the `deleteItemConfirmation` message to Mobile's message.

Use mobile's trash message for item delete

---

src/background/runtime.background.ts

The helper method yields either 1) the configured web vault url or 2)
the configured server url. If neither are configured, null is returned,
which is already handled by defaulting to vault.bitwarden.com
Easier configuration of self-hosted SSO instances
* **runtime.background.ts** If only Server URL was configured, this did not fall back correctly to the configured server URL, but redirected to vault.bitwarden.com. This is fixed by the helper method getWebVaultUrl, which already exists in jslib

Use helper method to get web vault url

---

src/_locales/en/messages.json
src/background/main.background.ts
src/background/runtime.background.ts
src/popup/vault/add-edit.component.html
src/popup/vault/add-edit.component.ts

> Allow organizations to restrict user's from saving added/cloned items to their personal vaults. Remove the personal ownership option when this policy is enabled and the user is not an Admin/Owner of the organization.
- **messages.json**: Added error message
- **main.background.ts**: Updated constructor for `runtimeBackground` object
- **runtime.background.ts**: Added `policyService` and `userService` to the class constructor. Added return logic to cipher creation via notification bar.  Adjusted `responseData` being sent to the content scripts - made sure to include whether or not personal ownership is allowed. Added helper method for determining if personal ownership should be allowed via the notification bar.
- **add-edit.component.html**: Adjusted visibility to use …

[Policy] Personal Ownership

---

src/background/main.background.ts
src/content/sso.ts
src/popup/accounts/home.component.ts
src/popup/accounts/two-factor.component.ts
src/services/autofill.service.ts
tslint.json

Closes 2fa window if the window was opened as part of an sso login. Reduces the number of hanging tabs left open from sso flow.
Closes #1479 
* **main.background.ts**: linter fix, just removed from whitespace.
* **two-factor.component.ts**: subscribe to query parameters and alter onSuccessfulLogin event handler to close the current window.
This is a workaround until we can get browser extension sso to use the
toolbar popup.
main.background.ts is a linter autofix

Close 2fa window if redirected from sso login

---

package.json
src/background/main.background.ts
src/background/runtime.background.ts
src/popup/services/popup-search.service.ts
src/popup/services/services.module.ts

Use the default consoleLogService. jslib is moving toward requiring clients to specify a console logger. This change also includes the browser-process-hrtime dependency
* **package.json**: include `browser-process-hrtime`
* **main.background.ts**: define consoleLogService dependency. This just uses the base class in non-dev mode since there's no dev build concept currently existing in the browser extension.
* **runtime.background.ts**: linter fix
* **popup-search.service.ts/services.module.ts**: including new required ConsoleLogService dependency
Need to update jslib reference once bitwarden/jslib#221 is merged

Add ConsoleLogService dependency from jslib

---

src/popup/components/action-buttons.component.html
src/popup/components/action-buttons.component.ts

Offering copying of totp from context menu covers only one method-of-use. Offering another quick-copy button on the tabs/cipher list view closes this gap.
action-buttons are responsible for populating the quick-action buttons to the right of cipher names in the cipher list view.
* **action-buttons.component.html**: add another view to copy configured totp. Uses loginView.hasTotp to verify plaintext copy is allowed and valid.
* **action-buttons.component.ts**: Converts totp configuration code to totp, copies that password to the clipboard, and pushes a notification that a hidden field was copied.
Waiting on bitwarden/jslib#225

Add totp copy to clipboard button to cipher view

---

package-lock.json

Upgrade `bl` from `2.2.0` to `2.2.1`. To get rid of the following (potential from the Bitwarden's user perspective) vulnerability:
```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Remote Memory Exposure                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ bl                                                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ @microsoft/signalr-protocol-msgpack                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ @microsoft/signalr-protocol-msgpack > msgpack5 > bl          │ …
```

Upgrade bl: 2.2.0 -> 2.2.1

---

src/popup/app-routing.animations.ts
src/popup/components/action-buttons.component.ts
src/popup/vault/add-edit.component.html
src/popup/vault/add-edit.component.ts
src/popup/vault/share.component.ts
src/popup/vault/view.component.html
src/popup/vault/view.component.ts

Editing and Sharing a cipher simultaneously results in lost edits. Move
share button to the view page to resolve this confusion.
Previous routing caused the share form to be animated again on
submission, resulting in a stuttering page load. This method correctly
animates all transitions with the concession that the share page
always takes you back to the view page. This is not necessarily the current
behavior, but it is the most likely behavior in the current scheme
Implementing this is pretty simple copy-paste from `add-edit.component.ts`.
Animations on this were a bit of a journey. Current behavior loads in the share page twice with animations and hard-cuts back to the edit page. I wanted smooth in-out transitions for all button navigations.
The first issue is that the slide in …

Move share from edit to view. Fix animations

---

src/_locales/en/messages.json
src/background/main.background.ts
src/background/nativeMessaging.background.ts

The old implementation assumed that only a single browser extension was running, which resulted in the `sharedSecret` being constantly invalidated. This change assumes the browser sends a unique `appId` which is used to decide which shared secret to use.
Also display an error message informing the user to turn on desktop biometrics before browser biometrics can be enabled.
Depends on https://github.com/bitwarden/desktop/pull/615

Native Messaging - Support multiple extensions concurrently

---

src/background/nativeMessaging.background.ts

Due to a missing break statement the browser extension would show the fingerprint verification message instead of the communication interrupted error.
I also changed the return statement to break to be more consistent with the other cases.

Fix native messaging handling interuptions wrong

---

src/browser/safariApp.ts
src/content/sso.ts
src/popup/accounts/sso.component.ts
src/safari/safari/SafariExtensionViewController.swift

Closes #1473. Safari SSO sign on from browser is still broken. Full SSO process is triggered, but final tab open to the SSO extension component does not work. We need to get Safari responding correctly to messages in all contexts.
* **safariApp.ts**: webkit message handlers is not available from a tab opened to an extension resource. In this context, we should use safari.extension.dispatchMessage as done elsewhere.
* **content/sso.ts**: Safari app extension does not respond to chrome.runtime. Use dispatchMessage here too.
* **SafariExtensionsViewController.swift**: `createNewTab` messages for extension resources are delivered as path?query URIs only, which Safari does not interpret correctly. Detect these types of paths and navigate to the appropriate resource

Fix safari sso

---

src/services/autofill.service.ts

As #1441 pointed out, the comment `Only update last used index if doAutoFill didn't throw an exception` confuses maintainers/ contributors. 
https://github.com/bitwarden/browser/blob/74a9ff799227759628de01669208fc1e1ea14829/src/services/autofill.service.ts#L257-L271
This pull request attempt to improve the readability of the code in this section, to resolve #1441 .
This pull request renamed the variable for `doAutoFill` from _autoFillResponse_ to _totpCode_ as:
1. The **response** keyword implies the code may continue to execute with a failed-to-autofill state.
2. The return variable from `doAutoFill` can only be **TOTP** code or **null**, as described here: https://github.com/bitwarden/browser/issues/1441#issuecomment-717868796. Using totpCode as the variable name properly describe the …

Improved readability as #1441

---

src/background/nativeMessaging.background.ts

I forgot to catch some errors that could occur. I switched to a more generic check to avoid this issue in the future.

Native messaging, generic error handling

---

src/_locales/en/messages.json
src/popup/vault/add-edit.component.html

> To clear up any confusion while the `Personal Ownership` policy is enabled and in effect, a banner has been added to the `add-edit` component. Mimic the password generator banner.
- **add-edit.component.html**: `app callout` banner added to the top of the component
- **messages.json**: added banner string

[Policy] Personal Ownership banner

---

src/popup/components/action-buttons.component.ts

Resolves a bug introduced in https://github.com/bitwarden/browser/pull/1493 where it was not possible to copy *any* field from an item without TOTP.

Fix action buttons not working when TOTP is not available

---

src/popup/scss/base.scss

Small tweak to get the popover arrow to appear with the same background color as the header. Applies to Firefox.
Before:
After:

Popover arrow background color

---

src/_locales/en/messages.json
src/background/nativeMessaging.background.ts

If the desktop and browser applications are logged into two different accounts, the biometric unlock sequence would still work but send the wrong encryption hash which would result in the vault not decrypting secrets correctly.
This was solved by including the `userId` in `setupEncryption` which the desktop application verifies before allowing the communication to be secured. Which also necessitated a new error message.
Companion PR: https://github.com/bitwarden/desktop/pull/645

Handle desktop logged into a different account for biometrics

---

src/popup/scss/base.scss

https://github.com/bitwarden/browser/pull/1529 Set the body to have the same backgorund color as the header to resolve the popover arrow appearing with a different color in firefox. Unfortunately this had a bleed though effect on the login page.
Resolved by adding a background color to the app-root element instead which always appears.

Resolve login page having wrong background

---

gulpfile.js
src/_locales/en/messages.json
src/popup/settings/settings.component.ts

Since FF doesn't support having `nativeMessaging` as a optional permission. https://bugzilla.mozilla.org/show_bug.cgi?id=1630415

Make nativeMessaging optional on all platforms except firefox

---

src/popup/scss/box.scss
src/popup/scss/variables.scss

Closes #1550 
Action-button does not sufficiently alter action-box buttons that are disabled. This introduces new theme variable disabledOpacity to allow setting opacity of disabled object. Unfortunately, not all disabled elements look good with the same color/opacity combinations, so this isn't applied to all `&[disabled]` rules.
I've also darkened the action-button for the light theme to comply with WCAG AA standards. Because light uses a new color to denote a button is disabled, opacity is set to 1. Other themes don't do this so they differentiate through opacity.
* **box.scss**: Use theme opacity **and** color to differentiate disabled vs enabled
* **variables.scss**: Set reasonable colors/themes for disabled elements
* **light**: uses a new color, darken relative to previous and so …

Fix action button disable css

---

src/_locales/en/messages.json
src/popup/app-routing.module.ts
src/popup/app.module.ts
src/popup/settings/excluded-domains.component.html
src/popup/settings/excluded-domains.component.ts
src/popup/settings/settings.component.html

- **Feature name**: Ability to manage Excluded Domains
- **Description**: Adds an "Excluded Domains" screen in the Settings tab. This allows users to add and remove “Excluded Domains”, which are domains that Bitwarden will not offer to save the password for. 
- **Community Forums link:** see [here](https://community.bitwarden.com/t/ability-to-manage-excluded-domains/14194) for previous discussion.
Located in the Settings tab:
It uses the familiar URI list from the item edit screen. It includes an optional dropdown list to select from currently open domains:
It raises an error if the user tries to save with an invalid domain:
If the user enters a URI that includes a path or other information, only the domain portion of the URI will be saved. For example, …

add settings -> Excluded Domains component

---

gulpfile.js
src/manifest.json
src/popup/settings/settings.component.html
src/popup/settings/settings.component.ts
src/services/browserPlatformUtils.service.ts

We should follow https://bugzilla.mozilla.org/show_bug.cgi?id=1630415 for when we can re-add this feature. I also hid the setting from safari since we currently don't support it either.

Remove nativeMessaging requirement from Firefox

---

src/popup/components/action-buttons.component.html
src/popup/components/action-buttons.component.ts
src/popup/components/ciphers-list.component.html
src/popup/components/ciphers-list.component.ts
src/popup/vault/ciphers.component.html

Fix #869. With auto-fill on page load enabled, clicking the "launch" button for a cipher will auto-fill the last used cipher for that URI, not necessarily the cipher that you clicked the launch button for.
@addisonbeck Fixed the same problem when double-clicking on a cipher to launch it (see #1391). However, the launch button calls a different method, and the changes were not replicated in that method.
Rather than copy & paste this previous fix, I have refactored so that the launch button calls the same method as double-clicking.
Previously:
- `ciphers.component` implements the `launchCipher` method, which is passed down to the child `ciphers-list.component` and called when a cipher is double clicked.
- `ciphers-list.component` does not pass this down to its own child, …

Auto-fill the correct cipher after clicking launch button

---

src/background/nativeMessaging.background.ts

Chrome APIs are not available in the old safari extensions which caused the extension to crash on start in safari.

Resolve safari not working due to missing chrome api (nativeMessaging)

---

package.json

`npm run build:xcode` will now copy build output to `src/safari/safari/app` (except for `popup/index.html`) in accordance with the [Safari testing instructions](https://github.com/bitwarden/company/wiki/Local-Dev:-Browser).
This makes it quicker & easier to side-load the extension via Xcode for testing in Safari.
I haven't tracked this in Asana, let me know if it needs a card somewhere.

Add build:xcode script to package.json

---

src/_locales/en/messages.json
src/popup/app-routing.module.ts
src/popup/app.module.ts
src/popup/scss/base.scss
src/popup/send/send.component.html
src/popup/send/send.component.ts
src/popup/tabs.component.html

> Implement the Send navigation tab
- **jslib**: Updated from **9ddec9b** to **859f317**
- **messages.json**: Added `send` string
- **app-routing.module.ts**: Added `send` to `tabs` path
- **app.module.ts**: Added `SendComponent` to list of registered modules
- **scss/base.scss**: Adjusted tabs scss to include a (potential) 5th tab
- **send/send.component.html**: Added skeleton class html
- **send/send.component.ts**: Added skeleton ts class
- **tabs.component.html**: Updated to use new scss classes based on number of tabs visible
- Make sure the `Send` navigation tab is available and directs you to a temporary component
- Make sure the popout component only contains 4 navigations tabs (including send)

[Send] Navigation Tab

---

src/popup/vault/groupings.component.html

I broke the launch cipher button in various places as a result of #1576. This was picked up in QA.
In `ciphers-list.component`, I had renamed `onDoubleSelected` to `launchEvent`, but hadn't changed all references to this in other places in the code. This PR updates those references to un-break this component.

Fix launch buttons

---

src/_locales/en/messages.json

@clayadams5226 found in QA testing that any changes in the new Excluded Domains component do not take effect until you refresh the page. We decided it was not a big issue,  but we should add some text to explain this to the user.

Add UI text to explain Excluded Domains functionality

---

src/safari/safari/SafariWebExtensionHandler.swift
src/services/browserPlatformUtils.service.ts

Added `copyToClipboard` to the native swift code to handle an edge case where copying TOTP refused to work. Safari for some reason forgot a user triggered the event.

Fix copying TOTP not working in Safari

---

gulpfile.js

Required to communicate with the native code in swift.

Fix nativeMessaging not being enabled in safari

---

src/safari/safari/SafariWebExtensionHandler.swift

With the new Safari Web Extension the save dialog appeares behind the Safari window. Which is obviously not acceptable UI behaviour.
After reading documentation, articles I found the [`isFloatingPanel`](https://developer.apple.com/documentation/appkit/nspanel/1531901-isfloatingpanel) property which forces the `NSSavePanel` to appear on top of everything else. While appearing on top of everything is not perfect either it's in my opinion better than not showing up at all.

Set save dialog to be a floatingPanel

---

package.json

I added a helper script to copy build output into the Xcode directory, but [as Chad foreshadowed](https://github.com/bitwarden/browser/pull/1589), it was almost immediately deprecated. This PR removes that script to avoid confusion.
The recommended way to test in Safari is `npm run dist:safari:dmg`.
This reverts commit c99b716b209c3180c6831686d67aa580df53d414, reversing changes made to 8e20e483733d9be1ff50d495f88a29cdb6647ef7.

Revert "Merge pull request #1589 from bitwarden/npm-xcode-script"

---

src/background/main.background.ts
src/safari/safari/SafariWebExtensionHandler.swift
src/services/vaultTimeout.service.ts

Safari adds a delay to `setInterval` and `setTimeout` on the background page, which causes the vault to not lock within the expected time-frame. It could take up to 60s before the vault locked which differs significantly from the other browsers.
After exploring a few different alternatives it seems the only work-around is to replicate `setInterval` by using the native extension as a timer.
Depends on https://github.com/bitwarden/jslib/pull/275

Resolve safari not checking vault timeout every 10s

---

src/_locales/en/messages.json
src/popup/app-routing.animations.ts
src/popup/app-routing.module.ts
src/popup/app.component.ts
src/popup/app.module.ts
src/popup/scss/box.scss
src/popup/scss/misc.scss
src/popup/send/send-add-edit.component.html
src/popup/send/send-add-edit.component.ts
src/popup/send/send-groupings.component.ts
src/popup/send/send-type.component.ts

> Implement the `add` and `edit` flow for Send.
- **jslib**: Updated to 8a3b551
- **messages.json**: Fixed `Link vs link` debacle. Added new strings.
- **routing-animations**: Added animation routes for both adding and editing Sends (to/from)
- **app-routing.module.ts**: Added `add-send` and `edit-send` to routing paths
- **app.component.ts**: Added scope cleanup for `vault/GroupingsComponentScope`.  Removed unnecessary `TODO`
- **app.module.ts**: Added `SendAddEditComponent`. Added `DatePipe` provider that is used within the new component.
- **box.scss**: Added `box-header-exapandble` and `flex-label` stylings. Adjusted `input` to not include radio styling. Added `radio-group` styling.
- **misc.scss**: Added `clickable` class styling to add hover states for `app-callout`
- …

[Send] Add/Edit functionality

---

src/_locales/en/messages.json
src/popup/components/send-list.component.html
src/popup/components/send-list.component.ts
src/popup/scss/base.scss
src/popup/send/send-add-edit.component.html
src/popup/send/send-groupings.component.html
src/popup/send/send-groupings.component.ts
src/popup/send/send-type.component.html
src/popup/send/send-type.component.ts

> Apply enforcement for the `Disable Send` enterprise policy
- **messages.json**: Added `sendDisabled` string
- **send-list.component.html**: Applied `disabled` class to the icon if user cannot edit Sends
- **send-list.component.ts**: Added new `Input` parameter `disabledByPolicy` to adjust disabled state of `remove password` button
- **scss/base.scss**: Added `flex` and `tab-page` CSS into the base `content` container to handle centering of `no-items` content with a banner (see screenshots)
- **send-add-edit.component.html**: Made all necessary input fields `readonly` or `disabled` based on the `disableSend` boolean.  Added banner with policy explanation.
- **send-groupings.component.html**: Adjusted `content` styling if necessary, adjusted `addSend` buttons if necessary, and passed …

[Send] Enterprise policy enforcement

---

src/popup/send/send-add-edit.component.html

> `Current Access Count` input field gives the impression that the value (at some point) could be changed on Firefox and Safari because the action bars are not hidden when `readonly`. 
- **send/add-edit.component.html**: Changed `accessCount` input type from `number` to `text`

[Send] Updated current access input type to text

---

src/background/main.background.ts

When locking the browser extension on Safari, the badges tend to persist for a while, I found that switching from Safari to another app and back usually resolves it. This is not exactly the desired behavior, and it seems to be caused by some incorrect behavior with Safari not reliably resolving `chrome.browserAction.setIcon` which prevents subsequent code from running.
- **main.background.ts**: Added a separate behavior for Safari where we don't wait for `setIcon` to resolve before continuing. From my testing this doesn't seem to negatively affect anything else.

Resolve safari not refreshing badge correctly

---

package.json
src/popup/scss/misc.scss
src/popup/send/send-add-edit.component.html

Implemented date/time fallbacks for Firefox and Safari similar to what was added in web.
1. Added a polyfill for `<input type="date">` in Safari
2. Added some general css classes for applying flex properties (used here to create inline, joined date & time inputs)
3. Added relevant conditionals and inputs to support using date and type input types in browsers that don't support datetime-local.

implemented date & time fallbacks for safari and FF

---

src/services/browserPlatformUtils.service.ts

Fix #1658. I updated our web vault to support FIDO U2F in Edge (https://github.com/bitwarden/web/pull/804) but didn't update the browser extension as well.
`browserPlatformUtils`: Add Edge to the list of browsers that support U2F. No other changes are required, we just have to stop blocking it.

Enable FIDO U2F on Edge

---

src/_locales/en/messages.json
src/popup/send/send-add-edit.component.html

https://github.com/bitwarden/jslib/pull/300
https://github.com/bitwarden/web/pull/879
QA requested a few fix ups to the send date fallbacks.
1. The calendar popup for `<input type="date">` doesn't work in the Firefox browser plugin. This is for the same reason `<input type="file">` popups don't work, and has been handled in a similar way by adding some subtext telling users to pop out the extension to use the picker. The text based date input works as expected regardless of being in a popup or not.
2. Better error messages for input validation. Placeholders were created for messages in jslib but they didn't get added to clients.
3. We should auto populate `expirationTime` if `expirationDate` is set and no time is already present. Not doing so was causing confusion when trying to just set …

Send Date Fallback QA Fixes

---

gulpfile.js
src/_locales/en/messages.json
src/browser/browserApi.ts
src/popup/settings/settings.component.ts
src/services/browserPlatformUtils.service.ts

Adds support for browser biometrics on Firefox >= 87.
- **gulpfile.js**: No longer removes the optional_permission for Firefox.
- **src/browser/browserApi.ts`**: Handles Chrome/Firefox apis for permission request.
- **src/popup/settings/settings.component.ts**: Reworked how permission request works, Firefox has a "bug" in which user interaction flag disappears in promises chains. Hence we no longer check the permission and instead request it from the get-go. We also cannot display the information message.
- **src/services/browserPlatformUtils.service.ts**: Added check to ensure Firefox version >= 87.
Only Firefox nightly currently supports this. We should do a general testing to ensure permission prompts still works across browsers. Once Firefox 87 is released, we should do a quick …

Add support for browser biometrics on Firefox >= 87

---

src/popup/services/services.module.ts

I encountered the same problem on  Chrome and ms edge
I write this fix, I have tested on the latest versions of Firefox, chrome, and ms edge, It works.
Indeed, firefox doesn't limit the popup height like this. 
This method should not break anything.
Fixes https://github.com/bitwarden/browser/issues/1008
Fixes https://github.com/bitwarden/browser/issues/1030
Fixes https://github.com/bitwarden/browser/issues/1650
Also, I think this `innerHeight` can be used for other sizes instead of "-sm" and "-xs". 
The best popup ratio is known.

fix popup height

---

.github/workflows/release.yml

The creation of the zip file for the source upload seems to not have worked correctly when porting over from AppVeyor. This fix changes how we checkout out the repository. 
- .github/workflows/release.yml

fixes the release asset

---

src/background/nativeMessaging.background.ts

Firefox < 77 doesn't support `chrome.permisisons.onAdded`. Since this event is only relevant for when Browser Biometrics is enabled we can safely ignore it for older versions of FF.
Resolves #1699

Resolve FF < 77 not working

---

.github/workflows/release.yml

The issue of the empty source zip had something to do with how we were originally cloning it. That fix broke something else. Reverted to a slightly altered version.
- .github/workflows/release.yml
- Tested via `npm i`

fixing the source issue

---

src/popup/services/services.module.ts

PR #1627 introduced the following bugs:
* In Firefox on Mac, the browser extension does not consistently open/render when the Bitwarden icon is clicked.  Sometimes a gray box will briefly pop up before disappearing. 
* The browser extension in Safari does not open/expand correctly, leaving the extension nearly unusable unless the user manages to open the Pop Up. The extension window is so small and cannot easily be expanded.
The PR used `window.innerHeight` to set the height of the `body` element, but `window.innerHeight` is not reliable - sometimes it equals 0px (in Firefox) or 50px (in Safari), which is why the popup is not opening to its proper size.
PR #1627 was intended to fix duplicate/unnecessary scrollbars appearing in the popup window (see #1008, #1030, #1650). As an extra …

Revert "Merge pull request #1627 from emindeniz99/master"

---

src/popup/vault/view.component.html
src/popup/vault/view.component.ts

This is a minor UI bug that has been bothering me: the "Autofill" and "Autofill and Save" buttons currently appear for all item types, even those that do not support those operations.
* Hide Autofill button for secure notes (as they cannot be autofilled)
* Only show Autofill and Save button for logins (as only logins have a saved URI list)

Hide autofill buttons for certain cipher types

---

src/popup/vault/current-tab.component.html
src/popup/vault/current-tab.component.ts
src/popup/vault/groupings.component.html
src/popup/vault/groupings.component.ts

Close browser popup on <kbd>Esc</kbd> key press.
Fixes https://github.com/bitwarden/browser/issues/1384.
Old behavior when search box focused:
* Always use browser default behavior for `input type="search"` — clears input (no-op if input already empty)
New behavior when search box focused:
* If input not empty, use browser default behavior (popup can still be closed by pressing <kbd>Esc</kbd> a second time)
* If input empty, close popup instead

Close browser popup on Escape key press

---

src/popup/send/send-add-edit.component.html

Fix the following errors in the Send add-edit component:
This was caused by `appBoxRow` directive being in the wrong place - moved it per @addisonbeck's advice.

Fix appBoxRow error

---

src/browser/browserApi.ts
src/popup/accounts/two-factor.component.ts
src/popup/scss/misc.scss

On linux the WebAuthn browser controlled dialog appears inside the popup, which causes it to be cut off due to our limited popup width. To work around this I increase the width temporarily.
* **src/browser/browserApi.ts**: Added `getPlatformInfo` to figure out which os the browser is running on.
* **src/popup/accounts/two-factor.component.ts**: Add a temporary class `.linux-webauthn` to the body if on linux and using WebAuthn.
* **src/popup/scss/misc.scss**: Add `.linux-webauthn` class which expands the width to 490px which is slightly larger than the prompt.

Increase popup width on linux during WebAuthn process

---

src/background/main.background.ts
src/background/nativeMessaging.background.ts
src/safari/desktop.xcodeproj/project.pbxproj
src/safari/safari/SafariWebExtensionHandler.swift
src/services/browserPlatformUtils.service.ts

Adds support for browser biometrics to Safari. It was previously omitted due to needing some special logic to function correctly and we still used the old app extension.
Biometrics in Safari works slightly differently in that they do not require the desktop companion app to be running. (It's still necessary to enable biometrics inside the desktop app)
* **src/background/main.background.ts**: Inject platformUtilService to NativeMessagingBackground.
* **src/background/nativeMessaging.background.ts**: Add support for the slightly different Safari flow.
* **src/safari/desktop.xcodeproj/project.pbxproj**: Automatic Xcode reformat, figured we might as well commit it since it keeps reformatting the file.
* **src/safari/safari/SafariWebExtensionHandler.swift**: Native logic required for …

Add support for biometrics to Safari

---

src/popup/send/send-add-edit.component.html
src/popup/send/send-add-edit.component.ts

There is a bug in chromium which prevents the file picker from working correctly on Mac 11+. Temporarily adding the warning until this has been resolved. Once fixed we can revert this PR.

Show file picker warning in chromium on Mac 11

---

src/popup/scss/misc.scss

Fix #1700: `<option>` elements do not render correctly in FF sidebar when using the dark or node themes. e.g.
I presume it also affects the light theme, it's just less obvious.
There appears to be a FF rendering bug where the `<option>` background color will not be rendered correctly if it's identical to the background color of the parent `<select>` element. This only occurs in sidebar mode.
After some experimenting, I couldn't think of a better way to solve it than to offset the background-color value slightly for all `<option>` elements. This is enough to work around the FF bug, while not being visually distinct to users. Also, it's only visible when the user has a `<select>` element open, which is very brief.
This fix does not distinguish between browsers or popup vs. sidebar. I'm not …

Fix bgcolor of option els when in FF sidebar

---

src/popup/send/send-add-edit.component.ts

Fix https://app.asana.com/0/0/1200155711369722/f.
The actual issue here is a missing set of parenthesis, but simplifying the logic to _not_ show the picker whenever a popup warning message is displayed.
* **send-add-edit.component.ts**: simplify logic
This will require full regression testing across browsers. The expected behavior is:
* firefox: file picker hidden and warning message displayed in popup, not in side bar or popout -- for all OSes
* linux: file picker hidden and warning displayed in popups across all browsers
* safari: file picker hidden and warning displayed in popup, not in popout -- only relevant to mac
In all clients across all OSes, the file picker show never be displayed in `edit` mode.

Simplify and fix file picker logic

---

src/popup/send/send-add-edit.component.ts

Bump jslib and remove `tokenService` from the send `add-edit` component. Required for https://github.com/bitwarden/jslib/pull/344.

Don't use tokenService to manage emailVerified

---

src/popup/scss/base.scss

Firefox 89 includes the "Proton" redesign which changes how the extension is displayed. The popup arrow is removed and the extension has rounded corners. Unfortunately the bottom corners contains an ugly blue bleed-through. This reverts the previous PR which changed the background color to be the same as the header, which should mitigate most of the issue. However we still have a bit of bleed-though on the top instead but it's less noticeable.
Before:
After:

Revert "Popover arrow background color"

---

src/safari/safari/SafariWebExtensionHandler.swift

We had a slightly different logic for biometric unlock on Safari. Changed to use the exact same logic as Electron does to provide similar UX across all platforms. (It adds a password fallback)
We should re-test Safari biometric unlock to verify everything still works.

Change biometric prompt to use the same logic as electron

---

src/_locales/en/messages.json

As reported by user in Crowdin (https://crowdin.com/translate/bitwarden-browser/26/en-de#4816), the source string had a small typo. This PR fixes it.

Fix typo in webAuthnAuthenticate

---

src/_locales/en/messages.json

Safari gets angry when you try to submit an appex in your desktop app when submitting to MAS if the extension name (localized) is greater than 40 characters. This adds a description asking translators to not exceed this.

Add to extName description to limit to 40 chars

---

src/popup/app.component.ts
src/popup/settings/settings.component.ts

We dont epect to use HTML in the sweetalert title, so switch to `titleText` property.
https://sweetalert2.github.io/#titleText

use swal titletext to avoid XSS

---

README.md

With @Hinton bumping node to 14 recently, I've adjusted the README to show the need for Node 14.17 (LTS)

Bump Node Version from 8 to 14 in README.md

---

.github/workflows/build.yml
.github/workflows/release.yml

This pins all action versions in the workflows to commit hashes. This protects us from any malicious changes to the actions in case people force push tags.

Pin versions of actions in workflow

---

src/popup/settings/options.component.ts

With the new per-item Autofill On Page Load settings, I had intended that all logins continue to autofill by default, so that anyone currently using the feature will not experience any change in behaviour after upgrading their client. (Assuming that they have opted-in to the Autofill On Page Load feature to begin with.)
However, for some reason I had set it to NOT autofill login items by default, which QA picked up in testing.
If saved storage value for `autoFillOnPageLoadDefault` is `null` or `undefined`, default to `true` (autofill logins by default) instead of `false` (do not autofill logins by default).

[Autofill on Page Load options] Change default per-item setting to "autofill"

---

.github/workflows/release.yml

In the DevOps retro, we identified that the release workflows of the clients should be programmatically constrained to the `rc` branch to protect from human error on release

programmatically constraining releases to the rc branch

---

src/services/browserStorage.service.ts

Replicating this fix for browser: https://github.com/bitwarden/web/pull/1012
This is a pre-emptive fix - I'm not aware of it causing issues in browser currently, but it's caused issues in the other Angular clients, so replicating the code here won't hurt when someone inevitably goes to save a Set to localStorage.

Convert sets to arrays before saving in storage

---

src/popup/services/services.module.ts

Fix the following bug: when opening the popup in Firefox private browsing mode, it displays an infinite spinner instead of the private-mode.component (i.e. the warning page stating that private mode is not supported).
`searchService` and `passwordRepromptService` are instantiated in the popup, but their constructors take services started in the background. In private mode, these background services evaluate to `null`, which was throwing errors as soon as the popup services tried to use them.
Solved by checking for private mode before instantiating `searchService` and `passwordRepromptService` .

Don't start popup services if in private mode

---

src/services/browserPlatformUtils.service.ts

Updated the deprecated `addListener` to `addEventListener` to match [Web #1017](https://github.com/bitwarden/web/pull/1017)
Set the extension to the `Default` theme. Ensure the theme updates between dark and light when changing system theme. Needs testing on multiple OS' and browsers

Fix Deprecation Issue on addListener

---

src/services/browserStorage.service.ts

Fix issue where we aren't awaiting `get` to return its value rather than the promise of one.
FYI, this is a regression item and will be cherry-picked into `rc` upon merger to master. Please evaluate accordingly.
I wasn't able to produce a defect for this, but it should have to do with refreshing the popup, sidebar, or popout. It's possible this produces no visible issue, though.

Must await to get stored value

---

src/popup/scss/plugins.scss

> A recent update to the `angular2-toast` library cause our custom styling to not be applied properly.
- **plugins.scss**: The `toast-container` object is now a `class` and not an `id`. Updated some padding/margin to more closely match the current production toasts style. Removed unnecessary `toast` styles, they were breaking the animation.

[Toast] - BUG - Fixed styles

---

src/popup/vault/add-edit.component.html

Add help link to password reprompt option.

Add reprompt help link

---

src/background/main.background.ts
src/safari/safari/SafariWebExtensionHandler.swift
src/services/browserCrypto.service.ts

Fixes a few issues with browser biometric integration. Swift fixes for Safari and browserCryptoService changes for all.
> Note: This will be cherry-picked into `rc`, please evaluate accordingly
* **main.background.ts**: Use new browserCryptoService
* **browserCrypto.service.ts**: child class that specifically retrieves biometric key from Desktop using `BrowserPlatformUtils`. Note, Desktop sets the key in IPC communications so we return the key existing on `CryptoService`
* **SafariWebExtensionHandler.swift**: Try `Bitwarden_biometric` first, but fallback to `Bitwarden` without complaint. Upgrades to keys should be handled by the desktop application.

Get either 'Bitwarden' and 'Bitwarden_biometric' keys.

---

src/_locales/en/messages.json
src/popup/components/cipher-row.component.html
src/popup/settings/settings.component.html
src/popup/settings/settings.component.ts
src/popup/vault/share.component.html
src/popup/vault/view.component.html

The term "Share" is confusing to users because it implies maintaining ownership and control of a cipher while allowing others to access it as well. It also implies the ability to revoke access or to stop sharing -- neither of these things is true.
In addition to the share term being misleading, the [`fa-share-alt`](https://fontawesome.com/v4.7/icon/share-alt) icon implies a forking of the cipher item rather than transferring ownership.
When a cipher is "shared" it is irrevocably taken over by an organization. This occurs for good cryptographic and security reasons. The better solution to this is to revise the communication around "sharing." To that end, this work changes the term "share" to "move to organization" and the icon is changed to …

Redefine cipher "share" to "move to organization"

---

.github/workflows/release.yml

Disabling coverage asset upload because it does not exist. The [dependency bump](https://github.com/bitwarden/cli/actions/runs/979910489) broke it.

disabling the broken coverage asset

---

src/popup/services/services.module.ts

Follow up to #1886, in which I falsely claimed to fix the infinite spinner that appears in Firefox private mode. This time I promise that I've fixed it.
#1886 was the right approach, but I'd missed `i18nService`. Add a private mode check there so that we don't refer to `translationLocale` on a `null` object.
Note that `private-mode.component` still works even though `i18nService` is not set in the popup. It uses the chrome api instead - I assume this is by design.

Don't start i18n service if in private mode

---

src/popup/app-routing.module.ts
src/popup/services/debounceNavigationService.ts
src/popup/services/services.module.ts

**Note**: this may be a candidate for `rc`
Fix #1927. The latest update broke the password generator when accessed via the add-edit component. Maybe 80%, when returning from the password generator to the add-edit component, it would blank all the fields - so you would lose anything you entered, including the password you just generated. The other 20% of the time it would work as expected.
This mainly affected Firefox for me, I don't think I was able to reproduce it on Chrome.
There are 3 (relevant) trigger events for the Angular router to start navigation:
* `imperative` - e.g. calling `router.navigate`
* `popstate` - usually triggered by going forward or back through the browser history, e.g. `location.back()`
* `hashchange` - triggered when the hash component of the URL changes (only …

Fix loss of cipher data when using pass generator

---

README.md

I was working on a feature that required biometric unlocking in the browser, and was really confused because the browser extension kept throwing an error about not being able to communicate with the desktop application.
I discovered this is because the desktop application hardcodes production extension IDs into manifest files, and these IDs need to be updated to work with development versions of the browser extension.
Putting this up front in the README will hopefully save future newcomers some grief.
This is partly captured in the [desktop readme](https://github.com/bitwarden/desktop/blob/master/README.md), but it's not very clear, and it's not the first place that a browser developer would look (since you don't need to build the desktop application to make it work, just modify the …

[readme] enable desktop communication

---

README.md

Prior PR that I approved and merged in, https://github.com/bitwarden/browser/pull/1951, needed a little bit more info that Oscar had pointed out to help with other OS's regarding manifest locations such as macOS. This is not an exhaustive reference but at least points the person in the right direction.

Update manifest info in readme.md for desktop comm

---

src/services/browserPlatformUtils.service.ts

The biometric settings is visible when using the Bitwarden extension in Firefox for Android. Since we cannot communicate with the desktop applicaton on mobile, we should hide the setting.
I haven't had an opportunity to verify this PR on a mobile device.
Resolves https://github.com/bitwarden/browser/issues/1846

Hide biometric setting when running in Android

---

src/manifest.json

In addition to being less than ideal for security, it appears the bitwarden extension does not actually use any functions that require `unsafe-eval` to be allowed in the CSP.
I searched for `eval`, the `Function` constructor, `execScript`, and the `setTimeout`, `setInterval`,  & `setImmediate` functions with string literals passed as arguments, and found no examples of any of these in the codebase.
Therefore, the best option would be to remove this directive, which is exactly what this PR does :)
Please let me know if I'm mistaken, thanks!

Remove unsafe-inline from Content Security Policy in manifest.json

---

src/content/autofill.js

Don't use deprecated initKeyEvent() for autofill

---

src/popup/accounts/two-factor.component.html

Fixes: https://app.asana.com/0/0/1200719554428331/f
Chrome seems to balk at this attribute being added after the fact. It may be a race condition or an intentional block, but adding to the template fixes our missing allow attribute problem.
depends on bitwarden/jslib#455
>Note: this will be cherry picked to `rc`

Add iframe allow to initial load

---

.github/workflows/crowdin-sync.yml

In order to test the new Crowdin Sync workflow, the workflow needs to first exist in `master`

Adding stub for crowdin sync testing

---

src/popup/send/send-add-edit.component.html

Resolves https://app.asana.com/0/1200578627114106/1200719554428334/f
In web and desktop we use the HTML attribute `hidden` to toggle optional Send fields in and out of view. In browser we anomalously achieve this same functionality with an `*ngIf`. `*ngIf` not loading content into the DOM until its condition is met is causing the `efflux-dates-component` to not emit the initial deletion date value, resulting in an error.
Change the `*ngIf` to `[hidden]` for toggling Send optional fields on and off so form content is not added to or removed from the DOM dynamically.

Fix Send Options Toggling

---

src/manifest.json

PR #1873 suggested that we remove `unsafe-inline` from our browser CSP, because it didn't look like we had any code that would require it. I double checked this and merged it.
I've now realised that:
* these CSP options are removed entirely for FF, Chrome, Opera and Edge builds - so this change did not have the effect I intended
* when running a dev build using `npm run build`, the extension has started throwing errors about code being blocked by the CSP. I'm not yet sure what practical effect this has.
* it looks like CSP options are kept for Safari dist builds, which makes me concerned about the effect in prod.
It seems safest to revert this change pending further investigation. This should be cherry-picked to `rc`.

Revert CSP change

---

src/services/i18n.service.ts

With #1949 the AZ language was added. Unfortunately it was set on the first position of the supportedTranslationLocales[]. The first entry is used as a fallback in case the selected locale (browser/system) is not found. This results in users getting for example the login or register site displayed in Azerbaijani.
As can be seen here: https://community.bitwarden.com/t/bitwarden-registration-in-wrong-language/32642

Fixed order of supportedLocales to have 'en' as fallback again

---

src/_locales/en/messages.json
src/background/contextMenus.background.ts
src/background/main.background.ts
src/background/runtime.background.ts
src/content/contextMenuHandler.ts
src/manifest.json
webpack.config.js

It's bad UX to require users to open up dev tools and read the HTML just to create custom fields. This adds a new right-click option that will copy the best identifier to the clipboard, which the user can then paste into custom field Name.
I had originally included this in the [Linked Custom Fields PR](https://github.com/bitwarden/browser/pull/1963), but decided that it should be broken out into its own ticket. I've made some slight improvements to the logic since that PR.
The identifier that is copied to the clipboard is the html `id`, `name`, `aria-label` or `placeholder`. The script checks these attributes, in that order, and uses the first value it comes across which is valid (not null/blank) and unique. This is the same order that the autofill service tries to fill custom fields.
* …

Add new context menu item: Copy Custom Field Name

---

src/_locales/en/messages.json
src/popup/accounts/set-password.component.html
src/popup/scss/misc.scss

> Add callout banner during SSO Set password flow when a user will be automatically enrolled in Reset Password program.
- **set-password.component.html**: Added `callout` banner with information regarding auto enrollment
- **messages.json**: Added new strings for `callout` and missing sso string
- **misc.sass**: Added `ul` style
- [jslib: [SSO] Set password auto enroll update](https://github.com/bitwarden/jslib/pull/472)

[SSO/Auto Enroll] Set Password banner

---

src/notification/bar.js

Fix QA feedback for the "Select folder in save prompt" feature. I'd changed the `id` and `class` of the select folder dropdown, but hadn't updated all querySelectors.

Fix QA feedback: notificationBar save button not working

---

src/_locales/en/messages.json
src/popup/accounts/lock.component.ts
src/popup/settings/options.component.html
src/popup/settings/options.component.ts
src/popup/settings/settings.component.html
src/popup/settings/settings.component.ts

https://community.bitwarden.com/t/automatic-biometrics-prompt-on-open-popup/17383
This primarily rebases and cleans up the work originally performed by @cho-m (thanks!)
It requires a blocking prompt if the desktop application isn't open. This isn't ideal, but making this more user-friendly (i.e. a toast instead of blocking dialog) would require significant refactoring of the crypto service and should probably be handled as a follow-up.
Requires https://github.com/bitwarden/jslib/pull/483

Automatic biometrics prompt

---

src/popup/vault/current-tab.component.ts

Fix #2053:
> When using the Bitwarden extension from the Chrome Web Store, the extension does not automatically copy the TOTP after clicking on the appropriate login from the extension.
This only affects copying from `current-tab.component`. It appears that the popup closes before the copy-to-clipboard operation finishes - despite that being a completely synchronous operation.
This appeared around Chrome 93. Most affected users were using Chrome 93 on MacOS, which I could reproduce, and there was 1 report on Brave, which I couldn't reproduce. I couldn't find any release notes that indicate what change might have caused this, and it's unclear whether it's a Chrome or upstream Chromium issue.
* `current-tab.component` - add a short (50ms) delay to closing the window.
I don't like using …

Fix totp copy not working in Chrome

---

src/popup/accounts/lock.component.ts

In the browser extension, primarily on Safari the error message for biometrics sometimes disappears before it can be read. To resolve this, I needed to only close the dialog if the action was successful.
Depends on: https://github.com/bitwarden/jslib/pull/501

Prevent the lock component from removing the biometric error message

---

src/content/autofill.css
src/content/autofill.js
src/models/autofillField.ts
src/services/autofill.service.ts

This PR adds the ability to auto-fill the `innerText` of HTML `span` elements that exist on a page.
An example use case is auto-filling documentation with sensitive information. For example, an IT administrator could have a secure procedure written up in a wiki that contains some credentials. Since a wiki page is not a secure medium for storing credentials, the credentials can be stored as an item in Bitwarden targeting the wiki page (setting the URI of the wiki page with "exact" match detection configured).
This requires you to mark up your documentation page with `span` placeholders containing a `data-bwautofill` attribute and unique `id` such as:
```html
<span data-bwautofill id="secret-value-123"></span>
```
or put some placeholder text inside the `span` directing the user to …

Ability to auto-fill span elements

---

src/background/notification.background.ts

If the vault is locked and a user tries to log-in to a new site, we will check for the DisablePersonalOwnership policy (no private vault) and not show the prompt if it is active. This is to ensure the same behaviour as if the vault was unlocked.
In the future we will want to enable users with this policy active to save new credentials to an Org and/or collection. For now though, this fix prevents users from saving new logins in a vault they shouldn't have.
Asana ticket: https://app.asana.com/0/1200804338582616/1201295056358742/f
* **src/background/notification.background.ts:** Added the same check for allowPersonalOwnership if the vault is locked
All users of an organizations that have the DisablePersonalOwernship policy active, should not be shown a prompt to save new logins.

When vault is locked also check for personal ownership policy

---

src/popup/scss/misc.scss

Prevent passphrase words in the password generator from breaking over two lines when they're too long. Unfortunately only works when the word separator is left on the default `-`, as in other cases the browser doesn't seem to see the passphrase as being made up of words for CSS to break/unbreak (since the words themselves are broken up into `<span>`s by the highlighter).
Closes https://github.com/bitwarden/browser/issues/1096
Before, showing passphrase words changing
After - words remain intact and line breaks only happen on the hyphens

Prevent passphrase words from breaking over two lines (when using `-` separator)

---

src/_locales/en/messages.json
src/notification/bar.html
src/notification/bar.js
src/notification/bar.scss

Remove the handling of different window sizes, with modifying text and styles from bar.js and instead do everything with CSS.
Asana ticket: https://app.asana.com/0/1169444489336079/1200912318004726/f
* **src/notification/bar.html:** 
* Added html attributes `short-text` and `full-text`, added an attribute to contain `isVaultLocked` state
* **src/notification/bar.js:** 
* Removed the logic to differentiate between window sizes and setting textContent with different translations
* Fill new attributes `short-text` and `full-text` with the translations pulled from i18n
* Pass `isVaultLocked` value as a string into the isVaultLocked attribute of the select-folder dropdown
* **src/notification/bar.scss:** 
* Added media queries to adjust the translations by extracting the attribute value of …

Even more responsive notification bar

---

src/popup/scss/base.scss

With the new feature added to prompt for login if vault is locked, I did some CSS changes to center the fields. They should not be spread across the whole width. As the prompt for login is also possible when logged out of a vault, a different screen appears. This PR fixes the UI of those 2 screens (app-login/app-two-factor)
* **src\popup\scss\base.scss:** 
- Added padding to `app-login` `header `and `content` inside of media-queries
- Added padding to `app-two-factor` `header` and `content` inside of media-queries
**LOGIN**
**2FA**
1. Log out of Bitwarden extension
1. Use the shortcut (Cmd/Ctrl+Shift+L) or contextmenu to trigger auto-fill
1.  A new tab should open to prompt for login. 
1. The fields should not be spread across the whole width (see screenshots)

Center login and 2fa entry when login via new tab

---

src/background/main.background.ts
src/background/notification.background.ts

Fix a bug where the notificationBar was offering to save credentials even if the user was logged out. This should only occur when the user is logged in (locked or unlocked).
* **src/background/notification.background.ts** - `vaultTimeoutService.isLocked()` will return true if the vault is locked OR if the user is logged out. This is not intuitive and I think we should change it to avoid this pitfall. In the meantime, just add a call to `userService.isAuthenticated()`.
* update component dependencies
* Make sure the bug is fixed and no regressions on saving the password when the vault is locked.

Don't save passwords if user is logged out

---

src/popup/components/set-pin.component.html

If the user is using Key Connector and sets an unlock pin, do not ask them whether they want to "require unlocking with master password when the application is restarted". Instead, hide this checkbox and default it to false because they do not have a master password.
Requires https://github.com/bitwarden/jslib/pull/556.

[Key Connector] Hide "Master Pass On Restart" prompt when setting pin

---

src/_locales/en/messages.json
src/popup/accounts/lock.component.html

Hides the password input when using key connector.
Resolves https://app.asana.com/0/1201363553288890/1201394615545876/f
* **jslib:** Updated jslib
* **src/popup/accounts/lock.component.html:** 
* Use `identity` instead of `master password` in header/labels 
* Use hideInput from baseComponent to hide submit button(Unlock, top right corner) and master password field
**Without KeyConnector**
PIN
Biometrics enabled
**With KeyConnector**
PIN
Biometrics enabled

Hide password input when using key connector

---

src/safari/desktop/Info.plist
src/safari/safari/Info.plist

The copyright of the plist files for safari still had the year set to 2020 
**src/safari/desktop/info.plist:** Change copyright year from 2020 to 2021
**src/safari/safari/info.plist:** Change copyright year from 2020 to 2021

Update copyright year in .plist files for safari

---

package-lock.json
package.json
src/popup/app-routing.module.ts
src/popup/app.component.ts
src/popup/app.module.ts
src/popup/components/action-buttons.component.ts
src/popup/scss/plugins.scss
src/popup/settings/settings.component.ts
src/popup/settings/sync.component.ts
src/popup/vault/current-tab.component.ts

As a part of upgrading Angular, I noticed that the toaster library we use still depends on Angular 11. This PR replaces our current toaster library with `ngx-toastr`.
While at it, I replaced all direct calls to the library with `platformUtilsService.showToast` which will make it easier to do these changes in the future. (Please do not call the toaster library directly in the future!)
Depends on: https://github.com/bitwarden/jslib/pull/568
Removed toasterService from every component and used platformUtilsService instead. Note I didn't spend any time on formating the constructors since that will be a moot point soon.
Regression sweep to ensure toasts still behave correctly.

Replace toaster library

---

src/popup/scss/misc.scss

Firefox was experiencing a rendering issue in sidebar dropdown lists - see the original bug here: https://github.com/bitwarden/browser/issues/1700. To fix this, I inserted some CSS which offset the `<select>` background color by 1.
I reported this bug upstream and it was fixed in FF 90: https://bugzilla.mozilla.org/show_bug.cgi?id=1702940.
We support the last 2 major releases, and the current stable release is FF 95. We can now revert the fix.
* **src/popup/scss/misc.scss**: delete the CSS hack
See the original bug in #1700 and make sure that it cannot be reproduced.

Revert hack to fix appearance in FF sidebar

---

.github/workflows/build.yml
README.md
package-lock.json
package.json

With our plan to bump electron soon, we need to upgrade Node to v16 (LTS) as newer version of electron require it.
Depends on https://github.com/bitwarden/jslib/pull/575
Asana task: https://app.asana.com/0/1200804338582616/1201498644188841/f
* **jslib:** Bump jslib from https://github.com/bitwarden/jslib/pull/575
* **package.json:** Updated engine requirements and bumped @types/node to 16.11.12
* **package-lock.json:** Updates after running `npm i`
* **build.yml:** Setting the build to require node v16 and npm v8
* **README.md:** Updated requirements
Will require running regression testing.

Bump node to v16

---

src/background/notification.background.ts

In the latest release we display the save prompt, even if the vault is locked to aid users to save their just entered credentials. We did not respect the user setting `Disable AddLoginNotification` to true. 
Asana task: https://app.asana.com/0/1169444489336079/1201519992309109/f
* **src/background/notification.background.ts:** Load `Disable AddLoginNotification` setting via StorageService and do not prompt user if it has been disabled (locked/unlocked vault).
If the user has set Disable AddLoginNotification, then the prompt to save should never appear.

Fix save prompt showing when disabled by user

---

src/popup/accounts/lock.component.html
src/popup/accounts/login.component.html
src/popup/accounts/register.component.html
src/popup/accounts/set-password.component.html
src/popup/accounts/update-temp-password.component.html
src/popup/components/password-reprompt.component.html
src/popup/components/set-pin.component.html
src/popup/send/send-add-edit.component.html
src/popup/vault/add-edit-custom-fields.component.html
src/popup/vault/add-edit.component.html
src/popup/vault/view-custom-fields.component.html
src/popup/vault/view.component.html

Currently, the show/hide buttons to toggle the visibility of passwords/hidden fields don't expose their state to assistive technologies - they only change visually by swapping out the fontawesome icon used. Adding `aria-pressed="false"`/`aria-pressed="true"` makes these proper toggle buttons, whose state is exposed to assistive tech. This way a screen reader user can hear whether the password/hidden field is visible or not visible.
Closes https://github.com/bitwarden/browser/issues/2228
For all the various `toggleVisibility` buttons used, adds `[attr.aria-pressed]` referencing the relevant value (e.g. `showPassword`). Toggling the button dynamically changes the value of the attribute that's rendered.
No UI change
Test with a screen reader (e.g. NVDA). Alternatively, check that the …

Add aria-pressed attribute to all toggleVisibility buttons

---

src/popup/scss/box.scss
src/popup/send/send-add-edit.component.html
src/popup/settings/options.component.html

Currently the `box-header-expandable` controls (one in Send, three in Settings > Options) are not keyboard-operable (can't focus nor activate them using the keyboard), and they don't programmatically expose any particular interactive role nor do they convey their current state (whether the content they control is expanded or collapsed).
This PR changes these controls (currently generic `<div>` elements) to proper `<button>` elements (which, out of the box, are keyboard-focusable/operable). It also adds the `aria-expanded` attribute that conveys the state.
Closes https://github.com/bitwarden/browser/issues/1983
* **box.scss:** Change to the styles to make sure the `button` that is now used spans the entire width of its parent, and does not lead to awkward horizontal scrolling/overflow to …

A11y: make expandable box headers keyboard-operable, expose correct role/state

---

src/safari/desktop/Info.plist
src/safari/safari/Info.plist

As the year 2022 has arrived it's time to update our copyright in various places.
Asana task: https://app.asana.com/0/1200804338582616/1201609982295249/f
- **src/safari/desktop/Info.plist:** Update year in copyright to 2022
- **src/safari/safari/Info.plist:** Update year in copyright to 2022
Nothing really to test here other than to verify we show the current year in the copyright.

Update year in copyright

---

.prettierignore
src/services/autofill.service.ts

During the review of the prettier changes I decided to exclude the autofill.service.ts from prettier. The amount of lists (countries, isocodes, field-name, etc) just bloats the whole file. 
With https://github.com/bitwarden/browser/pull/2255 I refactored the service a little and this PR applies prettier.
- **.prettierignore:** Removed ignore for `src/services/autofill.service.ts`
- **src/services/autofill.service.ts:** Removed tslint-disable and applied prettier
No specific testing required

Apply prettier for previously ignored file

---

src/popup/vault/view.component.ts

Previously, deleting a password for a site would not update the badge for the extension.  So if you had 3 logins for a site and deleted one, it would still show 2.  I searched for an answer to this bug and saw it was reported in #1708 back in March.  I decided to see what it involved and found it was quite simple.
I added a call to the `messagingService` with the subscriber string "deletedCipher" since I saw in `runtime.background.ts` that this calls `this.main.refreshBadgeAndMenu()`.  This resolved the issue.
When comparing against an existing flow that properly refreshed the badge (adding a login), I noticed that this messaging code was added to the jslib `add-edit-components.ts` file.  However, the `view-component.ts` file in jslib did not have the MessagingService imported, while the …

Send deletedCipher message to messagingService so badge and menu refresh. Fixes #1708

---

src/popup/images/search-desktop-dark.svg
src/popup/images/search-desktop-light.svg
src/popup/images/search-desktop-solarized.svg
src/popup/scss/base.scss
src/popup/scss/variables.scss
src/popup/send/send-groupings.component.html
src/popup/vault/groupings.component.html

Remove sad faces from empty lists and replace with a more neutral image.
[Work Item](https://app.asana.com/0/1201211497354246/1201290230072117)
- **src/popup/send/send-groupings.component.html** & **src/popup/vault/groupings.component.html**: Replace icons with new images
- **src/popup/scss/variables.scss:** Add suffix key for new images to support theming
- **src/popup/scss/base.scss:** Add new style rule to pick correct image based on theme
- Added Dark, Light, and solarized themed svg's
| Before  |After    |   
|---|---|
|  ![Screen Shot 2022-01-21 at 10 32 04 AM](https://user-images.githubusercontent.com/8926729/150558716-e598c1bb-4996-4013-b2b6-45faa45dd830.png) | ![Screen Shot 2022-01-19 at 5 43 29 PM](https://user-images.githubusercontent.com/8926729/150558765-1ecbe0e7-314c-40a4-915 …

Replace sad face with searching image

---

src/background/models/notificationQueueMessageType.ts
src/background/notification.background.ts
src/content/message_handler.ts

When saving a new entry via the Add Login prompt (Bar) the badge number  did not get updated. Only after a page refresh the updated badge appears.
Asana task: https://app.asana.com/0/1169444489336079/1201703036655950/f
- **src/background/notification.background.ts:** 
- Minor refactoring to use early return and renamed message variables
- Send message `addedCipher` when a new entry was added so `refreshBadgeAndMenu` is called
- **src/content/message_handler.ts:** Add `addedCipher` to `forwardCommands` so that the message is passed on to main
The badge number should update when saving a new entry. This should be happening even if the vault was locked beforehand

Update badge number when saving a new entry

---

src/_locales/en/messages.json
src/background/main.background.ts

With https://github.com/bitwarden/browser/pull/2132 I added the ability to login/unlock your vault via the context menu. What I missed though was to change the text on the menu items to indicate that a user can login/unlock their vault when clicking on that item.
Asana task: https://app.asana.com/0/1169444489336079/1201703036655956/f
- **src/_locales/en/messages.json:** 
- Removed `vaultLocked` and `vaultLoggedOut`
- Added `unlockVaultMenu` and `loginToVaultMenu`
- **src/background/main.background.ts :** Use new menu items text
- **BEFORE:**
- **AFTER:**
When no user is logged in, the menu should show -> Login to your vault
When a user is logged in but the vault is locked the menu should show -> Unlock your vault

[UX] Change menu items for unauthed and locked vault

---

gulpfile.js
webpack.config.js

> `dist` builds were not copying over the new font sheets. Merge fix to both `master` and `rc`
- **gulpfile.js:** Updated fonts filter with new font sheets
- **webpack.config.js:** Updated exclusion image list with new font sheets
- Make sure `dist` builds are showing the new icons

[bug] Update gulp and webpack to include new font sheet

---

src/content/notificationBar.ts

With a fix that @addisonbeck has prepared, I realized that we also had an issue reading the `neverDomains`, the `disableAddLoginNotification` and the `disableChangePasswordNotification` settings within the notificationBar.
In prep for account switching the storage can have multiple userId's and the format of the storage has changed.
The reads for the browsers local storage would always return empty as the storage was migrated.
These changes will need to be 🍒 ⛏️ 
Asana tasks: https://app.asana.com/0/1169444489336079/1201771027990401/f and https://app.asana.com/0/1169444489336079/1201774155981522/f
- **src/content/notificationBar.ts:** Grab the activeUserId from storage and use that, to retrieve the neverDomains, disableAddLoginNotification and disableChangePasswordNotification setting.
- …

Fix regressions in notificationBar (NeverDomains, Save new login/update password prompt)

---

src/content/autofiller.ts
src/popup/app.component.ts
src/popup/settings/settings.component.ts

This PR resolves several regression bugs in browser.
1. Settings changes not persisting (fixed by pulling in jslib)
2. Autofill on page load not working (fixed by pointing autofill at the correct storage key)
3. Vault timeout being ignored (fixed by adjusting activity tracking logic)
4. On Browser Restart lock not working on first run (fixed by pulling in jslib)

[bug] Fix several regression bugs

---

src/background/main.background.ts
src/popup/app.component.ts

https://app.asana.com/0/inbox/1183359552741416/1201784235738526/1201782081866250
This will need to be cherry picked to rc
Manually logging out of the extension is clearing state, but not redirecting, leading to bad application behavior.
1. Don't manually grab a `userId` in `logout()`. Doing this makes it impossible for the conditional that sends the "doneLoggingOut" message to be met, since it only fires if userId is null (logging out the active user) or an inactive user is being logged out. 
2. Remove the `stateService.clean()` call from `"doneLoggingOut"`, this is redundant as it is called in the logout function, and results in errors that stop execution of the redirect.
Some unrelated changes I made while in the area:
1. Passing `userId` to `stateService.clean()` in `logout()`. This …

[bug] Dont block redirecting on logout

---

webpack.config.js

We can't submit our most recent release for Firefox because some files exceed the 4MB hard limit (popup/main.js and vendor.js). This PR adds further chunking rules to create three new caches
1. jslib
2. @angular ngcc compiled bundles
3. zxcvbn (the frequency list is large)
Smoke test should be sufficient

Chunk out jslib and large modules to separate caches

---

src/popup/components/cipher-row.component.html
src/popup/components/cipher-row.component.ts
src/popup/scss/box.scss
src/popup/vault/ciphers.component.html

We currently remove the separator element when a `box-content-row` is the last child. However, when we create these rows from ng templates each row gets a separate template element wrapping it. This PR tells the cipher-row component whether it is the last child
* **cipher-row**: apply override-last class to element it it's not _actually_ last
* **box.scss**: add rules for `override-last`. They're the same as the `.last` selector right under it, but that name makes no sense here
* **ciphers**: send in last to compoenent
Verify, no further risk

Display separator between ngFor'ed cipher components

---

src/content/notificationBar.ts

This PR concludes #1932 and the subsequent [Twitter thread](https://twitter.com/_atjn/status/1486299137180151809).
When the notification bar checks whether it is currently running on the Bitwarden vault URL, it has a minor issue that means it will also think that URLs like `https://vault.bitwarden.com.evil.com/` are valid vault URLs. This is a minor issue, but it is still good to fix. See #1932 for more details.

Make vault URL check more concise

---

src/popup/vault/view-custom-fields.component.html

The standard password field displays number and special characters in a different color for better readability. A hidden custom-field currently does not colorize it's value when shown.
Asana task: https://app.asana.com/0/1200804338582616/1201884248598923/f
- **src/popup/vault/view-custom-fields.component.html:** Pass value into ColorPasswordPipe when hidden value is shown
**BEFORE:**
**AFTER:**
When the value of a hidden custom field is shown, it should be colorized as the standard password field

BEEEP: Colorize hidden custom field when value visible

---

src/_locales/en/messages.json
src/popup/app.module.ts
src/popup/settings/export.component.html

https://app.asana.com/0/1183359552741420/1200074829339233
Depends on https://github.com/bitwarden/jslib/pull/688
Exports are often confusing to users in organizations because there is no indication on screen that a personal export won't include organization items and vice versa. We should add an information panel to this screen noting what exactly is being exported.
- **app.module.ts:** Added an import for the `ExportScopeCalloutComponent` added to facilitate this information in `jslib`.
- **export.component.html:** Added an `<app-export-scope-callout>` element if the "Disable Personal Vault Export" policy is not enabled. 
- **messages.json:** Added strings used by the `ExportScopeCalloutComponent` in jslib.
We expect this warning to clearly label what is being exported. It should not …

[feature] Implement scope warning for exports

---

src/background/main.background.ts

Fix bug in FF Private Mode: there are some edge cases that reload the extension while Private Mode windows are open, which breaks the Bitwarden icon in Private Mode windows (which should be locked to the blue icon and should not respond to state). This can happen, for example, if the user enables biometric unlock.
**Note:** will be cherry-picked to `rc`
Asana: https://app.asana.com/0/1169444489336079/1201916867174072/f
- **src/background/main.background.ts** - when the (non-private mode) background page first starts, check and set the icon for any existing Private Mode windows. Previously we only had the event listener to handle new windows, but that missed any that were already open.
Confirm bug is fixed and no regressions on icon behaviour generally.

[FF Private Mode] Set icon for Private Mode windows that are already open

---

src/_locales/en/messages.json
src/background/nativeMessaging.background.ts
src/models/biometricErrors.ts
src/popup/accounts/lock.component.html
src/popup/accounts/lock.component.ts
src/popup/app.component.ts
src/popup/scss/plugins.scss
src/popup/settings/settings.component.ts
webpack.config.js

The previous release accidentally enabled automatic biometric prompt for everyone. Since the current way is fairly intrusive I've reworked the logic and it now has a non user initiated mode which shows the error message below the text.
Depends on https://github.com/bitwarden/jslib/pull/703
Resolves https://app.asana.com/0/1201804463288267/1201889029543601
- **src/background/nativeMessaging.background.ts:** Changed some errors to propagate up the promise chain instead of creating a message. (We should do these for every message in the long term)
- **src/models/biometricErrors.ts**: Holds the error messages.
- **src/popup/accounts/lock.component.ts**: Added logic for non user initiated biometric triggers.
- **src/popup/settings/settings.component.ts**: Handle the new way of showing errors. …

Add support for no intrusive biometric

---

src/popup/app.component.ts
src/popup/send/send-groupings.component.ts
src/services/state.service.ts

Fix https://app.asana.com/0/1199398283201888/1201964764557907.
1. use FF
2. navigate to create a new Send
3. exit the popup (by clicking out of it) - no need to save the Send
4. open the popup and click the Send tab
5. observe infinite spinner
This is caused by retrieving the `BrowserSendComponentState` from in memory storage. When I try to log the stored value, I get a dead object error:
Dev tools:
The problem appears to be that the component state object is created in the popup and is garbage collected when the popup closes. `StateService` (in the background) tries to hold onto the object but can't.
We don't actually intend for these states to persist after the popup is closed anyway, so we should just clear these values more aggressively to ensure they don't persist between popup …

Fix infinite spinner when trying to restore Send state

---

src/popup/scss/box.scss
src/popup/vault/view-custom-fields.component.html
src/popup/vault/view.component.html

**May be cherry-picked to rc**
Fix misalignment of box-row content:
This was caused by #1780. The problem was that the character count view takes up a lot of vertical space, and the action buttons are vertically centered. This means that when you show the character count, the box-row expands, and the action buttons jump from under the cursor (to the new vertical center).
To solve this, we set `align-self: start`, but that was applied to the whole box model, so it had unintended consequences elsewhere.
- **src/popup/scss/box.scss** - undo the relevant `git blame` changes. Only apply `align-self: start` to those action buttons that we need it for, with a slight margin to align it. The pixel margin feels like a bit of a fudge, but it's only for this specific instance where we can be pretty …

EC-121 Fix box alignment

---

src/popup/generator/password-generator.component.html

Currently the range slider in the password generator options receives keyboard focus when navigating through the modal using `Tab`/`Shift+Tab`, but it lacks a focus indicator. Fundamentally though, the slider is redundant for keyboard users, as they can already operate the number input/spin box that precedes it. This PR removes the range slider from the keyboard focus cycle using `tabindex="-1"`.
Further, the range slider currently lacks an accessible name. Assistive technologies just announce it as a generic unlabelled "slider". This PR adds an explicit `aria-label` that mirrors the label for the preceding number input. This way, assistive tech users that still manage to reach the slider (e.g. using reading keys, rather than `Tab`/`Shift+Tab`) will still hear it announced …

[PS-122] Add `aria-label` to password generator length slider, make it non-keyboard-focusable

---

src/popup/app.component.ts

Fix the following bug:
install extension
select create account
fill out necessary fields
expected:successful account creation
actual:no error message or any UI feedback at all
Regression caused by https://github.com/bitwarden/browser/pull/2449. The new logic tries to clear grouping component state even when the user is not logged in, i.e. where `account == null`, and it throws an error about accessing the property of an undefined object.
Fix this by checking that the user is authenticated first.
**This will be picked to rc.**

[PS-199] Check if logged in before clearing grouping state

---

src/popup/scss/base.scss
src/popup/tabs.component.html

The tabs are currently exposed as links, and do not programmatically convey when they're selected/active or not.
This PR changes the tabs to `<button>` elements, and uses `aria-pressed` to programmatically denote when a tab is active (`aria-pressed="true"`) or not (`aria-pressed="false"`).
Closes https://github.com/bitwarden/browser/issues/1982
- **src/popup/tabs.component.html**: change the `<a routerlink="..." ...>` controls to `<button routerlink="..." ...>` (more semantically accurate, as they act as toggles), adds a local variable for each and uses it to set `aria-pressed`
- **src/popup/scss/base.scss**: expand the styles for tabs to apply not just to `a` elements, but both `a` and `button` elements. as by default buttons don't seem to auto-expand to full available width when in a …

[PS-266] A11y: change tabbed interface to toggle buttons, correctly announce currently active tab as pressed

---

src/popup/accounts/set-password.component.html
src/popup/components/password-reprompt.component.html

`<button>` elements already have an implicit button role by default, so `role="button"` is unnecessary
- **src/popup/accounts/set-password.component.html** and **src/popup/components/password-reprompt.component.html**:  remove unnecessary `role="button"`
No UI/visual change change.
None.

Remove unnecessary `role="button"` on `<button>` elements

---

src/popup/generator/generator.component.html

Show current selection as enabled on generator type option when "coming from add/edit" page.
- generator component view - Expended condition in `[disable]` attribute to only include types that are not the current selection.
- 
Test generating usernames and passwords from add/edit page.

fix disabling of generate type

---

src/popup/components/action-buttons.component.html
src/popup/components/cipher-row.component.html
src/popup/scss/box.scss

Currently, the various controls for each cipher/item in "Tab" and "My Vault" are not operable using the keyboard. Only the item as a whole receives focus, so a keyboard user can currently only either autofill (in "Tab") or view the item (in "My Vault"). The other controls (e.g. to copy just the username or password, to view - when in "Tab" -, etc) are only operable with the mouse.
This PR makes all controls for each cipher/item actual `<button>` elements, meaning they can be focused and operated using the keyboard. When the control is disabled, the `<button>` also receives an actual `disabled` attribute, making it non-keyboard-focusable and programmatically denoting that it's disabled.
In addition, this PR also adds extra information to each cipher/item, giving it an ARIA group role and …

[PS-329] A11y: make view, copy, etc controls for ciphers/items keyboard focusable/operable, add screen reader improvements

---

src/_locales/en/messages.json
src/popup/generator/generator.component.html

Add support for forwarded email generation with SimpleLogin, AnonAddy, and Firefox Relay to the username generator.
- **generator component view:** Added forwarded email provider options.
- **messages:** New translation strings.
Test each email forwarding service to make sure aliases are properly generated.
Test error conditions when service not properly configured.
Test error conditions when errors occur at the service itself (such as exceeding paid/free limits).

Forwarded email providers to username generator

---

src/popup/scss/box.scss
src/popup/scss/pages.scss

When navigating with the keyboard, you notice that the padding/margin around various (icon-based) controls is a bit...off-centre and disheveled looking.
This PR fixes the padding/margin so that icons always appear in the centre of their button. Using negative margins, this also tries to keep the overall look mostly the same/balanced.
- **box.scss**: remove the smaller right-hand padding, use negative right-hand margin instead
- **pages.scss**: tweak the padding/margin for the new generator buttons
Login before:
Login after:
---
Tab before:
Tab after:
---
My Vault before:
My Vault after:
---
Generator copy before:
Generator copy after: 
Generator refresh before:
Generator refresh after:
- test using keyboard navigation (`Tab` / `Shift+Tab`)

[PS-517] Normalise/fix button focus outlines

---

.github/workflows/build-browser.yml

While doing the last touches up on the mono repository, I forgot to bump jslib to the expected commit.
It also seems we lost the artifact path fixes from #2533.

[EC-183] Bump jslib to match the expected version

---

apps/browser/README.md

Trivial: correct markdown error in readme

Minor: correct markdown for image/alt in browser readme

---

.github/workflows/build-browser.yml

After the move to the mono-repo the browsers build action to push to Crowdin was failing as it could not find the configuration file.
https://github.com/bitwarden/bitwarden/runs/6289099115?check_suite_focus=true
- **.github/workflows/build-browser.yml:** Fix path to Crowdin config.yml

Fix directory for browser's Crowdin push config

---

apps/browser/src/popup/generator/generator.component.html

After adding email forwarding services to username generation, I neglected to implement `appApiAction` to handle the `usernameGeneratingPromise` as done in https://github.com/bitwarden/desktop/commit/75470dc1699eae28d79b39b02f5627f0b8716d67 .
- **generator component html:** Add `appApiAction` and spinning/disabled regenerate button.
n/a
Make sure button spins and disabled while waiting on API calls to third party services to finish.

add appApiAction to username generation

---

apps/browser/crowdin.yml

The Crowdin pull for browser was failing (https://github.com/bitwarden/clients/actions/runs/2278951990). The paths in the crowdin.yml had to be adjusted to the new repo structure.
If these changes fix the pull issue, then here's another [PR](https://github.com/bitwarden/clients/pull/2642) to add desktop crowdin pull and also fix the paths in `apps/desktop/crowdin.yml`.
- **apps/browser/crowdin.yml:** appended `/apps/browser` to all paths inside crowdin.yml for browser

Crowdin-Pull: Fix paths in browsers crowdin.yml

---

apps/browser/src/popup/settings/excluded-domains.component.html
apps/browser/src/popup/vault/add-edit.component.html

Currently, URI toggles ("Toggle current URIs" and "Toggle options" in the "Add item" view, "Toggle current URIs" in the "Settings > Excluded domains" listing) don't expose their toggle state to assistive technologies. This PR adds `aria-pressed` to these toggles. Additionally, it removes `appBlurClick` which leads to unnecessary loss of focus (similar to https://github.com/bitwarden/desktop/pull/1514)
Closes https://github.com/bitwarden/clients/issues/2653
- **src/popup/vault/add-edit.component.html:** remove `appBlurClick` from the two URI toggles, add `aria-pressed` to reflect their state
- **src/popup/settings/excluded-domains.component.html:**remove `appBlurClick` from the URI toggle, add `aria-pressed` to reflect its state
Videos using Chrome/NVDA on Windows, demonstrating how the …

[PS-555] Browser: Accessibility - Add `aria-pressed` to URI toggles, remove `appBlurClick`

---

apps/browser/src/popup/scss/box.scss
apps/desktop/src/scss/box.scss

Currently, both in the browser extension (in Chrome) and the desktop app, the chevron icon for expandable headers buttons is vertically misaligned. The problem is particularly visible in the chrome extension when navigating using the keyboard, as the outline awkwardly goes around the vertical "bump" of the icon. This PR fixes the alignment.
- **apps/browser/src/popup/scss/box.scss** and **apps/desktop/src/scss/box.scss**: add `align-items:center` to fix the vertical alignment of the icon
Current look of the expand/collapse controls in the chrome extension - note the chevron icon being too far to the top:
--- 
Note that in Firefox, this is currently not an issue, strangely enough. 
However, I verified that the change from this PR does not adversely affect Firefox in this case. There is no …

[PS-556] Desktop / Browser: Fix vertical alignment of expandable header chevron

---

apps/desktop/src/main/menu/menu.help.ts

Udpating the link in the desktop help menu to open a github issue.
- **apps/desktop/src/main/menu/menu.help.ts:** Updated help menu link from `https://github.com/bitwarden/desktop/issues` to `https://github.com/bitwarden/clients/issues`
When clicking on the menu entry, expect to be directed to the bitwarden/clients issues

[EC-195] Mono-repo: Update issues link to our new repos

---

apps/browser/src/popup/scss/base.scss

This may come down to a stylistic preference, but: currently, when certain controls/buttons (mostly it seems, the ones in the top toolbar) receive focus, they have a text underline. This looks strangely "webby" for text buttons, but leads to the very strange look of the "+" add button with underline, which just looks like an odd +/- symbol.
As it seems that in most other buttons/links this underline is then re-suppressed/not displayed (see for instance the "Pop out to new window" button which, in the CSS, is also set to underline, but due to the way the icon looks the underline is hidden), I'd love to see the underline removed here, for a cleaner/more consistent look.
Obviously, this will need to be run past design/UI decision makers.
- **/apps/browser/src/popup/scss/base.scss:** Remove …

[PS-565] Browser: Remove underline from focused buttons/controls

---

apps/browser/src/popup/vault/vault-select.component.html
apps/browser/src/popup/vault/vault-select.component.ts

https://bitwarden.atlassian.net/jira/software/projects/SG/boards/34?selectedIssue=SG-262
When logging in to the extension the organization switcher added for the End User Vault Refresh initiative does not appear until the page is refreshed in some way.
This is happening because of a sync problem. We are rendering content before a sync completes, so the switcher is checking for organizations before that data has been registered to state. The switcher shows up when refreshing the page because usually the sync has completed by then.
Unfortunately, this is a pattern of behavior that I don't think we can properly fix right now. Collections and folders have the same problem, and there is a bit of a hack in place right now that refreshes that data when a sync …

[fix] Organization switcher not loading on initial login

---

apps/browser/src/popup/vault/ciphers.component.ts
apps/browser/src/popup/vault/vault-filter.component.html
apps/browser/src/popup/vault/vault-filter.component.ts

Show folders and filter collections based on the selected collection
- **apps/browser/src/popup/vault/ciphers.component.ts:** Show vault filter in folders
- **apps/browser/src/popup/vault/vault-filter.component.html** Don't hide folders if an org is selected
- **apps/browser/src/popup/vault/vault-filter.component.ts** Pass org id to buildCollections to filter out collections from other orgs.

[SG-294] Show folders and properly filter collections

---

apps/desktop/src/scss/buttons.scss

https://bitwarden.atlassian.net/jira/software/projects/SG/boards/34?selectedIssue=SG-282
Long filters do not truncate when they wrap and instead cut off the screen. They should truncate with an ellipsis.
Add the necessary scss to truncate text buttons

[fix] Truncate text buttons on overflow

---

apps/browser/src/popup/vault/add-edit.component.ts
apps/browser/src/popup/vault/ciphers.component.ts
apps/browser/src/popup/vault/current-tab.component.ts
apps/browser/src/popup/vault/vault-filter.component.html
apps/browser/src/popup/vault/vault-filter.component.ts
apps/browser/src/popup/vault/vault-select.component.ts

- Adding an Item defaults owner to selected vault
- Close vault filter if view behind it is scrolled
- **apps/browser/src/popup/vault/add-edit.component.ts:** Use selectedVault param to set owner dropdown
- **apps/browser/src/popup/vault/ciphers.component.ts:** Pass selectedVault as a param
- **apps/browser/src/popup/vault/current-tab.component.ts:** Pass selectedVault as a param
- **apps/browser/src/popup/vault/vault-filter.component.ts:** Pass selectedVault as a param
- **apps/browser/src/popup/vault/vault-filter.component.html:** Add `cd-scrollable` directive to allow scrollStrategy to be used for vault filter
- **apps/browser/src/popup/vault/vault-select.component.ts:** Close the vault filter overlay if the user scrolls on the component behind it. …

[SG-300] Adding an Item defaults owner to selected vault

---

.github/workflows/build-browser.yml
.github/workflows/build-desktop.yml

Move the Safari extension build task from the desktop build workflow to the browser build.
Use the build Safari extension artifact in the desktop build to prepare mac OS packages

[DEVOPS-810] Move Safari build to browser workflow

---

apps/desktop/src/app/vault/vault.component.ts

https://bitwarden.atlassian.net/jira/software/projects/SG/boards/34?selectedIssue=SG-334
When the add cipher button is clicked we are supposed to be pre-filling organization, collection, and folder based on what vault filters are active.
QA reported that we aren't doing this for organizations, and I noticed it also wasn't working for folders.
Replace `VaultComponent.updateCollectionProperties()` with `VaultComponent.prefillNewCipherFromFilter()` that also considers the active organization filter and folder filter.

[fix] Prefill add cipher form from filter data

---

apps/desktop/src/app/vault/vault.component.ts

https://bitwarden.atlassian.net/jira/software/projects/SG/boards/34?selectedIssue=SG-335
This will be cherry-picked to rc
When a sync completes we reload the entire vault component. This is a little overkill, because that re-evaluates query params that haven't changed. Right now this is causing the active filter to be changed randomly on sync.
I think we just want to reload ciphers here, along with orgs/collections/folders in filters. I removed the `load()` call and just explicitly reload ciphers instead.

[fix] Be more precise about what is reloaded in the vault on sync complete

---

apps/desktop/src/scss/base.scss

When there's not enough vertical space, the `.vault-filters` container has a vertical scrollbar. Currently in `master`, this is the raw unstyled standard scrollbar, which looks ugly and odd compared to the custom styled scrollbars in the other columns.
This PR applies the same custom `--webkit-scrollbar...` styles to `.vault-filters` as well.
- **apps/desktop/src/scss/base.scss**: expand selectors for the various `--webkit-scrollbar...` pseudos to also include `.vault-filters`
Before, with the default scrollbar in the vault filters:
After, with the fix (note that here the "+" button in the second column is scrolled out of view, as this PR does not include the fix from https://github.com/bitwarden/clients/pull/2693):

Desktop: Custom webkit scrollbar styles for `.vault-filters`

---

apps/desktop/src/app/vault/vault.component.ts

https://bitwarden.atlassian.net/jira/software/projects/SG/boards/34?selectedIssue=SG-338
The trash filter is not working
We aren't passing in the `deleted` param that `CiphersComponent.reload()` expects to facilitate this. This commit passes it from the filter.
https://user-images.githubusercontent.com/15897251/169148012-51c69dc6-0492-4471-b50e-1d6b307121ab.mov

[fix] Pass deleted param to CiphersComponent.reload()

---

apps/desktop/src/app/send/send.component.html
apps/desktop/src/scss/list.scss

Fix Add Send button being hidden.
- **apps/desktop/src/app/send/send.component.html:** Move footer with 'Add Send' button into content section
- **apps/desktop/src/scss/list.scss:** Add css class to make send list full height, and scroll on overflow
ts

[SG-342] Fix 'Add Send' button being outside section

---

apps/desktop/src/app/layout/account-switcher.component.ts
apps/desktop/src/app/layout/search/search.component.ts

The search bar was not clearing in the header when users were switching between accounts.
apps/desktop/src/app/layout/search/search.component.ts
- Added broadcaster service and NgZone , search component now listens for the "clearSearchBarText" message, and then sets the search bar values to empty.
apps/desktop/src/app/layout/account-switcher.component.ts 
- sends a message now to search component to reset the search values to empty string.

Clearing the search bar when switching accounts

---

apps/desktop/src/app/accounts/settings.component.ts
apps/desktop/src/locales/en/messages.json

Desktop browser integration is currently unavailable on the linux platform. This fix shows an error when the user tries to enable it in settings.
closes #2556

[PS-524] show error when trying to enable browser integration on desktop

---

.github/workflows/release-desktop.yml

This PR fixes a spelling error when setting the output variable `release-version` on the `setup` job.
- **.github/workflows/release-desktop.yml:** Replace `verison` with `version`.

Fix Desktop Release Workflow Spelling Error

---

.github/workflows/build-browser.yml
.github/workflows/build-desktop.yml

New Desktop Builds should be automatically triggered on a new Safari Extension build completed from master, rc, or hotfix-rc branches.
I've added trigger for desktop build workflow to watch for the browser builds from branches master, rc and hotfix-rc. Also changed the conditions on the artifacts download steps in the desktop build.

Devops 818 trigger desktop on browser build

---

.github/workflows/crowdin-pull.yml

After migrating web into the mono-repo this also adds it to the crowdin-pull action
The previous action in web was actually failing for quite a while: https://github.com/bitwarden/web/actions/workflows/crowdin-pull.yml so we should execute the action after review & merge.
- **.github/workflows/crowdin-pull.yml:** Add name and crowdin_project_id crowdin-pull action

Adding web to the crowdin pull action

---

clients.code-workspace

Improve the developer experience by providing a preconfigured vscode workspace file, using the [multi-root workspace](https://code.visualstudio.com/docs/editor/multi-root-workspaces) feature. This is much better for the monorepo.
Devs should just open this file as a vscode workspace, rather than opening the folder.
Benefits:
* better UI for navigating and searching (see screenshots below)
* required to pick up vscode settings (including debugging settings) without opening app folders individually
I'll update our contributing docs to note this once merged.
File tree:
Searching for a file:
Opening a debugging terminal:
Searching for text:

Add vscode workspace file

---

apps/desktop/electron-builder.json
apps/desktop/installer.nsh

```
```
This PR fixes our Windows installer from removing Bitwarden and crashing before installing the new version.
Found the fix here: https://github.com/electron-userland/electron-builder/issues/2363#issuecomment-350693134
- **apps/desktop/electron-builder.json:** Adds the `include` key to our `nsis` config to specify the custom installer script
- **apps/desktop/installer.nsh:** Custom installer script that fixes the issue of prompting for UAC when Bitwarden is installed for `All Users`
```
```

Add NSIS custom installer script for UAC fix on Windows

---

apps/browser/src/_locales/fil/messages.json

```
```
The `fil` locale is failing due to the property `extName` being over 40 characters.  This PR replaces the value with our English default.
- **apps/browser/src/_locales/fil/messages.json:** Replace the `extName` value with our English default.
```
```

Fix extName for the 'fil' locale

---

apps/web/src/app/accounts/accept-emergency.component.ts
apps/web/src/app/accounts/accept-organization.component.ts
apps/web/src/app/common/base.accept.component.ts
apps/web/src/app/modules/organizations/users/enroll-master-password-reset.component.html
apps/web/src/app/modules/organizations/users/enroll-master-password-reset.component.ts
apps/web/src/app/modules/vault-filter/components/organization-options.component.html
apps/web/src/app/modules/vault-filter/components/organization-options.component.ts
apps/web/src/app/organizations/sponsorships/accept-family-sponsorship.component.ts
bitwarden_license/bit-web/src/app/providers/manage/accept-provider.component.ts
bitwarden_license/bit-web/src/app/providers/setup/setup-provider.component.ts
libs/common/src/models/request/organizationUserAcceptRequest.ts

```
```
Fixes two feature deficiencies with [PS-616] (bitwarden/web#1698). 
1. Withdraw should not require a user verification request
2. Auto enrollment was broken due to all enrollment requiring user verification. This is not possible with the current acceptance flow. [PS-795]
* **accept-organization**: Update accept request to optionally specify a reset password key. This key is required if (and only used if) auto enroll in master password is enabled for the organization. Side benefit of cleaning up this promise flow a bit.
* **enroll-master-password-reset.component**: This modal component now only handles enrollment in MPR. Withdrawing is handled by the organization-options component.
* **organization-options**:
* use api-action-directive to properly parse and handle api exceptions -- …

[PS-616] [PS-795] Fix/withdraw master password reset without user verification

---

apps/web/src/app/settings/emergency-access-add-edit.component.html
apps/web/src/app/settings/emergency-access.component.html
apps/web/src/app/settings/emergency-access.component.ts

```
```
The emergency access page was missing some UX candy (spinners/disabled buttons) and was using the old-style options menu for managing contacts.
* **emergency-access-add-edit.component.html:** Fix the modal to reference the `form.loading` flag instead of the submit button so that the save button is properly disabled during network communication.
* **emergency-access.component.html:** Use the new `<bit-menu />` component for the options menu and add spinners for both trusted and granted contacts while they are loading.
* **emergency-access.component.ts:** Add a `loaded` flag for spinners in the template.
```
```

[PS-787] Emergency access page UI issues

---

.github/workflows/build-browser.yml

```
```
This PR fixes the Browser Source Code artifact to only contain the source code for the `browser` client.  Currently it contained `browser` and `desktop`.
- **.github/workflows/build-browser.yml:** Added logic to copy only the `browser` source to the `browser-source.zip` artifact.
```
```

Fix Browser Source Code Artifact

---

apps/web/src/app/modules/vault-filter/vault-filter.component.ts
apps/web/src/app/modules/vault-filter/vault-filter.module.ts
apps/web/src/app/modules/vault-filter/vault-filter.service.ts
apps/web/src/app/modules/vault/modules/individual-vault/individual-vault.component.ts

https://bitwarden.atlassian.net/browse/SG-293
```
```
This is a 1:1 recreation of https://github.com/bitwarden/web/pull/1691 for `clients`
QA made a note that it would be good UX to expand the organization filters if they are hidden when clicking on an organization badge in the items list.
1. Extend the `BaseVaultFiltersService` to manage an observable for `collapsedFilterNodes` that can be modified from outside the `VaultFiltersComponent`. Update `VaultFiltersModule` to use the local service instead of the `Base` service.
2. Subscribe to the new observable in `VaultFiltersComponent.ngOnInit()` to update the collapsed state of filters when changed from outside the `VaultFiltersComponent`
3. Add a helper method to `VaultFiltersService` for expanding vault filters if they are collapsed that …

[feat] Allow the org badge click event to expand collapsed vault filters

---

.github/workflows/build-browser.yml
.github/workflows/build-cli.yml
.github/workflows/build-desktop.yml
.github/workflows/build-web.yml

```
```
Add root config files to trigger builds for all of the clients.
- **.github/workflows/build-browser.yml**: Update both pull_request and push trigger paths to include all files from the root directory except for the`.md` and `.txt` ones.
- **.github/workflows/build-cli.yml**: Update both pull_request and push trigger paths to include all files from the root directory except for the`.md` and `.txt` ones.
- **.github/workflows/build-desktop.yml**: Update both pull_request and push trigger paths to include all files from the root directory except for the`.md` and `.txt` ones.
- **.github/workflows/build-web.yml**: Update both pull_request and push trigger paths to include all files from the root directory except for the`.md` and `.txt` ones.
```
```

Add root config files to trigger build workflows

---

apps/desktop/src/app/vault/vault.component.ts

```
```
Fixes 'No Folder' showing all items in Desktop
- **apps/desktop/src/app/vault/vault.component.ts:** Fix folder condition check that was flagging all as passing the vault filter because the 'No Folder' selection does not have a folder id and we need to rely on the `selectedFolder` property to determine this properly.
Showing that Desktop and Web show the same items for the No Folder selection 
```
```

[SG-383] Fix ‘No Folder’ filter showing everything

---

apps/web/src/app/modules/vault/modules/individual-vault/individual-vault.component.ts
apps/web/src/app/modules/vault/modules/organization-vault/organization-vault.component.ts
apps/web/src/app/organizations/guards/permissions.guard.ts
apps/web/src/app/vault/ciphers.component.html

Changes the query parameter for linkable ciphers in Web Vault to use `itemId` instead of `cipherId` to avoid using "cipher" terminology in front of end users. Also maintains backwards compatibility for any `cipherId` links that are already in use.
Direct links to ciphers will now look like:  `https://vault.bitwarden.com/#/vault?itemId={GUID}`
- **individual-vault.component.ts:** Add small helper function to retrieve cipherId from either `itemId` or `cipherId` query parameters.
- **organization-vault.component.ts:** Add small helper function to retrieve cipherId from either `itemId` or `cipherId` query parameters.
- **permissions.guard.ts:** Check for both `cipherId` and `itemId` query parameters when direct linking to an organization's cipher.
- **ciphers.component.ts:** Use `itemId` …

[PS-788] - Item links use `cipherId` in query string

---

apps/web/src/app/modules/vault/modules/individual-vault/individual-vault.component.ts

https://bitwarden.atlassian.net/browse/SG-293?focusedCommentId=13459&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-13459
```
```
In the ciphers list we show a badge for organization ownership that can be clicked to filter the vault by the organization in question. This expansion does not work for items labeled "Me". Clicking these badges filters by "My Vault" but doesn't expand the filter list.
This commit corrects this behavior so the "Me" badges expand the organization filters when clicked. It does so by simply moving the line that checks for filter expansion out of a conditional that expects an organization, and instead does it any time an organization filter is changed.
* Move the `VaultFilterService.ensureVaultFiltersAreExpanded()` reference in …

[fix] Organization filter list expansion on badge click

---

apps/desktop/src/app/accounts/login.component.html
apps/web/src/connectors/captcha.scss

```
```
Our hcaptcha on desktop had formatting that caused scrollbars and weird formatting. This PR centers our hcaptcha in our connector and fixes the scrollbar issue on desktop.
```
```

[PS-927] center hcaptcha in connector and fix formatting on desktop

---

apps/web/src/app/organizations/layouts/organization-layout.component.ts
apps/web/src/app/organizations/services/navigation-permissions.service.ts

```
```
A user with the Manage SSO custom permission cannot access the org admin page.
- **apps/web/src/app/organizations/services/navigation-permissions.service.ts** - add the `ManageSso` permission to the array of permissions that get access to the "Manage" tab (and therefore the Organization admin view)
- **apps/web/src/app/organizations/layouts/organization-layout.component.ts** - add the manage SSO route to the `manageRoute()` getter. This determines which sub-page to navigate the user to when they click the Manage tab.
More work needs to be done to refactor these permissions, but this will be cherry-picked to `rc`, so I don't intend to do it here.
```
```

[EC-241] Fix Manage SSO navigation permissions

---

libs/common/src/services/search.service.ts

```
```
The purpose of this PR is to enable the Bitwarden CLI command `bw get <object> <id>` to search for the `<id>` provided in the list of URIs in a specific vault item. 
Currently, the search will only check the first URI on a specific vault item.  
See https://github.com/bitwarden/clients/issues/2762 for more details.
Added code to search through all the values in the URIs array.
Even with just a singular URI on the vault item, c.login.uris will be an array of one. 
```
```

[PS-766] Fix for CLI check full array of URIs in search

---

clients.code-workspace

```
```
The multi-root workspace config broke the Javascript Debug Terminal for cli, i.e. breakpoints are no longer being hit. This PR fixes the source maps in the workspace config.
I've verified that this fixes debugging in cli (including libs).
Credit to @MGibson1 for debugging this with me.
This basically aims to replicate the old [CLI settings.json](https://github.com/bitwarden/cli/blob/master/.vscode/settings.json):
* remove the meteor sourcemap override, we don't use meteor. I assume this was copy/pasted from an online recipe
* `"webpack:///./~/*": "${workspaceFolder:root}/node_modules/*"`   - resolves node_modules to the repo root
*  `"webpack://@bitwarden/cli/*": "${workspaceFolder}/*"`  - if you open the debug terminal in the cli workspace, then workspaceFolder will resolve to …

Fix javascript debug terminal source maps

---

apps/browser/src/popup/vault/vault-select.component.ts

Fix bug related to dropdown that would reopen when closed.
Changed the param passed to restrict click throughs, which caused the issue.

[SG-387] [Vault Filter] - Clicking the dropdown header while menu is open does not close overlay

---

apps/browser/src/_locales/en/messages.json
apps/browser/src/popup/settings/settings.component.ts

```
```
When switching to a custom time interval of 0 hours 0 minutes, an error toast appears. This happens because of this  https://github.com/bitwarden/clients/pull/2836  change on the web which prevents a user from having 0 hours 0 minutes or less as a custom timeout value on the web.
- **apps/browser/src/popup/settings/settings.component.ts:** Added an extra condition to check if the vault value is 0 on the browser, this prevents execution from getting to the toast error since the `immediately` feature on the browser is `0`.
```
```

[PS-968] regression bug fix on custom timeout switch for the browser

---

apps/web/src/app/components/premium-badge.component.ts

```
```
Our new premium badge is actually a button that has a popup. The button didn't have a type and we weren't preventing the default behavior when clicking the button. This meant that when adding a new item and pressing `Enter`, the button would be clicked, the form submitted, and the popup would show.
This PR prevents this behavior
Before (Pressing `Enter` to submit)
https://user-images.githubusercontent.com/24985544/175538562-1c5d56cd-2221-423d-9cff-cdfebefabfb0.mov
After (Pressing `Enter` to submit)
https://user-images.githubusercontent.com/24985544/175548320-ef482062-d27a-490a-958e-7d9d29c601b5.mov
```
```

[PS-998] Add button type to premium badge

---

apps/web/.gitignore
apps/web/package.json
apps/web/webpack.config.js

```
```
Add [webpack-bundle-analyzer](https://github.com/webpack-contrib/webpack-bundle-analyzer) to help us understand the size of our bundles and how webpack splits it up as we start to implement lazy loading (prompted by #2918).
The results are shown like so:
- install `webpack-bundle-analyzer`
- add `npm run build:bit:dev:analyze`. This command runs webpack, outputs build stats to a `stats.json` file, then runs `webpack-bundle-analyzer` pointing at that file.
- add a logging environment variable for `webpack.config.js`, otherwise the `envConfig` logging also gets written to the `stats.json` file
- add `stats.json` to `.gitignore`
I have deliberately chosen the CLI usage, because this ensures that the webpack bundles exist on disk and their size can be accurately measured. The …

Add webpack-bundle-analyzer

---

apps/web/src/app/modules/vault/modules/individual-vault/individual-vault.component.ts
apps/web/src/app/modules/vault/modules/organization-vault/organization-vault.component.ts

> Replace the query param strings as they were inadvertently removed during the vault filter refresh
> EC-282 
> EC-286
- **individual-vault.component.ts**: Updated `go` method to reference `activeFilter` object instead of class properties. 
- **organization-vault.component.ts**: Updated `go` method to reference `activeFilter` object instead of class properties. Added `deleted` getter and updated all references to `activeFilter.status === "trash"` to use the getter.

[EC-282/EC-286] Update queryParams to use new filter object

---

apps/web/src/locales/en/messages.json

```
```
Change the delete account toast text to be clearer that only the Bitwarden account will be deleted.
- **apps/web/src/locales/en/messages.json:** Changed the toast text message to be clearer.
```
```

[PS-724] Reword delete account toast

---

apps/web/src/app/modules/vault-filter/components/organization-options.component.ts
apps/web/src/app/settings/change-password.component.ts
libs/angular/src/components/set-password.component.ts

```
```
PS-616 added user verification to master password enrollment requests, but missed a few instances of password setting. This PR includes the new password hash in those requests.
* **change-password.component**: missed updating on master password change
* **set-password.component**: missed updating when we're setting our password after auth. This occurs for SSO-created accounts.
```
- [ x] I have checked for **linting** errors (`npm run lint`) (required)
```

[PS-1051] Fix/add master pass hash to all org reset key requests

---

apps/desktop/src/app/accounts/settings.component.ts
apps/desktop/src/locales/en/messages.json

```
```
Added a warning when the user selects vault timeout value "Never". Similar to what already happens on the browser client.
- **apps/desktop/src/app/accounts/settings.component.ts** Added logic to determine if the selected value equals to the option "Never". If true opens a dialog to confirm the choice.
- **apps/desktop/src/locales/en/messages.json**  Added dialog text message to confirm the choice
```
```

[PS-722] Desktop: Add warning when vault timeout is set to never

---

apps/desktop/src/app/vault/vault.component.ts
apps/web/src/app/modules/vault-filter/components/collection-filter.component.html
apps/web/src/app/modules/vault-filter/vault-filter.service.ts
apps/web/src/app/modules/vault/modules/individual-vault/individual-vault.component.ts
apps/web/src/app/modules/vault/modules/organization-vault/organization-vault.component.ts
apps/web/src/app/modules/vault/vault.service.ts
libs/angular/src/modules/vault-filter/components/collection-filter.component.ts
libs/angular/src/modules/vault-filter/models/vault-filter.model.spec.ts
libs/angular/src/modules/vault-filter/models/vault-filter.model.ts
libs/angular/src/modules/vault-filter/vault-filter.component.ts
libs/angular/src/modules/vault-filter/vault-filter.service.ts
libs/common/src/services/collection.service.ts

```
```
Fix regression where filtering on "Unassigned" collections is no longer possible
- **apps/web/src/app/modules/vault-filter/vault-filter.service.ts**
Always add an `Unassigned` collection when the user is an admin (emulating how `No folder` is implemented.)
- **apps/web/src/app/modules/vault/modules/individual-vault/individual-vault.component.ts**
Remove `buildFilter` and use the new common one in `vault-filter.model.ts`
- **apps/web/src/app/modules/vault/modules/organization-vault/organization-vault.component.ts**
Remove `buildFilter` and use the new common one in `vault-filter.model.ts`
- **libs/angular/src/modules/vault-filter/models/vault-filter.model.spec.ts**
Added tests for existing and new filter function behavior  
- …

[EC-267] Unassigned collection has disappeared in web vault

---

apps/desktop/electron-builder.json

https://bitwarden.atlassian.net/browse/SG-421
```
```
Patch a bug we are seeing from the `2022.06` `desktop` release that renders browser biometrics unusable on Windows machines. 
When we moved the projects to a monorepo we also started using a root level `package.json` file. 
One of the desktop dependencies is `regedit`, and we package a registry list from `regedit` into the distribution files of Windows builds. This is then used to modify registries to enable browser biometrics.
We did not modify the file path for these dist files, so they are still looking for `desktop/node_modules`. They should be looking for `clients/node_modules`.
This commit updates this file path to look upwards to the root `node_modules` folder.
```
```

[fix] Adjust extraResources in electronBuilder to account for the monorepo move

---

libs/common/src/services/state.service.ts

https://bitwarden.atlassian.net/jira/software/projects/SG/boards/34?selectedIssue=SG-423
```
```
On https://github.com/bitwarden/jslib/pull/824 we fixed a generator bug. That PR was lost in the move to `clients`, and is missing from its code and history. This PR recreates jslib 824 verbatim.  
```
```

[fix] Generator settings not persisting across web sessions

---

.github/workflows/release-web.yml

```
```
Move the `latest` tag to be created on update to the self-host script instead of the server/web releases.
Related PRs:
- https://github.com/bitwarden/self-host/pull/33
- https://github.com/bitwarden/server/pull/2098
- **.github/workflows/release-web.yml:** Remove tagging Docker images as `lastest, only tag a static version.
```
```

[DEVOPS-832] Update timing on SelfHost "latest" tag

---

.github/workflows/release-qa-web.yml

```
```
Publish QA web vault to separate branch (same strategy as on production web vault). To create better parity between Production and QA, we need to move the QA Web Vault to Cloudflare Pages.
- **.github/workflows/release-qa-web.yml:** Download the newest web vault version and commit it to `cf-pages-qa` branch. The branch is tracked by Cloudflare pages and web vault will be published from it.
```
```

Move the QA Web Vault to CloudFlare Pages

---

apps/web/src/app/settings/organization-plans.component.html
apps/web/src/app/settings/organization-plans.component.ts

```
```
Fix issue where form would allow submit if email is invalid
Fix issue with F4E org create form not having default product set
- **apps/web/src/app/settings/organization-plans.component.html:** 
- Use new bit-submit-button component to assist in form validation
- Remove duplicate form field validators
- **apps/web/src/app/settings/organization-plans.component.ts:** 
- Make name and billing email required only if a new org is being created. 
- Set default product if `acceptingSponsorship` is true.
Submit in new org:
https://user-images.githubusercontent.com/8926729/178771687-c95800ea-fa8d-4f8e-bcba-b0a63e383294.mov
F4E new org screen:
https://user-images.githubusercontent.com/8926729/178776302-eea90787-4002-47d3-91df-911d836405b9.mov
```
```

[SG 435 & SG-436] Reusable org Component bug fixes

---

apps/browser/src/background/main.background.ts
apps/browser/src/popup/services/services.module.ts
libs/angular/src/services/theming/theming.service.ts

https://bitwarden.atlassian.net/jira/software/projects/SG/boards/34?selectedIssue=SG-379
```
```
The Safari extension is not respecting the OS set system theme, and is always in light mode when system theme is selected in the extension.
On https://github.com/bitwarden/clients/pull/2943 we moved theming out of the background page and into the popup exclusively (yay). It turns out, Safari doesn't like this (oh no). The Safari popup does not handle the `(prefers-color-scheme)` media query correctly, and always matches to light mode. I don't have an explanation for why this happens, I never found any resources related to this issue, but using the background  window instead to determine the system theme works correctly.
Using the background window has many downsides, however. 
* The entire …

[fix] System theming in the Safari extension

---

libs/angular/src/services/theming/theming.service.ts

https://bitwarden.atlassian.net/browse/PS-1135
```
```
DI is busted on the latest desktop build and needs to be patched. Current builds on TestFlight don't load.
This is happening because on https://github.com/bitwarden/clients/pull/3107 I used a union typed constructor argument that Angular (understandably) does not know how to inject on clients that don't use a factory to build it.
To resolve the issue I've removed the reference to Angular's `MediaMatcher`  in `ThemingService` and instead universally leaned on a `Window` for `ThemingService`'s media matching needs.
```
```

[fix] Always use the Window directly in ThemingService

---

.github/workflows/release-cli.yml
.github/workflows/release-desktop.yml

```
```
At times, we find that we need to re-run a workflow to publish to an app store. We need the ability to have more selection over the specific stores. This adds a boolean input for each publish option, which defaults to `true`. 
- **.github/workflows/release-cli.yml:** Added publish options
- **.github/workflows/release-desktop.yml:** Added publish options
Desktop:
CLI:
```
```

Add publish options to release workflows

---

apps/web/src/app/settings/organization-plans.component.html

```
```
When switching the template driven form to a reactive form, a field was missed, causing the binding to not display correctly. 
This is just swapping out the old property for the new one.
- **apps/web/src/app/settings/organization-plans.component.html:** Replace `additionalStorage` with `formGroup.controls["additionalStorage"].value`
Before:
After:
```
```

[SG-445] Fix additional storage binding for annual total

---

apps/web/config/qa.json

```
```
Test that turning off the showTrial flag in qa.json turns off the ability to route to `https://vault.qa.bitwarden.pw/#/trial`
Set `showTrial` to false
```
```

[SG-439] Turn off trial route in qa for testing

---

apps/browser/src/popup/settings/settings.component.html
apps/browser/src/popup/settings/settings.component.ts
apps/desktop/src/app/accounts/settings.component.html
apps/desktop/src/app/accounts/settings.component.ts
apps/desktop/src/locales/en/messages.json

1. I missed some changes and some typos in the initial PR, this fixes those.
2. After discussions with @danielleflinn the "Ask for biometrics on launch" checkbox is now hidden if biometrics are disabled (see: https://bitwarden.atlassian.net/browse/PS-684)
3. I refactored biometric checkbox to use `ngModel`. Also added a note about a bug that's is affecting the checkbox (the bug is not introduced in this PR, it's been there since before). The bug affects `[checked]` as well as `[ngModel]`.
- **apps/browser/src/popup/settings/settings.component.html:** Hide auto prompt checkbox if biometrics disabled.
- **apps/browser/src/popup/settings/settings.component.ts :** Remove superfluous default. State service already contains default values.
- …

[PS-683] Fix missed defaults and sentence cases

---

apps/web/src/app/modules/trial-initiation/trial-initiation.component.html
apps/web/src/app/modules/trial-initiation/trial-initiation.component.ts
apps/web/src/app/oss-routing.module.ts

```
```
Replace the `register` route with the `TrialInitiation` component. This is still feature flagged so we can flip the switch to show/hide it if needed. This also created the need to add a state where an account is created not in the Trial flow.
- **apps/web/src/app/modules/trial-initiation/trial-initiation.component.html:** Show only register component if the org parameter is not passed. The diff shown is a lot bigger than the actual change, the trial content has been wrapped in a div with an ngIf to display only if the user is in the trial flow.
- **apps/web/src/app/modules/trial-initiation/trial-initiation.component.ts:** Add policy checks for account creation
- **apps/web/src/app/oss-routing.module.ts:** Replace RegisterComponent with TrialInitiationComponent if the showTrial …

[SG-462] Move Trial Initiation to register route

---

apps/web/src/app/services/event.service.ts
apps/web/src/locales/en/messages.json
libs/common/src/enums/eventType.ts

```
```
We're missing the `EventType`s for restore/revoke events, so the description comes up empty. Fix this by adding the new event types to clients.
**This will be cherry-picked to rc**
- update `EventType`s to match event types on the server
- add i18n strings in `EventService`
- copy `messages.json` from https://github.com/bitwarden/clients/pull/3135 to get the new wording (no additional changes to this file). We should merge that PR first.
```
```

[EC-339] Add eventType and UI strings for Restore/Revoke OrgUser

---

apps/desktop/stores/chocolatey/tools/chocolateyinstall.ps1

Fix URL pointing to the desktop release in the chocolatey install script.
- **apps/desktop/stores/chocolatey/tools/chocolateyinstall.ps1:** Change repo and tag name in the url
```
```

Fix url in choco install script after monorepo migration

---

apps/browser/src/background/runtime.background.ts
apps/browser/src/popup/vault/current-tab.component.ts
apps/browser/src/popup/vault/view.component.ts
apps/browser/src/services/autofill.service.ts

```
```
Require specifying the tab that is to be autofilled in the autofill service.
- **apps/browser/src/services/autofill.service.ts:** Add a `tab` property to `options` to specify the tab to be autofilled.
- **_all others changes_:** Make use of the new `tab` property when calling `doAutoFill()` from the `autofillService`
```
```

[PS-94] Ensure autofill always uses the same tab

---

.eslintrc.json
package.json

```
```
Ensures the pipeline fails on eslint errors, and changes some warnings to errors as we want those to be blocked.
```
```

Change eslint settings to error instead of warn

---

libs/components/src/tabs/tab-item.component.ts

> Update tabs component to use the `focus-visible` attribute for keyboard selection instead of `focus`. This prevents focus from mouse clicks.
> CL-17
- **tab-item.component.ts**: Replaced `focus` with `focus-visible` for keyboard selection

[CL-17] Use focus-visible for keyboard selection

---

apps/browser/src/popup/settings/excluded-domains.component.ts

This is to fix the error of "localhost is not a valid domain" whenever localhost is added to the excluded domains on the settings menu.
```
```
- **apps/browser/src/popup/settings/excluded-domains.component.ts:** 
- Added a new method `getNewlyAddedDomians` that extract the new/modified URI that the user added. 
- Made modifications to the `submit`, so that only the newly/Modified URI will be validated, while the existing ones will be saved without validation because they have been validated already. 
```
```

Ps 693/fix localhost exclude domain bug 2

---

apps/browser/src/popup/scss/pages.scss
apps/desktop/src/scss/environment.scss
apps/desktop/src/scss/pages.scss

```
```
With the changes made with https://github.com/bitwarden/clients/pull/2662 the settings button for setting the environment urls disappeared. This brings it back.
Additionally I removed the no longer needed css for the settings button for desktop.
- **apps/browser/src/popup/scss/pages.scss:** Change css to be applied to a <button> instead of a link (<a>)
- **apps/desktop/src/scss/environment.scss:** Removed no longer needed `settings-icon` from css, which was replaced with `environment-urls-settings-icon`
- **apps/desktop/src/scss/pages.scss:** Removed no longer needed `settings-icon` from css, which was replaced with `environment-urls-settings-icon`
```
```

Fix missing settings button

---

apps/web/src/app/modules/trial-initiation/billing.component.ts
apps/web/src/app/modules/trial-initiation/trial-initiation.component.ts
apps/web/src/app/oss-routing.module.ts

```
```
- Allow routing to both Register component and Trial Component to allow Marketing to do a phased rollout of the new trial flow
- Fix bug where if a valid org param isn't passed, no org type is chosen and going through the stepper errors on billing
- Fix a bug where creating a families org in the the stepper throws an error
- **apps/web/src/app/modules/trial-initiation/billing.component.ts:** Set additional seats to 0 is it is a families plan
- **apps/web/src/app/modules/trial-initiation/trial-initiation.component.ts:** Default org selected to families if the param is not a valid one
- **apps/web/src/app/oss-routing.module.ts:** Allow routing to both Register and Trial (but still have Trial feature flagged)
```
```

[SG-485] and [SG-486] Trial Initiation routing and bug fixes

---

.github/workflows/release-browser.yml
.github/workflows/release-cli.yml
.github/workflows/release-desktop.yml
.github/workflows/release-qa-web.yml
.github/workflows/release-web.yml

```
```
In order for Jira to track Deployments, our release/deploy YAML jobs needed to call the Deployment and Deployment Status APIs in GitHub.  See [here](https://github.com/atlassian/github-for-jira/blob/main/docs/deployments.md) for documentation.
.github/workflows/release-browser.yml
.github/workflows/release-cli.yml
.github/workflows/release-desktop.yml
.github/workflows/release-qa-web.yml
.github/workflows/release-web.yml
- For all of these files, the changes were to add job steps that will create a Github deployment, then update the deployment status to success or failure.
```
```

[ENG 71] Add calls to Github Deployments API to allow Jira integration on Deployments

---

libs/common/src/services/state.service.ts

```
```
When logging in to CLI with a username and password, I receive:
```
webpack-internal:///../../libs/common/src/services/state.service.ts:2000
userId: state.activeUserId,
^
TypeError: Cannot read properties of null (reading 'activeUserId')
at StateService.eval (webpack-internal:///../../libs/common/src/services/state.service.ts:2000:31)
at Generator.next (<anonymous>)
at fulfilled (webpack-internal:///../../libs/common/src/services/state.service.ts:41:58)
```
This is because a callback (`stateUpdater`) passed to the `updateState` method was returning null, so it was setting the state to null, and this error was thrown the next time we tried to check something on the state.
**This will be picked to rc**
- **libs/common/src/services/state.service.ts**
- Change the problematic …

Don't allow updateState to set state to null

---

apps/desktop/src/app/accounts/delete-account.component.html
apps/desktop/src/app/accounts/delete-account.component.ts
apps/desktop/src/app/accounts/settings.component.html
apps/desktop/src/app/accounts/settings.component.ts
apps/desktop/src/app/app.component.ts
apps/desktop/src/app/app.module.ts
apps/desktop/src/locales/en/messages.json
apps/desktop/src/main/menu/menu.account.ts
apps/desktop/src/scss/box.scss
apps/desktop/src/scss/misc.scss
apps/desktop/src/scss/pages.scss
apps/web/src/app/settings/delete-account.component.html
apps/web/src/app/settings/delete-account.component.ts
apps/web/src/locales/en/messages.json
libs/angular/src/components/user-verification.component.ts
libs/angular/src/services/jslib-services.module.ts
libs/angular/src/services/modal.service.ts
libs/common/src/abstractions/account/account-api.service.abstraction.ts
libs/common/src/abstractions/account/account.service.abstraction.ts
libs/common/src/abstractions/api.service.ts
libs/common/src/services/account/account-api.service.ts
libs/common/src/services/account/account.service.ts
libs/common/src/services/api.service.ts

Placeholder
MAS (Mac App Store) has rejected our release due to some new changes to the app store review guidelines effective June 30 which were not communicated due to our Desktop client missing an ability for a user to delete their user account.
- **apps/desktop/src/app/accounts/delete-account.component.html:** New desktop modal
- **apps/desktop/src/app/accounts/delete-account.component.ts:** New desktop modal
- **apps/desktop/src/app/accounts/settings.component.html:** New option linking to desktop modal
- **apps/desktop/src/app/accounts/settings.component.ts:** New option linking to desktop modal
- **apps/desktop/src/app/app.component.ts:** Use new function in modal service to close all modals
- **apps/desktop/src/app/app.module.ts:** New desktop modal component
- …

[EC-317] Desktop client delete user account

---

libs/components/src/toggle-group/toggle.component.ts

```
```
Changes `[1px]` to `px`, since we should avoid absolute values.
```
```

Remove absolute value in toggle group

---

apps/browser/src/popup/vault/current-tab.component.ts

```
```
When selecting a vault on the vault selector the focus was lost. This was caused because the selector was removed from DOM on ngIf.
- **vault-select.component.ts:** Added new variable isLoading to check if load() function is running. Kept loaded variable to so the ngIf on the html page only changes on the first run.
```
```

[PS-1161] Keeping focus on vault selector after selecting a vault

---

libs/common/src/models/domain/organization.ts

```
```
Fix bug where non-enterprise owners and admins can access the Manage SCIM page.
**This will be picked to `hotfix-rc-scim`**
- **libs/common/src/models/domain/organization.ts** - add `useScim` to the `canManageScim` checks, which makes sure that the organization has SCIM enabled. This is not the current pattern for this class, but logically you cannot manage it for your org if the org does not have it enabled. I will create a tech debt ticket to review this and refactor permission handling.
```
```

Fix non-enterprise users being able to access scim

---

apps/browser/src/popup/vault/vault-select.component.ts

```
```
Currently when the vault selector is open and Escape key is pressed. The whole browser extension popup is closed. It should close the selector on this case.
- **vault-select.component.ts:** Added listener to prevent escape from closing the extension popup
```
```

[PS-1162] Preventing escape from closing popup when vault selector is open

---

apps/cli/package.json
apps/cli/src/commands/serve.command.ts
apps/cli/src/program.ts

```
```
Blocks requests that are coming from browser by blocking any request with an `Origin`. Optionally allow users to allow requests with an `origin` header.
Note, a list of allowed origins is not acceptable here since origin can be changed in extensions.
- **serve.command.ts**: Insert koa middleware which responds with 403 if origin protection is enabled.
- **program.ts**: Add option to disable origin protection.
```
```

[PS-1152] CLI serve forbid browser requests

---

apps/browser/src/popup/app.component.ts
apps/desktop/src/app/accounts/lock.component.ts
apps/desktop/src/app/app.component.ts
apps/desktop/src/app/layout/search/search-bar.service.ts
apps/desktop/src/app/layout/search/search.component.ts
apps/desktop/src/app/send/send.component.ts
apps/desktop/src/app/vault/ciphers.component.ts
libs/angular/src/components/lock.component.ts
libs/common/spec/services/folder.service.spec.ts
libs/common/src/abstractions/state.service.ts
libs/common/src/services/environment.service.ts
libs/common/src/services/folder/folder.service.ts
libs/common/src/services/state.service.ts

```
```
We should only be subscribing to observables and if we create subscriptions, we should keep a reference and clean them up when not needed anymore (`unsubscribe`). We currently expose the `BehaviourSubject` and subscribe to this and also call unsubscribe. Calling `unsubscribe` on a subject, cancels all subscriptions and not just the one in use.
This is part of https://bitwarden.atlassian.net/browse/TDL-121
- **libs/common/src/abstractions/state.service.ts**: Change type of `activeAccount` to be an `Observable` instead of a `BehaviourSubject`
- **libs/common/src/services/state.service.ts**: 
- Change type of `activeAccount` to be an `Observable` instead of a `BehaviourSubject`
- Change `activeAccountSubject` to be used change state (`BehaviourSubject`) internally and not be exposed …

Fix active account and searchBar observables/subscriptions

---

.github/workflows/release-cli.yml

```
```
Applied solution from https://github.com/npm/cli/issues/2453 thread to fix publish CLI to NPM.
```
```

Fix CLI publish to NPM

---

apps/web/src/app/accounts/register-form/register-form.component.ts
apps/web/src/app/accounts/register.component.html

```
```
When creating the new reusable components, we missed sending the reference data on submit of the register form.
- **apps/web/src/app/accounts/register-form/register-form.component.ts:** Get referenceData as an input from parent component
- **apps/web/src/app/accounts/register.component.html:** Send referenceData from outer component to new register component.
```
```

[SG-575] Send reference data on account creation

---

apps/desktop/native-messaging-test-runner/src/test-ipc.ts
apps/desktop/src/app/accounts/settings.component.ts
apps/desktop/src/main.ts

```
```
Fixes a bug where enabling browser setting was not starting native messaging service.
- **apps/desktop/src/app/accounts/settings.component.ts:** Send correct value to messaging service
- **apps/desktop/src/main.ts:** Wasn't causing issues, but fix missing await I noticed while investigating this
- **apps/desktop/native-messaging-test-runner/src/test-ipc.ts:** Update test runner error message with more context
```
```

[SG-569] Native Messaging settings bug

---

libs/common/src/abstractions/config/ServerConfig.ts
libs/common/src/services/config.service.ts

Most of these commits are not relevant to the issue you were facing, and are just changes I made along the way while debugging. Feel free to merge this PR, cherry pick the stuff you want, or recreate the changes you need by hand.
The final commit, [Build server config in async](https://github.com/bitwarden/clients/commit/599e03583147da1a9659ec6a1c700d9339eac346), fixes your issue with subscriptions. Javascript doesn't support async management in constructors, but some of your observable logic runs asynchronously like fetching configs from state or the server. A good way to circumvent this is to lean on some other observable that doesn't have this dependency, like checking if the active account is unlocked in state. Then you can do all of your async checks in the subscription callback. …

Sm 90 addison

---

libs/angular/src/components/lock.component.ts

```
```
This fixes a bug where the lock component gets stuck in a loading state while switching between accounts.
Although the bug only occurs on desktop because of account switching, the change was made in libs which affects also web and browser. I have verified that there are no negative effects from removing the initial `this.load`
This was likely introduced due to my changes with https://github.com/bitwarden/clients/pull/3268 which fixed the subscription to `activeAccount$`
- **libs/angular/src/components/lock.component.ts**: Do not call `this.load` on the ngOnInit twice. 
```
```

[PS-1290] Client fails to render vault when switching between accounts

---

apps/web/config/cloud.json
apps/web/config/selfhosted.json

```
```
Enabled Trial Initiation in cloud.  It was disabled for the `2022.8` release but will be enabled for `2022.9`.
- **cloud.json:** Enabled showTrial feature flag
```
```

[SG-587] Enabled showTrial feature flag in cloud

---

apps/web/src/app/vault/vault.module.ts

https://bitwarden.atlassian.net/jira/software/projects/SG/boards/34?selectedIssue=SG-360
```
```
The work to remove the `module/` folder left out an import, which is causing organization badges to not appear.
Import `OrganizationBadgeModule` in `VaultModule` where it is used.
```
```

[SG-550] Import OrganizationBadgeModule in VaultModule

---

.github/workflows/build-browser.yml
.github/workflows/build-cli.yml
.github/workflows/build-desktop.yml
.github/workflows/build-web.yml
.github/workflows/release-browser.yml
.github/workflows/release-cli.yml
.github/workflows/release-desktop.yml
.github/workflows/release-web.yml

```
```
With every hotfix for Web, Cli, and Browser we push out on the shared `hotfix-rc` branch, we block Desktop TestFlight publishing on `master` and `rc`. As we near the start of release preparation, hotfixes on Web, Cli, and Browser jeopardize the testing time of Desktop since the latest version cannot be published to TestFlight for testing.
This change decouples the hotfix-rc branch from the clients by creating one branch for each client. This solution maintains the same hotfix branching strategy for all clients in this repo while fixing the problem of the other clients holding up Desktop.
- **.github/workflows/*-browser.yml:** Replaced all instances of `hotfix-rc` with `hotfix-rc-browser`
- **.github/workflows/*-cli.yml:** Replaced all instances of `hotfix-rc` with `hotfix-rc-cli` …

[workflows] Decouple hotfix-rc branches

---

apps/browser/src/popup/scss/box.scss
apps/desktop/src/scss/box.scss

```
```
A slight layout/styling tweak for `.box-header-expandable` - one specific to desktop, and one for both desktop and browser:
Currently, on desktop, the "Settings" modal looks very awkwards and cramped - the content of the three panels ("Security", "Preferences", "App Settings") looks a bit too close to the expandable header button, making it feel quite untidy.
this PR adds a bit more bottom margin to the `.box-header-expandable` button when it's expanded (`[aria-expanded=true]`).
---
On both desktop and browser extension, clicking on a `.box-header-expandable` with the mouse/touch leads to the background colour changing and remaining "stuck" until focus is moved to another control. This looks a bit awkward.
Animated gif showing how the background gets "stuck" on the desktop …

[PS-1303] Desktop/browser: tweak `.box-header-expandable` styles

---

apps/cli/src/program.ts

```
```
The CLI command `bw sync` will run even if the vault is locked. You only need to be logged in. This makes it easier to use `bw sync` in automated scripts.
As far as I can tell, `bw sync` doesn't use the master password at any point, so there is no compelling reason to ask for it.
Potentially related or similar issues: #2739, bitwarden/cli#91, bitwarden/cli#423
- **program.ts:** Replace the unlock check.
I think that's it. It seems to me that sync.command.ts and sync.service.ts don't need changing.
(I noticed sync.service.ts calls cryptoService, but apparently not to decrypt anything.)
- As far as I can tell, the Bitwarden browser extensions (apps/browser/src/background/main.background.ts) and desktop app (apps/desktop/src/app/app.component.ts + …

[PS-1201] Allow bw sync without unlocking

---

apps/browser/config/development.json
apps/browser/src/background.ts
apps/browser/src/background/main.background.ts
apps/browser/src/background/service_factories/crypto-function-service.factory.ts
apps/browser/src/background/service_factories/encrypt-service.factory.ts
apps/browser/src/background/service_factories/environment-service.factory.ts
apps/browser/src/background/service_factories/factory-options.ts
apps/browser/src/background/service_factories/key-generation-service.factory.ts
apps/browser/src/background/service_factories/log-service.factory.ts
apps/browser/src/background/service_factories/state-migration-service.factory.ts
apps/browser/src/background/service_factories/state-service.factory.ts
apps/browser/src/background/service_factories/storage-service.factory.ts
apps/browser/src/flags.ts
apps/browser/src/listeners/onInstallListener.ts
apps/browser/src/services/browser-environment.service.ts
apps/browser/src/types/group-policy-environment.ts

```
```
Fix oninstall hook for manifest v3.
I'm also trying out a way of organizing Manifest V3 factories for command initialization. In effect, it's hiding the initialization specifics within a factory method and forcing only the minimum required parameters for all dependent services to be provided.
This is a reasonable pattern until services are decoupled to the point that we just want simple initializers.
Most of the changes are with creating factories. Other changes are:
- **background**: add onInstall listener
- **main.background**: use factories
- **onInstallListener**: Copied from runtime.background (It still exists there for mv2 usage).
```
```

[PS-1265] fix on install hook

---

.github/workflows/build-browser.yml
apps/browser/gulpfile.js
apps/browser/package.json

This requires a second build due to the differences being handled in webpack.
```
```
Adds MV3 artifact to build pipelines
```
```

Add Manifest v3 artifact to pipelines

---

apps/desktop/src/main.ts

```
```
This PR fixes a small URL error in the updater. Currently a user is redirected to the old repository (https://github.com/bitwarden/desktop/releases) when clicking on "Check for Updates..." in the "Help" menu, if a client without auto-updater is used.
- **apps/desktop/src/main.ts:** Adjustment of the gitHubProject parameter passed to the updater (so the user will be redirected to the correct URL https://github.com/bitwarden/clients/releases).
```
```

[PS-1347] Fix "Check for Updates..." URL (for clients without auto-updater)

---

README.md
apps/web/README.md

```
```
Some small remnants from our move to the mono-repo.
- **README.md:** Added missing build badges for cli and web on our root README.
- **apps/web/README.md:** Fixed the link to web builds badge.
```
```

Fix GitHub build badges

---

apps/web/src/app/organizations/billing/organization-billing-routing.module.ts
apps/web/src/app/organizations/layouts/organization-layout.component.ts
apps/web/src/app/organizations/navigation-permissions.ts
apps/web/src/app/organizations/organization-routing.module.ts
apps/web/src/app/organizations/reporting/organization-reporting-routing.module.ts
bitwarden_license/bit-web/src/app/organizations/organizations-routing.module.ts

```
```
#3252 refactored the organization routing permissions which were also modified as part of the org admin refresh. This PR properly brings those changes into `feature/org-admin-refresh` branch in order to account for the new tabs.
- **apps/web/src/app/organizations/billing/organization-billing-routing.module.ts:** Use the new `canAccessBillingTab` callback and remove redundant guards for child routes
- **apps/web/src/app/organizations/layouts/organization-layout.component.ts:** Use the new `canAccess<Tab>` callbacks
- **apps/web/src/app/organizations/navigation-permissions.ts:** Add new `canAccess<Tab>` callbacks for the new tabs added as part of the org admin refresh. And remove unused callbacks.
- **apps/web/src/app/organizations/reporting/organization-reporting-routing.module.ts:* …

[EC-451] Org Admin Refresh Permissions Refactor

---

apps/browser/src/background/main.background.ts
apps/browser/src/listeners/onCommandListener.ts
apps/browser/src/services/browserPlatformUtils.service.spec.ts
apps/browser/src/services/browserPlatformUtils.service.ts

```
```
With the introduction of a ThemingService with https://github.com/bitwarden/clients/pull/2943, the 
`browserPlatformUtilsService` no longer needs to depend on the `stateService`. This PR removes it as a dependency. 
- **apps/browser/src/services/browserPlatformUtils.service.ts:** Remove `stateService` (import & constructor)
- **Related changes to instantiation of BrowserPlatformUtilsService:**
- apps/browser/src/background/main.background.ts,
- apps/browser/src/listeners/onCommandListener.ts, 
- apps/browser/src/services/browserPlatformUtils.service.spec.ts
```
```

Remove stateService from browserPlatformUtilsService

---

apps/desktop/native-messaging-test-runner/src/bw-credential-create.ts
apps/desktop/native-messaging-test-runner/src/bw-credential-update.ts
apps/desktop/native-messaging-test-runner/src/nativeMessageService.ts
apps/desktop/src/app/services/services.module.ts
apps/desktop/src/services/nativeMessageHandler.service.ts

```
```
- Fix an issue found by QA where updating or creating a login isn't updating the desktop app or other clients until a refresh.
- Add check in credential update and create for userId
- **apps/desktop/native-messaging-test-runner/src/bw-credential-create.ts:** Get and send activeUserId with request
- **apps/desktop/native-messaging-test-runner/src/bw-credential-update.ts:** Refactor credentialUpdate params
- **apps/desktop/native-messaging-test-runner/src/nativeMessageService.ts:** Refactor and simplify params
- **apps/desktop/src/app/services/services.module.ts:** Follow other services naming convention and inject messaging service
- **apps/desktop/src/services/nativeMessageHandler.service.ts:** Add userId checks to create and update commands, and also use messaging service to …

[SG-626] Fix Desktop app not showing updated credentials from native messages

---

apps/browser/gulpfile.js

```
```
Resolves a warning in Firefox due to the storage manifest not being used in Firefox. It instead allows for arbitrary data.
Follow up to https://github.com/bitwarden/clients/pull/3120
- **apps/browser/gulpfile.js:** Delete the `storage` key from the Firefox manifest.
```
```

[SM-184] Remove manifest.storage in Firefox since it's not supported

---

package-lock.json
package.json

```
```
We have moved over to using `jest` as our testing framework. This PR only removes the no longer needed npm packages for `jasmine`
- **package.json && package-lock.json:** Ran `npm uninstall jasmine-spec-reporter` and `npm uninstall jasmine-core`
```
```

Remove jasmine related npm packages

---

libs/common/src/services/usernameGeneration.service.ts

```
```
The inputs to the various forwarding services was refactored to be a standard object in #3318.  However, only some of the services have a `website` property defined.  I moved this into the proper cases for services that require a website value.
- **usernameGeneration.service.ts:** `o.website` was not defined in all cases.  It is used in only some of the forwarding types.  Because the same Options object is used for all of them, it was resulting in an error when passed in to the fastmail generator.  This was refactored in #3318.
```
```

Changed where website parameter is passed in to forwarding services

---

libs/common/src/services/usernameGeneration.service.ts

```
```
This reverts commit 8dd15a1ff3d681baab9f691d48b3ac5966e28a0e.  I mistakenly changed to not pass in `o.website` for the Fastmail provider.  In my testing I didn't catch that the `website` parameter was being used in Fastmail.
- **userNameGeneration.service.ts:** Reverted the change to only pass in the `website` parameter for some providers.
```
```

Revert PR #3393 because it was not the right solution

---

libs/common/src/emailForwarders/fastmailForwarder.ts

```
```
https://bitwarden.atlassian.net/browse/SG-515
Fix issue where Fastmail forwarding errors were not being parsed in certain situations. 
- **fastmailForwarder.ts:** Add condition to catch errors under notCreated response property.
```
```

catch fastmail errors in notCreated response prop

---

bitwarden_license/bit-web/src/app/sm/secrets/secrets-list.component.html

```
```
The purpose of this PR is to fix displaying dates in the secrets list overview.
The dates were not being displayed as requested in the Figma examples.
This is dependent on the server side change in https://github.com/bitwarden/server/pull/2206
bitwarden_license/bit-web/src/app/sm/secrets/secrets-list.component.html
Sending the date to the angular date pipe for formatting and localization.
```
```

[SM-63] Display dates based off Figma

---

apps/web/config/development.json
apps/web/config/qa.json
apps/web/src/utils/flags.ts
bitwarden_license/bit-web/src/app/sm/sm-routing.module.ts
bitwarden_license/bit-web/src/app/sm/sm.guard.ts

```
```
Use the feature flag functionality in order to use EE.
- **apps/web/src/utils/flags.ts:** Adds a new secrets manager flag.
- **bitwarden_license/bit-web/src/app/sm/sm-routing.module.ts**: Use the `buildFlaggedRoute` functionality.
- **bitwarden_license/bit-web/src/app/sm/sm.guard.ts**: Temporarily disable, we should use this to verify the organization or something.
```
```

[SM-185] Use feature flags for secrets

---

apps/browser/src/background/nativeMessaging.background.ts

```
```
Introduced serialization of `EncStrings` directly to the encrypted string. Native Messaging exchange with Desktop expects a full serialization object, rather than a string it can init from. It would be nice to fix this by processing the encString properly in Desktop, but that wouldn't be backwards compatible with existing installs.
Bootstrap the old serialization method in in Native messaging.

SG-647 Handle special serialization case for native messaging.

---

.github/workflows/brew-bump-cli.yml
.github/workflows/brew-bump-desktop.yml
.github/workflows/build-browser.yml
.github/workflows/build-cli.yml
.github/workflows/build-desktop.yml
.github/workflows/build-web.yml
.github/workflows/crowdin-pull.yml
.github/workflows/release-cli.yml
.github/workflows/release-desktop-beta.yml
.github/workflows/release-desktop.yml
.github/workflows/release-qa-web.yml

```
```
The GitHub action Azure Key Vault is being deprecated and will no longer be maintained. The outcome of the related spike offers a solution to implement as a drop-in replacement using bash and the Az CLI. All references for the `Azure/get-keyvault-secrets` action will need to be replaced with this bash step in all our workflows.

Update deprecated Azure Key Vault action in workflows

---

apps/web/webpack.config.js

```
```
I got tired of errors while watching my dev console, so I added an icon server proxy to our dev web server. To use, just start up the icons server project locally, run web, and watch as your errors disappear 🪄 ☁️

Add icons to dev proxies

---

apps/browser/src/popup/services/services.module.ts
apps/desktop/src/app/services/init.service.ts
apps/desktop/src/app/services/services.module.ts
apps/web/src/app/core/core.module.ts
apps/web/src/app/core/init.service.ts
apps/web/src/app/core/state/state.service.ts
libs/angular/src/services/injection-tokens.ts
libs/angular/src/services/jslib-services.module.ts
libs/angular/src/services/theming/theming.service.ts

```
```
Short answer: move the `InjectionToken`s defined in `JslibServicesModule` to their own file.
Longer answer: I'm introducing some ES2020 syntax in #3043, which Node and Jest only have experimental support for. To avoid having to enable experimental ESM support in tests, we can just move some code around to avoid it being imported in test files.
This isn't as brittle as it sounds; the ES2020 code will be in `JslibServicesModule`, which is not needed for tests. At the moment it's only being imported to get access to the `InjectionToken`s that are defined in it, so if we move them into a separate file, we should be good.
- move `InjectionToken`s to their own file
- update import paths
- If this …

[EC-523] Move Injection Tokens to their own file

---

apps/web/src/app/accounts/register-form/register-form.component.html
libs/angular/src/components/register.component.ts

```
```
The objective of this PR is to get trial initiation working in an environment where captcha is enabled. Currently the flow stops if a captcha is not requested when registering, but is when logging in. This PR should enable captchas to fire whenever the heck they want and still be handled by the trial initiation component. 
See commits and descriptions. I did a bit of restructuring in this PR that won't make any sense on the full diff. The first handful of commits break up the `submit()` function on the `RegistrationComponent` into a couple of sizable chunks. I didn't modify any lines of logic in these. The final commit, [[fix] Check for captchas during login from trial initiation](https://github.com/bitwarden/clients/commit/47f621666353e3227a7fd0b957bba7a0982b5d4f), creates the …

[SG-656] Fix Trial Initiation Captcha Issue

---

apps/desktop/src/services/nativeMessageHandler.service.ts

```
```
Fix bw-generate-password command not checking for locked vault state
- **apps/desktop/src/services/nativeMessageHandler.service.ts:** Refactor account status checks into method and call in `bw-credential-create`, `bw-credential-update`, and `bw-generate-password`

[SG-652] Check for locked vault before generating password

---

libs/components/src/dialog/simple-dialog/simple-dialog.component.html
libs/components/tailwind.config.base.js

```
```
The simple dialogs didn't have a width set. This changes them to always use `w-96` and also adds a max-width of `90vw`.

[SM-224] Change the simple dialog width

---

apps/browser/src/popup/vault/view.component.html
apps/desktop/src/app/vault/view.component.html
apps/web/src/app/vault/add-edit.component.html
libs/angular/src/components/view.component.ts

```
```
Fixed bug where free users with classic organizations were not able to see TOTP codes.
Removed the `canAccessPremium`.
Added validations for organizations.
Browser:
Web:
Desktop:

[SG-659] Classic 2019 plans no longer generating TOTP codes for Free users

---

apps/cli/package.json
apps/cli/stores/chocolatey/bitwarden-cli.nuspec
apps/cli/stores/snap/snapcraft.yaml

```
```
While doing some updates in our Crowdin projects regarding the store descriptions, I noticed that the CLI's description wasn't set beside also still having links to the old repo.
- Update all links from `github.com/bitwarden/cli` to `github.com/bitwarden/clients`
- Updated an old logo (replaced it with the one we use on desktop (bitwarden.nuspec)
- Fixed the description for the stores ([chocolately](https://community.chocolatey.org/packages/bitwarden-cli) and [snapcraft](https://snapcraft.io/bw)) 
Adding Devops to also review this, as I would like to ensure this does not affect the upload to the stores on a release.
Relates to [RELEASE-325](https://bitwarden.atlassian.net/browse/RELEASE-325)
Commits have been split to show each individual change.
- Please add **unit tests** where …

[PS-1447] Fix issues with CLI stores (npm/choco/snapcraft)

---

apps/desktop/desktop_native/Cargo.toml
apps/desktop/desktop_native/src/biometric/windows.rs

```
```
Windows Hello prompt now appears within the context of the application. This means we need to ensure the application is in the foreground and focused for best result.
This also seems to resolve the issue with Windows Hello appearing below other windows if the application is minimized. Unfortunately we can't decide the location of that Window, but it's better than it appearing below other windows.
Resolves https://github.com/bitwarden/clients/issues/3504
- **apps/desktop/desktop_native/Cargo.toml:** Added two new Apis needed for `SetFocus` and `SetForegroundWindow`.
- **apps/desktop/desktop_native/src/biometric/windows.rs**: Added a new method `set_focus` which changes the foreground application + sets the focus.
- Please add **unit tests** where it makes sense to do so (encouraged …

[PS-1469] Ensure the window is focused when prompting for biometrics

---

apps/desktop/native-messaging-test-runner/src/bw-credential-create.ts
apps/desktop/native-messaging-test-runner/src/bw-credential-retrieval.ts
apps/desktop/native-messaging-test-runner/src/bw-credential-update.ts
apps/desktop/native-messaging-test-runner/src/bw-generate-password.ts
apps/desktop/native-messaging-test-runner/src/bw-handshake.ts
apps/desktop/native-messaging-test-runner/src/bw-status.ts
apps/desktop/native-messaging-test-runner/src/ipcService.ts
apps/desktop/native-messaging-test-runner/src/nativeMessageService.ts
apps/desktop/src/app/accounts/settings.component.ts
apps/desktop/src/app/services/services.module.ts
apps/desktop/src/locales/en/messages.json
apps/desktop/src/models/nativeMessaging/unencryptedMessageResponse.ts
apps/desktop/src/services/nativeMessageHandler.service.ts

```
```
Add a confirmation dialog when completing a handshake with the DuckDuckGoBrowser
- **apps/desktop/native-messaging-test-runner/src/bw-handshake.ts:** Add message to handle canceled response in test.
- **apps/desktop/native-messaging-test-runner/src/ipcService.ts:** Increase timeout for messages slightly to account for having to accept connection.
- **apps/desktop/native-messaging-test-runner/src/nativeMessageService.ts:** Fix status return
- **apps/desktop/src/app/accounts/settings.component.ts:** Set DDG Shared key to null if disabling setting
- **apps/desktop/src/app/services/services.module.ts:** Add i18n Service
- **apps/desktop/src/locales/en/messages.json:** Add new messages for dialog
- **apps/desktop/src/models/nativeMessaging/unencryptedMessageResponse.ts:** Fix status …

[SG-649] Add confirmation dialog and tweak shared key retrieval 

---

libs/components/src/button/button.directive.ts
libs/components/src/button/button.stories.ts
libs/components/src/submit-button/submit-button.component.html
libs/components/src/submit-button/submit-button.component.ts
libs/components/src/submit-button/submit-button.stories.ts

```
```
Adds support for using `<button bitButton block>` instead of `<button bitButton [block]=true">`. Also added block to submit-button.
> CL-54

[CL-54] Add support for button block without argument + submit button

---

libs/common/src/services/api.service.ts

```
```
Through the ongoing work to fix [SG-656](https://bitwarden.atlassian.net/jira/software/c/projects/SG/boards/71?modal=detail&selectedIssue=SG-656) we have created a backwards compatibility issue. 
On https://github.com/bitwarden/clients/pull/3531/files I changed the `postRegister()` api service method to expect a response body to come back from the server. A sibling PR modified the server to send a response.
The backwards compatibility issue comes up when a new client that expects a response from `register` calls an old server that doesn't send one. This throws a json parsing error and doesn't continue. This PR addresses this backwards compatibility issue.
* Add logic to the `apiSerice.send()` method that checks to see if an api response had a body in it before trying to parse it …

[SG-656\ Don't try and parse a json response if one is not received

---

apps/cli/src/send.program.ts

https://bitwarden.atlassian.net/browse/PS-1519 - Correct documentation so that it states:
_Examples:
bw send get searchText
bw send get id
bw send get searchText --text
bw send get searchText --file
bw send get searchText --file --output ../Photos/photo.jpg
bw send get searchText --file --raw_
send.programs.ts: command order corrected in internal documentation
If this change requires a documentation update - notify the documentation team
No documentation changes required - this changes the internal documentation to correctly reflect the documentation on the website.

[PS-1519] Correct bw send get -h internal CLI documentation

---

apps/web/src/locales/en/messages.json
apps/web/src/scss/base.scss
bitwarden_license/bit-web/src/app/sm/secrets/secrets-list.component.html
bitwarden_license/bit-web/src/app/sm/secrets/secrets-list.component.ts
bitwarden_license/bit-web/src/app/sm/secrets/secrets.component.html
bitwarden_license/bit-web/src/app/sm/secrets/secrets.component.ts

```
```
This PR is for creating a view for when no secrets are available. 
- apps/web/src/locales/en/messages.json
Adding new messages for empty secrets view
- bitwarden_license/bit-web/src/app/sm/secrets/secrets-list.component.html
Display empty secrets view if no secrets are passed in as input.
- bitwarden_license/bit-web/src/app/sm/secrets/secrets-list.component.ts
Add event emitters for when buttons are clicked for empty secret view.
- bitwarden_license/bit-web/src/app/sm/secrets/secrets.component.html
bitwarden_license/bit-web/src/app/sm/secrets/secrets.component.ts
Handle launching new secret dialog
- If this …

[SM-198] Empty Secrets View

---

.eslintrc.json
libs/common/spec/importers/bitwardenPasswordProtectedImporter.spec.ts
libs/common/spec/models/domain/cipher.spec.ts
libs/common/spec/models/domain/encString.spec.ts
libs/common/spec/models/domain/login.spec.ts
libs/common/spec/models/domain/send.spec.ts
libs/common/spec/models/domain/sendAccess.spec.ts
libs/common/spec/services/import.service.spec.ts
libs/common/spec/utils.ts
libs/common/spec/web/services/webCryptoFunction.service.spec.ts

```
```
* add an eslint rule to prohibit electron/node/angular code being imported into libs/common.
* bonus: fix the eslint Typescript parser, which was not configured properly
We could also apply similar rules to the other `libs/` directories, or even clients, but it didn't seem worth building up a large ruleset for. `libs/common` is usually the main offender.
**.eslintrc.json**
* add `eslint-plugin-import` to the plugins array so we can use it
* add the eslint Typescript parser settings, [per the docs](https://github.com/import-js/eslint-import-resolver-typescript#configuration), so that it can resolve import paths correctly (e.g. our `@bitwarden/*` mapping). As soon as I did this I got a bunch of linting errors (see below), so I think this was a bug in our existing config.
* add the …

[EC-570] eslint: Prevent angular/node/electron imports into libs/common

---

bitwarden_license/bit-web/src/app/sm/secrets/secrets.component.html

```
```
This PR is for removing one of the `(editSecretEvent)="openEditSecret($event)"`.
- bitwarden_license/bit-web/src/app/sm/secrets/secrets.component.html
Remove one occurrence of `(editSecretEvent)="openEditSecret($event)"`

SM Fix double edit secret dialog

---

apps/desktop/src/scss/left-nav.scss
apps/web/src/scss/vault-filters.scss

```
```
Fix how we display long organization/collection/folder names in the vault filter. They should be truncated, but instead, they are being centered and wrapped.
This will be picked to rc.
This regression was caused by #3407, which removed the `white-space: nowrap` option for buttons generally. We just need to add back that setting for filter buttons specifically.

[EC-569] Fix alignment for long filter names

---

bitwarden_license/bit-web/src/app/sm/secrets/secrets-list.component.html

```
```
This PR is for fixing the typescript errors occurring at secrets-list.component when first loading. 
The change will display a spinning loading icon while the secrets list is initialized.
- bitwarden_license/bit-web/src/app/sm/secrets/secrets-list.component.html
Check that secrets is initialized before displaying data. If not, display the spinning loading icon.
Loading Icon displayed

SM Fix typescript errors on secrets initialization 

---

libs/common/src/services/anonymousHub.service.ts

```
```
We hyphenate multi word routes as a rule, but the new AnonymousHub needed for passwordless broke this rule. This commit adjusts the route name used.
This depends on https://github.com/bitwarden/server/pull/2315/files
This commit will be cherry picked to rc.

Rename anonymousHub route to anonymous-hub

---

.eslintrc.json
apps/web/src/app/accounts/login/login.component.ts
apps/web/src/app/accounts/register-form/register-form.component.ts
apps/web/src/app/accounts/trial-initiation/billing.component.ts
libs/angular/src/components/login.component.ts
libs/angular/src/components/register.component.ts
libs/angular/src/components/settings/vault-timeout-input.component.ts

```
```
We should ensure the new typed syntax are used for forms since it offers better typing support. The old syntax will return a `never` type of unknown keys, i.e. `const t: never = formGroup.get("unknown").value`, while `formGroup.value.unknown` will fail compiling.
The expression tree is not perfect but it's as good as it can be without hardcoding any variable names or writing our own eslint-typescript plugin.
```
ChainExpression[expression.object.callee.property.name='get'][expression.property.name='value']
```
Ensures we have a method called `get` which is followed by an expression `.value`. …

[SM-265] Add eslint rule forbidding get().value

---

apps/web/src/app/vault/vault-filter/organization-filter/organization-filter.component.html

```
```
Fix:
> How to reproduce:
> Enable Single-org & disable personal vault. 
> Go to my vault and the 3-dot menu is missing. Users couldn't leave, enroll in master reset, etc.
This will be picked to rc.
The `organization-filter.component` has a switch statement, which shows different layouts depending on (among other things) whether the Single Org and/or Personal Vault policy applies. This particular case was missing the template code for the organization options menu. Copy + paste it across from elsewhere in the template.
This is being rewritten as part of #3440, so this is just a basic job to fix the regression for this release.
Before:
After: …

Add organization-options menu to single org

---

libs/components/src/stories/colors.stories.mdx
libs/components/src/tw-theme.css
libs/components/tailwind.config.base.js

```
```
Add a color option for code blocks.

[CL-42] Add code color

---

.eslintrc.json
apps/browser/src/services/localBackedSessionStorage.service.spec.ts
apps/browser/src/services/state.service.spec.ts
apps/desktop/src/app/vault/generator.component.spec.ts
apps/web/.eslintrc.json
apps/web/src/app/accounts/trial-initiation/trial-initiation.component.spec.ts
libs/common/spec/importers/bitwardenJsonImporter.spec.ts
libs/common/spec/importers/bitwardenPasswordProtectedImporter.spec.ts
libs/common/spec/misc/logInStrategies/apiLogIn.strategy.spec.ts
libs/common/spec/misc/logInStrategies/logIn.strategy.spec.ts
libs/common/spec/misc/logInStrategies/passwordLogIn.strategy.spec.ts
libs/common/spec/misc/logInStrategies/ssoLogIn.strategy.spec.ts
libs/common/spec/models/domain/cipher.spec.ts
libs/common/spec/models/domain/encString.spec.ts
libs/common/spec/models/domain/login.spec.ts
libs/common/spec/models/domain/send.spec.ts
libs/common/spec/models/domain/sendAccess.spec.ts
libs/common/spec/services/cipher.service.spec.ts
libs/common/spec/services/export.service.spec.ts
libs/common/spec/services/folder.service.spec.ts
libs/common/spec/services/import.service.spec.ts
libs/common/spec/services/settings.service.spec.ts
libs/common/spec/services/stateMigration.service.spec.ts
libs/common/spec/utils.ts
libs/common/spec/web/services/webCryptoFunction.service.spec.ts

```
```
We've made the decision to replace substitute with jest mock extend. To assist in this this PR adds an eslit rule which forbids the imports of `@fluffy-spoon/substitute`. Existing imports are ignored.

Forbid substitute

---

apps/browser/src/popup/vault/current-tab.component.html
apps/browser/src/popup/vault/current-tab.component.ts

```
```
Fixes #2371 
The goal is to reduce the likelihood of typed letters getting skipped when searching from the Current Tab page on the browser extension.
Effectively, the only change should be increasing the debounce time of the search from 200ms to 500ms. 
The custom debounce implementation that used `window.setTimeout` has been replaced by an observables-based debounce implementation.
Also, the following autofocus implementation has been replaced with the `appAutofocus` directive. This is not related to the issue described in PS-1335; the intention was just to improve standardization. 
```
window.setTimeout(() => {
document.getElementById("search").focus();
}, 100);
```
This code changes in this PR do not completely eliminate the problem, but the frequency that it occurs should be …

[PS-1335] problem with dropped letters keypresses when searching vault from browser extension debounce

---

apps/web/src/app/send/send.component.html

```
```
The send filters got truncated due to their use of the `bitButton` component. Since the filters are not really buttons I've simply removed the component.
Resolves #3789 

[PS-1676] Resolve Send Filters being truncated

---

.github/ISSUE_TEMPLATE/browser.yml
.github/ISSUE_TEMPLATE/cli.yml
.github/ISSUE_TEMPLATE/desktop.yml
.github/ISSUE_TEMPLATE/web.yml

Updates our issues templates to inform that we track work outside of Github and to not expect Github tracking data.

Inform that we track issues outside of Github

---

apps/browser/src/popup/components/cipher-row.component.html
apps/browser/src/popup/scss/box.scss
apps/desktop/src/app/vault/ciphers.component.html
apps/desktop/src/scss/list.scss

```
```
Instead of using the `truncate` pipe we should truncate using CSS. This allows us to ensure the items take up the maximum amount of space instead of a fixed number of characters.
The CSS is slightly annoying but I didn't want to spend more time on this, it will all go away once we migrate to Tailwind either way.
Resolves #3788 
Browser:
Desktop:

[PS-1674] Correct truncation of ciphers in browser

---

.github/workflows/automatic-issue-responses.yml

```
```
We regulary receive pull requests that update our translation files directly, instead of using Crowdin. This PR adds a job to close these PRs when the `translation-pr` label is added.
> We really appreciate you taking the time to improve our translations.
> 
>  However we use a translation tool called [Crowdin](https://crowdin.com/) to help manage our localization efforts across many 
> different languages. Our translations can only be updated using Crowdin, so we'll have to close this PR, but would really appreciate if you'd consider joining our awesome translation community over at Crowdin.
> 
> More information can be found in the [localization section](https://contributing.bitwarden.com/contributing/#localization-l10n) of our [Contribution …

[PS-1640] BEEEP: Add job to close translation PRs

---

apps/web/src/scss/styles.scss
apps/web/webpack.config.js
libs/components/src/index.ts
libs/components/src/multi-select/index.ts

```
```
- Include the MultiSelect module in the Component Library's barrel file 
- Import the MultiSelect ngSelect theme (`components/src/multi-select/scss/bw.theme.scss`) into the Web `styles.scss` 
- Add the necessary sha256 hash to webpack config CSP policy to support ngSelect inline styles

Fix MultiSelect component styles and CSP error

---

apps/browser/src/content/autofill.js

```
```
Honor the sandbox attribute of CSP and iframes.
Note: `self.origin` is 'null' if inside a frame with sandboxed csp or iframe tag

[PS-1735] Do not autofill if sandboxed

---

apps/web/src/app/accounts/login/login.component.html
libs/angular/src/components/login.component.ts

```
```
The `Log in with device` button should be hidden if the environment is self-hosted
- **libs/angular/src/components/login.component.ts:** Added extra condition to the `showLoginWithDevice` variable to check if the environment is self-hosted or not.

[SG-768] Hide Login with Device button on Self-Hosted

---

apps/browser/src/popup/accounts/hint.component.html
apps/browser/src/popup/accounts/hint.component.ts
apps/browser/src/popup/accounts/login.component.html
apps/browser/src/popup/accounts/login.component.ts

```
```
Fix issue where launching Master Password Hint would clear email.
Since the browser extension doesn't have traditional routes and the components are destroyed on navigation, I used navigation state data to achieve this.
- **apps/browser/src/popup/accounts/login.component.html:** Use state data to send email to hint component
- **apps/browser/src/popup/accounts/hint.component.ts:** Set email if present in route state data 
- **apps/browser/src/popup/accounts/hint.component.html:** Use state data to send email back to login component
- **apps/browser/src/popup/accounts/login.component.ts:** Set email if present in route state data (is sent from hint component)
https://user-images.githubusercontent.com/8926729/197574162-984c0bb4-1ca6-4d27-9277-0f15badb59e3.mov
- Please add **unit …

[SG-753] Keep email after hint component is launched in browser

---

apps/browser/src/popup/accounts/home.component.ts
apps/browser/src/popup/accounts/login.component.html
apps/browser/src/popup/accounts/login.component.ts

```
```
Fix email and rememberEmail form values not getting set properly on navigation
- **apps/browser/src/popup/accounts/home.component.ts:** Add route params for the email and rememberEmail form values.
- **apps/browser/src/popup/accounts/login.component.ts:** Send email and rememberEmail form values to home component on navigation
https://user-images.githubusercontent.com/8926729/197846821-8e4142ed-36a7-454f-a4a6-968e0df13eb5.mov

[SG-754] & [SG-764] Fix email and rememberEmail form values

---

apps/browser/src/popup/accounts/login.component.html
apps/browser/src/popup/scss/base.scss

```
```
The `product` team recommended minor changes to the UI for the browser extension; The close button and avatar are not needed because of the two-step login flow.
https://user-images.githubusercontent.com/13024008/198112337-5f82aaf8-2e40-4674-ba71-a94449f86d7d.mov

[SG-769] Removed avatar and close button from the password screen

---

apps/web/src/app/organizations/vault/vault.component.ts

```
```
Currently we reload all ciphers when a vault filter changes. This is fine if the ciphers are in local sync data, but for admins, this means they're fetching & decrypting ciphers from the server every time.
This will be solved by EC-14, but I wanted to get a fix in in the meantime. #3532 will allow the user to switch filters rapidly, potentially queuing up a lot of decryption.
@jlf0dev and @coroiu Requesting your review specifically as you're probably the most across this area of the code currently.
- **apps/web/src/app/organizations/vault/vault.component.ts** - previously this called `CiphersComponent.reload`, which called `CiphersComponent.load` (which has the api call in it), which then called `CiphersComponent.ApplyFilter`. This basically just calls `ApplyFilter` directly to …

[EC-626] Don't refresh org vault on filter change

---

apps/web/src/app/settings/verify-email.component.ts
apps/web/src/app/vault/vault.component.html
apps/web/src/app/vault/vault.component.ts

```
```
Fix for #2800 where clicking the "Send Email" button in the warning box pops up an error telling the user that the email is already verified.
- **apps/web/src/app/settings/verify-email.component.ts**
Added some logic to check if an email is already verified or not when a user clicks on the "Send Email" button.
Added an EventEmitter to the verify-email component so that it can let its parent know that the email's already verified and that it can close the warning box.
Added code to pop-up a Toast briefly letting the user know that their email is verified.
- **apps/web/src/app/vault/vault.component.html**
Added the EventEmitter to the template to call a new function `updateVerifyEmail`.
- **apps/web/src/app/vault/vault.component.ts**
Added new function `updateVerifyEmail` to update …

[SM-260] Fix #2800 - Handle already verified email when resending verification email

---

apps/web/src/app/settings/verify-email.component.ts
apps/web/src/app/vault/vault.component.html
apps/web/src/app/vault/vault.component.ts

```
```
Hides the email verification prompt if attempting to verify an already verified email.
Resolves: https://github.com/bitwarden/clients/issues/2800

[SM-260] Hide email verification prompt if already verified

---

apps/browser/src/popup/accounts/hint.component.ts
apps/browser/src/popup/accounts/login.component.html
apps/browser/src/popup/accounts/login.component.ts
apps/browser/src/popup/accounts/two-factor.component.ts
apps/browser/src/popup/services/services.module.ts
apps/desktop/src/app/accounts/hint.component.ts
apps/desktop/src/app/accounts/login.component.html
apps/desktop/src/app/accounts/login.component.ts
apps/desktop/src/app/accounts/two-factor.component.ts
apps/desktop/src/app/services/services.module.ts
apps/web/src/app/accounts/hint.component.ts
apps/web/src/app/accounts/login/login.component.html
apps/web/src/app/accounts/login/login.component.ts
apps/web/src/app/accounts/two-factor.component.ts
apps/web/src/app/core/core.module.ts
libs/angular/src/components/hint.component.ts
libs/angular/src/components/login.component.ts
libs/angular/src/components/two-factor.component.ts
libs/angular/src/services/jslib-services.module.ts
libs/common/src/abstractions/login.service.ts
libs/common/src/services/login.service.ts

```
```
Add a new LoginService to persist login form values during navigation to other components to and from the login component.
- **libs/services:** Add LoginService and LoginServiceAbstraction
- **Login Component** Inject LoginService into this component, save the values on navigation, and clear on successful login
- **Hint Component** Inject LoginService to get to refill the email
- **Two Factor Component** Inject LoginService to get to clear the values on successful login
Desktop:
https://user-images.githubusercontent.com/8926729/198373537-b2059210-50e7-4094-b2e8-7cc7b5464780.mov
Web:
https://user-images.githubusercontent.com/8926729/198374018-8b4674be-3a89-4cb0-8efd-c04e60be708b.mov
- If this …

[SG-782] Add login service to streamline login form data persistence

---

bitwarden_license/bit-web/src/app/secrets-manager/layout/no-items.component.html
bitwarden_license/bit-web/src/app/secrets-manager/layout/no-items.component.ts

```
```
After the merge to master the css class `no-items-image` was replaced by the icon directive. Updating secrets manager to use the new way.

Use new icon for no item

---

libs/common/src/services/api.service.ts

https://bitwarden.atlassian.net/browse/SG-785
```
```
When identity returns a 400 error code on token refresh, users are logged out. This is bad if the 400 was for some reason other than the token being invalid. This change limits that condition by parsing the JSON response and only logging our when the response when error = "invalid_grant".
- **api.service.ts:** Only log out on 400s when error json string is invalid_grant.

400s only log out on invalid  grant error

---

apps/web/src/app/organizations/billing/organization-billing-tab.component.html
apps/web/src/app/organizations/billing/organization-billing-tab.component.ts

```
```
Update the Billing tab so that the Payment Method and Billing History pages are no longer visible for self hosted instances.
- **organization-billing-tab.component.html:** Add flag for rendering the Payment Method and Billing History tabs that depends on the `platformUtilsService.isSelfHost()` method.

[EC 657] Defect payment method and billing history pages not hidden

---

.github/workflows/build-desktop.yml
apps/browser/src/popup/accounts/login.component.html
libs/angular/src/components/login.component.ts

```
```
Due to the introduction of the two-step login flow, the clients need to have a `focus` on the master password field.
- **apps/browser/src/popup/accounts/login.component.html** Added the `appAutoFocus` directive to the login template on the browser.
- **apps/desktop/src/app/accounts/login.component.ts:** On the `continue` button, click the `focusInput` method is called to focus on the `masterPassword` field.
- **libs/angular/src/components/login.component.ts:** Removed the `focusInput` method on the base `loginComponent`.
https://user-images.githubusercontent.com/13024008/199129315-2b8381ab-900b-4e88-9e43-81ef24a26fa1.mov
https://user-images.githubusercontent.com/13024008/199298107-5af285cc-3488-499c-a04e-2487b6ca97b1.mov …

[SG-792] Added focus to master password field on browser and desktop

---

apps/browser/src/popup/accounts/home.component.html
apps/browser/src/popup/scss/environment.scss

```
```
Fix the Bitwarden logo getting cut off on the Safari browser extension
- **apps/browser/src/popup/accounts/home.component.html:** Add `login-page` 
- **apps/browser/src/popup/scss/environment.scss:** Add `login-page` specific rules for `browser_safari`
Before:
After:

[SG-797] Fix Safari extension logo height

---

apps/browser/src/popup/accounts/login.component.html
apps/desktop/src/app/accounts/login.component.html

```
```
Use correct provider icons for login page in Browser and Desktop
- **apps/browser/src/popup/accounts/login.component.html:** `bwi-bank` -> `bwi-provider`
- **apps/desktop/src/app/accounts/login.component.html:** `bwi-bank` -> `bwi-provider`

[SG-798] & [SG-799] Use correct provider icon instead of bank icon

---

apps/web/src/app/core/event.service.ts

```
```
Fix the following bug:
> When I try to view event logs for an Organization, I get a red error toast: “this.policies is undefined”. This prevents events from loading.
**This affects rc and the fix will need to be cherry-picked.**
EventService.policies was `undefined` because the service was using ngOnInit to subscribe to the policies observable. However, ngOnInit is for components, not services. We should use the constructor instead and leave the subscription running for the lifetime of the service.

[EC-659] Fix undefined property error in event logs

---

apps/desktop/src/app/accounts/settings.component.ts

```
```
If a user has not set their language, the language value in the dropdown on the Preferences page in the desktop app is blank. The fix in this PR will display "Default" in that case instead of blank. 
- Added nullish coalescing. If the user has not yet set a language, the getLocale function returns `undefined`, but in order to display correctly in the dropdown the locale value must be `null`. 

[PS-1763] - handle undefined locale value in desktop app

---

apps/web/src/locales/en/messages.json

```
```
fix typo in event log text
- locales/en/**messages.json:** updated "Account password saved" to "Changed account password"

[EC-662] - fixed typo in event log

---

apps/web/src/locales/en/messages.json

```
```
While reviewing #3969 I noticed that part of our used language deviates.
Mainly the use of personal vault instead of individual.
And 2 small capitalization changes according to #3577
Those got introduced with #3925
- **apps/web/src/locales/en/messages.json:** Updates to 4 messages

Org admin refresh translation nitpicks

---

apps/web/src/connectors/duo.html
apps/web/src/connectors/duo.ts

```
```
Prevent iframe src loads invoked by Duo Web SDK `init` from executing hostnames outside of Duo trusted domains.
- **duo.html:** Add CSP limited to duo hostnames.
- **duo.ts:** Only pass hostname value of the parsed `host` parameter.

add csp and only pass hostname to duo init

---

apps/web/src/app/accounts/login/login.component.html
apps/web/src/app/accounts/login/login.component.ts

```
```
Fix master password hint not being clickable because of form errors
- **apps/web/src/app/accounts/login/login.component.html:** Move the hint button out of form field and adjust spacing
- **apps/web/src/app/accounts/login/login.component.ts:** Add method for manual navigation
https://user-images.githubusercontent.com/8926729/199808923-4136f12d-6a54-4382-9e1d-23b81185228b.mov

[SG-757] Move hint button out of the form field

---

libs/common/src/abstractions/organization/organization.service.abstraction.ts

```
```
**This fix will need to be cherry picked to `rc`**
The Organization tab was not being displayed for custom users with manage groups, users, or assigned collections permissions. When the Manage tab was re-added for OAVR V1, the `canAccessOrgAdmin` helper was not updated to check for the Manage tab, and this PR corrects that.
- **organization.service.abstraction.ts:** Check if the user can access the manageTab when determining if they can access the org admin console.

[PS-1804] Display Organization tab for users with custom permissions

---

apps/web/src/app/organizations/guards/org-redirect.guard.ts
apps/web/src/app/organizations/layouts/organization-layout.component.html
apps/web/src/app/organizations/layouts/organization-layout.component.ts
apps/web/src/app/organizations/organization-routing.module.ts
apps/web/src/app/organizations/reporting/organization-reporting-routing.module.ts
apps/web/src/app/organizations/reporting/reporting.component.ts
apps/web/src/app/organizations/settings/organization-settings-routing.module.ts
apps/web/src/app/organizations/settings/settings.component.html
libs/common/src/abstractions/organization/organization.service.abstraction.ts
libs/components/src/tabs/tab-nav-bar/tab-link.component.html
libs/components/src/tabs/tab-nav-bar/tab-link.component.ts

```
```
**This fix will need to be cherry picked to `rc`**
The active tab in the org vault was not showing as selected when a child route active. 
**Problem**
This was caused by giving each tab a specific route based off which routes were available as children. Ex. "manage" became "manage/members". The tab didn't recognize that other child routes, such as "manage/collections" were also under the current route, and deselected the tab.
**Solution**
In order to fix this, we had to stop setting the tab route dynamically and give it the correct route ("manage"), we then added options to make the tab active if it was a subset of the current route.
**Problem**
This caused a secondary problem where the route guard tried to redirect us to the first child component ("manage/members"), and if we …

[EC-678] [EC-673] Fix active tab not showing selected while in child route

---

apps/web/src/app/accounts/sso.component.html
apps/web/src/locales/en/messages.json

```
```
**This should be picked to `rc` to avoid creating unnecessary confusion during the November release.**
In OAVR V1 the “Organization identifier” field was renamed to "SSO identifier" and moved to the SSO page. But the user facing “SSO identifier” was not renamed on the Login page. This could create confusion since the fields correspond to the same data but have different names. 
- Replace 'Organization Identifier' with 'SSO identifier'
- Sentence case 'SSO identifier' in `messages.json`
- Add 'SSO' to SSO login page helper text in `messages.json` …

[EC-672] Update SSO login page language

---

apps/browser/src/safari/desktop.xcodeproj/project.pbxproj
apps/browser/webpack.config.js
libs/common/src/services/cryptography/multithread-encrypt.service.implementation.ts

```
```
Fix the vault not loading on the Safari browser extension.
**This will need to be cherry-picked into rc**
This was caused by the web workers changes. `libs/common/services/cryptography/encrypt.worker.ts` was being split by webpack into 2 files (named 447.js and 800.js), which were not included in the Xcode project (`desktop.xcodeproj`) used to bundle the app extension. As a result, Safari couldn't find them when the dynamic imports were evaluated at runtime.
To fix this I have:
* added `encrypt.worker.ts` as an explicit entrypoint in `webpack.config.js`, and also annotated the import statement with a [magic comment](https://webpack.js.org/api/module-methods/#magic-comments). The effect of this is that it the web worker code is bundled exactly once into a file called …

[EC-661] Add web worker code bundles to Safari browser extension

---

apps/web/src/app/settings/payment.component.ts

```
```
The component uses a special webpack loader to load scss variables and programmatically apply them to stripe. The loader is not supported by storybook which breaks all components that depend on SharedModule or LooseComponentsModule
Remove references to scss code
Inspiration from Figma

[EC-645] fix web payment component breaking storybook compilation

---

.github/workflows/automatic-issue-responses.yml
.github/workflows/automatic-pull-request-responses.yml

```
```
I previously added a workflow (#3730) to close **Community**-PRs that contains translations. Once labelled with `translation-pr` it was expected that those PRs got closed with a nice response to the contributor.
Today we received our first [PR](https://github.com/bitwarden/clients/pull/3991) where I added the label, but the job did not trigger. I figured out that the trigger was only operating on issues and not on pull-requests. [Documentation here](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request)
Instead of just adding the trigger, I decided to extract this into a separate workflow.
- **.github/workflows/automatic-issue-responses.yml:** Extended workflow name to differentiate between issues and pull request activated workflows.
- …

Extract and fix trigger for PR auto responses (Translation-PRs)

---

apps/web/src/app/tools/import-export/import.component.html
apps/web/src/app/tools/import-export/import.component.ts

```
```
The import button was not correctly displaying the loading animation. These changes revert the observable usage as that was possibly being blocked by the import.
- **apps/web/src/app/tools/import-export/import.component.html:** Updated variable name reference and removed async
- **apps/web/src/app/tools/import-export/import.component.ts:** Reverted observable usage

[EC-650] Revert observable usage from ImportComponent

---

apps/web/src/app/organizations/manage/people.component.html

```
```
Changing the text from "People" to "Members" caused the page heading to stack and remove spacing between elements. A solution was to update the page to use Tailwind classes to style the Members page header so that it supports wrapping the controls to a new line should they exceed the width of the container.
> Note: The rest of this page will be updated in OAVR V2.
- **people.component.html:** Use tailwind classes to style the page header
- Replace `page-header d-flex` with Tailwind classes for border, margin, and flex
- Have the `<h1>Members</h1>` tag grow to fill container width with right padding to ensure it never gets squished against the toggle controls.
- Wrap the controls in their own flex container with spacing and top margin
- Add fixed width to the search control as it …

[EC-670] Update Members tab to support flex wrap

---

apps/web/src/app/core/event.service.ts
apps/web/src/locales/en/messages.json
libs/angular/src/components/view.component.ts

```
```
The Event “Viewed Card Number for item item-identifier” is not being displayed on the Events logs list.
This pull request has related changes on [this server pull request](https://github.com/bitwarden/server/pull/2381).
- **apps/web/src/app/core/event.service.ts:** Added missing enum to display text for card view event
- **apps/web/src/locales/en/messages.json:** Added message for “Viewed Card Number for item item-identifier”
- **libs/angular/src/components/view.component.ts:** Fixed clients to capture correct event type 'Cipher_ClientToggledCardNumberVisible' …

[EC-675] Display the Event for “Viewed Card Number for item item-identifier”

---

apps/browser/src/popup/scss/misc.scss
apps/browser/src/popup/vault/vault-filter.component.html

This could be done a number of ways. I think this might be the least problematic, but could also be done by just changing "position: absolute" to "relative on the ".no-items" class - misc.css:138 I'm unable to load the spinner to test this method since the style rules are linked.
```
```
.no-items element in the empty vault was overlapping the select box above it rendering it unclickable on the right side. Adding a z-index to the select box container fixed the issue.
classed the container with z10 and added appropriate styles to misc.css:138 of:
.z10 {
position: relative;
z-index: 10;
}
- If this change requires a **documentation update** - notify …

[PS-1840] - fix for covered dropdown on empty vault

---

apps/cli/src/program.ts

This warning was kept vague during fix rollout, but now that we're more than a release past, we can expand the explanation.
```
```
cli-v2022.9.0 updated defaults to the `serve` command which closed a CSRF vulnerability in the command. An option was included to allow for backwards compatibility in non-standard deployments, but the explanation was left relatively terse in hopes to give people a chance to update without too many hints on how to exploit.
This PR expands the warning message to explain why it is probably a bad idea to disable origin protection. …

Expand serve origin protection warning

---

apps/desktop/src/app/vault/share.component.html
apps/desktop/src/app/vault/share.component.ts

```
```
Resolves the share modal not closing correctly. This issue occurs because we previously relied on the `data-dismiss="modal"` which only works if the elements exists when the modal is opened. Since we use an `async` pipe the dismiss element appears later which causes the click handle to not exist.
Resolved by adding an explicit click handle on the component itself. In the future this will resolve itself once we migrate to the new dialog service.

[SM-340] Fix share modal not closing on cancel

---

libs/common/spec/services/policy.service.spec.ts
libs/common/src/services/policy/policy.service.ts

```
```
The `PolicyService` method `policyAppliesToUser` was throwing an error on Desktop and Browser clients due to the parameter `policyFilter` being passed null.
- **libs/common/src/services/policy/policy.service.ts:** Added a null check to determine if the passed function should be executed

[EC-739 / EC-740] Add null check to policyFilter on PolicyService

---

libs/common/src/services/policy/policy.service.ts

```
```
In the Policies refactor to use observables a bug was introduced which caused serviced that used the state service directly to not used refreshed values.
- **libs/common/src/services/policy/policy.service.ts:** Revert back to clearing the decrypted policies on the state service.

[EC-744 / EC-745] Revert PolicyService back to clearing DecryptedPolicies on StateService

---

apps/desktop/src/app/vault/add-edit.component.ts

```
```
The Desktop AddEditComponent was not calling BaseAddEditComponent.ngOnInit which checks if the user has any policy that disables 'Personal Ownership'.
- **apps/desktop/src/app/vault/add-edit.component.ts:** Call BaseAddEditComponent.ngOnInit

[EC-746] Call BaseAddEditComponent.ngOnInit on Desktop AddEditComponent

---

apps/web/src/app/organizations/vault/add-edit.component.ts

```
```
To allow owners, admins, and providers to edit ciphers within collections and organizations that they should have permission to edit. 
Edit @djsmith85: This will be 🍒 ⛏️ to `rc`
In the case that a user has permission to edit any collection in a given organization, set the cipher's `edit` value to true so they are able to edit that cipher.

[PS-1798] - ensure admin users can edit ciphers

---

apps/browser/src/popup/send/send-add-edit.component.ts

> Browser extension was incorrectly overriding `ngOnInit` method and not allowing the superclass to run its code to properly setup the policy observables while adding/editing a send.
- **send-add-edit.component.ts**: Replace call to load with `super.ngOnInit()` to properly init observables

[EC-743] Call super to ngOnInit to include policy observable changes

---

.github/workflows/release-cli.yml
.github/workflows/release-desktop.yml
.github/workflows/release-qa-web.yml
.github/workflows/release-web.yml

```
```
We were creating Github deployments (and notifying Jira) when Dry Run jobs were triggered.  This change will not create or update deployment statuses when the workflow is a Dry Run.
- **release_cli.yml:** Added additional condition to deployment steps
- **release_desktop.yml:** Added additional condition to deployment steps
- **release_desktop.yml:** Added additional condition to deployment steps
- **release_qa_web.yml:** Remove extra step no longer necessary, as we're setting the `initial_status`

Updated workflows to not create Github deployment on Dry Run

---

apps/web/src/app/vault/vault-filter/organization-filter/organization-filter.component.html

```
```
Fix the following bug:
> I was going to test manually enrolling in Admin Password Reset and realized my user could not see the 3 dot menu.
Enterprise Org with the following policies enabled:
> 
> master password reset
> 
> single organization
> 
> remove individual vault
> 
> steps to reproduce:
> 
> as a user in an Organization configured like above > log into web vault
> 
> on the vault screen, observe there is no menu beside the org name
> 
> expected:
> 
> 3 dot menu that lets you leave the Org, link SSO if configured, enroll in admin password reset if configured
> 
> disabling the remove individual vault policy seems to bring the menu back however?
Re-apply commit 7c3255d (#3678) which was accidentally reverted by the Org Admin Refresh changes in commit 09c3bc8 (#3925).
- …

[EC-735] Add organization-options menu to single org (again)

---

apps/web/src/app/settings/payment-method.component.html

```
```
> When adding credit to an org using PayPal, the credit does not get applied to the org. Instead, the credit gets applied to Account Settings of the user’s account.
Add the `[organizationId]` to the `app-add-credit` and `app-adjust-payment` components in the payment method component. It was forgotten when the payment-method.component was re-used for both individual accounts and organizations as part of the OAVR.
- **apps/web/src/app/settings/payment-method.component.html:** Add the `[organizationId]`

[EC-750] Specify organizationId for credit and adjust payment components

---

apps/browser/src/services/browser-environment.service.ts

```
```
Handles the errors caused by the managed environments in Safari. Note, does not solve the bug in EC 661 since the behaiour still occurs.
- **apps/browser/src/services/browser-environment.service.ts:** Added a null check for when managed environments are not available, i.e. returning null. Also resolved an error that could appear in `settingsHaveChanged` by exiting early if there are no managed environments.

[SM-330] Disable managed environments for safari

---

bitwarden_license/bit-web/src/app/secrets-manager/projects/projects-list.component.html
bitwarden_license/bit-web/src/app/secrets-manager/secrets/secrets-list.component.html
bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/service-accounts-list.component.html

```
```
Inputs should be associated with descriptive labels for better screen reader support.
- **`/app/secrets-manager/secrets/secrets-list.component.html`:** Associated existing label
- **`/app/secrets-manager/projects/projects-list.component.html`:** Added new label
- **`/app/secrets-manager/service-accounts/service-accounts-list.component.html`:** Associated existing label
Updated list header for Projects, Secrets, & Service Accounts:

[SM-301] fix: associate labels with inputs

---

apps/desktop/src/main/menu/menu.help.ts

```
- [ x ] Other
```
Add Mastodon to the Help -> Follow Us menu in the desktop app
- **apps/desktop/src/main/menu/menu.help.ts:** Added section for Mastodon
- Please add **unit tests** where it makes sense to do so (encouraged but not required) - N/A
- If this change requires a **documentation update** - notify the documentation team - N/A
- If this change has particular **deployment requirements** - notify the DevOps team - N/A

[PS-1856] Added Mastodon to follow us menu

---

apps/browser/webpack.config.js

```
```
Service workers are unable to finish startup and therefore they won't work at all. This is because of the code webpack was generating after #3043 but this fixes that by targeting web worker for background in MV3 which is something that should probably happen regardless. 
* Removed unneeded plugin from shared main config
* Added plugin back behind MV2 check
* Added background entry behind MV2 check
* Added totally new config for MV3 behind check
* Target `webworker` for MV3 background
* Export array of configs

[PS-1829] Fix Service Worker Startup in MV3

---

libs/components/src/link/link.directive.ts
libs/components/src/link/link.module.ts
libs/components/src/link/link.stories.ts

```
```
`bitLink` using the `button` dom element do not line up properly with surrounding text.
Buttons are automatically set to `inline-block` (and cannot be changed to `inline`) causing height calculations to happen differently. Setting an explicit line height to match surrounding text fixes this.

[CL-59] [Bug] Link buttons have different height depending on html tag used

---

apps/desktop/src/services/nativeMessageHandler.service.ts

```
```
Reduce intermittent communication issues with native messages.
- **apps/desktop/src/services/nativeMessageHandler.service.ts:**  Remove extra call to toJSON() on SymmetricCryptoKey. There is no need to serialize it to get the `keyB64` property.

[SG-832] Remove extra serialization call on SymmetricCryptoKey in native messaging service

---

apps/web/config/cloud.json

Changed the feature flag for Passwordless to enable it on `cloud.json`, which is used in Production Cloud.
```
```
Enable the feature flag so that we will start showing the "Login with Device" button in Production.
- **cloud.json:** Enabled Passwordless

Enabled passwordless in Production

---

apps/browser/src/decorators/session-sync-observable/session-sync.decorator.spec.ts
apps/browser/src/decorators/session-sync-observable/session-sync.decorator.ts

```
```
Session-sync uses class names and property names to generate unique keys to sync values. However, minification was selecting different class names for different instances of services, which was causing them not to sync properly.
This was happening _only_ in production mode for some reason, perhaps due to minifying post chunking?
At any rate, I've removed constructor names and tacked on an index to the sync. A reminder that these decorators are run at definition-time and so the index is locked in only once per class declaration.

Do not use object constructors for names

---

apps/web/src/app/components/organization-switcher.component.ts
apps/web/src/app/layouts/navbar.component.ts
libs/angular/src/components/share.component.ts
libs/angular/src/vault/vault-filter/services/vault-filter.service.ts
libs/common/src/abstractions/organization/organization.service.abstraction.ts

```
```
Make each component own their own organization filtering and apply the provider filter on components that used to have this filter built into them from `OrganizationService.getAll()`.
- **libs/common/src/abstractions/organization/organization.service.abstraction.ts:** Add a helper for filtering out provider organizations.
- Utilize the filter in various places that it is needed based on who used to call `getAll` from before #3462 

[PS-1942] Add Provider Filters

---

apps/browser/src/popup/generator/generator.component.html
apps/desktop/src/app/vault/generator.component.html
apps/web/src/app/tools/generator.component.html

Fix what I assume is a typo `name="DuckDudkGoApiKey"` > `name="DuckDuckGoApiKey"`
```
```
Noticed while fixing a merge conflict on https://github.com/bitwarden/clients/pull/3405 ... I assume this `name` is wrong?
- **apps/browser/src/popup/generator/generator.component.html**, **apps/desktop/src/app/vault/generator.component.html**, **apps/web/src/app/tools/generator.component.html**:  fix typo `name="DuckDudkGoApiKey"` > `name="DuckDuckGoApiKey"`

[PS-1962] Fix typo for DuckDuckGo form field

---

bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/access/dialogs/access-token-create-dialog.component.ts
bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/access/dialogs/access-token-dialog.component.html
bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/access/dialogs/access-token-dialog.component.ts

```
```
The purpose of this PR is to: 
- Fix the access token display dialog for never expiring tokens.
- Add a maximum input of 80 characters to the name form field in the create access token dialog
- bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/access/dialogs/access-token-create-dialog.component.ts
bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/access/dialogs/access-token-dialog.component.html
bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/access/dialogs/access-token-dialog.component.ts
Support never expiring tokens 
- bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/access/dialogs/access-token-create-dialog.component.ts
Input validator
- Please add **unit tests** where it makes sense to do so (encouraged …

[SM-360] Fix access token display dialog for never expiring tokens

---

apps/desktop/src/app/send/send.component.ts
apps/desktop/src/locales/en/messages.json

```
```
Fixes https://github.com/bitwarden/clients/issues/4096
Adds a menu item to remove a previously set password from a Send.
- **apps/desktop/src/app/send/send.component.ts:** Add menu item to "Remove password"
- **apps/desktop/src/locales/en/messages.json:** Add entries to messages.json for menu item, message box and toast notifcation
BEFORE:
AFTER:

[PS-1901] Add menu item to remove a previously set password from a Send

---

apps/browser/README.md
apps/cli/README.md
apps/desktop/README.md

```
```
Fixing our links in the specific client README's to our setup guides in our contribution docs.

Fix links in README to our contrib guidelines

---

apps/browser/src/decorators/session-sync-observable/session-syncer.spec.ts
apps/browser/src/decorators/session-sync-observable/session-syncer.ts
apps/browser/src/services/browser-state.service.ts
libs/common/src/services/memoryStorage.service.ts
libs/common/src/services/state.service.ts

```
```
Fix account disk cache sync between background and visualizers. One known bug caused by this was strange behavior when setting a pin in browser for the first time, then reloading the popup. This fixes the issue by syncing the account disk cache used by background and serializers.

[ps-2003] Ps/ps 1854 fix pin

---

apps/web/src/app/organizations/organization.module.ts
apps/web/src/app/organizations/shared/components/search-input/search-input.component.html
apps/web/src/app/organizations/shared/components/search-input/search-input.component.ts
apps/web/src/app/organizations/shared/components/search-input/search-input.stories.ts
apps/web/src/app/organizations/shared/index.ts
apps/web/src/app/organizations/shared/shared-organization.module.ts

```
```
During OAVR work, we found a case for creating a common “search” component for the org admin console screens. This adds the new search component to a new `SharedOrganizationModule` to be used by the `OrganizationModule`.
The new `SharedOrganizationModule` will allow us to easily add new shared components that are only used by the Organization admin console screens without polluting the component library.
- **organizations/shared/shared-organization.module.ts:** Add the new `SharedOrganizationModule`
- **organizations/organization.module.ts:** Use the new shared module
- **organizations/shared/components/search-input/search-input.component.ts:** The new search input component  …

[EC-623] Reusable Search Input Component

---

libs/components/src/form-field/form-field-control.ts

```
```
The new search input component uses input [`type="search"`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/search) which was not an allowed type for the `bitInput` directive and caused the web build to fail.
- **libs/components/src/form-field/form-field-control.ts** Add "search" as a valid type to the `InputTypes` enum

Add 'search' as a valid InputType

---

apps/web/src/app/accounts/trial-initiation/trial-initiation.component.html
apps/web/src/app/accounts/trial-initiation/trial-initiation.component.ts
apps/web/src/app/settings/organization-plans.component.ts

```
```
Add a validator to check that the organization name does not exceed 51 characters
- **apps/web/src/app/accounts/trial-initiation/trial-initiation.component.html:** Disable 'next' button on org name step if there are any validation errors
- **apps/web/src/app/accounts/trial-initiation/trial-initiation.component.ts** Add maxLength validator to org name field and subscribe to org name field changes so error can be displayed while the user is typing.
- **apps/web/src/app/settings/organization-plans.component.ts:** Add maxLength validator to the normal organization creation flow as well.
https://user-images.githubusercontent.com/8926729/203579714-38ebd6ef-9d8c-47b2-a69e-cd4813babcf7.mov
- If this …

[SG-664] Add org name length validation to inputs

---

apps/desktop/electron-builder.json
package-lock.json
package.json

```
```
Update `electron` to `21.3.1`
Update `electron-store` to `8.1.0`
Update `electron-notarize` to `1.2.2` -> Last version, package got renamed to `@electron/notarize`
Update `electron-rebuild` to `3.2.9` -> Last version, package got renamed to `@electron/rebuild`
Update `electron-updater` to `5.3.0`
There hasn't been any serious breaking changes in electron for these versions:
https://www.electronjs.org/docs/latest/breaking-changes#planned-breaking-api-changes-200
Keeping `electron-builder` at `22.11.10` (still need to figure out how to fix the signing issues)
- **package.json:** Updating the versions as stated above
- **package-lock.json:** Changes after executing `npm i` after each change
- **apps/desktop/electron-builder.json:** Set `electronVersion` to `21.3.1` so the workflow …

[PS-1892] Bump electron

---

libs/components/src/checkbox/checkbox.component.ts
libs/components/tailwind.config.base.js

```
```
Inline styles added by angular are not added to CSP header and so do not work in browsers. This PR uses an alternative method of styling the checkbox.
- **libs/components/src/checkbox/checkbox.component.ts** Remove styles from angular decorators and bind them to the host element directly.
- **libs/components/tailwind.config.base.js** Add basic support for mask-image to tailwind
There should be no graphical changes.

[EC-838] fix: CSP issues with inline styles

---

apps/browser/src/popup/accounts/login.component.ts
apps/browser/src/popup/services/services.module.ts
apps/desktop/src/app/services/services.module.ts
apps/web/src/app/accounts/login/login-with-device.component.ts
apps/web/src/app/accounts/login/login.component.html
apps/web/src/app/core/core.module.ts
libs/angular/src/components/login.component.ts
libs/angular/src/services/jslib-services.module.ts
libs/common/src/abstractions/login.service.ts
libs/common/src/services/login.service.ts

```
```
Fix rememberEmail functionality for Logging in with SSO.
I decided to do some light refactoring here and added a method to LoginService to handle this functionality that started to be duplicated in multiple places.
- **LoginService:** Add `saveEmailSettings()` method to set the `rememberedEmail` value in state service.
- **Login Components:** Replace old ways of doing this manually with method from login service

[SG-884] Fix Remember Email functionality for Login with SSO

---

libs/components/src/menu/menu-trigger-for.directive.ts

```
```
`bit-menu` should always be visible on screen.
- `libs/components/src/menu/menu-trigger-for.directive.ts`: change overlay's `withPush` to true

[SM-326] fix: keep bit-menu on screen

---

bitwarden_license/bit-web/src/app/secrets-manager/layout/org-switcher.component.ts
libs/components/src/navigation/nav-group.component.ts

```
```
The `org-switcher` component should close when an organization is clicked. 
- `bitwarden_license/bit-web/src/app/secrets-manager/layout/org-switcher.component.ts`: Emit `openChange` when the `toggle` method is fired
- `libs/components/src/navigation/nav-group.component.ts`: Same change as `org-switcher`

[SM-384] fix: close org-switcher on click

---

bitwarden_license/bit-web/src/app/secrets-manager/layout/org-switcher.component.ts

```
```
The `org-switcher` should sort organizations alphanumerically.
- `bitwarden_license/bit-web/src/app/secrets-manager/layout/org-switcher.component.ts`: Added Array.sort to organizations state

[SM-387] fix org-switcher sorting

---

apps/web/src/app/accounts/trial-initiation/trial-initiation.component.spec.ts
apps/web/src/app/accounts/trial-initiation/trial-initiation.component.ts

```
```
Fix routing to organization members when completing the Trial Initiation flow. This route was probably updated with the Admin refresh work.
- **apps/web/src/app/accounts/trial-initiation/trial-initiation.component.ts:** Route to updated org members route
- **apps/web/src/app/accounts/trial-initiation/trial-initiation.component.spec.ts** Adjust unit tests

[SG-890] Fix routing to org members in trial confirmation

---

bitwarden_license/bit-web/src/app/secrets-manager/projects/projects-list/projects-list.component.html
bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/service-accounts-list.component.html
bitwarden_license/bit-web/src/app/secrets-manager/shared/secrets-list.component.html

```
```
This PR prevents tables in SM from having long horizontal scroll due to text overflow. Long text will now wrap.
- `bitwarden_license/bit-web/src/app/secrets-manager/projects/projects-list`: Add `wordbreak: all` to `<td>`
- `bitwarden_license/bit-web/src/app/secrets-manager/shared/secrets-list`: ^
- `bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/service-accounts-list`: ^ 

[SM-308] fix: add word break to table cells in SM

---

apps/web/src/app/tools/import-export/import.component.html
libs/common/spec/importers/passky-json-importer.spec.ts
libs/common/spec/importers/test-data/passky-json/passky-encrypted.json.ts
libs/common/spec/importers/test-data/passky-json/passky-unencrypted.json.ts
libs/common/src/enums/importOptions.ts
libs/common/src/importers/passky/passky-json-importer.ts
libs/common/src/importers/passky/passky-json-types.ts
libs/common/src/services/import.service.ts

```
```
Adds an importer for [Passky](https://passky.org/)
The export is a simple json format than can either be encrypted or unencrypted.
```
{
encrypted: false,
passwords: [
{
website: "https://bitwarden.com/",
username: "testUser",
password: "testPassword",
message: "my notes",
},
],
}
```
This passky-json-importer does not support importing encrypted backups from Passky (Displays error message: `Unable to import an encrypted passky backup.`)
- **libs/common/src/importers/passky/passky-json-types.ts:** Create type-definitions for the passky-json export
- **libs/common/spec/importers/testData/passky/_._:** Added testdata for an encrypted and unencrypted Passky export
- **libs/common/spec/importers/passky-json-importer.spec.ts:** Wrote unit-tests
- …

[PS-2066] BEEEP: Add importer for Passky

---

libs/components/src/link/link.directive.ts

```
```
On web the bit links get a ring around them for some reason. This fixes the issue
Before fix (on a feature branch)

fix: ring around bitLink in web vault

---

.github/workflows/staged-rollout-desktop.yml

```
```
This PR removes the `setup` job requirement from the `Staged Rollout Desktop` workflow.  This change is due to not being able to run the workflow today with the `rc` branch already deleted.
- **.github/workflows/staged-rollout-desktop.yml:** Removed the `setup` job.

Remove setup job from Staged Rollout Desktop workflow

---

bitwarden_license/bit-web/src/app/secrets-manager/layout/navigation.component.html
bitwarden_license/bit-web/src/app/secrets-manager/layout/navigation.component.ts
bitwarden_license/bit-web/src/app/secrets-manager/layout/org-switcher.component.ts

```
```
The `org-switcher` should only show organizations with access to Secrets Manager.
- `clients/bitwarden_license/bit-web/src/app/secrets-manager/layout/org-switcher.component.ts`: Added a generic `filter` function Input
- `clients/bitwarden_license/bit-web/src/app/secrets-manager/layout/layout.component.html`: Updated the SM navigation to pass the `org-switcher` a filter that only shows orgs with access to SM

[SM-385] filter orgs in SM org-switcher

---

apps/web/src/app/organizations/components/access-selector/access-selector.stories.ts
libs/components/src/multi-select/multi-select.component.html

```
```
Fix multiselect dropdown gets hidden inside dialog.
Has been tested inside `feature/org-admin-refresh`
Bug:
With fix:
On feature branch
There's a related bug making the dropdown look a little weird [CL-75 Bug Multi-select dropdown has weird bottom border](https://bitwarden.atlassian.net/browse/CL-75)
[CL-75]: https://bitwarden.atlassian.net/browse/CL-75?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[EC-823] Multiselect dropdown gets hidden inside dialog

---

apps/web/src/app/organizations/members/components/member-dialog/member-dialog.component.ts

```
```
Fix the `ngOnInit` that was broken during member dialog group tab changes.
Updated the component `ngOnInit` logic to only use the `userDetails` if it is available and in editMode.

Update ngOnInit to properly handle inviting new members

---

apps/web/src/app/organizations/manage/groups.component.html

```
```
Fixes the two client event listeners from both firing if a user clicks on the button directly. Allows the user to either click the button (support for ARIA) and also optionally click the table cell.
Add `$event.stopPropagation()` to the button click event so it doesn't propagate up the DOM tree.

[EC-824] Fix Group table opening two dialogs

---

apps/web/src/app/layouts/product-switcher/product-switcher.component.ts

```
```
This PR prevents [Angular error NG0100 ](https://angular.io/errors/NG0100) in the `product-switcher`
- `apps/web/src/app/layouts/product-switcher/product-switcher.component.ts`: Manually run change detection in `ngAfterViewInit`

[SM-403] fix: NG0100 in Product Switcher

---

apps/web/src/app/vault/vault-filter/services/vault-filter.service.ts

```
```
The vault filter service would not always properly nest collections depending on the order the collections were created. This PR forces the collections to first be sorted alphabetically before building the node tree to ensure proper nesting.

Fix nested collections

---

apps/web/src/app/organizations/members/components/member-dialog/member-dialog.component.ts
apps/web/src/app/organizations/shared/components/access-selector/access-selector.component.ts

```
```
If a member belongs to a group that has collection access, and you attempt to remove access to an individual collection (that doesn’t belong necessarily to the group) from the member, then the modal ends up sending all collection details to the endpoint with malformed guids. This causes the server to through an exception and fail silently (with console error logs).
The problem only occurs when the member has access to multiple collections via groups (they show up as disabled controls) and a single collection with direct access (an enabled control). 
When a user removes the access to the single collection, the form array of access items then only contains disabled controls (via the groups). For some reason, when Angular detects that a form array only contains disabled controls [it …

[EC-862] Member dialog collections tab fails to save when trying to remove collection access

---

libs/common/spec/misc/logInStrategies/logIn.strategy.spec.ts
libs/common/spec/misc/logInStrategies/passwordLogIn.strategy.spec.ts
libs/common/spec/misc/logInStrategies/ssoLogIn.strategy.spec.ts
libs/common/spec/misc/logInStrategies/user-api-login.strategy.spec.ts
libs/common/src/misc/logInStrategies/logIn.strategy.ts
libs/common/src/misc/logInStrategies/passwordLogin.strategy.ts
libs/common/src/misc/logInStrategies/passwordlessLogin.strategy.ts
libs/common/src/misc/logInStrategies/ssoLogin.strategy.ts
libs/common/src/misc/logInStrategies/user-api-login.strategy.ts

```
```
Fix this bug:
> User is trying to confirm an account created in 2018 to their organization but receive no visible errors, just inactivity after clicking confirm.
> The dev tools show a 404 error
**Analysis:**
The 404 is occurring because the first step of the key exchange is to fetch the user’s public key, which doesn’t exist.
I was able to reproduce this locally by creating a new user and then nulling out the User.PrivateKey and User.PublicKey fields in the db.
We have migration logic in `logIn.strategy.ts` for old users who don't have RSA keys (specifically `createKeyPairForOldAccount`), but it fails because the user’s master key isn’t set yet. This means that we can't decrypt the `EncKey` which we need to encrypt the new private key once it's generated.
* …

[EC-836] Trying to confirm 2018 user account to organization returns 404

---

apps/browser/src/content/autofill.js

```
```
It is possible to store null URIs for cipher items, if this occurs, the autofill script throws when trying to index the protocol of the uri. Fix is to null check URIs here.

Handle null value URLs in autofiller script

---

apps/web/src/app/organizations/shared/components/access-selector/access-selector.component.ts

```
```
The [prior fix](https://github.com/bitwarden/clients/pull/4313) for EC-862 cleared the from array control when it was disabled which broke the access selector afterwards. It was unnecessary, only an empty `[]` needs to be emitted by the control in that instance to avoid saving bad values.
- **access-selector.component.ts:** Add comments explaining the fix for EC-862 and remove the line that clears the form array control.

[EC-862] Avoid clearing disabled form array in access selector

---

apps/web/src/app/organizations/manage/groups.component.html
apps/web/src/app/organizations/members/people.component.html
libs/components/src/badge-list/badge-list.component.ts

```
```
When showing the `+n more` badge in the badge list, it didn't make sense to show `+1 more` when the actual value could be displayed instead. This updates the badge list logic to only show the `+n more` badge when there are 2 or more items than the maximum.

[EC-883] Fix badge list "+n more" message

---

apps/web/src/app/organizations/manage/groups.component.html

```
```
Update the Collections column in the Groups table to show "All" when a group has "access to all current and future collections" enabled.

[EC-882] Show "All" in Group collections column

---

apps/browser/src/safari/desktop/Info.plist
apps/browser/src/safari/safari/Info.plist
apps/cli/stores/chocolatey/bitwarden-cli.nuspec
apps/desktop/electron-builder.json
apps/desktop/stores/chocolatey/bitwarden.nuspec
apps/web/src/404.html

```
```
It's almost 2023 and time again to bump our copyright to be up-to-date for the next client releases.
Searched for 2022 and copyright and updated the year.

[PS-2125] Update year in copyrights

---

bitwarden_license/bit-web/src/app/organizations/manage/sso.component.ts

```
```
Remove SHA-1 encryption from SSO Outbound and Minimum Signing Algorithm lists as it is not supported.
- **bitwarden_license/bit-web/src/app/organizations/manage/sso.component.ts:** Removed the sha-1 entry from the algorithm list

[EC-277] Remove SHA-1 encryption from SSO Outbound and Minimum Signing Algorithm lists

---

apps/web/src/scss/tables.scss

```
```
Updating the vault-items-component in Web to use the new `bit-table` CL component broke some of the styles for the `app-vault-icon` component. This PR adds a new CSS rule targeting the `app-vault-icon` when used within a `bit-table` component until `app-vault-icon` is updated/replaced and uses Tailwind.

[EC-870] Cipher icon normalization

---

libs/components/src/dialog/dialog.service.ts

```
```
This PR updates the component library's dialog service to close all open dialogs when the vault locks. 
- `libs/components/src/dialog/dialog.service.ts`: When this service is constructed, it will listen for auth status changes and if the vault is locked will call `this.closeAll()`
The alternative would be to just close dialogs on any route change, but this was decided against. 

[EC-879] fix: close dialogs on vault lock

---

apps/web/src/app/organizations/vault/vault.component.html
apps/web/src/app/organizations/vault/vault.component.ts

```
```
The collection names were missing from the breadcrumbs due to `ng-template` being used instead of `ng-container`. 
Additionally, remove the breadcrumb array `slice(1)` to always include showing the current collection in the vault header.

[EC-877] Fix missing collection breadcrumbs

---

apps/web/src/app/organizations/core/services/group/group.service.ts
apps/web/src/app/organizations/manage/groups.component.ts

```
```
The success toast for bulk group deletion was trying to use a server response that was never added (it was ultimately unnecessary) so update the service to not expect a result and success toast to use the requested group count instead. 
- **apps/web/src/app/organizations/core/services/group/group.service.ts:** Remove response type and cleanup
- **apps/web/src/app/organizations/manage/groups.component.ts:** Use the request group count instead and remove the result

[EC-896] Fix bulk group deletion message count

---

apps/web/src/app/organizations/vault/group-badge/group-name-badge.component.html
apps/web/src/app/organizations/vault/group-badge/group-name-badge.component.ts

```
```
The vault items component was using its own implementation of a badge list and it would sometimes fail to give enough spacing between badges. This updates the vault items component to use the CL badge list component so that it shares the same styles and appearance.
- Remove the existing maxItems implementation
- Add an array of groupNames that is updated whenever the `@Input()`s change (group Ids or list of all groups)
- Sort the groupNames by name

[EC-871] Fix collection group labels

---

apps/web/src/app/organizations/shared/components/access-selector/access-selector.component.html

```
```
The permission dropdown arrow was not properly activating the dropdown after we changed it to a bit icon. This PR changes the container to a `<label for="">` tag to provide click/hover support.

[EC-878] Fix access selector permission dropdown arrow

---

apps/browser/src/background/main.background.ts
apps/browser/src/listeners/update-badge.ts

```
```
Fixes #4260
The badge was not showing or updating it's state (logout/lock/match) across browser windows and also not always in private/incognito mode
I've tried to split up the commits and provide detailed explainations for the changes in the commit messages.
I also provided links to the old implementation prior to the update-badge work to show the regressions.
- **apps/browser/src/listeners/update-badge.ts:** Show and update badge on all windows (Chrome MV2/MV3 (both with and without incognito mode), Firefox: MV2 (with and without private mode)
- **apps/browser/src/background/main.background.ts:** Small fix for Firefox private mode
- If this change requires a **documentation update** - notify …

[PS-2072] Browser Badge fixes

---

apps/web/src/app/vault/vault-items.component.html

```
```
Item names weren't using the `bitLink` directive, causing them to use the default font style.
I also noticed that `a` tags couldn't be navigated into with the keyboard. Even though the item link uses the URL to navigate to the edit modal, I decided to change it to a `button` since it doesn't navigate away from the current location.

[EC-906] add bitLink to item names

---

apps/browser/src/popup/vault/add-edit-custom-fields.component.html
apps/desktop/src/app/vault/add-edit-custom-fields.component.html
apps/web/src/app/vault/add-edit-custom-fields.component.html
libs/angular/src/directives/true-false-value.directive.ts

```
```
Reverts the custom field  changes introduced by #3601.
Contrary to intention we actually do expect these to be strings. I've updated the types to correspond to the expected behavior.
Note: This will be cherry picked to `rc`.

[SM-410] Fix boolean custom fields not working

---

apps/web/src/app/vault/vault-items.component.html
libs/components/src/badge/badge.directive.ts
libs/components/src/table/table.component.html

```
```
Whenever an item was added with a long name, our vault table would expand to accommodate instead of wrapping the text. This caused issues when we had notification boxes on the side.
This PR should prevent this behavior.
- **table.component.html:** Set the style `word-break: break-word`. We can't use the tailwind version of this because they use `overflow-wrap: break-word` which doesn't seem to work on tables.
- **vault-items.component.html:** Allow the badge column in the table to shrink instead of splitting it 50/50 with the name column
- **badge.directive.ts:** Adding the `word-break: break-word` on the table would also apply this to the badges. We need to prevent badges from wrapping anyway, so i've set them to be `inline-block` in the directive.
Before:
After:
- Please add …

[EC 911] Prevent Table from overflowing

---

apps/browser/src/decorators/session-sync-observable/session-syncer.spec.ts
apps/browser/src/decorators/session-sync-observable/session-syncer.ts

Reverts bitwarden/clients#4245
We're seeing stalled logout issues due to this commit. We need to rethink these debounces, probably add some time information to ensure ignoring out-of-date items rather than debounce.
Alternatively, we can look to reducing debounce time in the next release and see if that improves things. This doesn't seem super likely since the logout delay observed is ~10 seconds while debounce time is just 0.5 sec. It appears that the logout actions are being eaten, not delayed by debounce.

PS-2171 Revert "Ps/sync only when changed"

---

apps/web/src/app/vault/vault-items.component.html

```
```
Vault row contents were not properly following the alignment rules specified in Figma. Row contents are now middle aligned and item names are now `text-align: start` to avoid centering text when wrapping item names onto multiple lines.  
Row content remains middle aligned vertically
Row content remains middle aligned vertically and text aligned at the start of the column

[EC-905] Vault row alignment

---

apps/web/src/app/organizations/shared/components/access-selector/access-selector.component.html

```
```
Second attempt at fixing misaligned selects.
Added explicit height to regular `select` that matches `ng-select` `min-height`. I honestly tried to fix this properly and I have a refactored `ng-select` theme that doesn't use `min-height` on my computer. But the issue is that the regular `select` element height is calculated differently depending on browsers. We need to look into [CL-78 [Improvement] Completely restyled selects](https://bitwarden.atlassian.net/browse/CL-78) before we attempt removing the `height` rules.

[EC-828] Fix misaligned selects

---

libs/components/src/breadcrumbs/breadcrumb.component.html
libs/components/src/breadcrumbs/breadcrumb.component.ts
libs/components/src/breadcrumbs/breadcrumbs.component.html
libs/components/src/breadcrumbs/breadcrumbs.component.ts
libs/components/src/breadcrumbs/breadcrumbs.module.ts
libs/components/src/breadcrumbs/breadcrumbs.stories.ts
libs/components/src/breadcrumbs/index.ts
libs/components/src/index.ts

Original implementation from ef20ee1882648fd36c8b775106652dd16c5fb55e (https://github.com/bitwarden/clients/pull/3762)
```
```
Code has already been tested. This PR makes the component available to master so that SM can use it without having to wait for `feature/org-admin-refresh`

[EC-937] Pre-merge breadcrumbs into master so SM can use it

---

libs/components/src/radio-button/radio-button.component.html
libs/components/src/radio-button/radio-button.component.ts
libs/components/src/radio-button/radio-button.stories.ts

```
```
The `RadioButtonComponent` in the Component Library does not allow disabling a single radio button input, only the whole group via the `FormControl`. This PR adds this ability via the `disabled` input on `RadioButtonComponent`. Note that there is no way to do this in the `FormControl` API.
- **libs/components/src/radio-button/radio-button.component.ts** - add `disabled` input and rename existing getter to `groupDisabled` to distinguish it
- **libs/components/src/radio-button/radio-button.component.html** - pass these inputs down to the radio button input
- **libs/components/src/radio-button/radio-button.stories.ts** - update the story so we can test this …

[EC-934] Allow disabling a single radio button input

---

.github/workflows/test.yml
.gitignore
jest.config.js
package-lock.json
package.json

```
```
Utilizes a popular Action to process .NET test results and upload them as a report artifact. Much easier to parse results than working through the commandline output.
- **.github/workflows/test.yml:** Additional step for report processing
- **jest.config.js:** Configuration of new reporter
- **package.json:** New package to provide JUnit report results

Upload and process test results as an artifact and report

---

libs/components/src/dialog/animations.ts
libs/components/src/dialog/dialog/dialog.component.html
libs/components/src/dialog/dialog/dialog.component.ts
libs/components/src/dialog/simple-dialog/simple-dialog.component.html
libs/components/src/dialog/simple-dialog/simple-dialog.component.ts

```
```
This PR adds a fade-in effect to `bit-dialog` that mimics Bootstrap modals:
https://github.com/twbs/bootstrap/blob/main/dist/css/bootstrap.css#L3190
https://github.com/twbs/bootstrap/blob/main/dist/css/bootstrap.css#L5312
This PR does **not**  add a _fade-out_ effect. Adding a fade-out effect will require a more significant overhaul of the dialog components to support closing after an `animationend` callback. I don't believe this is easily doable with `@angular/cdk/dialog` and we would need to build something from `@angular/cdk/overlay` instead.
- `libs/components/src/dialog/animations.ts`: `@fadeIn` animation for use in `bit-dialog` and `bit-simple-dialog`
<video src="https://user-images.githubusercontent.com/17113462/209240392-3cda05d4-12ec-43f0-9e6a-2115ffc60cf4.mov">https://use …

[SM-303] feat: add fadeIn animation to bit-dialog

---

apps/web/src/app/organizations/tools/exposed-passwords-report.component.ts
apps/web/src/app/organizations/tools/inactive-two-factor-report.component.ts
apps/web/src/app/organizations/tools/unsecured-websites-report.component.ts
apps/web/src/app/organizations/tools/weak-passwords-report.component.ts
apps/web/src/app/reports/pages/cipher-report.component.ts
apps/web/src/app/reports/pages/exposed-passwords-report.component.ts
apps/web/src/app/reports/pages/inactive-two-factor-report.component.ts
apps/web/src/app/reports/pages/reused-passwords-report.component.ts
apps/web/src/app/reports/pages/unsecured-websites-report.component.ts
apps/web/src/app/reports/pages/weak-passwords-report.component.ts

```
```
The cipher-report.component has a dependency on stateService which it doesn’t use. As this is a base-component for a lot of the reports, the dependency on stateService is dragged into the other constructors.
This aims to remove the unneeded dependency on stateService
- **apps/web/src/app/reports/pages/cipher-report.component.ts:** Remove unneeded dependency on `stateService` which in turn can be removed from:
- **apps/web/src/app/reports/pages/reused-passwords-report.component.ts**
-
- **apps/web/src/app/reports/pages/exposed-passwords-report.component.ts:** 
- **apps/web/src/app/organizations/tools/exposed-passwords-report.component.ts:** 
-
- **apps/web/src/app/organizations/tools/inactive-two-factor-report.component.ts:**
- …

[TDL-216] Reports remove unneeded dependency on stateService

---

apps/desktop/src/main/menu/menu.help.ts

```
```
During the review of the 2022.12 desktop release by Apple it got rejected as it had references to a third-party platform
Apple's review:
> We noticed that your submission includes information about third-party platforms that may not be relevant for App Store users.
> Specifically, your app includes Android references in the Get Mobile app.
>Referencing thrid-party platforms in your app or its metadata is generally not relevant for App Store iusers, who are focused on the experiences offered by their current device.
- **apps/desktop/src/main/menu/menu.help.ts:** Hide the menu-item linking to the PlayStore to download our Android Mobile App from the MacAppStore Desktop version. …

[PS-2238] Hide get android submenu on MacStore release

---

apps/web/src/app/vault/add-edit.component.html

```
```
Users without permission to views passwords were mistakenly show the button to view the password character count. This hides the button if the `viewPassword` flag is false.

[EC-891] Hide password character count button for hidden passwords

---

apps/web/src/app/organizations/core/services/collection-admin.service.ts
apps/web/src/app/organizations/core/views/collection-admin.view.ts
apps/web/src/app/organizations/vault/vault-items.component.ts
apps/web/src/app/vault/vault-filter/services/vault-filter.service.ts
apps/web/src/app/vault/vault-items.component.html
apps/web/src/app/vault/vault-items.component.ts
apps/web/src/locales/en/messages.json
libs/common/src/models/response/collection.response.ts

```
```
It was discovered that Manager users would still see collections in the vault that the did not have access to. This is the intended behavior, as Managers have permission to create Collections by default. However, even though Managers can view all collections, they do not always have permission to edit all collections, so this PR removes the edit/delete controls when they do not have the appropriate permissions. It also introduces a new warning message indicating they do not have sufficient privileges to view all the items in a collection they do not have access to. 
There is a required server change for this PR: https://github.com/bitwarden/server/pull/2542
- **apps/web/src/app/organizations/vault/vault-items.component:** Add logic to the component to hide controls for collections …

[EC-887] Fix Managers can see options to edit/delete Collections they aren't assigned to

---

apps/web/src/app/organizations/members/people.component.html
apps/web/src/app/organizations/shared/components/access-selector/access-selector.component.html
apps/web/src/app/organizations/vault/vault-items.component.ts
apps/web/src/app/vault/vault-items.component.html
apps/web/src/locales/en/messages.json

```
```
Our new "You do not have permission to view all items in this collection." placeholder in the Vault table was showing even if a user was an Admin or above. We don't need to show this for Admins or Owners because they have access to everything by default.
There are also various UI fixes included in this PR:
- Make table item text size consistent across Vault and Members pages
- Decrease Role column text size and make muted
- Make Policies column text muted
- Right align options button in Vault table
- Right align delete button in access selector
- Sentence case access selector placeholder text
**Vault after:**
**Members after:**
**Access Selector after:** …

OAVR Misc Changes

---

apps/web/src/app/organizations/vault/vault.component.html
apps/web/src/app/vault/vault-items.component.html

```
```
We were still using the bootstrap dropdown in the Admin Console, this PR uses our new `bit-menu` component instead.
We also had the old boostrap `btn` class applied to our "New" dropdown in the Admin Console. Removing this fixes the weird border showing when selected.
I have also applied more click handlers to the rows in the vault table. You can now tap anywhere to select the row, and interactable elements won't propagate that click down.

[EC-969] "New" button border color

---

libs/common/spec/importers/keeper-csv-importer.spec.ts
libs/common/spec/importers/test-data/keeper-csv/testdata.csv.ts
libs/common/src/importers/keeper/keeper-csv-importer.ts

```
```
Keeper CSV importer imports TOTP values to the correct field. (See https://github.com/bitwarden/clients/blob/master/libs/common/src/importers/keeper/keeper-json-importer.ts#L29 for reference).
Keeper exports TOTP fields with the label `TFC:Keeper`, rather than insert it as a normal key/value field it sets `cipher.login.totp`.

[PS-2263] Keeper CSV import: import TOTP to correct field

---

libs/angular/src/components/icon.component.html

```
```
Vault item icons were misaligned and different colors. The fallback image for logins was text-muted, but the icon itself was using the regular text color. 
This PR removes `bwi-fw` to align the icons with images, and makes all icons muted text color.
**Before**
**After**

Align icons with images and make all muted color

---

libs/common/spec/services/export.service.spec.ts
libs/common/src/enums/kdfType.ts

https://bitwarden.atlassian.net/browse/PS-2273
```
```
[Latest OWASP recommendations](https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html#pbkdf2) suggest at least 310k iterations for PBKDF2 now. This PR adjusts our default to 350k.
- **kdfType.ts:** Increase iterations default.

adjust default kdf iterations to 350k

---

apps/browser/src/background.ts
apps/browser/src/browser/cipher-context-menu-handler.ts
apps/browser/src/browser/context-menu-clicked-handler.ts
apps/browser/src/listeners/combine.spec.ts
apps/browser/src/listeners/combine.ts
apps/browser/src/listeners/index.ts

```
```
The combined listener was sending the `(response: any) => void` callback into the 3rd argument on all the listeners instead of what the listeners were expecting, which was the `CachedServices`. They could all still work just fine because all listeners will just create their own services but they should really try to use the cached services. 
- **apps/browser/src/background.ts:** Manually setup the message listener so we can disregard the `sendResponse` argument. 
- **apps/browser/src/browser/cipher-context-menu-handler.ts:** Change it to expect all 3 arguments that will be passed in. Also add a gate before initializing any of the services that will check if this listener will need to do anything anyways.
- **apps/browser/src/browser/context-menu-clicked-handler.ts:** Expect all 3 …

[PS-2303] MV3 Service Cache Enhancements

---

libs/common/spec/importers/dashlane-csv-importer.spec.ts
libs/common/src/importers/dashlane/dashlane-csv-importer.ts

```
```
Fixes #4282 
The month wasn't set properly on import, as we expect to receive the number of month without a leading zero. The year isn't as strict on import as we assume it being 20XX.
Using the `base.setCardExpiration` helper method takes care of all identifying and substringing.
- **libs/common/src/importers/dashlane/dashlane-csv-importer.ts:** Use `base.setCardExpiration` to set the `expMonth` and `expYear`.
- **libs/common/spec/importers/dashlane-csv-importer.spec.ts:** Adjusted expected test result after manual test

[PS-2094] Dashlane-csv-importer: Set month on import

---

libs/common/src/services/i18n.service.ts

```
```
Improve fragile logic for setting the default language to English if the user's chosen one is not supported or found.
- **libs/common/src/services/i18n.service.ts:** Add `defaultLocale` variable set to `en` and use it wherever we check for the default locale.

[SG-853] Add variable defining default locale as english

---

libs/angular/src/components/add-edit.component.ts

```
```
Currently all managed orgs are visible when Provider User creates an item. This PR fixes that bug by filtering the list. Solution follows existing fixes, eg: https://github.com/bitwarden/clients/pull/4147/files#diff-dc5367fd068ae86241ba5a5123e59aaac54ad3ab8897d42fde18599607ff613cR27 
Fix tested in following scenarios: 
- Provider user without any personal organizations (only clients)
- Provider user with both personal and client organizations

[EC-822] All managed orgs are visible when Provider User creates an item

---

.github/workflows/release-cli.yml

```
```
Change NPM api key in CLI release workflow so that it doesn't suggest that it is/can be used only for cli.
- **.github/workflows/release-cli.yml:** Change name for NPM API key secret from `cli-npm-api-key` to `npm-api-key` as it's general key not tied to CLI npm package.

Change NPM api key in CLI release workflow

---

apps/web/src/app/organizations/shared/components/access-selector/access-selector.component.html

```
```
Left padding was added to the multi-select for the permission select that could be shown next to it. This padding has been moved to the permission select so it only shows if the permission select is shown.

[EC-1021] move padding to permission select

---

apps/web/src/app/organizations/vault/vault-items.component.ts
apps/web/src/app/organizations/vault/vault.component.html
apps/web/src/app/organizations/vault/vault.component.ts
apps/web/src/app/vault/vault-items.component.html
apps/web/src/app/vault/vault-items.component.ts
apps/web/src/app/vault/vault.component.html
apps/web/src/app/vault/vault.component.ts

```
```
Our default behavior when clicking on a vault row should be the default behavior instead of simply selecting the row. For items, that's the edit dialog. For collections, it's navigating into the collection.
When clicking on an item, we now send that event up to the top level `vault.component`.
When clicking on a collection, we navigate.
I've removed a lot of the `(click)` events on `td`s and moved them to the `tr`.
https://user-images.githubusercontent.com/24985544/214131558-66b2b80d-50f9-449e-8bb0-7f0f0ea7ffc0.mov

[EC-1026] Use primary action when clicking on vault row

---

apps/web/src/app/organizations/billing/organization-subscription-selfhost.component.html
apps/web/src/app/organizations/billing/organization-subscription-selfhost.component.ts
libs/common/src/models/api/billing-sync-config.api.ts

```
```
The Last License Sync date was still showing the F4E sync date, which is separate.
Update to show the last license sync date received from server
Goes with https://github.com/bitwarden/server/pull/2626
- add new license sync date property to the response object
- update the template to display this date
- adjust loading logic so that we reload the organizationConnection after a sync (to get the new sync date). But only do this if cloud communication is enabled. (And we only need to check whether cloud communication is enabled on the first load, because you need to restart the self-hosted instance to change that.)
- If this change requires a **documentation update** - notify the documentation …

[License sync] [EC-1036] Show correct license sync date

---

apps/browser/src/background/main.background.ts

```
```
On logout we call stateService.clean to remove the account. The check for vault-timeout in reseedStorage will always return null as the account was already cleaned. The check needs to be done beforehand.
- **apps/browser/src/background/main.background.ts:** 
- Retrieve vault-timeout set by user, before removing the account from stateService (`.clean()`)

[PS-1137] Fix reseed storage

---

apps/web/src/app/vault/vault.component.ts

```
```
Fix an issue where linking to an Item on Personal Vault results in an error “Unknown item, you may need to request permission to access this item.”.
This issue is happening due to the `this.route.queryParams` subscriptions being fired in the wrong order. The command `this.cipherService.get(cipherId)` was returning null because `this.syncService.fullSync(false)` was not yet executed.
- **apps/web/src/app/vault/vault.component.ts:** Combined both subscriptions to be executed in a certain order where `this.syncService.fullSync(false)` always runs first. …

[EC-1053] Link to an Item for Personal Vault results in an error

---

bitwarden_license/bit-web/src/app/secrets-manager/layout/no-items.component.html
bitwarden_license/bit-web/src/app/secrets-manager/projects/projects-list/projects-list.component.html
bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/access/access-list.component.html
bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/access/access-tokens.component.ts
bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/access/dialogs/access-token-create-dialog.component.ts
bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/service-account.component.html
bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/service-account.component.ts
bitwarden_license/bit-web/src/app/secrets-manager/shared/secrets-list.component.html

```
```
This PR adds a Create Access Token button to the header of the Service Account page.
Along the way, this PR also refactors the content projection logic in `sm-no-items`
- `secrets-manager/service-accounts/access/access-token-button.component`: new button component to open the  create access token dialog
- `secrets-manager/service-accounts/access/access-tokens.component`: removed logic no longer needed due to `sm-access-token-button`
- `secrets-manager/layout/no-items.component.html`: updated content projection to be more flexible; updated all references to `sm-no-items` …

[SM-383] add create access token button

---

apps/browser/src/background/main.background.ts

```
```
Remove unneeded sidebarAction in main.background
With https://github.com/bitwarden/clients/pull/3571 the updating of the badge got refactored. Moving this variable/action into `browserApi.getSidebarAction`
- **apps/browser/src/background/main.background.ts:** Removed declaration and defintion of `sidebarAction`

Remove unneeded sidebarAction in main.background

---

apps/desktop/src/app/vault/vault.component.ts

```
```
The right click context menu in the desktop client was incorrectly showing the "Clone" menu option for items that belong to an organization. The desktop client does not support cloning organization items and this was causing inconsistent behaviors.
- **apps/desktop/src/app/vault/vault.component.ts:** Exclude the "Clone" menu item for vault items that belong to an organization.

[EC-669] Hide Clone menu item for organization items

---

apps/browser/src/popup/app-routing.module.ts
apps/browser/src/popup/app.module.ts
apps/browser/src/popup/settings/autofill.component.html
apps/browser/src/popup/settings/autofill.component.ts
apps/browser/src/popup/settings/options.component.html
apps/browser/src/popup/settings/settings.component.html

```
```
Add “Auto-fill” option under “Manage”
When clicked, slide up a new page title “Auto-fill” where the following settings are moved from the “Options” page:
Auto-fill on page load
Default auto-fill setting for login items
Default URL match detection
Remove above items from the “Options” page
Added new Autofill component for the navigation in Settings
Moved code from Options to Autofill
Declared component and route

[SG-901] Relocate Autofill on page load setting

---

apps/browser/src/autofill/notification/bar.html
apps/browser/src/autofill/notification/bar.scss
apps/browser/src/autofill/notification/bar.ts
apps/browser/webpack.config.js

```
```
Getting in some low-hanging tech debt before starting on save prompt improvements. It'll be easiest to review this commit-by-commit to see each step individually. I also recommend hiding whitespace in the diff.
This is being merged into a feature branch to minimise QA's testing load, but it shouldn't be too long lived.
- convert `bar.js` to typescript (cherry-picked from @justindbaur, thank you!)
- use native [template elements](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/template) for the notification bar template content, instead of hiding it in hidden divs. Elements within templates are not returned by `getElementById` or `querySelector` calls (unless called explicitly on `template.content`), so we can use proper ids instead of misusing classnames to identify …

[EC-1062] Convert bar.js to TS and refactor

---

.eslintrc.json
apps/web/src/app/accounts/login/login-with-device.component.html
apps/web/src/app/accounts/register-form/register-form.component.html
apps/web/src/app/accounts/trial-initiation/trial-initiation.component.html
apps/web/src/app/accounts/trial-initiation/vertical-stepper/vertical-step-content.component.html
apps/web/src/app/components/user-verification-prompt.component.html
apps/web/src/app/organizations/shared/components/access-selector/access-selector.component.html
apps/web/src/app/settings/change-avatar.component.html
apps/web/src/app/tools/import-export/export.component.html
apps/web/src/app/tools/import-export/file-password-prompt.component.html
apps/web/src/vault/app/vault/add-edit.component.html
bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-dialog.component.html
libs/components/src/table/table.component.html
package-lock.json
package.json

```
```
Note: this is branched from #3825 to avoid conflicts. That can be merged first and this will automatically update to target master.
Use [eslint-plugin-tailwindcss](https://github.com/francoismassart/eslint-plugin-tailwindcss) to lint our Tailwind classes. This specifically enables the following rules (list below copy/pasted from the README):
* [enforces-negative-arbitrary-values](https://github.com/francoismassart/eslint-plugin-tailwindcss/blob/master/docs/rules/enforces-negative-arbitrary-values.md): make sure to use negative arbitrary values classname without the negative classname e.g. -top-[5px] should become top-[-5px]
* [enforces-shorthand](https://github.com/francoismassart/eslint-plugin-tailwindcss/blob/master/docs/rules/enforces-shorthand.md): merge multiple classnames …

[EC-1051] Add TailwindCSS linting rules

---

libs/common/src/models/request/account/set-key-connector-key.request.ts
libs/common/src/services/keyConnector.service.ts

```
```
Due to https://github.com/bitwarden/mobile/pull/2339 I had another look at the changes, and saw that in the key connector code, adding memory / parallelism seems to have been forgotten. The server side does expect the parameters: https://github.com/bitwarden/server/blob/cb1ba50ce26ce33b2a5acf30536a2075e4fadebd/src/Api/Models/Request/Accounts/SetKeyConnectorKeyRequestModel.cs#L17-L21
The changes are: 
- set-key-connector-key.request.ts: Replace kdfiterations by kdfconfig in parameters and add memory and parallelism
- keyConnector.service.ts: replace kdfIterations by kdfConfig as the parameter for the key connector request

[PS-2414] Fix missing kdf parameters in key connector code

---

apps/browser/src/manifest.json

https://bitwarden.atlassian.net/browse/PS-2387
```
```
Apparently the browser extension manifest v2 file also needs a CSP for loading WASM support. It works on my machine with ot without it, but QA is reporting problems in their testing that seems to suggest it is needed here too.
- **manifest.json:** Add wasm support to CSP.

Add `wasm-unsafe-eval` to browser CSP

---

bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/service-accounts-list.component.html

```
```
The `sm-no-items` component wasn't displaying correctly in the service accounts page. This renames the children of the component to make content projection work properly.

[SM-479] fix sm-no-items in service accounts

---

apps/browser/webpack.config.js
apps/cli/webpack.config.js
apps/web/webpack.config.js
libs/common/spec/misc/utils.spec.ts
libs/common/src/misc/utils.ts
libs/common/src/services/api.service.ts

```
```
Improve the URL path inspection process with API calls. Utilizes the native Node path normalization method to 
process traversals before it becomes an actual URL request.
- **apps/*/webpack.config.js:** Fallback configuration to use webpack's native support for the path library
- **libs/common/spec/misc/utils.spec.ts:** Test for the new utility
- **libs/common/src/misc/utils.ts:** New utility method for path normalization
- **libs/common/src/services/api.service.ts:** Usage of new utility method in favor of insufficient URL comparison …

[CSA-28] Use path normalization in API requests

---

apps/browser/gulpfile.js
apps/browser/src/manifest.json

https://bitwarden.atlassian.net/browse/PS-2387
```
```
Previously we have been removing the CSP from the manifest.json file on dist builds. With the addition of argon2, we now require the CSP to be defined to allow WASM code to load. This PR removes the step during the dist build that deletes the CSP definition. It also bases our CSP back to the default value, which is `"script-src 'self'; object-src 'self';"`.
- **manifest.json:** Remove `'unsafe-eval'` since it is not part of the default CSP.
- **gulpfile.js:**: Don't delete the CSP from manifest.
- If this change has particular **deployment requirements** - notify …

[PS-2387] dont remove CSP on browser dist

---

libs/angular/src/vault/components/add-edit.component.ts

```
```
Fix #4276. There is a race condition where `writeableCollections` is being set within a subscription callback in the `AddEditComponent` base class, which happens asynchronously but cannot be `await`ed by the child class. The child class ends up racing ahead and accessing it before it's set by the base class.
This does not actually need to be in the subscription callback, so we can just move the assignment up to `ngOnInit` in the base class. Same with `canUseReprompt` which I've moved while we're here.
However, this generally seems at high regression risk due to the way this subscription is structured (lots of unpredictable side effects) so I will flag with the appropriate team.
- Please add **unit tests** where it makes sense …

[EC-1063] Fix race condition when adding item from collections list

---

apps/web/src/app/organizations/shared/components/access-selector/access-selector.component.html

```
```
Make sure permission selector doesn't shrink when multi-select wants to grow

[EC-1009] UI feedback adjust width on multi selects to remain consistent with menus

---

apps/web/src/app/organizations/core/services/group/group.service.ts
apps/web/src/app/organizations/core/services/group/requests/group.request.ts
apps/web/src/app/organizations/manage/group-add-edit.component.ts

```
```
The external ID field in the group modal needs to be read-only. This is because edits to the group ID will break the SCIM connection (if SCIM is enabled).
Disable field, remove field from all data classes.

[EC-1003] Make External ID in group modal to read-only

---

apps/web/src/app/organizations/core/services/user-admin.service.ts
apps/web/src/app/organizations/core/views/organization-user-admin-view.ts
apps/web/src/app/organizations/members/components/member-dialog/member-dialog.component.html
apps/web/src/app/organizations/members/components/member-dialog/member-dialog.component.ts
libs/common/src/abstractions/organization-user/responses/organization-user.response.ts

```
```
Add readonly external id field to member dialog.
See server PR: https://github.com/bitwarden/server/pull/2594

[EC-861] Add external id to member modal

---

.github/workflows/test.yml
package.json

```
```
Adds a convenience script to typecheck as we do as part of our build pipeline ([added here](https://github.com/bitwarden/clients/pull/3421)).
⚠️ Here I only add the script, but I'm of the opinion this should be added to the `test` script directly
```json
"test": "concurrently -n Types,Jest -c yellow,cyan \"npm run test:types\" \"jest\"",
```
Opinions on that?
I also see much less value in adding these to watch commands, but open to investigating that as well.

Add type check to npm scripts

---

libs/components/src/table/cell.directive.ts

```
```
Content in cells were not aligned correctly. 
This PR changes all cells across all tables to be vertically aligned to the middle. From what I can see we that's what we always want and I can't spot any places where it has any big impact.
I'm not sure if this is what we want though, so I'm putting this PR up to gather feedback. Alternatives are:
- Add `@Input() align: string;` to `bitCell` directive
- Use `class="tw-align-middle"` in places where it is needed

[Dev Design feedback] The collection name is not aligned with permission text

---

apps/web/src/locales/en/messages.json
apps/web/src/scss/tailwind.css
bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-delete.component.ts
bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-dialog.component.html
bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-dialog.component.ts
libs/components/src/dialog/dialog.service.ts

```
```
This PR fixes misc issues with the secret dialog in SM:
- Add a delete button to the dialog
- (The delete button stacks a delete confirmation dialog on top of the secret dialog.)
- Alphabetize projects in project list
- Fix project name overflow in table
- Fix small style issues
- `libs/components/src/dialog/dialog.service.ts`: Update dialog overlay to work with stacked/nested dialogs
- `bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-delete.component.ts`: delete confirmation dialog returns an array of IDs that were deleted
- `bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-dialog.component`: style fixes; add delete button; close dialog if the secret is deleted
Stacked dialog: …

[SM-73] fix defects

---

bitwarden_license/bit-web/src/app/secrets-manager/layout/navigation.component.html
bitwarden_license/bit-web/src/app/secrets-manager/layout/org-switcher.component.html
bitwarden_license/bit-web/src/app/secrets-manager/layout/org-switcher.component.ts

```
```
The New Organization button should not be shown in the SM org-switcher. This PR adds an input that toggles its visibility. 
- **`bitwarden_license/bit-web/src/app/secrets-manager/layout/org-switcher.component.ts`** add new boolean input `hideNewButton`

[SM-477] remove new org button from org-switcher

---

bitwarden_license/bit-web/src/app/secrets-manager/layout/org-switcher.component.html

```
```
The options on a org-switcher item don't do anything at the moment. This PR removes the fake options.
- **`bitwarden_license/bit-web/src/app/secrets-manager/layout/org-switcher.component.html`:** Removed `bit-menu` and trigger button

[SM-464] remove org switcher item options

---

apps/web/src/app/organizations/shared/components/access-selector/access-selector.component.html

```
```
Fix font size not matching figma.
Technically we were using the correct CSS classes so the issue is actually Figma not matching our deployment environment. Hopefully we'll remove bootstrap soon and stop having these issues.

[EC-1027] The collection name within the modal table appears to be a smaller font than the permission label

---

apps/browser/src/auth/popup/two-factor.component.ts

```
```
Fix for WebAuthn being broken in any chromium 110, this makes it so that the WebAuthn prompt opens up in a new tab just like we do for Firefox and Safari. 
I am not totally sure if this will be fixed or is now the intended behavior, I will be filing an issue with chromium to find out that information, but in the meantime we should get this feature back to working for users. 
Additional context to reviewers:
- WebAuthn Support was added [here](https://github.com/bitwarden/clients/pull/1379)
- A mention of firefox NOT supporting webauthn in the iframe of browser extension [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1460986)
- A mention of an enterprise policy introduced in chrome 110 that can disable the check [here](https://support.google.com/chrome/a/answer/7679408#webAth11 …

[PS-2176] Open WebAuthn Prompt in New Tab for all browser extensions

---

apps/browser/src/autofill/browser/main-context-menu-handler.spec.ts
apps/browser/src/autofill/browser/main-context-menu-handler.ts
apps/browser/src/background/main.background.ts

```
```
With the recent rebuild of the contextmenu to support MV2 and MV3, there have been some issues with async operations and creating/modifying the contextmenu. Most of the errors are irrelevant for the program flow, but the throw causes other side-effects. By catching and logging them, we are able to cancel out any side-effects and keep track of any issues occurring. This is a bandaid which we hopefully can remove the need for in the future.
If only Chrome offered to query which contextMenu items are present, then we could remove specific child items instead of constantly rebuilding it.
- **apps/browser/src/autofill/browser/main-context-menu-handler.ts:** Add try-catch and logging to `init()` and `loadOptions`
- **apps/browser/src/background/main.background.ts:** Fix constructor for …

[PS-2455] Catch and log contextmenu errors

---

.github/workflows/build-cli.yml

```
```
Split *nix and windows cli builds.
- **.github/workflows/build-cli.yml:** Add new job outside of os matrix for building Windows CLI artifacts. Removed Windows-only steps from CLI build for macOS and linux.

[DEVOPS-1185] Split out the windows os from the new cli matrix build

---

libs/common/src/services/api.service.ts

Co-authored-by: Jake Fink <jfink@bitwarden.com>
```
```
#4580 introduced URI decoding to our path traversal tests, but we pass in queries as part of those paths. This causes all previously encoded queries to be decoded and processed as part of a path, which caused some weird unintended consequences, depending on `path` implementation.
This PR splits path parts to maintain traversal safety, while keeping queries properly encoded

PS-2450 EC-1073 Do not decode and normalize query

---

apps/browser/src/autofill/browser/context-menu-clicked-handler.spec.ts
apps/browser/src/autofill/browser/context-menu-clicked-handler.ts
apps/browser/src/background/main.background.ts

```
```
Revert to logic that was used for MV2 as shown [here](https://github.com/bitwarden/clients/blob/e941f06bac63a2de6fae35d21c74cfde313014fa/apps/browser/src/background/contextMenus.background.ts#L134-L145). This is so that the unlock on autofill retries the autofill request. 
- **apps/browser/src/autofill/browser/context-menu-clicked-handler.ts:** Change it so that it accepts an autofill callback so that MV3 and MV2 can have different implementations.
- **apps/browser/src/background/main.background.ts:** Send a custom MV2 callback that is based on the logic that was in place before context menu changes. 
- **apps/browser/src/autofill/browser/context-menu-clicked-handler.spec.ts:** Update tests to use the callback.
- Please add **unit tests** where it makes sense to do so (encouraged …

[PS-2456] Revert to MV2 Autofill Logic

---

apps/web/src/vault/individual-vault/vault-filter/services/vault-filter.service.ts
libs/angular/src/vault/vault-filter/services/vault-filter.service.ts

```
```
Fix an issue where the "Folders" filter section was being hidden by mistake and certain folders were being shown incorrectly when filtering by an organization. 
Specifically:
- "All vaults" and "My vault" should always show all folders
- Organization vault should only show non-empty folders and the "No folder" folder
- Ensures the "Folders" filter section is always visible

[EC-1037] [EC-742] Cleanup vault folder filter logic

---

apps/browser/src/browser/browserApi.ts
apps/browser/src/decorators/session-sync-observable/session-sync.decorator.spec.ts
apps/browser/src/decorators/session-sync-observable/session-sync.decorator.ts
apps/browser/src/decorators/session-sync-observable/session-syncer.spec.ts
apps/browser/src/decorators/session-sync-observable/session-syncer.ts
apps/browser/src/decorators/session-sync-observable/sync-item-metadata.ts
apps/browser/src/decorators/session-sync-observable/synced-item-metadata.spec.ts
apps/browser/src/services/browser-i18n.service.ts
apps/browser/src/services/browser-policy.service.ts
apps/browser/src/services/browser-state.service.ts

```
```
Removes ctor initialization from session syncer, which seems to never work as intended. From my testing this resolves PS-2457 and PS-2464.

Remove ctor initialization in session sync

---

apps/browser/src/vault/popup/components/vault/current-tab.component.ts

```
```
Fix callout not dismissing when clicking 'Got it'
- **apps/browser/src/vault/popup/components/vault/current-tab.component.ts:** Set `showHotToAutofill` variable to false when the user clicks 'Got it'

Fix callout still present after clicking 'Got it'

---

libs/common/spec/importers/keeper-csv-importer.spec.ts
libs/common/src/importers/base-importer.ts

```
```
In Bitwarden, subfolders are separated/indicated using forward-slashes The Keeper CSV export separates folders uses backslashes 
The import completes successfully, but subfolders are not shown as subfolders in the UI. They behaved like normal root-folders.
- **libs/common/src/importers/base-importer.ts:** Replace backslashes with forwardslashes in baseImporter, as this ensures all importers using this method benefit from this fix.
- **libs/common/spec/importers/keeper-csv-importer.spec.ts:** Added tests to verfiy folder/collection creation …

[PS-2422] Keeper CSV import: Fix subfolders not being created

---

bitwarden_license/bit-web/src/app/secrets-manager/shared/projects-list.component.html
bitwarden_license/bit-web/src/app/secrets-manager/shared/secrets-list.component.html

```
```
Fix column spacing issue in the Projects List and Secrets List components introduced in [375c552](https://github.com/bitwarden/clients/commit/375c5526239dd3b1b2a53ae32330d1906d9c2e07).
- **projects-list.component.html:** Remove tailwind classes
- **secrets-list.component.html:** Remove tailwind classes
**Before Fix:**
**After Fix:**

Fix SM Projects List & Secrets List Column Spacing

---

apps/web/src/scss/tailwind.css

```
```
Hide the browser's default marker for the HTML `<details>` element when `tw-list-none` is present
- **`apps/web/src/scss/tailwind.css`:** Add patch to Tailwind for consistent `<details>` styling across browsers: https://github.com/tailwindlabs/tailwindcss/issues/924#issuecomment-915509785

[SM-539] hide HTML Details marker on Safari

---

bitwarden_license/bit-web/src/app/secrets-manager/layout/layout.component.html

```
```
Flexbox is fun. Needed to add `tw-min-w-0` to layout in order to resolve the header consuming to much space.
Before:
After:

[SM-553] Fix header sometimes taking up to much space

---

bitwarden_license/bit-web/src/app/secrets-manager/shared/secrets-list.component.html

```
```
The project badges in the secrets list should be truncated to ~32 characters. 
- **bitwarden_license/bit-web/src/app/secrets-manager/shared/secrets-list.component.html:** Add `tw-truncate`

[SM-538] truncate project badge

---

bitwarden_license/bit-web/src/app/secrets-manager/overview/overview.component.html
bitwarden_license/bit-web/src/app/secrets-manager/overview/overview.component.ts

```
```
- Hides "Create a project" and "Import secrets" from the onboarding if user is not an admin.
- Fixes a small padding issue I came across 

[SM-554] hide admin onboarding items from non-admin

---

bitwarden_license/bit-web/src/app/secrets-manager/overview/overview.component.ts

```
```
This PR fixes an issue where routes were never being reused.
Background:
The `OverviewComponent` sets `this.router.routeReuseStrategy.shouldReuseRoute = () => false;`
This is done to remount the page and trigger the loading spinner when switching organizations, which is needed to prevent a potential vertical layout shift from the onboarding component appearing.
This PR sets `this.router.routeReuseStrategy.shouldReuseRoute` back to its initial value when navigating away from the overview page. …

[SM-571] reenable route reuse on destroy

---

bitwarden_license/bit-web/src/app/secrets-manager/overview/overview.component.html
bitwarden_license/bit-web/src/app/secrets-manager/overview/overview.component.ts
bitwarden_license/bit-web/src/app/secrets-manager/projects/project/project-secrets.component.html
bitwarden_license/bit-web/src/app/secrets-manager/projects/project/project-secrets.component.ts
bitwarden_license/bit-web/src/app/secrets-manager/secrets/secrets.component.html
bitwarden_license/bit-web/src/app/secrets-manager/secrets/secrets.component.ts
bitwarden_license/bit-web/src/app/secrets-manager/shared/secrets-list.component.html

```
```
This PR adds functionality to the "Copy secret name" and "Copy secret value" buttons in the secrets list.
Bound `PlatformUtilsService.copyToClipboard` to the `(editSecretEvent)` and `(copySecretNameEvent)` outputs in all the places we use the secrets list.

[SM-520] add secret copy actions

---

.github/workflows/label-issue-pull-request.yml

```
```
In #4727, I added a new Github workflow to add a `needs-qa` label.  Upon merge into `master`, I discovered that I had the incorrect syntax for the `types` field in YAML.  
- **label-issue-pull-request.yml:** Modified the syntax for the triggering types.  Putting the `-` in front of the field was interpreted as a list of lists of types, which is not the intent.

Corrected syntax for job to label branches with needs-qa

---

.github/workflows/label-issue-pull-request.yml

```
```
Fix inadvertent runs of the `Label Issue Pull Request` action.
I did not account for scenarios where `needs-qa` has been removed (as it has been tested) but we need to pull `master` into the branch.  That push would trigger the action to run again, applying the tag that was removed.  I modified the action to be a bit more selective on when it will trigger.  Now it will only trigger when a PR is opened and when edited, which is to catch when the target branch changes.
- **[.github/workflows/label-issue-pull-request.yml](https://github.com/bitwarden/clients/compare/fix-issue-label-action?expand=1#diff-d6bbcb02c652bcaa86a2da3c08ca015be30a974bc462339fffde8dc1acd334d6):** Removed `synchronize` from trigger list.
- Please add **unit tests** where it makes sense to do so (encouraged but …

Modified needs-qa labeler to only fire when PR is opened or edited

---

libs/components/src/color-password/color-password.component.ts

```
```
Fix the following bug: When selecting and copying a password displayed using the `ColorPasswordComponent`, the copied selection included hidden whitespace.
Thanks to @coroiu for this fix, I'm just doing the Jira/Github admin.
* use `span` elements instead of `div`, to avoid invisible whitespace
* move `tw-inline-flex` to the "count" display only, it's not required for the normal display and interferes with Chrome

[AC-1084] Don't copy hidden spaces when selecting password

---

apps/web/src/locales/en/messages.json
bitwarden_license/bit-web/src/app/secrets-manager/overview/onboarding.component.html
bitwarden_license/bit-web/src/app/secrets-manager/overview/onboarding.component.ts
bitwarden_license/bit-web/src/app/secrets-manager/overview/overview.component.html
bitwarden_license/bit-web/src/app/secrets-manager/overview/overview.component.ts
bitwarden_license/bit-web/src/app/secrets-manager/sm-routing.module.ts

```
```
It seems the router reuse hack causes a unintended side effect of tricking the application into believing the `/login` route should be stored, which results in a redirect loop from `/login` to `/login` which is handled by not redirecting anywhere.
Also added `AuthGuard` to the secrets manager routes, which ensures that the previous url is properly stored when redirecting to the login page. …

[SM-589][SM-592] Remove router reuse hack

---

libs/components/src/icon/icon.component.ts
libs/components/src/icon/icon.components.spec.ts

```
```
The SM logo was not consistently registering click events. This was caused by `BitIcon` repeatedly updating its `innerHTML`. This PR fixes `BitIcon` to only update when the icon source is changed. 
- **libs/components/src/icon/icon.component.ts:** Remove `innerHTML` getter. 
- **libs/components/src/icon/icon.components.spec.ts:** Update tests to not fail from Angular's `` comments.

[SM-607] fix BitIcon innerHTML rerender removing click handler

---

apps/browser/src/autofill/background/notification.background.ts
apps/browser/src/background/runtime.background.ts
libs/angular/src/vault/components/add-edit.component.ts
libs/common/src/vault/types/add-edit-cipher-info.ts

```
```
Fix the following bugs in the new auto-save edit flow:
* when updating an existing item, the state of the "collections" checkboxes were not being restored according to `cipher.collectionIds`
* if you have the Remove Personal Vault policy activated, but still have some personal items (from before the policy was turned on), the edit flow changes the Owner from individual to organization. This is not how the popup works and is not able to be saved (we have the "Move to Organization" flow to do this properly).
- save `collectionIds` in the `AddEditCipherInfo` object. This is used because `AddEditComponent` doesn't use reactive forms and doesn't map the selected collection checkboxes to the `Cipher` object until the item is saved, so it's not expecting `cipher.collectionIds` to be …

[AC-1173] Fix state bugs in auto-save edit flow

---

bitwarden_license/bit-web/src/app/secrets-manager/overview/overview.component.ts
bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-delete.component.ts
bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-dialog.component.html
bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-dialog.component.ts

```
```
The purpose of this PR is to fix the edit secret dialog that doesn't launch when the secret is not assigned to a project.
The PR also has the secrets list refresh when a project deletion occurs on the overview page.
- bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-dialog.component.html
- bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-dialog.component.ts
Load default value if not projects exist.
- bitwarden_license/bit-web/src/app/secrets-manager/overview/overview.component.ts
Have secrets list refresh when a project deletion occurs on the overview page.
- If …

[SM-611] Fix edit dialog & overview secrets refresh

---

apps/web/src/app/settings/organization-plans.component.ts

```
- [c] Bug fix
```
Single org policy should not block provider admins from creating client organizations

[AC-1078] Provider Admin part of an org with Single Org Policy enabled cannot create new Client Organizations

---

bitwarden_license/bit-web/src/app/secrets-manager/shared/secrets-list.component.html

```
```
Items in the secrets list that are not assigned to a project should show an "Unassigned" warning badge.
- **bitwarden_license/bit-web/src/app/secrets-manager/shared/secrets-list.component.html:** Check projects length and show badge

[SM-621] unassigned secret badge

---

apps/web/src/scss/tailwind.css
libs/components/src/link/link.directive.ts

```
```
HTML button's have a default center text align. We don't correct for this in `bitLink`, resulting in `a[bitLink]` and `button[bitLink]` having different styles, when they _should_ be visually indistinct. This PR updates `bitLink` to have a text align of `unset`. 
- **apps/web/src/scss/tailwind.css:** Adds a new global class `tw-text-unset`. This was needed because Tailwind is inconsistent with where arbitrary values are allowed--we can't simply do `tw-text-[unset]` like we can with other Tailwind classes.
- **libs/components/src/link/link.directive.ts:** Updates the `bitLink` directive to use `tw-text-unset`
- …

[SM-624] add text-align unset to bitLink

---

bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-dialog.component.html
bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-dialog.component.ts

```
```
Currently, when user edits a secret, the loading spinner appears twice. 
The goal of this PR is to...
- Keep the spinner from flickering off and on.
- Only show the spinner with the edit modal. Don't show it with the add modal.
- Update the spinner size to keep the modal from changing size when it is finished loading.
- The spinner is now absolutely position over the main content, to ensure no size changes. 
- The form is disabled while loading.
https://user-images.githubusercontent.com/17113462/223830234-e4117910-c14b-4801-8042-9bb7ed76abe8.mov
https://user-images.githubusercontent.com/17113462/223801734-da66a847-1f4e-4f1c-977a-220e7e623501.mov …

[SM-470] fix SM edit secret spinner

---

bitwarden_license/bit-web/src/app/secrets-manager/shared/header.component.html
libs/angular/src/pipes/user-name.pipe.ts

```
```
If the user doesn't have a name, the SM header account dropdown should fallback to showing the user's email.

[SM-590] show email as fallback name in SM header

---

bitwarden_license/bit-web/src/app/secrets-manager/overview/overview.component.ts
bitwarden_license/bit-web/src/app/secrets-manager/projects/project/project-secrets.component.ts
bitwarden_license/bit-web/src/app/secrets-manager/secrets/secrets.component.ts
bitwarden_license/bit-web/src/app/secrets-manager/shared/secrets-list.component.ts

```
```
Fixes copying a secret's value from the secrets list in SM. 
In Safari, we cannot wait for a promise to resolve _and then_ copy text. Instead, we have to pass the promise itself to a `ClipboardItem` constructor. 
This is a short-term fix just for the secrets list in SM. Bringing this fix into the `PlatformUtilsService` itself would warrant further testing/investigation.

[SM-632] fix copy secret value in Safari

---

bitwarden_license/bit-web/src/app/secrets-manager/trash/trash.component.html

```
```
Add callout to SM Trash page about secret auto-deletion after 30 days.
The auto delete is not implemented yet but once it is and is turned on, any secrets older than 30 days will be automatically deleted.

SM-637: Add SM Trash Auto-delete Callout

---

bitwarden_license/bit-web/src/app/secrets-manager/shared/secrets-list.component.html

```
```
Remove clickable links for the secrets when the secrets are displaying in the SM Trash.
Secrets List with Links
Trash List without Links

SM-617: Remove secret links when displaying secret in the trash

---

apps/web/src/app/vault/individual-vault/vault.component.ts

```
```
We are still seeing reports of users getting locked out of their vault after changing KDF iterations.  We are going to disable the warning again.
- **vault.component.ts:** Disabled the low KDF iteration warning.

Disable the KDF warning

---

apps/browser/src/_locales/en/messages.json
apps/browser/src/vault/popup/components/vault/current-tab.component.ts

```
```
Remove "You can also try auto-fill on page load" from browser extension callout.
- **apps/browser/src/_locales/en/messages.json:** Remove extra sentence.

[PM-1405] Remove auto-fill on page load verbiage

---

bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/service-accounts-list.component.ts
bitwarden_license/bit-web/src/app/secrets-manager/shared/projects-list.component.ts
bitwarden_license/bit-web/src/app/secrets-manager/shared/secrets-list.component.ts

```
```
Add error messages when executing bulk actions on secrets or projects but nothing is selected.
Specifically:
- When bulk deleting secrets but nothing is selected, this toast should show & no actions are taken
- When bulk restoring secrets from the trash but nothing is selected, this toast should show & no actions are taken
- When bulk deleting projects but nothing is selected, this toast should show & no actions are taken
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing …

SM-615: Add Error Messages for Unselected Bulk Actions in SM

---

apps/web/webpack.config.js

```
```
In our Webpack config, font assets are not renamed with hashes. This means that whenever a font file changes, it is not necessarily updated in the user's cache. This PR fixes that by including a hash in the filename. 
- **apps/web/webpack.config.js:** Changed naming rule to `fonts/[name].[contenthash][ext]`

[SM-668] hash font asset names

---

libs/common/src/models/view/send.view.ts

```
```
Copy send link was broken on browser extension. The `key` part of url wasn't being sent.
- **send.view.ts:** `ToJson` was affecting current `this` object and changing the `key` property into a Base64 string, so all the subsequent calls to  `Utils.fromBufferTo` on `ToJson` or `get urlB64Key()` were returning and empty string as they were expecting `key` to be an `ArrayBuffer`. So now a copy of `this` is made and changed by `ToJson` …

PM-1195 - Copy send link fix on browser

---

bitwarden_license/bit-web/src/app/secrets-manager/shared/secrets-list.component.html

```
```
Fix small bug in the `sm/SM-574` branch for this PR: https://github.com/bitwarden/clients/pull/4941. When deleting a secret we should pass the whole secret, not just the `id`. (Note, we emit this type: `SecretListView[]`)
Testing should be covered in https://github.com/bitwarden/clients/pull/4941.
- **secret-list.component.html:** Pass entire secret list view object, not just id

SM-671: Fix Secret Deletion Bug

---

apps/desktop/src/locales/en/messages.json
apps/desktop/src/main/menu/menu.help.ts

```
```
- Change naming for “Get help” link to “Help and feedback”
- Remove “Contact us” option from help menu
- 
- **apps/desktop/src/main/menu/menu.help.ts:** Remove 'Contact us' option. Rename 'Get help' to 'Help and Feedback'.
Before:
After:

[PM-1254] Desktop help menu adjustments

---

libs/components/src/tabs/shared/tab-list-item.directive.ts

```
```
The acitve tab uses the wrong background color. Seems the transparent background gets priority over the correct background. This should work better once we've removed the base bootstrap styling.
Before:
After:

[PM-1644] Resolve active tab using the wrong background color

---

apps/web/src/auth/login/login.component.html
libs/angular/src/auth/components/login.component.ts

```
```
Fix the web client login master password flow not autofocusing the master password field after a valid email has been entered. 
- **apps/web/src/auth/login/login.component.html:** Remove `appAutoFocus` directive as it doesn't work anymore since we refactored the login.component to work with [autofill & two step login](https://github.com/bitwarden/clients/pull/4844) (Note: at least I think that's when it was broken). Add template reference variable so web login component can focus the input. 
- **libs/angular/src/auth/components/login.component.ts:** On email validation, autofocus the master password input. 
https://user-images.githubusercontent.com/116684653/229230208-06873574-bda7-4318-9830-4ff7db900b91.mov
- Please add **unit tests** where it makes sense to do so (encouraged but …

Defect / PM-1354 - Fix master password not auto focused on web login flow

---

apps/desktop/src/app/app.component.ts

```
```
Locking all non-active accounts prior to active lead to process reload issues. This was ultimately due to auth guard being triggered and loading lock with the prompt biometrics parameter.
I'm not sure why auth guard routing depended on locking order, but if the active account is logged out first this doesn't occur, blocking this issue 🤷 
- **app.component.ts**: instead of locking in order, lock the active account first, then lock all others. …

[PM-1890] Lock active account first

---

apps/browser/src/popup/settings/settings.component.ts

```
```
observable value change is triggering twice, debounce to display warning only once on choosing never lock. Other observables in file either are not triggering multiple times, or, in the case of biometrics, quickly turning off in the event of failed native messaging is desirable.

[PM-1889] Debounce value changes

---

apps/web/src/app/vault/org-vault/vault.component.ts
libs/angular/src/vault/components/add-edit.component.ts
libs/common/src/vault/abstractions/cipher.service.ts
libs/common/src/vault/services/cipher.service.ts

```
```
After [refactoring the vault tables](https://github.com/bitwarden/clients/pull/4967) we stopped calling the Cipher Admin restore endpoints which Provider Admin users need since they don't have direct Organization permissions.
- **apps/web/src/app/vault/org-vault/vault.component.ts:** Passing the `organization.canEditAnyCollection` argument to `cipherService`
- **libs/angular/src/vault/components/add-edit.component.ts:** Passing the `organization.canEditAnyCollection` argument to `cipherService`
- **libs/common/src/vault/abstractions/cipher.service.ts:** Added new parameter `orgAdmin: boolean` do determine if the service should call the admin delete cipher endpoint
- **libs/common/src/vault/services/cipher.service.ts:** Calling either `apiService.putRestoreCipherAdmin` or …

[AC-1340] [Defect] Provider users unable to restore vault items for client organizations

---

libs/angular/src/auth/components/login.component.ts

```
```
[AC-1267](https://bitwarden.atlassian.net/browse/AC-1267) - Fix Login Master Pass Entry Prematurely Showing Validation Errors
- **libs/angular/src/auth/components/login.component.ts:** 
- Mark master pass (MP) field as untouched on any load of MP section of login page post email validation in order to prevent validation errors of "input required" from being shown prematurely before the user has entered anything or lost focus on the input **when the user hits enter** on the login screen after entering an email 
- Improve the logic around the MP autofocus to match existing code patterns to ensure there are no possible scenarios in which the MP would not be autofocused.
https://user-images.githubusercontent.com/116684653/233497641-99787170-c304-4207-b233-22deb59d6457.mov
- Please add …

Defect/AC-1267 - Fix Login Master Pass Entry Prematurely Showing Validation Errors

---

apps/cli/src/tools/send/commands/receive.command.ts

```
```
`receive.command` is still defaulting bitwarden cloud domains to `vault.bitwarden.com/api` this updates to use `api.bitwarden.com`
- **receive.command.ts:** Updated ApiUrl method to return `api.bitwarden.com` instead `vault.bitwarden.com/api`

[PM-1267] Update cli receive command to use api.bitwarden.com

---

apps/web/src/app/vault/individual-vault/vault.component.ts
libs/common/src/enums/feature-flag.enum.ts

```
```
Refactor the `isLowKdfIteration()` method to check if the `display-kdf-iteration-warning` feature flag is enabled before evaluating the low KDF iteration warning condition. This will allow for better control over when the low KDF iteration warning is displayed to users.
- **libs/common/src/enums/feature-flag.enum.ts:** Created a new flag `DisplayLowKdfIterationWarningFlag`
- **apps/web/src/app/vault/individual-vault/vault.component.ts** Updated the `isLowKdfIteration()` method to include a call to retrieve the feature flag value for `display-kdf-iteration-warning`. …

[PM-1700] Put KDF warning behind a LaunchDarkly Feature Flag

---

libs/components/src/dialog/dialog.service.stories.ts
libs/components/src/dialog/dialog/dialog.component.html
libs/components/src/dialog/dialog/dialog.stories.ts
libs/components/src/dialog/simple-configurable-dialog/simple-configurable-dialog.component.html
libs/components/src/dialog/simple-dialog.service.stories.ts
libs/components/src/dialog/simple-dialog/simple-dialog.component.html
libs/components/src/dialog/simple-dialog/simple-dialog.stories.ts

```
```
This allows us to remove the base styling from each dialog.
Simply replace:
```html
<div bitDialogFooter class="tw-flex tw-items-center tw-flex-row tw-gap-2">
<button bitButton buttonType="primary">Save</button>
<button bitButton buttonType="secondary">Cancel</button>
</div>
```
with:
```html
<ng-container bitDialogFooter>
<button bitButton buttonType="primary">Save</button>
<button bitButton buttonType="secondary">Cancel</button>
</ng-container>
``` …

[PM-1913] Add base styling to dialog footer component

---

bitwarden_license/bit-web/src/app/secrets-manager/shared/projects-list.component.html

```
```
Fixes Axe a11y issue "Table header text should not be empty" by moving show/hide logic to the `th` instead of the `button`. 
Also fixes the vertical layout shift by using css `visibility` instead of `*ngIf`.
- **bitwarden_license/bit-web/src/app/secrets-manager/shared/projects-list.component.html:** Updates show/hide logic in table header
Existing behavior:
https://user-images.githubusercontent.com/17113462/235195169-843840fc-afdb-4b2b-b4c2-e75ceffd78bc.mov
New behavior:
https://user-images.githubusercontent.com/17113462/235195302-565c1ce4-196b-4d99-8589-483089ac706b.mov …

[SM-724] improve table header a11y; fix vertical layout shift

---

apps/cli/src/program.ts

https://bitwarden.atlassian.net/browse/AC-1311
```
```
Some error states of the login command will hang and not cleanly exit. The thought is that something is not properly awaited. The cause is unknown still, but this works around the problem until a proper solution can be found. Several other commands appear to be passing this flag, likely for the same reasons. Since the login command is not returning large amounts of data to stdout (such as `bw list`, for example), the risks of exiting immediately should not be a problem.
- **program.ts:** Exit immediately flag passed while processing the response for the login command.
- If this change requires a **documentation update** - notify the documentation …

exit immediately after login command run

---

apps/browser/src/popup/scss/base.scss

```
```
I just made the previous commit https://github.com/bitwarden/clients/pull/3929 complete by applying the change to all affected search inputs, not just ones inside of `.tab-page`
"clients/apps/browser/src/popup/scss/base.scss" : I modified the previous fix that made for better contrast on the search input apply to all pages.
The correct behaviour exists in the "outer" routes, seen here.
However, in the Vault submenu items like Login, Card, Identity, Secure Note, Folders, and Collections, the dismiss icon for both light and dark themes is not legible.
So I moved the previous fix to apply to all inputs of type search, and now the above pages look like this
- If this change requires …

[PM-1909] Apply search input contrast fix to all pages

---

bitwarden_license/bit-web/src/app/secrets-manager/secrets-manager.module.ts
bitwarden_license/bit-web/src/app/secrets-manager/sm-routing.module.ts
bitwarden_license/bit-web/src/app/secrets-manager/sm.guard.ts

```
```
When users land on `/sm` they are now redirected to their first available organization with access to SM. If the user does not have access to SM, they are redirected to the vault. 
- **bitwarden_license/bit-web/src/app/secrets-manager/sm.guard.ts:** Updated guard to redirect based on available orgs. Rewrote the guard to no longer use the deprecated `CanActivate` interface and to use the new `CanActivateFn` pattern.
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/access …

[SM-673] redirect from SM root to overview page

---

libs/components/src/input/input.directive.ts

```
```
https://github.com/bitwarden/clients/pull/4375 introduced a behavior where errors would disappear when the user started typing on an invalid field but introduced an issue where errors would never appear if the user tried to submit the form by using `enter` while focused on the invalid field. See videos below
https://user-images.githubusercontent.com/2285588/234590217-0f39965a-a4c9-49f3-8fad-ace4d8a9e760.mov
https://user-images.githubusercontent.com/2285588/234590312-a0a4ab6b-2ba1-4042-a7cc-83af022030a1.mov
- Ensure that all UI …

[PM-2114] Tweak error onBlur/touched/untouched behavior

---

package-lock.json
package.json

```
```
Some packages were accidentally duplicated while upgrading Electron Builder in #5038. This PR removes the duplicates.

[PM-2183] Remove duplicated electron packages

---

.github/workflows/brew-bump-cli.yml
.github/workflows/build-web.yml
.github/workflows/chromatic.yml
.github/workflows/enforce-labels.yml
.github/workflows/label-issue-pull-request.yml
.github/workflows/release-web.yml
.github/workflows/test.yml
.github/workflows/version-bump.yml

```
```
Renovate is complaining because some of the GH workflows used the wrong version tags.
- Bumped crowdin for web since it was fairly outdated (and tag v1.4.9 doesn't exist)
- Removed tag for chromatic, they don't tag their releases.
- enforce-label shouldn't have `v` prefix.
- release-web couldn't find v2.0.5 anywhere nor that commit. Changed to 2.0.1 since that's used in the other places.
- brew-bump-cli.yml missing tag for action-homebrew
- build-web.yml fix tag for docker
- Fix rust toolchain. (downgraded two commits since they only changed documentation)
- crazy-max/ghaction-import-gpg reference correct version tag. …

Fix version tags for gh workflows

---

.github/workflows/label-issue-pull-request.yml

```
```
The workflow to add `needs-qa` was triggered on a PR `open` or `edited` trigger.  The intent there was to capture when the target branch changed, so you couldn't open a PR targeting a non-`master` branch then re-target to `master` and avoid having the label applied.
However, this caused problems when the PR description was changed, as it would re-add the `needs-qa` label.
- **label-issue-pull-request.yml:** Removed `edited` from trigger array …

Removed PR edit trigger from workflow that adds needs-qa label

---

apps/web/src/app/vault/components/vault-items/vault-cipher-row.component.html
apps/web/src/app/vault/components/vault-items/vault-collection-row.component.html

```
```
Resolve UI issues in the vault:
- insufficient line-height causes vertical character cutoff of collection names in the vault tab view 
- long names in the vault views cause text to wrap and not truncate properly
see: https://github.com/bitwarden/clients/pull/5345#discussion_r1183840081
| --- | --- |
| ![all-before](https://user-images.githubusercontent.com/1556494/235962007-dde92504-840f-453a-9a70-658b5aa47d9c.png) | ![all-after](https://user-images.githubusercontent.com/1556494/235962006-d5269883-3b4d-46a8-b9ac-45df753ee9b4.png) |
| ![vault-before](https://user-images.githubusercontent.com/1556494/235962012-07f6fa89-b520-424e-84fb-9000751f6a45.png) | ![vault-after](https://user-images.githubusercontent.com/1556494/235962009-f3c47e4d-e8cd-42bc-8148-d8bc1d387ba6.p …

[PM-1884] Address vault ui long name overflow and vertical letter cutoff

---

apps/browser/src/_locales/en/messages.json
apps/browser/src/autofill/content/autofill.js

```
```
Update the iframe autofill alert text to indicate the context of Bitwarden.
- Updated existing iframe autofill warning text
- Use `chrome.i18n.getMessage` API to pull dialog text from catalog entries
- small formatting changes and removed trailing spaces
| Before (Chrome) | After (Chrome) |
| --- | --- |
| ![before](https://user-images.githubusercontent.com/1556494/236222929-eb64c18e-efad-4a8f-b5ce-e4f71f81e6ec.png) | ![after](https://user-images.githubusercontent.com/1556494/236222947-7916dfd5-7fa3-462f-bfb2-98f2d9fbae6f.png) |
| Before (Firefox) | After (Firefox) |
| --- | --- |
| ![firefox-before](https://user-images.githubusercontent.com/1556494/236326018-2d6bedd5-5220-4d18-ab1a-bf917af08ef7.png) | ![firefox-after](https://user-images.githubusercontent.com/1556494/236326016-21b …

[PM-1498] Update the iframe autofill alert text

---

package-lock.json
package.json

```
```
Remove [tapable](https://github.com/webpack/tapable) as dependency as we don't use it
tapable is a package which is used by other packages we depend on, but we don't actually use it anywhere.
- **package.json and package-lock.json:** Changes after running `npm uninstall tapable`

Remove tapable as dependency as we don't use it

---

apps/browser/src/browser/browserApi.ts
libs/angular/src/services/theming/theming.service.ts

```
```
Fix the memory leaks that appear only in Safari.
- **browserApi.ts:** Deregister all messageListeners on a popup unload event in Safari
- **theming.service.ts:** Remove a reference cycle between window and ThemingService caused by subscribing to the matchMedia event. Note that in Safari we are using the background page window here and it doesn't handle dynamic theme changes, so we could just as well disable the `monitorSystemThemeChanges` in Safari.
https://github.com/bitwarden/clients/blob/89ae1017e3dfec0e10f2fd189970d7321611298d/apps/browser/src/popup/services/services.module.ts#L481-L482 …

[PM-2197] Fix memory leaks in Safari

---

apps/browser/config/base.json
apps/browser/config/production.json
apps/cli/config/production.json
apps/desktop/config/production.json
apps/web/config/selfhosted.json

```
```
Enable client-side flags for QA to test vault item encryption.  This PR turns on the new encryption in the following environments:
- Desktop
- Browser
- CLI
- Web Vault
- Self-hosted environment
- **base.json:** Added base default of `false` for Browser config.
- **production.json:** For CLI, Desktop, and Browser, set `enableCipherKeyEncryption` to `true`
- **selfhosted.json:** For web vault, set `enableCipherKeyEncryption` to `true` for self-hosted, so QA can test on their self-hosted instances
- Ensure that all UI additions …

Updated config to turn on vault-item encryption for QA testing.

---

apps/browser/src/auth/popup/two-factor.component.ts
apps/browser/src/browser/browserApi.ts

```
```
[Jira: PM-2403](https://bitwarden.atlassian.net/browse/PM-2403)
1. Fix issue with Safari's tab extension not closing after successful SSO Login + 2FA continue which sidesteps the inconsistent MP invalid issue (due to invalid KDF config settings on reload) 
- Firefox + sidebar, opera + sidebar, chrome, safari, and edge tested; see below videos for proof. 
2. Refactor existing reload logic to exempt the current window as we really only need to reload sidebars so they end up on the lock screen vs. staying on the login screen and we are just going to close the open extension running in the tab anyway.
3. Add comments to explain _why_ we are refreshing and closing things. 
- **apps/browser/src/auth/popup/two-factor.component.ts:**  Exempt current window from reload. Refactor close …

Defect/PM-2403 - Fix non-locally reproducible Master Password Invalid issue in Safari after SSO + 2FA login

---

apps/browser/src/auth/popup/two-factor-options.component.html
apps/browser/src/auth/popup/two-factor-options.component.ts
apps/browser/src/auth/popup/two-factor.component.ts

```
```
[Jira: PM-2403](https://bitwarden.atlassian.net/browse/PM-2403)
Persist SSO flag between 2FA component and 2FA Options component and back so that the correct onSuccessful login logic can run which closes the tab extension and sidesteps Safari master password invalid issues due to null KDF config / iterations again. Tested on Chrome, Firefox + sidebar, Edge, Opera + sidebar, and Safari
- **apps/browser/src/auth/popup/two-factor-options.component.html, apps/browser/src/auth/popup/two-factor-options.component.ts, apps/browser/src/auth/popup/two-factor.component.ts:** Persist sso query param flag between all 2FA routes.  …

Defect/PM-2403 - Attempt 2 at fixing Safari - SSO + 2FA login flow not properly closing the tab 

---

apps/cli/src/tools/import.command.ts
apps/cli/src/vault.program.ts

```
```
Analog to https://github.com/bitwarden/clients/pull/4380 we also need to add a full sync to the `import.command`, so that when a user calls `bw list items` those are populated.
- **apps/cli/src/vault.program.ts:** Pass in the syncService into the importCommand
- **apps/cli/src/tools/import.command.ts:** Require syncService and call fullSync after a successful import.

[PM-2368] Add fullSync on successful import

---

apps/browser/src/background/main.background.ts
apps/browser/src/popup/services/services.module.ts

```
```
The [PR](https://github.com/bitwarden/clients/pull/5538) for adding validations to ensure new encryption isn't called when the server doesn't support it works on all clients except the browser.
The initial failure was due to the `CipherService` attempting to access the configApiService before it had been instantiated. To resolve this issue, I ensured the `ConfigApiService` was initialized within the `main.background.ts` file on the browser client side. …

[PM-1689] Add restriction to only encrypt fails on browser

---

apps/cli/src/bw.ts

```
```
The [PR](https://github.com/bitwarden/clients/pull/5538) for adding validations to ensure new encryption isn't called when the server doesn't support it fails on the CLI.
The initial failure was due to the CipherService attempting to access the configApiService before it had been instantiated.

[PM-2565] Add restriction to only encrypt fails on CLI

---

libs/common/src/tools/generator/username/email-forwarders/simple-login-forwarder.ts

```
```
While working on https://github.com/bitwarden/clients/pull/4809 I had some issues seeing proper api error messages as the details weren’t showing up in the error toasts. It turned out that the returning errors were thrown inside a try-catch. Those would then be caught by the catch and then a generic error message would be thrown.
This pattern was also discovered in the SimpleLogin username generator.
- **libs/common/src/tools/generator/username/email-forwarders/simple-login-forwarder.ts** `Remove try-catch to display proper api-errors …

[PM-2522] Simplelogin: Fix display of api-error messages

---

.github/CODEOWNERS

```
```
Move `apps/browser/src/autofill` to be owned by @bitwarden/team-client-integrations-dev 

Change ownership of autofill from vault to client integrations

---

apps/cli/src/commands/serve.command.ts

These options are no longer considered safe as the file location or environment variable could be guessed by an attacker.
```
```
Remove `passwordFile` and `passwordEnv` from `bw serve` query options going to the `unlock` endpoint.

Remove password options from `serve` unlock

---

apps/cli/src/bw.ts

```
```
CLI's import was throwing the following exception `Cannot read properties of undefined (reading 'getAuthStatus')`. Changing the service creation order so that `AuthService` is defined when called on import
- **bw.ts:** Changed the order of service creation so that when creating the `ConfigApiService` instance the `AuthService` is already defined

[PM-2744] cli import is failing

---

libs/angular/src/vault/components/attachments.component.ts
libs/common/src/vault/abstractions/cipher.service.ts
libs/common/src/vault/services/cipher.service.ts

```
```
To fix the problem of adding an attachment to an item with cipher key level encryption in a client with user key level encryption.
- **attachments.component.ts:** Identify the encryption level of the item to which we pretend to add an attachment. If it's level is cipher key encryption and the client has this level disabled, we revert it's encryption level in order to have the item and the attachment in the same level of encryption. …

[PM-2582] Fix adding attachments 

---

apps/web/src/app/tools/import-export/dialog/file-password-prompt.component.html
apps/web/src/app/tools/import-export/dialog/file-password-prompt.component.ts
apps/web/src/app/tools/import-export/import.component.ts
libs/importer/src/importers/bitwarden/bitwarden-password-protected-importer.ts

```
```
Migrate file-password-prompt to dialog which also cleaned up any custom tailwind class usage
- **apps/web/src/app/tools/import-export/dialog/file-password-prompt.component.html:** Replace to use bitDialog
- **apps/web/src/app/tools/import-export/dialog/file-password-prompt.component.html:** Replace usage of ModalRef to DialogRef
- **apps/web/src/app/tools/import-export/import.component.ts:** Get result from new dialog
- **libs/importer/src/importers/bitwarden/bitwarden-password-protected-importer.ts:** Fix issue with cancel/empty password returned
**BEFORE:**
**AFTER:** …

[PM-1826] [PM-2168] [Tech debt] Migrate file-password-prompt to dialog

---

apps/browser/src/auth/popup/lock.component.ts
apps/browser/src/auth/popup/login-decryption-options/login-decryption-options.component.ts
apps/desktop/src/auth/lock.component.ts
apps/desktop/src/auth/login/login-decryption-options/login-decryption-options.component.ts
apps/web/src/app/auth/lock.component.ts
apps/web/src/app/auth/login/login-decryption-options/login-decryption-options.component.ts
libs/angular/src/auth/components/base-login-decryption-options.component.ts
libs/angular/src/auth/components/lock.component.ts
libs/angular/src/auth/components/two-factor.component.ts
libs/angular/src/services/jslib-services.module.ts
libs/common/src/abstractions/device-crypto.service.abstraction.ts
libs/common/src/auth/abstractions/device-trust-crypto.service.abstraction.ts
libs/common/src/auth/login-strategies/sso-login.strategy.ts
libs/common/src/auth/services/device-trust-crypto.service.implementation.ts
libs/common/src/auth/services/device-trust-crypto.service.spec.ts
libs/common/src/platform/abstractions/state.service.ts
libs/common/src/platform/models/domain/account.ts
libs/common/src/platform/services/state.service.ts
libs/common/src/services/device-crypto.service.implementation.ts

```
```
- Users who have a master password have the option to approve their login using their master password on the `LoginDecryptionOptionsComponent`. 
- If the user chooses to trust (“remember”) the device, then, once they unlock their vault via MP, we should establish trust, removing the necessity of entering their master password in the future. 
- **libs/common/src/platform/abstractions/state.service.ts && libs/common/src/platform/services/state.service.ts:** - Add `getUserDeviceTrustChoice() `and `setUserDeviceTrustChoice(...)` methods to save user's choice in local storage 
- **libs/common/src/abstractions/device-crypto.service.abstraction.ts && libs/common/src/services/device-crypto.service.implementation.ts:** - Add `getUserDeviceTrustChoice() `and `setUserDeviceTrustChoice(...)` …

Feature/PM-1212 - TDE - Approve with master password flow

---

apps/desktop/src/auth/login/login.component.html
apps/desktop/src/auth/login/login.component.ts

Change event handle to view
```
```
After clicking "Not you?" on second login step, the region selector does not open dialog.
- Add static to ViewRef and move event handling to view
https://github.com/bitwarden/clients/assets/4648522/90aaa354-6d9d-4a9e-a4c5-7bb5009cb72c

[PM-2538] Settings won't open after leaving screen

---

libs/common/src/billing/models/response/plan.response.ts

```
```
Add the new properties of plan that are related to the secrets manager changes
- **libs/common/src/billing/enums/bitwarden-product-type.enum.ts:** Added a new enum for the bitwarden products
- **libs/common/src/billing/models/response/plan.response.ts** Added a new properties from the server api

[AC-1410] Update the Plan response Model On The Client

---

apps/browser/src/platform/browser/browser-api.ts

```
```
Fix an issue where Firefox's default passkey handler was not being invoked. This was caused by `sendResponse()` in `runtime.background.ts` not getting a response back from the callback being sent in `browser-api.ts`.
- **apps/browser/src/platform/browser/browser-api.ts:** Return the callback in call to `chrome.runtime.onMessage.addListener()` and check that is a boolean value of true.
Demo that it works with the passkey feature flag off:
https://github.com/bitwarden/clients/assets/8926729/1cfb0e73-fcb3-49b6-8ec4-634e440ccf98
- …

[PM-2560] Fix Firefox default passkeys handling

---

.github/CODEOWNERS

```
```
While reviewing https://github.com/bitwarden/clients/pull/5774/ the `team-leads-eng` got pinged as `bitwarden_license/bit-web/src/app/auth/sso/sso.component.html` had no codeowner.
Assigning `bitwarden_license/bit-web/src/app/auth/` to be owned by @bitwarden/team-auth-dev
[Extend auth ownership](https://github.com/bitwarden/clients/commit/2e44f8552781640d88928a86eb416c4c47bf040b)

Extend auth ownership

---

apps/web/src/app/billing/organizations/organization-subscription-cloud.component.ts
apps/web/src/app/billing/organizations/secrets-manager/sm-adjust-subscription.component.html
apps/web/src/app/billing/organizations/secrets-manager/sm-adjust-subscription.component.ts
libs/common/src/billing/models/request/organization-sm-subscription-update.request.ts

```
```
Fix: even if max autoscale limits were disabled (using the checkbox), we were still sending the max autoscale values, which meant the form values were not being saved properly.
Goes with https://github.com/bitwarden/server/pull/3085.
* Main change is in constructing the request object - send null if the limit is disabled.
* However, I also updated the form control names to match the request object (which in turn matches the server), for better consistency in naming. Also because `seatLimit` vs. `limitSeats` was confusing.
* I also deleted the constructor for the request object in favour of manually assigning the properties, given that JS/TS does not have named parameters. …

[AC-1504] Allow SM max autoscale limits to be disabled

---

apps/web/src/app/billing/organizations/organization-subscription-cloud.component.ts
apps/web/src/app/billing/organizations/secrets-manager/sm-adjust-subscription.component.html
apps/web/src/app/billing/organizations/secrets-manager/sm-adjust-subscription.component.ts
libs/common/src/billing/models/request/organization-sm-subscription-update.request.ts

```
```
To be consistent with `Seats`, `MaxStorageGb` and `SmSeats`, `Organization.SmServiceAccounts` will include additional + base plan amount, rather than just the additional (which is how it works today).
On the client side, we just need to subtract the base amount back out of the total we receive from the server, to display the additional to the client.
Pairs with server-side changes in bitwarden/server#3086
This is branched from #5781 so that should be merged first.
- Ensure …

[AC-1488] Store Organization.SmServiceAccounts as total not additional

---

libs/common/src/platform/services/environment.service.ts
libs/common/src/platform/services/state.service.ts

```
```
Properly pass the user's selected region from the global (pre-authenticated) state into the user's account state when they are logged in.  The current implementation does not allow different regions to be selected between accounts on clients that support multiple accounts.
- **state.service.ts:** Added logic to pull region from global state and pass in to the account state.
- **environment.service.ts:** Modified `setRegion()` to clear the environment URLs when a non-self-hosted region is selected.
- Ensure that all UI additions …

[PM-2846][PM-2860] Properly pass region from global to account state

---

apps/web/src/app/core/init.service.ts

```
```
In https://github.com/bitwarden/clients/pull/5764, we changed logic to clear environment URLs when the US or EU region is selected.  Doing so exposed another bug in the initialization of the web client.
- **init.ts:** Properly await the `setUrls` call

Adding missing await to properly set region on web client

---

apps/browser/src/vault/popup/components/vault/add-edit.component.html

```
```
When editing a login item with a non-discoverable passkey, the passkey field does not show.
- **apps/browser/src/vault/popup/components/vault/add-edit.component.html:** Added the read-only field to the add-edit component.

[PM-2932] [Defect] Non-discoverable passkey is missing passkey text field in edit view (Browser)

---

libs/angular/src/auth/components/lock.component.ts

After setting user key, must AWAIT retrieval of user's previous choice to have trusted the device or not. Thanks for identifying this @justindbaur!
```
```

TDE - Defect - LockComp - Fix missing await

---

apps/web/src/app/auth/settings/two-factor-verify.component.html
apps/web/src/app/settings/account.component.ts
apps/web/src/app/settings/security-keys.component.ts

```
```
Fixes for defects found by QA:
- [PM-2928 [Defect] Users without Master Passwords still see `Change Email` in the UI and are prompted for an MP](https://bitwarden.atlassian.net/browse/PM-2928)
- [PM-2929 [Defect/Missed Requirement] Change Encryption Key settings visible for users without Master Password](https://bitwarden.atlassian.net/browse/PM-2929)
- [PM-2930 [Defect] Recovery Code and 2FA related modals contain copy that references a Master Password](https://bitwarden.atlassian.net/browse/PM-2930)
- Ensure that all UI …

[PM-2928] [PM-2929] [PM-2930] Fixes for: [PM-1203] Replace MP confirmation with verification code

---

libs/common/src/platform/services/environment.service.ts

```
```
There is a race condition introduced by a missing `await` when clearing the environment URLs for a non-self-hosted region.  This is causing the web client to not properly initialize its URLs when they are specified on startup (e.g. local development or self-hosted instance).
- **environment.service.ts:** Added missing `await`.

[PM-2846] Added missing await on environment URL reset

---

libs/angular/src/auth/components/base-login-decryption-options.component.ts
libs/common/src/abstractions/devices/devices-api.service.abstraction.ts
libs/common/src/abstractions/devices/devices.service.abstraction.ts
libs/common/src/auth/login-strategies/sso-login.strategy.spec.ts
libs/common/src/auth/models/domain/user-decryption-options/trusted-device-user-decryption-option.ts
libs/common/src/auth/models/response/user-decryption-options/trusted-device-user-decryption-option.response.ts
libs/common/src/platform/models/domain/account.ts
libs/common/src/services/devices/devices-api.service.implementation.ts
libs/common/src/services/devices/devices.service.implementation.ts

```
```
- Remove exist-by-types API call
- Define `HasApprovingDevices` on TDE options
- Use `HasApprovingDevices` to decide whether or not do show approve with other device button
Related server PR: bitwarden/server#3101
- **base-login-decryption-options.component.ts:** Remove code relating to merging the observable from the API call version of getting if they have an approving device and just get it from the TDE options.
- **trusted-device-user-decryption-option.response.ts:** Define new property
- Remove calls that are no longer used.
- If this change has particular **deployment requirements** - notify the DevOps …

[PM-2998] Move Approving Device Check

---

apps/browser/src/_locales/en/messages.json
apps/browser/src/auth/popup/login-decryption-options/login-decryption-options.component.ts
apps/desktop/src/auth/login/login-decryption-options/login-decryption-options.component.ts
apps/desktop/src/locales/en/messages.json
apps/web/src/app/auth/login/login-decryption-options/login-decryption-options.component.ts
apps/web/src/locales/en/messages.json
libs/angular/src/auth/components/base-login-decryption-options.component.ts

```
```
Add account created toast

[PM-2908] [Defect] Missing account creation toast when onboarding to tde org

---

apps/web/src/app/billing/organizations/organization-subscription-cloud.component.html
apps/web/src/app/billing/organizations/organization-subscription-cloud.component.ts
apps/web/src/app/billing/organizations/secrets-manager/sm-subscribe-standalone.component.ts
apps/web/src/app/billing/organizations/secrets-manager/sm-subscribe.component.html

```
```
Fix the SM subscribe component not appearing in the billing tab for free orgs.
Requires https://github.com/bitwarden/server/pull/3114.
**organization-subscription-cloud**
* free orgs do not have a `sub.subscription` object, because that comes from Stripe, and free orgs don't have a Stripe record. Remove that null check in the `showSecretsManagerSubscribe` boolean logic.
* fix up spacing between components
**sm-subscribe**
* fix bug where the Save button was not shown for free orgs
* send zero values for free orgs, it was previously sending the default values (i.e. 1 additional seat) and then throwing an error because a free org cannot buy additional seats
Free org:
Paid org (proof of no regression on layout):
- Please add **unit tests** where it makes sense to do so (encouraged …

[AC-1531] Fix SM subscribe component not showing in free org billing tab

---

libs/angular/src/components/share.component.ts

```
```
Org members with user role cannot move Items with a passkey to the organization, and users can move non-Discoverable/Discoverable Passkey to the org if the opposite type exists in the org vault.
- **libs/angular/src/components/share.component.ts:** `cipherService.getAllFromApiForOrganization` required the user role to have some rights to get all ciphers from an org, used `cipherService.getAllDecrypted` instead since there is no rights restriction and all that is needed is getting ciphers of an organization. Also, prevented the movement of Discoverable/Discoverable Passkey to org if the opposite type exists in the org vault by removing the extra condition to check if a cipher has a `nonDiscoverableId`.
- Please add **unit tests** where it makes sense to do so (encouraged but not …

[PM-3093],[PM-3094] Org Members with User Role Cannot Move Item with Passkey to Organization

---

apps/browser/src/vault/popup/components/vault/add-edit.component.html
apps/browser/src/vault/popup/components/vault/view.component.ts
apps/desktop/src/locales/en/messages.json
apps/desktop/src/vault/app/vault/add-edit.component.html
apps/desktop/src/vault/app/vault/view.component.html
apps/web/src/app/vault/components/vault-items/vault-items.component.ts
apps/web/src/app/vault/individual-vault/vault.component.ts
apps/web/src/locales/en/messages.json
libs/angular/src/components/share.component.ts
libs/angular/src/vault/components/icon.component.ts
libs/angular/src/vault/components/view.component.ts

```
```
**For Non-discoverable passkey:** 
- The passkey field is missing when editing an item.
- There's no dialog warning when cloning a non-discoverable passkey (web and desktop).
**For Discoverable passkey:** 
- The clone button should not be an option on the footer of the vault item view (desktop).
- **apps/browser/src/vault/popup/components/vault/view.component.tst:** Moved dialog to the base class to be shared by browser and desktop.
- **apps/desktop/src/vault/app/vault/add-edit.component.html:** Added passkey view to during edit for non-discoverable passkey.
Also, I added a check to prevent dialog popups on ciphers without non-discoverable passkey. …

[PM-3046] [PM-3047] Defects for discoverable and non-discoverable passkeys on desktop and web

---

apps/web/src/app/vault/individual-vault/add-edit.component.html

```
```
Login items on Web are always showing the Passkey field even when the item does not have a non-discoverable passkey on it.
The bug might have appeared during merge. The two-step passkey view was outside the `ngIf` conditional.

[PM-3148] Passkey Field Always Shows on Login Items

---

libs/importer/src/services/import.service.ts

```
```
On providing an invalid format (csv, xml, json) the importer should throw an error and display "Data is not formatted correctly. Please check your import file and try again."
- **libs/importer/src/services/import.service.ts:** Added a try-catch and on SyntaxError, throw ImportFormatError

[PM-267] Display importFormatError when failed to parse input

---

libs/common/src/platform/models/domain/account.ts
libs/common/src/platform/services/state.service.ts

```
```
Trust wasn't being properly established on chrome-based browsers.
- **state.service.ts** Properly serialize key before saving it
- **account.ts** Change type to match the serialized version of the key

[Defect] In Chromium-based Browser Extensions, Establishing trust after authentication

---

apps/web/src/app/auth/trial-initiation/trial-initiation.component.spec.ts
apps/web/src/app/auth/trial-initiation/trial-initiation.component.ts

```
```
The path for an organization member maintenance is `/organizations/{id}/members`.  It was previously `/organizations/{id}/manage/members`.  When this URL changed, it broke the trial initiation component that navigated to that link when the user clicks "Invite Users.
- **trial-initiation.component.ts:** Changed routing.
- **trial-intiation.component.spec.ts:** Adjusted test to reflect changed route.

[PM-3168] Fix trial initiation "Invite Users" link

---

apps/web/src/app/billing/settings/add-credit.component.ts

```
```
Recent work was finished for the mothership where we added the custom field `region` to PayPal objects so that the mothership could route traffic to the appropriate PayPal IPN endpoint. Everything worked as expected, with the exception of adding credits under the payment method page. When adding credits, we found that the server-side logic was bypassed entirely, and instead, the user was redirected to PayPal where they could add their credits, then they would be redirected back to Bitwarden. This pull request resolved this issue where the `region` custom field isn't being set by the server by getting the user's region setting on the client side, and adding that as a custom field to Paypal.
- **add-credit.component.ts:** Adding the user's region as an additional custom field when …

[AC-1562] Added region custom field to PayPal add credits

---

apps/browser/src/background/main.background.ts
apps/web/src/app/billing/organizations/secrets-manager/sm-subscribe-standalone.component.ts
libs/angular/src/services/jslib-services.module.ts
libs/common/src/admin-console/abstractions/organization/organization-api.service.abstraction.ts
libs/common/src/admin-console/abstractions/organization/organization.service.abstraction.ts
libs/common/src/admin-console/services/organization/organization-api.service.ts
libs/common/src/admin-console/services/organization/organization.service.ts
libs/common/src/vault/services/sync/sync.service.ts

```
```
Updating the organization in clients using the `ProfileOrganizationResponseModel` return from Server `subscribe-secrets-manager`
- **secrets-manager/sm-subscribe-standalone.component.ts:** Return the response from Server `subscribe-secrets-manager` and call upsert in organizationService
- **abstractions/organization/organization-api.service.abstraction.ts:** Modify the interface to return `ProfileOrganizationResponseModel` for `subscribeToSecretsManager` method
- **admin-console/services/organization/organization-api.service.ts:** Modify the implementation to return `ProfileOrganizationResponseModel` for `subscribeToSecretsManager` method …

[AC-1458] Update local organization data after subscribing to Secrets Manager

---

apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.html
apps/web/src/locales/en/messages.json

> Leftover from previous verbiage changes, update remaining `password reset` to `account recovery` within the custom permission list
- **messages.json:** Removed old message and replaced with `manageAccountRecovery`
- **apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.html**: Updated reference to new message

[AC-1542] Update manage password reset label

---

apps/browser/src/auth/popup/login-with-device.component.html
apps/browser/src/auth/popup/login-with-device.component.ts

```
```
`LoginWithDeviceComponent` is used for both TDE and non-TDE device login, which means that we cannot have a hardcoded route. This fix uses location.back for a very simple fix :)

[PM-3210] "View all login options" incorrectly navigates to /login

---

apps/web/src/app/billing/organizations/secrets-manager/sm-adjust-subscription.component.html
apps/web/src/app/billing/organizations/secrets-manager/sm-adjust-subscription.component.ts
apps/web/src/app/billing/organizations/secrets-manager/sm-subscribe.component.html
apps/web/src/locales/en/messages.json

```
```
Fix a bug where the max service account cost estimate included the free service accounts included in the plan.
- rename current getters to include the word `Cost`, to make it clear they're calculating money and not seats/service accounts themselves
- fix the calculation for potential max service account cost
- I also noticed that the "Your plan comes with X service accounts." should be repeated below this input (per the Figma). Split the current string for `additionalServiceAccountsDesc` so that we can reuse the first sentence. Update current places it's used to use the 2 new strings instead of the 1 old one.
Adjust subscription component, showing the additional hint text and correct calculation:
Subscribe component, showing no regression on the hint text:
- Please add **unit …

[AC-1567] Fix max additional service account cost estimate

---

apps/browser/src/autofill/background/notification.background.ts
apps/browser/src/autofill/content/notification-bar.ts
apps/browser/src/autofill/notification/bar.ts
apps/browser/src/background/main.background.ts

The link for the Bitwarden logo on the browser extension notification bar always points to `vault.bitwarden.com`. EU users need it to point to the EU domain (`vault.bitwarden.eu`).
The user's `region` setting is now passed to the nav bar's iframe url query string, where it is retrieved and used to conditionally update the icon anchor `href` as needed.

[PM-2596] Bitwarden logo on notification bar should point to vault domain for the user's region

---

libs/common/src/abstractions/organization-user/organization-user.service.ts
libs/common/src/services/organization-user/organization-user.service.implementation.ts

```
```
In https://github.com/bitwarden/server/pull/3121 we removed the response for the bulk enable SM access endpoint. This PR updates the client accordingly.

[AC-1461] Secrets Manager seat autoscaling cleanup

---

apps/web/src/app/billing/organizations/secrets-manager/sm-adjust-subscription.component.ts

```
```
The "service account limit" cannot be less than the current service accounts in your subscription. However, we were using the _additional_ service accounts as the minimum, rather than the _total_ (additional + base).
- use total service accounts in the validator instead of just the additional

[AC-1570] Fix service account limit validator

---

apps/web/src/locales/en/messages.json
bitwarden_license/bit-web/src/app/auth/sso/sso.component.html

> Update the radio button label from `Trusted device encryption` to `Trusted devices`
- **messages.json**: Updated string key for Crowdin localization changes and changed message to `Trusted devices`
- **../auth/sso/sso.component.html**: Updated string reference

[AC-1537] Update trusted devices radio button label

---

apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.ts
apps/web/src/locales/en/messages.json

> remove leftover `password reset` verbiage from permission required toast and replace with `account recovery`
- **apps/web/src/locales/en/messages.json**: Change message key and replace `password reset` -> `account recovery`
- **.../components/member-dialog/member-dialog.component.ts**: Update toast message reference

[AC-1574] Replace reset password verbiage for permissions required toast

---

apps/web/src/app/vault/individual-vault/vault.component.ts

```
```
Hide low KDF warning for users without a master password
- **apps/web/src/app/vault/individual-vault/vault.component.ts:** Use UserVerificationService to check if a user has a master password to determine if the low KDF warning should be shown.

[PM-3038] Hide low KDF warning for users without a master password

---

apps/web/src/app/vault/components/collection-dialog/collection-dialog.component.ts
apps/web/src/app/vault/individual-vault/vault.component.ts

```
```
Fix issue where members of provider orgs have the option to create collections from individual vault.
- **apps/web/src/app/vault/components/collection-dialog/collection-dialog.component.ts:** Filter out provider orgs from the org dropdown
- **apps/web/src/app/vault/individual-vault/vault.component.ts:** Don't show the New Collection option in the individual vault if a user only belongs to a provider org.

[PM-3031] Remove provider orgs from org dropdown in the collection dialog

---

apps/desktop/src/main/menu/menu.first.ts

```
```
In https://github.com/bitwarden/clients/pull/5894, we added a check that disabled the Settings menu on desktop if the account was not "lockable".  This meant that an account without a master password couldn't access the Settings menu at all.  This is not the desired behavior.
This change reverts this behavior back to the previous check - if the account is locked or there is no active account, the Settings menu is disabled.  If there is an active account and the account is not locked, the Settings menu is enabled.
- **menu.first.ts:** Reverted `enabled` property to be based on whether the account is locked, not whether it is lockable.
- If this change requires a **documentation update** - notify …

[PM-3315] Changed settings menu to be enabled whenever the account is not locked

---

libs/common/src/auth/services/auth.service.ts

```
```
Fix vault locking when quitting the app, even when the vault timeout is set to never
- **libs/common/src/auth/services/auth.service.ts:** Add missing await
https://github.com/bitwarden/clients/assets/8926729/8706272d-59f8-44ca-ad83-7f7b18bebb85

[PM-3219] Vault locking when setting timeout to never

---

apps/browser/src/auth/popup/lock.component.html
apps/browser/src/auth/popup/lock.component.ts
apps/desktop/src/auth/lock.component.html
apps/desktop/src/auth/lock.component.ts
apps/web/src/app/auth/lock.component.ts
libs/angular/src/auth/components/lock.component.ts

```
```
In https://github.com/bitwarden/clients/pull/5894, we added a check that hid the master password input AND the PIN input if PIN was not enabled.
I decided to take the opportunity to remove the confusing `hideInput` property (what input was it hiding and why?) and instead introduce `masterPasswordEnabled` to align with the existing `pinEnabled` property.  The intent of `hideInput` was to hide the UI for master password and PIN entry in the case where users don't have either input.  Previously, that was only with Key Connector, but now we have TDE as well.
Now, we hide that UI if we don't have `pinEnabled` and don't have `masterPasswordEnabled`.
- **lock.component.html:** Replaced `hideInput` with references to `pinEnabled` and `masterPasswordEnabled` (all clients)
- …

[PM-3314] Fixed missing MP prompt on lock component

---

libs/common/src/platform/services/crypto.service.ts

```
```
A CLI that is trying to unlock after upgrade to `tde-key-model-migration` will not have a `UserKey` yet but will have an encrypted crypto symmetric key which is just it's legacy location/name. I made it so that all calls to this method that don't already supply an encrypted user key will be able to fallback to trying to get it from there if the new location does not have it.
- **libs/common/src/platform/services/crypto.service.ts:** Checks the legacy location for it it has what is now called the `UserKey` that has been encrypted with the `MasterKey`. …

[PM-3061] Fix Upgrade CLI Not Finding `UserKey`

---

apps/desktop/src/auth/login/login-with-device.component.html
apps/desktop/src/auth/login/login-with-device.component.ts

Mirror PR #5982 in just simply providing a back action on click which works for all app generated scenarios
```
```
- **apps/desktop/src/auth/login/login-with-device.component.html:** Replace `goToLogin()` with `back()` method
- **apps/desktop/src/auth/login/login-with-device.component.ts:** Replace `goToLogin()` with `back()` method
https://github.com/bitwarden/clients/assets/116684653/4aa2498d-1d08-44bb-a7ea-a3610538858f
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/access …

PM-3210 - TDE - LoginWithDevice - view login options routing fix 

---

apps/browser/src/auth/popup/login-decryption-options/login-decryption-options.component.ts

PM-3355 - TDE - Browser JIT Account Creation - Create user logic still had old logic for simply closing the extension tab but, as we no longer open the login decryption options in a tab, we needed replace that with direct navigation to the vault. 
```
```
- **apps/browser/src/auth/popup/login-decryption-options/login-decryption-options.component.ts:** Replace now deprecated logic w/ simple vault navigation on successful account creation
This was probably an issue across all browser extensions:
Chrome:
https://github.com/bitwarden/clients/assets/116684653/eb59beb3-712e-4562-b7c2-8616c0427d70
Firefox:
https://github.com/bitwarden/clients/assets/116684653/9bcd091a-5cf9-4f47-b9dd-ca478b770d93
- If this …

PM-3355 - TDE - Browser JIT Account Creation Infinite Loop Fix

---

apps/browser/src/popup/settings/settings.component.ts

```
```
Fix a bug where a user could not enable biometrics. This was caused by valueChanges for the biometrics checkbox firing multiple times, interrupting the flow and causing errors.
- **apps/browser/src/popup/settings/settings.component.ts:** Use `distinctUntilChanged` to only get the first emitted value of the form control.

[PM-3353] Fix enabling biometrics

---

apps/desktop/src/services/native-messaging.service.ts

```
```
Fix enabling biometrics breaking for user with no mp
- **apps/desktop/src/services/native-messaging.service.ts:** Use optional chaining on master key because it will be null for users without a master password.

[PM 3347] Fix enabling biometrics breaking for user with no mp

---

libs/common/src/auth/services/device-trust-crypto.service.implementation.ts

```
```
Prevent device trust logic from executing if TDE has been turned off after the user has chosen to trust a device. 
- **libs/common/src/auth/services/device-trust-crypto.service.implementation.ts:** Short circuit `trustDeviceIfRequired` if TDE has been disabled. 

TDE - DeviceTrustCryptoService - Don't trust a device if TDE was turned off

---

libs/angular/src/auth/components/user-verification.component.ts
libs/angular/src/vault/services/password-reprompt.service.spec.ts
libs/angular/src/vault/services/password-reprompt.service.ts
libs/common/src/auth/abstractions/user-verification/user-verification.service.abstraction.ts
libs/common/src/auth/services/user-verification/user-verification.service.ts

```
```
Server PR: https://github.com/bitwarden/server/pull/3184
Similar Tickets:
https://bitwarden.atlassian.net/browse/PM-3373
https://bitwarden.atlassian.net/browse/PM-3375
Use OTP as our form of verification for sessions in which the user has never entered a password. This is done by making the user verification `hasMasterPassword` check more strict by also seeing if the master key hash is in state.
- **libs/common/src/auth/services/user-verification/user-verification.service.ts:** Add method that builds on the `hasMasterPassword` method by also checking for hash.
- **libs/angular/src/vault/services/password-reprompt.service.ts:** Skip reprompt if they have never entered their MP in this session
- **libs/angular/src/auth/components/user-verification.component.ts:** Switch user …

[PM-3356] Fallback to OTP When MasterPassword Hasn't Been Used

---

libs/common/src/auth/services/device-trust-crypto.service.implementation.ts

Reverts bitwarden/clients#6010 b/c the user decryption options doesn't get dynamically updated so this code doesn't do what we thought it would. Also, it broke tests.

Revert "TDE - DeviceTrustCryptoService - Don't trust a device if TDE was turned off"

---

apps/desktop/src/app/app.component.ts
apps/desktop/src/main/menu/menu.account.ts
apps/desktop/src/main/menu/menu.updater.ts
apps/desktop/src/main/menu/menubar.ts

```
```
Hide the Change Master Password menu option on the desktop when a user has no Master Password.
- **app.component.ts:** Moved the `hasMasterPassword` to the `MenuAccount`, since it is dependent upon the active account just like `isLockable` and the other properties on the account.  I also changed from negative ("hide...") to positive "has..." to avoid negation in the conditionals.
- **menu.updater.ts:** Moved the master password property to the `MenuAccount` class.
- **menu.account.ts:** Changed `items()` to dynamically build the item array and only show the `changeMasterPassword` item if the active account has a master password.  This follows the pattern of other menu options with dynamic item lists.
- **menubar.ts:** Use the `hasMasterPassword` property on the active account to …

[PM-3383] Hide Change Password menu option for user with no MP

---

apps/browser/src/manifest.json
apps/browser/src/manifest.v3.json
apps/browser/src/platform/services/browser-platform-utils.service.ts

```
```
Resolves #3829 
Bumping the min version of our next version of Firefox from `42` -> `91`. `91` was chosen because it is the second most recent version of Firefox ESR. This may stop some users from updating to the next version of our browser extension `2023.9.X`. Older versions of the clients are not guaranteed to be supported on newer version of our server. We recommend anyone on an unsupported version of Firefox to update to a supported version.
- **apps/browser/src/manifest{.v3}.json:** Update `strict_min_version`.
- Ensure …

Bump Firefox Min Version

---

apps/web/src/app/admin-console/organizations/settings/account.component.html
apps/web/src/app/admin-console/organizations/settings/account.component.ts
apps/web/src/locales/en/messages.json
libs/common/src/admin-console/abstractions/organization/organization-api.service.abstraction.ts
libs/common/src/admin-console/models/data/organization.data.ts
libs/common/src/admin-console/models/domain/organization.ts
libs/common/src/admin-console/models/request/organization-collection-management-update.request.ts
libs/common/src/admin-console/models/request/organization-update.request.ts
libs/common/src/admin-console/models/response/organization.response.ts
libs/common/src/admin-console/models/response/profile-organization.response.ts
libs/common/src/admin-console/services/organization/organization-api.service.ts

> Add UI within the organization settings for updating the collection management option of limiting collection creation/deletion to Owners/Admins only.
- **account.component.html**: Added UI for the `Collection Management` section.
- **account.component.ts**: Added form group for the new collection management section. Added submit handler that calls the collection management specific API. Updated observable chain to properly refresh `OrganizationResponse` API calls.
- **messages.json**: Added collection management specific strings
- **organization-api.service/abstraction**: Added `updateCollectionManagement` API 
- **organization/data/domain**: Added `limitCollectionCdOwnerAdmin` property
- **organization-collection-management-update.request.ts**: Added request model for collection …

[AC-1374] Limit collection create/delete

---

apps/browser/src/autofill/browser/cipher-context-menu-handler.spec.ts
apps/browser/src/autofill/browser/cipher-context-menu-handler.ts
apps/browser/src/autofill/services/autofill.service.ts

```
```
We introduced a new method on the `userVerificationService` that checks that a user has a master password **and** they have logged in with it (i.e. it is in state).  That is the only way that we can have the MP hash in state to do the reprompt comparison.  
This changes the code from https://github.com/bitwarden/clients/pull/5885 to use this new method.
- **cipher-context-menu-handler.spec.ts:** Changed test to use new method.
- **cipher-context-menu-handler.ts:** Changed to use new method.
- **autofill.service.ts:** Changed to use new method.
- If this change has particular **deployment requirements** - notify …

[PM-3453] Update Autofill service to use new method to check for MP hash

---

apps/browser/src/autofill/content/notification-bar.ts
apps/browser/src/autofill/types/index.ts

Do not display the bitwarden banner on web vault domains (e.g. `vault.bitwarden.eu`)
- Users will not want to see the Bitwarden banner to add their vault login credentials to the same vault they've just logged into, since it serves no practical purpose. Removing the banner in these cases serves as a Quality of Life improvement.
- There is some small risk that the banner enables a haphazard workflow whereby a user could potentially lock themselves out of their vault by, in haste, misunderstanding a banner action.
~The code early return (that would otherwise display the banner) no longer matches the end of the location hostname against `vault.bitwarden.com` but now matches the start of the location hostname against `vault.bitwarden` (ignores TLD)~
User settings are loaded earlier and the …

[PM-2597] Do not show the notification banner on the configured bitwarden vault domain

---

apps/web/src/app/vault/individual-vault/vault.component.ts
apps/web/src/app/vault/org-vault/vault.component.ts

```
```
[PM-3451](https://bitwarden.atlassian.net/browse/PM-3451)
Update password re-prompt logic checks to ensure we have an existing cipher in the add/edit flows to avoid showing the MP re-prompt when creating a new cipher. 
- Resolves issues introduced in #5844 / [PM-2286](https://bitwarden.atlassian.net/browse/PM-2286)
- **apps/web/src/app/vault/individual-vault/vault.component.ts, and apps/web/src/app/vault/org-vault/vault.component.ts** Enhance re-prompt logic checks to ensure that a cipher exists (note: the `editCipherId(...)` method actually is a `createEditCipher(...)` method)
Video of behavior (MP re-prompt should not occur on new cipher creation):
https://github.com/bitwarden/clients/assets/116684653/86d086ad-4a46-4fff-bb4f-31dd1410df81
Video of fixed behavior: …

PM-3451 - Fix MP Re-prompt incorrectly shown for new cipher creation

---

apps/browser/src/popup/services/services.module.ts

```
```
[PM-3456](https://bitwarden.atlassian.net/browse/PM-3456)
Resolve Firefox Browser Extension issue with TDE Admin Auth Request flow 
- The foreground popup must retrieve the long lived background services for the new TDE services
- **apps/browser/src/popup/services/services.module.ts:** 
- Add logic to retrieve `AuthRequestCryptoService` from background
- Add logic to retrieve `DeviceTrustCryptoService` from background
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/acc …

PM-3456 - TDE Admin Auth Req Flow - FF dead object issue 

---

apps/browser/src/autofill/browser/cipher-context-menu-handler.spec.ts
apps/browser/src/autofill/browser/cipher-context-menu-handler.ts
apps/browser/src/autofill/browser/context-menu-clicked-handler.ts
apps/browser/src/autofill/content/message_handler.ts
apps/browser/src/autofill/services/autofill.service.ts
apps/browser/src/background/runtime.background.ts
apps/browser/src/platform/browser/browser-api.ts
apps/browser/src/platform/popup/abstractions/browser-popout-window.service.ts
apps/browser/src/platform/popup/browser-popout-window.service.ts
apps/browser/src/vault/popup/components/vault/view.component.html
apps/browser/src/vault/popup/components/vault/view.component.ts

Password reprompt is not triggering when using hotkey combos or the right-click context menu to autofill, copy the page password, or copy the page TOTP. This PR updates those cases to trigger a new window for password reprompt, a la #5384 
See notes in changes.
https://github.com/bitwarden/clients/assets/1556494/2595cfa3-a45d-4466-8c31-2f49cee14707

[PM-1345] Bugfix - Items with "Re-prompt Masterpassword" fail silently

---

apps/web/src/app/billing/settings/organization-plans.component.ts

```
```
The SM subtotal on the create organization page did not include the cost of SM service accounts.
* remove unnecessary `if` statements (the service account one referred to `hasAdditionalStorageOption` which was incorrect, but also this is handled by the getters, so we can simplify this logic and just remove it altogether)
* pass in `plan` (being the SM plan) to `additionalServiceAccountTotal`, not the `selectedPlan` (which is a PM plan without the required cost info) …

[AC-1599] Fix Secrets Manager cost subtotal when creating an organization

---

apps/browser/src/_locales/en/messages.json
apps/browser/src/auth/popup/login-decryption-options/login-decryption-options.component.html
apps/browser/src/auth/popup/login-with-device.component.html
apps/desktop/src/auth/login/login-decryption-options/login-decryption-options.component.html
apps/desktop/src/auth/login/login-with-device.component.html
apps/desktop/src/locales/en/messages.json
apps/web/src/app/auth/login/login-with-device.component.html
apps/web/src/locales/en/messages.json
bitwarden_license/bit-web/src/app/auth/sso/sso.component.html

```
```
In order for CrowdIn translators to pick up the changes, the message `key` must change.  I've updated the keys for the messages that changed for TDE.
- **messages.json:** Updated the message `key` for `loginInitiated` on desktop and browser (it was already updated on web) and the TDE description message on web
- All other files - Updated the usages of this message to reflect the change.

Updated message keys for CrowdIn to pick them up

---

apps/browser/src/background/main.background.ts
apps/cli/src/bw.ts
apps/web/src/app/core/init.service.ts
libs/angular/src/services/injection-tokens.ts
libs/angular/src/services/jslib-services.module.ts
libs/common/src/services/vault-timeout/vault-timeout.service.ts

Resolve more TDE Feature PR feedback from @djsmith85 (https://github.com/bitwarden/clients/pull/5950#pullrequestreview-1584301576)
```
```

TDE PR Feedback resolutions round 2

---

.vscode/settings.json
apps/browser/src/_locales/en/messages.json
apps/desktop/src/locales/en/messages.json

```
```
This PR adds CL i18n entries to desktop and browser `messages.json` so components render properly in all clients.
I also updated `.vscode/settings.json` to exclude all locales except english in vscode search results.

[CL-120] add CL i18n entries to desktop and browser

---

libs/components/src/navigation/nav-group.component.html
libs/components/src/navigation/nav-item.component.html
libs/components/src/navigation/nav-item.stories.ts

```
```
`bit-nav-item` uses `slot-start` and `slot-end` for its content projection selectors. 
To be consistent with the pattern we are starting to use in the CL, these were renamed to target `slot="start"` and `slot="end"`.

[CL-119] rename slots in nav-item

---

apps/browser/src/popup/app-routing.module.ts

```
```
The web and desktop client usually direct to the vault-page on login but the browser redirects to the tabs-tab showing the favourites and cards
- **apps/browser/src/popup/app-routing.module.ts:** Change the redirect-route for browser login from `/tabs/vault` to `/tabs/tabs`

[PM-3590] Fix route in redirectGuard for browser login

---

libs/common/src/admin-console/abstractions/organization/organization.service.abstraction.ts

```
```
In the Admin Console, members with “Manage groups” permissions can view the Vaults tab. They should only be able to view the Groups tab.
- **libs/common/src/admin-console/abstractions/organization/organization.service.abstraction.ts:** Removed checking `org.canManageGroups` in `canAccessVaultTab` permission check

[AC-1552] Fixed issue where Org members with "Manage groups" permissions can view the Vault tab

---

libs/angular/src/services/jslib-services.module.ts
libs/common/src/auth/login-strategies/sso-login.strategy.spec.ts
libs/common/src/auth/login-strategies/sso-login.strategy.ts
libs/common/src/auth/services/key-connector.service.ts

```
```
Addresses several issues with handling Key Connector in connection with TDE.
- `KeyConnectorService` was not being properly instantiated due to 2 additional dependencies defined in `JslibServicesModule`.
- Prior to TDE, the identity token response would not include the `KeyConnectorUrl` if the user has a master password. This meant that we could just check for the presence of that property in order to ascertain whether the user has a blank master password or not.  However, post-TDE, the identity token will _always_ contain a `KeyConnectorUrl` in the `UserDecryptionOptions` property - regardless of whether the user has a master password or not.  This PR adds the check for the user having a master password to the client and only attempts to set the `masterKey` from Key Connector if …

[PM-3533] Support onboarding Key Connector users with existing master passwords

---

apps/web/src/app/billing/settings/organization-plans.component.html

```
```
This PR is purposed to fix the issue where the Cancel button was misaligned when a free user is upgrading their org plan. In the Billing > Subscription section of the Settings on the Org page, the Cancel button was appearing below the Submit button instead of aligning with it in OrganizationPlansComponent. This issue has been fixed in this PR.
- **organization-plans.component.html:** Updated the cancel button to use the `bitButton` component to match the styling of the submit button
Before:
After:
- Ensure that all UI additions …

[PM-264] When a free user is upgrading their org plan, the Cancel button is misaligned

---

.github/workflows/release-desktop.yml

```
```
This PR fixes the logic in the `Release Desktop` workflow to make sure that jobs only run when the specified input box is checked.  The workflow was running jobs regardless of the input box value.
- **.github/workflows/release-desktop.yml:** Add `== 'true'` to `if` keys to make sure the jobs run when the proper input box is selected.

Release Desktop Workflow - Fix job run logic

---

apps/browser/src/platform/popup/browser-popout-window.service.ts

This ensures that if multiple single-action windows are opened (e.g. reprompt keyboard shortcut bug), the extra windows will be dismissed right away
Important note: This does _not_ address _preventing_ multiple/excess window generation. This PR is for handling those scenarios within the browser popout service by closing excess windows. Additional upstream work around this (addressing other cases and root causes) will be addressed in followup tasks.
See notes in the comments

[PM-3588] Close duplicate single-action windows

---

apps/cli/src/program.ts
apps/cli/src/tools/generate.command.ts
apps/cli/src/utils.ts

```
```
This PR aims to add missing password generation options to the CLI. Options like **Minimum numbers**, **Minimum special**, and **Avoid ambiguous characters** are present in clients like `desktop` and `browser`, but not in the `cli`.
Since the options are already accepted by the `password-generation` service, the only changes made were in the following files:
- `program.ts` - Accept the `minNumber`, `minSpecial`, and `ambiguous` options in the CLI
- `generate.command.ts` - Accept and validate the options passed to the program and forward them to the `generatePassword` function from the `password-generation` service.
- `utils.ts` - Also took the chance to extract two new utils - `convertNumberOption` and `convertStringOption` to use when parsing the input options.
- Please add …

[PM-3326] [CLI] Add minNumber, minSpecial and ambiguous password generation options

---

libs/common/src/auth/login-strategies/login.strategy.spec.ts
libs/common/src/auth/login-strategies/login.strategy.ts
libs/common/src/auth/login-strategies/sso-login.strategy.spec.ts
libs/common/src/auth/login-strategies/sso-login.strategy.ts
libs/common/src/platform/models/domain/account.ts

```
```
Prior to TDE, the user's "decryption options" were implied based on the presence or absence of the `keyConnectorUrl` in the token response.  Post-TDE, we have build an explicit `UserDecryptionOptions` property on the response from the server.  However, clients must be able to handle pre-TDE server versions for our self-hosted customers who do not upgrade. 
This has been done by using the `keyConnectorUrl` to initialize the `hasMasterPassword`.  The key code to look at on the server is [here](https://github.com/bitwarden/server/blob/5f4a303180ea4f6caf9c5ed50c6c3858e678e18b/src/Identity/IdentityServer/CustomTokenRequestValidator.cs#L104), in the pre-TDE server-side code.  If the user has a master password, the `keyConnectorUrl` will **not** be in the response.  This allows us to …

[PM-3758] Handle user decryption options from pre-TDE server response

---

libs/common/src/admin-console/abstractions/organization/organization.service.abstraction.ts
libs/common/src/admin-console/models/domain/organization.ts

```
```
As part of work for https://github.com/bitwarden/server/pull/3233 it was identified the need to block access to the Organization tab if the user's only active permission is to view assigned collections.
- **libs/common/src/admin-console/abstractions/organization/organization.service.abstraction.ts:** Updated access to the vault tab permission to only check if the user can view all collections
- **libs/common/src/admin-console/models/domain/organization.ts:** Updated the permission check to view all collections in an organization to not consider if the user can create new collections …

[AC-1612] Disabled access to the Organization Vault tab if the user only has access to assigned collections

---

apps/browser/src/platform/browser/browser-api.ts
apps/browser/src/popup/services/popup-utils.service.ts
libs/common/src/platform/misc/utils.ts
libs/common/src/vault/api/fido2-key.api.ts
libs/common/src/vault/models/data/fido2-key.data.ts
libs/common/src/vault/models/domain/fido2-key.spec.ts
libs/common/src/vault/models/domain/fido2-key.ts
libs/common/src/vault/models/domain/login.spec.ts
libs/common/src/vault/models/view/fido2-key.view.ts
libs/common/src/vault/models/view/login.view.ts
libs/common/src/vault/services/fido2/fido2-authenticator.service.spec.ts
libs/common/src/vault/services/fido2/fido2-authenticator.service.ts
libs/common/src/vault/services/fido2/fido2-client.service.spec.ts
libs/common/src/vault/services/fido2/guid-utils.ts

[PM-3660] Address PR feedback

---

libs/common/src/vault/services/cipher.service.spec.ts
libs/common/src/vault/services/cipher.service.ts

```
```
Fix org admins being unable to clone a vault item from org vault to individual vault## Code changes
- **libs/common/src/vault/services/cipher.service.ts:** Only call postCipherAdmin if the orgId on a cipher is not null
- **libs/common/src/vault/services/cipher.service.spec.ts:** Add a test to cover new condition
https://github.com/bitwarden/clients/assets/8926729/c8fe90f0-f4ad-4e55-9f97-a23945c77084

[PM-3505] Fix org admins being unable to clone a vault item from org vault to individual vault

---

bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/access/access.service.ts
libs/common/src/auth/services/device-trust-crypto.service.implementation.ts
libs/common/src/auth/services/device-trust-crypto.service.spec.ts
libs/common/src/auth/services/key-connector.service.ts
libs/common/src/platform/abstractions/crypto-function.service.ts
libs/common/src/platform/services/crypto.service.ts
libs/common/src/platform/services/web-crypto-function.service.spec.ts
libs/common/src/platform/services/web-crypto-function.service.ts
libs/common/src/tools/send/services/send.service.ts
libs/node/src/services/node-crypto-function.service.spec.ts
libs/node/src/services/node-crypto-function.service.ts

```
```
Uses generateKey in subtle crypto get generate material used either directly as keys or used to generate keys for aes.

[PM-3732] Use subtle to make aes keys

---

apps/browser/src/vault/fido2/content/page-script.ts

```
- [ X ] New feature development
```
Some sites will prompt you to use your passkey the moment you navigate to their sign-in page. Our objective is to gracefully fail that request, and the user will have to take some form of action (clicking use passkey, typing in username, etc) to use their passkey. 
page-script has been updated to look for an `mediation` key in the `options` argument for `navigate credentials get`. It will throw an error if the mediation value is `optional`
I found two sites that will prompt for using an existing passkey on load. With the new `mediation optional` logic the users will have to take action to use their passkeys. Those sites are [Kayak](https://www.kayak.com/) and [BestBuy](https://www.bestbuy.com/)
Kayak after the user submits their email
BestBuy after …

[PM-1722] gracefully fail if site prompts user for passkey on load

---

apps/desktop/src/index.html
apps/desktop/src/scss/environment.scss
apps/desktop/src/vault/app/vault/vault.component.ts

```
```
The DUO 2fa iframe is not clickable on macOS. This seems to be related to the `-webkit-app-region: drag` that is turned on for the `layout_frontend`. Since we now have a proper drag handle in the top bar we should be able to safely disable this.
Resolves https://github.com/bitwarden/clients/issues/5680
- **apps/desktop/src/scss/environment.scss:** Remove `webkit-app-region: drag` for `layout_frontend`.
- **apps/desktop/src/vault/app/vault/vault.component.ts**: Remove `layout_frontend` since it's no longer used.
- Ensure that …

[PM-2643] Resolve DUO iframe not being clickable

---

apps/browser/src/vault/fido2/content/messaging/messenger.ts

```
```
Add a window origin check on the `postMessage` implementation.
- **messenger.ts:** Modified listener to only `next()` the message if the origin matches the window origin.  This is an approach to resolve the security concerns documented [here](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage#security_concerns).

[PM-3820] Window Messaging Fix;

---

apps/browser/src/background/main.background.ts
apps/browser/src/platform/background/service-factories/config-service.factory.ts
apps/browser/src/vault/background/service_factories/cipher-service.factory.ts
apps/cli/src/bw.ts
libs/angular/src/services/jslib-services.module.ts
libs/common/src/platform/abstractions/config/config.service.abstraction.ts
libs/common/src/platform/services/config/config.service.ts
libs/common/src/vault/services/cipher.service.spec.ts
libs/common/src/vault/services/cipher.service.ts

Updated version check.
```
```
The `CipherService` had a dependency on `ConfigApiService` instead of `ConfigService`.  What that meant is that every encryption operation made a call to the server to retrieve the server version.
This change updates to depend on the `ConfigService` instead, with a new method on the `ConfigService` to do the server version comparison instead of relying on the consuming service to do so.
- **config.service.ts:** Added new method for consumers to check server version compatibility for a desired feature.
- **config.service.abstraction.ts:** New method definition.
- **cipher.service.ts:** Updated to reference the new method on `ConfigService`.  Also updated to short-circuit the need to call `ConfigService` at all to only occur if the feature flag is on.
- Other …

[PM-2814] Add ConfigService to CipherService

---

apps/browser/src/tools/popup/send/send-add-edit.component.html

```
```
The popout warning message was showing when the send had the type of file and text selected, it should show only to file.
- **send-add-edit.component.html:** Using the type instead the send.type as validation

[PM-3822] Only show popout warning on file SendAddEdit

---

libs/angular/src/vault/components/password-reprompt.component.ts
libs/common/src/auth/services/user-verification/user-verification.service.ts

```
```
Fix Master Password reprompt erroring when a user has logged in with biometrics by getting or deriving the key when the reprompt is submitted.
- **libs/angular/src/vault/components/password-reprompt.component.ts:** Get or derive the key before comparing the master password hashes. 

[PM-3600] Try to get key in master password reprompt check

---

apps/web/config/cloud.json
apps/web/config/qa.json

I was testing https://github.com/bitwarden/clients/pull/6261 and I realized that `ENV=cloud npm run build:oss:watch` does not work. It fails with:
```
[webpack-cli] TypeError: Cannot read properties of undefined (reading 'upgrade')
```
This fixes the problem.

[PM-3881] Fix ENV=cloud npm run build:oss:watch

---

libs/common/src/vault/abstractions/fido2/fido2-authenticator.service.abstraction.ts
libs/common/src/vault/api/fido2-key.api.ts
libs/common/src/vault/models/data/cipher.data.ts
libs/common/src/vault/models/data/fido2-key.data.ts
libs/common/src/vault/models/domain/cipher.ts
libs/common/src/vault/models/domain/fido2-key.spec.ts
libs/common/src/vault/models/domain/fido2-key.ts
libs/common/src/vault/models/domain/login.spec.ts
libs/common/src/vault/models/request/cipher.request.ts
libs/common/src/vault/models/response/cipher.response.ts
libs/common/src/vault/models/view/cipher.view.ts
libs/common/src/vault/models/view/fido2-key.view.ts
libs/common/src/vault/services/cipher.service.ts
libs/common/src/vault/services/fido2/fido2-authenticator.service.spec.ts
libs/common/src/vault/services/fido2/fido2-authenticator.service.ts

```
```
Server PR here: https://github.com/bitwarden/server/pull/3261
- Add `discoverable` property to Fido2Key
- Remove handling of standalone `Fido2Key` cipher type
**Note:** This PR does not remove the actual `CipherType.Fido2Key` type, since UI views and components still rely on it. The removal will be part of [PM-3810 Storage v2 - Unify the UI when viewing an item that has a passkey (clients)](https://bitwarden.atlassian.net/browse/PM-3810) …

[PM-3807] Store all passkeys as login cipher type

---

libs/common/src/platform/abstractions/config/config.service.abstraction.ts
libs/common/src/platform/services/config/config.service.ts
libs/common/src/vault/services/cipher.service.spec.ts
libs/common/src/vault/services/cipher.service.ts

```
```
Refactored the new `checkServerMeetsVersionRequirement` to return an observable instead of a promise, as recommended by @eliykat here: https://github.com/bitwarden/clients/pull/6241#discussion_r1320973020.
- **config.service.ts:** Refactored to return an observable.
- **cipher.service.ts:** Refactored to use `firstValueFrom()`.

Updated checkServerMeetsVersionRequirement to use observable

---

libs/common/src/vault/abstractions/cipher.service.ts
libs/common/src/vault/services/cipher.service.spec.ts
libs/common/src/vault/services/cipher.service.ts

```
```
We removed the `key` property from the `CipherView` in https://github.com/bitwarden/clients/pull/6241/commits/242570cf3bd55052cf250f5ec3850137ac927e37.  Doing this broke key rotation, as the assumption was that the encryption key for the cipher key would always be the user's encryption key.  This isn't valid on key rotation, when it's the new encryption key that should be used.
Note: I've created https://bitwarden.atlassian.net/browse/PM-3899 to capture the work to make it such that we don't need to re-encrypt the entire cipher on key rotation any more, once we have removed the cipher key encryption feature flag and are confident that all clients are using the new method.
- **cipher.service.ts:**
- Moved the cipher model update and password history update to their own methods to …

[PM-2814] Handle key rotation missing key

---

apps/desktop/src/app/tools/send/add-edit.component.ts
libs/angular/src/tools/send/add-edit.component.ts

```
```
The password was being set on edit, this was caused because if we send "" the password will be set to an empty string so we are sending it null to avoid it being set
- **send/add-edit.component.ts:** Clearing the password on the send object if it is empty and using that property in all cases

[PM-3878] Setting send password to null if it is empty

---

libs/components/src/form-field/error-summary.stories.ts
libs/components/src/utils/i18n-mock.service.ts

```
```
Add support for placeholders in the i18n-mock. Since we don't provide full message objects this works slightly different in that you use the expanded form, i.e. `__$1__`.

[CL-128] Support placeholders in i18n mock

---

.github/workflows/chromatic.yml
libs/components/src/styles.css

```
```
Rem sizes are calculated based on the font-size defined in `html`. To maintain better consistency across storybook and the web vault we should use the same sizes. This changes storybook to also use `font-size: 14` in `html`.

[CL-60] Set font-size on html

---

apps/browser/src/vault/popup/components/vault/add-edit.component.html
apps/browser/src/vault/popup/components/vault/view.component.html
apps/desktop/src/vault/app/vault/add-edit.component.html
apps/desktop/src/vault/app/vault/view.component.html
apps/web/src/app/vault/individual-vault/add-edit.component.html
apps/web/src/app/vault/individual-vault/vault.component.ts
libs/angular/src/components/share.component.ts
libs/angular/src/vault/components/add-edit.component.ts
libs/angular/src/vault/components/view.component.ts
libs/common/src/models/api/login.api.ts
libs/common/src/models/export/login.export.ts
libs/common/src/vault/models/data/login.data.ts
libs/common/src/vault/models/domain/cipher.spec.ts
libs/common/src/vault/models/domain/login.spec.ts
libs/common/src/vault/models/domain/login.ts
libs/common/src/vault/models/request/cipher.request.ts
libs/common/src/vault/models/view/login.view.ts
libs/common/src/vault/services/cipher.service.ts
libs/common/src/vault/services/fido2/fido2-authenticator.service.spec.ts
libs/common/src/vault/services/fido2/fido2-authenticator.service.ts

```
```
https://github.com/bitwarden/server/pull/3268
Refactor how passkeys are stored so that we may support multiple passkeys in a single login item in the future.

[PM-3807] Store passkeys as array

---

libs/angular/src/tools/send/add-edit.component.ts

```
```
On desktop the HideEmail checkbox is showing as inactive on some cases when it is selected and has the do not HideEmail policy. When selected should always be clickable, this fixes it.
Moved the verification to validate if the HideEmail box is active to the `UpdateFormValues` method so that it is called on Send change at desktop

[PM-3928] HideEmail enable validation moved to UpdateFormValues

---

apps/browser/src/popup/scss/base.scss

```
```
This PR fixes a Chrome bug that shrinks the popover window width to 25px when both of the following are true:
- `position: fixed` is on the root element
- (This style is applied by `.cdk-global-scrollblock` when a dialog is opened with the `DialogService`)
- Zoom is higher that 100% in the browser appearance settings
- `.cdk-global-scrollblock` was overridden to not apply `position: fixed` on `html`. This means that users on the Chrome extension _who have zoom set to above 100%_ will be able to scroll when dialogs are open (since there is overflow on the `html` element after zooming).
Bug:
https://github.com/bitwarden/clients/assets/17113462/63e37586-34a3-4e8a-89dc-16fe4212e2a7
Fixed:
https://github.com/bitwarden/clients/assets/17113462/a9b60e33-c41e-4eef-ab82-942764cb9c80
- …

[PM-3894] fix popover size when dialog is open and Chrome is zoomed

---

apps/browser/src/platform/polyfills/zone-patch-chrome-runtime.ts
apps/browser/src/popup/app.component.ts
apps/browser/src/popup/polyfills.ts

```
```
This simplifies the browser by removing the need to call `ngZone.run(() => {...});` when using  `BrowserApi.messageListener` 
Based on the following PR-review discussion https://github.com/bitwarden/clients/pull/5989#discussion_r1310129598
- **zone-patch-chrome-runtime.ts:** Zone.js patch functions. Inspired by [zone.js media query patch](https://github.com/angular/angular/blob/690c8325cdb94735dff8b7494a27bf9ea6f4b80a/packages/zone.js/lib/browser/webapis-media-query.ts)
- **polyfills.ts:** Make sure to import the patches so they run before angular zone is created
- **app.component.ts:** Remove calls to `ngZone` which are no longer needed …

[PM-3783] Add zone.js support for `chrome.runtime.onMessage`

---

libs/angular/src/tools/send/add-edit.component.ts

```
```
On desktop when syncing the vault, after a change on the Sends Option policies, it doesn't properly enables or disables the send currently open.
- **send/Add-Edit.component.ts:** Added check to only disable if the hideEmail is unchecked and enabling on all the other cases.

[PM-3982] Improved validation on send hide email policy subscriber
