.github/workflows/version-bump.yml
```
```
This PR adds a check to the version input to make sure it is newer than the current version for each client that is supposed to be bumped.
- **.github/workflows/version-bump.yml:** Add check for each client to make sure input version is newer. Make sure PR is not created if not run from `master`.
=> Update Version Bump workflow - Add version input protection

apps/browser/src/popup/app.module.ts, apps/browser/src/popup/settings/about.component.html, apps/browser/src/popup/settings/about.component.ts, apps/browser/src/popup/settings/settings.component.ts
```
```
Migrates the browser's `AboutComponent` to use a CL simple dialog and be a standalone component. 
=> [PM-2415] migrate AboutComponent to CL

libs/components/src/link/link.directive.ts
```
```
Fixes a bug where the focus-visible outline wasn't visible on `bitLink`
- **libs/components/src/link/link.directive.ts:** Remove default ring color of `tw-ring-text-contrast`. This color is the same as the main bg color.
=> [CL-89] fix focus-visible outline in bitLink

apps/cli/src/bw.ts, apps/cli/src/platform/services/cli-config.service.ts, libs/common/src/platform/services/config/config.service.ts
```
```
`ConfigService` uses rxjs `timer` to fetch an updated `ServerConfig` at regular intervals.
`timer` uses setTimeout/setInterval under the hood, which prevents the node process from exiting when the command is finished. Cli should never be alive long enough to use the timer, so I've just overridden it in a subclass with `NEVER` (which is an observable that never emits or completes, basically just a stand-in).
One alternative solution is to use the `takeUntil(this.destroy$)` pattern, however we don't currently have that pattern in CLI and I didn't think it was worth introducing it here; maybe we reconsider that if we start using more timers.
This is targeting feature because we don't use configService in CLI yet in `master`.
- …
=> [PM-3867] Don't use rxjs timer in CLI ConfigService

apps/browser/src/autofill/services/autofill.service.spec.ts, apps/browser/src/autofill/services/autofill.service.ts
```
```
Remove injection of autofill scripts from `allFrames` into the specific `frameId` that is associated with the sender tab.
Validated that this resolved issues present within https://www.seznam.cz/ when scrolling ajax content.
Resolves https://github.com/bitwarden/clients/pull/6348
- **apps/browser/src/autofill/services/autofill.service.ts:** Adjusting script injection to take into account the specific frameId for a given tab sender. Remove `allFrames` declaration that facilitated injection in all frame contexts.
=> [PM-4011] Remove Autofill Injection in All Frames

.github/workflows/release-desktop.yml
```
```
This PR reverts a change I made in a previous PR shortening `if` key values to `inputs.INPUT_NAME` instead of `github.event.inputs.INPUT_NAME`.  This broke the workflow and would not execute the proper steps.
=> Release Desktop workflow - Revert change to if key's

apps/web/src/app/vault/individual-vault/bulk-action-dialogs/bulk-delete-dialog/bulk-delete-dialog.component.ts, libs/common/src/abstractions/api.service.ts, libs/common/src/models/request/collection-bulk-delete.request.ts, libs/common/src/services/api.service.ts
> Tech Debt - cleaning up out of scope changes from a previous PR.  Removing the `organizationId` property from the `collection-bulk-delete.request` model as it is no longer necessary for the API controller operations.
- **.../bulk-delete-dialog/bulk-delete-dialog.component.ts**: Updated call to api to match new method signature
- **libs/common/src/abstractions/api.service.ts**: updated interface with new method signature
- **libs/common/src/models/request/collection-bulk-delete.request.ts**: updated request model by removing `organizationId` 
- **libs/common/src/services/api.service.ts**: updated service call with updated method signature and changed organization id source to passed in parameter.
- If …
=> [AC-1649] Remove organizationId from collection-bulk-delete.request

apps/browser/src/popup/scss/popup.scss, apps/desktop/src/scss/styles.scss
```
```
Desktop and browser don't render `bit-select` or `bit-multi-select` properly. This is caused by the `ng-select` styles not being imported on those clients.
https://github.com/bitwarden/clients/assets/17113462/abb4da4b-65fd-4395-b4e5-0d20c3e4c907
=> [CL-130] fix select styles on desktop & browser

libs/components/src/form-field/form-field.stories.ts, libs/components/src/input/input.directive.ts
```
```
Use a darker background when a `bitInput` is readonly. This only applies to `bitInput` on `input` and `textarea`, but not `select`, since it relies on the HTML `readonly` attribute.
- **libs/components/src/form-field/form-field.stories.ts:** Add "Readonly" story
- **libs/components/src/input/input.directive.ts**: update styles
=> [CL-113] add readonly styles to bitInput

libs/common/src/vault/models/view/fido2-key.view.ts
```
```
Converting from `Date` to IsoString was throwing an error because I missed a spot where conversion to Date should happened.
=> [PM-4036] Fixed iso string issue where the date wasn't converted back to Date

apps/web/src/app/vault/org-vault/add-edit.component.ts, libs/common/src/vault/abstractions/cipher.service.ts, libs/common/src/vault/services/cipher.service.ts
```
```
When sharing a cipher with an org, the key we need to use to decrypt the cipher key is different than the key we need to use to re-encrypt it.  We need to decrypt the key using the individual user's key and encrypt it using the org key.
In order to make that intent explicit, I've added a new parameter to `encrypt()` to pass in the key we want to use to decrypt the cipher key.  Previously we had a `key` parameter, and it represented (and still does represent) the key used to encrypt either the cipher or the cipher key (depending on if cipher key encryption is enabled).  The new parameter represents the key used to decrypt the cipher key.  Currently, the only use case is for sharing with an org.
- Please add **unit tests** …
=> [PM-3978] Handle sharing with org with cipher key encryption

libs/common/src/models/export/fido2key.export.ts
```
```
Editing a login item with passkeys returns **key.creationDate.toISOString** is not a function error in the CLI.
=> [PM-4045] Get error returned when editing an item with a passkey in the CLI

apps/web/src/app/billing/settings/tax-info.component.ts
```
```
[PM-263](https://bitwarden.atlassian.net/browse/PM-263)
Currently, unchecking the "Include VAT/GST Information (optional)" does not prevent the app from sending already populated VAT/GST info to Stripe. Therefore, the change is not propagated and when the page is reloaded, the VAT/GST information is the same as before. 
This PR updates that logic to clear VAT/GST logic when that checkbox is unchecked.
- **tax-info.component.ts:** If `taxInfo.includeTaxId` is `false`, clear out all the VAT/GST information in the request we send to Stripe.
https://github.com/bitwarden/clients/assets/144709477/a509cc6e-c96d-4851-b956-2f506f022030 …
=> Clear VAT/GST Info when Box is Unchecked [PM-263]

libs/common/src/vault/models/data/collection.data.ts, libs/common/src/vault/models/domain/collection.spec.ts, libs/common/src/vault/models/domain/collection.ts, libs/common/src/vault/models/response/collection.response.ts, libs/common/src/vault/models/view/collection.view.ts
```
```
The manage property was added to the `CollectionAccessSelectionView`, but it was never added to the primary collection view even though it is being sent down from the server.
We need to add the manage property to both `CollectionDetailsResponse` and `CollectionView` models in the Clients (used in sync data) so it can be used for future client side work.
There are no server changes as it the flag is already being [sent down in the sync data](https://github.com/bitwarden/server/blob/4e7b9d2edd0d1a70df5cc6a1b634f4f7a30af4e9/src/Api/Vault/Models/Response/SyncResponseModel.cs#L38-L39). …
=> [AC-1680] Add manage property to collection view and response models

apps/web/src/app/billing/organizations/organization-subscription-cloud.component.html, apps/web/src/app/billing/organizations/organization-subscription-cloud.component.ts, apps/web/src/app/billing/settings/user-subscription.component.html, apps/web/src/app/billing/settings/user-subscription.component.ts, apps/web/src/locales/en/messages.json, libs/common/src/billing/models/response/organization-subscription.response.ts, libs/common/src/billing/models/response/subscription.response.ts
```
```
[JIRA Ticket](https://bitwarden.atlassian.net/browse/AC-1657)
The purpose of this PR is to consume newly added discount information from the Subscription API endpoints and use the existence of discounts to conditionally display new copy under the Subscriptions tables.
- **messages.json:** Add new translation entries used to build up the copy being added under the Subscriptions tables.
- **subscription.response.ts:** Add a new `BillingCustomerDiscount` class. Add it as a field to the `SubscriptionResponse`. Populate the discount using the `Discount` response property.
- **organization-subscription.response.ts:** Add the `BillingCustomerDiscount` as a field to the `OrganizationSubscriptionResponse` class. Populate the discount using the `Discount` response property.
- …
=> Conditionally display new copy under subscriptions table [AC-1657]

apps/browser/src/vault/popup/components/vault/view.component.html
```
```
To create parity with other clients, we need to move the “Passkey” field to be above the “Verification Code (TOTP)” field when viewing an item in browser. The “Edit Item” screen already has this layout, so we just need the View screen to match.
=> [PM-4146] Move Passkey Above Verification Code when Viewing an Item

libs/common/src/vault/services/fido2/fido2-client.service.ts
```
```
This issue arose from this [PR](https://github.com/bitwarden/clients/pull/6322), which refactors the client service. The `rpId` constant, defaulting to the domain when absent, wasn't forwarded to the `mapToMakeCredentialParams` function, leading to an error when creating a passkey.
=> [PM-4051] Cannot save passkey on Shopify

libs/common/src/vault/models/data/collection.data.ts, libs/common/src/vault/models/domain/collection.spec.ts, libs/common/src/vault/models/response/collection.response.ts
```
```
As discussed [in this comment](https://github.com/bitwarden/clients/pull/6417#discussion_r1337930412), `collection.hidePasswords` is included in sync data from the server, but isn't set by the response model on the client. This means it won't flow through to the view model.
This PR fixes this by adding the missing properties in the chain of response -> data -> domain -> view models.
CC @djsmith85 you mentioned that this property is not sent by the server, however your link was to the public API. The private sync endpoint does appear to include this data.
No QA required as this is not currently used, although we expect it to be in the near future.
- Please add **unit tests** where it makes sense to do so (encouraged but not …
=> [AC-1689] Add hidePasswords property to collection data and response models

.github/workflows/build-browser.yml, .github/workflows/build-cli.yml, .github/workflows/build-desktop.yml, .github/workflows/build-web.yml, .github/workflows/chromatic.yml, .github/workflows/lint.yml, .github/workflows/release-desktop-beta.yml, .github/workflows/test.yml
```
```
Pull the node version from the `.nvmrc` file and use it in every `setup-node` action.
=> [DEVOPS-1572] Update JS workflows to Node version 18

apps/web/src/app/vault/components/vault-items/vault-items.component.html, libs/angular/src/directives/fallback-src.directive.ts, libs/components/src/menu/menu-trigger-for.directive.ts
```
```
This PR disables view recycling in `vault-items`. This prevents a bug where the overlay menu would reattach onto new elements after scrolling in a virtual scroll viewport.
While testing this change on the `vault-items` story in Storybook, a bug was also found with the `fallback-src` directive. If the fallback itself is missing, the directive will request the resource in an infinite loop. This was fixed by only trying to set the fallback image once.
- Ensure that all UI …
=> [CL-104] fix overlay + virtual scroll view recycling bug

apps/browser/src/auth/popup/login.component.ts, apps/browser/src/auth/popup/two-factor.component.ts, apps/browser/src/popup/app-routing.module.ts
```
```
Routing logic is no longer needed on `login` and `2fa` components as we decided to default to the browser implementation if not logged in.
=> Remove routing logic from login and 2fa

libs/angular/src/vault/components/add-edit.component.ts
```
```
Fixed bug in which passkey was being displayed on cloned item but not saved with it.
- **add-edit.component.ts:** Removed passkey on `load()` and not on `submit()` so that it isn't displayed in the UI.
=> [PM-4271] Move clearing of passkey when cloning from submit to load

apps/browser/src/vault/popup/components/vault/add-edit.component.ts
```
```
Previously, when using the `+` button for creating a cipher with a passkey item, the cipher item was initially created and then, if user verification was required, the user was prompted for the master password. With this update, the master password prompt is presented before the cipher creation.
https://github.com/bitwarden/clients/assets/13024008/62a12ef4-18dc-492a-9c7f-a349fe12a082
=> [PM-4226] Add Cipher With Passkey Flow Change

apps/browser/src/autofill/content/autofill.js, apps/browser/src/autofill/services/insert-autofill-content.service.spec.ts, apps/browser/src/autofill/services/insert-autofill-content.service.ts, apps/browser/src/vault/popup/components/vault/view.component.ts
```
```
This revisits a new fix for https://github.com/bitwarden/clients/pull/6280, which introduced a bug that is being reverted to avoid potentially making it to release without a resolution. This PR re-approaches the solve for that issue.
Do a check of the target tab URL to see if it changed during master password reprompt, before executing the form fill.
Original issue:
https://github.com/bitwarden/clients/assets/1556494/d7c6e4a9-746f-44d4-8a6e-8b8a83c6e880
=> [PM-4127] Bugfix - Check original target tab URL before executing deferred action due to reprompt

apps/browser/src/vault/fido2/content/page-script.ts, libs/common/src/vault/services/fido2/fido2-client.service.spec.ts, libs/common/src/vault/services/fido2/fido2-client.service.ts
```
```
This bug was introduced from PR  #6057. A verification was added to the client's assertion to prevent passkeys from being requested within iframes.
=> [PM-4296] Cannot login to Bitwarden with FIDO2 WebAuthn if extension is installed and logged in

apps/browser/src/_locales/en/messages.json, apps/browser/src/auth/guards/fido2-auth.guard.ts, apps/browser/src/platform/browser/browser-api.ts, apps/browser/src/popup/services/popup-utils.service.ts, apps/browser/src/vault/popup/components/fido2/fido2-use-browser-link.component.html, apps/browser/src/vault/popup/components/fido2/fido2.component.html, apps/desktop/src/locales/en/messages.json, apps/web/src/locales/en/messages.json, libs/common/src/models/export/fido2-credential.export.ts, libs/common/src/models/export/login.export.ts, libs/common/src/platform/models/domain/enc-string.ts
```
```
This PR addresses feedback gotten from #4715 
The changes include cleaning up unused i18n tokens, cleaning up listeners for Safari and using a button instead of an `a` tag for `use browser`.
=> Address PR feedback

libs/importer/src/components/dialog/file-password-prompt.component.html, libs/importer/src/components/dialog/file-password-prompt.component.ts
```
```
When importing a password protected file, we prompt the user to enter their password. When entering the password the import got canceled and on some occasions the user got logged out.
- **libs/importer/src/components/dialog/file-password-prompt.component.html and libs/importer/src/components/dialog/file-password-prompt.component.ts:** Use a FormGroup instead of single FormControl and use BitSubmitDirective which overrides the forms preventDefault …
=> [PM-4321] [Defect] When trying to import a password protected file the user is logged out

apps/browser/src/autofill/services/autofill.service.spec.ts, apps/browser/src/autofill/services/autofill.service.ts
Non-Premium accounts can autofill TOTP codes with the autofill keyboard shortcut; this PR fixes this issue to the expected behaviour.
In the autofill service, `doAutoFill` already does a `canAccessPremium` check to determine if a TOTP code should be copied to the clipboard. These changes leverage `canAccessPremium` to conditionally null out `cipher.login.totp`
=> [PM-4141] Bugfix - Non-Premium accounts can autofill TOTP codes with the autofill keyboard shortcut

apps/browser/src/platform/popup/browser-popout-window.service.ts
```
```
With the updates to the `browser-popout-window.service` from https://github.com/bitwarden/clients/pull/6600 we will update the passkey popup size to accommodate the new spacing. 
Remove default width from `openFido2Popout` and updated height to 450. 
Removing width will also fix this half off screen bug here: https://bitwarden.atlassian.net/browse/PM-4295
New height and width looks good with chrome and firefox
Firefox
Chrome
=> PM-4376 update size for passkey popup

libs/common/src/vault/services/fido2/fido2-client.service.ts
```
```
On eBay, there are two options for passkey creation “Face/Fingerprint/PIN Passkey” and “Security Key Sign In”. Creating and retrieving using the passkeys approach works, but with the security key, creation is successful, but retrieval throws an error, and this happens because eBay requires userVerification on creation but omits this on retrieval. To address this issue, userVerification should also be required on `preferred`. 
Added a change to require user verification when userVerification is `preferred` or `undefined`.
- …
=> [PM-4358] Passkey can be Created but not Retrieved on eBay

apps/browser/src/vault/popup/components/fido2/fido2.component.html, apps/browser/src/vault/popup/components/fido2/fido2.component.ts
```
```
When the passkey popup is open, if a user uses the search bar, the filtered ciphers will match properly. If the user were to delete the text in the search bar, the filtered ciphers should only show ciphers with a matching URI
refactored the search method in the `fido2.component` and it's invocation in the corresponding html. Also removed redundant code. 
NOTE: If you pull this branch to try this locally and the popup looks half sized, there is a fix for it located in this PR: https://github.com/bitwarden/clients/pull/6615
https://github.com/bitwarden/clients/assets/8302660/f77de9bd-f74c-410c-8c8f-c2fa32180268
=> PM-4299 Passkey Popup search bar is empty only show matching uri ciphers

apps/browser/src/popup/services/services.module.ts, apps/browser/src/tools/popup/components/file-popout-callout.component.ts, apps/browser/src/tools/popup/send/send-add-edit.component.ts, apps/browser/src/tools/popup/services/file-popout-utils.service.ts
Separating the logic from the `FilePopoutCalloutComponent` into a new Service
```
```
The logic used on the `FilePopoutCalloutComponent` is also necessary to Parent Components. We are separating that logic into a service so that it can be used by all the components.
- **services.module.ts:** Added the new `FilePopoutUtilsService`
- **file-popout-callout.component.ts:** Removed the logic regarding which callout should be shown and using the new service that deals with that.
- **send-add-edit.component.ts:** Using the `FilePopoutUtilsService` to check if the callout is visible
- **file-popout-utils.service.ts:** Service containing all the logic if the callout should be visible and which text should present to the user
- Please add **unit tests** where it makes sense to do so (encouraged but …
=> [PM-4375] Reuse show file selector callout logic

apps/browser/src/popup/app.module.ts, apps/browser/src/popup/scss/base.scss, apps/browser/src/popup/services/services.module.ts, apps/browser/src/tools/popup/components/file-popout-callout.component.html, apps/browser/src/tools/popup/components/file-popout-callout.component.ts, apps/browser/src/tools/popup/send/send-add-edit.component.html, apps/browser/src/tools/popup/send/send-add-edit.component.ts, apps/browser/src/tools/popup/services/file-popout-utils.service.ts
```
```
We identified another [use case](https://github.com/bitwarden/clients/pull/6503) for the callout shown on the Send create page on browser when having a File-Send selected.
This extracts it into it's own standalone component and also using the bit-callout instead of the bit-callout.
- **Extract callout in send-add-edit into separate component -** https://github.com/bitwarden/clients/commit/5b48737e69755485410e75abe3f1c22dc464358a
- Created new file-popout-callout.component
- Register component within app.module
- Replaced usage within send-add-edit.component
- **Override popup header style to fix bit-callout -** https://github.com/bitwarden/clients/commit/8676f94f54f6ef835c7e5da5343ded3fda3c5f5d …
=> [PM-4306] Extract file-popout-callout component used within Send on browser

apps/browser/src/popup/settings/settings.component.ts, apps/browser/src/tools/popup/settings/import/import-browser.component.html, apps/browser/src/tools/popup/settings/import/import-browser.component.ts, libs/importer/src/components/import.component.html, libs/importer/src/components/import.component.ts
```
```
Due to some issues with selecting a file and the popup closing while the FilePickerDialog of the OS is shown, we have added a callout which is shown on certain browsee
This callout component was extracted with https://github.com/bitwarden/clients/pull/6564 as it was previously only used within Send.
- **No longer popout automatically -** https://github.com/bitwarden/clients/commit/e6d000e55c38c5d2fb8b50890cea1944ddb9ede7
- **Add FilePopoutCalloutComponent to import-browser -** https://github.com/bitwarden/clients/commit/dce65fdcc24475ef11b5ee73c4cd907067676a50
- **Hide fileSelector on base import.component when callout is shown -** https://github.com/bitwarden/clients/commit/88ff9db0f487adc56b1b59b716590b9098dace3c
- Extend import.component to receive an input to show/hide the …
=> [PM-4290] Add pop out warning on import page

apps/browser/src/popup/settings/settings.component.html, apps/browser/src/popup/settings/settings.component.ts, apps/browser/src/tools/popup/settings/import/import-browser.component.html, apps/browser/src/tools/popup/settings/import/import-browser.component.ts, libs/importer/src/components/import.component.html, libs/importer/src/components/import.component.ts
This reverts commit 8dc81b603dc56d666c05bed6d89998d186e7c7fe.
```
```
Revert the work done on #6645 as we've decided to always popout the import page. The generates a smoother experience with uploading files and also with the login flows for the new Lastpass importer (https://github.com/bitwarden/clients/pull/6541)
- **Revert "[PM-4290] Add pop out warning on import page -** https://github.com/bitwarden/clients/pull/6651/commits/cdfc1007899d5f005067bf929107de611144761e
- This reverts commit https://github.com/bitwarden/clients/commit/8dc81b603dc56d666c05bed6d89998d186e7c7fe.
- **Change icon on Import items in browser-settings -** https://github.com/bitwarden/clients/pull/6651/commits/05f85237d69791084b1b8080bff5a9e6c3dd588f
- Replace the bwi-angle-right icon with the bwi-external-link and …
=> Revert "[PM-4290] Add pop out warning on import page (#6645)"

libs/importer/src/components/lastpass/lastpass-direct-import.service.ts
```
```
The fixes an issue where the direct LP importer only imports login ciphers, but not types like credit cards, identities, etc. The change here brings [parity with the standalone importer tool.](https://github.com/bitwarden/importer/blob/master/src/Importer/Services/LastPass/LastPassImportService.cs#L37)
- **libs/importer/src/components/lastpass/lastpass-direct-import.service.ts:** Set `parseSecureNotesToAccount` to false
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/a …
=> [PM-4510] LP importer disable parseSecureNotesToAccount

apps/desktop/src/locales/en/messages.json
```
```
Fixes wrong error message is displayed when entering a wrong password (password protected import). With `invalidPassword` missing from `messages.json`, the i18nService would return "", which the defaults to showing the generic invalid format error.
Will be 🍒 ⛏️ to `rc`
- **apps/desktop/src/locales/en/messages.json:** Add missing `invalidPassword`
=> [PM-4512] Wrong error message is displayed when entering a wrong password (password protected import)

apps/browser/src/vault/fido2/content/page-script.ts
```
```
Race condition causes safari to try to request native webauthn before the window has gotten focus back, resulting in an error. This fix waits for focus before triggering the request
=> [PM-4401] fix: wait for focus before triggering fallback

apps/browser/src/tools/popup/settings/import/import-browser.component.html
```
```
The importer on browser does not allow scrolling of overflow content. This PR fixes that by adding a `main` element, which is expected on browser extension page components. 
- **apps/browser/src/tools/popup/settings/import/import-browser.component.html:** Add `main` element
https://github.com/bitwarden/clients/assets/17113462/687bd15f-0eb2-49a8-b89e-4db649f15023
=> [PM-4433] fix scrolling in browser importer

apps/web/src/app/vault/components/vault-items/vault-items.component.html, apps/web/src/app/vault/components/vault-items/vault-items.component.ts, apps/web/src/app/vault/core/views/collection-admin.view.ts, apps/web/src/app/vault/individual-vault/vault-header/vault-header.component.html, apps/web/src/app/vault/individual-vault/vault-header/vault-header.component.ts, apps/web/src/app/vault/org-vault/vault-header/vault-header.component.html, apps/web/src/app/vault/org-vault/vault-header/vault-header.component.ts, libs/common/src/vault/models/view/collection.view.ts
> Lift the `ConfigService` dependency to the parent component in order to alleviate the need for all chained functions to be `async`
- **.../vault/components/vault-items/vault-items.component.html**: Removed `async` pipe
- **.../vault/components/vault-items/vault-items.component.ts**: Elevated `ConfigService` call to `ngOnInit` and passed in boolean result to the view
- **.../vault/core/views/collection-admin.view.ts**: Removed `async` from function and changed parameter to a boolean
- **.../vault/individual-vault/vault-header/vault-header.component.html**: Reverted changes to grab data using the `get` function
- **.../vault/individual-vault/vault-header/vault-header.component.ts**: Elevated `ConfigService` call to `ngOnInit` and passed in boolean result to the view
- …
=> [AC-1757] ConfigService dependency fix

libs/common/src/platform/services/state.service.ts
```
```
This is a partial fix to `account does not exist` errors experienced from #6622. This occurs when all users are logged out, we use the last logged in user as the active user to indicate which settings should be loaded by default.
This is a partial fix to PM-4515. We still experience null accounts in the stateService, but this is no longer due to account service by what I can tell.
- **stateService**: detect when an active account is not in the authed accounts list (by its abscence in the `accounts` subject) and add to accountService prior to switching. This should only occur at initialization so no changes to the `setActiveUser` method, as `addAccount` should be called prior to setting active User.
- Please add **unit tests** where it makes sense to do so (encouraged but not …
=> Handle active user not logged in

apps/browser/src/_locales/en/messages.json, apps/desktop/src/locales/en/messages.json, libs/importer/src/components/lastpass/dialog/lastpass-multifactor-prompt.component.html, libs/importer/src/components/lastpass/dialog/lastpass-multifactor-prompt.component.ts, libs/importer/src/components/lastpass/lastpass-direct-import-ui.service.ts
```
```
Updates the `lastpass-multifactor-prompt.component` to handle different _variants._ Adds a variant for YubiKey authentication (so the dialog shows relevant copy when using a YubiKey as opposed to an authenticator app).
- **messages.json:** Add new entry to desktop and browser
- **libs/importer/src/components/lastpass/dialog/lastpass-multifactor-prompt.component:** Add `variant` dialog data field; base the dialog copy off of it
- **libs/importer/src/components/lastpass/lastpass-direct-import-ui.service.ts:** Open different dialog variants based on the calling context …
=> [PM-4508] add YubiKey specific copy to LastPass import mfa dialog

libs/importer/src/components/lastpass/import-lastpass.component.html
```
```
Fixes a bug where the LP importer form fields wouldn't submit if `enter` was pressed.
- **libs/importer/src/components/lastpass/import-lastpass.component.html:** Removed a keydown handler that was preventing the default submit action. This was originally added to prevent the default form submit behavior of refreshing the page--but this is also remedied by removing the `form` element entirely. It isn't needed since this component is used within a larger `form`.
https://github.com/bitwarden/clients/assets/17113462/6ea13fb1-e68b-4b21-bb92-a2805d7d1c26 …
=> [PM-4509] submit LP importer on enter keydown

apps/browser/src/popup/settings/settings.component.ts
```
```
'Custom/Log out' vault timeout changes to 'Lock' in the Chrome extension when leaving the settings page and reentering it the second time.
**VaultTimeout** change was being triggered in a time where the value of **VaultTimeoutAction** was not yet loaded. This was setting a new **VaultTimeoutAction** from the UI form value instead of state, always defaulting to **lock.**
=> [PM-3572] 'Custom/Log out' vault timeout changes to 'Lock'

libs/common/src/vault/services/fido2/fido2-client.service.ts
```
```
In https://github.com/bitwarden/clients/pull/6617/, we added a check to require user verification if the relying party supplied a `preferred` status, or if it was `undefined`.  After discussion with Product, they felt that this was too restrictive and we should not require it on `preferred`.
- **fido2-client.service.ts:** Removed `preferred` from UV check.
=> [PM-4358] No longer prompt for user verification when "preferred" is supplied by the Relying Party

apps/browser/src/vault/fido2/content/page-script.ts
```
```
Fix an issue where `waitForFocus` is running inside of the iframe and so never reacts to the parent window receiving focus.
=> [PM-4553] [Defect] Browser fallback fails on first click on bitwarden

apps/browser/src/vault/popup/components/fido2/fido2.component.ts, libs/common/src/vault/services/fido2/fido2-client.service.ts
```
```
We will be bypassing user verification in the passkey implementation, pending implementation of PIN and biometrics as options for providing user verification.
The logic will map the relying party request as follows:
| Relying Party Request | Interpret as User Verification Required? | Value Returned to RP |
| --- | --- | --- |
| `required` | `true` | `true` |
| `preferred` | `true` | `true` |
| `undefined` (not provided) | `true` | `true` |
| `discouraged` | `false` | `false` |
- **fido2.component.ts:**
- Removed check for whether a user has a master password when creating or retrieving a passkey
- Passed through the `userVerification` value to `userVerified`, bypassing user verification until we implement PIN and Biometrics.
- **fido2-client.service.ts:** 
- Added back logic that …
=> [PM-4580] Removed user verification requirement

apps/browser/src/vault/popup/components/vault/add-edit.component.ts
```
```
In #6711 we removed the user verification requirement from the `Fido2Component`.  This PR missed a case where the verification was being performed in the `AddEditComponent` as well.
- **add-edit.component.ts:** Defaulted the user verification check to `true`.  I opted to leave the method there so that we can add the proper user verification when ready and have the structure in place for it.
=> [PM-4580] Bypass user verification of passkeys on add-edit component

bitwarden_license/bit-web/src/app/secrets-manager/models/view/access-policy.view.ts, bitwarden_license/bit-web/src/app/secrets-manager/projects/project/project-people.component.ts, bitwarden_license/bit-web/src/app/secrets-manager/shared/access-policies/access-policy-selector/models/ap-item-view.type.ts, bitwarden_license/bit-web/src/app/secrets-manager/shared/access-policies/access-policy.service.ts, bitwarden_license/bit-web/src/app/secrets-manager/shared/access-policies/models/responses/access-policy.response.ts
```
```
The purpose of this PR is to fix an access removal dialog bug that occurs when initially landing on the page without making changes.
When patching the form group value, `currentUser` and `currentUserInGroup` properties need to be set.
- **bitwarden_license/bit-web/src/app/secrets-manager/models/view/access-policy.view.ts:** 
Add `currentUser` to the view, so the property can be set on the access policy selector form group.
- **bitwarden_license/bit-web/src/app/secrets-manager/projects/project/project-people.component.ts:**
Add code to setting `currentUser` and `currentUserInGroup` during form group patch.
- **bitwarden_license/bit-web/src/app/secrets-manager/shared/access-policies/access-policy-selector/models/ap-item-view.type.ts:**
Add `currentUser` in model conversion.
- …
=> [SM-996] Fix access removal dialog bug

apps/browser/src/popup/settings/await-desktop-dialog.component.html, apps/browser/src/popup/settings/await-desktop-dialog.component.ts, apps/browser/src/popup/settings/settings.component.ts, apps/desktop/src/app/components/browser-sync-verification-dialog.component.ts
```
```
Fixes a bug where the `BrowserSyncVerificationDialogComponent` and `AwaitDesktopDialogComponent` could not be closed by the user after opening. 
Removes `disableClose` from the dialogs' options. This originally provided parity with SweetAlert's `allowOutsideClick` feature when migrating to the dialog service. However, `disableClose` was [recently updated](https://github.com/bitwarden/clients/blob/2ecd710ab1a1c47e45dff984a8f8a441e55c646a/libs/components/src/dialog/directives/dialog-close.directive.ts#L17-L24) to also disable buttons with the attribute `bitDialogClose`. This means dialogs with `disableClose` will only be closable programmatically.
- **apps/desktop/src/app/components/browser-sync-verification-dialog.component:** Remove `disableClose`
- …
=> [PM-4357] remove disableClose on BrowserSyncVerificationDialog and AwaitDesktopDialog

.github/renovate.json, .github/workflows/label-issue-pull-request.yml
```
```
Disable `needs-qa` label for renovate PRs. Also add `npm` to ignore list for renovate and remove `zone.js`.
=> [PM-2331] Disable needs-qa label for renovate PRs

.github/CODEOWNERS
```
```
Adding all messages.json files besides en/ into ownership of team-tools-dev
- **.github/CODEOWNERS:** Adding all locales folders into ownership of team-tools-dev. The ownership of ocales/en should be overridden by the [rules added further down](https://github.com/bitwarden/clients/compare/update-codeowners-for-crowdin?expand=1#diff-3d36a1bf06148bc6ba1ce2ed3d19de32ea708d955fed212c0d27c536f0bd4da7R107-R110)
=> Update CODEOWNERS for Crowdin PRs

apps/browser/src/popup/settings/settings.component.ts
Make the "Change Master Password" link on Browser settings direct to the Login page (for the user's environment) instead of the Help site.
- `apps/browser/src/popup/settings/settings.component.ts`
https://github.com/bitwarden/clients/assets/102181210/d3e58547-3a28-4497-9b19-7f5f9345e6f2
=> [PM-290][Browser] Make Change MP Link Direct to Login Page

apps/web/src/app/tools/send/add-edit.component.html, libs/angular/src/tools/send/add-edit.component.ts
```
```
In the send item popup add a premium badge to the File option and disable it's selection.
- **libs/angular/src/tools/send/add-edit.component.ts:** For the typeOptions items I added a new property for premium. Set the File type to true and the Text type to false. 
- **apps/web/src/app/tools/send/add-edit.component.html:** Added the app-premium-badge component to the radio group label and to display if the user does not have premium and if the current typeOption is a premium option. The radio button is also disabled if the user does not have premium and if the typeOption is a premium option.
=> [PM-105] Premium Badge Send File

apps/web/src/app/auth/settings/webauthn-login-settings/create-credential-dialog/create-credential-dialog.component.html, apps/web/src/app/auth/settings/webauthn-login-settings/create-credential-dialog/create-credential-dialog.component.ts, apps/web/src/app/auth/settings/webauthn-login-settings/delete-credential-dialog/delete-credential-dialog.component.html, apps/web/src/app/auth/settings/webauthn-login-settings/delete-credential-dialog/delete-credential-dialog.component.ts, apps/web/src/app/auth/settings/webauthn-login-settings/webauthn-login-settings.module.ts, libs/angular/src/auth/components/user-verification.component.ts
```
```
Use generic user verification field 
=> [PM-3722] Use `UserVerificationPrompt` in passkey registration dialog

.github/CODEOWNERS, .github/whitelist-capital-letters.txt, libs/tools/README.md
```
```
I want to slightly deviate from the pattern that Auth and Vault have taken with their libs.
Instead of having `libs/{team-name}/src` and having all features the team owns under one lib, I'd prefer to have a folder we own (libs/tools) and under this folder we have several packages which encapsulate the feature/product.
Next move for this would be creating:
i.e 
`libs/tools/send/package.json`
or
`libs/tools/password-generator/package.json`
- **.libs/tools/README.md:** Create the libs/tools folderUpdate CODEOWNERS for `libs/tools` to be owned by `team-tools-dev`
- **.github/whitelist-capital-letters.txt:** Add exception for the capital `README.md` in `libs/tools`
- **.github/CODEOWNERS:** Update CODEOWNERS for `libs/tools` to be owned by `team-tools-dev`
- Please add **unit tests** …
=> [PM-4266] Create folder for tools owned features

libs/common/src/vault/services/cipher.service.ts
```
```
We believe that autofill on page load may be trying to retrieve ciphers before we have a encryption key available to decrypt them. This is a temporary fix to stop that decryption attempt from occurring if we don't have a key yet.
=> [PM-4660] return early from cipher decryption if no encryption key

apps/browser/src/background/main.background.ts, libs/common/src/vault/services/fido2/domain-utils.spec.ts, libs/common/src/vault/services/fido2/domain-utils.ts, libs/common/src/vault/services/fido2/fido2-client.service.spec.ts, libs/common/src/vault/services/fido2/fido2-client.service.ts
```
```
- Add support for excluded domains
- Fix crash when using `localhost` (https://bitwarden.atlassian.net/browse/PM-4573)
=> [PM-4531] Do not override webauthn on excluded domains

apps/browser/src/background/main.background.ts, apps/browser/src/vault/fido2/browser-fido2-user-interface.service.ts, libs/common/src/vault/services/fido2/fido2-authenticator.service.spec.ts, libs/common/src/vault/services/fido2/fido2-authenticator.service.ts, libs/common/src/vault/services/fido2/fido2-client.service.ts
```
```
Automatically fallback to browser if no passkeys are found in bitwarden vault
- **fido2 authenticator/client**: Handle automatic fallback exceptions
- **browser-user-interface**: Don't show popup during `ensureVaultUnlocked` if the vault is already unlocked
=> [PM-4688] Automatically fallback on passkey retrieval if no passkeys are found

libs/common/src/vault/services/fido2/guid-utils.ts
```
```
In https://github.com/bitwarden/clients/pull/6792, we updated `Utils.isGuid` to perform a more relaxed check for GUID formatting, in order to support passkey GUIDs that don't match the variant restrictions. In order to support a release of the passkey implementation without requiring a regression of all other uses if `isGuid`, we have decided to take that relaxed logic and apply it just in the passkey use case.
We will introduce https://github.com/bitwarden/clients/pull/6792 after this change and remove this code, assuming it does not break anything else.
- **guid-utils.ts:** Added method to validate GUID.
- If …
=> Added separate function for GUID validation for passkeys

apps/browser/src/vault/fido2/content/page-script.ts
```
```
Tested using: https://fedcm-rp-demo.glitch.me/
Filter non-webauthn calls to credmanager apis and just forward those to the browser
=> [PM-4704] Filter non-webauthn calls to credmanager apis

apps/browser/src/vault/fido2/content/content-script.ts
```
```
Followup to: https://github.com/bitwarden/clients/pull/6790
Previous PR added logic to the background script which automatically fell back to the browsers native implementation if the hostname was found to be excluded. This PR check the same thing but completely disables the fido2 page-script injection if:
- Hostname is excluded
- No user is logged in
=> [PM-4531] Completely disable fido2 injection for excluded sites

apps/browser/src/background/runtime.background.ts, apps/browser/src/vault/fido2/content/page-script.ts
```
```
- Add proper error handling and fallback logic to `waitForFocus` when `window.top` is not available due to cross-origin frames.
- Force tab and window focus in the background-script 
=> [PM-4678] [Defect] Passkey browser fallback broken on iCloud

apps/browser/src/autofill/services/abstractions/autofill-overlay-content.service.ts, apps/browser/src/autofill/services/autofill-overlay-content.service.spec.ts, apps/browser/src/autofill/services/autofill-overlay-content.service.ts, apps/browser/src/autofill/services/collect-autofill-content.service.ts
```
```
An issue was identified when attempting to trigger autofill from the overlay after the DOM for a page has mutated. The issue comes down to the fact that the overlay attempts to avoid calling for the re-capture of page details by piggy-backing on the response from other sections of the code that collect page details.
The fixes in this ticket facilitate a re-check when opening the overlay that triggers a re-collection of page details if a DOM mutation has been observed within the `CollectPageDetailsContent` service.
- **apps/browser/src/autofill/services/abstractions/autofill-overlay-content.service.ts:** Adding typing data for a new public property that determines if the overlay needs to re-collect page details
- **apps/browser/src/autofill/services/autofill-overlay-content.service. …
=> [PM-4744] Page Details that Update after Mutation Observer has Triggered Do Not Update within Overlay Background

apps/desktop/src/auth/login/login-approval.component.ts, apps/desktop/src/auth/preload.ts
```
```
Removed all uses of `ipcRenderer` from login-approval.component.ts, and moves them to use the ipc preload, getting us step closer to enabling electron sandboxing.
=> [PM-3682] Remove ipcRenderer from login-approval

apps/browser/src/autofill/background/tabs.background.spec.ts, apps/browser/src/autofill/background/tabs.background.ts
```
```
An issue was introduced when the tabs.background.ts file was refactored for the overlay. Windows does not correctly track focus changes within Chrome windows, and often will return a -1 instead of an actual value when the focus listener is triggered. Logic has been reverted to what was present before to ensure we update cipher data in the overlay and other parts of the extension.
- **apps/browser/src/autofill/background/tabs.background.spec.ts:** Adding a test to verify reverted behavior.
- **apps/browser/src/autofill/background/tabs.background.ts:** Reverting logic when checking for the focused window ID to ensure cipher data updates.
https://github.com/bitwarden/clients/assets/16629865/bb11a2d3-0496-4c7c-930c-ee49c5cbcfe9
=> [PM-4743] Windows Chromium Browser is Not Updating Overlay Ciphers on Tab Update

apps/browser/src/autofill/background/overlay.background.spec.ts, apps/browser/src/autofill/background/overlay.background.ts, apps/browser/src/autofill/services/autofill-overlay-content.service.spec.ts, apps/browser/src/autofill/services/autofill-overlay-content.service.ts, apps/browser/src/autofill/services/collect-autofill-content.service.ts
```
```
This PR includes a number of fixes that hopefully will address the weird UI issues that are being seen when the overlay is open on a stale tab. These include the following:
- A guard within the overlay background that ensures the correct ports are registered for the overlay list and button
- A `focusout` listener that ensures the overlay elements will be cleaned up if the Window loses focus
- A `visibilitychange` listener that ensures the overlay elements will be cleaned up if the window becomes hidden
- Fixes for how we handle repositioning dom elements within the root `html` element to ensure the overlay only updates those when it is injected
- A method to ensure the overlay is built if the DOM injects form field elements after a mutation has occurred in the DOM
- …
=> [PM-4763] Fixing Issues with the Overlay UI Positioning and Presentation

apps/browser/src/autofill/constants.ts, apps/browser/src/autofill/services/autofill-overlay-content.service.spec.ts, apps/browser/src/autofill/services/autofill-overlay-content.service.ts
```
```
The autofill overlay isn't resetting on websites that set up the `html` and `body` elements with a fixed position. As a result, we're modifying the listeners that trigger this behavior to facilitate globally caught triggers for scroll events. This ensures that we can reposition the overlay when any element scrolls within the DOM.
- **apps/browser/src/autofill/constants.ts:** Adding events to the list of constants so that we aren't referenced the string value when setting up visibility change and focus out listeners.
- **apps/browser/src/autofill/services/autofill-overlay-content.service.spec.ts:** Updating jest tests to verify logic changes made to scroll listener within the AutofillOverlayContentService
- **apps/browser/src/autofill/services/autofill-overlay-content.service.ts:** …
=> [PM-4790] Overlay not resetting on scroll of websites that do not scroll body element

apps/desktop/src/platform/preload.ts, apps/desktop/src/services/native-message-handler.service.ts
```
```
Removed all uses of `ipcRenderer` from native-message-handler.service.ts, and moves them to use the ipc preload, getting us step closer to enabling electron sandboxing.
=> [PM-3686] Remove ipcRenderer from native-message-handler

apps/browser/src/platform/decorators/session-sync-observable/session-syncer.spec.ts, apps/browser/src/platform/services/abstractions/abstract-chrome-storage-api.service.ts, apps/browser/src/platform/services/local-backed-session-storage.service.ts, apps/cli/src/platform/services/lowdb-storage.service.ts, apps/cli/src/platform/services/node-env-secure-storage.service.ts, apps/desktop/src/platform/services/electron-renderer-secure-storage.service.ts, apps/desktop/src/platform/services/electron-renderer-storage.service.ts, apps/desktop/src/platform/services/electron-storage.service.ts, apps/web/src/app/core/html-storage.service.ts, libs/angular/test-utils.ts, libs/common/spec/fake-storage.service.ts, libs/common/spec/utils.ts, libs/common/src/platform/abstractions/storage.service.ts, libs/common/src/platform/services/memory-storage.service.ts, libs/common/src/platform/state/global-state.ts, libs/common/src/platform/state/implementations/default-global-state.spec.ts, libs/common/src/platform/state/implementations/default-global-state.ts, libs/common/src/platform/state/implementations/default-user-state.spec.ts, libs/common/src/platform/state/implementations/default-user-state.ts, libs/common/src/platform/state/implementations/util.spec.ts, libs/common/src/platform/state/implementations/util.ts, libs/common/src/platform/state/key-definition.spec.ts, libs/common/src/platform/state/key-definition.ts, libs/common/src/platform/state/state-update-options.ts, libs/common/src/platform/state/user-state.ts
```
```
Adds three improvements needed for the state provider framework (#6640).
1. Options in update logic to include dependencies and to provide a `shouldUpdate` callback to use as a guard clause to updates
2. Removes the `value` from storage service updates and allows the subscriber to `get` the update, if it's relevant. This reduces messaging sizes, limits platform differences in object messaging, and centralizes all state reads to a single location, which is relevant for...
3. Limit calls to `KeyDefinition.deserializer` to only when the storage service itself informs that data has been serialized. This allows us to transparently swap out storage providers that may or may not serialize data. Otherwise, the deserializer needs to handle data differences resulting from that proccess …
=> Ps/pm 2910/state framework improvements

libs/components/src/stories/migration.mdx
```
```
Docs for migrating components to use CL components
=> [CL-135] CL migration docs

apps/web/src/app/components/environment-selector/environment-selector.component.html, apps/web/src/app/components/environment-selector/environment-selector.component.ts, libs/angular/src/auth/components/environment-selector.component.html, libs/angular/src/auth/components/environment-selector.component.ts, libs/common/src/enums/feature-flag.enum.ts
```
```
Remove references to the EU Environment feature flag from the client codebase, now that it is a permanent feature.
- **environment-selector.component.ts:** Removed property for EU environment check.
- **environment-selector.component.html:** Removed conditional checks for EU environment.
- **feature-flag.enum.ts:** Removed feature flag value.
=> Remove EU environment feature flag from clients

apps/web/src/app/reports/pages/inactive-two-factor-report.component.ts
```
```
Remove `Can Edit, Except Passwords` from inactive 2fa reports. This is a follow up to the [Vault Health Reports Ticket](https://bitwarden.atlassian.net/browse/AC-1333)
Update inside `setCiphers` logic of `inactive-two-factor-report`. Add `!viewPassword` to check.
https://github.com/bitwarden/clients/assets/8302660/9482456c-3114-4949-af45-13babdce5ee0
=> AC-1694 Remove Can Edit Except PW ciphers from Inactive 2FA

apps/web/src/app/vault/individual-vault/vault-filter/shared/components/vault-filter-section.component.html
```
```
Previously on long organization names, if an organization was disabled the `bwi-exclamation-triangle` would misalign with the menu icon inside of `vault-filter-section`. Added styles to center and inline these elements. 
Added `tw-flex tw-items-center` to the wrapper of the two icons inside `vault-filter-section`
=> PM-4828 Align disable and menu icon in vault filter

apps/web/src/locales/en/messages.json
```
```
Fixed i18n phrase that referred to self-hosted deployments as "on-premise" instead of "on-premises".
=> Fix on-premise vs. on-premises in org plan verbiage

apps/web/src/locales/en/messages.json
```
```
Added i18n messages for new WebAuthn login component:
- **messages.json:** Added messages for all phrases used in `login-via-webauthn.component.ts`.
=> [PM-4938] Add missing translations on WebAuthn login

apps/browser/src/_locales/en/messages.json
```
```
The `typePasskey` phrase was missing from browser, so the "Passkey" label was missing from the add/edit and view components on the extension.  It is now displaying above the created time as expected.
- **messages.json:** Added `typePasskey` phrase for the passkey label in browser.
=> [PM-4919] Add typePasskey phrase to browser

libs/common/src/auth/login-strategies/webauthn-login.strategy.spec.ts, libs/common/src/auth/login-strategies/webauthn-login.strategy.ts
```
```
Resolve [PM-5001](https://bitwarden.atlassian.net/browse/PM-5001) where, on passkey authN and attempted MP decryption, the user receives `ERROR Error: Uncaught (in promise): Error: No encrypted user key found`. 
- **libs/common/src/auth/login-strategies/webauthn-login.strategy.ts:** Set user key should set the master key encrypted user key if it exists so that the passkey authN + MP decryption flow can work.
- **libs/common/src/auth/login-strategies/webauthn-login.strategy.spec.ts** Update decryption tests to assert for this case
https://github.com/bitwarden/clients/assets/116684653/244ddf1f-4697-4d6a-a222-ba0e66130aa0 …
=> Auth/PM-5001 - WebAuthn Login + MP Decryption fix 

apps/browser/src/auth/popup/account-switching/account-switcher.component.html, apps/browser/src/auth/popup/account-switching/account-switcher.component.ts
```
```
To resolve [PM-4865](https://bitwarden.atlassian.net/browse/PM-4865). 
- **apps/browser/src/auth/popup/account-switching/account-switcher.component.ts:** - On init, pull available vault timeout actions and check if the active user can lock and assign result to a public variable `activeUserCanLock`
- **apps/browser/src/auth/popup/account-switching/account-switcher.component.html:** Use `activeUserCanLock` to determine if the lock button should be shown. 
https://github.com/bitwarden/clients/assets/116684653/18e001ee-5b95-4596-90d1-75e81e4e1447
- If this change has particular **deployment requirements** - notify …
=> PM-4865 - Browser Account Switcher - Only show lock button for lockable accounts

libs/common/src/services/vault-timeout/vault-timeout.service.spec.ts, libs/common/src/services/vault-timeout/vault-timeout.service.ts
```
```
While working on a different ticket I started working on tests for VaultSettingsService and noticed a bug while writing the tests. The other ticket may not be completed as quickly so I decided to make a PR for these items instead of waiting for the other work.
Helps with PM-4996
- **libs/common/src/services/vault-timeout/vault-timeout.service.spec.ts:** Add a lot of tests to cover the service.
- **libs/common/src/services/vault-timeout/vault-timeout.service.ts:** Fix a bug where we would be getting the vault timeout actions for the current active user vs getting them for the user actively locking.
- If this …
=> Vault Timeout Service Tests & Bug Fix

apps/browser/src/_locales/en/messages.json, apps/browser/src/auth/popup/account-switching/account-switcher.component.html, apps/browser/src/auth/popup/account-switching/account-switcher.component.ts
```
```
Disables lock button for locked users. Also changes the hide behavior for non-lockable accounts to disable with a tooltip
=> Hide lock now for locked users

apps/browser/gulpfile.js, package-lock.json, package.json
Per our new [dependency management process](https://contributing.bitwarden.com/contributing/dependencies/), we’ve been working on getting the Autofill dependency responsibilities updated. The `clients` project has several packages in use by a single author who has migrated their packages [to pure ESM](https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c).
In the case of `del`, the package is only used when building the production distributions of the Safari extension, and is used to clear the appropriate subpath of the `dist/Safari` build directory before rebuilding. `rimraf` has been capable of Promise chaining and using glob patterns for a while now (the presumed reason for using `del`), and is used more widely across the clients repo.
I’ve dropped in rimraf in place of …
=> [PM-5505] Replace del with rimraf

libs/common/src/platform/services/state.service.ts
This is a temporary fix until the owning services can update state themselves. It uses the presence of an auto key to surmise unlocked state on init. This is safe since it's run only once on extension start.
=> [PM-4927] Temporarily load all auth states on init of state service

apps/browser/src/auth/popup/account-switching/account-switcher.component.html, apps/browser/src/auth/popup/account-switching/account-switcher.component.ts, apps/browser/src/auth/popup/account-switching/account.component.ts
```
```
Adds loading overlay to account switcher after interaction. This load is removed naturally upon navigation away from the switcher.
- **component.html**: 
- This is mostly formatting
- added a second `<main>` element absolutely positioned to handle the non-interactable overlay
- pushed accoutn-switcher to a div element to appropriately limit it's width to be consistent with other pages in popouts
- removed ul bullets
- **switcher-component.ts**: set loading on each navigable piece of work
- **account.component.ts**: output when an account is selected to switch to
popout is correctly sized
view in popup
- If this …
=> Ps/pm 5004/add load to account switcher

apps/web/src/app/tools/send/send-access-text.component.ts
```
```
This fixes the following regression:
- User is unable to toggle hidden text when opening a send that has hide text by default enabled 
- **apps/web/src/app/tools/send/send-access-text.component.ts:** Update the content of the textArea when toggling the text visibility
=> [PM-5051] Fix hide text toggle on Send access

libs/components/src/layout/layout.component.html, libs/components/src/layout/layout.component.ts, libs/components/src/layout/layout.stories.ts
```
```
Adds a new color scheme for the sidebar and navigation components, to be used within the Admin console.
- **libs/components/src/layout/layout.component.html:** Override colors used in nav components based on variant input
- **libs/components/src/layout/layout.component.ts:** Add `variant` input
- **libs/components/src/layout/layout.stories.ts:** Add new `Secondary` story
https://github.com/bitwarden/clients/assets/17113462/d85040d2-f27b-4e58-b0e3-6be35055d56c …
=> [CL-145] add secondary variant to bit-layout side nav

apps/web/src/app/vault/components/collection-dialog/collection-dialog.component.ts
```
```
Restore previous behaviour when creating a new collection:
* front-end - no users are added by default
* server - if you're a Manager or have EditAssignedCollections permission, you're assigned to the collection on creation
The server PR is https://github.com/bitwarden/server/pull/3498.
- only add the current user on the front-end if flexible collections is ON.
- in that case, we add them with Can Manage permissions, per the new flexible collections permission system. …
=> [AC-1873] Only assign user in the front-end if using Flexible Collections

.github/CODEOWNERS
```
```
Removes the tech-leads as the default code owner to speed up work. Most files should have gotten an owner by now.
=> Remove tech-leads as default codeowner

libs/common/src/services/vault-timeout/vault-timeout.service.spec.ts, libs/common/src/services/vault-timeout/vault-timeout.service.ts
```
```
This changes the behavior of `checkVaultTimeout` to only consider the view being open as being in indicator for the currently active user. If they are not the active user, even if we know a view is open their vault timeout will lock them out once it has passed enough time without other activity. 
- **libs/common/src/services/vault-timeout/vault-timeout.service.ts:** Pass the result of the view being open and active user to the `shouldLock` so that it can determine whether or not it cares about the view being open for that user.
- **libs/common/src/services/vault-timeout/vault-timeout.service.spec.ts:** Rewrote one test because the behavior is expected to be different, the view being open used to matter for all users and now it should only matter for the active user.
- Please add …
=> [PM-4926] Only Keep Active User Alive When A View is Open

.github/CODEOWNERS
```
```
With https://github.com/bitwarden/clients/pull/6986 we removed @bitwarden/tech-leads as default owners. With that the exception for the en/messages.json to not be owned by anyone was also removed. This resulted in the @bitwarden/team-tools-dev also owning these files. This fixes it.
- **.github/CODEOWNERS:** Add previous exception of ownership for the en/messages.json files
=> Add exception for en/messages.json to not be owned by anyone

libs/importer/src/importers/onepassword/types/onepassword-1pux-importer-types.ts
```
```
An issue was found with the `LoginFieldTypeEnum` of the `onepassword-1pux-importer` having two identical values for `TextOrHtml` and `PhoneNumber`.
According to [About the 1Password Unencrypted Export format](https://support.1password.com/1pux-format/#item-details)  the PhoneNumber value should actually be `TEL` and not `T`
As far as I know, this has not been an issue, as I haven't been able to create a loginfield of type PhoneNumber within 1Password. Additionally, if the `onepassword-1pux-importer` can't [map a fieldtype](https://github.com/bitwarden/clients/blob/5582d7644c4cfc4516ca1c5fb43c8cf3256e5c02/libs/importer/src/importers/onepassword/onepassword-1pux-importer.ts#L166-L177) it will still add the contents as a custom field, retaining all data.
- …
=> [PM-5162] [1pux importer] Fix phone value entry in LoginFieldTypeEnum

libs/common/src/platform/services/environment.service.ts, libs/common/src/platform/services/state.service.ts
```
```
We are currently making ~70k calls/minute to the `/config` endpoint.  This compares to around ~6k/minute for `sync`, for comparison.  In testing, I've identified some ways to reduce these calls incrementally.
- There appeared to be a duplicate `next`ing of the `activeAccount$` observable on account change.  The `setActiveAccount` and `addAccount` were both issuing the change.
- I added `distinctUntilChanged` to the subscription on the `EnvironmentService`, so that if the `activeAccount$` were to `next` the same user ID it will not re-retrieve the environment URLs.  The assumption here is that a given user will have the same environment URLs when changing accounts.
- **environment.service.ts:** Added `distinctUntilChanged`
- **state.service.ts:** Removed extra observable `next` on …
=> [PM-5111] Reduce calls to config endpoint

apps/desktop/src/platform/services/i18n.main.service.ts
```
```
This issue was introduced in #6482, where I changed the file loading to use the promise version of `readFile`. This seemed to work correctly for most cases, but it breaks the "start to menu bar" feature, as the menu bar icon refuses to appear.
I can't quite make heads or tails on why the promise version of this function would break on this specific case, I tried to make sure there wasn't a missing await but couldn't get anywhere, so I'll just revert that change and go back to the sync function 🤷
=> [PM-5144] Use sync fs in desktop i18n loading

apps/browser/src/vault/fido2/content/content-script.ts
```
```
Disable passkey storage on your own web vault so that you can't register login-passkeys with your own vault
This can be thought of as the equivalent of suppressing the notification bar on the Bitwarden vault (see https://github.com/bitwarden/clients/blob/6c3cb841a2d54e1b61be7f4f6c9df56d99665684/apps/browser/src/autofill/content/notification-bar.ts#L103).
=> [PM-4766] Disable fido2 integration on bw vault page

apps/browser/src/background/main.background.ts
The subsequent path helps to trigger process reload when the active user logs out and the new active is locked.
```
```
Remove early return from logout callback -- this was blocking process reload in the legitimate case of a locked second account and logout of a primary account.
=> Do not early return from logout

apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.html, libs/common/src/admin-console/enums/organization-user-type.enum.ts, libs/common/src/admin-console/models/domain/organization.ts
```
```
This PR is stacked on top of https://github.com/bitwarden/clients/pull/6906/ because they overlap a good bit.
Deprecates the ability to designate a user as `OrganizationUserType.Manager` behind `FeatureFlags.FlexibleCollections`
- **apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.html:** Hides the Manager option in the member dialog UI
- ~~**apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.ts:** Maps Manager role to User role when form group loads~~ Reverted, as this will be handled on the server instead.
- **libs/common/src/admin-console/enums/organization-user-type.enum.ts:** Add deprecation comment to enum
- **libs/common/src/admin-console/models/domain/organization.ts:** …
=> [AC-1786] deprecate manager role

apps/browser/src/auth/popup/account-switching/account-switcher.component.html, apps/browser/src/auth/popup/account-switching/account.component.html, apps/browser/src/popup/scss/box.scss
The contrast for the account switcher page is low on the Dark theme. The Solorized Dark theme colors are completely incorrect. This PR updates styles on the Account Switcher page to work for every theme by adding a temporary stop-gap class `account-switcher-row`.
- Add `account-switcher-row` class
- `apps/browser/src/popup/scss/box.scss`
- Add `account-switcher-row` class to relevant elements on the Account Switcher page
- `apps/browser/src/auth/popup/account-switching/account-switcher.component.html`
- `apps/browser/src/auth/popup/account-switching/account.component.html`
=> [PM-5212] Account Switching Theme Styling

apps/desktop/src/app/app.component.ts, apps/web/src/app/app.component.ts
```
```
If there is an issue connecting to SignalR, we get into a loop that includes calling the `/config` endpoint:
1. Connect to SignalR
2. Sync (this will not _actually_ sync most of the time, because `needsSync` will detect that it isn't necessary)
3. SignalR closes the connection
4. Attempt to reconnect
This loop will continue until successful SignalR connection.  When the sync occurs in step 2 of this loop, the `syncCompleted` message is sent, which is intercepted by the `AppComponent` and triggers a call to the config endpoint.
What this PR does is recognize that the vast majority of the time, the `fullSync()` call in step 2 above will not actually perform a sync.  We can detect that by checking `successfully` in the handler and not refresh the config in that case.
- …
=> [PM-4107] Only call config on successful sync

apps/web/src/app/admin-console/organizations/tools/vault-export/org-vault-export.component.ts, apps/web/src/app/tools/vault-export/export.component.html, apps/web/src/app/tools/vault-export/export.component.ts
```
```
Hide the vault selector on export page behing the flexible collections feature flag
- **web/export.component.ts:** added property with flexible collections feature flag
- **web/export.component.html:** Reading flexible collections flag to decide if should show or not the vault selector
=> [PM-5060] Add flexible collection feature flag to export vault selector

apps/browser/src/autofill/services/autofill-constants.ts, apps/browser/src/autofill/services/collect-autofill-content.service.spec.ts, apps/browser/src/autofill/services/collect-autofill-content.service.ts
```
```
An issue was identified when form fields are collected from a web page where the extension caches form field data that is not visible in the viewport on load. On subsequent calls for the form field data, we end up with a stale `viewable` data value that disallows autofilling the field. 
To resolve this, we need to essentially check the visibility of the form element each time the data is queried by a background process. This ensures that we continue to only fill visible elements, but have up to date data each time a fill is attempted. 
Resolves #7202
- **apps/browser/src/autofill/services/autofill-constants.ts:** Adding `login` as a constant value that we check against when verifying if we are filling a username field.
- **apps/browser/src/autofill/services/collect-autofill-content …
=> [PM-5245] Autofill not triggering for fields that are not visible on load

libs/components/src/dialog/dialog.service.ts
```
```
Undeprecates `DialogService.openSimpleDialogRef`, as it is needed to close simple dialogs programmatically.
=> [CL-152] undeprecate openSimpleDialogRef

apps/browser/src/platform/background/service-factories/active-user-state-provider.factory.ts, apps/browser/src/platform/background/service-factories/single-user-state-provider.factory.ts, apps/browser/src/platform/background/service-factories/state-provider.factory.ts
```
```
We neglected to add a factory for `ActiveUserStateProvider`, `SingleUserStateProvider`, and  the combined `StateProvider` classes.
=> Add missing state provider factories

apps/web/src/app/admin-console/organizations/settings/account.component.html, apps/web/src/app/auth/settings/account/account.component.html, apps/web/src/app/auth/settings/account/danger-zone.component.html, apps/web/src/app/auth/settings/account/danger-zone.component.ts, apps/web/src/app/auth/settings/account/danger-zone.stories.ts, apps/web/src/app/shared/loose-components.module.ts
```
```
Extract a re-useable danger-zone component instead of needing to duplicate the code. I wasn't sure which team should own it, but defaulted to auth since ac is more an extension.
This results in a minimal change in the visual UI on the users account settings. But it matches the current styling of the AC which I consider acceptable.
|Before|After|
|-|-|
|![image](https://github.com/bitwarden/clients/assets/137855/192ea9a3-de0c-4ccf-bbc1-c8086ccb0785)|![image](https://github.com/bitwarden/clients/assets/137855/c6f9fba6-b13e-4cfe-bbf9-e4a447d24c68)| …
=> [PM-5299] Extract a danger-zone component

apps/browser/src/auth/popup/account-switching/account-switcher.component.ts, apps/browser/src/background/main.background.ts, apps/browser/src/popup/app-routing.module.ts, libs/angular/src/auth/guards/unauth.guard.ts
```
```
Browsers were resolving promise races in differing orders between `authService.AuthStatus` and `accountService.swithcAccount`. We were also legacy navigating home, which happened to be the right answer _iff_ switch account won the race and `authStatus` correctly identified us as logged in/unlocked. If it lost, we ended up at the login screen.
This corrects the account-switcher navigation on logout, updates background logout messaging to emit only a `switchFinish` or `doneLoggingOut`, depending on what actually occured, and upgrades the _browser only_ unauthGuard to a `canActivateFn`, which is the new requirement.
This guard function uses an observable pattern over a promise so that it is not susceptible to the same race as described above -- it also uses the `accountService` …
=> [pm-5287] fix account switch logout routing

libs/common/src/platform/services/state.service.ts
When the overlay feature flag is on, the default overlay visibility setting should be set to off (to allow users to opt-in if they wish)
=> [PM-5333] Bugfix - Autofill overlay visibility setting should be off by default

libs/common/src/admin-console/models/data/organization.data.ts, libs/common/src/admin-console/models/domain/organization.ts
```
```
The new `allowAdminAccessToCollectionItems` that was added in AC-1122 needs to also be added to the `organization.ts` model so it can be accessed without making an unnecessary API call.
Add the missing property to `organization.data.ts` and `organization.ts`.
=> [AC-1982] Add AllowAdminAccessToAllCollectionItems setting to the organization

apps/browser/src/autofill/content/notification-bar.ts
```
```
`chrome.storage.local.get("key", ...)` will return to you (through callback) an object that contains your key, this is because you can request multiple keys at once. You can see us access that object with the requested key in our chrome storage services [here](https://github.com/bitwarden/clients/blob/96d1c8338557a8f49be7507e4d5ec9dd36bfc34c/apps/browser/src/platform/services/abstractions/abstract-chrome-storage-api.service.ts#L47). I missed that and was not accessing the "global" key so the notification bar logic always thought they had 0 never domains. 
This was found by an amazing community member (@jlcfly) [here](https://github.com/bitwarden/clients/issues/1641#issuecomment-1856983921)
- **apps/browser/src/autofill/content/notification-bar.ts:** Access returned object by key
- …
=> [PM-5301] Access Returned Object With Global Key

libs/common/src/platform/services/state.service.ts
When the overlay feature flag is on, the default overlay visibility setting should be set to off (to allow users to opt-in if they wish)
**NOTE:** This is a recreation of https://github.com/bitwarden/clients/pull/7266 to main. There were prettier changes in `main` after this release tag was created, so a cherry-pick brought in a lot of extra style changes we did not want.
=> [pm-5333] Make autofill overlay setting off by default

.github/workflows/build-desktop.yml, .github/workflows/release-desktop-beta.yml
```
```
This PR updates the `build-desktop.yml` and `release-desktop-beta.yml` workflows to properly set `NODE_OPTIONS`.  It cannot be set through `GITHUB_ENV` per GitHub's instructions.
https://github.blog/changelog/2023-10-05-github-actions-node_options-is-now-restricted-from-github_env/
- **.github/workflows/build-desktop.yml:** Deleted the `Set Node options` steps and added a `NODE_OPTIONS` environment variable to the job `env` key.
- **.github/workflows/release-desktop-beta.yml:** Deleted the `Set Node options` steps and added a `NODE_OPTIONS` environment variable to the job `env` key. …
=> Fix setting NODE_OPTIONS in workflows

apps/browser/src/auth/popup/account-switching/account.component.html
- Simply changes the color of the active account status to be green for better visibility.
- `apps/browser/src/auth/popup/account-switching/account.component.html` - add conditional classes if account is the active account
=> [PM-5429] Change Active Account Status to Green

apps/cli/src/commands/serve.command.ts, apps/cli/src/tools/send/commands/remove-password.command.ts, apps/cli/src/tools/send/send.program.ts
```
```
The `accessUrl` returned after removing a password from a send should take into consideration the environment
- **remove-password.command.ts:** Get the `webVaultUrl` and pass it to the `SendResponse`
=> [PM-2424] Return current environment on remove-password CLI command

apps/browser/src/auth/popup/login-decryption-options/login-decryption-options.component.ts, apps/browser/src/auth/popup/utils/post-logout-message-listener.ts
```
```
The `Not you` button on this screen initiates a logout for the current account. If you have an additional account this will mean we switch accounts to the next account. We need to listen for that message and route them appropriately. 
- **apps/browser/src/auth/popup/utils/post-logout-message-listener.ts:** Create a helper listener for listening to post logout messages, this is because I believe this exact logic will be reused to fix a different bug. 
- **apps/browser/src/auth/popup/login-decryption-options/login-decryption-options.component.ts:** Override the `super.logOut` method by starting to listen to messages, doing the super implementation, then waiting until that message comes or we timeout. If the `switchAccountMessage` was sent, then route them to home.
- Please add …
=> [PM-5455] Listen for Finish Message

apps/browser/src/platform/popup/header.component.html, apps/browser/src/platform/popup/header.component.ts, apps/browser/src/tools/popup/generator/generator.component.html, libs/common/src/platform/models/domain/account.ts, libs/common/src/platform/models/domain/enc-string.ts, libs/common/src/platform/services/memory-storage.service.ts, libs/common/src/platform/services/state.service.ts, libs/common/src/vault/models/view/cipher.view.ts, libs/common/src/vault/models/view/login.view.ts
```
```
We had missed an in-memory getter that loses prototype with the new structured clone being used to avoid dead objects.
This would have been an issue for mv3, so we need to adjust behavior at the getter rather than change storage behavior. I'm inspecting the retrieved value and re-applying the appropriate prototype. This is equivalent to what we do with `getDecryptedCiphers`, but without the decorator helper.
I also hide the account switcher in the generator when coming from the add-edit component. It's not relevant there and switching acocunts would result in undefined behavior.
I've audited the other usages of memory objects and it looks like this is our only current one incorrectly accessing potentially prototype-less objects.
**header.component**: add input which allows users …
=> [PM-5468] Ensure prototypes available on memory stored objects

apps/web/src/app/vault/individual-vault/bulk-action-dialogs/bulk-delete-dialog/bulk-delete-dialog.component.html, apps/web/src/app/vault/individual-vault/bulk-action-dialogs/bulk-delete-dialog/bulk-delete-dialog.component.ts, apps/web/src/app/vault/individual-vault/vault.component.ts, apps/web/src/app/vault/org-vault/vault.component.ts
```
```
Bulk deleting collections did not work from org or individual vaults.
* To fix individual vault: the `apiService` call was referencing `this.organization` instead of the local variable `organization`: https://github.com/bitwarden/clients/commit/dbce6014d4b1c50fcbb0392902bc4d99ebe5321d
* To fix the admin vault: the dialog took both `collections` and `collectionIds`. In the org vault, `collections` was not being set. However, these refer to the same collections, so I deleted the duplicate `collectionIds` property and made everyone use the `collections` property instead. https://github.com/bitwarden/clients/commit/17e1ad5b7491d67d63001eb7b51db44114be9317 …
=> [AC-1921] Fix undefined property errors when bulk deleting collections

apps/browser/src/auth/popup/update-temp-password.component.ts, libs/angular/src/auth/components/update-temp-password.component.ts
```
```
Listen to a logout finish message just before sending the `logout` message. 
- **apps/browser/src/auth/popup/update-temp-password.component.ts:** Set the `onSuccessfulChangePassword` action so that it gets ran instead of the default of only sending the logout message. Have that method start listening for finishing messages before calling the logout message.
- **libs/angular/src/auth/components/update-temp-password.component.ts:** Make `Router` available to inherited classes. …
=> [PM-5453] Route on `switchAccountFinish` Message

apps/browser/src/platform/state/background-derived-state.provider.ts, apps/browser/src/platform/state/background-derived-state.ts, apps/browser/src/platform/state/derived-state-service-interactions.spec.ts, apps/browser/src/platform/state/foreground-derived-state.provider.ts, apps/browser/src/platform/state/foreground-derived-state.ts, libs/common/spec/fake-state-provider.ts, libs/common/src/platform/state/derive-definition.ts, libs/common/src/platform/state/derived-state.provider.ts, libs/common/src/platform/state/implementations/default-derived-state.provider.ts, libs/common/src/platform/state/implementations/default-derived-state.spec.ts, libs/common/src/platform/state/implementations/default-derived-state.ts, libs/common/src/platform/state/implementations/default-state.provider.ts, libs/common/src/platform/state/state.provider.ts, libs/common/src/types/state.d.ts
#7290 introduced these types, but during development we switched over to specifying dependencies in type parameters instead of an object. This change meant we no longer needed these `Type` or `ShapeToInstance` types, greatly simplifying the types related to derived state.
=> Remove unnecessary complex types

libs/components/src/menu/menu.component.html
```
```
When a user is a member of a lot of organizations and has a small screen device (or rotated 90 degrees) and want's to select an organization or maybe even add a new organization, that isn't possible because those links in the menu are not visible because they overflow the screen.
This PR simply adds the `tw-overflow-y-auto` class to the menu `div` and will automatically add a scrollbar when needed.
- **libs/components/src/menu/menu.component.html:** adds the `tw-overflow-y-auto` class to the menu `div` to allow auto overflow to add a scrollbar when needed.
| Without scrolling patch |With scrolling patch|
| -------------------------- | -------------------------- |
|![without_scrolling](https://user-images.githubusercontent.com/610450/214311970-6a5a806d-d29e-4da3-9ade-9747f5e250df.gi …
=> [PM-4906] Allow bitmenu to overflow and scroll when needed

apps/browser/README.md, apps/browser/src/popup/settings/settings.component.ts, apps/desktop/src/main/menu/menu.help.ts
```
```
When user clicks on Settings -> Rate the extension menu item, an old version of Chrome Web Store is shown with note that it will be discontinued in January. This small update make sure that user is redirected to a new Web Store review page.
Relates to: https://community.bitwarden.com/t/update-chrome-webstores-link/61529
The only changes are basically two URLs for Chrome and Vivaldi.
- **settings.component.ts:** UpdatedURLs
- **menu.help.ts:** Updated URL
- **README.md:** Updated links
=> [PM-5632] Update Bitwarden extension review URLs

libs/common/src/enums/feature-flag.enum.ts, libs/common/src/vault/services/fido2/fido2-client.service.spec.ts, libs/common/src/vault/services/fido2/fido2-client.service.ts
```
```
Remove the feature flag for storing credentials in the vault now that the feature has been released.
- **fido2-client.service.ts:** Removed feature flag check and restructured conditional to be clearer.
- **fido2-client.service.spec.ts:** Removed tests for feature flag support.
- **feature-flag.enum.ts:** Removed `Fido2VaultCredentials` feature flag as well as `DisplayLowKdfIterationWarningFlag` which was not used in code. …
=> Remove Fido2VaultCredentials feature flag

apps/web/src/app/vault/individual-vault/vault.component.ts
```
```
When opening the add collection dialog from the individual vault be sure to avoid selecting an provider organization. 
We prevented provider organizations from being selectable in https://github.com/bitwarden/clients/pull/5941 but didn't add the same check when opening the dialog initially.
- **apps/web/src/app/vault/individual-vault/vault.component.ts:** Add check for `!o.isProviderUser` when opening the collection dialog. …
=> [PM-5680] Exclude provider orgs when opening the add collection dialog

libs/common/src/platform/state/implementations/default-active-user-state.spec.ts, libs/common/src/platform/state/implementations/default-active-user-state.ts, libs/common/src/platform/state/implementations/default-global-state.spec.ts, libs/common/src/platform/state/implementations/default-global-state.ts, libs/common/src/platform/state/implementations/default-single-user-state.ts
```
```
We rewrote the inner workings of `DefaultActiveUserState` and `DefaultSingleUserState` to rely more on various rxjs offerings instead of rolling our own. This migrates `DefaultGlobalState` to do the same. 
Also, during migrating it we made a decision to not do an inner subscription to `state$` and instead always go and get the data from state ourselves. This was applied to the other states. 
- **libs/common/src/platform/state/implementations/default-active-user-state.spec.ts:** Update expectation of test to show that we do expect a call to update to always go and get state.
- **libs/common/src/platform/state/implementations/default-active-user-state.ts:** Update it to always go to storage on update.
- **libs/common/src/platform/state/implementations/default-global-state.spec.ts:** …
=> Global State Rewrite

apps/browser/src/background/main.background.ts, apps/cli/src/bw.ts, apps/web/src/app/billing/organizations/sm-subscribe-standalone.component.ts, libs/angular/src/services/jslib-services.module.ts, libs/common/src/admin-console/abstractions/organization/organization.service.abstraction.ts, libs/common/src/admin-console/services/organization/organization.service.spec.ts, libs/common/src/admin-console/services/organization/organization.service.ts, libs/common/src/vault/services/sync/sync.service.ts
```
```
Removing this logic from clients as it is now implemented on the API side https://github.com/bitwarden/server/pull/3617
- Removed all ConfigService references that were added to get the Flexible Collections feature flag value
- Removed logic to override the Manager type value and Edit/Delete assigned collections permissions
=> [AC-1893] Removed logic to downgrade Manager roles and remove Edit/Delete any collection permissions for Flexible Collections

apps/web/src/app/vault/components/vault-items/vault-cipher-row.component.html, apps/web/src/app/vault/components/vault-items/vault-cipher-row.component.ts, apps/web/src/app/vault/components/vault-items/vault-items.component.html, apps/web/src/app/vault/components/vault-items/vault-items.component.ts, apps/web/src/app/vault/org-vault/vault.component.html
```
```
The 3 dot menu was missing from the cipher rows in the individual vault. updated logic in individual vault so 3dot menu does not get pushed off page
the boolean logic of `showCollections` for the empty column wasn't enough to address both vaults. Instead added a boolean `viewingOrgVault` from the `org vault component html` to `vault items` to `vault cipher row` 
INDIVIDUAL VAULT
ORG VAULT
ORG VAULT NESTED COLLECTION
=> AC-2057 3dot menu missing in individual vault

apps/browser/src/autofill/popup/settings/autofill.component.ts, apps/browser/src/platform/flags.ts, apps/browser/src/platform/popup/header.component.ts, apps/browser/src/popup/settings/excluded-domains.component.ts, apps/browser/src/popup/settings/options.component.ts, apps/browser/src/popup/settings/settings.component.ts
```
```
Disables account switching specifically for safari, which unfortunately isn't ready. The better place for this is arguably in environment configurations, but I don't want to expand that functionality more than it has to in hopes that this is a rare/one-off occurrence.
=> [PM-5667] Hard code account switching off on Safari

apps/desktop/electron-builder.json
```
```
With the last release we bumped [Electron to V27](https://github.com/bitwarden/clients/pull/7134). With V27 Electron has [dropped support](https://www.electronjs.org/docs/latest/breaking-changes#removed-macos-1013--1014-support) for MacOs 10.13 and 10.14.
This PR bump the LSMinimumSystemVersion to 10.15 which tells the Mac App Store, that the next release will require 10.15 as a min OS version.
=> [PM-5792] Bump LSMinimumSystemVersion to 10.15

apps/desktop/src/auth/lock.component.ts, apps/desktop/src/main/window.main.ts, libs/angular/src/auth/components/lock.component.ts, libs/common/src/platform/abstractions/state.service.ts, libs/common/src/platform/models/domain/account.ts, libs/common/src/platform/services/state.service.ts, libs/common/src/platform/services/system.service.ts
```
```
If "Cancel" is chosen on the biometrics prompt for desktop, a process reload will occur. This process reload unfortunately will prompt biometrics again, resulting in a loop.
This change introduces a flag on disk indicating that biometrics has been cancelled to prevent a second reprompt after process reload.
=> [PM-2772] add flag to deter process reload if cancel is clicked on biometrics

apps/browser/src/autofill/services/autofill-constants.ts, apps/browser/src/autofill/services/autofill.service.spec.ts, apps/browser/src/autofill/services/autofill.service.ts
Autofilling ciphers will sometimes fill values in search inputs with a missing / non-search type attribute
These changes aim to improve overall early disqualification of fields when autofilling. The strategies are progressively broadened with each commit:
2bcec716d881d260d2e57b6bb6309fb78f97b065 - exclude non-standard search inputs from identity autofill
97c5704f40485ea94b82df162de7d017065e1535 - exclude non-standard search inputs from all autofill
e5f457ede6f1b521dfcbe5bc423c19d1dfd6706d - check against excluded login field types when loading password fields
https://github.com/bitwarden/clients/assets/1556494/49564171-6f1c-40aa-99fd-d6baf10a6dbf
https://github.com/bitwarden/clients/assets/1556494/2297c671-9ced-4b7f-a31d-3fbc692803da
Before these changes, we've relied only on …
=> [PM-4437] Bug - Exclude non-standard search inputs from autofill

apps/browser/src/autofill/services/autofill-constants.ts, apps/browser/src/autofill/services/autofill.service.spec.ts, apps/browser/src/autofill/services/autofill.service.ts
- Bug fix
When gathering/finding login fields to fill, we were qualifying fields (in part) by the values of the field attributes. We would then disqualify _attributes_ based on a constant list of values to ignore (e.g. "captcha, "findanything", etc). However, we weren't disqualifying the whole field, so as long as it qualified otherwise (with a later attribute, for example), we'd use it in autofill.
In Paypal's case, they have a field in their login workflow with an `id` value of "splitPasswordCaptcha" and a `placeholder` value of "Enter code" (what ultimately qualifies the field).
This field would be autofilled with TOTP (when it should be left alone, causing the first step of login to fail with an error (see: https://github.com/bitwarden/clients/issues/5915).
These changes update our …
=> [PM-5531] Improve captcha field autofill disqualification

apps/web/src/connectors/duo-redirect.ts
- Bug fix
Changes `duo_code` param to `code`. I tested this the same way as shown in https://github.com/bitwarden/clients/pull/7594
=> Rename Duo Redirect Query Param

apps/browser/src/autofill/services/autofill-constants.ts, apps/browser/src/autofill/services/autofill-overlay-content.service.spec.ts, apps/browser/src/autofill/services/autofill-overlay-content.service.ts, clients.code-workspace
```
```
An [issue was identified](https://github.com/bitwarden/clients/issues/7628) where the inline auto-fill menu can display on `textarea` input fields, even if those fields are not fillable. This behavior on the prod version of the extension can be seen on https://translate.google.com by adding the word `email` to the field. 
This issue presents as a bit more of a nuanced concern, especially when it comes to the fact that we do allow `textarea` fields to be captured within the collect process. By default, we do not fill these `textarea` fields, however. To fill these, a user would have to add a custom element to their cipher, and at that point we qualify it as a fillable field. 
Because of that, for the moment I'm making the decision to move forward with ignoring `textarea` fields …
=> [PM-5806] Remove the Inline Auto-fill Menu From `textarea` Fields

libs/angular/src/vault/components/add-edit.component.ts
- Bug fix
When creating a new cipher, the view errors on access to the `login` property of `cipher`:
- added optional chaining for `cipher` for cases where it is undefined
=> Bugfix - Handle access on undefined cipher properties

libs/common/src/platform/services/cryptography/encrypt.service.implementation.ts
```
```
Another partial fix for https://github.com/bitwarden/clients/issues/1597
When developing https://github.com/bitwarden/clients/pull/6465 I also considered looking at what is bottlenecking the single threaded "decryption" speed when having large (10k+ cipher) vaults, but did not investigate further at the time. When looking at the unlock process in a profiler, the actual decryption did not play a significant role in the unlock time. Instead, there are many smaller overheads here and there (GC's due to many heap allocations, overhead from async await, and others) that cause the slowness during unlock.
This PR addresses one aspect, but there are other gains left to be had.
One small and simple fix is simply replacing a Promise.all with a for loop. While Promise.all would be faster in …
=> [PM-5749] Make cipher decryption faster by replacing promise.all in encrypt.service.implementation

apps/web/src/app/billing/organizations/organization-plans.component.ts
```
```
In self-hosted environments, when adding a new organization, the user encounters a spinning icon and a console error. This was due to the additional call to `changedProduct` in `ngOnInit` without wrapping that call around a check to ensure the environment isn't self-hosted.
- **organization-plans.component.ts:** Preventing call to `changedProduct` if self-hosted
=> [PM-5676] Preventing call to `changedProduct` if self hosted

libs/common/src/tools/generator/username/forwarders/forward-email.spec.ts, libs/common/src/tools/generator/username/forwarders/forward-email.ts
```
```
* Internationalize error strings
* Introduce structural options
* Reduce cyclomatic complexity (It's still high, but lower than the legacy forwarder.)
Split from https://github.com/bitwarden/clients/pull/6924. 
These changes do not require QA testing; they are not yet consumed by external code.
These changes omit i18n messages; those will be included in a later PR.
* `libs/common/src/tools/generator/username/forwarders/forward-email.spec.ts` - unit tests
* `libs/common/src/tools/generator/username/forwarders/forward-email.ts` - replacement forwarder for `libs/common/src/tools/generator/username/email-forwarders/forward-email-forwarder.ts`
=> [PM-5843] add forward email forwarder

libs/common/src/tools/generator/username/forwarders/firefox-relay.spec.ts, libs/common/src/tools/generator/username/forwarders/firefox-relay.ts
```
```
* Internationalize error strings
* Introduce structural options
* Reduce cyclomatic complexity (It's still high, but lower than the legacy forwarder.)
Split from https://github.com/bitwarden/clients/pull/6924. 
These changes do not require QA testing; they are not yet consumed by external code.
These changes omit i18n messages; those will be included in a later PR.
* `libs/common/src/tools/generator/username/forwarders/firefox-relay.spec.ts` - unit tests
* `libs/common/src/tools/generator/username/forwarders/firefox-relay.ts` - replacement forwarder for `libs/common/src/tools/generator/username/email-forwarders/firefox-relay-forwarder.ts`
=> [PM-5842] add firefox relay forwarder

libs/common/src/tools/generator/username/forwarders/fastmail.spec.ts, libs/common/src/tools/generator/username/forwarders/fastmail.ts
```
```
* Internationalize error strings
* Introduce structural options
* Reduce cyclomatic complexity (It's still high, but lower than the legacy forwarder.)
Split from https://github.com/bitwarden/clients/pull/6924. 
These changes do not require QA testing; they are not yet consumed by external code.
These changes omit i18n messages; those will be included in a later PR.
* `libs/common/src/tools/generator/username/forwarders/fastmail.spec.ts` - unit tests
* `libs/common/src/tools/generator/username/forwarders/fastmail.ts` - replacement forwarder for `libs/common/src/tools/generator/username/email-forwarders/fastmail-forwarder.ts`
=> [PM-5841] add fastmail forwarder

libs/common/src/tools/generator/username/forwarders/duck-duck-go.spec.ts, libs/common/src/tools/generator/username/forwarders/duck-duck-go.ts
```
```
* Internationalize error strings
* Introduce structural options
* Reduce cyclomatic complexity (It's still high, but lower than the legacy forwarder.)
Split from https://github.com/bitwarden/clients/pull/6924. 
These changes do not require QA testing; they are not yet consumed by external code.
These changes omit i18n messages; those will be included in a later PR.
* `libs/common/src/tools/generator/username/forwarders/duck-duck-go.spec.ts` - unit tests
* `libs/common/src/tools/generator/username/forwarders/duck-duck-go.ts` - replacement forwarder for `libs/common/src/tools/generator/username/email-forwarders/duck-duck-go-forwarder.ts`
=> [PM-5840] add duck duck go forwarder

apps/web/src/app/core/core.module.ts, apps/web/src/app/platform/web-active-user-state.provider.ts, apps/web/src/app/platform/web-global-state.provider.ts, apps/web/src/app/platform/web-single-user-state.provider.ts, apps/web/src/app/platform/window-storage.service.ts, libs/angular/src/services/injection-tokens.ts, libs/common/spec/fake-state-provider.ts, libs/common/src/platform/state/implementations/default-active-user-state.provider.ts, libs/common/src/platform/state/implementations/default-global-state.provider.ts, libs/common/src/platform/state/implementations/default-single-user-state.provider.ts, libs/common/src/platform/state/key-definition.spec.ts, libs/common/src/platform/state/key-definition.ts, libs/common/src/platform/state/state-definition.ts, libs/common/src/platform/state/state-definitions.spec.ts
```
```
Adds the ability for creators of `StateDefinition` to override the storage location per client type. Currently, this mostly enables creating a state definition like: `new StateDefinition("myState", "disk", { web: "disk-local" });`. This differs from just defining `"disk"` because by default `"disk"` on the web client and stored in session storage. This means that users migrating state from state service with `defaultOnDiskLocalOptions()` will want to use the new overload. This updates the migration matrix to be like such:
| StateService | StateProvider |
| --- | --- |
| `defaultOnDiskOptions()`| `new StateDefinition("state", "disk")`|
| `defaultOnDiskLocalOptions()` | `new StateDefinition("state", "disk", { web: "disk-local" })` |
| `defaultInMemoryOptions()` | `new …
=> [PM-5829] Add `disk-local` option for `web`

apps/web/src/app/vault/core/collection-admin.service.ts, apps/web/src/app/vault/org-vault/vault.component.html
```
```
We were missing a forward slash at the start of the bulk collection access URL. This wasn't a problem locally, but when deploying to a QA cloud environment it means the POST request is sent to `/apiorganizations/collections/bulk-access`.
I also noticed that the bulk access button depends on that flag but not on `organization.flexibleCollections`. I fixed that while I was here. …
=> [AC-2071] Fix bulk collection access API call

libs/common/src/vault/services/cipher.service.ts
```
```
Set the minimum server version that will support vault item encryption to `2024.1.3`, as the final pieces of this will be released with the release on 2/6, which will be server `2023.1.3`.
Server PR: https://github.com/bitwarden/server/pull/3718
Mobile PR: https://github.com/bitwarden/mobile/pull/2959
- **cipher.service.ts:** Updated minimum server version.
=> [PM-5638] Bump minimum server version for vault item encryption

apps/web/src/app/auth/guards/deep-link.guard.ts
```
```
Resolve [PM-5762](https://bitwarden.atlassian.net/browse/PM-5762)
`DeepLinkGuard` - Fix issue in which org invite acceptance was broken due to us not properly checking for the lock url: if an org name or org user email contained lock, then the login redirect url would not persist and take the user to the accept org invite page after login.
- **apps/web/src/app/auth/guards/deep-link.guard.ts:** Check for `/lock` url instead of `lock` text
https://github.com/bitwarden/clients/assets/116684653/7045b792-45ff-40a1-87ac-df4b9fe6075c …
=> Auth/PM-5762 - Fix org invite acceptance not working if user email or org has "lock" in the name

apps/browser/webpack.config.js
```
```
The `path-browserify` dependency needs to be enqueued within the `Webpack` build for the browser extension as a fallback script. This is already done for mv2, so that example can be used to facilitate this inclusion.
This should present as a very small addition to the implementation, both in effort and impact. The inclusion of the package does not seem to cause any verifiable issues with manifest v3.
- **apps/browser/webpack.config.js:** Adding `path-browserify` dependency when build manifest v3.
=> [PM-5877] Update the extension's webpack compilation process to include `path-browserify` in manifest v3

apps/web/src/app/vault/components/collection-dialog/collection-dialog.component.ts
```
```
Add an additional check for the `limitCollectionCreationDeletion` setting when determining if the delete collection button should be shown in collection dialog.
- **apps/web/src/app/vault/components/collection-dialog/collection-dialog.component.ts:** Update the condition to only show the button if both the `manage` flag is true and the `limitCollectionCreationDeletion` setting is disabled. 
- The `this.collection.canDelete(organization)` check performs similar logic (including the check for admins) but doesn't yet have the `manage` flag set when opened in the org vault; so we have to check the collection from the sync data. There is planned worked to reduce this weird behavior in [AC-2084](https://bitwarden.atlassian.net/browse/AC-2084) to include all the collection/cipher …
=> [AC-2115] Hide delete collection button in collection dialog

bitwarden_license/bit-web/src/app/secrets-manager/layout/org-switcher.component.html, libs/components/src/navigation/nav-group.component.html, libs/components/src/navigation/nav-group.component.ts
```
```
Updates the `bit-nav-group` to hide active styles when the component is expanded. 
- **bitwarden_license/bit-web/src/app/secrets-manager/layout/org-switcher.component.html:** Update the `org-switcher` to work with new pattern. Previously, it was hiding active styles for all child nav items. Since the active style of the parent nav group is now hidden, we want to show the active style with the children. If we didn't make this change, active styles would not be shown in the parent or child nav items.
- **libs/components/src/navigation/nav-group.component.ts:** Set the parent `bit-nav-item` to hide active styles when `open` is true.
**New behavior:** 
https://github.com/bitwarden/clients/assets/17113462/7d2b9291-7ac9-4b40-9aa8-21627598284f
- Please add **unit tests** where it makes …
=> [CL-173] hide nav-group active styles when expanded

libs/common/src/platform/state/state-definitions.ts
```
```
Instantiate `StateDefinition` objects for Admin Console services.
Implementation will come in subsequent PRs, but this PR creates state that will be used by `OrganizationService`, `ProviderService`, and `PolicyService`.
1. Create `StateDefinitions` for each admin console service. 
This relates to the following items in Jira:
* [**AC-2008**: Transition `PolicyService` to use …
=> Add state definitions for Admin Console services

libs/components/src/layout/layout.component.html
```
```
The `main` element in `bit-layout` should become a scroll container when it is overflowed. If it doesn't, the sidebar won't appear fixed.
- **libs/components/src/layout/layout.component.html:** Add `tw-overflow-auto` and `tw-h-screen` to `main` el
Before:
https://github.com/bitwarden/clients/assets/17113462/fa79ebc6-ea9e-4f75-9057-9f3b26aa074a
After:
https://github.com/bitwarden/clients/assets/17113462/001f573a-f8f3-49e1-9cde-b225bcd82bdf …
=> [CL-178] contain overflow in bit-layout main content

apps/desktop/src/app/layout/account-switcher.component.ts
```
```
We have a bug in which adding an account when the current account is locked causes an infinite loading screen.  The issue is that clearing state causes the `LockComponent` to respond to the `activeAccount$` observable and trigger `load()`, which in turn attempts to log the user out - since the `activeAccount` does not have any state (it's `null`) and thus has no lock methods.
Instead, we should route the user to `/login` before clearing state, ensuring that `LockComponent` does not respond to the state change.
- **account-switcher.component.ts:** Changed the order of operations on adding a new account to route to `/login` before clearing state.  …
=> [PM-5991] Updated ordering on account switch to route before clearing state

libs/common/src/auth/services/devices-api.service.implementation.ts
```
```
We currently have 2 different `Device-Identifier` headers that we expect on the server:
- `Device-Identifier` on [CurrentContext](https://github.com/bitwarden/server/blob/rc/src/Core/Context/CurrentContext.cs#L64)
- `X-Device-Identifier` on the model for the [known device request](https://github.com/bitwarden/server/blob/rc/src/Api/Models/Request/KnownDeviceRequestModel.cs#L13)
In https://github.com/bitwarden/clients/pull/7807, I added the incorrect header to the request.  This PR addresses that by using the `Device-Identifier`.
I have also created https://bitwarden.atlassian.net/browse/PM-6086 to capture the tech debt to consolidate this with a single header name.
- **devices-api.service.implementation.ts:** Changed header to match the one that the server uses to build the …
=> Modified to use the correct header.

libs/common/spec/fake-state-provider.ts, libs/common/spec/fake-state.ts, libs/common/src/platform/state/implementations/default-active-user-state.provider.spec.ts, libs/common/src/platform/state/implementations/default-active-user-state.provider.ts, libs/common/src/platform/state/implementations/default-state.provider.spec.ts, libs/common/src/platform/state/implementations/default-state.provider.ts, libs/common/src/platform/state/state.provider.ts, libs/common/src/platform/state/user-state.provider.ts
```
```
Currently it's common in the codebase to allow for an optional `userId` parameter while dealing with state. The implication be that a missing userId implies active user.
We intentionally did not build this assumption into state providers, but have not made it very easy to access the currently active user id.
Here, I provide both a re-emission of the currently active ID as well as convenience methods to get and set values in common patterns.
I think the minimum we should do here is the user id re-emit, but I also think the other calls could be useful to help wean us off of the optional userId pattern.
- **activeUser state provider**: re-emit active user id from the account service's `activeAccount$` observable
- **state provider**: 
- re-emit active account provider's new …
=> Allow common get and set operations from state providers

apps/desktop/src/app/services/init.service.ts, apps/desktop/src/main.ts, libs/common/src/platform/abstractions/state.service.ts, libs/common/src/platform/services/state.service.ts, libs/common/src/state-migrations/migrate.ts
```
```
Make it possible to run migrations in desktops main process.
- **apps/desktop/src/app/services/init.service.ts:** Don't run migrations during state service init in `InitService` since the main process should be running them instead.
- **apps/desktop/src/main.ts:** Run migrations first, and then do the rest of the existing steps.
- **libs/common/src/platform/abstractions/state.service.ts:** Add optional `InitOptions` to `init` method.
- **libs/common/src/platform/services/state.service.ts:** Respect `runMigrations` choice and instead check the migrations are complete if they do not want migrations ran.
- **libs/common/src/state-migrations/migrate.ts:** Add method for waiting for migrations to complete by checking the stateVersion piece of state.
- Please add **unit tests** where it …
=> [PM-6032] Run migrations in main process

apps/web/src/app/vault/components/collection-dialog/collection-dialog.component.html
> When creating/viewing a collection from the individual vault or organization tab, the Group label is missing from the Group/Member permission table. 
- **apps/web/src/app/vault/components/collection-dialog/collection-dialog.component.html**: Moved the `v1` flag check down to the necessary child `span`. Replaced with `organization.flexibleCollections` check.
=> [AC-2147] Show grant collection access helper text

libs/common/src/vault/services/vault-settings/vault-settings.service.ts
```
```
During the migration of the enable passkeys state to the state provider framework, the default option setting was set to `false` instead of `true.`
=> [PM-6124] Default Passkey Setting not correct

apps/desktop/src/app/accounts/settings.component.ts, apps/desktop/src/app/services/services.module.ts, apps/desktop/src/auth/lock.component.spec.ts, apps/desktop/src/auth/lock.component.ts, apps/desktop/src/platform/services/electron-crypto.service.spec.ts, apps/desktop/src/platform/services/electron-crypto.service.ts, libs/common/src/platform/biometrics/biometric-state.service.spec.ts, libs/common/src/platform/biometrics/biometric-state.service.ts, libs/common/src/platform/biometrics/biometric.state.spec.ts, libs/common/src/platform/biometrics/biometric.state.ts
```
```
#7761 removed stored state for requiring password on start for biometric and just used the existence of a client key half.
The thing is, we want to persist that behavrior through logouts, but don't want to persiste the client key half. This requires use of state, so this PR adds that state back in.
A lot of this reverts component and module work in #7761, while updating to `biometricStateService`.
=> [PM-5537] Persist require password on startup through logout

apps/web/src/app/vault/core/views/collection-admin.view.ts
```
```
The `CollectionAdminView` and `CollectionView` had started to diverge causing inconsistent behaviors when flexible collections was enabled. This updates the `CollectionAdminView` to also consider the `manage` flag when FC is enabled. With this change the delete button in the collection dialog now shows correctly in the individual vault.
- **apps/web/src/app/vault/core/views/collection-admin.view.ts:** Add `|| this.manage` to the `CanDelete` and `CanEdit` helpers. …
=> [AC-2115] Update admin view to also collection check manage flag

libs/common/src/platform/state/derive-definition.ts, libs/common/src/platform/state/implementations/default-derived-state.spec.ts, libs/common/src/platform/state/implementations/default-derived-state.ts
```
```
Adds option to ensure that memory storage is clear or derived values on cleanup. This is useful since parent state emissions are not recorded unless something is subscribed to derived state. This ensures no cached data remains.
=> [PM-6156] Add derive option to clear state after cleanup

libs/components/src/navigation/nav-group.component.ts, libs/components/src/navigation/nav-group.stories.ts, libs/components/src/navigation/nav-item.component.html, libs/components/src/navigation/nav-item.component.ts
```
```
If the route associated with a `bit-nav-item` becomes active, it should open parent `bit-nav-group`s.
- **libs/components/src/navigation/nav-group.component.ts:** 
- Inject parent `bit-nav-group`
- bubble `open` change to parent
- refactor `ContentChildren` to use abstract base class injection token; this prevents a circular reference between nav group and item
- **libs/components/src/navigation/nav-item.component.ts:**
-  Inject parent `bit-nav-group`
-  call parent open method when route becomes active
- rename `active` to `isActive` to be more consistent with `ActiveRoute` props
- **libs/components/src/navigation/nav-group.stories.ts:**
- replace `RouterTestingModule` with actual router, so we can better test active route styles in Storybook. 
`bit-nav-group` with child active …
=> [CL-179][PM-6011] open parent bit-nav-groups when bit-nav-item becomes active

libs/common/spec/fake-account-service.ts, libs/common/src/platform/state/implementations/default-state.provider.spec.ts, libs/common/src/platform/state/implementations/default-state.provider.ts, libs/common/src/platform/state/state.provider.ts
```
```
Updates `getUserState$` helper method implemented in #7824 to not update the user being observed as active user changes.
Internal discussions revealed this to be somewhat unexpected and an observable that watches the state of whatever user was active at the time of the call is more consistent to expectations.
=> Prefer get methods to return single user states unless specified active

.github/workflows/build-web.yml
```
```
This PR adds a trigger to the `Build Web` workflow so that it builds when we publish a new release.
- **.github/workflows/build-web.yml:** Add `release` trigger and fix `IMAGE_TAG` to allow both branches (`refs/heads/main`) and tags (`refs/tags/web-v2024.2.0`).
=> DEVOPS-1788 - Allow Build Web workflow to trigger on the publish of a new release

libs/common/spec/fake-state-provider.ts, libs/common/spec/fake-state.ts, libs/common/src/platform/state/implementations/default-active-user-state.spec.ts, libs/common/src/platform/state/implementations/default-active-user-state.ts, libs/common/src/platform/state/implementations/default-state.provider.ts, libs/common/src/platform/state/state.provider.ts, libs/common/src/platform/state/user-state.ts
This allows us to ensure that linked updates all go to the same user without risking active account changes in the middle of an operation.
```
```
Small interface change that returns the impacted userId for active user updates.
This allows complex update methods to ensure that they update the same UserId for the entire transaction.
I didn't find any usages of the return value other than tests, which were updated.
=> ActiveUserState Update should return the userId of the impacted user.

libs/components/src/popover/popover.stories.ts
```
```
The `InitiallyOpen` story for `bitPopover` is flaky and will trigger erroneous visual diffs. This PR removes it from Chromatic snapshot testing.
=> [CL] exclude popover story from Chromatic

.github/workflows/build-desktop.yml
```
```
This PR adds the build number as a GitHub step summary for all of the MacOS jobs in the Build Desktop workflow.
- **.github/workflows/build-desktop.yml:** Add build number to GitHub step summary.
=> Add Build Number as Step Summary for MacOS jobs in Build Desktop workflow

apps/web/src/app/admin-console/organizations/settings/account.component.html, apps/web/src/app/admin-console/organizations/settings/account.component.ts, apps/web/src/locales/en/messages.json
> We want to emphasize that this action is irreversible, hence the addition of the dialog after the user selects Turn on.
- **account.component.html**: Replaced `[bitAction]` with `(click)` listener for opening the dialog instead
- **account.component.ts**: Replaced existing handler with method to launch the simple dialog. Constructed the dialog with the necessary options, including an accept action that will show a spinner until the promise resolves.
- **messages.json**: Added title and content dialog strings
https://github.com/bitwarden/clients/assets/26154748/4e765ac7-2a2d-4522-bb5e-fafa3b34aaaa …
=> [AC-2113] Confirmation dialog for enabling collection enhancements

libs/common/src/tools/generator/password/password-generation.service.ts
```
```
The password policy generator failed to load the passphrase evaluator because it used a truthy check to load the evaluator. It should have used an explicit check for `options.type`.
* `libs/common/src/tools/generator/password/password-generation.service.ts` - compare `options.type === "password"`.
=> [PM-5736] check credential type explicitly when loading evaluator

apps/desktop/desktop_native/Cargo.lock, apps/desktop/desktop_native/Cargo.toml
```
```
See https://github.com/bitwarden/clients/issues/6812.
Confirmed issue is still present without this change. Confirmed works on Wayland and X11 (via XWayland) using Sway WM, with this change. No testing performed on other platforms.
=> [PM-5663] Fix copy to clipboard not working on Wayland

libs/common/src/tools/generator/key-definition.spec.ts, libs/common/src/tools/generator/key-definitions.ts, libs/common/src/tools/generator/username/index.ts, libs/common/src/tools/generator/username/subaddress-generator-options.ts, libs/common/src/tools/generator/username/subaddress-generator-strategy.spec.ts, libs/common/src/tools/generator/username/subaddress-generator-strategy.ts
```
```
Implement a generator strategy for generating subaddresses in the username generator.
The objects in this PR are not consumed by the application and thus do not require QA.
- `libs/common/src/tools/generator/key-definitions.ts` - add subaddress key definition
- `libs/common/src/tools/generator/key-definitions.spec.ts` - unit tests
- `libs/common/src/tools/generator/username/index.ts` - publish strategy
- `libs/common/src/tools/generator/username/subaddress-generator-options.ts` - introduce options
- `libs/common/src/tools/generator/username/subaddress-generator-strategy.spec.ts` - introduce strategy
- `libs/common/src/tools/generator/username/subaddress-generator-strategy.ts` - unit tests
=> [PM-5972] add subaddress generator strategy

libs/common/src/tools/generator/key-definition.spec.ts, libs/common/src/tools/generator/key-definitions.ts, libs/common/src/tools/generator/username/catchall-generator-options.ts, libs/common/src/tools/generator/username/catchall-generator-strategy.spec.ts, libs/common/src/tools/generator/username/catchall-generator-strategy.ts, libs/common/src/tools/generator/username/index.ts
```
```
Implement a generator strategy for generating catchall addresses in the username generator.
The objects in this PR are not consumed by the application and thus do not require QA.
- `libs/common/src/tools/generator/key-definitions.ts` - add catchall key definition 
- `libs/common/src/tools/generator/key-definitions.spec.ts` - unit tests, and fix a typo missed in the EFF word list PR
- `libs/common/src/tools/generator/username/index.ts` - publish strategy
- `libs/common/src/tools/generator/username/catchall-generator-options.ts` - introduce options
- `libs/common/src/tools/generator/username/catchall-generator-strategy.spec.ts` - introduce strategy
- `libs/common/src/tools/generator/username/catchall-generator-strategy.ts` - unit tests
=> [PM-5973] add catchall generation strategy

libs/common/src/admin-console/services/provider.service.spec.ts, libs/common/src/admin-console/services/provider.service.ts
```
```
This PR takes steps toward supporting the new `StateProvider` APIs in the `ProviderService'.
The focus of this change is to add and test a key definition for the only data point owned by this service: the `providers` list.
> 💡 This PR does not have any impact on the system at large. The key definition and `StateProvider` will be implemented in follow up steps.
1. Add a key definition to `provider.service.ts` for `PROVIDERS` and test to assert it deserializes properly.
* Jira work item: [`AC-2010`](https://bitwarden.atlassian.net/browse/AC-2010?atlOrigin=eyJpIjoiNjAxZWUxNjRkNjdhNDQ4MWExOWE5ZGQ0NTU3NDM3MTAiLCJwIjoiaiJ9)
* https://github.com/bitwarden/clients/pull/7781 does the same thing for `OrganizationService`, and is a good source to compare to for reviews. That said, it has a …
=> Add a `KeyDefinition` for `providers`

apps/web/src/connectors/duo-redirect.ts
- Bug fix
Refactors the `duoHandOffMessage` feature. The handoff message must be added by clients to allow for translations.
The key to this implementation is in parsing a number out of the translated `message` and using that as the starting point for the countdown timer. Parsing the number this way allows us to leave the translated text in tact during the countdown. This way the client does not have to split up the `message` text into several translations, such as:
`['This window will automatically close in', 5, 'seconds']`
...which would cause bad translations in languages that swap word order.
https://github.com/bitwarden/clients/assets/102181210/860dc80c-6ff9-4e40-8d1d-74d428ded5b7
https://github.com/bitwarden/clients/assets/102181210/cfe3ece4-c1cb-4c6c-8d5f-91d937907f22 …
=> Duo Redirect Handoff Message Fix

libs/common/src/platform/abstractions/state.service.ts, libs/common/src/platform/models/domain/account.ts, libs/common/src/platform/services/state.service.ts
```
```
Our documentation team is looking to document what we store in local storage on the web client.  In reviewing that, I came upon `entityId` and `entityType` state getters and setters.  Upon further investigation, these have no references in code outside of their definitions in `StateService`.
- **state.service.ts:** Removed unused state references.
=> [PM-6241] Remove unused entityId and entityType state

.github/CODEOWNERS, apps/web/src/app/layouts/header/web-header.component.html, apps/web/src/app/layouts/header/web-header.component.ts, apps/web/src/app/layouts/header/web-header.stories.ts, apps/web/src/app/layouts/header/web-layout-migration-banner.service.ts
```
```
Components should never access state directly. Business logic should be abstracted behind a service. (This makes refactoring easier and mocking more direct--see the changes to the associated story.)
This PR:
- updates the _web layout migration banner_ to interact with a new service.
- adds CL as codeowner for the web header components, which did not previously have one.
No visual changes. …
=> move web layout migration banner logic into a service

apps/browser/src/popup/scss/base.scss, libs/components/src/layout/layout.component.html, libs/components/src/tw-theme.css
```
```
Fixes two issues related to CDK virtual scroll:
- virtual scroll containers will clip their content when scrolling if a parent element has height set to `100vh`
- when opening a dialog that utilizes scroll blocking, virtual scroll containers will change scroll position
- **libs/components/src/layout/layout.component.html:** Update layout css to not use `100vh`. Instead, the intended style is achieved through the sidebar having `position: sticky` and unsetting `left` 
- **libs/components/src/tw-theme.css:** override `.cdk-global-scrollblock` to not use position fixed
- **apps/browser/src/popup/scss/base.scss:** remove `.cdk-global-scrollblock` override because it is now capture in `tw-theme.css`.
I tested these changes alongside #7981 and #6957 to verify that `bit-layout`, …
=> [CL-192][CL-193] fix virtual scroll

apps/desktop/src/main/menu/menu.view.ts, apps/desktop/src/main/window.main.ts
```
```
Disable devtools when not running the application in development mode. Of note is that our `isDev` function can be enabled with an environment variable and we should evaluate if we want `isDev` to use https://www.electronjs.org/docs/latest/api/app#appispackaged-readonly instead.
- **apps/desktop/src/main/menu/menu.view.ts:** Hide menu item
- **apps/desktop/src/main/window.main.ts**: Only allow devtools in dev mode
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessi …
=> [PM-6006] Restrict desktop devtools to dev mode only

libs/common/src/platform/services/state.service.ts
```
```
Speed up the CLI list items command (see issue https://github.com/bitwarden/clients/issues/7742)
- **state.service.ts** : Only call GetGlobals() when we actually need them
Since we only need it as a backup if `accountVaultTimeoutAction` is null/undefined, there should be no need to call this function every time.
While the overhead may seem trivial at first glance, it can add up to a massive increase in runtime when the function is called repeatedly in quick succession (e.g. when running `bw list items` where it is executed once for every item).
In my concrete case this change leads to a 25x speedup.
Before:
```
❯ time node build/bw.js list items > /dev/null
node build/bw.js list items > /dev/null  14.33s user 4.59s system 23% cpu 1:21.04 total
```
After:
```
❯ time node …
```
=> [PM-6163] Speed up list items command - Only call GetGlobals() when we actually need them

apps/web/src/app/billing/organizations/organization-plans.component.ts
In `selectablePlans`, optional chaining is used, but no fallback is provided in undefined cases, resulting in errors in the subsequent sort:
https://github.com/bitwarden/clients/blob/main/apps/web/src/app/billing/organizations/organization-plans.component.ts#L291
This case can be seen by visiting https://localhost:8443/#/create-organization of a self-hosted instance
=> [PM-6381] Bugfix- handle org plans uncovered undefined case

apps/browser/src/vault/fido2/webauthn-utils.ts
```
```
Change `authenticator-attachment` from `cross-platform` to `platform` because this is a more appropriate value.
=> [PM-4935] Change authenticator-attachment to platform

apps/web/src/app/vault/individual-vault/vault-filter/components/link-sso.directive.ts
```
```
The link-sso component has a couple of properties set in its constructor. Unfortunately this means that whenever Auth updates the base component dependencies, vault has to review the PR since the link-sso constructor needs to be updated.
Properties outside the constructor are treated the same in the generated JS. `window.location.origin` will also work as seen below:
Auth will do its best to not use derived properties on the base class that could cause issues:
```
class Parent {
constructor() {
this.hi = "hi";
this.greeting = this.hi + " parent"
}
}
class Child extends Parent {
constructor() {
super();
this.hi = "jake";
}
}
var k = new Child();
console.log(k.greeting);
// "hi parent"
``` …
=> Remove constructor from link-sso

apps/browser/jest.config.js, apps/browser/src/platform/services/browser-crypto.service.ts, apps/browser/src/platform/services/browser-state.service.spec.ts, apps/browser/src/popup/services/services.module.ts, libs/common/spec/fake-account-service.ts, libs/common/spec/fake-state-provider.ts, libs/common/src/auth/abstractions/account.service.ts, libs/common/src/auth/services/account.service.spec.ts, libs/common/src/auth/services/account.service.ts, libs/common/src/auth/services/device-trust-crypto.service.implementation.ts, libs/common/src/auth/services/device-trust-crypto.service.spec.ts, libs/common/src/platform/abstractions/crypto.service.ts, libs/common/src/platform/abstractions/state.service.ts, libs/common/src/platform/models/domain/account.ts, libs/common/src/platform/services/crypto.service.spec.ts, libs/common/src/platform/services/crypto.service.ts, libs/common/src/platform/services/key-state/user-key.state.ts, libs/common/src/platform/services/state.service.ts, libs/common/src/platform/state/state-definitions.ts
```
```
- Migrates in-memory user key to state providers.
- Creates new crypto service for browser rather than taking if from the background 🥳 
- Adds the concept of a downgrade-only update to authentication status. This is important because we don't want to have to worry about the ordering of calls that cause lock vs logout.
- ❓ **Should we change lock/unlock to be a boolean `isUnlocked` and logged out/ logged in to a `hasToken` boolean? The observable could then calculate the authentication status if we feel that's still a useful tool.** @jlf0dev your input would be valuable here.
- **browser services module**: Creates new crypto service and crypto function service specific to the foreground.  The crypto service's factory is to register crypto service and encrypt service to the …
=> Ps/pm 5533/migrate decrypted user key

apps/web/src/app/vault/org-vault/vault.component.ts, libs/common/src/admin-console/models/domain/organization.ts
```
```
Fixes a couple edge cases for Custom Users with `editAnyCollection` and `deleteAnyCollection` permissions and cleans up some feature flagging logic that was leaking FC functionality to non-FC orgs when the V1 flag is enabled.
Related Server PR: https://github.com/bitwarden/server/pull/3837
Update the `canEditAllCiphers()` method to allow custom users with the `editAnyCollection` permission to always be able to edit any cipher, regardless of the collection management setting that restricts admins/owners.
_I recommend reading each commit to get a better understanding of why each line/section was modified._
- Update the V1 flexible collections flag check to include a check to ensure the organization has migrated to FC.
- The `editableCollections$` observable now re-uses the …
=> [AC-2195] Fixes for FC V1 for Custom Users

apps/web/src/app/vault/org-vault/vault.component.html
```
```
The `vault-items` component has a `viewingOrgVault` input that should be set to true in the AC. It not being set causes the table row to have fewer cells then expected. 
- **apps/web/src/app/vault/org-vault/vault.component.html:** set `viewingOrgVault` to true in template of `app-org-vault`
After: 
Before:
(Notice misalignment at end of row item)
=> [PM-6450] add missing table cell to vault table in AC

apps/browser/src/vault/popup/components/vault/add-edit.component.html
Add fixed-width class to icons so they take up the same width as their siblings
| --- | --- |
| ![Screenshot 2024-02-23 at 12 16 16 PM](https://github.com/bitwarden/clients/assets/1556494/c699b2cb-a94c-4c51-a7be-abd016cdee21) | ![Screenshot 2024-02-23 at 12 13 36 PM](https://github.com/bitwarden/clients/assets/1556494/2ef92071-1c1b-4310-a440-44c5180874be) |
=> [PM-6391] Add "fixed-width" class to view icons

apps/cli/src/bw.ts
```
```
Removes erroneous reference to biometric state from CLI, which doesn't have any biometric capability.
=> [PM-6476] Remove biometrics from CLI

apps/browser/src/autofill/background/service_factories/badge-settings-service.factory.ts, apps/browser/src/background/main.background.ts, apps/browser/src/platform/listeners/update-badge.ts, apps/browser/src/popup/settings/options.component.ts, libs/angular/src/services/jslib-services.module.ts, libs/common/src/autofill/services/badge-settings.service.ts, libs/common/src/platform/abstractions/state.service.ts, libs/common/src/platform/models/domain/account.ts, libs/common/src/platform/services/state.service.ts, libs/common/src/platform/state/state-definitions.ts, libs/common/src/state-migrations/migrate.ts, libs/common/src/state-migrations/migrations/18-move-autofill-settings-to-state-providers.spec.ts, libs/common/src/state-migrations/migrations/25-move-clear-clipboard-to-autofill-settings-state-provider.spec.ts, libs/common/src/state-migrations/migrations/26-move-badge-settings-to-state-providers.spec.ts, libs/common/src/state-migrations/migrations/26-move-badge-settings-to-state-providers.ts
- Implement Badge Settings state provider
- migrate `disableBadgeCounter` user setting to badge settings state provider
- Created Badge Settings state service
- Replaced instances of state now handled by the Badge Settings service with their appropriate counterparts
- Created migration script to upgrade or rollback state storage changes
- `disableBadgeCounter` has been renamed with the "enabled" prefix, and its call-site logic appropriately inverted.
=> [PM-5568] Implement Badge Settings state provider

apps/desktop/src/main.ts, apps/desktop/src/platform/main/biometric/biometrics.service.spec.ts, apps/desktop/src/platform/main/biometric/biometrics.service.ts
```
```
Remove extra stateService parameters. Because we're loading the `BiometricWindowsMain` with a dynamic `require` the service was loaded as `any` and not type checked, causing the extra stateService param was being interpreted as a logService and causing errors.
=> [PM-6495] Remove extra parameters in biometrics constructors

libs/common/src/platform/services/crypto.service.spec.ts, libs/common/src/platform/services/crypto.service.ts
```
```
Disk state should only be cleared if memory only is not specified. This cleans up that logic to make the issue more clear, but ultimately it's about only setting disk if `!memoryOnly`.
These clear methods now have pretty thorough tests around their parameters
=> Fix clear keys state logic

apps/browser/src/popup/services/services.module.ts
```
```
Reverted the change in https://github.com/bitwarden/clients/pull/7970 that updated `CryptoService` DI to remove the reliance on `getBgService`.  This is still necessary until further state provider migrations are complete.
- **services.module.ts:** Added back use of `getBgService`.
=> Updated CryptoService DI to use getBgService again

libs/components/src/radio-button/radio-button.stories.ts, libs/components/src/radio-button/radio-group.component.html
```
```
The font size of the radio group legend was incorrect and did not match design specifications. This PR updates the size.
- **radio-button.stories.ts:** Also added `html` comment for editor support for the template string, which caused a couple formatting changes
**Before (prod)**
Web
Storybook
**After (local)**
Web
Storybook
=> [CL-170] Fix size of radio group legend

libs/common/src/vault/services/fido2/fido2-authenticator.service.spec.ts, libs/common/src/vault/services/fido2/fido2-authenticator.service.ts
```
```
Remove incrementing counter for new passkeys. Will help us in the future with export/import, improving performance, etc.
Note: Older clients will still increment these new passkeys and "activate" the counter incrementing function. This is ok. Browser extensions are usually updated fairly quickly and so the amount of passkeys that this happens to should be limited.
- Only increment counter if stored value is larger than zero …
=> [PM-5725] New passkeys should always return 0 as counter value

apps/browser/src/background/main.background.ts, apps/cli/src/bw.ts, apps/desktop/src/app/app.component.ts, apps/web/src/app/core/state/state.service.ts, libs/angular/src/services/jslib-services.module.ts, libs/common/src/platform/abstractions/state.service.ts, libs/common/src/platform/models/domain/account.ts, libs/common/src/platform/services/state.service.ts, libs/common/src/platform/state/state-definitions.ts, libs/common/src/state-migrations/migrate.ts, libs/common/src/state-migrations/migrations/15-move-folder-state-to-state-provider.spec.ts, libs/common/src/state-migrations/migrations/26-revert-move-last-sync-to-state-provider.spec.ts, libs/common/src/state-migrations/migrations/26-revert-move-last-sync-to-state-provider.ts, libs/common/src/vault/abstractions/sync/sync.service.abstraction.ts, libs/common/src/vault/services/sync/sync.service.ts
commit 1405fc22ccb55469f220a4e5b8eae0713646af26
Author: Matt Gibson <mgibson@bitwarden.com>
Date:   Thu Feb 29 18:24:35 2024 -0500
Fix missing type import
commit fd38b06ad83df7d6a13df0a2eaf5ea324ef4a34a
Author: Matt Gibson <mgibson@bitwarden.com>
Date:   Thu Feb 29 17:57:34 2024 -0500
Update ordering of badge settings migrator to be consistent with `rc`, which was cut with only up to version 25
commit fcbb39fe3e1e58c7d431b57a7aedcaa785fd9162
Author: Matt Gibson <mgibson@bitwarden.com>
Date:   Thu Feb 29 17:15:01 2024 -0500
Prefer revert migrations to noop
this revert avoids the need to change behavior between released vs unreleased migrations and keeps some dangerous code out of the repo :success:
commit 48aac760c4f5cc50a88b97eb1857bba4e45671cb
Author: Matt Gibson <mgibson@bitwarden.com> …
=> Squashed commit of the following:

apps/web/src/app/admin-console/organizations/layouts/organization-layout.component.ts, apps/web/src/app/layouts/product-switcher/product-switcher-content.component.ts
```
```
- `PM-6584` When a user is part of only one org, and that org is deactivated, they do not see the admin console in the product switcher.
- `PM-6632` Users with admin custom permissions cannot see the organization in the organization switcher
- **apps/web/src/app/layouts/product-switcher/product-switcher-content.component.ts:** Previously, we checked if an organization is enabled to determine the organization set to `acOrg`variable. I have updated the logic by removing the `enabled` condition. The admin console product can now be included in the product switcher for deactivated organizations.
- **apps/web/src/app/admin-console/organizations/layouts/organization-layout.component.ts:** Switched the `orgFilter` to use the helper function `canAccessOrgAdmin`.
***Before*** …
=> [PM-6584] [PM-6632] [Defects] Vertical Vault Refresh Product Switcher

libs/common/spec/fake-state-provider.ts
```
```
Include storage location in cache key for fake state. `states` is publicly exposed but wasn't used in any tests.
The storage location is already used in the cache key for the real state providers. 
- Use storage location in cache key.
=> Include Storage Location In Fake Cache Key

.github/workflows/deploy-web.yml
```
- Build/deploy pipeline (DevOps)
```
Switch to using hash comparison instead of name + timestamp for azcopy. I'm hoping that this will fix DEVOPS-1844
- **.github/workflows/deploy-web.yml:** Add in `--compare-hash` flag
Successful test run: https://github.com/bitwarden/clients/actions/runs/8163323877
=> azcopy - Switch hash comparison from timestamp

apps/browser/src/vault/fido2/browser-fido2-user-interface.service.ts, apps/browser/src/vault/popup/components/fido2/fido2.component.ts, libs/common/src/vault/abstractions/fido2/fido2-user-interface.service.abstraction.ts, libs/common/src/vault/services/fido2/fido2-authenticator.service.spec.ts, libs/common/src/vault/services/fido2/fido2-authenticator.service.ts
```
```
When creating a passkey and a new vault item, we want to set `name` to be `rp`'s name value (`rp.name`). If the `rp` does not provide a name then we save rp.id which is the url
(see the "target" name in the extension)
|Client| Before      | After |
| ----------- | ----------- | ----------- |
|Safari | ![Screenshot 2024-02-15 at 2 42 18 PM](https://github.com/bitwarden/clients/assets/14082576/4910a986-342f-483f-a409-f06d15c426be) |  <img width="506" alt="Screenshot 2024-02-16 at 12 34 27 PM" src="https://github.com/bitwarden/clients/assets/14082576/efccd03b-6a48-4ddb-b63e-77bc0076343b">|
|Firefox | |<img width="434" alt="Screenshot 2024-02-16 at 12 06 11 PM" src="https://github.com/bitwarden/clients/assets/14082576/0a7666d2-4ea …
=> [PM-4882] Passkeys: funnel rp name or id to the cipher name on save

apps/web/src/app/vault/individual-vault/vault-onboarding/vault-onboarding.component.html
```
```
Remove logic for the import data text field. Keeping only the string `If you don’t have any data to import, create a new item instead.` Dynamic text logic will be applied in future ticket [PM-5335](https://bitwarden.atlassian.net/browse/PM-5335)
[PM-5335]: https://bitwarden.atlassian.net/browse/PM-5335?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> change text for import data field in onboarding vault

apps/browser/src/autofill/background/notification.background.ts, apps/browser/src/autofill/background/overlay.background.spec.ts, apps/browser/src/autofill/background/overlay.background.ts, apps/browser/src/autofill/browser/context-menu-clicked-handler.spec.ts, apps/browser/src/autofill/browser/context-menu-clicked-handler.ts, apps/browser/src/autofill/browser/main-context-menu-handler.spec.ts, apps/browser/src/autofill/browser/main-context-menu-handler.ts, apps/browser/src/autofill/content/autofill-init.spec.ts, apps/browser/src/autofill/overlay/iframe-content/autofill-overlay-iframe.service.spec.ts, apps/browser/src/autofill/overlay/iframe-content/autofill-overlay-iframe.service.ts, apps/browser/src/autofill/overlay/pages/button/autofill-overlay-button.ts, apps/browser/src/autofill/overlay/pages/list/autofill-overlay-list.ts, apps/browser/src/autofill/overlay/pages/shared/autofill-overlay-page-element.ts, apps/browser/src/autofill/popup/settings/autofill.component.ts, apps/browser/src/autofill/services/autofill-overlay-content.service.spec.ts, apps/browser/src/autofill/services/autofill-overlay-content.service.ts, apps/browser/src/autofill/services/autofill.service.spec.ts, apps/browser/src/autofill/services/autofill.service.ts, apps/browser/src/autofill/services/insert-autofill-content.service.spec.ts, apps/browser/src/autofill/services/insert-autofill-content.service.ts, apps/browser/src/autofill/utils/autofill-overlay.enum.ts, apps/browser/src/background/runtime.background.ts, apps/browser/src/popup/settings/options.component.ts, apps/browser/src/vault/popup/components/vault/current-tab.component.ts, apps/browser/tsconfig.json, libs/common/src/autofill/constants/index.ts, libs/common/src/autofill/services/autofill-settings.service.ts, libs/common/src/autofill/types/index.ts, libs/common/src/state-migrations/migrations/18-move-autofill-settings-to-state-providers.ts, libs/common/src/state-migrations/migrations/25-move-clear-clipboard-to-autofill-settings-state-provider.ts
- Bug fix
After the [Autofill Settings state migration](https://github.com/bitwarden/clients/pull/7767), the org policy for the autofill on page load setting was not being properly retrieved. This resulted in the default value of the policy being disabled.
This has been addressed by proxying a request to the policy service for the `ActivateAutofill` (`11`) policy from the autofill settings service. Additionally, state has been added to track the policy toast display, as the policy state was being used to track the toast state in the original code (conflation of concerns). Unaddressed, this would result in the policy state being overwritten and not being used after the first load (e.g. the user could change the setting and …
=> [AC-2248][PM-5352] Bugfix - Fix non-working policy state in autofill settings service

libs/common/src/state-migrations/migrate.ts
```
```
Developers will often work on a state migration in one branch then context switch to another branch that doesn't have that state migration. Because we don't do migrations in the desktop renderer and instead attempt to wait for their completion it would think the migrations weren't completed before bailing out after waiting 8 seconds. If we consider `stateVersion >= CURRENT_VERSION` it will tell the caller that migrations have completed sooner. The higher state version is unlikely to have any considerable issue for the developer. Both @MGibson1 and @eliykat have reported this happening to them. …
=> Consider Higher `stateVersion` "ready"

apps/browser/src/background/main.background.ts, apps/browser/src/popup/services/services.module.ts
```
```
Removes usage of `getBgService` by reusing storage that is created for angular. This is equivalent to what background does today, but segregates the services by execution context
=> Use existing angular storage service for browser's secure storage

libs/common/spec/fake-state-provider.ts, libs/common/src/platform/state/state.provider.ts
```
```
I forgot to include `UserKeyDefinition` into the union for the methods to return the fakes. This makes it hard to write tests with the new key definition.
=> [PM-6404] Add `UserKeyDefinition` to union

libs/common/src/autofill/services/autofill-settings.service.ts
- Bug fix
If the user has never explicitly/manually set the "Copy TOTP automatically" option, we don't have a stored setting for it. When this is the case, we defer to the default setting value. In this case it's "false" when it should be "true".
The issue should go away if the user sets the setting, but if they don't (or if they reinstall the extension or otherwise clear state), it will remain at the default value (off).
`autoCopyTotp` originates from `disableAutoTotpCopy` in the old state service (before https://github.com/bitwarden/clients/pull/7767):
in that work, call sites and state migration logic were inverted to allow the setting to drop the "disable" prefix, but the default value for the setting was left at "false" when it should have been updated to "true" (the original …
=> [PM-6740] Fix default value for autoCopyTotp

libs/common/spec/fake-state-provider.ts, libs/common/src/platform/abstractions/crypto.service.ts, libs/common/src/platform/services/crypto.service.spec.ts, libs/common/src/platform/services/crypto.service.ts
```
```
It's possible to test user key presence without an active user due to things like guard services. This hardens crypto service against these kind of usages.
=> Fix and test hasUserKey implementation

apps/web/src/app/admin-console/organizations/members/components/bulk/bulk-remove.component.ts, apps/web/src/app/admin-console/organizations/members/components/bulk/bulk-restore-revoke.component.ts
```
```
currently, when revoking or removing users in orgs that are not using SSO w/ Trusted Devices, or Key Connector, they are given the details column with a warning stating "user does not have a master password" for invited users. While that is technically correct, the users do not need to be warned about this.
- apps/web/src/app/admin-console/organizations/members/components/bulk/bulk-remove.component.ts
- apps/web/src/app/admin-console/organizations/members/components/bulk/bulk-restore-revoke.component.ts
changes for both files were the same. added a check to verify the User Status is greater than 0 in addition to the existing HasMasterPassword check
Before:
After: …
=> [AC-2304] added User Status check to revoke-restore and remove components

apps/web/src/app/vault/components/premium-badge.stories.ts
```
```
#8133 introduced `BillingAccountProfileStateService` as a dependency for `NotPremiumDirective` which was not supplied in the Premium Badge storybook module. This PR addresses that.
Add a mock implementation of `BillingAccountProfileStateService`
=> Fix Premium Badge Storybook

libs/common/src/admin-console/services/provider.service.spec.ts, libs/common/src/admin-console/services/provider.service.ts
```
```
We are seeing some problems with providers being retrieved when there is no user active at this time. We've already updated the implementation of `getUserState$` to not throw and instead wait until a user becomes active and we added `getUserStateOrDefault$` which will return a default value when a user isn't active at the time but we want to pick this to `rc` where those changes aren't done yet. I just re-implemented it locally here to keep overall impact low.
https://github.com/bitwarden/clients/blob/087d174194453c9eca6e28ed95facdc5998ab205/libs/common/src/platform/state/implementations/default-state.provider.ts#L44-L54 …
=> [PM-6853] Recreate `getUserStateOrDefault$`

libs/common/src/platform/services/state.service.ts, libs/common/src/vault/services/cipher.service.ts
```
```
Occasionally we may attempt to cache an empty cipher array and that could have been from an attempt to decrypt the vault a bit to early, this will keep it from making it to the cache and allow for the next time ciphers are requested for it to do the work instead of trusting the cache which might be wrong.
=> [PM-6853] Stop Caching Empty Ciphers List

libs/common/src/auth/abstractions/avatar.service.ts, libs/common/src/auth/services/avatar.service.ts, libs/common/src/vault/services/sync/sync.service.ts
```
```
We are currently seeing a loop where we get this value from sync and that causes us to update the avatar color on the server which then updates the revision date causing for a sync to happen the next time some requests it without forcing. The method that sets the avatar color from sync shouldn't go and update the server since it already got it from there. 
=> Create New Method for Setting Avatar Color from Sync

libs/auth/src/angular/user-verification/user-verification-dialog.component.html, libs/auth/src/angular/user-verification/user-verification-dialog.component.ts, libs/auth/src/angular/user-verification/user-verification-dialog.types.ts, libs/auth/src/angular/user-verification/user-verification-form-input.component.html, libs/auth/src/angular/user-verification/user-verification-form-input.component.ts
```
```
The re-worked user-verification component got introduced with https://github.com/bitwarden/clients/pull/7536 but was missing to use the newer [bit-callout](https://components.bitwarden.com/?path=/docs/component-library-callout--docs) instead of the old app-callout. This replaces the usages of the callouts.
- **libs/auth/src/angular/user-verification/user-verification-dialog.component.html:** Use `bit-callout` instead of `app-callout`
- **libs/auth/src/angular/user-verification/user-verification-form-input.component.html:** Use `bit-callout` instead of `app-callout` and fixed the calloutType being used
- **libs/auth/src/angular/user-verification/user-verification-dialog.component.ts:** Import CalloutModule and add it as a dependency
- …
=> [PM-6969] Use bit-callout within userVerification

apps/browser/src/popup/services/services.module.ts
```
```
As part of the StateProvider work we are re-visiting the usage of shared services between the background and popup and removing all unnecessary services.
- **Remove PasswordStrengthService from popup/services.module -** https://github.com/bitwarden/clients/commit/fc7d8b2a5d89f454328dc12bd053c0eb226b077f
-  No state needs to be shared between background and popup. Meaning it can be safely removed.
- **Remove ImportService from popup/services.module -** https://github.com/bitwarden/clients/commit/fd87d3739d84da30da432523d1f277bcb4c7688d
- Can be removed as the import.component is standalone and provides the importService. For the fileless LP import we also don't need the injector within the popup as it's provided via `jslib.services.module`.
- Please add **unit tests** where it …
=> [PM-6195] Refactor injection of services in browser services module

apps/desktop/src/app/accounts/settings.component.html, apps/desktop/src/app/app.module.ts, apps/desktop/src/app/tools/export/export.component.html, apps/desktop/src/app/tools/generator.component.html, apps/desktop/src/app/tools/send/add-edit.component.html, apps/desktop/src/vault/app/vault/add-edit.component.html
```
```
In an partial effort to have a slightly more modern look and feel on the desktop and hopefully getting rid of some our custom css, my goal is to replace the usage of app-callouts with [bit-callouts](https://components.bitwarden.com/?path=/docs/component-library-callout--docs).
- **Enable usage of the bit-callout within desktop -** https://github.com/bitwarden/clients/commit/df38b3fefaa19149f7d5960428f5abd71bfe15e8
-  Adding this should be temporary, with the vision being: All components are standalone and they'd depend/import the CalloutModule themselves if they need it
- **Replace vaultTimeoutPolicy callout in settings -** https://github.com/bitwarden/clients/commit/2e959a0a334c1f0a6228cc44e21252e25031cd16
- **Replace OwnershipPolicy callout in add-edit cipher -** …
=> [PM-6967] Replace app-callouts with bit-callouts on desktop

apps/desktop/src/main.ts
```
```
Force hardware acceleration to be disabled for machines with AMD switchable graphics due to https://github.com/bitwarden/clients/issues/8003.
This relies on https://www.electronjs.org/docs/latest/api/app#appgetgpuinfoinfotype, an alternative implementation could use `deviceId` but hopefully `amdSwitchable` is slightly more generic and catches more devices.
=> [PM-6983] Disable hardware acceleration for bad GPUs

apps/browser/src/popup/scss/base.scss
```
```
The extension contains global CSS that targets `header` elements. This was unintentionally overriding the styles of the `header` within the template of `bit-dialog`.
- **apps/browser/src/popup/scss/base.scss:** Exclude `bit-dialog` from CSS selector.
Before:
After:
=> [CL-232] exclude bit-dialog from global extension header styles

apps/browser/src/popup/scss/base.scss
```
```
This PR fixes select overlays not being visible when the popup window is zoomed beyond 100%.
This was caused by the positioning strategy of `ng-select`, which requires the body have `positive: relative`. 
- **apps/browser/src/popup/scss/base.scss:** Add `positive: relative` to `body`. This causes another bug (0 height content, see recording), which is remedied by adding a min width.
https://github.com/bitwarden/clients/assets/17113462/1eafc6b8-2a50-4e0e-b3f8-337fee43d556 …
=> [PM-4406] fix select overlay visibility when popup is zoomed

apps/desktop/src/main/menu/menu.help.ts
```
```
Running `app.relaunch` crashes on mac app store builds. Disabling it for now while we track https://github.com/electron/electron/issues/41690. Unfortunately this means MAS users will have to manually start the app after it quits.
=> [PM-7048] Disable relaunch on MAS

libs/common/src/state-migrations/migrations/38-migrate-token-svc-to-state-provider.spec.ts, libs/common/src/state-migrations/migrations/38-migrate-token-svc-to-state-provider.ts
```
```
Previous to the TokenService state provider migration (#7975) ( [PM-5263](https://bitwarden.atlassian.net/browse/PM-5263)), access / refresh tokens + client id & secret were improperly being persisted to local storage on account scaffolding. The #7975 changes no longer persist this data for new logins, but the migration was still incorrectly porting over the tokens from the account in local storage to the new state provider location in local storage.  This change utilizes the new migration type to stop the migration of those tokens but only for web local storage.  …
=> Auth/PM-5263 - TokenService State provider migration bug fix to avoid persisting tokens in local storage

libs/angular/src/components/share.component.ts
```
```
The `share.component.ts` called `filterCollections()` at the end of `load()` which could run before the `organizations$` observable emitted (responsible for setting `this.organizationId`) resulting in an empty list of collections. This PR moves the call to `filterCollections()` into the `organizations$` subscription and is called right after `this.organizationId` is assigned.
- **libs/angular/src/components/share.component.ts:** See above.
https://github.com/bitwarden/clients/assets/8764515/e0f4396f-4e91-4615-8ade-3fe692a38292 …
=> [AC-2351] Fix unable to move items to organization in Browser

libs/auth/src/common/models/domain/user-decryption-options.ts
```
```
As part of the user decryption options service, I decided to always initialize a `TrustedDeviceOption` and `KeyConnectorOptions` to prevent possible null references. This broke regular SSO login since existence of the `TrustedDeviceOption` was used to determine if trusted device was available for login and where to navigate. Since we don't store the keys themselves, this has been reverted to the original behavior. …
=> [PM-7088] Only initialize user decryption options if present on response obj

apps/web/src/app/vault/components/vault-items/vault-items.component.html, apps/web/src/app/vault/components/vault-items/vault-items.component.ts, apps/web/src/app/vault/individual-vault/vault.component.html, apps/web/src/app/vault/individual-vault/vault.component.ts, apps/web/src/app/vault/org-vault/vault.component.html, apps/web/src/app/vault/org-vault/vault.component.ts, libs/common/src/enums/feature-flag.enum.ts
```
```
Remove the BulkCollectionAccess feature flag. This feature has rolled out alongside the collection enhancements. By the time the next release rolls around, we can consider it stable.
Server PR: https://github.com/bitwarden/server/pull/3928
Self explanatory, however note that:
* in the individual vault template, I removed the `showBulkEditCollectionAccess` input altogether because it's always overridden by `showAdminActions="false"`. This means we never showed it in the individual vault.
* in the org vault, I kept the input because it still depends on `org.flexibleCollections`. It'll be removed once we remove that org-level flag. …
=> [AC-1724] Remove BulkCollectionAccess feature flag

apps/desktop/src/platform/main/biometric/biometrics.service.abstraction.ts, libs/angular/src/platform/abstractions/form-validation-errors.service.ts, libs/angular/src/platform/services/theming/theming.service.abstraction.ts, libs/common/src/platform/abstractions/app-id.service.ts, libs/common/src/platform/abstractions/broadcaster.service.ts, libs/common/src/platform/abstractions/config/config-api.service.abstraction.ts, libs/common/src/platform/abstractions/crypto-function.service.ts, libs/common/src/platform/abstractions/crypto.service.ts, libs/common/src/platform/abstractions/encrypt.service.ts, libs/common/src/platform/abstractions/file-download/file-download.service.ts, libs/common/src/platform/abstractions/file-upload/file-upload.service.ts, libs/common/src/platform/abstractions/i18n.service.ts, libs/common/src/platform/abstractions/key-generation.service.ts, libs/common/src/platform/abstractions/log.service.ts, libs/common/src/platform/abstractions/messaging.service.ts, libs/common/src/platform/abstractions/platform-utils.service.ts, libs/common/src/platform/abstractions/system.service.ts, libs/common/src/platform/abstractions/translation.service.ts, libs/common/src/platform/abstractions/validation.service.ts, libs/common/src/platform/biometrics/biometric-state.service.ts, libs/common/src/platform/state/derived-state.provider.ts, libs/common/src/platform/state/global-state.provider.ts, libs/common/src/platform/state/state.provider.ts, libs/common/src/platform/state/user-state.provider.ts, libs/common/src/platform/theming/theme-state.service.ts
```
```
We currently use a callback syntax for abstract services. This syntax isn't completely strict compliant and will fail the `strictPropertyInitialization` check. We also currently don't get any compile time errors if we forget to implement a function.
To that end this PR updates all platform owned services to use the appropriate `abstract` keyword for non implemented functions. I also updated the fields to be actual functions and not properties. …
=> [STRICT TS] Migrate platform abstract services functions

apps/desktop/src/app/accounts/settings.component.ts
```
```
lazy resolved biometric text. We cannot load biometric text on init because they are not valid everywhere. This was causing issues with settings storage on linux.
Fixes #8270 
=> Move biometric texts all to getters

.github/workflows/release-desktop-beta.yml, .github/workflows/release-desktop.yml
```
```
- Remove R2 bucket secrets and publish to R2 step from desktop artifacts release workflows
- This is required as part of the migration from Cloudflare to Fastly for these static assets
- We will use the existing AWS S3 buckets as the origins fronted by Fastly
- **release-desktop-beta.yml** Removed R2, CF secrets from **Retrieve secrets** step and removed **Publish artifacts to R2** step
- **release-desktop.yml** Removed R2, CF secrets from **Retrieve secrets** step and removed **Publish artifacts to R2** step
- Ensure that all …
=> CLOUDOPS-1369 Remove R2 bucket secrets and step from artifacts

libs/common/src/auth/services/token.state.ts, libs/common/src/platform/services/state.service.ts
```
```
Finish resolving [PM-5263](https://bitwarden.atlassian.net/browse/PM-5263); fixes bug [PM-7164](https://bitwarden.atlassian.net/browse/PM-7164)
#7975 migrated the state, but we just discovered that we were not properly clearing the refresh token and API key client Id / secret on log out.
- **libs/common/src/auth/services/token.state.ts:** Add comments to token state explaining why they aren't user key definitions and why they don't implement `clearOn` 
- **libs/common/src/platform/services/state.service.ts:** `deAuthenticateAccount` should clear all tokens - not just the access token. In the previous state service implementation, the rest of the tokens were cleaned up on logout automatically for us, but we must handle this manually now. 
- Please add **unit tests** where it makes …
=> [PM-5263, PM-7164] TokenService - Clear all tokens on log out

apps/web/src/app/tools/vault-export/export.component.ts
```
```
Export from TDE accounts should ask for an email code verification and not a PIN
- **web/export.component.ts:** Removed the set to `clientSideOnlyVerification` on the UserVerificationDialog as it was preventing the use of OTP.
=> [PM-7165] Removing clientSideOnlyVerification from Web ExportComponent

.github/workflows/release-desktop-beta.yml, .github/workflows/release-desktop.yml
Reverts bitwarden/clients#8534
Need to revert this while we investigate the issues encountered during the cutover for artifacts.bitwarden.com. Release is next week and don't want to cause any issues since we had to roll artifacts back to Cloudflare R2 bucket.
=> Revert "CLOUDOPS-1369 Remove R2 bucket secrets and step from artifacts"

apps/browser/src/background/main.background.ts, apps/browser/src/platform/background/service-factories/storage-service.factory.ts, apps/browser/src/platform/services/local-backed-session-storage.service.spec.ts, apps/browser/src/platform/services/local-backed-session-storage.service.ts
```
```
Update `LocalBackedSessionStorage` to be aware of and send update from other Bitwarden contexts. I'd still rather have this utilize ports so that this communication is more siloed from our general use of messaging but this is a solid first pass that is working quite well. 
I also made it possible to partition these services so that we don't have to unnecessarily invalidate caches for things that might rarely update because of things that update often. Right now we are only partitioning between state service and state providers but more can be added through some fine tuning.  …
=> [PM-5740] LocalBackedSessionStorage Updates

libs/angular/src/platform/services/logging-error-handler.ts, libs/angular/src/services/jslib-services.module.ts
```
```
The custom `ErrorHandler` recently introduced ([here](https://github.com/bitwarden/clients/pull/8543)) causes a circular dependency error for `APPLICATION_REF`. 
~It is unclear to me why exactly this is happening~, but injecting the dependency with `Injector.get` solves the issue.
edit: This seems to be a known issue. See here: https://medium.com/@amcdnl/global-error-handling-with-angular2-6b992bdfb59c
> There is one problem though, since error handling is really important it needs to be loaded first, thus making it not possible to use dependency injection in the constructor to get other services such as the error handle api service to send the server our error details. As a result, we have to manually call the injector with the service name in the execution of the handleError …
=> [PM-7229] Fix circular dependency in ErrorHandler

libs/components/src/menu/menu-trigger-for.directive.ts
```
```
Within the `menu-trigger-for.directive.ts` file, we should be conditionally referencing the `this.menu.keyManager` class. This class is not instantiated in cases where the ARIA role of the MenuComponent is not `'menu'`.
- **libs/components/src/menu/menu-trigger-for.directive.ts:** Wrapping both calls to `this.menu.keyManager` within a conditional that ensures it is a defined value.
=> [CL-253] Fix undefined reference to `keyManager` within `menu-trigger-for` directive

apps/web/src/app/billing/organizations/subscription-status.component.html, apps/web/src/app/billing/organizations/subscription-status.component.ts
```
```
The refactoring completed as part of [AC-1759](https://bitwarden.atlassian.net/browse/AC-1759) did not take into account what happens when the organization is free (doesn't have a Stripe subscription). This PR handles that case.
https://github.com/bitwarden/clients/assets/144709477/865f61d8-d144-4f67-8060-0e6e51faf4cd
[AC-1759]: https://bitwarden.atlassian.net/browse/AC-1759?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [AC-2404] Fix subscription page for free org with new statuses enabled

apps/web/src/app/vault/org-vault/vault.component.ts, libs/angular/src/vault/components/add-edit.component.ts, libs/common/src/admin-console/models/domain/organization.ts
```
```
We recently made a change to use the `canEditAnyCollection` helper to determine if a user can edit unassigned ciphers. This no longer works because `canEditAnyCollection` will start to return false in V1 FC when admins are restricted. So we need a separate helper to determine if the user can access unassigned ciphers (any admin/owner or custom user with `editAnyCollection` permission) 
- **organization.ts:**
- Add a new `canEditUnassignedCiphers()` helper 
- Remove the redundant and ambiguous `canUseAdminCollections()` helper that was just a wrapper around `canEditAnyCollection()` and was adding unnecessary noise to our permissions.
- **vault.component.ts:**
- Use `canEditUnassignedCiphers` where appropriate
- Replace uses of `canUseAdminCollections()` with …
=> [PM-7292] Fix viewing/editing unassigned ciphers for admins

apps/browser/src/background/main.background.ts, apps/cli/src/bw.ts, apps/desktop/src/app/app.component.ts, apps/web/src/app/app.component.ts, libs/common/src/admin-console/abstractions/policy/policy.service.abstraction.ts, libs/common/src/admin-console/services/policy/policy.service.spec.ts, libs/common/src/admin-console/services/policy/policy.service.ts
```
```
These changes swap the `POLICIES` `KeyDefinition` to a `UserKeyDefinition`. The difference is that UserKeyDefinition comes with some baked in functionality for clearing state on lock or logout.
Using this new type lets us remove boilerplate lines from the centralized logOut methods in each application that clear state.
=> Tell `POLICIES` to clear its own state on logout

apps/browser/src/background/main.background.ts, apps/cli/src/bw.ts, apps/desktop/src/app/app.component.ts, libs/common/src/admin-console/services/provider.service.ts
```
```
These changes swap the `PROVIDERS` `KeyDefinition` to a `UserKeyDefinition`. The difference is that `UserKeyDefinition` comes with some baked in functionality for clearing state on lock or logout.
Using this new type lets us remove boilerplate lines from the centralized `logOut` methods in each application that clear state.
=> Tell `PROVIDERS` to clear its own state on logout

apps/browser/src/autofill/background/abstractions/notification.background.ts, apps/browser/src/autofill/background/notification.background.spec.ts, apps/browser/src/autofill/background/notification.background.ts, apps/browser/src/autofill/content/notification-bar.ts, apps/browser/src/background/main.background.ts
- Bug fix
Looks like things broke with the state updates in https://github.com/bitwarden/clients/pull/8325
The notification bar content script is still looking in the old state location for the server config
These changes add messaging to the notification bar background in order to get the server config values from the new state service location.
=> [PM-7216] Bugfix - Fix notification bar content script using old server config state storage

apps/web/package.json
```
```
We regularly run out of heap space running `build:bit:dev:watch`, increase the `max-old-space-size` to avoid this issue going forward.
=> Increase max-old-space for bit:dev:watch

bitwarden_license/bit-web/src/app/admin-console/organizations/manage/domain-verification/domain-add-edit-dialog/domain-add-edit-dialog.component.html, bitwarden_license/bit-web/src/app/admin-console/organizations/manage/domain-verification/domain-add-edit-dialog/domain-add-edit-dialog.component.ts, libs/common/src/admin-console/services/organization-domain/requests/organization-domain.request.ts
> Adjust the domain verification dialog to separate the save/verify domain steps. Generate the DNS TXT record server-side in order to increase security from potential client-side manipulation.
- **...domain-add-edit-dialog.component.html**: Visually separated the save/verify steps. Introduced a `Next` button before allowing verification while also hiding items specific to the `verify` step, until necessary.
- **...domain-add-edit-dialog.component.ts**: Removed client-side DNS TXT record generation. Removed chaining to the `verify` step as the user will not yet have had a chance to upload the generated record to their DNS provider.
- **...organization-domain.request.ts**: Removed the `txt`object property. 
https://github.com/bitwarden/clients/assets/26154748/fda88e65-c021-4741-87fa-152517d8 …
=> [AC-2350] - FIX - Separate domain verification steps

apps/browser/src/popup/services/services.module.ts
```
```
With the changes for https://github.com/bitwarden/clients/pull/8380 an issue was identified with how the `AutofillService` references the `TotpService` as part of its dependencies. The change in this PR addresses that issue, ensuring we are correctly referencing the `TotpServiceAbstraction` to populate the dependency.
- **apps/browser/src/popup/services/services.module.ts:** Updating the dependency reference for `AutofillService` to reference the `TotpServiceAbstraction` instead of the `TotpService` class implementation
=> [PM-7388] Fix AutofillService dependency reference to TotpService within poppup services module

libs/common/src/platform/services/key-state/user-key.state.ts
```
```
I had missed the ever had user key boolean as user-scoped in #8584. This PR moves that value to be cleared on logout.
=> Use `UserKeyDefinition` for user-scoped data

apps/browser/src/background/main.background.ts, apps/browser/src/platform/decorators/session-sync-observable/session-syncer.ts, apps/browser/src/popup/services/services.module.ts
```
```
The changes in this PR add mv3 specific logic that removes usage of the `BrowserMessagingPrivateModeBackgroundService` and `MultithreadEncryptService` within manifest v3. 
`BrowserMessagingPrivateModeBackgroundService` is a service class that will be removed with the rollout of manifest v3. The work done without our state providers should facilitate a way to handle messaging in a more effective manner, and this class's purpose will be defunct with those changes.
`MultithreadEncryptService` cannot be used within the background service worker. As a result, we need to remove usage of it to ensure the extension does not trigger an error when attempting to use the class within the background script.
The behavior has been adjusted to ensure that manifest v2 hasn't been affected. 
- …
=> [PM-7370] Remove usage of `BrowserMessagingPrivateModeBackgroundService` and `MultithreadEncryptService` from manifest v3

apps/web/src/app/layouts/header/web-header.component.html, apps/web/src/app/layouts/header/web-header.component.ts, apps/web/src/app/layouts/header/web-unassigned-items-banner.service.spec.ts, apps/web/src/app/layouts/header/web-unassigned-items-banner.service.ts, apps/web/src/locales/en/messages.json, libs/common/src/abstractions/api.service.ts, libs/common/src/enums/feature-flag.enum.ts, libs/common/src/platform/state/state-definitions.ts, libs/common/src/services/api.service.ts
```
```
Show a banner re: unassigned organization items if the user is an admin or owner of an org that has unassigned items.
Server PR: https://github.com/bitwarden/server/pull/3967
**unassigned-items-banner.service.ts**
This does the main work. It uses a single piece of state, `SHOW_BANNER_KEY`, to manage the banner:
- `null` -> the banner has not been shown to the user yet, check with the server whether we need to display it. This then updates the value which will trigger another run through the subscribe callback
- `true` -> show the banner
- `false` -> do not show the banner (because it has been dismissed or the server indicated it's not required)
Note that this is user state (because its value is computed per user) that is not cleared on logout (because we don't want to show them …
=> [AC-2436] Show unassigned items banner in web

libs/angular/src/services/unassigned-items-banner.service.spec.ts, libs/angular/src/services/unassigned-items-banner.service.ts
```
```
QA reported the unassigned items banner appearing for a brief moment for users who should not see it. Fix.
I thought returning `EMPTY` on the callback's initial run would not emit any value. However, it seems to have emitted a non-falsey value which caused the banner to briefly appear until the server value could be loaded from state.
We could return `false` instead if we wanted, but I simplified it further and just returned the server value early (after updating state). That way the observable will always emit the correct value (from a business logic perspective) the first time.
This will need to be cherry-picked into:
* rc
* hotfix-rc-browser
* hotfix-rc-web …
=> [AC-2436] Fix flashing unassigned items banner

apps/browser/src/background/main.background.ts, apps/desktop/electron-builder.json, apps/desktop/src/app/app.component.ts, libs/angular/src/services/unassigned-items-banner.service.spec.ts, libs/angular/src/services/unassigned-items-banner.service.ts, libs/common/src/services/search.service.ts
=> [PM-4700] Fixed issue with clearing search index state

libs/common/src/admin-console/services/policy/policy.service.spec.ts, libs/common/src/admin-console/services/policy/policy.service.ts
```
```
This fixes a regression for password generator policy. The policy should always apply to all users, including to owners and policy administrators.
- **libs/common/src/admin-console/services/policy/policy.service.ts:** categorically apply password generation policy
- **libs/common/src/admin-console/services/policy/policy.service.spec.ts:** test that the policy is returned for owners and policy administrators
=> [PM-7345] apply password generator policy categorically

apps/browser/src/_locales/en/messages.json, apps/browser/src/vault/popup/components/vault/current-tab.component.html, apps/web/src/app/layouts/header/web-header.component.html, apps/web/src/locales/en/messages.json, libs/angular/src/services/unassigned-items-banner.service.spec.ts, libs/angular/src/services/unassigned-items-banner.service.ts
```
```
Show the unassigned items banner in advance of the self-hosted flexible collections release, to give self-hosted users advance warning of the change.
Client-side, this really just means changing the text to use future tense instead.
Server-side, see https://github.com/bitwarden/server/pull/3978.
=> [AC-2443] Update unassigned items banner text for self-hosted

apps/desktop/src/vault/app/vault/add-edit.component.ts, libs/angular/src/vault/components/add-edit.component.ts
```
```
Currently, when creating an item under an organization, collections are not loaded, and because of this, the item cannot be saved. The objective of this ticket is to ensure collections load when displaying the form when adding a new item.
The collections were loaded in ngOnInit, which is not executed until after the first ngOnChanges call. As a result, when ngOnChanges needed the collections immediately (such as when adding a new item), they were unavailable. 
To fix this bug, I ensure collections are always loaded before they are needed.
https://github.com/bitwarden/clients/assets/13024008/9b615c38-e212-44d5-9909-ad6819160fd7 …
=> [PM-6696] Collections not loading when adding item

libs/common/src/admin-console/abstractions/organization/organization.service.abstraction.ts, libs/common/src/admin-console/services/organization/organization.service.ts, libs/common/src/admin-console/services/policy/policy.service.spec.ts, libs/common/src/admin-console/services/policy/policy.service.ts
```
```
- To add a method on the `OrganizationService` which accepts an optional user id and returns an observable of the given or active user's organizations state.
- To then resolve a bug in the `PolicyService` in which the `getAll$(...)` method didn't pass the optional user id into the retrieval of the organizations. This would result in a hang if you called to get policies before there was an active account (a scenario I ran into in #8604) even if you provided a user id. 
- **libs/common/src/admin-console/abstractions/organization/organization.service.abstraction.ts:** Add `getAll$`docs
- **libs/common/src/admin-console/services/organization/organization.service.ts:** Add `getAll$` method
- **libs/common/src/admin-console/services/policy/policy.service.ts:** Update …
=> Update Organization and Policy Services to allow the passing of a user id and to prevent hangs waiting on an active user

apps/web/src/app/admin-console/organizations/shared/components/access-selector/access-selector.models.ts, apps/web/src/app/vault/components/collection-dialog/collection-dialog.component.ts
```
```
#8335 introduced some new helpers to handle the new readonly mode for the collection dialog. Unfortunately, the helpers will throw an exception when creating a new collection. This PR adds some null checks to help avoid that.
- **access-selector/access-selector.models.ts:** Update `convertToPermission` to handle undefined/null values and return appropriately
- **collection-dialog.component.ts:** Only attempt to find a collection for the group/user if the collectionId is present (we're editing an existing collection).
- Ensure …
=> [AC-2431] New collection dialog bug

libs/common/src/vault/services/cipher.service.ts
```
```
#8314 migrated cipher service to state providers for MV3. The `state$` observable represents the actual value of the given key in the storage provider, which can be null. This PR handles null cases in observed data values.
=> Handle null values coming from state

libs/common/src/state-migrations/migrations/57-move-cipher-service-to-state-provider.spec.ts, libs/common/src/state-migrations/migrations/57-move-cipher-service-to-state-provider.ts
```
```
#8314 migrated cipher encrypted data from state service to state providers. State service held data in an encrypted pair, with potentially both encrypted and decrypted values. We want the encrypted form for these disk migrations (decrypted would always be empty on disk anyways).
This migration has not yet been released and so does not need to be reverted and reapplied.
=> Fix migrated state service data

libs/common/src/tools/generator/state/buffered-key-definition.ts, libs/common/src/tools/generator/state/buffered-state.spec.ts, libs/common/src/tools/generator/state/buffered-state.ts
```
```
**Note:** Dependency of #8605, #8606. These branches are the only consumers of `BufferedState`, and QA will occur there.
Fix a `BufferedState` bug that causes updates to endlessly loop once an overwrite occurs when wired to `SecretState` in electron. The bug occurs because `SecretState` emissions are ordered before the buffered value is cleared, causing `updateOutput` to repeatedly process the buffered value. 
The solution wires the overwrite logic in parallel with the output logic using `merge`. Emissions from the overwrite stream are ignored, which lets the output stream to control all emissions from `BufferedState.state$`.
This also had a nice side effect of clearing up some double-emissions in the test cases.
- **libs/common/src/tools/generator/state/buffered-key-definition.ts: …
=> [PM-6819] fix update cycle when overwriting state from buffer

apps/browser/src/autofill/background/service_factories/autofill-service.factory.ts, apps/browser/src/autofill/services/autofill.service.spec.ts, apps/browser/src/autofill/services/autofill.service.ts, apps/browser/src/background/main.background.ts, apps/browser/src/popup/services/services.module.ts
```
- Bug fix
```
If no user is logged in, some autofill settings (in user state as `inlineMenuVisibility` and `autofillOnPageLoad`) which are used for pre-login autofill script injections will await an active account indefinitely. This PR adds active account checks to guard against this case.
=> [PM-7610] [MV3] Guard overlay visibility and autofill on page load settings from awaiting indefinitely when there is no active account

libs/common/src/services/event/event-collection.service.ts
```
```
Individual vault export event was not showing on organization event logs. `EventCollectionService` only updated events when they had a cipher id or a organization id. 
Individual vault export has neither so it was not being added. Added an if exception for this event type.
- **event-collection.service.ts:** Added an if validation that allows `User_ClientExportedVault` to be updated even not having `organizationid` and `cipherid` …
=> [PM-7603] Fix individual vault export not appearing on Event Logs

apps/browser/src/background/main.background.ts, apps/browser/src/platform/background/service-factories/derived-state-provider.factory.ts, apps/browser/src/platform/services/browser-memory-storage.service.ts, apps/browser/src/platform/state/background-derived-state.provider.ts, apps/browser/src/platform/state/background-derived-state.ts, apps/browser/src/platform/state/derived-state-interactions.spec.ts, apps/browser/src/platform/state/foreground-derived-state.provider.ts, apps/browser/src/platform/state/foreground-derived-state.spec.ts, apps/browser/src/platform/state/foreground-derived-state.ts, apps/browser/src/platform/storage/browser-storage-service.provider.ts, apps/browser/src/popup/services/services.module.ts, apps/cli/src/bw.ts, apps/desktop/src/main.ts, libs/angular/src/services/jslib-services.module.ts, libs/common/spec/fake-state-provider.ts, libs/common/src/platform/state/derive-definition.ts, libs/common/src/platform/state/implementations/default-derived-state.provider.ts, libs/common/src/platform/state/implementations/default-derived-state.spec.ts, libs/common/src/platform/state/state-definition.ts, libs/common/src/platform/state/state-definitions.ts
```
```
Creates a new custom storage location for browser to specify that an object represents something large (defined as unrestricted in size, uncountable). This is typically enumerable account-specific data like vault items, folders, collections.
Anything that is _not_ marked as "large" is now stored in session storage -- the intended memory sync space for manifest version 3. We held off on using it for fear of the 10MB limit. However, for countable items this is more than enough. 
For now, sends, search, and ciphers are the only first party key definitions requiring this storage treatment.
Additionally, `DerivedState` is often used to represent lists of decrypted data. Because it is wired up differently and assumed memory storage, this needed to default to the new large object …
=> Browser MV3: Default store values to session storage

apps/browser/config/development.json, apps/browser/src/background/main.background.ts, apps/browser/src/platform/background/service-factories/storage-service.factory.ts, apps/browser/src/platform/decorators/dev-flag.decorator.spec.ts, apps/browser/src/platform/flags.ts, apps/browser/src/platform/services/local-backed-session-storage.service.spec.ts, apps/browser/src/platform/services/local-backed-session-storage.service.ts, libs/common/spec/index.ts, libs/common/src/platform/misc/lazy.spec.ts, libs/common/src/platform/misc/lazy.ts
```
```
My testing has shown that the current implementation of `localBackedSessionStore` creates problems as the total amount of stored data increases. Every value retrieved suffers from the presence of all other data due to the single blob nature.
In the extreme, signing in with an account with thousands of vault items (~50MB worth) significantly impacts a second vault with only 5, which should still be perfectly snappy. The solution to this coupling is, of course, to decouple. We _could_ do this by assigning namespaces by global/userId, but my testing suggests that it is not necessary to bundle even to that extent. It's sufficient to group the large, enumerable lists of items (ciphers, collections, folders, sends, etc) into one key-value-pair each. We do lose some time with …
=> [PM-7653] Do not store disk-backed sessions as single blobs

apps/browser/src/background/main.background.ts, apps/cli/src/bw.ts, libs/angular/src/services/jslib-services.module.ts, libs/auth/src/common/login-strategies/login.strategy.spec.ts, libs/auth/src/common/login-strategies/login.strategy.ts, libs/common/src/auth/abstractions/token.service.ts, libs/common/src/auth/services/token.service.spec.ts, libs/common/src/auth/services/token.service.ts, libs/common/src/auth/services/token.state.spec.ts, libs/common/src/auth/services/token.state.ts, libs/common/src/platform/abstractions/state.service.ts, libs/common/src/platform/models/domain/account-tokens.spec.ts, libs/common/src/platform/models/domain/account.spec.ts, libs/common/src/platform/models/domain/account.ts, libs/common/src/platform/services/state.service.ts, libs/common/src/vault/services/sync/sync.service.ts
Reverts bitwarden/clients#8792 before `rc` cut so we can have more dedicated time to QA it.
=> Revert "Auth/PM-6689 - Migrate Security Stamp to Token Service and State Provider"

.vscode/settings.json
```
```
Adds support for rust-analyzer to find the `desktop_native` rust module in VSCode. Otherwise, even if you navigate to the subdirectory and open a rust file, rust-analyzer will fail to load.
=> Add rust analyzer support for desktop-native

apps/browser/src/background/main.background.ts
```
```
A bug has been encountered with the master password reprompt workflow when attempting to autofill a vault item from keyboard shortcut or context menu. This issue seems to be occurring due to a follow up load event that is triggering in the view component.
This follow up load event is triggering due to a message that is sent to the component of syncCompleted. This shouldn’t be occurring, and is happening due to the re-instantiation of MainBackground within the popup vault. Guarding against that event will be necessary.
- **apps/browser/src/background/main.background.ts:** Guarding against calling a fullSync within `MainBackground` when it is initialized in the popup.
=> [PM-7660] Master Password Re-Prompt from Autofill Not Working

apps/browser/src/popup/services/services.module.ts
```
```
This helps fix unlock with biometric because the crypto service is responsible for prompting for biometrics when the key is requested and since it was getting its instance from the fake background which has the `BackgroundPlatformUtilsService` which wasn't working because parts of the background it was trying to use were gone. Changing this means it gets the `ForegroundPlatformUtilsService` which allows the biometrics to work the way it was intended, through a message to the true background.
`CryptoFunctionService` is already being injected without `getBgService` ([see](https://github.com/bitwarden/clients/compare/ps/pm-7617/fix-biometric-unlock?expand=1#diff-210fa6ef76ade2d9a5dc1a77eefb240c2c0f71e951d00ac6fcdc38e83fe328f8L195-L199)).
- Please add **unit tests** where it makes …
=> [PM-7617] Stop CryptoService from using `getBgService`

apps/browser/src/manifest.v3.json
```
```
We aren't currently using the `alarms` api, so we don't currently need the `alarms` permisson. Until we use it, we can remove it.
=> Remove `alarms` Permission

libs/components/src/styles.scss
```
```
The Storybook code block is rendering dark text on a dark background due to global Bootstrap styles that are injected into the page. This PR overrides that CSS and colors the text white.
- **libs/components/src/styles.scss:** add color override
Before fix:
After fix:
=> [CL-110] fix code block text color in Storybook

apps/browser/src/_locales/en/messages.json
```
```
Shorten extension description to 112 characters as that is a limit setup by Apple
Safari extension description is limited to 112 chars Add that restriction within the description
- **Shorten extension description to 112 characters as that is a limit set up -** https://github.com/bitwarden/clients/commit/dfa7776c6e53da729afc6c04361326843e214260
- Safari extension description is limited to 112 chars
- Add that restriction within the description.ext:** Description of what was changed and why
- Ensure that all UI additions follow …
=> [PM-7681] Shorten browser extension description to unblock Apple Testflight

libs/angular/src/auth/components/login-via-auth-request.component.ts
```
```
When logging in with Admin Approvals, we were only using the stored keypair if the notification was already approved on page load. We weren't actually storing the keypair if a notification was received later on. 
This change stores the keypair so when a notification comes through the hub, the correct private key is used.
=> [PM-7566] Set keypair for admin auth requests before waiting for notification

apps/browser/src/models/account.ts, apps/browser/src/platform/background/service-factories/state-service.factory.ts, apps/browser/src/platform/services/browser-state.service.spec.ts, apps/browser/src/platform/services/default-browser-state.service.ts, apps/desktop/src/app/services/services.module.ts, apps/desktop/src/main.ts, apps/web/src/app/core/core.module.ts, apps/web/src/app/core/state/state.service.ts, libs/angular/src/services/injection-tokens.ts, libs/angular/src/services/jslib-services.module.ts, libs/common/src/platform/services/state.service.ts
```
```
Remove the `useAccountCache` option from `StateService` and all the code it enabled. In browser, this involved making a message to another context, in some cases that message would return `undefined` and cause problems in MV3. 
The disk cache should largely not be needed since most larger objects has been removed out of state service in favor or state providers. All the items left can be retrieved from disk quite quickly.  …
=> Remove `StateService` `useAccountCache`

apps/browser/src/background/main.background.ts, apps/cli/src/bw.ts, libs/angular/src/services/jslib-services.module.ts, libs/auth/src/common/login-strategies/login.strategy.spec.ts, libs/auth/src/common/login-strategies/login.strategy.ts, libs/common/src/auth/abstractions/token.service.ts, libs/common/src/auth/services/token.service.spec.ts, libs/common/src/auth/services/token.service.ts, libs/common/src/auth/services/token.state.spec.ts, libs/common/src/auth/services/token.state.ts, libs/common/src/platform/abstractions/state.service.ts, libs/common/src/platform/models/domain/account-tokens.spec.ts, libs/common/src/platform/models/domain/account.spec.ts, libs/common/src/platform/models/domain/account.ts, libs/common/src/platform/services/state.service.ts, libs/common/src/vault/services/sync/sync.service.ts
Reverts bitwarden/clients#8860.  `rc` has been cut so this should go back into `main`.
=> Revert "Revert "Auth/PM-6689 - Migrate Security Stamp to Token Service and State Provider""

libs/components/src/card/card.component.ts, libs/components/src/card/card.stories.ts, libs/components/src/card/index.ts, libs/components/src/index.ts, libs/components/src/section/section.component.ts, libs/components/src/section/section.stories.ts
```
```
Adds a card component to the CL
- **libs/components/src/card** Add card component and stories
- **libs/components/src/section** Adjust section bottom margin to be `24px` on small screens, otherwise `48px` (what it is today). My thinking/assumptions:
1. this enables many of the card UIs on the extension
2. we are unlikely to want 48px spaced sections on small screens in general (otherwise we would be using them in the extension).
3. we are fine with this flowing through to the web vault 
See Storybook for more
- Ensure that all …
=> [CL-236] Card component

apps/web/src/app/admin-console/organizations/members/people.component.ts, libs/angular/src/services/jslib-services.module.ts, libs/common/src/billing/abstractions/billilng-api.service.abstraction.ts, libs/common/src/billing/abstractions/organization-billing.service.ts, libs/common/src/billing/models/response/organization-billing-metadata.response.ts, libs/common/src/billing/services/billing-api.service.ts, libs/common/src/billing/services/organization-billing.service.ts
```
```
In one of my previous changes, I added an API invocation to the `people.component` on the Web Vault that gets the organization's subscription. However, this endpoint is permission protected, which broke the `people.component` for anyone that wasn't an owner. 
That invocation was just being used to determine whether the organization was using SM Standalone. Instead, I created a new endpoint that doesn't do any unnecessary permissions check and just returns the data required by the component. I then used that endpoint in the `people.component` instead.
`server`: https://github.com/bitwarden/server/pull/4014
https://github.com/bitwarden/server/assets/144709477/9dccf62f-f234-4f53-82c0-8a285f8649cf
=> [AC-2488] Use new endpoint to determine SM standalone for organization

apps/browser/src/background/runtime.background.ts, apps/browser/src/platform/services/local-backed-session-storage.service.ts
```
```
With #8709 messages now go to all contexts, an unguarded resending of a message like this is likely to cause recursion. 2FA sends this message on successful completion. This causes a `RangeError: Maximum call stack size exceeded`. If we only guard to care about messages from the external context we avoid having infinite recursion but still allow the message to come from one popup and make it to another popup. 
While debugging this locally I saw failures with comparing the search index. This wouldn't be seen by our testers but it did hamper me while testing this bug so I added a fallback. …
=> [PM-7687] Fix `reloadPopup` Recursion

libs/common/src/models/export/card.export.ts, libs/common/src/models/export/cipher.export.ts, libs/common/src/models/export/collection.export.ts, libs/common/src/models/export/fido2-credential.export.ts, libs/common/src/models/export/field.export.ts, libs/common/src/models/export/folder.export.ts, libs/common/src/models/export/identity.export.ts, libs/common/src/models/export/login-uri.export.ts, libs/common/src/models/export/login.export.ts, libs/common/src/models/export/password-history.export.ts, libs/common/src/models/export/utils.ts
```
```
This was likely caused by moving to use StateProviders in CipherService and not removing the getBgService out of services.module. (https://github.com/bitwarden/clients/pull/8314)
Due to the different contexts (fore-/background) the type-information was lost and the export tried to use the EncStrings from domain instead of the unencrypted values from the view models.
This would be solved by deleting the `getBGService`-call for CipherService in `services.module`, but as that might have larger impacts, @justindbaur and I decided to make these changes for main/rc.
A second PR removing the getBGService calls for Cipher- and CollectionService will be created and when merged into main, has a longer time to get tested. The work included in the 2nd PR will be needed for MV3 anyways.
This …
=> [PM-7701] Fix broken export from browser

apps/browser/src/platform/services/abstractions/abstract-chrome-storage-api.service.ts, apps/browser/src/platform/services/abstractions/chrome-storage-api.service.spec.ts
```
```
#8621 moved all locally stored objects to json serialized data, but reintroduced a bug in safari refusing to set null values. This corrects that issue.
=> Reintroduce null object remove rerouting

apps/browser/src/tools/popup/services/browser-send-state.service.ts, apps/browser/src/vault/popup/components/vault/current-tab.component.ts, apps/browser/src/vault/services/vault-browser-state.service.ts, libs/common/src/vault/abstractions/cipher.service.ts, libs/common/src/vault/services/cipher.service.ts
```
```
Working to optimize the load times of the current-tab component. The changes in this PR address two concerns, the first involves avoiding re-indexing ciphers when pulling decrypted ciphers for the current tab (as searching is not a concern with this tab, and using the search bar forces the user to the vault tab which triggers the re-index). The second concern addresses whether we should trigger state updates within LocalBackedSessionStorage when a `nullish` state value is attempting to set a `nullish` value in local storage.
- **apps/browser/src/tools/popup/services/browser-send-state.service.ts:** Adding `shouldUpdate` methods that ensure we do not attempt to save a `nullish` value to local storage if the current value is already `nullish`.
- …
=> [PM-7710] Avoid re-indexing ciphers on current tab component and re-setting null storage values for popup components

bitwarden_license/bit-web/src/app/billing/providers/clients/manage-client-organizations.component.ts
```
```
There was a merge problem between #8839 & #8612 where the default value parameter to `getFeatureFlag` was removed. But the PR was written while it was still there.
=> Fix ConfigService Merge Conflict

libs/auth/src/common/login-strategies/sso-login.strategy.ts
```
```
Try to resolve [PM-7745](https://bitwarden.atlassian.net/browse/PM-7745) where the vault sometimes fails to decrypt with a `No private key` error.  We can't reproduce this locally, but I suspect that the `UserId` isn’t coming back from the `StateService` or it’s getting an incorrect one. That would then result in a null `devicePrivateKey`  in the `DeviceTrustService.decryptUserKeyWithDeviceKey(…)` which would then call `await this.cryptoService.rsaDecrypt(encryptedUserKey.encryptedString,  devicePrivateKey)`  which would throw the `No private key` error.
I suspect that I introduced the issue here: https://github.com/bitwarden/clients/pull/7882/files#diff-874e570f3547ce8f7fd1941c7ac3180fa157307e40052ba983dd20be417660fdR303
- …
=> PM-7745 - SSO Login Strategy - Attempt to fix TDE decryption "no private key" error

apps/browser/src/platform/state/foreground-derived-state.provider.ts
```
```
Fixes a bug introduced in #8844 where port names for derived state are no longer unique to the derived state.
=> Use unique port names for derived states

apps/browser/src/platform/state/foreground-derived-state.ts, apps/browser/src/vault/popup/components/vault/vault-filter.component.ts
```
```
Add a bandaid for derived folders not emitting at least once, we (platform) are going to keep looking into making this work better but for now this makes the experience of folders not emitting much better for users in MV3. 
I also encountered an issue occasionally in derived state where we were getting `"remove"` updates and returning `null` from the `switchMap` but were just calling `s.derived` on the value, which was causing some errors. …
=> Bandaid Folders Not Emitting

libs/common/src/platform/misc/utils.ts
```
```
`window` is undefined in a service worker so the service worker tried to use a node package to get the URL. We just swallow that error right now so it just appeared to not be a match. Changing this allows us to use the `URL` that is available on `self`. 
I checked to see if `self` was defined in node and I couldn't find the best of sources telling me either way but the fact that [this](https://www.npmjs.com/package/node-self) package exists and I can use desktop and CLI as normal. Even using `bw list items --search` makes me pretty confident this will work nicely.  …
=> [PM-7758] Check that `self` is undefined instead of `window`

apps/browser/src/background/main.background.ts, apps/browser/src/popup/settings/settings.component.ts
```
```
Safari logout isn't currently working. I've proved that the background _is_ receiving the "logout" message, but something is happening between there and the actual logout.
I can't prove it, but I'm pretty sure the `await firstValueFrom(accountService.activeAccount$)` is hanging before any operations are able to get done.
To fix this, I'm passing the userId through with the message and adding error handling to the `logout` method if a userId isn't found.
- Ensure that all …
=> [PM-7750] pass userId when logging out and add error handling if one isn't found in background

apps/browser/src/background/runtime.background.ts
```
```
adds error handling to our background messages.
=> [PM-7750] add error handling to runtime.background messaging

libs/common/src/platform/services/crypto.service.ts, libs/common/src/platform/services/key-state/user-key.state.spec.ts, libs/common/src/platform/services/key-state/user-key.state.ts
```
```
This has two fixes:
1. We need to be able to derive private/public keys using arbitrary keys. This is due to using these values to validate whether a key is correct or not.
2. These validations rely on throws to determine whether the keypair has been decrypted, which doesn't happen. Instead, it returns null. We check for null and return invalide key if we don't derive both keys.
=> Use a passed in key in derivation so we can validate other keys

.github/workflows/deploy-web.yml
```
```
Add a commit value as a URL, allowing QA engineers to jump from the GitHub workflow summary to the deployed commit.
- **.github/workflows/deploy-web.yml:** Add a step to display a URL in the GH summary, pointing to the deployed commit.
=> [DEVOPS-1917] - Display Web deployed commit in GH summary

apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.ts, apps/web/src/app/vault/core/views/collection-admin.view.ts
```
```
In #8758, I switched the Members modal -> Collection tab over to using the `collection.canEdit` getter to determine user permissions. However, this does not take into account the `Manage Users` custom permission, which is specifically for this tab. 
The result is that a custom user with the `Manage Users` permission is seeing disabled collection rows when editing a member:
This is in `rc` for 2024.5.0 so it will need to be cherry-picked. The server-side changes did not make `rc` cut, and are properly feature flagged, so they need a fix but not as urgently.
- **apps/web/src/app/vault/core/views/collection-admin.view.ts** - add a new `canEditUserAccess` getter. The current `canEdit` getter indicates they can edit the collection including any access, `canEditUserAccess` only …
=> [AC-2523] Fix broken members dialog for Manage Users custom permission

apps/browser/gulpfile.js
```
```
The existing beta version isn't guaranteed to be a higher number than the previous one based solely on the last 4 digits of the `GITHUB_RUN_ID` this takes full advantage of the number to create our last 2 digits of our version.
Using UInt16 values keeps up in line with the max allowed in one version slot according to Google. https://developer.chrome.com/docs/extensions/reference/manifest/version
=> Fix Beta Version

apps/web/src/app/billing/organizations/organization-subscription-selfhost.component.html, libs/common/src/billing/models/view/self-hosted-organization-subscription.view.ts
```
```
Subscriptions in self-serve trials do not have a grace period. We need to hide the grace period note when this is the case. This can be identified when the expiration and expiration with grace period are exactly the same.
=> [AC-2403] Hide grace period note when in self-serve trial

apps/browser/src/autofill/background/web-request.background.ts, apps/browser/src/background/main.background.ts, apps/browser/src/manifest.v3.json
```
```
Adds support for auto filling basic auth prompts in the Manifest v3 version of our extension.
https://bitwarden.com/help/basic-auth-autofill/
=> [PM-6144] Basic auth autofill in Manifest v3

apps/web/src/app/layouts/product-switcher/product-switcher-content.component.ts
```
```
Sort organizations by name in the product switcher, resulting in the organizations being iterated over in the same order they are visually displayed in the filters.
- Currently when navigating from Password Manager to Admin Console the first organization that can be access is chosen but it isn't necessarily first alphabetically. 
- **product-switcher-content.component.ts:**
- Sort organizations by `name` attribute
|Before|After|
|------|-----|
|Org "aa bb org" is shown first but not selected when navigating to the Admin Console even though admin permissions are available.| Org "aa bb org" is chosen first when navigating to the Admin Console|
|![before](https://github.com/bitwarden/clients/assets/125900171/6703fb47-cf42-476d-b2fd-a0b83bcabdb8)|![after](https://github.com/bitwarden/c …
=> [PM-6533] Sort organizations by name within product switcher

apps/desktop/src/main/native-messaging.main.ts
```
```
Adds Chrome Mv3 beta extension to the list of allowed native messaging hosts for chrome
=> Add beta extension to allowed native messaging hosts

bitwarden_license/bit-web/src/app/admin-console/providers/settings/account.component.ts
```
```
When a Provider Owner/Admin user deletes the Provider from the Provider Portal Settings page, the user currently remains on the My Provider page. The user should be directed to the Password Manager Vaults page - similar to when an Org Admin/Owner deletes an Organization from the Admin Console Org Settings page.
Navigate to Provider Portal via product switcher
Go to the Setting page
Click ‘Delete provider’
Enter MP and confirm
Expected Result - Green confirmation banner is displayed confirming provider has been deleted and user is taken to the Password Manager Vaults page
Actual Result - Green confirmation banner is displayed confirming provider has been deleted and user remains on the My Provider page in the Provider Portal
- …
=> [AC-2547] Defect - Deleting Provider from Provider Portal should take user to Password Manager Vault page

apps/browser/src/autofill/services/autofill.service.spec.ts, apps/browser/src/autofill/services/autofill.service.ts, apps/browser/src/background/main.background.ts, apps/browser/src/manifest.v3.json, apps/browser/src/platform/background/service-factories/browser-script-injector-service.factory.ts, apps/browser/src/platform/services/browser-script-injector.service.spec.ts, apps/browser/src/platform/services/browser-script-injector.service.ts, apps/browser/src/popup/services/services.module.ts, apps/browser/src/tools/background/fileless-importer.background.spec.ts, apps/browser/src/vault/fido2/background/fido2.background.ts, apps/browser/src/vault/fido2/content/content-script.spec.ts, apps/browser/src/vault/fido2/content/content-script.ts, apps/browser/src/vault/fido2/content/page-script-append.mv2.ts, apps/browser/src/vault/fido2/content/page-script.ts, apps/browser/src/vault/fido2/content/page-script.webauthn-supported.spec.ts, apps/browser/src/vault/fido2/content/page-script.webauthn-unsupported.spec.ts
- Bug fix
The fido2 content script is throwing errors in the extension (clicking on "Errors" from the extensions page).
| | |
| --- | --- | 
| ![Screenshot 2024-04-25 at 11 31 48 AM](https://github.com/bitwarden/clients/assets/1556494/1f36d457-81f9-48a5-aeb7-5a5134691789) | ![Screenshot 2024-04-25 at 11 31 31 AM](https://github.com/bitwarden/clients/assets/1556494/14ed5f18-2d1c-4198-a2b9-ae42bb39ff95) |
- Extra guarding against content script execution in unintended environments prevents the fido2 content script errors from emitting
- Additionally, address errors emitting (improperly?) from host permissions issues in MV3 and update v3 manifest host permissions for proper "all domains":
| | |
| --- | --- |
| ![Screenshot …
=> [PM-7627] [MV3] Do not run fido2 content scripts on browser settings or extension pages

apps/browser/src/platform/services/default-browser-state.service.ts, apps/desktop/src/app/app.component.ts, apps/desktop/src/app/services/services.module.ts, apps/desktop/src/services/encrypted-message-handler.service.ts, apps/desktop/src/services/native-messaging.service.ts, libs/common/src/platform/abstractions/state.service.ts, libs/common/src/platform/services/state.service.ts
```
```
Remove accounts subject from state service. Use account service as the source for known user ids.
- **state service**: remove account subject
- **app component / encrypted message handler **: use account service for userId enumeration
- **native messaging handler**: one case of account enumeration, but mostly awaits and fixes for showing the fingerprint of the requested user rather than whichever happens to be active at the time of the request.
To come is a PR removing session sync, since this was the last usage.
- Ensure that …
=> Use account service for account enumeration.

apps/web/src/app/auth/emergency-access/services/emergency-access.service.spec.ts, apps/web/src/app/auth/emergency-access/services/emergency-access.service.ts, libs/common/src/admin-console/models/domain/encrypted-organization-key.ts, libs/common/src/platform/abstractions/crypto.service.ts, libs/common/src/platform/services/crypto.service.ts, libs/common/src/platform/services/key-state/org-keys.state.spec.ts
```
```
The goal here is to update the requirements of `CryptoService` `rsa{Encrypt|Decrypt}` to disallow the optional private/public key parameters. Before, if someone didn't use the parameter OR passed in `null`/`undefined` we would retrieve the private key/public key of the user for them. If we couldn't retrieve that key we would throw an exception saying `No private key`. Instead if we require this parameter we reduce developer error where they might try to decrypt something that wasn't encrypted with the users key and instead was encrypted with another key. We can also change their call sites to doing the validation that the key exists for themselves and we can throw more specific errors. 
No one was actually not passing in a second parameter of `rsaEncrypt` already but that doesn't …
=> [PM-7907] No more optional `privateKey`

libs/angular/src/auth/components/set-password.component.ts, libs/auth/src/common/login-strategies/auth-request-login.strategy.spec.ts, libs/auth/src/common/login-strategies/auth-request-login.strategy.ts, libs/auth/src/common/login-strategies/login.strategy.ts, libs/auth/src/common/login-strategies/password-login.strategy.spec.ts, libs/auth/src/common/login-strategies/password-login.strategy.ts, libs/auth/src/common/login-strategies/sso-login.strategy.ts, libs/auth/src/common/login-strategies/user-api-login.strategy.spec.ts, libs/auth/src/common/login-strategies/user-api-login.strategy.ts, libs/auth/src/common/login-strategies/webauthn-login.strategy.spec.ts, libs/auth/src/common/login-strategies/webauthn-login.strategy.ts, libs/common/src/auth/services/key-connector.service.ts, libs/common/src/models/response/profile.response.ts, libs/common/src/platform/abstractions/crypto.service.ts, libs/common/src/platform/services/crypto.service.ts, libs/common/src/vault/services/sync/sync.service.ts
```
```
Various tech debt things where `CryptoService` should highly encourage the use of `UserId`, especially for mutations. Many of these uses are in either `SyncService` where the user id is easily available and during the login process where it can be made available with minor changes. 
This also makes the `SymmetricCryptoKey` parameter required in `makeKeyPair`, it updates the two call sites that weren't passing it in with either a `UserKey` that was already in context, and was very recently set or I called the method that `makeKeyPair` used to call for them. …
=> [PM-7907] Encourage The Use of UserId in CryptoService

libs/components/src/item/item-content.component.html, libs/components/src/item/item.component.html, libs/components/src/item/item.stories.ts
```
```
Overflow text in the default and secondary slots of `bit-item` should be truncated. 
See "Text Overflow" story changes
=> [CL-280] truncate overflow text in bit-item

apps/browser/src/platform/popup/layout/popup-tab-navigation.component.ts, apps/browser/src/popup/app-routing.module.ts, apps/browser/src/popup/app.module.ts, apps/browser/src/popup/extension-refresh-route-utils.ts, apps/browser/src/popup/tabs-v2.component.ts, libs/angular/src/utils/component-route-swap.ts, libs/common/src/enums/feature-flag.enum.ts
```
```
Introduce usage of the new `popup-tab-navigation` for the browser refresh.  Also adds some routing helpers to easily swap between components based on a feature flag
This is a generic helper function that allows us to easily swap between components based on some `async` condition. It duplicates the route definition, and applies the provided condition function as a `CanMatchFn`. If the condition passes, the alternate component will be rendered. If it fails, then the route will fallback to the default component. See documentation for example usage.
A reusable wrapper around the `componentRouteSwap()` helper to reduce some of the boilerplate of setting up the swap condition based on the `extension-refresh` feature flag. 
Another helper method that can be used to conditionally redirect …
=> [PM-6827] Browser Extension Refresh - Tabs Routing

apps/web/src/app/billing/organizations/organization-subscription-cloud.component.html, apps/web/src/app/billing/organizations/organization-subscription-cloud.component.ts, libs/common/src/admin-console/models/response/provider/provider.response.ts
```
```
When a provider admin accesses the Org Billing Subscription page through the Admin Console, rather than the Provider Portal, the user is still able to see Manage Billing Subscription 
They should instead see the [design outlined here](https://www.figma.com/proto/m8eMk6yeKfOq4AUuyp70ih/Consolidated-Billing?page-id=698%3A10060&type=design&node-id=873-6419&viewport=-339%2C-3810%2C0.71&t=yF61N9Za3qW0lHMW-1&scaling=min-zoom&starting-point-node-id=913%3A20780)
- Ensure that all …
=> [AC-2558] Provider Admin still sees manage billing options - not the provided image

angular.json, apps/browser/src/platform/popup/layout/popup-layout.stories.ts
```
```
`npm run storybook` is broken after the changes made in https://github.com/bitwarden/clients/pull/9004
Compodoc (a dependency of Storybook) performs static analysis on the Angular code. It fails when parsing [this line](https://github.com/bitwarden/clients/pull/9004/files#diff-2502db9ec554bdfd084c897239c7344e2f693755acd16f1e5986a9141cec2278R327), yielding this error:
```
[10:42:47] Analysing routes definitions and clean them if necessary
Unhandled Rejection at: Promise {
<rejected> InvalidOperationError: Could not find the node's symbol.
/Users/shane/Repos/clients/apps/browser/src/popup/app-routing.module.ts:327:6
> 327 |   ...extensionRefreshSwap(TabsComponent, TabsV2Component, {
at Object.throwIfNullOrUndefined (/Users/shane/Repos/clients/node_modules/@ts-morph/common/dist/ts-mor …
```
=> [PS] fix broken local Storybook

apps/browser/src/auth/popup/lock.component.ts
```
```
#8211 altered native messaging background to respond with `Error` objects rather than strings. This correctly parses those errors into the error descriptions the lock component expects.
Additionally, we were not removing our pending biometric lock if an error was thrown in the catch statement.
=> Handle error object for biometric lock

apps/web/src/app/auth/settings/change-password.component.ts
```
```
Check the current master password client side during the change master password logic:
- Prevent sending new valid key when the user inputted an invalid current master password.
- Allow for faster feedback since it can be done before spending time computing the hash.
Replace the `getOrDeriveMasterKey` by `makeMasterKey` to ensure that the master key is computed from the user input and not retrieved from the store.
Add `decryptUserKeyWithMasterKey` to short circuit the rest of the logic if the user inputted an invalid current password.
Was playing with the client code and though this could be worth it, no idea if you are interested in such modifications.
Have a nice day :).
=> [PM-6749] Check MasterPassword in web app during change

libs/auth/src/angular/anon-layout/anon-layout.component.html
The secondary content in AnonLayout was slightly off center. This PR centers it.
| [Previous](https://components.bitwarden.com/?path=/story/auth-anon-layout--with-long-content)  | [New](https://62a88a6de5b807fa98886113-mnnctvowfr.chromatic.com/?path=/story/auth-anon-layout--with-long-content) |
| ------------- | ------------- |
| ![Screenshot 2024-05-07 at 4 57 03 PM](https://github.com/bitwarden/clients/assets/102181210/07c364d7-f07d-471e-b864-e0b964185aff) | ![Screenshot 2024-05-07 at 4 59 21 PM](https://github.com/bitwarden/clients/assets/102181210/bf68649f-3764-4923-971a-957b16957df1)  |
https://www.chromatic.com/review?appId=62a88a6de5b807fa98886113&number=9079&type=linked&view=activity
=> [Bug Fix] Center secondary content in AnonLayout

apps/browser/src/platform/services/platform-utils/browser-platform-utils.service.ts
```
```
`chrome.runtime.sendMessage` on safari doesn't have a timeout for a response. We are using the lack of a response to determine whether the popup is open or not.
=> [PM-7747] add timeout to safari sendMessageWithResponse

apps/web/src/app/vault/components/vault-items/vault-collection-row.component.ts
```
```
This bug was introduced in https://github.com/bitwarden/clients/pull/8609 because Admin users should see "Can Edit" for the Unassigned Collection.
This PR fixes that by checking if the user is an Admin or (if the V1 feature flag is enabled) by checking if the user can edit any collection.
=> [AC-2484] Fix bug where Custom Users with "Delete any collection" permission incorrectly see "Can Edit" permission for Unassigned Collection

apps/cli/src/bw.ts, apps/cli/src/platform/services/node-env-secure-storage.service.ts, libs/common/src/platform/abstractions/encrypt.service.ts
```
```
Was looking through some code and noticed the `() => CryptoService` smell of avoiding circular dependencies. The methods it was using on `CryptoService` were deprecated anyways in favor of using your own key and calling `EncryptService`. Since this uses a special key and not the user key this will work just fine for us. 
I also noticed that the abstract class of `EncryptService` technically allowed an optional key but it shouldn't. The implementation doesn't expect it to be optional and will throw if a null-ish value is passed in. No one appeared to be using the optional version of it anyways.  …
=> Use encrypt service in node env secure storage

apps/web/src/app/vault/components/vault-items/vault-collection-row.component.ts, apps/web/src/app/vault/components/vault-items/vault-items.component.html, apps/web/src/app/vault/components/vault-items/vault-items.component.ts, apps/web/src/app/vault/org-vault/vault.component.html
```
```
#8858 was merged without updating from `main` first, which means that a call to `organization.canEditUnassignedCiphers` was missing a required parameter. This broke `main`.
Pass the `restrict-provider-access` feature flag value from the org vault -> `VaultItemsComponent` -> `VaultCollectionRowComponent` -> into the method call.
=> [AC-2484] Fix build error caused by canEditUnassignedCiphers

apps/browser/src/auth/popup/settings/account-security.component.ts, apps/desktop/src/app/accounts/settings.component.ts, libs/common/src/services/vault-timeout/vault-timeout-settings.service.spec.ts, libs/common/src/services/vault-timeout/vault-timeout-settings.service.ts
```
```
1. To fix the `VaultTimeoutSettingsService.setVaultTimeoutOptions` method condition which needed to use `never` instead of null which I missed in #8604
2. To fix the fact that the never lock warning dialog wasn't properly shown to users on browser or desktop anymore
- **libs/common/src/services/vault-timeout/vault-timeout-settings.service.ts:** Replace a null check with a check for the `VaultTimeoutStringType.Never`
- **libs/common/src/services/vault-timeout/vault-timeout-settings.service.spec.ts** Test the fix to ensure it can't happen again
- **apps/browser/src/auth/popup/settings/account-security.component.ts:** Fix browser never lock warning not showing up
- **apps/desktop/src/app/accounts/settings.component.ts:** Fix desktop never lock warning not showing up
- Please add …
=> PM-5501 - VaultTimeoutSettingsSvc State Provider Migration - Small bugfixes

libs/auth/src/common/services/pin/pin.service.implementation.ts
Fixes a part of the `decryptAndMigrateOldPinKeyEncryptedMasterKey()` method where `undefined` was getting wrapped in `new EncString(undefined)` and passed into `masterPasswordService.decryptUserKeyWithMasterKey()`, resulting in an error.
=> [PM-5363] PinService Migration Fix

apps/web/src/app/vault/org-vault/vault.component.html
```
```
The Unassigned collection appears to be represented by `selectedCollection = null`. However, I was missing a null check in #9118. This means that the restricted access page fails to load (specifically for providers if provider access is restricted).
Add additional null checks. The Unassigned collection is not a real collection, so you cannot view or edit it, which means that these input values will default to false in this case anyway - as intended. …
=> [AC-2487] Fix restricted access view not loading for Unassigned

apps/web/src/app/layouts/product-switcher/navigation-switcher/navigation-switcher.component.html, apps/web/src/app/layouts/product-switcher/navigation-switcher/navigation-switcher.component.spec.ts, libs/components/src/navigation/nav-item.component.ts, libs/components/src/navigation/nav-item.stories.ts
```
```
The product switcher shown within the navigation has a requirement that the items be shown as "active" when any route within the specific product is active. The current implementation of the the navigation item uses `routerLinkActiveOptions` to show the active style automatically. 
In this case, that won't work because the link destination and the current path are different.
Adding an Input to force active styles to be shown.
- **nav-item.component.ts:**
- Add `forceActiveStyles` Input that defaults to `false
- **nav-item.stories.ts:**
- Add stories to show the new attribute
- **navigation-switcher.component.html:** 
- Pass `isActive` attribute of the product, this is how the current product switcher works in the upper right
- Please add **unit tests** where it makes sense to do …
=> [PM-8017] Force active styles for navigation items

apps/web/src/app/auth/anon-layout-wrapper.component.ts, libs/auth/src/angular/anon-layout/anon-layout.component.html
- Makes the AnonLayout page background `tw-bg-background-alt`
- Makes the AnonLayout primary content area `tw-bg-background`
- Removes `layout_frontend` class from body element
https://62a88a6de5b807fa98886113-uyskarvklc.chromatic.com/?path=/docs/documentation-introduction--docs
=> Update AnonLayout BG Colors

apps/web/src/app/admin-console/organizations/manage/group-add-edit.component.ts
```
```
Fix a bug where the edit group modal wasn't loading for a provider when "allow admin access to all collections" was off.
When this setting is off, a user cannot add themselves to a group. The code that does this assumes that the user is a member of the org, which is not true for a provider, so it was throwing a null error.
Add in a null check and explanatory comment. If the user is not a member of the org, there is nothing to remove from the list. …
=> [AC-2602] Fix groups modal not loading for providers

apps/browser/src/background/main.background.ts, apps/browser/src/platform/offscreen-document/offscreen-document.service.spec.ts, apps/browser/src/platform/offscreen-document/offscreen-document.service.ts, apps/browser/src/popup/services/services.module.ts
```
```
The API has race issues with determining if an offscreen document exists (https://groups.google.com/a/chromium.org/g/chromium-extensions/c/s2Wp55bjySE/m/SnjJu1MdAAAJ). However, there are no negative effects of attempting to open multiple other than this throw.
=> [PM-8159] [PM-8158] [PM-8156] Swallow multiple offscreen document errors

apps/browser/src/platform/popup/popup-section-header/popup-section-header.component.html, apps/browser/src/platform/popup/popup-section-header/popup-section-header.component.ts, apps/browser/src/platform/popup/popup-section-header/popup-section-header.stories.ts, apps/browser/src/popup/app.module.ts
```
```
Adds a new PopupSectionHeader component to be used within the browser extension refresh 
- **popup-section-header.*** 
- Implementation of heading component & associated stories
- I followed the implementation pretty closely that is in [PM-7878](https://bitwarden.atlassian.net/browse/PM-7878).
- With the each title slot having to implement `noMargin class="tw-mb-0"` would this be better off as an input rather than a slot?
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing …
=> [PM-7878] PopupSectionHeader component

apps/web/src/app/billing/shared/adjust-payment-dialog.component.ts
```
```
Adding a payment method using the modal on the Payment Method page currently succeeds, but throws a Toast error because the unneeded invocation of the `PaymentMethodWarningService` fails. We should only invoke this if the FF is on.
https://github.com/bitwarden/clients/assets/144709477/5648e776-34f3-496b-aaf2-f59918254de2
=> [AC-2598] Only call PaymentMethodWarningService when FF is on

apps/web/src/app/admin-console/organizations/manage/group-add-edit.component.html, apps/web/src/app/admin-console/organizations/manage/group-add-edit.component.ts, apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.html, apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.ts, apps/web/src/app/vault/components/collection-dialog/collection-dialog.component.html, apps/web/src/app/vault/org-vault/bulk-collections-dialog/bulk-collections-dialog.component.html, apps/web/src/locales/en/messages.json
```
```
When `Allow owners and admins to manage all collections` is off, the members modal -> collection tab was missing additional copy: `You can only assign collections you manage.`
- **apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.ts** - rename `restrictedAccess$` to `restrictEditingSelf$` to be more specific. Separate out the collection management setting to its own observable, `allowAdminAccessToAllCollectionItems$`, so that we can use it to display this missing copy (which only depends on the setting, not on editing yourself).
- everything else is basically name updates - e.g. we already had this copy in `messages.json` but its i18n string was `editGroupCollectionsRestrictionsDesc`, which isn't accurate now that we're using it …
=> [AC-2610] [AC-2613] Fix copy in members and groups dialogs

apps/browser/src/platform/popup/layout/popup-header.component.html
```
```
The back navigation on the popup-header component isn't working. I thought this might have been a bug in one of the consuming components, but turns out the back()-method isn't wired to the backButton.
- **apps/browser/src/platform/popup/layout/popup-header.component.html:** Wire up the button click to execute `back()`
=> [CL-288] Fix the back navigation on the popup-header component

apps/web/src/app/vault/org-vault/vault.component.html, apps/web/src/app/vault/org-vault/vault.component.ts
```
```
#8265 added functionality to hide the Vault filter section for providers that was not properly hidden behind the `restrict-provider-access` feature flag. This PR ensures the section is only hidden when the flag is enabled.
Add a `hideVaultFilters` getter that takes the feature flag into consideration.
=> [AC-2601] Hide Vault filters for providers when flag enabled

apps/browser/src/auth/popup/account-switching/current-account.component.ts, apps/browser/src/popup/app.module.ts
```
```
While trying to implement the new `popup-page` on the [new settings-page](https://github.com/bitwarden/clients/pull/9213), I noticed the `app-current-account` is not standalone yet. This will be needed for any other pages/components that are also standalone.
- **apps/browser/src/auth/popup/account-switching/current-account.component.ts:** Mark the component as standalone and import necessary modules
- **apps/browser/src/popup/app.module.ts:** Remove CurrentAccountComponent from declarations and add it as an import
- Ensure that …
=> [CL-287] Make `app-current-account` a standalone component

apps/browser/src/_locales/en/messages.json, apps/browser/src/background/nativeMessaging.background.ts, apps/desktop/src/services/native-messaging.service.ts
```
```
#9023 allowed reading of any user to be requested through browser IPC requests. However, this neglects that the user key will then necessarily be loaded into memory without being protected by process reload.
Process reload is the means by which we protect user keys in memory. once an account locks, it triggers a process reload (assuming no other accounts are unlocked), that frees renderer memory.
However, if the user is not unlocked, it is not protected by the process reload, so we may keep user keys in memory.
<details>
<summary>Displayed when the requested user to unlock is not logged in or is locked on the desktop client</summary>
</details> …
=> [PM-8197] Do not allow browser biometric for locked account

apps/browser/src/background/main.background.ts
```
```
This PR is an alternative to #9225, where we specifically wait for account switch to register before proceeding. There are `activeAccount` dependencies in update-badge that were hanging due to the active account not yet propagating through.
=> Wait for account to switch before proceeding

apps/browser/src/background/runtime.background.ts
- Bug fix
Resolve a scenario whereby a user whose account is locked logs into a form and attempts to save the entered credentials via the Bitwarden notification bar. They will be prompted to unlock their vault and upon successfully unlocking via the pop up window, will be left in a state where the notification bar does not dismiss, nor is the cipher saved.
`refreshBadge` appears to be blocking subsequent block calls from executing. The underlying cause has been traced to `cipherService.getAllDecrypted` (via `getAllDecryptedForUrl`), but for the short term, moving `refreshBadge` (and `refreshMenu`, which makes the same call) resolves these UX issues while we examine how to proceed in the long-term.
- This fix also [requires the `multithreadDecryption` feature flag to be …
=> [PM-8156] Bugfix - Defer badge and menu state updates

apps/browser/src/platform/popup/layout/popup-layout.mdx, apps/browser/src/platform/popup/layout/popup-layout.stories.ts, apps/browser/src/platform/popup/layout/popup-page.component.html
```
```
The extension layout component should grow to fill 100% of the available height. Otherwise, devs will be unable to vertically center page content. See: https://github.com/bitwarden/clients/pull/9199#issuecomment-2113504341
- **apps/browser/src/platform/popup/layout/popup-layout.stories.ts:** Add story
- **apps/browser/src/platform/popup/layout/popup-page.component.html:** propogate `tw-h-full` down element tree
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibil …
=> [CL-290] make popup layout grow to full height

apps/desktop/src/app/accounts/settings.component.ts
```
```
Enabling the DuckDuckGo integration is showing an error modal, but the integration works after dismissal.
This error has been happening for a while, and there will have to be some deeper investigation into it. Do not show the error modal for now.
=> [PM-8265] Do not show error modal on enabling DDG integration

apps/browser/src/autofill/services/autofill.service.ts
- Bug fix
A regression was introduced with [these changes](https://github.com/bitwarden/clients/pull/8863/files#diff-ff919521412a590452c7e201f94d1c80997766b29cf4870faa84275768edc6a8L115-L120) where the inline menu (with the unlock your vault prompt) would appear if there was no active user. That menu should not appear in that scenario.
Replace the original check for active accounts before using the (global) `inlineMenuVisibility` setting …
=> [PM-8287] Do not show the inline menu when there are no active users

apps/web/src/app/billing/organizations/organization-plans.component.html
```
```
Currently all subscription plans can be selected at the same time, should make it only one selectable at a time.
- **organization-plans.component.html:** Changed the *ngFor directive to be inside radio button group.
https://github.com/bitwarden/clients/assets/162679756/dbab53a4-45ea-48f5-9baf-a5df52990a43
=> PM-8045 All Subscription plans can be selected same time

apps/browser/src/tools/popup/settings/export.component.html, apps/browser/src/tools/popup/settings/export.component.ts, apps/desktop/src/app/tools/export/export.component.html, apps/desktop/src/app/tools/export/export.component.ts, apps/web/src/app/admin-console/organizations/tools/vault-export/org-vault-export.component.ts, apps/web/src/app/tools/vault-export/export.component.ts, libs/tools/export/vault-export/vault-export-ui/package.json, libs/tools/export/vault-export/vault-export-ui/src/components/export.component.ts
```
```
On the web we use the new `UserVerificationDialogComponent` which supports additional verification methods besides a user’s master password.
This possibility is currently missing on browser and desktop, which fails for user’s that login with for example a `passkey` or `Login with Device`
This also pays forward on the initiative to create a shareable export component which can be used across clients which would also enable password-encrypted exports to browser and desktop.
- **Move/replace submit and userVerification logic from web into the BaseExportComponent -** https://github.com/bitwarden/clients/commit/662a659d08a13b96206ef00ad17b251e5038235f
- Add "@bitwarden/auth" as dependency to the vault-export-ui package
- New submit logic also checks for password-encrypted exports which …
=> [PM-8252] Use new user-verification for exports on all clients

libs/common/src/state-migrations/migrations/62-migrate-vault-timeout-settings-svc-to-state-provider.spec.ts, libs/common/src/state-migrations/migrations/62-migrate-vault-timeout-settings-svc-to-state-provider.ts
```
```
[PM-5501](https://bitwarden.atlassian.net/browse/PM-5501)
To remove the global vault timeout data **on desktop** as it is no longer referenced or used. It was stored in a different key format which meant that the migration which successfully deleted the global data on other clients didn't work on desktop. 
- **libs/common/src/state-migrations/migrations/62-migrate-vault-timeout-settings-svc-to-state-provider.ts:** Remove desktop formatted global values
- **libs/common/src/state-migrations/migrations/62-migrate-vault-timeout-settings-svc-to-state-provider.spec.ts** Test change …
=> Auth/PM-5501 - VaultTimeoutSettingsSvc State Provider Migration - Cleanup desktop orphaned data

apps/browser/src/auth/popup/account-switching/services/account-switcher.service.spec.ts, apps/browser/src/auth/popup/account-switching/services/account-switcher.service.ts, apps/browser/src/autofill/background/overlay.background.spec.ts, apps/browser/src/autofill/background/overlay.background.ts
```
```
We are experiencing a hang due to https://github.com/bitwarden/clients/blob/e8ed4f38f48aa644df57dfc8a3d4913dcf8b5573/apps/browser/src/background/main.background.ts#L1218 and the fact that the auth status is not updated during account switch for this service. Ideally, the service would just use latest everywhere, but this is sufficient for this bug fix.
Account-switcher changes avoid multiple updates for the same event.
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/ac …
=> Retrieve auth status when updating overlay ciphers.

apps/browser/src/auth/popup/account-switching/current-account.component.ts
```
```
A regression was found where a user was not able to re-enter the account-switcher after clicking on `Add account`
Originally caused with work done on https://github.com/bitwarden/clients/pull/9215
This should override the need to revert with https://github.com/bitwarden/clients/pull/9291
- **apps/browser/src/auth/popup/account-switching/current-account.component.ts:** Add `RouterModule` to the imports of the standalone `CurrentAccountComponent`
https://github.com/bitwarden/clients/assets/2670567/6729611c-94f8-4963-9d20-0d9a9f1bb9dc
- If this change has particular **deployment requirements** - notify the DevOps …
=> [PM-8311] Add missing RouterModule to the CurrentAccountComponent

libs/common/spec/utils.ts, libs/common/src/vault/models/domain/collection.spec.ts, libs/common/src/vault/models/domain/collection.ts, libs/common/src/vault/services/collection.service.ts, libs/importer/src/importers/bitwarden/bitwarden-json-importer.ts, libs/tools/export/vault-export/vault-export-core/src/services/org-vault-export.service.ts
magical black-box key retrieval is slow, due to needing to repeatedly resolve (and potentially decrypt) keys. Doing the work up front is both more explicit and much faster.
```
```
The collection service was using auto-magical key resolutions to decrypt collections, which is slow due to repeated retrieval and potentially needing to redecrypt the custody chain for the user’s keys many times.
That particular user is laggy in the tab and vault views, likely for similar reasons.
This slowness was revealed through testing upgrade paths rather than just identifying it from fresh installs. What doesn’t make sense is why the upgrade path reveals these issues. There may be something deeper here that this fix patches over by better practices in key handling.
There are only two real changes here, …
=> Prefer prefetching keys

libs/importer/src/components/import.component.ts
Fixes a bug where `PinService` was undefined on the `ImportService` causing the import component to throw an error. Resolved by adding `PinService` to `ImportComponent` and wrapping dependencies in `SafeProvider()` for added safety.
If reviewer wants to also test locally:
1. Log in as an owner of an organization
2. Navigate to Admin Console > Settings >Export
3. Select encrypted json option and password protected option
4. Set a password and export
5. navigate to Import page and try to import the encrypted json file with password set
Or
1. Log in as a user in web vault
2. Navigate to Tools > Export Vault
3. Select encrypted json option and password protected option
4. Set a password and export
5. navigate to Import page and try to import the encrypted json file with password set …
=> [PM-8295] Fix ImportService DI

apps/browser/src/popup/scss/misc.scss, apps/browser/src/vault/popup/components/vault/vault-v2.component.html
```
```
Changes in #9199 inadvertently broke the spacing in the current browser vault list app icons. This PR re-adds the previous style in the form of a temporary addition to `styles.css` for browser (similar to what we had to do for Desktop). 
Also adds some list Ids to the vault list items containers for QA test automation.
=> [PM-6825] Fix app icon styling in Browser

apps/web/src/app/vault/components/vault-items/vault-collection-row.component.html, apps/web/src/app/vault/components/vault-items/vault-collection-row.component.ts, apps/web/src/app/vault/components/vault-items/vault-items.component.ts, apps/web/src/app/vault/core/collection-admin.service.ts, apps/web/src/app/vault/core/views/collection-admin.view.ts, apps/web/src/app/vault/org-vault/vault.component.ts, apps/web/src/app/vault/utils/collection-utils.ts, libs/common/src/admin-console/models/domain/organization.ts, libs/common/src/vault/models/domain/collection.spec.ts, libs/common/src/vault/models/response/collection.response.ts, libs/common/src/vault/models/view/collection.view.ts
```
```
Orphaned/Unmanaged collections broke many assumptions in our permission getters and required complicated client side logic to determine if a user has the ability to manage the orphaned collection. We decided to move that logic into the serverside sproc in https://github.com/bitwarden/server/pull/4108 in the form of an `Unmanaged` property on the collection.
This PR utilizes the new `Unmanaged` property in the `CollectionAdminView` permission getters (`canEdit`, `canEditUserAccess`, etc..) to avoid the need to calculate in multiple places. Now that its in the getters, this PR also removes/updates the repeated logic that was implemented for the "AddAccess" badge story.
- Add the `Unmanaged` property
- Remove helpers that were used to determine if a collection was unmanaged …
=>  [PM-8004] [AC-2603] [AC-2616] [AC-2621] [AC-2622] Unmanaged collection fixes

apps/browser/src/platform/popup/popup-section-header/popup-section-header.component.html, apps/browser/src/platform/popup/popup-section-header/popup-section-header.stories.ts, apps/browser/src/vault/popup/components/vault-v2/autofill-vault-list-items/autofill-vault-list-items.component.html, apps/browser/src/vault/popup/components/vault-v2/autofill-vault-list-items/autofill-vault-list-items.component.ts, apps/browser/src/vault/popup/components/vault-v2/vault-list-items-container/vault-list-items-container.component.html, apps/browser/src/vault/popup/components/vault-v2/vault-list-items-container/vault-list-items-container.component.ts
```
```
Add the refresh button for the autofill items section when the popup is in the FF sidebar. Also, this tweaks the popup-section-header to properly align the `title-suffix` slot with the title and adds a corresponding story.
- `popup-section-header.component.html` - Add `tw-flex tw-items-center tw-gap-1` classes to `h1` container.
- `autofill-vault-list-items/autofill-vault-list-items.component.html` - Add logic to show refresh button and call service to refresh the current tab.
- `vault-list-items-container/vault-list-items-container.component.ts` - Add Input/Outputs for showing refresh button.
Also see new story in storybook. …
=> [PM-8333] Autofill refresh button for sidebar popup (Firefox)

libs/components/src/button/button.component.ts, libs/components/src/item/item-content.component.ts
```
```
The button and item-content components should not have text decoration when used with an anchor element. This was missed due to certain global styles being present in the web app but not the extension.
Before:
After:
https://github.com/bitwarden/clients/assets/17113462/e3e942a9-d60b-468b-b660-5bc548eef087
=> [CL-289] fix text decoration in CL button and item-content

bitwarden_license/bit-web/src/app/admin-console/providers/manage/people.component.html, bitwarden_license/bit-web/src/app/admin-console/providers/manage/user-add-edit.component.ts
> Provider portal was missing/using incorrect text for the `invite member` button and dialog
- **.../providers/manage/people.component.html**: Changed `inviteUsers` to `inviteMember` to align with `Admin Console` flow
- **.../providers/manage/user-add-edit.component.ts**: Updated both `invite` and `edit` strings to use the `member` verbiage that also aligns with `Admin Console` flow
=> [PM-1210] Provider invite/edit member text

apps/web/src/app/vault/individual-vault/vault-onboarding/vault-onboarding.component.html, apps/web/src/app/vault/individual-vault/vault-onboarding/vault-onboarding.component.spec.ts, apps/web/src/app/vault/individual-vault/vault-onboarding/vault-onboarding.component.ts, libs/common/src/enums/feature-flag.enum.ts
```
```
removes the `vault-onboarding` feature flag for the end-user onboarding component since this feature is live
- **vault-onboarding.component.html ** removed `showOnboardingAccess` so that it doesnt check the feature flag value
- **vault-onboarding.component.ts** removing getting feature flag & storing it in variable
- **feature-flag.enum.ts** removes corresponding flag from shared enum
- **vault-onboarding.component.spec.ts** remove `ConfigService` from being mocked in the spec …
=> [PM-6606] remove onboarding feature flag

apps/browser/src/vault/services/vault-browser-state.service.ts, apps/web/src/app/vault/individual-vault/vault-banners/services/vault-banners.service.ts, apps/web/src/app/vault/individual-vault/vault-onboarding/services/vault-onboarding.service.ts, libs/common/src/vault/services/collection.service.ts, libs/common/src/vault/services/key-state/ciphers.state.ts, libs/common/src/vault/services/key-state/collapsed-groupings.state.ts, libs/common/src/vault/services/key-state/folder.state.ts, libs/common/src/vault/services/key-state/vault-settings.state.ts
```
```
UserKeyDefinitions are purpose built for storing user data and offer the ability to ensure cleanup on user status events.
This PR moves vault code that uses user-scoped state to UserKeyDefinitions.
Please be sure that each `clearOn` definition aligns with expectations. Particularly the component ones are just educated guesses on my part.
=> Use User Key Definitions for user-scoped data

apps/browser/src/tools/popup/services/key-definitions.ts
```
```
UserKeyDefinitions are purpose built for storing user data and offer the ability to ensure cleanup on user status events.
This PR moves tools code that uses user-scoped state to UserKeyDefinitions.
Please be sure that each clearOn definition aligns with expectations. My gut says that component data isn't relevant past a lock, but I'm not very familiar on the usage of this data.
=> Prefer UserKeyDefinition for user-scoped data

apps/browser/src/autofill/services/autofill.service.spec.ts, apps/browser/src/autofill/services/autofill.service.ts, apps/browser/src/background/main.background.ts, apps/browser/src/popup/services/services.module.ts
https://bitwarden.atlassian.net/browse/PM-8447
Resolves https://github.com/bitwarden/clients/issues/9369
An issue was identified in mv3 where injection of the autofill on load script shortly after the browser has initialized can cause the decryption process for ciphers to hang. To resolve this, we are avoiding injection of the autofill on load content script in cases where the user's account is locked. While we have guards in place to avoid triggering autofill on load in a locked state, this now further guards the behavior and ensures that we do not attempt to trigger a decryption of ciphers in a state where organization keys are not present in the state of the extension.
https://github.com/bitwarden/clients/assets/16629865/7e6af46f-9c92-4871-8d05-c75bb8b7a7c9 …
=> [PM-8447] Autofill On Load Causes Decryption to Hang After Browser Startup

apps/web/src/app/vault/org-vault/vault.component.html
> Users that do not have permission to view event logs specific to a cipher were given the menu option within the vault item's row. Hide the menu option when the accessing user does not have permission to view the event logs.
- **apps/web/src/app/vault/org-vault/vault.component.html:** Updated the `useEvents` input to be evaluated based on the `canAccessEventLogs`. This shows the menu for Owners, Admins, Providers, and custom users with the AccessEventLogs permission
https://github.com/bitwarden/clients/assets/26154748/e7e8d191-e4de-4083-ad3f-bc8c2d350788 …
=> [PM-7024] - BUG - View events for cipher available for users without permission

libs/importer/src/importers/lastpass/access/services/parser.ts
```
```
Adding info on which step of the parse an error was thrown to help further debugging.
- **parser.ts:** Added a step counter that should add log info to the throw and indicates where the user was before the error
=> [PM-7875] Add log to which step parse failed on LastPass import

apps/web/src/app/auth/key-rotation/user-key-rotation.service.spec.ts, apps/web/src/app/auth/key-rotation/user-key-rotation.service.ts
```
```
Adds client side guardrails on key rotation to prevent corrupting the vault when
- Sync requests timed out/failed
- Local cipher decryption failed
Reproduction steps for the corruption this prevents are here: #7709
Server side check for ciphers here: https://github.com/bitwarden/server/pull/4098
=> [PM-5938] Prevent vault coruption on key-rotation on desycned vault

apps/browser/src/auth/popup/lock.component.ts, apps/desktop/src/auth/lock.component.spec.ts, apps/desktop/src/auth/lock.component.ts, libs/angular/src/auth/components/lock.component.ts, libs/common/src/vault/services/sync/sync.service.ts
```
```
Notifications for logout or account changes are only processed while an account is unlocked. This means that if an account change occurs while locked, or the account gets deleted while locked, the client (browser/desktop) does not know about this, even after unlocking. This leads to items being desynced, and if the account was deleted, the client is in a broken state.
This PR fixes that, by, upon unlock checking if a full sync is required. Since fullSync checks the account revision timestamp, the "expensive" full sync only happens when needed, and thus prevents a desynced state. Further, the account revision timestamp is negative if (and only if) the account was deleted. In this case we log the client out. (We might want to change this on the server side to give a proper error …
=> [PM-3050] Add sync on unlock, logout when account is deleted

apps/browser/src/autofill/background/notification.background.spec.ts, apps/browser/src/autofill/background/overlay.background.spec.ts, apps/browser/src/autofill/content/autofill-init.spec.ts, apps/browser/src/autofill/content/content-message-handler.spec.ts, apps/browser/src/autofill/spec/testing-utils.ts, apps/browser/src/platform/offscreen-document/offscreen-document.spec.ts, apps/browser/src/vault/fido2/background/fido2.background.spec.ts
https://bitwarden.atlassian.net/browse/PM-8480
A testing utility method that sends a mock extension message has a confusing/ambiguous name of `sendExtensionRuntimeMessage`. This needs to be renamed to ensure that our team understands the purpose of that method. I’ll be modifying the method name to `sendMockExtensionMessage`. This change should not affect any logic in production. The change strictly affects testing files. …
=> [PM-8480] Rename ambiguous Jest testing method

libs/common/src/platform/models/domain/enc-string.spec.ts, libs/common/src/platform/models/domain/enc-string.ts
https://bitwarden.atlassian.net/browse/PM-8436
https://bitwarden.atlassian.net/browse/PM-8483
A change was made in #9191 to use `EncryptService` instead of `CryptoService` to do the RSA decryption of organization keys. This changes it to parse the string data with `EncString` and take the `.dataBytes` property vs relying on `CryptoService.rsaDecrypt` logic to handle getting the data as bytes. `EncString` didn't have cases for encryption types 5 & 6 so it left the `data` & `mac` properties `undefined`. When those are null, so would `get dataBytes` and that would cause `SubtleCrypto.decrypt` to throw. All we have to do is set the data to the correct piece (I also do `mac` even though it's never actually used). This should fix the decryption of organization keys from ~2018. 
- Contributor …
=> [PM-8436] [PM-8483] Support Asymmetric Mac Encryption Types in EncString

apps/desktop/native-messaging-test-runner/package-lock.json, apps/desktop/native-messaging-test-runner/package.json
https://bitwarden.atlassian.net/browse/PM-8516
I was reviewing node related dependencies, and `@tsconfig/node16` references node16. Since it's unused it's better to remove it than upgrading it.
- 🤔 …
=> [PM-8516] Remove unused dependency `@tsconfig/node16`

apps/browser/src/autofill/content/autofill-init.spec.ts, apps/browser/src/autofill/utils/index.spec.ts, apps/browser/src/vault/fido2/content/page-script.webauthn-supported.spec.ts, apps/browser/test.setup.ts
I ran into this issue while adding tests in https://github.com/bitwarden/clients/pull/9365. I'm pulling it into a separate PR to be discussed/reviewed separately and not get lost in my other PR.
Add `import "jest-preset-angular/setup-jest";` to `test.setup.ts` in the browser application.
- This is needed for certain Angular/TestBed features. It's also included in other applications `test.setup.ts` file
This caused 3 existing tests to break. Based on from what I can tell, the root cause is now Promises are replaced and integrated with `zone`.
- `autofill-init.spec.ts`
- Error: `sendResponse` was not being called
- Fix: use `flushPromises` rather than await a dummy promise 
- `page-script.webauthn-supported.spec.ts`
- Error:  `require("./page-script");` was being called which runs the …
=> Browser - Add `jest-preset-angular`

apps/web/src/app/auth/core/services/webauthn-login/request/webauthn-login-attestation-response.request.ts
```
```
https://bitwarden.atlassian.net/browse/PM-8134
We should have used base64url, but accidently used base64
=> Fix PM-8134: Change b64 to b64url

libs/auth/src/angular/user-verification/user-verification-form-input.component.ts, libs/common/src/auth/services/user-verification/user-verification.service.ts
[PM-8358](https://bitwarden.atlassian.net/browse/PM-8358).  
To resolve displaying an incorrect error if the user verification dialog is opened with the "server" (default) flow with a MP and immediately submitted with an empty secret.  
- …
=> Auth/PM-8358 - User Verification dialog & form input fix for empty submit displaying wrong error

libs/auth/src/angular/anon-layout/anon-layout.component.html
Adds a `tw-min-w-64` to anonlayout primary content to help with "thin" content.
This example is from `/accept-emergency`
| Before  | After |
| ------------- | ------------- |
| ![image](https://github.com/bitwarden/clients/assets/102181210/b3d54ab6-2f1b-45bd-92bd-2682df2d0705)  | ![Screenshot 2024-06-03 at 1 29 04 PM](https://github.com/bitwarden/clients/assets/102181210/cd5aca63-7ff6-419c-a34d-a0cebadb700e)  | …
=> Min-width to anonlayout

bitwarden_license/bit-cli/src/admin-console/device-approval/deny-all.command.ts, bitwarden_license/bit-cli/src/admin-console/device-approval/deny.command.ts, bitwarden_license/bit-cli/src/admin-console/device-approval/device-approval.program.ts
https://bitwarden.atlassian.net/browse/AC-1679 and subtasks
Implement the `deny` and `deny-all` commands for device approvals in the CLI.
This follows the same patterns as the other commands we've done.
Note that I had to add `organizationId` as a parameter to `deny` because our REST api requires it.
Deny:
```
Usage: bw device-approval deny [options] <organizationId> <requestId>
Deny a pending request
Arguments:
organizationId  The id of the organization
requestId       The id of the request to deny
Options:
-h, --help      display help for command
```
Deny all:
```
Usage: bw device-approval deny-all [options] <organizationId>
Deny all pending requests for an organization
Options:
-h, --help  display help for command
```
- All formatters and local linters …
=> [AC-2635] [AC-2636] Add device-approval deny and deny-all commands

.github/workflows/release-desktop-beta.yml
https://bitwarden.atlassian.net/browse/BRE-94
Replace `dawidd6/action-download-artifact` with `bitwarden/gh-actions/download-artifacts`. …
=> [BRE-94] Replace `dawidd6/action-download-artifact` with `bitwarden/gh-actions/download-artifacts`

.github/workflows/test.yml, libs/shared/jest.config.angular.js
Improve jest performance and split execution plan for dev vs CI. 
Locally, utilizing resources based on thread availability improves performance vs fixed threading.
<details>
<summary>my hyperfine results</summary>
```
❯ hyperfine 'npm test' 'npm test -- --maxWorkers=50%' 'npm test -- --maxWorkers=25%'
Benchmark 1: npm test
Time (mean ± σ):     34.298 s ±  0.371 s    [User: 115.773 s, System: 14.455 s]
Range (min … max):   33.880 s … 34.978 s    10 runs
Benchmark 2: npm test -- --maxWorkers=50%
Time (mean ± σ):     24.585 s ±  0.504 s    [User: 140.707 s, System: 18.622 s]
Range (min … max):   23.856 s … 25.460 s    10 runs
Benchmark 3: npm test -- --maxWorkers=25%
Time (mean ± σ):     34.489 s ±  0.455 s    [User: 116.269 s, System: 14.511 s]
Range (min … max):   33.835 s … 35.374 s …
```
=> Improve jest performance

libs/common/src/tools/state/buffered-state.spec.ts
pre work for #8669
Currently KeyDefinitions and UserKeyDefinitions are interchangeable, but internally BufferedState already uses UserKeyDefinitions and extends UserKeyDefinitionOptions, so testing with that class makes more sense.
Additionally, #8669 is lined up to separate KeyDefinitions as global-only state and UserKeyDefinitions as user-scoped state. …
=> Prefer UserKeyDefinitions for `getUser` state

apps/browser/src/vault/popup/services/vault-popup-list-filters.service.spec.ts, apps/browser/src/vault/popup/services/vault-popup-list-filters.service.ts
[PM-8587](https://bitwarden.atlassian.net/browse/PM-8587)
Swap icons for collections in the extension filters. 🤦 I'm not sure what designs I was looking at before.
|Folder -> `bwi-folder`|Collection -> `bwi-collection`|
|----------------------|------------------------------|
|![Screen Shot 2024-06-04 at 16 03 33 PM](https://github.com/bitwarden/clients/assets/125900171/39288e8c-ff6e-46cb-8ed5-5726484f2bab)|![Screen Shot 2024-06-04 at 16 03 51 PM](https://github.com/bitwarden/clients/assets/125900171/d77c87cc-c8a6-4f1f-b64b-c7d13c2836aa)| …
=> [PM-8587] Update icons for folder & collection filters

libs/auth/src/angular/anon-layout/anon-layout.component.html, libs/auth/src/angular/anon-layout/anon-layout.stories.ts
Adds a `tw-min-w-[28rem]` to anon-layout.
https://62a88a6de5b807fa98886113-mkkhfpgsrc.chromatic.com/?path=/story/auth-anon-layout--with-thin-primary-content …
=> Larger min-w to anonlayout content container

libs/common/spec/observable-tracker.ts, libs/common/src/platform/services/app-id.service.spec.ts, libs/common/src/platform/services/app-id.service.ts
https://bitwarden.atlassian.net/browse/PM-8285
Resolves a race condition when retrieving app ids where quickly subscribing multiple times would trigger the update function multiple times.
This could not be resolved by converting to a hot observable because of context sharing in the browser. Instead, I'm just using a switchmap and should update to determine what the valid appId is and filtering duplicates due to the switch map. …
=> [PM-8285] Resolve app id race

libs/components/src/async-actions/form-button.directive.ts, libs/components/src/async-actions/in-forms.stories.ts
https://bitwarden.atlassian.net/browse/CL-243
Fix an issue where `bitFormButton` will enabled buttons that were initially disabled.
See Storybook
https://github.com/bitwarden/clients/assets/17113462/decd1df0-4b17-421e-b316-2d53387d2d9d
- …
=> [CL-243] honor initial disabled state in `bitFormButton`

libs/angular/src/auth/components/login-via-auth-request.component.ts
https://bitwarden.atlassian.net/browse/PM-8590
Auth requests require an exactly 25-character credential, but the password generator defaults to "passphrases", which don't respect the character limit. Specifying the type explicitly ensures a password respecting the character limit is generated.
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or …
=> [PM-8590] specify generator algorithm

apps/browser/src/platform/popup/layout/popup-page.component.html
https://bitwarden.atlassian.net/browse/CL-302
The main content in the popup layout should have visible bottom padding when it is a scroll container. 
Before: 
After: …
=> [CL-302] respect bottom padding in scrollable popup-layout

apps/browser/src/vault/popup/services/vault-popup-list-filters.service.spec.ts, apps/browser/src/vault/popup/services/vault-popup-list-filters.service.ts
[PM-8623](https://bitwarden.atlassian.net/browse/PM-8623)
- Free organizations should show the family icon rather than the business icon
- Add tests for all icon variants 
|Before|After|
|------|-----|
|![Screen Shot 2024-06-06 at 09 19 30 AM](https://github.com/bitwarden/clients/assets/125900171/03e1d211-7a55-4c6c-a35f-cba2112d6761)|![Screen Shot 2024-06-06 at 09 19 13 AM](https://github.com/bitwarden/clients/assets/125900171/ec6a67bd-fcc4-4eea-a9ca-745ffd38e1fc)|
- 🎨 (`:art:`) for suggestions / …
=> [PM-8623] Show family icon for free orgs in filter chips

libs/components/src/badge/badge.directive.ts
[CL-286](https://bitwarden.atlassian.net/browse/CL-286)
This PR updates the `badge` component to use `focus-visible` instead of `focus`, which aligns with how we treat interactive focusable elements in the component library.
Check Storybook Publish action and view the Badge story. …
=> [CL-286] Update badge to use focus-visible instead of focus

apps/browser/src/vault/popup/services/vault-popup-items.service.spec.ts, apps/browser/src/vault/popup/services/vault-popup-items.service.ts, libs/common/spec/observable-tracker.ts
[PM-8379](https://bitwarden.atlassian.net/browse/PM-8379)
Refactor the vault popup item service to reduce redundant emissions and add a `loading$` observable that will be used to show a loading spinner once [CL-285](https://bitwarden.atlassian.net/browse/CL-285) is complete. 
No UI changes yet.
- 📝 (`:memo:`) …
=> [PM-8379] Vault Popup Loading State Preliminary Work

apps/browser/src/vault/popup/services/vault-popup-list-filters.service.spec.ts, apps/browser/src/vault/popup/services/vault-popup-list-filters.service.ts
[PM-8624](https://bitwarden.atlassian.net/browse/PM-8624)
Add logic to check for `PersonalOwnership` policy when determining to show the "Vaults" filter
From Ticket:
- If the user is only in a single org and that org has the “Remove Individual Vault” policy enabled, then the Vault filter should be hidden
- If the user is in multiple orgs and at least one org has the “Remove Individual Vault” policy enabled, then “My Vault” should not be shown
- If the user is an Owner or an Admin, the above two or are not applicable
The [documentation](https://github.com/bitwarden/clients/blob/b169207b74ee593365a82b1b73c6d0241a21928e/libs/common/src/admin-console/abstractions/policy/policy.service.abstraction.ts#L41-L45) around the `policyAppliesToActiveUser$` method infers that the owner/admin check is …
=> [PM-8624] PersonalOwnershipPolicy check in Vault Filters

libs/components/src/badge/badge.directive.ts, libs/components/src/badge/badge.mdx, libs/components/src/badge/badge.stories.ts, libs/components/tailwind.config.base.js
[CL-250](https://bitwarden.atlassian.net/browse/CL-250)
This PR updates the styles of the `badge` component according to the new designs for the extension refresh. This also involved adding some more text color options in the tailwind config. 
Check the Storybook Publish action and the `badge` stories.
- 📝 …
=> [CL-250] Update badge styles for extension refresh

bitwarden_license/bit-cli/src/admin-console/device-approval/device-approval.program.ts
https://bitwarden.atlassian.net/browse/AC-2762
When writing the device approval commands, we used positional parameters for all input values. However, our other commands use a flag for the organization id: `--organizationid`. We got feedback from our integration team that these commands should be consistent, so this PR implements the option flag for the organization id instead of an argument.
A couple of notes on implementation:
1. elsewhere we use `.option` to define options, however commander also provides `.requiredOption` which automatically checks for missing/empty option values and returns an error in that case. That's what I've used here.
2. other commands normalize the casing of option names: [example](https://github.com/bitwarden/clients/blob/main/apps/cli/src/admin-console/comman …
=> [AC-2762] Use --organizationid flag for device-approval commands

apps/web/src/app/vault/components/vault-items/vault-collection-row.component.ts, apps/web/src/app/vault/org-vault/vault-header/vault-header.component.html, apps/web/src/app/vault/org-vault/vault-header/vault-header.component.ts, apps/web/src/app/vault/org-vault/vault.component.ts
[AC-2771](https://bitwarden.atlassian.net/browse/AC-2771) and [AC-2772](https://bitwarden.atlassian.net/browse/AC-2772)
Fix issue with restricted providers introduced in #9585. It mistakenly assumed the `/assigned` ciphers endpoint would return empty if the provider was not a member. Instead, it throws a 404 error and prevents restricted providers from using the AC vault for the organization. This PR adds the removed check to prevent hitting that endpoint only if the provider is restricted and they are not a member.
It also fixes some missing UI elements for restricted providers that are also members.
Filters are present, new dropdown has new "Item", and header search is hidden
Filters are hidden, new collections button only, and header collection search is visible 
- Contributor …
=> [AC-2771] [AC-2772] Provider Restriction Fixes

apps/desktop/src/main.ts
A previous PR (https://github.com/bitwarden/clients/pull/9310) accidentally removed `MainCryptoFunctionService` from `main.ts`. This service was setting up the IPC handler for the argon2 hash, and removing it causes any use of the argon2 function from the renderer process to fail.
This PR adds the service back.  …
=> [PM-8870] Fix argon2 in desktop

apps/browser/src/autofill/services/collect-autofill-content.service.ts, apps/browser/src/autofill/utils/index.ts
https://bitwarden.atlassian.net/browse/PM-8869
A regression was encountered within Safari that breaks cache re-validation of autofill page details. This is due to a performance improvement that was implemented for Firefox which uses the window.requestIdleCallback API.
That API is not available in Safari in any manner, and as a result any calls made in collection of page details breaks. To resolve this, we need to fallback to a setTimeout method when the API is not available, allowing us to mimic in some manner the behavior of requestIdleCallback …
=> [PM-8869] Fix broken autofill cache invalidation features on Safari

libs/common/src/tools/generator/passphrase/passphrase-generator-strategy.ts, libs/tools/generator/core/src/strategies/passphrase-generator-strategy.ts
https://bitwarden.atlassian.net/browse/PM-8857
The uniform distribution produces inclusive random numbers on its tail end, but is being used in an exclusive for loop. This caused the algorithm to occasionally skip appending a number to one of the words in the passphrase.
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical …
=> [PM-8857] fix passphrase missing number

apps/web/src/app/layouts/product-switcher/navigation-switcher/navigation-switcher.stories.ts, apps/web/src/app/layouts/product-switcher/product-switcher.stories.ts
During https://github.com/bitwarden/clients/pull/9587, I added the `SyncService` to the underlying `ProductSwitcherService` but missed adding mocks for it to the corresponding storybook stories. Thus resulting in rendering errors.
|Product Switcher|Navigation Product Switcher|
|-|-|
|![Screen Shot 2024-06-14 at 13 56 46 PM](https://github.com/bitwarden/clients/assets/125900171/95fb5a3a-bde8-47e8-ab5d-f59a1ad47913)|![Screen Shot 2024-06-14 at 13 56 40 PM](https://github.com/bitwarden/clients/assets/125900171/75f7fdad-9aa6-4301-9854-96030d510b0f)| …
=> [Fix] Storybook: product navigation errors

apps/web/src/app/auth/login/login.component.html, libs/auth/src/angular/anon-layout/anon-layout.component.html
Attempt to fix a bug where anon-layout content is getting stretched due the fact that our `body` element has a min-width of 1010px.
This PR makes it so at least the anon-layout content stays centered. I believe we will eventually remove the body min-width 1010px in the future to make it truly responsive.
https://62a88a6de5b807fa98886113-lmtdmuingl.chromatic.com/?path=/story/auth-anon-layout--with-primary-content
https://github.com/bitwarden/clients/assets/102181210/806235ea-81fb-4b51-9bc2-2d170174a954
https://github.com/bitwarden/clients/assets/102181210/a13968f5-0a47-48b4-ab6c-00e8a244516a …
=> Fix AnonLayout width bug

apps/web/src/app/auth/settings/security/change-kdf/change-kdf-confirmation.component.ts
https://bitwarden.atlassian.net/browse/PM-8482
```
```
To make change KDF confirmation component to have a browser validation when master password is empty.
- **change-kdf-confirmation.component.ts:** Added a condition to check whether the master password is empty.
https://github.com/bitwarden/clients/assets/162679756/c5c40713-0359-4290-9051-ed3121189fe1
=> PM-8482 Change KDF Confirmation no longer has browser validation

apps/web/src/app/auth/settings/security/security.component.html
https://bitwarden.atlassian.net/browse/PM-7387
With the Vertical Vault refresh, we lost the check on the presence of a master password on the user's account to show/hide the "Master Password" tab.  This PR adds it back. …
=> [PM-7387] Hide Master Password tab for users without MP

libs/common/src/tools/generator/random.ts, libs/tools/generator/core/src/engine/crypto-service-randomizer.ts
https://bitwarden.atlassian.net/browse/PM-8858
Append only one digit when generating a passphrase with a number in it.
=> [PM-8858] include only 1 digit in passphrase

libs/common/src/auth/services/device-trust.service.implementation.ts, libs/common/src/auth/services/device-trust.service.spec.ts
https://bitwarden.atlassian.net/browse/PM-8865
If a user somehow loses trust on a device, the "Remember device" checkbox would subsequently default to unchecked.  This was due to resetting to "false" after the trust process was completed previously.
This change re-initializes the state to `null` instead, so that the logic on the component can handle defaulting it to the appropriate value.
https://github.com/bitwarden/clients/assets/106564991/60e317be-e6d3-4065-88b8-8807c37511a1
- Communicated to DevOps …
=> [PM-8865] Reset "should trust device" state to null

apps/web/src/app/layouts/product-switcher/navigation-switcher/navigation-switcher.stories.ts
Turns out you can't provide the mock service.. that you're trying to mock. I'm not sure how I missed that on the original fix in https://github.com/bitwarden/clients/pull/9664#issuecomment-2176161583.
Tested both switchers locally in storybook 🚀 
|NavigationProductSwitcher|ProductSwitcher|
|-|-|
|<img width="1233" alt="Screenshot 2024-06-18 at 9 53 51 AM" src="https://github.com/bitwarden/clients/assets/125900171/6d7dc162-e37f-4771-908b-9691c9e0f4c7">|<img width="1222" alt="Screenshot 2024-06-18 at 9 53 59 AM" src="https://github.com/bitwarden/clients/assets/125900171/73934520-e06a-45d0-beee-39a90d3581d0">| …
=> [Storybook] Product Switcher errors

libs/common/src/auth/abstractions/token.service.ts, libs/common/src/auth/models/domain/set-tokens-result.ts, libs/common/src/auth/services/token.service.spec.ts, libs/common/src/auth/services/token.service.ts, libs/common/src/services/api.service.ts
https://bitwarden.atlassian.net/browse/PM-7672
We identified the opportunity for a race condition in the `ApiService` in the manner in which it refreshed the access token and immediately read the value from state (via an observable).  This has the potential for not resolving to the new state value.
Instead, we have changed the methods on the `TokenService` to return the new value from the state update. …
=> Auth/pm 7672/Update token service to return new token from state

apps/web/src/app/admin-console/organizations/members/services/organization-user-reset-password/organization-user-reset-password.service.spec.ts, apps/web/src/app/admin-console/organizations/members/services/organization-user-reset-password/organization-user-reset-password.service.ts, apps/web/src/app/auth/emergency-access/services/emergency-access.service.spec.ts, apps/web/src/app/auth/emergency-access/services/emergency-access.service.ts, apps/web/src/app/auth/key-rotation/user-key-rotation.service.spec.ts, apps/web/src/app/auth/key-rotation/user-key-rotation.service.ts, apps/web/src/app/auth/migrate-encryption/migrate-legacy-encryption.component.ts, apps/web/src/app/auth/settings/change-password.component.ts, libs/auth/src/common/abstractions/index.ts, libs/auth/src/common/abstractions/user-key-rotation-data-provider.abstraction.ts, libs/common/src/platform/abstractions/crypto.service.ts, libs/common/src/platform/services/crypto.service.ts, libs/common/src/tools/send/services/send.service.abstraction.ts, libs/common/src/tools/send/services/send.service.spec.ts, libs/common/src/tools/send/services/send.service.ts, libs/common/src/vault/abstractions/cipher.service.ts, libs/common/src/vault/abstractions/folder/folder.service.abstraction.ts, libs/common/src/vault/services/cipher.service.spec.ts, libs/common/src/vault/services/cipher.service.ts, libs/common/src/vault/services/folder/folder.service.spec.ts, libs/common/src/vault/services/folder/folder.service.ts
Copied from #9498, we unfortunately had key rotation changes that were merged immediately after `rc` was cut. This is a blocker for our release, so I have created a branch off the original work and rebased it on `rc`, without the new key rotation changes.
Everything should be the exact same as #9498, before commit 20b5edca6dfe7a20729b9f782b52805f02777d9a. Which means everything was previously pre-approved (even though I may not be able to prove it 😞).
https://bitwarden.atlassian.net/browse/PM-6789
Fixes legacy user migration by using the legacy key for private key re-encryption.
I took the chance to finish distributing key rotation logic to each domain using an interface.
https://github.com/bitwarden/clients/assets/24985544/48c0d98f-4625-4de5-8f6e-7f634f2568ea …
=> [PM-6789] rc version legacy migration fix

apps/browser/src/vault/popup/components/vault/add-edit.component.html, apps/desktop/src/vault/app/vault/add-edit.component.html, apps/web/src/app/vault/individual-vault/add-edit.component.html, apps/web/src/app/vault/individual-vault/add-edit.component.ts
[PM-7215](https://bitwarden.atlassian.net/browse/PM-7215)
This PR aims to ensure that the remove button doesn't appear when a user with only view access tries to edit an item. …
=> [PM-7215] User with Can View permission can remove passkey or delete URIs from UI, though it isn't saved

apps/web/src/app/tools/send/add-edit.component.html
https://bitwarden.atlassian.net/browse/PM-830
Add attribute aria-expanded to Send add-edit options button on Web so that Voice Over announces if it is expanded or collapsed …
=> [PM-830] Add attribute aria-expanded to Send add-edit options button

apps/web/src/app/vault/individual-vault/vault-filter/services/abstractions/vault-filter.service.ts, apps/web/src/app/vault/individual-vault/vault-filter/services/vault-filter.service.ts, apps/web/src/app/vault/individual-vault/vault.component.ts
[PM-8994](https://bitwarden.atlassian.net/browse/PM-8994)
Log in with a user and navigate to a organization in the individual vault.
Log out from that user
Log into another user
Vault items should load properly
https://github.com/bitwarden/clients/assets/8302660/9d7f0b1a-92f2-483b-9888-d955355f4af9
- 📝 …
=> [PM-8994] Load vault data when coming from another user that was viewing an org

apps/web/src/app/admin-console/organizations/settings/account.component.ts
https://bitwarden.atlassian.net/browse/AC-2166
This PR resolves an error on the organization account settings page where owners of organizations linked to resellers could not update the organization name without receiving the "BillingEmail field is required" error. 
Because the form controls are disabled by default and the billing email control is only enabled in the case the organization is **not** managed, we have to check if the form controls are disabled when building the request and, if they are, use the values from the organization directly.
https://github.com/bitwarden/clients/assets/144709477/9a8e4860-b75a-4b39-ab90-3d4a639d84dd
- …
=> [AC-2166] Resolve billing email error on organization name update

libs/auth/src/angular/input-password/input-password.mdx, libs/auth/src/angular/input-password/input-password.stories.ts
Addresses feedback from design to add another story to show Default vs WithPolicy states, and also adds Storybook docs.
- https://github.com/bitwarden/clients/pull/9752/commits/451ae847f97fe15235bc6a8d517b1ef6ca9695f5 - split up stories (1 default, 1 with policy)
- https://github.com/bitwarden/clients/pull/9752/commits/52bab67981edc696598eb33bf7acc0f1109963b2 - add storybook docs for the `InputPasswordComponent` in general
https://62a88a6de5b807fa98886113-eyxqepkwyx.chromatic.com/?path=/docs/auth-input-password--docs
- CI …
=> [PM-5085] Add additional InputPasswordComponent story and docs

libs/common/src/platform/state/state-definitions.ts
https://bitwarden.atlassian.net/issues/PM-7098
resolves #8507
Translation locale should have been persisted in web in #8122, but was mistakenly left in session.
Unfortunately we cannot migrate this data from session, as it is lost on tab closed. …
=> Translation settings should be persisted on web

bitwarden_license/bit-web/src/app/billing/providers/clients/create-client-dialog.component.html, bitwarden_license/bit-web/src/app/billing/providers/clients/create-client-dialog.component.ts, bitwarden_license/bit-web/src/app/billing/providers/subscription/provider-subscription.component.html
https://bitwarden.atlassian.net/browse/AC-2803
Updates the Provider Portal to dynamically display or hide the UI elements related to a provider's subscription discount based on whether one exists or not. Previously, some of this was hard-coded as we always expected the guaranteed 35% discount.
https://github.com/bitwarden/clients/assets/144709477/55895b34-480d-4000-8326-0fa5e84d44e1 …
=> [AC-2803] Make provider discount dynamic in provider portal for Consolidated Billing

.github/workflows/build-desktop.yml
Fixes missed mac os build runners from #8073. 
Mac runners have progressed above python 3.12, which removed `distutils`. We need to ensure it's installed for node-gyp compilations by installing the setuptools package. …
=> Add setuptools to mac pipeline

apps/web/src/app/tools/send/access.component.ts, apps/web/src/app/tools/send/send.component.ts, libs/tools/send/send-ui/package.json, libs/tools/send/send-ui/src/icons/expired-send.icon.ts, libs/tools/send/send-ui/src/icons/index.ts, libs/tools/send/send-ui/src/icons/no-send.icon.ts, libs/tools/send/send-ui/src/index.ts
https://bitwarden.atlassian.net/browse/PM-9250
Preparing to re-use the existing icons on other clients (namely browser for the extension UI refresh) …
=> [PM-9250] Move send icons to @bitwarden/send-ui

libs/auth/src/angular/input-password/input-password.component.html, libs/auth/src/angular/input-password/input-password.component.ts, libs/auth/src/angular/input-password/input-password.mdx, libs/auth/src/angular/input-password/input-password.stories.ts, libs/auth/src/angular/input-password/password-input-result.ts
Changes the `orgId` input `masterPasswordPolicyOptions` and updates Storybook stories and docs.
https://62a88a6de5b807fa98886113-ffshafpbwp.chromatic.com/?path=/docs/auth-input-password--docs
- 🤔 …
=> [PM-5085] InputPasswordComponent Updates (email verification)

.github/workflows/build-cli.yml, apps/cli/package.json, apps/cli/stores/snap/snapcraft.yaml
https://bitwarden.atlassian.net/browse/AC-2811
Due to recent enhancements to the CLI being backed by the Bitwarden License
Agreement we need to update storefronts so that they point to the correct
licenses and artifacts.
The Snap store update in this work may be problematic and will need to be
monitored on release. The GUI setting indicating the use of a GPL license may
override the newly added configuration setting in snapcraft.yaml that
indicates the project uses a proprietary license. We should monitor the snap
store upon release and manually update the license to "Proprietary" in the
Snap Store website if it doesn't take from the changed configuration file.
This will require admin access to the Bitwarden snap package.
There are two major steps to this: updating the build job to bundle …
=> Update CLI storefronts to use bitwarden licensed artifacts

apps/web/src/app/vault/individual-vault/vault.component.ts, libs/vault/src/components/assign-collections.component.ts
https://bitwarden.atlassian.net/browse/PM-9341
If I filter by “My Vault”, select a couple items, and select “Assign to collections” from the bulk action menu, I get a console error and the modal never appears.
https://github.com/bitwarden/clients/assets/13024008/81634544-67ce-44fd-940c-1a53d6275365
- 📝 …
=> [PM-9341] Cannot assign to collections when filtering by My Vault

apps/web/src/app/vault/components/vault-items/vault-items.component.ts
https://bitwarden.atlassian.net/browse/PM-9370
Assign to collections should show up on the admin console. 
The fix for this was to move the `showBulkMove`(which is only set for individual vault to prevent the `assign to collection` option from showing up in the trash filter) from `bulkAssignToCollectionsAllowed` function to `showAssignToCollections`. `showAssignToCollections` is used by the individual vault to know when to hide or show the menu option. …
=> [PM-9370] Assign to Collections now hidden in Admin Console

apps/browser/src/vault/popup/components/fido2/fido2-cipher-row.component.html, apps/browser/src/vault/popup/components/fido2/fido2-cipher-row.component.ts, libs/common/src/vault/models/view/cipher.view.ts, libs/common/src/vault/models/view/login.view.ts
- **Added username to subtitle**
- **Added subName to cipher**
https://bitwarden.atlassian.net/browse/PM-4878 …
=> PM-4878: Add passkey information to items when signing in

apps/browser/src/vault/popup/components/vault-v2/attachments/cipher-attachments/cipher-attachments.component.html, apps/browser/src/vault/popup/components/vault-v2/attachments/cipher-attachments/cipher-attachments.component.spec.ts
[PM-9378](https://bitwarden.atlassian.net/browse/PM-9378)
Add `testid` for an attachment name and size for automated testing. 
[PM-9378]: https://bitwarden.atlassian.net/browse/PM-9378?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlh …
=> [PM-9378] add testids for attachment name and size

libs/vault/src/components/assign-collections.component.ts
[PM-9414](https://bitwarden.atlassian.net/browse/PM-9414)
Modal should be closed after personal item(s) are successfully assigned to an organization.
https://github.com/bitwarden/clients/assets/13024008/d5467114-3fce-4e79-83b8-2df5cb4b0e29 …
=> [PM-9414] Modal not dismissed when moving items only from personal vault

apps/web/src/app/auth/settings/emergency-access/emergency-access.component.html, apps/web/src/locales/en/messages.json, bitwarden_license/bit-web/src/app/admin-console/providers/manage/people.component.html
User feedback of lost vaults due to thinking that Emergency Access was completed.
https://bitwarden.atlassian.net/browse/PM-9344
Prefer `Needs confirmation` to `Accepted` display status. This emphasizes that action is still required to complete setup. …
=> [PM-9344] Clarify accepted user state

apps/web/src/app/admin-console/organizations/settings/two-factor-setup.component.ts, apps/web/src/app/auth/settings/two-factor-duo.component.ts, apps/web/src/app/auth/settings/two-factor-setup.component.ts
https://bitwarden.atlassian.net/browse/PM-9317
We weren't sending the organization id or the correct two factor type to the dialog when configuring Organization Duo. This fixes that and adds some better handling of the dialog callbacks.
https://github.com/bitwarden/clients/assets/24985544/773d55a1-fee2-4862-8485-1ddcb63a1d1b …
=> [PM-9317] fix duo subscriptions and org vs individual duo setup

apps/browser/src/vault/popup/components/vault-v2/add-edit/add-edit-v2.component.ts
https://bitwarden.atlassian.net/browse/PM-7162
Fixes a missed null check in #9758 that prevents the cipher form from rendering. …
=> [PM-7162] Fix broken getter when original cipher is null

apps/browser/src/_locales/en/messages.json, libs/common/src/platform/services/config/default-config.service.ts, libs/vault/src/cipher-form/cipher-form-container.ts, libs/vault/src/cipher-form/components/card-details-section/card-details-section.component.html, libs/vault/src/cipher-form/components/card-details-section/card-details-section.component.spec.ts, libs/vault/src/cipher-form/components/card-details-section/card-details-section.component.ts, libs/vault/src/cipher-form/components/cipher-form.component.html, libs/vault/src/cipher-form/components/cipher-form.component.ts
Stacked on top of @shane-melton's https://github.com/bitwarden/clients/pull/9758 to integrate with `CipherFormConfigService`
[PM-8525](https://bitwarden.atlassian.net/browse/PM-8525)
Add Card Details section for editing a card cipher
- Slight changes from the current implementation:
- Expiration year is now a numerical input to limit the input to numerical values
- The year input doesn't take up as much vertical space as the month select. I manually applied a height here because the `bitInput` seems to override all classes applied to it's host element.
|Edit Card|
|-|
|<video src="https://github.com/bitwarden/clients/assets/125900171/f6595f05-5466-4b9f-a84e-dda935741b47" />|
- …
=> [PM-8525] Edit Card

libs/common/src/state-migrations/migrations/66-move-final-desktop-settings.ts
Fixes an issue in migration 66 where it might attempt to save `undefined` to the electron store, which is not supported by the underlying library. …
=> [PM-9440] Fix: handle undefined value in migration 66

apps/desktop/native-messaging-test-runner/src/variables.ts, apps/desktop/src/services/native-message-handler.service.ts, apps/desktop/src/services/native-messaging.service.ts
Since `sha1` is not an encryption algorithm, but a cryptographic hash function - used in the rsa-oaep padding scheme before encrypting using the actual encryption algorithm - RSA - for clarity, this renames the variables referencing `sha1` from `EncryptionAlgorithm` to `HashAlgorithmForAsymmetricEncryption`, making the code slightly easier to follow. …
=> Rename "encryptionAlgorithm" to "hashAlgorithmForEncryption" for clarity

apps/browser/src/background/main.background.ts, apps/desktop/src/app/layout/account-switcher.component.ts, libs/angular/src/auth/components/login.component.ts, libs/angular/src/services/jslib-services.module.ts, libs/auth/src/common/abstractions/login-email.service.ts, libs/auth/src/common/services/login-email/login-email.service.spec.ts, libs/auth/src/common/services/login-email/login-email.service.ts
https://bitwarden.atlassian.net/browse/PM-7972
"Remember email" feature on login page didn't have great integration with account switching. This adds the following functionality.
If adding an account through account switching:
- Don't show the remembered email
- Never clear the remembered email if box isn't checked (original email should persist)
- Overwrite the remembered email if box _is_ checked
https://github.com/bitwarden/clients/assets/24985544/0a1b86fe-546d-4b2d-a4c3-b17d49e94fc0
https://github.com/bitwarden/clients/assets/24985544/7c1a2a8b-f8a1-44d4-bcac-9f124979483f
- …
=> [PM-7972] Account switching integration with "remember email" functionality

libs/components/src/callout/callout.component.html, libs/components/src/callout/callout.component.spec.ts, libs/components/src/callout/callout.component.ts, libs/components/src/callout/callout.mdx, libs/components/src/callout/callout.module.ts
https://bitwarden.atlassian.net/browse/CL-234
Update `bit-callout` component to use new styles.
side quests:
- update docs
- make component standalone
- https://github.com/bitwarden/clients/pull/9925
- brought this into scope so we don't have two different callout styles within the app.
See Storybook for more. …
=> [CL-234] callout style refresh

apps/web/src/locales/en/messages.json, bitwarden_license/bit-web/src/app/admin-console/providers/providers-layout.component.html, bitwarden_license/bit-web/src/app/admin-console/providers/providers-layout.component.ts, bitwarden_license/bit-web/src/app/admin-console/providers/services/provider-client-vault-privacy-banner.service.ts, libs/common/src/enums/feature-flag.enum.ts, libs/common/src/platform/state/state-definitions.ts
https://bitwarden.atlassian.net/browse/AC-2833
In order to communicate upcoming client vault privacy changes to Bitwarden
MSPs we should post a banner notification to the top of the Provider Portal.
https://github.com/bitwarden/clients/assets/15897251/ff26a1e4-a487-43b7-8d83-541a4defb207 …
=> Communicate the upcoming client vault privacy changes to MSPs

apps/browser/src/vault/popup/components/vault-v2/attachments/cipher-attachments/cipher-attachments.component.html
[PM-9593](https://bitwarden.atlassian.net/browse/PM-9593)
For long attachment names, the width of the name was forcing the chose file button to wrap. Adding `white-space: nowrap` to keep minimum width of the button preserved.
|Before|After|
|-|-|
|<img width="383" alt="Screenshot 2024-07-08 at 10 18 00 PM" src="https://github.com/bitwarden/clients/assets/125900171/ca9f5b9f-4882-43e0-a1b0-904d44fe823d">|<img width="383" alt="Screenshot 2024-07-08 at 10 17 16 PM" src="https://github.com/bitwarden/clients/assets/125900171/f536c682-d221-49ab-a3d8-ddcde3ae4e79">| …
=> [PM-9593] Long Attachment Names

apps/web/src/app/billing/shared/update-license-dialog.component.ts, apps/web/src/app/billing/shared/update-license.component.ts
https://bitwarden.atlassian.net/browse/PM-9600
Resolve the validation message that is not been displayed when there is no uploaded file …
=> [PM-9600] [Defect] Update license dialog - Validation text is missing when submitting without file attachment

libs/common/src/vault/models/domain/login.ts, libs/common/src/vault/services/cipher.service.ts
[PM-9619](https://bitwarden.atlassian.net/browse/PM-9619)
Prevent saving empty string `""` login URIs. The cipher service originally saved a `null` value when the URI was an empty string which would then cause the checksum validation step to fail upon decryption.
Also, if an empty string / `null` value has already been saved add a null check to avoid trying to validate a checksum for a null value. We should simply treat the URI as if it does not exist and skip it. The next save of the cipher will clean up the null value due to the above change. …
=> [PM-9619] Fix broken vault upon saving empty URI

apps/web/src/locales/en/messages.json
https://bitwarden.atlassian.net/browse/AC-2855
When the feature flag `AC-1795_updated-subscription-status-section` is enabled, the clients repo uses a new "subscription status" component. If the organization is for a sponsored organization, then the status is simply "Sponsored" which is translated here https://github.com/bitwarden/clients/blob/billing/AC-2855/sponsored-status-not-displaying/apps/web/src/app/billing/organizations/subscription-status.component.ts#L39
That key was missing, so this PR adds it in.
- CI builds …
=> [AC-2855] Added missing i18n key for "sponsored"

libs/angular/src/tools/password-strength/password-strength-v2.component.html, libs/angular/src/tools/password-strength/password-strength-v2.component.spec.ts, libs/angular/src/tools/password-strength/password-strength-v2.component.ts, libs/angular/src/tools/password-strength/password-strength.component.ts, libs/tools/export/vault-export/vault-export-ui/src/components/export.component.html, libs/tools/export/vault-export/vault-export-ui/src/components/export.component.ts
https://bitwarden.atlassian.net/browse/PM-5165
https://bitwarden.atlassian.net/browse/PM-8645
Create a new password-strength component using the ProgressComponent from the Component library.
The existing component was kept to not break visual styles on non-CL-pages. A follow-up to this is to replace all existing usages with the new component.
- 👍 …
=> [PM-5165][PM-8645] Migrate password strength component

apps/browser/src/vault/popup/services/vault-popup-items.service.spec.ts, apps/browser/src/vault/popup/services/vault-popup-items.service.ts
[PM-9599](https://bitwarden.atlassian.net/browse/PM-9599)
Filter out deleted ciphers from the cipher list that is provided to the vault filter service.
❓ Would deleted ciphers ever be needed? My current fix here would eliminate them from the lowest level, they would never be available. 
|Before|After|
|-|-|
|![Screenshot 2024-07-09 at 10 43 47 AM](https://github.com/bitwarden/clients/assets/125900171/1750717c-370b-426e-93e0-1e7258af6355)|![Screenshot 2024-07-09 at 10 43 29 AM](https://github.com/bitwarden/clients/assets/125900171/78737800-23e5-4b43-9f18-ce31f4ab58b4)| …
=> [PM-9599] Filter out deleted ciphers in popup service

apps/web/src/app/vault/components/vault-items/vault-items.component.ts, apps/web/src/app/vault/individual-vault/vault.component.ts, libs/vault/src/components/assign-collections.component.ts
[PM-9601](https://bitwarden.atlassian.net/browse/PM-9601)
[PM-9602](https://bitwarden.atlassian.net/browse/PM-9602)
- `Assign to Collections` menu option should not show up on view-only items when the collection management setting is on
- View-only collections should not show up when assigning collections to an item when the collection management setting is on
https://github.com/bitwarden/clients/assets/13024008/d8c3d773-7772-4f1b-a44c-4409da423ff0
- …
=> [PM-9601] [PM-9602] When collection management setting is turned on view only collections and assign to collections menu option show up

apps/web/src/app/admin-console/organizations/sponsorships/families-for-enterprise-setup.component.ts
https://bitwarden.atlassian.net/browse/AC-2846
This PR resolves a bug where an organization member who is not the owner of the Families organization still sees that organization as an option to redeem the sponsorship against. This PR filters out organizations for which the user is not an owner.
- `apps\web\src\app\admin-console\organizations\sponsorships\families-for-enterprise-setup.component.ts` …
=> [AC-2846] Ensuring User is Owner when redeeming F4E sponsorship

apps/browser/src/vault/popup/components/vault-v2/add-edit/add-edit-v2.component.html, apps/browser/src/vault/popup/components/vault-v2/add-edit/add-edit-v2.component.ts, apps/browser/src/vault/popup/components/vault-v2/attachments/attachments-v2.component.html, apps/browser/src/vault/popup/components/vault-v2/attachments/attachments-v2.component.spec.ts, apps/browser/src/vault/popup/components/vault-v2/attachments/attachments-v2.component.ts
[PM-9455](https://bitwarden.atlassian.net/browse/PM-9455)
The back button within the `PopupHeader` component strictly calls `location.back()`. An issue arises when the extension is forced into a popout window, in this case by the attachments component. When this occurs there is no browser history and thus the user is stuck.
Here I used the `backAction` input to conditionally check if there is a history to navigate to, otherwise navigate to the most probable route the user was on before.
❓ The way this is set up makes it so the logic has to implement this check all the way back to the `/vault` path. This makes sense but also feels kind of manual. Is there another way to hook back into the existing history? Otherwise it might just be the circumstance we're in. …
=> [PM-9455] Back button fallback

apps/browser/src/background/runtime.background.ts, apps/browser/src/popup/services/services.module.ts, apps/browser/src/services/vault-timeout/foreground-vault-timeout.service.ts
https://bitwarden.atlassian.net/browse/PM-6188
> [!NOTE]  
> Follow-up to https://github.com/bitwarden/clients/pull/10050
This PR removes the shared reference to the background vaulttimeout service. While the vaulttimeout service only gets inited in the background serviceworker, we do need to watch for manual calls to logout and lock. These need to be passed through via ipc to the background instance, so this PR also introduces a foregroundvaulttimeoutservice that routes the calls to the background serviceworker via IPC.
- …
=> [PM-6188] Remove getbgservice call for vaulttimeoutservice

apps/browser/src/vault/popup/components/vault-v2/view-v2/view-v2.component.ts
[PM-9632](https://bitwarden.atlassian.net/browse/PM-9632)
created a method `checkForPasswordReprompt` for the password reprompt logic. Will be used in both the edit and delete methods. 
https://github.com/user-attachments/assets/acb08627-e66d-48d9-9ab9-144b5d0c7abb …
=> [PM9632] added MP reprompt check to edit button in view-v2

libs/vault/src/cipher-form/components/cipher-form.component.ts
[PM-8526](https://bitwarden.atlassian.net/browse/PM-8526)
Fix saving new Note cipher types. The `SecureNoteView` does not automatically set the `type` property (even though there is only 1 option?) so the `CipherFormComponent` now does so explicitly when creating new Note items. …
=> [PM-8526] Set secureNote type when creating a new note

libs/components/src/dialog/dialog.service.stories.ts, libs/components/src/dialog/dialog/dialog.component.html, libs/components/src/dialog/dialog/dialog.component.ts, libs/components/src/dialog/dialog/dialog.mdx, libs/components/src/dialog/dialog/dialog.stories.ts, libs/components/src/dialog/dialogs.mdx, libs/components/src/dialog/simple-dialog/simple-configurable-dialog/simple-configurable-dialog.service.stories.ts, libs/components/src/dialog/simple-dialog/simple-dialog.component.html, libs/components/src/dialog/simple-dialog/simple-dialog.mdx, libs/components/src/dialog/simple-dialog/simple-dialog.service.stories.ts, libs/components/src/dialog/simple-dialog/simple-dialog.stories.ts, libs/components/src/typography/typography.directive.ts
https://bitwarden.atlassian.net/browse/CL-251
- Update dialog and simple dialog styles for extension refresh
- add `background` input to dialog to change the bg color
- Add import block to docs. 
- Fix simple dialog text overflow bug
See Storybook for more. …
=> [CL-239][CL-251][CL-342] dialog style refresh

apps/web/src/app/auth/settings/account/profile.component.html
https://bitwarden.atlassian.net/browse/PM-9707
We're in the process of removing bootstrap from our web vault. As part of this I've started to audit the areas that breaks in #8071.
The Avatar customize button appeared below the avatar after removing Boostrap. This resolves it by adding flex, it also has the added benefit of aligning the button vertically as it's currently slightly misaligned.
|Before|After|
|--|--|
| ![image](https://github.com/user-attachments/assets/5cae2de8-3a62-44c6-b4ef-54a2667f4a36) | ![image](https://github.com/user-attachments/assets/abc72d55-3cd3-4bca-b384-e70bbac8761a) | …
=> [PM-9707] [Boostrap] Fix avatar and customize placement

apps/browser/src/_locales/en/messages.json, apps/browser/src/auth/popup/account-switching/account.component.html, apps/browser/src/auth/popup/account-switching/services/account-switcher.service.ts
https://github.com/bitwarden/clients/issues/10051
As the PR title states, it will translate the omitted string in the account switch dialog
=> [PM-9643] Add translation for Add account option in account switcher

apps/browser/src/background/main.background.ts, apps/cli/src/service-container.ts, libs/angular/src/services/jslib-services.module.ts, libs/common/src/platform/services/config/config.service.spec.ts, libs/common/src/platform/services/config/default-config.service.ts
Change ConfigService to only go and retrieve user config when the user has unlocked. This keeps the application from saving user config that was retrieved without a access token.  …
=> [PM-8979] Check that user is authed before getting user config

apps/browser/src/_locales/en/messages.json, apps/browser/src/auth/popup/two-factor-auth.component.ts, apps/desktop/src/auth/two-factor-auth.component.ts, apps/desktop/src/locales/en/messages.json, apps/web/src/app/auth/two-factor-auth.component.ts, apps/web/src/locales/en/messages.json, libs/angular/src/auth/components/two-factor-auth/two-factor-auth-webauthn.component.html, libs/angular/src/auth/components/two-factor-auth/two-factor-auth-webauthn.component.ts, libs/angular/src/auth/components/two-factor-auth/two-factor-auth.component.html, libs/angular/src/auth/components/two-factor-auth/two-factor-auth.component.ts
https://bitwarden.atlassian.net/browse/PM-7084
https://bitwarden.atlassian.net/browse/PM-9026
> [!IMPORTANT]  
> **STACKED PR:** This set of changes is split into a set of smaller PR's that can be reviewed independently, in parallel. Merging still should be done in order once all PR's are reviewed. Merging can be done incrementally as the feature is feature flagged.
#9767 - Shared two-fa options component
#9768 - Shared two-fa orchestrator component & totp authenticator component
#9769 - Shared two-fa yubikey component
#9770 - Shared two-fa email component
#9771 - Shared two-fa webauthn component
#9772 - Shared two-fa duo component
- …
=> [PM-7084] 5/6: Introduce shared webauthn two-factor component

libs/angular/src/auth/components/change-password.component.ts
https://bitwarden.atlassian.net/browse/PM-6838
Ensures that when changing the master password, the minimum length message under the master password input matches the minimum length required by an enforced MP length policy, if present.
If no policy is present, the message will default to 12.
| Old | New |
| ------------- | ------------- |
| ![Screenshot 2024-07-12 at 12 35 30 PM](https://github.com/user-attachments/assets/70279491-1620-47da-aa99-14cd426ae383) | ![Screenshot 2024-07-12 at 12 23 38 PM](https://github.com/user-attachments/assets/597ea15d-894c-49e9-a72f-19b299d46571)  | …
=> [PM-6838] Fix wrong minlength message on ChangePasswordComponent

libs/common/src/vault/services/cipher.service.spec.ts, libs/common/src/vault/services/cipher.service.ts
https://bitwarden.atlassian.net/browse/PM-9868
https://github.com/bitwarden/server/pull/4522
Fixes key rotation for org members. It was broken since the user account key rotation tried to rotate org ciphers using the user-key.
- ❓ …
=> [PM-9868] Fix key rotation being broken due to org ciphers being included

apps/web/src/app/admin-console/organizations/members/members.component.html
https://bitwarden.atlassian.net/browse/AC-1463
The people screen has a button that can be clicked to open a modal for inviting new users to an organization. This modal depends on data from the people list for conditional logic, like whether or not the seat count cor the organization has been reached. If the modal is opened before the people list loads these conditions can not process correctly, causing bugs.
This commit disabled the button until the people list loads to prevent this kind of behavior.
https://github.com/user-attachments/assets/3d39a4f1-f144-47e3-980d-b50d82ee9c05 …
=> Disable a button during initial page load

apps/desktop/src/scss/box.scss
https://bitwarden.atlassian.net/browse/PM-9874
Fix incorrectly sized two-step login icon size by adjusting the desktop css. …
=> [PM-9874] Fix icon size of two-step login options

apps/cli/src/admin-console/models/response/organization-collection.response.ts, apps/cli/src/commands/edit.command.ts, apps/cli/src/commands/get.command.ts, apps/cli/src/vault/create.command.ts
https://bitwarden.atlassian.net/browse/AC-2870
Collection management permissions can be set for a group or a specific user. Currently the CLI only outputs group associations when it displays collection configuration information. This can cause bugs when piping commands together.
This commit ensures that `user` associations also get output. In all cases this data was already available and just needed to be added to a response model.
- Updated any …
=> Output user-specific associations for collections in the CLI

libs/vault/src/cipher-form/components/custom-fields/add-edit-custom-field-dialog/add-edit-custom-field-dialog.component.spec.ts, libs/vault/src/cipher-form/components/custom-fields/add-edit-custom-field-dialog/add-edit-custom-field-dialog.component.ts, libs/vault/src/cipher-form/components/custom-fields/custom-fields.component.ts
[PM-9910](https://bitwarden.atlassian.net/browse/PM-9910)
When adding/editing a note cipher, "Linked" should not be an option for custom fields.
|Adding|Editing|
|-|-|
|<video src="https://github.com/user-attachments/assets/fdd8a119-deba-40d4-bd43-38edd5b8e1fe" />|<video src="https://github.com/user-attachments/assets/6b035483-c01e-439d-8d06-f19812441ccf" />|
- 🌱 …
=> [PM-9910] Filter out linked option for notes

libs/vault/src/cipher-form/cipher-form.stories.ts
Use a static Date in the CipherForm storybook. #10081 added `new Date()` which causes the story to be slightly different every time it runs. …
=> Use static date for storybook data

apps/web/src/app/vault/individual-vault/folder-add-edit.component.ts, apps/web/src/app/vault/individual-vault/vault.component.ts, libs/common/src/vault/services/folder/folder.service.ts
[PM-8050](https://bitwarden.atlassian.net/browse/PM-8050)
Deleting a folder should not clear all folders on the client. There seems to be a malfunction with `SyncService.syncDeleteFolder`, which tries to sync the web client after a folder has been deleted on the web client. Previously, we returned when `folders[id] == null`, which clears the folder state. …
=> [PM-8050] Deleting one folder deletes all other folders

libs/vault/src/cipher-view/custom-fields/custom-fields-v2.component.html, libs/vault/src/cipher-view/custom-fields/custom-fields-v2.component.ts
[PM-9629 Checkbox Should Reflect Value](https://bitwarden.atlassian.net/browse/PM-9629)
[PM-9630 Formatting of Custom Fields Spacing](https://bitwarden.atlassian.net/browse/PM-9630)
Updated elements and classes in `custom-fields-v2` to use CL components
Updated checkbox to reflect the proper value of the field
Disabled checkbox …
=> [PM-9629] Custom Fields V2 View Section Defects

libs/vault/src/cipher-form/components/custom-fields/custom-fields.component.html
[PM-9890](https://bitwarden.atlassian.net/browse/PM-9890)
Add testids for automation testing:
> on the <bit-card> that holds the list of custom fields: data-testid="custom-fields"
> on the <div> that holds each custom field entry: data-testid="{fieldLabel}-entry" where {fieldLabel} is the field label for that entry.
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for …
=> [PM-9890] Custom Fields - testids for automation testing

apps/browser/src/background/main.background.ts, apps/browser/src/platform/services/abstractions/abstract-chrome-storage-api.service.ts, apps/browser/src/platform/services/browser-local-storage.service.spec.ts, apps/browser/src/platform/services/browser-local-storage.service.ts, apps/browser/test.setup.ts, apps/browser/tsconfig.json, libs/common/custom-matchers.d.ts, libs/common/spec/matchers/index.ts, libs/common/spec/matchers/promise-fulfilled.spec.ts, libs/common/spec/matchers/promise-fulfilled.ts, libs/common/test.setup.ts
https://bitwarden.atlassian.net/browse/PM-8285
This closes a narrow race condition resulting from storage operations during a reseed event. …
=> [PM-8847] Delay browser local storage operations during reseed

bitwarden_license/bit-web/src/app/tools/reports/member-access-report/member-access-report.component.html
https://bitwarden.atlassian.net/browse/AC-2902
String were hardcoded instead of using the localization service. Fixed it
It doesn't require QA as this feature is under feature flag and has not been tested yet …
=> [AC-2902] Fix hardcoded strings on MemberAccessReportComponent

.github/CODEOWNERS
https://bitwarden.slack.com/archives/C04MF5S8XKN/p1721252901769749?thread_ts=1721034173.235149&cid=C04MF5S8XKN
https://bitwarden.atlassian.net/browse/PM-8836
Move native messaging ipc to auth for now, DDG is still under autofill ownership. This will be returned/(given to platform) once there is a more clear separation between biometrics and ipc.
- 👍 …
=> [PM-8836] Adust CODEOWNERS to move biometrics native IPC to auth ownership

libs/vault/src/cipher-form/components/custom-fields/custom-fields.component.spec.ts, libs/vault/src/cipher-form/components/custom-fields/custom-fields.component.ts
[PM-9892](https://bitwarden.atlassian.net/browse/PM-9892)
Originally I was using the `originalCipherView` for retrieving the linked options for the custom field. This doesn't work when a user adds a cipher because the `originalCipherView` is null. 
Swapping to using the `linkedFieldOptions` from the view prototypes instead. 
|Adding Login|Adding Card|Adding Identity|
|-|-|-|
|<video src="https://github.com/user-attachments/assets/bd65da05-a0e8-4be1-a81a-217605566d17" />|<video src="https://github.com/user-attachments/assets/6f2dc4d7-d52b-4059-99a8-7b7df59a95ac" />|<video src="https://github.com/user-attachments/assets/772359cf-d080-4fe5-898b-c95c29e20c68" />|
- ❓ …
=> [PM-9892] Linked Types for adding a cipher

apps/browser/src/_locales/en/messages.json, libs/vault/src/cipher-form/components/custom-fields/add-edit-custom-field-dialog/add-edit-custom-field-dialog.component.ts
[PM-9912](https://bitwarden.atlassian.net/browse/PM-9912)
Swap custom field labels for boolean field from "Boolean" to "Checked"
[PM-9912]: https://bitwarden.atlassian.net/browse/PM-9912?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MD …
=> [PM-9912] "Boolean" to "Checked" for custom label

libs/vault/src/cipher-form/components/custom-fields/custom-fields.component.ts
[PM-9922](https://bitwarden.atlassian.net/browse/PM-9922)
Fix focus management related bugs:
- Focus isn't directed into the input when first adding a custom field
- Issue; This was a timing issue, on the first add of a custom item, `this.customFieldRows.changes` was emitting before `this.focusOnNewInput$` was emitting. Thus the subscribe was never called. 
- Fix: I switched to using `zip` so the subscribe will be called when both `this.customFieldRows.changes` & `this.focusOnNewInput$` emit in pairs which is more inlined with my intention.
- Checkbox fields were not being focused
- Issue: I missed that the checkbox implementation is wrapped in a `label` rather than associating the checkbox & label by `id`. When querying for the label, `null` would be returned and the method would error. …
=> [PM-9922] Custom Fields - Focus Management

libs/vault/src/cipher-view/item-history/item-history-v2.component.html, libs/vault/src/cipher-view/item-history/item-history-v2.component.ts
[PM-9634 Hide PW Updated If Not Login Type](https://bitwarden.atlassian.net/browse/PM-9634)
[PM-9637 Update PW History Styling](https://bitwarden.atlassian.net/browse/PM-9637)
`Password Updated` line will not show if there is no history or the item is not a login item
`Password History` link updated with body2 typography and is pushed down
- 👍 …
=> [PM-9634] update item history browser v2

apps/browser/src/_locales/en/messages.json, libs/vault/src/cipher-form/components/custom-fields/add-edit-custom-field-dialog/add-edit-custom-field-dialog.component.ts
[PM-9912](https://bitwarden.atlassian.net/browse/PM-9912)
The entire time working through https://github.com/bitwarden/clients/pull/10168, I thought it was "Checked", I was wrong. It's supposed to be `Checkbox`. Sometimes it's the simple changes that get ya. 
|"Checkbox"|
|-|
|![Screenshot 2024-07-22 at 12 05 56 PM](https://github.com/user-attachments/assets/98d06742-d449-4b0a-8bf7-0e23dbfc5fc9)|
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant …
=> [PM-9912] Checked to Checkbox

apps/web/src/app/admin-console/organizations/guards/is-enterprise-org.guard.ts, apps/web/src/app/billing/organizations/change-plan.component.html, apps/web/src/app/billing/organizations/change-plan.component.ts, apps/web/src/app/billing/organizations/organization-plans.component.ts, apps/web/src/app/billing/organizations/organization-subscription-cloud.component.html, apps/web/src/app/billing/organizations/organization-subscription-cloud.component.ts
https://bitwarden.atlassian.net/browse/AC-2505
The objective is to pre select the enterprise option when clicking upgrade from the member access report dialog on the reports page.
To achieve this was added an option through queryParams that will pre select the desired upgrade option on the subscription page
- **is-enterprise-org.guard.ts:** Passing a new queryParam to the subscription page that has `ProductTierType.Enterprise` as value
- **organization-subscription-cloud.component.ts:** Checks if the `productTierType` queryParam exists, if it exists tries to convert into the `ProductTierType` and set it to be passed as an input bind
- **organization-plans.component.ts:** Updates the `productTier` option from the component with the `preSelectedProductTier` that was sent as an input, in …
=> [PM-2505] Pre-Select enterprise on upgrade from MemberAccessReport dialog

libs/common/src/platform/state/implementations/default-single-user-state.spec.ts, libs/common/src/platform/state/implementations/state-base.ts, libs/common/src/platform/state/key-definition.spec.ts, libs/common/src/platform/state/key-definition.ts, libs/common/src/platform/state/user-key-definition.ts
https://bitwarden.atlassian.net/browse/PM-9980
Special case `0` to mean there should be no cache of the value kept at all, this mean you can configure your state definition to go to the storage service on every retrieval when you subscribe to it. …
=> [PM-9980] Special Case `0` to mean no caching at all

libs/common/src/vault/linked-field-option.decorator.ts, libs/common/src/vault/models/view/card.view.ts, libs/common/src/vault/models/view/identity.view.ts, libs/common/src/vault/models/view/login.view.ts, libs/vault/src/cipher-form/components/custom-fields/custom-fields.component.ts
~~Stacked on top of https://github.com/bitwarden/clients/pull/10167~~
[PM-9926](https://bitwarden.atlassian.net/browse/PM-9926)
Display linked fields in the custom field select in the same order as they are in the UI. 
- I ended up extending the `linkedFieldOption` decorator to allow for an "attributes" object to be passed in. 
- This was a little deeper than I was expecting to go, but this felt like the most explicit way to make the sorting explicit & extensible for new fields. Happy to explore other options though!
- Reorder `LoginLinkedId`, `CardLinkedId`, `IdentityLinkedId` enums to match the UI order. 
- An `enum` isn't technically ordered but getting the keys of it will produce the expected order. 
- I went against this because it felt unintuitive and "magical". How would someone …
=> [PM-9926] Linked Fields order

libs/vault/src/cipher-view/custom-fields/custom-fields-v2.component.html
[PM-9629](https://bitwarden.atlassian.net/browse/PM-9629)
field value comes in as a string. updated checkbox in custom fields to account for that.  …
=> [PM-9629] custom fields checkbox

libs/vault/src/cipher-form/components/custom-fields/add-edit-custom-field-dialog/add-edit-custom-field-dialog.component.html
None - Noticed myself
Swap "Edit" for "Save" on the edit custom field dialog
=> Swap "edit" for "save" in edit dialog

libs/common/spec/matchers/promise-fulfilled.spec.ts
Loosen timings to avoid false failures.
Biggest ones here are the not resolved tests that can be evaluated at any time, so they just never resolve/reject. …
=> Fix Flaky Promise resolution matcher tests

libs/components/src/form-control/label.directive.ts, libs/components/src/form-field/form-field-control.ts, libs/components/src/form-field/form-field.component.html, libs/components/src/form-field/form-field.component.ts, libs/components/src/form-field/form-field.stories.ts, libs/components/src/input/input.directive.ts
[](https://bitwarden.atlassian.net/browse/CL-244)
Add new styles for `bit-form-field` when the contained input is marked as `readonly`.
See Chromatic Storybook --> Form --> Field --> Readonly
- 🤔 …
=> [CL-244] readonly fields

apps/web/src/app/billing/organizations/organization-subscription-cloud.component.html, apps/web/src/app/billing/organizations/organization-subscription-cloud.component.ts
https://bitwarden.atlassian.net/browse/AC-2919
When the user of a reseller's client organization loads the Subscription page, the provider is not going to be stored in state because it's not returned from the sync response. We need to null check the provider in the call to determine whether or not the organization is a consolidated billing client. 
https://github.com/user-attachments/assets/34ae3fcd-ae9b-4dae-b818-f3f7e1fd57f5 …
=> [AC-2919] Resolve subscription page error for reseller managed organization users when CB is on

apps/browser/src/background/main.background.ts, apps/cli/src/service-container.ts, libs/angular/src/services/jslib-services.module.ts, libs/auth/src/common/login-strategies/sso-login.strategy.spec.ts, libs/auth/src/common/login-strategies/sso-login.strategy.ts, libs/common/src/auth/abstractions/device-trust.service.abstraction.ts, libs/common/src/auth/abstractions/devices-api.service.abstraction.ts, libs/common/src/auth/services/device-trust.service.implementation.ts, libs/common/src/auth/services/device-trust.service.spec.ts, libs/common/src/auth/services/devices-api.service.implementation.ts, libs/common/src/enums/feature-flag.enum.ts
https://bitwarden.atlassian.net/browse/PM-10059
bitwarden/server#4554
Notifies server when the client has a device key, but doesn't receive decryption keys from the server. …
=> [PM-10059] alert server if device trust is lost

libs/vault/src/cipher-view/cipher-view.component.html, libs/vault/src/cipher-view/custom-fields/custom-fields-v2.component.html, libs/vault/src/cipher-view/custom-fields/custom-fields-v2.component.ts
[PM-9630 remove copy icon](https://bitwarden.atlassian.net/browse/PM-9630)
[PM-10018 linked fields in Card and Identity](https://bitwarden.atlassian.net/browse/PM-10018)
Removed the copy icon from Linked Fields in custom fields
Update Linked Fields to utilize the new `linkedfieldoptions`. Showing the proper text for Card and Identity fields
- 👍 …
=> [PM-9630] Custom Field Browser V2 updates

libs/common/src/vault/models/domain/collection.ts, libs/common/src/vault/services/collection.service.ts
https://bitwarden.atlassian.net/browse/PM-4311
This will allow external id from collections to be correctly imported into the vault. We already export it but it is not imported.
- **domain/collection.ts:** Removed "externalId" from not include list
- **collection.service.ts:** Setting the externalId data on the encrypt method …
=> [PM-4311] Populate the collection's external id when importing

apps/browser/src/_locales/en/messages.json, apps/browser/src/autofill/popup/settings/autofill-v1.component.html, apps/browser/src/autofill/popup/settings/autofill-v1.component.ts, apps/browser/src/autofill/popup/settings/autofill.component.html, apps/browser/src/autofill/popup/settings/autofill.component.ts, apps/browser/src/popup/app-routing.module.ts, apps/browser/src/popup/app.module.ts, libs/common/src/autofill/constants/index.ts, libs/common/src/autofill/types/index.ts
PM-8338
Create a new Autofill Settings and Excluded Domains components to match Design specs.
- Like other extension refresh work, the new components are behind the `extension-refresh` feature flag.
- Existing components have been renamed to use a "v1" naming scheme for easier deprecation in the future
- There are some expected/approved differences from design due to presumptive design system work on the horizon
- Replacements of hyphenated "auto-fill" to "autofill" in the existing view are expected/approved by Design
Note: some of the screenshots below were taken before the Autofill on page load warning text update, which looks like this: 
**UX Recording**
https://github.com/user-attachments/assets/2494df29-8889-40e2-9ec4-d2747ef28b7c
**Firefox**
**Unknown/unsupported client**
- …
=> [PM-8338] New Autofill Settings Components

libs/components/src/toggle-group/toggle.component.ts
[CL-337](https://bitwarden.atlassian.net/browse/CL-337)
The toggle group was displaying incorrectly when used on a page with another parent component utilizing `tw-group`. If not namespaced (like `tw-group/namespace-here`), the groups will interact and cause styling issues. This PR fixes this issue for the toggle group by giving namespaces to both `tw-group` and `tw-peer`.
This can be checked in the Storybook Publish > Kitchen Sink stories, which use toggle group. Additionally, in the web app:
Before:
After:
- CI builds …
=> [CL-337] Fix toggle group visual bug from tw-group collisions

apps/browser/src/_locales/en/messages.json, apps/web/src/locales/en/messages.json, libs/vault/src/components/assign-collections.component.html
[PM-9951](https://bitwarden.atlassian.net/browse/PM-9951)
Refine copy of the assignment collection copy/design:
- Make singular and plural versions of the bulk assignment description so `item` has the correct plurality. 
- Add back the bullet for the assignment warning message
|Extension|Web - plural|Web - singular|
|-|-|-|
|<img width="382" alt="Screenshot 2024-07-24 at 10 31 23 AM" src="https://github.com/user-attachments/assets/185f0df9-77ca-4f66-a78b-294a353b26dd">|<img width="1731" alt="Screenshot 2024-07-24 at 10 31 45 AM" src="https://github.com/user-attachments/assets/1bd52740-b7d2-4e46-a8b0-aab35366b8ab">|<img width="1730" alt="Screenshot 2024-07-24 at 10 36 21 AM" src="https://github.com/user-attachments/assets/e75b751d-9163-46a6-87ca-94b14b3d07ec">| …
=> [PM-9951] Assignment Collections copy (part 2)

libs/common/src/vault/models/domain/collection.spec.ts, libs/common/src/vault/models/domain/collection.ts, libs/common/src/vault/services/collection.service.ts
https://bitwarden.atlassian.net/browse/PM-4311
ExternalId on the Collection is set to an encrypted string. Fixing the test case.  …
=> [PM-4311] - Collections test fix

libs/vault/src/cipher-form/components/identity/identity.component.html, libs/vault/src/cipher-form/components/identity/identity.component.ts
[PM-9924](https://bitwarden.atlassian.net/browse/PM-9924)
Missing the middle name field in the Identity Edit page …
=> [PM-9924] add middle name field

libs/vault/src/cipher-form/cipher-form-container.ts, libs/vault/src/cipher-form/components/additional-options/additional-options-section.component.spec.ts, libs/vault/src/cipher-form/components/additional-options/additional-options-section.component.ts, libs/vault/src/cipher-form/components/card-details-section/card-details-section.component.spec.ts, libs/vault/src/cipher-form/components/card-details-section/card-details-section.component.ts, libs/vault/src/cipher-form/components/cipher-form.component.ts, libs/vault/src/cipher-form/components/custom-fields/custom-fields.component.spec.ts, libs/vault/src/cipher-form/components/custom-fields/custom-fields.component.ts, libs/vault/src/cipher-form/components/identity/identity.component.ts, libs/vault/src/cipher-form/components/item-details/item-details-section.component.spec.ts, libs/vault/src/cipher-form/components/item-details/item-details-section.component.ts, libs/vault/src/cipher-form/components/login-details-section/login-details-section.component.spec.ts, libs/vault/src/cipher-form/components/login-details-section/login-details-section.component.ts
[PM-9190](https://bitwarden.atlassian.net/browse/PM-9190)
While working on the AutoFill options section I ran up against the problem of modifying deeply nested fields of the `CipherView` (specifically the `LoginView.uris`). The `patchCipher` method did not support updating such a nested field in isolation and so the auto fill options form would overwrite other changes made by the login details section. 
To overcome this, I refactored the `patchCipher` method to accept an `updateFn` that is provided the current instance of the modified cipher so that the child form sections can more precisely modify the properties relevant to them. While fairly trivial to refactor in each child form component, it did require a bit more verbosity to properly test in the spec files.  …
=> [PM-9190] Refactor CipherForm patchCipher method

apps/web/src/app/auth/settings/two-factor-authenticator.component.ts, libs/common/src/abstractions/api.service.ts, libs/common/src/auth/models/request/disable-two-factor-authenticator.request.ts, libs/common/src/auth/models/request/update-two-factor-authenticator.request.ts, libs/common/src/auth/models/response/two-factor-authenticator.response.ts, libs/common/src/enums/feature-flag.enum.ts, libs/common/src/services/api.service.ts
[PM-9925](https://bitwarden.atlassian.net/browse/PM-9925)
[Server PR](url)
These changes are behind feature flag: `authenticator-2fa-token`
Currently to have a compliant TOTP implementation we do not allow users to re-use any TOTP. We support two TOTPs: Email and Authenticator. Both of these are used for two factor authentication. Email however is used for Bitwarden implementations that use Trusted Device Encryption as a means to verify a user.
There are some actions in Bitwarden that require User Verification. One of them being setting up Two Factor Authentication. Since any TOTP is invalidated after they are used this means the current flow for setting up Two Factor needed to be adjusted. We now only consume the OTP when a user is writing two factor data. We do not require it when …
=> [PM-9925] Tokenable for User Verification on Two Factor Authenticator settings

apps/browser/src/vault/popup/components/vault/vault-v2.component.html, apps/browser/src/vault/popup/components/vault/vault-v2.component.ts
[PM-8379](https://bitwarden.atlassian.net/browse/PM-8379)
Bind the `VaultPopupItemService.loading$` observable to the new `[loading]` input on `<popup-page>`.
https://github.com/user-attachments/assets/82ba18c5-aaf8-459e-a737-bcf39c6f6f2b …
=> [PM-8379] Implement loading state in VaultV2

apps/browser/src/vault/popup/components/fido2/fido2.component.ts, apps/browser/src/vault/popup/components/vault-v2/add-edit/add-edit-v2.component.html, apps/browser/src/vault/popup/components/vault-v2/add-edit/add-edit-v2.component.ts, apps/browser/src/vault/popup/components/vault/add-edit.component.ts, apps/browser/src/vault/popup/utils/fido2-popout-session-data.ts, libs/vault/src/cipher-form/abstractions/cipher-form-config.service.ts, libs/vault/src/cipher-form/components/cipher-form.component.ts, libs/vault/src/cipher-form/components/identity/identity.component.ts, libs/vault/src/cipher-form/components/item-details/item-details-section.component.ts, libs/vault/src/cipher-form/components/login-details-section/login-details-section.component.html, libs/vault/src/cipher-form/components/login-details-section/login-details-section.component.spec.ts, libs/vault/src/cipher-form/components/login-details-section/login-details-section.component.ts, libs/vault/src/cipher-form/services/default-cipher-form-config.service.ts
[PM-9959](https://bitwarden.atlassian.net/browse/PM-9959)
[PM-9962](https://bitwarden.atlassian.net/browse/PM-9962)
Add support for Passkey creation with the new add-edit-v2 component.
> [!NOTE]  
> The automatic password generation shown below will be removed in [PM-10100](https://bitwarden.atlassian.net/browse/PM-10100).
https://github.com/user-attachments/assets/d5bdaa14-cefc-4585-83e8-4e7a35d6dec4 …
=> [PM-9959] [PM-9962] Browser Refresh - Passkey Fixes

libs/vault/src/cipher-view/item-details/item-details-v2.component.html, libs/vault/src/cipher-view/item-details/item-details-v2.component.ts
[PM-10447](https://bitwarden.atlassian.net/browse/PM-10047)
Updated the name input in item details to use the bit-form-field. This will grab the latest style changes. The screenshot below is with our current styles. Will look updated when brought into feature branch `ps/extension-refresh` …
=> [PM-10047] update name input in item details

libs/vault/src/cipher-form/components/additional-options/additional-options-section.component.html, libs/vault/src/cipher-form/components/card-details-section/card-details-section.component.html, libs/vault/src/cipher-form/components/custom-fields/custom-fields.component.html, libs/vault/src/cipher-form/components/identity/identity.component.html, libs/vault/src/cipher-form/components/item-details/item-details-section.component.html, libs/vault/src/cipher-form/components/login-details-section/login-details-section.component.html
[PM-9825](https://bitwarden.atlassian.net/browse/PM-9825)
The bottom margin on the section should match the left/right margin.
| Before  | After  |
|---|---|
|<img width="376" alt="Screenshot 2024-07-29 at 10 03 03 AM" src="https://github.com/user-attachments/assets/0fb68a2c-27f2-496b-85c3-9aed04b5b388">|<img width="376" alt="Screenshot 2024-07-29 at 10 00 21 AM" src="https://github.com/user-attachments/assets/c7ac774d-b2ca-4ead-ac04-1c3be1635924">|
|<img width="374" alt="Screenshot 2024-07-29 at 10 03 27 AM" src="https://github.com/user-attachments/assets/5d5533c8-4842-47d5-a32c-2eed50e0bde3">|<img width="377" alt="Screenshot 2024-07-29 at 9 59 53 AM" src="https://github.com/user-attachments/assets/734e7d8a-c7fe-4939-9bdd-cf3b896b3c78">|
- All formatters …
=> [PM-9825] Remove margin from last field in section

libs/vault/src/cipher-view/card-details/card-details-view.component.html
[PM-7901](https://bitwarden.atlassian.net/browse/PM-7901)
Missed adding the `disableMargin` to one of the fields in card details section
https://github.com/user-attachments/assets/46af0d10-489a-45e8-b8af-3951e79eba72 …
=> [PM-7901] update disableMargin in card details view

libs/auth/src/angular/input-password/input-password.component.html, libs/auth/src/angular/input-password/input-password.component.ts, libs/auth/src/angular/input-password/input-password.stories.ts
Per discussion with design, this PR adds an input to the `InputPasswordComponent` to control whether the button is inline or block (spanning the full width of the form). The default is block.
https://62a88a6de5b807fa98886113-jcwogneslh.chromatic.com/?path=/story/auth-input-password--inline-button
| Full Width | Inline |
| ----- | ----- |
| <img width="494" alt="Screenshot 2024-07-19 at 5 12 07 PM" src="https://github.com/user-attachments/assets/79f9d2fc-fb2c-495d-82eb-2b92d7b4877e"> | <img width="495" alt="Screenshot 2024-07-19 at 5 12 17 PM" src="https://github.com/user-attachments/assets/2d6d27cd-ce8f-4a85-9a38-35d41f9fc21e"> |
- …
=> InputPassword Button Adjustment

bitwarden_license/bit-web/src/app/admin-console/providers/services/web-provider.service.ts, bitwarden_license/bit-web/src/app/billing/providers/billing-history/provider-billing-history.component.ts, bitwarden_license/bit-web/src/app/billing/providers/clients/manage-client-name-dialog.component.ts, bitwarden_license/bit-web/src/app/billing/providers/clients/manage-client-subscription-dialog.component.ts, bitwarden_license/bit-web/src/app/billing/providers/clients/manage-clients.component.ts, bitwarden_license/bit-web/src/app/billing/providers/subscription/provider-subscription.component.html, bitwarden_license/bit-web/src/app/billing/providers/subscription/provider-subscription.component.ts, libs/angular/src/services/jslib-services.module.ts, libs/common/src/billing/abstractions/billilng-api.service.abstraction.ts, libs/common/src/billing/services/billing-api.service.ts, libs/common/src/billing/services/payment-method-warnings.service.spec.ts, libs/common/src/billing/services/payment-method-warnings.service.ts
https://bitwarden.atlassian.net/browse/AC-2888
This PR does some light refactoring and improves the error handling of the Consolidated Billing feature. 
- Renames the provider-specific methods in the `billingApiService` to include the word "provider"
- Wraps provider-specific methods that retrieve information in a try/catch that logs and shows a toast for any error that results from executing the request
- Moves any non-async logic out of `ngOnInit` and into the component constructor, adds `takeUntilDestroyed`
- Removes the "Add Credit" option from the Provider's subscription page per a Product requirement
- Protected functional changes …
=> [AC-2888] Improve consolidated billing error handling

apps/browser/src/autofill/popup/settings/autofill.component.html
PM-10131
Remove margin from last field in each card of autofill settings
=> [PM-10131] Remove margin from last field in each card of autofill settings

apps/browser/src/autofill/popup/settings/autofill.component.html, apps/browser/src/autofill/popup/settings/excluded-domains.component.html, apps/browser/src/autofill/popup/settings/notifications.component.html
PM-10139
Section headers should use heading 6 styling
=> [PM-10139] Section headers should use heading 6 styling

apps/desktop/src/auth/lock.component.ts
https://bitwarden.atlassian.net/browse/PM-8225
https://bitwarden.atlassian.net/browse/PM-10005
This PR adds dynamic detection for biometrics availability (e.g. clamshell mode, unplugged windows hello fingerprint / webcam device, client key half becomes available after a browser initated unlock).
- 📝 …
=> [PM-8225] Implement periodic biometric readiness check in lock component

apps/browser/src/autofill/services/autofill-constants.ts, apps/browser/src/autofill/services/inline-menu-field-qualification.service.ts
https://bitwarden.atlassian.net/browse/PM-10416
A couple of smaller issues have been found with how we capture data from user filled identity fields. This PR fixes the captured value used to populate the state field, address level 1 and level 2 fields, and zip code field. …
=> [PM-10416] Address field is used to populate state field when adding identity cipher from inline menu

apps/browser/src/_locales/en/messages.json, apps/browser/src/autofill/popup/settings/autofill-v1.component.ts, apps/browser/src/autofill/popup/settings/autofill.component.ts
PM-10134
Add text to default URI match detection select.
- This applies to both the current AND v2 browser autofill settings experience (per @danielleflinn )
- This does **not** update the value of the same selection in the add/edit cipher view
- This does not affect the corresponding message catalog keys in the desktop or web clients
- 🌱 (`:seedling:`) or ♻️ …
=> [PM-10134] Add text to default URI match detection select

libs/components/src/radio-button/radio-button.component.ts, libs/components/src/radio-button/radio-button.stories.ts, libs/components/src/radio-button/radio-input.component.ts
[CL-274](https://bitwarden.atlassian.net/browse/CL-274)
This PR updates the styling for the radio button to match the new extension refresh styles and adds a new story for the disabled state. Some styling was completed as part of the checkbox updates because they share a wrapper component.
See more in the Storybook Publish action (Form > Radio Button stories). …
=> [CL-274] Update styling for radio button

libs/components/src/item/item-content.component.html, libs/components/src/item/item-content.component.ts
[CL-338](https://bitwarden.atlassian.net/browse/CL-338)
If the end slot of the item content is empty, then it should not render. The parent container uses `tw-gap` to separate the end slot from the main content, so if the end slot is empty, we don't want the gap to display because this puts extra blank space at the end of the container. 
With end slot content:
Without end slot content: …
=> [CL-338] Remove extra space in item content when end slot is empty

apps/browser/src/popup/scss/base.scss
[CL-377](https://bitwarden.atlassian.net/browse/CL-377)
The browser extension's global css was overriding the input component's background color in dark mode. This PR excludes the component from the global css.
Before:
After:
- ❓ …
=> [CL-377] Fix extension style conflict for input background

apps/browser/src/_locales/en/messages.json, apps/browser/src/auth/popup/account-switching/account-switcher.component.html, apps/browser/src/auth/popup/account-switching/account-switcher.component.ts
[PM-9839](https://bitwarden.atlassian.net/browse/PM-9839)
- Disable account switching within the `AccountSwitcherComponent` component for safari users.
- This utilizes the [`enableAccountSwitching`](https://github.com/bitwarden/clients/blob/9c8d5a2b3555c977840946c727aa6882d2791b53/apps/browser/src/platform/flags.ts#L41-L46) method that automatically returns false when the browser is safari.
- @JaredSnider-Bitwarden I went a little beyond what we discussed and implemented the same checks for both the extension refresh and non-extension refresh instances on the page. The `account-switcher` path isn't guarded by anything so it could technically be accessed. Maybe unneeded defensive programming but it was a trivial add.
- Added logic to only show the `Lock All` button if there were any …
=> [PM-9839] Extension - Safari - Disable Account Switching

apps/browser/src/background/main.background.ts
https://bitwarden.atlassian.net/browse/PM-9458
Deduplicate backgroundmemorystorageservice to prevent race condition with one background service that has the userkey and one that does not.
- 🤔 …
=> [PM-9458] Deduplicate background storage service in browser mv2

apps/browser/src/vault/popup/components/vault-v2/vault-ui-onboarding/vault-ui-onboarding.component.ts
[PM-10433](https://bitwarden.atlassian.net/browse/PM-10433)
Expected to be able to get to the Learn More button with keyboard navigation and be able to hit Enter key to be directed to blog post
- 🤔 …
=> [PM-10433] Missing Focus state for Learn More button 

apps/browser/src/autofill/services/inline-menu-field-qualification.service.ts
https://bitwarden.atlassian.net/browse/PM-10550
An issue was found with how we handle qualifying credit card fields for the inline menu. Two problems arose during testing, the first being that we were not positioning the inline menu on credit card fields that contain an autocomplete="off" attribute. The second was how we were handling verification of keywords within the field, and issues with how we were parsing multi-word meta data values.
This PR fixes those issues and allows for presentation of the credit card inline menu on the example website listed in the linked Jira ticket. …
=> [PM-10550] Card inline menu not displayed on popup payment form

apps/browser/src/autofill/services/inline-menu-field-qualification.service.ts
https://bitwarden.atlassian.net/jira/software/c/projects/BW/boards/93?selectedIssue=PM-10598
We recently removed a qualification rule for ensuring the inline menu appears in valid locations for identity ciphers. This rule involved a check for the `autocomplete="off"` attribute on the field. If this check showed that the autocomplete attribute was set to a disabled value, it would not show the inline menu within that field.
This has led to a situation where the inline menu appears is many unrelated fields, which isn't helpful. I'm reverting that check to ensure the inline menu appears for identities only when autocomplete is expected. 
- …
=> [PM-10598] Revert autocomplete="off" removal when qualifying the inline menu for identity fields

libs/angular/src/directives/copy-click.directive.spec.ts, libs/angular/src/directives/copy-click.directive.ts, libs/vault/src/cipher-view/additional-options/additional-options.component.html, libs/vault/src/cipher-view/card-details/card-details-view.component.html, libs/vault/src/cipher-view/custom-fields/custom-fields-v2.component.html, libs/vault/src/cipher-view/view-identity-sections/view-identity-sections.component.html
[PM-10437](https://bitwarden.atlassian.net/browse/PM-10437)
[PM-10438](https://bitwarden.atlassian.net/browse/PM-10438)
Display the label of the field that was copied in the success message.
- If anyone has a suggestion for an input variable name other than `valueLabel` I'm all ears. Not my most creative name 😅 
|Copy Success - Card, Identity, Note|
|-|
|<video src="https://github.com/user-attachments/assets/8e1a2359-9a44-48bb-aed5-e7bfcb77cb7f"/>|
- ❌ …
=> [PM-10437][PM-10438] Copy toast message

libs/vault/src/cipher-form/components/additional-options/additional-options-section.component.html, libs/vault/src/cipher-form/components/card-details-section/card-details-section.component.html, libs/vault/src/cipher-form/components/custom-fields/custom-fields.component.html, libs/vault/src/cipher-form/components/identity/identity.component.html, libs/vault/src/cipher-form/components/item-details/item-details-section.component.html, libs/vault/src/cipher-form/components/login-details-section/login-details-section.component.html
[PM-10070](https://bitwarden.atlassian.net/browse/PM-10070)
Standardize section headings across the browser refresh to be `h6` rather than `h5`
https://github.com/user-attachments/assets/5842634d-962c-42e2-b31f-8160fc4576c7 …
=> [PM-10070] Browser Refresh headings

apps/browser/src/vault/popup/components/vault-v2/add-edit/add-edit-v2.component.html, apps/browser/src/vault/popup/components/vault-v2/add-edit/add-edit-v2.component.ts, apps/browser/src/vault/popup/components/vault-v2/view-v2/view-v2.component.html, apps/browser/src/vault/popup/components/vault-v2/view-v2/view-v2.component.ts
[PM-9921](https://bitwarden.atlassian.net/browse/PM-9921)
Add `PopOutComponent` to the header of the Add/Edit/View cipher components within the browser refresh
The back button behavior is broken once the extension is popped out. I expect that to be fixed in [PR 9556](https://github.com/bitwarden/clients/pull/9556) & [PM-9455](https://bitwarden.atlassian.net/browse/PM-9455)  
https://github.com/user-attachments/assets/6a382a13-1bbf-4e13-867f-50c0830b1c49 …
=> [PM-9921] Add Popout to Add/Edit/View components

bitwarden_license/bit-web/src/app/admin-console/providers/manage/members.component.ts
https://bitwarden.atlassian.net/browse/AC-2926
@eliykat caught an issue where the subscription that wires up the `searchControl` and `statusToggle` was not receiving an initial value for `searchControl`. This was due to an `emitEvent: false` option being used when `searchControl` was set in the component constructor. Removing it fixed the status toggles.
https://github.com/user-attachments/assets/673b1149-3bd9-442d-9b56-154f49946673
- Updated any …
=> [AC-2926] Fix status toggles for new Members page

apps/desktop/desktop_native/Cargo.lock, apps/desktop/desktop_native/core/Cargo.toml, apps/desktop/desktop_native/core/src/lib.rs, apps/desktop/desktop_native/core/src/process_isolation/linux.rs, apps/desktop/desktop_native/core/src/process_isolation/macos.rs, apps/desktop/desktop_native/core/src/process_isolation/mod.rs, apps/desktop/desktop_native/core/src/process_isolation/windows.rs, apps/desktop/desktop_native/napi/index.d.ts, apps/desktop/desktop_native/napi/index.js, apps/desktop/desktop_native/napi/src/lib.rs, apps/desktop/src/main/window.main.ts
https://bitwarden.atlassian.net/browse/PM-8395
https://bitwarden.atlassian.net/browse/PM-9433
https://bitwarden.atlassian.net/browse/PM-9435
Coredumps on Linux sometimes get logged to disk, which means we had to disable process (renderer) reloading on Linux, meaning that gc'd memory sticks around. Further, the main process does not get reloaded at all. In Linux, any process can attach a debugger to any other process of the same user, and read it's memory.
To fix this, this PR implements two solutions, **for production builds**. These do not yet cover all cases (and I'm not sure whether it is possible within the constraints of Electron), but should improve resistance to memory dumping attacks in many scenarios. Specifically, we make use of PR_SET_DUMPABLE=0 (read more about the behavior …
=> [PM-8395] Add runtime memory isolations & prevent crashdumps on desktop Linux

apps/browser/src/autofill/utils/index.ts
https://bitwarden.atlassian.net/browse/PM-10654
An issue was identified where MS Edge (which is currently still using mv2) no longer receives `chrome.runtime.sendMessage` responses correctly. This issue was introduced due to a change made to help Safari resolve responses from these messages more effectively. The change allowed Safari to handle a returned promise from the API, rather than by using the legacy callback method that was supported in mv2 on Chromium browsers.
Until we move all browsers to mv3, we will need to account for these two scenarios separate. These changes allow for that.  …
=> [PM-10654] Inline menu not working in MS Edge

apps/browser/src/autofill/deprecated/content/autofill-init.deprecated.spec.ts, apps/browser/src/autofill/services/autofill-overlay-content.service.spec.ts, apps/browser/src/autofill/services/inline-menu-field-qualification.service.spec.ts, apps/browser/src/autofill/utils/index.spec.ts
https://bitwarden.atlassian.net/browse/PM-10654
This PR fixes some Jest tests that were broken upon merging the changes for https://github.com/bitwarden/clients/pull/10414 …
=> [PM-10654] Fixing broken jest tests

apps/browser/src/background/main.background.ts, libs/common/src/platform/services/cryptography/encrypt.service.implementation.ts
https://bitwarden.atlassian.net/browse/PM-10607
Added slightly more verbose and clearer logging around decryption errors to help give context to how they are occurring.
When a user encounters decryption errors, we ask them to send a screenshot of their Console.  This will provide more helpful messages in the console for us to review and also for end users. …
=> Add consistent and contextual logging around decryption failure

apps/browser/src/background/nativeMessaging.background.ts, apps/desktop/src/services/native-messaging.service.ts
https://bitwarden.atlassian.net/browse/PM-8225
Improves the debugging experience for biometrics ipc by disabling the age check on messages when in dev mode. Since this is limited to development mode it does not impact security.
- ❓ …
=> [PM-8225] Disable biometrics timeout check in development mode

apps/desktop/resources/memory-dump-wrapper.sh
https://bitwarden.atlassian.net/browse/PM-10689
https://bitwarden.atlassian.net/browse/PM-9434
prevents rpm installed bitwarden instances from starting since the /usr/bin/bitwarden entry is a symlink. This causes the wrapper script use the wrong path to look for the actual bitwarden binary. This PR fixes this by following the symlink (if it is a symlink) and using the original path instead. …
=> [PM-10689] Fix rpm (& deb) packages not starting by following symlink

libs/components/src/toggle-group/toggle-group.mdx, libs/components/src/toggle-group/toggle-group.stories.ts, libs/components/src/toggle-group/toggle.component.html, libs/components/src/toggle-group/toggle.component.ts
[CL-271](https://bitwarden.atlassian.net/browse/CL-271)
This PR updates the styling of the toggle component to match the new spec for the extension refresh design. It also adds text wrap and truncation for toggle labels when they exceed the width of the toggle group. The mdx page for toggle group has been updated to more clearly explain the built-in behavior. …
=> [CL-271] Update styles for toggle

libs/components/src/no-items/no-items.component.html
[PM-8626](https://bitwarden.atlassian.net/browse/PM-8626)
Center all content in no items content
- FireFox extensions have default css that overrides the inheritance of text alignment:
|Empty Vault|No Results|Deactivated Org|
|-|-|-|
|<img width="431" alt="empty-vault" src="https://github.com/user-attachments/assets/5898d623-d71b-4db6-b0b2-0ea7202a778c">|<img width="436" src="https://github.com/user-attachments/assets/5deca452-c6ab-4cf2-a057-defec87b8e0b"/>|<img width="436" alt="deactivated-state" src="https://github.com/user-attachments/assets/7f0f3d1d-6e12-467f-98cb-9ddac4a8d21a">| …
=> [PM-8626] FireFox no-items alignment

apps/browser/src/_locales/en/messages.json, apps/browser/src/platform/popup/layout/popup-header.component.html, apps/browser/src/vault/popup/components/vault-v2/add-edit/add-edit-v2.component.ts, apps/browser/src/vault/popup/components/vault-v2/vault-generator-dialog/vault-generator-dialog.component.html, apps/browser/src/vault/popup/components/vault-v2/vault-generator-dialog/vault-generator-dialog.component.spec.ts, apps/browser/src/vault/popup/components/vault-v2/vault-generator-dialog/vault-generator-dialog.component.ts, apps/browser/src/vault/popup/services/browser-cipher-form-generation.service.ts, libs/vault/src/cipher-form/components/cipher-generator/cipher-form-generator.component.html, libs/vault/src/cipher-form/components/cipher-generator/cipher-form-generator.component.spec.ts, libs/vault/src/cipher-form/components/cipher-generator/cipher-form-generator.component.ts, libs/vault/src/cipher-form/index.ts
[PM-9675](https://bitwarden.atlassian.net/browse/PM-9675)
Introduce the `CipherFormGenerator` component and a corresponding Browser dialog to show the generator while editing/creating Login ciphers.
The generator options are currently a placeholder and will be replaced once they are available from the Tools team in [PM-7119](https://bitwarden.atlassian.net/browse/PM-7119).
https://github.com/user-attachments/assets/40881509-265d-45cc-8925-f55335a3d72f
- …
=> [PM-9675] Browser Refresh Login - Generator dialog

apps/browser/src/autofill/popup/settings/notifications.component.html
PM-10423
Fix notification settings view to match spacing and labels found elsewhere (e.g. Autofill settings)
| --- | --- |
| ![Screenshot 2024-08-07 at 1 25 34 PM](https://github.com/user-attachments/assets/6a81aff3-77f4-4637-8e23-6e8c128cb196) | ![Screenshot 2024-08-07 at 1 16 23 PM](https://github.com/user-attachments/assets/65c8d8e4-420f-43a2-a36d-6a785d172154) |
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or …
=> [PM-10423] Fix notification settings spacing and labels

libs/components/src/form-control/form-control.component.ts, libs/components/src/form-field/form-field.component.ts
[CL-381](https://bitwarden.atlassian.net/browse/CL-381)
This PR updates the margin for the form control and form field elements so that they are spaced more evenly. The form field also now has top padding to account for the vertical space that the absolutely placed label takes up.
See the Storybook Publish action's Form stories. …
=> [CL-381] Update spacing around form elements

apps/browser/src/_locales/en/messages.json, apps/browser/src/vault/popup/services/browser-cipher-form-generation.service.ts, apps/web/src/locales/en/messages.json, libs/vault/src/cipher-form/abstractions/cipher-form-generation.service.ts, libs/vault/src/cipher-form/components/cipher-generator/cipher-form-generator.component.ts, libs/vault/src/cipher-form/components/login-details-section/login-details-section.component.html, libs/vault/src/cipher-form/components/login-details-section/login-details-section.component.spec.ts, libs/vault/src/cipher-form/components/login-details-section/login-details-section.component.ts, libs/vault/src/cipher-form/services/default-cipher-form-generation.service.ts
[PM-10100](https://bitwarden.atlassian.net/browse/PM-10100)
Stacked on top of https://github.com/bitwarden/clients/pull/10352
Remove the automatic password generation for new login items. Instead, new help text will be shown encouraging users to use the password generator.
https://github.com/user-attachments/assets/5af5c249-4f8c-451b-8aa8-b2c750b506ea …
=> [PM-10100] Remove auto password generation

apps/web/src/app/auth/settings/two-factor-duo.component.html, apps/web/src/app/auth/two-factor.component.html, libs/angular/src/auth/components/two-factor-auth/two-factor-auth-yubikey.component.html
https://bitwarden.atlassian.net/browse/PM-10723
The inline menu is appearing within the vault on `type="password"` fields that are set to accept a 2fa code in some manner. That shouldn't happen, but guarding against that behavior in the inline menu's logic isn't the right approach to resolve the issue. 
Instead, for these types of fields we need to set the `autocomplete` attribute to `autocomplete="off"`, which ensures the inline menu ignores the field. …
=> [PM-10723] Remove autocomplete="new-password" attribute from 2fa based code inputs

apps/browser/src/vault/popup/components/vault-v2/item-more-options/item-more-options.component.ts
[PM-10652](https://bitwarden.atlassian.net/browse/PM-10652)
The fill and save dropdown from an item was calling MP reprompt twice. Looking further the check for MP reprompt already exists inside `this.vaultPopupAutofillService.doAutofillAndSave(this.cipher)`. Removing the excess reprompt logic. 
https://github.com/user-attachments/assets/832618ca-ef48-4287-bdf4-12e5ebcbf4a6 …
=> [PM-10652] remove excess MP reprompt call for fill and save

apps/browser/src/_locales/en/messages.json, apps/browser/src/popup/app-routing.module.ts, apps/browser/src/vault/popup/settings/appearance-v2.component.html, apps/browser/src/vault/popup/settings/appearance-v2.component.spec.ts, apps/browser/src/vault/popup/settings/appearance-v2.component.ts
[PM-7713](https://bitwarden.atlassian.net/browse/PM-7713)
Adds browser refresh version of the appearance settings page
- Same options as the current page, only some copy updates and removes the unused hints
https://github.com/user-attachments/assets/379c7c6e-b2e1-463c-aea2-92b19d76d7fb
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications …
=> [PM-7713] Refresh Appearance Settings

apps/web/src/app/billing/individual/premium.component.ts, apps/web/src/app/billing/organizations/organization-plans.component.ts
https://bitwarden.atlassian.net/browse/PM-10026
In main the zip code field is marked as (Required), but you can still create a subscription without entering one. In production you can also subscribe without having to enter a zip code. It is not this way when upgrading your organization in Admin Console though. I’m not certain what the expected behavior in production should be at this point, if it’s always been this way or was just introduced recently, but it seems like it should behave like the other required fields. Because of this I’m not sure if I marked the priority correct or if this is not a big issue.
https://github.com/user-attachments/assets/099b853d-66c9-4062-8f0a-5f2d00ecc6f0
- Written new …
=> [PM-10026] [Defect] Zip code is not being enforced when subscribing in Password Manager

apps/browser/src/platform/services/abstractions/abstract-chrome-storage-api.service.ts, apps/browser/src/platform/services/abstractions/chrome-storage-api.service.spec.ts, apps/browser/src/platform/services/browser-local-storage.service.spec.ts, apps/browser/src/platform/services/browser-local-storage.service.ts
https://bitwarden.atlassian.net/browse/PM-10788
The docs on these methods state: `or on failure (in which case runtime.lastError will be set).` which means we should reject the promise if this value is set. Not doing so could mean that if a `get` call fails we would instead resolve the promise with null.
- 📝 …
=> [PM-10788] Handle `chrome.runtime.lastError`

apps/browser/src/background/main.background.ts, apps/browser/src/platform/offscreen-document/offscreen-document.ts, apps/browser/src/platform/storage/browser-storage-service.provider.ts, apps/browser/src/platform/storage/offscreen-storage.service.ts, apps/browser/src/popup/services/services.module.ts, apps/web/src/app/core/core.module.ts, apps/web/src/app/platform/web-migration-runner.spec.ts, apps/web/src/app/platform/web-migration-runner.ts, libs/common/src/platform/state/state-definition.ts, libs/common/src/platform/state/state-definitions.ts, libs/common/src/platform/storage/primary-secondary-storage.service.ts, libs/common/src/platform/storage/window-storage.service.ts
https://bitwarden.atlassian.net/browse/PM-10754
Adds a new special storage location for browser to allow for duplication of stored data. This makes it so that data can be stored first in `chrome.storage.local` but also in `localStorage`. Data is saved in both places but it's only retrieved from `chrome.storage.local` if a non-null value is found, if a null-ish value is found that is when we will attempt to read from `localStorage`. Since `localStorage` is not available in the MV3 service worker we have to create a offscreen document to access it. 
I created a relatively generic service for having a primary-secondary storage service concept because we may also do this in web with `localStorage` and `IndexedDB`. 
- All formatters and local linters executed …
=> [PM-10754] Store DeviceKey In Backup Storage Location

apps/browser/src/vault/popup/settings/folders-v2.component.html, apps/browser/src/vault/popup/settings/folders-v2.component.ts
[PM-10784](https://bitwarden.atlassian.net/browse/PM-10784)
Rather than allowing a user to create any type of cipher on the folders page, the new button should show the new folder button
|Before|After|
|-|-|
|<img width="384" alt="folder-before" src="https://github.com/user-attachments/assets/9a89c8ad-3234-4670-91bb-d3d6459963cc">|<video src="https://github.com/user-attachments/assets/48831e20-597f-481b-8692-c97efe1e80ea" />|
- ❌ (`:x:`) or ⚠️ …
=> [PM-10784] New Folder button

apps/browser/src/vault/popup/components/vault-v2/add-edit/add-edit-v2.component.ts, apps/browser/src/vault/popup/components/vault-v2/view-v2/view-v2.component.html, apps/browser/src/vault/popup/components/vault-v2/view-v2/view-v2.component.spec.ts, apps/browser/src/vault/popup/components/vault-v2/view-v2/view-v2.component.ts
[PM-10700](https://bitwarden.atlassian.net/browse/PM-10700)
Navigate the user to the "View" screen after creating a cipher.
- I also added logic to navigate the user back to the vault from the view when the "back" button is hit. Otherwise the user would get navigated back to the add/edit screen.
- Added test file for the view component
https://github.com/user-attachments/assets/541ab4f9-aa32-484d-83ad-41a5d78251fa
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more …
=> [PM-10700] Navigate to View after cipher creation

libs/vault/src/cipher-form/components/item-details/item-details-section.component.html
[PM-9595](https://bitwarden.atlassian.net/browse/PM-9595)
Fix the Owner and Folder inputs from resizing based on their selected contents.
https://github.com/user-attachments/assets/f942083d-bc04-42aa-973a-e84ffdb1c6f1 …
=> [PM-9595] Browser Refresh - Fix owner / folder selects expanding out of container

apps/browser/src/_locales/en/messages.json, apps/web/src/locales/en/messages.json, libs/vault/src/cipher-form/components/login-details-section/login-details-section.component.html, libs/vault/src/cipher-form/components/login-details-section/login-details-section.component.ts
[PM-10651](https://bitwarden.atlassian.net/browse/PM-10651)
To have better discoverability, this icon should be shown as a bit-link with primary styling. Also adds title and aria label for the icon link.
- …
=> [PM-10651] Use bitLink for authenticator tooltip and add A11y support

apps/browser/src/auth/popup/extension-anon-layout-wrapper/extension-anon-layout-wrapper.component.html, apps/browser/src/auth/popup/extension-anon-layout-wrapper/extension-anon-layout-wrapper.component.ts, libs/auth/src/angular/anon-layout/anon-layout-wrapper.component.ts, libs/auth/src/angular/anon-layout/anon-layout.component.ts
[PM-10799](https://bitwarden.atlassian.net/browse/PM-10799)
**Issue**: When navigating from the create account screen to the login screen the `maxWidth` on the anon layout is being lost. 
**Cause**: The input was becoming `undefined` during the routing change but wasn't being set to the initial value again. Resulting in no max width being set on the layout.
**Fix**: Catch changes to the `maxWidth` input with `ngOnChanges` and ensure that `'md'` is used for as default value
https://github.com/user-attachments/assets/d0bb03fa-0fc5-462f-aee6-08397fb83174 …
=> [PM-10799] Login UI Width

libs/angular/src/auth/components/lock.component.ts, libs/auth/src/common/abstractions/pin.service.abstraction.ts, libs/auth/src/common/services/pin/pin.service.implementation.ts, libs/auth/src/common/services/pin/pin.service.spec.ts, libs/common/src/auth/services/user-verification/user-verification.service.spec.ts, libs/common/src/auth/services/user-verification/user-verification.service.ts
https://bitwarden.atlassian.net/browse/PM-10601
Builds on work from https://github.com/bitwarden/clients/pull/10332. 
To clean up the base `LockComponent` load logic which had too much PIN specific logic that should have been in a tested service.  This also applied to the `UserVerificationService`. 
Note: for this test, I temporarily changed the `verificationType` to "client" for the user verification dialog prompt. 
https://github.com/user-attachments/assets/a53d3abf-04c9-44d9-93e2-b583f6d7d8f5
https://github.com/user-attachments/assets/62c17d7e-635d-460c-b779-9de6ea1ffba5
https://github.com/user-attachments/assets/cc70d4e6-f40d-4ffb-84fc-be07317bdad6
- Written new unit and / or integration tests …
=> Auth/PM-10601 - Tech Debt Cleanup - Refactor Lock Component and User Verification to use PinService

libs/vault/src/cipher-form/components/login-details-section/login-details-section.component.html
[PM-10761](https://bitwarden.atlassian.net/browse/PM-10761)
Fix the password help text so that it is not broken up for screen readers due to the visual icon. …
=> [PM-10761] Fix broken text for screen readers

apps/browser/src/vault/popup/components/vault-v2/new-item-dropdown/new-item-dropdown-v2.component.ts, apps/browser/src/vault/popup/components/vault/vault-v2.component.ts
[PM-10757](https://bitwarden.atlassian.net/browse/PM-10757)
Pass in the current tab URL when creating a new item via the new item dropdown. …
=> [PM-10757] Browser Refresh - Pre-populate current tab when creating a new item

apps/browser/src/autofill/content/auto-submit-login.spec.ts
https://bitwarden.atlassian.net/browse/PM-10155
Fixing jest tests within the auto-submit content script. Triggered in an invalid manner due to a change within the sendMessage util used within autofill scripts. …
=> [PM-10155] Fixing broken jest tests for auto-submit content script

apps/browser/src/autofill/overlay/inline-menu/pages/list/autofill-inline-menu-list.ts
https://bitwarden.atlassian.net/browse/PM-10796
An issue was identified where a list of ciphers within the inline menu could potentially overlay the "New Login Item" button when switching between form fields. This occurs as a result of how we handle refreshing the list of ciphers as a user navigates from field to field. To resolve this, we are doing a check on the size of the cipher list container when updating a list of ciphers. This will ensure that we properly set the scroll class when the list is updated, even if a resize even does not trigger.  …
=> [PM-10796] Fix inline menu cipher list scroll behavior

apps/browser/src/popup/extension-refresh-route-utils.ts, libs/angular/src/auth/functions/unauth-ui-refresh-route-swap.ts
Builds on https://github.com/bitwarden/clients/pull/10327
https://bitwarden.atlassian.net/browse/PM-10069
To refactor (move + rename) the `unauthExtensionRefreshSwap()` function so it is available on non-extension clients as we discovered that, due to our component consolidation efforts, we will need it in those contexts. 
n/a …
=> Auth/PM-10069 - Refactor unauthExtensionRefreshSwap to be available in non-extension clients + rename

apps/browser/src/autofill/background/overlay.background.spec.ts, apps/browser/src/autofill/background/overlay.background.ts
https://bitwarden.atlassian.net/browse/PM-10897
An issue was identified with the inline menu's behavior when adding a login cipher from the inline menu. In an effect to capture all data that is present within any sub frames of a page, we are effectively overwriting the expected URI for a new login cipher with an invalid URI. 
Resolving this requires us to validate whether a found sub frame contains partial data for a login cipher, and if so we need to treat the top level frame as the authoritative URI for a new login cipher.  …
=> [PM-10897] Fixing invalid url reference when creating login ciphers from inline menu

apps/browser/src/autofill/services/inline-menu-field-qualification.service.ts
https://bitwarden.atlassian.net/browse/PM-10949
An issue was identified where the inline menu is appearing on fields for identity ciphers when it should not be present. To resolve this, we are switching from checking for identity fields in a fuzzy manner to checking in a strict manner. This ensures tighter validation, and still treats the `autocomplete` attribute as the most authoritative identifier. …
=> [PM-10949] Identity inline menu showing in unexpected fields

libs/common/src/enums/feature-flag.enum.ts
https://bitwarden.atlassian.net/browse/PM-10310
Add a feature flag for the in progress account deprovisioning work …
=> Add `AccountDeprovisioning` feature flag

apps/desktop/src/main/window.main.ts
https://bitwarden.atlassian.net/browse/PM-10879
The change https://github.com/bitwarden/clients/pull/9393 introduced a syscall to PR_SET_DUMPABLE, to prevent memory dumping and debugger attachment of the main process on Linux. This resulted in a defect where portals (including the file portal) do not work anymore:
https://github.com/flatpak/xdg-desktop-portal/issues/785
Until this issue is fixed on the portal side, this PR is moving the feature behind an environment variable, usable by people who do not use file attachments but who have extremely high security requirements.
- …
=> [PM-10879] Move linux memory isolations behind env variable

apps/browser/src/platform/popup/view-cache/popup-router-cache.service.ts, apps/browser/src/platform/popup/view-cache/popup-router-cache.spec.ts, apps/browser/src/platform/services/popup-view-cache-background.service.ts
https://bitwarden.atlassian.net/browse/PM-10940
Fix misc issues with https://github.com/bitwarden/clients/pull/9556:
- adds checks for when state is `null`
- fixes back navigation when in sidebar, see [here](https://github.com/bitwarden/clients/pull/10619/files#diff-7c27943c4f1d5aa04888448f185ac1e6d18c7f019b6371905a1abb4163144528R100)
- fixes console error constructing `PopupRouterCacheService`, see [here](https://github.com/bitwarden/clients/pull/10619/files#diff-7c27943c4f1d5aa04888448f185ac1e6d18c7f019b6371905a1abb4163144528R38-R41)
-  fixes back navigation fallback logic, see https://github.com/bitwarden/clients/pull/10541
- fixes Firefox/MV2 error by using `BrowserApi.getTab` instead of direct Chrome API
- All formatters and local linters executed …
=> [PM-10940] misc popout history cache bug fixes

apps/browser/src/_locales/en/messages.json, apps/web/src/locales/en/messages.json
Removed duplicate message keys introduced with https://github.com/bitwarden/clients/issues/10331 …
=> Remove duplicate message-keys

libs/components/src/dialog/dialogs.mdx, libs/components/src/form/forms.mdx, libs/components/src/stories/kitchen-sink/kitchen-sink.stories.ts
[CL-433](https://bitwarden.atlassian.net/browse/CL-433)
A couple of storybook docs pages were broken due to the way they were importing stories. This PR fixes that. It also adds a missing translation to the kitchen sink story to fix a console error.
Check storybook publish action -- Form and Dialog top-level docs pages. …
=> [CL-433] Fix broken docs pages

apps/browser/src/popup/app-routing.module.ts, apps/browser/src/popup/extension-refresh-route-utils.ts, libs/angular/src/utils/extension-refresh-swap.ts
n/a but blocks #10451 
To move the extension refresh route swap utility function to be available to non-extension clients. 
n/a …
=> Move extension refresh swap function to libs so other clients can use it

libs/tools/export/vault-export/vault-export-ui/src/components/export.component.html, libs/tools/export/vault-export/vault-export-ui/src/components/export.component.ts
https://bitwarden.atlassian.net/browse/PM-8490
This PR adds a password generator button to the file password input in the vault export …
=> [PM-8490] - Add generate password to password-protected export

apps/web/src/app/billing/accounts/trial-initiation/trial-billing-step.component.ts, apps/web/src/app/billing/individual/premium.component.ts, apps/web/src/app/billing/individual/user-subscription.component.ts, apps/web/src/app/billing/organizations/adjust-subscription.component.ts, apps/web/src/app/billing/organizations/billing-sync-api-key.component.ts, apps/web/src/app/billing/organizations/organization-plans.component.ts, apps/web/src/app/billing/organizations/organization-subscription-cloud.component.ts, apps/web/src/app/billing/organizations/organization-subscription-selfhost.component.ts, apps/web/src/app/billing/organizations/sm-adjust-subscription.component.ts, apps/web/src/app/billing/organizations/sm-subscribe-standalone.component.ts, apps/web/src/app/billing/settings/sponsored-families.component.ts, apps/web/src/app/billing/settings/sponsoring-org-row.component.ts, apps/web/src/app/billing/shared/adjust-storage.component.ts, apps/web/src/app/billing/shared/offboarding-survey.component.ts, apps/web/src/app/billing/shared/payment-method.component.ts, apps/web/src/app/billing/shared/update-license.component.ts
https://bitwarden.atlassian.net/browse/PM-6567
This PR migrates all use of the deprecated `PlatformUtilsService.showToast` to `@bitwarden/components/ToastService.showToast` in the billing components
- 🤔 …
=> [PM-6567] billing - migrate toast to CL service

libs/components/src/form-field/form-field.component.ts
[CL-380](https://bitwarden.atlassian.net/browse/CL-380)
This PR removes the hover state from disabled form fields since they are not interactive elements.
https://github.com/user-attachments/assets/ccd8dfec-cbfa-4a09-835f-688c50eda1a4
- ❓ …
=> [CL-380] Remove hover state from disabled form fields

libs/vault/src/cipher-view/autofill-options/autofill-options-view.component.html
[PM-11117 Different URI](https://bitwarden.atlassian.net/browse/PM-11117)
Changing the value of the input in `autofill options view` to show the user the `hostOrUri` value. This will not contain any website prefixes such as `http`, `https`, `ftp` …
=> [PM-11117] update autofill options to show different uri

bitwarden_license/bit-web/src/app/tools/reports/member-access-report/member-access-report.component.html, bitwarden_license/bit-web/src/app/tools/reports/member-access-report/member-access-report.component.ts, bitwarden_license/bit-web/src/app/tools/reports/member-access-report/response/member-access-report.response.ts, bitwarden_license/bit-web/src/app/tools/reports/member-access-report/services/member-access-report.mock.ts, bitwarden_license/bit-web/src/app/tools/reports/member-access-report/services/member-access-report.service.spec.ts, bitwarden_license/bit-web/src/app/tools/reports/member-access-report/services/member-access-report.service.ts, bitwarden_license/bit-web/src/app/tools/reports/member-access-report/view/member-access-report.view.ts
https://bitwarden.atlassian.net/browse/AC-3004
Adds the functionality of editing a member on a popup while on the member access report screen …
=> Added functionality to edit members on MemberAccessReportComponent

bitwarden_license/bit-web/src/app/secrets-manager/projects/dialog/project-delete-dialog.component.ts, bitwarden_license/bit-web/src/app/secrets-manager/projects/dialog/project-dialog.component.ts, bitwarden_license/bit-web/src/app/secrets-manager/projects/guards/project-access.guard.spec.ts, bitwarden_license/bit-web/src/app/secrets-manager/projects/guards/project-access.guard.ts, bitwarden_license/bit-web/src/app/secrets-manager/projects/project/project-people.component.ts, bitwarden_license/bit-web/src/app/secrets-manager/projects/project/project-service-accounts.component.ts, bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-delete.component.ts, bitwarden_license/bit-web/src/app/secrets-manager/secrets/dialog/secret-dialog.component.ts, bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/access/access-tokens.component.ts, bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/dialog/service-account-delete-dialog.component.ts, bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/dialog/service-account-dialog.component.ts, bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/guards/service-account-access.guard.spec.ts, bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/guards/service-account-access.guard.ts, bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/people/service-account-people.component.ts, bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/projects/service-account-projects.component.ts, bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/service-accounts-list.component.ts, bitwarden_license/bit-web/src/app/secrets-manager/settings/porting/sm-export.component.ts, bitwarden_license/bit-web/src/app/secrets-manager/shared/projects-list.component.ts, bitwarden_license/bit-web/src/app/secrets-manager/shared/secrets-list.component.ts, bitwarden_license/bit-web/src/app/secrets-manager/trash/dialog/secret-hard-delete.component.ts, bitwarden_license/bit-web/src/app/secrets-manager/trash/dialog/secret-restore.component.ts
https://bitwarden.atlassian.net/browse/SM-1141
This PR migrates all secrets manager toasts to the new CL toastService …
=> [SM-1141] migrate secrets manager toasts to CL toastService

apps/desktop/src/locales/en/messages.json
I suppose this change is relevant to:
https://bitwarden.atlassian.net/browse/PM-990
as it's a follow up to:
- https://github.com/bitwarden/clients/pull/4586
Trying to fix this `autometic` typo by updating it to `automatic`.
Location of the typo is this modal that currently appears when toggling `Unlock with system authentication` on my Flatpak installation on my Fedora system. …
=> [PM-11314] Fix system auth typo 'autometic' -> 'automatic'

apps/browser/src/autofill/popup/settings/autofill.component.ts, apps/browser/src/autofill/popup/settings/excluded-domains.component.html, apps/browser/src/autofill/popup/settings/excluded-domains.component.ts
PM-9673
The updated excluded domains view in the browser client does not focus inputs when they are first created and should, as an a11y concern.
https://github.com/user-attachments/assets/78b7cd62-ec11-4996-af4b-089b9ca8c4e2
=> [PM-9673] Autofocus newly added input in the excluded domains view

libs/components/src/toggle-group/toggle-group.component.ts, libs/components/src/toggle-group/toggle-group.mdx, libs/components/src/toggle-group/toggle-group.stories.ts, libs/components/src/toggle-group/toggle.component.ts
[CL-405](https://bitwarden.atlassian.net/browse/CL-405)
This PR adds the option for toggle groups to span the full width of their container. The default behavior remains the same (i.e. not spanning full width). …
=> [CL-405] Allow toggle group input to be full width

libs/components/src/item/item-content.component.html, libs/components/src/item/item.stories.ts
[CL-318](https://bitwarden.atlassian.net/browse/CL-318)
Text truncation for item content was working fine when there was only the default slot populated. Adding the start slot was causing the truncation to break. This PR updates where the truncation is applied to prevent that from happening, and updates the text overflow story to use the start slot. …
=> [CL-318] Ensure item content truncates when the 'start' slot is populated

apps/web/src/app/settings/preferences.component.ts
https://bitwarden.atlassian.net/browse/PM-9906
To fix the fact that having an org policy would block users from updating their preferences. This was due to the fact that we previously retrieved the values using `form.value` which omits disabled fields by default (having a policy disabled the vault timeout action radio input). We had to swap to using `form.getRawValue()` which provides all values regardless of enabled status. 
https://github.com/user-attachments/assets/07d02c15-e179-4c6c-9f4b-a39e2c15b0d5 …
=> Auth/PM-9906 - Web Preferences Component - Fix policy blocking preference update

libs/vault/src/cipher-view/login-credentials/login-credentials-view.component.html
[PM-10987 remove hover on copy for non premium users](https://bitwarden.atlassian.net/browse/PM-10987)
[PM-11118 remove hover for TOTP countdown](https://bitwarden.atlassian.net/browse/PM-11118)
Free users could see the TOTP input as hidden, their copy button should be disabled with no hover, and the premium badge should be clickable
Premium users should see the TOTP countdown but it should not show a `cursor-pointer` when hovered 
https://github.com/user-attachments/assets/1b573ff1-afd4-42f0-a7ba-ece93d4e2b50
- CI builds …
=> [PM-11118] adjust hover cursor styles for TOTP buttons

libs/vault/src/cipher-form/components/cipher-generator/cipher-form-generator.component.spec.ts, libs/vault/src/cipher-form/components/cipher-generator/cipher-form-generator.component.ts
[PM-10993](https://bitwarden.atlassian.net/browse/PM-10993)
The legacy password generation service implementation causes the state to be modified multiple times with a single save call. The upcoming replacement services from Tools will better support our use case here. So for now, I'm removing the call to save the password type option to the users settings in state. This avoids the multiple calls to update state and thus the repeated emissions (some outside of NgZone) that was causing unexpected behaviors.
- CI builds …
=> [PM-10993] Browser Refresh - Fix duplicate password generation emissions in Firefox

libs/vault/src/cipher-view/login-credentials/login-credentials-view.component.html
[PM-11126](https://bitwarden.atlassian.net/browse/PM-11126)
Do not show the `copy` or `toggle` icons in `login-credentials` unless user has `viewPassword` set to true
https://github.com/user-attachments/assets/e6de0274-1511-4567-a3e5-bb52592827eb …
=> [PM-11126] Do Not Show PW Toggle or Copy Unless User Can View PW

apps/web/src/app/oss-routing.module.ts, apps/web/src/app/tools/send/access.component.html, apps/web/src/app/tools/send/access.component.ts, apps/web/src/app/tools/send/send-access-explainer.component.html, apps/web/src/app/tools/send/send-access-explainer.component.ts, apps/web/src/locales/en/messages.json
https://bitwarden.atlassian.net/browse/PM-4473
This PR uses the anon layout for the send access page. Some refactoring of the access component was required in order to satisfy the design specs and the anon layout requirements.
|Before|After|
---|---
|![Screenshot 2024-08-23 at 9 28 27 AM](https://github.com/user-attachments/assets/62466653-03f9-4eaa-91bd-7c98ba24aa6b)|![Screenshot 2024-08-23 at 9 27 13 AM](https://github.com/user-attachments/assets/7c88acd2-762d-4e34-8b84-7bcadf18800e)| …
=> [PM-4473] use anon layout for send access component

libs/angular/src/auth/components/two-factor-auth/two-factor-auth.component.html
https://bitwarden.atlassian.net/browse/PM-11423
Fixes the alignment of 2fa auth components so they are center instead of leaning right.
Note: there is still a scrollbar in the following screenshot. This is due to the extra space added at the top of the page. That will be fixed (removed) in a separate PR to keep testing separate.
🚨 TIP: review this PR by hiding whitespace: …
=> [PM-11423] Bugfix - 2FA Auth Component Misalignment

libs/common/src/platform/abstractions/crypto.service.ts, libs/common/src/platform/services/crypto.service.spec.ts, libs/common/src/platform/services/crypto.service.ts
- Add new function in `CryptoService` that sets both UserKey and UserPrivateKey and also verifies that the private key can actually be decrypted with the user key. …
=> [PM-6727] Implement new `setUserKeys` function in `CryptoService`

apps/browser/src/_locales/en/messages.json, apps/web/src/locales/en/messages.json, libs/vault/src/cipher-view/autofill-options/autofill-options-view.component.html, libs/vault/src/cipher-view/login-credentials/login-credentials-view.component.html
(PM-11130)[https://bitwarden.atlassian.net/browse/PM-11130]
Added aria-labels to PW count button in login credentials and updated aria-label for launch website button in autofill
https://github.com/user-attachments/assets/b8548954-4cf4-4e9b-9164-33b37a110c62 …
=> [PM-11130] Accessibility in Login and Autofill View V2

libs/vault/src/cipher-view/item-details/item-details-v2.component.html
[PM-10374 last margin item details](https://bitwarden.atlassian.net/browse/PM-10374)
Remove margin from collections list if there are no folders inside item details v2 …
=> [PM-10374] Remove last margin from Item Details V2

apps/web/src/app/vault/individual-vault/vault.component.ts
https://bitwarden.atlassian.net/browse/PM-11338?atlOrigin=eyJpIjoiNDk5MTRjNzQ0NjZjNDIyNWEwYzljZTRiOWIwYjk0MzEiLCJwIjoiaiJ9
An error was being thrown when closing the dialog via clicking on the dialog backdrop. We were attempting to access a property on `undefined`. This PR checks `result` is not null or undefined before trying to access the `action` property. …
=> PM-11338: [Defect] Clicking outside of View {Item} dialog should close the dialog properly

libs/components/src/toggle-group/toggle-group.component.ts, libs/components/src/toggle-group/toggle.component.ts
[CL-442](https://bitwarden.atlassian.net/browse/CL-442)
[CL-405](https://bitwarden.atlassian.net/browse/CL-405)
This PR addresses 2 things:
1. There was a bug with the toggle group that caused it to display incorrectly in the browser extension. It was relying on global css present in the web app and Storybook that affects the `label` element `display` property. This PR explicitly sets the `display` property on the component.
2. The ticket to enable full width toggle groups was merged to the feature branch, but needs to be applied to `main` so that teams can use it during development prior to the merge of the feature branch. This PR applies the relevant css classes and input required to render a full width toggle group without the extension refresh changes, from #10658.
A randomly placed …
=> [CL-442][CL-405] Fix toggle group display in extension and add fullWidth input to main

apps/browser/src/autofill/utils/index.ts
https://bitwarden.atlassian.net/browse/PM-11519
An issue was found where websites that set a global `browser` variable trigger an issue with autofill content script behavior. This PR fixes that issue, allowing for autofill features to function on these websites once again. …
=> [PM-11519] `browser` global reference triggering an error when sending an extension message

apps/browser/src/autofill/services/autofill-constants.ts
Add "otp" TotpFieldNames array in autofill-constants.ts. Noticed on https://id.fedoraproject.org/login/
N/A
Add "otp" TotpFieldNames array in autofill-constants.ts. Noticed on https://id.fedoraproject.org/login/
As an aside, has a custom "linked" field been considered here like with passwords? I noticed at least [one request](https://community.bitwarden.com/t/allow-custom-field-names-for-totp-autofill/62103
) on the forum, but couldn't find much here with a search.
N/A …
=> [PM-11329] [chore] Add "otp" TotpFieldNames array in autofill-constants.ts

libs/vault/src/cipher-view/login-credentials/login-credentials-view.component.html, libs/vault/src/cipher-view/login-credentials/login-credentials-view.component.ts, libs/vault/src/components/totp-countdown/totp-countdown.component.ts
[PM-11427 Copy TOTP code without space](https://bitwarden.atlassian.net/browse/PM-11427)
update totp-countdown-component to pass to login both the totpcode and the formatted code. one for display and the other for copy
https://github.com/user-attachments/assets/ce480c31-5c35-48ad-abbc-15f6585f6350
- 📝 …
=> [PM-11427] Copy TOTP Code without space

apps/web/src/app/billing/organizations/adjust-subscription.component.html, apps/web/src/app/billing/organizations/adjust-subscription.component.ts
https://bitwarden.atlassian.net/browse/AC-2962
This PR removes the unused `payment.component` from the `adjust-subscription.component` template. For most of this work, we're migrating usage of the `payment.component` to the `payment-v2.component`, but since the original `payment.component` wasn't even being used in the first place, this is a simple removal. …
=> [AC-2962] Remove unused payment.component from adjust-subscription.component

apps/browser/src/vault/popup/components/vault-v2/item-copy-action/item-copy-actions.component.html, libs/vault/src/services/copy-cipher-field.service.spec.ts, libs/vault/src/services/copy-cipher-field.service.ts
[PM-11429](https://bitwarden.atlassian.net/browse/PM-11429)
- Users with the `Can View/Edit, Except Passwords` permissions will be able to copy values from an item except passwords. 
- The `Copy password` option in the item dropdown will not be shown if `viewPassword` is false. 
- The `viewPassword` check inside `copy-cipher-field` has been removed
https://github.com/user-attachments/assets/b2200f5e-a7b9-43b6-a670-d134eb9d9930 …
=> [PM-11429] Item Menu Copy Password Permissions

libs/vault/src/cipher-view/login-credentials/login-credentials-view.component.html
[PM-11428](https://bitwarden.atlassian.net/browse/PM-11428)
Removing the `disable` attr on the TOTP input in `login-credentials-view`. This will remove that extra shaded background. The view is already read only so there is no interaction for the user. 
This is how it will look once merged into main, and main is brought into the `ps/extension-refresh` branch …
=> [PM-11428] Style Totp View Input Browser V2

apps/web/src/app/vault/utils/collection-utils.spec.ts, apps/web/src/app/vault/utils/collection-utils.ts
[Slack thread](https://bitwarden.slack.com/archives/C04N1TX1CGM/p1713382222824719)
To resolve an error that occurs every time I lock the web vault where the collections get cleared during the lock process but the `collection-utils` `getNestedCollectionTree(...)` method doesn't have nullish data handling so it errors. 
Video: 
https://github.com/user-attachments/assets/17ee347f-9dfc-4836-815c-6f016d1bc9da
Screenshot …
=> Fix Web Vault Lock throwing error due to missing nullish collection check

apps/web/src/app/vault/components/vault-items/vault-collection-row.component.html, apps/web/src/app/vault/components/vault-items/vault-items.component.html, apps/web/src/locales/en/messages.json
[PM-11206](https://bitwarden.atlassian.net/browse/PM-11206)
For clarity purposes, we would like to rename some of the bulk and inline menu actions for collections
https://github.com/user-attachments/assets/1f662b15-3330-4331-852b-afbf13fb366d …
=> [PM-11206] Collection inline and bulk menu copy updates

apps/browser/src/background/main.background.ts, apps/browser/src/platform/services/background-browser-biometrics.service.ts
https://bitwarden.atlassian.net/browse/PM-11593
There is a dependency cycle of nativemessagingbackground -> cryptoservice -> browserbackgroundbiometricservice. This lead to browserbiometricsservice not having the nativemessagingbackground passed in. Before  https://github.com/bitwarden/clients/pull/10374 this was not an issue since the biometric callback was in the MainBackground and got the nativemessagingbackground during runtime.
This PR fixes the dependency cycle by instead passing in a function that dynamically returns the nativemessagingbackground during runtime to the browserbackgroundbiometricservice.
- Protected functional changes …
=> [PM-11593] Fix backgroundbrowserbiometricservice initialization

libs/vault/src/cipher-view/item-history/item-history-v2.component.html, libs/vault/src/cipher-view/item-history/item-history-v2.component.ts
[PM-10726](https://bitwarden.atlassian.net/browse/PM-10726)
Implement the `bitLink` directive to match new designs
|Before|After|
|-|-|
|![Screen Shot 2024-08-28 at 10 31 12 AM](https://github.com/user-attachments/assets/d1e4cb13-7ccc-4247-9ac4-f408090ac554)|![Screen Shot 2024-08-28 at 10 30 53 AM](https://github.com/user-attachments/assets/4ca00715-6266-4983-a08a-82bc708f05fa)|
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns …
=> [PM-10726] implement bitLink for password history

apps/browser/src/auth/popup/home.component.ts, apps/browser/src/auth/popup/login.component.ts, apps/web/src/app/auth/hint.component.ts, libs/angular/src/auth/components/base-login-decryption-options.component.ts, libs/angular/src/auth/components/hint.component.ts, libs/angular/src/auth/components/login-via-auth-request.component.ts, libs/angular/src/auth/components/login.component.ts, libs/auth/src/common/abstractions/login-email.service.ts, libs/auth/src/common/services/login-email/login-email.service.spec.ts, libs/auth/src/common/services/login-email/login-email.service.ts, libs/common/src/platform/state/state-definitions.ts
https://bitwarden.atlassian.net/browse/PM-11136
With the Auth Browser Refresh work (in progress), we will have a popout option on each page of the Browser Extension. This means that for certain flows, we will need a better way of retaining / persisting the login email to the popout.
Currently, the LoginEmailService has an `email` property that exists as a normal property on the service. This PR converts it to a state provider (in memory), and updates any components where the `getEmail()` and `setEmail()` methods are being used.
- `getEmail()` changes to `loginEmail$`
- `setEmail()` changes to `setLoginEmail()`
**Showing (a) normal login, (b) normal login with remember email, (c) password hint flow**
https://github.com/user-attachments/assets/2381a72a-58bd-40c0-9854-0a372176f52b
**Showing …
=> [PM-11136] Convert LoginEmailService email property to state provider

apps/browser/src/autofill/services/autofill.service.ts, apps/browser/src/vault/popup/components/vault/add-edit.component.ts, libs/angular/src/vault/components/add-edit.component.ts, libs/common/src/vault/models/view/card.view.ts, libs/common/src/vault/utils.spec.ts, libs/common/src/vault/utils.ts, libs/importer/src/importers/base-importer.ts, libs/vault/src/cipher-form/components/card-details-section/card-details-section.component.ts
PM-11350
We don’t currently enforce a normalized format for stored, user-entered values of expiry year (e.g. credit cards). Because of this, values like “00” are ambiguous, and invalid values like “0302", "awdawdawd", “40000”, and “4.5” are accepted.
These changes aim to normalize user submitted values to a YYYY format (given the context of expiration) so that downstream logic doesn’t have ensure proper handling these cases and to more authoritatively establish the full date to be stored.
Note, format normalization during new/edit cipher views happens upon save/submit (not on field value change).
**browser client**
https://github.com/user-attachments/assets/36545025-0e48-4910-ae08-a7c6f198555d
**browser client with component refresh** …
=> [PM-11350] Use shared expiration year normalization util function

libs/common/src/platform/services/crypto.service.ts
https://bitwarden.atlassian.net/browse/PM-11634
The userPublicKey$ observable is documented as returning null, however it instead throws an error if the private key is null / the user does not have a keypair. This PR fixes this behaviour by returning null early if the privatekey for the user is null.
https://github.com/user-attachments/assets/cd756337-b5c0-4146-ad5d-d16d8079363b …
=> [PM-11634] Return null in derivePublicKey if privateKey is null

libs/components/src/form-field/form-field.component.ts, libs/vault/src/cipher-view/additional-options/additional-options.component.html, libs/vault/src/cipher-view/autofill-options/autofill-options-view.component.html, libs/vault/src/cipher-view/card-details/card-details-view.component.html, libs/vault/src/cipher-view/card-details/card-details-view.component.ts, libs/vault/src/cipher-view/custom-fields/custom-fields-v2.component.html, libs/vault/src/cipher-view/item-details/item-details-v2.component.html, libs/vault/src/cipher-view/login-credentials/login-credentials-view.component.html, libs/vault/src/cipher-view/login-credentials/login-credentials-view.component.ts, libs/vault/src/cipher-view/read-only-cipher-card/read-only-cipher-card.component.html, libs/vault/src/cipher-view/read-only-cipher-card/read-only-cipher-card.component.ts, libs/vault/src/cipher-view/view-identity-sections/view-identity-sections.component.html, libs/vault/src/cipher-view/view-identity-sections/view-identity-sections.component.ts
[PM-10934](https://bitwarden.atlassian.net/browse/PM-10934)
Remove the bottom border from the last visible form field across all cipher types (when in view).
- The new CL FormField component has the ability to do this via Input on the [ps/extension-refresh](https://github.com/bitwarden/clients/blob/33c973d0730387bc2fafe2835da8d273e8d0ae3d/libs/components/src/form-field/form-field.component.ts#L38-L40) branch, so I added the same API here to match to allow for an easy integration.
- For the sections that have dynamic form fields, I added a thin wrapper component to handle the logic of updating the `disableReadOnlyBorder` property. 
- Because the markup is different between the old and new form field component I didn't see a reliable way to use CSS media queries to remove the bottom border. …
=> [PM-10934] Remove last form-field bottom border

apps/web/src/app/layouts/header/web-header.component.html
[PM-11444](https://bitwarden.atlassian.net/browse/PM-11444)
Swap colors of account menu from `info` to `muted`. I verified with Danielle that is this okay to go to main as the defect was more apparent in the `ps/extension-refresh` branch.
|Before|After|
|-|-|
|<img width="240" alt="Screenshot 2024-09-03 at 1 55 17 PM" src="https://github.com/user-attachments/assets/374481eb-3952-4175-8fdf-04db1b2f43eb">|<img width="265" alt="Screenshot 2024-09-03 at 1 54 58 PM" src="https://github.com/user-attachments/assets/ed478e0c-1fd5-404c-b2f2-cb258437637f">|
|Before|After|
|-|-|
|![Screen Shot 2024-09-04 at 10 10 06 AM](https://github.com/user-attachments/assets/08d61fa7-3377-4085-99ed-d3173d49764d)|![Screen Shot 2024-09-04 at 10 10 02 AM](https://github.com/user-attachments/assets/d4e6a17c-5d6b-4c50 …
=> [PM-11444] swap account font color for muted

libs/vault/src/cipher-view/cipher-view.component.ts
[PM-10734](https://bitwarden.atlassian.net/browse/PM-10734)
Remove brand from logic that determines if the card section should show, thus removing the scenario of when _only_ a brand exists.
|Before|After|
|-|-|
|![Screenshot 2024-09-03 at 2 57 53 PM](https://github.com/user-attachments/assets/26af187b-902b-4197-841d-ee6168c22809)|![Screenshot 2024-09-03 at 2 57 28 PM](https://github.com/user-attachments/assets/c383ea56-d1d7-4300-9d1a-8af5a2ad327a)|
- ❌ …
=> [PM-10734] Brand Only Cards

apps/web/src/app/vault/individual-vault/add-edit.component.ts, libs/common/src/vault/utils.spec.ts, libs/common/src/vault/utils.ts, libs/vault/src/cipher-view/cipher-view.component.ts
PM-11458
When determining whether the card expiration message should display or not, we don't consider `Date`s parsing of non-standard values. We can leverage the work in https://github.com/bitwarden/clients/pull/10735 to ensure the expiration Year is normalized correctly, resulting in a correct evaluation of the card expiry.
Additionally, add logic to disregard expiration month if the expiration year is in the past
- ❌ (`:x:`) or ⚠️ (`:warning:`) for …
=> [PM-11458] Bugfix - If two digit year was entered for card, the expired card message shows if card is not expired

apps/web/src/app/auth/settings/two-factor-setup.component.ts, apps/web/src/app/auth/settings/two-factor-webauthn.component.ts
[PM-9923](https://bitwarden.atlassian.net/browse/PM-9923)
If there is an error during user verification we want to inform the user of the issue. 
https://github.com/user-attachments/assets/fbbc0bff-d3bf-46ed-bc50-fb278521d91d
- ❓ …
=> [PM-9923] Show toast when error on WebAuthn Two Factor update 

apps/browser/src/autofill/background/overlay.background.ts
https://bitwarden.atlassian.net/browse/PM-11656
This PR fixes an issue found where ciphers could potentially be updated for the inline menu when the user is focused on a vault popup. We want to ensure that an update to ciphers in that state doesn't happen, and if identity or card ciphers need to be updated when that does occur, that they are invalidated so that the next update to the list of ciphers triggers an update to identity and card ciphers. 
- …
=> [PM-11656] Inline menu updates with empty list of ciphers

apps/web/src/app/admin-console/organizations/shared/components/access-selector/access-selector-dialog.stories.ts, apps/web/src/app/admin-console/organizations/shared/components/access-selector/access-selector-reactive.stories.ts, apps/web/src/app/admin-console/organizations/shared/components/access-selector/access-selector.stories.ts, apps/web/src/app/admin-console/organizations/shared/components/access-selector/storybook-utils.ts
https://bitwarden.atlassian.net/browse/PM-11623
The access selector stories were in a single file which was hard to understand and maintain. This was called out during the last major Storybook update.
Notable changes:
- split stories into separate files
- move common helper methods to a utils file
- add typesafety to the `Story` type, instead of using `StoryObj<any>`
- add jsdoc comments, which are displayed in Storybook in the autogenerated Docs page of each category. This really helps understand what we're actually looking at and how it mirrors what's in our production app
- add a story for the Collection dialog in a disabled state
- tweak some of the test data to better represent real world examples after flexible collection changes, e.g. disabled rows
- fix the group member access …
=> [PM-11623] Refactor access-selector stories

apps/desktop/scripts/after-pack.js, package-lock.json, package.json
https://bitwarden.atlassian.net/browse/PM-5506
Enable the use of electron fuses to forbid the use of `ELECTRON_RUN_AS_NODE`.
While I was at it, I also enabled the r[est of the fuses](https://www.electronjs.org/docs/latest/tutorial/fuses):
- `EnableCookieEncyption`: I don't think we really use cookies for anything, but it doesn't cost anything to encrypt them anyway.
- `EnableNodeOptionsEnvironmentVariable`: Forbids the use of `NODE_OPTIONS` and `NODE_EXTRA_CA_CERTS`. Some people might use these to set some self signed CA, but other than that it seems safe to enable.
- `EnableNodeCliInspectArguments`: Disables the use of `--inspect`, the node debugging tool. Might make it harder to extract secrets from memory?
- `EnableEmbeddedAsarIntegrityValidation` and `OnlyLoadAppFromAsar`: Validates …
=> [PM-5506] Enable electron fuses

apps/web/src/app/admin-console/organizations/manage/entity-events.component.html, apps/web/src/app/auth/two-factor.component.html, apps/web/src/app/settings/domain-rules.component.html
[CL-322](https://bitwarden.atlassian.net/browse/CL-322)
In the extension refresh feature branch, we are restyling form fields and will no longer be supporting fields without labels. This PR removes `tw-sr-only` from the few form fields that had sr-only labels. It also updates the entity events dialog to use the form field component properly.
Design has approved the copy (in some cases, we are using the existing sr-only text; in others, we are replacing the label with different copy). Design has also ok'd this being merged to `main` with no flag because these fields should have labels anyway, so these fields will gain visible labels in the next release after this PR is merged. Please let me know if you have concerns.
I haven't successfully set up 2 factor locally, but it's this form field …
=> [CL-322] Remove tw-sr-only from form field labels

apps/browser/src/auth/popup/login.component.ts, libs/angular/src/auth/components/login.component.ts
https://bitwarden.atlassian.net/browse/PM-11635
To resolve registration being broken on the extension due to the login component no longer executing the base component `ngOnInit` logic which was responsible for parsing the email from the query params. The extension register and login flows both use query params to pass email to the login component. They probably should use the `loginEmailService` in the future so we only have one method of saving the user's email in app, but we probably will still have to support query params as we offer links with prefilled email, I think. 
I recorded logging in to prove the login flow still preserves email and then I recorded new account creation to show it is fixed. 
https://github.com/user-attachments/assets/a6e55db1-76f5-41cd-bdf6-03ff36af34bf
- …
=> Auth/PM-11635 - Extension Registration Bugfix - Unable to login after account creation issue

apps/browser/src/background/main.background.ts, apps/cli/src/service-container/service-container.ts, apps/web/src/app/core/core.module.ts, libs/angular/src/services/jslib-services.module.ts, libs/common/src/platform/abstractions/app-id.service.ts, libs/common/src/platform/services/app-id.service.spec.ts, libs/common/src/platform/services/app-id.service.ts
https://bitwarden.atlassian.net/browse/PM-11526
Switch to getting app id through storage service and direct key to try and avoid any possible weirdness with the observable. The key we are using exactly matches the one state provider would have created for us. …
=> [PM-11526] Change AppIdService to Use Storage Directly

apps/web/src/app/billing/organizations/adjust-subscription.component.ts
https://bitwarden.atlassian.net/browse/AC-3028
Password Manager seats count and seat limit is blank after organization is created and when updating the seat count or setting the seat limit
https://github.com/user-attachments/assets/990bed94-629a-4a17-9858-4f43a3d0ea9a …
=> [AC-3028] [Defect] Password Manager seats count is blank after organization is created

libs/components/src/card/card.component.ts, libs/components/src/card/card.stories.ts, libs/components/src/item/item.component.html, libs/components/src/item/item.mdx, libs/components/src/item/item.stories.ts
[CL-357](https://bitwarden.atlassian.net/browse/CL-357)
If a `bit-card` or `bit-item` are used in the web app, we want to remove the border radius. This is because the background of the web app is white, and the `card` and `item` backgrounds are also white, which makes the bottom border look strange if it has a radius. 
This is meant to be a short-term solution to the white-on-white problem, so we are using a simple css ancestor selector to check if the `card` or `item` is rendered within the web app's `bit-layout`. This means that `card`s and `item`s used in the browser extension will still retain their border radius as per design specifications, as will `card`s and `item`s in dialogs in both the web app and the browser extension. (Dialogs are rendered outside of the `bit-layout` even on …
=> [CL-357] Remove border radius when displayed in web app

libs/angular/src/auth/components/update-temp-password.component.ts
https://bitwarden.atlassian.net/browse/PM-10856
In #9480, we added an additional warning for TDE offboarding.  In doing so, the phrase names were accidentally changed to no longer match those in `messages.json`.  This adjusts them back to what they were prior to that PR, while leaving the new TDE phrase in place. …
=> Changed temp password reset phrase names to match translations

apps/browser/src/_locales/en/messages.json, apps/web/src/locales/en/messages.json, libs/vault/src/cipher-view/login-credentials/login-credentials-view.component.html
[PM-11130](https://bitwarden.atlassian.net/browse/PM-11130)
- Update aria-label of the character count button to have more specific text
- Also added `aria-expanded` so that the screen reader announces whether the content is expanded or not.
https://github.com/user-attachments/assets/6fcbb2b8-ee6f-4fe3-b86d-7db01f183b5c
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for …
=> [PM-11130] Character Count aria-label

apps/web/src/app/billing/organizations/organization-plans.component.html, apps/web/src/app/billing/organizations/organization-plans.component.ts
https://bitwarden.atlassian.net/browse/AC-2965
This PR updates the `organization-plans.component` to use the new `payment-v2.component` when the `AC-2476-deprecate-stripe-sources-api` is on. This new component begins using some new Stripe methods under the hood to avoid an upcoming deprecation.
Server PR: https://github.com/bitwarden/server/pull/4737
https://github.com/user-attachments/assets/4b78eb86-841e-4401-9051-6cc4eaa58955
https://github.com/user-attachments/assets/8ff355a4-64b2-4a97-aa71-2d36138d32d7
https://github.com/user-attachments/assets/8ebcf4db-b855-4a9a-9c5c-3056637ec1cd …
=> [AC-2965] Use payment-v2.component in organization-plans.component when FF is on

apps/browser/src/popup/app-routing.animations.ts, apps/browser/src/vault/popup/components/vault-v2/view-v2/view-v2.component.html, apps/browser/src/vault/popup/settings/trash-list-items-container/trash-list-items-container.component.ts
[PM-11692](https://bitwarden.atlassian.net/browse/PM-11692)
[PM-11693](https://bitwarden.atlassian.net/browse/PM-11693)
[PM-11694](https://bitwarden.atlassian.net/browse/PM-11694)
* Viewing item does not slide transition in
* Restoring/permanently deleting item from View item page takes you to Vault page
* Permanently Delete button has incorrect screenreader announcement
https://github.com/user-attachments/assets/5ecc3ea8-56fa-46aa-88d8-1696a5cd460a
- …
=> [PM-11692] [PM-11693] [PM-11694] Fixed defects with browser refresh trash component

apps/browser/src/autofill/services/collect-autofill-content.service.ts
Fixes errors and high CPU usage / browser lockup on offending webpages.
HTMLTableCellElement.cellIndex will be -1 if the cell is not part of any row, which will cause getTextContentFromElement to fail since it will not receive a valid sibling cell.
See https://developer.mozilla.org/en-US/docs/Web/API/HTMLTableCellElement/cellIndex
Change comes from discovered bug in use of addon on Microsoft Edge.
Fixes console errors and browser instability.
- Updated …
=> [PM-11629] Handle detached table cells in autofill service

apps/web/src/app/billing/organizations/change-plan-dialog.component.html
https://bitwarden.atlassian.net/browse/AC-3022
Selecting a plan makes the plan cards content to auto-adjusts
Uploading Screen Recording 2024-09-09 at 11.24.13.mov… …
=> [AC-3022][Defect] Selecting a plan makes the plan cards content to auto-adjusts

apps/cli/src/base-program.ts, apps/cli/src/program.ts, apps/cli/src/service-container/service-container.ts, libs/common/src/platform/services/user-auto-unlock-key.service.ts
https://bitwarden.atlassian.net/browse/PM-10684
To remove a race condition between checking for the user key in state and setting the auto user key. 
The `apps/cli/src/program.ts` "option:session" handler being async allowed it to execute in parallel with the command and `apps/cli/src/base-program.ts` `exitIfLocked()` method. The `exitIfLocked()` method was calling to check if there was a user key before the "option:session" handler had finished setting the user key from the auto user key. 
https://github.com/user-attachments/assets/3b0b9742-16ee-49d9-92b1-17dbe5399366
- Used …
=> Auth/PM-10684 - Fix CLI asking for MP even if session key provided as command option

libs/components/src/item/item-content.component.html
[PM-11702](https://bitwarden.atlassian.net/browse/PM-11702)
- Issue: If a user has a larger default font size and longer email address the icons can be pushed out of view of the account switcher.
- Fix: Reset `min-width` within `bit-item-content` to `0` to override flex from setting `min-width` to `auto`.
- I don't get to link to a spec often but here it's the only thing that makes sense. [CSS Spec for Flex](https://www.w3.org/TR/css-flexbox-1/#min-size-auto)
- TLDR; `flex` sets `min-width: auto` whose overflow is visible and not a scroll element, auto equates to the "content-based minimum size". Which I understand to be the natural width of the content. The width of the item  content grows with the `rem` unit causing overflow. Rather than having the text be truncated.
|Before|After| …
=> [PM-11702] BitItemContent overflow

apps/browser/src/platform/popup/layout/popup-footer.component.html, apps/browser/src/platform/popup/layout/popup-header.component.html, libs/components/src/item/item.component.ts, libs/components/src/item/item.stories.ts
[CL-445](https://bitwarden.atlassian.net/browse/CL-445)
This PR fixes a few small spacing and sizing issues that were uncovered after updating the base rem size to 16px. …
=> [CL-445] Fix small sizing and spacing issues

libs/components/src/form-field/form-field.component.html
[CL-382](https://bitwarden.atlassian.net/browse/CL-382)
This PR adds padding to the readonly form field to account for the change in border width when the field is focused, which prevents the elements around the form field from shifting around as the field is focused and unfocused. Because border widths are in pixels, I switched the existing padding to a pixel unit and then accounted for the added focus border width when the field is unfocused.
Before:
https://github.com/user-attachments/assets/084c39d9-2507-4257-85c8-1cc32f28729d
After:
https://github.com/user-attachments/assets/4ed6b471-0aa4-4866-8af3-8287ba7e3917
- Protected functional …
=> [CL-382] Reduce element shifting on readonly hover

libs/components/src/stories/colors.mdx, libs/components/src/tw-theme.css, libs/components/tailwind.config.base.js
[CL-396](https://bitwarden.atlassian.net/browse/CL-396)
This PR updates the base color palette as per the most recent colors from design.
Check Storybook for changes (recommend the Colors page and the Kitchen Sink). …
=> [CL-396] Update theme colors to new hexes

apps/web/src/app/billing/organizations/change-plan-dialog.component.html, apps/web/src/app/billing/organizations/change-plan-dialog.component.ts, apps/web/src/app/billing/shared/payment/payment-v2.component.ts
https://bitwarden.atlassian.net/browse/PM-11728
This PR adds the `payment-v2.component` to the `change-plan-dialog.component` and uses it to tokenize the payment method when the `AC-2476-deprecate-stripe-sources-api` FF is on.
See Server PR: https://github.com/bitwarden/server/pull/4757 …
=> [PM-11728] Use payment-v2.component in change-plan-dialog.component

apps/web/src/app/vault/org-vault/vault-header/vault-header.component.html, bitwarden_license/bit-web/src/app/secrets-manager/shared/new-menu.component.html
[PM-11436](https://bitwarden.atlassian.net/browse/PM-11436)
Standardize the "+ New" button on Password Manager, Secrets Manager and Admin Console
- Also add a check for "organization" to stop the "new item" from flashing before the organization is populated in the Admin Console
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of …
=> [PM-11436] New "+" button

.github/workflows/test.yml
We are experiencing failures of our CI in validating desktop native integrations on windows in the form of buffer overflows due to repeated Node-API GetProcAddress failures. Possibly related to https://github.com/napi-rs/napi-rs/issues/1405.
I work around that here by only testing the `core` crate in windows. The other two OSes still test the full workspace.
We don't have any tests in the napi crate, so there's no harm in removing those tests right now. If we have tests there in the future, we'll need to actually fix this. However, the napi crate is just a wiring crate, so maybe we won't ever have any unit tests there.
- Protected …
=> Do not test napi crate on windows

apps/web/src/app/auth/migrate-encryption/migrate-legacy-encryption.component.ts, apps/web/src/locales/en/messages.json, libs/common/src/vault/abstractions/folder/folder-api.service.abstraction.ts, libs/common/src/vault/services/folder/folder-api.service.ts
https://bitwarden.atlassian.net/browse/PM-10914
Many legacy migrations have failed due to un-decryptable folders. This allows the user the option to delete all their folders and attempt the migration again.
See bitwarden/server#4761 for server-side changes
https://github.com/user-attachments/assets/67883850-bde4-4b5c-a799-29ad912cd66a …
=> [PM-10914] add option to delete all folders if migration fails

apps/browser/src/platform/popup/layout/popup-header.component.html, libs/components/src/section/section-header.component.html, libs/components/src/stories/colors.mdx, libs/components/src/tw-theme.css, libs/components/src/typography/typography.directive.ts
[CL-395](https://bitwarden.atlassian.net/browse/CL-395)
We are removing the `text-headers` color to use `text-main` instead. I also fixed a typo with the primary-600 color.
SVGs were already updated to use the `art` palette colors instead of `text-headers` and `info-600` here: #10990 
See Storybook (Typography story is the most affected)
- 👍 (`:+1:`) …
=> [CL-395] Remove text headers color

apps/desktop/src/locales/en/messages.json, apps/web/src/locales/en/messages.json, libs/tools/export/vault-export/vault-export-ui/src/components/export.component.html, libs/tools/export/vault-export/vault-export-ui/src/components/export.component.ts
https://bitwarden.atlassian.net/browse/PM-11949
With https://github.com/bitwarden/clients/pull/10539 we introduced a generate password and copy password button for password-protected exports. 
The generate password button worked, but instead of just setting the field values it also stored it within a local variable. This was then used for the copy password button. When a user had not used or modified the content of the password field, the value of the local variable was copied to the clipboard instead of then password field content.
This PR fixes this by removing the local variable and instead of manually copying the values and showing the success toast, we now use the copy-click-directive.
- Written …
=> [PM-11949] Fix generating and copying export password

apps/web/src/app/billing/services/stripe.service.ts, apps/web/src/app/billing/shared/payment/payment-label-v2.component.html, apps/web/src/app/billing/shared/payment/payment-label-v2.component.ts, apps/web/src/app/billing/shared/payment/payment-v2.component.html, apps/web/src/app/billing/shared/payment/payment-v2.component.ts, apps/web/src/app/billing/shared/payment/payment.component.html, apps/web/src/app/billing/shared/payment/payment.component.ts, apps/web/src/app/billing/shared/tax-info.component.html, apps/web/src/locales/en/messages.json, apps/web/src/scss/forms.scss
[PM-11657](https://bitwarden.atlassian.net/browse/PM-11657)
Update Stripe components to match the new design components that are currently in development on the `ps/extension-refresh` branch.
- This work is separate from the working going on around the `AC2476_DeprecateStripeSourcesAPI` flag, so I implemented the changes on both `payment.component` and `payment-v2.component`.
- One change that _isn't_ behind a flag is switching the copy for Security code from `Security code (CVV)` to `Security code / CVV`. I wanted to refrain from injecting feature flag logic there so I got the go ahead from @danielleflinn that this change can go in to main now. 
I wasn't able to get the `DM Sans` font to load within the iframe from Stripe. Their documentation does allow for passing a …
=> [PM-11657] Stripe + Browser Refresh Styling

apps/browser/src/popup/app.component.ts, libs/common/src/services/vault-timeout/vault-timeout.service.ts
https://bitwarden.atlassian.net/browse/PM-12007
`switchMap` was a bad choice for this particular operation, the logout process can change the active user, so while the the logout process was happening the `AccountService.activeAccount$` will emit again. `switchMap` attempts to cancel the ongoing emission (with a promise like this, that does nothing to actually stop the process) and then moves onto run the code with the new emissions. A `concatMap` will make sure an emission that was started will finish, it seems very clear to me that that is what we intend, by the fact we wrap this operation in a `firstValueFrom`. 
This makes it so that logout only runs once and then we properly calculate the next up user. Before logout seemed to happen about 3 times, the first time it would select the …
=> [PM-12007] Fix vault timeout action logout with account switching

apps/browser/src/tools/popup/settings/about-page/more-from-bitwarden-page-v2.component.html, apps/browser/src/tools/popup/settings/about-page/more-from-bitwarden-page-v2.component.ts, libs/common/src/admin-console/abstractions/organization/organization.service.abstraction.ts
https://bitwarden.atlassian.net/browse/PM-11631
This PR hides the "Free Bitwarden Families" button if none of their orgs have family sponsorship available. …
=> [PM-11631] - hide free Bitwarden Families button if user is not eligible

libs/common/src/platform/misc/lazy.ts
I saw `Lazy` while reviewing an unrelated PR and thought it was cool so I checked it out and saw that it could be simplified with the use of a symbol. It's not really a necessary PR but I just wanted to share it in case we wanted to merge  it :) …
=> feat: simplify lazy.ts

apps/browser/src/_locales/en/messages.json, apps/desktop/src/locales/en/messages.json, apps/web/src/locales/en/messages.json
PM-12031
- Fix typo where an "f" character should be a "t" character
- fix misc metadata typos in the message catalogs
=> [PM-12031] Bugfix - Fix typos

apps/web/src/app/admin-console/organizations/create/organization-information.component.ts, apps/web/src/app/billing/accounts/trial-initiation/trial-billing-step.component.html, apps/web/src/app/billing/accounts/trial-initiation/trial-billing-step.component.ts
https://bitwarden.atlassian.net/browse/PM-11725
This PR adds the `payment-v2.component` to the `trial-billing-step.component` and uses it when the `AC-2476-deprecate-stripe-sources-api` is active. All supporting server-side changes have already been made. …
=> [PM-11725] Use payment-v2.component in trial-billing-step.component

apps/desktop/desktop_native/core/src/clipboard.rs
https://bitwarden.atlassian.net/browse/PM-2718
We added support for setting `exclude_from_history` https://github.com/1Password/arboard/pull/159, which hides values from MacOS clipboard managers by setting `org.nspasteboard.ConcealedType`. This enables the use of `exclude_from_history` in our desktop application.
Resolves #2633. …
=> [PM-2718] Set nspasteboard.ConcealedType for clipboard on MacOS

apps/web/src/app/vault/individual-vault/vault-header/vault-header.component.ts
[PM-11436](https://bitwarden.atlassian.net/browse/PM-11436)
- Set `extensionRefreshEnabled` to be undefined so the "new" button isn't shown until the feature flag is resolved
|Before|After|
|-|-|
| <video src="https://github.com/user-attachments/assets/d439652d-59e1-4629-b584-ae2803231997" />|<video src="https://github.com/user-attachments/assets/fab4d98d-c267-416c-8d75-4d41efccf052" />|
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or …
=> [PM-11436] - Password Manager "New" flashing

libs/angular/src/scss/webfonts.css
[CL-447](https://bitwarden.atlassian.net/browse/CL-447)
This is our first time using variable fonts, and it turns out you do need to define the font weight range in order for it to work properly across all browsers. I don't know exactly why, but Chrome and Firefox were rendering it fine while Safari was not. Adding the font weight range gave Safari the correct weight styling.
Before:
After: …
=> [CL-447] Ensure DM Sans displays correctly at all font weights

apps/browser/src/vault/popup/components/vault-v2/add-edit/add-edit-v2.component.spec.ts, apps/browser/src/vault/popup/components/vault-v2/add-edit/add-edit-v2.component.ts, apps/browser/src/vault/popup/components/vault-v2/view-v2/view-v2.component.spec.ts, apps/browser/src/vault/popup/components/vault-v2/view-v2/view-v2.component.ts, libs/vault/src/cipher-form/components/card-details-section/card-details-section.component.html, libs/vault/src/cipher-form/components/card-details-section/card-details-section.component.spec.ts, libs/vault/src/cipher-form/components/card-details-section/card-details-section.component.ts, libs/vault/src/cipher-form/components/custom-fields/custom-fields.component.html, libs/vault/src/cipher-form/components/custom-fields/custom-fields.component.spec.ts, libs/vault/src/cipher-form/components/custom-fields/custom-fields.component.ts, libs/vault/src/cipher-form/components/login-details-section/login-details-section.component.html, libs/vault/src/cipher-form/components/login-details-section/login-details-section.component.spec.ts, libs/vault/src/cipher-form/components/login-details-section/login-details-section.component.ts, libs/vault/src/cipher-view/card-details/card-details-view.component.html, libs/vault/src/cipher-view/card-details/card-details-view.component.ts, libs/vault/src/cipher-view/cipher-view.component.html, libs/vault/src/cipher-view/custom-fields/custom-fields-v2.component.html, libs/vault/src/cipher-view/custom-fields/custom-fields-v2.component.ts, libs/vault/src/cipher-view/login-credentials/login-credentials-view.component.html, libs/vault/src/cipher-view/login-credentials/login-credentials-view.component.ts, libs/vault/src/services/copy-cipher-field.service.spec.ts, libs/vault/src/services/copy-cipher-field.service.ts
- something went sideways in a merge
I didn't notice one of my [commits](https://github.com/bitwarden/clients/pull/10832/commits/2f4bc893f0c7447269ca57832aee91f7948eacf4) erased all of my changes in https://github.com/bitwarden/clients/pull/10832. Which I'm still a little confused by. 
Anyways, this adds back all of the event collections in the extension refresh components
|Event|Location|
|-|-|
|`Cipher_ClientViewed`| View, Edit |
|`Cipher_ClientToggledPasswordVisible`| View, Edit |
|`Cipher_ClientToggledHiddenFieldVisible`| View, Edit |
|`Cipher_ClientToggledCardCodeVisible`| View, Edit |
|`Cipher_ClientToggledCardNumberVisible`| View, Edit|
|`Cipher_ClientToggledTOTPSeedVisible`| Edit |
|`Cipher_ClientCopiedPassword`| Vault, View |
|`Cipher_ClientCopiedHiddenField` | View |
| …
=> [PM-11267] Extension Refresh Events

apps/browser/src/vault/popup/components/vault-v2/view-v2/view-v2.component.ts, apps/browser/src/vault/popup/services/browser-totp-capture.service.spec.ts, apps/browser/src/vault/popup/services/browser-totp-capture.service.ts, libs/vault/src/cipher-form/abstractions/totp-capture.service.ts, libs/vault/src/cipher-view/autofill-options/autofill-options-view.component.ts
[PM-11393](https://bitwarden.atlassian.net/browse/PM-11393)
The `AutofillOptionsSection` component was dependent on the `TotpCaptureService` which was not being provided in Web. We can make this dependency optional by using `PlatformUtilsService` instead of making the `TotpCaptureService` serve unrelated purposes. Without the dependency the `AutofillOptionsSection` component can now render without issue on Web. …
=> [PM-11393] Browser Refresh - Fix missing Autofill Options section in Web view

apps/browser/src/background/main.background.ts, apps/browser/src/popup/app.component.ts
https://bitwarden.atlassian.net/browse/PM-12298
When Safari does `chrome.runtime.reload` they apparently also fire the onInstalled reason of `installed` this makes us open a web page each time the user locks/logs out. Safari apparently does not do this for side-loaded extensions. The best fix for this is to fallback to the logic we ran before for safari which is just a `window.location.reload`.  …
=> [PM-12298] Add Back Safari Only Handling of Process Reload

libs/components/src/search/search.component.html, libs/components/src/search/search.component.ts, libs/components/tsconfig.json
[PM-8582](https://bitwarden.atlassian.net/browse/PM-8582)
This PR addresses poor performance in Safari, observed in the browser extension refresh. We don't quite know why, but using `type="search"` for a search input causes rendering lag in Safari. Our existing extension code conditionally uses `type="text"` for Safari, so we are implementing the same logic for the component library Search component. Note that this will also apply to Safari web.
I was unable to reproduce the poor performance in Safari version 17.6, but it has been reproduced in 17.5. While this change helps mitigate the poor performance, it does not entirely eliminate it in version 17.5. Since it looks like more recent versions of Safari perform better, we expect this issue to lessen as more people update Safari.
- …
=> [PM-8582] Improve search performance in Safari

libs/tools/send/send-ui/src/send-list-items-container/send-list-items-container.component.html
While reviewing and testing https://github.com/bitwarden/clients/pull/11002 I noticed that clicking on the copy send link and delete send buttons within the send list view, would also navigate to the selected Send's edit page. 
The area to display the button was also the click area to trigger navigating to `/edit-send`. Scoping the front part of the area to navigate to edit and the buttons on the end to their actions fixes this. …
=> Fix click on copy send link and delete send buttons

apps/web/src/app/tools/reports/pages/exposed-passwords-report.component.html, apps/web/src/app/tools/reports/pages/exposed-passwords-report.component.ts
https://bitwarden.atlassian.net/browse/PM-12067
With the migration to use the [TableComponent](https://components.bitwarden.com/?path=/docs/component-library-table--docs) from the Component library, it enables us to add column sorting to the exposed passwords report.
- **Add sorting to exposed passwords report -** https://github.com/bitwarden/clients/commit/8020734b85a3b199a470b2b8c0b7ef085d398b88
- Create new type to represent a row within the report
- Add types and remove usage of any
- Include the exposed number of times within the data passed to the datasource/table instead of looking it up via the `exposedPasswordMap`
- Enable sorting via bitSortable
- Set default sort to order by exposed number of times in descending order
- **Show headers and sort also within AC version of …
=> [PM-12067] Add sorting to exposed passwords report

apps/browser/src/popup/scss/tailwind.css, libs/components/tailwind.config.base.js
[CL-448](https://bitwarden.atlassian.net/browse/CL-448)
Add custom styles for scrollbar in the Tailwind Configuration
- FireFox doesn't support the `webkit` prefix, I used [scrollbar-color](https://developer.mozilla.org/en-US/docs/Web/CSS/scrollbar-color) instead. The only downside is it doesn't support the hover styles.
- Safari doesn't seem to respond when the system theme is transitioned for the browser. That's why there is a separate video for light/dark below
|Chrome|Safari Light|Safari Dark|FireFox|
|-|-|-|-|
|<video src="https://github.com/user-attachments/assets/11a8403f-9a62-451a-853e-a2c3b2a678b8"/>|<video src="https://github.com/user-attachments/assets/6899be72-7f87-48ad-a949-715ad5b1d492" />|<video src="https://github.com/user-attachments/assets/9fb9ece5-da25-4700-8772-8cd5dd5d …
=> [CL-448] Scrollbar Styles

apps/web/src/app/vault/components/vault-items/vault-cipher-row.component.html, apps/web/src/app/vault/components/vault-items/vault-cipher-row.component.ts, apps/web/src/app/vault/components/vault-items/vault-items.component.html, apps/web/src/app/vault/components/vault-items/vault-items.component.ts, apps/web/src/app/vault/individual-vault/vault.component.html
This reverts commit 8921230b4f5f33d0948572e47261604a6a3d731e.
Reverting this change as we have some defects and we need this feature on all clients. …
=> Revert "[PM-11200] Move delete item permission to Can Manage (#10890)"

libs/auth/src/angular/anon-layout/anon-layout-wrapper.component.ts
https://bitwarden.atlassian.net/browse/PM-12365
When you use the `AnonLayoutWrapperDataService` to set data in the `AnonLayoutWrapperComponent`, I’m seeing an `ExpressionChangedAfterItHasBeenCheckedError` shown in the console quite often. We should update the wrapper component to fire change detection if the `AnonLayoutWrapperDataService` receives new information. …
=> Auth/PM-12365 - AnonLayoutWrapperComponent - Fix ExpressionChangedAfterItHasBeenCheckedError

libs/components/src/chip-select/chip-select.component.html, libs/components/src/chip-select/chip-select.component.ts
[CL-439](https://bitwarden.atlassian.net/browse/CL-439)
A11y already present:
- Chip announces it is a button for a menu
- Users can navigate menu with up/down arrow keys
- X button on the chip announces as "Remove { label }"
A11y implemented in this PR:
Not being implemented:
- Chip menu and submenus announce the number of items -- we would need to switch our menu component to use list semantic elements, which we should do, but it's out of scope for this. Ticket here: [CL-452](https://bitwarden.atlassian.net/browse/CL-452)
View the stories for the Chip Select in Storybook (specifically the nested items story) to play with the keyboard nav and screenreader support.
- Written new unit and / or …
=> [CL-439] Improve keyboard and visual a11y for chip select

apps/browser/src/_locales/en/messages.json, libs/tools/send/send-ui/src/send-form/components/options/send-options.component.html, libs/tools/send/send-ui/src/send-form/components/options/send-options.component.ts, libs/tools/send/send-ui/src/send-form/components/send-details/base-send-details.component.ts, libs/tools/send/send-ui/src/send-form/components/send-details/send-details.component.html, libs/tools/send/send-ui/src/send-form/components/send-details/send-details.component.ts, libs/tools/send/send-ui/src/send-form/components/send-details/send-file-details.component.ts, libs/tools/send/send-ui/src/send-form/components/send-details/send-text-details.component.html, libs/tools/send/send-ui/src/send-form/components/send-details/send-text-details.component.ts, libs/tools/send/send-ui/src/send-form/send-form-container.ts
https://bitwarden.atlassian.net/browse/PM-11904
This PR adds the new send options form. …
=> [PM-11904] - send options form

apps/web/src/app/vault/org-vault/vault-header/vault-header.component.ts
[AC-2617](https://bitwarden.atlassian.net/browse/AC-2617)
When switching between a page to collections in org vault (e.g. settings > Collections), if the users internet is slow to load the org data, "undefined" will show in the header until org is loaded. 
Added placeholder text of "Collections" while loading
https://github.com/user-attachments/assets/c698b785-60e1-4e76-8eda-b28899bf18b5 …
=> [AC-2617] Loading "Collections" Text on slow load of Org Header

libs/vault/src/cipher-form/components/custom-fields/add-edit-custom-field-dialog/add-edit-custom-field-dialog.component.html
[PM-12052](https://bitwarden.atlassian.net/browse/PM-12052)
- The delete button for custom fields doesn't show a border on hover because of an applied `border-0` class.
- This must have been me trying to match the extension refresh designs. Removing the border class here, on the `ps/extension-refresh` branch the component displays as it should. 
Same change, but on `ps/extension-refresh` showing the hover state:
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more …
=> [PM-12052] Remove border styles from custom field delete

libs/components/src/chip-select/chip-select.component.html, libs/components/src/chip-select/chip-select.component.ts, libs/components/src/chip-select/chip-select.stories.ts
[CL-451](https://bitwarden.atlassian.net/browse/CL-451)
This PR adds the option to render the chip select as a full width variant, meaning it will stretch to fill its container.
See Storybook.
- 🤔 …
=> [CL-451] Add option for full width chip select

apps/web/src/app/billing/organizations/change-plan-dialog.component.html, apps/web/src/app/billing/organizations/change-plan-dialog.component.ts, apps/web/src/app/billing/organizations/organization-subscription-cloud.component.ts
https://bitwarden.atlassian.net/browse/AC-3052
https://bitwarden.atlassian.net/browse/AC-3053
https://bitwarden.atlassian.net/browse/AC-3051 …
=> [AC-3052] [Defect] Payment method section is blank when upgrading Teams SM trial initiated org paid with Bank Account

apps/web/src/app/billing/organizations/organization-plans.component.html
https://bitwarden.atlassian.net/browse/PM-11438
This PR adds the appropriate padding on the input button for the new organization license field.
This was previously attempted in https://github.com/bitwarden/clients/pull/10982 but the appropriate commit didn't make it in.
|Before|After|
---|---
|
- 📝 …
=> [PM-11438] - Add padding to new org input

apps/browser/src/autofill/popup/settings/autofill.component.html
PM-12359
> In the autofill settings page, the “Autofill shortcut” section shows “Manage shortcuts” text as larger, this makes the hierarchy of the page a bit funky. 
This PR fixes that
| --- | --- |
| ![section-before](https://github.com/user-attachments/assets/cd985016-0164-49bc-b39a-11e6ef1d0390) | ![section-after](https://github.com/user-attachments/assets/483d414f-fd95-43ef-a17d-37e7e44ed451) |
- ❌ (`:x:`) or ⚠️ (`:warning:`) for …
=> [PM-12359] Fix typography of change shortcut section text

apps/browser/src/autofill/popup/settings/autofill.component.html, apps/browser/src/autofill/popup/settings/excluded-domains.component.html, apps/browser/src/autofill/popup/settings/notifications.component.html
PM-12360
Remove extra padding from extension popup view containers for autofill settings, notification settings, and excluded domains settings
Note, changes are behind the browser refresh feature flag
| --- | --- |
| ![autofill-before](https://github.com/user-attachments/assets/7c372c1c-6829-4113-85f6-6c82845081b8) | ![autofill-after](https://github.com/user-attachments/assets/802de26e-9df2-45fc-ace7-53a1a7f68ec4) |
| ![notifications-before](https://github.com/user-attachments/assets/c8054662-9f6c-4e96-afe7-91dfcd446b57) | ![notifications-after](https://github.com/user-attachments/assets/6cd65fdb-a701-4790-9d70-4f701311a133) |
| ![excluded-before](https://github.com/user-attachments/assets/da466c33-723a-41ec-a454-835b9cafcd07) | …
=> [PM-12360] Remove container padding for popup views

libs/components/src/form-field/form-field.component.html
[PM-12070](https://bitwarden.atlassian.net/browse/PM-12070)
Using the `disableReadOnlyBorder` attribute of the form field causes a shift when the field is focused in the extension but **not** in Storybook.
I'm kind of dumbfounded by this one, but I'll retrace my steps for the history books. Having `ngClass` and two conditionals within it with the same class (`tw-border-b-2`) is behaving differently in storybook versus the extension.
My hypothesis is that tailwind is recognizing that `tw-border-b-2` is defined in both and is filtering one of them out because it isn't present in the class name. To support this, if you change one of the `tw-border-b-2` to be a different numeric value: `tw-border-b-3` then it will be present in the class name as expected.
I can't find any root cause for this …
=> [PM-12070] FormField readonly shift

libs/components/src/link/link.directive.ts, libs/components/src/link/link.mdx, libs/components/src/link/link.stories.ts
[CL-275](https://bitwarden.atlassian.net/browse/CL-275)
This PR updates the styles for the Link component to match the new extension refresh spec. …
=> [CL-275] Update link styles

apps/browser/src/background/main.background.ts, apps/browser/src/platform/services/browser-local-storage.service.ts, apps/browser/src/popup/services/services.module.ts
https://bitwarden.atlassian.net/browse/PM-12424
Add retries to our `get` operation on `chrome.storage.local`. Even will completely empty state `chrome.storage.local.get` should return an `{}` empty object store, so if it was null we shouldn't treat that as a `null` value that we have stored. We should treat it like an error. This is a similar workaround (EFForg/privacybadger#2980) privacy badger has implemented. …
=> [PM-12424] Add Retries to `get`

apps/web/src/app/vault/org-vault/vault.component.ts
[PM-12528](https://bitwarden.atlassian.net/browse/PM-12528)
Make `allCollectionsWithoutUnassigned$` depend on the `refresh$` subject so that any emissions from `refresh$` force the `allCollectionsWithoutUnassigned$` to refetch collections from the API. 
Additionally, clean up the `allCollectionsWithoutUnassigned$` observable as it no longer needs to "marry" sync data with the collections from API. The API now includes permission details in the response.
Some background: #11092 added a new subscription to the `allCollectionsWithoutUnassigned$` observable in order to access collections when the route parameters updated. This had the unintended side effect of keeping the subscription alive which never allowed the `refCount` of the `shareReplay` to drop to 0 which would clear the list of …
=> [PM-12528] AC Fix Collection Refresh

apps/browser/src/_locales/en/messages.json, apps/browser/src/tools/popup/send-v2/add-edit/send-add-edit.component.html, apps/browser/src/tools/popup/send-v2/add-edit/send-add-edit.component.ts, libs/tools/send/send-ui/src/send-list-items-container/send-list-items-container.component.ts
https://bitwarden.atlassian.net/browse/PM-12505
This PR adds the delete button to the footer of the edit send page.
https://github.com/user-attachments/assets/6d1e657e-7816-4564-b5d5-58311b2c92dc
- 🤔 …
=> [PM-12505] - add delete send button to footer

libs/tools/send/send-ui/src/send-form/components/options/send-options.component.ts, libs/tools/send/send-ui/src/send-form/components/send-form.component.ts
https://bitwarden.atlassian.net/browse/PM-12562
https://bitwarden.atlassian.net/browse/PM-12567
This PR fixes the password input so that it shows as blank instead of the encrypted password hash when editing a send.
It also ensures the password isn't send to the api if it's an empty string or undefined.
- 📝 …
=> [PM-12567][PM-12562] - fix send password input

apps/desktop/src/platform/services/ssh-agent.service.ts
Just some suggested changes to https://github.com/bitwarden/clients/pull/10293 …
=> SSH agent rxjs tweaks

apps/web/src/app/billing/organizations/organization-plans.component.ts
https://bitwarden.atlassian.net/browse/PM-12326
Since the generated payment tokens for the legacy `payment.component` and the `payment-v2.component` are tied to different Stripe entities (Payment Methods vs. Sources), I need to use the newer `PUT /organizations/{id}/billing/payment-method` endpoint to update the organization's payment method rather than using the existing endpoint that processes bank account sources.
https://github.com/user-attachments/assets/870ab45a-e573-4cc1-be4b-b1e374f61f1c
- …
=> [PM-12326] Fix free organization bank account upgrade after Stripe sources deprecation

apps/web/src/app/vault/org-vault/vault.component.ts
[PM-12586](https://bitwarden.atlassian.net/browse/PM-12586)
Make `allCiphers$` depend on the `refresh$` subject to force `allCiphers$` to refetch ciphers from the API. 
https://github.com/user-attachments/assets/f0b5b4c6-b9d1-4172-8828-1f37d5568615 …
=> [PM-12586] Admin Console - New items created cannot be viewed or edited until refreshing page

apps/web/src/app/vault/org-vault/vault.component.ts
[PM-12609](https://bitwarden.atlassian.net/browse/PM-12609)
Use a `shareReplay` for the `allCiphers$` observable on the AC Collections tab to avoid repeated API calls to fetch ciphers. …
=> [PM-12609] Use shareReplay for allCiphers$ observable

apps/browser/src/platform/popup/layout/popup-layout.stories.ts, apps/browser/src/platform/popup/layout/popup-tab-navigation.component.ts, apps/browser/src/tools/popup/send-v2/send-v2.component.html, apps/browser/src/tools/popup/send-v2/send-v2.component.spec.ts, apps/browser/src/tools/popup/send-v2/send-v2.component.ts, libs/angular/src/utils/extension-refresh-swap.ts
https://bitwarden.atlassian.net/browse/PM-12504
This PR implements the following requirements to the send list page and app tab nav for when sends are disabled:
1. remove the create send button
2. display callout
3. remove sends from tab if user has no sends
|With existing send|Without existing send|
---|---
|![Screenshot 2024-09-20 at 3 51 59 PM](https://github.com/user-attachments/assets/a36e1738-ebd2-458e-82b3-9fef504b6c5a)|![Screenshot 2024-09-20 at 3 35 02 PM](https://github.com/user-attachments/assets/3df34540-b071-49b9-be0f-f936107add01)| …
=> [PM-12504] - hide create send button and send tab when sends are disabled

apps/browser/src/tools/popup/settings/about-page/more-from-bitwarden-page-v2.component.ts, libs/common/src/admin-console/abstractions/organization/organization.service.abstraction.ts, libs/common/src/admin-console/services/organization/organization.service.ts
https://bitwarden.atlassian.net/browse/PM-12395
This PR fixes an issue where the "Free Bitwarden Families" button was showing in the browser extension for enterprise users even when it wasn't available.
- …
=> [PM-12395] - hide free bitwarden families button when not available

apps/browser/src/platform/popup/layout/popup-layout.stories.ts, libs/components/src/section/section.component.ts
[CL-455](https://bitwarden.atlassian.net/browse/CL-455)
The section has a breakpoint for applying more bottom margin at larger screen sizes. This PR conditionally applies that breakpoint so that it does not affect sections within dialogs or sections within the browser extension. At this time, design has no expectation that we would want to support wide views of the extension with the larger margin.
Check Storybook for behavior:
- Section story will show the increased bottom margin at large screen sizes, and less margin at small screen sizes
- Dialog story "With Cards" shows sections being used with the small margin
- Popup layout "Popup Page" story shows a section being used with the small margin
- …
=> [CL-455] Do not use responsive margin for sections in dialogs or extension

libs/angular/src/admin-console/components/collections.component.ts
[PM-12622](https://bitwarden.atlassian.net/browse/PM-12622)
When selecting collections for assignment, ensure we check that `readOnly` is falsy, not only `== null`. 
#11207 cleaned up the collections observable in the org vault which was originally setting `readOnly` to `null` via the sync'd collections (which implied `false`). Now that its being properly set to `false`, using `== null` caused the collection dialog to believe every collection was readonly and cleared them all.
https://github.com/user-attachments/assets/8770c088-338b-4262-a515-2b884781a648
- Used …
=> [PM-12622] Check that readOnly is falsy not only null

apps/desktop/src/app/accounts/settings.component.html, apps/desktop/src/locales/en/messages.json
https://bitwarden.atlassian.net/browse/PM-3912
Rename the description of the browser integration to reflect the fact that it is not used in safari. …
=> [PM-3912] Rename biometric integration description to exclude safari

libs/components/src/chip-select/chip-select.component.ts
[CL-459](https://bitwarden.atlassian.net/browse/CL-459)
This PR ensures that the chip select has the following behavior:
https://github.com/user-attachments/assets/4a9f8661-ed3c-472f-93de-c8d1d3b2af2d
- 🤔 …
=> [CL-459] Fix chip behavior when opening menu while item is selected

apps/web/src/app/vault/org-vault/vault.component.ts
[PM-12678](https://bitwarden.atlassian.net/browse/PM-12678)
I was not able to replicate with the flow shown in the ticket description. However I was able to consistently replicate the bug with unassigned items. 
Updated the org vault firstSetup subscription to limit unnecessary calls from `refresh$` on `allCiphers` and `allCollections` 
NOTE: The screen recording below will show the `model-backdrop` element is no longer called. It will also show the unassigned item as `readOnly` on the next opening, that is a separate bug not related to this modal overlay. That bug will be addressed here: https://bitwarden.atlassian.net/browse/PM-10378
https://github.com/user-attachments/assets/17a02c34-a9cc-4034-81f1-f3c28365e522
- All formatters and local linters …
=> [PM-12678] After Editing An Item Can No Longer Click On Vault Page

apps/web/src/app/billing/organizations/change-plan-dialog.component.html
https://bitwarden.atlassian.net/browse/AC-3071
Service account line showing as $12 /month …
=> [AC-3071][Defect] SM Trial org - Service Accounts line item in the Total section displays per month rather than per year for Annual plan

libs/tools/send/send-ui/src/send-form/components/options/send-options.component.html
https://bitwarden.atlassian.net/browse/PM-12721
This PR adds a copy button to the send options password field …
=> [PM-12721] - add copy button to send options password field

apps/browser/src/vault/popup/components/vault-v2/attachments/open-attachments/open-attachments.component.html, apps/web/src/app/vault/individual-vault/add-edit-v2.component.html, libs/components/src/item/item-content.component.html, libs/components/src/item/item.mdx, libs/components/src/item/item.stories.ts
[CL-458](https://bitwarden.atlassian.net/browse/CL-458)
This PR vertically centers the content of the `default` slot of the `bit-item-content` component so that badges and text line up vertically. (Note that the badge looks a bit off here on `main` but will look correct once the extension refresh feature branch is merged in.) This PR also moves the badge outside of the truncation of the default content to align better with UI expectations, by introducing a new content slot. The two usages of `bit-item-content` with badges have been updated to use the new slot.
- Used …
=> [CL-458] Exclude badges from truncation and vertically center content

libs/common/src/autofill/utils.ts
=> [PM-12982] Bugfix - Fix incorrect handling of the first day of the next month is isCardExpired

apps/browser/src/platform/popup/layout/popup-page.component.html, apps/browser/src/popup/scss/tailwind.css, apps/browser/src/vault/popup/components/vault/vault-v2.component.html
[CL-488](https://bitwarden.atlassian.net/browse/CL-448)
Migrate the globally applied scrollbar styles to a custom tailwind class. That way it can be applied selectively to specific elements. 
- In this case the popup page and the `vault-v2`. The `vault-v2` component uses the popup page but has it's own scroll container. 
- `tw-styled-scrollbar` isn't very creative but is unique and will probably never be added to tailwind
- This could have also been a plugin but I opted to stay in the CSS realm. I can go either way!
|Vault Items| Generic Popup Page | Select dropdown with browser default scrollbar|
|-|-|-|
|<img width="379" alt="Screenshot 2024-09-25 at 2 13 50 PM" src="https://github.com/user-attachments/assets/a0fb4a81-9679-4add-9651-5c23dbd8e295">|<img width="387" alt="Screenshot …
=> [CL-448] Selectively apply styled scrollbar

apps/browser/src/tools/popup/send-v2/send-v2.component.html, libs/tools/send/send-ui/src/new-send-dropdown/new-send-dropdown.component.html, libs/tools/send/send-ui/src/new-send-dropdown/new-send-dropdown.component.ts
https://bitwarden.atlassian.net/browse/PM-12732
This PR fixes the create send button shown in the main window when no sends are active. …
=> [PM-12732] - fix new send button

apps/browser/src/platform/browser/browser-api.register-content-scripts-polyfill.ts
Tweaks code to compile on TS 5.3. @cagonzalezcs I believe you added this code, could you take a look that it still does what it's supposed to?
Tip: You can play around with the typings here [TypeScript Playground](https://www.typescriptlang.org/play/?ts=5.3.3#code/CYUwxgNghgTiAEA3W8wAsYHsC2IBc8UAdgJ4DcAUBfPAGYCuRYALgJaZHwByIAzsyGAAFLAA8SAHgAq8EKIFFgveJgBGAK3DMAfAApmsAOYhmBKQEoz8AN7Ua8OM3oxOREAHd4IzOP1GTADQ2dvbwxsx+MOFBAA5YMebBoaFgHPzwcZgxIDDMJABqUBD0CAC88AZRJgDamTGEygDWICSYtPBSALqUIcms7boAhHU5eYXFIIm2ycmOzkSUMzQAvlRL8P3w+iTZbRnxowVFJfClZ-AARGqaLBdTvTNzLtx8AsJiknm77SO5RxN6X5jY6TRZLVYPeybbbffZZQ7jE6Dc4XBhMNgcO5JdYOEzzOHZP6IkBgmYQ9ZPTi6AB0tKM9FwRGYvAA+gRiCRqp1EqVtJDQm5PN5sKxeCBdLo4LxMBBECAgnAbswedpsTiCQiQTS6VEGSAmaygpK+PQIKZCKQVWr1RsBugsLhqTBGGxHdB+ABRGBYGD3G2zEBK3SC+Ben26e04EBOl2sN1QT3ezAwam …
=> [PM-11780] Resolve TypeScript 5.3 compile error

apps/web/src/app/billing/individual/user-subscription.component.html, apps/web/src/app/billing/individual/user-subscription.component.ts
https://bitwarden.atlassian.net/browse/PM-7452
As part of this [server PR](https://github.com/bitwarden/server/pull/4835), premium users who choose PayPal to create their subscription will have an incomplete subscription by default until the `invoice.created` webhook handler has a chance to charge their PayPal account. This change just ensures they still their subscription as active while we set an arbitrary 15 seconds for that process to take place.
https://github.com/user-attachments/assets/320fae15-c44b-4f0d-b927-224cc5c9d04c …
=> [PM-7452] Show incomplete premium subscription as active if created less than 15 seconds ago

apps/browser/src/platform/popup/layout/popup-tab-navigation.component.html
https://bitwarden.atlassian.net/browse/PM-12990
This PR fixes the alignment for the footer buttons to allow for differing number of nav elements.
**Note** - the elements flow as expected without this fix with the web inspector opened which is why it made it through the first time. If you wish to test before and after behavior locally ensure that the inspector is not opened beforehand.
|Before|After|
---|---
|![Screenshot 2024-09-30 at 3 31 17 PM](https://github.com/user-attachments/assets/bb63989c-ad6b-4a3b-867f-1570fba887d2)|![Screenshot 2024-09-30 at 3 30 51 PM](https://github.com/user-attachments/assets/b1a7a502-e397-4778-8c32-0c90ef627487)| …
=> [PM-12990]- center align footer buttons

apps/browser/src/vault/popup/components/vault-v2/vault-list-items-container/vault-list-items-container.component.html
[PM-12718](https://bitwarden.atlassian.net/browse/PM-12718)
Vault items weren't keyboard focusable because they were an anchor tag without a `href`
- Refactored the element to be a button. This feels fine from an accessibility standpoint as the button could navigate _or_ display an action (password reprompt).
- The focus state is `outline` which doesn't display within the layout of the element. This caused the outline to be cut off by the container. I added some CSS to alter the `overflow` and `contain` properties of `cdk-virtual-scroll-viewport` element so that the outline can be shown via overflow. 
|Chrome|FireFox|Safari|
|-|-|-|
|<video src="https://github.com/user-attachments/assets/56293d11-0a71-4828-a7dc-ca295b193a4b"/>|<video …
=> [PM-12718] Vault item - keyboard focus

apps/web/src/app/billing/organizations/organization-subscription-selfhost.component.html
[PM-11606](https://bitwarden.atlassian.net/browse/PM-11606)
When selecting the "automatic sync" radio button, the "manual upload" button was rendering inline to the two buttons below the "automatic sync" radio button. There's also some spacing updates here to give some breathing room. 
| automatic sync selected | manual upload selected |
| <img width="1628" alt="Screenshot 2024-09-27 at 10 17 02 AM" src="https://github.com/user-attachments/assets/f57b1b52-e9b2-4baf-b273-af2f8e7d9f8d"> | <img width="1629" alt="Screenshot 2024-09-27 at 10 17 23 AM" src="https://github.com/user-attachments/assets/003bdb21-bc4f-4e2b-b3cc-eef3877f495f"> |
- Written new unit and / or integration tests …
=> PM-11606 | self host billing page radio buttons fix
