libs/common/src/state-migrations/migration-helper.ts
```
```
Add support for removing data using the migration helper.
=> Add support for removing values in migration helper

libs/components/src/index.ts, libs/components/src/section/index.ts, libs/components/src/section/section.component.ts, libs/components/src/section/section.stories.ts
```
```
Adds a `bit-section` component for more consistent page layouts.
See storybook
=> [CL-169] add section component

apps/browser/src/background/main.background.ts, apps/browser/src/popup/services/services.module.ts
```
```
fix `main` attempt # 2
=> Add key generation service to deps

apps/web/src/app/admin-console/organizations/layouts/organization-layout.component.html, apps/web/src/app/layouts/product-switcher/product-switcher-content.component.ts, apps/web/src/app/layouts/user-layout.component.html, apps/web/src/locales/en/messages.json, bitwarden_license/bit-web/src/app/admin-console/providers/providers-layout.component.html
```
```
Fix some minor design issues that were reported during QA that was put on hold while we merged the main branch.
- Fix missing a11y attributes for new vertical nav logo links
- Fix incorrect order of products in product switcher
- Fix casing of Collections nav item for organizations with FC enabled
=> [PM-6397] [AC-2141] [PM-6449] VVR Design Follow Up Fixes

libs/angular/src/tools/send/add-edit.component.ts
```
```
In some cases the lack of validation of the checkbox state was leading to a repetitive loop turning worsening the performance.
- **send/add-edit.component.ts:** Added validation to verify `hideEmail` checkbox state on subscriber
=> [PM-6401]Checking if hideEmail control is enabled before trying to deactivate on Sends

libs/common/src/platform/state/implementations/default-active-user-state.spec.ts
```
```
This test is occasionally failing, extending this time should make it a bit more resilient to running in the CI pipeline.
Examples:
https://github.com/bitwarden/clients/actions/runs/8024238343/job/21922378973#step:8:1447
https://github.com/bitwarden/clients/actions/runs/8023608096/job/21920403547#step:8:1446
- **libs/common/src/platform/state/implementations/default-active-user-state.spec.ts:** Longer delay
- Ensure that all UI additions follow [WCAG AA requirements](https://contributing.bitwarden.com/contributing/accessibility/ …
=> Extend Cleanup Delay

libs/auth/src/common/services/auth-request/auth-request.service.spec.ts, libs/auth/src/common/services/auth-request/auth-request.service.ts
```
```
Accidentally used `authRequestResponse.key` instead of `authRequestResponse.publicKey` in #8056, breaking auth requests
=> [PM-5499] Use public key for approving auth requests

libs/common/src/state-migrations/migrations/11-move-org-keys-to-state-providers.spec.ts, libs/common/src/state-migrations/migrations/13-move-provider-keys-to-state-providers.spec.ts, libs/common/src/state-migrations/migrations/18-move-autofill-settings-to-state-providers.spec.ts, libs/common/src/state-migrations/migrations/24-move-sm-onboarding-key-to-state-providers.spec.ts, libs/common/src/state-migrations/migrations/25-move-clear-clipboard-to-autofill-settings-state-provider.spec.ts, libs/common/src/state-migrations/migrations/26-move-badge-settings-to-state-providers.spec.ts
- Bug fix
Fix migration rollbacks
=> Bug - Fix migration rollbacks

apps/desktop/src/app/services/services.module.ts
```
```
`SystemService` expects the following services, this fixes the desktop DI to supply the correct services.
https://github.com/bitwarden/clients/blob/668980ad38b6cab29ed2f8d86c9028d4aad7aec0/libs/common/src/platform/services/system.service.ts#L20-L25
This likely would have caused issues around process reload on desktop as well. 
Also fixes PM-6520
- Fix DI
=> [PM-6526] Fix `SystemService` DI

apps/browser/package.json, apps/browser/src/manifest.json, apps/browser/src/manifest.v3.json, apps/cli/package.json, apps/desktop/package.json, apps/desktop/src/package-lock.json, apps/desktop/src/package.json, package-lock.json
```
```
This PR updates the `Browser`, `CLI`, and `Desktop` applications to the proper versions for the upcoming release.
=> DEVOPS-1841 - Change versions to proper values

.github/workflows/build-web.yml
```
```
Extends the QA functionality of a Git hash to all internal builds for non-production environments and excluding self-host.
- **.github/workflows/build-web.yml:**
- Extend the existing matrix with a new key called `git_metadata`, setting this to a value of `true` results in triggering the step to add the metadata to `version.json`. By using a matrix key here, we can add/remove where needed with simple updates.
- Updated the name of the step to be more descriptive.
Examples of changes, reflected in `version.json`.
EUPRD build:
EUQA build: …
=> [DEVOPS-1796] - Add git hash to all lower environment builds

apps/browser/src/popup/services/services.module.ts
```
```
We can't grab background pages in MV3, we need to migrate off of this.
=> Deprecate getBgService

apps/web/src/scss/base.scss, apps/web/src/scss/tailwind.css, libs/components/src/tw-theme.css
```
```
Select options will not position themselves properly if the body is not `position: relative`. 
- add `relative` to `body`
- remove vertical scrollbar hack
https://github.com/bitwarden/clients/assets/17113462/7cabc6e5-59f1-4294-8e4c-f5466b0c536a
=> [CL-203] fix select options position

.github/workflows/release-web.yml
```
```
Update GitHub deployment step to use `Web Vault - US Production Cloud` instead of `Web Vault - Production` due to new naming convention. 
- **release-web.yml:** Update environment parameters
=> DEVOPS-1743 REFACTOR: environment name for Web Vault deployment

apps/browser/src/popup/services/services.module.ts
```
```
Removes AuditService from services module for browser. This service is stateless beyond dependency injection.
=> Remove Unused services

libs/common/src/platform/state/state-definitions.ts
```
```
Propose team as a first pass organization to state definitions
=> Organize State Definitions

.github/workflows/deploy-web.yml
```
```
Make inputs simpler for tired engineers during after-hours deploys
- **.github/workflows/deploy-web.yaml:** Update inputs
- Successful run without force delete: https://github.com/bitwarden/clients/actions/runs/8182565494/job/22374105785#step:10:1
- Successful run with force delete: https://github.com/bitwarden/clients/actions/runs/8182579742/job/22374144283#step:10:1
=> Update Deploy Web Inputs

apps/browser/src/popup/services/services.module.ts
```
```
Removes usage of `getBgService` from browser's service providers. ApiService has no state other than that derived from injected services. The constructor's determination of device type will run once for each api service created, but that's quite small.
=> Create new ApiService for Angular contexts

apps/browser/src/popup/services/services.module.ts
```
```
Remove usage of `getBgService` from browser services.
=> Use new FileUploadService in Angular context

apps/browser/src/popup/services/services.module.ts
```
```
Remove usage of `getBgService`
=> [PM-6647] Create new log service for angular environment

apps/browser/src/popup/services/services.module.ts
Co-authored-by: Justin Baur <justindbaur@users.noreply.github.com>
```
```
=> Remove duplicate provider

apps/browser/src/background/main.background.ts, apps/browser/src/platform/background/service-factories/app-id-service.factory.ts, apps/cli/src/bw.ts, libs/angular/src/services/jslib-services.module.ts
```
```
I missed service initialization in my app id service pr #8229. This fixes that error
=> Fix missed service dependency changes

.github/workflows/version-auto-bump.yml, .github/workflows/version-bump.yml
```
```
This PR updates the `Version Bump` workflow to use the `version-next` action to automatically calculate the next release version if an override version is not specified.
* **.github/workflows/version-bump.yml:** Move around steps and add required logic to make use of the `version-next` action.
- Please check for formatting errors (`dotnet format --verify-no-changes`) (required)
- If making database changes - make sure you also update Entity Framework queries and/or migrations
=> DEVOPS-1840 - Update version bump workflow for automatic version calculation

libs/angular/src/services/jslib-services.module.ts
Missed in https://github.com/bitwarden/clients/pull/8226
=> Bugfix - Fix cipher service factory not using domain settings service correctly

libs/common/spec/fake-state-provider.ts
```
```
I broke linting in #8298, this will fix it.
=> Reorder import

libs/common/src/platform/state/implementations/default-active-user-state.ts
```
```
Improves the ability to determine which state is requesting active users when none exist.
=> Log key when no active user found

apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.ts
```
```
Fix for #8299. The `restrictedAccess$` callback was throwing an error when inviting a new user because `userDetails` is null in that case.
Add this null check - if you're inviting a new user, there are no restrictions on what you can edit.
=> [AC-2309] Fix null error when inviting member

libs/common/src/platform/state/user-key-definition.ts
```
```
Much like #8326, it is very valuable to log the offender when they've incorrectly used the method. This helps diagnose errors in code when code has been minified and the stack trace isn't as helpful.
=> [PM-6853] Add the key definition name in the error for buildKey

apps/desktop/src/main.ts, apps/desktop/src/platform/services/illegal-secure-storage-service.ts, libs/angular/src/services/jslib-services.module.ts
```
```
Fix `TokenService` not using `SecureStorageService` injection token so data wasn't truly being saved in secure storage. 
=> PM-5263  - TokenService needs to actually use secure storage

libs/common/src/platform/state/state-definitions.ts
```
```
The user selected theme should be saved in `localStorage` on web, as it was previously in `StateService`. 
https://github.com/bitwarden/clients/blob/5a12bc0958fa81d5c1f8476e232632376fdb7b12/libs/common/src/platform/services/state.service.ts#L1827-L1831
=> Use `disk-local` for Theme

libs/common/src/platform/abstractions/state.service.ts, libs/common/src/platform/models/domain/global-state.ts, libs/common/src/platform/services/state.service.ts
```
```
I had forgotten to delete state service methods and global state properties for #8122. This removes them.
=> Delete missed state in #8122

.github/workflows/version-bump.yml
```
```
This PR fixes the `set-final-version-output` step so that the `cut_rc` job can properly compare the new version to make sure it has been bumped.
- **.github/workflows/version-bump.yml:** Make sure each `if` statement executes and sets the proper output.
=> Version Bump Workflow - Fix set-final-version-output step

.github/renovate.json
```
```
The NAPI crates need to be updated simultaneously, so let's add a renovate group to do it for us
=> Update renovate to group napi packages

apps/web/src/app/vault/individual-vault/vault-onboarding/vault-onboarding.component.ts
```
- [ X ] New feature development
```
=> [PM-6927] update date for onboarding component to release

libs/common/src/auth/services/user-verification/user-verification.service.ts
```
```
Accidentally removed [here](https://github.com/bitwarden/clients/commit/2111b37c329cb21ba5ad2ce231e5134129d75d5e#diff-4c0073b6d32735757ba5af2c8236caf08d0370c17ddf419218e855f3febbe4be)
Will need to be cherry picked to `rc`
=> add back call to verify by PIN

apps/browser/src/tools/popup/settings/export.component.ts, apps/desktop/src/app/tools/export/export.component.ts, apps/web/src/app/tools/vault-export/export.component.ts, libs/tools/export/vault-export/vault-export-ui/src/components/export.component.ts, libs/tools/export/vault-export/vault-export-ui/src/index.ts
```
```
Moving the base ExportComponent out of libs/angular into the tools-owned library/package specific for the vault-export-ui
- **libs/tools/export/vault-export/vault-export-ui/src/components/export.component.ts:** Moved from `@bitwarden/angular`, 
- **libs/tools/export/vault-export/vault-export-ui/src/index.ts:** Export from @bitwarden/vault-export-ui
- **apps/browser/src/tools/popup/settings/export.component.ts:** 
- **apps/desktop/src/app/tools/export/export.component.ts:**
- **apps/web/src/app/tools/vault-export/export.component.ts:**
- Fix imports on browser, desktop and web …
=> [PM-7135] Move export.component from libs/angular to @bitwarden/vault-export-ui

libs/auth/src/common/login-strategies/password-login.strategy.ts, libs/auth/src/common/services/login-strategies/login-strategy.service.ts
```
```
Was returning local version of master key hash from login strategies. We need server version for authentication with 2fa
=> [PM-7130] Return correct master password hash from login strategies

libs/auth/src/common/login-strategies/password-login.strategy.ts
```
```
During login strategy refactor, I missed setting the captcha bypass token on the actual 2fa token request. 
=> [PM-7073] Send captcha bypass token on 2fa token request

apps/browser/src/auth/popup/login-via-auth-request.component.ts, apps/desktop/src/auth/login/login-via-auth-request.component.ts, apps/web/src/app/auth/login/login-via-auth-request.component.ts, libs/angular/src/auth/components/login-via-auth-request.component.ts, libs/angular/src/services/jslib-services.module.ts, libs/auth/src/common/abstractions/auth-request.service.abstraction.ts, libs/auth/src/common/abstractions/login-strategy.service.ts, libs/auth/src/common/services/auth-request/auth-request.service.ts, libs/auth/src/common/services/login-strategies/login-strategy.service.ts, libs/common/src/auth/abstractions/anonymous-hub.service.ts, libs/common/src/auth/services/anonymous-hub.service.ts
- cleanup hanging promises
```
```
moves the auth request notification to auth request service. Also cleans up some hanging promises.
=> [PM-5499] Move auth request notification to service

bitwarden_license/bit-web/src/app/admin-console/organizations/manage/scim.component.ts
```
```
This adds a missing await to resolve [PM-7163](https://bitwarden.atlassian.net/browse/PM-7163?atlOrigin=eyJpIjoiMmFlOGExMTMzNDI2NGJhNWJiYjZjZjJmZWExOTg0ZTIiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
[PM-7163]: https://bitwarden.atlassian.net/browse/PM-7163?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Await `this.getScimEndpointUrl()`

libs/common/src/platform/state/user-state.ts
```
```
adds clarification to when `null` is emitted from state providers, and when there is no emit.
=> add clarification around null in state provider

.checkmarx/config.yml
```
```
Update checkmarx SAST preset to one we can tweak as needed.
=> Update SAST preset to query set

libs/angular/src/services/jslib-services.module.ts
=> Fix TokenService dependency

apps/web/src/app/billing/organizations/organization-subscription-cloud.component.html
```
```
One liner that only shows the button to reinstate a subscription pending cancelation if the user is able to edit the subscription.
=> [AC-1933] Don't let users who can't edit a subscription reinstate it

libs/common/src/billing/models/billing-keys.state.ts, libs/common/src/billing/services/account/billing-account-profile-state.service.ts
```
```
uses `UserKeyDefintion` to specify automatic clear events for billing data.
=> Use user definition clearOn events for billing

apps/web/src/app/admin-console/organizations/layouts/organization-layout.component.html, apps/web/src/app/admin-console/organizations/layouts/organization-layout.component.ts, apps/web/src/app/layouts/toggle-width.component.ts, apps/web/src/app/layouts/user-layout.component.html, apps/web/src/app/layouts/user-layout.component.ts, bitwarden_license/bit-web/src/app/admin-console/providers/providers-layout.component.html, bitwarden_license/bit-web/src/app/admin-console/providers/providers-layout.component.ts, bitwarden_license/bit-web/src/app/secrets-manager/layout/layout.module.ts, bitwarden_license/bit-web/src/app/secrets-manager/layout/navigation.component.html
```
```
Add a dev tool for toggling the web vault width. This allows developers and designers to experiment with how the vault currently behaves with responsiveness and ensure new functionality looks good.
https://github.com/bitwarden/clients/assets/137855/dedabf12-97dc-4be6-8c0f-b625b222d124
=> [PM-7057] Add dev tool for toggling width in web vault

bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/projects/service-account-projects.component.html
```
```
The purpose of this PR is to fix the empty message to use the correct i18n key.
=> [SM-1159] Use correct i18n key

libs/common/src/tools/generator/state/padded-data-packer.ts
```
```
Unit tests trim vertical pipes when appear in the data packer's JSON data, but electron is not as forgiving. It throws errors in this situation.
Extracted from #8605 because it's needed to fix errors in #8606. 
- **libs/common/src/tools/generator/state/padded-data-packer.ts** fixes the encoding error by trimming the pipes before b64 decoding the result. Also cleans up some variable names.
=> [PM-6819] fix fencepost errors in padded data packer

apps/desktop/electron-builder.json
```
```
Adds instructions to the snap description to enable required permissions.
Related: #8651
=> [PM-7349] add snap description

apps/browser/src/background/main.background.ts
- Bug fix
Fixes a bug in browser where LoginEmailService was used but not instantiated in `main.background.ts`
=> [PM-7363] Instantiate LoginEmailService in Browser (bug fix) 

libs/components/src/tw-theme.css, libs/components/tailwind.config.base.js
```
```
This PR updates the color palette as per the new designs for the extension refresh project. This will be merged into the extension refresh feature branch, and will enable us to begin creating new components and updating existing ones for the new designs.
As of now, we are only touching light and dark theme. Solarized and nord will not be updated as part of the extension refresh work.
- **libs/components/src/tw-theme.css:** Update existing color variables and add new ones
- **libs/components/tailwind.config.base.js:** Add references to new color variables
See Chromatic Storybook checks for links to view the changes.
- If this change requires a **documentation update** - notify the documentation …
=> [CL-245] update to new palette

apps/browser/src/background/main.background.ts
```
```
Prefer running events on the passed in user id, this `userId` will get the active user id if it's not passed in so it's exactly what we want. Desktop already does this with it's logout method.
=> Prefer Passed In UserId

apps/desktop/electron-builder.json
```
```
Decrease snap description character length to reach 128 limit.
Related: https://github.com/bitwarden/clients/pull/8672
=> [PM-7349] Decrease snap description character length to reach 128 limit

libs/components/src/stories/colors.mdx
```
```
This PR adds the new design system colors to the storybook Colors page.
=> [CL-245] Add new color swatches to storybook

apps/web/src/app/admin-console/organizations/create/organization-information.component.html, apps/web/src/app/admin-console/organizations/create/organization-information.component.ts, apps/web/src/app/admin-console/organizations/settings/account.component.html, apps/web/src/app/admin-console/organizations/settings/account.component.ts, apps/web/src/app/billing/organizations/organization-plans.component.ts
```
```
Removed the "business name" fields from the admin console organization info, and the create organization page.
Also updated the create organization page to prefill the logged in user's email into the billing email field
Server PR: https://github.com/bitwarden/server/pull/3970
- **apps\web\src\app\admin-console\organizations\create\organization-information.component.html:** Deleted checkbox to indicate that the org is owned by a business, and the field for the business name
- **apps\web\src\app\admin-console\organizations\create\organization-information.component.ts:** Added ngOnInit to prefill the billing email with the logged in user's email
- **apps\web\src\app\admin-console\organizations\settings\account.component.html:** Removed business name field
- …
=> [AC-2319] remove the owned by business checkbox business name

apps/cli/src/bw.ts
```
```
`masterPasswordService` was never initialized on the `bw.ts` throwing exception on CLI
- **bw.ts:** Initialized `masterPasswordService`
=> [PM-7441] Initializing masterPasswordService on bw.ts

apps/desktop/package.json, apps/desktop/src/package-lock.json, apps/desktop/src/package.json, package-lock.json
I am trying to get a testflight build and accidentally triggered this.
Reverts bitwarden/clients#8751
=> Revert "Bump desktop"

apps/web/src/app/billing/organizations/organization-billing-history-view.component.html
```
```
Migrate the Organization billing history view component to use the component library.
organization-billing-history-view.component.html - changed CSS class to use equivalent tailwind CSS
Before Migration:
After Migration:
=> [PM-5015] org billing history view component migration

apps/browser/src/background/main.background.ts, apps/browser/src/popup/services/services.module.ts
```
```
Changed to `MainBackground` to better facilitate it's use in MV3. 
- **apps/browser/src/background/main.background.ts:** Only create background services in the actual background version of the `MainBackground`. Also only `init` those classes in the true background.
- **apps/browser/src/popup/services/services.module.ts:** Send in value indicating it's being used in the popup.
=> [PM-7138] [PM-7526]Guard Background Only and MV2 Only Actions

libs/common/src/vault/services/cipher.service.ts
```
```
Fix ciphers syncing problem after an add/edit/delete operation on them. 
- **cipher.service.ts:** Add missing value assignment
=> [PM-7533] Add missing value assignment

apps/browser/src/_locales/en/messages.json, apps/browser/store/locales/en/copy.resx, apps/browser/store/windows/AppxManifest.xml
```
```
- Update browser's display name to `Bitwarden Password Manager`
- Update browser's summary
- Update browser's long description
- **apps/browser/store/locales/en/copy.resx:** Update name, summary, and long description
- **apps/browser/store/windows/AppxManifest.xml:** Update name and summary
- **apps/browser/src/_locales/en/messages.json:** Update name and summary
=> Browser copy updates for Marketing

apps/web/src/app/billing/organizations/organization-plans.component.ts
=> [PM-7571] Removed 2023 plans for view for grandfathered 2020 providers

apps/browser/src/manifest.v3.json
```
```
Fix TOTP site read in MV3.
Discussions on this permission available on original PR, #5985
=> Fix TOTP scanner in MV3

apps/browser/store/locales/en/copy.resx
```
```
Followup from https://github.com/bitwarden/clients/pull/8822 with additional browser copy updates to include more accurate numbers and credit
- **apps/browser/store/locales/en/copy.resx:** Copy updates
=> Browser Copy Updates: number of translations and translator credit

.github/workflows/deploy-web.yml
```
```
https://bitwarden.atlassian.net/jira/software/c/projects/DEVOPS/boards/127?quickFilter=244&selectedIssue=DEVOPS-1919
Accurately show the commit SHA that will be used, linked from the artifact deployed. This leverages the new feature here in https://github.com/bitwarden/gh-actions/pull/276
In this workflow, there are three ways to deploy and artifact, this intends to handle each scenario and will retrieve the commit SHA that was used when the artifact was created.
1. From the latest artifact on main.
- Example run: https://github.com/bitwarden/clients/actions/runs/8755091884
3. From a GitHub build workflow ID
- Example run: https://github.com/bitwarden/clients/actions/runs/8754991688/job/24028086605#step:9:4
5. From a newly created build artifact if an artifact isn't found in `1.`. …
=> [DEVOPS-1919] - Slack messages contain the incorrect git commit sha

apps/browser/src/popup/services/services.module.ts
Reverts bitwarden/clients#8843
=> Revert "[PM-7617] Stop CryptoService from using `getBgService`"

libs/angular/src/vault/components/view.component.ts
…efore the sync could complete
```
```
Fixed a race condition between two observables, where the `this.canAccessPremium` flag would sometimes be undefined as the full sync would run before the subscriber to `this.billingAccountProfileStateService.hasPremiumFromAnySource$` had the chance to emit. 
=> [PM-7647] Fixed race condition with has premium state

apps/cli/src/bw.ts
```
```
We forgot to include CLI in the new auto key strategy. Add `UserKeyInitService` to CLI init so we have a user key in memory for decryption operations.
=> [PM-7703] Set auto key on command in cli

apps/browser/src/autofill/services/autofill.service.ts
…essages
```
```
We had multiple message handler content scripts being injected into pages. This resulted in multiple messages being passed to the background page whenever a callback from SSO was sent.
=> [PM-7702] Remove extra content script being injected

apps/browser/src/platform/browser/browser-api.ts, apps/browser/src/platform/services/platform-utils/browser-platform-utils.service.ts, apps/browser/src/popup/settings/about.component.html, apps/browser/src/popup/settings/about.component.ts
```
```
This allows us to put more information in `version_name` and have it more easily findable in app. 
=> Display `version_name` in AboutComponent

bitwarden_license/bit-web/src/app/secrets-manager/integrations/integration-card/integration-card.component.html
```
```
Fix integrations card links not opening in a new page
=> Make integrations links open in a new page

apps/browser/src/platform/state/background-derived-state.provider.ts
```
```
#8937 failed to change both foreground and background bugs. This applies the fix to background as well.
=> Use unique port names for derived states

libs/components/src/form/forms.mdx
```
```
Run `npm run prettier` after #8636.
=> Run `npm run prettier` & Fix `main` Linter

apps/browser/src/background/main.background.ts, apps/browser/src/platform/background/service-factories/migration-runner.factory.ts, apps/browser/src/popup/services/services.module.ts, apps/cli/src/bw.ts, apps/desktop/src/app/services/services.module.ts, apps/desktop/src/main.ts, apps/web/src/app/core/core.module.ts, apps/web/src/app/platform/web-migration-runner.ts, libs/angular/src/services/injection-tokens.ts, libs/angular/src/services/jslib-services.module.ts, libs/common/src/platform/services/migration-builder.service.spec.ts, libs/common/src/platform/services/migration-runner.spec.ts, libs/common/src/platform/services/migration-runner.ts, libs/common/src/state-migrations/migration-builder.spec.ts, libs/common/src/state-migrations/migration-helper.spec.ts, libs/common/src/state-migrations/migration-helper.ts, libs/common/src/state-migrations/migrator.spec.ts
```
```
Adds a `clientType` property to `MigrationHelper` so that migration writers can have client specific logic if needed. 
=> [PM-7766] Add `clientType` to MigrationHelper

apps/web/src/app/layouts/product-switcher/product-switcher-content.component.html, apps/web/src/app/layouts/product-switcher/product-switcher-content.component.ts
```
```
- Update Admin Console icon
- Force Admin Console text to wrap so it is shown on two lines for both the selected and unselected states
- **product-switcher-content.component.ts:**
- Update icon
- **product-switcher-content.component.html**
- Set max-width and text align so text wraps regardless if it is selected or not
|Before|After|
|------|-----|
|<img width="428" alt="Screenshot 2024-04-29 at 10 24 03 AM" src="https://github.com/bitwarden/clients/assets/125900171/23241036-17fd-4867-aa04-b5349dba471e">|<img width="424" alt="Screenshot 2024-04-29 at 10 22 39 AM" src="https://github.com/bitwarden/clients/assets/125900171/1b7aba95-a822-41d5-9a5e-e8f725726ea0">| …
=> [AC-2140] Swap Admin Console icon

apps/browser/src/popup/services/services.module.ts
```
```
Follow up from https://github.com/bitwarden/clients/pull/8906
as mentioned there, with both services having been migrated to use StateProvider, we should be able to remove them from popup/services.module.
- **Remove usage of getBgService for CipherService -** https://github.com/bitwarden/clients/commit/32e90d35f12d8e63debceb1df530254d0056098c
- With CipherService using StateProviders: https://github.com/bitwarden/clients/pull/8314 - we should no longer need CipherService
- **Remove usage of getBgService for CollectionService -** https://github.com/bitwarden/clients/commit/a7a018bf79d46636c38b9de77b2d89bbeeb620a0
- With CollectionService using StateProviders: https://github.com/bitwarden/clients/pull/7732 - we should no longer need CollectionService
- Please add **unit tests** …
=> [PM-7701] Clean up services module

apps/web/src/app/admin-console/organizations/manage/group-add-edit.component.ts
```
```
Update the Groups modal to match my use of ShareReplay in the Members modal: https://github.com/bitwarden/clients/pull/8796. I didn't catch this when I fixed the Members modal.
=> [AC-2087] Use refCount: true for shareReplay

libs/auth/src/common/login-strategies/auth-request-login.strategy.ts, libs/auth/src/common/login-strategies/login.strategy.spec.ts, libs/auth/src/common/login-strategies/login.strategy.ts, libs/auth/src/common/login-strategies/password-login.strategy.spec.ts, libs/auth/src/common/login-strategies/password-login.strategy.ts, libs/auth/src/common/login-strategies/sso-login.strategy.spec.ts, libs/auth/src/common/login-strategies/sso-login.strategy.ts, libs/auth/src/common/login-strategies/user-api-login.strategy.spec.ts, libs/auth/src/common/login-strategies/user-api-login.strategy.ts, libs/auth/src/common/login-strategies/webauthn-login.strategy.spec.ts, libs/auth/src/common/login-strategies/webauthn-login.strategy.ts, libs/common/src/auth/abstractions/key-connector.service.ts, libs/common/src/auth/models/domain/auth-result.ts, libs/common/src/auth/services/key-connector.service.spec.ts, libs/common/src/auth/services/key-connector.service.ts, libs/common/src/platform/services/crypto.service.ts
```
```
We shouldn't ever be getting the userId from the account service in our login strategies since its derived from the token. This PR requires userIds when setting keys.
=> [PM-6727] Part 1: pass userId in login strategies

libs/common/src/platform/services/crypto.service.ts
```
```
Accidentally introduced a bug in #9030 with the init account validation since we can't access the private key (user state) until the user key has been set.
Heads up: This was a situation where the observable would hang and not return anything to the `firstValueFrom`
=> Fix init account validation

apps/web/src/locales/en/messages.json, bitwarden_license/bit-web/src/app/admin-console/providers/settings/account.component.ts
```
```
Small text updates
Add period to end of modal so it reads, “You must unlink all clients before you can delete [provider name].”
Per [Figma](https://www.figma.com/proto/m8eMk6yeKfOq4AUuyp70ih/Consolidated-Billing?page-id=698%3A10060&type=design&node-id=1309-18496&viewport=-11087%2C521%2C0.25&t=tpHXkqSav41X2FCa-1&scaling=min-zoom&starting-point-node-id=1309%3A18496&show-proto-sidebar=1), change ‘Cancel’ button to ‘Close’ …
=> [AC-2557] Defect - Modal text updates

apps/browser/src/auth/background/service-factories/device-trust-service.factory.ts, apps/browser/src/background/main.background.ts, apps/cli/src/bw.ts, libs/angular/src/auth/components/base-login-decryption-options.component.ts, libs/angular/src/services/jslib-services.module.ts, libs/auth/src/common/login-strategies/sso-login.strategy.ts, libs/common/src/auth/services/device-trust.service.implementation.ts, libs/common/src/auth/services/device-trust.service.spec.ts
```
```
Adds logging to TDE service operations
Two main areas of (minor) complexity in this:
1. adding log service to device trust service
2. removed catch from base decryption options so that errors bubble up and prevent routing
=> [PM-7919] Add more tde logging

apps/browser/config/base.json, apps/browser/config/development.json, apps/browser/src/background/runtime.background.ts, apps/desktop/config/base.json, libs/common/src/platform/misc/flags.ts
- Other
Don't show the welcome window every time the extension is reinstalled when debugging
=> [PM-7662] Suppress welcome window on install when extension is in dev mode

apps/web/src/app/billing/organizations/organization-subscription-cloud.component.html
=> [AC-2558] Provider Admin still sees manage billing options - not the provided image

apps/browser/src/platform/services/browser-state.service.spec.ts
```
```
Fix test after session-sync removal with https://github.com/bitwarden/clients/pull/9024
=> Fix test after session-sync removal

apps/browser/src/popup/app-routing.module.ts, apps/browser/src/popup/app.module.ts, apps/browser/src/vault/popup/components/vault/vault-v2.component.html, apps/browser/src/vault/popup/components/vault/vault-v2.component.ts
```
- [ X ] New feature development
```
Create a new Vault V2 component, add it to `app.routing.module`. Make sure the extension can toggle between the `VaultFilterComponent` and the `VaultV2Component` based on the extension refresh flag
=> [PM-6822] Create new Vault V2 component for extension refresh

apps/browser/src/popup/scss/misc.scss, apps/browser/src/tools/popup/settings/about/about.component.html
```
```
Allows selecting of version numbers in about page in browser. Useful for issue reporting.
=> Allow selecting of version numbers for copy-pasting in issues

apps/browser/src/popup/settings/options.component.html, apps/browser/src/popup/settings/options.component.ts
```
```
Remove settings from options.component which had been moved to notifications.component (https://github.com/bitwarden/clients/pull/8919)
- **apps/browser/src/popup/settings/options.component.html and apps/browser/src/popup/settings/options.component.ts:** Remove options that had been moved with #8919
=> [PM-7740] Remove settings from options.component

apps/web/src/app/billing/organizations/organization-plans.component.ts
```
```
#8448 incorrectly merged and introduced a compiler error [here](https://github.com/bitwarden/clients/pull/8448/files#diff-0f895be23a9593b7a42bcb0b7c5c58ca19baab2fa9a3c035293054380d9e7e15R598-R599) when removing the try/catch block. 
- **apps/web/src/app/billing/organizations/organization-plans.component.ts:** Resolve the error by reverting the line to the prior commit: https://github.com/bitwarden/clients/pull/8709/files#diff-7917b34553b9b86a2aa8f8536db3a9e6bd97487fadc2cdc67496a731f881dc68R106-R107
- Ensure that all UI …
=> fix merge error in PM-5017 #8448

libs/common/src/tools/send/services/send.service.ts
```
```
Fixes a bug that causes sends to null their key during key rotation. This bug occurs due to two factors:
1. Send key rotation decrypted the send key using the rotation key. It should use the original key.
2. Decryption returns `null` when it fails instead of reporting an error.
This change loads the active user's original key from the `CryptoService`. It does so without specifying a `userId` because the crypto service is unaware of the active user's id and introducing the account service would require significant changes to dependency injection. This is too large for a bugfix that needs to move to RC with the quickness.
- **libs/common/src/tools/send/services/send.service.ts**
=> [PM-8028] rotate sends from original key to rotated key

apps/web/src/app/billing/organizations/organization-subscription-cloud.component.ts
```
```
In the prior implementation, we decided if we should show the "manage in provider portal" message and graphic by retrieving the provider from the API, then checking if the provider type was "MSP." This became an issue for users who were not "provider users," meaning that they could not access that endpoint.
This solution sidesteps the need to query the API by simply checking if the user can view the subscription. This works due to the fact that that getter already checks if the organization has a provider, and the user is a provider user. If the user can view but not edit the subscription, then that same getter already checks if the provider type is MSP.
https://github.com/bitwarden/clients/assets/133619638/dc48e975-9b25-4cb2- …
=> [AC-2587] Resolve 404 on Billing Subscription Page

apps/browser/src/background/nativeMessaging.background.ts, apps/desktop/src/platform/services/electron-crypto.service.ts
```
```
This backports PR #9181 into `rc`, see comments in PR for why this doesn't exactly match that PR. This squashed commit from this PR will be used to backport this change into `hotfix-rc-browser` as well. 
=> Backport PR #9181

libs/common/src/admin-console/models/domain/encrypted-organization-key.ts, libs/common/src/platform/services/crypto.service.ts, libs/common/src/platform/services/key-state/org-keys.state.spec.ts, libs/common/src/platform/services/key-state/org-keys.state.ts, libs/common/src/platform/services/key-state/provider-keys.state.spec.ts, libs/common/src/platform/services/key-state/provider-keys.state.ts, libs/common/src/platform/services/key-state/user-key.state.spec.ts, libs/common/src/platform/services/key-state/user-key.state.ts
```
```
This reduces emissions in general due to updates of multiple inputs and removes decryption errors due to partially updated dependencies
=> [PM-8155] Keep crypto derive dependencies in lockstep

apps/desktop/src/main.ts
```
```
Jira: [PM-5501](https://bitwarden.atlassian.net/browse/PM-5501?focusedCommentId=58410)
Remove no longer necessary desktop global default vault timeout values; there are no references to them after the state provider migration. They would be removed in the migration and then incorrectly restored on app restart. 
- **apps/desktop/src/main.ts:** Delete deprecated storage defaults
[PM-5501]: …
=> Auth/PM-5501 - VaultTimeoutSettingsSvc State Provider Migration Desktop Cleanup

apps/browser/src/_locales/bs/messages.json, apps/browser/src/auth/popup/account-switching/account-switcher.component.ts
```
```
PR between 2 test branches to test a Jira automation.
=> Automation test PR

libs/auth/src/angular/anon-layout/anon-layout-wrapper.component.ts
Makes AnonLayoutWrapperComponent data properties optional.
=> [PM-8236] Make data properties optional

apps/web/src/app/admin-console/organizations/policies/disable-send.component.html
```
```
Migrate the Disable Send component to use the component library.
- **disable-send.component.html:** Checkbox component added from library
https://github.com/bitwarden/clients/assets/162679756/c11ccda0-f437-442c-a998-5afef4eda0cf
=> AC-2389 Migrate Disable Send Component

apps/web/src/app/admin-console/organizations/members/components/member-dialog/nested-checkbox.component.html
```
```
Migrate the Nested checkbox component to use the component library.
- **nested-checkbox.component.html:** Converted all checkbox fields to use bit component library.
https://github.com/bitwarden/clients/assets/162679756/00abbfa2-571e-4dd0-9d8d-399496f32c3f
=> AC-2387 Migrate Nested Checkbox Component

.github/workflows/version-auto-bump.yml
```
```
Fix version autobump https://github.com/bitwarden/clients/actions/runs/9180787790/job/25246021962
```bash
could not parse provided JSON: invalid character '\\' looking for beginning of object key string
```
- **version-auto-bump.yml:** Invalid characters by passin in parameters to trigger
=> BRE-40 Fix version-auto-bump.yml trigger parameters

apps/browser/src/autofill/popup/settings/notifications.component.ts, apps/browser/src/popup/app-routing.module.ts, apps/browser/src/popup/app.module.ts
- Other
Originally part of https://github.com/bitwarden/clients/pull/9291, which was closed
=> Papercut - Fix typo

apps/browser/src/background/main.background.ts, apps/cli/src/service-container.ts, apps/desktop/src/app/app.component.ts, apps/web/src/app/app.component.ts, libs/common/src/tools/generator/legacy-password-generation.service.ts
```
```
Fix error thrown when the history is cleared and the account is undefined.
- **libs/common/src/tools/generator/legacy-password-generation.service.ts:** - filter out missing active accounts; return empty dataset if no account becomes available after 1 second.
=> fix clear when account unavailable error

.github/workflows/version-bump.yml
```
```
This PR fixes the version bump commit message and description in the resulting PR.
- **.github/workflows/version-bump.yml:** Update commit message and PR description.
=> BRE-64 - Fix version bump message

apps/browser/src/_locales/en/messages.json, apps/browser/src/popup/app-routing.module.ts, apps/browser/src/tools/popup/settings/about-page/about-page-v2.component.html, apps/browser/src/tools/popup/settings/about-page/about-page-v2.component.ts, apps/browser/src/tools/popup/settings/about-page/about-page.component.html, apps/browser/src/tools/popup/settings/about-page/about-page.component.ts, apps/browser/src/tools/popup/settings/about-page/more-from-bitwarden-page-v2.component.html, apps/browser/src/tools/popup/settings/about-page/more-from-bitwarden-page-v2.component.ts
```
```
Create new about-page and more-from-bitwarden page using `popup-page` & `popup-header` and migrating navigation items to use bit-item
- **Remove button to launch contact form from about-page -** https://github.com/bitwarden/clients/commit/9a668d7e1ccaa2a30507e64e6cc2fc6e56103704
- **Remove button to launch community forums from about-page -** https://github.com/bitwarden/clients/commit/4dfdbfab8b4002a0fefc90cfe71879425e72692f
- **Create about-page-v2 component -** https://github.com/bitwarden/clients/commit/c1407c8b82a047dd74cdd55833437ad15c87cac9
- Copy existing about-page.component
- Add missing imports as page is marked as standalone
- Add popup-page and -header
- Migrate navigation items to use bit-items and bit-item-content
- Route to new page when feature flag enabled
- …
=> [PM-7178] Update about and more-from-bitwarden pages [UI changes]

.github/workflows/version-bump.yml
Jira: https://bitwarden.atlassian.net/browse/BRE-87
Add a new parameter to whether to send a notification for upcoming releases, which must be disabled by default.
Related PR: https://github.com/bitwarden/devops/pull/2329
- ❓ …
=> BRE-87 ADD: Slack notification enable feature and check in version-bump workflow

apps/web/src/locales/en/messages.json
https://bitwarden.atlassian.net/browse/PM-5954
Updated the correct grammar from Addons to Add-ons under the billing tab when a user adds additional storage …
=> Change Addons to Add-ons

apps/web/src/app/tools/vault-export/export.component.ts
https://bitwarden.atlassian.net/browse/PM-8389
With https://github.com/bitwarden/clients/pull/9244 I had moved the submit and user-verification logic into the ExportBaseComponent and accidentally removed the success toast being displayed after vault export. This PR brings the success toast back.
The `platformservice.showToast` is marked as deprecated and should be replaced with `toastService.showToast`, but I wanted to bring this back with as minimal changes as possible. Usage of the new service will be part of https://bitwarden.atlassian.net/browse/PM-6568
- Used …
=> [PM-8389] Fix missing confirmation toast on vault export

apps/browser/src/autofill/background/service_factories/autofill-service.factory.ts, apps/browser/src/autofill/services/autofill.service.spec.ts, apps/browser/src/autofill/services/autofill.service.ts, apps/browser/src/background/main.background.ts, apps/browser/src/popup/services/services.module.ts
…
https://bitwarden.atlassian.net/browse/PM-8447
Hotfix of the changes implemented within https://github.com/bitwarden/clients/pull/9400
This is being done to address required additions to the Autofill Service factory as well as to avoid incorporating conflicting changes from other PRs. …
=> [PM-8447] HOTFIX: Autofill On Load Causes Extension to Hang After Browser Startup

.eslintrc.json, .github/whitelist-capital-letters.txt, apps/browser/tsconfig.json, apps/desktop/tsconfig.json, apps/web/tsconfig.json, bitwarden_license/bit-common/tsconfig.json, bitwarden_license/bit-web/tsconfig.json, libs/shared/tsconfig.libs.json, libs/tools/send/README.md, libs/tools/send/send-ui/jest.config.js, libs/tools/send/send-ui/package.json, libs/tools/send/send-ui/tsconfig.json, libs/tools/send/send-ui/tsconfig.spec.json, tsconfig.eslint.json, tsconfig.json
https://bitwarden.atlassian.net/browse/PM-8448
Create a new library package to contain all Angular components used for Bitwarden Send and which should be shared.
All the changes made are analog to the previous changes to re-use the import and export UI's on all clients.
These changes will not require QA, as they are not in use anywhere. This is just defining the new package and it's structure. …
=> [PM-8448] Create BItwarden Send UI library package

apps/web/src/app/oss-routing.module.ts, apps/web/src/locales/en/messages.json, libs/auth/src/angular/anon-layout/anon-layout-wrapper.component.html, libs/auth/src/angular/anon-layout/anon-layout-wrapper.component.ts, libs/auth/src/angular/anon-layout/anon-layout.component.html, libs/auth/src/angular/anon-layout/anon-layout.component.ts, libs/auth/src/angular/anon-layout/anon-layout.mdx, libs/auth/src/angular/anon-layout/anon-layout.stories.ts
[PM-8368](https://bitwarden.atlassian.net/browse/PM-8368)
Provides a way to add the environment selector to the AnonLayout footer for both Web and Libs (Desktop/Browser) implementations of the environment selector.
- Setting a data property `showReadonlyHostname: true` will show the readonly hostname
- Setting the relevant (web or libs) env selector component in the route `outlet` will show the specified env-selector
- Setting neither of the above will show no environment info at all.
https://www.chromatic.com/review?appId=62a88a6de5b807fa98886113&number=9397&type=linked
- …
=> [PM-8368] AnonLayout Footer Updates

libs/common/src/tools/generator/username/email-forwarders/fastmail-forwarder.ts, libs/common/src/tools/generator/username/forwarders/fastmail.ts
Reverts bitwarden/clients#9127
=> Revert "[PM-8039] Fastmail: Change website default value to empty string."

libs/common/src/tools/generator/username/email-forwarders/fastmail-forwarder.ts, libs/common/src/tools/generator/username/forwarders/fastmail.ts
Reverts bitwarden/clients#9437
=> Unrevert [PM-8039] Fastmail: Change website default value to empty string.

libs/common/src/tools/generator/username/email-forwarders/fastmail-forwarder.ts
N/A
Fix lint failure by running latest prettier.
=> fix lint failure

.github/workflows/build-cli.yml, .github/workflows/build-desktop.yml, .github/workflows/release-desktop-beta.yml
- [Card](https://bitwarden.atlassian.net/browse/BRE-69)
- To upgrade macOS runner from 11 to 13 …
=> [BRE-69] - Upgrade to Macos-13 Runner

babel.config.json
[PM-6788](https://bitwarden.atlassian.net/browse/PM-6788)
Safari v15 will still not load Bitwarden despite the introduction of `@babel/preset-env` in https://github.com/bitwarden/clients/pull/9383. The cause may actually be a bug that is present in Safari v15, rather than a true compat issue, see https://github.com/babel/babel/issues/14289. 
Enabling "bugfixes" in the config for `@babel/preset-env` will fix these sort of issues by transpiling known bugs to non-broken alternatives. See https://babeljs.io/blog/2020/03/16/7.9.0 …
=> [PM-6788] enable bugfixes in babel/preset-env

libs/auth/src/common/abstractions/login-strategy.service.ts, libs/auth/src/common/services/login-strategies/login-strategy.service.ts
Remove extra unused method for auth requests.
- 🎨 …
=> remove extra unused method

.github/workflows/build-cli.yml
Follow up from #9293.
Update the cli build workflow so that it's kicked off whenever there are changes to the bit-cli directory. Currently our updates to the bit-licensed client aren't updating CI builds. …
=> [AC-2482] Add bit-cli directory to cli build workflow

apps/browser/src/_locales/en/messages.json, apps/browser/src/vault/popup/components/vault-v2/vault-list-filters/vault-list-filters.component.html, apps/browser/src/vault/popup/services/vault-popup-list-filters.service.ts
[PM-8594](https://bitwarden.atlassian.net/browse/PM-8594)
- Match designs by having singular verbiage for both collection and type filters.
- Match designs by using singular verbiage for cipher types
|Before|After|
|-------|-----|
|![Screen Shot 2024-06-04 at 16 10 39 PM](https://github.com/bitwarden/clients/assets/125900171/cf2dcf4c-1efb-4a46-819b-a000b9ccf950)|![Screen Shot 2024-06-04 at 16 10 14 PM](https://github.com/bitwarden/clients/assets/125900171/644d7c80-700e-4603-8015-f6119495ea68)|
|![Screen Shot 2024-06-04 at 16 19 20 PM](https://github.com/bitwarden/clients/assets/125900171/6401d2c4-11b1-4a20-8ea1-a0937ae00b8e)|![Screen Shot 2024-06-04 at 16 18 23 PM](https://github.com/bitwarden/clients/assets/125900171/c923dc0e-7fad-4e69-89e3-b14f5ee41a9f)| …
=> [PM-8594] use singular version of the copy for filters

apps/browser/src/_locales/en/messages.json, apps/browser/src/vault/popup/components/vault-v2/item-more-options/item-more-options.component.ts
[PM-8665](https://bitwarden.atlassian.net/browse/PM-8665)
Show a toast when an item is added or removed from favorites.
https://github.com/bitwarden/clients/assets/8764515/0c006f07-e835-47a5-be8a-c2683ca34228 …
=> [PM-8665] Show toast when favorite is toggled

libs/components/src/stories/colors.mdx, libs/components/src/tw-theme.css, libs/components/tailwind.config.base.js
[CL-267](https://bitwarden.atlassian.net/browse/CL-267)
This PR adds 100-level variants to `info`, `success`, `danger`, and `warning` that will be used in component updates. It also updates the `primary-600` color in the light theme in order to provide more contrast between `primary-600` and `primary-700`.
Check Storybook Publish action and view the Colors page. …
=> [CL-267] Add 100-level color variants and update primary-600

apps/web/src/app/oss-routing.module.ts, libs/auth/src/angular/anon-layout/anon-layout-wrapper.component.ts
A few adjustments to AnonLayout:
- Check for undefined before attempting translation so we don't run into errors - https://github.com/bitwarden/clients/pull/9590/commits/5396842d3d81ed23e721f65668f05a81f48056ab
- Remove duplicate route - https://github.com/bitwarden/clients/pull/9590/commits/2fecc0ef8c9d13625f0fdc013687aee7230a68ca …
=> Check undefined data properties before i18n

apps/web/src/app/billing/shared/update-license-dialog.component.ts, apps/web/src/app/billing/shared/update-license.component.ts
=> Upload license dialog not closing bug fix

apps/web/src/app/billing/shared/update-license-dialog.component.ts, apps/web/src/app/billing/shared/update-license.component.ts
This reverts commit bece0720863b875bb999c9477afab23c8f85f22b. …
=> Revert "Upload license dialog not closing bug fix (#9588)"

apps/web/src/app/billing/accounts/trial-initiation/trial-billing-step.component.ts, apps/web/src/app/billing/individual/premium.component.ts, apps/web/src/app/billing/organizations/organization-plans.component.ts, apps/web/src/app/billing/shared/adjust-payment-dialog.component.ts, apps/web/src/app/billing/shared/tax-info.component.html, apps/web/src/app/billing/shared/tax-info.component.ts
This reverts commit 99dc88688a09cbea8eeee26b9b95e78e6377c5c5. …
=> Revert "[PM-5024] tax info component migration (#8199)"

bitwarden_license/bit-web/src/app/admin-console/providers/setup/setup.component.ts
=> [AC-2764] Fix provider setup component

.github/workflows/test.yml
Streamlines the test workflow a bit to no longer need the check run but instead use the Codecov secret conditionally, which is simpler. …
=> Conditionally use Codecov secret

apps/browser/src/vault/popup/services/vault-popup-list-filters.service.ts
[PM-8831](https://bitwarden.atlassian.net/browse/PM-8831)
Ensure deleted items are not shown in the new vault popup. …
=> [PM-8831] Hide trashed items from new vault popup lists

apps/web/src/app/auth/recover-delete.component.ts
[PM-8866](https://bitwarden.atlassian.net/browse/PM-8866)
Add missing form validation
https://github.com/bitwarden/clients/assets/116684653/0f41865f-d694-4aac-9cf4-98c98090d719 …
=> Auth/PM-8866 - Fix Recover delete component submit missing form validation

apps/web/src/app/oss-routing.module.ts
[PM-8867](https://bitwarden.atlassian.net/browse/PM-8867)
To fix the RecoverDelete component's missing page title. …
=> PM-8867 - RecoverDelete comp - fix missing page title

.github/workflows/release-browser.yml
https://bitwarden.atlassian.net/browse/RELEASE-1200
Update build artifact name for releasing.
https://github.com/bitwarden/clients/pull/9654 …
=> [RELEASE-1200] update browser release asset name

apps/web/src/app/auth/sso.component.ts
[PM-8886](https://bitwarden.atlassian.net/browse/PM-8886)
See title.
https://github.com/bitwarden/clients/assets/116684653/e6ba8e2a-be00-4e7c-98e1-eda186fd2516 …
=> Auth/PM-8886 - SsoComponent - fix missing form validation

apps/web/src/app/oss-routing.module.ts
https://bitwarden.atlassian.net/browse/PM-8855
To fix missing page titles on pages which had the route data in the incorrect location. 
SSO:
Emergency Access: …
=> Auth/ Fix web route data configuration issues for SSO comp and AcceptEmergency comp

apps/web/src/app/auth/two-factor.component.html
=> Bug fix - Yubikey code obscured

bitwarden_license/bit-web/src/app/billing/providers/subscription/subscription-status.component.html
https://bitwarden.atlassian.net/browse/AC-2721
Fix the red color issue with subscription date …
=> [AC-2721] [Defect] Apply Subscription Status Updates in Provider Subscription details

libs/tools/generator/extensions/src/legacy-password/index.ts, libs/tools/generator/extensions/src/legacy-username/index.ts
https://bitwarden.atlassian.net/browse/PM-8959
Somehow I didn't save the barrel files in my last PR.
=> [PM-8959] fix file names

apps/web/src/app/auth/recover-two-factor.component.ts
https://bitwarden.atlassian.net/browse/PM-8860
Prevents an api call on the recover 2fa form if validation hasn't been passed. …
=> [PM-8860] add client side form validation to recover 2fa component

apps/web/src/app/oss-routing.module.ts
https://bitwarden.atlassian.net/browse/PM-8854
Adds back region selector to 2fa pages …
=> [PM-8854] add back env selector to 2fa

apps/web/src/app/auth/settings/two-factor-base.component.ts, apps/web/src/app/auth/settings/two-factor-email.component.ts
https://bitwarden.atlassian.net/browse/PM-8939
Our client side validation on submit of the email setup 2fa component was checking to make sure the token and email were there before continuing. The problem here is that disabling email goes through the same flow, so because there was no token or email while disabling, it wouldn't actually disable the 2fa.
I caught another bug here that server side errors weren't being shown. This was because we removed the `formPromise` from the template, but not the code itself. When a `formPromise` is used with an `appApiAction`, server side errors are caught and shown in popups. In order to handle this transition period where we have both kinds of 2fa setup components, I've created a secondary disable that doesn't require the `formPromise`. New …
=> [PM-8939] fix email 2fa validation

package-lock.json, package.json
Reverts bitwarden/clients#9684
=> Revert "[PM-8956][deps] Tools: Update electron-updater to v6.2.1"

apps/browser/src/auth/guards/fido2-auth.guard.ts, apps/browser/src/vault/popup/components/fido2/fido2.component.ts, apps/browser/src/vault/popup/components/vault/add-edit.component.ts
[PM-8996](https://bitwarden.atlassian.net/browse/PM-8996)
Revert changes from [PM-4577](https://github.com/bitwarden/clients/pull/8746) and bypass user verification.
https://github.com/bitwarden/clients/assets/13024008/0208ce08-71ad-4e91-9277-48e263260dd2 …
=> [PM-8996] Revert user verification for passkeys

libs/common/src/admin-console/models/data/organization.data.ts, libs/common/src/admin-console/models/response/profile-organization.response.ts
https://bitwarden.atlassian.net/browse/PM-9042
We had previously renamed `ProductType` to be `ProductTierType`, but missed updating the property in this PR. This PR addresses this. …
=> [PM-9042] Fixed name for product tier to match property sent from the server

apps/web/src/app/admin-console/settings/sponsored-families.component.ts
https://bitwarden.atlassian.net/browse/AC-2776
https://bitwarden.atlassian.net/browse/PM-773
This PR addresses an issue with the Sponsored Families component's `sponsorshipEmail` form field. Previously, the form field was configured to update its value and validation status on `blur`, i.e., when the form field loses focus. This led to a problem where pressing the "Enter" key to submit the form before the field lost focus resulting in a `null` value being read by the submit function.  The proposed change in this PR is to modify the `updateOn` strategy from `blur` to `change`. This ensures that the form control's value and validation status are updated every time the value of the form control changes, thereby resolving the issue.
The PR includes changes to the …
=> [AC-2776][PM-773] Update email on sponsored families signup to update on change

.github/workflows/scan.yml
[PM-7288](https://bitwarden.atlassian.net/browse/PM-7288): Deploy scanning workflow organization-wide
Improving code quality and code coverage issues with Sonar
[PM-7288]: https://bitwarden.atlassian.net/browse/PM-7288?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Include sources in scan workflow for Sonar

apps/web/src/app/auth/settings/security/change-kdf/change-kdf.component.ts, libs/auth/src/angular/input-password/input-password.component.ts, libs/auth/src/common/services/pin/pin.service.spec.ts
Fixes a couple missed references from #9567
- 🎨 …
=> reference correct default kdf config

.eslintrc.json
N/A
Add an eslint rule prohibiting importing Bitwarden-licensed code in OSS code.
This uses the `no-restricted-imports` for regular static import statements, and `no-restricted-syntax` for dynamic imports [per this recommendation](https://github.com/eslint/eslint/issues/13594#issuecomment-704249328).
- 📝 …
=> Add eslint rule prohibiting Bitwarden-licensed imports in OSS code

apps/browser/src/platform/popup/layout/popup-header.component.html, apps/browser/src/platform/popup/layout/popup-header.component.ts, libs/components/src/index.ts, libs/components/src/utils/index.ts
https://bitwarden.atlassian.net/browse/CL-319
Add the ability to customize the back action in the popup header component. …
=> [CL-319] custom back action in popup header component

libs/angular/src/utils/component-route-swap.ts
https://bitwarden.atlassian.net/browse/PM-9182
We need a way to specify alternative route options, should they not be the same for the swapped components. …
=> [PM-9182] Introduce optional alternative componentRouteSwap route options

libs/tools/send/send-ui/src/index.ts, libs/tools/send/send-ui/src/new-send-dropdown/new-send-dropdown.component.html, libs/tools/send/send-ui/src/new-send-dropdown/new-send-dropdown.component.ts
https://bitwarden.atlassian.net/browse/PM-9253
Create a new button and dropdown from which a user can select which type of Send they want to create (text/file)
Once selected the user will be directed to the send-add-edit page.
No QA needed as this component is not used anywhere yet. It will be tested once the SendV2 and SendAddEditV2 components have been built. …
=> [PM-9253] Create "new Send"-button with type selection

libs/common/src/tools/generator/random.ts, libs/tools/generator/core/src/engine/crypto-service-randomizer.ts
https://bitwarden.atlassian.net/browse/PM-9306
Shuffle the copy of the array so that the input argument isn't modified unless requested by the caller.
**Note:** QA to be performed on `rc`.
=> shuffle copied array

.github/workflows/staged-rollout-desktop.yml
https://bitwarden.atlassian.net/browse/BRE-151
Fix Staged Rollout Desktop workflow …
=> [BRE-151] Fix Staged Rollout Desktop workflow

.github/workflows/release-desktop.yml
https://bitwarden.atlassian.net/browse/BRE-133
Always publish Desktop electron artifacts and `.yml`s with rollout percentage to S3 when a GitHub Release is created. …
=> [BRE-133] Fix Partial Desktop Release

apps/web/src/app/auth/sso.component.ts
https://bitwarden.atlassian.net/jira/software/c/projects/BW/boards/87?selectedIssue=PM-8718
If the identifier parameter is passed in the URL, the component will auto-submit the form and redirect to login if the sso identifier does not exist, and to the sso provider if it does exist.
**_Concerns for reviewing:_**
:question: Right now we just catch all errors from the parent component, the sso prevalidation failing being one of them. Are there other errors, where redirecting to /login after the autosubmit flow failed is a problem?
(Recording is in the Jira ticket)
- Used …
=> [PM-8718] Streamlined SSO autosubmit flow

apps/cli/README.md
https://bitwarden.atlassian.net/browse/AC-2819
We are going to be publishing the `oss` builds of Bitwarden on homebrew, which is different from other package managers that will get the `bit` version. This PR adds a clarification to the README about this discrepancy.  …
=> Update the README to mention the discrepancy with homebrew

apps/web/src/app/oss-routing.module.ts
https://bitwarden.atlassian.net/browse/PM-4950
See title.
Hint has title:
Verify delete has title: …
=> Auth/PM-4950 - Fix hint and verify delete components that had the route data in the wrong place

apps/browser/src/vault/popup/components/fido2/fido2.component.ts, apps/browser/src/vault/popup/components/vault/add-edit.component.ts, libs/common/src/platform/services/fido2/fido2-authenticator.service.spec.ts, libs/common/src/platform/services/fido2/fido2-authenticator.service.ts
https://bitwarden.atlassian.net/browse/PM-4661
https://share.cleanshot.com/p1PH1krC …
=> PM-4661: Add passkey.username as item.username

libs/vault/src/components/assign-collections.component.ts
https://bitwarden.atlassian.net/browse/PM-9366
https://bitwarden.atlassian.net/browse/PM-9365
Refactor from [here](https://github.com/bitwarden/clients/pull/9507/commits/acff13fdb01869cc61cdccbbe7adc620c26b8b30#diff-7284795e4ad934efdac734034df1cf1ae58c83795b31e962d6bb90aeb823ee06L159) only sets the selectedOrgId when an organization is selected from the form which causes the error when organization ciphers are selected for assignment.
- Updated any …
=> [PM-9365] [PM-9366] Assign to collections throws error

apps/web/src/app/auth/key-rotation/user-key-rotation.service.spec.ts, apps/web/src/app/auth/key-rotation/user-key-rotation.service.ts
https://bitwarden.atlassian.net/browse/PM-9006
Validate users MP during key rotation
Before:
https://github.com/bitwarden/clients/assets/24985544/7d41454f-c002-4273-b195-832592296cdd
After:
https://github.com/bitwarden/clients/assets/24985544/d3679837-e1bc-4b44-a155-b240eb992122 …
=> [PM-9006] validate mp during key rotations

apps/cli/package.json, package-lock.json
Reverts bitwarden/clients#9906
=> Revert "Bump client(s) version"

apps/web/src/app/billing/accounts/trial-initiation/trial-billing-step.component.ts, apps/web/src/app/billing/individual/premium.component.ts, apps/web/src/app/billing/organizations/organization-plans.component.ts
https://bitwarden.atlassian.net/browse/AC-2830
Fix the issue of not able to create a free org …
=> [AC-2830] Unable to create a free organization

libs/common/src/services/api.service.ts
[PM-9437](https://bitwarden.atlassian.net/browse/PM-9437)
Replace the `CollectionDetailsResponse` with `CollectionAccessDetailsResponse` which properly sets the `Assigned` property. The `Assigned` property is used by the `CollectionAdminService` to update the local collection state and without it, newly created collections are not made available until page refresh. …
=> [PM-9437] Use CollectionAccessDetailsResponse object for creating/updating collections

apps/desktop/src/main.ts, libs/common/src/platform/services/migration-runner.ts
Migration 66 caused the migration mechanism to get locked up without any errors being logged. This adds high-level error handling which at least logs the errors to improve visibility and lets the application start. It does not address the reason for migration 66 throwing an exception …
=> [PM-9441] Catch and log exceptions during migration

libs/importer/spec/protonpass-json-importer.spec.ts, libs/importer/spec/test-data/protonpass-json/protonpass.json.ts, libs/importer/src/importers/protonpass/protonpass-json-importer.ts, libs/importer/src/importers/protonpass/types/protonpass-json-type.ts
https://bitwarden.atlassian.net/browse/PM-9318
Protonpass has changed their export format and this broke the import of usernames
Renamed `username` to `itemEmail` and added `itemUsername`
- **Fix username field used for ProtonPass import -** https://github.com/bitwarden/clients/commit/25b948b7dc59bda096189552920a7cc1206b82a9
- **Import additional field itemUsername -** https://github.com/bitwarden/clients/commit/315e511e6b16127c22a6ca3581f93ca89c6c45f3 …
=> [PM-9318] Fix username on protonpass import

apps/web/src/app/auth/settings/two-factor-authenticator.component.html, apps/web/src/app/auth/settings/two-factor-authenticator.component.ts, apps/web/src/locales/en/messages.json
[PM-8943](https://bitwarden.atlassian.net/browse/PM-8943)
Address race condition when loading the `qrious.min.js` in the `two-factor-authenticator.component.ts`.
Also added verbiage to inform the user of any possible errors when trying to load the QR Code.
https://github.com/bitwarden/clients/assets/137194738/0f80926b-bc39-42af-9421-960c27300cfa
- 👍 …
=> [PM-8943] Update QRious script initialization in Authenticator two-factor provider

apps/browser/src/popup/services/services.module.ts
https://bitwarden.atlassian.net/browse/PM-9457?focusedCommentId=62818
Login via admin approval or device had some strange state behavior where it wasn't updating the rest of the application. We believe that by using a separate popup version (instead of re-using the bg version), it fixes these issues.
- 📝 …
=> [PM-9457] remove getBgService for auth request service

.github/whitelist-capital-letters.txt, libs/common/src/tools/integration/README.md, libs/common/src/tools/integration/extension-point-id.ts, libs/common/src/tools/integration/index.ts, libs/common/src/tools/integration/integration-configuration.ts, libs/common/src/tools/integration/integration-context.spec.ts, libs/common/src/tools/integration/integration-context.ts, libs/common/src/tools/integration/integration-id.ts, libs/common/src/tools/integration/integration-metadata.ts, libs/common/src/tools/integration/rpc/api-settings.ts, libs/common/src/tools/integration/rpc/index.ts, libs/common/src/tools/integration/rpc/integration-request.ts, libs/common/src/tools/integration/rpc/request-options.ts, libs/common/src/tools/integration/rpc/rest-client.spec.ts, libs/common/src/tools/integration/rpc/rest-client.ts, libs/common/src/tools/integration/rpc/rpc-definition.ts, libs/common/src/tools/integration/rpc/rpc.ts, libs/common/src/tools/integration/rpc/token-header.ts
https://bitwarden.atlassian.net/browse/PM-9598
Factor general integration logic out of the forwarder code.
* Integration metadata - information generalized across any integration
* Rpc mechanism - first step towards applying policy to integrations is abstracting their service calls (e.g. static baseUrl)
**Note:** QA is not needed. This code has no consumers.
Email forwarder integrations embedded this metadata. It was extracted to begin the process of making integrations compatible with meta-systems like policy.
This PR consists mostly of interfaces, which are not particularly useful on their own. Examples on how they're used can be found in the readme. …
=> [PM-9598] Introduce integrations

libs/angular/src/admin-console/components/collections.component.ts
[AC-2549](https://bitwarden.atlassian.net/browse/AC-2549)
This fixes an issue where the error toast was not triggering when a user that has "can view" permission, tries to edit the cipher into an org with "can edit" permission
https://github.com/bitwarden/clients/assets/14082576/70918dfa-be17-4b0a-b01f-f7234957cbdc …
=> AC-2549 - FC, show error toast when editing a cipher in collection with "can view" permissions

libs/angular/src/directives/api-action.directive.ts
Add a deprecation comment to `[appApiAction]`. `[bitSubmit]` should be used instead. …
=> [DS] add deprecation comment to ApiActionDirective

apps/web/src/app/auth/sso.component.ts
https://bitwarden.atlassian.net/browse/PM-9606
Sets a loading indicator in case the sso redirection flow takes a long time.
https://github.com/bitwarden/clients/assets/11866552/b0d8e777-a427-4982-938d-d8336ebf1e66 …
=> [PM-9606] Set loading indicator on automatic sso flow

libs/vault/src/cipher-form/components/card-details-section/card-details-section.component.html
[PM-9513](https://bitwarden.atlassian.net/browse/PM-9513)
Adding test-ids to the visibility toggles for card number and card code for automated testing
[PM-9513]: https://bitwarden.atlassian.net/browse/PM-9513?atlOrigin=eyJpIjo …
=> [PM-9513] Add testids for visibility buttons on edit card

apps/web/src/app/billing/individual/user-subscription.component.ts, apps/web/src/app/billing/shared/update-license-dialog.component.ts, apps/web/src/app/billing/shared/update-license-types.ts, apps/web/src/app/billing/shared/update-license.component.ts
https://bitwarden.atlassian.net/browse/AC-2859
Resolved circular dependency introduced in https://github.com/bitwarden/clients/pull/9871 …
=> [AC-2859] Resolved circular dependency with UpdateLicenseDialogResult enum

apps/web/src/app/billing/individual/premium.component.ts
https://bitwarden.atlassian.net/browse/PM-9635
Fix this error on license upload for selfhost (`Cannot read properties of undefined (reading 'taxFormGroup'`)
Open image-20240710-133801.png
image-20240710-133801.png …
=> [PM-9635] [Defect] Error thrown uploading premium license file

bitwarden_license/bit-web/src/app/billing/providers/clients/create-client-dialog.component.html, bitwarden_license/bit-web/src/app/billing/providers/clients/manage-client-subscription-dialog.component.html, bitwarden_license/bit-web/src/app/billing/providers/clients/manage-client-subscription-dialog.component.ts, bitwarden_license/bit-web/src/app/billing/providers/clients/manage-clients.component.html
https://bitwarden.atlassian.net/browse/AC-2853
https://bitwarden.atlassian.net/browse/AC-2854
https://bitwarden.atlassian.net/browse/AC-2861
This PR resolves some small Consolidated Billing UI bugs around the input field used to select a seat count when creating or updating a client organization.
- 📝 …
=> [AC-2853] [AC-2854] [AC-2861] Consolidated Billing UI Bugs 

apps/web/src/locales/en/messages.json
https://bitwarden.atlassian.net/browse/PM-1935
One line tweak to remove a trailing period from some copy on the lock component from direction of Danielle
BEFORE
AFTER …
=> PM-1935/vault-locked-message-fix

libs/vault/src/cipher-form/components/identity/identity.component.html, libs/vault/src/cipher-form/components/identity/identity.component.ts
[PM-9646 Show Bold Headers](https://bitwarden.atlassian.net/browse/PM-9646)
[PM-9513 Add test ids to visibility toggles](https://bitwarden.atlassian.net/browse/PM-9513)
[PM-9658 Use New Show/Hide Toggle](https://bitwarden.atlassian.net/browse/PM-9658)
Updates made to address the three listed defects. Fixed with importing necessary module, and updating the toggle button …
=> [PM-9646] Identity v2 Edit Defects

libs/vault/src/cipher-view/additional-information/additional-information.component.ts, libs/vault/src/cipher-view/attachments/attachments-v2.component.ts, libs/vault/src/cipher-view/custom-fields/custom-fields-v2.component.ts, libs/vault/src/cipher-view/item-details/item-details-v2.component.html, libs/vault/src/cipher-view/item-details/item-details-v2.component.ts, libs/vault/src/cipher-view/item-history/item-history-v2.component.ts
[PM-9627 Pulling incorrect item name](https://bitwarden.atlassian.net/browse/PM-9627)
[PM-9628 Formatting of Collections List](https://bitwarden.atlassian.net/browse/PM-9628)
This PR will
- Import Typography Module for item details (NOTE: also pulled it in for the other reusable view components)
- Populate the Item Name field with the `cipher.name`
- Updated spacing to match figma for the collections list `tw-mb-1`
- Updated element types in html
- Updated font to match figma for the `<p>` tags using `bitTypography`
- CI …
=> [PM-9627] item details v2 defects

libs/auth/src/angular/registration/registration-finish/registration-finish.component.html
[PM-9688](https://bitwarden.atlassian.net/browse/PM-9688)
To fix button text to say create account instead of set password. All clients have the "createAccount" translation key in their `messages.json`. 
- …
=> Auth/PM-9688 - Registration with Email Verification - Fix RegistrationFinishComponent Copy

apps/web/src/app/billing/accounts/trial-initiation/trial-billing-step.component.ts, apps/web/src/app/billing/individual/premium.component.ts, apps/web/src/app/billing/shared/adjust-payment-dialog.component.ts, apps/web/src/app/billing/shared/tax-info.component.ts
https://bitwarden.atlassian.net/browse/PM-9704
Fix this error (`An error has occurred. Zip / postal code is required`.)  on trial initiation pagae
https://github.com/user-attachments/assets/3ea54faf-698e-44ab-9f32-18c946f8728a
- ❓ …
=> [PM-9704][Defect] Creating organization from Secrets Manager trial path throwing an error

apps/web/src/app/tools/reports/pages/inactive-two-factor-report.component.html
https://bitwarden.atlassian.net/browse/PM-4964
This PR migrates the `app-callout` and `table` components to the new library component in `InactiveTwoFactorReportComponent` …
=> [PM-4965] Migrate inactive two factor report

apps/web/src/app/tools/reports/pages/reused-passwords-report.component.html
https://bitwarden.atlassian.net/browse/PM-4967
This PR migrates the `app-callout` and `table` components to the new library component in `ReusedPasswordsReportComponent` …
=> [PM-4967] Migrate reused passwords report components

apps/browser/src/auth/popup/two-factor-auth-email.component.ts, apps/browser/src/auth/popup/two-factor-auth.component.ts, apps/desktop/src/auth/two-factor-auth.component.ts, apps/web/src/app/auth/two-factor-auth.component.ts, libs/angular/src/auth/components/two-factor-auth/two-factor-auth-email.component.html, libs/angular/src/auth/components/two-factor-auth/two-factor-auth-email.component.ts, libs/angular/src/auth/components/two-factor-auth/two-factor-auth.component.html, libs/angular/src/auth/components/two-factor-auth/two-factor-auth.component.ts
https://bitwarden.atlassian.net/browse/PM-7084
https://bitwarden.atlassian.net/browse/PM-9025
> [!IMPORTANT]  
> **STACKED PR:** This set of changes is split into a set of smaller PR's that can be reviewed independently, in parallel. Merging still should be done in order once all PR's are reviewed. Merging can be done incrementally as the feature is feature flagged.
#9767 - Shared two-fa options component
#9768 - Shared two-fa orchestrator component & totp authenticator component
#9769 - Shared two-fa yubikey component
#9770 - Shared two-fa email component
#9771 - Shared two-fa webauthn component
#9772 - Shared two-fa duo component
- …
=> [PM-7084] 4/6: Introduce shared email two-factor component

.github/workflows/scan.yml
Excludes tests from Sonar as a recommended best practice. …
=> Exclude tests from Sonar

apps/browser/src/_locales/en/messages.json, apps/browser/src/popup/app-routing.module.ts, apps/browser/src/tools/popup/send/send-v2.component.html, apps/browser/src/tools/popup/send/send-v2.component.ts
https://bitwarden.atlassian.net/browse/PM-9851
Create a new Send component for the extension UI refresh. This is currently WIP and features will be added with futures PRs. This is just to have the basic page and conditional routing based on the feature-flag done.
No QA needed as testing will be done, once more feature like, listing, filters and search are implemented. …
=> [PM-9851] Create browsers SendV2 component

apps/web/src/app/auth/settings/change-password.component.ts
https://bitwarden.atlassian.net/browse/PM-9848
Fix key rotation, which was broken in https://github.com/bitwarden/clients/pull/9722 .
This sets the master key locally before calling the key rotation service, so that the key verification in the service works.
https://github.com/user-attachments/assets/b9387ac8-4c54-4dda-bd80-c99b743a059c
- 👍 (`:+1:`) …
=> [PM-9848] Fix key rotation being broken due to master key validation

apps/browser/src/_locales/en/messages.json, apps/desktop/src/locales/en/messages.json, apps/web/src/locales/en/messages.json, libs/auth/src/angular/registration/registration-start/registration-start.component.html
https://bitwarden.atlassian.net/browse/PM-9930
To tweak the marketing email copy per product request. …
=> Auth - Registration with Email Verification - Registration Start Comp - update copy per product request

libs/components/src/select/select.component.html, libs/vault/src/components/assign-collections.component.html, libs/vault/src/components/assign-collections.component.ts
[PM-9952](https://bitwarden.atlassian.net/browse/PM-9952)
[PM-9954](https://bitwarden.atlassian.net/browse/PM-9954)
PM-9954 - Truncate `select` options to use ellipsis overflow and have a `title` so hovering with a mouse will display the option name
PM-9952 - Disable org selector when there is only a single organization
|Long Org Name|Disabled Selector|
|-|-|
|<video src="https://github.com/user-attachments/assets/0d0d9549-f071-4733-bf19-d377a1f4bf7e"/>|<video src="https://github.com/user-attachments/assets/a4db9b57-4cc8-49b4-ba9a-3af0d7ec9524" />| …
=> [PM-9952][PM-9954] Minor assign collection fixes

.github/workflows/build-browser.yml, apps/browser/package.json
Increae NodeJs Head Memory in `package.json` by setting the `NODE_OPTIONS` env var.  …
=> Add in NODE_OPTIONS for Build Safari job

apps/browser/src/vault/popup/components/vault-v2/view-v2/view-v2.component.html
[PM-9817](https://bitwarden.atlassian.net/browse/PM-9817)
Update the edit to be a button element in the view-v2 component
https://github.com/user-attachments/assets/76b0a552-4fcb-4929-beac-7a9faa9c0b3f
- 🤔 …
=> [PM-9817] edit button hover

apps/browser/src/_locales/en/messages.json, apps/browser/src/vault/popup/components/vault-v2/assign-collections/assign-collections.component.html, apps/browser/src/vault/popup/components/vault-v2/item-more-options/item-more-options.component.html, apps/web/src/locales/en/messages.json, libs/vault/src/components/assign-collections.component.ts
[PM-9951](https://bitwarden.atlassian.net/browse/PM-9951)
Update bulk assignment & extension copy to match design / feedback from Danielle
|Assign to collections title|Singular success message|Plural success message|
|-|-|-|
|![assign to collections header](https://github.com/user-attachments/assets/6e180236-3f6e-4cbe-b462-fe03fb7251e9)|<video src="https://github.com/user-attachments/assets/f046ab9d-492b-482e-ad1f-5403c3915774" />|<video src="https://github.com/user-attachments/assets/02ff85f9-9880-4b4f-a183-f6c2899eef7b" />| …
=> [PM-9951] Assign to Collection copy

libs/vault/src/cipher-view/item-details/item-details-v2.component.html
[PM-9644](https://bitwarden.atlassian.net/browse/PM-9644)
Adding test ids to item details fields …
=> [PM9644] adding test ids in item details v2

libs/auth/src/angular/registration/registration-env-selector/registration-env-selector.component.html, libs/auth/src/angular/registration/registration-env-selector/registration-env-selector.component.ts
https://bitwarden.atlassian.net/browse/PM-10076
Web shouldn't display an env selector when it is self hosted.  …
=> Auth/PM-10076 - Registration with Email Verification - Registration start - Hide Web Self Hosted Env Selector

libs/auth/src/angular/registration/registration-finish/registration-finish.component.html, libs/auth/src/angular/registration/registration-finish/registration-finish.component.ts
https://bitwarden.atlassian.net/browse/PM-10095
To fix a missed `switchMap` condition where we need a valid observable return + to disable loading for when the user is accepting an non-SSO org invite. 
https://github.com/user-attachments/assets/9e0c4149-c07e-4f06-909c-1ff9b48d0017 …
=> Auth/PM-10095 - Registration with Email Verification - Registration Finish - Fix endless load on Org Invite Accept

apps/desktop/package.json, apps/desktop/src/package-lock.json, apps/desktop/src/package.json, package-lock.json
https://bitwarden.atlassian.net/browse/BRE-183
We need to perform a manual version downgrade due to [Release Desktop 2024.7.1](https://bitwarden.atlassian.net/browse/RELEASE-1212 ) …
=> BRE-183 Manual version downgrade desktop version

apps/cli/src/service-container.ts
https://bitwarden.atlassian.net/browse/PM-9451
Fixes #9919. Move the initialization of the `UserVerificationApiService` above the `UserVerificationService` in cli. The api service was undefined and the master password was never sent to the server for validation. …
=> [PM-9451] move initialization of UV service dep

libs/common/src/auth/services/device-trust.service.implementation.ts, libs/common/src/platform/services/app-id.service.ts
https://bitwarden.atlassian.net/browse/PM-9980
Use the [new feature](#10221) where `0` avoid any caching of values at all for certain keys that are part of values we appear to be losing. 
- 🤔 …
=> [PM-9980] Turn off cache for certain keys

libs/common/src/auth/services/device-trust.service.implementation.ts, libs/common/src/platform/services/app-id.service.ts
https://bitwarden.atlassian.net/browse/PM-9978
Turn on debug logs for 2 keys important in the TDE flows. This won't log any value about the data only if the value is null vs non-null.  …
=> Turn On Debug Info For 2 Keys

.github/workflows/retrieve-current-desktop-rollout.yml
- [Card](https://bitwarden.atlassian.net/browse/BRE-225?atlOrigin=eyJpIjoiYmI1MzQ3NTI3MDQ2NDQ2Zjg5NjE0NWZmNTJiYjIwY2IiLCJwIjoiaiJ9)
This workflow retrieves the current Desktop rollout percentage.
- 🤔 …
=> BRE-225 - Add Retrieve Current Desktop Rollout workflow

libs/vault/src/cipher-view/item-details/item-details-v2.component.html, libs/vault/src/cipher-view/item-details/item-details-v2.component.ts
[PM-10141](https://bitwarden.atlassian.net/browse/PM-10141)
Fix styling of the name input for item details.
- `FormFieldModule` import was missing.
- Added usage of `bit-form-field` so styles are consistent with other implementations.
- Double checked styles of orgs/collections/folders and updated to match figma.
|Before|After|
|-|-|
|![Screen Shot 2024-07-29 at 09 18 20 AM](https://github.com/user-attachments/assets/4714209a-71f0-4e0b-b787-1e64de14d70f)|![Screen Shot 2024-07-29 at 09 17 59 AM](https://github.com/user-attachments/assets/73323a95-977a-4eee-9c2e-d367bf31a829)| …
=> [PM-10141] Fix name input styling

libs/common/src/tools/integration/rpc/rest-client.ts, libs/tools/generator/core/src/engine/rpc/create-forwarding-address.spec.ts, libs/tools/generator/core/src/engine/rpc/create-forwarding-address.ts, libs/tools/generator/core/src/engine/rpc/get-account-id.spec.ts, libs/tools/generator/core/src/engine/rpc/get-account-id.ts
https://bitwarden.atlassian.net/browse/PM-10259
Fix the above bug report.
* Add accept headers to indicate that only JSON responses are supported
* Remove X-Requested-With header since it requires specialized CORS support and doesn't seem to be required by addy.io. (It returns identical responses with and without the header.)
* Expand error processing to accommodate all client error codes (400)
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant …
=> [PM-10259] improve forwarder rpc error handling

apps/web/package.json, package-lock.json
The version number for Web was incorrectly bumped and needed adjustment. …
=> Fix version number for Web

libs/angular/src/directives/api-action.directive.ts
API errors currently display in console as: `Received API exception: object object`. This uses the log service improvements from #8989 to correctly serialize and print the exception received.
- 🤔 …
=> Log full api error

apps/browser/src/vault/fido2/browser-fido2-user-interface.service.ts
PM-7956
Adding some typing for fido2 message type values. These changes will also be used in upcoming work in branch `pm-7956` (fido2 popup components will be updated to use these constants/types in that branch) …
=> [PM-7956] Improve typing for fido2 message type values

apps/cli/src/platform/services/cli-platform-utils.service.ts
Fix cli build by adding stubs for methods added in the linux biometrics PR. …
=> Fix cli build by adding biometric stubs

libs/components/src/dialog/simple-dialog/simple-dialog.component.html, libs/components/src/dialog/simple-dialog/simple-dialog.stories.ts
https://bitwarden.atlassian.net/browse/CL-342
Reapplies the text overflow story/fix from https://github.com/bitwarden/clients/pull/10096 to `main`. 
See Storybook --> Dialog --> Simple Dialog --> Text Overflow …
=> [CL-342] make overflow text wrap in simple dialog

libs/components/src/badge/badge.mdx, libs/components/src/badge/badge.stories.ts, libs/components/src/button/button.mdx, libs/components/src/checkbox/checkbox.mdx, libs/components/src/checkbox/checkbox.stories.ts, libs/components/src/dialog/dialog/dialog.mdx, libs/components/src/dialog/dialog/dialog.stories.ts, libs/components/src/dialog/simple-dialog/simple-dialog.mdx, libs/components/src/dialog/simple-dialog/simple-dialog.stories.ts, libs/components/src/form-field/form-field.mdx, libs/components/src/form/form.stories.ts, libs/components/src/icon-button/icon-button.mdx, libs/components/src/link/link.mdx, libs/components/src/search/search.mdx, libs/components/src/select/select.mdx, libs/components/src/table/table.stories.ts, libs/components/src/toast/toast.mdx, libs/components/src/typography/typography.mdx
PM-9969
Add component import examples, clean up some html/formatting nits
=> [PM-9969] Papercut - Update component library storybook docs

libs/vault/src/cipher-view/additional-options/additional-options.component.html, libs/vault/src/cipher-view/card-details/card-details-view.component.html, libs/vault/src/cipher-view/item-details/item-details-v2.component.html, libs/vault/src/cipher-view/item-history/item-history-v2.component.html
[PM-10374](https://bitwarden.atlassian.net/browse/PM-10374)
- Remove margin from additional options, item details, item history
- Refactor card details to use new remove options css logic
https://github.com/user-attachments/assets/25adc102-f28b-4f3c-ba65-81bf5ece6c49 …
=> [PM-10374] update some view v2 components for margins

libs/vault/src/cipher-view/card-details/card-details-view.component.html
[PM-10486](https://bitwarden.atlassian.net/browse/PM-10486)
hide empty cardholder field …
=> [PM-10486] hide empty cardholder field

apps/browser/src/auth/popup/extension-anon-layout-wrapper/extension-anon-layout-wrapper.component.ts, libs/auth/src/angular/anon-layout/anon-layout-wrapper.component.ts, libs/auth/src/angular/anon-layout/anon-layout-wrapper.stories.ts
https://bitwarden.atlassian.net/browse/PM-9603
To add the ability to avoid translating the page subtitle as we have designs where a user's email needs to go in the subtitle slot.
See [storybook](https://62a88a6de5b807fa98886113-bzgncgkebr.chromatic.com/).  …
=> Auth/PM-9603 - AnonLayout Dynamic Content Support - Non-translated Page Subtitle Support

apps/browser/src/background/runtime.background.ts
=> Added missing feature flag for setting autofill policy on load

libs/importer/spec/test-data/protonpass-json/protonpass.json.ts, libs/importer/src/importers/protonpass/protonpass-json-importer.ts
https://github.com/bitwarden/clients/issues/10472
Fix import of credit card expiration date from ProtonPass.
Changed the treatment of the string creditCardContent.expirationDate …
=> [PM-10764] Fix ProtonPass creditCard expirationDate import

apps/web/src/app/billing/organizations/adjust-subscription.component.html, apps/web/src/app/billing/organizations/adjust-subscription.component.ts
https://bitwarden.atlassian.net/browse/AC-1791
Make the password manager seat and autoscaling adjustment works as the secret manager seat and autoscaling adjustment …
=> [AC-1791][Defect] Billing - Total Subtext, Additional Seat Count calculation is not consistent

.github/workflows/chromatic.yml
https://bitwarden.atlassian.net/browse/CL-386
Utilizes the check run workflow to protect the Chromatic secret. …
=> Move Chromatic to more secure execution model

apps/browser/src/background/main.background.ts, apps/desktop/src/app/layout/account-switcher.component.ts
Reverts bitwarden/clients#10342
@JaredSnider-Bitwarden Mixed up PR's and intended to merge a different PR this one had a minor bug returned from QA, so while not urgent, I'd rather revert for now and take another look.
=> Revert "[PM-8316] Fix account switcher on logged out account on startup"

apps/browser/src/background/nativeMessaging.background.ts
Fixes issues introduced by the combination of https://github.com/bitwarden/clients/pull/10411 and https://github.com/bitwarden/clients/pull/9675
To fix `nativeMessaging.background` by replacing removed state service usage with account service for user id retrieval
n/a …
=> Fix nativeMessaging.background - Replace StateService usage with AccountService

apps/browser/src/_locales/en/messages.json, apps/web/src/locales/en/messages.json, libs/vault/src/cipher-form/components/autofill-options/autofill-options.component.html, libs/vault/src/cipher-form/components/autofill-options/autofill-options.component.spec.ts, libs/vault/src/cipher-form/components/autofill-options/autofill-options.component.ts, libs/vault/src/cipher-form/components/autofill-options/uri-option.component.html, libs/vault/src/cipher-form/components/autofill-options/uri-option.component.ts
[PM-10751](https://bitwarden.atlassian.net/browse/PM-10751)
[PM-10752](https://bitwarden.atlassian.net/browse/PM-10752)
[PM-10790](https://bitwarden.atlassian.net/browse/PM-10790)
> [!NOTE] 
> There are other style changes in https://github.com/bitwarden/clients/pull/10454 that will address odd spacing and font size in the screenshot below.
- 👍 …
=> [PM-9190] Browser Refresh - Autofill section fixes

.github/workflows/build-desktop.yml, apps/desktop/package.json, apps/desktop/scripts/after-sign.js
- [Card](https://bitwarden.atlassian.net/browse/BRE-243?atlOrigin=eyJpIjoiNDJjNDY4OWQ0MDk5NDRkYWI4ZGI0OTE2ZjQ4OTAxMWYiLCJwIjoiaiJ9)
This PR updates the notarization process to use an api key for App Store Connect. …
=> BRE-243 - Fix credentials used for Desktop upload to App Store

.github/workflows/test.yml
Both test results and Codecov will fail on forks, so avoid those steps when secrets are not available. …
=> Test for secrets before performing restricted actions

.github/workflows/test.yml
Check if not cancelled when reporting test results, using the latest reporter Action. …
=> Use cancellation check with latest test reporter

.github/workflows/test.yml
Codecov can now receive test results in addition to coverage, so send what we have there too.
https://app.codecov.io/github/bitwarden/clients/tests/codecov-results …
=> Upload test results to Codecov

apps/web/src/app/tools/reports/pages/exposed-passwords-report.component.html
https://bitwarden.atlassian.net/browse/PM-10537
This PR adds a missing header to the exposed passwords report
|Before|After|
---|---
|![Screenshot 2024-08-14 at 10 27 18 AM](https://github.com/user-attachments/assets/f848e368-c92f-43b3-a9dc-777de53635eb)|![Screenshot 2024-08-14 at 10 27 01 AM](https://github.com/user-attachments/assets/5abb5b72-19fd-4270-88d1-14209be8f048)| …
=> [PM-10537] - add missing header to exposed passwords report

package-lock.json, package.json
https://bitwarden.atlassian.net/browse/PM-8956
- 🎨 …
=> [PM-8956] Bump electron-updater to 6.3.3

apps/web/src/app/tools/reports/pages/breach-report.component.html, apps/web/src/app/tools/reports/pages/cipher-report.component.ts, apps/web/src/app/tools/reports/pages/exposed-passwords-report.component.html, apps/web/src/app/tools/reports/pages/inactive-two-factor-report.component.html, apps/web/src/app/tools/reports/pages/reused-passwords-report.component.html, apps/web/src/app/tools/reports/pages/unsecured-websites-report.component.html, apps/web/src/app/tools/reports/pages/weak-passwords-report.component.html
https://bitwarden.atlassian.net/browse/PM-4962
This is the final PR to migrate the reports components. In particular this PR removes any remaining bootstrap classes and in addition, adds a few missing header columns. …
=> [PM-4962] remove all bootstrap classes from reports. add missing header column

apps/desktop/src/vault/app/accounts/premium.component.ts
https://github.com/bitwarden/clients/pull/10514 broke main since the `StateService` was only removed from the base class. …
=> Fix desktop broken on main

apps/web/src/app/tools/reports/reports-layout.component.html
https://bitwarden.atlassian.net/browse/PM-4970
This PR migrates the report-layout component from bootstrap to the component library. …
=> migrate report-layout component

apps/browser/src/background/runtime.background.ts
[PM-10825](https://bitwarden.atlassian.net/browse/PM-10825) …
=> [PM-10825] Autofill on page load checkbox is not checked when policy is enabled

apps/browser/package.json
- [Card](https://bitwarden.atlassian.net/browse/BRE-252?atlOrigin=eyJpIjoiMzEyZGYwZDgzZDYyNDUyOGE3YTIyZThkMDAyODMxMWYiLCJwIjoiaiJ9)
This PR sets the `BROWSER` environment variable so that the logic in the `webpack.config.js` file is executed correctly for the `Safari` build. …
=> BRE-252 - Fix Safari Browser Build

apps/browser/src/_locales/en/messages.json, apps/browser/src/billing/popup/settings/premium-v2.component.html, apps/browser/src/billing/popup/settings/premium-v2.component.ts, libs/common/src/platform/services/config/default-config.service.ts
https://bitwarden.atlassian.net/browse/PM-8228
This PR fixes a couple of defects with the copy in the new premium component
|Before|After|
---|---
|![image-20240820-192913](https://github.com/user-attachments/assets/7ec3b736-ea5b-4c22-aefd-a3a4f80d0220)|![Screenshot 2024-08-20 at 3 43 21 PM](https://github.com/user-attachments/assets/22a9575c-e6eb-4050-a300-9ee0fdd7330b)| …
=> [PM-8228] - new premium component - fix copy

apps/web/src/app/billing/shared/tax-info.component.html
https://bitwarden.atlassian.net/browse/PM-10985
This PR increases the width of the postal code input to prevent wrapping when the "(required)" text is present.
|Before|After|
---|---
|![Screenshot 2024-08-20 at 5 08 07 PM](https://github.com/user-attachments/assets/26eddf23-5773-4fd8-83e3-5ccbb1ac02d0)|![Screenshot 2024-08-20 at 5 07 30 PM](https://github.com/user-attachments/assets/76c3bee6-a2ad-4168-9f77-adad5600a09b)| …
=> [PM-10985] - fix postal code alignment

apps/web/src/app/billing/shared/update-license-dialog.component.ts
Fixes missing argument in `UpdateLicenseDialogComponent` constructor …
=> Resolved broken web build

apps/desktop/src/app/tools/import/import-desktop.component.html
https://bitwarden.atlassian.net/browse/PM-8386
This PR adds the `alt` background for the desktop import dialog to match the new import component as part of the extension refresh.
|Light|Dark|
---|---
|![desktop-light](https://github.com/user-attachments/assets/f3eb0a3b-5a09-4752-991a-d52039a4f880)|![desktop-dark](https://github.com/user-attachments/assets/7d656377-bc5d-4da2-92e0-ab820c5f3fd1)| …
=> [PM-8386] - add alt bg to import dialog

.github/workflows/release-cli.yml
- [Card](https://bitwarden.atlassian.net/browse/BRE-271?atlOrigin=eyJpIjoiNDUyYzdkZTAwODdiNDQyNmIxN2ZiYWMwOWVmODBlMzEiLCJwIjoiaiJ9)
This PR fixes the variable reference so that the proper version number is provided to the GitHub release step. …
=> BRE-271 - Fix reference to variable

.github/workflows/build-cli.yml, .github/workflows/chromatic.yml, .github/workflows/crowdin-pull.yml, .github/workflows/deploy-web.yml, .github/workflows/publish-cli.yml, .github/workflows/publish-desktop.yml, .github/workflows/publish-web.yml, .github/workflows/release-desktop.yml, .github/workflows/scan.yml, .github/workflows/test.yml
- [Card](https://bitwarden.atlassian.net/browse/BRE-272?atlOrigin=eyJpIjoiMTE3NmM1ZGRkNzYxNDlkOTg5YmJiYjBmYjZiMjkzNWMiLCJwIjoiaiJ9)
This PR fixes some logic/syntax issues with the new publish workflows.  A few other workflows were updated with miscellaneous formatting updates. …
=> BRE-272  - Fix Publish Workflows and other misc workflow updates

libs/angular/src/platform/guard/feature-flag.guard.spec.ts, libs/angular/src/platform/guard/feature-flag.guard.ts
https://bitwarden.atlassian.net/browse/PM-7606
This PR migrates all platform toasts to the new CL `toastService` …
=> [PM-7606] migrate platform toasts to CL toastService

.github/workflows/publish-cli.yml, .github/workflows/publish-web.yml, .github/workflows/release-cli.yml
- [Card](https://bitwarden.atlassian.net/browse/BRE-272?atlOrigin=eyJpIjoiMGUyZjE5OTg0MzAwNDRjNDllM2IyZGNiYWFkNDdjYzAiLCJwIjoiaiJ9)
This PR updates the `Release CLI` workflow to add the NPM build zip artifact for use in the `Publish CLI` workflow.  The `Publish CLI` workflow has also been updated with correct URLs for downloading artifacts from GitHub releases. …
=> BRE-272 - Fix CLI release and publish workflows

.github/workflows/publish-cli.yml, .github/workflows/publish-desktop.yml
- [Card](https://bitwarden.atlassian.net/browse/BRE-272?atlOrigin=eyJpIjoiZmIxMjgyOGU2NWZhNGRjMThjMWJkZDFiOTAwOTA0YjgiLCJwIjoiaiJ9)
This PR fixes some logic/syntax in the `Publish CLI` and `Publish Desktop` workflows. …
=> BRE-272 - Fix Publish Workflows

apps/browser/src/_locales/en/messages.json, apps/browser/src/billing/popup/settings/premium-v2.component.html
https://bitwarden.atlassian.net/browse/PM-8228
This PR fixes a copy and margin defect for the new premium feature component. 
|Before|After|
---|---
|![Screenshot 2024-08-22 at 3 19 50 PM](https://github.com/user-attachments/assets/f9accd4f-212c-4013-a6ac-08c6d938fa00)|![Screenshot 2024-08-22 at 3 18 11 PM](https://github.com/user-attachments/assets/fd380643-b70d-40b6-8408-f9b702257517)| …
=> [PM-8228] - premium component - fix copy and margin

.github/workflows/publish-cli.yml
- [Card](https://bitwarden.atlassian.net/browse/BRE-277?atlOrigin=eyJpIjoiNDllODIxNGY0ZDM1NDU1ODk3MmYxMzM4ZjBjMWYyODkiLCJwIjoiaiJ9)
This PR updates the `Publish CLI` workflow to extract the release artifact to the proper directory for upload to NPM. …
=> BRE-277 - Fix CLI NPM publish job

apps/desktop/desktop_native/Cargo.lock, apps/desktop/desktop_native/core/Cargo.toml, apps/desktop/desktop_native/core/src/ssh_agent/mod.rs, apps/desktop/desktop_native/core/src/ssh_agent/namedpipelistenerstream.rs
Add windows support for the SSH agent. …
=> Add SSH Agent Support on Windows

.github/workflows/build-cli.yml
- [Card](https://bitwarden.atlassian.net/browse/BRE-277?atlOrigin=eyJpIjoiYWQwMGY3MGMyMjBiNDc4NWJlYTMxOWZmMTE3YmM5M2EiLCJwIjoiaiJ9)
This PR fixes the NPM artifact uploaded by the `Build CLI` workflow.  Once merged the `Release CLI` workflow will properly find the NPM artifact and upload it to the GitHub release. …
=> BRE-277 - Fix NPM build artifact

libs/common/src/platform/services/config/config.service.spec.ts
=> Fixed Config Service Failing Test

apps/browser/src/autofill/background/notification.background.spec.ts, apps/browser/src/autofill/background/notification.background.ts, apps/browser/src/background/commands.background.ts, apps/browser/src/background/idle.background.ts, apps/browser/src/background/main.background.ts
https://bitwarden.atlassian.net/browse/PM-7830
Remove the `async` modifier from background init functions that don't need it. …
=> [PM-7830] Remove Some Unneccesary Async From Init Methods

.github/workflows/build-browser.yml, .github/workflows/build-desktop.yml, .github/workflows/build-web.yml
Reverts bitwarden/clients#10596
=> Revert "[deps] DevOps: Update crowdin/github-action action to v2"

apps/browser/src/autofill/fido2/background/fido2.background.spec.ts, apps/browser/src/autofill/fido2/background/fido2.background.ts, apps/browser/src/background/main.background.ts, apps/browser/src/vault/fido2/browser-fido2-user-interface.service.ts, libs/common/src/platform/abstractions/fido2/fido2-authenticator.service.abstraction.ts, libs/common/src/platform/abstractions/fido2/fido2-client.service.abstraction.ts, libs/common/src/platform/abstractions/fido2/fido2-user-interface.service.abstraction.ts, libs/common/src/platform/services/fido2/fido2-authenticator.service.spec.ts, libs/common/src/platform/services/fido2/fido2-authenticator.service.ts, libs/common/src/platform/services/fido2/fido2-client.service.spec.ts, libs/common/src/platform/services/fido2/fido2-client.service.ts, libs/common/src/platform/services/fido2/noop-fido2-user-interface.service.ts
=> feat: make fido2 services generic

apps/web/src/app/core/core.module.ts, apps/web/src/app/platform/web-biometric.service.ts
https://bitwarden.atlassian.net/browse/PM-11414
To resolve the issue of the lock component not working as there was not a `WebBiometricService` implementation provided to the web `CoreModule`. 
https://github.com/user-attachments/assets/48c66e84-5c66-4ffb-ac62-2aba41f0759d …
=> Auth/PM-11414 - Fix Web Client Lock Component

libs/components/src/item/item.component.html, libs/components/src/item/item.stories.ts
https://bitwarden.atlassian.net/browse/CL-278
https://bitwarden.atlassian.net/browse/CL-391
`bit-item` misc style fixes:
- use correct colors
- use small icon button in stories
- use pointer when hovering links/anchors
See Storybook
- ❓ …
=> [CL-278][CL-391] misc bit-item style fixes

apps/browser/src/autofill/popup/settings/excluded-domains.component.html
PM-10451
Add id to saved excluded domains for testing automation
=> [PM-10451] Add id to divs in saved Excluded Domain rows

libs/common/src/models/export/cipher.export.ts, libs/common/src/models/export/ssh-key.export.ts, libs/importer/src/components/dialog/import-success-dialog.component.ts
https://bitwarden.atlassian.net/browse/PM-10399
Add import / export for ssh key item type for the bitwarden json export format. …
=> [PM-10399] Add ssh key import export for bitwarden json

apps/browser/src/autofill/utils/index.ts
https://bitwarden.atlassian.net/browse/PM-11519
Applying a further fix to the previously related `browser` issue. …
=> [PM-11519] browser global variable triggering error fix jest

apps/cli/package.json, apps/desktop/src/package-lock.json, apps/desktop/src/package.json, package-lock.json, package.json
Revert bitwarden/clients#9819 due to build issues with mac desktop builds
=> Revert "[deps] Platform: Update argon2 to v0.41.1"

apps/browser/src/vault/popup/components/vault-v2/add-edit/add-edit-v2.component.ts
[PM-10705](https://bitwarden.atlassian.net/browse/PM-10705)
Lowercase the cipher type for add/edit in the extension refresh
https://github.com/user-attachments/assets/719a358a-8154-46d7-9475-afaa0cc68c37
[PM-10705]: …
=> [PM-10705] Lowercase Add/Edit header

apps/web/src/app/auth/settings/verify-email.component.html, apps/web/src/app/vault/individual-vault/vault-banners/vault-banners.component.html, bitwarden_license/bit-web/src/app/admin-console/providers/providers-layout.component.html, libs/components/src/banner/banner.component.html, libs/components/src/banner/banner.component.ts, libs/components/src/banner/banner.mdx, libs/components/src/banner/banner.stories.ts
https://bitwarden.atlassian.net/browse/CL-257
Update the banner component to use new colors. Update usage sites to use different `bitLink` color.
See banner Storybook …
=> [CL-257] update banner component styles

apps/browser/src/vault/popup/settings/trash-list-items-container/trash-list-items-container.component.ts, apps/browser/src/vault/popup/settings/trash.component.html
[PM-11620](https://bitwarden.atlassian.net/browse/PM-11620)
* Callout title should be title case
* Import TypographyModule …
=> [PM-11620] Typography bug fixes

apps/web/src/locales/en/messages.json
https://bitwarden.atlassian.net/browse/PM-11388?atlOrigin=eyJpIjoiOWVhNzllOTEzYmY3NDk3ZmFjNDM0NjY3ZTk4ZjJlNzMiLCJwIjoiaiJ9
Adds missing translation messages for components used in new view dialog: 
The `CipherViewComponent` that is wrapped by the new view dialog was previously used in `browser`, but is new to `web vault`. There are several translations that hadn't been ported over to web vault. This PR adds them. …
=> [PM-11388] [Defect] Section headers are missing for View {Item} on web

libs/tools/send/send-ui/src/send-list-items-container/send-list-items-container.component.html
https://bitwarden.atlassian.net/browse/PM-11621
This PR reduces the size of a the header text field in the send list to match the design for the extension refresh.
|Before|After|
---|---
|![Screenshot 2024-09-04 at 11 29 44 AM](https://github.com/user-attachments/assets/6a330ff6-42da-49dd-80d6-d0f76cb85582)|![Screenshot 2024-09-04 at 11 29 11 AM](https://github.com/user-attachments/assets/4770aa91-fb6d-47a2-905a-4a1e4b40eb09)| …
=> [PM-11621] - send list - reduce header size

libs/common/src/platform/services/app-id.service.ts
Remove comments from PR: #10835  …
=> [PM-11526] Remove Comments

apps/desktop/src/platform/services/sso-localhost-callback.service.ts
https://bitwarden.atlassian.net/browse/PM-11461
Fix sso jit provisioning which was missing the org identifier in the state; we were sending the wrong state (not the received but initial) to the sso component. …
=> [PM-11461] Fix jit proivisioning for snap desktop

apps/browser/src/platform/background.html
Add missing doctype declaration. …
=> [PM-11592] Add missing doctype

apps/cli/src/service-container/service-container.ts
https://bitwarden.atlassian.net/browse/PM-8013
To not log MAC failures for secure storage.
https://github.com/user-attachments/assets/b171d489-e3f0-4a2b-ac89-354c0ed79903 …
=> [PM-8013] CLI MAC failure logs

apps/browser/src/tools/popup/send/send-groupings.component.ts, apps/browser/src/tools/popup/send/send-type.component.ts
https://bitwarden.atlassian.net/browse/PM-11779
To upgrade to Typescript 5.3. we need to address: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-3.html#checks-for-super-accesses-on-instance-properties
- ❓ …
=> [PM-11779] Typescript 5.3: Fix-super-missuse-on-instance-properties

apps/browser/src/popup/app-routing.module.ts, libs/angular/src/utils/extension-refresh-redirect.ts
Blocks work on https://github.com/bitwarden/clients/pull/10451 for https://bitwarden.atlassian.net/browse/PM-9449
Related previous PR: https://github.com/bitwarden/clients/pull/10640
I need to be able to use the extension redirect function on desktop. 
n/a  …
=> Move extension refresh redirect util function to libs so other clients can use it

.github/CODEOWNERS
=> Add initial key-management CODEOWERSHIP

apps/web/src/app/billing/organizations/change-plan-dialog.component.html
=> [PM-11728] Run prettier

apps/desktop/src/app/app-routing.module.ts
Removes a duplicate desktop route I missed on https://github.com/bitwarden/clients/pull/10492. Hint component routing is now handled [here](https://github.com/bitwarden/clients/pull/11034/files#diff-7ce475261cef5f7986cae55e5ef0fd00878aa54912a56a583bce8428ca64f864R119-R154). …
=> [PM-8116] Remove Duplicate Route

apps/web/src/404.html, apps/web/src/scss/forms.scss, libs/components/src/stories/colors.mdx, libs/components/src/tw-theme.css
[CL-397](https://bitwarden.atlassian.net/browse/CL-397)
We are removing the color `primary-500`, so this PR replaces any last instances with `primary-600` and deletes 500 from the codebase.
- 🤔 …
=> [CL-397] Remove primary-500

.github/workflows/build-desktop.yml
- [Card](https://bitwarden.atlassian.net/browse/BRE-315?atlOrigin=eyJpIjoiMjMwNDExODA3MDA3NDAzNmJmOTE5OWEwMzU1ZDExODgiLCJwIjoiaiJ9)
This PR updates the Desktop build workflow in order to push builds to TestFlight on `main`, `rc`, and `hotfix-rc-desktop` branches.
- [Test output alert](https://bitwarden.slack.com/archives/C074F5UESQ0/p1726187579622639). …
=> BRE-315 - Update workflow to push to TestFlight on protected branches

libs/vault/src/cipher-view/custom-fields/custom-fields-v2.component.html, libs/vault/src/cipher-view/view-identity-sections/view-identity-sections.component.html
https://bitwarden.atlassian.net/browse/PM-11468?atlOrigin=eyJpIjoiOTBkOTAwZmI0NzdhNGFiYmI1YjcxMjU5ZTJmYTNjYTgiLCJwIjoiaiJ9
Adds `data-testid` values for identity copy buttons, custom fields, and custom field copy buttons.
- ❓ …
=> PM-11468: Add data-testids for View Item pages

libs/tools/send/send-ui/src/send-list-items-container/send-list-items-container.component.html
https://bitwarden.atlassian.net/browse/PM-11633
This PR adds the appropriate hover affect for the send list item copy and delete buttons
|Before|After|
---|---
|![Screenshot 2024-09-17 at 11 37 23 AM](https://github.com/user-attachments/assets/849d36b6-adce-4435-9294-73eb5bc51ad3)|![Screenshot 2024-09-17 at 11 40 08 AM](https://github.com/user-attachments/assets/cb1fa367-c9f9-4dae-bb84-9fcb1e5a9959)| …
=> [PM-11633] - fix send list item button hover

apps/desktop/src/platform/main/biometric/biometrics.service.ts
https://bitwarden.atlassian.net/browse/PM-12238
On desktop, cancelling biometrics should not force a process reload every time, since we do not load any secret into ram that process reload should clear.
- …
=> [PM-12238] Don't process reload when cancelling biometrics

.github/workflows/build-desktop.yml
This PR fixes the alert message for Desktop builds to include the TestFlight build number in the alert message. …
=> Fix alert message for Desktop builds

apps/web/webpack.config.js
https://bitwarden.atlassian.net/browse/PM-11342
Fix 404 page lacking styles on nested pages. …
=> [PM-11342] Fix 404 missing styles

apps/web/src/connectors/duo-redirect.ts
[PM-10096](https://bitwarden.atlassian.net/browse/PM-10096)
Adding `duofederal.com` as a valid url per [Duo's Documentation](https://help.duo.com/s/article/8720?language=en_US). …
=> [PM-10096] Add `duofederal.com` as a valid url for connector

apps/web/src/locales/en/messages.json
https://bitwarden.atlassian.net/browse/PM-12381?atlOrigin=eyJpIjoiNDM4NDIzMzFiNzU5NDQyMzllZDcxODlkOTVmOTBmZDciLCJwIjoiaiJ9
Adds missing translation keys used in the add/edit custom field dialog.
- 🤔 …
=> PM-12381: [Defect] - Add/edit custom field modal issues

libs/tools/send/send-ui/src/send-form/components/send-details/send-details.component.html, libs/tools/send/send-ui/src/send-form/components/send-details/send-details.component.ts
https://bitwarden.atlassian.net/browse/PM-12361
This PR adds the send link with a copy button to the form when editing a send.
|Before|After|
---|---
|![Screenshot 2024-09-19 at 12 45 07 PM](https://github.com/user-attachments/assets/c38fe31c-f3a9-4ed5-b486-1c0e9d4f76c7)|![Screenshot 2024-09-19 at 12 44 44 PM](https://github.com/user-attachments/assets/cda051f4-880a-4bd3-8e75-7248dc8a765b)| …
=> [PM-12361] - add copy send link

libs/tools/send/send-ui/src/send-form/components/options/send-options.component.html, libs/tools/send/send-ui/src/send-form/components/options/send-options.component.ts
https://bitwarden.atlassian.net/browse/PM-12335
This PR hides the "Hide your email address from viewers" checkbox if the org policy doesn't allow hiding the email.
No UI changes, only logic.
- 🤔 …
=> [PM-12335] - disable hide email when in policy in send options

apps/web/src/app/billing/organizations/change-plan-dialog.component.html
https://bitwarden.atlassian.net/browse/AC-3060
- 🎨 …
=> [AC-3060][Defect] Change payment method text link is showing when upgrading Free org

libs/tools/send/send-ui/src/send-form/components/options/send-options.component.html, libs/tools/send/send-ui/src/send-form/components/send-details/send-details.component.html, libs/tools/send/send-ui/src/send-form/components/send-details/send-file-details.component.html, libs/tools/send/send-ui/src/send-form/components/send-details/send-file-details.component.ts
https://bitwarden.atlassian.net/browse/PM-12560
This PR fixes the existing send form UI defects.
|New|Edit|
---|---
|![Screenshot 2024-09-23 at 5 22 34 PM](https://github.com/user-attachments/assets/2344c2b3-d1b0-4787-94fd-1d82889ccac7)|![Screenshot 2024-09-23 at 5 22 12 PM](https://github.com/user-attachments/assets/fe253359-2e71-4bd8-8704-0eac2d49794a)| …
=> [PM-12560] - fix send form defects

package-lock.json, package.json
=> Pin regedit dependency

libs/components/src/form-field/password-input-toggle.directive.ts, libs/tools/send/send-ui/src/send-form/components/options/send-options.component.html, libs/tools/send/send-ui/src/send-form/components/send-details/send-details.component.html, libs/tools/send/send-ui/src/send-form/components/send-details/send-file-details.component.html
https://bitwarden.atlassian.net/browse/PM-12561
This PR adds the required data attributes to the send forms …
=> [PM-12561] - add data attrs for send form

libs/components/src/multi-select/scss/bw.theme.scss
[CL-457](https://bitwarden.atlassian.net/browse/CL-457)
This PR fixes the vertical centering of the input field in the select component. I also updated the multiselect so that the two components are using the same css overrides, which makes them look more uniform.
https://github.com/user-attachments/assets/7a8fcad5-c266-40f7-81ce-26ae9bd7551d
- 👍 …
=> [CL-457] Center input text for select and multiselect

apps/browser/src/tools/popup/send-v2/send-v2.component.html, apps/browser/src/tools/popup/send-v2/send-v2.component.spec.ts, apps/browser/src/tools/popup/send-v2/send-v2.component.ts, libs/tools/send/send-ui/src/services/send-items.service.spec.ts, libs/tools/send/send-ui/src/services/send-items.service.ts
https://bitwarden.atlassian.net/browse/PM-12704
This PR adds a loading state to the send list as well as updates the send service to properly emit when the loading has started and completed.
- 🤔 …
=> [PM-12704] - fix loading state for send list

libs/tools/send/send-ui/src/send-form/components/options/send-options.component.html, libs/tools/send/send-ui/src/send-form/components/options/send-options.component.ts, libs/tools/send/send-ui/src/send-form/send-form.module.ts
https://bitwarden.atlassian.net/browse/PM-12716
This PR adds the missing password generation function to the send form password. …
=> [PM-12716] - add missing password generation function to send form password

apps/web/src/app/billing/organizations/change-plan-dialog.component.ts
https://bitwarden.atlassian.net/browse/AC-3063
Correct Members seats is displayed but summary Total amount is not correct …
=> [AC-3063][Defect] Upgrade after updating the seats count - Total amount displayed is incorrect

apps/web/src/app/tools/reports/pages/exposed-passwords-report.component.html, apps/web/src/app/tools/reports/pages/reused-passwords-report.component.html, apps/web/src/app/tools/reports/pages/weak-passwords-report.component.html, apps/web/src/locales/en/messages.json
https://bitwarden.atlassian.net/browse/PM-12066
Add missing column headers to weak, exposed and reused password reports …
=> [PM-12066] Add missing column headers to reports

apps/browser/src/tools/popup/send-v2/add-edit/send-add-edit.component.html
https://bitwarden.atlassian.net/browse/PM-12505
This PR fixes the alignment and size of the delete button in the send form.
|Static|Loading|
---|---
|![Screenshot 2024-09-27 at 10 54 07 AM](https://github.com/user-attachments/assets/a8d44f7e-f6d0-42f9-9d92-63ce7ecf851e)|![Screenshot 2024-09-27 at 10 54 12 AM](https://github.com/user-attachments/assets/c1ec9c88-971d-4739-8f0e-42c4bde8fc32)| …
=> [PM-12505] - fix delete send button

libs/components/src/navigation/nav-group.stories.ts, libs/components/src/navigation/nav-item.component.html, libs/components/src/navigation/side-nav.component.html, libs/components/src/tw-theme.css
=> [CL-388] Update vertical nav colors for new palette

apps/browser/src/_locales/en/messages.json, apps/browser/src/tools/popup/send-v2/send-file-popout-dialog/send-file-popout-dialog-container.component.ts, libs/angular/src/utils/extension-refresh-swap.ts
https://bitwarden.atlassian.net/browse/PM-11927
This PR fixes the following bugs in the file send popout dialog
- There is a typo in the modal, where it says “te” instead of “the” 
- The modal is appearing even when creating a text send  …
=> [PM-11927] - fix file send popout copy and logic

apps/browser/src/tools/popup/send-v2/send-v2.component.html, libs/tools/send/send-ui/src/services/send-items.service.ts
https://bitwarden.atlassian.net/browse/PM-12774
This PR fixes an issue where the send filters were displayed when active sends were present. …
=> [PM-12774] - don't display filters when no sends are available

libs/auth/src/angular/anon-layout/anon-layout.stories.ts
https://bitwarden.atlassian.net/browse/PM-12694
To fix the `AnonLayoutComponent` storybook story that was broken in #11263
See storybook.  …
=> Auth/PM-12694 - Fix AnonLayout Storybook Story

apps/browser/src/autofill/popup/fido2/fido2.component.ts
PM-12367
Update fido2 overwrite passkey dialog type to match expected design
| --- | --- |
| ![Screenshot 2024-10-03 at 2 46 01 PM](https://github.com/user-attachments/assets/43c72ba9-b6c0-402b-985d-9422d8afc9ab) | ![Screenshot 2024-10-03 at 2 45 18 PM](https://github.com/user-attachments/assets/c71cb759-0664-48f7-adae-02e89803b628) |
- 🌱 …
=> [PM-12367] Update fido2 overwrite passkey dialog type

apps/browser/src/platform/popup/layout/popup-tab-navigation.component.ts
https://bitwarden.atlassian.net/browse/PM-13151
This PR reverts the change to remove the Send tab when sends are disabled as it was [communicated](https://bitwarden.atlassian.net/browse/PM-13146?focusedCommentId=72190) by design this was unintentionally added to the comps. …
=> [PM-13151] - revert change to removing send tab

apps/web/src/app/vault/components/vault-items/vault-items.component.ts
[PM-13253](https://bitwarden.atlassian.net/browse/PM-13253)
Ensure the bulk edit collection access menu option is available from the AC after the VaultBulkActions feature flag was removed.
- 🤔 …
=> [PM-13253] Fix Bulk edit collection access

libs/common/src/enums/feature-flag.enum.ts
https://bitwarden.atlassian.net/browse/PM-13233
Add the feature flag for access intelligence and default to false.  …
=> [PM-13233] Adding client side access intelligence feature flag

apps/desktop/src/app/tools/generator/credential-generator.component.html
https://bitwarden.atlassian.net/browse/PM-13173
Replace usage of tools-password-generator with tools-credential-generator after https://github.com/bitwarden/clients/pull/11398 has merged.
- 🤔 …
=> [PM-13173] Replace usage of tools-password-generator with tools-credential-generator

apps/browser/src/_locales/en/messages.json, apps/browser/src/autofill/popup/fido2/fido2.component.html
PM-12368
Fix copy and hardcoded copy strings to match expected design
=> [PM-12368] Bugfix - fix fido2 component copy translations

apps/browser/src/popup/scss/base.scss
[CL-472](https://bitwarden.atlassian.net/browse/CL-472)
The search input background color was getting overridden by some legacy browser CSS. This PR excludes the component from that css.
| <img width="375" alt="Screenshot 2024-09-30 at 3 18 00 PM" src="https://github.com/user-attachments/assets/5503adb8-1181-4399-8d8c-777a60429aea"> | ![Screenshot 2024-10-08 at 2 54 45 PM](https://github.com/user-attachments/assets/413b8cb0-a3d9-47a6-84b9-b206f2f57cba) |
- …
=> [CL-472] Fix search background color in extension

apps/desktop/desktop_native/napi/index.d.ts
The napi update in #10564 updates how the file is generated. This update the checked in file with the change. …
=> Run `npm run electron`

apps/browser/src/tools/popup/settings/about-page/about-page-v2.component.html
https://bitwarden.atlassian.net/browse/PM-13410
Design teak: Remove the right angle icon from about bitwarden button within settings …
=> [PM-13410] Remove right angle icon from about bitwarden button

.eslintrc.json, .github/whitelist-capital-letters.txt, .storybook/main.ts, .vscode/settings.json, apps/browser/src/_locales/en/messages.json, apps/browser/tsconfig.json, apps/desktop/src/locales/en/messages.json, apps/desktop/tsconfig.json, apps/web/src/locales/en/messages.json, apps/web/tsconfig.json, bitwarden_license/bit-common/tsconfig.json, bitwarden_license/bit-web/tsconfig.json, libs/shared/tsconfig.libs.json, libs/tools/card/README.md, libs/tools/card/jest.config.js, libs/tools/card/package.json, libs/tools/card/src/card.component.html, libs/tools/card/src/card.component.ts, libs/tools/card/src/card.stories.ts, libs/tools/card/src/index.ts, libs/tools/card/test.setup.ts, libs/tools/card/tsconfig.json, libs/tools/card/tsconfig.spec.json, tsconfig.eslint.json, tsconfig.json
https://bitwarden.atlassian.net/browse/CL-425
This PR adds a new card-like component to be used initially for the new reports initiative but will likely see re-use elsewhere.
|LTR|RTL|
---|---
|![Screenshot 2024-10-02 at 5 25 42 PM](https://github.com/user-attachments/assets/84ebb803-3396-4fc0-9924-e6175fc23433)|![Screenshot 2024-10-09 at 11 19 43 AM](https://github.com/user-attachments/assets/b4d7c05a-74ec-442c-a2e8-58ddf4292532)|
- Updated any …
=> [CL-425] - add tools card component

apps/browser/src/tools/popup/generator/credential-generator.component.ts
https://bitwarden.atlassian.net/browse/PM-13264
This PR fixes an issue where the links in the credential generator were non-functional because of a missing `RouterModule` import. …
=> [PM-13264] - fix link in credential generator

apps/web/src/locales/en/messages.json
[PM-13442](https://bitwarden.atlassian.net/browse/PM-13442)
The custom fields help text translations were missing from the web
<video src="https://github.com/user-attachments/assets/6acf64a3-d403-4ab4-b6b5-5ca8e149d40c" /> …
=> [PM-13442] Add custom field copy to web

apps/browser/src/popup/app-routing.module.ts, apps/web/src/app/oss-routing.module.ts, bitwarden_license/bit-web/src/app/admin-console/providers/providers-routing.module.ts
https://bitwarden.atlassian.net/browse/PM-13318
Initial PR: [#11513](https://github.com/bitwarden/clients/pull/11513)
To update a few missed page titles & subtitles to the proper new structure to ensure they are translated. 
Hint Before:
Hint after: …
=> Auth/PM-13318 - Update remaining page titles to new translation interface

apps/web/src/app/vault/components/vault-items/vault-items.stories.ts
N/A
Ensure the collection checkboxes continue to show in the storybook for Vault Items.
See storybook build. …
=> Fix vault items storybook

apps/browser/package.json, apps/browser/src/manifest.json, apps/browser/src/manifest.v3.json
We need to create a beta version for the extension refresh beta build that will allow us to turn the flag on in Launch Darkley. …
=> PM-000 | update version for extension refresh beta

libs/tools/card/src/card.stories.ts
Fix stories title for card-component …
=> Fix stories title for card-component

.github/workflows/auto-branch-updater.yml, .github/workflows/automatic-issue-responses.yml, .github/workflows/automatic-pull-request-responses.yml, .github/workflows/brew-bump-desktop.yml, .github/workflows/build-browser.yml, .github/workflows/build-cli.yml, .github/workflows/build-desktop.yml, .github/workflows/build-web.yml, .github/workflows/chromatic.yml, .github/workflows/crowdin-pull.yml, .github/workflows/deploy-web.yml, .github/workflows/enforce-labels.yml, .github/workflows/lint.yml, .github/workflows/locales-lint.yml, .github/workflows/publish-cli.yml, .github/workflows/publish-desktop.yml, .github/workflows/publish-web.yml, .github/workflows/release-browser.yml, .github/workflows/release-cli.yml, .github/workflows/release-desktop-beta.yml, .github/workflows/release-desktop.yml, .github/workflows/release-web.yml, .github/workflows/retrieve-current-desktop-rollout.yml, .github/workflows/scan.yml, .github/workflows/staged-rollout-desktop.yml, .github/workflows/stale-bot.yml, .github/workflows/test.yml, .github/workflows/version-auto-bump.yml, .github/workflows/version-bump.yml
- [Card](https://bitwarden.atlassian.net/browse/BRE-372) …
=> [BRE-372] - Clean up document start

apps/web/src/app/admin-console/organizations/policies/policy-edit.component.html, apps/web/src/app/admin-console/organizations/policies/policy-edit.component.ts
[PM-13652](https://bitwarden.atlassian.net/browse/PM-13652)
Tech Debt: remove Promise and appApiAction directive from policy-edit.component …
=> [PM-13652] Remove appApiAction directive and Promise from policy-edit.component

libs/auth/src/angular/registration/registration-finish/registration-finish.component.ts
https://bitwarden.atlassian.net/browse/PM-13368
To add Org 2FA required policy support to the new registration with email verification flow. 
https://github.com/user-attachments/assets/d6cbf5a8-ac68-4d8e-bf16-cf7f2bbf61c7
- ❓ …
=> Auth/PM-13368 - Registration with Email Verification - Registration Finish - 2FA Support

libs/components/src/icon/icon.mdx
n/a
To update the icon docs to include a section about viewbox scaling and the need to remove any hardcoded widths & heights for proper behavior. 
See storybook publish. …
=> Update Icon Docs to include information on viewbox scaling

apps/browser/src/tools/popup/send-v2/send-created/send-created.component.ts
https://bitwarden.atlassian.net/browse/PM-11926
This PR fixes an issue in Safari where the translation service doesn't seem to be interpolating number variables so string casting is required.
- 🤔 …
=> [PM-11926] - Safari- send created page fix expiration date

libs/auth/src/angular/registration/registration-start/registration-start-secondary.component.html, libs/auth/src/angular/registration/registration-start/registration-start-secondary.component.ts
https://bitwarden.atlassian.net/browse/PM-13820
To add a missing `bitLink` directive to the Log In anchor. 
n/a …
=> Auth/PM-13820 - RegistrationStartSecondaryComp - add bitLink to link

apps/web/src/app/tools/access-intelligence/access-intelligence.component.html, apps/web/src/app/tools/access-intelligence/access-intelligence.component.ts, apps/web/src/app/tools/access-intelligence/password-health-members.component.html, apps/web/src/app/tools/access-intelligence/password-health-members.component.ts, apps/web/src/app/tools/access-intelligence/password-health.mock.ts
https://bitwarden.atlassian.net/browse/PM-13453
This PR adds a health report table component with an additional member count field …
=> [PM-13453] - Health report raw data with member count component

libs/tools/send/send-ui/src/send-form/components/options/send-options.component.html, libs/tools/send/send-ui/src/send-form/components/options/send-options.component.ts
https://bitwarden.atlassian.net/browse/PM-13809
This PR adds a "Remove Password" button to the send form if the send currently has a password.
https://github.com/user-attachments/assets/4455e39e-3071-4585-a99c-4cc1b080c84d
- ❓ …
=> [PM-13809] - add remove password button

.github/CODEOWNERS
https://bitwarden.atlassian.net/browse/PM-13959
Adding the new tools team files in bitwarden_license to be assigned to the tools team in github CODEOWNERSHIP …
=> [PM-13959] Tools team code ownership for license lib files

apps/browser/src/vault/popup/components/vault-v2/vault-list-filters/vault-list-filters.component.html
[
](https://bitwarden.atlassian.net/browse/PM-12309)
Update chip styling …
=> Updating chipSelect to be the new styling

libs/tools/generator/components/src/credential-generator.component.html, libs/tools/generator/components/src/username-generator.component.html
https://bitwarden.atlassian.net/browse/PM-13976
Add IDs targetable by automated tests to the username and forwarder dropdowns
=> [PM-13976] Add test ids to username and forwarder inputs

apps/web/src/connectors/sso.ts, libs/auth/src/angular/login/default-login-component.service.spec.ts, libs/auth/src/angular/login/default-login-component.service.ts
https://bitwarden.atlassian.net/browse/PM-8111
To fix the Extension SSO flow that I broke refactoring the SSO connector. The clientId needs to be in the state or it won't be present on redirect from SSO provider. 
Broken behavior:
https://github.com/user-attachments/assets/c8f07774-23ce-4e5b-bcfc-1591788ed874
Fixed behavior:
https://github.com/user-attachments/assets/f17fd7c1-65c3-4311-a705-f9ca139b897e …
=> Auth/PM-8111 - LoginComponent Refactor Bug - Fix Extension SSO

libs/tools/send/send-ui/src/send-form/components/options/send-options.component.html, libs/tools/send/send-ui/src/send-form/components/options/send-options.component.ts
https://bitwarden.atlassian.net/browse/PM-13809
This PR modifies the password label after removing a password. …
=> [PM-13809] - show New password after removing a password

apps/browser/src/popup/scss/base.scss
[PM-8625](https://bitwarden.atlassian.net/browse/PM-8625)
This PR increases the width of the browser extension to 380px, which matches the width when the extension is popped out. …
=> [PM-8625] Increase popup width

libs/tools/generator/components/src/username-generator.component.ts
https://bitwarden.atlassian.net/browse/PM-14002
The entries within the username and forwarders drop-down weren't showing
- **Fix "Forwarded email alias" not showing in drop-down -** https://github.com/bitwarden/clients/commit/9a466777ab189b32450f46a38785978785ee9f75
- **Fixed username and forwarder options not showing -** https://github.com/bitwarden/clients/commit/7190d3cf280b047fbb37d3e85f7e75b2a9d50950
- Options were being translated twice
- Updated …
=> [PM-14002] Fix username generator from vault item

apps/web/src/app/tools/access-intelligence/access-intelligence.component.html, apps/web/src/app/tools/access-intelligence/access-intelligence.component.ts, apps/web/src/locales/en/messages.json
https://bitwarden.atlassian.net/browse/PM-13979
This PR adds the remaining UI elements to the access intelligence page, not including the table components but the content above. …
=> [PM-13979] - add remaining components to access intelligence page

libs/admin-console/src/common/collections/services/default-vnext-collection.service.spec.ts
Follow up from #11705. 
Fix `DefaultVNextCollectionService` tests. #11684 added an extra parameter to some asserted calls and my branch was out of date when I merged in to `main`. Update the tests to account for the new parameter.
- ❓ …
=> Fix vNextCollectionService tests

libs/tools/send/send-ui/src/send-form/components/send-details/send-details.component.html, libs/tools/send/send-ui/src/send-form/components/send-details/send-details.component.ts
https://bitwarden.atlassian.net/browse/PM-14022
This PR changes the send link input from `readonly` to `disabled` in order to match design specs.
|Before|After|
---|---
|![Screenshot 2024-10-25 at 3 24 46 PM](https://github.com/user-attachments/assets/ec5f5fbc-b705-4f47-854d-9c5b65adf2b9)|![Screenshot 2024-10-25 at 3 24 20 PM](https://github.com/user-attachments/assets/aaecdb4d-1260-4933-ab1d-3d1215e77e3b)| …
=> [PM-14022] - change send link to disabled

libs/auth/src/angular/login/login.component.ts
https://bitwarden.atlassian.net/browse/PM-3301?atlOrigin=eyJpIjoiM2Y4Y2ZjYzczOTAwNDZiNWJlZDVkYTcwYzYzYTc2MzYiLCJwIjoiaiJ9
Move the "incorrect password" error from a toast to an inline error.
- 🤔 …
=> [PM-3301] Move incorrect username or password error to inline field error

libs/common/src/platform/abstractions/sdk/sdk.service.ts
Document `userClient$` not supporting `firstValueFrom`
- …
=> Document `firstValueFrom` not being supported

apps/web/src/app/tools/access-intelligence/no-priority-apps.component.ts, apps/web/src/app/tools/access-intelligence/password-health-members.component.html, apps/web/src/app/tools/access-intelligence/password-health-members.component.ts, apps/web/src/locales/en/messages.json, libs/components/src/icon/icons/index.ts, libs/components/src/icon/icons/security.ts
https://bitwarden.atlassian.net/browse/PM-14038
This PR finishes the remaining UI elements for the priority applications UI
https://github.com/user-attachments/assets/0ac299ad-0489-4abc-ba4e-f17dddb509ce
- …
=> [PM-14038] - priority applications UI

apps/browser/src/auth/popup/account-switching/services/account-switcher.service.spec.ts, apps/web/src/app/key-management/key-rotation/user-key-rotation.service.ts, libs/angular/src/auth/guards/auth.guard.spec.ts, libs/angular/src/auth/guards/lock.guard.spec.ts, libs/auth/src/angular/lock/lock.component.ts, libs/common/spec/fake-account-service.ts, libs/common/src/auth/abstractions/account.service.ts, libs/common/src/auth/services/account.service.spec.ts, libs/common/src/auth/services/account.service.ts, libs/common/src/auth/services/password-reset-enrollment.service.implementation.spec.ts, libs/common/src/platform/services/fido2/fido2-authenticator.service.spec.ts, libs/common/src/platform/state/implementations/default-active-user-state.spec.ts
n/a b/c BEEEP time work
To add some small misc improvements to the `AccountService` - (1) prefer `null` over `undefined` and (2) add new a new `Account` type so we don't have to use `{ id: UserId } & AccountInfo` everywhere.
- ❓ …
=> BEEEP - Auth AccountService Improvements

apps/browser/src/background/main.background.ts, apps/browser/src/popup/app.component.ts, apps/cli/src/service-container/service-container.ts, apps/desktop/src/app/app.component.ts, apps/web/src/app/app.component.ts, libs/common/src/platform/abstractions/sdk/sdk.service.ts, libs/common/src/platform/services/sdk/default-sdk.service.ts
https://bitwarden.atlassian.net/browse/PM-14180
Improve error logging to include some additional information about the error. …
=> [PM-14180] Provide more debugging details in wasm-debug

apps/web/src/app/billing/organizations/organization-subscription-cloud.component.html, apps/web/src/app/billing/organizations/organization-subscription-cloud.component.ts, libs/common/src/billing/models/response/organization-billing-metadata.response.ts
https://bitwarden.atlassian.net/browse/PM-14275
1. Show the subscription if the user is an owner of an organization managed by a reseller.
2. Show just self-host when the user is an owner of an organization managed by a consolidated billing MSP. …
=> [PM-14275] Resolve reseller & CB MSP organization owner experience for subscription page

apps/web/src/app/billing/organizations/organization-plans.component.html
https://bitwarden.atlassian.net/browse/PM-13740
This PR adds `bit-error-summary` to the organization plans component. …
=> [PM-13740] - add error summary to organization plans

apps/web/src/app/billing/organizations/billing-sync-api-key.component.html, apps/web/src/app/billing/organizations/billing-sync-key.component.html
https://bitwarden.atlassian.net/browse/PM-11698
This PR fixes the header size in the billing sync dialogs. …
=> [PM-11698] - fix header in billing sync dialog

apps/browser/src/tools/popup/send-v2/send-created/send-created.component.spec.ts
https://bitwarden.atlassian.net/browse/PM-14358
This PR fixes the send-created specs tests so they pass when run locally in a daylight savings timezone. …
=> [PM-14358] - fix send-created tests

apps/web/src/app/auth/settings/account/danger-zone.stories.ts
https://bitwarden.atlassian.net/browse/PM-11407
Fix Chromatic test failure due to missing import in dagner zone story. …
=> [PM-11407] Fix story for danger zone component

apps/web/src/app/auth/settings/account/danger-zone.stories.ts
https://bitwarden.atlassian.net/browse/PM-11407
Fixes the Danger Zone UI story and mocks the missing service class. …
=> [pm-11407] fix UI story for danger zone component

apps/desktop/src/locales/en/messages.json
https://bitwarden.atlassian.net/browse/PM-14430
fix SSH casing to be all caps in settings and floating menu helper text
https://github.com/user-attachments/assets/60d9d671-275d-4cd7-9e4e-8d6350d7b9f0
- 🤔 …
=> fix SSH casing

package-lock.json, package.json
Bump SDK ahead of RC cut
This version contains:
- GPL license
- Function to get SDK version …
=> chore: bump SDK to 0.1.7

scripts/tsconfig.json
The TypeScript update broke locale tests, to fix this we need to define moduleResolution manually as mentioned in the TS changelog. …
=> Fix locale test after typescript upgrade

package.json
These types were included by a sub-dependency before the dependency supported TypeScript. The dependency then moved to native TS, but these types were still included, causing then to clash with the native ones. These are no longer included and so we no longer need this hack …
=> chore: remove post-install type hack

libs/common/src/services/api.service.ts
Fixes bug introduced in #11605 where we have the parameters switched up. …
=> [PM-13804] Reverse Arguments

apps/desktop/src/locales/en/messages.json, apps/desktop/src/vault/app/vault/add-edit.component.ts
https://bitwarden.atlassian.net/browse/PM-14215
Forgot to handle the key type unsupported case during import, leading to silent errors in some cases. …
=> [PM-14215] fix unsupported key type error message

.github/workflows/build-web.yml
- [Slack](https://bitwarden.slack.com/archives/C024Z7LQNLB/p1731005608786019)
This PR adds a check to the `trigger-web-vault-deploy` job so that it doesn't run when the workflow is triggered by `pull_request_target`. …
=> Add event_name check to Deploy Web trigger job

.github/workflows/build-web.yml
Fixes missing quotes in `if` key. …
=> Fix quotes

.github/workflows/build-browser.yml, .github/workflows/build-cli.yml, .github/workflows/build-desktop.yml, .github/workflows/build-web.yml
- [Card](https://bitwarden.atlassian.net/browse/BRE-412?atlOrigin=eyJpIjoiNDRmN2I5MzQyNDNkNDA4ODhjZGE5MzhmYTM3MzI5YjUiLCJwIjoiaiJ9)
This PR adds a check so the `Check for failures` job does not trigger on `pull_request_target` events.
- ❓ …
=> BRE-412 - Add check for trigger event

apps/browser/src/vault/popup/components/vault-v2/item-more-options/item-more-options.component.ts
[PM-13892](https://bitwarden.atlassian.net/browse/PM-13892)
The `item-more-options` component was configuring the `canClone$` observable on `ngOnInit` which only fires once. This was a problem when the component was being cached by the `cdkVirtualScroll` and changing the `cipher` input without re-creating the component (e.g. not calling `ngOnInit` again).
Updating the `cipher` input to set an internal behavior subject allows the `canClone$` observable to react to changes to the behavior subject and ensure the value corresponds to the current cipher. …
=> [PM-13892] Browser Refresh - Fix clone menu option

apps/desktop/src/platform/services/electron-log.service.spec.ts
Fix test fail introduced in https://github.com/bitwarden/clients/pull/10207 …
=> Fix electron-log test

apps/web/src/locales/en/messages.json
https://bitwarden.atlassian.net/browse/PM-14810
fixed SSH casing on Web Vault item type …
=> PM-14810/ssh-not-all-caps-on-web-vault-item-type

libs/common/src/enums/feature-flag.enum.ts
[PM-14418](https://bitwarden.atlassian.net/browse/PM-14418)
Add `security-tasks` feature flag. …
=> [PM-14418] Add security-tasks feature flag

.github/workflows/build-browser.yml, .github/workflows/build-cli.yml, .github/workflows/build-desktop.yml, .github/workflows/build-web.yml
Another check run follow-up.
Some steps relied on branch name checks, but we also need to avoid the PR target event. …
=> Use correct event and branch targets for some workflow steps

package-lock.json
Bump browser version to 2024.11.1 manually due to error in the repository management workflow: https://github.com/bitwarden/clients/actions/runs/11816189946/job/32918960921. One place to update version left after: https://github.com/bitwarden/clients/pull/11980 PR. …
=> Bump browser version in package-lock.json

.github/workflows/build-web.yml
- [Card](https://bitwarden.atlassian.net/browse/BRE-424?atlOrigin=eyJpIjoiMTIxYzFiM2M0MzhhNDZlODlhMWIzN2VjNGRmYjc2YjgiLCJwIjoiaiJ9)
This PR updates the logic for the Docker image tag so that it supports the `pull_request_target` trigger. …
=> BRE-424 - Change Docker image tag logic to support pull_request_target trigger

.github/workflows/repository-management.yml
Fix github token generating in `repository-management.yml` workflow …
=> Fix github token generating in repository-management.yml workflow

libs/angular/src/vault/components/add-edit.component.ts
https://bitwarden.atlassian.net/browse/PM-13829
This PR expands the check on unassigned items to include an empty array. …
=> [PM-13829] Add check for empty array when deleting unassigned items

.github/workflows/build-desktop.yml, apps/desktop/resources/entitlements.mac.plist, apps/desktop/resources/entitlements.mas.inherit.plist, apps/desktop/resources/entitlements.mas.plist
Fix DMG build not running
- 🎨 (`:art:`) for suggestions …
=> revert: recent changes to build-desktop.yml and entitlements

apps/browser/src/platform/services/sdk/browser-sdk-client-factory.ts
Webpack seems to always convert imports to be async. This causes a issue where init_sdk is not always initialized before we call it. To resolve this I added a promise we can await in MV3 mode, and also defined a timeout which throws an error we can use to identify if we have issues loading the module.
- 📝 …
=> Ensure we await for the wasm module to load

libs/components/src/item/item.component.html
[CL-470](https://bitwarden.atlassian.net/browse/CL-470)
Decreasing the focus ring size on `bit-item` by 1px
| before | after |
|<img width="416" alt="Screenshot 2024-11-15 at 9 22 41 AM" src="https://github.com/user-attachments/assets/15e139f8-1014-4778-b7a9-85018c351e93">  |  <img width="399" alt="Screenshot 2024-11-15 at 9 22 25 AM" src="https://github.com/user-attachments/assets/96a523b0-9eec-4829-95cd-939c83f89007"> |
- Updated …
=> [CL-470] decrease bit-item ring size

.github/workflows/build-browser.yml
Fix broken browser build after merge conflict.
- 🎨 …
=> Fix broken browser build

README.md
FIx linting issues introduced with https://github.com/bitwarden/clients/pull/12027
I didn't catch em before merging it 🙈  …
=> Fix linting on main

apps/web/src/app/admin-console/organizations/policies/password-generator.component.html, apps/web/src/app/admin-console/organizations/policies/password-generator.component.ts
https://bitwarden.atlassian.net/browse/PM-15058
Align HTML min/max constraints with generator configurations so that angular validation and HTML error messages are consistent with one another.
=> [PM-15058] fix admin console hmtl constraints

.github/workflows/build-cli.yml, .github/workflows/build-desktop.yml, .github/workflows/deploy-web.yml, .github/workflows/test.yml
https://bitwarden.atlassian.net/browse/BRE-443
- Some workflow linter works before deploying `bwwl` org-wide …
=> [BRE-443] - Fix Linting pre bwwl Deployment

apps/browser/src/auth/popup/settings/account-security.component.ts
https://bitwarden.atlassian.net/browse/PM-13192?atlOrigin=eyJpIjoiOGU3OTFkZTUzM2MyNDk2ODlhMDI4NTM3MjM1NWI0ODQiLCJwIjoiaiJ9
Remove `startWith` to prevent log out toast warning from showing on page init.
https://github.com/user-attachments/assets/09a6b33e-8118-4849-8d99-c3936b00507c
https://github.com/user-attachments/assets/c0d797b9-dfc1-4391-ba6e-8738e25b2c34 …
=> [PM-13192] [Defect] - Account Security settings not converted to use bit-select

apps/web/src/app/billing/shared/payment/payment-v2.component.html, apps/web/src/app/billing/shared/verify-bank-account/verify-bank-account.component.html, apps/web/src/app/billing/shared/verify-bank-account/verify-bank-account.component.ts, apps/web/src/locales/en/messages.json, libs/common/src/billing/models/request/verify-bank-account.request.ts
https://bitwarden.atlassian.net/browse/PM-15048
Updates the bank account verification functionality behind the Stripe Sources API deprecation flag to use Stripe's updated statement descriptor verification approach.
https://github.com/user-attachments/assets/cd820b28-3ce8-482d-ba26-69ad97f6bae8
- 📝 (`:memo:`) …
=> Update bank account verification to use statement descriptor

libs/tools/generator/components/src/password-generator.component.ts
https://bitwarden.atlassian.net/browse/PM-15148
Fix an issue with toggle group entry on password-generator not being displayed properly on non-English clients …
=> [PM-15148] Fix toggle entry not displaying correctly on non-English clients

apps/browser/src/platform/popup/layout/popup-layout.stories.ts, apps/browser/src/platform/popup/layout/popup-tab-navigation.component.html, apps/browser/src/platform/popup/layout/popup-tab-navigation.component.ts
https://bitwarden.atlassian.net/browse/PM-15138
- **Ensure labels on nav-buttons can be translated -** https://github.com/bitwarden/clients/commit/c9be7dd52e71009123e1cdfd84fd435e9eb9e4c9 
- Introduce using i18n by importing JslibModule
- Use i18n within markup
- Ensure navButtons.labels is a key that is present in the en/messages.json
https://github.com/user-attachments/assets/8861462d-84e2-4ec5-87bd-f5b671a98932 …
=> [PM-15138] Ensure labels on nav-buttons can be translated

apps/browser/src/platform/popup/layout/popup-tab-navigation.component.html
https://bitwarden.atlassian.net/browse/PM-15191
While https://github.com/bitwarden/clients/pull/12084 did update the labels to show translations, it was missed to update the `button.title` which is used for tooltips and possibly also SR announcements. …
=> [PM-15191] Add translation to navButton.title

libs/tools/generator/core/src/engine/data.ts
https://github.com/bitwarden/clients/issues/12098
Fix password generator ascii sets, mistakenly swapped by https://github.com/bitwarden/clients/pull/10032
=> [PM-15353] [PM-15167] Fix password generator ascii ambiguous sets

apps/desktop/desktop_native/core/Cargo.toml
There was a conflict between versions in napi and core, which started causing the builds to fail when the version was pinned in #12121   …
=> Fix conflict with pinned dependency

apps/web/src/connectors/duo-redirect.ts
https://bitwarden.atlassian.net/browse/PM-15384
Adjust Duo URL validation.
=> validate proper duo hostnames

libs/components/src/toggle-group/toggle.component.html, libs/components/src/toggle-group/toggle.component.ts
[CL-513](https://bitwarden.atlassian.net/browse/CL-513)
The toggle component's title was not being set within an Angular lifecycle, which was causing change detection errors. 
| ![Screenshot 2024-11-25 at 2 34 20 PM](https://github.com/user-attachments/assets/600805fe-80f0-4dd5-b379-76cfd6b85b0b) | ![Screenshot 2024-11-25 at 2 32 20 PM](https://github.com/user-attachments/assets/77dee742-1ff4-4091-a4dd-b46ea2471155) | …
=> [CL-513] Fix lifecycle order for toggle title attribute

libs/common/src/platform/services/file-upload/bitwarden-file-upload.service.ts
=> fix: lint after PM-13923

apps/browser/src/background/main.background.ts, apps/browser/src/platform/services/sdk/browser-sdk-client-factory.ts, apps/browser/src/popup/services/services.module.ts, libs/common/src/platform/services/sdk/default-sdk.service.ts
https://bitwarden.atlassian.net/browse/PM-15444
Increase WASM timeout to 10s, and add a recoverable error if it takes more than 3s to better understand how long it actually takes. …
=> [PM-15444] Increase WASM timeout to 10s

apps/browser/src/vault/popup/services/vault-ui-onboarding.service.ts
[PM-7306](https://bitwarden.atlassian.net/browse/PM-7306)
This PR updates the release date so that new accounts created after the browser refresh is released will see the onboarding module. 
- 🤔 …
=> PM-7306 | browser refresh onboarding module: update release date

apps/browser/src/vault/popup/components/vault/vault-filter.component.html, apps/browser/src/vault/popup/components/vault/vault-filter.component.ts, apps/desktop/src/vault/app/vault/vault-filter/filters/type-filter.component.html, apps/desktop/src/vault/app/vault/vault-filter/filters/type-filter.component.ts, apps/web/src/app/vault/individual-vault/vault-filter/components/vault-filter.component.ts, apps/web/src/app/vault/org-vault/vault-filter/vault-filter.component.ts
https://bitwarden.atlassian.net/browse/PM-15541
Hides the ssh key item filters behind the ssh feature flag. …
=> [PM-15541] Hide ssh key filter behind feature flag

apps/browser/src/auth/popup/settings/account-security.component.ts
https://bitwarden.atlassian.net/browse/PM-15517?atlOrigin=eyJpIjoiNmY2MzU2YWQwNWUxNDA5MzkzMDg0Yjc4ZTAxNzViZjIiLCJwIjoiamlyYS1zbGFjay1pbnQifQ
Hotfix change, needs to be cherry picked. …
=> [PM-15517] Fix biometrics enabling in extension

apps/desktop/src/platform/services/ssh-agent.service.ts
https://bitwarden.atlassian.net/browse/PM-15083
Disables syncing organization keys to the ssh agent. We can re-evaluate later whether we allow it via an org policy. …
=> [PM-15083] Disable ssh agent for organization items

.github/CODEOWNERS
Remove the SM team from CODEOWNERS …
=> Remove SM team from CODEOWNERS

apps/cli/src/service-container/service-container.ts, libs/angular/src/services/injection-tokens.ts, libs/angular/src/services/jslib-services.module.ts, libs/auth/src/common/services/login-strategies/login-strategy.service.ts
[https://bitwarden.atlassian.net/browse/PM-13659](https://bitwarden.atlassian.net/browse/PM-13659?atlOrigin=eyJpIjoiOWIyMjM4ZDZmM2M2NDk3NjljOTExZDAzMjdkYTVjM2EiLCJwIjoiaiJ9)
Trying to fix this https://github.com/bitwarden/clients/pull/12201 not working in deployed environments when it works locally. 
To try to fix the existing 2FA timeout solution only working locally, but not in a deployed env like our US dev env. The issues likely stem from the handler being executed outside the Angular context. 
https://github.com/user-attachments/assets/5bf0b647-a364-4453-95ae-783cc619e41a
https://github.com/user-attachments/assets/5d017529-4505-4ba1-b045-753d37838de5
https://github.com/user-attachments/assets/02ce5ed9-f531-4a47-8f25-fa1bfe1010aa
- All formatters and …
=> Auth/PM-13659 - 2FA Timeout - Attempted Fix

.github/renovate.json
https://bitwarden.atlassian.net/browse/BRE-470
- Update BRE team name in Renovate configs …
=> [BRE-470] - Update Renovate Conf for BRE team

apps/web/src/app/billing/organizations/payment-method/organization-payment-method.component.html, apps/web/src/app/billing/shared/payment-method.component.html, apps/web/src/app/vault/individual-vault/vault-banners/vault-banners.component.html, apps/web/src/app/vault/org-vault/vault.component.html, bitwarden_license/bit-web/src/app/secrets-manager/overview/overview.component.html
https://bitwarden.atlassian.net/browse/CL-511
This PR updates link `linkType` prop from `contrast` to `secondary` for all components whose banners include a link, fixing a poor color contrast.
- 🤔 …
=> [CL-511] - add variant to links within banners

.github/CODEOWNERS
https://bitwarden.atlassian.net/browse/PM-14828
Assign a bunch of workflows to Platform. All concerned workflows are related
to building, testing, and linting applications in the monorepo. Some helper
actions, like version bumpers, are included because of development's role as
release branch managers in the CI/CD partnership model.
I suspect some of these are dead jobs based on last runtime, but we'll be
cleaning that up later. For now everything relevant has been assigned
outright. …
=> chore(codeowners): assign a bunch of workflows to Platform

libs/tools/generator/core/src/engine/username-randomizer.ts
https://bitwarden.atlassian.net/browse/PM-15872
Username generation should output 4 digits
=> [PM-15872] fix username generation character limit

apps/web/src/app/billing/settings/sponsored-families.component.ts
https://bitwarden.atlassian.net/browse/PM-15888
Prevent access to /settings/sponsored-families via the url when the policy is turn on.
https://github.com/user-attachments/assets/b4ebf1ef-ec72-4a78-8d75-c4ed11193a4c …
=> [PM-15888][Defect] When policy is ON, user can access Free Bitwarden Families settings page via the URL

libs/angular/src/directives/text-drag.directive.ts
=> fix: text-drag directive ts-strict error

bitwarden_license/bit-web/src/app/admin-console/providers/clients/vnext-clients.component.ts, bitwarden_license/bit-web/src/app/billing/providers/clients/vnext-manage-clients.component.ts
https://bitwarden.atlassian.net/browse/PM-12443
Resolves TS strict errors for new components …
=> [PM-12443] fix ts strict errors

apps/browser/src/_locales/az/messages.json, apps/browser/src/_locales/bg/messages.json, apps/browser/src/_locales/cs/messages.json, apps/browser/src/_locales/da/messages.json, apps/browser/src/_locales/de/messages.json, apps/browser/src/_locales/pt_PT/messages.json, apps/browser/src/_locales/ru/messages.json, apps/browser/src/_locales/sk/messages.json, apps/browser/src/_locales/uk/messages.json
Reverts bitwarden/clients#12386
=> Revert "Autosync Crowdin Translations for browser"

apps/browser/src/_locales/ko/messages.json
Resolve sideloading error of browser builds by reverting to last known good state (0df7b53bb48bce033c9a881e4592b5be6ac13803) of the KO message catalog file
=> Revert KO message catalog file to 0df7b53bb48bce033c9a881e4592b5be6ac13803

.github/CODEOWNERS
=> Add autofill to ssh-agent codeowners

libs/components/src/button/button.component.spec.ts, libs/components/src/form-field/bit-validators/forbidden-characters.validator.spec.ts, libs/components/src/form-field/bit-validators/trim.validator.spec.ts, libs/components/src/radio-button/radio-button.component.spec.ts, libs/components/src/toggle-group/toggle-group.component.spec.ts, libs/components/src/toggle-group/toggle.component.spec.ts, libs/components/tsconfig.json
I missed the component library tsconfig in #12235. This PR corrects taht omission. …
=> [PM-6684] Add strict to missed components tsconfig

apps/web/src/app/oss-routing.module.ts
https://bitwarden.atlassian.net/browse/PM-16172
To update web's lockV2 component to use the "Your vault is locked verbiage" that the other clients use as "Your account is locked" is not as clear as we would like.  …
=> Auth/PM-16172 - Web - LockV2 - make page title consistent with other clients

libs/components/src/async-actions/in-forms.stories.ts, libs/components/src/async-actions/standalone.stories.ts, libs/components/src/badge/badge.stories.ts, libs/components/src/breadcrumbs/breadcrumbs.stories.ts, libs/components/src/dialog/dialog.service.stories.ts, libs/components/src/toggle-group/toggle-group.stories.ts
[CL-135](https://bitwarden.atlassian.net/browse/CL-135)
When we converted components to be standalone, a couple of story declarations were missed and were causing errors. These should be imports now.
- 🤔 …
=> [CL-135] Fix imports for standalone component stories

apps/browser/src/background/main.background.ts
https://bitwarden.atlassian.net/browse/PM-16199
Make the sync on start of the service worker optional.  …
=> Make Sync Optional on SW Start

.github/workflows/build-desktop.yml
Occassionally I have been noticing some translations being overwritten/deleted, but even looking at Crowdin logs, I couldn't identify an issue. My hunch that this might have to do with some of the workflow changes we did recently. It also seemed to happen more on the desktop translations.
An example can be found here: https://github.com/bitwarden/clients/pull/12494/files#diff-b5b68762020612dac3271a29bf2caae1895766ecfcbf7dbb4063dc7185389d36R211
No changes can be found for that file within Crowdin for those strings.
Looking at some recent changes made to the workflows I saw that the Crowdin Push on desktop was slightly different than the other ones:
Related to https://github.com/bitwarden/clients/pull/11961
- All formatters and local linters executed and …
=> Fix Crowdin push

apps/web/src/app/auth/organization-invite/accept-organization.component.html, apps/web/src/app/auth/organization-invite/accept-organization.component.ts
https://bitwarden.atlassian.net/browse/PM-4949
Remove stale flow for AcceptOrganizationComponent and update template logic to use Tailwind.
* Removed stale flow code
* Updated template with tailwind styles and removed the main part of the ui and left a spinner.
* Updated function name to make more sense.
https://github.com/user-attachments/assets/58779013-b291-4385-a54b-defd1c103733
https://github.com/user-attachments/assets/25c1a35f-9be1-49ef-88e6-46193c4fbd50 …
=> [PM-4949] Update Accept Organization Invite Flow

apps/desktop/src/app/accounts/settings.component.html, apps/desktop/src/app/accounts/settings.component.ts
The open on login option does not currently work for Microsoft Store installed apps. So we are going to hide the option until https://github.com/electron/electron/issues/42016 becomes resolved. 
- 🤔 …
=> [PM-11948] Hide Open At Login Option On Windows Store Installs

libs/components/src/badge-list/badge-list.stories.ts
[CL-135](https://bitwarden.atlassian.net/browse/CL-135)
When we converted components to be standalone, a couple of story declarations were missed and were causing errors. These should be imports now. This PR follows #12464 because I missed this story. …
=> [CL-135] Fix import statement for standalone component

libs/common/src/autofill/utils.spec.ts, libs/common/src/autofill/utils.ts
PM-16667
Fix broken/flaky tests in the New Year. See commented lines.
=> [PM-16667] Fix flaky card expiry tests

bitwarden_license/bit-common/src/tools/reports/risk-insights/services/risk-insights-report.service.ts
https://bitwarden.atlassian.net/browse/PM-16484
Fixing at risk member count update …
=> [PM-16484] Fixing the at risk member count update

.github/workflows/build-browser.yml
- [Card](https://bitwarden.atlassian.net/browse/BRE-534?atlOrigin=eyJpIjoiZmRjOWY2NWVlMmYzNGE5Y2JlZTU4YTE1ZjlmYjg1YWMiLCJwIjoiaiJ9)
This PR updates the Build Browser workflow in order to parallelize building the different extensions.  This reduces the time to run the workflow significantly.
[Test Run](https://github.com/bitwarden/clients/actions/runs/12563470882) …
=> BRE-534 - Update workflow to parallelize extension builds

bitwarden_license/bit-web/src/app/billing/providers/subscription/provider-subscription.component.html, bitwarden_license/bit-web/src/app/billing/providers/subscription/provider-subscription.component.ts
https://bitwarden.atlassian.net/browse/PM-16664
- 🎨 …
=> [PM-16664] Fix annual pricing for billable providers

bitwarden_license/bit-web/src/app/billing/providers/subscription/provider-subscription.component.html, bitwarden_license/bit-web/src/app/billing/providers/subscription/provider-subscription.component.ts
Reverts bitwarden/clients#12662
=> Revert "[PM-16664] Fix annual pricing for billable providers"

apps/browser/src/auth/popup/account-switching/account-switcher.component.html, apps/browser/src/auth/popup/account-switching/account-switcher.component.ts, apps/browser/src/auth/popup/account-switching/account.component.html, apps/browser/src/auth/popup/account-switching/account.component.ts
https://bitwarden.atlassian.net/browse/PM-16258
Remove conditional rendering for extensionRefresh feature flag
| <img width="448" alt="image" src="https://github.com/user-attachments/assets/4084d4e0-a4df-45f0-a71d-3d2866dddc10" /> | <img width="448" alt="image" src="https://github.com/user-attachments/assets/ec6ddc4b-fcd8-4b56-88f0-94edfaeccce4" /> | …
=> [PM-16258] Remove v1 account switcher

apps/browser/src/background/runtime.background.ts, apps/browser/src/popup/app-routing.module.ts, apps/desktop/src/app/app-routing.module.ts, apps/desktop/src/platform/services/electron-key.service.ts, bitwarden_license/bit-web/src/app/secrets-manager/integrations/integrations.component.spec.ts, libs/common/src/platform/services/fido2/fido2-active-request-manager.spec.ts
https://bitwarden.atlassian.net/browse/PM-16838
Imports containing `/src/` are forbidden. …
=> [PM-16838] Fix bad imports for shared and platform code

.github/renovate.json
PM-16843
Assign Autofill team ownership of lit and @emotion/css packages …
=> [PM-16843] Assign Autofill team ownership of lit and @emotion/css packages

.github/workflows/deploy-web.yml, .github/workflows/lint.yml, .github/workflows/publish-cli.yml, .github/workflows/publish-desktop.yml, .github/workflows/release-browser.yml, .github/workflows/release-cli.yml, .github/workflows/release-desktop-beta.yml, .github/workflows/release-desktop.yml
Resolve all errors and warning exposed by the new workflow linter. The
following errors and warnings have been resolved:
```
Linting: .github/workflows/deploy-web.yml
- warning Job [setup] => Job outputs with more than one word should use an
underscore: (environment-url, environment-name, environment-artifact,
azure-login-creds, retrieve-secrets-keyvault, sync-utility,
sync-delete-destination-files, slack-channel-name)
- warning Job [artifact-check] => Job outputs with more than one word should
use an underscore: (artifact-build-commit)
Linting: .github/workflows/enforce-labels.yml
Linting: .github/workflows/lint.yml
- error Job [rust] => Workflow runner must be pinned
Linting: .github/workflows/locales-lint.yml
Linting: .github/workflows/publish-cli.yml
- warning Job [setup] => Job …
```
=> fix(ci): Resolve errors and warnings exposed by new workflow linter

apps/desktop/src/platform/services/ssh-agent.service.ts
https://bitwarden.atlassian.net/browse/PM-16886
This PR fixes the initialization of the ssh agent, that was intended to start properly directly once the flag is enabled. However, this lead to the message listeners being destroyed upon process reload, and never re-created because the ssh-agent was already inited. This PR fixes the behavior to always init the listeners, but make them dependent on a service-local featureflag variable. 
Additionally, there seems to have been a change to cipherservice, requiring a lock check instead of checking if the result of `getAllDecrypted` is null. …
=> [PM-16886] Fix ssh agent initialization

apps/web/src/app/vault/components/premium-badge.stories.ts
This PR adds/modifies some dependencies to the premium badge story that were causing the rendering to fail. …
=> update dependencies in premium-badge story

libs/tools/generator/core/src/policies/available-algorithms-policy.ts
https://bitwarden.atlassian.net/browse/PM-16897
Eliminate circular dependencies from `@bitwarden/generator-core` module to prepare for npm modularization.
=> [PM-16897] remove circular dependency

apps/browser/tailwind.config.js, apps/desktop/tailwind.config.js, apps/web/tailwind.config.js, libs/components/tailwind.config.base.js
https://bitwarden.atlassian.net/browse/PM-16889
The purpose of this PR is to add the KM lib into the tailwind configs. This is to fix tailwind styling that isn't being applied after moving the lock component over to the KM lib.
- ❓ …
=> [PM-16889] Add KM lib to tailwind configs

apps/web/src/app/auth/settings/security/device-management.component.html, apps/web/src/locales/en/messages.json
https://bitwarden.atlassian.net/browse/PM-16896
Device Management - remove the remove device option as it isn't ready for production yet without session de-authentication implemented.  …
=> Auth/PM-16896 - Device Management - Remove 3 dot menu and remove text from table description

.github/workflows/repository-management.yml
This PR updates the checkout step for the cherry pick job so that all branches and tags are checked out. This should fix the cherry pick job finding the `rc` or any `hotfix-rc` branch. …
=> Update checkout action for cherry pick job

bitwarden_license/bit-web/src/app/tools/reports/member-access-report/services/member-access-report.abstraction.ts, bitwarden_license/bit-web/src/app/tools/reports/member-access-report/services/member-access-report.service.spec.ts, libs/common/src/tools/send/models/domain/send.spec.ts, libs/common/src/tools/send/services/send.service.spec.ts, libs/importer/src/components/lastpass/lastpass-direct-import.service.ts, libs/tools/generator/components/src/credential-generator.component.ts, libs/tools/generator/components/src/password-generator.component.ts, libs/tools/generator/components/src/username-generator.component.ts
https://bitwarden.atlassian.net/browse/PM-16927
Addresses bad imports using `../src/..` identified with #12744  …
=> [PM-16927] Fix bad imports identified with #12744

package-lock.json, package.json
https://bitwarden.atlassian.net/browse/PM-16845
`@angular/elements` is unused. We can safely remove it. …
=> [PM-16845] Uninstall Angular elements

bitwarden_license/bit-web/src/app/secrets-manager/overview/overview.module.ts, bitwarden_license/bit-web/src/app/secrets-manager/projects/guards/project-access.guard.spec.ts, bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/guards/service-account-access.guard.spec.ts
https://bitwarden.atlassian.net/browse/PM-16929
Fix bad imports in unowned code. …
=> [PM-16929] Fix bad imports in unowned code

libs/angular/src/vault/components/icon.component.html
https://bitwarden.atlassian.net/browse/PM-13028
This PR aligns the default globe icon with the cipher icons.
|Before|After|
---|---
|![Screenshot 2025-01-09 at 10 11 00 AM](https://github.com/user-attachments/assets/7764e2ed-9dbb-4070-ab81-55cd1d176efc)|![Screenshot 2025-01-09 at 10 06 53 AM](https://github.com/user-attachments/assets/b1889a8d-8cfe-47d8-9814-f8935c131fa6)| …
=> [PM-13028] - align default globe vault icon with cipher icons

apps/desktop/resources/com.bitwarden.desktop.devel.yaml, apps/web/src/app/billing/organizations/change-plan-dialog.component.html
https://bitwarden.atlassian.net/browse/PM-16819
- 🎨 …
=> [PM-16819][Defect] Clicking Cancelled org is not displaying the upgrade path UI

apps/browser/src/auth/popup/settings/account-security.component.ts, apps/browser/src/vault/popup/services/vault-popup-autofill.service.ts
Follow up to https://github.com/bitwarden/clients/pull/10601 …
=> Fix linting conflicts after merge

bitwarden_license/bit-web/src/app/admin-console/organizations/manage/domain-verification/domain-verification.component.ts
https://bitwarden.atlassian.net/browse/PM-17048
This PR fixes a bug that prevented the claimed domains page from loading for custom users with the "manage SSO" permission.
The issue was caused by a server request to check the single organization policy, which required the "manage policies" permission.
Updated the code to use the policy service instead of making the server-side check. …
=> Fix claimed domains page for manage SSO users by replacing policies server check with policy service

libs/tools/generator/core/tsconfig.json
https://bitwarden.atlassian.net/browse/PM-16897
Eliminate circular dependencies from @bitwarden/generator-core module to prepare for npm modularization.
=> [PM-16897] remove circular reference to generator-core

apps/web/src/app/billing/organizations/organization-plans.component.ts
https://bitwarden.atlassian.net/browse/PM-17096
Resolved issue where an infinite spinner would display on self-hosted instances when creating a new org. …
=> Updated org plans component to not call for tax info on self hosted instances

.github/renovate.json
[bitwarden.atlassian.net/browse/PM-14640](https://bitwarden.atlassian.net/browse/PM-14640)
Clarified the group name for the `github-action` managed minor dependencies to align with the server as introduced in https://github.com/bitwarden/server/pull/5274. …
=> Renamed group for consistency with server renovate

.github/renovate.json
Move linting dependencies to architecture ownership
- 🎨 …
=> Move linting dependencies to architecture ownership

bitwarden_license/bit-web/src/app/tools/access-intelligence/org-at-risk-members-dialog.component.html
https://bitwarden.atlassian.net/browse/PM-17173
Ensure that the dialogs match 
- title (case, verbiage and counts)
- blurb on the page (style)
- records (style) …
=> PM-17173 minor style changes

.github/workflows/publish-desktop.yml
[BRE-563](https://bitwarden.atlassian.net/browse/BRE-563)
Adding ability to skip electron publish.   Helpful for hotfixes that need to only publish choco or Snap. …
=> [BRE-563] Adding ability to skip electron publish

apps/desktop/src/vault/app/vault/credential-generator-dialog.component.html, libs/tools/generator/core/src/data/generators.ts
https://bitwarden.atlassian.net/browse/PM-16858
This PR addresses the QA feedback and updates the button copy for generate passphrase modal. It also remove a legacy css class to ensure the modern button styling is applied.
|Passphrase|Password|Username|
---|---|---
|![Screenshot 2025-01-13 at 10 07 05 AM](https://github.com/user-attachments/assets/b676afcf-92c2-4aa9-92bd-5ea7522253c0)|![Screenshot 2025-01-13 at 10 06 59 AM](https://github.com/user-attachments/assets/98555222-13e5-4c52-bbf9-d37e407760ee)|![Screenshot 2025-01-13 at 10 06 52 AM](https://github.com/user-attachments/assets/92d2b37c-e389-4518-a86f-2707bbe99ca3)|
- Protected …
=> [PM-16858] - Desktop - Generator modal - Update submit button

apps/desktop/scripts/start.js
-
https://github.com/electron/electron/issues/41066
Adds --no-sandbox to the electron dev build to make it launch on ubuntu. …
=> Add --no-sandbox to make electron dev build work on ubuntu

apps/browser/src/platform/popup/layout/popup-layout.stories.ts, libs/angular/src/directives/copy-click.directive.spec.ts, libs/components/src/dialog/dialog.service.stories.ts, libs/components/src/dialog/simple-dialog/simple-configurable-dialog/simple-configurable-dialog.service.stories.ts, libs/components/src/dialog/simple-dialog/simple-dialog.service.stories.ts, libs/components/src/stories/kitchen-sink/components/kitchen-sink-main.component.ts, libs/components/src/stories/kitchen-sink/components/kitchen-sink-table.component.ts, libs/components/src/stories/kitchen-sink/components/kitchen-sink-toggle-list.component.ts, libs/components/src/table/sortable.component.ts
In #12806 we started getting linting errors in stories and specs. Might be related to the inline templates being linted. Created a separate PR to simplify the review. …
=> Add type=button to stories

libs/common/src/platform/abstractions/sdk/sdk.service.ts
=> Fix sdk client undefined

apps/desktop/desktop_native/core/src/ipc/mod.rs
https://bitwarden.atlassian.net/browse/PM-17431
On Mac release builds we're using the `Group Containers` directory from our application to give our IPC UNIX sockets some protection from other apps accessing them. This works great on the sandboxed App Store build, but our non-sandboxed DMG builds have some issues with them, causing a lot of users to constantly get dialogs saying that Bitwarden wants to access data from other apps:
This is very confusing for users and makes it look like we're trying to read data from other apps, plus the dialog appears every single time the app is opened, making it very annoying.
This PR changes the IPC path code to detect when the app is sandboxed (by checking the home directory) and only using `Group Containers` in that case. If the app is not sandboxed, …
=> [PM-17431] Don't use Group Containers dir for non-sandboxed DMG

apps/browser/src/autofill/content/components/lit-stories/buttons/action-button.lit-stories.ts, apps/browser/src/autofill/content/components/lit-stories/buttons/badge-button.lit-stories.ts, apps/browser/src/autofill/content/components/lit-stories/buttons/close-button.lit-stories.ts, apps/browser/src/autofill/content/components/lit-stories/buttons/edit-button.lit-stories.ts, apps/browser/src/autofill/content/components/lit-stories/notification/body.lit-stories.ts, apps/browser/src/autofill/content/components/lit-stories/notification/footer.lit-stories.ts, apps/browser/src/autofill/content/components/lit-stories/notification/header.lit-stories.ts
https://bitwarden.atlassian.net/browse/PM-17351
Implement appropriate design links per component for design add on.  …
=> PM-17351-implement-lit-sb-design-links

apps/cli/src/tools/import.command.ts
https://bitwarden.atlassian.net/browse/PM-15506
Fast follow to https://github.com/bitwarden/clients/pull/12839 to implement getUserId and getOrganizationById. …
=> [PM-15506] Refactor import.command to use getOrganizationById and getUserId

.github/workflows/release-browser.yml, .github/workflows/release-cli.yml, .github/workflows/release-desktop-beta.yml, .github/workflows/release-desktop.yml
Fix name of the `release-version-check` action.
- 🎨 …
=> Fix name of the release-version-check action

apps/web/src/app/vault/individual-vault/vault-banners/services/vault-banners.service.ts, libs/common/src/platform/state/implementations/state-base.ts, libs/common/src/platform/state/implementations/util.ts, libs/common/src/platform/state/key-definition.ts, libs/key-management/package.json, libs/key-management/src/abstractions/kdf-config.service.ts, libs/key-management/src/kdf-config.service.spec.ts, libs/key-management/src/kdf-config.service.ts, libs/key-management/src/models/kdf-config.spec.ts, libs/key-management/src/models/kdf-config.ts
https://bitwarden.atlassian.net/browse/PM-14445
TS strict mode fixed for KDF in Key Management
Other KM areas changes to follow later
Also fixed bunch of eslint ignores and increased test coverage.
- 🤔 …
=> [PM-14445] TS strict for Key Management KDF

apps/web/src/app/billing/shared/adjust-payment-dialog/adjust-payment-dialog-v2.component.ts
https://bitwarden.atlassian.net/browse/PM-17423
https://github.com/user-attachments/assets/f1aabb62-2ac7-4096-864b-e10d7f15ff9b …
=> [PM-17423][Defect] Upgrade modal - Missing payment information validation message

libs/common/src/vault/abstractions/cipher.service.ts, libs/common/src/vault/services/cipher.service.ts, libs/vault/src/cipher-form/components/item-details/item-details-section.component.spec.ts, libs/vault/src/cipher-form/components/item-details/item-details-section.component.ts, libs/vault/src/cipher-form/services/default-cipher-form.service.ts
https://bitwarden.atlassian.net/browse/PM-17213
This PR updates the cipher form to allow changing of ownership from personal to org. Once owned by an org ownership is no longer possible.
https://github.com/user-attachments/assets/ddefb39c-ea40-4ac6-b6f7-4c159ccab7ff …
=> [PM-17213] - allow changing of item owner from personal to org

apps/desktop/src/package-lock.json, apps/desktop/src/package.json
=> chore: correct the desktop version number

apps/browser/src/tools/popup/settings/settings-v2.component.html
https://bitwarden.atlassian.net/browse/PM-17484
To bring more visual interest to the extension settings page, we should add icons before each settings page link
| ![image](https://github.com/user-attachments/assets/f1a02769-5b95-4c7b-8da1-d260b44e028e) | ![image](https://github.com/user-attachments/assets/31b3bd10-2745-4a5c-991c-768993af819c) | …
=> [PM-17484] Add icons to settings page

libs/vault/src/components/carousel/carousel-button/carousel-button.component.html
=> Fix linting

apps/web/src/app/admin-console/organizations/guards/org-permissions.guard.spec.ts, apps/web/src/app/admin-console/organizations/guards/org-permissions.guard.ts
https://bitwarden.atlassian.net/browse/PM-17692
Fix the following bug introduced by #12839:
>Steps to reproduce:
>
> Be an owner of 2 orgs: 1 free and 1 enterprise.
> 
> Try to access the settings → Policies page for the enterprise organization.
> 
> Observe: you are redirected back to the Admin Console Collections tab with an error toast saying you don’t have permissions.
>
> This also affects other Settings pages (and probably other AC pages, this is not comprehensive).
This was caused by a typo in `OrgPermissionsGuard`:
```ts
organizations.find((org) => route.params.organizationId)
```
This is not actually doing any comparison, it's returning `true` because the orgId in the params is truthy, so it just grabs the first org available.
I have refactored this to use our rxjs operators and …
=> [PM-17692] Fix AC navigation permissions bug

apps/browser/src/background/main.background.ts, apps/web/src/app/core/core.module.ts, apps/web/src/app/platform/notifications/permissions-webpush-connection.service.ts
I broke some linting errors from merging something not up to date with `main` in #11346. …
=> Fix lint errors from merge

.github/renovate.json
https://bitwarden.atlassian.net/browse/PM-12444
Remove ngx-infinite-scroll dependency from renovate. …
=> [PM-12444] remove dependency from renovate

apps/desktop/src/auth/set-password.component.ts, apps/web/src/app/auth/settings/change-password.component.ts, apps/web/src/app/auth/settings/emergency-access/takeover/emergency-access-takeover.component.ts, libs/angular/src/auth/components/change-password.component.ts, libs/angular/src/auth/components/set-password.component.ts, libs/angular/src/auth/components/update-password.component.ts, libs/angular/src/auth/components/update-temp-password.component.ts
https://bitwarden.atlassian.net/browse/PM-16485
- **Remove deprecated and unused PasswordGenerationService -** https://github.com/bitwarden/clients/commit/da66865c3f7223953fb802720c4990d98703dfe2
- **Remove unused state-service -** https://github.com/bitwarden/clients/commit/59c92ba4e70a42aeb05a8231d453b56a144c79ad
- **Remove passwordGeneration- and state-Service from set-password.component -** https://github.com/bitwarden/clients/pull/13132/commits/db85bd9d54032bacc78220b62de516c821b26b3b
- Communicated …
=> [PM-16485] Remove legacy generator from change password component

libs/components/src/toast/toast.component.ts
The `title` option on `ToastService.showToast` is meant to be optional. …
=> [UIF] correct Toast title type

.github/CODEOWNERS, .github/renovate.json
We updated our github team name. …
=> Update codeowner and renovate files with new team name

apps/web/src/app/admin-console/organizations/shared/components/access-selector/access-selector.models.ts, apps/web/src/app/vault/components/vault-items/vault-cipher-row.component.ts, apps/web/src/app/vault/components/vault-items/vault-collection-row.component.ts, apps/web/src/locales/en/messages.json
https://bitwarden.atlassian.net/browse/PM-16579
Updates copy for permissions on collections/items …
=> [PM-16579] update copy

apps/browser/src/autofill/services/collect-autofill-content.service.ts
[PM-17918](https://bitwarden.atlassian.net/browse/PM-17918)
Resolve errors re: DomQueryService not being available
[PM-17918]: https://bitwarden.atlassian.net/browse/PM-17918?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYz …
=> [PM-17918] Bugfix - DomQueryService erroring as undefined

apps/web/src/app/billing/organizations/change-plan-dialog.component.html
https://bitwarden.atlassian.net/browse/PM-17100
- 🎨 …
=> [PM-17100] Fixed copy for Families upgrade card

libs/common/src/enums/feature-flag.enum.ts
https://bitwarden.atlassian.net/browse/PM-15179
Aleksandra was unable to create the flag with capitalized letters. …
=> Update feature flag name

.github/workflows/test.yml
Rust code coverage for `apps/desktop/desktop_native` is missing in codecov. …
=> desktop native written in rust code coverage

.github/CODEOWNERS
The `libs/key-management-ui` is Key Management owned component, but currently it is not owned by anyone. …
=> Key Magement UI angular module ownership

apps/web/src/app/tools/reports/pages/weak-passwords-report.component.html, apps/web/src/app/tools/reports/pages/weak-passwords-report.component.ts
Reverts bitwarden/clients#12359
=> Revert "[PM-13404] Weak Passwords Report - Sort by password weakness"

.github/CODEOWNERS
=> Add Platform as co-owners

apps/web/src/app/vault/components/collection-dialog/collection-dialog.component.html, apps/web/src/locales/en/messages.json
https://bitwarden.atlassian.net/browse/PM-17850
fixes an instance of the old copy still being present. …
=> [PM-17850] add new copy, remove old

libs/vault/src/cipher-form/cipher-form.stories.ts
https://github.com/bitwarden/clients/pull/13274
This PR fixes an issue introduced by https://github.com/bitwarden/clients/pull/13236 which was causing the cipher form story to not render properly.
- 🤔 …
=> [PM-18023] - fix cipher form story 

.github/CODEOWNERS, .github/codecov.yml
Fixes some typos preventing correct ownership and coverage from being applied. …
=> Fix typos in codeowners and codecov

apps/browser/package.json, apps/browser/src/manifest.json, apps/browser/src/manifest.v3.json, package-lock.json
- https://bitwarden.atlassian.net/browse/RELEASE-1540
The Browser was incorrectly bumped in the `main` branch in [this commit](https://github.com/bitwarden/clients/commit/049877c4ce165530e6e2fdd49e57258374a5cc68) and subsequently cherry-picked into `rc`. The correct version to be released is `2025.1.3`, as the last release Browser version was `2025.1.2`.
What has happened is that:
1. I tried updating the version directly to `rc`  in [this commit](https://github.com/bitwarden/clients/commit/67c2545cd3080cc907090c9e7080347068f6f5a1), failed because there are more places to update the version. It has been reverted.
2. I attempted to run the [repository-management](https://github.com/bitwarden/clients/actions/runs/13178808642) worklfow to update in all the places required. Failed because the …
=> Fix Browser version to 2025.1.3

libs/importer/src/components/import.component.html
https://bitwarden.atlassian.net/browse/PM-16864
Relates to previous work: https://github.com/bitwarden/clients/pull/12448
This PR fixes a styling issue where the help links on the Import Vault page were not readable in Dark Mode due to poor color contrast on the extension.
The bit-link directive with the appropriate linkType has been applied to resolve this issue.
This applies to help links for the formats: 
- Lastpass
- Chrome
- Firefox
- Safari
- 1password
- Gnome-Keyring
| ![image](https://github.com/user-attachments/assets/920721cd-e0da-4b6f-be92-957bb73e2ded) | ![image](https://github.com/user-attachments/assets/90814629-ce90-4cd2-87ea-43febcaa55f6) |
- …
=> [PM-16964] Format help links on vault import

bitwarden_license/bit-web/src/app/vault/services/default-admin-task.service.spec.ts, bitwarden_license/bit-web/src/app/vault/services/default-admin-task.service.ts
=> Fixed request payload for bulk-create endpoint

apps/desktop/src/package-lock.json, apps/desktop/src/package.json
The auto bump bot has been acting kinda crazy lately. We're preparing for the first release of February, but desktop is one version ahead of where it should be. …
=> chore: correct desktop version

libs/auth/src/angular/sso/sso.component.ts, libs/common/src/auth/abstractions/sso-login.service.abstraction.ts, libs/common/src/auth/services/sso-login.service.ts
https://bitwarden.atlassian.net/browse/PM-14445
Fixes TS strict errors in SSO code. Introduced with #13039, which introduces explicit null expectations in global state. Must have missed this, due to not being completely up to date with main. …
=> [PM-14445] Auth SSO Login TS strict failures

apps/browser/src/autofill/services/autofill.service.spec.ts, apps/browser/src/autofill/services/autofill.service.ts, apps/browser/src/background/main.background.ts, apps/browser/src/background/runtime.background.ts
This reverts commit 1b3bc71e5061dbc2855aa219f84e15c0028377ec.
[PM-18120](https://bitwarden.atlassian.net/browse/PM-18120)
The changes introduced in [PM-15943](https://github.com/bitwarden/clients/pull/13143) has caused some autofill cases to fail.
BIT failure
https://github.com/bitwarden/browser-interactions-testing/actions/runs/13209571963
- 🌱 (`:seedling:`) or …
=> [PM-18120] Bugfix - Revert PM-15943 (1b3bc71e50)

apps/web/src/app/layouts/product-switcher/navigation-switcher/navigation-switcher.stories.ts, apps/web/src/app/layouts/product-switcher/product-switcher.stories.ts
https://bitwarden.atlassian.net/browse/PM-15445
Missed a mock dependency in the `product-switcher.stories` setup. …
=> [PM-15445] Fix storybook

apps/browser/src/manifest.v3.json, apps/browser/webpack.config.js
=> Support Firefox MV3

apps/web/src/app/auth/verify-email-token.component.html
https://bitwarden.atlassian.net/browse/PM-17183?atlOrigin=eyJpIjoiYzI0ZmE5MmI2ZTg2NDEzMmFlMWRiODg2Y2ZmMjAzZmMiLCJwIjoiaiJ9
Removes Bootstrap styles from VerifyEmailTokenComponent. While I was here I updated the layout to match the general application loading screen. …
=> [PM-17183] Remove Bootstrap from VerifyEmailTokenComponent

bitwarden_license/bit-web/src/app/tools/access-intelligence/critical-applications.component.html, bitwarden_license/bit-web/src/app/tools/access-intelligence/critical-applications.component.ts
https://bitwarden.atlassian.net/browse/PM-17212?isEligibleForUserSurvey=true
To send notifications on the Critical Apps tab.
Request Password change button disabled (when there are no at-risk passwords)
Success message:
Error when API call fails: …
=> PM-17212 Invoke notifications API

apps/desktop/src/vault/app/vault/vault.component.ts, libs/angular/src/vault/components/view.component.ts
https://bitwarden.atlassian.net/browse/PM-18055
This PR fixes an issue where the vault item view and list views weren't syncing after a vault item was saved.
https://github.com/user-attachments/assets/84489c23-d19a-491e-b67c-a5fd4306a16c …
=> [PM-18055] - sync list and item view after saving vault item

libs/angular/src/vault/components/add-edit.component.ts, libs/vault/src/cipher-form/components/sshkey-section/sshkey-section.component.ts, package-lock.json, package.json
=> chore: update sdk to main.105

libs/auth/src/angular/anon-layout/anon-layout.component.html
https://bitwarden.atlassian.net/browse/PM-18408
To add a bit more responsive scaling to the anon-layout so that the extension doesn't have scrollbars on the new login page. 
Before:
After:
- 🤔 …
=> Auth/PM-18408 - AnonLayout - Improve responsive scaling for extension to remove scrollbars on login in new UI

libs/common/src/vault/services/cipher.service.ts
https://bitwarden.atlassian.net/browse/PM-18337
Fresh account registration without key throws error, unable to login. …
=> [PM-18337] Fresh account registration without key throws error, unable to login

libs/auth/package.json, libs/importer/package.json, libs/node/package.json, libs/tools/card/package.json, libs/tools/export/vault-export/vault-export-core/package.json, libs/tools/export/vault-export/vault-export-ui/package.json, libs/tools/generator/components/package.json, libs/tools/generator/core/package.json, libs/tools/generator/extensions/history/package.json, libs/tools/generator/extensions/legacy/package.json, libs/tools/generator/extensions/navigation/package.json, libs/tools/send/send-ui/package.json, package-lock.json, package.json
https://bitwarden.atlassian.net/browse/PM-18363
Some of the package.json referenced invalid packages potentially resulting in the error seen in https://github.com/bitwarden/clients/issues/12747.
We currently do not use the internal dependencies defined in `package.json` and as this might be confusing to people It's simpler to remove it for now.
I also noticed that we had `libs/*` as a workspace directory but this doesn't capture nested libs. I'm a bit unsure if we gain anything by having our packages defined in the workspace entry but in an effort to be consistent I tweaked this to be `libs/**/*` which is inclusive of nested packages.
- …
=> [PM-18363] Remove internal dependencies from package.json

bitwarden_license/bit-web/src/app/tools/access-intelligence/all-applications.component.html, bitwarden_license/bit-web/src/app/tools/access-intelligence/all-applications.component.ts, bitwarden_license/bit-web/src/app/tools/access-intelligence/app-table-row-scrollable.component.html, bitwarden_license/bit-web/src/app/tools/access-intelligence/app-table-row-scrollable.component.ts, bitwarden_license/bit-web/src/app/tools/access-intelligence/critical-applications.component.html, bitwarden_license/bit-web/src/app/tools/access-intelligence/critical-applications.component.ts, bitwarden_license/bit-web/src/app/tools/access-intelligence/password-health-members-uri.component.html, bitwarden_license/bit-web/src/app/tools/access-intelligence/password-health-members.component.html, bitwarden_license/bit-web/src/app/tools/access-intelligence/password-health.component.html
https://bitwarden.atlassian.net/browse/PM-18401
To implement virtual scrolling on all tables across all tabs
Screen renders in approximately 6 seconds. …
=> PM-18401 apply scroll tables across all tables

apps/web/src/app/billing/shared/payment/payment.component.ts
https://bitwarden.atlassian.net/browse/PM-17223
Changed error message when submitting invalid/required/empty payment information for bank account
`Invalid input provided, Please ensure all required fields are filled out correctly and try again.`
to
`Invalid input provided. Please ensure all required fields are filled out correctly and try again.`
- 👍 …
=> [PM-17223] Update comma to period after "Invalid input provided" text

libs/common/spec/observable-tracker.ts, libs/common/src/platform/abstractions/sdk/sdk.service.ts, libs/common/src/platform/services/sdk/default-sdk.service.spec.ts, libs/common/src/platform/services/sdk/default-sdk.service.ts
=> [PM-17408] Create new method on sdk service to allow explicit addition of a new client instance

libs/common/src/platform/services/sdk/default-sdk.service.ts
not sure how this wasn't caught in the CI before the merge …
=> fix: type error

apps/browser/src/auth/popup/extension-anon-layout-wrapper/extension-bitwarden-logo.icon.ts
https://bitwarden.atlassian.net/browse/PM-14413
To fix the extension Bitwarden logo not having a title so that screen readers can read that it is a Bitwarden logo image. 
https://github.com/user-attachments/assets/346d303d-1911-4596-bcdd-8921b230ea6d …
=> Auth/PM-14413 - Extension BW Logo - Add A11y title to svg for screen reader support

apps/desktop/desktop_native/Cargo.toml, apps/desktop/desktop_native/core/Cargo.toml, apps/desktop/desktop_native/macos_provider/Cargo.toml, apps/desktop/desktop_native/napi/Cargo.toml, apps/desktop/desktop_native/objc/Cargo.toml, apps/desktop/desktop_native/objc/src/lib.rs, apps/desktop/desktop_native/proxy/Cargo.toml, apps/desktop/desktop_native/windows-plugin-authenticator/Cargo.toml
Extracted duplicate cargo package metadata (version, license, publishable, edition) into the workspace file to avoid repetition and making changes easier. Also changed the workspace dependency syntax to use `= { workspace = true }` for consistency.
I've included a fix as well for a breakage when migrating to edition 2024 as well, where some extern functions must be now marked as unsafe in `apps/desktop/desktop_native/objc/src/lib.rs`. We were only calling them in unsafe context already so the change is only to the function declarations. …
=> Extract common cargo info and edition 2024 fix

libs/auth/src/angular/new-device-verification/new-device-verification.component.html
https://bitwarden.atlassian.net/browse/PM-18580
To add the missing `bitFormButton` to get loading state on form submission on the `NewDeviceVerificationComponent`
https://github.com/user-attachments/assets/956a74d6-8337-4296-8284-a5658a3c99a9 …
=> Auth/PM-18580 - NewDeviceVerificationComp - Add missing bitFormButton to get loading state on form submission

apps/web/src/app/billing/organizations/organization-plans.component.html
https://bitwarden.atlassian.net/browse/PM-17507
This resolves this error:
```
apps/web/src/app/billing/organizations/organization-plans.component.html
248:21  error  Classname 'tx-text-sm' is not a Tailwind CSS class!  tailwindcss/no-custom-classname
``` …
=> [PM-17507] Fixed typo in tailwind class name

apps/web/src/app/billing/organizations/change-plan-dialog.component.html
https://bitwarden.atlassian.net/browse/PM-17506
- 🎨 …
=> [PM-17506] Bootstrap to tailwind updates

apps/web/src/app/billing/accounts/trial-initiation/trial-billing-step.component.html
https://bitwarden.atlassian.net/browse/PM-17505
Resolves this error:
```
apps/web/src/app/billing/accounts/trial-initiation/trial-billing-step.component.html
3:5  error  Classname 'text-muted' is not a Tailwind CSS class!  tailwindcss/no-custom-classname
``` …
=> [PM-17505] Updated trial-billing-step.component.html to use `tw-text-muted` instead of `text-muted`

apps/web/src/app/billing/organizations/organization-subscription-cloud.component.html
https://bitwarden.atlassian.net/browse/PM-17508
```
apps/web/src/app/billing/organizations/organization-subscription-cloud.component.html
4:6  error  Classname 'text-muted' is not a Tailwind CSS class!  tailwindcss/no-custom-classname
``` …
=> [PM-17508] Updated to use tailwind's `tw-text-muted`

apps/browser/src/vault/popup/components/vault-v2/new-settings-callout/new-settings-callout.component.html, apps/browser/src/vault/popup/components/vault-v2/new-settings-callout/new-settings-callout.component.ts, apps/browser/src/vault/popup/components/vault-v2/vault-page.service.ts
https://bitwarden.atlassian.net/browse/PM-18621
https://bitwarden.atlassian.net/browse/PM-18615
https://bitwarden.atlassian.net/browse/PM-18623
This PR fixes a few defects from the new settings popover feature.
- Link font should be bold
- Link should be navigable via keyboard
- Popover should not show when quick copy actions  …
=> [PM-18623][PM-18621][PM-18615] fix defects for new settings popover

apps/browser/src/auth/popup/account-switching/account-switcher.component.html, apps/browser/src/auth/popup/account-switching/account-switcher.component.ts
https://bitwarden.atlassian.net/browse/PM-11648
Fix text styling by removing hardcoded styles and importing `Typography` module …
=> Auth/PM-11684 - Extension - AcctSwitcherComp - Fix missing typography import

apps/browser/src/auth/popup/extension-anon-layout-wrapper/extension-anon-layout-wrapper.component.html
https://bitwarden.atlassian.net/browse/PM-18574
To fix the `ExtensionAnonLayoutWrapperComponent's` styling of the logo so that it centers vertically in the popup header. 
Before:
After: …
=> Auth/PM-18574 - ExtensionAnonLayoutWrapperComp - add inline flex to logo so it vertically centers

libs/common/src/key-management/crypto/services/encrypt.service.spec.ts
https://bitwarden.atlassian.net/browse/PM-18697
Adds some more validation in response to:
https://github.com/bitwarden/clients/pull/13628#discussion_r1975396981 …
=> [PM-18697] Validate parameters in encrypt service tests

apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.html, apps/web/src/locales/en/messages.json
https://bitwarden.atlassian.net/browse/PM-17781
Replaces icon buttons in the member modal with text buttons. Also shortens some copy in the same modal. …
=> [PM-17781] Replace icon buttons with text buttons

apps/web/src/app/admin-console/organizations/policies/policies.component.html
https://bitwarden.atlassian.net/browse/CL-604
Add ngPreserveWhitespace to fix badge padding.
Before:
After: …
=> [CL-604] Add ngPreserveWhitespace to fix badge padding

apps/browser/src/_locales/en/messages.json, apps/browser/src/popup/app-routing.module.ts, apps/desktop/src/app/app-routing.module.ts, apps/desktop/src/locales/en/messages.json, apps/web/src/app/oss-routing.module.ts, apps/web/src/connectors/webauthn-fallback.ts, apps/web/src/locales/en/messages.json
https://bitwarden.atlassian.net/browse/PM-18710
To fix the incorrect page title of "Verify identity" being used instead of the design appropriate "Verify your identity"
Note: changing to a new translation key is the only way to get Crowdin to pick up the changes. This affected the 2FA flows and the new device verification screen. …
=> Auth/PM-18710 - New UI - Consolidate "verifyIdentity" translation to fix extension

libs/common/src/enums/feature-flag.enum.ts
https://bitwarden.atlassian.net/browse/PM-17151
remove feature flag …
=> remove feature flag

apps/desktop/package.json, apps/desktop/src/package-lock.json, apps/desktop/src/package.json, package-lock.json
Updated desktop to `2025.2.1`, since the last release was `2025.2.0`: https://github.com/bitwarden/clients/releases/tag/desktop-v2025.2.0.
This changes the same 4 files as the [previous commit](https://github.com/bitwarden/clients/commit/9655b1b3bc15b9798c77a47d78e7ca877dc76e5d#diff-11ad47a13b33220232271b205534e9d019114fa51b416694cb70bbe4a9e6404e) to do the same thing for the desktop. …
=> Update desktop to 2025.2.1

apps/web/src/app/billing/settings/sponsored-families.component.html
https://bitwarden.atlassian.net/browse/PM-17510
apps/web/src/app/billing/settings/sponsored-families.component.html
5:8  error  Classname 'text-muted' is not a Tailwind CSS class!  tailwindcss/no-custom-classname …
=> [PM-17510]Migrate SponsoredFamilies

libs/angular/src/billing/components/invoices/invoices.component.html
https://bitwarden.atlassian.net/browse/PM-17528
libs/angular/src/billing/components/invoices/invoices.component.html
3:5  error  Classname 'text-muted' is not a Tailwind CSS class!  tailwindcss/no-custom-classname
7:9  error  Classname 'sr-only' is not a Tailwind CSS class!     tailwindcss/no-custom-classname …
=> [PM-17528]Migrate invoices.component.html

apps/web/src/app/billing/organizations/organization-subscription-selfhost.component.html
https://bitwarden.atlassian.net/browse/PM-17509
Resolves this error:
```
apps/web/src/app/billing/organizations/organization-subscription-selfhost.component.html
5:8   error  Classname 'text-muted' is not a Tailwind CSS class!  tailwindcss/no-custom-classname
69:13  error  Classname 'mt-5' is not a Tailwind CSS class!        tailwindcss/no-custom-classname
``` …
=> [PM-17509] Updated classes to use tailwind

bitwarden_license/bit-web/src/app/billing/providers/subscription/provider-subscription.component.html
https://bitwarden.atlassian.net/browse/PM-17527
Resolves
```
bitwarden_license/bit-web/src/app/billing/providers/subscription/provider-subscription.component.html
4:8   error  Classname 'text-muted' is not a Tailwind CSS class!  tailwindcss/no-custom-classname
14:11  error  Classname 'pb-2' is not a Tailwind CSS class!        tailwindcss/no-custom-classname
``` …
=> [PM-17527] Updated to use tailwind

apps/web/src/app/oss-routing.module.ts
https://bitwarden.atlassian.net/browse/PM-18737
To get the UI refreshed 2FA page subtitle wrapping properly. 
Before:
After: …
=> Auth/PM-18737 - UI Refresh - Web - 2FA - add md width to all 2FA titles / subtitles

libs/auth/src/angular/new-device-verification/new-device-verification.component.ts
https://bitwarden.atlassian.net/browse/PM-18641
To fix the fact that the invalid verification code error wasn't shown when the user hit enter (+ add translation)
https://github.com/user-attachments/assets/a806860f-3c3d-4b26-a67e-a4a88077067a
https://github.com/user-attachments/assets/9f79a45f-b0bc-4c10-847d-64605dd08804
https://github.com/user-attachments/assets/970e7b95-6757-4213-bc7e-57aac70020c1 …
=> Auth/PM-18641 - New Device Verification -  Show invalid code on enter keypress

libs/importer/src/importers/bitwarden/bitwarden-csv-importer.spec.ts, libs/importer/src/importers/bitwarden/bitwarden-csv-importer.ts
https://bitwarden.atlassian.net/browse/PM-16690
While importing a Bitwarden CSV file, the hierarchy  of collections are not created. Instead, a single collection with the hierarchy separated by `/` is created.
For the hierarchy: 
- TECHNIQUE/AURA/AFIPH/TOIP
- TECHNIQUE/AURA/ACMES/Network …
=> [PM-16690] Bitwarden CSV Import - collections not created 

.github/ISSUE_TEMPLATE/browser.yml
Changes the Build Version field to Environment Versions with the expectation of also including sdk and server versions in order to more accurate reproduce issues.
Related to https://github.com/bitwarden/clients/pull/13465
- ❓ …
=> Update version in issue template

apps/browser/package.json, apps/browser/src/manifest.json, apps/browser/src/manifest.v3.json, apps/cli/package.json, apps/desktop/package.json, apps/desktop/src/package-lock.json, apps/desktop/src/package.json, apps/web/package.json, package-lock.json
=> chore: bump client versions

apps/browser/src/vault/popup/components/vault-v2/new-settings-callout/new-settings-callout.component.html
https://bitwarden.atlassian.net/browse/PM-18623
This PR changes the font weight to bold for the new settings callout link …
=> [PM-18623] - bold new settings callout link

bitwarden_license/bit-web/src/app/admin-console/organizations/manage/device-approvals/device-approvals.component.html
https://bitwarden.atlassian.net/browse/PM-18688
replaces non-tailwind class with the tw class.
Old:
https://github.com/user-attachments/assets/0a46de99-37af-482f-8cd8-92841db4cf33
New:
https://github.com/user-attachments/assets/86eec4d2-9c52-4f6b-96d4-4de921aa2cbc …
=> [PM-18688] Migrate Device Approvals component

bitwarden_license/bit-web/src/app/admin-console/organizations/manage/domain-verification/domain-verification.component.html
https://bitwarden.atlassian.net/browse/PM-18689
migrates domain-verification.component to use tw classes only. Only UI change observed is the color of the loading spinner being slightly less opaque. 
Old:
https://github.com/user-attachments/assets/6fa300e0-2645-462f-ac0c-770cd4536c98
New:
https://github.com/user-attachments/assets/42802b9e-2e57-498f-9d83-0b21deed59e0 …
=> [PM-18689] Migrate domain-verification.component

apps/web/src/app/tools/reports/pages/exposed-passwords-report.component.html, apps/web/src/app/tools/reports/pages/reused-passwords-report.component.html, apps/web/src/app/tools/reports/pages/weak-passwords-report.component.html, libs/components/src/table/table-scroll.component.html
https://bitwarden.atlassian.net/browse/PM-2630
Implement virtual scrolling to allow for very large data
No changes from the original design …
=> [PM-2630] virtual scroll on tables

libs/common/src/enums/feature-flag.enum.ts
https://bitwarden.atlassian.net/browse/PM-19083
Creates a feature flag for the upcoming work on the Send UI refresh for the Bitwarden desktop apps …
=> [PM-19083] Introduce desktop-send-ui-refresh feature-flag

apps/web/src/app/admin-console/organizations/collections/vault-header/vault-header.component.html
https://bitwarden.atlassian.net/browse/PM-17519
replaces class with tailwind version …
=> add tw class

libs/vault/src/cipher-view/item-history/item-history-v2.component.html
https://bitwarden.atlassian.net/browse/PM-13137
This PR allows the item history text to be selectable in the browser extension …
=> [PM-13137] - allow item history to be selectable

apps/web/src/app/admin-console/organizations/manage/group-add-edit.component.html, apps/web/src/app/admin-console/organizations/manage/groups.component.html, apps/web/src/app/admin-console/organizations/members/components/bulk/bulk-status.component.html, apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.html, apps/web/src/app/admin-console/organizations/members/members.component.html, apps/web/src/app/admin-console/organizations/sponsorships/accept-family-sponsorship.component.html, apps/web/src/app/admin-console/organizations/sponsorships/accept-family-sponsorship.component.ts, apps/web/src/app/admin-console/organizations/sponsorships/families-for-enterprise-setup.component.html, bitwarden_license/bit-web/src/app/admin-console/providers/manage/accept-provider.component.html, bitwarden_license/bit-web/src/app/admin-console/providers/manage/accept-provider.component.ts, bitwarden_license/bit-web/src/app/admin-console/providers/verify-recover-delete-provider.component.html
https://bitwarden.atlassian.net/browse/PM-17372
Migrates various Admin Console owned components off bootstrap to tailwind and CL components. …
=> [PM-17372] Migrate components

.github/workflows/build-desktop.yml, apps/desktop/electron-builder.json
https://github.com/actions/runner-images/issues/11101
The ubuntu-20.04 runner will be removed from GitHub on April 1st.  This PR updates the ubuntu version to 22.04 …
=> update github runner for child process

libs/common/src/enums/feature-flag.enum.ts
Introduces the `export-attachments`-feature flag to guard the functionality being introduced with https://github.com/bitwarden/clients/pull/10465 …
=> Introduce `export-attachments` feature-flag

libs/vault/src/cipher-view/cipher-view.component.html, libs/vault/src/cipher-view/login-credentials/login-credentials-view.component.html
[PM-19025](https://bitwarden.atlassian.net/browse/PM-19025)
Update Icon and A11y for View Item Warning Banner
https://github.com/user-attachments/assets/69fdbd76-fb6e-47f7-b0a7-6765d5c3d70f
- 🤔 …
=> [PM-19025] Update Icon and A11y for View Item Warning Banner

apps/web/src/app/vault/components/browser-extension-prompt/browser-extension-prompt-install.component.html
[PM-18916](https://bitwarden.atlassian.net/browse/PM-18916)
Open's the extension web store in a new tab
<video src="https://github.com/user-attachments/assets/f9c163f8-de2d-401c-bb97-754a1570d509" />
[PM-18916]: …
=> [PM-18916] Open web store in new tab

apps/web/src/app/vault/components/vault-item-dialog/vault-item-dialog.component.ts
https://bitwarden.atlassian.net/browse/PM-18089
fixes issue showing edit button …
=> [PM-18089] fix showEdit bug

libs/auth/src/common/abstractions/login-strategy.service.ts, libs/auth/src/common/login-strategies/opaque-login.strategy.ts, libs/auth/src/common/models/domain/login-credentials.ts, libs/auth/src/common/services/login-strategies/login-strategy.service.ts, libs/common/src/auth/models/request/identity-token/opaque-token.request.ts, libs/common/src/auth/opaque/default-opaque.service.ts, libs/common/src/auth/opaque/models/cipher-configuration.ts
=> Innovation/OPAQUE - Add and cleanup some TODOs

package-lock.json, package.json
https://bitwarden.atlassian.net/browse/PM-19092
Hopefully fixes an error coming from the SDK. 
```
i.__externref_table_alloc is not a function
``` …
=> Update `@bitwarden/sdk-internal` version

apps/web/src/app/vault/individual-vault/vault-header/vault-header.component.ts
https://bitwarden.atlassian.net/browse/PM-19244
Fixes an issue introduced with https://github.com/bitwarden/clients/pull/13557 where collections could not be created. …
=> [PM-19244] add missing null check, fix feature flag logic, cleanup

libs/angular/src/services/jslib-services.module.ts
[PM-17648](https://bitwarden.atlassian.net/browse/PM-17648)
Fixes a service injection issue introduced as part of https://github.com/bitwarden/clients/pull/13552
https://github.com/user-attachments/assets/d2d10eb0-c6d1-41ac-97e6-c9b87ba3ac6d …
=> [PM-17648] Fix MasterPasswordApiService injection

libs/auth/src/common/login-strategies/opaque-login.strategy.ts, libs/auth/src/common/login-strategies/password-login.strategy.ts, libs/auth/src/common/models/domain/login-credentials.ts, libs/common/src/auth/models/response/pre-password-login.response.ts, libs/common/src/auth/opaque/default-opaque-key-exchange.service.ts, libs/common/src/auth/opaque/models/opaque-cipher-configuration.ts, libs/common/src/auth/opaque/models/registration-start.request.ts, libs/common/src/auth/opaque/opaque-key-exchange.service.ts
=> Rename CipherConfig to OpaqueCipherConfig per discussion

apps/browser/src/autofill/background/notification.background.spec.ts, apps/browser/src/autofill/background/notification.background.ts, apps/browser/src/autofill/content/components/notification/body.ts, apps/browser/src/autofill/content/components/notification/container.ts, apps/browser/src/autofill/notification/abstractions/notification-bar.ts, apps/browser/src/autofill/notification/bar.ts, apps/browser/src/background/main.background.ts
https://bitwarden.atlassian.net/browse/PM-19291
- Pass relevant data into dropdown component
- Pass all data(ciphers, folders, orgs) into notificationBarIframeInitData using promise all
- Alphabetized portions of `notification-background` and `main-background`
- Fixed relevant tests  …
=> PM-19291 Pass relevant folder and vault data to drop down component within notification footer 

apps/browser/src/background/main.background.ts, apps/web/src/app/tools/reports/pages/reports-home.component.ts, apps/web/src/app/tools/reports/reports-routing.module.ts, libs/common/src/enums/feature-flag.enum.ts
=> Wrapped phishing detection feature behind feature flag

.github/workflows/build-web.yml
https://bitwarden.slack.com/archives/C024Z7LQNLB/p1742373543364149
Fix web docker build for community PR …
=> [BRE-723] Fix web docker build for community PR

apps/web/src/app/auth/settings/change-password.component.ts
=> feat : adding feature flag to change password flow

apps/browser/src/_locales/en/messages.json, apps/browser/src/vault/popup/components/vault-v2/item-more-options/item-more-options.component.html, apps/browser/src/vault/popup/components/vault-v2/item-more-options/item-more-options.component.ts, apps/browser/src/vault/popup/settings/archive.component.ts, libs/common/src/vault/abstractions/cipher.service.ts, libs/common/src/vault/models/request/cipher-bulk-archive.request.ts, libs/common/src/vault/services/cipher.service.ts
[PM-19406](https://bitwarden.atlassian.net/browse/PM-19406)
Add/implement actions to archive/unarchive items from the browser extension.
https://github.com/user-attachments/assets/e7b8c517-fb29-4faa-aee5-701b02a76a8c …
=> [PM-19406] Archive item actions Browser

apps/web/src/app/billing/individual/premium/premium.component.html
Doesn't ultimately seem to affect URL resolution, but should fix it anyway 🤷 
=> Bugfix - Link typo

apps/web/src/app/admin-console/organizations/manage/events.component.html
https://bitwarden.atlassian.net/browse/PM-19277
Hover state below modal in upgrade event logs view
https://github.com/user-attachments/assets/7321ede5-3574-475f-816d-84773b55f486 …
=> [PM-19277]Hover state below modal in upgrade event logs view

README.md
=> [PM-19046] Update README mobile references

libs/common/src/models/export/ssh-key.export.ts
https://bitwarden.atlassian.net/browse/PM-19571
Hotfix regression.
=> [PM-19571] do not import ssh keys when rehydrating exported data

libs/common/src/models/export/ssh-key.export.ts
Reverts bitwarden/clients#14012
=> Revert "[PM-19571] do not import ssh keys when rehydrating exported data"

apps/web/src/app/admin-console/organizations/collections/vault.component.html
https://bitwarden.atlassian.net/browse/PM-19503
Fixes table width to be full width when filters are hidden. …
=> [PM-19503] Fix provider table width

libs/vault/src/cipher-view/sshkey-sections/sshkey-view.component.html
Add data-testids to the View SSH Key component to enable automation …
=> [PM-19615] Add data-testids to View SSH Key Component

.github/renovate.json5, package-lock.json, package.json
[PM-14052](https://bitwarden.atlassian.net/browse/PM-14052)
Add [lit signals](https://lit.dev/docs/data/context/) to use with lit components in injected content script UX
[PM-14052]: …
=> [PM-14052] Add lit signals dependency

.github/workflows/test.yml
Removes the Codecov token which is no longer needed to upload results. …
=> Remove references to Codecov token

apps/browser/src/background/main.background.spec.ts, apps/browser/src/background/main.background.ts, apps/browser/tsconfig.json, libs/common/src/platform/scheduling/task-scheduler.service.ts, libs/platform/src/background-sync/background-sync.service.spec.ts, libs/platform/src/background-sync/background-sync.service.ts, libs/platform/src/background-sync/index.ts, libs/platform/src/index.ts, libs/platform/tsconfig.json, tsconfig.json
https://bitwarden.atlassian.net/browse/PM-19396
The browser extension was not performing scheduled background syncs as expected. This was due to missing task scheduling code that was accidentally removed during the web push implementation (PR https://github.com/bitwarden/clients/pull/11346).
This commit:
- Creates a new `BackgroundSyncService` to manage sync scheduling
- Properly initializes the sync interval in `main.background.ts`
- Adds a test to ensure the sync initialization code isn't accidentally removed again
- Organizes platform module structure to support the new service
Screenshots were taken from a locally running extension with the timers manually increased to sync every 30 seconds
- …
=> fix(browser): restore timer based background syncs

bitwarden_license/bit-web/src/app/admin-console/providers/clients/clients.component.html
https://bitwarden.atlassian.net/browse/PM-17359
Migrate provider clients component to tailwind and CL components.
Old:
New: …
=> [PM-17359] Migrate provider clients component

apps/web/src/app/vault/components/vault-items/vault-items.component.ts
https://bitwarden.atlassian.net/browse/PM-19655
Fixes QA bug found for limit item deletion work where the restore button shows for items not in the trash.
https://github.com/user-attachments/assets/275b1e29-6213-4099-b0bf-bb3524e1de92
- ❓ …
=> [PM-19655] Fix restore option showing for items not in trash

bitwarden_license/bit-web/src/app/admin-console/providers/providers.module.ts, bitwarden_license/bit-web/src/app/admin-console/providers/setup/setup-provider.component.html, bitwarden_license/bit-web/src/app/admin-console/providers/setup/setup-provider.component.ts
https://bitwarden.atlassian.net/browse/PM-17362
Migrates setup-provider.component off of bootstrap to tailwind and CL components.
Old:
New: …
=> [PM-17362] Migrate setup-provider.component

libs/vault/src/cipher-form/components/autofill-options/autofill-options.component.html
https://bitwarden.atlassian.net/browse/PM-19764
This PR disables the drag function when there is only a single website URI.
https://github.com/user-attachments/assets/4dadbded-df9e-4265-a23f-7f23d5b7a961
https://github.com/user-attachments/assets/e9620bec-ad2a-4118-b706-24b44f31490e …
=> [PM-19764] - Drag is not disabled when there is only a single website URI

apps/web/src/app/admin-console/organizations/manage/events.component.html
https://bitwarden.atlassian.net/browse/PM-19530
Replication steps
Set the web app to use dark mode
navigate to event logs as a free or families organization
observe the upgrade modal
Expected: the modal uses dark theme colors
Actual: the modal uses light theme colors …
=> [PM-19530]Theme not respected on upgrade modal

.github/workflows/build-browser-target.yml, .github/workflows/build-browser.yml, .github/workflows/build-cli-target.yml, .github/workflows/build-cli.yml, .github/workflows/build-desktop-target.yml, .github/workflows/build-desktop.yml, .github/workflows/build-web-target.yml, .github/workflows/build-web.yml
- Added comments to the top of the build workflows to explain why certain steps may or may not run, based on the source of the PR.
- Shortened the job name a bit to differentiate it from the workflow name so it reads better in the workflow view: …
=> Add comments to build workflows to indicate their intended use

apps/web/src/app/admin-console/organizations/settings/account.component.html, apps/web/src/locales/en/messages.json
https://bitwarden.atlassian.net/browse/PM-19003
Update the limit item deletion message. …
=> [PM-19003] Update the limit item deletion message.

apps/web/src/locales/en/messages.json
https://bitwarden.atlassian.net/browse/PM-16540
-
- 🎨 …
=> [PM-16540] Fix typo in newly introduced message

.github/workflows/build-web.yml
https://bitwarden.atlassian.net/browse/PM-19876
This PR updates the `Build Web` workflow in order to allow PRs to generate build artifacts without the need of secrets. …
=> Update build web workflow

.npmrc
We should always be pinning packages anyways, so this will default `npm install my-package` to install a pinned version.
https://docs.npmjs.com/cli/v11/commands/npm-install#save-exact …
=> Add save-exact=true

apps/desktop/desktop_native/macos_provider/src/registration.rs, apps/desktop/desktop_native/napi/index.d.ts, apps/desktop/desktop_native/napi/src/lib.rs, apps/desktop/macos/autofill-extension/CredentialProviderViewController.swift, apps/desktop/package.json, apps/desktop/src/autofill/services/desktop-autofill.service.ts
This adds a missing field on the request POC, "excludedCredentials". …
=> PM-19511: Add support for ExcludedCredentials

apps/desktop/src/autofill/services/desktop-fido2-user-interface.service.ts
When updatedCipher is newed up, it causes every "if(this.updatecIpher) flow - essential always trying to updated a passkey instead of creating one.  …
=> PM-8353: Simplify created/updatedCipher

apps/browser/src/autofill/fido2/content/messaging/messenger.ts
Replace the FallbackRequestedError rejection pattern with direct AbortController.abort() calls when destroying the Messenger. This eliminates misleading console errors and ensures correct cancellation behavior.
The FallbackRequestedError is intended specifically for user-requested WebAuthn fallbacks, not general message cleanup operations.
**Disclaimer:**
I do not have a complete understanding of the `Fido2ClientService`. It is possible that the `FallbackRequestedError` is indeed necessary in the `Messenger`, but I could not determine its usefulness based on the code or tests.
Moreover, I'm not sure whether `abort` should always be called on destroy. Should that be left entirely to the handler? If so, I believe the `onDestroy` logic in the `Messenger` could be removed altogether. …
=> [PM-19216] Properly handle message aborts during cleanup

apps/browser/src/background/main.background.ts, apps/browser/src/platform/ipc/ipc-content-script-manager.service.ts, libs/common/src/enums/feature-flag.enum.ts
=> [PM-18040] Inject ipc content script dynamically

apps/web/src/app/auth/settings/two-factor/two-factor-verify.component.ts
https://bitwarden.atlassian.net/browse/PM-20180?atlOrigin=eyJpIjoiNDg3OWEzM2IyYTY0NGVkMTliZTc4NzQ2YzcyNWEyODEiLCJwIjoiaiJ9
Fixes bug introduced by PM-8976: The two factor Duo setup menu was unable to open. Adding `OrganizationDuo` to the modal title generation function fixes the issue.
https://github.com/user-attachments/assets/56312da4-c61b-46eb-b01a-08db403ddf36 …
=> [PM-20180] Modal is not displayed when click on Manage option for 2FA on Orgs

apps/browser/scripts/package-safari.ps1, apps/desktop/scripts/after-pack.js
[Card](https://bitwarden.atlassian.net/browse/BRE-622)
- Mac app store certificate rotation …
=> [BRE-622] - Update Apple Signing certificte SHA-1

.github/workflows/deploy-web.yml
[BRE-777](https://bitwarden.atlassian.net/browse/BRE-777)
Fixing the output variable to use dashes to match what's provided by https://github.com/bitwarden/gh-actions/blob/main/download-artifacts/action.yml#L94  …
=> [BRE-777] Fixing output to match what's in gh-actions

.github/renovate.json5, .gitignore, nx.json, package-lock.json, package.json
https://bitwarden.atlassian.net/browse/PM-20239
This does commits 2, 3, and 4 from the [POC repo](https://github.com/addisonbeck/bitwarden-nx-poc).  …
=> [PM-20239] Initializing `nx`

apps/browser/src/autofill/content/components/buttons/close-button.ts, apps/browser/src/autofill/content/components/buttons/option-selection-button.ts, apps/browser/src/autofill/content/components/cipher/cipher-action.ts, apps/browser/src/autofill/content/components/icons/brand-icon-container.ts, apps/browser/src/autofill/content/components/notification/header.ts, apps/browser/src/autofill/content/components/option-selection/option-item.ts
[PM-20325](https://bitwarden.atlassian.net/browse/PM-20325)
Misc design fixes/tweaks (see commit messages) to match intended UX …
=> [PM-20325] - Misc design fixes/tweaks

libs/common/src/models/view/view.ts
n/a
To document when the `View` class should be used. 
n/a …
=> Add docs to view class

libs/common/src/enums/feature-flag.enum.ts
https://bitwarden.atlassian.net/browse/PM-20495
With the split of the Tools team, the feature flags owned by Data Insights and Reporting are moved into their own section …
=> [PM-20495] Move feature flags for Data Insights and Reporting

apps/browser/src/autofill/background/notification.background.ts
https://bitwarden.atlassian.net/browse/PM-20490
Added [of](https://rxjs.dev/api/index/function/of) to mitigate the erroneous return-type annotation which was causing `updatePassword` to never fire 
- 🤔 …
=> PM-20490 mitigate return-type annotation to allow update

apps/browser/src/_locales/en/messages.json, apps/desktop/src/locales/en/messages.json, apps/web/src/connectors/webauthn-fallback.ts, apps/web/src/locales/en/messages.json, libs/auth/src/angular/two-factor-auth/two-factor-auth.component.ts
https://bitwarden.atlassian.net/browse/PM-20055
Updates the text when a user is prompted to verify their identity.  …
=> [PM-20055] Clarify 2FA copy for security key

apps/browser/src/autofill/content/components/cipher/cipher-action.ts, apps/browser/src/autofill/content/components/cipher/cipher-item.ts, apps/browser/src/autofill/content/components/lit-stories/ciphers/cipher-action.lit-stories.ts, apps/browser/src/autofill/content/components/lit-stories/notification/body.lit-stories.ts, apps/browser/src/autofill/content/components/notification/body.ts, apps/browser/src/autofill/content/components/notification/button-row.ts, apps/browser/src/autofill/content/components/notification/container.ts, apps/browser/src/autofill/content/components/notification/footer.ts, apps/browser/src/autofill/notification/bar.ts
https://bitwarden.atlassian.net/browse/PM-19281
The objective of this PR is to localize text utilized throughout the notification bar experience up to this point. …
=> PM-19281 localize relevant notification bar text

libs/vault/src/cipher-form/components/autofill-options/uri-option.component.html
https://bitwarden.atlassian.net/browse/PM-19134
This PR updates a class name to use the `tw` prefix …
=> [PM-19134] - Migrate uri-option.component.html

apps/browser/src/autofill/background/notification.background.ts
https://bitwarden.atlassian.net/browse/PM-20393
We want to only return the matching cipher on update for the time being, get decrypted ciphers has been updated to support this, upcoming changes to the saving ciphers will impact this method which I decided to isolate the change to update for now. 
https://github.com/user-attachments/assets/063d61f0-5a4e-43fd-a26b-cd9509f0493d …
=> PM-20393 return only matching ciphers on type of change

libs/common/src/key-management/crypto/services/encrypt.service.implementation.ts
https://github.com/bitwarden/clients/pull/14371
Fixes the build issue introduced my merging main in https://github.com/bitwarden/clients/pull/14371 without requiring re-review from all teams.
- 🤔 …
=> [PM-20492] Remove key.key.bytelength check in encryptUint8array

libs/common/src/key-management/crypto/abstractions/encrypt.service.ts, libs/common/src/key-management/crypto/services/encrypt.service.implementation.ts, libs/common/src/key-management/crypto/services/encrypt.service.spec.ts
https://bitwarden.atlassian.net/browse/PM-20567
To better structure the move of all domain code to the new methods, this PR first introduces the new APIs, and proxies them to the old ones, and marks the old ones as deprecated. This way, we can move each team individually with one PR, to make for a much simpler PR chain. Further, the proxy implementation can be directly replaced with an SDK implementation (that supports the new features for COSE).
- …
=> [PM-20567] Add new encrypt service functions

apps/web/src/app/billing/organizations/change-plan-dialog.component.html, apps/web/src/app/billing/organizations/change-plan-dialog.component.ts, apps/web/src/app/billing/organizations/organization-subscription-cloud.component.ts
https://bitwarden.atlassian.net/browse/PM-20984
Missed several Free Organization considerations when resolving [PM-20300](https://bitwarden.atlassian.net/browse/PM-20300).
https://github.com/user-attachments/assets/40a35e1d-cacd-4385-a10e-a3c310efca1b …
=> [PM-20984] Fix free organization upgrade/change plan issues

apps/browser/src/autofill/content/components/cipher/cipher-info.ts
https://bitwarden.atlassian.net/browse/PM-21027
Add tooltip to item name in cipher info  …
=> PM-21027-add tooltip to cipher item name in notification bar

apps/desktop/macos/autofill-extension/CredentialProviderViewController.swift
- **Exclude credentials using kvc to avoid comilation error in cicd**
=> PM-8353: Fix compilation errors

.github/renovate.json5
Architecture owns linting dependencies.
- 🎨 (`:art:`) …
=> Move additional linting to architecture

apps/desktop/src/main/menu/menu.file.ts, apps/desktop/src/vault/app/vault/vault-items-v2.component.html, apps/desktop/src/vault/app/vault/vault-v2.component.html, apps/desktop/src/vault/app/vault/vault-v2.component.ts, apps/desktop/src/vault/app/vault/vault.component.ts
https://bitwarden.atlassian.net/browse/PM-19579
This PR adds the "SSH Key" option when creating a new cipher in the desktop via the "+" button or from the menu. It also removed some unused menu code in `vault-v2.component.ts` as the menu items are already defined in `vault-items.v2.component.html`
https://github.com/user-attachments/assets/6c5d280f-9336-475e-ab3d-aa4af70296d8 …
=> [PM-19579] - add sshKey option to desktop

apps/browser/webpack.config.js
https://bitwarden.atlassian.net/browse/PM-20424
Speeds up Browser build for development by leveraging caching and turning off optimisations.
- On M3 Pro with NODE_OPTIONS="--max-old-space-size=8192"
- Measured using `/usr/bin/time -l npm run build:watch`
|Script| Before                                                   | After                                                            |
|---|----------------------------------------------------------|------------------------------------------------------------------|
|First run, no cache| 45 seconds main, 30 seconds background, 5.2GB max memory | 25 seconds main, 31 seconds background, 5.2GB max memory  |
|Subsequent run with caching, minimal or no changes to source code| (the same as no cache)                                   | 16 …
=> [PM-20424] [BEEEP] browser client webpack optimisations

apps/web/src/app/billing/members/free-bitwarden-families.component.ts
https://bitwarden.atlassian.net/browse/PM-21106
The incorrect parameter was being passed to `DELETE /organization/sponsorship/{organizationId}`. 
https://github.com/user-attachments/assets/b676d16f-db63-4743-aca2-c0e44552f241
- ❓ …
=> [PM-21106] Fix remove sponsorship invocation for admin-initiated sponsorships

libs/vault/src/services/default-change-login-password.service.spec.ts, libs/vault/src/services/default-change-login-password.service.ts
[PM-19026](https://bitwarden.atlassian.net/browse/PM-19026)
The CSP on the web and desktop prevent the clients from making requests to URLs to find the `well known` url to make a password change. Currently this throws error for each URI on the cipher.
- Add check for platforms that are not the browser to short circuit and return the first URL available. 
- A full server driven solution will be built as a part of [PM-21024](https://bitwarden.atlassian.net/browse/PM-21024)
No errors in web, browser still finds the well known URL
<video src="https://github.com/user-attachments/assets/33cb86e5-5b02-408e-88ab-486b3d547fe0" /> …
=> [PM-19026] Short circuit well known URL check 

apps/browser/src/autofill/content/components/notification/confirmation/body.ts, apps/browser/src/autofill/content/components/notification/confirmation/message.ts
https://bitwarden.atlassian.net/browse/PM-21282
- 🎨 …
=> PM-21282 reintroduce item name 

apps/web/src/app/billing/organizations/organization-plans.component.ts, apps/web/src/app/billing/shared/self-hosting-license-uploader/organization-self-hosting-license-uploader.component.ts, libs/common/src/billing/services/organization-billing.service.ts
https://bitwarden.atlassian.net/browse/PM-21001
Moves billing files to the new encrypt interface functions introduced in https://github.com/bitwarden/clients/pull/14398 …
=> [PM-21001] Move billing code to new encrypt service interface

bitwarden_license/bit-web/src/app/admin-console/organizations/organizations-routing.module.ts
https://bitwarden.atlassian.net/browse/PM-21372
> Fix the `domain-verification` routing by removing the `resolve` property and replacing it with the `data` property. …
=> [PM-21372] Replace resolve with data in organization routing

bitwarden_license/bit-web/src/app/secrets-manager/projects/project.service.ts, bitwarden_license/bit-web/src/app/secrets-manager/secrets/secret.service.spec.ts, bitwarden_license/bit-web/src/app/secrets-manager/secrets/secret.service.ts, bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/access/access.service.ts, bitwarden_license/bit-web/src/app/secrets-manager/service-accounts/service-account.service.ts, bitwarden_license/bit-web/src/app/secrets-manager/settings/services/sm-porting-api.service.spec.ts, bitwarden_license/bit-web/src/app/secrets-manager/settings/services/sm-porting-api.service.ts, bitwarden_license/bit-web/src/app/secrets-manager/shared/access-policies/access-policy.service.spec.ts, bitwarden_license/bit-web/src/app/secrets-manager/shared/access-policies/access-policy.service.ts
https://bitwarden.atlassian.net/browse/PM-21001
Moves SM files to the new encrypt interface functions introduced in https://github.com/bitwarden/clients/pull/14398 …
=> [PM-21001] Move sm code to new encrypt service interface

.github/workflows/build-browser.yml, .github/workflows/build-desktop.yml, .github/workflows/build-web.yml
Reverts bitwarden/clients#12310
=> Revert "[deps]: Update crowdin/github-action action to v2"

apps/desktop/src/locales/en/messages.json
https://bitwarden.atlassian.net/browse/PM-21408
This PR re-adds the i18n keys that were inadvertently removed in [this PR](https://github.com/bitwarden/clients/pull/14417)  …
=> [PM-21408] - re-add missing desktop cipher form i18n keys

apps/browser/src/_locales/en/messages.json, apps/browser/src/vault/popup/settings/download-bitwarden.component.html, apps/browser/src/vault/popup/settings/download-bitwarden.component.ts
https://bitwarden.atlassian.net/browse/PM-21277
This PR fixes multiple issues to the download bitwarden component:
- add alt tags to app store and google play image links
- add `bitLink` directive to all anchor tags
- remove account switcher from header
https://github.com/user-attachments/assets/c97dce0e-43de-47b0-8d84-e354aee650d8 …
=> [PM-21277] - multiple fixes for Download Bitwarden component

libs/common/src/platform/services/key-generation.service.spec.ts, libs/common/src/platform/services/key-generation.service.ts
Follow-up to https://github.com/bitwarden/clients/pull/14371
As per suggestion by @Thomas-Avery here: https://github.com/bitwarden/clients/pull/14371#discussion_r2059089179 this adds unit tests for stretchKey, and makes it throw if a 64 byte key is passed in. …
=> [PM-20492] Clean up stretchKey

apps/desktop/src/vault/app/vault/vault-v2.component.ts
https://bitwarden.atlassian.net/browse/PM-21196
This PR fixes an issue where the desktop vault wasn't properly getting the "partial-edit" in the cipher form for non-edit users.
https://github.com/user-attachments/assets/7a2adc4f-b735-44af-84cc-28ceb188a97f …
=> [PM-21196] - [Desktop] - set cipher form to partial edit for non edit permission

libs/vault/src/cipher-view/card-details/card-details-view.component.html, libs/vault/src/cipher-view/card-details/card-details-view.component.ts, libs/vault/src/cipher-view/custom-fields/custom-fields-v2.component.ts, libs/vault/src/cipher-view/login-credentials/login-credentials-view.component.html, libs/vault/src/cipher-view/login-credentials/login-credentials-view.component.ts
https://bitwarden.atlassian.net/browse/PM-21021
This PR fixes an issue where the hidden field state was persisting between different cipher views.
https://github.com/user-attachments/assets/a3397e47-71d3-4cb3-b96e-ac9503e9034a
https://github.com/user-attachments/assets/2b6bb8f9-2b9d-4cd3-97f0-4d916f57f081
- 📝 …
=> [PM-21021] - fix toggled hidden field state for custom fields view

apps/browser/src/platform/services/platform-utils/browser-platform-utils.service.ts
https://bitwarden.atlassian.net/browse/PM-17111
While doing the server work for this task we clarified for ourselves how this works and decided to leave a helpful comment for the next reader.
- 🤔 …
=> docs(update-auth-approving-clients): [PM-17111] Add Browser to List of Approving Clients

libs/common/src/key-management/master-password/services/master-password.service.spec.ts
Adds tests to the decryption function of the masterpasswordservice …
=> Add tests for masterpasswordservice

.github/renovate.json5, .storybook/preview.tsx, .storybook/test-runner.ts, package-lock.json, package.json, tsconfig.eslint.json
https://bitwarden.atlassian.net/browse/CL-301
Adds Storrybook addons for test runner and a11y …
=> [CL-301] Enable Storybook test runner. Run a11y tests also

apps/desktop/src/autofill/preload.ts, apps/desktop/src/autofill/services/desktop-autofill.service.ts, apps/desktop/src/platform/main/autofill/native-autofill.main.ts
This PR improves the autofill IPC reliability, especially when the app goes through a cold start.
=> Improve Autofill IPC reliability

apps/cli/package.json, bitwarden_license/bit-cli/src/bw.ts, package-lock.json
https://bitwarden.atlassian.net/browse/PM-19878
We added a dependency to core-js with https://github.com/bitwarden/clients/pull/13353 in the CLI which means we should be installing core-js when installing the cli through npm.
Resolves https://github.com/bitwarden/clients/issues/14121 …
=> [PM-19878] Add core-js to cli

.github/CODEOWNERS
https://bitwarden.atlassian.net/browse/PM-21639
The implementation of Nx requires some very basic, repetitive changes to all jest configs across the monorepo.
While doing this Platform has identified some ways we could improve the general experience and code reuse between jest configs across the project.
To that end we'd like to assume ownership of jest configs for the period of time that Nx is being implemented. As followup work for the implementation we will be refactoring jest across the project to take a similar approach to configuration as Nx does for tsconfig. To simplify: we will be creating a base jest config to be extended across clients.
Once Nx is implemented we will be removing the (already present) override to the ownership rule for tsconfig, and after the jest configuration …
=> assume temporary ownership of jest config

apps/desktop/electron-builder.json
https://github.com/bitwarden/clients/issues/14394
Fixed issue on given link …
=> [PM-20588] Fixed app description

angular.json
Bit-web needs to exist in angular.json for migrations to accurately capture those files. …
=> Add bit-web to angular.json

apps/browser/src/autofill/content/components/notification/confirmation/body.ts
[PM-21455](https://bitwarden.atlassian.net/browse/PM-21455)
Fixes Safari specific rendering of fit-content on height for SVG. …
=> [PM-21455] Replace fit-content with auto

apps/browser/src/autofill/fido2/utils/webauthn-utils.ts, libs/common/src/platform/services/fido2/fido2-utils.ts
This reverts commit df8d184889ef9accf5d07c3d740eb976d30dffea.
https://bitwarden.atlassian.net/browse/PM-21553
QA asked to test this in a feature branch before merging to main. This reverts the merge to main. …
=> Revert "PM-21553: Added support for credential.toJSON() (#14734)"

libs/common/src/platform/services/fido2/fido2-utils.spec.ts
Adds tests for changes made in PM-19511
Adds tests for `Fido2Utils.cipherHasNoOtherPasskeys` to test true scenarios where passkeys match or there are no passkeys, or false scenarios where passkeys don't match. …
=> Add tests for `cipherHasNoOtherPasskeys`

libs/auth/src/angular/sso/sso.component.ts, libs/common/src/enums/feature-flag.enum.ts
https://bitwarden.atlassian.net/browse/PM-21471
Removes feature flag and associated logic from clients. …
=> [PM-21471] Remove feature flag logic

apps/web/src/app/billing/organizations/change-plan-dialog.component.ts
https://bitwarden.atlassian.net/browse/PM-21875
Adds data validation to the upgrade dialog where it was missing …
=> [PM-21875] Added data validation where it was missing to upgrade dialog

apps/browser/src/auth/popup/settings/account-security.component.ts
N/A
Fix bad import in the AccountSecurity component.
N/A
=> Fix `SpotlightComponent` import

apps/web/src/app/admin-console/organizations/manage/group-add-edit.component.html, apps/web/src/app/admin-console/organizations/manage/group-add-edit.component.ts, apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.html, apps/web/src/app/admin-console/organizations/members/components/member-dialog/member-dialog.component.ts, apps/web/src/app/admin-console/organizations/shared/components/collection-dialog/collection-dialog.component.html, apps/web/src/app/admin-console/organizations/shared/components/collection-dialog/collection-dialog.component.ts, libs/common/src/enums/feature-flag.enum.ts
https://bitwarden.atlassian.net/browse/PM-18524
Remove feature flagged logic from clients. …
=> [PM-18633] Remove feature flagged logic

libs/tools/generator/core/src/metadata/password/sdk-eff-word-list.spec.ts, libs/tools/generator/core/src/metadata/password/sdk-eff-word-list.ts, libs/tools/generator/core/src/metadata/password/sdk-random-password.spec.ts, libs/tools/generator/core/src/metadata/password/sdk-random-password.ts
N/A
Fix type errors caused by merge of generator credential service merge. …
=> align sdk generator types

libs/common/src/admin-console/abstractions/policy/policy.service.abstraction.ts
Follow up to https://bitwarden.atlassian.net/browse/PM-21085
Add additional jsdoc to PolicyService, particularly around its data source and the pitfalls of using it before the first sync has completed.
- 🤔 …
=> Add additional jsdoc to PolicyService

.github/renovate.json5
We chose to block `lowdb` from upgrading since we don't support ES Modules. This PR blocks the types related to that package …
=> Pin @types/lowdb to v1

.github/workflows/chromatic.yml
Follow up to BRE-609
update the pull_request_target section to be compliant with our workflow linter rules, only allowing it to run against `main` …
=> fix chromatic linter failure

bitwarden_license/bit-web/src/app/dirt/access-intelligence/all-applications.component.html, bitwarden_license/bit-web/src/app/dirt/access-intelligence/all-applications.component.ts, bitwarden_license/bit-web/src/app/dirt/access-intelligence/app-table-row-scrollable.component.html, bitwarden_license/bit-web/src/app/dirt/access-intelligence/app-table-row-scrollable.component.ts, bitwarden_license/bit-web/src/app/dirt/access-intelligence/critical-applications.component.html, bitwarden_license/bit-web/src/app/dirt/access-intelligence/risk-insights.component.html, bitwarden_license/bit-web/src/app/dirt/access-intelligence/risk-insights.component.ts, libs/common/src/enums/feature-flag.enum.ts
https://bitwarden.atlassian.net/browse/PM-14469
Removing client feature flag for critical applications. Any related logic has also been removed.  …
=> [PM-14469] Removing critical applications feature flag and logic

apps/web/src/app/core/init.service.ts
https://bitwarden.atlassian.net/browse/PM-21914
This PR adds `taskService.listenForTaskNotifications` to `InitService` to ensure security tasks are refreshed when a new task notification is sent.
https://github.com/user-attachments/assets/9a5b97c1-862d-445c-991c-a792a98eab16 …
=> [PM-21914] - add taskService.listenForTaskNotifications to init service

apps/web/src/app/key-management/migrate-encryption/migrate-legacy-encryption.component.ts, libs/key-management-ui/src/key-rotation/key-rotation-trust-info.component.ts, libs/key-management-ui/src/lock/components/lock.component.ts, libs/key-management-ui/src/trust/account-recovery-trust.component.ts, libs/key-management-ui/src/trust/emergency-access-trust.component.ts
https://bitwarden.atlassian.net/browse/CL-714
Remove `standalone: true` from every instance since it's the default as of Angular 19. …
=> [CL-714] Remove standalone true from km

apps/web/src/app/layouts/product-switcher/navigation-switcher/navigation-switcher.stories.ts, apps/web/src/app/layouts/product-switcher/product-switcher.module.ts, apps/web/src/app/layouts/product-switcher/shared/product-switcher.service.spec.ts, apps/web/src/app/layouts/product-switcher/shared/product-switcher.service.ts, apps/web/webpack.config.js, bitwarden_license/bit-web/src/app/secrets-manager/overview/overview.component.ts
We needed to update the CSP rule for ng-select. And our old `I18nPipe` caused some errors for the product switcher in the navigation. …
=> Fix ng select and product switcher

apps/browser/src/background/main.background.ts, apps/browser/src/vault/popup/components/vault-v2/vault-v2.component.html, libs/angular/src/services/jslib-services.module.ts, libs/common/src/enums/feature-flag.enum.ts, libs/common/src/vault/tasks/services/default-task.service.spec.ts, libs/common/src/vault/tasks/services/default-task.service.ts, libs/vault/src/components/assign-collections.component.spec.ts
https://bitwarden.atlassian.net/browse/PM-19632
- 🎨 …
=> [PM-19632] Remove security task flag - step 1

libs/common/src/abstractions/api.service.ts, libs/common/src/services/api.service.ts, libs/common/src/vault/services/cipher.service.ts
https://bitwarden.atlassian.net/browse/PM-22344
This PR updates the type for the `shareManyWithServer` endpoint to match the new response type implemented in [this PR](https://github.com/bitwarden/server/pull/5911). …
=> [PM-22344] - update response type for shareManyWithServer

apps/web/src/app/auth/settings/account/profile.component.html
https://bitwarden.atlassian.net/browse/PM-21904
This PR ensures the link next to "This account is owned by $ORG" opens in a new tab instead of navigating away from the current page.
https://github.com/user-attachments/assets/425277c6-02f8-464c-8a19-189f5c84e78f …
=> [PM-21904]  - open claimed-accounts in new tab

apps/web/src/app/admin-console/organizations/policies/index.ts, apps/web/src/app/admin-console/organizations/policies/policies.component.ts, apps/web/src/app/admin-console/organizations/policies/policies.module.ts, apps/web/src/app/admin-console/organizations/policies/restricted-item-types.component.html, apps/web/src/app/admin-console/organizations/policies/restricted-item-types.component.ts, apps/web/src/locales/en/messages.json, libs/common/src/admin-console/enums/policy-type.enum.ts, libs/common/src/enums/feature-flag.enum.ts
https://bitwarden.atlassian.net/browse/PM-19306
This PR adds the "Remove Card Item Type" Policy to the AC. There are plans to expand this to all item types so this PR keeps the naming generic so we can simply add an array of `CipherType`s to the form data when the time comes.
[Corresponding server PR](https://github.com/bitwarden/server/pull/5914)
https://github.com/user-attachments/assets/6cf70317-516b-4356-afa0-25014e2aee6f …
=> [PM-19306] - [Vault] In Admin Console Policies area add the remove card item type policy

.github/workflows/build-cli.yml
Confirm the dependencies in `apps/cli/package.json` are sufficient to run the CLI. (the version we publish to npm) …
=> Confirm we can run the npm published CLI

apps/web/webpack.config.js
[CL-525](https://bitwarden.atlassian.net/browse/CL-525)
As part of the Angular 19 upgrade, the virtual scroll cdk had css changes that resulted in a new hash. Angular also added a new injected style for their `cdk-visually-hidden` class. The class is already declared in other imported css from Angular and working fine in our code, so adding the hash here is technically unnecessary, but it looks like this is an intermediary step on the Angular side to deprecate the existing css, so I've added it. ([See Angular PR here.](https://github.com/angular/components/pull/29757))
- Used …
=> [CL-525] Update more Angular CSPs for v19 upgrade

apps/web/src/app/billing/organizations/change-plan-dialog.component.ts, apps/web/src/app/billing/organizations/organization-subscription-cloud.component.html, apps/web/src/app/billing/organizations/organization-subscription-cloud.component.ts
https://bitwarden.atlassian.net/browse/PM-20416
Replication steps
Create a paid org with a subscription
cancel the subscription and downgrade the organization to a Free org (do not remove the customer or subscription info)
navigate to billing > Subscription
select “upgrade plan”
Expected: the upgrade modal allows the free org to select between paid org types
Actual: the upgrade modal only allows the org to select free org type …
=> [PM 20416]Downgraded paid org cannot upgrade from Free

apps/web/src/app/secrets-manager/secrets-manager-landing/request-sm-access.component.ts, apps/web/src/app/secrets-manager/secrets-manager-landing/sm-landing.component.ts
https://bitwarden.atlassian.net/browse/CL-714
Remove `standalone: true` from every instance since it's the default as of Angular 19. …
=> [CL-714] Remove standalone true from sm

libs/admin-console/src/common/collections/models/collection.data.ts, libs/admin-console/src/common/collections/models/collection.response.ts, libs/admin-console/src/common/collections/models/collection.spec.ts, libs/admin-console/src/common/collections/models/collection.ts, libs/admin-console/src/common/collections/models/collection.view.ts, libs/vault/src/cipher-form/components/item-details/item-details-section.component.spec.ts
https://bitwarden.atlassian.net/browse/PM-22099
Add CollectionType enum and types. …
=> [PM-22099] expose default collection in clients collection service

libs/components/src/tw-theme.css
https://bitwarden.atlassian.net/browse/CL-687
Updates to a few semantic colors in dark mode …
=> [CL-687] Updated dark mode color variables

.github/workflows/build-browser.yml, .github/workflows/build-desktop.yml, .github/workflows/build-web.yml, apps/web/crowdin.yml
Revert https://github.com/bitwarden/clients/pull/14929, which still doesn't quite work …
=> Revert "[deps]: Update crowdin/github-action action to v2 (#14929)"

apps/desktop/src/main.ts
https://bitwarden.atlassian.net/browse/PM-21502
Implement the workaround described here: https://github.com/electron/electron/issues/46538 …
=> Implement workaround for breaking change in electron 36

apps/web/src/app/admin-console/organizations/organization-routing.module.ts
[PM-18390](https://bitwarden.atlassian.net/browse/PM-18390)
This fixes the navigation for a Teams Org to be able to access the integrations page.
https://github.com/user-attachments/assets/867cf6b6-1f32-4e1d-9182-339da39dd44f
- ❓ …
=> [PM-18390] - Fix Teams Integration Navigation

libs/angular/src/vault/components/vault-items.component.ts
https://bitwarden.atlassian.net/browse/PM-22841
This PR fixes an issue introduced in [this PR](https://github.com/bitwarden/clients/pull/15176)  where the desktop vault list was showing a blank list of ciphers. …
=> [PM-22841] - [Desktop]  - Vault items shows blank cipher list

apps/browser/src/key-management/biometrics/background-browser-biometrics.service.ts
https://bitwarden.atlassian.net/browse/PM-22719
`Injectable` is for angular, this only runs in the background.  …
=> Remove injectable from background-browser-biometrics

apps/browser/src/_locales/en/messages.json, apps/browser/src/auth/popup/settings/account-security.component.ts
[PM-22419](https://bitwarden.atlassian.net/browse/PM-22419)
Replace the message.json value for the success toast with the correct text …
=> [PM-22419] update success toast text

apps/web/src/app/admin-console/organizations/policies/restricted-item-types.component.ts, apps/web/src/locales/en/messages.json
https://bitwarden.atlassian.net/browse/PM-22741
This PR adds missing copy for the remove card item type policy. …
=> [PM-22741] - [Defect] Missing copy in the Edit policy Remove card item type policy

apps/desktop/src/main/menu/menu.file.ts
https://bitwarden.atlassian.net/browse/PM-22453
This PR updates the desktop menu ribbon New -> "Secure Note" to "Note". The remaining changes have already been applied in a [separate PR](https://github.com/bitwarden/clients/pull/15176).
- …
=> [PM-22453] - [Desktop] Rename Secure note to Note

apps/web/src/app/admin-console/organizations/members/members.component.ts
https://bitwarden.atlassian.net/browse/PM-23026
fixes erroneous `takeUntilDestroyted`. …
=> [PM-23026] fix error

apps/web/src/app/admin-console/organizations/members/services/organization-user/organization-user.service.ts, apps/web/src/app/admin-console/organizations/shared/components/access-selector/access-selector.component.html, apps/web/src/locales/en/messages.json
https://bitwarden.atlassian.net/browse/PM-23086
Fixes missing i18n string and typo in default collection name …
=> [PM-23086] fix My Items collection name

apps/desktop/src/platform/services/desktop-settings.service.ts
Related: https://bitwarden.atlassian.net/browse/PM-23126
Based on direction from the platform team, new settings should only be added to the Desktop Settings Service if they are owned by platform. Other teams should add settings to their own relevant service. …
=> Note for DesktopSettingsService

apps/desktop/electron-builder.json, apps/desktop/src/autofill/modal/credentials/fido2-create.component.html, apps/desktop/src/autofill/modal/credentials/fido2-create.component.spec.ts, apps/desktop/src/autofill/modal/credentials/fido2-create.component.ts, apps/desktop/src/autofill/modal/credentials/fido2-excluded-ciphers.component.spec.ts, apps/desktop/src/autofill/modal/credentials/fido2-excluded-ciphers.component.ts, apps/desktop/src/autofill/modal/credentials/fido2-vault.component.spec.ts, apps/desktop/src/autofill/modal/credentials/fido2-vault.component.ts, apps/desktop/src/autofill/services/desktop-fido2-user-interface.service.ts, libs/components/src/dialog/simple-dialog/types.ts
Refactor the three passkey modals to clean up the code a little, fix typescript typing issues, and *hopefully* make these modals clearer for future changes. …
=> Refactor Fido2 Components

apps/browser/src/manifest.json
https://bitwarden.atlassian.net/browse/PM-14942
To add `notifications` to the extension requested permissions to be able to show login approval notifications. 
n/a …
=> Auth/PM-14942 - feat(manifest): add notifications to requested extension permissions for extension login approval notifications

libs/common/src/vault/services/cipher.service.ts, libs/vault/src/cipher-form/components/new-item-nudge/new-item-nudge.component.html, libs/vault/src/cipher-form/components/new-item-nudge/new-item-nudge.component.spec.ts, libs/vault/src/cipher-form/components/new-item-nudge/new-item-nudge.component.ts
[PM-23197](https://bitwarden.atlassian.net/browse/PM-23197)
After deleting a collection, the `cipherService.getAllDecrypted` was returning an empty array. This was getting picked up in the newItemNudges when looking at `cipherService.cipherViews$`. This caused the `newItemNudge` to show in the edit view even when the user still had items in their vault.
Updated the `getAllDecrypted` call to return the decCiphers in the initial if block
Also updated the nudgeComponent to use Observables and update spec
https://github.com/user-attachments/assets/9bb32802-89c5-4e75-acbe-4ec10b39c898 …
=> [PM-23197] update cipherService to return decCiphers

libs/angular/src/services/jslib-services.module.ts, libs/common/src/key-management/sends/abstractions/index.ts, libs/common/src/key-management/sends/abstractions/send-password.service.ts, libs/common/src/key-management/sends/index.ts, libs/common/src/key-management/sends/services/default-send-password.service.spec.ts, libs/common/src/key-management/sends/services/default-send-password.service.ts, libs/common/src/key-management/sends/services/index.ts, libs/common/src/key-management/sends/types/index.ts, libs/common/src/key-management/sends/types/send-hashed-password.type.ts
https://bitwarden.atlassian.net/browse/PM-23700
To create a `SendPasswordService` to provide a KM owned service for hashing raw send passwords and returning a hashed password. Note: all of the hashing code was taken from the existing Send `access.component.ts` `load` method. This code isn't feature flagged as it will be consumed by the new send components later on. Also, this was discussed with @Thomas-Avery to get early feedback on the idea. 
n/a
- …
=> Auth/PM-23700 -  Create SendPasswordService

apps/browser/src/_locales/en/messages.json, apps/browser/src/vault/popup/components/vault-v2/vault-list-items-container/navigation-dialog/vault-item-group-navigation-dialog.component.html, apps/browser/src/vault/popup/components/vault-v2/vault-list-items-container/navigation-dialog/vault-item-group-navigation-dialog.component.ts, apps/browser/src/vault/popup/components/vault-v2/vault-list-items-container/navigation-dialog/vault-item-group-navigation-dialog.service.ts, apps/browser/src/vault/popup/components/vault-v2/vault-list-items-container/navigation-dialog/vault-item-group-navigation-dialog.stories.ts, apps/browser/src/vault/popup/components/vault-v2/vault-list-items-container/vault-list-items-container.component.html, apps/browser/src/vault/popup/components/vault-v2/vault-list-items-container/vault-list-items-container.component.ts, libs/common/src/platform/state/state-definitions.ts, libs/components/src/a11y/index.ts, libs/components/src/utils/focus-visible-within.ts, libs/components/src/utils/index.ts
https://bitwarden.atlassian.net/browse/CL-277
- 🎨 …
=> [CL-724] Vault list item keyboard nav dialog

libs/common/src/enums/feature-flag.enum.ts
https://bitwarden.atlassian.net/browse/PM-18021
Adds `ForceUpdateKDFSettings` feature flag. …
=> [PM-18021] Feature flag for ForceUpdateKDFSettings

libs/angular/src/auth/password-management/change-password/change-password.component.ts
https://bitwarden.atlassian.net/browse/PM-23811
Fixed angular common import to now properly handle the ngIf to show the callout. …
=> fix(change-password): [PM-23811] Callout Missing Bug

apps/desktop/src/vault/app/vault/vault-filter/filters/organization-filter.component.html
https://bitwarden.atlassian.net/browse/PM-23752
This PR renames the switch case in the org filters component that was missed from the [policy renaming PR](https://github.com/bitwarden/clients/pull/15228).
https://github.com/user-attachments/assets/2bfd4926-7433-400d-94af-aadecfd5b9d3 …
=> [PM-23752] - [Desktop] My Vault showing in filter when user belongs to one org with policy enabled

apps/web/src/locales/en/messages.json, bitwarden_license/bit-web/src/app/admin-console/organizations/manage/domain-verification/domain-verification.component.html
https://bitwarden.atlassian.net/browse/PM-20128
> Update Claimed Domains description verbiage and update container max width. …
=> [PM-20128] Update Claimed Domains description

apps/desktop/desktop_native/autotype/src/windows.rs, apps/desktop/src/app/services/services.module.ts, apps/desktop/src/autofill/main/main-desktop-autotype.service.ts, apps/desktop/src/autofill/preload.ts, apps/desktop/src/autofill/services/desktop-autotype.service.ts, apps/desktop/src/main.ts
https://bitwarden.atlassian.net/browse/PM-22789
- 🎨 …
=> [PM-22789] Handle Hotkey Event for Autotype

.github/workflows/deploy-web.yml
[BRE-831](https://bitwarden.atlassian.net/browse/BRE-831)
Fixing permissions …
=> [BRE-831] Fixing permissions

.github/workflows/build-browser-target.yml, .github/workflows/build-desktop-target.yml, .github/workflows/build-web-target.yml
[BRE-831](https://bitwarden.atlassian.net/browse/BRE-831)
Fixing PR target permissions, which are required because of the crowdin-push job in the underlying build workflows …
=> [BRE-831] Fixing PR target permissions

apps/browser/src/autofill/background/auto-submit-login.background.ts
[PM-23036](https://bitwarden.atlassian.net/browse/PM-23036)
Prevents failed initialization of the auto-submit login policy because `getUserId` was being called on a locked account, which errored and canceled the observable subscription.
- …
=> Only call activeAccount$ when activeAccountStatus$ is Unlocked.

libs/angular/src/vault/abstractions/deprecated-vault-filter.service.ts
https://bitwarden.atlassian.net/browse/PM-24040
Migrate vault abstract services to strict ts …
=> [PM-24040] Migrate vault abstract services to strict ts

libs/common/src/platform/abstractions/fido2/fido2-active-request-manager.abstraction.ts
https://bitwarden.atlassian.net/browse/PM-24043
Migrate platform owned abstract service to strict ts …
=> [PM-24043] Migrate platform owned abstract service to strict ts

libs/components/tailwind.config.base.js
https://bitwarden.atlassian.net/browse/CL-685
Update 'xs' font size to 13px/.8125rem …
=> [CL-685] update xs text size

.github/workflows/scan.yml
https://bitwarden.atlassian.net/browse/VULN-254
During #15635 the test-inclusions and exclusions were mistakenly removed. This is restoring those values. …
=> Add mistakenly removed parameters for Sonar

apps/web/src/app/vault/components/setup-extension/setup-extension.component.html
[PM-24125](https://bitwarden.atlassian.net/browse/PM-24125)
Swapped the `href` for the Learning Center and Help links on the success state
<video src="https://github.com/user-attachments/assets/3840bd95-da58-4b77-896f-b4258ded898a" />
- ⛏ (`:pick:`) for minor or nitpick …
=> [PM-24125] Swap destinations for learning center and help links

.github/workflows/deploy-web.yml
[BRE-1022](https://bitwarden.atlassian.net/browse/BRE-1022)
Replacing Service Principals with Managed Identities for azcopy in deploy-web.yml …
=> [BRE-1022] Replacing SPs with Managed Identity for Deploy Web

.github/workflows/deploy-web.yml
Reverts bitwarden/clients#15830
=> Revert "[BRE-1022] Replacing SPs with Managed Identity for Deploy Web"

.github/workflows/deploy-web.yml
[BRE-1022](https://bitwarden.atlassian.net/browse/BRE-1022)
Replacing service principal credentials to use managed identity access …
=> [BRE-1022] Replace SPs with Managed Identities

package-lock.json, package.json
[PM-21691](https://bitwarden.atlassian.net/browse/PM-21691)
This updates the sdk to the latest version in clients. …
=> [PM-21691] Update internal-sdk to 0.2.0-main.242

apps/web/src/app/billing/trial-initiation/complete-trial-initiation/complete-trial-initiation.component.html
https://bitwarden.atlassian.net/browse/PM-24174
**Problem**
When users complete trial initiation and click "Create Account", the button does not show a loading state during the account creation process, providing poor user feedback.
**Root Cause**
The trial initiation component (`CompleteTrialInitiationComponent`) was missing the `[loading]="submitting"` binding on its <auth-input-password> components. While the component properly manages the `submitting` state internally, this state was not being communicated to the child component to trigger the loading UI.
**Solution**
Added the missing `[loading]="submitting"` binding to both `<auth-input-password>` components in the trial initiation template:
- Non-stepper flow component
- Stepper flow "Create Account" step component
This aligns the …
=> [PM 24174]Fix: Add missing loading state to trial initiation create account button

apps/cli/src/tools/send/send.program.ts
https://bitwarden.atlassian.net/browse/PM-24092
`bw send template {object}` was ignoring its object parameter because positional parameters are passed as arguments, not named options. …
=> [PM-24092] fix positional argument processing

apps/browser/src/autofill/background/tabs.background.ts, apps/browser/src/autofill/content/autofill-init.ts, apps/browser/src/autofill/content/autofiller.ts, apps/browser/src/autofill/content/bootstrap-autofill-overlay-menu.ts, apps/browser/src/autofill/content/bootstrap-autofill-overlay-notifications.ts, apps/browser/src/autofill/content/bootstrap-autofill-overlay.ts, apps/browser/src/autofill/content/trigger-autofill-script-injection.ts, apps/browser/src/autofill/services/autofill.service.ts, apps/browser/src/background/idle.background.ts, apps/browser/src/background/runtime.background.ts
[PM-23211](https://bitwarden.atlassian.net/browse/PM-23211)
Misc cleanup that didn't fit in other work …
=> [PM-23211] eslint/ts disable removals

libs/components/src/popover/popover.stories.ts
[CL-821](https://bitwarden.atlassian.net/browse/CL-821)
The popover tests are flaky due to an underlying issue with the positioning. Muting them until we figure it out. …
=> [CL-821] Mute popover story tests until flakiness is fixed

apps/web/src/app/billing/payment/components/add-account-credit-dialog.component.ts
https://bitwarden.atlassian.net/browse/PM-17202
When reworking the account credit component, I accidentally used `=` instead of `:` to set custom fields. This PR resolves that. …
=> [PM-17202] Fix `custom` field in PayPal transaction for account credit

apps/web/src/scss/tailwind.css, apps/web/src/scss/vault-filters.scss
[CL-653](https://bitwarden.atlassian.net/browse/CL-653)
This PR fixes 2 bugs introduced after we removed bootstrap's base styling:
1. Missing background color on provider setup page and possibly elsewhere (reapplying `background-color` and `color` based on [previous themify code](https://github.com/bitwarden/clients/blob/0b057f4c6807fc38653213973a8828ff9307ec1a/apps/web/src/scss/base.scss#L22))
2. Vault filters overflowing their container (reapplying the overflow parts of the `.no-btn` class [extended previously](https://github.com/bitwarden/clients/blob/0b057f4c6807fc38653213973a8828ff9307ec1a/apps/web/src/scss/vault-filters.scss))
| <img width="2310" height="1090" alt="image (11)" src="https://github.com/user-attachments/assets/f82bf501-3d19-4968-87 …
=> [CL-653] Fix provider setup bg and vault filter truncation

.github/workflows/test-browser-interactions.yml
[PM-24785](https://bitwarden.atlassian.net/browse/PM-24785)
Fix for changes made in https://github.com/bitwarden/clients/pull/16034
verified issue; checkout needs to come first >< :
https://github.com/bitwarden/clients/actions/runs/16996553939/job/48188551856?pr=16038
- …
=> [PM-24785] Fix step order

apps/browser/src/autofill/overlay/inline-menu/content/autofill-inline-menu-content.service.spec.ts, apps/browser/src/autofill/overlay/inline-menu/content/autofill-inline-menu-content.service.ts
[PM-24936](https://bitwarden.atlassian.net/browse/PM-24936) …
=> [PM-24936] Prevent inline menu inheritance of potentially dangerous opacity from host body and above

libs/common/src/tools/send/services/send.service.spec.ts, libs/common/src/tools/send/services/send.service.ts
https://bitwarden.atlassian.net/browse/PM-17667
Moves imports to the km exports so we can drop the platform re-exports. …
=> [PM-17667] Move usage of key-generation service for tools to KM

apps/web/src/app/admin-console/organizations/manage/events.component.ts, apps/web/src/app/admin-console/organizations/manage/user-confirm.component.ts, apps/web/src/app/admin-console/organizations/sponsorships/accept-family-sponsorship.component.ts, apps/web/src/app/shared/loose-components.module.ts
https://bitwarden.atlassian.net/browse/PM-24214
Migrate AC owned loose components to standalone. …
=> [PM-24214] Migrate AC owned loose components to standalone

apps/web/src/app/admin-console/organizations/layouts/organization-layout.component.ts
https://bitwarden.atlassian.net/browse/PM-24973
I missed an import for the new `OrganizationWarningsModule` that caused broken pages in the AC Settings section. Adding this import to `OrganizationLayoutComponent` resolves it.
https://github.com/user-attachments/assets/7a43eeb7-5619-4366-bf22-6e6416c96ded
- 📝 …
=> [PM-24973] Add `OrganizationWarningsModule` to `OrganizationLayoutComponent`

libs/common/src/platform/ipc/ipc.service.ts
=> [PM-19174] Add ipc service usage docs

apps/browser/src/popup/app.component.ts
This was throwing an error in `AppComponent.ngOnInit` causing the rest of the method not to run and especially miss all the message listeners. 
Found on a call with @Patrick-Pimentel-Bitwarden and @JaredSnider-Bitwarden.
- ❓ …
=> Fix `AppComponent.ngOnInit` throwing an error

apps/browser/src/autofill/overlay/inline-menu/content/autofill-inline-menu-content.service.spec.ts, apps/browser/src/autofill/overlay/inline-menu/content/autofill-inline-menu-content.service.ts
[PM-25025](https://bitwarden.atlassian.net/browse/PM-25025)
[PM-25025]: https://bitwarden.atlassian.net/browse/PM-25025?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [PM-25025] Additional defense against top-layer content

apps/web/src/app/admin-console/organizations/members/members.component.html
https://bitwarden.atlassian.net/browse/PM-24109
Fixes icon spacing in members compopnent
Before:
After: …
=> [PM-24109] Fix icon spacing

apps/web/src/app/admin-console/organizations/shared/components/access-selector/access-selector.models.ts
https://bitwarden.atlassian.net/browse/PM-23996
Fixes order of permission in the access selector permission list.
New:
Old: …
=> [PM-23996] Fix permission order

apps/browser/src/autofill/overlay/inline-menu/abstractions/autofill-inline-menu-content.service.ts, apps/browser/src/autofill/overlay/inline-menu/content/autofill-inline-menu-content.service.spec.ts, apps/browser/src/autofill/overlay/inline-menu/content/autofill-inline-menu-content.service.ts, apps/browser/src/autofill/services/abstractions/autofill-overlay-content.service.ts, apps/browser/src/autofill/services/autofill-overlay-content.service.ts, apps/browser/src/autofill/services/collect-autofill-content.service.ts
[PM-25122](https://bitwarden.atlassian.net/browse/PM-25122)
Move the inline menu to the top-layer via popover api
[PM-25122]: https://bitwarden.atlassian.net/browse/PM-25122?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA …
=> [PM-25122] Top-layer inline menu population

.github/workflows/lint.yml, apps/desktop/desktop_native/Cargo.toml, apps/desktop/desktop_native/autotype/Cargo.toml, apps/desktop/desktop_native/clippy.toml, apps/desktop/desktop_native/core/Cargo.toml, apps/desktop/desktop_native/core/src/autofill/unix.rs, apps/desktop/desktop_native/core/src/autofill/windows.rs, apps/desktop/desktop_native/core/src/autostart/unimplemented.rs, apps/desktop/desktop_native/core/src/biometric/windows.rs, apps/desktop/desktop_native/core/src/ipc/mod.rs, apps/desktop/desktop_native/core/src/password/macos.rs, apps/desktop/desktop_native/core/src/password/windows.rs, apps/desktop/desktop_native/core/src/powermonitor/linux.rs, apps/desktop/desktop_native/core/src/powermonitor/unimplemented.rs, apps/desktop/desktop_native/core/src/ssh_agent/mod.rs, apps/desktop/desktop_native/core/src/ssh_agent/named_pipe_listener_stream.rs, apps/desktop/desktop_native/core/src/ssh_agent/unix.rs, apps/desktop/desktop_native/core/src/ssh_agent/windows.rs, apps/desktop/desktop_native/macos_provider/Cargo.toml, apps/desktop/desktop_native/macos_provider/src/lib.rs, apps/desktop/desktop_native/napi/Cargo.toml, apps/desktop/desktop_native/napi/src/lib.rs, apps/desktop/desktop_native/objc/Cargo.toml, apps/desktop/desktop_native/proxy/Cargo.toml, apps/desktop/desktop_native/proxy/src/main.rs, apps/desktop/desktop_native/windows_plugin_authenticator/Cargo.toml, apps/desktop/desktop_native/windows_plugin_authenticator/src/lib.rs
Apply the same clippy configuration as we have in sdk-internal. https://github.com/bitwarden/sdk-internal/blob/49f84e6094884af64edd2d7d7399e7400ffed35a/Cargo.toml#L91-L94
Adds FIXME comments to all existing violations. `unwrap` is bad as those will resullt in panics and crash the application. Unused async is ignored in napi since that would require changes to the js side which I don't want to deal with. …
=> Configure clippy

libs/common/src/vault/services/cipher.service.ts
[PM-25317](https://bitwarden.atlassian.net/browse/PM-25317)
Reverts bitwarden/clients#15906 as it introduced a bug where searching is non-functional in the extension. 
Searching is functional:
<video src="https://github.com/user-attachments/assets/e6e4e70d-c8e7-4f4d-9493-e966f9f67d44"/>
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications …
=> [PM-25317] Revert "PM-23386 Display autofill options after sync"

apps/web/src/app/admin-console/organizations/shared/components/collection-dialog/collection-dialog.component.ts
https://bitwarden.atlassian.net/browse/PM-25369
`CollectionAdminView` model instantiation is fixed to clone the current collection into a `CollectionAdminView` that is minimally valid. Then, we set all the data we need on the clone directly rather than in the ctor. …
=> [PM-25369] Fix model creation when editing collections

apps/web/src/app/billing/accounts/trial-initiation/trial-billing-step.component.ts, apps/web/src/app/billing/organizations/payment-method/organization-payment-method.component.html, apps/web/src/app/billing/organizations/payment-method/organization-payment-method.component.ts, apps/web/src/app/billing/shared/adjust-payment-dialog/adjust-payment-dialog.component.ts, apps/web/src/app/billing/shared/payment-method.component.ts, apps/web/src/app/billing/trial-initiation/complete-trial-initiation/complete-trial-initiation.component.html, apps/web/src/app/billing/trial-initiation/complete-trial-initiation/complete-trial-initiation.component.ts
https://bitwarden.atlassian.net/browse/PM-22312
Remove the `ts-strict-ignore` comment and refactor the components to enable Typescript 5.8 updgrade …
=> [PM-22312] Resolve TS 5.8 errors

apps/browser/src/background/main.background.ts
[PM-25440](https://bitwarden.atlassian.net/browse/PM-25440)
Should also fix:
[PM-25438](https://bitwarden.atlassian.net/browse/PM-25438)
[PM-25439](https://bitwarden.atlassian.net/browse/PM-25439)
#15855 Added the `ConfigService` as a dependency of `DefaultSdkService`. However, in `main.background.ts` the `DefaultSdkService` was being constructed before the `ConfigService` so an undefined value was being passed in leading to exceptions when attempting to load the SDK. …
=> [PM-24796] Fix ordering of service construction in main.background.ts

.github/CODEOWNERS
The UIF team will take ownership of the Chromatic Github action …
=> Update CODEOWNERS for Chromatic GitHub action

apps/web/src/app/admin-console/organizations/collections/vault.component.ts
https://bitwarden.atlassian.net/browse/PM-25589
adds missing `?` …
=> [PM-25589] Missing null check

apps/web/src/locales/en/messages.json, bitwarden_license/bit-web/src/app/dirt/access-intelligence/critical-applications.component.html
https://bitwarden.atlassian.net/browse/PM-19992
Update en/messages.json with minor empty state text adjustments.
None …
=> [PM-19992] Update en/messages.json with minor empty state text adjustments

libs/importer/src/components/chrome/import-chrome.component.ts
https://bitwarden.atlassian.net/browse/PM-25579
When selecting one of the new direct browser importers, it attempts to load all the browser profile from the selected browser. This was unfortunately only done during the component init and didn't react to import format changes. Selecting another direct browser importer, should load the profiles from the newly selected browser. 
This PR migrates the `format` input into a Angular Signal and use effect to execute loading the profileList.
Will be 🍒 ⛏️  to `rc` …
=> [PM-25579] Fix browser profiles not loading on import format change

.github/workflows/build-cli.yml, .github/workflows/publish-cli.yml
[bre-1104](https://bitwarden.atlassian.net/browse/bre-1104)
npm supports publishing with OIDC, updating our cli workflow to support that …
=> [bre-1104] update cli npm publish to use oidc

libs/common/src/enums/feature-flag.enum.ts
https://bitwarden.atlassian.net/browse/PM-25870
In this task, we add a feature flag to the application.
At this time, there are no changes on the UI.
None at this time. …
=> [PM-25870] feature flag for Activity tab on Risk Insights

apps/desktop/desktop_native/napi/index.d.ts
~Looks like `index.d.ts` has an update that wasn't committed previously?~
The change was here: https://github.com/bitwarden/clients/pull/16100
~Looks like it was intentional, and the Rust function needs to be made async.~
Looks like we do need this PR based on a conversation with @djsmith85 and @adudek-bw!
- …
=> Add generated update to index.d.ts

libs/components/src/stories/introduction.mdx, libs/components/src/stories/migration.mdx
[CL-864](https://bitwarden.atlassian.net/browse/CL-864)
As I was going through UIF-related Confluence pages, I saw some info duplicated between Confluence and Storybook. I have deprecated the Confluence pages and moved any missing info into Storybook. And also fixed the display of ordered lists on the intro page.
See Storybook intro page and migration page. …
=> [CL-864] Move a couple small docs things to Storybook from Confluence

libs/common/src/platform/services/fido2/fido2-client.service.ts
https://bitwarden.atlassian.net/browse/PM-25591
Removes the google.com workaround when creating passkeys. Google claimed that whatever bug they had in their behaviour when this workaround was introduced should not be present any more and they would expect us to send correct transports.
Original PR where the workaround was introduced: https://github.com/bitwarden/clients/pull/6847
With relevant quote from @trmartin4: 
> ...after discussing with Google, we would like to solve this with a temporary inclusion of the usb transport along with
> internal, preferably when just the google.com relying party is supplied in order to limit the scope of the workaround.
> This will be temporary, as Google has assured us that they are fixing this more permanently on their end. …
=> PM-25591: Remove fido2 google.com workaround

apps/web/src/locales/en/messages.json, bitwarden_license/bit-common/src/dirt/organization-integrations/services/organization-integration-configuration-api.service.spec.ts, bitwarden_license/bit-common/src/dirt/organization-integrations/services/organization-integration-configuration-api.service.ts, bitwarden_license/bit-web/src/app/dirt/organization-integrations/integration-card/integration-card.component.html, bitwarden_license/bit-web/src/app/dirt/organization-integrations/integration-dialog/connect-dialog/connect-dialog-hec.component.html
https://bitwarden.atlassian.net/browse/PM-25931
Fix the issue with saving data into Integrations and Configurations
Helper text implemented: …
=> PM-25931 fixing bugs found by QA

apps/web/src/locales/en/messages.json, libs/pricing/src/components/cart-summary/cart-summary.component.html, libs/pricing/src/components/cart-summary/cart-summary.component.mdx, libs/pricing/src/components/cart-summary/cart-summary.component.stories.ts
https://bitwarden.atlassian.net/browse/PM-26012
This PR:
- Adds test-ids to value divs and the collapse button
- Update localization logic for stories
- Adds localization messages for the component
NOTE: There are no design changes to the component only localization and testing updates …
=> [PM-26012] Add Test-ids to Cart Summary Component

bitwarden_license/bit-web/src/app/dirt/organization-integrations/integration-card/integration-card.component.ts
https://bitwarden.atlassian.net/browse/PM-25983
On successful save/delete - show a toast
Delete Success
On Save Sucess …
=> [PM-25983] Integrations - Toast on successful save/delete

bitwarden_license/bit-web/src/app/auth/sso/sso.component.ts
Reverts bitwarden/clients#16506 (b/c it should be tested on feature branch, not main)
=> Revert "[PM-18470] Pre-populate Key Connector URL"

libs/key-management/project.json
- https://bitwarden.atlassian.net/browse/PM-20254
- https://github.com/bitwarden/clients/pull/16538
- https://github.com/bitwarden/clients/pull/16539
- https://github.com/bitwarden/clients/pull/16540
- https://github.com/bitwarden/clients/pull/16542
- https://github.com/bitwarden/clients/pull/16544
- https://github.com/bitwarden/clients/pull/16545
- https://github.com/bitwarden/clients/pull/16546
- https://github.com/bitwarden/clients/pull/16547
- https://github.com/bitwarden/clients/pull/16548
- https://github.com/bitwarden/clients/pull/16549
- https://github.com/bitwarden/clients/pull/16550
- https://github.com/bitwarden/clients/pull/16551
- https://github.com/bitwarden/clients/pull/16562
- https://github.com/bitwarden/clients/pull/16563
- https://github.com/bitwarden/clients/pull/16564 …
=> build: add nx configuration in libs/key-management

apps/cli/src/vault/create.command.ts
https://bitwarden.atlassian.net/browse/PM-7979
https://github.com/user-attachments/assets/1c2f12da-444e-412a-88b3-47a85318d7fd …
=> [PM-7979] Fix folder creation race condition in CLI

apps/web/src/locales/en/messages.json, bitwarden_license/bit-web/src/app/dirt/access-intelligence/all-activity.component.html
https://bitwarden.atlassian.net/browse/PM-26416
updated the copy on the at-risk members card …
=> [PM-26416] Updated text of At-Risk members card

libs/importer/src/components/chrome/import-chrome.component.ts
https://bitwarden.atlassian.net/browse/PM-26030
When importing using the new chromium importer and the target browser does not have any logins to import, it would just show a generic error. This refines it to re-use the message we show on other importers …
=> [PM-26030] [Chromium importer] Add specific error when no logins were found

.github/workflows/review-code.yml
https://bitwarden.atlassian.net/browse/PM-26339
Create a GH action to execute a Claude Code Review. 
Currently filtering by code owned by the vault team only.  …
=> Create Claude code review action

apps/web/src/app/admin-console/organizations/policies/base-policy-edit.component.ts, apps/web/src/app/admin-console/organizations/policies/policies.component.ts
https://bitwarden.atlassian.net/browse/PM-26366
adds support for dynamic policy edit dialogs for each policy edit definition. …
=> [PM-26366] Refactor BasePolicyEditDefinition
